{
  "hash": "31ef5698421489500a3507762ebdabdc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lineare Algebra für die Hauptkomponentenanalyse\"\ndescription: \"Matrizen als Abbildungen, Eigenwerte und Eigenvektoren — und was die PCA daraus macht.\"\ncategories: [\"Multivariate Verfahren\", \"R\", \"Python\"]\nquelle: [\"StatDa\"]\nseitentyp: konzept\nstand: fertig\norder: 15\n---\n\n\n\n\n\n## Kernideen\n\n- Eine Matrix ist eine **Abbildung**: Sie nimmt einen Punkt und verschiebt ihn.\n- **Eigenvektoren** sind die Richtungen, die diese Abbildung **nicht dreht** —\n  sie werden nur gestreckt, und der Streckfaktor ist der **Eigenwert**.\n- Die **Kovarianzmatrix** ist die Abbildung, um die es in der PCA geht. Ihre\n  Eigenvektoren sind die Hauptkomponenten, ihre Eigenwerte die Varianzen\n  entlang dieser Richtungen.\n- Die **Summe der Eigenwerte** ist die Spur der Matrix und damit die\n  Gesamtvarianz. Deshalb lässt sich \"Anteil erklärter Varianz\" überhaupt\n  ausrechnen.\n- Eigenvektoren symmetrischer Matrizen stehen **senkrecht** aufeinander —\n  deshalb sind Hauptkomponenten unkorreliert.\n- Ein **Eigenwert von null** bedeutet, dass eine Variable eine exakte\n  Linearkombination der anderen ist.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Korrelation](../grundlagen/korrelation.qmd) und\n[Distanzmasse](distanzmasse.qmd). Diese Seite liefert den Unterbau für die\n[Hauptkomponentenanalyse](hauptkomponentenanalyse.qmd) und die\n[Faktorenanalyse](faktorenanalyse.qmd).\n:::\n\n### Eine Matrix ist eine Abbildung\n\nEin Vektor ist ein Punkt, eine Matrix macht daraus einen anderen Punkt. Die\nMultiplikation $A\\mathbf{v}$ ist keine Zahlenschieberei, sondern eine\ngeometrische Operation: Streckung, Drehung, Scherung oder eine Mischung davon.\n\nZwei Kennzahlen fassen eine solche Abbildung zusammen:\n\n- Die **Determinante** sagt, wie sich die **Fläche** (im Raum: das Volumen)\n  ändert. Determinante 1 heisst flächentreu, Determinante 0 heisst, dass alles\n  auf eine Linie zusammenfällt.\n- Die **Spur** ist die Summe der Diagonalelemente. Bei einer Kovarianzmatrix\n  ist das die Summe der Varianzen, also die Gesamtvarianz.\n\n### Eigenvektoren und Eigenwerte\n\nDie meisten Richtungen werden von einer Abbildung gedreht. Einige nicht —\ndiese heissen **Eigenvektoren**:\n\n$$A\\mathbf{v} = \\lambda \\mathbf{v}$$\n\nDer Vektor $\\mathbf{v}$ zeigt nach der Abbildung noch in dieselbe Richtung, nur\num den Faktor $\\lambda$ gestreckt. Gefunden werden die Eigenwerte über\n\n$$\\det(A - \\lambda I) = 0,$$\n\nbei einer $2\\times 2$-Matrix also über eine quadratische Gleichung, deren\nKoeffizienten Spur und Determinante sind:\n\n$$\\lambda^2 - \\operatorname{spur}(A)\\,\\lambda + \\det(A) = 0$$\n\nDaraus folgen zwei Merksätze, die auf jeder Grösse gelten:\n\n$$\\sum_i \\lambda_i = \\operatorname{spur}(A) \\qquad \\prod_i \\lambda_i = \\det(A)$$\n\n### Was das mit der PCA zu tun hat\n\nDie Kovarianzmatrix $S$ ist **symmetrisch** und **positiv semidefinit**. Daraus\nfolgt alles, was die PCA braucht:\n\n| Eigenschaft der Matrix | Folge für die PCA |\n|---|---|\n| symmetrisch | alle Eigenwerte sind reell |\n| symmetrisch | Eigenvektoren stehen **senkrecht** aufeinander → Hauptkomponenten sind unkorreliert |\n| positiv semidefinit | alle Eigenwerte sind $\\ge 0$ → es gibt keine negative Varianz |\n| Spur = Gesamtvarianz | $\\lambda_i / \\sum \\lambda_j$ ist der **Anteil erklärter Varianz** |\n| Eigenwert $= 0$ | eine Variable ist eine exakte Linearkombination der anderen |\n\nDie PCA ist damit kein neues Verfahren, sondern die **Eigenzerlegung der\nKovarianz- oder Korrelationsmatrix**, in Statistiksprache übersetzt.\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Was eine Matrix mit Punkten macht\n\n#### Frage und Datenlage\n\nVier einfache $2\\times 2$-Matrizen und derselbe Punkt $(1, 1)$. Was passiert?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nA <- matrix(c(2, 1, 1, 3), nrow = 2)          # symmetrisch\nstreckung <- matrix(c(3, 0, 0, 0.5), nrow = 2)\ndrehung <- matrix(c(0, 1, -1, 0), nrow = 2)   # 90 Grad\nscherung <- matrix(c(1, 0, 1.5, 1), nrow = 2)\n\npunkte <- rbind(c(1, 0), c(0, 1), c(1, 1), c(1, -1), c(2, 1))\ncbind(punkte, abgebildet = punkte %*% t(A))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     [,1] [,2] [,3] [,4]\n[1,]    1    0    2    1\n[2,]    0    1    1    3\n[3,]    1    1    3    4\n[4,]    1   -1    1   -2\n[5,]    2    1    5    5\n```\n\n\n:::\n\n```{.r .cell-code}\nfor (nm in c(\"A\", \"streckung\", \"drehung\", \"scherung\")) {\n  M <- get(nm)\n  cat(sprintf(\"%-10s det = %5.2f  spur = %5.2f  (1,1) -> (%.2f, %.2f)\\n\",\n              nm, det(M), sum(diag(M)),\n              (M %*% c(1, 1))[1], (M %*% c(1, 1))[2]))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nA          det =  5.00  spur =  5.00  (1,1) -> (3.00, 4.00)\nstreckung  det =  1.50  spur =  3.50  (1,1) -> (3.00, 0.50)\ndrehung    det =  1.00  spur =  0.00  (1,1) -> (-1.00, 1.00)\nscherung   det =  1.00  spur =  2.00  (1,1) -> (2.50, 1.00)\n```\n\n\n:::\n\n```{.r .cell-code}\nquadrat <- rbind(c(0, 0), c(1, 0), c(1, 1), c(0, 1), c(0, 0))\nbild <- quadrat %*% t(A)\nggplot() +\n  geom_path(data = data.frame(quadrat), aes(X1, X2), linetype = \"dashed\") +\n  geom_path(data = data.frame(bild), aes(X1, X2), linewidth = 0.9) +\n  coord_equal() +\n  labs(x = \"\", y = \"\", subtitle = \"gestrichelt: Einheitsquadrat, durchgezogen: Bild unter A\")\n```\n\n::: {.cell-output-display}\n![Beispiel 1: das Einheitsquadrat vor und nach der Abbildung.](lineare-algebra-pca_files/figure-html/fig-b1-la-r-1.png){#fig-b1-la-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nA = np.array([[2., 1.], [1., 3.]])\nstreckung = np.array([[3., 0.], [0., 0.5]])\ndrehung = np.array([[0., -1.], [1., 0.]])\nscherung = np.array([[1., 1.5], [0., 1.]])\n\npunkte = np.array([[1., 0.], [0., 1.], [1., 1.], [1., -1.], [2., 1.]])\nprint(np.column_stack([punkte, punkte @ A.T]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[ 1.  0.  2.  1.]\n [ 0.  1.  1.  3.]\n [ 1.  1.  3.  4.]\n [ 1. -1.  1. -2.]\n [ 2.  1.  5.  5.]]\n```\n\n\n:::\n\n```{.python .cell-code}\nfor nm, M in [(\"A\", A), (\"streckung\", streckung),\n              (\"drehung\", drehung), (\"scherung\", scherung)]:\n    bild = M @ np.array([1., 1.])\n    print(f\"{nm:<10} det = {np.linalg.det(M):5.2f}  spur = {np.trace(M):5.2f}\"\n          f\"  (1,1) -> ({bild[0]:.2f}, {bild[1]:.2f})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nA          det =  5.00  spur =  5.00  (1,1) -> (3.00, 4.00)\nstreckung  det =  1.50  spur =  3.50  (1,1) -> (3.00, 0.50)\ndrehung    det =  1.00  spur =  0.00  (1,1) -> (-1.00, 1.00)\nscherung   det =  1.00  spur =  2.00  (1,1) -> (2.50, 1.00)\n```\n\n\n:::\n\n```{.python .cell-code}\nquadrat = np.array([[0., 0.], [1., 0.], [1., 1.], [0., 1.], [0., 0.]])\nbild = quadrat @ A.T\nfig, achse = plt.subplots(figsize=(7, 3.6))\nachse.plot(quadrat[:, 0], quadrat[:, 1], \"--\", color=\"black\")\nachse.plot(bild[:, 0], bild[:, 1], lw=1.6, color=\"black\")\nachse.set_aspect(\"equal\")\nachse.set_title(\"gestrichelt: Einheitsquadrat, durchgezogen: Bild unter A\",\n                fontsize=10)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Abbildung in Python.](lineare-algebra-pca_files/figure-html/fig-b1-la-py-1.png){#fig-b1-la-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Punkt | Bild unter $A$ |\n|---|---|\n| (1, 0) | (2, 1) |\n| (0, 1) | (1, 3) |\n| (1, 1) | (3, 4) |\n| (1, −1) | (1, −2) |\n| (2, 1) | (5, 5) |\n\n| Matrix | Determinante | Spur | (1,1) wird zu |\n|---|---|---|---|\n| $A$ | **5.00** | 5.00 | (3.00, 4.00) |\n| Streckung | 1.50 | 3.50 | (3.00, 0.50) |\n| Drehung 90° | 1.00 | 0.00 | (−1.00, 1.00) |\n| Scherung | 1.00 | 2.00 | (2.50, 1.00) |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die **Spalten** von $A$ sind die Bilder der Einheitsvektoren | $(1,0) \\to (2,1)$ und $(0,1) \\to (1,3)$ — genau die Spalten. **So liest man eine Matrix: Jede Spalte sagt, wohin eine Achse wandert.** |\n| $(2,1) \\to (5,5)$ und $(1,1) \\to (3,4)$ | Die Abbildung ist linear: doppelter Punkt, doppeltes Bild, und Summen bleiben Summen. |\n| Determinante 5 heisst **fünffache Fläche** | Das Einheitsquadrat wird zu einem Parallelogramm der Fläche 5, gut in der Grafik zu sehen. |\n| Drehung und Scherung haben Determinante **1** | Beide sind flächentreu. Die Drehung hat Spur 0, weil sie **keine** Richtung unverändert lässt — sie hat in der reellen Ebene gar keine Eigenvektoren. |\n| Die Streckung ist die **einfachste** Abbildung | Eine Diagonalmatrix streckt jede Achse für sich, ohne zu drehen. Die Achsen selbst sind hier die Eigenvektoren. |\n\n::: {.note-box}\n**Und genau darauf läuft die Eigenzerlegung hinaus:** Sie sucht das\nKoordinatensystem, in dem die Abbildung wie eine Diagonalmatrix aussieht — also\nein reines Strecken ohne Drehung.\n\n$$A = V \\Lambda V^{\\top}$$\n\n$V$ enthält die Eigenvektoren als Spalten (das neue Koordinatensystem),\n$\\Lambda$ die Eigenwerte auf der Diagonalen (die Streckfaktoren). Für eine\nKovarianzmatrix heisst das: **Dreh das Koordinatensystem so, dass die Variablen\nunkorreliert sind.** Das ist die PCA.\n:::\n\n#### Interpretation\n\nEine Matrix beschreibt, wohin Punkte wandern. Determinante und Spur fassen das\nzusammen, die Eigenzerlegung nimmt es auseinander.\n\n### Beispiel 2: Eigenwerte von Hand\n\n#### Frage und Datenlage\n\nDieselbe Matrix $A = \\begin{pmatrix} 2 & 1 \\\\ 1 & 3\\end{pmatrix}$. Die\nEigenwerte über die quadratische Gleichung, die Eigenvektoren über Einsetzen\nund Nachrechnen — und zum Schluss der Vergleich mit der eingebauten Funktion.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nA <- matrix(c(2, 1, 1, 3), nrow = 2)\n\nspur <- sum(diag(A)); determinante <- det(A)\ndiskriminante <- spur^2 - 4 * determinante\nlambda1 <- (spur + sqrt(diskriminante)) / 2\nlambda2 <- (spur - sqrt(diskriminante)) / 2\nround(c(spur = spur, determinante = determinante,\n        diskriminante = diskriminante,\n        lambda1 = lambda1, lambda2 = lambda2), 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         spur  determinante diskriminante       lambda1       lambda2 \n     5.000000      5.000000      5.000000      3.618034      1.381966 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Zu jedem Eigenwert der Eigenvektor: (A - lambda I) v = 0 hat fuer eine\n# 2x2-Matrix die Loesung v = (A12, lambda - A11), danach normiert.\nfor (lam in c(lambda1, lambda2)) {\n  v <- c(A[1, 2], lam - A[1, 1]); v <- v / sqrt(sum(v^2))\n  cat(sprintf(\"lambda = %.4f  v = (%.4f, %.4f)  A v = (%.4f, %.4f)  lambda v = (%.4f, %.4f)\\n\",\n              lam, v[1], v[2], (A %*% v)[1], (A %*% v)[2], lam * v[1], lam * v[2]))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlambda = 3.6180  v = (0.5257, 0.8507)  A v = (1.9021, 3.0777)  lambda v = (1.9021, 3.0777)\nlambda = 1.3820  v = (0.8507, -0.5257)  A v = (1.1756, -0.7265)  lambda v = (1.1756, -0.7265)\n```\n\n\n:::\n\n```{.r .cell-code}\n# Die beiden Merksaetze\nround(c(summe_eigenwerte = lambda1 + lambda2, spur = spur,\n        produkt_eigenwerte = lambda1 * lambda2, determinante = determinante), 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  summe_eigenwerte               spur produkt_eigenwerte       determinante \n                 5                  5                  5                  5 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Und die eingebaute Funktion\nzerlegung <- eigen(A)\nround(zerlegung$values, 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.618034 1.381966\n```\n\n\n:::\n\n```{.r .cell-code}\nround(vorzeichen_fest(zerlegung$vectors), 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]      [,2]\n[1,] 0.525731  0.850651\n[2,] 0.850651 -0.525731\n```\n\n\n:::\n\n```{.r .cell-code}\n# Senkrecht? Skalarprodukt der beiden Eigenvektoren\nV <- vorzeichen_fest(zerlegung$vectors)\nround(c(skalarprodukt = sum(V[, 1] * V[, 2])), 12)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nskalarprodukt \n            0 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Und die Rekonstruktion A = V Lambda V'\nround(V %*% diag(zerlegung$values) %*% t(V), 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     [,1] [,2]\n[1,]    2    1\n[2,]    1    3\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nA = np.array([[2., 1.], [1., 3.]])\n\nspur = np.trace(A)\ndeterminante = np.linalg.det(A)\ndiskriminante = spur ** 2 - 4 * determinante\nlambda1 = (spur + np.sqrt(diskriminante)) / 2\nlambda2 = (spur - np.sqrt(diskriminante)) / 2\nprint({\"spur\": round(float(spur), 6), \"determinante\": round(float(determinante), 6),\n       \"diskriminante\": round(float(diskriminante), 6),\n       \"lambda1\": round(float(lambda1), 6), \"lambda2\": round(float(lambda2), 6)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'spur': 5.0, 'determinante': 5.0, 'diskriminante': 5.0, 'lambda1': 3.618034, 'lambda2': 1.381966}\n```\n\n\n:::\n\n```{.python .cell-code}\nfor lam in [lambda1, lambda2]:\n    v = np.array([A[0, 1], lam - A[0, 0]])\n    v = v / np.sqrt((v ** 2).sum())\n    print(f\"lambda = {lam:.4f}  v = ({v[0]:.4f}, {v[1]:.4f})\"\n          f\"  A v = ({(A @ v)[0]:.4f}, {(A @ v)[1]:.4f})\"\n          f\"  lambda v = ({lam * v[0]:.4f}, {lam * v[1]:.4f})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlambda = 3.6180  v = (0.5257, 0.8507)  A v = (1.9021, 3.0777)  lambda v = (1.9021, 3.0777)\nlambda = 1.3820  v = (0.8507, -0.5257)  A v = (1.1756, -0.7265)  lambda v = (1.1756, -0.7265)\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"summe_eigenwerte\": round(float(lambda1 + lambda2), 6),\n       \"spur\": round(float(spur), 6),\n       \"produkt_eigenwerte\": round(float(lambda1 * lambda2), 6),\n       \"determinante\": round(float(determinante), 6)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'summe_eigenwerte': 5.0, 'spur': 5.0, 'produkt_eigenwerte': 5.0, 'determinante': 5.0}\n```\n\n\n:::\n\n```{.python .cell-code}\nwerte, V = eigen_absteigend(A)\nprint(np.round(werte, 6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[3.618034 1.381966]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(np.round(V, 6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[ 0.525731  0.850651]\n [ 0.850651 -0.525731]]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"skalarprodukt\": round(float(V[:, 0] @ V[:, 1]), 12)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'skalarprodukt': 0.0}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(np.round(V @ np.diag(werte) @ V.T, 6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[2. 1.]\n [1. 3.]]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Schritt | Wert |\n|---|---|\n| Spur | 5 |\n| Determinante | 5 |\n| Diskriminante $5^2 - 4\\cdot 5$ | 5 |\n| $\\lambda_1 = (5 + \\sqrt{5})/2$ | **3.618034** |\n| $\\lambda_2 = (5 - \\sqrt{5})/2$ | **1.381966** |\n\n| $\\lambda$ | Eigenvektor $v$ | $Av$ | $\\lambda v$ |\n|---|---|---|---|\n| 3.6180 | (0.5257, 0.8507) | (1.9021, 3.0777) | (1.9021, 3.0777) |\n| 1.3820 | (0.8507, −0.5257) | (1.1756, −0.7265) | (1.1756, −0.7265) |\n\n| Beobachtung | Erklärung |\n|---|---|\n| $Av$ und $\\lambda v$ stimmen **Stelle für Stelle** überein | Das ist die Definition, hier als Probe. Die Abbildung dreht diese beiden Richtungen nicht, sie streckt sie nur. |\n| Summe der Eigenwerte = **5** = Spur | Und das Produkt $3.618 \\cdot 1.382 = 5$ = Determinante. **Zwei Kontrollen, die bei jeder Matrix funktionieren** — nützlich, um ein Ergebnis zu prüfen, ohne es nachzurechnen. |\n| Das Skalarprodukt der Eigenvektoren ist **0** | Die beiden stehen senkrecht aufeinander. Das gilt für jede symmetrische Matrix und ist der Grund, weshalb Hauptkomponenten unkorreliert sind. |\n| $V \\Lambda V^{\\top}$ ergibt wieder $A$ | Die Zerlegung verliert nichts. Behält man nur die grössten Eigenwerte, wird daraus eine **Näherung** — genau das tut die PCA beim Weglassen von Komponenten. |\n| $\\lambda_1 > \\lambda_2$, aber beide positiv | $A$ ist positiv definit. Wäre ein Eigenwert negativ, könnte $A$ keine Kovarianzmatrix sein. |\n\n::: {.warning-box}\n**Eigenvektoren sind nur bis aufs Vorzeichen bestimmt.** Ist $v$ ein\nEigenvektor, so ist $-v$ einer mit demselben Eigenwert. R und Python wählen\nnicht dieselbe Konvention, und auch dieselbe Software kann bei kleinsten\nDatenänderungen umspringen.\n\n| | R `eigen()` | Python `np.linalg.eigh()` |\n|---|---|---|\n| Reihenfolge | **absteigend** | **aufsteigend** |\n| Vorzeichen | LAPACK-abhängig | LAPACK-abhängig |\n\nAuf dieser Seite legt deshalb die Hilfsfunktion `vorzeichen_fest` bzw.\n`eigen_absteigend` beides fest: absteigend sortiert, und die betragsmässig\ngrösste Komponente jedes Vektors positiv.\n\n**Für die Auswertung heisst das:** Ein Vorzeichenwechsel in einer\nKomponentenladung ist **keine inhaltliche Aussage**. Nur die relativen\nVorzeichen **innerhalb** eines Eigenvektors sind interpretierbar.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Matrix hat die Eigenwerte 3.618 und 1.382 mit den zugehörigen\n> Eigenvektoren (0.526, 0.851) und (0.851, −0.526). Summe und Produkt der\n> Eigenwerte reproduzieren Spur und Determinante, und die beiden Eigenvektoren\n> stehen senkrecht aufeinander.\n\n### Beispiel 3: Die PCA ist die Eigenzerlegung der Kovarianzmatrix\n\n#### Frage und Datenlage\n\n200 Personen mit Körpergrösse in Zentimetern und Gewicht in Kilogramm. Die PCA\nwird einmal von Hand aus der Kovarianzmatrix gerechnet und einmal mit der\neingebauten Funktion.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 200\nZ <- normalmatrix(5150, n, 2)\ngroesse <- 172 + 9 * Z[, 1]\ngewicht <- 70 + 0.55 * (groesse - 172) + 7 * Z[, 2]\nD <- cbind(groesse = groesse, gewicht = gewicht)\n\nround(rbind(mittel = colMeans(D), sd = apply(D, 2, sd)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        groesse gewicht\nmittel 170.9779 69.8522\nsd       9.7200  8.0371\n```\n\n\n:::\n\n```{.r .cell-code}\nS <- cov(D)\nround(S, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        groesse gewicht\ngroesse 94.4777 45.6142\ngewicht 45.6142 64.5957\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(korrelation = cor(D)[1, 2]), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nkorrelation \n     0.5839 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Von Hand: quadratische Gleichung aus Spur und Determinante\nspur <- sum(diag(S)); dt <- det(S)\nl1 <- (spur + sqrt(spur^2 - 4 * dt)) / 2\nl2 <- (spur - sqrt(spur^2 - 4 * dt)) / 2\nround(c(spur = spur, determinante = dt, lambda1 = l1, lambda2 = l2,\n        anteil1 = l1 / spur, anteil2 = l2 / spur), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        spur determinante      lambda1      lambda2      anteil1      anteil2 \n    159.0735    4022.2035     127.5356      31.5379       0.8017       0.1983 \n```\n\n\n:::\n\n```{.r .cell-code}\nv1 <- c(S[1, 2], l1 - S[1, 1]); v1 <- v1 / sqrt(sum(v1^2))\nv2 <- c(S[1, 2], l2 - S[1, 1]); v2 <- v2 / sqrt(sum(v2^2))\nround(rbind(v1 = v1, v2 = v2), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     [,1]    [,2]\nv1 0.8097  0.5868\nv2 0.5868 -0.8097\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(winkel_grad = atan2(v1[2], v1[1]) * 180 / pi), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwinkel_grad \n     35.932 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Die Scores: Daten zentriert und auf die Eigenvektoren projiziert\nscores <- scale(D, center = TRUE, scale = FALSE) %*% cbind(v1, v2)\nround(c(varianz_score1 = var(scores[, 1]), varianz_score2 = var(scores[, 2]),\n        kovarianz = cov(scores)[1, 2]), 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nvarianz_score1 varianz_score2      kovarianz \n      127.5356        31.5379         0.0000 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(summe_varianzen_roh = sum(apply(D, 2, var)), spur = spur), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsumme_varianzen_roh                spur \n           159.0735            159.0735 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Und die eingebaute Funktion\npk <- prcomp(D)\nround(pk$sdev^2, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 127.5356  31.5379\n```\n\n\n:::\n\n```{.r .cell-code}\nround(vorzeichen_fest(pk$rotation), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           PC1     PC2\ngroesse 0.8097 -0.5868\ngewicht 0.5868  0.8097\n```\n\n\n:::\n\n```{.r .cell-code}\nmitte <- colMeans(D)\nggplot(data.frame(D), aes(groesse, gewicht)) +\n  geom_point(alpha = 0.45, size = 1.4) +\n  annotate(\"segment\", x = mitte[1], y = mitte[2],\n           xend = mitte[1] + sqrt(l1) * v1[1], yend = mitte[2] + sqrt(l1) * v1[2],\n           linewidth = 1, arrow = arrow(length = unit(0.18, \"cm\"))) +\n  annotate(\"segment\", x = mitte[1], y = mitte[2],\n           xend = mitte[1] + sqrt(l2) * v2[1], yend = mitte[2] + sqrt(l2) * v2[2],\n           linewidth = 1, arrow = arrow(length = unit(0.18, \"cm\"))) +\n  coord_equal() +\n  labs(x = \"Körpergrösse (cm)\", y = \"Gewicht (kg)\")\n```\n\n::: {.cell-output-display}\n![Beispiel 3: Streudiagramm mit den beiden Eigenvektoren, skaliert auf die Wurzel ihres Eigenwerts.](lineare-algebra-pca_files/figure-html/fig-b3-la-r-1.png){#fig-b3-la-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nn = 200\nZ = normalmatrix(5150, n, 2)\ngroesse = 172 + 9 * Z[:, 0]\ngewicht = 70 + 0.55 * (groesse - 172) + 7 * Z[:, 1]\nD = np.column_stack([groesse, gewicht])\n\nprint({\"mittel\": np.round(D.mean(axis=0), 4).tolist(),\n       \"sd\": np.round(D.std(axis=0, ddof=1), 4).tolist()})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'mittel': [170.9779, 69.8522], 'sd': [9.72, 8.0371]}\n```\n\n\n:::\n\n```{.python .cell-code}\nS = np.cov(D, rowvar=False)\nprint(np.round(S, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[94.4777 45.6142]\n [45.6142 64.5957]]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"korrelation\": round(float(np.corrcoef(D, rowvar=False)[0, 1]), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'korrelation': 0.5839}\n```\n\n\n:::\n\n```{.python .cell-code}\nspur = np.trace(S)\ndt = np.linalg.det(S)\nl1 = (spur + np.sqrt(spur ** 2 - 4 * dt)) / 2\nl2 = (spur - np.sqrt(spur ** 2 - 4 * dt)) / 2\nprint({\"spur\": round(float(spur), 4), \"determinante\": round(float(dt), 4),\n       \"lambda1\": round(float(l1), 4), \"lambda2\": round(float(l2), 4),\n       \"anteil1\": round(float(l1 / spur), 4), \"anteil2\": round(float(l2 / spur), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'spur': 159.0735, 'determinante': 4022.2035, 'lambda1': 127.5356, 'lambda2': 31.5379, 'anteil1': 0.8017, 'anteil2': 0.1983}\n```\n\n\n:::\n\n```{.python .cell-code}\nv1 = np.array([S[0, 1], l1 - S[0, 0]]); v1 /= np.sqrt((v1 ** 2).sum())\nv2 = np.array([S[0, 1], l2 - S[0, 0]]); v2 /= np.sqrt((v2 ** 2).sum())\nprint(np.round(np.vstack([v1, v2]), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[ 0.8097  0.5868]\n [ 0.5868 -0.8097]]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"winkel_grad\": round(float(np.degrees(np.arctan2(v1[1], v1[0]))), 3)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'winkel_grad': 35.932}\n```\n\n\n:::\n\n```{.python .cell-code}\nscores = (D - D.mean(axis=0)) @ np.column_stack([v1, v2])\nprint({\"varianz_score1\": round(float(scores[:, 0].var(ddof=1)), 6),\n       \"varianz_score2\": round(float(scores[:, 1].var(ddof=1)), 6),\n       \"kovarianz\": round(float(np.cov(scores, rowvar=False)[0, 1]), 6)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'varianz_score1': 127.535558, 'varianz_score2': 31.537898, 'kovarianz': 0.0}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"summe_varianzen_roh\": round(float(D.var(axis=0, ddof=1).sum()), 4),\n       \"spur\": round(float(spur), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'summe_varianzen_roh': 159.0735, 'spur': 159.0735}\n```\n\n\n:::\n\n```{.python .cell-code}\nwerte, V = eigen_absteigend(S)\nprint(np.round(werte, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[127.5356  31.5379]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(np.round(V, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[ 0.8097 -0.5868]\n [ 0.5868  0.8097]]\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achse = plt.subplots(figsize=(7, 4))\nachse.scatter(groesse, gewicht, s=12, alpha=0.45, color=\"black\")\nm = D.mean(axis=0)\nfor lam, v in [(l1, v1), (l2, v2)]:\n    achse.annotate(\"\", xy=(m[0] + np.sqrt(lam) * v[0], m[1] + np.sqrt(lam) * v[1]),\n                   xytext=(m[0], m[1]),\n                   arrowprops=dict(arrowstyle=\"->\", lw=1.4, color=\"black\"))\nachse.set_aspect(\"equal\")\nachse.set_xlabel(\"Körpergrösse (cm)\")\nachse.set_ylabel(\"Gewicht (kg)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselbe Zerlegung in Python.](lineare-algebra-pca_files/figure-html/fig-b3-la-py-1.png){#fig-b3-la-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| | Körpergrösse | Gewicht |\n|---|---|---|\n| Mittelwert | 170.978 | 69.852 |\n| Standardabweichung | 9.720 | 8.037 |\n\nKovarianzmatrix:\n\n| | Grösse | Gewicht |\n|---|---|---|\n| **Grösse** | 94.478 | 45.614 |\n| **Gewicht** | 45.614 | 64.596 |\n\nKorrelation **0.584**.\n\n| Grösse | Wert |\n|---|---|\n| Spur (= Gesamtvarianz) | **159.074** |\n| Determinante | 4022.20 |\n| $\\lambda_1$ | **127.536** — Anteil **80.2 %** |\n| $\\lambda_2$ | **31.538** — Anteil **19.8 %** |\n| erster Eigenvektor | (0.8097, 0.5868), Winkel **35.9°** |\n| zweiter Eigenvektor | (0.5868, −0.8097) |\n| Varianz der Scores | **127.536** und **31.538** |\n| Kovarianz der Scores | **0.000000** |\n| Summe der rohen Varianzen | 159.074 = Spur |\n| `prcomp()$sdev^2` | **127.536** und **31.538** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die Eigenwerte **sind** die Varianzen der Scores | 127.536 und 31.538, in beiden Rechnungen identisch. Das ist die gesamte Aussage der PCA: Der Eigenwert misst, wie stark die Daten in dieser Richtung streuen. |\n| Die Kovarianz der Scores ist **exakt null** | Weil die Eigenvektoren senkrecht aufeinander stehen. **Die PCA erzeugt unkorrelierte Variablen aus korrelierten.** |\n| 94.478 + 64.596 = 127.536 + 31.538 | Die Gesamtvarianz wird nur **umverteilt**, nicht verändert. Deshalb ist \"Anteil erklärter Varianz\" eine sinnvolle Grösse. |\n| Die erste Komponente zeigt in **35.9 Grad** | Nicht in 45 Grad, obwohl beide Ladungen positiv sind. Die Richtung wird von der grösseren Varianz der Körpergrösse (94.5 gegen 64.6) zur Grössenachse hin gezogen. |\n| Die Handrechnung und `prcomp()` stimmen überein | Bis auf die Vorzeichenkonvention. **`prcomp()` ist keine Blackbox, sondern `eigen(cov(D))`** — mit dem Unterschied, dass intern eine Singulärwertzerlegung verwendet wird, die numerisch stabiler ist. |\n\n::: {.note-box}\n**Woran man die beiden Komponenten inhaltlich erkennt:**\n\n| Komponente | Ladungen | Bedeutung |\n|---|---|---|\n| erste | 0.810 und 0.587, **beide positiv** | \"allgemeine Körpergrösse\" — wer gross ist, ist eher schwer |\n| zweite | 0.587 und **−0.810** | \"schwer **für** seine Grösse\" — der Gegensatz zwischen den beiden |\n\nDie erste Komponente ist fast immer ein Grösseneffekt, wenn alle Variablen\npositiv korreliert sind. Die interessanten Aussagen stecken meist in der\nzweiten.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Eigenzerlegung der Kovarianzmatrix liefert die Eigenwerte 127.54 und\n> 31.54, also 80.2 und 19.8 Prozent der Gesamtvarianz von 159.07. Die Scores auf\n> den beiden Eigenvektoren haben genau diese Varianzen und sind unkorreliert;\n> `prcomp()` reproduziert dasselbe Ergebnis.\n\n### Beispiel 4: Warum die Einheit alles verändert\n\n#### Frage und Datenlage\n\nDieselben Daten, nur die Körpergrösse in **Millimetern** statt Zentimetern.\nDanach dieselben Daten standardisiert. Drei Rechnungen, drei Antworten.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# (1) Zentimeter -- wie in Beispiel 3\nS_cm <- cov(D)\ne_cm <- eigen(S_cm)\nround(rbind(eigenwert = e_cm$values,\n            anteil = e_cm$values / sum(e_cm$values)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              [,1]    [,2]\neigenwert 127.5356 31.5379\nanteil      0.8017  0.1983\n```\n\n\n:::\n\n```{.r .cell-code}\n# (2) Millimeter: dieselbe Information, andere Zahl\nD_mm <- cbind(groesse = D[, 1] * 10, gewicht = D[, 2])\nS_mm <- cov(D_mm)\nround(S_mm, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        groesse gewicht\ngroesse 9447.77  456.14\ngewicht  456.14   64.60\n```\n\n\n:::\n\n```{.r .cell-code}\ne_mm <- eigen(S_mm)\nround(rbind(eigenwert = e_mm$values,\n            anteil = e_mm$values / sum(e_mm$values)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               [,1]    [,2]\neigenwert 9469.8938 42.4736\nanteil       0.9955  0.0045\n```\n\n\n:::\n\n```{.r .cell-code}\n# (3) Standardisiert, also die Korrelationsmatrix\nR <- cor(D)\nround(R, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        groesse gewicht\ngroesse  1.0000  0.5839\ngewicht  0.5839  1.0000\n```\n\n\n:::\n\n```{.r .cell-code}\ne_r <- eigen(R)\nround(rbind(eigenwert = e_r$values,\n            anteil = e_r$values / sum(e_r$values)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            [,1]   [,2]\neigenwert 1.5839 0.4161\nanteil    0.7919 0.2081\n```\n\n\n:::\n\n```{.r .cell-code}\nround(vorzeichen_fest(e_r$vectors), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       [,1]    [,2]\n[1,] 0.7071  0.7071\n[2,] 0.7071 -0.7071\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(summe_eigenwerte = sum(e_r$values), anzahl_variablen = ncol(D)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsumme_eigenwerte anzahl_variablen \n               2                2 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Die ersten Eigenvektoren im Vergleich\nround(rbind(cm = vorzeichen_fest(e_cm$vectors)[, 1],\n            mm = vorzeichen_fest(e_mm$vectors)[, 1],\n            standardisiert = vorzeichen_fest(e_r$vectors)[, 1]), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 [,1]   [,2]\ncm             0.8097 0.5868\nmm             0.9988 0.0484\nstandardisiert 0.7071 0.7071\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nS_cm = np.cov(D, rowvar=False)\nw_cm, V_cm = eigen_absteigend(S_cm)\nprint(np.round(np.vstack([w_cm, w_cm / w_cm.sum()]), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[127.5356  31.5379]\n [  0.8017   0.1983]]\n```\n\n\n:::\n\n```{.python .cell-code}\nD_mm = np.column_stack([D[:, 0] * 10, D[:, 1]])\nS_mm = np.cov(D_mm, rowvar=False)\nprint(np.round(S_mm, 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[9447.77  456.14]\n [ 456.14   64.6 ]]\n```\n\n\n:::\n\n```{.python .cell-code}\nw_mm, V_mm = eigen_absteigend(S_mm)\nprint(np.round(np.vstack([w_mm, w_mm / w_mm.sum()]), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[9469.8938   42.4736]\n [   0.9955    0.0045]]\n```\n\n\n:::\n\n```{.python .cell-code}\nR = np.corrcoef(D, rowvar=False)\nprint(np.round(R, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1.     0.5839]\n [0.5839 1.    ]]\n```\n\n\n:::\n\n```{.python .cell-code}\nw_r, V_r = eigen_absteigend(R)\nprint(np.round(np.vstack([w_r, w_r / w_r.sum()]), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1.5839 0.4161]\n [0.7919 0.2081]]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(np.round(V_r, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[ 0.7071 -0.7071]\n [ 0.7071  0.7071]]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"summe_eigenwerte\": round(float(w_r.sum()), 4),\n       \"anzahl_variablen\": D.shape[1]})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'summe_eigenwerte': 2.0, 'anzahl_variablen': 2}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(np.round(np.vstack([V_cm[:, 0], V_mm[:, 0], V_r[:, 0]]), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[0.8097 0.5868]\n [0.9988 0.0484]\n [0.7071 0.7071]]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Rechnung | $\\lambda_1$ | $\\lambda_2$ | Anteil 1 | Anteil 2 |\n|---|---|---|---|---|\n| Kovarianz, **cm** | 127.54 | 31.54 | **80.2 %** | 19.8 % |\n| Kovarianz, **mm** | 9469.89 | 42.47 | **99.6 %** | **0.4 %** |\n| **Korrelation** | 1.5839 | 0.4161 | **79.2 %** | 20.8 % |\n\nErste Eigenvektoren:\n\n| Rechnung | Ladung Grösse | Ladung Gewicht |\n|---|---|---|\n| cm | 0.8097 | 0.5868 |\n| mm | **0.9988** | **0.0484** |\n| standardisiert | **0.7071** | **0.7071** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| In Millimetern erklärt die erste Komponente **99.6 statt 80.2 Prozent** | Die Varianz der Grösse wird beim Wechsel auf Millimeter mit $10^2 = 100$ multipliziert (9447.8 statt 94.5), die des Gewichts nicht. Die Komponente folgt der grössten Varianz — und die ist jetzt fast nur noch die Grösse. |\n| Der erste Eigenvektor kippt auf (**0.999, 0.048**) | Die Komponente ist praktisch nur noch die Körpergrösse. **Dieselben Daten, eine andere Einheit, eine völlig andere Antwort.** |\n| Die Korrelationsmatrix hat Eigenwerte, die sich zu **2** addieren | Allgemein zur **Anzahl der Variablen**, weil jede standardisierte Variable die Varianz 1 hat. Daher das Kaiser-Kriterium \"Eigenwert > 1\": eine Komponente soll mehr erklären als eine einzelne Variable. |\n| Der erste Eigenvektor ist **exakt (0.707, 0.707)** | Bei zwei standardisierten Variablen immer, unabhängig von der Korrelation — die Matrix ist dann symmetrisch in beiden Variablen. Die **Eigenwerte** $1 \\pm r$ hängen dagegen von der Korrelation ab: $1 + 0.584 = 1.584$ und $1 - 0.584 = 0.416$. |\n| Die Anteile aus cm und aus der Korrelation liegen nahe beieinander | 80.2 gegen 79.2 Prozent. Zufall dieses Datensatzes: Die beiden Standardabweichungen sind mit 9.72 und 8.04 ähnlich gross. Bei sehr ungleichen Streuungen klaffen sie weit auseinander. |\n\n::: {.warning-box}\n**Die Regel, die daraus folgt:** Eine PCA auf der **Kovarianzmatrix** ist nur\nzulässig, wenn alle Variablen in **derselben Einheit** gemessen sind und\nUnterschiede in der Streuung inhaltlich gemeint sind — etwa mehrere\nTemperaturmessungen oder Preise in Franken.\n\nSobald Einheiten gemischt werden (Zentimeter, Kilogramm, Franken, Punkte), führt\nnur die **Korrelationsmatrix** zu einem sinnvollen Ergebnis, weil das Verfahren\nsonst schlicht die Variable mit der grössten Zahlenspanne findet.\n\n| Funktion | Standardverhalten | Standardisierung einschalten |\n|---|---|---|\n| R `prcomp()` | **Kovarianz** | `scale. = TRUE` |\n| R `princomp()` | **Kovarianz** | `cor = TRUE` |\n| Python `sklearn.decomposition.PCA` | **Kovarianz** | `StandardScaler` vorschalten |\n\n**Alle drei standardisieren von sich aus nicht.** Das ist der häufigste Fehler\nbei einer PCA.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Der blosse Wechsel von Zentimetern auf Millimeter hebt den Anteil der ersten\n> Komponente von 80.2 auf 99.6 Prozent und dreht ihren Eigenvektor von\n> (0.810, 0.587) auf (0.999, 0.048). Auf der Korrelationsmatrix gerechnet ist\n> das Ergebnis von der Einheit unabhängig: Eigenwerte 1.584 und 0.416, Summe\n> gleich der Anzahl Variablen.\n\n### Beispiel 5: Wenn ein Eigenwert null wird\n\n#### Frage und Datenlage\n\nDrei Variablen, von denen die dritte einmal exakt und einmal fast exakt die\nSumme der beiden ersten ist. Was macht die Eigenzerlegung daraus?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 200\nZ <- normalmatrix(6160, n, 3)\nx1 <- 100 + 15 * Z[, 1]\nx2 <- 50 + 0.6 * (x1 - 100) + 9 * Z[, 2]\nx3 <- x1 + x2                 # exakt abhaengig\nx4 <- x1 + x2 + 0.5 * Z[, 3]  # fast abhaengig\nx5 <- 50 + 8 * Z[, 3]         # unabhaengig\n\nbericht <- function(name, D) {\n  R <- cor(D)\n  # Eigenwerte und Determinante einer Korrelationsmatrix sind theoretisch\n  # nicht negativ; numerisch kann bei exakter Abhaengigkeit -1e-16 stehen.\n  w <- pmax(eigen(R)$values, 0)\n  cat(sprintf(\"%-10s Eigenwerte: %s | Summe %.4f | Rang %d | det %.6f\\n\",\n              name, paste(sprintf(\"%.6f\", w), collapse = \"  \"),\n              sum(w), qr(R)$rank, abs(det(R))))\n}\nbericht(\"exakt\", cbind(x1, x2, x3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nexakt      Eigenwerte: 2.675167  0.324833  0.000000 | Summe 3.0000 | Rang 2 | det 0.000000\n```\n\n\n:::\n\n```{.r .cell-code}\nbericht(\"fast\", cbind(x1, x2, x4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfast       Eigenwerte: 2.674740  0.324956  0.000304 | Summe 3.0000 | Rang 3 | det 0.000264\n```\n\n\n:::\n\n```{.r .cell-code}\nbericht(\"normal\", cbind(x1, x2, x5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnormal     Eigenwerte: 1.690445  0.992690  0.316865 | Summe 3.0000 | Rang 3 | det 0.531727\n```\n\n\n:::\n\n```{.r .cell-code}\n# Der Varianzinflationsfaktor misst dasselbe aus Regressionssicht\nvif_wert <- function(D, j) {\n  modell <- lm(D[, j] ~ D[, -j])\n  1 / (1 - summary(modell)$r.squared)\n}\nround(c(x1 = vif_wert(cbind(x1, x2, x4), 1), x2 = vif_wert(cbind(x1, x2, x4), 2),\n        x4 = vif_wert(cbind(x1, x2, x4), 3)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     x1      x2      x4 \n 730.07  509.19 2058.31 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(x1 = vif_wert(cbind(x1, x2, x5), 1), x2 = vif_wert(cbind(x1, x2, x5), 2),\n        x5 = vif_wert(cbind(x1, x2, x5), 3)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  x1   x2   x5 \n1.85 1.88 1.02 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(korr_x1_x2 = cor(x1, x2), korr_x4_x1 = cor(x4, x1),\n        korr_x4_x2 = cor(x4, x2)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nkorr_x1_x2 korr_x4_x1 korr_x4_x2 \n    0.6759     0.9304     0.8985 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nn = 200\nZ = normalmatrix(6160, n, 3)\nx1 = 100 + 15 * Z[:, 0]\nx2 = 50 + 0.6 * (x1 - 100) + 9 * Z[:, 1]\nx3 = x1 + x2\nx4 = x1 + x2 + 0.5 * Z[:, 2]\nx5 = 50 + 8 * Z[:, 2]\n\n\ndef bericht(name, D):\n    R = np.corrcoef(D, rowvar=False)\n    w = np.maximum(np.linalg.eigvalsh(R)[::-1], 0)\n    werte = \"  \".join(f\"{v:.6f}\" for v in w)\n    print(f\"{name:<10} Eigenwerte: {werte} | Summe {w.sum():.4f}\"\n          f\" | Rang {np.linalg.matrix_rank(R)} | det {abs(np.linalg.det(R)):.6f}\")\n\n\nbericht(\"exakt\", np.column_stack([x1, x2, x3]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nexakt      Eigenwerte: 2.675167  0.324833  0.000000 | Summe 3.0000 | Rang 2 | det 0.000000\n```\n\n\n:::\n\n```{.python .cell-code}\nbericht(\"fast\", np.column_stack([x1, x2, x4]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfast       Eigenwerte: 2.674740  0.324956  0.000304 | Summe 3.0000 | Rang 3 | det 0.000264\n```\n\n\n:::\n\n```{.python .cell-code}\nbericht(\"normal\", np.column_stack([x1, x2, x5]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnormal     Eigenwerte: 1.690445  0.992690  0.316865 | Summe 3.0000 | Rang 3 | det 0.531727\n```\n\n\n:::\n\n```{.python .cell-code}\ndef vif_wert(D, j):\n    y = D[:, j]\n    X = np.column_stack([np.ones(len(D)), np.delete(D, j, axis=1)])\n    b = np.linalg.lstsq(X, y, rcond=None)[0]\n    r2 = 1 - ((y - X @ b) ** 2).sum() / ((y - y.mean()) ** 2).sum()\n    return 1 / (1 - r2)\n\n\nDf = np.column_stack([x1, x2, x4])\nprint({\"x1\": round(float(vif_wert(Df, 0)), 2), \"x2\": round(float(vif_wert(Df, 1)), 2),\n       \"x4\": round(float(vif_wert(Df, 2)), 2)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'x1': 730.07, 'x2': 509.19, 'x4': 2058.31}\n```\n\n\n:::\n\n```{.python .cell-code}\nDn = np.column_stack([x1, x2, x5])\nprint({\"x1\": round(float(vif_wert(Dn, 0)), 2), \"x2\": round(float(vif_wert(Dn, 1)), 2),\n       \"x5\": round(float(vif_wert(Dn, 2)), 2)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'x1': 1.85, 'x2': 1.88, 'x5': 1.02}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"korr_x1_x2\": round(float(np.corrcoef(x1, x2)[0, 1]), 4),\n       \"korr_x4_x1\": round(float(np.corrcoef(x4, x1)[0, 1]), 4),\n       \"korr_x4_x2\": round(float(np.corrcoef(x4, x2)[0, 1]), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'korr_x1_x2': 0.6759, 'korr_x4_x1': 0.9304, 'korr_x4_x2': 0.8985}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Fall | $\\lambda_1$ | $\\lambda_2$ | $\\lambda_3$ | Summe | Rang | Determinante |\n|---|---|---|---|---|---|---|\n| $x_3 = x_1 + x_2$ (**exakt**) | 2.675167 | 0.324833 | **0.000000** | 3 | **2** | **0.000000** |\n| $x_4 = x_1 + x_2 + \\varepsilon$ (**fast**) | 2.674740 | 0.324956 | **0.000304** | 3 | 3 | 0.000264 |\n| unabhängig | 1.690445 | 0.992690 | 0.316865 | 3 | 3 | 0.531727 |\n\nVarianzinflationsfaktoren:\n\n| Fall | $x_1$ | $x_2$ | dritte Variable |\n|---|---|---|---|\n| fast abhängig | **730.07** | **509.19** | **2058.31** |\n| unabhängig | 1.85 | 1.88 | 1.02 |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Der dritte Eigenwert ist im exakten Fall **null** | Es gibt eine Richtung, in der die Daten **keine** Streuung haben — alle 200 Punkte liegen auf einer Ebene im dreidimensionalen Raum. Die dritte Variable trägt keine neue Information. |\n| Der Rang fällt von 3 auf **2** | Der Rang zählt, wie viele Richtungen tatsächlich genutzt werden. **Rang = Anzahl der Eigenwerte grösser null.** |\n| Die Determinante ist **0** | Sie ist das Produkt der Eigenwerte. Ein Faktor null macht das Produkt null — und eine Matrix mit Determinante null lässt sich **nicht invertieren**. |\n| Im \"fast\"-Fall ist $\\lambda_3$ **0.000304** statt 0 | Nicht null, aber fast. Die Determinante liegt bei 0.000264. Der Rang ist formal 3, praktisch aber 2. |\n| Die VIF explodieren auf **730 bis 2058** | Faustregel ist 10. Eine VIF von 2058 heisst: Der Standardfehler dieses Koeffizienten ist $\\sqrt{2058} \\approx 45$ mal so gross wie ohne Kollinearität. |\n| Die Summe der Eigenwerte ist **immer 3** | Bei jeder Korrelationsmatrix mit drei Variablen. Die Gesamtvarianz ist festgelegt; nur ihre Aufteilung ändert sich. |\n| Die einzelnen Korrelationen sind **unauffällig** | $r(x_1, x_2) = 0.676$, $r(x_4, x_1) = 0.930$. Hoch, aber nichts, was allein Alarm auslösen würde. **Kollinearität steckt in der Kombination, nicht in einzelnen Paaren** — die Korrelationsmatrix durchzusehen genügt nicht. |\n\n::: {.note-box}\n**Dasselbe Problem, drei Sprachen:**\n\n| Sicht | Anzeichen | Kennzahl |\n|---|---|---|\n| lineare Algebra | eine Richtung ohne Streuung | $\\lambda_{\\min} \\approx 0$ |\n| Matrizenrechnung | Matrix nicht invertierbar | $\\det \\approx 0$, Rang < $p$ |\n| Regression | Koeffizienten instabil, riesige Standardfehler | VIF $> 10$ |\n| PCA | letzte Komponenten überflüssig | kleine Eigenwerte |\n\n**Für die PCA ist das kein Problem, sondern ihr Zweck.** Sie verträgt\nkollineare Variablen problemlos und liefert genau die Antwort \"die letzte\nRichtung ist überflüssig\". Für eine\n[Regression](../regression/multiple-lineare-regression.qmd) ist dieselbe Lage ein\nernstes Problem, weil sie die Matrix invertieren muss. Das ist einer der\nGründe, eine PCA einer Regression vorzuschalten.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Ist eine Variable die exakte Summe zweier anderer, hat die Korrelationsmatrix\n> den Eigenwert null, den Rang 2 und die Determinante 0. Bei einer nur fast\n> exakten Abhängigkeit bleibt ein Eigenwert von 0.0003 übrig, und die\n> Varianzinflationsfaktoren steigen auf 730 bis 2058 — während die einzelnen\n> Korrelationen mit 0.68 bis 0.93 unauffällig aussehen.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nWas ist ein Eigenvektor einer Matrix?\n\n- [x] Eine Richtung, die von der Abbildung nicht gedreht, sondern nur gestreckt\n      wird ~ Richtig. Der Streckfaktor ist der Eigenwert; A mal v ergibt lambda\n      mal v.\n- [ ] Der längste Vektor in der Matrix ~ Eigenvektoren werden normiert, ihre\n      Länge ist beliebig wählbar.\n- [ ] Die erste Spalte der Matrix ~ Die Spalten sind die Bilder der\n      Einheitsvektoren, nur bei einer Diagonalmatrix sind das die\n      Eigenvektoren.\n:::\n\n::: {.quiz}\nDie Kovarianzmatrix hatte die Spur 159.07 und die Eigenwerte 127.54 und 31.54.\nWas sagt der Vergleich?\n\n- [x] Die Gesamtvarianz wird umverteilt, nicht verändert ~ Richtig, 127.54 plus\n      31.54 ergibt 159.07. Deshalb lässt sich ein Anteil erklärter Varianz\n      angeben, hier 80.2 und 19.8 Prozent.\n- [ ] Die PCA hat Varianz hinzugefügt ~ Die Summe ist identisch; eine\n      Drehung des Koordinatensystems kann keine Varianz erzeugen.\n- [ ] Die Eigenwerte sind zufällig nahe an der Spur ~ Die Gleichheit gilt\n      exakt und für jede Matrix.\n:::\n\n::: {.quiz}\nWarum sind Hauptkomponenten unkorreliert?\n\n- [x] Weil die Eigenvektoren einer symmetrischen Matrix senkrecht aufeinander\n      stehen ~ Richtig. Im Beispiel war die Kovarianz der beiden Scores exakt\n      null, und das Skalarprodukt der Eigenvektoren ebenfalls.\n- [ ] Weil die Daten vorher standardisiert werden ~ Standardisierung ändert\n      nichts an der Korrelation zwischen Variablen; im Beispiel wurde nicht\n      standardisiert.\n- [ ] Weil die Stichprobe gross genug war ~ Es gilt exakt und bei jedem\n      Stichprobenumfang.\n:::\n\n::: {.quiz}\nDer Wechsel von Zentimetern auf Millimeter hob den Anteil der ersten Komponente\nvon 80.2 auf 99.6 Prozent. Was folgt daraus?\n\n- [x] Bei gemischten Einheiten muss die Korrelationsmatrix verwendet werden ~\n      Richtig. Auf der Kovarianzmatrix findet das Verfahren sonst nur die\n      Variable mit der grössten Zahlenspanne. prcomp braucht dafür\n      scale. gleich TRUE.\n- [ ] Millimeter sind die genauere Einheit und daher vorzuziehen ~ Die\n      Information ist in beiden Fällen dieselbe, nur die Zahlen sind grösser.\n- [ ] Die PCA ist unbrauchbar ~ Sie ist brauchbar, sobald die Frage nach der\n      Standardisierung bewusst entschieden wird.\n:::\n\n::: {.quiz}\nEine Korrelationsmatrix von drei Variablen hat die Eigenwerte 2.675, 0.325 und\n0.000. Was bedeutet das?\n\n- [x] Eine Variable ist eine exakte Linearkombination der beiden anderen ~\n      Richtig. Der Rang ist 2, die Determinante null, und die Matrix lässt sich\n      nicht invertieren. Für eine Regression ist das fatal, für eine PCA ist es\n      die gesuchte Antwort.\n- [ ] Die dritte Variable ist konstant ~ Dann wäre ihre Korrelation gar nicht\n      definiert; hier streut sie sehr wohl, nur nicht unabhängig.\n- [ ] Die Stichprobe ist zu klein ~ Der Effekt hängt nicht am\n      Stichprobenumfang, sondern an der exakten Abhängigkeit.\n:::\n\n::: {.quiz}\nDie paarweisen Korrelationen lagen bei 0.68 bis 0.93, die\nVarianzinflationsfaktoren aber bei 730 bis 2058. Wie passt das zusammen?\n\n- [x] Kollinearität steckt in der Kombination mehrerer Variablen, nicht in\n      einzelnen Paaren ~ Richtig. Deshalb genügt es nicht, die\n      Korrelationsmatrix durchzusehen; VIF oder der kleinste Eigenwert zeigen\n      es.\n- [ ] Die VIF sind falsch berechnet ~ Sie folgen direkt aus dem\n      Bestimmtheitsmass der Regression einer Variablen auf alle anderen, hier\n      über 0.999.\n- [ ] Korrelationen über 0.9 sind immer unproblematisch ~ Sie sind bereits\n      hoch; entscheidend ist aber die gemeinsame Abhängigkeit.\n:::\n\n## Verlinkte Ressourcen\n\n- [Hauptkomponentenanalyse](hauptkomponentenanalyse.qmd)\n- [Faktorenanalyse](faktorenanalyse.qmd)\n- [Distanzmasse](distanzmasse.qmd)\n- [3Blue1Brown, Essence of Linear Algebra](https://www.3blue1brown.com/topics/linear-algebra)\n",
    "supporting": [
      "lineare-algebra-pca_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}