{
  "hash": "b2c7f5ac99ba63e4b9c478ba9924ddd2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Kreuzvalidierung\"\ndescription: \"Validierungsansatz, LOOCV, k-fache CV und wie man k wählt.\"\ncategories: [\"Regression\", \"Modellvalidierung\", \"Resampling\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: methode\nstand: fertig\norder: 38\n---\n\n\n\n\n\nAlle Beispiele rechnen mit demselben Datensatz wie auf der Seite\n[Modellauswahl](modellauswahl.qmd): 150 Fälle, zwei Prädiktoren `x1` und `x2`,\ndie tatsächlich auf `y` wirken, und sechs Grössen `z1` bis `z6`, die\nkonstruktionsbedingt wirkungslos sind. Weil die Wahrheit bekannt ist, lässt\nsich prüfen, ob die Kreuzvalidierung sie findet.\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Wie gut sagt ein Modell neue, ungesehene Daten vorher? |\n| Eingang | ein oder mehrere angepasste Modelle, dieselben Daten |\n| Was das Verfahren liefert | geschätzter Vorhersagefehler (MSE oder RMSE) auf Daten, die nicht zur Schätzung benutzt wurden |\n| Varianten | Validation Set, Leave-One-Out (LOOCV), k-fache CV, wiederholte CV |\n| R-Funktionen | `boot::cv.glm()`, manuell mit `lm()` und Faltenzuordnung |\n| Python-Funktionen | `sklearn.model_selection.cross_val_score`, `KFold`, `LeaveOneOut` |\n| Verwandte Methoden | [Modellauswahl](modellauswahl.qmd), [Bootstrap-Resampling](../inferenz/bootstrap-resampling.qmd), [Regressionsdiagnostik](regressionsdiagnostik.qmd) |\n\n## Wann diese Methode, wann nicht\n\n| Situation | Kreuzvalidierung geeignet? |\n|---|---|\n| Vorhersagegüte eines Modells ehrlich schätzen | ja, das ist ihr Kernzweck |\n| Zwei oder mehr Modelle vergleichen | ja, über den CV-Fehler |\n| Hyperparameter wählen (Polynomgrad, Regularisierungsstärke) | ja |\n| Das wahre Modell identifizieren | bedingt; BIC ist dafür oft besser |\n| Konfidenzintervalle für Koeffizienten | nein; dafür eignet sich der [Bootstrap](../inferenz/bootstrap-resampling.qmd) |\n| Zeitreihen | nicht mit zufälligen Splits; siehe [Zeitreihen](../zeitreihen/index.qmd) |\n\n## Grundidee und Modell\n\n### Validation-Set-Ansatz\n\nDie einfachste Idee: Die Daten werden in eine Trainings- und eine Testmenge\naufgeteilt. Das Modell wird nur auf der Trainingsmenge geschätzt, der Fehler\nnur auf der Testmenge gemessen.\n\nVorteile: einfach, schnell. Nachteile: Der Fehler hängt stark davon ab, welche\nFälle in welcher Menge landen. Bei kleinen Datensätzen ist das Ergebnis\ninstabil, und ein grosser Testanteil verschwendet Trainingsdaten.\n\n### Leave-One-Out-Kreuzvalidierung (LOOCV)\n\nLOOCV treibt die Idee auf die Spitze: Jede Beobachtung wird einmal\nzurückgehalten, das Modell auf den übrigen $n - 1$ Fällen geschätzt, und der\nFehler am einen zurückgehaltenen Fall gemessen. Der CV-Fehler ist der\nDurchschnitt der $n$ quadrierten Abweichungen:\n\n$$\n\\text{CV}_{(n)} = \\frac{1}{n} \\sum_{i=1}^{n} \\left( y_i - \\hat{y}_{(i)} \\right)^2\n$$\n\nBei linearen Modellen gibt es eine Abkürzungsformel, die die $n$ Modelle nicht\neinzeln anpassen muss. Sie nutzt die Hat-Werte $h_{ii}$ aus der einzigen\nAnpassung auf allen Daten:\n\n$$\n\\text{CV}_{(n)} = \\frac{1}{n} \\sum_{i=1}^{n} \\left( \\frac{y_i - \\hat{y}_i}{1 - h_{ii}} \\right)^2\n$$\n\nDas spart enorm Rechenzeit und liefert exakt dasselbe Ergebnis.\n\n### k-fache Kreuzvalidierung\n\nDie Daten werden in $k$ gleich grosse Teile (Falten) aufgeteilt. Für jede\nFalte wird das Modell auf den $k - 1$ übrigen Falten geschätzt und der Fehler\nauf der zurückgehaltenen Falte gemessen. Der CV-Fehler ist der Durchschnitt\nüber alle $k$ Falten.\n\nLOOCV ist der Spezialfall $k = n$. In der Praxis sind $k = 5$ und $k = 10$\nüblich.\n\n### Wahl von k: Bias-Varianz-Abwägung der CV selbst\n\nDie Kreuzvalidierung selbst unterliegt einer Bias-Varianz-Abwägung:\n\n| k | Bias des CV-Fehlers | Varianz des CV-Fehlers | Rechenaufwand |\n|---|---|---|---|\n| $k = n$ (LOOCV) | fast null, weil das Training fast alle Daten nutzt | hoch, weil die $n$ Trainingsmengen stark überlappen und die Fehlerschätzungen korreliert sind | $n$ Modellanpassungen (bei linearen Modellen per Formel vermeidbar) |\n| $k = 5$ | leicht positiv, weil 20 % der Daten fehlen | niedrig, weniger Überlappung | 5 Modellanpassungen |\n| $k = 10$ | mässig | mässig | 10 Modellanpassungen |\n\n**$k = 10$ gilt als bester Kompromiss** und ist die Standardempfehlung. $k = 5$\nist vertretbar, wenn der Datensatz gross ist. LOOCV lohnt sich hauptsächlich\nbei sehr kleinen Datensätzen oder wenn die Abkürzungsformel greift.\n\n### Wiederholte Kreuzvalidierung\n\nWeil die Aufteilung in Falten zufällig ist, schwankt der CV-Fehler. Bei\nwiederholter CV (repeated CV) wird die gesamte k-fache CV mehrfach mit\nverschiedenen Aufteilungen durchgeführt und der Fehler gemittelt. Das\nstabilisiert das Ergebnis, vervielfacht aber die Rechenzeit.\n\n### CV bei Klassifikation\n\nBei binärer Zielgrösse ersetzt die Fehlklassifikationsrate den MSE. Stratified\nCV stellt sicher, dass jede Falte denselben Anteil der Klassen enthält wie der\nGesamtdatensatz. Das ist besonders bei unbalancierten Klassen wichtig, damit\nkeine Falte nur Fälle einer Klasse enthält.\n\n### Zeitreihen-CV\n\nBei Zeitreihen sind zufällige Splits falsch, weil sie die zeitliche Ordnung\nzerstören. Stattdessen kommt eine Vorwärtsvalidierung zum Einsatz: Das Modell\nwird auf den Daten bis Zeitpunkt $t$ geschätzt und auf den Daten danach\ngeprüft, und $t$ wird schrittweise nach vorne geschoben. Details auf der Seite\n[Zeitreihen](../zeitreihen/index.qmd).\n\n### Bootstrap zur Modellbewertung\n\nDer Bootstrap zieht Stichproben mit Zurücklegen aus den Daten. Er kann\nebenfalls für Modellbewertung eingesetzt werden, neigt aber dazu, den\nVorhersagefehler zu unterschätzen, weil Trainingsdaten und Testdaten\nüberlappen. Die Variante \".632 Bootstrap\" korrigiert das teilweise. Für\nKonfidenzintervalle und Standardfehler ist der Bootstrap die bessere Wahl;\nfür Vorhersagegüte ist die Kreuzvalidierung direkter. Mehr dazu auf der Seite\n[Bootstrap-Resampling](../inferenz/bootstrap-resampling.qmd).\n\n## Voraussetzungen und ihre Prüfung\n\nDie Kreuzvalidierung selbst hat wenige Voraussetzungen:\n\n| Voraussetzung | Prüfung | Folge bei Verletzung |\n|---|---|---|\n| Beobachtungen sind unabhängig | Fachliche Überlegung; bei Zeitreihen oder gruppierten Daten andere CV-Strategie nötig | Der CV-Fehler ist zu optimistisch |\n| Jede Falte ist repräsentativ | Bei kleinem n oder seltenen Klassen prüfen, ob die Verteilung in den Falten stimmt | Instabile Ergebnisse; stratified CV oder wiederholte CV hilft |\n| Kein Datenleck | Alle Vorverarbeitungsschritte (Variablenselektion, Skalierung) müssen **innerhalb** jeder Falte geschehen, nicht vorher | Massiv zu optimistischer Fehler; siehe Beispiel 2 |\n\nDie dritte Zeile ist die wichtigste und häufigste Fehlerquelle. Sie wird in\nBeispiel 2 demonstriert.\n\n## Output lesen\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| `cv.glm(...)$delta[1]` (R) | roher CV-Fehler (Durchschnitt der quadrierten Abweichungen über alle Falten) | das ist der MSE, nicht der RMSE; für die Wurzel selbst sorgen |\n| `cv.glm(...)$delta[2]` (R) | bias-korrigierter CV-Fehler | die Korrektur ist meist winzig; bei grossem n praktisch identisch mit delta[1] |\n| `cross_val_score(..., scoring=\"neg_mean_squared_error\")` (Python) | Array mit einem Wert je Falte; **negativ** vorzeichnet | sklearn maximiert Scores; MSE ist ein Fehler, daher das Minuszeichen. `−np.mean(scores)` ergibt den MSE |\n| Standardabweichung der Falten-Scores | wie stabil der CV-Fehler über die Falten ist | grosse Streuung deutet auf zu wenige Daten je Falte oder heterogene Daten hin |\n| LOOCV-Formel mit Hat-Werten | exakter LOOCV-MSE ohne $n$ einzelne Anpassungen | nur für lineare Modelle; bei nicht-linearen Modellen muss tatsächlich $n$-mal gefittet werden |\n\n## Interpretationsfallen\n\n- **Variablenselektion vor CV ist ein Datenleck.** Wer die besten Prädiktoren\n  auf allen Daten auswählt und dann kreuzvalidiert, misst nicht die\n  Vorhersagegüte, sondern die Fähigkeit, sich an genau diesen Datensatz\n  anzupassen. Die Selektion muss in jede Falte hinein.\n- **Der CV-Fehler ist selbst eine Schätzung mit Varianz.** Ein Unterschied von\n  0.01 im RMSE zwischen zwei Modellen kann rein zufällig sein. Wiederholte CV\n  und die Streuung über die Falten geben einen Anhaltspunkt.\n- **LOOCV hat hohe Varianz.** Die $n$ Trainingsmengen überlappen fast\n  vollständig, ihre Fehler sind stark korreliert, und der Durchschnitt glättet\n  weniger, als man bei $n$ Werten erwartet.\n- **Negative Scores in sklearn sind kein Fehler.** sklearn maximiert Scores.\n  Da MSE ein Fehler ist, wird er negiert. `neg_mean_squared_error` liefert\n  negative Werte, die betragsmässig dem MSE entsprechen.\n- **CV vergleicht Modelle, sie validiert sie nicht.** Ein kleiner CV-Fehler\n  heisst nicht, dass das Modell die Daten angemessen beschreibt. Dafür\n  braucht es die [Diagnostik](regressionsdiagnostik.qmd).\n\n## Ergebnis berichten\n\n> Verglichen wurden [Anzahl] Modelle mittels [k]-facher Kreuzvalidierung auf\n> [n] Beobachtungen. Gewählt wurde [Modell] mit einem mittleren\n> Vorhersagefehler (RMSE) von [Wert] (SD über Falten: [Wert]). Das\n> nächstbeste Modell erreichte [Wert]. Die Variablenselektion erfolgte\n> [innerhalb jeder Falte / vorab, und warum].\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt der Kreuzvalidierung |\n|---|---|\n| [Modellauswahl mit AIC/BIC](modellauswahl.qmd) | schnelle Rangordnung geschachtelter Modelle ohne Rechenaufwand; AIC ist asymptotisch äquivalent zu LOOCV |\n| [Bootstrap-Resampling](../inferenz/bootstrap-resampling.qmd) | Konfidenzintervalle und Standardfehler für Koeffizienten; für Vorhersagegüte ist CV direkter |\n| [Regressionsdiagnostik](regressionsdiagnostik.qmd) | die Frage ist nicht, welches Modell besser vorhersagt, sondern ob ein gegebenes Modell zulässig ist |\n| [Klassifikationsgüte](klassifikationsguete.qmd) | spezifische Masse für Klassifikation (Sensitivität, Spezifität, AUC) |\n| Regularisierung (Ridge, Lasso) | viele Prädiktoren; CV dient dort zur Wahl der Regularisierungsstärke |\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: k-fache CV und LOOCV im Vergleich\n\n#### Frage und Datenlage\n\nWie gross ist der Vorhersagefehler des wahren Modells (`x1 + x2`)? Stimmen\n5-fache, 10-fache und Leave-One-Out-Kreuzvalidierung überein?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- Manuelle k-fache CV ---\ncv_manuell <- function(formel, k) {\n  falte <- (seq_len(n) - 1) %% k\n  fehler <- sapply(0:(k - 1), function(f) {\n    test <- falte == f\n    modell <- lm(formel, data = daten[!test, ])\n    mean((daten$y[test] - predict(modell, daten[test, ]))^2)\n  })\n  mean(fehler)\n}\n\nmse_5  <- cv_manuell(y ~ x1 + x2, k = 5)\nmse_10 <- cv_manuell(y ~ x1 + x2, k = 10)\n\n# --- LOOCV mit Abkuerzungsformel (Hat-Werte) ---\nm12 <- lm(y ~ x1 + x2, data = daten)\nh   <- hatvalues(m12)\nmse_loo_formel <- mean((residuals(m12) / (1 - h))^2)\n\n# --- LOOCV mit boot::cv.glm ---\nm12_glm <- glm(y ~ x1 + x2, data = daten)\ncv_out  <- cv.glm(daten, m12_glm, K = n)\n\ncat(\"5-fach  MSE:\", round(mse_5, 4), \" RMSE:\", round(sqrt(mse_5), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n5-fach  MSE: 35.2813  RMSE: 5.9398 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"10-fach MSE:\", round(mse_10, 4), \" RMSE:\", round(sqrt(mse_10), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n10-fach MSE: 35.1933  RMSE: 5.9324 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"LOOCV (Formel) MSE:\", round(mse_loo_formel, 4),\n    \" RMSE:\", round(sqrt(mse_loo_formel), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLOOCV (Formel) MSE: 36.2795  RMSE: 6.0232 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"cv.glm delta[1]:\", round(cv_out$delta[1], 4),\n    \" delta[2]:\", round(cv_out$delta[2], 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncv.glm delta[1]: 36.2795  delta[2]: 36.2742 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nX = daten[[\"x1\", \"x2\"]].values\ny = daten[\"y\"].values\n\nmodell = LinearRegression()\n\n# --- k-fache CV ---\nscores_5  = cross_val_score(modell, X, y, cv=KFold(n_splits=5, shuffle=False),\n                            scoring=\"neg_mean_squared_error\")\nscores_10 = cross_val_score(modell, X, y, cv=KFold(n_splits=10, shuffle=False),\n                            scoring=\"neg_mean_squared_error\")\n\nmse_5  = -np.mean(scores_5)\nmse_10 = -np.mean(scores_10)\n\n# --- LOOCV ---\nscores_loo = cross_val_score(modell, X, y, cv=LeaveOneOut(),\n                             scoring=\"neg_mean_squared_error\")\nmse_loo = -np.mean(scores_loo)\n\n# --- LOOCV mit Abkuerzungsformel ---\nm12 = smf.ols(\"y ~ x1 + x2\", data=daten).fit()\nH = m12.get_influence().hat_matrix_diag\nmse_loo_formel = np.mean((m12.resid / (1 - H)) ** 2)\n\nprint(f\"5-fach  MSE: {mse_5:.4f}  RMSE: {np.sqrt(mse_5):.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n5-fach  MSE: 35.1485  RMSE: 5.9286\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"10-fach MSE: {mse_10:.4f}  RMSE: {np.sqrt(mse_10):.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n10-fach MSE: 34.9726  RMSE: 5.9138\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"LOOCV       MSE: {mse_loo:.4f}  RMSE: {np.sqrt(mse_loo):.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLOOCV       MSE: 36.2795  RMSE: 6.0232\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"LOOCV (Formel) MSE: {mse_loo_formel:.4f}  RMSE: {np.sqrt(mse_loo_formel):.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLOOCV (Formel) MSE: 36.2795  RMSE: 6.0232\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Verfahren | MSE | RMSE | Wie das zu lesen ist |\n|---|---|---|---|\n| 5-fach CV | ca. 35.3 | ca. 5.94 | Die Falten sind deterministisch (jeder fünfte Fall); das stabilisiert den Vergleich. |\n| 10-fach CV | ca. 35.7 | ca. 5.97 | Sehr nah am 5-fachen Ergebnis. |\n| LOOCV (brute force) | ca. 36.2 | ca. 6.02 | $n = 150$ einzelne Anpassungen, rechnerisch aufwendig. |\n| LOOCV (Hat-Formel) | ca. 36.2 | ca. 6.02 | Exakt dasselbe Ergebnis aus einer einzigen Anpassung. |\n| `cv.glm delta[1]` | ca. 36.2 | | Roh-CV-Fehler, identisch mit LOOCV. |\n| `cv.glm delta[2]` | ca. 36.2 | | Bias-korrigiert; bei diesem n praktisch identisch mit delta[1]. |\n\nDie drei Varianten liefern fast denselben Fehler. Das ist typisch, wenn das\nModell nicht überangepasst ist: Dann spielt es kaum eine Rolle, ob 80 % oder\n99 % der Daten zum Training genutzt werden.\n\n::: {.note-box}\n**delta[1] und delta[2] in `cv.glm`.** `delta[1]` ist der rohe CV-MSE.\n`delta[2]` wendet eine Bias-Korrektur an, die den Unterschied zwischen dem\nTrainings- und dem Testfehler berücksichtigt. Bei grossem n und einfachen\nModellen ist die Korrektur vernachlässigbar. Beide Werte sind MSE, nicht RMSE.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Für das Modell `y ~ x1 + x2` liefern 5-fache, 10-fache und\n> Leave-One-Out-Kreuzvalidierung übereinstimmend einen RMSE von etwa 5.9 bis\n> 6.0. Die LOOCV-Abkürzungsformel über Hat-Werte stimmt exakt mit der\n> aufwendigen Variante überein. Die Ergebnisse bestätigen, dass das Modell\n> stabil ist und nicht überangepasst.\n\n### Beispiel 2: Datenleck durch Variablenselektion vor CV\n\n#### Frage und Datenlage\n\nEin häufiger Fehler: Zuerst werden auf allen Daten die besten Prädiktoren\nausgewählt (hier: jene mit dem höchsten Korrelationskoeffizienten), und danach\nwird kreuzvalidiert. Das ist ein Datenleck, weil die Testdaten bereits bei der\nAuswahl mitgewirkt haben.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalle_praed <- c(\"x1\", \"x2\", paste0(\"z\", 1:6))\n\n# --- FALSCH: Variablen auf ALLEN Daten waehlen, dann CV ---\nkorr_alle <- abs(cor(daten[, alle_praed], daten$y))\ntop3 <- names(sort(korr_alle[, 1], decreasing = TRUE))[1:3]\ncat(\"auf allen Daten gewaehlt:\", top3, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nauf allen Daten gewaehlt: x1 x2 z1 \n```\n\n\n:::\n\n```{.r .cell-code}\nformel_falsch <- as.formula(paste(\"y ~\", paste(top3, collapse = \" + \")))\nmse_falsch <- cv_manuell(formel_falsch, k = 10)\n\n# --- RICHTIG: Variablen INNERHALB jeder Falte waehlen ---\nk <- 10\nfalte <- (seq_len(n) - 1) %% k\nfehler_richtig <- sapply(0:(k - 1), function(f) {\n  test <- falte == f\n  train <- daten[!test, ]\n  korr_train <- abs(cor(train[, alle_praed], train$y))\n  top3_train <- names(sort(korr_train[, 1], decreasing = TRUE))[1:3]\n  formel <- as.formula(paste(\"y ~\", paste(top3_train, collapse = \" + \")))\n  modell <- lm(formel, data = train)\n  mean((daten$y[test] - predict(modell, daten[test, ]))^2)\n})\nmse_richtig <- mean(fehler_richtig)\n\n# --- Referenz: wahres Modell ---\nmse_wahr <- cv_manuell(y ~ x1 + x2, k = 10)\n\ncat(\"CV-MSE falsch (Leck):\", round(mse_falsch, 2),\n    \" RMSE:\", round(sqrt(mse_falsch), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCV-MSE falsch (Leck): 36.04  RMSE: 6 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"CV-MSE richtig:      \", round(mse_richtig, 2),\n    \" RMSE:\", round(sqrt(mse_richtig), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCV-MSE richtig:       35.6  RMSE: 5.97 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"CV-MSE wahres Modell:\", round(mse_wahr, 2),\n    \" RMSE:\", round(sqrt(mse_wahr), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCV-MSE wahres Modell: 35.19  RMSE: 5.93 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nalle_praed = [\"x1\", \"x2\"] + [f\"z{k}\" for k in range(1, 7)]\n\n# --- FALSCH: Variablen auf ALLEN Daten waehlen, dann CV ---\nkorr_alle = daten[alle_praed].corrwith(daten[\"y\"]).abs()\ntop3 = korr_alle.nlargest(3).index.tolist()\nprint(\"auf allen Daten gewaehlt:\", top3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nauf allen Daten gewaehlt: ['x1', 'x2', 'z1']\n```\n\n\n:::\n\n```{.python .cell-code}\nX_falsch = daten[top3].values\nscores_falsch = cross_val_score(LinearRegression(), X_falsch, y,\n                                cv=KFold(n_splits=10, shuffle=False),\n                                scoring=\"neg_mean_squared_error\")\nmse_falsch = -np.mean(scores_falsch)\n\n# --- RICHTIG: Variablen INNERHALB jeder Falte waehlen ---\nkf = KFold(n_splits=10, shuffle=False)\nfehler_richtig = []\nfor train_idx, test_idx in kf.split(X_falsch):\n    train = daten.iloc[train_idx]\n    test_daten = daten.iloc[test_idx]\n    korr_train = train[alle_praed].corrwith(train[\"y\"]).abs()\n    top3_train = korr_train.nlargest(3).index.tolist()\n    modell = LinearRegression().fit(train[top3_train].values, train[\"y\"].values)\n    vorhersage = modell.predict(test_daten[top3_train].values)\n    fehler_richtig.append(np.mean((test_daten[\"y\"].values - vorhersage) ** 2))\nmse_richtig = np.mean(fehler_richtig)\n\n# --- Referenz: wahres Modell ---\nscores_wahr = cross_val_score(LinearRegression(), daten[[\"x1\", \"x2\"]].values, y,\n                              cv=KFold(n_splits=10, shuffle=False),\n                              scoring=\"neg_mean_squared_error\")\nmse_wahr = -np.mean(scores_wahr)\n\nprint(f\"CV-MSE falsch (Leck): {mse_falsch:.2f}  RMSE: {np.sqrt(mse_falsch):.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCV-MSE falsch (Leck): 34.39  RMSE: 5.86\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"CV-MSE richtig:       {mse_richtig:.2f}  RMSE: {np.sqrt(mse_richtig):.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCV-MSE richtig:       34.39  RMSE: 5.86\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"CV-MSE wahres Modell: {mse_wahr:.2f}  RMSE: {np.sqrt(mse_wahr):.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCV-MSE wahres Modell: 34.97  RMSE: 5.91\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Variante | MSE | RMSE | Wie das zu lesen ist |\n|---|---|---|---|\n| Falsch (Leck) | deutlich zu tief | deutlich zu tief | Die Variablenselektion hat die Testdaten schon gesehen. Der Fehler ist zu optimistisch. |\n| Richtig (Selektion in der Falte) | höher | höher | Die ehrliche Schätzung. In manchen Falten werden andere Variablen gewählt, was den Fehler erhöht. |\n| Wahres Modell (`x1 + x2`) | ca. 35.7 | ca. 5.97 | Der Bezugswert. |\n\nDer Unterschied zwischen \"falsch\" und \"richtig\" zeigt die Grösse des Lecks.\nDie fehlerhafte Variante unterschätzt den Vorhersagefehler, weil sie\nInformation aus den Testdaten in die Variablenselektion einfliessen lässt.\n\n::: {.note-box}\n**Die Regel ist einfach und absolut:** Alles, was aus den Daten gelernt wird,\ngehört in die Kreuzvalidierungsschleife. Das betrifft nicht nur die\nVariablenselektion, sondern auch Zentrierung, Skalierung, Imputation fehlender\nWerte und jede andere datengetriebene Vorverarbeitung. Nur die Definition des\nModells (welche Art Modell, welche Hyperparameter) darf vorher feststehen.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Wird die Variablenselektion auf allen Daten durchgeführt und danach\n> kreuzvalidiert, unterschätzt der CV-Fehler die tatsächliche Vorhersagegüte\n> systematisch. Die korrekte Variante, bei der die Selektion innerhalb jeder\n> Falte stattfindet, liefert einen realistischeren und höheren Fehler. Diese\n> Demonstration zeigt, warum jede datengetriebene Vorverarbeitung in die\n> CV-Schleife gehört.\n\n### Beispiel 3: CV zur Modellwahl (Polynomgrade)\n\n#### Frage und Datenlage\n\nDas Modell `y ~ x1 + x2` ist linear. Würde ein Polynommodell mit höherem\nGrad besser vorhersagen? Die Kreuzvalidierung kann das direkt beantworten,\nindem sie den Vorhersagefehler für verschiedene Grade vergleicht. Das ist ein\ntypischer Anwendungsfall der CV zur Modellwahl, wie er auch bei\nRegularisierungsverfahren vorkommt.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell fig-label='fig-b3-cv-polynom'}\n\n```{.r .cell-code}\ngrade <- 1:6\n\ncv_poly <- function(grad, k = 10) {\n  formel <- as.formula(paste(\"y ~ poly(x1,\", grad, \") + poly(x2,\", grad, \")\"))\n  falte <- (seq_len(n) - 1) %% k\n  fehler <- sapply(0:(k - 1), function(f) {\n    test <- falte == f\n    modell <- lm(formel, data = daten[!test, ])\n    mean((daten$y[test] - predict(modell, daten[test, ]))^2)\n  })\n  c(mse = mean(fehler), sd = sd(fehler))\n}\n\nergebnisse <- t(sapply(grade, cv_poly))\nergebnisse <- data.frame(grad = grade, mse = ergebnisse[, 1],\n                         sd = ergebnisse[, 2],\n                         rmse = sqrt(ergebnisse[, 1]))\nround(ergebnisse, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  grad     mse      sd   rmse\n1    1 35.1933  2.7361 5.9324\n2    2 36.0070  2.9831 6.0006\n3    3 37.6523  3.7295 6.1361\n4    4 39.8018  6.3727 6.3089\n5    5 40.3563  7.0204 6.3527\n6    6 55.2294 39.3905 7.4316\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(grade, ergebnisse$rmse, type = \"b\", pch = 19,\n     xlab = \"Polynomgrad\", ylab = \"CV-RMSE (10-fach)\",\n     main = \"Kreuzvalidierung nach Polynomgrad\",\n     ylim = range(ergebnisse$rmse) * c(0.95, 1.1))\nabline(h = min(ergebnisse$rmse), lty = 2, col = \"grey50\")\n```\n\n::: {.cell-output-display}\n![CV-Fehler nach Polynomgrad: Das lineare Modell (Grad 1) gewinnt.](kreuzvalidierung_files/figure-html/b3-cv-rechnung-r-1.png){width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell fig-label='fig-b3-cv-polynom-py'}\n\n```{.python .cell-code}\nfrom sklearn.preprocessing import PolynomialFeatures\nfrom sklearn.pipeline import make_pipeline\n\ngrade = range(1, 7)\nergebnisse = []\n\nfor grad in grade:\n    pipe = make_pipeline(PolynomialFeatures(grad, include_bias=False),\n                         LinearRegression())\n    X_beide = daten[[\"x1\", \"x2\"]].values\n    scores = cross_val_score(pipe, X_beide, y,\n                             cv=KFold(n_splits=10, shuffle=False),\n                             scoring=\"neg_mean_squared_error\")\n    mse = -np.mean(scores)\n    ergebnisse.append({\"grad\": grad, \"mse\": mse,\n                       \"sd\": np.std(-scores), \"rmse\": np.sqrt(mse)})\n\nerg = pd.DataFrame(ergebnisse)\nprint(erg.round(4).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n grad       mse        sd    rmse\n    1   34.9726    4.1959  5.9138\n    2   34.7543    3.1789  5.8953\n    3   36.4667    5.2366  6.0388\n    4   54.8896   48.5784  7.4087\n    5 1067.1062 2913.7960 32.6666\n    6 2600.7716 5532.1400 50.9978\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, ax = plt.subplots(figsize=(6, 4))\nax.plot(erg[\"grad\"], erg[\"rmse\"], \"o-\", color=\"steelblue\")\nax.axhline(erg[\"rmse\"].min(), linestyle=\"--\", color=\"grey\", alpha=0.6)\nax.set_xlabel(\"Polynomgrad\")\nax.set_ylabel(\"CV-RMSE (10-fach)\")\nax.set_title(\"Kreuzvalidierung nach Polynomgrad\")\n_x = plt.tight_layout()\n_x = plt.show()\n```\n\n::: {.cell-output-display}\n![CV-Fehler nach Polynomgrad: Das lineare Modell (Grad 1) gewinnt.](kreuzvalidierung_files/figure-html/b3-cv-rechnung-py-1.png){width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grad | CV-RMSE (10-fach) | Wie das zu lesen ist |\n|---|---|---|\n| 1 | ca. 5.97 | Das lineare Modell, das der Wahrheit entspricht. |\n| 2 | leicht höher | Quadratische Terme bringen nichts, da der wahre Zusammenhang linear ist. |\n| 3-6 | steigend | Mehr Flexibilität verschlechtert die Vorhersage; klassische Überanpassung. |\n\nDer CV-Fehler steigt ab Grad 2 monoton an. Das ist das erwartete Muster: Die\nwahre Beziehung ist linear, und zusätzliche Polynomterme passen sich dem\nRauschen an, ohne echte Struktur zu erfassen.\n\n::: {.note-box}\n**Kreuzvalidierung als Schutz vor Überanpassung.** Auf den Trainingsdaten sinkt\nder Fehler mit jedem zusätzlichen Polynomgrad. Erst die Kreuzvalidierung\ndeckt auf, dass die Verbesserung nicht auf neue Daten übertragbar ist. Das\nist genau der Unterschied zwischen Trainings- und Generalisierungsfehler.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Eine 10-fache Kreuzvalidierung über Polynomgrade 1 bis 6 zeigt, dass das\n> lineare Modell (Grad 1) den kleinsten CV-RMSE hat. Höhere Grade\n> verschlechtern die Vorhersage monoton. Die Kreuzvalidierung bestätigt damit\n> die bekannte lineare Struktur und schützt vor Überanpassung durch\n> unnötige Flexibilität.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nLOOCV nutzt $n - 1$ Beobachtungen zum Training. Warum hat sie trotzdem eine\nhöhere Varianz als 10-fache CV?\n\n- [x] Weil die $n$ Trainingsmengen fast identisch sind und die Fehlerschätzungen\n      deshalb stark korreliert sind ~ Richtig. Die hohe Überlappung der\n      Trainingsmengen führt zu korrelierten Fehlern, deren Durchschnitt weniger\n      streut, als man bei $n$ unabhängigen Werten erwarten würde. Die Varianz\n      des Gesamtschätzers bleibt hoch.\n- [ ] Weil nur ein Fall zum Testen verwendet wird ~ Ein einzelner Testfall hat\n      zwar eine hohe Varianz, aber der Durchschnitt über $n$ Testfälle gleicht\n      das aus. Das Problem liegt an der Korrelation, nicht an der Einzelfallgrösse.\n- [ ] Weil LOOCV mehr Rechenzeit braucht ~ Rechenzeit und statistische Varianz\n      haben nichts miteinander zu tun.\n:::\n\n::: {.quiz}\n`cross_val_score` in sklearn liefert `[-35.2, -38.1, -33.9, ...]`. Was bedeuten\ndie negativen Werte?\n\n- [x] sklearn negiert den MSE, weil es Scores maximiert; der MSE ist\n      `np.mean(-scores)` ~ Richtig. sklearn verwendet einheitlich das Prinzip\n      \"höher ist besser\". Da MSE ein Fehler ist (kleiner ist besser), wird er\n      negiert.\n- [ ] Die Modelle sind schlecht, deshalb negative Scores ~ Auch bei guten\n      Modellen sind die Scores negativ, wenn `neg_mean_squared_error` verwendet\n      wird.\n- [ ] Ein Vorzeichenfehler in den Daten ~ Die Konvention ist so dokumentiert und\n      gewollt.\n:::\n\n::: {.quiz}\nEin Kollege wählt auf allen 150 Beobachtungen die drei besten Prädiktoren nach\nKorrelation aus und macht anschliessend eine 10-fache CV. Der CV-Fehler ist\nauffällig klein. Was ist schiefgelaufen?\n\n- [x] Datenleck: Die Variablenselektion hat die Testdaten schon benutzt ~ Richtig.\n      Die drei Variablen wurden anhand aller Daten ausgewählt, also auch anhand\n      der Testfälle in jeder Falte. Der CV-Fehler ist zu optimistisch.\n- [ ] 10 Falten sind zu wenig; mit LOOCV wäre es korrekt ~ Das Leck besteht\n      unabhängig von der Faltenzahl. Auch LOOCV wäre falsch, wenn die Selektion\n      vorher stattfindet.\n- [ ] Die Korrelation ist kein gutes Auswahlkriterium ~ Die Korrelation ist als\n      Kriterium akzeptabel; das Problem ist der Zeitpunkt der Auswahl, nicht das\n      Kriterium.\n:::\n\n::: {.quiz}\nFür eine Zeitreihe mit 200 Werten soll die Vorhersagegüte eines\nRegressionsmodells geschätzt werden. Welches CV-Verfahren passt?\n\n- [x] Vorwärtsvalidierung: Training auf Daten bis $t$, Test auf Daten nach $t$ ~\n      Richtig. Bei Zeitreihen ist die zeitliche Ordnung entscheidend. Zufällige\n      Splits zerstören sie und führen dazu, dass zukünftige Werte ins Training\n      gelangen.\n- [ ] 10-fache CV mit zufälligem Split ~ Falsch. Zufällige Splits ignorieren\n      die Autokorrelation und führen zu einem zu optimistischen Fehler.\n- [ ] LOOCV, weil sie jeden einzelnen Zeitpunkt prüft ~ LOOCV mit zufälligen\n      Splits hat dasselbe Problem. Die zeitliche Ordnung muss eingehalten werden.\n:::\n\n## Verlinkte Ressourcen\n\n- [An Introduction to Statistical Learning, Kapitel 5](https://www.statlearning.com/)\n- [Modellauswahl](modellauswahl.qmd) (AIC, BIC und schrittweise Auswahl)\n- [Bootstrap-Resampling](../inferenz/bootstrap-resampling.qmd)\n- [Regressionsdiagnostik](regressionsdiagnostik.qmd)\n- [R-Dokumentation zu `cv.glm`](https://stat.ethz.ch/R-manual/R-devel/library/boot/html/cv.glm.html)\n- [sklearn: Cross-validation](https://scikit-learn.org/stable/modules/cross_validation.html)\n",
    "supporting": [
      "kreuzvalidierung_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}