{
  "hash": "e4aff59d7423c3690194e5bd655deb5c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Bayessche Inferenz\"\ndescription: \"Prior, Likelihood und Posterior: Glaubwürdigkeitsintervalle, der Einfluss des Priors und Wahrscheinlichkeiten für Hypothesen.\"\ncategories: [\"Bayes\", \"Schätzen\", \"A/B-Testing\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: methode\nstand: fertig\norder: 80\n---\n\n\n\n\n\nAlle Beispiele rechnen exakt mit Beta-Verteilungen, ohne Simulation. R und\nPython geben deshalb dieselben Zahlen aus.\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Wie plausibel ist ein Parameterwert, gegeben die Daten und das Vorwissen? |\n| Ergebnis | eine ganze Verteilung für den Parameter, die Posterior |\n| Was die Methode liefert | Posterior-Mittel oder -Median, Glaubwürdigkeitsintervall, Wahrscheinlichkeiten wie P(Anteil > 10 %) |\n| R-Funktion | Beta-Binomial exakt mit `qbeta()`, `pbeta()`; allgemeine Modelle mit `brms` oder `rstanarm` |\n| Python-Funktion | `scipy.stats.beta`; allgemeine Modelle mit `PyMC` |\n| Verwandte Methoden | [Schätzen und Konfidenzintervalle](schaetzen-konfidenzintervalle.qmd), [bedingte Wahrscheinlichkeit und Bayes](../wahrscheinlichkeit/bedingte-wahrscheinlichkeit-bayes.qmd), [Hypothesentests: Grundlagen](hypothesentests-grundlagen.qmd) |\n\n## Wann diese Methode, wann nicht\n\nBayessche Inferenz beantwortet die Frage, die viele eigentlich stellen, wenn\nsie einen p-Wert berechnen: Wie wahrscheinlich ist es, dass der Effekt positiv\nist? Das kann ein frequentistisches Verfahren nicht, weil dort der Parameter fest\nist und nur die Daten zufällig sind.\n\nSie lohnt sich besonders, wenn Vorwissen vorhanden ist und genutzt werden soll,\nwenn Entscheidungen direkt an Wahrscheinlichkeiten hängen („Variante B ist mit\n96 Prozent besser\"), und wenn wenige Daten vorliegen, sodass ein vernünftiger\nPrior die Schätzung stabilisiert.\n\n| Situation | Stattdessen oder zusätzlich |\n|---|---|\n| Vorwissen soll ausdrücklich keine Rolle spielen, Regulierung verlangt Fehlerraten | [frequentistische Tests](hypothesentests-grundlagen.qmd) mit festgelegtem Niveau |\n| Das Modell ist komplex (Regression, gemischte Modelle) | dieselbe Logik mit `brms` oder `PyMC`, gerechnet per MCMC |\n| Nur eine Punktschätzung mit Intervall ist gefragt, viele Daten | [Konfidenzintervall](schaetzen-konfidenzintervalle.qmd); bei flachem Prior fast dieselben Zahlen |\n\n## Grundidee und Modell\n\nDer Satz von Bayes auf einen Parameter $\\theta$ angewandt:\n\n$$\\underbrace{p(\\theta \\mid \\text{Daten})}_{\\text{Posterior}} \\;\\propto\\; \\underbrace{p(\\text{Daten} \\mid \\theta)}_{\\text{Likelihood}} \\cdot \\underbrace{p(\\theta)}_{\\text{Prior}}$$\n\nFür einen Anteil (Konversionsrate, Fehlerquote) gibt es eine besonders\neinfache Form. Ist der Prior eine Beta-Verteilung und sind die Daten $k$\nErfolge in $n$ Versuchen, dann ist auch die Posterior eine Beta-Verteilung:\n\n$$\\text{Beta}(a, b) \\;\\xrightarrow{\\;k \\text{ von } n\\;}\\; \\text{Beta}(a + k,\\; b + n - k)$$\n\n| Bestandteil | Bedeutung |\n|---|---|\n| $a, b$ des Priors | Vorwissen, gelesen als $a$ frühere Erfolge und $b$ frühere Misserfolge |\n| $\\text{Beta}(1, 1)$ | flacher Prior: jeder Anteil zwischen 0 und 1 gleich plausibel |\n| Posterior-Mittel $a/(a+b)$ | Punktschätzung, liegt zwischen Prior-Mittel und beobachtetem Anteil |\n| 95-Prozent-Glaubwürdigkeitsintervall | Bereich, in dem der Parameter **mit 95 Prozent Wahrscheinlichkeit** liegt |\n\nGenau der letzte Satz ist der Unterschied zum\n[Konfidenzintervall](schaetzen-konfidenzintervalle.qmd), das eine Aussage über\ndas Verfahren macht, nicht über den Parameter.\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung | Vorgehen |\n|---|---|---|---|---|\n| Passendes Datenmodell | hier: unabhängige Versuche mit gleichem Anteil | Erhebungsdesign | Posterior zu schmal | hierarchisches Modell, Gruppen einbeziehen |\n| Prior vor den Daten festgelegt | kein Anpassen des Priors an das gewünschte Ergebnis | Dokumentation | Ergebnis beliebig | Prior begründen und vorab festhalten |\n| Prior-Sensitivität geprüft | Ergebnis hängt nicht nur am Prior | mit flachem und informativem Prior rechnen | Schlussfolgerung nicht belastbar | beide Ergebnisse berichten, Beispiel 2 |\n\n## Output lesen\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| Posterior-Mittel | Punktschätzung | bei schiefer Posterior lieber den Median berichten |\n| Glaubwürdigkeitsintervall | 2.5- und 97.5-Prozent-Quantil der Posterior | darf wörtlich als Wahrscheinlichkeitsaussage gelesen werden |\n| $P(\\theta > c)$ | Wahrscheinlichkeit, dass der Parameter eine Schwelle überschreitet | direkt entscheidungsrelevant, kein p-Wert |\n| $P(\\theta_B > \\theta_A)$ | Wahrscheinlichkeit, dass B besser ist als A | sagt nichts darüber, **wie viel** besser; dafür die Differenz ansehen |\n\n## Interpretationsfallen\n\n- **Der Prior ist keine Meinung, die man frei wählt**, sondern Teil des Modells.\n  Er gehört begründet und im Bericht genannt.\n- **Ein flacher Prior ist nicht „ohne Annahme\".** Er sagt, dass ein Anteil von\n  0.95 genauso plausibel ist wie 0.10. Für Konversionsraten ist das oft\n  unrealistisch.\n- **$P(B > A) = 0.96$ heisst nicht, dass B um viel besser ist.** Eine winzige,\n  aber sichere Differenz ergibt dieselbe Wahrscheinlichkeit.\n- **Bei vielen Daten verschwindet der Einfluss des Priors**, bei wenigen Daten\n  dominiert er. Beispiel 2 zeigt beides.\n- **Glaubwürdigkeits- und Konfidenzintervall liegen oft nah beieinander**, sie\n  bedeuten trotzdem Verschiedenes.\n\n## Ergebnis berichten\n\n> Mit einem [flachen / informativen, Beta(a, b)] Prior ergibt sich für\n> [Parameter] ein Posterior-Mittel von [Wert] (95-Prozent-Glaubwürdigkeitsintervall\n> [unten] bis [oben]). Die Wahrscheinlichkeit, dass [Parameter] [Schwelle]\n> überschreitet, beträgt [Wert].\n\nImmer genannt werden: Prior mit Begründung, Datenmodell, Posterior-Kennzahl\nmit Intervall und bei Entscheidungen die relevante Wahrscheinlichkeit.\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt der bayesschen Auswertung |\n|---|---|\n| [Schätzen und Konfidenzintervalle](schaetzen-konfidenzintervalle.qmd) | kein Vorwissen, Fehlerraten über viele Wiederholungen stehen im Vordergrund |\n| [Hypothesentests](hypothesentests-grundlagen.qmd) | Entscheidung mit festgelegter Irrtumswahrscheinlichkeit verlangt |\n| [Bootstrap](bootstrap-resampling.qmd) | Unsicherheit einer beliebigen Kennzahl ohne Verteilungsannahme |\n| [Bedingte Wahrscheinlichkeit und Bayes](../wahrscheinlichkeit/bedingte-wahrscheinlichkeit-bayes.qmd) | der Satz von Bayes für Ereignisse statt für Parameter |\n\n## Beispiele\n\nJedes Beispiel steht in einem eigenen Reiter.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Eine Konversionsrate\n\n#### Frage und Datenlage\n\nEine neue Landingpage wurde 120 Mal aufgerufen, 18 Besuche endeten mit einer\nAnmeldung. Wie hoch ist die Anmelderate, und wie wahrscheinlich liegt sie über\n10 Prozent, der Rate der alten Seite? Ausgegangen wird von einem flachen Prior.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk <- 18; n <- 120\nbeta_bericht(1 + k, 1 + n - k)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       a        b   mittel   median    unten     oben \n 19.0000 103.0000   0.1557   0.1539   0.0973   0.2249 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Wahrscheinlichkeit fuer eine Rate ueber 10 Prozent\nround(pbeta(0.10, 1 + k, 1 + n - k, lower.tail = FALSE), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9679\n```\n\n\n:::\n\n```{.r .cell-code}\n# zum Vergleich: beobachteter Anteil, Wald- und exaktes Konfidenzintervall\nanteil <- k / n\nwald <- anteil + c(-1, 1) * qnorm(0.975) * sqrt(anteil * (1 - anteil) / n)\nround(c(anteil = anteil, wald = wald, exakt = binom.test(k, n)$conf.int), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nanteil  wald1  wald2 exakt1 exakt2 \n0.1500 0.0861 0.2139 0.0914 0.2267 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom statsmodels.stats.proportion import proportion_confint\n\nk, n = 18, 120\nprint(beta_bericht(1 + k, 1 + n - k))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'a': 19, 'b': 103, 'mittel': 0.1557, 'median': 0.1539, 'unten': 0.0973, 'oben': 0.2249}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"P(Rate > 0.10):\", round(stats.beta(1 + k, 1 + n - k).sf(0.10), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nP(Rate > 0.10): 0.9679\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Anteil:\", round(k / n, 4),\n      \" Wald:\", np.round(proportion_confint(k, n, method=\"normal\"), 4),\n      \" exakt:\", np.round(proportion_confint(k, n, method=\"beta\"), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnteil: 0.15  Wald: [0.0861 0.2139]  exakt: [0.0914 0.2267]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| Posterior | Beta(19, 103) | flacher Prior plus 18 Erfolge und 102 Misserfolge | einfach zu rechnen, weil Beta und Binomial zusammenpassen |\n| `mittel` | 0.1557 | Posterior-Mittel | etwas über dem beobachteten Anteil von 0.15, weil der flache Prior wie ein zusätzlicher Erfolg und Misserfolg wirkt |\n| `median` | 0.1539 | Posterior-Median | liegt unter dem Mittel, die Posterior ist leicht rechtsschief |\n| `unten`, `oben` | 0.0973 bis 0.2249 | 95-Prozent-Glaubwürdigkeitsintervall | Mit 95 Prozent Wahrscheinlichkeit liegt die Rate in diesem Bereich, gegeben Daten und Prior. |\n| P(Rate > 0.10) | 0.9679 | Wahrscheinlichkeit, dass die neue Seite über der alten Rate liegt | direkt die Frage des Auftraggebers; kein p-Wert |\n| Wald-Intervall | 0.0861 bis 0.2139 | frequentistisch, Normalnäherung | symmetrisch um 0.15 und bei kleinen Anteilen zu schmal auf der unteren Seite |\n| exaktes Intervall | 0.0914 bis 0.2267 | frequentistisch, Clopper-Pearson | numerisch nah am Glaubwürdigkeitsintervall, aber anders zu lesen |\n\n#### Interpretation und Ergebnissatz\n\nDas Glaubwürdigkeitsintervall und das exakte Konfidenzintervall liegen fast\ngleich. Der Unterschied liegt nicht in den Zahlen, sondern darin, was man sagen\ndarf: Nur beim bayesschen Intervall ist „mit 95 Prozent Wahrscheinlichkeit\nliegt die Rate zwischen 9.7 und 22.5 Prozent\" korrekt.\n\n> Mit flachem Prior ergibt sich für die Anmelderate ein Posterior-Mittel von\n> 0.156 (95-Prozent-Glaubwürdigkeitsintervall 0.097 bis 0.225). Die\n> Wahrscheinlichkeit, dass die Rate über 10 Prozent liegt, beträgt 0.97.\n\n### Beispiel 2: Wie stark der Prior wirkt\n\n#### Frage und Datenlage\n\nAus früheren Kampagnen ist bekannt, dass Anmelderaten meist um 10 Prozent\nliegen. Das lässt sich als Prior Beta(20, 180) ausdrücken: Mittel 0.10, so viel\nGewicht wie 200 frühere Besuche. Wie verändert dieser Prior das Ergebnis, einmal\nbei wenigen Daten (4 von 20) und einmal bei vielen (180 von 1200)?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvergleich <- rbind(\n  flach_wenig = beta_bericht(1 + 4, 1 + 20 - 4),\n  info_wenig  = beta_bericht(20 + 4, 180 + 20 - 4),\n  flach_viel  = beta_bericht(1 + 180, 1 + 1200 - 180),\n  info_viel   = beta_bericht(20 + 180, 180 + 1200 - 180)\n)\nvergleich\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              a    b mittel median  unten   oben\nflach_wenig   5   17 0.2273 0.2189 0.0822 0.4191\ninfo_wenig   24  196 0.1091 0.1079 0.0715 0.1534\nflach_viel  181 1021 0.1506 0.1504 0.1309 0.1713\ninfo_viel   200 1200 0.1429 0.1427 0.1250 0.1617\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nvergleich = pd.DataFrame({\n    \"flach_wenig\": beta_bericht(1 + 4, 1 + 20 - 4),\n    \"info_wenig\": beta_bericht(20 + 4, 180 + 20 - 4),\n    \"flach_viel\": beta_bericht(1 + 180, 1 + 1200 - 180),\n    \"info_viel\": beta_bericht(20 + 180, 180 + 1200 - 180),\n}).T\nprint(vergleich)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 a       b  mittel  median   unten    oben\nflach_wenig    5.0    17.0  0.2273  0.2189  0.0822  0.4191\ninfo_wenig    24.0   196.0  0.1091  0.1079  0.0715  0.1534\nflach_viel   181.0  1021.0  0.1506  0.1504  0.1309  0.1713\ninfo_viel    200.0  1200.0  0.1429  0.1427  0.1250  0.1617\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Fall | beobachtet | Posterior-Mittel | 95-Prozent-Intervall | Wie es zu lesen ist |\n|---|---|---|---|---|\n| flach, 4 von 20 | 0.20 | 0.2273 | 0.0822 bis 0.4191 | sehr breit: zwanzig Besuche sagen wenig |\n| informativ, 4 von 20 | 0.20 | 0.1091 | 0.0715 bis 0.1534 | Der Prior mit dem Gewicht von 200 Besuchen überstimmt die 20 neuen. |\n| flach, 180 von 1200 | 0.15 | 0.1506 | 0.1309 bis 0.1713 | fast genau der beobachtete Anteil |\n| informativ, 180 von 1200 | 0.15 | 0.1429 | 0.1250 bis 0.1617 | Der Prior zieht nur noch leicht Richtung 0.10. |\n\n#### Interpretation und Ergebnissatz\n\nBei wenigen Daten entscheidet der Prior. Das ist gewollt, wenn das Vorwissen\ngut ist, und gefährlich, wenn die neue Seite tatsächlich anders funktioniert.\nBei vielen Daten liefern beide Priors nahezu dasselbe. Deshalb gehört eine\nSensitivitätsprüfung mit mindestens zwei Priors in jede Auswertung mit wenigen\nDaten.\n\n> Bei 4 Anmeldungen in 20 Besuchen hängt das Ergebnis stark am Prior\n> (Posterior-Mittel 0.227 mit flachem, 0.109 mit informativem Prior); eine\n> belastbare Aussage über die Rate ist mit diesen Daten nicht möglich.\n\n### Beispiel 3: Ist Variante B besser als A\n\n#### Frage und Datenlage\n\nIn einem Test sahen 120 Besuche die Variante A (18 Anmeldungen) und 125 die\nVariante B (30 Anmeldungen). Wie wahrscheinlich ist B besser als A?\n\nDie Wahrscheinlichkeit $P(p_B > p_A)$ lässt sich exakt als Integral rechnen:\nFür jeden möglichen Wert von $p_A$ wird die Wahrscheinlichkeit gewichtet, dass\n$p_B$ darüber liegt.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\naA <- 1 + 18; bA <- 1 + 120 - 18\naB <- 1 + 30; bB <- 1 + 125 - 30\n\nrbind(A = beta_bericht(aA, bA), B = beta_bericht(aB, bB))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   a   b mittel median  unten   oben\nA 19 103 0.1557 0.1539 0.0973 0.2249\nB 31  96 0.2441 0.2427 0.1737 0.3221\n```\n\n\n:::\n\n```{.r .cell-code}\nb_besser <- integrate(function(x) dbeta(x, aA, bA) *\n                        pbeta(x, aB, bB, lower.tail = FALSE), 0, 1)$value\nround(c(p_b_besser = b_besser,\n        differenz_mittel = aB / (aB + bB) - aA / (aA + bA)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      p_b_besser differenz_mittel \n          0.9610           0.0884 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\naA, bA = 1 + 18, 1 + 120 - 18\naB, bB = 1 + 30, 1 + 125 - 30\n\nprint(pd.DataFrame({\"A\": beta_bericht(aA, bA), \"B\": beta_bericht(aB, bB)}).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      a      b  mittel  median   unten    oben\nA  19.0  103.0  0.1557  0.1539  0.0973  0.2249\nB  31.0   96.0  0.2441  0.2427  0.1737  0.3221\n```\n\n\n:::\n\n```{.python .cell-code}\nb_besser, _ = integrate.quad(lambda x: stats.beta.pdf(x, aA, bA) * stats.beta.sf(x, aB, bB), 0, 1)\nprint(\"P(B besser):\", round(b_besser, 4),\n      \" Differenz der Mittel:\", round(aB / (aB + bB) - aA / (aA + bA), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nP(B besser): 0.961  Differenz der Mittel: 0.0884\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| Posterior A | Mittel 0.1557, 0.0973 bis 0.2249 | wie in Beispiel 1 | |\n| Posterior B | Mittel 0.2441, 0.1737 bis 0.3221 | 30 von 125 mit flachem Prior | Die Intervalle überlappen, das allein entscheidet nichts. |\n| P(B besser) | 0.961 | Wahrscheinlichkeit, dass B die höhere Rate hat | beantwortet die Frage direkt |\n| Differenz der Mittel | 0.0884 | erwarteter Vorsprung von B | rund neun Prozentpunkte; das ist die Grösse, an der die Entscheidung hängt |\n\n#### Interpretation und Ergebnissatz\n\nÜberlappende Intervalle heissen nicht, dass kein Unterschied besteht: Die\nWahrscheinlichkeit für B liegt trotzdem bei 96 Prozent. Ob sich der Wechsel\nlohnt, entscheidet aber die Grösse des Vorsprungs zusammen mit den Kosten, nicht\ndie Wahrscheinlichkeit allein.\n\n> Mit flachen Priors beträgt die Wahrscheinlichkeit, dass Variante B eine\n> höhere Anmelderate hat als A, 0.96; der erwartete Vorsprung liegt bei 8.8\n> Prozentpunkten (Posterior-Mittel 0.244 gegen 0.156).\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEin 95-Prozent-Glaubwürdigkeitsintervall reicht von 0.10 bis 0.22. Welche\nAussage ist korrekt?\n\n- [x] Gegeben Daten und Prior liegt der Anteil mit 95 Prozent Wahrscheinlichkeit\n      in diesem Bereich ~ Richtig. Genau diese Lesart ist beim bayesschen\n      Intervall erlaubt, beim Konfidenzintervall nicht.\n- [ ] Bei 100 Wiederholungen der Studie enthielten 95 Intervalle den wahren\n      Anteil ~ Das ist die Lesart des Konfidenzintervalls.\n- [ ] 95 Prozent der Daten liegen in diesem Bereich ~ Das Intervall beschreibt\n      den Parameter, nicht die Streuung der einzelnen Werte.\n:::\n\n::: {.quiz}\nMit 12 Beobachtungen und einem stark informativen Prior liegt das\nPosterior-Mittel fast genau beim Prior-Mittel. Was folgt daraus?\n\n- [x] Die Daten reichen nicht, um den Prior zu überstimmen; das Ergebnis muss\n      mit einem zweiten Prior geprüft werden ~ Richtig. Die Aussage stammt dann\n      vor allem aus dem Vorwissen, nicht aus der Messung.\n- [ ] Die Daten bestätigen das Vorwissen ~ Das lässt sich so nicht sagen; auch\n      abweichende Daten würden bei diesem Prior kaum etwas ändern.\n- [ ] Der Prior war falsch gewählt ~ Nicht zwingend; er ist nur so stark, dass\n      zwölf Beobachtungen wenig bewegen.\n:::\n\n::: {.quiz}\nEin A/B-Test ergibt P(B besser als A) = 0.99. Reicht das für die Entscheidung\nzugunsten von B?\n\n- [x] Nicht allein, es fehlt die Grösse des Vorsprungs ~ Richtig. Eine\n      Differenz von 0.1 Prozentpunkten kann bei vielen Daten mit 99 Prozent\n      Wahrscheinlichkeit positiv sein und trotzdem die Umstellung nicht wert.\n- [ ] Ja, 99 Prozent ist sicher genug ~ Sicher ist nur die Richtung, nicht dass\n      sich der Unterschied lohnt.\n- [ ] Nein, dafür braucht es einen p-Wert ~ Ein p-Wert beantwortet eine andere\n      Frage und ergänzt die Grösse des Effekts ebenso wenig.\n:::\n\n## Verlinkte Ressourcen\n\n- [Statistical Rethinking (Richard McElreath), Vorlesungen](https://github.com/rmcelreath/stat_rethinking_2024)\n- [Bayes Rules! An Introduction to Applied Bayesian Modeling](https://www.bayesrulesbook.com/)\n- [brms: Bayesian Regression Models using Stan](https://paulbuerkner.com/brms/)\n- [PyMC: Einführung](https://www.pymc.io/projects/docs/en/stable/learn.html)\n",
    "supporting": [
      "bayessche-inferenz_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}