{
  "hash": "8395f4aad329f936eb607771d99eb489",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"QQ-Plots\"\ndescription: \"Verteilungen grafisch vergleichen und typische Muster deuten.\"\ncategories: [\"Verteilungen\", \"Visualisierung\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"ESDS\"]\nseitentyp: konzept\nstand: fertig\norder: 70\n---\n\n\n\n\n\n## Kernideen\n\n- Der QQ-Plot vergleicht **beobachtete** Quantile mit **theoretischen**.\n- Punkte auf der Geraden bedeuten Übereinstimmung mit der Referenzverteilung.\n- Er zeigt die **Art** der Abweichung; ein Test nur ihr Vorhandensein.\n- Die vier Muster: Krümmung heisst Schiefe, S-Form heisst schwere oder leichte\n  Ränder.\n- Abweichungen an den Enden sind bei kleinen Stichproben normal.\n- Bei grossem $n$ schlägt jeder Normalitätstest an, der Plot bleibt lesbar.\n- Die Referenzverteilung muss nicht die Normalverteilung sein.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Lage- und Streuungsmasse](../grundlagen/lage-streuungsmasse.qmd)\nfür Quantile, denn der QQ-Plot besteht aus nichts anderem, und die\n[Normalverteilung](normalverteilung-zgws.qmd) als übliche Referenz. Die\nzugehörigen Tests stehen unter\n[Normalitätstests](../tests/normalitaetstests.qmd).\n:::\n\n### Wie ein QQ-Plot entsteht\n\nOb eine Verteilungsannahme passt, lässt sich am Histogramm nur grob beurteilen,\nweil dessen Aussehen von der Klassenzahl abhängt. Der QQ-Plot ist präziser und\nentsteht in drei Schritten:\n\n1. Die $n$ Beobachtungen **sortieren**. Der kleinste Wert ist das empirische\n   $\\tfrac{0.5}{n}$-Quantil, der zweitkleinste das $\\tfrac{1.5}{n}$-Quantil und\n   so weiter.\n2. Zu jeder dieser Positionen das **theoretische** Quantil der Referenzverteilung\n   berechnen.\n3. Beides gegeneinander auftragen.\n\nPasst die Annahme, liegen die Punkte auf einer Geraden — und zwar auf der mit\nSteigung $\\sigma$ und Achsenabschnitt $\\mu$. **Die Gerade wird nicht angepasst,\nsie folgt aus den Daten.**\n\n::: {.note-box}\n**Warum $\\tfrac{i - 0.5}{n}$ und nicht $\\tfrac{i}{n}$?** Weil sonst der grösste\nWert das 100-Prozent-Quantil wäre, und das ist bei einer unbegrenzten Verteilung\nunendlich. Es gibt mehrere gebräuchliche Korrekturen; R verwendet bei kleinen\nStichproben $\\tfrac{i - 3/8}{n + 1/4}$, `scipy` dieselbe Formel. Die Unterschiede\nsind in der Mitte unsichtbar und an den Rändern klein.\n:::\n\n### Die vier Muster\n\n| Bild | Bedeutung | Was in den Daten steckt |\n|---|---|---|\n| Punkte **auf** der Geraden | Annahme passt | |\n| durchgehende **Krümmung nach oben** (links unter, rechts über der Linie in einem Bogen) | **rechtsschief** | ein langer Rand nach rechts |\n| durchgehende **Krümmung nach unten** | **linksschief** | ein langer Rand nach links |\n| **S-Form**: links unter, rechts über der Geraden | **schwerere Ränder** | mehr extreme Werte als erwartet |\n| **umgekehrte S-Form**: links über, rechts unter | **leichtere Ränder** | weniger extreme Werte, etwa bei begrenzten Skalen |\n\nDer Unterschied zwischen Krümmung und S-Form ist der entscheidende: Eine\nKrümmung geht **in eine Richtung**, eine S-Form knickt an **beiden** Enden in\nentgegengesetzte Richtungen ab.\n\n### QQ-Plot oder Test?\n\n| | QQ-Plot | Normalitätstest |\n|---|---|---|\n| Sagt | **wie** abgewichen wird | **ob** abgewichen wird |\n| Bei kleinem $n$ | schwer zu lesen | findet fast nichts |\n| Bei grossem $n$ | bleibt lesbar | schlägt immer an |\n| Braucht | ein Urteil | eine Schwelle |\n\nDie praktische Empfehlung ist eindeutig: **Der Plot entscheidet, der Test\nergänzt.** Der Grund steht in Beispiel 4.\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Ein QQ-Plot von Hand\n\n#### Frage und Datenlage\n\nZehn Messwerte. Der QQ-Plot wird Schritt für Schritt gebaut, damit klar wird,\nwas auf den Achsen steht.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- round(qnorm(lehmer(1122, 10), mean = 20, sd = 4), 1)\nsortiert <- sort(x)\n\nn <- length(x)\nposition <- (seq_len(n) - 0.5) / n      # empirische Quantilstufen\ntheoretisch <- qnorm(position)          # theoretische Quantile\n\nround(data.frame(rang = seq_len(n), wert = sortiert,\n                 position = round(position, 4),\n                 theoretisch = round(theoretisch, 4)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   rang wert position theoretisch\n1     1 10.5     0.05     -1.6449\n2     2 16.2     0.15     -1.0364\n3     3 20.9     0.25     -0.6745\n4     4 21.1     0.35     -0.3853\n5     5 21.8     0.45     -0.1257\n6     6 21.9     0.55      0.1257\n7     7 22.4     0.65      0.3853\n8     8 22.9     0.75      0.6745\n9     9 23.1     0.85      1.0364\n10   10 23.2     0.95      1.6449\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nplot(theoretisch, sortiert, pch = 16, main = \"von Hand\",\n     xlab = \"theoretisches Quantil\", ylab = \"beobachteter Wert\")\nabline(a = mean(x), b = sd(x), lwd = 2)\nqqnorm(x, pch = 16, main = \"qqnorm()\")\nqqline(x, lwd = 2)\npar(mfrow = c(1, 1))\n\nround(c(mittel = mean(x), sd = sd(x),\n        steigung_der_geraden = coef(lm(sortiert ~ theoretisch))[2]), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                          mittel                               sd \n                          20.400                            4.027 \nsteigung_der_geraden.theoretisch \n                           3.399 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 1: links der selbst gebaute QQ-Plot, rechts der von qqnorm().](qq-plots_files/figure-html/fig-b1-qq-r-1.png){#fig-b1-qq-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nx = np.round(stats.norm.ppf(lehmer(1122, 10), loc=20, scale=4), 1)\nsortiert = np.sort(x)\n\nn = len(x)\nposition = (np.arange(1, n + 1) - 0.5) / n\ntheoretisch = stats.norm.ppf(position)\n\nprint(pd.DataFrame({\"rang\": np.arange(1, n + 1), \"wert\": sortiert,\n                    \"position\": position.round(4),\n                    \"theoretisch\": theoretisch.round(4)}).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n rang  wert  position  theoretisch\n    1  10.5      0.05      -1.6449\n    2  16.2      0.15      -1.0364\n    3  20.9      0.25      -0.6745\n    4  21.1      0.35      -0.3853\n    5  21.8      0.45      -0.1257\n    6  21.9      0.55       0.1257\n    7  22.4      0.65       0.3853\n    8  22.9      0.75       0.6745\n    9  23.1      0.85       1.0364\n   10  23.2      0.95       1.6449\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nachsen[0].scatter(theoretisch, sortiert, color=\"black\")\ngitter = np.array([theoretisch.min(), theoretisch.max()])\nachsen[0].plot(gitter, x.mean() + x.std(ddof=1) * gitter, lw=2, color=\"black\")\nachsen[0].set_title(\"von Hand\")\nachsen[0].set_xlabel(\"theoretisches Quantil\")\nachsen[0].set_ylabel(\"beobachteter Wert\")\n_ = stats.probplot(x, dist=\"norm\", plot=achsen[1])\nachsen[1].set_title(\"probplot()\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nText(0.5, 1.0, 'probplot()')\n```\n\n\n:::\n\n```{.python .cell-code}\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: derselbe Aufbau in Python.](qq-plots_files/figure-html/fig-b1-qq-py-1.png){#fig-b1-qq-py width=100%}\n:::\n\n```{.python .cell-code}\nsteigung, achsenabschnitt = np.polyfit(theoretisch, sortiert, 1)\nprint({\"mittel\": round(float(x.mean()), 3),\n       \"sd\": round(float(x.std(ddof=1)), 3),\n       \"steigung_der_geraden\": round(float(steigung), 3)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'mittel': 20.4, 'sd': 4.027, 'steigung_der_geraden': 3.399}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Rang | beobachteter Wert | Position $\\tfrac{i-0.5}{10}$ | theoretisches Quantil |\n|---|---|---|---|\n| 1 | 10.5 | 0.05 | **-1.6449** |\n| 2 | 16.2 | 0.15 | -1.0364 |\n| 3 | 20.9 | 0.25 | -0.6745 |\n| 4 | 21.1 | 0.35 | -0.3853 |\n| 5 | 21.8 | 0.45 | -0.1257 |\n| 6 | 21.9 | 0.55 | 0.1257 |\n| 7 | 22.4 | 0.65 | 0.3853 |\n| 8 | 22.9 | 0.75 | 0.6745 |\n| 9 | 23.1 | 0.85 | 1.0364 |\n| 10 | 23.2 | 0.95 | **1.6449** |\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Die **Position** ist der Rang, auf 0 bis 1 umgerechnet | 0.05 bis 0.95 | Der kleinste von zehn Werten steht für das 5-Prozent-Quantil, nicht für das 10-Prozent-Quantil und nicht für das Minimum. |\n| Das **theoretische Quantil** ist $\\Phi^{-1}(\\text{Position})$ | -1.645 bis +1.645 | Bei der Standardnormalverteilung. Die Werte sind symmetrisch, weil die Positionen es sind. |\n| Die **Steigung** der Geraden | 3.399 | Ungefähr die Standardabweichung der Daten (4.027). Dass sie kleiner ausfällt, liegt an den beiden tiefen Werten links. |\n| Der **Achsenabschnitt** | 20.4 | Genau der Mittelwert. |\n| Die beiden linken Punkte liegen **unter** der Geraden | 10.5 und 16.2 | Bei zehn Beobachtungen ist das nicht deutbar — Beispiel 3 zeigt, wie stark die Ränder streuen. |\n\n::: {.note-box}\n**Was der QQ-Plot dem Histogramm voraushat:** Er braucht keine Klassenzahl. Ein\nHistogramm derselben zehn Werte sähe je nach Klassenbreite völlig verschieden\naus; die zehn Punkte hier sind eindeutig bestimmt.\n\n**Und was er ihm nicht voraushat:** Er zeigt die Verteilung nicht direkt. Wer\nsehen will, ob es zwei Gipfel gibt, braucht das Histogramm — im QQ-Plot äussert\nsich Zweigipfligkeit als schwer erkennbare Stufe.\n:::\n\n#### Interpretation\n\nDie zehn Punkte liegen ungefähr auf einer Geraden. Bei $n = 10$ ist das aber\nkaum mehr als die Feststellung, dass nichts offensichtlich Falsches vorliegt.\n\n### Beispiel 2: Die vier Muster\n\n#### Frage und Datenlage\n\nFünf Stichproben zu je 200 Werten, alle aus demselben Strom gleichverteilter\nZufallszahlen über die jeweilige Quantilfunktion erzeugt: normal,\nrechtsschief, linksschief, mit schweren Rändern (t-Verteilung mit 3\nFreiheitsgraden) und mit leichten Rändern (Gleichverteilung).\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\narten <- c(\"normal\", \"rechtsschief\", \"linksschief\",\n           \"schwere_raender\", \"leichte_raender\")\n\npar(mfrow = c(2, 3), mar = c(4, 4, 3, 1))\nfor (art in arten) {\n  d <- stichprobe(2233, art)\n  qqnorm(d, pch = 16, cex = 0.5, main = art)\n  qqline(d, lwd = 2)\n}\nplot.new()\npar(mfrow = c(1, 1))\n\nschiefe <- function(x) {\n  z <- (x - mean(x)) / sqrt(mean((x - mean(x))^2))\n  mean(z^3)\n}\nwoelbung <- function(x) {\n  z <- (x - mean(x)) / sqrt(mean((x - mean(x))^2))\n  mean(z^4) - 3\n}\n\nfor (art in arten) {\n  d <- stichprobe(2233, art)\n  cat(sprintf(\"%-16s Schiefe %+.3f | Wölbung %+.3f | Shapiro-Wilk p %.2e\\n\",\n              art, schiefe(d), woelbung(d), shapiro.test(d)$p.value))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnormal           Schiefe +0.073 | Wölbung -0.439 | Shapiro-Wilk p 3.16e-01\nrechtsschief     Schiefe +1.363 | Wölbung +1.529 | Shapiro-Wilk p 5.96e-13\nlinksschief      Schiefe -1.363 | Wölbung +1.529 | Shapiro-Wilk p 5.96e-13\nschwere_raender  Schiefe +0.832 | Wölbung +4.206 | Shapiro-Wilk p 7.18e-07\nleichte_raender  Schiefe -0.038 | Wölbung -1.347 | Shapiro-Wilk p 1.20e-07\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 2: fünf Muster im QQ-Plot gegen die Normalverteilung.](qq-plots_files/figure-html/fig-b2-qq-r-3.png){#fig-b2-qq-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\narten = [\"normal\", \"rechtsschief\", \"linksschief\",\n         \"schwere_raender\", \"leichte_raender\"]\n\nfig, achsen = plt.subplots(2, 3, figsize=(7, 5))\nfor achse, art in zip(achsen.ravel(), arten):\n    _ = stats.probplot(stichprobe(2233, art), dist=\"norm\", plot=achse)\n    achse.set_title(art, fontsize=9)\n    achse.get_lines()[0].set_markersize(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nText(0.5, 1.0, 'normal')\nText(0.5, 1.0, 'rechtsschief')\nText(0.5, 1.0, 'linksschief')\nText(0.5, 1.0, 'schwere_raender')\nText(0.5, 1.0, 'leichte_raender')\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen.ravel()[-1].axis(\"off\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(1.0))\n```\n\n\n:::\n\n```{.python .cell-code}\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselben fünf Muster in Python.](qq-plots_files/figure-html/fig-b2-qq-py-1.png){#fig-b2-qq-py width=100%}\n:::\n\n```{.python .cell-code}\nfor art in arten:\n    d = stichprobe(2233, art)\n    print(f\"{art:16s} Schiefe {stats.skew(d):+.3f}\"\n          f\" | Wölbung {stats.kurtosis(d):+.3f}\"\n          f\" | Shapiro-Wilk p {stats.shapiro(d).pvalue:.2e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnormal           Schiefe +0.073 | Wölbung -0.439 | Shapiro-Wilk p 3.16e-01\nrechtsschief     Schiefe +1.363 | Wölbung +1.529 | Shapiro-Wilk p 5.96e-13\nlinksschief      Schiefe -1.363 | Wölbung +1.529 | Shapiro-Wilk p 5.96e-13\nschwere_raender  Schiefe +0.832 | Wölbung +4.206 | Shapiro-Wilk p 7.18e-07\nleichte_raender  Schiefe -0.038 | Wölbung -1.347 | Shapiro-Wilk p 1.20e-07\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Stichprobe | Schiefe | Wölbung | Shapiro-Wilk p | Muster im Plot |\n|---|---|---|---|---|\n| **normal** | +0.073 | -0.439 | **0.316** | Punkte auf der Geraden |\n| **rechtsschief** | **+1.363** | +1.529 | 6·10⁻¹³ | Bogen nach oben |\n| **linksschief** | **-1.363** | +1.529 | 6·10⁻¹³ | Bogen nach unten |\n| **schwere Ränder** | +0.832 | **+4.206** | 7·10⁻⁷ | S-Form, beide Enden weg von der Geraden |\n| **leichte Ränder** | -0.038 | **-1.347** | 1·10⁻⁷ | umgekehrte S-Form, beide Enden zur Geraden hin |\n\n| Beobachtung | Erklärung |\n|---|---|\n| **Schiefe** unterscheidet die beiden Bögen | +1.363 gegen -1.363, exakt gespiegelt — die linksschiefe Stichprobe ist die rechtsschiefe mit umgekehrtem Vorzeichen. |\n| **Wölbung** unterscheidet die beiden S-Formen | +4.21 gegen -1.35. Positive Wölbung heisst schwerere Ränder als die Normalverteilung, negative leichtere. Die Normalverteilung hat definitionsgemäss die Wölbung 0. |\n| Die **leichten Ränder** sind die Gleichverteilung | Sie hat gar keine Ränder — bei 25 und 75 ist Schluss. Im QQ-Plot äussert sich das darin, dass die äussersten Punkte **weniger** extrem sind, als die Normalverteilung erwarten liesse. |\n| Der **Test** unterscheidet nichts davon | Vier p-Werte zwischen 10⁻⁷ und 10⁻¹³ — alle \"hochsignifikant nicht normal\", ohne dass daraus hervorginge, **was** los ist. |\n\n::: {.note-box}\n**Warum die Art der Abweichung wichtiger ist als ihr Vorhandensein:**\n\n| Abweichung | Praktische Folge | Was hilft |\n|---|---|---|\n| **Schiefe** | Mittelwert ist nicht mehr der typische Wert; symmetrische Intervalle passen nicht | Transformation (Logarithmus), oder Median und Rangverfahren |\n| **schwere Ränder** | mehr Ausreisser als erwartet; Mittelwert und Standardabweichung werden instabil | robuste Verfahren, getrimmte Mittelwerte |\n| **leichte Ränder** | meist harmlos; Tests werden eher konservativ | nichts |\n\nEin Test, der nur \"nicht normal\" meldet, führt zu keiner dieser drei\nEntscheidungen. Der Plot schon.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Stichprobe zeigt im QQ-Plot einen durchgehenden Bogen nach oben und eine\n> Schiefe von +1.36. Die Abweichung von der Normalverteilung ist eine\n> Rechtsschiefe; vor weiteren Auswertungen wird eine Logarithmierung geprüft.\n\n### Beispiel 3: Wie viel Streuung ist normal?\n\n#### Frage und Datenlage\n\nDie häufigste Fehldeutung: Punkte, die an den Enden von der Geraden abweichen,\nwerden für einen Befund gehalten. Sechs Stichproben aus **derselben**\nNormalverteilung — dreimal mit $n = 20$, dreimal mit $n = 200$.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 3), mar = c(4, 4, 3, 1))\nfor (n in c(20, 200)) {\n  for (k in 1:3) {\n    d <- qnorm(lehmer(5000 + 10 * k + n, n))\n    qqnorm(d, pch = 16, cex = 0.6, main = paste(\"n =\", n))\n    qqline(d, lwd = 2)\n  }\n}\npar(mfrow = c(1, 1))\n\nfor (n in c(20, 200)) {\n  for (k in 1:3) {\n    d <- qnorm(lehmer(5000 + 10 * k + n, n))\n    cat(sprintf(\"n = %3d, Stichprobe %d | Schiefe %+.3f | Shapiro-Wilk p %.3f\\n\",\n                n, k, schiefe(d), shapiro.test(d)$p.value))\n  }\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn =  20, Stichprobe 1 | Schiefe -1.068 | Shapiro-Wilk p 0.011\nn =  20, Stichprobe 2 | Schiefe -0.289 | Shapiro-Wilk p 0.640\nn =  20, Stichprobe 3 | Schiefe +0.494 | Shapiro-Wilk p 0.525\nn = 200, Stichprobe 1 | Schiefe +0.086 | Shapiro-Wilk p 0.279\nn = 200, Stichprobe 2 | Schiefe +0.287 | Shapiro-Wilk p 0.199\nn = 200, Stichprobe 3 | Schiefe +0.093 | Shapiro-Wilk p 0.174\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: sechsmal dieselbe Normalverteilung. Oben n = 20, unten n = 200.](qq-plots_files/figure-html/fig-b3-qq-r-3.png){#fig-b3-qq-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(2, 3, figsize=(7, 4.6))\nfor zeile, n in enumerate([20, 200]):\n    for k in range(1, 4):\n        d = stats.norm.ppf(lehmer(5000 + 10 * k + n, n))\n        _ = stats.probplot(d, dist=\"norm\", plot=achsen[zeile, k - 1])\n        achsen[zeile, k - 1].set_title(f\"n = {n}\", fontsize=9)\n        achsen[zeile, k - 1].get_lines()[0].set_markersize(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nText(0.5, 1.0, 'n = 20')\nText(0.5, 1.0, 'n = 20')\nText(0.5, 1.0, 'n = 20')\nText(0.5, 1.0, 'n = 200')\nText(0.5, 1.0, 'n = 200')\nText(0.5, 1.0, 'n = 200')\n```\n\n\n:::\n\n```{.python .cell-code}\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselben sechs Stichproben in Python.](qq-plots_files/figure-html/fig-b3-qq-py-1.png){#fig-b3-qq-py width=100%}\n:::\n\n```{.python .cell-code}\nfor n in [20, 200]:\n    for k in range(1, 4):\n        d = stats.norm.ppf(lehmer(5000 + 10 * k + n, n))\n        print(f\"n = {n:3d}, Stichprobe {k} | Schiefe {stats.skew(d):+.3f}\"\n              f\" | Shapiro-Wilk p {stats.shapiro(d).pvalue:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn =  20, Stichprobe 1 | Schiefe -1.068 | Shapiro-Wilk p 0.011\nn =  20, Stichprobe 2 | Schiefe -0.289 | Shapiro-Wilk p 0.640\nn =  20, Stichprobe 3 | Schiefe +0.494 | Shapiro-Wilk p 0.525\nn = 200, Stichprobe 1 | Schiefe +0.086 | Shapiro-Wilk p 0.279\nn = 200, Stichprobe 2 | Schiefe +0.287 | Shapiro-Wilk p 0.199\nn = 200, Stichprobe 3 | Schiefe +0.093 | Shapiro-Wilk p 0.174\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| n | Stichprobe | Schiefe | Shapiro-Wilk p |\n|---|---|---|---|\n| 20 | 1 | **-1.068** | **0.011** |\n| 20 | 2 | -0.289 | 0.640 |\n| 20 | 3 | +0.494 | 0.525 |\n| 200 | 1 | +0.086 | 0.279 |\n| 200 | 2 | +0.287 | 0.199 |\n| 200 | 3 | +0.093 | 0.174 |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Alle sechs Stichproben stammen aus **exakt derselben** Normalverteilung | Jede Abweichung von der Geraden ist damit definitionsgemäss Zufall. |\n| Bei $n = 20$ schwankt die Schiefe zwischen **-1.07 und +0.49** | In jeder der drei Stichproben anders. Wer eine davon einzeln sähe, könnte \"linksschief\" oder \"schwere Ränder\" hineinlesen. |\n| Bei $n = 200$ liegt sie zwischen **+0.09 und +0.29** | Deutlich enger, und die Punkte liegen im Bild näher an der Geraden — am weitesten entfernt noch immer an den Enden. |\n| Die erste Stichprobe bei $n = 20$ hat **p = 0.011** | Ein **Fehlalarm**: Der Test verwirft die Normalverteilung, obwohl die Daten aus ihr stammen. Genau das ist der Fehler erster Art, und bei einem Niveau von 5 Prozent passiert er bei einer von zwanzig Stichproben. Hier bei einer von sechs — auch das ist Zufall. |\n| Die übrigen fünf p-Werte liegen zwischen 0.17 und 0.64 | Unauffällig, wie zu erwarten. |\n\n::: {.note-box}\n**Warum die Ränder immer stärker streuen**, ist eine einfache Rechnung: Der\ngrösste von $n$ Werten hat eine Verteilung, deren Streuung mit $n$ **wächst** —\ner kann beliebig weit hinausrutschen. Der Median dagegen wird mit wachsendem $n$\nimmer genauer bestimmt.\n\nDeshalb sind die Punkte in der Mitte eines QQ-Plots verlässlich und die an den\nEnden nicht. Manche Umsetzungen zeichnen deshalb ein **Konfidenzband** ein — in R\netwa `car::qqPlot()`, das die Punktweise-Streuung berücksichtigt. Wo es fehlt,\nmuss man es im Kopf haben.\n\n**Die praktische Faustregel:** Unter etwa 30 Beobachtungen ist ein QQ-Plot nur\nfür grobe Befunde brauchbar. Was dort wie eine Abweichung aussieht, ist meist\nkeine.\n:::\n\n#### Interpretation\n\nEin QQ-Plot wird nicht Punkt für Punkt gelesen, sondern auf ein **durchgehendes\nMuster** hin. Ein einzelner Ausreisser am Rand ist keins — und ein einzelner\np-Wert unter 0.05 auch nicht, wie die erste Stichprobe zeigt.\n\n### Beispiel 4: Wenn der Test anschlägt und der Plot gerade bleibt\n\n#### Frage und Datenlage\n\nEine Verteilung, die von der Normalverteilung **praktisch bedeutungslos**\nabweicht: eine log-normale mit $\\sigma = 0.15$, also eine Schiefe von rund 0.45.\nGetestet bei wachsender Stichprobengrösse.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleicht_schief <- function(n) exp(0.15 * qnorm(lehmer(4455, n)))\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nfor (n in c(50, 5000)) {\n  d <- leicht_schief(n)\n  qqnorm(d, pch = 16, cex = 0.4, main = paste(\"n =\", n))\n  qqline(d, lwd = 2)\n}\npar(mfrow = c(1, 1))\n\nfor (n in c(20, 50, 200, 1000, 5000)) {\n  d <- leicht_schief(n)\n  rein <- qnorm(lehmer(3344, n))\n  cat(sprintf(\"n = %4d | leicht schief: Schiefe %+.3f, p %.2e | rein normal: p %.3f\\n\",\n              n, schiefe(d), shapiro.test(d)$p.value,\n              shapiro.test(rein)$p.value))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn =   20 | leicht schief: Schiefe +1.502, p 1.51e-02 | rein normal: p 0.723\nn =   50 | leicht schief: Schiefe +1.480, p 4.75e-04 | rein normal: p 0.077\nn =  200 | leicht schief: Schiefe +0.836, p 2.62e-05 | rein normal: p 0.733\nn = 1000 | leicht schief: Schiefe +0.531, p 1.03e-08 | rein normal: p 0.317\nn = 5000 | leicht schief: Schiefe +0.479, p 2.18e-20 | rein normal: p 0.538\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 4: dieselbe leicht schiefe Verteilung bei n = 50 und n = 5000.](qq-plots_files/figure-html/fig-b4-qq-r-3.png){#fig-b4-qq-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndef leicht_schief(n):\n    return np.exp(0.15 * stats.norm.ppf(lehmer(4455, n)))\n\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nfor achse, n in zip(achsen, [50, 5000]):\n    _ = stats.probplot(leicht_schief(n), dist=\"norm\", plot=achse)\n    achse.set_title(f\"n = {n}\", fontsize=9)\n    achse.get_lines()[0].set_markersize(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nText(0.5, 1.0, 'n = 50')\nText(0.5, 1.0, 'n = 5000')\n```\n\n\n:::\n\n```{.python .cell-code}\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselbe Gegenüberstellung in Python.](qq-plots_files/figure-html/fig-b4-qq-py-1.png){#fig-b4-qq-py width=100%}\n:::\n\n```{.python .cell-code}\nfor n in [20, 50, 200, 1000, 5000]:\n    d = leicht_schief(n)\n    rein = stats.norm.ppf(lehmer(3344, n))\n    print(f\"n = {n:4d} | leicht schief: Schiefe {stats.skew(d):+.3f},\"\n          f\" p {stats.shapiro(d).pvalue:.2e}\"\n          f\" | rein normal: p {stats.shapiro(rein).pvalue:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn =   20 | leicht schief: Schiefe +1.502, p 1.51e-02 | rein normal: p 0.723\nn =   50 | leicht schief: Schiefe +1.480, p 4.75e-04 | rein normal: p 0.077\nn =  200 | leicht schief: Schiefe +0.836, p 2.62e-05 | rein normal: p 0.733\nn = 1000 | leicht schief: Schiefe +0.531, p 1.03e-08 | rein normal: p 0.317\nn = 5000 | leicht schief: Schiefe +0.479, p 2.18e-20 | rein normal: p 0.538\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| n | Schiefe | Shapiro-Wilk p (leicht schief) | Shapiro-Wilk p (rein normal) |\n|---|---|---|---|\n| 20 | +1.502 | **0.015** | 0.723 |\n| 50 | +1.480 | 4.8·10⁻⁴ | 0.077 |\n| 200 | +0.836 | 2.6·10⁻⁵ | 0.733 |\n| 1 000 | +0.531 | 1.0·10⁻⁸ | 0.317 |\n| **5 000** | **+0.479** | **2.2·10⁻²⁰** | 0.538 |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die Schiefe **sinkt** mit wachsendem n | Von 1.50 auf 0.48 — sie nähert sich dem wahren Wert der Verteilung an. Bei kleinen Stichproben ist die geschätzte Schiefe selbst sehr unsicher. |\n| Der p-Wert **fällt** um 18 Grössenordnungen | Und die Verteilung ändert sich dabei nicht. Was wächst, ist allein die Fähigkeit des Tests, eine feste Abweichung zu entdecken. |\n| Bei $n = 5000$ ist $p = 2 \\cdot 10^{-20}$ | Für eine Verteilung, die im QQ-Plot fast gerade aussieht und deren Schiefe unter 0.5 liegt. **Statistisch hochsignifikant, praktisch bedeutungslos.** |\n| Die **rein normale** Stichprobe bleibt bei jedem n unauffällig | 0.08 bis 0.73. Der Test macht also keinen Fehler — er entdeckt korrekt, was da ist. |\n| Die beiden QQ-Plots | sehen bei n = 50 und n = 5000 fast gleich aus. Nur der zweite hat mehr Punkte. |\n\n::: {.note-box}\n**Das ist keine Schwäche des Tests, sondern seine Eigenschaft.** Ein\nNormalitätstest prüft die Nullhypothese \"exakt normalverteilt\", und die ist bei\nechten Daten praktisch immer falsch. Mit genügend Beobachtungen wird jede noch\nso kleine Abweichung nachweisbar.\n\nDaraus folgt die Umkehrung, die genauso wichtig ist: **Bei kleinen Stichproben\nfindet der Test nichts**, gerade dort, wo die Normalitätsannahme am meisten\nzählt — denn bei grossem $n$ sorgt der\n[zentrale Grenzwertsatz](normalverteilung-zgws.qmd) ohnehin dafür, dass\nMittelwertverfahren funktionieren.\n\nDer Test ist also genau dort blind, wo man ihn bräuchte, und genau dort\nempfindlich, wo man ihn nicht braucht. Deshalb: **Plot ansehen, Grössenordnung\nder Abweichung beurteilen, und die Frage stellen, ob das gewählte Verfahren\ndarauf empfindlich reagiert.**\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Normalitätsannahme ist formal verletzt (Shapiro-Wilk p < .001 bei n =\n> 5000), die Abweichung ist mit einer Schiefe von 0.48 jedoch gering und im\n> QQ-Plot kaum erkennbar. Für Verfahren, die auf Mittelwerten beruhen, ist sie\n> bei dieser Stichprobengrösse ohne Belang.\n\n### Beispiel 5: Eine andere Referenzverteilung\n\n#### Frage und Datenlage\n\nDer QQ-Plot ist nicht auf die Normalverteilung festgelegt. Getestet wird eine\nStichprobe von Wartezeiten gegen **zwei** Referenzen: die Normalverteilung und\ndie Exponentialverteilung.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwartezeit <- -log(lehmer(6677, 300)) / 0.5      # exponential, Rate 0.5\n\nn <- length(wartezeit)\nposition <- (seq_len(n) - 0.5) / n\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nqqnorm(wartezeit, pch = 16, cex = 0.5, main = \"Referenz: Normalverteilung\")\nqqline(wartezeit, lwd = 2)\n\nplot(qexp(position, rate = 0.5), sort(wartezeit), pch = 16, cex = 0.5,\n     main = \"Referenz: Exponential\", xlab = \"theoretisches Quantil\",\n     ylab = \"beobachteter Wert\")\nabline(a = 0, b = 1, lwd = 2)\npar(mfrow = c(1, 1))\n\nround(c(mittel = mean(wartezeit), sd = sd(wartezeit),\n        schiefe = schiefe(wartezeit),\n        erwartete_schiefe_exponential = 2), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       mittel                            sd \n                        2.054                         1.957 \n                      schiefe erwartete_schiefe_exponential \n                        1.858                         2.000 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 5: dieselben Wartezeiten gegen zwei Referenzverteilungen.](qq-plots_files/figure-html/fig-b5-qq-r-3.png){#fig-b5-qq-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nwartezeit = -np.log(lehmer(6677, 300)) / 0.5\n\nn = len(wartezeit)\nposition = (np.arange(1, n + 1) - 0.5) / n\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\n_ = stats.probplot(wartezeit, dist=\"norm\", plot=achsen[0])\nachsen[0].set_title(\"Referenz: Normalverteilung\", fontsize=9)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nText(0.5, 1.0, 'Referenz: Normalverteilung')\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[0].get_lines()[0].set_markersize(3)\n\nachsen[1].scatter(stats.expon.ppf(position, scale=2), np.sort(wartezeit),\n                  s=8, color=\"black\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<matplotlib.collections.PathCollection object at 0x7f34287e2750>\n```\n\n\n:::\n\n```{.python .cell-code}\ngrenze = [0, np.sort(wartezeit).max()]\nachsen[1].plot(grenze, grenze, lw=2, color=\"black\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[<matplotlib.lines.Line2D object at 0x7f34275ac890>]\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[1].set_title(\"Referenz: Exponential\", fontsize=9)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nText(0.5, 1.0, 'Referenz: Exponential')\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[1].set_xlabel(\"theoretisches Quantil\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nText(0.5, 0, 'theoretisches Quantil')\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[1].set_ylabel(\"beobachteter Wert\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nText(0, 0.5, 'beobachteter Wert')\n```\n\n\n:::\n\n```{.python .cell-code}\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselbe Gegenüberstellung in Python.](qq-plots_files/figure-html/fig-b5-qq-py-1.png){#fig-b5-qq-py width=100%}\n:::\n\n```{.python .cell-code}\nprint({\"mittel\": round(float(wartezeit.mean()), 3),\n       \"sd\": round(float(wartezeit.std(ddof=1)), 3),\n       \"schiefe\": round(float(stats.skew(wartezeit)), 3),\n       \"erwartete_schiefe_exponential\": 2})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'mittel': 2.054, 'sd': 1.957, 'schiefe': 1.858, 'erwartete_schiefe_exponential': 2}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Referenz | Bild | Schluss |\n|---|---|---|\n| **Normalverteilung** | deutlicher Bogen nach oben | Die Annahme passt nicht. |\n| **Exponentialverteilung** | Punkte auf der Winkelhalbierenden | Die Annahme passt. |\n\n| Kennzahl | beobachtet | erwartet bei Exponential mit Rate 0.5 |\n|---|---|---|\n| Mittelwert | **2.054** | $1/0.5 = 2$ |\n| Standardabweichung | **1.957** | ebenfalls $1/0.5 = 2$ |\n| Schiefe | **1.858** | genau 2, unabhängig von der Rate |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Bei der Exponentialverteilung ist die Referenzgerade die **Winkelhalbierende** | Weil die Rate hier bekannt vorgegeben wurde. Wäre sie zu schätzen, ergäbe sich wie beim Normalfall eine Gerade mit anderer Steigung. |\n| Mittelwert **gleich** Standardabweichung | Die charakteristische Eigenschaft der Exponentialverteilung. Sie allein ist schon ein brauchbarer erster Hinweis. |\n| Die Schiefe von 2 ist **fest** | Bei jeder Rate. Auch das ist prüfbar, ohne einen Plot zu zeichnen. |\n\n::: {.note-box}\n**Wann sich eine andere Referenz lohnt:**\n\n| Referenz | Typischer Anlass |\n|---|---|\n| Exponential | Wartezeiten, Lebensdauern, Abstände zwischen Ereignissen |\n| Weibull | Ausfallzeiten mit Alterung — siehe [Zensierung](../ueberlebenszeit/zensierung-ueberlebensfunktion.qmd) |\n| log-normal | Löhne, Preise, alles multiplikativ Entstehende |\n| t-Verteilung | Residuen mit mehr Ausreissern als erwartet |\n| Gleichverteilung | p-Werte unter der Nullhypothese, siehe [Hypothesentests](../inferenz/hypothesentests-grundlagen.qmd) |\n\nDer letzte Fall ist der praktisch nützlichste: Ein QQ-Plot der p-Werte aus vielen\nTests gegen die Gleichverteilung zeigt sofort, ob mehr kleine p-Werte auftreten\nals unter der Nullhypothese zu erwarten.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Wartezeiten sind nicht normalverteilt (deutlicher Bogen im QQ-Plot,\n> Schiefe 1.86), passen aber gut zu einer Exponentialverteilung mit Rate 0.5:\n> Mittelwert (2.05) und Standardabweichung (1.96) stimmen wie erwartet überein,\n> und im QQ-Plot gegen diese Referenz liegen die Punkte auf der\n> Winkelhalbierenden.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEin QQ-Plot zeigt Punkte, die links unterhalb und rechts oberhalb der Geraden\nliegen, also eine S-Form. Was heisst das?\n\n- [ ] Die Daten sind rechtsschief ~ Schiefe zeigt sich als durchgehender Bogen in\n      eine Richtung, nicht als Abknicken an beiden Enden.\n- [x] Die Verteilung hat schwerere Ränder als die Normalverteilung ~ Richtig.\n      An beiden Enden liegen extremere Werte, als das Modell erwarten lässt.\n      Praktisch heisst das mehr Ausreisser, was Verfahren stört, die auf dem\n      Mittelwert beruhen.\n- [ ] Die Stichprobe ist zu klein ~ Bei kleinen Stichproben streuen die Ränder\n      stärker, aber dann in beide Richtungen zufällig, nicht systematisch.\n:::\n\n::: {.quiz}\nBei n = 5000 ergibt ein Shapiro-Wilk-Test p = 2·10⁻²⁰, der QQ-Plot sieht aber\nfast gerade aus. Was folgt daraus?\n\n- [x] Die Abweichung ist nachweisbar, aber klein ~ Richtig. Mit wachsender\n      Stichprobe wird jede noch so kleine Abweichung signifikant, weil die\n      Nullhypothese \"exakt normal\" bei echten Daten praktisch immer falsch ist.\n      Entscheidend ist die Grössenordnung, nicht der p-Wert.\n- [ ] Der Plot ist falsch gezeichnet ~ Beide zeigen dieselben Daten korrekt.\n- [ ] Die Daten müssen transformiert werden ~ Nicht wegen des p-Werts. Ob eine\n      Transformation nötig ist, entscheidet die Grösse der Abweichung und die\n      Empfindlichkeit des geplanten Verfahrens.\n:::\n\n::: {.quiz}\nSechs QQ-Plots aus derselben Normalverteilung sehen an den Rändern verschieden\naus. Warum?\n\n- [x] Die äussersten Punkte streuen am stärksten, weil dort die wenigsten\n      Beobachtungen liegen ~ Richtig. Der grösste von n Werten hat eine breite\n      Verteilung, der Median eine enge. Deshalb wird ein QQ-Plot auf ein\n      durchgehendes Muster hin gelesen, nicht Punkt für Punkt.\n- [ ] Der Zufallszahlengenerator ist ungeeignet ~ Alle sechs stammen aus derselben\n      Verteilung; die Unterschiede sind der Zufall selbst.\n- [ ] Die Stichproben sind unterschiedlich gross ~ Je drei sind gleich gross, und\n      auch innerhalb dieser drei unterscheiden sich die Ränder.\n:::\n\n::: {.quiz}\nWozu dient die Position $(i - 0.5)/n$ statt $i/n$?\n\n- [x] Sonst wäre der grösste Wert das 100-Prozent-Quantil, das bei unbegrenzten\n      Verteilungen unendlich ist ~ Richtig. Die Korrektur setzt jeden Rang in die\n      Mitte seines Anteilsintervalls. Es gibt mehrere gebräuchliche Varianten,\n      die sich nur an den Rändern leicht unterscheiden.\n- [ ] Um die Punkte gleichmässiger zu verteilen ~ Sie sind so oder so\n      gleichmässig verteilt.\n- [ ] Um den Mittelwert zu treffen ~ Mit dem Mittelwert hat die Korrektur nichts\n      zu tun.\n:::\n\n::: {.quiz}\nEine Stichprobe hat Mittelwert 2.0, Standardabweichung 2.0 und Schiefe 2.0.\nWelche Verteilung liegt nahe?\n\n- [x] Die Exponentialverteilung ~ Richtig. Bei ihr sind Mittelwert und\n      Standardabweichung immer gleich, und die Schiefe beträgt unabhängig von der\n      Rate genau 2. Diese drei Kennzahlen ersetzen den QQ-Plot zwar nicht, sind\n      aber ein starker Hinweis — im Beispiel ergeben sich 2.05, 1.96 und 1.86.\n- [ ] Die Normalverteilung ~ Ihre Schiefe ist null.\n- [ ] Die Gleichverteilung ~ Ihre Schiefe ist ebenfalls null, und ihre\n      Standardabweichung ist deutlich kleiner als ihr Mittelwert.\n:::\n\n## Verlinkte Ressourcen\n\n- [OpenIntro Statistics, Kapitel zu Verteilungen](https://www.openintro.org/book/os/)\n- [Normalitätstests](../tests/normalitaetstests.qmd)\n- [Normalverteilung und zentraler Grenzwertsatz](normalverteilung-zgws.qmd)\n",
    "supporting": [
      "qq-plots_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}