{
  "hash": "25b1aa14b889f0ce0f8a3716b457350b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lage- und Streuungsmasse\"\ndescription: \"Mittelwert, Median, Quartile, Standardabweichung und ihre Robustheit.\"\ncategories: [\"Deskriptive Statistik\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"ESDS\"]\nseitentyp: konzept\nstand: fertig\norder: 30\n---\n\n\n\n\n\n## Kernideen\n\n- Lage **und** Streuung gehören zusammen. Ein Mittelwert ohne Streuungsmass ist\n  eine halbe Information.\n- Lagemasse: Modus, Median, arithmetisches Mittel — welches zulässig ist,\n  entscheidet das [Skalenniveau](skalenniveaus.qmd).\n- **Robuste** Masse (Median, IQR) ignorieren extreme Werte, **empfindliche**\n  (Mittel, Standardabweichung) nutzen alle.\n- Quantile beantworten Anteilsfragen direkt: Das $p$-Quantil ist der Wert, unter\n  dem ein Anteil $p$ liegt.\n- Der Abstand zwischen Mittel und Median verrät die Schiefe, auch ohne Bild.\n- Im Nenner der Varianz steht $n-1$, und das hat einen nachrechenbaren Grund.\n- **R und NumPy rechnen verschieden**: `sd()` teilt durch $n-1$, `np.std()`\n  voreingestellt durch $n$.\n- Der Boxplot bündelt fünf Kennzahlen und zeigt die Form nicht.\n\n## Erklärung\n\nLage und Streuung beantworten zwei verschiedene Fragen: **wo** liegt die\nVerteilung, und **wie breit** ist sie. Zwei Datensätze mit identischem\nMittelwert können völlig verschiedene Sachverhalte beschreiben, wenn ihre\nStreuung sich unterscheidet.\n\n### Die Lagemasse und das Skalenniveau\n\n| Lagemass | ab Skalenniveau | robust | was es beschreibt |\n|---|---|---|---|\n| Modus | nominal | ja | die häufigste Ausprägung |\n| Median | ordinal | ja | der Wert in der Mitte der sortierten Reihe |\n| Arithmetisches Mittel | metrisch | nein | der Schwerpunkt der Werte |\n\nDer Median teilt die sortierte Reihe in zwei gleich grosse Hälften. Bei\nungerader Anzahl ist er der mittlere Wert, bei gerader das Mittel der beiden\nmittleren. Das arithmetische Mittel\n\n$$\\bar{x} = \\frac{1}{n}\\sum_{i=1}^{n} x_i$$\n\nist dagegen der **Schwerpunkt**: Die Summe der Abweichungen vom Mittel ist immer\nnull. Genau diese Eigenschaft macht es empfindlich, denn ein weit entfernter\nWert zieht den Schwerpunkt mit sich wie ein langer Hebel.\n\n::: {.note-box}\nDaraus wird eine Merkregel, die sich rückwärts anwenden lässt. Wer nur zwei\nZahlen hat und die Form nicht sieht, kann sie vergleichen:\n\n| Beobachtung | Form der Verteilung | typisches Beispiel |\n|---|---|---|\n| Mittel **grösser** als Median | rechtsschief, langer Rand nach rechts | Löhne, Wartezeiten, Schadenshöhen |\n| Mittel **kleiner** als Median | linksschief, langer Rand nach links | Prüfungsergebnisse bei leichter Prüfung |\n| Mittel **gleich** Median | symmetrisch | Messfehler um einen Sollwert |\n:::\n\n### Quantile\n\nDas $p$-Quantil ist der Wert, unterhalb dessen ein Anteil $p$ der Beobachtungen\nliegt. Der Median ist damit das 0.5-Quantil; die Quartile teilen die Daten in\nvier Viertel.\n\nEin Detail, über das man sonst stolpert: Es gibt neun verschiedene Definitionen,\nwie zwischen zwei Beobachtungen interpoliert wird. R verwendet standardmässig\nTyp 7 — und NumPy und pandas rechnen mit derselben linearen Interpolation, sodass\nbeide Sprachen hier ohne Zutun dasselbe Ergebnis liefern.\n\n### Die Streuungsmasse\n\nAuch hier gibt es die robuste und die empfindliche Familie.\n\n| Mass | Formel | robust | Eigenschaften |\n|---|---|---|---|\n| Spannweite | Maximum minus Minimum | nein | nutzt nur zwei Werte, wächst systematisch mit $n$ — das instabilste Mass |\n| Interquartilsabstand | $Q_3 - Q_1$ | ja | umfasst die mittleren fünfzig Prozent, ignoriert die äusseren Viertel vollständig |\n| Varianz | $s^2 = \\frac{1}{n-1}\\sum(x_i - \\bar{x})^2$ | nein | in quadrierten Einheiten, deshalb nicht direkt lesbar |\n| Standardabweichung | $s = \\sqrt{s^2}$ | nein | zurück in der Einheit der Daten; das Mass, das berichtet wird |\n| Variationskoeffizient | $v = s / \\bar{x}$ | nein | macht Grössenordnungen vergleichbar; nur bei positiven Verhältnisskalen sinnvoll |\n\n#### Warum im Nenner $n-1$ steht\n\nDie Formel teilt nicht durch die Anzahl der Werte, sondern durch eins weniger.\nDas wirkt wie ein Schreibfehler und hat einen Grund.\n\nGemessen werden die Abweichungen vom **geschätzten** Mittel, also von dem\nMittel, das aus genau diesen Daten stammt. Dieses Mittel liegt zwangsläufig\nmitten in den Daten drin. Es gibt keine Zahl, um die die Werte enger streuen als\num ihren eigenen Mittelwert; jeder andere Bezugspunkt, auch der wahre Mittelwert\nder Grundgesamtheit, ergäbe eine grössere Abweichungssumme.\n\nWer also durch $n$ teilt, misst die Streuung um den **günstigsten aller\nmöglichen** Bezugspunkte und erhält deshalb systematisch einen zu kleinen Wert.\nDie Korrektur um eins gleicht das aus. Sie heisst Bessel-Korrektur, und\nBeispiel 4 rechnet sie nach.\n\n#### Der Sprachunterschied, der daraus folgt\n\n**R rechnet immer mit $n-1$, NumPy standardmässig mit $n$.** pandas verhält sich\nwie R. Wer die Sprachen mischt, bekommt für dieselben Daten zwei verschiedene\nStandardabweichungen.\n\nGesteuert wird das in Python über den Parameter `ddof` — delta degrees of\nfreedom. Er gibt an, wie viel im Nenner von $n$ **abgezogen** wird: `ddof=0`\nteilt durch $n$, `ddof=1` durch $n-1$. Der Name nennt also nicht das Ergebnis,\nsondern die Grösse des Abzugs, und das ist der Grund, warum er beim ersten Lesen\nnichts sagt.\n\n### Der Boxplot und seine Anatomie\n\nDer Boxplot bündelt die robuste Familie in einem Bild. Die Box reicht von $Q_1$\nbis $Q_3$, der Strich darin ist der Median. Die Antennen gehen bis zum am\nweitesten entfernten Wert, der noch innerhalb von $1.5 \\times \\text{IQR}$ ab dem\njeweiligen Quartil liegt — alles darüber hinaus wird als Punkt gezeichnet.\n\nDie 1.5-Regel ist eine **Konvention, kein Test**. Sie markiert Werte, die einen\nzweiten Blick verdienen; sie beweist nicht, dass ein Wert falsch ist. Bei\nnormalverteilten Daten fallen rund 0.7 Prozent der Beobachtungen darunter, in\ngrossen Stichproben also regelmässig einige, ohne dass irgendetwas\nschiefgelaufen wäre.\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Was ein einziger Wert anrichtet\n\n#### Frage und Datenlage\n\nSechs Messwerte: 12, 14, 15, 15, 18, 21. Was passiert mit Mittel und Median,\nwenn ein siebter Wert von 470 dazukommt — etwa durch einen Tippfehler oder einen\nechten Extremfall?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(12, 14, 15, 15, 18, 21)\n\nrbind(\n  \"ohne Ausreisser\" = c(mittel = mean(x), median = median(x),\n                        sd = sd(x), iqr = IQR(x)),\n  \"mit Ausreisser\"  = c(mittel = mean(c(x, 470)), median = median(c(x, 470)),\n                        sd = sd(c(x, 470)), iqr = IQR(c(x, 470)))\n) |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                mittel median     sd iqr\nohne Ausreisser  15.83     15   3.19   3\nmit Ausreisser   80.71     15 171.68   5\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nx = np.array([12, 14, 15, 15, 18, 21])\nx_gross = np.append(x, 470)\n\n\ndef kennzahlen(werte):\n    q1, q3 = np.quantile(werte, [0.25, 0.75])\n    return {\"mittel\": werte.mean(), \"median\": np.median(werte),\n            \"sd\": werte.std(ddof=1), \"iqr\": q3 - q1}\n\n\nprint(pd.DataFrame([kennzahlen(x), kennzahlen(x_gross)],\n                   index=[\"ohne Ausreisser\", \"mit Ausreisser\"]).round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 mittel  median      sd  iqr\nohne Ausreisser   15.83    15.0    3.19  3.0\nmit Ausreisser    80.71    15.0  171.68  5.0\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| | Mittel | Median | Standardabweichung | IQR |\n|---|---|---|---|---|\n| ohne Ausreisser | 15.83 | **15.0** | 3.19 | **3.00** |\n| mit Ausreisser | **80.71** | **15.0** | **171.68** | **5.00** |\n| Faktor | **5.1** | **1.00** | **53.8** | **1.67** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Das Mittel **verfünffacht** sich | Der eine Wert von 470 trägt allein $470/7 = 67$ zum Mittel bei — mehr als die sechs anderen zusammen. |\n| Der Median bleibt **exakt** bei 15 | Er zählt nur ab, wie viele Werte links und rechts liegen. Ob ein Wert knapp oder weit rechts liegt, ist ihm gleich. Bei sieben statt sechs Werten rückt er von der Mitte zweier Werte auf den vierten — hier zufällig derselbe. |\n| Die Standardabweichung **verfünfzigfacht** sich | Noch empfindlicher als das Mittel, weil sie die Abweichung **quadriert**: $(470 - 80.7)^2$ ist rund 151 000 und beherrscht die Summe vollständig. |\n| Der IQR steigt von 3.0 auf 5.0 | Er umfasst nur die mittleren fünfzig Prozent; der Extremwert selbst liegt weit ausserhalb. Dass er sich überhaupt ändert, liegt nur daran, dass aus sechs Werten sieben werden und die Quartile dadurch auf andere Rangpositionen fallen. |\n\n::: {.note-box}\nDer Vergleich der beiden **Faktoren** ist die eigentliche Lehre: 53.8 gegen 1.67.\nWer eine Streuung berichtet, entscheidet damit implizit, wie stark einzelne\nExtremwerte durchschlagen sollen.\n\nUnd daraus folgt die Praxisregel: **Sobald eine Verteilung schief ist oder\nAusreisser enthält, beschreibt das robuste Paar (Median, IQR) den typischen Fall\nbesser.** Genau darum werden Löhne und Immobilienpreise als Median berichtet.\n:::\n\n#### Interpretation\n\nDer Ausreisser ist damit nicht erklärt — nur seine Wirkung. Ob 470 ein\nTippfehler, ein Sonderfall oder ein echter Messwert ist, entscheidet die Sache,\nnicht die Statistik. Was nicht geht: ihn stillschweigend entfernen.\n\n### Beispiel 2: Schiefe an Löhnen\n\n#### Frage und Datenlage\n\n800 konstruierte Monatslöhne mit dem typischen Verlauf: viele im mittleren\nBereich, einzelne sehr hohe. Was macht das mit Mittel und Median?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data.frame(lohn = loehne), aes(lohn)) +\n  geom_histogram(bins = 45, fill = \"grey75\", colour = \"white\") +\n  geom_vline(xintercept = median(loehne)) +\n  geom_vline(xintercept = mean(loehne), linetype = \"dashed\") +\n  annotate(\"text\", x = median(loehne), y = Inf, label = \"Median\",\n           vjust = 1.6, hjust = 1.1, size = 3.5) +\n  annotate(\"text\", x = mean(loehne), y = Inf, label = \"Mittel\",\n           vjust = 1.6, hjust = -0.1, size = 3.5) +\n  labs(x = \"Monatslohn (CHF)\", y = \"Anzahl\")\n\nround(c(minimum = min(loehne), q25 = quantile(loehne, 0.25),\n        median = median(loehne), mittel = mean(loehne),\n        q75 = quantile(loehne, 0.75), q90 = quantile(loehne, 0.90),\n        maximum = max(loehne)), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nminimum q25.25%  median  mittel q75.75% q90.90% maximum \n 1736.0  5132.8  6927.0  7621.1  9112.0 12380.3 23844.0 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(spannweite = diff(range(loehne)), iqr = IQR(loehne),\n        sd = sd(loehne), vk = sd(loehne) / mean(loehne)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nspannweite        iqr         sd         vk \n 22108.000   3979.250   3420.327      0.449 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 2: rechtsschiefe Verteilung. Der lange rechte Rand zieht das Mittel über den Median.](lage-streuungsmasse_files/figure-html/fig-b2-lage-r-1.png){#fig-b2-lage-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, achse = plt.subplots()\nachse.hist(loehne, bins=45, color=\"0.75\", edgecolor=\"white\")\nachse.axvline(np.median(loehne), color=\"black\")\nachse.axvline(loehne.mean(), color=\"black\", linestyle=\"--\")\nachse.annotate(\"Median\", (np.median(loehne), achse.get_ylim()[1]),\n               ha=\"right\", va=\"top\", fontsize=9)\nachse.annotate(\"Mittel\", (loehne.mean(), achse.get_ylim()[1]),\n               ha=\"left\", va=\"top\", fontsize=9)\nachse.set_xlabel(\"Monatslohn (CHF)\")\nachse.set_ylabel(\"Anzahl\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselbe Verteilung mit matplotlib.](lage-streuungsmasse_files/figure-html/fig-b2-lage-py-1.png){#fig-b2-lage-py width=100%}\n:::\n\n```{.python .cell-code}\nq25, q75, q90 = np.quantile(loehne, [0.25, 0.75, 0.90])\nprint(pd.Series({\"minimum\": loehne.min(), \"q25\": q25,\n                 \"median\": np.median(loehne), \"mittel\": loehne.mean(),\n                 \"q75\": q75, \"q90\": q90, \"maximum\": loehne.max()}).round(1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nminimum     1736.0\nq25         5132.8\nmedian      6927.0\nmittel      7621.1\nq75         9112.0\nq90        12380.3\nmaximum    23844.0\ndtype: float64\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pd.Series({\n    \"spannweite\": loehne.max() - loehne.min(),\n    \"iqr\": q75 - q25,\n    \"sd\": loehne.std(ddof=1),           # ddof=1 entspricht sd() in R\n    \"vk\": loehne.std(ddof=1) / loehne.mean(),\n}).round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nspannweite    22108.000\niqr            3979.250\nsd             3420.327\nvk                0.449\ndtype: float64\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Kennzahl | Wert | Was sie sagt |\n|---|---|---|\n| Minimum | 1 736 | |\n| $Q_{25}$ | rund 5 200 | Ein Viertel verdient weniger. |\n| **Median** | **6 927** | Die Hälfte verdient weniger, die Hälfte mehr. **Das ist der typische Lohn.** |\n| **Mittel** | **7 621** | Rund 700 Franken höher — der Abstand ist die Schiefe. |\n| $Q_{75}$ | rund 9 200 | |\n| $Q_{90}$ | 12 380 | Zehn Prozent verdienen mehr als das. |\n| Maximum | 23 844 | Das Dreieinhalbfache des Medians. |\n\n| Streuungsmass | Wert | Wie er zu lesen ist |\n|---|---|---|\n| Spannweite | **22 108** | Beschreibt nur die beiden Extremwerte, sonst nichts. Bei 8000 statt 800 Löhnen wäre sie grösser, ohne dass sich an der Verteilung etwas geändert hätte. |\n| **IQR** | **3 979** | Die mittleren fünfzig Prozent liegen in einem Band von rund 4000 Franken. Das ist die brauchbare Aussage. |\n| Standardabweichung | 3 420 | Kleiner als der IQR — bei einer symmetrischen Verteilung wäre sie kleiner als die Hälfte davon. Der Vergleich der beiden ist selbst ein Schiefemass. |\n| Variationskoeffizient | **0.449** | Die Streuung beträgt 45 Prozent des Mittelwerts. Damit lässt sich diese Lohnverteilung mit einer aus einem anderen Land oder einer anderen Währung vergleichen. |\n\n::: {.note-box}\n**Warum das Mittel überhaupt höher liegt**, im Bild abgelesen: Die Masse der\nLöhne liegt links, aber einzelne sehr hohe Werte ziehen sich weit nach rechts.\nDer Median zählt nur ab; das Mittel ist ein Schwerpunkt, und ein weit entfernter\nWert wirkt darin wie ein langer Hebel. Deshalb rutscht das Mittel dorthin, wo der\nRand länger ausläuft, während der Median stehen bleibt.\n\nDie Differenz von 694 Franken ist die kompakteste Beschreibung der Schiefe, die\nes gibt — und sie steht in jeder Lohnstatistik zum Ablesen bereit.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Der Medianlohn beträgt 6 927 Franken (IQR 3 979, n = 800). Die Verteilung ist\n> rechtsschief: Das arithmetische Mittel liegt mit 7 621 Franken rund zehn\n> Prozent darüber, und zehn Prozent der Löhne überschreiten 12 380 Franken.\n\n### Beispiel 3: Quantile beantworten Anteilsfragen\n\n#### Frage und Datenlage\n\nEin Hersteller garantiert, dass 90 Prozent der Bauteile eine Toleranz von\nhöchstens 0.4 mm einhalten. Welche Kennzahl prüft diese Zusage — und welche\nnicht?\n\nDazu die kleinen Werte aus Beispiel 1, an denen sich die Interpolation zeigen\nlässt.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(x, probs = c(0.25, 0.5, 0.75))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  25%   50%   75% \n14.25 15.00 17.25 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Wie kommt 14.25 zustande? Typ 7 interpoliert linear zwischen den Rängen\nsortiert <- sort(x)\nposition <- 1 + 0.25 * (length(x) - 1)          # Rangposition des 25%-Quantils\nc(position = position,\n  unten = sortiert[floor(position)],\n  oben = sortiert[ceiling(position)],\n  anteil = position - floor(position))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nposition    unten     oben   anteil \n    2.25    14.00    15.00     0.25 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(np.quantile(x, [0.25, 0.5, 0.75]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[14.25 15.   17.25]\n```\n\n\n:::\n\n```{.python .cell-code}\nsortiert = np.sort(x)\nposition = 1 + 0.25 * (len(x) - 1)\nprint({\"position\": position,\n       \"unten\": int(sortiert[int(np.floor(position)) - 1]),\n       \"oben\": int(sortiert[int(np.ceil(position)) - 1]),\n       \"anteil\": round(position - np.floor(position), 2)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'position': 2.25, 'unten': 14, 'oben': 15, 'anteil': np.float64(0.25)}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nDie drei Quartile der Werte 12, 14, 15, 15, 18, 21:\n\n| Quantil | Wert |\n|---|---|\n| $Q_{25}$ | **14.25** |\n| $Q_{50}$ (Median) | 15.00 |\n| $Q_{75}$ | **17.25** |\n\n| Schritt | Rechnung | Ergebnis |\n|---|---|---|\n| Rangposition | $1 + 0.25 \\cdot (6 - 1)$ | **2.25** |\n| Nachbarn | zweiter Wert = 14, dritter Wert = 15 | |\n| Interpolation | $14 + 0.25 \\cdot (15 - 14)$ | **14.25** |\n\n| Frage | Antwort | Warum |\n|---|---|---|\n| Prüft das **0.9-Quantil** die Zusage? | **Ja** | Es ist genau der Wert, unter dem 90 Prozent der Beobachtungen liegen, und lässt sich unmittelbar mit den 0.4 mm vergleichen. |\n| Prüft der **Mittelwert** sie? | Nein | Er sagt nichts darüber, wie viele Teile unter einer Schranke liegen. Ein kleines Mittel ist mit vielen Ausreissern vereinbar. |\n| Prüft die **Standardabweichung** sie? | Nein | Sie beschreibt die Streubreite insgesamt. Auf einen Anteil lässt sich daraus nur schliessen, wenn man zusätzlich eine Verteilungsform unterstellt — und genau das will man bei einer Garantiezusage nicht. |\n\n::: {.note-box}\n**Warum 14.25 und nicht 14?** Weil das 25-Prozent-Quantil bei sechs Werten\nzwischen den Rängen liegt. Es gibt neun gebräuchliche Konventionen, wie dann\ninterpoliert wird; R nimmt Typ 7, und NumPy sowie pandas rechnen genauso.\n\nBei anderen Werkzeugen ist das nicht garantiert: Excel, SPSS und SQL-Datenbanken\nverwenden teils andere Typen, und bei kleinen Stichproben kommen dann sichtbar\nverschiedene Zahlen heraus. Bei $n$ in den Hunderten ist der Unterschied\nvernachlässigbar.\n:::\n\n#### Interpretation\n\nQuantile sind das direkte Werkzeug für Anteilsfragen — Garantiezusagen,\nService-Level, Grenzwerte. Der Umweg über Mittel und Streuung braucht immer eine\nzusätzliche Annahme.\n\n### Beispiel 4: Warum $n-1$\n\n#### Frage und Datenlage\n\nDie Behauptung: Die Division durch $n$ unterschätzt die Varianz systematisch,\ndie durch $n-1$ trifft sie im Mittel. Das lässt sich nachrechnen — mit 20 000\nStichproben zu je fünf Werten aus einer Grundgesamtheit mit bekannter Varianz\n$\\sigma^2 = 25$.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 20000 Stichproben zu je 5 Werten, sigma = 5, also sigma^2 = 25\nalle <- matrix(normalwerte(3311, 20000 * 5, 100, 5), nrow = 20000, byrow = TRUE)\n\ndurch_n <- mean(apply(alle, 1, function(v) mean((v - mean(v))^2)))\ndurch_n_1 <- mean(apply(alle, 1, var))          # var() teilt durch n - 1\n\nround(c(wahr = 25, geteilt_durch_n = durch_n,\n        geteilt_durch_n_1 = durch_n_1,\n        verhaeltnis = durch_n / 25), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             wahr   geteilt_durch_n geteilt_durch_n_1       verhaeltnis \n           25.000            20.203            25.254             0.808 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Der Faktor ist kein Zufall\nround((5 - 1) / 5, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nalle = normalwerte(3311, 20000 * 5, 100, 5).reshape(20000, 5)\n\ndurch_n = ((alle - alle.mean(axis=1, keepdims=True)) ** 2).mean(axis=1).mean()\ndurch_n_1 = alle.var(axis=1, ddof=1).mean()\n\nprint({\"wahr\": 25,\n       \"geteilt_durch_n\": round(float(durch_n), 3),\n       \"geteilt_durch_n_1\": round(float(durch_n_1), 3),\n       \"verhaeltnis\": round(float(durch_n) / 25, 3)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'wahr': 25, 'geteilt_durch_n': 20.203, 'geteilt_durch_n_1': 25.254, 'verhaeltnis': 0.808}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"(n - 1) / n =\", round((5 - 1) / 5, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(n - 1) / n = 0.8\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | Wert |\n|---|---|\n| wahre Varianz $\\sigma^2$ | **25.00** |\n| Mittel über 20 000 Stichproben, geteilt durch $n$ | **20.20** |\n| Mittel über 20 000 Stichproben, geteilt durch $n-1$ | **25.25** |\n| Verhältnis 20.20 zu 25 | **0.808** |\n| $(n-1)/n$ bei $n = 5$ | **0.800** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die Variante mit $n$ liegt **um 19 Prozent zu tief** | Und zwar nicht zufällig: Das Verhältnis 0.808 trifft den theoretischen Wert $(n-1)/n = 0.8$ auf ein Prozent genau. Die Unterschätzung ist also exakt vorhersagbar. |\n| Die Variante mit $n-1$ trifft | 25.25 gegenüber 25.00. Die Restabweichung von einem Prozent ist Stichprobenzufall über die 20 000 Wiederholungen. |\n| Bei $n = 5$ ist der Fehler gross | Ein Fünftel des Nenners macht viel aus. |\n| Bei $n = 500$ wäre er 0.2 Prozent | Deshalb spielt die Frage bei grossen Stichproben praktisch keine Rolle — und deshalb ist sie trotzdem wichtig, weil kleine Stichproben der Normalfall sind, in dem man sie braucht. |\n\n::: {.note-box}\n**Der Sprachunterschied in einer Zeile:**\n\n| Aufruf | Nenner | Ergebnis für 12, 14, 15, 15, 18, 21 |\n|---|---|---|\n| `sd(x)` in R | $n-1$ | **3.1885** |\n| `np.std(x)` | $n$ | **2.9107** |\n| `np.std(x, ddof=1)` | $n-1$ | 3.1885 |\n| `pd.Series(x).std()` | $n-1$ | 3.1885 |\n\nAbweichend verhält sich also **nur NumPy selbst**. Beispiel 5 zeigt es an den\nZahlen.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Division durch $n$ unterschätzt die Varianz bei $n = 5$ systematisch um den\n> Faktor $(n-1)/n = 0.8$; die Bessel-Korrektur gleicht das aus. In der Simulation\n> über 20 000 Stichproben ergibt sich 20.20 gegenüber 25.25, bei einer wahren\n> Varianz von 25.\n\n### Beispiel 5: Der Boxplot und was er verschweigt\n\n#### Frage und Datenlage\n\nZwei Verteilungen mit fast identischen Boxplots: eine zweigipflige (zwei Wolken\num 35 und 65) und eine gleichmässige zwischen 25 und 75. Was zeigt der Boxplot,\nwas nicht?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwerte <- c(normalwerte(4411, 120, 50, 8), 88, 91, 12)\nkennz <- quantile(werte, c(0.25, 0.5, 0.75))\niqr <- kennz[3] - kennz[1]\n\nzweigipflig <- c(normalwerte(5511, 400, 35, 5), normalwerte(5512, 400, 65, 5))\ngleichmaessig <- 25 + 50 * lehmer(5513, 800)\ndat <- data.frame(\n  wert = c(zweigipflig, gleichmaessig),\n  form = rep(c(\"zweigipflig\", \"gleichmässig\"), each = 800)\n)\n\npar(mfrow = c(1, 2), mar = c(3, 4, 2, 1))\nboxplot(werte, main = \"Anatomie\", ylab = \"Messwert\", col = \"grey90\")\ntext(1.35, kennz, labels = c(\"Q1\", \"Median\", \"Q3\"), cex = 0.8)\nboxplot(wert ~ form, data = dat, main = \"zwei Formen\", xlab = \"\", ylab = \"Wert\",\n        col = \"grey90\")\npar(mfrow = c(1, 1))\n\nround(c(q1 = kennz[1], median = kennz[2], q3 = kennz[3], iqr = iqr,\n        grenze_unten = kennz[1] - 1.5 * iqr,\n        grenze_oben = kennz[3] + 1.5 * iqr), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          q1.25%       median.50%           q3.75%          iqr.75% \n           45.31            50.15            56.30            10.99 \ngrenze_unten.25%  grenze_oben.75% \n           28.83            72.78 \n```\n\n\n:::\n\n```{.r .cell-code}\nsort(werte[werte < kennz[1] - 1.5 * iqr | werte > kennz[3] + 1.5 * iqr])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 12 88 91\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 5: links die Anatomie des Boxplots, rechts zwei fast gleiche Boxplots zu sehr verschiedenen Verteilungen.](lage-streuungsmasse_files/figure-html/fig-b5-lage-r-1.png){#fig-b5-lage-r width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dat, aes(wert)) +\n  geom_histogram(bins = 40, fill = \"grey75\", colour = \"white\") +\n  facet_wrap(~ form) +\n  labs(x = \"Wert\", y = \"Anzahl\")\n```\n\n::: {.cell-output-display}\n![Beispiel 5: erst das Histogramm macht die zwei Gipfel sichtbar.](lage-streuungsmasse_files/figure-html/fig-b5b-lage-r-1.png){#fig-b5b-lage-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nwerte = np.append(normalwerte(4411, 120, 50, 8), [88, 91, 12])\nq1, med, q3 = np.quantile(werte, [0.25, 0.5, 0.75])\niqr = q3 - q1\n\nzweigipflig = np.concatenate([normalwerte(5511, 400, 35, 5),\n                              normalwerte(5512, 400, 65, 5)])\ngleichmaessig = 25 + 50 * lehmer(5513, 800)\n\nfig, achsen = plt.subplots(2, 2, figsize=(7, 5))\nachsen[0, 0].boxplot(werte, whis=1.5, widths=0.35, patch_artist=True,\n                     boxprops={\"facecolor\": \"0.9\"},\n                     medianprops={\"color\": \"black\"})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'whiskers': [<matplotlib.lines.Line2D object at 0x7f7a112110d0>, <matplotlib.lines.Line2D object at 0x7f7a110f6d50>], 'caps': [<matplotlib.lines.Line2D object at 0x7f7a110f6930>, <matplotlib.lines.Line2D object at 0x7f7a110f6660>], 'boxes': [<matplotlib.patches.PathPatch object at 0x7f7a11223740>], 'medians': [<matplotlib.lines.Line2D object at 0x7f7a110f6450>], 'fliers': [<matplotlib.lines.Line2D object at 0x7f7a110f5550>], 'means': []}\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[0, 0].set_title(\"Anatomie\")\nachsen[0, 1].boxplot([zweigipflig, gleichmaessig], widths=0.4,\n                     patch_artist=True, boxprops={\"facecolor\": \"0.9\"},\n                     medianprops={\"color\": \"black\"})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'whiskers': [<matplotlib.lines.Line2D object at 0x7f7a110f7170>, <matplotlib.lines.Line2D object at 0x7f7a110f6ed0>, <matplotlib.lines.Line2D object at 0x7f7a11120890>, <matplotlib.lines.Line2D object at 0x7f7a11120b00>], 'caps': [<matplotlib.lines.Line2D object at 0x7f7a110f62a0>, <matplotlib.lines.Line2D object at 0x7f7a11201520>, <matplotlib.lines.Line2D object at 0x7f7a11120da0>, <matplotlib.lines.Line2D object at 0x7f7a110f7b60>], 'boxes': [<matplotlib.patches.PathPatch object at 0x7f7a110f6b70>, <matplotlib.patches.PathPatch object at 0x7f7a11120410>], 'medians': [<matplotlib.lines.Line2D object at 0x7f7a111202f0>, <matplotlib.lines.Line2D object at 0x7f7a11120f20>], 'fliers': [<matplotlib.lines.Line2D object at 0x7f7a11120440>, <matplotlib.lines.Line2D object at 0x7f7a11121190>], 'means': []}\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[0, 1].set_xticklabels([\"zweigipflig\", \"gleichmässig\"])\nachsen[0, 1].set_title(\"zwei Formen\")\nfor achse, daten, titel in zip(achsen[1], [zweigipflig, gleichmaessig],\n                               [\"zweigipflig\", \"gleichmässig\"]):\n    achse.hist(daten, bins=40, color=\"0.75\", edgecolor=\"white\")\n    achse.set_title(titel)\n    achse.set_xlabel(\"Wert\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 5: oben die Boxplots, unten dieselben Daten als Histogramm.](lage-streuungsmasse_files/figure-html/fig-b5-lage-py-1.png){#fig-b5-lage-py width=100%}\n:::\n\n```{.python .cell-code}\nprint({\"q1\": round(q1, 2), \"median\": round(med, 2), \"q3\": round(q3, 2),\n       \"iqr\": round(iqr, 2),\n       \"grenze_unten\": round(q1 - 1.5 * iqr, 2),\n       \"grenze_oben\": round(q3 + 1.5 * iqr, 2)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'q1': np.float64(45.31), 'median': np.float64(50.15), 'q3': np.float64(56.3), 'iqr': np.float64(10.99), 'grenze_unten': np.float64(28.83), 'grenze_oben': np.float64(72.78)}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Ausreisser:\",\n      np.round(np.sort(werte[(werte < q1 - 1.5 * iqr)\n                             | (werte > q3 + 1.5 * iqr)]), 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAusreisser: [12. 88. 91.]\n```\n\n\n:::\n\n```{.python .cell-code}\nfor name, daten in [(\"zweigipflig\", zweigipflig),\n                    (\"gleichmässig\", gleichmaessig)]:\n    a, b = np.quantile(daten, [0.25, 0.75])\n    print(f\"{name:14s} Median {np.median(daten):6.2f}  Q1 {a:6.2f}\"\n          f\"  Q3 {b:6.2f}  SD {daten.std(ddof=1):5.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nzweigipflig    Median  51.46  Q1  35.10  Q3  65.06  SD 15.82\ngleichmässig   Median  50.43  Q1  36.55  Q3  62.22  SD 14.45\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nDie Anatomie an 123 Werten:\n\n| Grösse | Wert | Bedeutung |\n|---|---|---|\n| $Q_1$ | 45.31 | untere Kante der Box |\n| Median | 50.15 | Strich in der Box |\n| $Q_3$ | 56.30 | obere Kante |\n| IQR | **10.99** | Höhe der Box |\n| Grenze unten | $45.31 - 1.5 \\cdot 10.99 = $ **28.83** | |\n| Grenze oben | $56.30 + 1.5 \\cdot 10.99 = $ **72.78** | |\n| markierte Werte | **12, 88, 91** | genau die drei absichtlich eingebauten |\n\n**Die Antennen enden nicht an diesen Grenzen**, sondern am letzten tatsächlichen\nWert davor. Das ist der häufigste Lesefehler: Die Antennenlänge ist ein Datenwert,\nkein gerechneter Grenzwert.\n\nUnd die beiden Formen im Vergleich:\n\n| | Median | $Q_1$ | $Q_3$ | SD |\n|---|---|---|---|---|\n| zweigipflig | 51.46 | 35.10 | 65.06 | 15.82 |\n| gleichmässig | 50.43 | 36.55 | 62.22 | 14.45 |\n\n| Beobachtung | Deutung |\n|---|---|\n| Die Mediane liegen **einen Punkt** auseinander | Aus zwei Boxplots nebeneinander wäre kein Unterschied ablesbar. |\n| Quartile und SD unterscheiden sich um wenige Prozent | Alle fünf Kennzahlen des Boxplots sind praktisch gleich. |\n| Die **Histogramme** zeigen etwas völlig anderes | Zwei getrennte Gipfel gegen eine flache Wanne. Der Boxplot kann das nicht zeigen, weil er nur fünf Zahlen kennt. |\n| Der Median 51.46 bei der zweigipfligen Verteilung | liegt in der **Lücke** zwischen den Gipfeln — an einer Stelle, an der praktisch keine Beobachtung liegt. Eine \"typische\" Beobachtung ist er damit nicht. |\n\n::: {.note-box}\nDeshalb gehört zum Boxplot immer ein zweiter Blick auf die Verteilung —\n[Histogramm](haeufigkeiten.qmd), Dichtekurve oder bei kleinen Stichproben schlicht\ndie einzelnen Punkte.\n\nSeine Stärke ist der **Gruppenvergleich**: zwanzig Boxplots nebeneinander sind\nlesbar, zwanzig Histogramme nicht. Seine Schwäche ist die **Form** einer\neinzelnen Verteilung.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Der markierte Wert liegt mehr als das Anderthalbfache des Interquartilsabstands\n> über dem oberen Quartil (Grenze 72.78 bei $Q_3$ = 56.30 und IQR = 10.99). Das\n> ist eine Konvention zum Hinsehen und kein Test.\n\n::::\n\n## Was beim Berichten festzuhalten ist\n\n- Lagemass **und** Streuungsmass, nie eines allein.\n- Bei schiefen Daten Median und IQR, bei symmetrischen Mittel und\n  Standardabweichung.\n- Die Stichprobengrösse dazu, denn ohne $n$ ist keine Streuungsangabe einzuordnen.\n- Ausreisser nicht stillschweigend entfernen, sondern benennen.\n- Beim Sprachwechsel an `ddof` denken.\n\n## Verständnisfragen\n\n::: {.quiz}\nEine Auswertung von 200 Wohnungsmieten meldet ein Mittel von 2140 Franken und\neinen Median von 1680 Franken. Was folgt daraus?\n\n- [ ] Es liegt ein Rechenfehler vor ~ Nein, beide Masse dürfen weit\n      auseinanderliegen. Genau dieser Abstand ist die Information.\n- [x] Die Verteilung ist rechtsschief ~ Richtig. Das Mittel liegt über dem\n      Median, also zieht ein langer rechter Rand mit wenigen sehr teuren\n      Wohnungen den Schwerpunkt nach oben.\n- [ ] Die Hälfte der Mieten liegt über 2140 Franken ~ Das gilt für den Median,\n      nicht für das Mittel. Über 1680 Franken liegt die Hälfte, über 2140\n      deutlich weniger.\n- [ ] Die Stichprobe ist zu klein ~ Der Umfang sagt über die Schiefe nichts\n      aus. 200 Beobachtungen sind für diese Aussage reichlich.\n:::\n\n::: {.quiz}\nEin Ausreisser lässt die Standardabweichung um den Faktor 54 steigen, den IQR um\nden Faktor 1.17. Woran liegt der Unterschied?\n\n- [x] Die Standardabweichung quadriert die Abweichungen, der IQR ignoriert die\n      äusseren Viertel ~ Richtig. Ein Wert weit draussen geht quadriert in die\n      Summe ein und beherrscht sie; für die Quartile zählt er nur als eine\n      Beobachtung von vielen.\n- [ ] Die Standardabweichung ist falsch berechnet ~ Beide sind korrekt; sie\n      messen verschiedene Dinge.\n- [ ] Der IQR ist ungenauer ~ Er ist unempfindlicher, was hier ein Vorteil und\n      bei symmetrischen Daten ein Nachteil ist: Dort nutzt er nur die Hälfte der\n      Information.\n:::\n\n::: {.quiz}\nEin Hersteller garantiert, dass 90 Prozent der Bauteile eine Toleranz von\nhöchstens 0.4 mm haben. Welche Kennzahl prüft diese Zusage direkt?\n\n- [x] Das 0.9-Quantil der gemessenen Abweichungen ~ Richtig. Es ist genau der\n      Wert, unter dem 90 Prozent der Beobachtungen liegen, und lässt sich\n      unmittelbar mit 0.4 mm vergleichen.\n- [ ] Der Mittelwert der Abweichungen ~ Er sagt nichts darüber, wie viele\n      Teile unter einer bestimmten Schranke liegen. Ein kleines Mittel ist mit\n      vielen Ausreissern vereinbar.\n- [ ] Die Standardabweichung ~ Sie beschreibt die Streubreite insgesamt.\n      Auf einen Anteil lässt sich daraus nur schliessen, wenn man zusätzlich\n      eine Verteilungsform unterstellt.\n:::\n\n::: {.quiz}\nDieselben zehn Messwerte werden in R mit `sd(x)` und in Python mit\n`np.std(x)` ausgewertet. Das R-Ergebnis ist grösser. Woran liegt das?\n\n- [x] NumPy teilt ohne Angabe durch $n$, R durch $n-1$ ~ Richtig. Der kleinere\n      Nenner in R ergibt den grösseren Wert. Mit `np.std(x, ddof=1)` stimmen\n      beide überein — und pandas verhält sich von sich aus wie R.\n- [ ] R rundet anders ~ Die Abweichung entsteht nicht beim Runden, sondern im\n      Nenner der Formel. Sie ist bei kleinem n deutlich sichtbar.\n- [ ] Die Werte wurden unterschiedlich eingelesen ~ Möglich wäre das, hier ist\n      es aber nicht die Ursache. Der Unterschied tritt auch bei identischen\n      Zahlen auf.\n:::\n\n::: {.quiz}\nWarum wird bei der Varianz überhaupt durch $n-1$ geteilt und nicht durch $n$?\n\n- [ ] Damit das Ergebnis grösser wird ~ Das ist die Folge, nicht der Grund.\n      Die Frage ist, warum die Vergrösserung berechtigt ist.\n- [x] Weil um das eigene Mittel gerechnet wird und die Streuung sonst\n      systematisch zu klein ausfällt ~ Richtig. Die Werte streuen um ihren\n      eigenen Mittelwert enger als um jeden anderen Bezugspunkt; die\n      Unterschätzung beträgt genau den Faktor $(n-1)/n$.\n- [ ] Weil ein Wert für den Mittelwert verbraucht wurde und deshalb einer\n      fehlt ~ Das ist die übliche Kurzformel und als Merkhilfe brauchbar, aber\n      sie erklärt nicht, warum daraus eine Unterschätzung folgt.\n:::\n\n::: {.quiz}\nZwei Maschinen produzieren Wellen. Maschine A hat eine Standardabweichung von\n0.8 mm bei einem Mitteldurchmesser von 40 mm, Maschine B eine von 2.0 mm bei\n200 mm. Welche arbeitet relativ gesehen genauer?\n\n- [ ] Maschine A, weil 0.8 kleiner ist als 2.0 ~ Der Vergleich der absoluten\n      Streuung übersieht, dass die Teile ganz verschieden gross sind.\n- [x] Maschine B ~ Richtig. Der Variationskoeffizient beträgt bei A 0.8/40 = 2\n      Prozent, bei B 2.0/200 = 1 Prozent. Gemessen an der Teilegrösse streut B\n      halb so stark.\n- [ ] Das lässt sich ohne die Stichprobengrössen nicht sagen ~ Für den\n      Vergleich der Streuung genügen Mittel und Standardabweichung. Der Umfang\n      beträfe die Genauigkeit der Schätzung, nicht den Vergleich selbst.\n:::\n\n::: {.quiz}\nZwei Gruppen haben nahezu identische Boxplots. Was lässt sich daraus schliessen?\n\n- [ ] Die Verteilungen sind gleich ~ Nein. Der Boxplot zeigt fünf Kennzahlen,\n      und die können übereinstimmen, während die Form völlig verschieden ist.\n- [x] Median, Quartile und Spannweite stimmen ungefähr überein, über die Form\n      sagt das nichts ~ Richtig. In Beispiel 5 unterscheiden sich die Mediane um\n      einen Punkt, während eine der Verteilungen zweigipflig ist und die andere\n      flach.\n- [ ] Eine der beiden Gruppen enthält Ausreisser ~ Ausreisser wären als\n      einzelne Punkte sichtbar. Hier ist gerade das Fehlen von Unterschieden\n      das Auffällige.\n:::\n\n## Verlinkte Ressourcen\n\n- [OpenIntro Statistics (frei verfügbar)](https://www.openintro.org/book/os/)\n- [Dokumentation zu `quantile` in R (die neun Typen)](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/quantile.html)\n- [`numpy.std` — Vorgabe `ddof=0`](https://numpy.org/doc/stable/reference/generated/numpy.std.html)\n",
    "supporting": [
      "lage-streuungsmasse_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}