{
  "hash": "de958a55dbd6f058072faf7331628b95",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Korrelation\"\ndescription: \"Pearson, Spearman und Kendall als Masse, ihre Grenzen und Fallstricke.\"\ncategories: [\"Korrelation\", \"Deskriptive Statistik\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"ESDS\"]\nseitentyp: konzept\nstand: entwurf\norder: 40\n---\n\n\n\n\n\n## Kernideen\n\n- Das **Streudiagramm** kommt vor jeder Kennzahl, nicht danach.\n- Die Kovarianz hängt an den Einheiten, die Korrelation nicht.\n- **Pearson** misst linearen Zusammenhang, **Spearman** und **Kendall** messen\n  monotonen.\n- Ein Wert nahe null schliesst einen starken, aber krummen Zusammenhang **nicht**\n  aus.\n- Ein einzelner Ausreisser kann das Vorzeichen von Pearson umkehren.\n- $r^2$ ist der Anteil gemeinsamer Streuung — und schon deshalb ist $r = 0.5$\n  nicht \"halb so stark\" wie $r = 1$.\n- Korrelation ist keine Kausalität, und das ist keine Floskel, sondern ein\n  nachrechenbarer Sachverhalt.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Lage- und Streuungsmasse](lage-streuungsmasse.qmd) für Varianz\nund Standardabweichung, [Skalenniveaus](skalenniveaus.qmd) für die Frage,\nwelches Mass zulässig ist. Ob ein beobachteter Zusammenhang mehr ist als\nZufall, beantwortet der\n[Korrelationstest](../tests/korrelationstests.qmd); die gerichtete Fassung\nsteht unter\n[einfache lineare Regression](../regression/einfache-lineare-regression.qmd).\n:::\n\n### Von einem Merkmal zu zweien\n\nBisher ging es um die Verteilung eines Merkmals. Die interessanteren Fragen\nbetreffen zwei: Steigt der Verbrauch mit der Laufzeit? Hängt der Blutdruck vom\nAlter ab? Für solche Fragen braucht es ein Mass für den gemeinsamen Verlauf.\n\nVor der Kennzahl steht die Grafik. Ein Zusammenhang lässt sich sehen, bevor er\ngerechnet wird, und was man sieht, entscheidet darüber, welche Kennzahl\nüberhaupt passt.\n\n### Kovarianz und Korrelation\n\nDie Kovarianz misst, ob zwei Merkmale gemeinsam von ihrem jeweiligen Mittel\nabweichen. Liegen beide gleichzeitig über oder unter ihrem Mittel, ist der\nBeitrag positiv.\n\n$$\\text{cov}(x,y) = \\frac{1}{n-1}\\sum_{i=1}^{n}(x_i - \\bar{x})(y_i - \\bar{y})$$\n\nIhr Nachteil ist, dass sie an den Einheiten hängt. Die Korrelation nach Pearson\nbehebt das, indem sie durch die beiden Standardabweichungen teilt. Das Ergebnis\nliegt immer zwischen minus eins und eins und ist einheitenfrei:\n\n$$r = \\frac{\\text{cov}(x,y)}{s_x \\cdot s_y}$$\n\n### Die drei gebräuchlichen Masse\n\n| Mass | Was es misst | Rechnet auf | Ab Skalenniveau | Robust |\n|---|---|---|---|---|\n| **Pearson** $r$ | linearer Zusammenhang | den Werten | metrisch | nein |\n| **Spearman** $\\rho$ | monotoner Zusammenhang | den Rängen | ordinal | ja |\n| **Kendall** $\\tau$ | monotoner Zusammenhang, über Paarvergleiche | den Rängen | ordinal | ja |\n\nSpearman ist nichts anderes als Pearson, angewendet auf die Ränge. Kendall geht\nanders vor: Er zählt für alle Paare von Beobachtungen, ob sie gleichgerichtet\n(konkordant) oder gegenläufig (diskordant) sind, und bildet daraus\n$\\tau = \\frac{\\text{konkordant} - \\text{diskordant}}{\\text{Anzahl Paare}}$.\n\nDaraus folgen die praktischen Unterschiede:\n\n| | Spearman | Kendall |\n|---|---|---|\n| Werte bei mittleren Zusammenhängen | grösser | kleiner (typisch rund zwei Drittel des Spearman-Werts) |\n| Deutung | \"wie gut passen die Ränge zueinander\" | direkt als Wahrscheinlichkeitsdifferenz: $(\\tau + 1)/2$ ist der Anteil gleichgerichteter Paare |\n| Bei vielen Bindungen | weniger zuverlässig | besser geeignet (Varianten $\\tau_b$, $\\tau_c$) |\n| Rechenaufwand | gering | quadratisch in $n$ |\n\n### Was $r$ bedeutet — und was nicht\n\n$r^2$ ist der Anteil der Streuung, den die beiden Merkmale teilen. Daraus folgt\neine Skala, die dem ersten Eindruck widerspricht:\n\n| $r$ | $r^2$ | gemeinsame Streuung |\n|---|---|---|\n| 0.9 | 0.81 | 81 % |\n| 0.7 | 0.49 | 49 % |\n| **0.5** | **0.25** | **25 %** |\n| 0.3 | 0.09 | 9 % |\n\nEin $r$ von 0.5 ist also nicht \"halb so stark\" wie ein $r$ von 1, sondern\nbeschreibt einen Zusammenhang, bei dem drei Viertel der Streuung anderswo\nherkommen.\n\n::: {.note-box}\n**Faustregeln für die Stärke sind fachabhängig.** In der Physik gilt $r = 0.9$\nals schwach, in der Sozialforschung als aussergewöhnlich hoch. Wer Schwellen\nnennt, sollte die Quelle dazu nennen. Aussagekräftiger als jede Schwelle ist das\nStreudiagramm plus die Angabe von $n$.\n:::\n\n### Der wichtigste Vorbehalt\n\nEin statistischer Zusammenhang belegt keine Ursache. Drei Erklärungen sind\nimmer möglich, und die Daten allein unterscheiden nicht zwischen ihnen: $x$\nwirkt auf $y$, $y$ wirkt auf $x$, oder eine dritte, nicht beobachtete Grösse\ntreibt beide. Beispiel 5 rechnet den dritten Fall durch.\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Warum die Grafik zuerst kommt\n\n#### Frage und Datenlage\n\nVier Datensätze zu je elf Punkten mit praktisch identischen Kennzahlen. Das\nBeispiel stammt von Anscombe und ist in R eingebaut.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlang <- data.frame(\n  satz = rep(1:4, each = 11),\n  x = c(anscombe$x1, anscombe$x2, anscombe$x3, anscombe$x4),\n  y = c(anscombe$y1, anscombe$y2, anscombe$y3, anscombe$y4)\n)\n\nggplot(lang, aes(x, y)) +\n  geom_point(size = 1.8) +\n  geom_smooth(method = \"lm\", formula = y ~ x, se = FALSE,\n              colour = \"black\", linewidth = 0.5) +\n  facet_wrap(~ satz, nrow = 1) +\n  labs(x = NULL, y = NULL)\n\nlang |>\n  group_by(satz) |>\n  summarise(mittel_x = mean(x), sd_x = sd(x),\n            mittel_y = round(mean(y), 2), sd_y = round(sd(y), 2),\n            pearson = round(cor(x, y), 3),\n            spearman = round(cor(x, y, method = \"spearman\"), 3),\n            .groups = \"drop\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n   satz mittel_x  sd_x mittel_y  sd_y pearson spearman\n  <int>    <dbl> <dbl>    <dbl> <dbl>   <dbl>    <dbl>\n1     1        9  3.32      7.5  2.03   0.816    0.818\n2     2        9  3.32      7.5  2.03   0.816    0.691\n3     3        9  3.32      7.5  2.03   0.816    0.991\n4     4        9  3.32      7.5  2.03   0.817    0.5  \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 1: vier Datensätze mit gleichem Mittelwert, gleicher Varianz und gleicher Korrelation.](korrelation_files/figure-html/fig-b1-kor-r-1.png){#fig-b1-kor-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nx123 = np.array([10, 8, 13, 9, 11, 14, 6, 4, 12, 7, 5], dtype=float)\nsaetze = {\n    1: (x123, np.array([8.04, 6.95, 7.58, 8.81, 8.33, 9.96, 7.24, 4.26,\n                        10.84, 4.82, 5.68])),\n    2: (x123, np.array([9.14, 8.14, 8.74, 8.77, 9.26, 8.10, 6.13, 3.10,\n                        9.13, 7.26, 4.74])),\n    3: (x123, np.array([7.46, 6.77, 12.74, 7.11, 7.81, 8.84, 6.08, 5.39,\n                        8.15, 6.42, 5.73])),\n    4: (np.array([8, 8, 8, 8, 8, 8, 8, 19, 8, 8, 8], dtype=float),\n        np.array([6.58, 5.76, 7.71, 8.84, 8.47, 7.04, 5.25, 12.50, 5.56,\n                  7.91, 6.89])),\n}\n\nfig, achsen = plt.subplots(1, 4, figsize=(7, 2.8), sharey=True)\nzeilen = []\nfor achse, (nummer, (x, y)) in zip(achsen, saetze.items()):\n    achse.scatter(x, y, s=14, color=\"black\")\n    steigung, achsenabschnitt = np.polyfit(x, y, 1)\n    gitter = np.linspace(x.min(), x.max(), 2)\n    achse.plot(gitter, achsenabschnitt + steigung * gitter,\n               color=\"black\", lw=0.6)\n    achse.set_title(f\"Satz {nummer}\", fontsize=9)\n    zeilen.append({\"satz\": nummer, \"mittel_x\": x.mean(), \"sd_x\": x.std(ddof=1),\n                   \"mittel_y\": y.mean(), \"sd_y\": y.std(ddof=1),\n                   \"pearson\": np.corrcoef(x, y)[0, 1],\n                   \"spearman\": stats.spearmanr(x, y).statistic})\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselben vier Datensätze in Python.](korrelation_files/figure-html/fig-b1-kor-py-1.png){#fig-b1-kor-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(pd.DataFrame(zeilen).round(3).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n satz  mittel_x  sd_x  mittel_y  sd_y  pearson  spearman\n    1       9.0 3.317     7.501 2.032    0.816     0.818\n    2       9.0 3.317     7.501 2.032    0.816     0.691\n    3       9.0 3.317     7.500 2.030    0.816     0.991\n    4       9.0 3.317     7.501 2.031    0.817     0.500\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Satz | Mittel x | SD x | Mittel y | SD y | Pearson | Spearman |\n|---|---|---|---|---|---|---|\n| 1 | 9.0 | 3.32 | 7.50 | 2.03 | **0.816** | 0.818 |\n| 2 | 9.0 | 3.32 | 7.50 | 2.03 | **0.816** | 0.691 |\n| 3 | 9.0 | 3.32 | 7.50 | 2.03 | **0.816** | 0.991 |\n| 4 | 9.0 | 3.32 | 7.50 | 2.03 | **0.817** | 0.500 |\n\n| Satz | Was das Bild zeigt | Was die Kennzahl verschweigt |\n|---|---|---|\n| 1 | eine gleichmässig streuende Punktwolke um eine Gerade | nichts — nur hier beschreibt $r$, was man sieht |\n| 2 | eine **exakte Parabel** | Der Zusammenhang ist perfekt und nicht linear. Pearson misst nur den geraden Anteil. |\n| 3 | eine **perfekte Gerade plus ein Ausreisser** | Ohne den einen Punkt wäre $r = 1$. Der Ausreisser drückt ihn auf 0.816. |\n| 4 | **zehn Punkte auf einer Senkrechten** plus einer weit rechts | Die Korrelation wird von einem einzigen Punkt erzeugt. Ohne ihn ist sie nicht definiert. |\n\n::: {.note-box}\nDie **Spearman-Spalte** ist die interessantere: Anders als Pearson unterscheidet\nsie die vier Sätze deutlich (0.82, 0.69, 0.99, 0.50). Das ist kein Zufall — die\nRänge reagieren anders auf Krümmung und Ausreisser als die Werte selbst.\n\nTrotzdem ersetzt auch sie das Bild nicht: Bei Satz 4 liefert sie 0.50 und sagt\ndamit nicht, dass zehn der elf Punkte denselben x-Wert haben.\n:::\n\n#### Interpretation\n\nJede Kennzahl fasst zusammen und wirft dabei etwas weg. Das Streudiagramm zeigt,\n**was** weggeworfen wurde — und ist deshalb der erste Schritt, nicht der letzte.\n\n### Beispiel 2: Kovarianz, Korrelation und die Einheiten\n\n#### Frage und Datenlage\n\n120 Anlagen mit Laufzeit in Stunden und Verbrauch in Litern. Was passiert mit\nKovarianz und Korrelation, wenn man Liter in Milliliter umrechnet?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(anlagen, aes(laufzeit, verbrauch)) +\n  geom_point(alpha = 0.6) +\n  labs(x = \"Laufzeit (h)\", y = \"Verbrauch (l)\")\n\nround(c(\n  cov_liter = cov(anlagen$laufzeit, anlagen$verbrauch),\n  cov_milliliter = cov(anlagen$laufzeit, anlagen$verbrauch * 1000),\n  r_liter = cor(anlagen$laufzeit, anlagen$verbrauch),\n  r_milliliter = cor(anlagen$laufzeit, anlagen$verbrauch * 1000)\n), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     cov_liter cov_milliliter        r_liter   r_milliliter \n       70.7551     70755.1254         0.9333         0.9333 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Die Korrelation von Hand, zur Kontrolle\nround(cov(anlagen$laufzeit, anlagen$verbrauch) /\n        (sd(anlagen$laufzeit) * sd(anlagen$verbrauch)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9333\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(sd_laufzeit = sd(anlagen$laufzeit), sd_verbrauch = sd(anlagen$verbrauch),\n        r_quadrat = cor(anlagen$laufzeit, anlagen$verbrauch)^2), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n sd_laufzeit sd_verbrauch    r_quadrat \n      4.9271      15.3864       0.8711 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 2: erster Blick auf zwei Merkmale. Die Punktwolke steigt und wirkt geradlinig.](korrelation_files/figure-html/fig-b2-kor-r-3.png){#fig-b2-kor-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, achse = plt.subplots(figsize=(7, 3.2))\nachse.scatter(anlagen[\"laufzeit\"], anlagen[\"verbrauch\"], s=14, alpha=0.6,\n              color=\"black\")\nachse.set_xlabel(\"Laufzeit (h)\")\nachse.set_ylabel(\"Verbrauch (l)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dasselbe Streudiagramm in Python.](korrelation_files/figure-html/fig-b2-kor-py-1.png){#fig-b2-kor-py width=100%}\n:::\n\n```{.python .cell-code}\nkov = np.cov(anlagen[\"laufzeit\"], anlagen[\"verbrauch\"])[0, 1]\nr = np.corrcoef(anlagen[\"laufzeit\"], anlagen[\"verbrauch\"])[0, 1]\nprint({\"cov_liter\": round(float(kov), 4),\n       \"cov_milliliter\": round(float(np.cov(anlagen[\"laufzeit\"],\n                                            anlagen[\"verbrauch\"] * 1000)[0, 1]), 1),\n       \"r_liter\": round(float(r), 4),\n       \"r_milliliter\": round(float(np.corrcoef(anlagen[\"laufzeit\"],\n                                               anlagen[\"verbrauch\"] * 1000)[0, 1]), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'cov_liter': 70.7551, 'cov_milliliter': 70755.1, 'r_liter': 0.9333, 'r_milliliter': 0.9333}\n```\n\n\n:::\n\n```{.python .cell-code}\nsx = anlagen[\"laufzeit\"].std(ddof=1)\nsy = anlagen[\"verbrauch\"].std(ddof=1)\nprint(\"von Hand:\", round(float(kov / (sx * sy)), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nvon Hand: 0.9333\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"sd_laufzeit\": round(float(sx), 4), \"sd_verbrauch\": round(float(sy), 4),\n       \"r_quadrat\": round(float(r ** 2), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'sd_laufzeit': 4.9271, 'sd_verbrauch': 15.3864, 'r_quadrat': 0.8711}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | in Litern | in Millilitern | Faktor |\n|---|---|---|---|\n| Kovarianz | **70.755** | **70 755** | **1000** |\n| Korrelation | **0.9333** | **0.9333** | **1** |\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Kovarianz 70.755 | Einheit: Stunden mal Liter | Die Zahl ist für sich genommen **nicht deutbar**. Ist 70 viel? Das hängt daran, in welchen Einheiten gemessen wurde. |\n| Kovarianz mal 1000 | genau der Umrechnungsfaktor | Am Zusammenhang hat sich nichts geändert, an der Zahl alles. |\n| Korrelation **unverändert** | 0.9333 in beiden Fällen | Im Nenner stehen die Standardabweichungen, und $s_y$ wächst um denselben Faktor 1000. Er kürzt sich heraus. Genau das ist der Zweck der Normierung. |\n| von Hand nachgerechnet | $70.755 / (4.927 \\cdot 15.386) = 0.9333$ | Die Korrelation ist nichts anderes als eine auf die Streuungen bezogene Kovarianz. |\n| $r^2$ | **0.871** | 87 Prozent der Streuung im Verbrauch gehen mit der Laufzeit einher. |\n\n::: {.note-box}\n**Was die Normierung kostet:** Die Kovarianz enthält die Grössenordnung des\nZusammenhangs, die Korrelation nicht. Ein $r$ von 0.93 sagt nichts darüber, **um\nwie viel** der Verbrauch je Stunde steigt — das sagt die Steigung einer\n[Regression](../regression/einfache-lineare-regression.qmd), hier rund 2.8 Liter\nje Stunde.\n\nFür die Frage \"wie eng\" ist die Korrelation richtig, für \"wie viel\" die\nRegression. Beide werden regelmässig verwechselt.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Laufzeit und Verbrauch hängen stark linear zusammen (Pearson $r$ = 0.93,\n> $r^2$ = 0.87, n = 120). Die Korrelation ist einheitenfrei und ändert sich\n> nicht, wenn der Verbrauch in Millilitern statt Litern gemessen wird.\n\n### Beispiel 3: Pearson gegen Spearman gegen Kendall\n\n#### Frage und Datenlage\n\nDrei Situationen, in denen die drei Masse auseinanderlaufen:\n\n1. ein **monotoner, aber gekrümmter** Zusammenhang: $y = e^{x/10}$\n2. ein **U-förmiger** Zusammenhang: $y = x^2$ plus Rauschen\n3. eine saubere Gerade **plus einen einzigen Ausreisser**\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx_exp <- 1:50\ny_exp <- exp(x_exp / 10)\n\nx_u <- seq(-3, 3, length.out = 80)\ny_u <- x_u^2 + normalwerte(6613, 80, 0, 0.5)\n\nx_rein <- 1:20\ny_rein <- x_rein + normalwerte(6614, 20, 0, 1)\nx_aus <- c(x_rein, 40)\ny_aus <- c(y_rein, -20)\n\npar(mfrow = c(1, 3), mar = c(4, 4, 2.5, 1))\nplot(x_exp, y_exp, pch = 16, cex = 0.7, main = \"monoton, gekrümmt\")\nplot(x_u, y_u, pch = 16, cex = 0.7, main = \"U-förmig\")\nplot(x_aus, y_aus, pch = 16, cex = 0.7, main = \"mit Ausreisser\")\npar(mfrow = c(1, 1))\n\nmasse <- function(x, y) {\n  c(pearson = cor(x, y),\n    spearman = cor(x, y, method = \"spearman\"),\n    kendall = cor(x, y, method = \"kendall\"))\n}\n\nround(rbind(gekruemmt = masse(x_exp, y_exp),\n            u_foermig = masse(x_u, y_u),\n            ohne_ausreisser = masse(x_rein, y_rein),\n            mit_ausreisser = masse(x_aus, y_aus)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                pearson spearman kendall\ngekruemmt         0.858    1.000   1.000\nu_foermig        -0.015   -0.015  -0.008\nohne_ausreisser   0.976    0.977   0.895\nmit_ausreisser   -0.108    0.708   0.714\n```\n\n\n:::\n\n```{.r .cell-code}\n# Beim U-Fall hilft die Transformation\nround(cor(abs(x_u), y_u), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.94\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: gekrümmt, U-förmig und mit Ausreisser.](korrelation_files/figure-html/fig-b3-kor-r-3.png){#fig-b3-kor-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nx_exp = np.arange(1, 51, dtype=float)\ny_exp = np.exp(x_exp / 10)\n\nx_u = np.linspace(-3, 3, 80)\ny_u = x_u ** 2 + normalwerte(6613, 80, 0, 0.5)\n\nx_rein = np.arange(1, 21, dtype=float)\ny_rein = x_rein + normalwerte(6614, 20, 0, 1)\nx_aus = np.append(x_rein, 40)\ny_aus = np.append(y_rein, -20)\n\nfig, achsen = plt.subplots(1, 3, figsize=(7, 2.8))\nfor achse, (x, y, titel) in zip(achsen, [\n        (x_exp, y_exp, \"monoton, gekrümmt\"),\n        (x_u, y_u, \"U-förmig\"),\n        (x_aus, y_aus, \"mit Ausreisser\")]):\n    achse.scatter(x, y, s=12, color=\"black\")\n    achse.set_title(titel, fontsize=9)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselben drei Fälle in Python.](korrelation_files/figure-html/fig-b3-kor-py-1.png){#fig-b3-kor-py width=100%}\n:::\n\n```{.python .cell-code}\ndef masse(x, y):\n    return {\"pearson\": np.corrcoef(x, y)[0, 1],\n            \"spearman\": stats.spearmanr(x, y).statistic,\n            \"kendall\": stats.kendalltau(x, y).statistic}\n\n\nprint(pd.DataFrame({\n    \"gekruemmt\": masse(x_exp, y_exp),\n    \"u_foermig\": masse(x_u, y_u),\n    \"ohne_ausreisser\": masse(x_rein, y_rein),\n    \"mit_ausreisser\": masse(x_aus, y_aus),\n}).T.round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 pearson  spearman  kendall\ngekruemmt          0.858     1.000    1.000\nu_foermig         -0.015    -0.015   -0.008\nohne_ausreisser    0.976     0.977    0.895\nmit_ausreisser    -0.108     0.708    0.714\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Nach Transformation |x| im U-Fall:\",\n      round(float(np.corrcoef(np.abs(x_u), y_u)[0, 1]), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNach Transformation |x| im U-Fall: 0.94\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Situation | Pearson | Spearman | Kendall |\n|---|---|---|---|\n| monoton, gekrümmt | 0.858 | **1.000** | **1.000** |\n| U-förmig | **-0.015** | **-0.015** | **-0.008** |\n| Gerade ohne Ausreisser | 0.976 | 0.977 | 0.895 |\n| **Gerade mit einem Ausreisser** | **-0.108** | **0.708** | **0.714** |\n\n| Fall | Was passiert |\n|---|---|\n| **Gekrümmt** | Spearman und Kendall liefern **exakt eins**, weil die Reihenfolge perfekt übereinstimmt — mehr misst eine Rangkorrelation nicht. Pearson bleibt bei 0.858, weil die Beziehung nicht geradlinig ist. Wer 0.858 als \"etwas Streuung\" liest, liegt falsch: Es gibt **keine** Streuung, nur Krümmung. |\n| **U-förmig** | Alle drei liefern praktisch null — und der Zusammenhang ist trotzdem perfekt deterministisch. Auch die Rangkorrelation versagt hier, denn der Zusammenhang ist nicht **monoton**: y fällt erst, dann steigt es. |\n| **Ausreisser** | Der spektakulärste Fall: Ein einziger von 21 Punkten dreht Pearson von **+0.976 auf -0.108** um. Spearman fällt nur auf 0.708, weil der Ausreisser rangmässig nur ein Punkt unter vielen ist. |\n\n::: {.note-box}\n**Was im U-Fall hilft:** Die Korrelation zwischen $\\lvert x \\rvert$ und $y$\nbeträgt **0.94**. Der Zusammenhang war also die ganze Zeit da — nur nicht in der\nForm, die eine Korrelation messen kann.\n\nDas ist das allgemeine Rezept: **Wenn das Bild eine Struktur zeigt, die die\nKennzahl nicht findet, transformiert man die Variablen, statt die Kennzahl zu\nverwerfen.** Übliche Kandidaten sind Logarithmus (bei multiplikativen\nZusammenhängen), Wurzel und Betrag.\n\nUnd der Grund, warum Kendall bei \"mit Ausreisser\" fast gleichauf mit Spearman\nliegt (0.714 gegen 0.708), obwohl es sonst kleinere Werte liefert: Beide zählen\ndenselben einen Punkt als eine Beobachtung.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Zwischen den Merkmalen besteht ein monotoner Zusammenhang (Spearman\n> $\\rho$ = 1.00, Kendall $\\tau$ = 1.00, n = 50). Die Pearson-Korrelation von 0.86\n> unterschätzt ihn, weil der Verlauf exponentiell und nicht linear ist.\n\n### Beispiel 4: Wann welches Mass\n\n#### Frage und Datenlage\n\nDie Wahl zwischen den drei Massen ist keine Geschmacksfrage. Sie folgt aus dem\nSkalenniveau und aus dem, was das Streudiagramm zeigt.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ordinale Daten: Zufriedenheit und Weiterempfehlung, je 1 bis 5\nzufrieden <- c(5, 4, 4, 5, 3, 2, 1, 3, 4, 5, 2, 3, 5, 4, 1, 2, 3, 4, 5, 3)\nempfehlen <- c(5, 5, 4, 4, 3, 2, 1, 4, 4, 5, 1, 3, 5, 3, 2, 2, 4, 5, 4, 3)\n\ntable(zufrieden, empfehlen)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         empfehlen\nzufrieden 1 2 3 4 5\n        1 1 1 0 0 0\n        2 1 2 0 0 0\n        3 0 0 3 2 0\n        4 0 0 1 2 2\n        5 0 0 0 2 3\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(pearson = cor(zufrieden, empfehlen),\n        spearman = cor(zufrieden, empfehlen, method = \"spearman\"),\n        kendall = cor(zufrieden, empfehlen, method = \"kendall\")), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n pearson spearman  kendall \n   0.864    0.846    0.759 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Kendall von Hand: konkordante gegen diskordante Paare\npaare <- expand.grid(i = seq_along(zufrieden), j = seq_along(zufrieden))\npaare <- paare[paare$i < paare$j, ]\nrichtung <- sign(zufrieden[paare$i] - zufrieden[paare$j]) *\n  sign(empfehlen[paare$i] - empfehlen[paare$j])\nc(konkordant = sum(richtung > 0), diskordant = sum(richtung < 0),\n  bindungen = sum(richtung == 0), paare = nrow(paare))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nkonkordant diskordant  bindungen      paare \n       125          7         58        190 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nzufrieden = np.array([5, 4, 4, 5, 3, 2, 1, 3, 4, 5, 2, 3, 5, 4, 1, 2, 3, 4, 5, 3])\nempfehlen = np.array([5, 5, 4, 4, 3, 2, 1, 4, 4, 5, 1, 3, 5, 3, 2, 2, 4, 5, 4, 3])\n\nprint(pd.crosstab(zufrieden, empfehlen))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncol_0  1  2  3  4  5\nrow_0               \n1      1  1  0  0  0\n2      1  2  0  0  0\n3      0  0  3  2  0\n4      0  0  1  2  2\n5      0  0  0  2  3\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"pearson\": round(float(np.corrcoef(zufrieden, empfehlen)[0, 1]), 3),\n       \"spearman\": round(float(stats.spearmanr(zufrieden, empfehlen).statistic), 3),\n       \"kendall\": round(float(stats.kendalltau(zufrieden, empfehlen).statistic), 3)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'pearson': 0.864, 'spearman': 0.846, 'kendall': 0.759}\n```\n\n\n:::\n\n```{.python .cell-code}\nkonkordant = diskordant = bindungen = 0\nfor i in range(len(zufrieden)):\n    for j in range(i + 1, len(zufrieden)):\n        richtung = (np.sign(zufrieden[i] - zufrieden[j])\n                    * np.sign(empfehlen[i] - empfehlen[j]))\n        if richtung > 0:\n            konkordant += 1\n        elif richtung < 0:\n            diskordant += 1\n        else:\n            bindungen += 1\n\nprint({\"konkordant\": konkordant, \"diskordant\": diskordant,\n       \"bindungen\": bindungen,\n       \"paare\": len(zufrieden) * (len(zufrieden) - 1) // 2})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'konkordant': 125, 'diskordant': 7, 'bindungen': 58, 'paare': 190}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nZwanzig Befragte, beide Merkmale auf einer Skala von 1 bis 5.\n\n| Mass | Wert | Zulässig? |\n|---|---|---|\n| Pearson | **0.864** | **nein** — er setzt voraus, dass der Abstand von 1 zu 2 dasselbe bedeutet wie der von 4 zu 5 |\n| Spearman | **0.846** | ja |\n| **Kendall** | **0.759** | ja, und **hier die bessere Wahl** |\n\nDie Aufteilung der 190 Paare in konkordante, diskordante und Bindungen zeigt,\nwarum:\n\n| Kategorie | Anzahl | Bedeutung |\n|---|---|---|\n| **konkordant** | **125** | Beide Merkmale zeigen in dieselbe Richtung: Wer zufriedener ist, empfiehlt auch eher. |\n| **diskordant** | **7** | Gegenläufig. |\n| **Bindungen** | **58** | Mindestens eines der beiden Merkmale ist bei beiden Befragten gleich. |\n| Summe | **190** | alle Paare aus 20 Befragten |\n\nOhne Bindungen wäre der Wert (125 - 7) / 190 = 0.621. Die Voreinstellung\n$\\tau_b$ rechnet die Bindungen aus dem Nenner heraus und kommt deshalb auf\n**0.759**.\n\n| Beobachtung | Deutung |\n|---|---|\n| Es gibt **58 Bindungen** von 190 Paaren | Also fast ein Drittel. Bei einer Skala mit fünf Stufen und zwanzig Befragten ist das unvermeidlich: Jeder Wert kommt mehrfach vor. |\n| Genau deshalb ist Kendall besser geeignet | Seine Varianten $\\tau_b$ und $\\tau_c$ behandeln Bindungen ausdrücklich; Spearman rechnet mit gemittelten Rängen und wird bei vielen Bindungen unzuverlässig. R und `scipy` verwenden voreingestellt $\\tau_b$. |\n| Kendall liegt mit 0.759 **unter** Spearman mit 0.846 | Der übliche Fall. Die beiden messen nicht dasselbe auf verschiedenen Skalen, sondern verschiedene Dinge — ein direkter Vergleich der Zahlen ist nicht sinnvoll. |\n| $(\\tau + 1)/2$ | Hier 0.88: der Anteil gleichgerichteter Paare. Das ist die einzige der drei Kennzahlen mit einer unmittelbaren Wahrscheinlichkeitsdeutung. |\n\n::: {.note-box}\n**Die Entscheidungsregel in vier Zeilen:**\n\n| Situation | Mass |\n|---|---|\n| beide metrisch, Streudiagramm zeigt eine Gerade | Pearson |\n| beide metrisch, Zusammenhang monoton aber krumm | Spearman |\n| mindestens eines ordinal, wenige Stufen, viele Bindungen | Kendall |\n| Zusammenhang nicht monoton (U-Form) | **keines** — transformieren oder ein Modell |\n:::\n\n#### Interpretation\n\nDie Reihenfolge ist immer dieselbe: erst Skalenniveau, dann Streudiagramm, dann\nKennzahl. Wer mit der Kennzahl anfängt, wählt sie nach Gewohnheit statt nach\nPassung.\n\n### Beispiel 5: Scheinkorrelation\n\n#### Frage und Datenlage\n\nDer klassische Fall: Glaceverkauf und Badeunfälle. Beide werden von der\nTemperatur getrieben, haben aber miteinander nichts zu tun. Was zeigt die\nKorrelation, und wie macht man den Schein sichtbar?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntemperatur <- 5 + 25 * lehmer(6615, 200)\nglace <- 20 + 3 * temperatur + normalwerte(6616, 200, 0, 10)\nbadeunfaelle <- 2 + 0.4 * temperatur + normalwerte(6617, 200, 0, 2)\n\nrest_glace <- resid(lm(glace ~ temperatur))\nrest_unfaelle <- resid(lm(badeunfaelle ~ temperatur))\n\npar(mfrow = c(1, 2), mar = c(4, 4, 2.5, 1))\nplot(glace, badeunfaelle, pch = 16, cex = 0.6, col = \"grey30\",\n     xlab = \"Glaceverkauf\", ylab = \"Badeunfälle\", main = \"roh\")\nplot(rest_glace, rest_unfaelle, pch = 16, cex = 0.6, col = \"grey30\",\n     xlab = \"Glace, Rest\", ylab = \"Unfälle, Rest\",\n     main = \"Temperatur herausgerechnet\")\npar(mfrow = c(1, 1))\n\nround(c(\n  glace_unfaelle = cor(glace, badeunfaelle),\n  glace_temperatur = cor(glace, temperatur),\n  unfaelle_temperatur = cor(badeunfaelle, temperatur),\n  partiell = cor(rest_glace, rest_unfaelle)\n), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     glace_unfaelle    glace_temperatur unfaelle_temperatur            partiell \n              0.767               0.900               0.829               0.085 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 5: links der scheinbare Zusammenhang, rechts derselbe nach Herausrechnen der Temperatur.](korrelation_files/figure-html/fig-b5-kor-r-1.png){#fig-b5-kor-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ntemperatur = 5 + 25 * lehmer(6615, 200)\nglace = 20 + 3 * temperatur + normalwerte(6616, 200, 0, 10)\nbadeunfaelle = 2 + 0.4 * temperatur + normalwerte(6617, 200, 0, 2)\n\nX = sm.add_constant(temperatur)\nrest_glace = sm.OLS(glace, X).fit().resid\nrest_unfaelle = sm.OLS(badeunfaelle, X).fit().resid\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nachsen[0].scatter(glace, badeunfaelle, s=10, color=\"0.3\")\nachsen[0].set_xlabel(\"Glaceverkauf\")\nachsen[0].set_ylabel(\"Badeunfälle\")\nachsen[0].set_title(\"roh\")\nachsen[1].scatter(rest_glace, rest_unfaelle, s=10, color=\"0.3\")\nachsen[1].set_xlabel(\"Glace, Rest\")\nachsen[1].set_ylabel(\"Unfälle, Rest\")\nachsen[1].set_title(\"Temperatur herausgerechnet\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselbe Gegenüberstellung in Python.](korrelation_files/figure-html/fig-b5-kor-py-1.png){#fig-b5-kor-py width=100%}\n:::\n\n```{.python .cell-code}\nprint({\n    \"glace_unfaelle\": round(float(np.corrcoef(glace, badeunfaelle)[0, 1]), 3),\n    \"glace_temperatur\": round(float(np.corrcoef(glace, temperatur)[0, 1]), 3),\n    \"unfaelle_temperatur\": round(float(np.corrcoef(badeunfaelle,\n                                                   temperatur)[0, 1]), 3),\n    \"partiell\": round(float(np.corrcoef(rest_glace, rest_unfaelle)[0, 1]), 3),\n})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'glace_unfaelle': 0.767, 'glace_temperatur': 0.9, 'unfaelle_temperatur': 0.829, 'partiell': 0.085}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Paar | $r$ | Deutung |\n|---|---|---|\n| Glace – Badeunfälle | **0.767** | Ein starker Zusammenhang, der jede Schwelle überschreitet. |\n| Glace – Temperatur | 0.900 | Die gemeinsame Ursache, erste Hälfte. |\n| Badeunfälle – Temperatur | 0.829 | Die gemeinsame Ursache, zweite Hälfte. |\n| **partiell**, Temperatur herausgerechnet | **0.085** | **Nichts bleibt übrig.** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| 0.767 ist **keine Fehlrechnung** | Der Zusammenhang existiert in den Daten. Was nicht existiert, ist eine Wirkung des einen auf das andere. |\n| Warum 0.767 herauskommt | Ungefähr das Produkt der beiden Einzelkorrelationen: $0.900 \\cdot 0.829 = 0.746$. Bei einer reinen gemeinsamen Ursache ist das genau die Erwartung. |\n| Die **partielle Korrelation** | Man rechnet die Temperatur aus beiden Merkmalen heraus (über eine Regression) und korreliert die **Reste**. Bleibt dort nichts übrig, war der Zusammenhang vollständig durch die dritte Grösse erklärt. |\n| 0.085 statt exakt 0 | Stichprobenzufall bei n = 200. |\n| Das rechte Streudiagramm | zeigt eine strukturlose Wolke gegenüber der klaren Steigung links. |\n\n::: {.note-box}\n**Was dieses Beispiel nicht zeigt: wie man die dritte Grösse findet.** Hier war\nsie bekannt, weil die Daten so konstruiert wurden. In echten Daten ist genau das\ndie Schwierigkeit — eine nicht erhobene gemeinsame Ursache bleibt unsichtbar,\nund keine Rechnung kann sie aufdecken.\n\nWas hilft, ist Fachwissen und ein Erhebungsdesign, das die Kandidaten mitmisst.\nSystematisch behandelt wird das unter\n[multipler Regression](../regression/multiple-lineare-regression.qmd) —\ntechnisch ist die partielle Korrelation oben genau ein Schritt davon.\n\nDie drei möglichen Erklärungen für jede beobachtete Korrelation bleiben:\n\n| Erklärung | Beispiel hier |\n|---|---|\n| $x$ wirkt auf $y$ | Glace verursacht Unfälle — inhaltlich absurd |\n| $y$ wirkt auf $x$ | Unfälle treiben den Glacekonsum — ebenso |\n| dritte Grösse treibt beide | Temperatur — das ist es |\n\nDie Daten allein unterscheiden nicht zwischen ihnen.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Glaceverkauf und Badeunfälle korrelieren mit $r$ = 0.77 (n = 200). Der\n> Zusammenhang geht vollständig auf die Aussentemperatur zurück: Wird sie aus\n> beiden Merkmalen herausgerechnet, bleibt eine partielle Korrelation von 0.09.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nDie Korrelation zwischen zwei Merkmalen beträgt 0.02. Haben sie nichts\nmiteinander zu tun?\n\n- [ ] Ja, der Wert liegt praktisch bei null ~ Ausgeschlossen ist damit nur ein\n      linearer Zusammenhang.\n- [x] Nicht unbedingt, ein U-förmiger Zusammenhang ergibt ebenfalls fast null ~\n      Richtig. Pearson misst nur den linearen Anteil. In Beispiel 3 liefert ein\n      deterministischer U-Zusammenhang r = -0.015, während die Korrelation mit\n      dem Betrag von x bei 0.94 liegt.\n- [ ] Der Wert ist zu klein zum Interpretieren ~ Interpretieren lässt er sich\n      gut, man muss nur wissen, was er misst.\n:::\n\n::: {.quiz}\nWarum ändert sich die Korrelation nicht, wenn eine Variable von Liter auf\nMilliliter umgerechnet wird, die Kovarianz aber schon?\n\n- [x] Weil im Nenner die Standardabweichungen stehen, die um denselben Faktor\n      wachsen ~ Richtig. Der Faktor 1000 kürzt sich heraus. Genau das ist der\n      Zweck der Normierung.\n- [ ] Weil die Korrelation gerundet wird ~ Mit Rundung hat es nichts zu tun.\n- [ ] Weil Milliliter und Liter dieselbe Einheit sind ~ Sie unterscheiden sich\n      um den Faktor 1000, und die Kovarianz zeigt das auch.\n:::\n\n::: {.quiz}\nEin einzelner Punkt kommt zu zwanzig anderen dazu, und die Pearson-Korrelation\nspringt von +0.98 auf -0.11. Was folgt daraus?\n\n- [x] Pearson ist nicht robust; ein Hebelpunkt kann das Vorzeichen umkehren ~\n      Richtig. Der Punkt liegt weit ausserhalb des x-Bereichs und zieht die\n      gedachte Gerade mit sich. Die Rangkorrelation fällt im selben Beispiel nur\n      auf 0.71, weil sie den Punkt als eine Beobachtung unter vielen zählt.\n- [ ] Die Daten wurden falsch erhoben ~ Möglich, folgt aber nicht daraus. Ein\n      extremer Wert kann echt sein.\n- [ ] Die Stichprobe ist zu klein ~ Bei grösserem n wäre die Wirkung kleiner,\n      aber das Problem bleibt dasselbe.\n:::\n\n::: {.quiz}\nZwei ordinale Merkmale mit je fünf Stufen sollen verglichen werden, n = 20. Was\nspricht für Kendall statt Spearman?\n\n- [x] Bei wenigen Stufen und vielen Bindungen ist Kendall zuverlässiger ~\n      Richtig. Seine Varianten behandeln Bindungen ausdrücklich, während Spearman\n      mit gemittelten Rängen rechnet. Zusätzlich hat Kendall eine unmittelbare\n      Deutung als Anteil gleichgerichteter Paare.\n- [ ] Kendall liefert grössere Werte ~ Er liefert typisch kleinere, weil er\n      etwas anderes misst.\n- [ ] Spearman ist für ordinale Daten nicht zulässig ~ Er ist zulässig, nur bei\n      vielen Bindungen weniger geeignet.\n:::\n\n::: {.quiz}\nGlaceverkauf und Badeunfälle korrelieren mit 0.77. Nach Herausrechnen der\nTemperatur bleibt 0.09. Was ist damit gezeigt?\n\n- [x] Der Zusammenhang lässt sich vollständig durch die gemeinsame Ursache\n      erklären ~ Richtig. Das ist die partielle Korrelation: Die Temperatur wird\n      aus beiden Merkmalen herausgerechnet, und aus den Resten bleibt nichts.\n- [ ] Glace verursacht keine Badeunfälle ~ Das ist die richtige inhaltliche\n      Schlussfolgerung, aber sie folgt aus dem Sachverstand, nicht aus der\n      Rechnung. Die Rechnung zeigt nur, dass die Temperatur genügt.\n- [ ] Die ursprüngliche Korrelation war falsch berechnet ~ Sie war korrekt. Der\n      Zusammenhang existiert in den Daten, nur nicht als Wirkung.\n:::\n\n::: {.quiz}\nEin Bericht nennt $r$ = 0.5 und beschreibt den Zusammenhang als \"halb so stark\nwie ein perfekter\". Was ist daran falsch?\n\n- [x] Geteilt wird die Streuung, und $r^2$ = 0.25 heisst 25 Prozent gemeinsame\n      Streuung ~ Richtig. Drei Viertel der Streuung kommen anderswo her. Die\n      Skala von r ist nicht linear in dem, was man umgangssprachlich unter\n      \"Stärke\" versteht.\n- [ ] Nichts, 0.5 ist die Hälfte von 1 ~ Rechnerisch ja, inhaltlich führt es in\n      die Irre.\n- [ ] r kann nicht als Stärke gedeutet werden ~ Es kann, nur nicht linear.\n:::\n\n## Verlinkte Ressourcen\n\n- [OpenIntro Statistics, Kapitel zu Zusammenhängen](https://www.openintro.org/book/os/)\n- [Spurious Correlations: Zusammenhänge ohne Ursache](https://www.tylervigen.com/spurious-correlations)\n- [Anscombes Quartett](https://en.wikipedia.org/wiki/Anscombe%27s_quartet)\n",
    "supporting": [
      "korrelation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}