{
  "hash": "702de59790f52e3f72d0abf71399970b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Zufallsvariablen\"\ndescription: \"Erwartungswert, Varianz und Verteilungsfunktion als Grundbegriffe.\"\ncategories: [\"Wahrscheinlichkeit\", \"Verteilungen\", \"R\", \"Python\"]\nquelle: [\"ESDS\"]\nseitentyp: konzept\nstand: entwurf\norder: 30\n---\n\n\n\n\n\n## Kernideen\n\n- Eine **Zufallsvariable** ist eine Abbildung des Ergebnisraums auf Zahlen — sie\n  macht den Zufall der Arithmetik zugänglich.\n- Die **Wahrscheinlichkeitsfunktion** gibt jedem Wert seine Wahrscheinlichkeit,\n  die **Verteilungsfunktion** summiert sie von unten auf.\n- Der **Erwartungswert** ist der Schwerpunkt der Verteilung und muss selbst kein\n  möglicher Wert sein.\n- **Varianz** und Standardabweichung beschreiben die Streuung des Modells.\n- Kennzahl aus **Daten** und Eigenschaft des **Modells** sind zweierlei — das\n  eine schätzt das andere.\n- Die Rechenregeln für Erwartungswert und Varianz sind verschieden: $E$ ist\n  immer linear, $\\text{Var}$ nicht.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Kombinatorik und Wahrscheinlichkeit](kombinatorik-wahrscheinlichkeit.qmd)\nfür den Wahrscheinlichkeitsbegriff und\n[bedingte Wahrscheinlichkeit](bedingte-wahrscheinlichkeit-bayes.qmd) für die\nUnabhängigkeit. Aus den\n[Lage- und Streuungsmassen](../grundlagen/lage-streuungsmasse.qmd) wird der\nUnterschied zwischen einer Kennzahl aus Daten und einer Eigenschaft des Modells\ngebraucht. Die konkreten Modelle folgen unter\n[diskrete Verteilungen](diskrete-verteilungen.qmd) und\n[stetige Verteilungen](stetige-verteilungen.qmd).\n:::\n\n### Vom Ereignis zur Zahl\n\nIn [Kombinatorik und Wahrscheinlichkeit](kombinatorik-wahrscheinlichkeit.qmd)\nwaren Ereignisse noch sprachlich beschrieben, etwa \"mindestens eine Sechs\".\nDamit lässt sich argumentieren, aber schlecht rechnen. Eine Zufallsvariable\nordnet jedem Ergebnis eine Zahl zu.\n\n| Begriff | Schreibweise | Was er beschreibt |\n|---|---|---|\n| Ergebnisraum | $\\Omega$ | alle möglichen Ausgänge des Zufallsvorgangs |\n| Zufallsvariable | $X: \\Omega \\to \\mathbb{R}$ | die Zuordnung einer Zahl zu jedem Ausgang |\n| Wahrscheinlichkeitsfunktion | $P(X = x)$ | wie wahrscheinlich ein bestimmter Wert ist |\n| Verteilungsfunktion | $F(x) = P(X \\le x)$ | wie wahrscheinlich höchstens dieser Wert ist |\n\nDer Zusammenhang zwischen den beiden letzten ist derselbe wie zwischen relativer\nund kumulierter [Häufigkeit](../grundlagen/haeufigkeiten.qmd), nur im Modell\nstatt in Daten.\n\n### Erwartungswert und Varianz\n\nDer Erwartungswert ist das mit Wahrscheinlichkeiten gewichtete Mittel der\nmöglichen Werte, die Varianz die gewichtete mittlere quadrierte Abweichung\ndavon:\n\n$$E(X) = \\sum_i x_i \\cdot P(X = x_i) \\qquad\n\\text{Var}(X) = \\sum_i (x_i - E(X))^2 \\cdot P(X = x_i)$$\n\nDer Erwartungswert ist der Wert, gegen den das arithmetische Mittel bei sehr\nvielen Wiederholungen strebt. Er muss selbst kein möglicher Wert sein — der\nErwartungswert eines Würfels ist 3.5.\n\n### Die Rechenregeln\n\nSie sehen sich ähnlich und verhalten sich verschieden:\n\n| Regel | Erwartungswert | Varianz |\n|---|---|---|\n| Konstante addieren | $E(X + b) = E(X) + b$ | $\\text{Var}(X + b) = \\text{Var}(X)$ |\n| Mit Konstante multiplizieren | $E(aX) = a \\, E(X)$ | $\\text{Var}(aX) = a^2 \\text{Var}(X)$ |\n| Summe zweier Variablen | $E(X + Y) = E(X) + E(Y)$, **immer** | $\\text{Var}(X + Y) = \\text{Var}(X) + \\text{Var}(Y)$, **nur bei Unabhängigkeit** |\n\nDrei Punkte, die daraus folgen und regelmässig verwechselt werden:\n\n1. **Verschieben ändert die Streuung nicht.** Alle Werte um 10 erhöhen\n   verschiebt den Schwerpunkt, nicht die Breite.\n2. **Strecken wirkt quadratisch auf die Varianz.** Verdoppelt man alle Werte,\n   vervierfacht sich die Varianz — die Standardabweichung verdoppelt sich.\n3. **Der Erwartungswert ist immer additiv**, auch bei abhängigen Variablen. Die\n   Varianz nicht: Bei Abhängigkeit kommt $2\\,\\text{Cov}(X,Y)$ dazu.\n\n### Modell und Daten\n\nBegrifflich streng zu trennen:\n\n| Aus dem Modell | Aus Daten |\n|---|---|\n| Erwartungswert $E(X)$ | Mittelwert $\\bar{x}$ |\n| Varianz $\\text{Var}(X)$ | empirische Varianz $s^2$ |\n| Verteilungsfunktion $F(x)$ | empirische Verteilungsfunktion |\n\nSie fallen nicht zusammen. Das eine **schätzt** das andere, und wie gut, hängt\nvon der Anzahl Beobachtungen ab — Beispiel 2 zeigt es.\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Die Augensumme zweier Würfel\n\n#### Frage und Datenlage\n\nZwei Würfel, Zufallsvariable ist die Augensumme. Der Ergebnisraum hat 36\ngleichwahrscheinliche Elemente, die Zufallsvariable nimmt elf Werte an — und\ndiese sind **nicht** gleich wahrscheinlich.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkombinationen <- expand.grid(wurf1 = 1:6, wurf2 = 1:6)\nsumme <- kombinationen$wurf1 + kombinationen$wurf2\n\ntable(summe)                        # wie viele Kombinationen je Summe\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsumme\n 2  3  4  5  6  7  8  9 10 11 12 \n 1  2  3  4  5  6  5  4  3  2  1 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(prop.table(table(summe)), 4)  # die Wahrscheinlichkeitsfunktion\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsumme\n     2      3      4      5      6      7      8      9     10     11     12 \n0.0278 0.0556 0.0833 0.1111 0.1389 0.1667 0.1389 0.1111 0.0833 0.0556 0.0278 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(cumsum(prop.table(table(summe))), 4)   # die Verteilungsfunktion\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     2      3      4      5      6      7      8      9     10     11     12 \n0.0278 0.0833 0.1667 0.2778 0.4167 0.5833 0.7222 0.8333 0.9167 0.9722 1.0000 \n```\n\n\n:::\n\n```{.r .cell-code}\nwerte <- as.numeric(names(table(summe)))\np <- as.numeric(prop.table(table(summe)))\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nplot(werte, p, type = \"h\", lwd = 6, col = \"grey60\", ylim = c(0, 0.2),\n     xlab = \"Augensumme\", ylab = \"P(X = x)\", main = \"Wahrscheinlichkeit\")\nplot(werte, cumsum(p), type = \"s\", lwd = 2, ylim = c(0, 1),\n     xlab = \"Augensumme\", ylab = \"F(x)\", main = \"Verteilungsfunktion\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 1: links die Wahrscheinlichkeitsfunktion, rechts die Verteilungsfunktion.](zufallsvariablen_files/figure-html/fig-b1-zv-r-1.png){#fig-b1-zv-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nsumme = np.array([a + b for a, b in product(range(1, 7), repeat=2)])\nwerte, anzahl = np.unique(summe, return_counts=True)\np = anzahl / len(summe)\n\nprint(dict(zip(werte.tolist(), anzahl.tolist())))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{2: 1, 3: 2, 4: 3, 5: 4, 6: 5, 7: 6, 8: 5, 9: 4, 10: 3, 11: 2, 12: 1}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(dict(zip(werte.tolist(), p.round(4).tolist())))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{2: 0.0278, 3: 0.0556, 4: 0.0833, 5: 0.1111, 6: 0.1389, 7: 0.1667, 8: 0.1389, 9: 0.1111, 10: 0.0833, 11: 0.0556, 12: 0.0278}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(np.cumsum(p).round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[0.0278 0.0833 0.1667 0.2778 0.4167 0.5833 0.7222 0.8333 0.9167 0.9722\n 1.    ]\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nachsen[0].vlines(werte, 0, p, lw=6, color=\"0.6\")\nachsen[0].set_ylim(0, 0.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(0.0, 0.2)\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[0].set_xlabel(\"Augensumme\")\nachsen[0].set_ylabel(\"P(X = x)\")\nachsen[0].set_title(\"Wahrscheinlichkeit\")\nachsen[1].step(werte, np.cumsum(p), where=\"post\", lw=2, color=\"black\")\nachsen[1].set_ylim(0, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(0.0, 1.0)\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[1].set_xlabel(\"Augensumme\")\nachsen[1].set_ylabel(\"F(x)\")\nachsen[1].set_title(\"Verteilungsfunktion\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselben beiden Funktionen in Python.](zufallsvariablen_files/figure-html/fig-b1-zv-py-1.png){#fig-b1-zv-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Augensumme | 2 | 3 | 4 | 5 | 6 | **7** | 8 | 9 | 10 | 11 | 12 |\n|---|---|---|---|---|---|---|---|---|---|---|---|\n| Kombinationen | 1 | 2 | 3 | 4 | 5 | **6** | 5 | 4 | 3 | 2 | 1 |\n| $P(X = x)$ | 0.028 | 0.056 | 0.083 | 0.111 | 0.139 | **0.167** | 0.139 | 0.111 | 0.083 | 0.056 | 0.028 |\n| $F(x)$ | 0.028 | 0.083 | 0.167 | 0.278 | 0.417 | **0.583** | 0.722 | 0.833 | 0.917 | 0.972 | **1.000** |\n\n| Ausgabe | Wie sie zu lesen ist |\n|---|---|\n| Die Kombinationen summieren sich zu **36** | Alle Ausgänge sind gleich wahrscheinlich; ungleich wird erst die **Summe**, weil es für die 7 sechs Wege gibt und für die 2 nur einen. |\n| $P(X = 7) = 6/36 = 0.167$ | Die 7 ist die wahrscheinlichste Augensumme — sechsmal so wahrscheinlich wie die 2. |\n| Die Funktion ist **symmetrisch** | $P(X = 2) = P(X = 12)$, und so weiter. Das ist die Folge davon, dass beide Würfel dieselbe Verteilung haben. |\n| $F(7) = 0.583$ | Mit 58.3 Prozent Wahrscheinlichkeit fällt die Summe **höchstens** 7. |\n| $F(12) = 1.000$ | Immer. Die Verteilungsfunktion endet definitionsgemäss bei eins. |\n| Die Verteilungsfunktion ist eine **Treppe** | Sie springt an jedem möglichen Wert um dessen Wahrscheinlichkeit und ist dazwischen konstant. Bei stetigen Zufallsvariablen wird daraus eine glatte Kurve. |\n\n::: {.note-box}\n**Was die Verteilungsfunktion leistet, was die Wahrscheinlichkeitsfunktion\nnicht kann:** Fragen der Form \"höchstens\", \"mindestens\" und \"zwischen\" beantwortet\nsie durch Ablesen statt durch Summieren.\n\n| Frage | Rechnung |\n|---|---|\n| $P(X \\le 7)$ | $F(7) = 0.583$ |\n| $P(X > 7)$ | $1 - F(7) = 0.417$ |\n| $P(5 \\le X \\le 9)$ | $F(9) - F(4) = 0.833 - 0.167 = 0.667$ |\n\nBeim letzten Fall ist die Falle: Abgezogen wird $F(4)$, nicht $F(5)$ — sonst\nfällt die 5 selbst mit heraus.\n:::\n\n#### Interpretation\n\nDie Zufallsvariable hat den Ergebnisraum von 36 auf elf Werte verdichtet. Das\nist der Zweck: Aus einer Liste von Ausgängen wird eine Verteilung, mit der sich\nrechnen lässt.\n\n### Beispiel 2: Erwartungswert, Varianz und die Gegenprobe\n\n#### Frage und Datenlage\n\nErwartungswert und Varianz der Augensumme — einmal exakt aus dem Modell und\neinmal aus 200 000 simulierten Würfen. Wie nahe kommen sich die beiden, und wie\nschnell?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\new <- sum(werte * p)\nvarianz <- sum((werte - ew)^2 * p)\n\nround(c(erwartungswert = ew, varianz = varianz,\n        standardabweichung = sqrt(varianz)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    erwartungswert            varianz standardabweichung \n            7.0000             5.8333             2.4152 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Gegenprobe: 200000 simulierte Wuerfe aus dem Kongruenzgenerator\nn <- 200000\nu <- lehmer(9911, 2 * n)\nwuerfe <- matrix(floor(6 * u) + 1, ncol = 2, byrow = TRUE)\nsim <- rowSums(wuerfe)\n\nround(c(mittel = mean(sim), varianz = var(sim)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n mittel varianz \n 7.0094  5.8303 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Wie schnell naehert sich der Mittelwert dem Erwartungswert?\nfor (k in c(100, 1000, 10000, 100000, 200000)) {\n  cat(sprintf(\"n = %6d | Mittel %.4f | Abweichung %.4f\\n\",\n              k, mean(sim[1:k]), abs(mean(sim[1:k]) - ew)))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn =    100 | Mittel 6.8800 | Abweichung 0.1200\nn =   1000 | Mittel 6.8450 | Abweichung 0.1550\nn =  10000 | Mittel 6.9771 | Abweichung 0.0229\nn = 100000 | Mittel 7.0087 | Abweichung 0.0087\nn = 200000 | Mittel 7.0094 | Abweichung 0.0094\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\new = float((werte * p).sum())\nvarianz = float(((werte - ew) ** 2 * p).sum())\n\nprint({\"erwartungswert\": round(ew, 4), \"varianz\": round(varianz, 4),\n       \"standardabweichung\": round(np.sqrt(varianz), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'erwartungswert': 7.0, 'varianz': 5.8333, 'standardabweichung': np.float64(2.4152)}\n```\n\n\n:::\n\n```{.python .cell-code}\nn = 200000\nu = lehmer(9911, 2 * n)\nwuerfe = (np.floor(6 * u) + 1).astype(int).reshape(n, 2)\nsim = wuerfe.sum(axis=1)\n\nprint({\"mittel\": round(float(sim.mean()), 4),\n       \"varianz\": round(float(sim.var(ddof=1)), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'mittel': 7.0094, 'varianz': 5.8303}\n```\n\n\n:::\n\n```{.python .cell-code}\nfor k in [100, 1000, 10000, 100000, 200000]:\n    mittel = sim[:k].mean()\n    print(f\"n = {k:6d} | Mittel {mittel:.4f} | Abweichung {abs(mittel - ew):.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn =    100 | Mittel 6.8800 | Abweichung 0.1200\nn =   1000 | Mittel 6.8450 | Abweichung 0.1550\nn =  10000 | Mittel 6.9771 | Abweichung 0.0229\nn = 100000 | Mittel 7.0087 | Abweichung 0.0087\nn = 200000 | Mittel 7.0094 | Abweichung 0.0094\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | aus dem **Modell** | aus **200 000 Würfen** |\n|---|---|---|\n| Erwartungswert / Mittelwert | **7.0000** | **7.0094** |\n| Varianz | **5.8333** | **5.8303** |\n| Standardabweichung | 2.4152 | 2.4146 |\n\nUnd die Annäherung mit wachsender Anzahl:\n\n| n | Mittelwert | Abweichung von 7 |\n|---|---|---|\n| 100 | 6.8800 | **0.1200** |\n| 1 000 | 6.8450 | **0.1550** |\n| 10 000 | 6.9771 | 0.0229 |\n| 100 000 | 7.0087 | 0.0087 |\n| 200 000 | 7.0094 | 0.0094 |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Der Erwartungswert ist **exakt 7** | Kein Rundungsergebnis: Die Verteilung ist symmetrisch um 7, und der Schwerpunkt einer symmetrischen Verteilung ist ihr Symmetriepunkt. |\n| Die Varianz ist $35/6 = 5.8\\overline{3}$ | Auch exakt. Für einen Würfel allein beträgt sie $35/12$; bei zwei **unabhängigen** Würfeln addieren sich die Varianzen. |\n| Die Abweichung von 1000 auf 10 000 fällt um den Faktor 7 | Nicht monoton — bei $n = 1000$ war sie zufällig grösser als bei 100. Erwartet wird ein Abfall mit $1/\\sqrt{n}$, also von 100 auf 10 000 um den Faktor 10. |\n| Bei 200 000 Würfen bleiben 0.0094 übrig | Das ist kein Fehler der Simulation, sondern der Rest an Zufall. Der Standardfehler beträgt $2.415/\\sqrt{200000} = 0.0054$; die beobachtete Abweichung liegt in dieser Grössenordnung. |\n\n::: {.note-box}\n**Was dieser Vergleich zeigt und was nicht.** Er zeigt das Gesetz der grossen\nZahlen: Der Mittelwert nähert sich dem Erwartungswert. Er zeigt **nicht**, dass\ndie beiden dasselbe sind.\n\nDer Unterschied ist der Kern der schliessenden Statistik: Man hat nie den\nErwartungswert, sondern immer nur einen Mittelwert aus endlich vielen\nBeobachtungen — und die Frage, wie weit der danebenliegen kann, führt direkt zum\n[Konfidenzintervall](../inferenz/schaetzen-konfidenzintervalle.qmd).\n\nUnd ein Detail zur Simulation: `var(sim)` in R teilt durch $n-1$, die\nModellvarianz nicht durch irgendetwas. Bei 200 000 Werten ist der Unterschied\nunsichtbar; bei kleinen Stichproben ist er genau die\n[Bessel-Korrektur](../grundlagen/lage-streuungsmasse.qmd).\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Augensumme zweier Würfel hat den Erwartungswert 7 und die Varianz 5.83\n> (Standardabweichung 2.42). Eine Simulation über 200 000 Würfe ergibt einen\n> Mittelwert von 7.009 und eine empirische Varianz von 5.830.\n\n### Beispiel 3: Die Rechenregeln nachgerechnet\n\n#### Frage und Datenlage\n\nEin einzelner Würfel, $E(X) = 3.5$ und $\\text{Var}(X) = 35/12 = 2.9167$. Was\npassiert bei Verschiebung, Streckung und Summierung?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- 1:6\npx <- rep(1 / 6, 6)\n\nkennzahlen <- function(werte, wkeit) {\n  e <- sum(werte * wkeit)\n  c(erwartungswert = e, varianz = sum((werte - e)^2 * wkeit))\n}\n\nround(rbind(\n  \"X (ein Wuerfel)\" = kennzahlen(x, px),\n  \"X + 10\"          = kennzahlen(x + 10, px),\n  \"2X\"              = kennzahlen(2 * x, px),\n  \"2X - 1\"          = kennzahlen(2 * x - 1, px)\n), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                erwartungswert varianz\nX (ein Wuerfel)            3.5  2.9167\nX + 10                    13.5  2.9167\n2X                         7.0 11.6667\n2X - 1                     6.0 11.6667\n```\n\n\n:::\n\n```{.r .cell-code}\n# Summe zweier unabhaengiger Wuerfel: addieren sich die Varianzen?\nround(c(zwei_mal_einzeln = 2 * kennzahlen(x, px)[\"varianz\"],\n        summe_direkt = varianz), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nzwei_mal_einzeln.varianz             summe_direkt \n                  5.8333                   5.8333 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Und wenn sie nicht unabhaengig sind: Y = X, also perfekt abhaengig\nround(kennzahlen(2 * x, px), 4)   # X + Y mit Y = X ist dasselbe wie 2X\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nerwartungswert        varianz \n        7.0000        11.6667 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nx = np.arange(1, 7, dtype=float)\npx = np.full(6, 1 / 6)\n\n\ndef kennzahlen(werte, wkeit):\n    e = float((werte * wkeit).sum())\n    return {\"erwartungswert\": e,\n            \"varianz\": float(((werte - e) ** 2 * wkeit).sum())}\n\n\nprint(pd.DataFrame([kennzahlen(x, px), kennzahlen(x + 10, px),\n                    kennzahlen(2 * x, px), kennzahlen(2 * x - 1, px)],\n                   index=[\"X (ein Würfel)\", \"X + 10\", \"2X\", \"2X - 1\"]).round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                erwartungswert  varianz\nX (ein Würfel)             3.5   2.9167\nX + 10                    13.5   2.9167\n2X                         7.0  11.6667\n2X - 1                     6.0  11.6667\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"zwei_mal_einzeln\": round(2 * kennzahlen(x, px)[\"varianz\"], 4),\n       \"summe_direkt\": round(varianz, 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'zwei_mal_einzeln': 5.8333, 'summe_direkt': 5.8333}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(kennzahlen(2 * x, px))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'erwartungswert': 7.0, 'varianz': 11.666666666666666}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Variable | Erwartungswert | Varianz | Regel |\n|---|---|---|---|\n| $X$ (ein Würfel) | **3.5000** | **2.9167** | — |\n| $X + 10$ | **13.5000** | **2.9167** | $E$ verschiebt sich, $\\text{Var}$ **nicht** |\n| $2X$ | **7.0000** | **11.6667** | $E$ verdoppelt sich, $\\text{Var}$ **vervierfacht** sich |\n| $2X - 1$ | 6.0000 | 11.6667 | beide Regeln zusammen |\n\n| Beobachtung | Erklärung |\n|---|---|\n| $X + 10$: die Varianz bleibt **exakt** gleich | Eine Verschiebung ändert alle Abweichungen vom Mittel nicht — sie verschiebt Werte und Schwerpunkt um denselben Betrag. |\n| $2X$: die Varianz wird **viermal** so gross | Weil sie quadrierte Abweichungen misst: $(2a)^2 = 4a^2$. Die Standardabweichung verdoppelt sich, wie erwartet. |\n| $2X$ und \"zwei Würfel\" haben **denselben** Erwartungswert | Beide 7. Die Additivität des Erwartungswerts gilt unabhängig davon, ob die Variablen zusammenhängen. |\n| Aber **verschiedene** Varianzen | $2X$ hat 11.67, die Summe zweier unabhängiger Würfel 5.83 — genau die Hälfte, also $2 \\cdot 2.9167$. |\n\n::: {.note-box}\n**Der Unterschied zwischen \"zweimal derselbe Würfel\" und \"zwei Würfel\" ist der\nKern der ganzen Varianzrechnung.**\n\n| | $2X$ (ein Würfel, verdoppelt) | $X + Y$ (zwei unabhängige Würfel) |\n|---|---|---|\n| Erwartungswert | 7 | 7 |\n| Varianz | $4 \\cdot 2.9167 = 11.67$ | $2 \\cdot 2.9167 = 5.83$ |\n| mögliche Werte | 2, 4, 6, 8, 10, 12 | 2 bis 12, alle |\n| Warum | Die Abweichungen verstärken sich **immer** gemeinsam. | Sie gleichen sich **teilweise** aus. |\n\nGenau dieser Ausgleich ist der Grund, warum der Standardfehler eines Mittelwerts\nmit $\\sqrt{n}$ und nicht mit $n$ kleiner wird: Der Mittelwert aus $n$\nunabhängigen Werten hat die Varianz $\\sigma^2/n$, also die Standardabweichung\n$\\sigma/\\sqrt{n}$.\n\nUnd daraus folgt der wichtigste praktische Satz: **Bei abhängigen Beobachtungen\ngilt das nicht.** Kommt $2\\,\\text{Cov}(X,Y)$ dazu, ist der Standardfehler zu\nklein gerechnet — der Grund, warum [Zeitreihen](../zeitreihen/zeitreihen-grundlagen.qmd)\nund geschachtelte Daten eigene Verfahren brauchen.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Eine Verschiebung um 10 erhöht den Erwartungswert um 10 und lässt die Varianz\n> unverändert (2.9167). Eine Streckung um den Faktor 2 verdoppelt den\n> Erwartungswert und vervierfacht die Varianz (11.6667).\n\n### Beispiel 4: Ein Erwartungswert, den niemand erlebt\n\n#### Frage und Datenlage\n\nEine Versicherung kalkuliert eine Police. Der Jahresschaden je Vertrag ist eine\nZufallsvariable mit vier möglichen Werten:\n\n| Schaden | 0 | 500 | 5 000 | 50 000 |\n|---|---|---|---|---|\n| Wahrscheinlichkeit | 0.930 | 0.050 | 0.018 | 0.002 |\n\nWie hoch muss die Prämie sein — und was sagt der Erwartungswert über den\nEinzelfall?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschaden <- c(0, 500, 5000, 50000)\nwkeit <- c(0.930, 0.050, 0.018, 0.002)\n\nsum(wkeit)                       # muss eins ergeben\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\nkennz <- kennzahlen(schaden, wkeit)\nround(c(kennz, standardabweichung = sqrt(kennz[\"varianz\"])), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            erwartungswert                    varianz \n                    215.00                 5416275.00 \nstandardabweichung.varianz \n                   2327.29 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(praemie_mit_20_prozent = kennz[\"erwartungswert\"] * 1.2,\n        anteil_ohne_schaden = wkeit[1],\n        anteil_ueber_praemie = sum(wkeit[-1])), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npraemie_mit_20_prozent.erwartungswert                   anteil_ohne_schaden \n                               258.00                                  0.93 \n                 anteil_ueber_praemie \n                                 0.07 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Was passiert bei 10000 unabhaengigen Vertraegen?\nn_vertraege <- 10000\nround(c(erwartete_summe = n_vertraege * kennz[\"erwartungswert\"],\n        sd_der_summe = sqrt(n_vertraege * kennz[\"varianz\"]),\n        sd_je_vertrag = sqrt(kennz[\"varianz\"] / n_vertraege)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nerwartete_summe.erwartungswert           sd_der_summe.varianz \n                    2150000.00                      232728.92 \n         sd_je_vertrag.varianz \n                         23.27 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nschaden = np.array([0, 500, 5000, 50000], dtype=float)\nwkeit = np.array([0.930, 0.050, 0.018, 0.002])\n\nprint(\"Summe der Wahrscheinlichkeiten:\", wkeit.sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSumme der Wahrscheinlichkeiten: 1.0\n```\n\n\n:::\n\n```{.python .cell-code}\nkennz = kennzahlen(schaden, wkeit)\nprint({**{k: round(v, 2) for k, v in kennz.items()},\n       \"standardabweichung\": round(np.sqrt(kennz[\"varianz\"]), 2)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'erwartungswert': 215.0, 'varianz': 5416275.0, 'standardabweichung': np.float64(2327.29)}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"praemie_mit_20_prozent\": round(kennz[\"erwartungswert\"] * 1.2, 2),\n       \"anteil_ohne_schaden\": wkeit[0],\n       \"anteil_ueber_praemie\": round(wkeit[1:].sum(), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'praemie_mit_20_prozent': 258.0, 'anteil_ohne_schaden': np.float64(0.93), 'anteil_ueber_praemie': np.float64(0.07)}\n```\n\n\n:::\n\n```{.python .cell-code}\nn_vertraege = 10000\nprint({\"erwartete_summe\": round(n_vertraege * kennz[\"erwartungswert\"], 2),\n       \"sd_der_summe\": round(np.sqrt(n_vertraege * kennz[\"varianz\"]), 2),\n       \"sd_je_vertrag\": round(np.sqrt(kennz[\"varianz\"] / n_vertraege), 2)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'erwartete_summe': 2150000.0, 'sd_der_summe': np.float64(232728.92), 'sd_je_vertrag': np.float64(23.27)}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | Wert | Wie sie zu lesen ist |\n|---|---|---|\n| **Erwartungswert** | **215.00** | Der mittlere Jahresschaden je Vertrag. |\n| **Standardabweichung** | **2 327.29** | Mehr als das **Zehnfache** des Erwartungswerts. |\n| Prämie mit 20 Prozent Zuschlag | 258.00 | |\n| Anteil ohne jeden Schaden | **93.0 %** | |\n| Anteil mit Schaden über der Prämie | **7.0 %** | |\n\n| Beobachtung | Erklärung |\n|---|---|\n| **Kein einziger Vertrag erlebt 215 Franken Schaden** | Der Erwartungswert ist keiner der vier möglichen Werte. Er beschreibt den Durchschnitt über viele Verträge, nicht einen Einzelfall. |\n| 93 Prozent zahlen und bekommen nichts | Und 0.2 Prozent bekommen das Zweihundertfache ihrer Prämie. Genau das ist Versicherung. |\n| Die Standardabweichung von 2 327 ist **zehnmal** so gross wie der Erwartungswert | Der Grund ist der eine seltene Grossschaden: Er trägt $0.002 \\cdot (50000-215)^2 = 4.96$ Millionen zur Varianz von 5.42 Millionen bei, also **91 Prozent**. |\n| Bei 10 000 Verträgen | erwartete Schadensumme 2.15 Millionen, Standardabweichung der Summe 232 730 — also nur **11 Prozent** der Summe. |\n| Je Vertrag gerechnet | sinkt die Standardabweichung von 2 327 auf **23.27** | Der Faktor $\\sqrt{10000} = 100$. **Das ist das Geschäftsmodell:** Nicht das Risiko verschwindet, sondern seine relative Schwankung. |\n\n::: {.note-box}\n**Warum ein Erwartungswert allein für eine Entscheidung nicht genügt**, in drei\nFällen:\n\n| Fall | Warum |\n|---|---|\n| **Einzelfall statt Wiederholung** | Wer eine Police einmal kauft, erlebt entweder 0 oder 50 000 — nie 215. |\n| **Sehr schiefe Verteilung** | Der Erwartungswert liegt hier zwischen dem 93. und dem 98. Perzentil. Der **Median** des Schadens ist 0. |\n| **Begrenzte Verlusttragfähigkeit** | Ein Unternehmen, das 50 000 nicht verkraftet, kann sich an einem positiven Erwartungswert nicht orientieren. |\n\nDeshalb gehört zu jedem Erwartungswert die Streuung — und bei stark schiefen\nVerteilungen zusätzlich ein Quantil, etwa der Wert, der in 99 Prozent der Fälle\nnicht überschritten wird.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Der erwartete Jahresschaden je Vertrag beträgt 215 Franken bei einer\n> Standardabweichung von 2 327 Franken; 93 Prozent der Verträge verursachen\n> keinen Schaden. Über 10 000 unabhängige Verträge sinkt die Standardabweichung\n> je Vertrag auf 23 Franken, weshalb ein Zuschlag von 20 Prozent auf den\n> Erwartungswert die Schwankung abdeckt.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nDer Erwartungswert einer Zufallsvariablen beträgt 3.5, aber die Variable kann\nnur ganzzahlige Werte annehmen. Ist das ein Widerspruch?\n\n- [x] Nein, der Erwartungswert muss kein möglicher Wert sein ~ Richtig. Er ist\n      der Schwerpunkt der Verteilung, also ein gewichteter Durchschnitt. Bei\n      einem Würfel liegt er genau zwischen 3 und 4.\n- [ ] Ja, ein Erwartungswert muss vorkommen können ~ Er beschreibt den\n      Durchschnitt über viele Wiederholungen, nicht einen Einzelfall.\n- [ ] Nur bei diskreten Variablen ist das erlaubt ~ Es gilt allgemein.\n:::\n\n::: {.quiz}\nAlle Werte einer Zufallsvariablen werden um 10 erhöht. Was passiert mit\nErwartungswert und Varianz?\n\n- [x] Der Erwartungswert steigt um 10, die Varianz bleibt gleich ~ Richtig. Eine\n      Verschiebung ändert die Abweichungen vom Mittel nicht, weil sich Werte und\n      Schwerpunkt gemeinsam verschieben.\n- [ ] Beide steigen um 10 ~ Die Varianz misst Streuung, nicht Lage.\n- [ ] Beide bleiben gleich ~ Der Erwartungswert verschiebt sich mit.\n:::\n\n::: {.quiz}\nWarum hat $2X$ eine viermal so grosse Varianz wie $X$, die Summe zweier\nunabhängiger Würfel aber nur eine doppelt so grosse?\n\n- [x] Bei $2X$ verstärken sich die Abweichungen immer gemeinsam, bei zwei Würfeln\n      gleichen sie sich teilweise aus ~ Richtig. Deshalb gilt\n      $\\text{Var}(2X) = 4\\,\\text{Var}(X)$, aber\n      $\\text{Var}(X+Y) = \\text{Var}(X) + \\text{Var}(Y)$ bei Unabhängigkeit.\n      Genau dieser Ausgleich erzeugt den Faktor Wurzel n beim Standardfehler.\n- [ ] Weil zwei Würfel mehr mögliche Werte haben ~ Die Anzahl möglicher Werte\n      erklärt die Varianz nicht.\n- [ ] Weil bei $2X$ falsch gerechnet wurde ~ Beide Rechnungen sind korrekt und\n      beschreiben verschiedene Zufallsvariablen.\n:::\n\n::: {.quiz}\nEine Police hat einen erwarteten Schaden von 215 Franken bei einer\nStandardabweichung von 2 327. Was folgt für die Kalkulation?\n\n- [x] Der Erwartungswert genügt nicht; über viele Verträge sinkt aber die\n      relative Schwankung ~ Richtig. Bei 10 000 unabhängigen Verträgen fällt die\n      Standardabweichung je Vertrag von 2 327 auf 23 Franken. Genau darauf beruht\n      das Geschäftsmodell.\n- [ ] Die Prämie muss 2 327 Franken betragen ~ Das wäre die Streuung eines\n      Einzelfalls, nicht der zu erwartende Aufwand.\n- [ ] Die Verteilung ist fehlerhaft, weil die Streuung grösser als der Mittelwert\n      ist ~ Bei stark schiefen Verteilungen ist das normal.\n:::\n\n::: {.quiz}\nEin Mittelwert aus 200 000 Simulationen beträgt 7.0094, der Erwartungswert\ngenau 7. Ist die Simulation fehlerhaft?\n\n- [x] Nein, die Abweichung liegt im Bereich des Zufalls ~ Richtig. Der\n      Standardfehler beträgt hier 2.42 geteilt durch die Wurzel aus 200 000, also\n      0.005. Eine Abweichung von 0.009 ist damit unauffällig.\n- [ ] Ja, bei so vielen Wiederholungen müsste 7.0000 herauskommen ~ Der\n      Mittelwert nähert sich dem Erwartungswert an, erreicht ihn aber nicht exakt.\n- [ ] Ja, der Zufallszahlengenerator ist ungeeignet ~ Er ist einfach, für diesen\n      Zweck aber ausreichend.\n:::\n\n## Verlinkte Ressourcen\n\n- [OpenIntro Statistics, Kapitel zu Zufallsvariablen](https://www.openintro.org/book/os/)\n- [Diskrete Verteilungen](diskrete-verteilungen.qmd)\n- [Stetige Verteilungen](stetige-verteilungen.qmd)\n",
    "supporting": [
      "zufallsvariablen_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}