{
  "hash": "450be7104c9b1b3a84c3ef1450bef12d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Kaplan-Meier-Schätzer\"\ndescription: \"Überlebenskurven schätzen, Median und Konfidenzband richtig deuten.\"\ncategories: [\"Survival-Analyse\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: methode\nstand: entwurf\norder: 20\n---\n\n\n\n\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Welcher Anteil hat zu einem gegebenen Zeitpunkt noch kein Ereignis erlebt, bei rechtszensierten Daten? |\n| Zielvariable | Zeit bis zum Ereignis plus Statusindikator |\n| Prädiktoren | keine, oder eine kategoriale Gruppierung für getrennte Kurven |\n| Was die Methode liefert | Überlebenskurve mit Konfidenzband, Anteile zu gewählten Zeitpunkten, Median, Anzahl unter Risiko |\n| R-Funktion | `survfit(Surv(zeit, status) ~ 1)`, gelesen mit `summary()` und `plot()` |\n| Python-Funktion | `KaplanMeierFitter().fit(zeit, status)` |\n| Verwandte Methoden | [Log-Rank-Test](log-rank-test.qmd), [Cox-Modell](cox-modell.qmd) |\n\n## Wann diese Methode, wann nicht\n\nTypische Fragestellungen: Wie lange bleiben Mitglieder, bis wann fällt ein\nBauteil aus, welcher Anteil ist nach zwölf Monaten noch ohne Rückfall.\nGemeinsam ist ihnen eine Zeit bis zu einem Ereignis und ein Teil Beobachtungen,\nbei denen das Ereignis noch nicht eingetreten ist.\n\nDer Kaplan-Meier-Schätzer ist beschreibend: Er schätzt die Kurve, ohne eine\nVerteilungsform zu unterstellen und ohne Einflussgrössen zu berücksichtigen. Er\nist deshalb fast immer der erste Schritt und selten der letzte.\n\n| Situation | Stattdessen |\n|---|---|\n| Gruppen sollen statistisch verglichen werden | [Log-Rank-Test](log-rank-test.qmd) |\n| Der Effekt mehrerer Einflussgrössen interessiert | [Cox-Modell](cox-modell.qmd) |\n| Es gibt keine Zensierung, alle Zeiten sind vollständig | gewöhnliche [deskriptive Statistik](../grundlagen/lage-streuungsmasse.qmd) genügt |\n| Zielgrösse ist ja oder nein ohne Zeitbezug | [logistische Regression](../regression/logistische-regression.qmd) |\n| Ein einzelner metrischer Prädiktor soll gezeigt werden | Klassen bilden und je Klasse eine Kurve, oder Cox-Modell |\n\n## Grundidee und Modell\n\nDie Kurve entsteht Schritt für Schritt: An jedem Zeitpunkt, an dem ein Ereignis\neintritt, wird der Anteil derjenigen berechnet, die diesen Zeitpunkt überstehen,\nund dieser Anteil multipliziert die bisherige Kurve.\n\n$$\\hat{S}(t) = \\prod_{t_i \\le t} \\left(1 - \\frac{d_i}{n_i}\\right)$$\n\n| Bestandteil | Bedeutung |\n|---|---|\n| $t_i$ | Zeitpunkt, an dem mindestens ein Ereignis eintritt |\n| $d_i$ | Anzahl Ereignisse zu diesem Zeitpunkt |\n| $n_i$ | Anzahl unter Risiko, also noch beobachtet und ohne Ereignis |\n| $1 - d_i/n_i$ | bedingte Wahrscheinlichkeit, diesen Zeitpunkt zu überstehen |\n| $\\prod$ | Produkt über alle Ereigniszeitpunkte bis $t$ |\n\nZensierte Beobachtungen tauchen nicht als Ereignis auf, verkleinern aber $n_i$\nfür alle späteren Zeitpunkte. Genau dadurch fliesst ihre Information ein: Sie\nhaben bis zu ihrem Ausscheiden mitgezählt. Die Kurve ist deshalb eine\nTreppenfunktion, die nur bei Ereignissen fällt.\n\n::: {.note-box}\n**Warum nicht einfach der Mittelwert der beobachteten Zeiten?** Weil die\nzensierten Beobachtungen dann entweder wegfallen müssten — was systematisch die\nlangen Verläufe entfernt und das Ergebnis zu pessimistisch macht — oder als\nEreigniszeiten gezählt würden, was sie zu kurz ansetzt. Der\nProdukt-Limit-Schätzer umgeht beides, indem er nur bedingte\nWahrscheinlichkeiten verkettet.\n:::\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung | Vorgehen |\n|---|---|---|---|---|\n| Rechtszensierung | Bekannt ist, dass das Ereignis nach der Beobachtungszeit liegt | Datenstruktur, Erhebung | Andere Zensierungsart braucht andere Verfahren | Verfahren für Intervall- oder Linkszensierung |\n| Nicht informative Zensierung | Zensierte haben dasselbe Risiko wie Beobachtete | nur inhaltlich, siehe [Zensierung](zensierung-ueberlebensfunktion.qmd) | Kurve systematisch zu optimistisch oder zu pessimistisch | Ursachen der Zensierung berichten, Sensitivitätsrechnung |\n| Unabhängige Beobachtungen | Ein Ereignis beeinflusst andere nicht | Erhebungsdesign | Konfidenzband zu schmal | Modelle für geschachtelte Daten |\n| Gleiche Grundgesamtheit über die Zeit | Kein Zustrom mit anderem Risiko mitten in der Beobachtung | Aufnahmezeitpunkte prüfen | Kurve mischt verschiedene Populationen | nach Aufnahmekohorte trennen |\n| Genügend unter Risiko am Kurvenende | Der rechte Teil beruht nicht auf wenigen Fällen | Risikotabelle ansehen | Kurvenende schwankt stark und wird überinterpretiert | Kurve abschneiden, wo die Zahl zu klein wird |\n\n## Output lesen\n\nR, `survfit()` und `summary()`:\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| `n` | Anzahl Beobachtungen | nicht Anzahl Ereignisse |\n| `events` | Anzahl eingetretener Ereignisse | trägt die Genauigkeit der Schätzung, nicht n |\n| `median` | Zeitpunkt, an dem die Kurve 0.5 erreicht | `NA`, wenn die Kurve nie unter 0.5 fällt; das ist kein Fehler |\n| `0.95LCL`, `0.95UCL` | Konfidenzintervall für den Median | oft breit und nach oben offen |\n| `time` | Zeitpunkte in `summary(..., times = ...)` | frei wählbar, sinnvoll an fachlich relevanten Marken |\n| `n.risk` | Anzahl unter Risiko zu diesem Zeitpunkt | sinkt durch Ereignisse und Zensierungen |\n| `n.event` | Ereignisse seit dem letzten Zeitpunkt | |\n| `survival` | geschätzter Anteil ohne Ereignis | die eigentliche Zahl zum Berichten |\n| `std.err` | Standardfehler dieser Schätzung | wächst mit fallender Anzahl unter Risiko |\n| `lower 95% CI`, `upper 95% CI` | Konfidenzintervall des Anteils | am Kurvenende sehr breit |\n\nPython, `KaplanMeierFitter`:\n\n| Zugriff | Was er liefert | Unterschied zu R |\n|---|---|---|\n| `median_survival_time_` | Median | R nennt ihn in der Zusammenfassung mit Intervall; Python gibt `inf` statt `NA` |\n| `survival_function_` | die vollständige Treppenfunktion als Tabelle | in R über `summary()` |\n| `survival_function_at_times([...])` | Anteile zu gewählten Zeitpunkten | Gegenstück zu `times =` |\n| `confidence_interval_` | Konfidenzband über alle Zeitpunkte | in R Teil von `summary()` |\n| `event_table` | Ereignisse, Zensierungen und Anzahl unter Risiko je Zeitpunkt | in R die Spalten `n.risk` und `n.event` |\n| `plot_survival_function()` | Kurve samt Band | in R `plot()` |\n\n::: {.note-box}\n**Die Konfidenzbänder unterscheiden sich zwischen den Paketen**, und zwar\nsichtbar. R rechnet standardmässig auf der Log-Skala (`conf.type = \"log\"`),\nlifelines auf der Log-Log-Skala. Beide sind gebräuchlich, das Log-Log-Band bleibt\nzuverlässiger zwischen 0 und 1. Abweichungen in der zweiten Nachkommastelle sind\ndeshalb normal und kein Rechenfehler; die Punktschätzung der Kurve ist in beiden\nSprachen identisch.\n:::\n\n## Interpretationsfallen\n\n- **Der Median ist keine mittlere Laufzeit.** Er ist der Zeitpunkt, an dem die\n  Kurve 0.5 erreicht — eine Aussage über die Kurve, nicht über einen Durchschnitt.\n- **Kein Median ist kein Fehler.** Fällt die Kurve nie unter 0.5, ist die Antwort\n  \"im Beobachtungszeitraum nicht erreicht\", und es gehört ein Anteil zu einem\n  festen Zeitpunkt berichtet.\n- **Das Kurvenende ist unzuverlässig.** Dort stehen wenige Beobachtungen unter\n  Risiko; ohne Risikotabelle ist die Kurve dort nicht lesbar.\n- **Zensierte Fälle sind keine Ereignisse.** Wer sie als solche zählt,\n  unterschätzt die Laufzeit systematisch; wer sie weglässt, überschätzt sie.\n- **Getrennte Kurven sind kein Test.** Der optische Abstand ersetzt den\n  [Log-Rank-Test](log-rank-test.qmd) nicht.\n- **Kaplan-Meier kontrolliert nichts.** Unterschiede zwischen Gruppen können von\n  ganz anderen Merkmalen kommen; dafür ist das [Cox-Modell](cox-modell.qmd) da.\n- **Die Kurve gilt für die beobachtete Population.** Über den Beobachtungszeitraum\n  hinaus sagt sie nichts.\n\n## Ergebnis berichten\n\nVorlage für den Ergebnissatz:\n\n> Von [n] Beobachtungen traten [Ereignisse] Ereignisse ein, [zensiert] waren zum\n> Stichtag zensiert. Der geschätzte Anteil ohne Ereignis beträgt nach [t]\n> [Anteil] (95-Prozent-Intervall [unten] bis [oben], [n.risk] unter Risiko). Der\n> Median liegt bei [Wert] beziehungsweise wurde im Beobachtungszeitraum nicht\n> erreicht.\n\nGenannt werden: n und Anzahl Ereignisse getrennt, Art und Zeitpunkt der\nZensierung, Anteile zu fachlich begründeten Zeitpunkten mit Intervall, die\nAnzahl unter Risiko dazu, und der Median nur, wenn er geschätzt ist.\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt Kaplan-Meier |\n|---|---|\n| [Log-Rank-Test](log-rank-test.qmd) | Gruppen sollen statistisch verglichen werden |\n| [Cox-Modell](cox-modell.qmd) | mehrere Einflussgrössen, Effektstärken als Hazard Ratios |\n| Parametrische Modelle (Weibull, Exponential) | eine Verteilungsform ist begründbar, Extrapolation nötig |\n| [Logistische Regression](../regression/logistische-regression.qmd) | Zielgrösse ohne Zeitbezug |\n| Konkurrierende Risiken | mehrere sich ausschliessende Ereignisarten |\n\n## Beispiele\n\nBeispiel 1 rechnet die Kurve an zehn Fällen von Hand nach. Die Beispiele 2 bis 5\narbeiten mit einem grösseren konstruierten Datensatz: 400 Fitnessabos, Monats-\nund Jahresverträge, Distanz zum Studio zwischen 0.5 und 15 Kilometern, und ein\nKündigungsrisiko, das mit Monatsvertrag und mit der Distanz steigt. Der Stichtag\nliegt bei 24 Monaten.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Die Kurve von Hand\n\n#### Frage und Datenlage\n\nZehn Fälle, sortiert nach Zeit. Das Pluszeichen markiert eine Zensierung, also\n\"bis hierher ohne Ereignis beobachtet, danach unbekannt\":\n\n$$2,\\; 3,\\; 3,\\; 5^+,\\; 6,\\; 7^+,\\; 8,\\; 8,\\; 10^+,\\; 12$$\n\nSieben Ereignisse — darunter zwei Paare, die auf denselben Zeitpunkt fallen —\nund drei Zensierungen mittendrin. Damit sind alle Situationen vertreten, die der Schätzer\nzu behandeln hat.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nklein <- data.frame(\n  zeit   = c(2, 3, 3, 5, 6, 7, 8, 8, 10, 12),\n  status = c(1, 1, 1, 0, 1, 0, 1, 1, 0, 1)\n)\n\nk <- survfit(Surv(zeit, status) ~ 1, data = klein, conf.type = \"log-log\")\nsummary(k)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(zeit, status) ~ 1, data = klein, conf.type = \"log-log\")\n\n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    2     10       1    0.900  0.0949       0.4730        0.985\n    3      9       2    0.700  0.1449       0.3287        0.892\n    6      6       1    0.583  0.1610       0.2298        0.821\n    8      4       2    0.292  0.1666       0.0471        0.609\n   12      1       1    0.000     NaN           NA           NA\n```\n\n\n:::\n\n```{.r .cell-code}\nk\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(zeit, status) ~ 1, data = klein, conf.type = \"log-log\")\n\n      n events median 0.95LCL 0.95UCL\n[1,] 10      7      8       2      NA\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nklein = pd.DataFrame({\n    \"zeit\": [2, 3, 3, 5, 6, 7, 8, 8, 10, 12],\n    \"status\": [1, 1, 1, 0, 1, 0, 1, 1, 0, 1],\n})\n\nk = KaplanMeierFitter().fit(klein[\"zeit\"], klein[\"status\"])\n\nprint(k.event_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          removed  observed  censored  entrance  at_risk\nevent_at                                                \n0.0             0         0         0        10       10\n2.0             1         1         0         0       10\n3.0             2         2         0         0        9\n5.0             1         0         1         0        7\n6.0             1         1         0         0        6\n7.0             1         0         1         0        5\n8.0             2         2         0         0        4\n10.0            1         0         1         0        2\n12.0            1         1         0         0        1\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(k.survival_function_.round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          KM_estimate\ntimeline             \n0.0            1.0000\n2.0            0.9000\n3.0            0.7000\n5.0            0.7000\n6.0            0.5833\n7.0            0.5833\n8.0            0.2917\n10.0           0.2917\n12.0           0.0000\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(k.confidence_interval_.round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      KM_estimate_lower_0.95  KM_estimate_upper_0.95\n0.0                    1.000                   1.000\n2.0                    0.473                   0.985\n3.0                    0.329                   0.892\n5.0                    0.329                   0.892\n6.0                    0.230                   0.821\n7.0                    0.230                   0.821\n8.0                    0.047                   0.609\n10.0                   0.047                   0.609\n12.0                   0.000                   0.000\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Median:\", k.median_survival_time_)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian: 8.0\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nDie Rechnung Schritt für Schritt. Jede Zeile ist ein Zeitpunkt, an dem etwas\npassiert:\n\n| $t_i$ | unter Risiko $n_i$ | Ereignisse $d_i$ | zensiert | Faktor $1 - d_i/n_i$ | $\\hat{S}(t_i)$ |\n|---|---|---|---|---|---|\n| 2 | 10 | 1 | 0 | $1 - 1/10 = 0.900$ | $1 \\cdot 0.900 = $ **0.9000** |\n| 3 | 9 | **2** | 0 | $1 - 2/9 = 0.7778$ | $0.900 \\cdot 0.7778 = $ **0.7000** |\n| 5 | 7 | 0 | **1** | — (kein Ereignis) | 0.7000 (unverändert) |\n| 6 | 6 | 1 | 0 | $1 - 1/6 = 0.8333$ | $0.700 \\cdot 0.8333 = $ **0.5833** |\n| 7 | 5 | 0 | **1** | — | 0.5833 |\n| 8 | 4 | **2** | 0 | $1 - 2/4 = 0.500$ | $0.5833 \\cdot 0.5 = $ **0.2917** |\n| 10 | 2 | 0 | **1** | — | 0.2917 |\n| 12 | 1 | 1 | 0 | $1 - 1/1 = 0$ | **0.0000** |\n\nDaran lässt sich jeder Mechanismus des Verfahrens ablesen:\n\n| Beobachtung | Was sie zeigt |\n|---|---|\n| Bei $t = 3$ ist $d_i = 2$ | Zwei Ereignisse zum selben Zeitpunkt werden **gemeinsam** verrechnet, nicht nacheinander. Sonst wäre $\\frac{8}{9} \\cdot \\frac{7}{8}$ zu rechnen — was hier zufällig dasselbe ergibt, bei anderen Konstellationen aber nicht. |\n| Bei $t = 5$ fällt die Kurve **nicht** | Eine Zensierung ist kein Ereignis. Die Kurve bleibt waagrecht. |\n| Aber $n_i$ springt von 7 auf 6 | Genau **so** wirkt die Zensierung: Der Fall zählt bis $t = 5$ voll mit und verschwindet danach aus dem Nenner. Seine Information \"hat mindestens 5 überlebt\" ist damit vollständig genutzt. |\n| Bei $t = 8$ halbiert sich die Kurve | 2 von 4 unter Risiko — der grösste Einzelschritt, obwohl vorher schon Zeitpunkte mit zwei Ereignissen vorkamen. Späte Schritte sind gross, weil der Nenner klein ist. |\n| Bei $t = 12$ erreicht die Kurve **exakt null** | Die letzte Beobachtung ist ein Ereignis. Wäre sie zensiert, endete die Kurve bei 0.2917 und bliebe dort — undefiniert, nicht null. |\n| Median = **8** | Der erste Zeitpunkt, an dem $\\hat{S}(t) \\le 0.5$ gilt. Bei $t = 6$ steht die Kurve auf 0.5833, bei $t = 8$ auf 0.2917. Der Median ist also nicht der Zeitpunkt, an dem die Kurve 0.5 *schneidet* — bei einer Treppenfunktion gibt es diesen Schnitt oft gar nicht. |\n\nDas Konfidenzintervall wächst mit jedem Schritt: bei $t = 2$ noch 0.47 bis 0.99,\nbei $t = 8$ schon 0.05 bis 0.61. Der Grund steht in der Spalte $n_i$ — je weniger\nunter Risiko, desto unsicherer die Schätzung.\n\n::: {.note-box}\nFür diesen kleinen Datensatz ist in R ausdrücklich `conf.type = \"log-log\"`\ngesetzt, damit die Bänder mit denen von lifelines übereinstimmen. Ohne diese\nAngabe rechnet R auf der Log-Skala und liefert andere Grenzen.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Von 10 Beobachtungen traten 7 Ereignisse ein, 3 waren zensiert. Der geschätzte\n> Anteil ohne Ereignis beträgt nach 6 Zeiteinheiten 0.58 (95-Prozent-Intervall\n> 0.23 bis 0.82, 6 unter Risiko). Der Median liegt bei 8.\n\n### Beispiel 2: Erst die Zensierung ansehen\n\n#### Frage und Datenlage\n\nBevor eine Kurve gezeichnet wird, gehört geklärt: Wie viele Ereignisse gibt es\nüberhaupt, und **wann** wird zensiert? Von der Antwort hängt ab, ob die zentrale\nAnnahme des Verfahrens plausibel ist.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(status = abo$status)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstatus\n  0   1 \n153 247 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(prop.table(table(abo$status)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    0     1 \n0.382 0.618 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Wann wird zensiert?\nrange(abo$zeit[abo$status == 0])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24 24\n```\n\n\n:::\n\n```{.r .cell-code}\n# Und wie verteilen sich Ereignisse und Zensierungen auf die Gruppen?\ntable(vertrag = abo$vertrag, status = abo$status)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       status\nvertrag   0   1\n  Jahr  101  64\n  Monat  52 183\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(abo[\"status\"].value_counts().to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{1: 247, 0: 153}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(abo[\"status\"].value_counts(normalize=True).round(3).to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{1: 0.618, 0: 0.382}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"zensiert von\", round(float(abo.loc[abo[\"status\"] == 0, \"zeit\"].min()), 3),\n      \"bis\", round(float(abo.loc[abo[\"status\"] == 0, \"zeit\"].max()), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nzensiert von 24.0 bis 24.0\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pd.crosstab(abo[\"vertrag\"], abo[\"status\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstatus     0    1\nvertrag          \nJahr     101   64\nMonat     52  183\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Ereignisse (`status` = 1) | **247** von 400 | Diese Zahl trägt die Genauigkeit der Schätzung, nicht die 400. |\n| Zensiert (`status` = 0) | **153**, also 38.3 Prozent | Ein normaler Anteil. Über etwa 70 Prozent Zensierung wird die Kurve am rechten Ende wertlos. |\n| Spanne der Zensierungszeiten | **genau 24 bis 24** | Der entscheidende Befund: Alle zensierten Fälle liegen exakt auf dem Stichtag. |\n| Kreuztabelle | Jahresverträge häufiger zensiert (101 von 165) als Monatsverträge (52 von 235) | Kein Problem, sondern das erwartete Bild: Wer seltener kündigt, erreicht häufiger den Stichtag. |\n\n::: {.note-box}\n**Warum die Spanne der Zensierungszeiten die wichtigste Zahl dieses Beispiels\nist:** Liegt jede Zensierung auf dem Stichtag, handelt es sich um\n*administrative* Zensierung — die Beobachtung endet, weil die Studie endet, und\nnicht weil mit dem Fall etwas passiert ist. Die Annahme \"Zensierte haben dasselbe\nRisiko wie die weiter Beobachteten\" ist dann von der Erhebung her begründet.\n\nWären die Zensierungen über den ganzen Zeitraum verstreut, hiesse das, dass Fälle\nmittendrin aus der Beobachtung fallen. Dann gehört die Frage nach dem **Grund**\nin die Auswertung: Wer aus einem Fitnessstudio wegzieht, ist unproblematisch; wer\ndas Abo unbemerkt über eine andere Kette weiterführt, verzerrt die Kurve\nsystematisch. Ausführlich unter\n[Zensierung](zensierung-ueberlebensfunktion.qmd).\n:::\n\n#### Interpretation\n\nDie Zensierung ist hier rein administrativ, das Verfahren ist also anwendbar.\nDiese Feststellung gehört an den Anfang jeder Survival-Auswertung — und in den\nBericht.\n\n### Beispiel 3: Die Kurve und ihre Zahlen\n\n#### Frage und Datenlage\n\nDie Kurve für alle 400 Abos, gelesen an fünf fachlich sinnvollen Zeitpunkten:\nnach 3, 6, 12, 18 und 24 Monaten.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkurve <- survfit(Surv(zeit, status) ~ 1, data = abo)\nkurve\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(zeit, status) ~ 1, data = abo)\n\n       n events median 0.95LCL 0.95UCL\n[1,] 400    247   16.7    14.4    18.7\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(kurve, times = c(3, 6, 12, 18, 24))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(zeit, status) ~ 1, data = abo)\n\n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    3    359      41    0.898  0.0152        0.868        0.928\n    6    320      39    0.800  0.0200        0.762        0.840\n   12    242      78    0.605  0.0244        0.559        0.655\n   18    187      55    0.468  0.0249        0.421        0.519\n   24    153      34    0.383  0.0243        0.338        0.433\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mar = c(4, 4, 2, 1))\nplot(kurve, xlab = \"Monate seit Abschluss\", ylab = \"Anteil ohne Kündigung\",\n     mark.time = TRUE, conf.int = TRUE, lwd = 2, ylim = c(0, 1))\nabline(h = 0.5, lty = 2)\n```\n\n::: {.cell-output-display}\n![Beispiel 3: Überlebenskurve mit Konfidenzband. Die senkrechten Markierungen sind zensierte Beobachtungen.](kaplan-meier_files/figure-html/fig-b3-km-r-1.png){#fig-b3-km-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nkm = KaplanMeierFitter().fit(abo[\"zeit\"], abo[\"status\"], label=\"alle\")\n\nprint(\"Ereignisse:\", int(abo[\"status\"].sum()), \"von\", len(abo))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEreignisse: 247 von 400\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Median:\", round(float(km.median_survival_time_), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian: 16.617\n```\n\n\n:::\n\n```{.python .cell-code}\nzeitpunkte = [3, 6, 12, 18, 24]\nband = km.confidence_interval_survival_function_\n# je Zeitpunkt die letzte Stuetzstelle der Treppenfunktion vor oder auf t\nstuetzen = [band.index[band.index <= t][-1] for t in zeitpunkte]\n\nprint(pd.DataFrame({\n    \"zeit\": zeitpunkte,\n    # unter Risiko zum Zeitpunkt t, wie R es zaehlt\n    \"n_risk\": [int((abo[\"zeit\"] >= t).sum()) for t in zeitpunkte],\n    \"S(t)\": km.survival_function_at_times(zeitpunkte).round(3).values,\n    \"unten\": band.iloc[:, 0].loc[stuetzen].round(3).values,\n    \"oben\": band.iloc[:, 1].loc[stuetzen].round(3).values,\n}).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n zeit  n_risk  S(t)  unten  oben\n    3     359 0.898  0.863 0.923\n    6     320 0.800  0.757 0.836\n   12     242 0.605  0.555 0.651\n   18     187 0.468  0.418 0.515\n   24     153 0.383  0.335 0.430\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achse = plt.subplots()\nkm.plot_survival_function(ax=achse, ci_show=True, color=\"#2166ac\")\nachse.axhline(0.5, linestyle=\"--\", color=\"black\", linewidth=0.8)\nachse.set_xlabel(\"Monate seit Abschluss\")\nachse.set_ylabel(\"Anteil ohne Kündigung\")\nachse.set_ylim(0, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(0.0, 1.0)\n```\n\n\n:::\n\n```{.python .cell-code}\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselbe Kurve mit lifelines.](kaplan-meier_files/figure-html/fig-b3-km-py-1.png){#fig-b3-km-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Monat | unter Risiko | $\\hat{S}(t)$ | Band, R (log) | Band, Python (log-log) |\n|---|---|---|---|---|\n| 3 | 359 | **0.898** | 0.868 – 0.928 | 0.863 – 0.923 |\n| 6 | 320 | **0.800** | 0.762 – 0.840 | 0.757 – 0.836 |\n| 12 | 242 | **0.605** | 0.559 – 0.655 | 0.555 – 0.651 |\n| 18 | 187 | **0.468** | 0.421 – 0.519 | 0.418 – 0.515 |\n| 24 | 153 | **0.383** | 0.338 – 0.433 | 0.335 – 0.430 |\n\nDie beiden Bänder liegen um wenige Tausendstel auseinander — der oben erwähnte\nUnterschied zwischen Log- und Log-Log-Skala. Die Punktschätzung ist identisch.\n\n| Ausgabe | Wert hier | Bedeutung |\n|---|---|---|\n| $\\hat{S}(12) = 0.605$ | 60.5 Prozent | Der geschätzte Anteil der Abos, die nach zwölf Monaten noch bestehen. **Nicht** \"60.5 Prozent der Kündigungen sind noch offen\" und nicht \"60.5 Prozent Wahrscheinlichkeit für dieses eine Abo\" — es ist eine Aussage über die Population. |\n| Verlauf 0.898 → 0.800 → 0.605 | in den ersten drei Monaten 10 Prozentpunkte, in den folgenden drei weitere 10, dann in sechs Monaten 20 | Das Risiko ist am Anfang am höchsten und nimmt ab. Genau diesen Verlauf zeigt der steile Beginn der Kurve. |\n| unter Risiko fällt 400 → 153 | | Die 153 am Schluss sind genau die zensierten Fälle: alle, die den Stichtag erreicht haben. |\n| Median | **16.62 Monate** | Der Zeitpunkt, an dem die Kurve unter 0.5 fällt. Zwischen Monat 18 (0.468) und Monat 12 (0.605), was zur Tabelle passt. |\n| Bandbreite | wächst von 0.060 auf rund 0.096 | Nicht weil die Daten schlechter werden, sondern weil immer weniger Fälle die Schätzung tragen. Zusätzlich ist das Band um 0.5 herum von Natur aus am breitesten — dort ist die Varianz eines Anteils maximal. |\n\n::: {.note-box}\nDie Zeitpunkte in `times =` sind **frei wählbar**, und genau darin liegt eine\nstille Gefahr: Wer sie nach dem Blick auf die Kurve auswählt, berichtet das\nErgebnis, das am besten aussieht. Sie gehören vorher festgelegt, aus der Sache\nheraus — hier etwa Quartals- und Jahresmarken, weil Verträge daran gebunden sind.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Von 400 Abos wurden im Beobachtungszeitraum 247 gekündigt, 153 waren am\n> Stichtag nach 24 Monaten noch aktiv. Der geschätzte Anteil ohne Kündigung\n> beträgt nach zwölf Monaten 0.61 (95-Prozent-Intervall 0.56 bis 0.66, 242 unter\n> Risiko) und nach 24 Monaten 0.38 (0.34 bis 0.43, 153 unter Risiko). Der Median\n> der Laufzeit liegt bei 16.6 Monaten.\n\n### Beispiel 4: Zwei Gruppen nebeneinander\n\n#### Frage und Datenlage\n\nGetrennte Kurven für Monats- und Jahresverträge. Die Frage: Wie gross ist der\nUnterschied, und was darf man aus zwei getrennten Kurven schliessen?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkurve_gruppen <- survfit(Surv(zeit, status) ~ vertrag, data = abo)\nkurve_gruppen\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(zeit, status) ~ vertrag, data = abo)\n\n                n events median 0.95LCL 0.95UCL\nvertrag=Jahr  165     64     NA      NA      NA\nvertrag=Monat 235    183   11.3    9.34    13.3\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(kurve_gruppen, times = c(12, 24))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(zeit, status) ~ vertrag, data = abo)\n\n                vertrag=Jahr \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n   12    134      31    0.812  0.0304        0.755        0.874\n   24    101      33    0.612  0.0379        0.542        0.691\n\n                vertrag=Monat \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n   12    108     127    0.460  0.0325        0.400        0.528\n   24     52      56    0.221  0.0271        0.174        0.281\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mar = c(4, 4, 2, 1))\nplot(kurve_gruppen, col = c(\"#2166ac\", \"#b2182b\"), lwd = 2, mark.time = TRUE,\n     xlab = \"Monate seit Abschluss\", ylab = \"Anteil ohne Kündigung\",\n     ylim = c(0, 1))\nlegend(\"bottomleft\", legend = c(\"Jahresvertrag\", \"Monatsvertrag\"),\n       col = c(\"#2166ac\", \"#b2182b\"), lwd = 2, bty = \"n\")\nabline(h = 0.5, lty = 2)\n```\n\n::: {.cell-output-display}\n![Beispiel 4: getrennte Kurven nach Vertragsart.](kaplan-meier_files/figure-html/fig-b4-km-r-3.png){#fig-b4-km-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, achse = plt.subplots()\nfor name, farbe in [(\"Jahr\", \"#2166ac\"), (\"Monat\", \"#b2182b\")]:\n    teil = abo[abo[\"vertrag\"] == name]\n    kmf = KaplanMeierFitter().fit(teil[\"zeit\"], teil[\"status\"], label=name)\n    kmf.plot_survival_function(ax=achse, ci_show=True, color=farbe)\n    anteile = kmf.survival_function_at_times([12, 24]).round(3).values\n    print(f\"{name:6s} n = {len(teil):3d} | Ereignisse: {int(teil['status'].sum()):3d}\"\n          f\" | Median: {float(kmf.median_survival_time_):7.3f}\"\n          f\" | S(12) = {anteile[0]:.3f} | S(24) = {anteile[1]:.3f}\")\n\nachse.axhline(0.5, linestyle=\"--\", color=\"black\", linewidth=0.8)\nachse.set_xlabel(\"Monate seit Abschluss\")\nachse.set_ylabel(\"Anteil ohne Kündigung\")\nachse.set_ylim(0, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(0.0, 1.0)\n```\n\n\n:::\n\n```{.python .cell-code}\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselben Gruppen mit lifelines.](kaplan-meier_files/figure-html/fig-b4-km-py-1.png){#fig-b4-km-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Gruppe | n | Ereignisse | Median | $\\hat{S}(12)$ | $\\hat{S}(24)$ |\n|---|---|---|---|---|---|\n| Jahresvertrag | 165 | 64 (39 %) | **nicht erreicht** | 0.812 | 0.612 |\n| Monatsvertrag | 235 | 183 (78 %) | **11.30 Monate** | 0.460 | 0.221 |\n\n| Ausgabe | Wie sie zu lesen ist |\n|---|---|\n| Der Median der Jahresverträge fehlt | R gibt `NA` aus, Python `inf`. Beides heisst dasselbe: Die Kurve fällt im Beobachtungszeitraum nie unter 0.5 — bei 24 Monaten steht sie noch bei 0.612. Ein Vergleich \"11.3 gegen NA\" ist deshalb nicht möglich; verglichen werden die **Anteile** zu festen Zeitpunkten. |\n| $\\hat{S}(12)$: 0.812 gegen 0.460 | Nach einem Jahr bestehen von den Jahresverträgen noch gut vier Fünftel, von den Monatsverträgen weniger als die Hälfte. Das ist die berichtbare Zahl. |\n| $\\hat{S}(24)$: 0.612 gegen 0.221 | Der Abstand bleibt bestehen und wächst sogar. Die Kurven laufen nicht wieder zusammen. |\n| Ereignisanteile 39 gegen 78 Prozent | Dieselbe Aussage roh gezählt — allerdings **ohne** Berücksichtigung der Zeit; deshalb ist sie nur eine grobe Ergänzung, keine Alternative zur Kurve. |\n\n::: {.note-box}\nDrei Dinge, die dieses Bild **nicht** zeigt:\n\n1. **Ob der Unterschied statistisch gesichert ist.** Der optische Abstand ist\n   kein Nachweis; dafür ist der [Log-Rank-Test](log-rank-test.qmd) zuständig.\n2. **Ob die Vertragsart die Ursache ist.** Wer einen Jahresvertrag wählt, hat\n   sich womöglich ohnehin schon für längeres Training entschieden. Die\n   Vertragsart könnte also Folge derselben Absicht sein, die auch das Bleiben\n   erklärt.\n3. **Ob andere Merkmale den Unterschied erzeugen.** Wohnen Jahresvertragskunden\n   näher am Studio, misst der Vergleich teilweise die Distanz. Genau dafür gibt\n   es das [Cox-Modell](cox-modell.qmd).\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Abos mit Monatsvertrag haben eine deutlich kürzere Laufzeit als solche mit\n> Jahresvertrag: Nach zwölf Monaten bestehen noch 46.0 gegenüber 81.2 Prozent,\n> nach 24 Monaten 22.1 gegenüber 61.2 Prozent. Der Median liegt bei\n> Monatsverträgen bei 11.3 Monaten und wurde bei Jahresverträgen im\n> Beobachtungszeitraum nicht erreicht (n = 235 beziehungsweise 165, 183\n> beziehungsweise 64 Kündigungen).\n\n### Beispiel 5: Kein Median, dünnes Kurvenende\n\n#### Frage und Datenlage\n\nEine Teilgruppe mit geringem Risiko: Jahresverträge von Personen, die weniger\nals fünf Kilometer entfernt wohnen. Was tut man, wenn die Kurve die Hälfte nie\nerreicht?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntreue <- subset(abo, vertrag == \"Jahr\" & distanz < 5)\n\nkurve_treue <- survfit(Surv(zeit, status) ~ 1, data = treue)\nkurve_treue\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(zeit, status) ~ 1, data = treue)\n\n      n events median 0.95LCL 0.95UCL\n[1,] 60     23     NA      NA      NA\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(kurve_treue, times = c(6, 12, 18, 24))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(zeit, status) ~ 1, data = treue)\n\n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    6     55       5    0.917  0.0357        0.849        0.989\n   12     51       4    0.850  0.0461        0.764        0.945\n   18     45       6    0.750  0.0559        0.648        0.868\n   24     37       8    0.617  0.0628        0.505        0.753\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ntreue = abo[(abo[\"vertrag\"] == \"Jahr\") & (abo[\"distanz\"] < 5)]\nkm_treue = KaplanMeierFitter().fit(treue[\"zeit\"], treue[\"status\"])\n\nprint(\"n =\", len(treue), \"| Ereignisse:\", int(treue[\"status\"].sum()))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 60 | Ereignisse: 23\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Median:\", km_treue.median_survival_time_)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian: inf\n```\n\n\n:::\n\n```{.python .cell-code}\nband = km_treue.confidence_interval_survival_function_\nzeitpunkte = [6, 12, 18, 24]\nstuetzen = [band.index[band.index <= t][-1] for t in zeitpunkte]\n\nprint(pd.DataFrame({\n    \"zeit\": zeitpunkte,\n    \"n_risk\": [int((treue[\"zeit\"] >= t).sum()) for t in zeitpunkte],\n    \"S(t)\": km_treue.survival_function_at_times(zeitpunkte).round(3).values,\n    \"unten\": band.iloc[:, 0].loc[stuetzen].round(3).values,\n    \"oben\": band.iloc[:, 1].loc[stuetzen].round(3).values,\n}).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n zeit  n_risk  S(t)  unten  oben\n    6      55 0.917  0.811 0.964\n   12      51 0.850  0.732 0.919\n   18      45 0.750  0.620 0.841\n   24      37 0.617  0.482 0.726\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| n | **60** | Von 400 bleiben 60 übrig. Die Teilgruppe ist klein — das ist der Preis jeder Aufteilung. |\n| Ereignisse | **23** | Nur 23 Kündigungen tragen die ganze Kurve. |\n| Median | **`NA` in R, `inf` in Python** | Kein Fehler, sondern die korrekte Aussage: **Mehr als die Hälfte war am Stichtag noch dabei.** Die Kurve endet bei 0.617 und wird nie tiefer beobachtet. |\n| unter Risiko bei Monat 6 | 55 | |\n| unter Risiko bei Monat 24 | **37** | Das Kurvenende beruht auf gut einem Drittel der Ausgangsgruppe. |\n| $\\hat{S}(24)$ | **0.617** | Rund 62 Prozent bestehen nach zwei Jahren noch. |\n\n::: {.note-box}\n**Was statt eines Medians berichtet wird:** ein Anteil zu einem festen, vorher\ngewählten Zeitpunkt, samt Intervall und Anzahl unter Risiko. Ein \"Median grösser\nals 24\" wäre irreführend präzise; die Daten sagen nur, dass er ausserhalb des\nBeobachtungsfensters liegt.\n\n**Wo die Kurve abgeschnitten gehört:** dort, wo die Anzahl unter Risiko unter\netwa zehn fällt. Bei 37 ist das hier nicht der Fall, weshalb die ganze Kurve\ngezeigt werden darf — mit Risikozahlen darunter. Fehlen diese Zahlen, ist eine\nKaplan-Meier-Kurve nicht beurteilbar, denn ein Absturz von 0.4 auf 0.2 sieht bei\n100 Fällen unter Risiko genauso aus wie bei zweien.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Für Jahresverträge von Personen mit weniger als fünf Kilometern Anfahrt (n = 60,\n> 23 Kündigungen) ist der Median im Beobachtungszeitraum nicht erreicht. Nach 24\n> Monaten bestehen noch 61.7 Prozent der Abos (37 unter Risiko).\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEine Beobachtung wird nach fünf Monaten zensiert. Was macht der\nKaplan-Meier-Schätzer damit?\n\n- [x] Sie zählt bis Monat 5 mit und verschwindet danach aus der Anzahl unter\n      Risiko ~ Richtig. Die Kurve fällt an dieser Stelle nicht, weil kein\n      Ereignis vorliegt; der Nenner der späteren Faktoren wird aber kleiner.\n      Genau so fliesst die Information \"hat mindestens 5 überlebt\" vollständig\n      ein.\n- [ ] Sie wird als Ereignis nach fünf Monaten gezählt ~ Das würde die Laufzeit\n      systematisch unterschätzen.\n- [ ] Sie wird aus der Analyse entfernt ~ Das würde die langen Verläufe\n      entfernen und ebenfalls verzerren.\n:::\n\n::: {.quiz}\nDer Median wird als `NA` beziehungsweise `inf` ausgegeben. Was heisst das?\n\n- [x] Die Kurve fällt im Beobachtungszeitraum nie unter 0.5 ~ Richtig. Mehr als\n      die Hälfte hatte am Stichtag noch kein Ereignis. Berichtet wird dann ein\n      Anteil zu einem festen Zeitpunkt, nicht ein \"Median grösser als 24\".\n- [ ] Es liegt ein Rechenfehler vor ~ Es ist die korrekte Ausgabe für diesen\n      Fall.\n- [ ] Zu viele Werte sind zensiert ~ Auch bei wenig Zensierung kann das\n      auftreten, wenn das Risiko einfach niedrig ist.\n:::\n\n::: {.quiz}\n$\\hat{S}(12) = 0.605$. Welche Aussage ist richtig?\n\n- [x] Geschätzte 60.5 Prozent der Population haben nach zwölf Monaten noch kein\n      Ereignis ~ Richtig. Es ist eine Aussage über die Population, aus der die\n      Stichprobe stammt, mit dem angegebenen Konfidenzintervall.\n- [ ] 60.5 Prozent der Beobachtungen sind noch unter Risiko ~ Das wäre die\n      Spalte `n.risk`, und sie unterscheidet sich, weil auch Zensierungen die\n      Anzahl unter Risiko senken.\n- [ ] Ein einzelnes Abo besteht mit 60.5 Prozent Wahrscheinlichkeit noch ~ Nur\n      dann, wenn dieses Abo wie ein zufällig gezogenes aus derselben Population\n      ist — was es meist nicht ist, weil man mehr über es weiss.\n:::\n\n::: {.quiz}\nZwei Kaplan-Meier-Kurven verlaufen deutlich getrennt. Was folgt daraus?\n\n- [x] Ein beschreibender Unterschied, mehr nicht ~ Richtig. Ob er statistisch\n      gesichert ist, klärt der Log-Rank-Test; ob er auf die Gruppenvariable\n      zurückgeht oder auf andere Merkmale, klärt ein Cox-Modell.\n- [ ] Die Gruppenvariable verursacht den Unterschied ~ Aus getrennten Kurven\n      folgt keine Ursache; die Gruppen können sich in vielem unterscheiden.\n- [ ] Der Unterschied ist signifikant ~ Der optische Abstand ist kein Test. Bei\n      kleinen Gruppen können sich Kurven deutlich trennen, ohne dass ein Test\n      etwas findet.\n:::\n\n::: {.quiz}\nWarum gehört zu jeder Kaplan-Meier-Kurve die Anzahl unter Risiko?\n\n- [x] Weil ein Kurvenabschnitt ohne sie nicht beurteilbar ist ~ Richtig. Ein\n      Absturz von 0.4 auf 0.2 sieht bei 100 Fällen unter Risiko genauso aus wie\n      bei zweien — bedeutet aber etwas völlig anderes. Das Konfidenzband zeigt\n      dasselbe, wird aber leichter überlesen.\n- [ ] Weil sie die Anzahl der Ereignisse angibt ~ Sie sinkt sowohl durch\n      Ereignisse als auch durch Zensierungen.\n- [ ] Weil sie zur Berechnung des Medians nötig ist ~ Der Median folgt aus der\n      Kurve, nicht aus der Risikotabelle.\n:::\n\n## Verlinkte Ressourcen\n\n- [survival: Vignette zur Survival-Analyse](https://cran.r-project.org/web/packages/survival/vignettes/survival.pdf)\n- [lifelines: Kaplan-Meier](https://lifelines.readthedocs.io/en/latest/Quickstart.html)\n- [Zensierung und Überlebensfunktion](zensierung-ueberlebensfunktion.qmd)\n",
    "supporting": [
      "kaplan-meier_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}