{
  "hash": "ee6f1a14f3acae56e6b7d871b0989384",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"matplotlib\"\ndescription: \"Figure und Axes, Achsen, Beschriftung und Export in Python.\"\ncategories: [\"matplotlib\", \"Visualisierung\", \"Python\", \"R\"]\nquelle: [\"PYFR\"]\nseitentyp: werkzeug\nstand: fertig\norder: 50\n---\n\n\n\n\n\n## Kernideen\n\n- **`Figure`** ist die Leinwand, **`Axes`** das Koordinatensystem darin,\n  **`Axis`** die einzelne Achse. Die Ähnlichkeit der letzten beiden Namen ist\n  eingebaut und muss gemerkt werden.\n- Es gibt **zwei Bedienweisen**. Der objektorientierte Weg ist der einzige, der\n  bei mehreren Grafiken eindeutig bleibt.\n- `plt.subplots()` liefert Figure und Axes in einem Schritt und ist deshalb der\n  übliche Einstieg.\n- Vier Grundtypen decken fast alles ab: Linie, Streuung, Balken, Histogramm.\n- Beim **Export** entscheiden `dpi` und `bbox_inches` darüber, ob die Grafik\n  brauchbar ist.\n- matplotlib zeichnet, was man sagt, Gruppierung, Legende und Reihenfolge\n  macht man selbst. Das ist der Unterschied zu [ggplot2](ggplot2.qmd).\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [NumPy und SciPy](../programmierung/numpy-scipy.qmd) und\n[pandas](../programmierung/pandas.qmd), weil die Daten von dort kommen. Wer\n[ggplot2](ggplot2.qmd) kennt, hat den Vergleich im Kopf; der Unterschied im\nDenkansatz ist der rote Faden dieser Seite.\n:::\n\n### Die Begriffe\n\n| Begriff | Was es ist |\n|---|---|\n| `Figure` | das ganze Bild, samt Grösse und Auflösung |\n| `Axes` | ein einzelnes Koordinatensystem darin |\n| `Axis` | eine Achse, also x oder y |\n\nDie Verwechslung von `Axes` und `Axis` ist eingebaut und lässt sich nur merken:\n**Ein `Axes` ist die Zeichenfläche, kein Strich.** In dieser Sammlung heisst die\nVariable deshalb konsequent `achse` beziehungsweise `achsen`, nie `ax`.\n\n### Zwei Bedienweisen, und warum das verwirrt\n\nMatplotlib lässt sich auf zwei Arten bedienen, und Codebeispiele im Netz\nmischen beide. Wer den Unterschied nicht kennt, kopiert Zeilen zusammen, die\nnicht zusammenpassen.\n\n| Weg | Aufruf | Wirkt auf |\n|---|---|---|\n| **pyplot** | `plt.scatter(...)`, `plt.xlabel(...)` | die *aktuelle* Grafik, implizit |\n| **objektorientiert** | `achse.scatter(...)`, `achse.set_xlabel(...)` | genau das benannte `Axes` |\n\nDie Empfehlung gilt ohne Ausnahme, sobald mehr als eine Grafik im Spiel ist:\n**der objektorientierte Weg.** Nur so bleibt eindeutig, wohin gezeichnet wird,\nund nur so lassen sich Grafiken in Funktionen erzeugen und zurückgeben.\n\nEin Nebeneffekt, der in dieser Sammlung überall auftaucht: Jeder\nmatplotlib-Aufruf gibt ein Objekt zurück, und in einem Quarto-Chunk wird das\nmitgedruckt. Deshalb steht im Code `_ = achse.scatter(...)`.\n\n### Der Unterschied im Denkansatz\n\n| | ggplot2 | matplotlib |\n|---|---|---|\n| Gruppen | `aes(colour = typ)` erzeugt Gruppen, Farben und Legende | man schleift selbst über die Gruppen |\n| Legende | entsteht aus der Zuordnung | entsteht aus `label=` plus `legend()` |\n| Teilbilder | `facet_wrap()` | `plt.subplots()` und eigene Schleife |\n| Statistik | `geom_smooth()` rechnet mit | selbst rechnen, etwa mit `np.polyfit` |\n| Theme | `theme_minimal()` | `plt.style.use()` oder `rcParams` |\n\nKeines der beiden ist besser. ggplot2 nimmt einem Arbeit ab und schreibt dafür\nvor, wie die Daten aussehen müssen; matplotlib verlangt mehr Zeilen und lässt\ndafür alles zu.\n\n### Der Datensatz dieser Seite\n\n150 Maschinen mit Laufzeit, Typ und Stromverbrauch, deterministisch erzeugt,\ndamit die R- und die Python-Fassung **dieselben** Maschinen zeigen.\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: pyplot oder objektorientiert\n\n#### Frage und Datenlage\n\nDerselbe Inhalt auf beide Arten. Und danach der Fall, in dem der Unterschied\nsichtbar wird: zwei Grafiken nacheinander.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(maschinen)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t150 obs. of  3 variables:\n $ laufzeit : num  2.6 15.9 21 18.1 12.6 4.9 8.3 17.7 3.7 18.5 ...\n $ typ      : Factor w/ 3 levels \"Drehbank\",\"Fräse\",..: 2 2 2 2 2 2 2 2 2 2 ...\n $ verbrauch: num  15 56 55 58.4 46.3 11.9 23.6 50.3 20.5 56.4 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(laufzeit_min = min(maschinen$laufzeit),\n        laufzeit_max = max(maschinen$laufzeit),\n        verbrauch_min = min(maschinen$verbrauch),\n        verbrauch_max = max(maschinen$verbrauch),\n        korrelation = cor(maschinen$laufzeit, maschinen$verbrauch)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n laufzeit_min  laufzeit_max verbrauch_min verbrauch_max   korrelation \n       2.1000       21.8000        4.4000       73.5000        0.8544 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(maschinen, aes(laufzeit, verbrauch)) +\n  geom_point(alpha = 0.6, size = 1.2) +\n  labs(x = \"Laufzeit in Stunden\", y = \"Verbrauch\")\n```\n\n::: {.cell-output-display}\n![Beispiel 1: In ggplot2 stellt sich die Frage nicht, es gibt nur einen Weg.](matplotlib_files/figure-html/fig-b1-mp-r-1.png){#fig-b1-mp-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(maschinen.dtypes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlaufzeit     float64\ntyp           object\nverbrauch    float64\ndtype: object\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"laufzeit_min\": round(float(laufzeit.min()), 4),\n       \"laufzeit_max\": round(float(laufzeit.max()), 4),\n       \"verbrauch_min\": round(float(verbrauch.min()), 4),\n       \"verbrauch_max\": round(float(verbrauch.max()), 4),\n       \"korrelation\": round(float(np.corrcoef(laufzeit, verbrauch)[0, 1]), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'laufzeit_min': 2.1, 'laufzeit_max': 21.8, 'verbrauch_min': 4.4, 'verbrauch_max': 73.5, 'korrelation': 0.8544}\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.python .cell-code}\n_ = plt.figure(figsize=(7, 2.6))\n_ = plt.scatter(maschinen[\"laufzeit\"], maschinen[\"verbrauch\"], s=10, alpha=0.6)\n_ = plt.xlabel(\"Laufzeit in Stunden\")\n_ = plt.ylabel(\"Verbrauch\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![Der pyplot-Weg: kurz für einen Zwischenblick.](matplotlib_files/figure-html/fig-b1a-mp-py-1.png){#fig-b1a-mp-py width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, achse = plt.subplots(figsize=(7, 2.6))\n_ = achse.scatter(maschinen[\"laufzeit\"], maschinen[\"verbrauch\"], s=10, alpha=0.6)\n_ = achse.set_xlabel(\"Laufzeit in Stunden\")\n_ = achse.set_ylabel(\"Verbrauch\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![Derselbe Inhalt objektorientiert: es ist jederzeit eindeutig, wohin gezeichnet wird.](matplotlib_files/figure-html/fig-b1b-mp-py-3.png){#fig-b1b-mp-py width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# Warum der Unterschied zaehlt: Welche Grafik ist \"die aktuelle\"?\nfig_a, achse_a = plt.subplots(figsize=(3, 2))\nfig_b, achse_b = plt.subplots(figsize=(3, 2))\nprint({\"aktuelle_figur_ist_b\": plt.gcf() is fig_b,\n       \"aktuelle_figur_ist_a\": plt.gcf() is fig_a})\n_ = achse_a.set_title(\"A\")      # eindeutig\n_ = plt.title(\"B\")              # landet auf der zuletzt angelegten\nprint({\"titel_a\": achse_a.get_title(), \"titel_b\": achse_b.get_title()})\nplt.close(fig_a)\nplt.close(fig_b)\n```\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | Wert |\n|---|---|\n| Beobachtungen | 150 |\n| Laufzeit | **2.1 bis 21.8** Stunden |\n| Verbrauch | **4.4 bis 73.5** |\n| Korrelation | **0.8544** |\n\n| Prüfung | Ergebnis |\n|---|---|\n| `plt.gcf() is fig_b` | **True** |\n| `plt.gcf() is fig_a` | **False** |\n| Titel auf `achse_a` | **\"A\"** |\n| Titel auf `achse_b` | **\"B\"** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Beide Wege erzeugen **dasselbe Bild** | Solange nur eine Grafik im Spiel ist, ist der pyplot-Weg kürzer und völlig in Ordnung. |\n| Bei zwei Figuren zeigt `plt.gcf()` auf die **zuletzt angelegte** | `plt.title(\"B\")` landet deshalb auf `fig_b`, obwohl im Code davor `achse_a` bearbeitet wurde. Genau so entstehen Grafiken, in denen die Beschriftung im falschen Bild steht. |\n| Der objektorientierte Weg benennt das Ziel | `achse_a.set_title(\"A\")` ist unabhängig davon, was zuletzt angelegt wurde. |\n| In ggplot2 stellt sich die Frage **gar nicht** | Dort ist eine Grafik ein Objekt, das man weitergibt. Es gibt keine \"aktuelle Grafik\". |\n| Die Variablen heissen hier `achse`, nicht `ax` | Damit der Unterschied zu `Axis` beim Lesen präsent bleibt. |\n\n::: {.note-box}\n**Die drei Zeilen, mit denen praktisch jede matplotlib-Grafik beginnt:**\n\n```python\nfig, achse = plt.subplots(figsize=(7, 4))\n...\nplt.tight_layout()\nplt.show()\n```\n\n`tight_layout()` verhindert abgeschnittene Beschriftungen, der häufigste\nSchönheitsfehler beim Export.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Der Datensatz umfasst 150 Maschinen mit Laufzeiten von 2.1 bis 21.8 Stunden\n> und Verbrauchswerten von 4.4 bis 73.5 bei einer Korrelation von 0.8544. Bei\n> zwei offenen Figuren wirkt jeder `plt.`-Aufruf auf die zuletzt angelegte,\n> der objektorientierte Weg benennt das Ziel und bleibt eindeutig.\n\n### Beispiel 2: Figure, Axes und das Gitter\n\n#### Frage und Datenlage\n\nWas genau liefert `plt.subplots(2, 2)` zurück, und wie spricht man ein\neinzelnes Teilbild an?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(maschinen, aes(laufzeit, verbrauch)) +\n  geom_point(alpha = 0.5, size = 1.1) +\n  facet_wrap(~ typ) +\n  labs(x = \"Laufzeit in Stunden\", y = \"Verbrauch\")\n```\n\n::: {.cell-output-display}\n![Beispiel 2: In ggplot2 übernimmt facet_wrap die Aufteilung.](matplotlib_files/figure-html/fig-b2-mp-r-5.png){#fig-b2-mp-r width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(with(maschinen, tapply(verbrauch, typ, mean)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDrehbank    Fräse   Presse \n   36.06    37.34    47.95 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(maschinen$typ)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nDrehbank    Fräse   Presse \n      50       50       50 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(2, 2, figsize=(7, 4))\nprint({\"typ_figur\": type(fig).__name__,\n       \"typ_achsen\": type(achsen).__name__,\n       \"form\": achsen.shape,\n       \"anzahl_axes\": achsen.size,\n       \"typ_einzeln\": type(achsen[0, 0]).__name__})\nplt.close(fig)\n\n# Bei einer einzigen Teilgrafik ist achsen KEIN Array\nfig, achse = plt.subplots(figsize=(3, 2))\nprint({\"einzeln_ist_array\": isinstance(achse, np.ndarray),\n       \"typ\": type(achse).__name__})\nplt.close(fig)\n\n# Mit squeeze=False bleibt es immer ein Gitter\nfig, achsen = plt.subplots(1, 1, squeeze=False, figsize=(3, 2))\nprint({\"mit_squeeze_false\": achsen.shape})\nplt.close(fig)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.python .cell-code}\ntypen = [\"Drehbank\", \"Fräse\", \"Presse\"]\nfig, achsen = plt.subplots(1, 3, figsize=(7, 2.8), sharex=True, sharey=True)\nfor achse, name in zip(achsen, typen):\n    teil = maschinen[maschinen[\"typ\"] == name]\n    _ = achse.scatter(teil[\"laufzeit\"], teil[\"verbrauch\"], s=10, alpha=0.6,\n                      color=\"0.3\")\n    _ = achse.set_title(f\"{name} (n={len(teil)})\", fontsize=10)\n    _ = achse.set_xlabel(\"Laufzeit\")\n_ = achsen[0].set_ylabel(\"Verbrauch\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: ein Teilbild je Maschinentyp, mit gemeinsamen Achsen.](matplotlib_files/figure-html/fig-b2-mp-py-1.png){#fig-b2-mp-py width=100%}\n:::\n\n```{.python .cell-code}\n\nprint(maschinen.groupby(\"typ\")[\"verbrauch\"].mean().round(2))\n```\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Aufruf | Rückgabe |\n|---|---|\n| `plt.subplots(2, 2)` | `Figure` plus ein Array der Form **(2, 2)** mit **4** `Axes` |\n| `plt.subplots()` | `Figure` plus **ein einzelnes** `Axes`, **kein** Array |\n| `plt.subplots(1, 1, squeeze=False)` | Array der Form **(1, 1)** |\n\n| Typ | Anzahl | mittlerer Verbrauch |\n|---|---|---|\n| Drehbank | 50 | **36.06** |\n| Fräse | 50 | **37.34** |\n| Presse | 50 | **47.95** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| `subplots(2, 2)` liefert ein **NumPy-Array** | Ansprechbar über `achsen[0, 0]` oder, flach durchlaufen, über `achsen.ravel()`. |\n| Bei einer einzigen Teilgrafik gibt es **kein Array** | Das ist die Quelle eines häufigen Fehlers: Code, der mit `achsen[0]` arbeitet, bricht ab, sobald nur noch eine Teilgrafik übrig ist. |\n| `squeeze=False` macht es einheitlich | Wer eine Funktion schreibt, die mit beliebig vielen Teilbildern umgehen soll, setzt das und spart sich die Fallunterscheidung. |\n| `sharex` und `sharey` sind das Gegenstück zu Facetten | Ohne sie hat jedes Teilbild eigene Achsen und die Teilbilder sind **nicht vergleichbar**, derselbe Punkt wie unter [Wahrnehmung, Beispiel 5](wahrnehmung-kodierung.qmd). |\n| Die Gruppierung macht man **selbst** | Die Schleife über `typen` ist genau die Arbeit, die `facet_wrap(~ typ)` in ggplot2 abnimmt. Dafür lässt sich hier jedes Teilbild einzeln anders gestalten. |\n\n::: {.note-box}\n**Nützliche Argumente von `subplots`:**\n\n| Argument | Wirkung |\n|---|---|\n| `figsize=(b, h)` | Grösse in Zoll |\n| `sharex`, `sharey` | gemeinsame Achsen, für Vergleichbarkeit fast immer nötig |\n| `squeeze=False` | Rückgabe bleibt ein Gitter |\n| `gridspec_kw={\"height_ratios\": [2, 1]}` | ungleich hohe Zeilen, etwa Kurve oben und Residuen unten |\n| `constrained_layout=True` | Alternative zu `tight_layout()` |\n:::\n\n#### Interpretation und Ergebnissatz\n\n> `plt.subplots(2, 2)` liefert eine Figure und ein (2, 2)-Array mit vier Axes,\n> `plt.subplots()` dagegen ein einzelnes Axes ohne Array, mit `squeeze=False`\n> bleibt die Form einheitlich. Die drei Maschinentypen haben mittlere\n> Verbrauchswerte von 36.06, 37.34 und 47.95 bei je 50 Maschinen.\n\n### Beispiel 3: Die vier Grundtypen\n\n#### Frage und Datenlage\n\nLinie, Streuung, Balken, Histogramm, vier Aufrufe, die fast alles abdecken,\nje einmal in matplotlib und in ggplot2.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmittel <- aggregate(verbrauch ~ typ, data = maschinen, FUN = mean)\nmittel$verbrauch <- round(mittel$verbrauch, 2)\nmittel\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       typ verbrauch\n1 Drehbank     36.06\n2    Fräse     37.34\n3   Presse     47.95\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(ggplot(maschinen, aes(laufzeit, verbrauch)) + geom_point(alpha = 0.5))\nprint(ggplot(mittel, aes(typ, verbrauch)) + geom_col(fill = \"grey70\"))\nprint(ggplot(maschinen, aes(verbrauch)) +\n        geom_histogram(bins = 20, fill = \"grey70\", colour = \"white\"))\n```\n\n::: {.cell-output-display}\n![Beispiel 3: Streuung, Balken und Histogramm in ggplot2.](matplotlib_files/figure-html/fig-b3-mp-r-3.png){#fig-b3-mp-r-1 width=100%}\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: Streuung, Balken und Histogramm in ggplot2.](matplotlib_files/figure-html/fig-b3-mp-r-4.png){#fig-b3-mp-r-2 width=100%}\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: Streuung, Balken und Histogramm in ggplot2.](matplotlib_files/figure-html/fig-b3-mp-r-5.png){#fig-b3-mp-r-3 width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmittel = maschinen.groupby(\"typ\")[\"verbrauch\"].mean().round(2)\nprint(mittel)\n\n# Fuer die Linie: Verbrauch nach Laufzeit in Stundenklassen\nklassen = pd.cut(maschinen[\"laufzeit\"], bins=range(2, 24, 2))\nverlauf = maschinen.groupby(klassen, observed=True)[\"verbrauch\"].mean()\nprint(verlauf.round(2))\n\nfig, achsen = plt.subplots(2, 2, figsize=(7, 4.4))\n_ = achsen[0, 0].plot(range(len(verlauf)), verlauf.to_numpy(), marker=\"o\", lw=1.6,\n                      color=\"0.3\")\n_ = achsen[0, 0].set_title(\"plot: Verlauf\", fontsize=10)\n_ = achsen[0, 1].scatter(maschinen[\"laufzeit\"], maschinen[\"verbrauch\"], s=8,\n                         alpha=0.5, color=\"0.3\")\n_ = achsen[0, 1].set_title(\"scatter: Zusammenhang\", fontsize=10)\n_ = achsen[1, 0].bar(mittel.index, mittel.to_numpy(), color=\"0.7\")\n_ = achsen[1, 0].set_title(\"bar: Vergleich\", fontsize=10)\n_ = achsen[1, 1].hist(maschinen[\"verbrauch\"], bins=20, color=\"0.7\",\n                      edgecolor=\"white\")\n_ = achsen[1, 1].set_title(\"hist: Verteilung\", fontsize=10)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: Linie, Streuung, Balken und Histogramm.](matplotlib_files/figure-html/fig-b3-mp-py-1.png){#fig-b3-mp-py width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint({\"anteil_ueber_50_prozent\":\n       round(float((maschinen[\"verbrauch\"] > 50).mean() * 100), 1),\n       \"median\": round(float(maschinen[\"verbrauch\"].median()), 2),\n       \"schiefe\": round(float(stats.skew(maschinen[\"verbrauch\"])), 3)})\n```\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Typ | mittlerer Verbrauch |\n|---|---|\n| Drehbank | **36.06** |\n| Fräse | **37.34** |\n| Presse | **47.95** |\n\n| Kennzahl | Wert |\n|---|---|\n| Anteil über 50 | **29.3 Prozent** |\n| Median | **40.55** |\n| Schiefe | **0.027** |\n\n| Aufruf | Aufgabe | ggplot2-Gegenstück |\n|---|---|---|\n| `achse.plot(x, y)` | Verlauf | `geom_line()` |\n| `achse.scatter(x, y)` | Zusammenhang | `geom_point()` |\n| `achse.bar(x, h)` | Vergleich | `geom_col()` |\n| `achse.hist(x, bins=)` | Verteilung | `geom_histogram()` |\n\n| Beobachtung | Erklärung |\n|---|---|\n| `plot` verbindet die Punkte in der **Reihenfolge der Daten** | Nicht nach x sortiert. Unsortierte Daten ergeben ein Gekritzel, das ist der häufigste Fehler bei `plot`. |\n| `bar` erwartet **fertige Höhen** | Wie `geom_col`. Ein Gegenstück zu `geom_bar`, das selbst zählt, gibt es nicht; dafür nimmt man `value_counts()` davor. |\n| `hist` zählt dagegen **selbst** | Und gibt die Klassengrenzen zurück, wenn man sie braucht. |\n| Der Verbrauch ist fast symmetrisch verteilt | Schiefe 0.027, Median 40.55. Knapp **29.3 Prozent** liegen über 50. |\n| Die Klassenbildung für den Verlauf macht man **selbst** | `pd.cut` plus `groupby`. In ggplot2 übernähme das `stat_summary()`. |\n\n::: {.note-box}\n**Was matplotlib nicht von sich aus tut** und wo die Zeilen hingehen, die man\nin ggplot2 spart:\n\n| Aufgabe | matplotlib |\n|---|---|\n| nach Gruppen einfärben | Schleife über die Gruppen |\n| Legende | `label=` je Aufruf, dann `achse.legend()` |\n| Glättungslinie | `np.polyfit` oder `statsmodels`, dann selbst zeichnen |\n| Klassen bilden | `pd.cut` und `groupby` |\n| Achsen teilen | `sharex=`, `sharey=` |\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Vier Aufrufe decken die vier Aufgaben ab: `plot` für den Verlauf, `scatter`\n> für den Zusammenhang, `bar` für den Vergleich der Mittelwerte 36.06, 37.34\n> und 47.95 und `hist` für die Verteilung, die mit einer Schiefe von 0.027 fast\n> symmetrisch ist.\n\n### Beispiel 4: Achsen, Grenzen und Skalen\n\n#### Frage und Datenlage\n\nDie Achse ist der Ort, an dem aus Zahlen Positionen werden. Vier Eingriffe:\nGrenzen setzen, logarithmisch skalieren, Ticks bestimmen, eine Hilfslinie\nziehen.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrenze <- 50\nround(c(anteil_ueber_grenze = mean(maschinen$verbrauch > grenze) * 100,\n        anzahl = sum(maschinen$verbrauch > grenze)), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nanteil_ueber_grenze              anzahl \n               29.3                44.0 \n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(maschinen, aes(laufzeit, verbrauch)) +\n  geom_point(alpha = 0.5, size = 1.1) +\n  geom_hline(yintercept = grenze, linetype = \"dashed\", colour = \"#b2182b\") +\n  scale_x_continuous(breaks = seq(0, 22, 4)) +\n  coord_cartesian(xlim = c(0, 23), ylim = c(0, 80)) +\n  labs(x = \"Laufzeit in Stunden\", y = \"Verbrauch\")\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselben Eingriffe in ggplot2.](matplotlib_files/figure-html/fig-b4-mp-r-3.png){#fig-b4-mp-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ngrenze = 50\nprint({\"anteil_ueber_grenze\":\n       round(float((maschinen[\"verbrauch\"] > grenze).mean() * 100), 1),\n       \"anzahl\": int((maschinen[\"verbrauch\"] > grenze).sum())})\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3))\n_ = achsen[0].scatter(maschinen[\"laufzeit\"], maschinen[\"verbrauch\"], s=8,\n                      alpha=0.5, color=\"0.3\")\n_ = achsen[0].axhline(grenze, ls=\"--\", color=\"#b2182b\")\n_ = achsen[0].set_xlim(0, 23)\n_ = achsen[0].set_ylim(0, 80)\n_ = achsen[0].set_xticks(range(0, 24, 4))\n_ = achsen[0].set_title(\"Grenzen, Ticks, Hilfslinie\", fontsize=10)\n\n_ = achsen[1].scatter(maschinen[\"laufzeit\"], maschinen[\"verbrauch\"], s=8,\n                      alpha=0.5, color=\"0.3\")\n_ = achsen[1].set_yscale(\"log\")\n_ = achsen[1].set_title(\"dieselben Daten, y logarithmisch\", fontsize=10)\nfor achse in achsen:\n    _ = achse.set_xlabel(\"Laufzeit in Stunden\")\n    _ = achse.set_ylabel(\"Verbrauch\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: Grenzen, Ticks, Hilfslinie und logarithmische Achse.](matplotlib_files/figure-html/fig-b4-mp-py-1.png){#fig-b4-mp-py width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# Was die logarithmische Achse mit den Abstaenden macht\npunkte = np.array([5., 10., 20., 40., 80.])\nprint(pd.DataFrame({\"wert\": punkte,\n                    \"abstand_linear\": np.r_[np.nan, np.diff(punkte)],\n                    \"abstand_logarithmisch\": np.r_[np.nan, np.diff(np.log10(punkte))]\n                    }).round(4).to_string(index=False))\n```\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Kennzahl | Wert |\n|---|---|\n| Anteil über der Grenze von 50 | **29.3 Prozent** |\n| Anzahl Maschinen | **44** |\n\nWas die logarithmische Achse mit gleichen Verhältnissen macht:\n\n| Wert | 5 | 10 | 20 | 40 | 80 |\n|---|---|---|---|---|---|\n| Abstand linear |   | 5 | 10 | 20 | 40 |\n| Abstand logarithmisch |   | **0.3010** | **0.3010** | **0.3010** | **0.3010** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die Verdopplung hat auf der Log-Achse **immer denselben Abstand** | 0.3010, also $\\log_{10} 2$. Das ist der Zweck: Gleiche **Verhältnisse** bekommen gleiche Strecken. |\n| Linear wächst der Abstand von 5 auf 40 | Dieselben Verdopplungen, achtfach verschiedene Strecken. |\n| `set_ylim` in matplotlib entspricht `coord_cartesian` in ggplot2 | Es zoomt, ohne Daten zu entfernen. Das ggplot2-Gegenstück `scale_y_continuous(limits =)` würde Punkte verwerfen. |\n| `axhline` ist die schnellste Anmerkung | Eine Grenzlinie plus die Zahl im Text sagt mehr als eine Legende. Hier: 44 von 150 Maschinen, also 29.3 Prozent, liegen darüber. |\n| `set_xticks` verhindert unglückliche Automatik | Bei Laufzeiten in Stunden sind Vierer-Schritte lesbarer als die automatischen 2.5er. |\n\n::: {.warning-box}\n**Wann eine logarithmische Achse richtig ist:** wenn die Daten über mehrere\nGrössenordnungen laufen **und** Verhältnisse interessieren, Einkommen,\nBevölkerungszahlen, Konzentrationen.\n\nWann nicht: bei Werten, die null oder negativ werden können, und wenn das\nPublikum die Achse nicht als logarithmisch erkennt. Eine Log-Achse ohne\ndeutliche Beschriftung ist eine\n[irreführende Darstellung](irrefuehrende-darstellungen.qmd), ein linearer\nAnstieg sieht dort flach aus.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> 44 der 150 Maschinen, also 29.3 Prozent, liegen über der Grenze von 50. Auf\n> einer logarithmischen Achse hat jede Verdopplung denselben Abstand von 0.3010,\n> während er linear von 5 auf 40 wächst.\n\n### Beispiel 5: Beschriftung und Export\n\n#### Frage und Datenlage\n\nAus der Rohgrafik wird eine Abbildung. Dazu kommen Titel, Einheit, Anmerkung\nund Quelle und dann die Frage, mit welchen Einstellungen sie gespeichert\nwird.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npresse <- maschinen[maschinen$typ == \"Presse\", ]\nandere <- maschinen[maschinen$typ != \"Presse\", ]\nround(c(mittel_presse = mean(presse$verbrauch),\n        mittel_andere = mean(andere$verbrauch),\n        differenz = mean(presse$verbrauch) - mean(andere$verbrauch)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmittel_presse mittel_andere     differenz \n        47.95         36.70         11.26 \n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(maschinen, aes(laufzeit, verbrauch)) +\n  geom_point(aes(colour = typ == \"Presse\"), alpha = 0.7, size = 1.3) +\n  scale_colour_manual(values = c(`FALSE` = \"#c7c7c7\", `TRUE` = \"#b2182b\"),\n                      guide = \"none\") +\n  annotate(\"text\", x = 4, y = 68, colour = \"#b2182b\", hjust = 0, size = 3.4,\n           label = \"Pressen: rund 11 Einheiten mehr\") +\n  labs(title = \"Pressen verbrauchen bei gleicher Laufzeit deutlich mehr\",\n       subtitle = \"150 Maschinen, Verbrauch gegen Laufzeit\",\n       x = \"Laufzeit in Stunden\", y = \"Verbrauch in Kilowattstunden\",\n       caption = \"Quelle: Betriebsdatenerfassung, Stand 2026\")\n```\n\n::: {.cell-output-display}\n![Beispiel 5: die fertige Fassung in ggplot2.](matplotlib_files/figure-html/fig-b5-mp-r-3.png){#fig-b5-mp-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nist_presse = maschinen[\"typ\"] == \"Presse\"\nprint({\"mittel_presse\": round(float(maschinen.loc[ist_presse, \"verbrauch\"].mean()), 2),\n       \"mittel_andere\": round(float(maschinen.loc[~ist_presse, \"verbrauch\"].mean()), 2),\n       \"differenz\": round(float(maschinen.loc[ist_presse, \"verbrauch\"].mean()\n                                - maschinen.loc[~ist_presse, \"verbrauch\"].mean()), 2)})\n\nfig, achse = plt.subplots(figsize=(7, 3.2))\n_ = achse.scatter(maschinen.loc[~ist_presse, \"laufzeit\"],\n                  maschinen.loc[~ist_presse, \"verbrauch\"],\n                  s=12, alpha=0.7, color=\"#c7c7c7\")\n_ = achse.scatter(maschinen.loc[ist_presse, \"laufzeit\"],\n                  maschinen.loc[ist_presse, \"verbrauch\"],\n                  s=12, alpha=0.7, color=\"#b2182b\")\n_ = achse.annotate(\"Pressen: rund 11 Einheiten mehr\", xy=(4, 68),\n                   color=\"#b2182b\", fontsize=9)\n_ = achse.set_title(\"Pressen verbrauchen bei gleicher Laufzeit deutlich mehr\")\n_ = achse.set_xlabel(\"Laufzeit in Stunden\")\n_ = achse.set_ylabel(\"Verbrauch in Kilowattstunden\")\n_ = fig.text(0.01, -0.04, \"Quelle: Betriebsdatenerfassung, Stand 2026\",\n             fontsize=7, color=\"0.4\")\nfor rand in (\"top\", \"right\"):\n    _ = achse.spines[rand].set_visible(False)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselbe fertige Fassung in matplotlib.](matplotlib_files/figure-html/fig-b5-mp-py-1.png){#fig-b5-mp-py width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# Was die Exporteinstellungen bedeuten\neinstellungen = pd.DataFrame({\n    \"zweck\": [\"Bildschirm\", \"Bericht (Druck)\", \"Folie\", \"Weiterverarbeitung\"],\n    \"format\": [\"png\", \"png\", \"png\", \"pdf oder svg\"],\n    \"dpi\": [96, 300, 150, \", \"],\n    \"bbox_inches\": [\"\", \"tight\", \"tight\", \"tight\"]})\nprint(einstellungen.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             zweck       format dpi bbox_inches\n        Bildschirm          png  96            \n   Bericht (Druck)          png 300       tight\n             Folie          png 150       tight\nWeiterverarbeitung pdf oder svg  ,        tight\n```\n\n\n:::\n\n```{.python .cell-code}\nbreite_zoll, hoehe_zoll = 7, 3.2\nfor dpi in (96, 150, 300):\n    print(f\"dpi {dpi:3d}: {int(breite_zoll * dpi)} x {int(hoehe_zoll * dpi)} Pixel\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndpi  96: 672 x 307 Pixel\ndpi 150: 1050 x 480 Pixel\ndpi 300: 2100 x 960 Pixel\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Gruppe | mittlerer Verbrauch |\n|---|---|\n| Pressen | **47.95** |\n| übrige | **36.70** |\n| **Differenz** | **11.26** |\n\nExportgrössen bei 7 × 3.2 Zoll:\n\n| dpi | Pixel |\n|---|---|\n| 96 | **672 × 307** |\n| 150 | **1050 × 480** |\n| 300 | **2100 × 960** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Der Titel nennt die **Aussage** | Nicht \"Streudiagramm Verbrauch gegen Laufzeit\". Die Zahl dazu, 11.26 Einheiten Unterschied, steht in der Anmerkung. |\n| Die Anmerkung steht **im Bild** | `annotate` in beiden Sprachen. Sie ersetzt einen Absatz Erklärtext darunter, den in fünf Sekunden niemand liest. |\n| Die Einheit gehört an die **Achse** | \"Verbrauch in Kilowattstunden\", nicht \"verbrauch\". Der Spaltenname aus der Datei ist keine Achsenbeschriftung. |\n| Die Grafik hat **zwei Farben**, nicht drei | Pressen rot, alle anderen grau. Die Unterscheidung Fräse/Drehbank trägt hier nichts zur Aussage bei. |\n| `bbox_inches=\"tight\"` ist beim Speichern fast immer nötig | Sonst werden Titel und Achsenbeschriftung abgeschnitten, `tight_layout()` allein wirkt nur auf die Anzeige. |\n| 300 dpi ergeben **2100 × 960** Pixel | Bei 7 Zoll Breite. Für den Druck ist das die Untergrenze; für den Bildschirm sind 96 bis 150 genug, und die Datei bleibt klein. |\n\n::: {.note-box}\n**Der Exportbefehl mit den Argumenten, die zählen:**\n\n```python\nfig.savefig(\"abbildung.png\", dpi=300, bbox_inches=\"tight\",\n            facecolor=\"white\")\n```\n\n| Argument | Warum |\n|---|---|\n| `dpi` | Auflösung; 300 für Druck, 150 für Folien |\n| `bbox_inches=\"tight\"` | schneidet den Rand passend, nichts fehlt |\n| `facecolor=\"white\"` | sonst ist der Hintergrund bei manchen Themes durchsichtig |\n| `format=\"pdf\"` | Vektorformat, beliebig skalierbar, für Berichte die bessere Wahl |\n\nIn R ist das Gegenstück `ggsave(\"abbildung.png\", breite, hoehe, dpi = 300)`.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Pressen verbrauchen im Mittel 47.95 gegenüber 36.70 bei den übrigen Maschinen,\n> also 11.26 Einheiten mehr. Die fertige Abbildung trägt diese Aussage im Titel,\n> die Zahl in der Anmerkung und die Einheit an der Achse; beim Export sorgt\n> `bbox_inches=\"tight\"` dafür, dass nichts davon abgeschnitten wird.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nWorin unterscheiden sich `Figure`, `Axes` und `Axis`?\n\n- [x] Figure ist das Bild, Axes die Zeichenfläche, Axis eine einzelne Achse ~\n      Richtig. Die Ähnlichkeit von Axes und Axis ist eingebaut; ein Axes ist\n      trotz des Namens kein Strich, sondern ein ganzes Koordinatensystem.\n- [ ] Axes und Axis sind dasselbe, nur Einzahl und Mehrzahl ~ Das ist die\n      naheliegende und falsche Deutung.\n- [ ] Figure und Axes sind dasselbe ~ Eine Figure kann viele Axes enthalten.\n:::\n\n::: {.quiz}\nZwei Figuren sind offen, dann folgt `plt.title(\"B\")`. Wo landet der Titel?\n\n- [x] Auf der zuletzt angelegten Figur ~ Richtig, `plt.` wirkt auf die\n      aktuelle Figur, unabhängig davon, welches Axes im Code davor bearbeitet\n      wurde. Genau deshalb ist der objektorientierte Weg eindeutig.\n- [ ] Auf beiden ~ pyplot wirkt immer nur auf eine.\n- [ ] Das führt zu einem Fehler ~ Es läuft fehlerfrei durch und landet nur am\n      falschen Ort, das macht den Fehler so schwer zu finden.\n:::\n\n::: {.quiz}\n`plt.subplots(2, 2)` und `plt.subplots()` geben Verschiedenes zurück. Was?\n\n- [x] Einmal ein (2, 2)-Array mit vier Axes, einmal ein einzelnes Axes ohne\n      Array ~ Richtig. Code, der mit `achsen[0]` arbeitet, bricht deshalb ab,\n      sobald nur eine Teilgrafik übrig ist. `squeeze=False` macht die Form\n      einheitlich.\n- [ ] Beide geben ein Array zurück, nur verschieden gross ~ Bei einer einzigen\n      Teilgrafik wird die Dimension entfernt.\n- [ ] Beide geben ein einzelnes Axes zurück ~ Bei 2 mal 2 sind es vier.\n:::\n\n::: {.quiz}\nWarum ergibt `achse.plot(x, y)` bei unsortierten Daten ein Gekritzel?\n\n- [x] plot verbindet die Punkte in der Reihenfolge der Daten, nicht nach x ~\n      Richtig. Vor einem Linienplot gehört `sort_values(\"x\")`, sonst springt\n      die Linie hin und her.\n- [ ] plot ist nur für Zeitreihen gedacht ~ Es funktioniert für jede geordnete\n      Grösse, verlangt aber, dass die Ordnung in den Daten steht.\n- [ ] Die Punkte sind zu dicht ~ Die Dichte ändert an der Reihenfolge nichts.\n:::\n\n::: {.quiz}\nAuf einer logarithmischen y-Achse haben die Werte 5, 10, 20, 40 und 80 jeweils\ndenselben Abstand von 0.3010. Warum?\n\n- [x] Weil gleiche Verhältnisse gleiche Strecken bekommen; 0.3010 ist der\n      Zehnerlogarithmus von 2 ~ Richtig. Das ist der Zweck der Log-Achse: Sie\n      macht aus Verdopplungen gleich lange Schritte.\n- [ ] Weil die Achse die Werte gleichmässig verteilt ~ Sie verteilt nicht die\n      Werte, sondern ihre Logarithmen.\n- [ ] Das ist Zufall dieser Zahlenreihe ~ Es gilt für jede Folge mit konstantem\n      Faktor.\n:::\n\n::: {.quiz}\nBeim Speichern mit `fig.savefig(\"bild.png\")` fehlt ein Teil der\nAchsenbeschriftung. Was hilft?\n\n- [x] `bbox_inches=\"tight\"` ~ Richtig. `tight_layout()` wirkt nur auf die\n      Anzeige; beim Export bestimmt `bbox_inches`, wie der Rand beschnitten\n      wird.\n- [ ] Eine höhere dpi-Zahl ~ Die ändert die Auflösung, nicht den Ausschnitt.\n- [ ] Eine kleinere Schrift ~ Behebt das Symptom manchmal, nicht die Ursache.\n:::\n\n## Verlinkte Ressourcen\n\n- [matplotlib: Anatomy of a Figure](https://matplotlib.org/stable/gallery/showcase/anatomy.html)\n- [matplotlib: Cheatsheets](https://matplotlib.org/cheatsheets/)\n- [ggplot2](ggplot2.qmd), dieselben Aufgaben in R\n- [seaborn und plotly](seaborn-plotly.qmd), was auf matplotlib aufsetzt\n- [Diagrammtyp wählen](diagrammtyp-waehlen.qmd), welche Grafik die Aufgabe löst\n",
    "supporting": [
      "matplotlib_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}