{
  "hash": "568e56e9ac69114922ad846525627d86",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Wahrnehmung und Kodierung\"\ndescription: \"Welche visuellen Kanäle genau abgelesen werden und welche nicht.\"\ncategories: [\"Wahrnehmung\", \"Visualisierung\", \"R\", \"Python\"]\nquelle: [\"DAVI\"]\nseitentyp: konzept\nstand: fertig\norder: 20\n---\n\n\n\n\n\n## Kernideen\n\n- Visuelle Kanäle sind unterschiedlich genau ablesbar, und die Rangfolge ist\n  bekannt.\n- **Position auf gemeinsamer Skala schlägt alles andere.** Die wichtigste\n  Variable bekommt den genauesten Kanal.\n- Fläche wird nicht nur ungenau, sondern **systematisch zu klein** geschätzt und wer den Radius statt der Fläche kodiert, verstärkt den Fehler noch.\n- Einige Merkmale werden vorbewusst erfasst, in weniger als einer\n  Viertelsekunde. **Hervorhebung wirkt nur durch Kontrast, und Kontrast nur,\n  wenn er selten ist.**\n- Farbton unterscheidet Kategorien, er kodiert keine Mengen.\n- Was keine Daten darstellt, konkurriert mit dem, was Daten darstellt.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Zielbild und Publikum](zielbild-audience.qmd), weil die\nAussage bestimmt, welche Variable den genauesten Kanal verdient. Die\nKonsequenzen für die Wahl stehen unter\n[Diagrammtyp wählen](diagrammtyp-waehlen.qmd).\n:::\n\n### Die Rangfolge der Kanäle\n\nDaten werden über visuelle Eigenschaften kodiert: Position, Länge, Winkel,\nFläche, Helligkeit, Farbton, Form. Diese Kanäle sind nicht gleichwertig. Wie\ngenau Menschen Werte daraus ablesen, ist untersucht, und die Reihenfolge ist\nstabil:\n\n| Rang | Kanal | Beispiel | Genauigkeit |\n|---|---|---|---|\n| 1 | Position auf gemeinsamer Skala | Punkte in einem Streudiagramm, Balkenenden an einer Achse | sehr hoch |\n| 2 | Position auf getrennten Skalen | dieselbe Grösse in mehreren kleinen Teilgrafiken | hoch |\n| 3 | Länge | Balken ohne gemeinsame Grundlinie | hoch |\n| 4 | Winkel und Steigung | Tortensegmente, Linienanstieg | mittel |\n| 5 | Fläche | Blasengrösse, Kacheln | niedrig |\n| 6 | Helligkeit und Sättigung | Heatmap-Zellen | niedrig |\n| 7 | Farbton | Kategorienfarben | nur für Unterscheidung, nicht für Mengen |\n\nDaraus folgt die praktisch wichtigste Regel der ganzen Visualisierung: **Die\nVariable, auf die es ankommt, bekommt Position.** Alles andere sind\nZusatzkanäle.\n\n### Warum Fläche doppelt gefährlich ist\n\nBei der Fläche kommen zwei Fehler zusammen, und sie verstärken einander.\n\nDer erste ist ein **Wahrnehmungsfehler**: Eine Fläche wird nicht proportional\nzu ihrer Grösse geschätzt, sondern ungefähr mit einem Exponenten um 0.7. Eine\nachtmal so grosse Fläche wirkt nur gut viermal so gross.\n\nDer zweite ist ein **Konstruktionsfehler**: Wer den **Radius** proportional zum\nWert setzt statt der Fläche, quadriert den Unterschied. Aus achtmal so viel\nwird eine 64-mal so grosse Fläche.\n\nDie beiden Fehler zeigen in entgegengesetzte Richtungen, heben sich aber nicht\nauf, sie machen die Grafik nur unvorhersehbar falsch. Beispiel 2 rechnet es\ndurch.\n\n### Was das Auge vorbewusst erfasst\n\nBestimmte Merkmale werden in unter einer Viertelsekunde erfasst, ohne dass man\nsuchen muss. Dazu gehören Farbe, Grösse, Ausrichtung, Umschliessung und\nräumliche Lage. Genau diese Merkmale eignen sich zum Hervorheben.\n\nDie Bedingung ist **Seltenheit**. Ein roter Balken unter zwanzig grauen springt\nins Auge; fünf rote Balken unter fünfzehn grauen sind nur noch bunt. Daraus\nfolgt die Arbeitsregel: alles grau, und genau das eine, worum es geht, farbig.\nMehr dazu unter [Farbe](farbe.qmd).\n\n### Was keine Daten zeigt, stört\n\nJedes Element einer Grafik konkurriert um Aufmerksamkeit. Was keine\nInformation trägt, nimmt sie dem, was welche trägt.\n\nStreichkandidaten, in dieser Reihenfolge:\n\n- dreidimensionale Effekte, Schatten, Farbverläufe in Flächen\n- dichte Gitternetze, dicke Rahmen, Hintergrundfüllungen\n- Legenden, wenn die Serien direkt beschriftet werden können\n- doppelte Information: Werte an den Balken **und** Achsenbeschriftung **und**\n  Legende\n\nNicht streichen: Achsenbeschriftung mit Einheit, Datenquelle, und den Titel mit\nder Aussage. Sparsamkeit, die den Kontext entfernt, macht die Grafik\nunbrauchbar; das Ziel ist weniger Zierrat, nicht weniger Information.\n\n### Die Konsequenz für die Praxis\n\nWer die Kanalrangfolge kennt, trifft drei Entscheidungen fast automatisch:\n\n1. **Vergleich von Mengen:** Balken, weil Länge auf gemeinsamer Skala.\n2. **Zusammenhang zweier Grössen:** Streudiagramm, weil Position zweimal.\n3. **Viele Kategorien:** nicht Farbe, sondern Position, sortierte Balken oder\n   kleine Teilgrafiken nebeneinander.\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Länge gegen Winkel\n\n#### Frage und Datenlage\n\nFünf Kategorien mit den Anteilen 23, 21, 19, 19 und 18 Prozent. Dieselben fünf\nZahlen einmal als Balken und einmal als Torte und die Frage, wie gross die\nUnterschiede im jeweiligen Kanal überhaupt sind.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkategorie <- c(\"A\", \"B\", \"C\", \"D\", \"E\")\nwert <- c(23, 21, 19, 19, 18)\ngrad <- wert / sum(wert) * 360\n\nround(rbind(wert = wert, grad = grad), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     [,1] [,2] [,3] [,4] [,5]\nwert 23.0 21.0 19.0 19.0 18.0\ngrad 82.8 75.6 68.4 68.4 64.8\n```\n\n\n:::\n\n```{.r .cell-code}\n# Alle Paare: Wie gross ist der Unterschied im Winkel?\npaare <- t(combn(5, 2))\nvergleich <- data.frame(\n  paar = paste0(kategorie[paare[, 1]], \"-\", kategorie[paare[, 2]]),\n  punkte = abs(wert[paare[, 1]] - wert[paare[, 2]]),\n  grad = round(abs(grad[paare[, 1]] - grad[paare[, 2]]), 1))\nvergleich[order(vergleich$grad), ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   paar punkte grad\n8   C-D      0  0.0\n9   C-E      1  3.6\n10  D-E      1  3.6\n1   A-B      2  7.2\n5   B-C      2  7.2\n6   B-D      2  7.2\n7   B-E      3 10.8\n2   A-C      4 14.4\n3   A-D      4 14.4\n4   A-E      5 18.0\n```\n\n\n:::\n\n```{.r .cell-code}\nc(paare_unter_10_grad = sum(vergleich$grad < 10), paare_gesamt = nrow(vergleich))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npaare_unter_10_grad        paare_gesamt \n                  6                  10 \n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nbarplot(wert, names.arg = kategorie, col = neutral,\n        ylab = \"Anteil in Prozent\", main = \"Länge\")\npie(wert, labels = kategorie, col = grey.colors(5), main = \"Winkel\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselben Anteile als Länge und als Winkel.](wahrnehmung-kodierung_files/figure-html/fig-b1-wk-r-1.png){#fig-b1-wk-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport itertools\n\nkategorie = list(\"ABCDE\")\nwert = np.array([23., 21., 19., 19., 18.])\ngrad = wert / wert.sum() * 360\n\nprint(pd.DataFrame({\"wert\": wert, \"grad\": grad}, index=kategorie).round(1).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         A     B     C     D     E\nwert  23.0  21.0  19.0  19.0  18.0\ngrad  82.8  75.6  68.4  68.4  64.8\n```\n\n\n:::\n\n```{.python .cell-code}\nzeilen = [{\"paar\": f\"{kategorie[i]}-{kategorie[j]}\",\n           \"punkte\": abs(wert[i] - wert[j]),\n           \"grad\": round(abs(grad[i] - grad[j]), 1)}\n          for i, j in itertools.combinations(range(5), 2)]\nvergleich = pd.DataFrame(zeilen).sort_values(\"grad\")\nprint(vergleich.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npaar  punkte  grad\n C-D     0.0   0.0\n C-E     1.0   3.6\n D-E     1.0   3.6\n A-B     2.0   7.2\n B-C     2.0   7.2\n B-D     2.0   7.2\n B-E     3.0  10.8\n A-C     4.0  14.4\n A-D     4.0  14.4\n A-E     5.0  18.0\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"paare_unter_10_grad\": int((vergleich[\"grad\"] < 10).sum()),\n       \"paare_gesamt\": len(vergleich)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'paare_unter_10_grad': 6, 'paare_gesamt': 10}\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.4))\nachsen[0].bar(kategorie, wert, color=NEUTRAL)\nachsen[0].set_ylabel(\"Anteil in Prozent\")\nachsen[0].set_title(\"Länge\")\n_ = achsen[1].pie(wert, labels=kategorie,\n                  colors=[str(g) for g in np.linspace(0.3, 0.85, 5)])\n_ = achsen[1].set_title(\"Winkel\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Gegenüberstellung in Python.](wahrnehmung-kodierung_files/figure-html/fig-b1-wk-py-1.png){#fig-b1-wk-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Kategorie | A | B | C | D | E |\n|---|---|---|---|---|---|\n| Anteil in Prozent | 23 | 21 | 19 | 19 | 18 |\n| Segment in Grad | 82.8 | 75.6 | 68.4 | 68.4 | 64.8 |\n\nDie zehn Paarvergleiche, nach Winkeldifferenz sortiert:\n\n| Paar | C-D | C-E | D-E | A-B | B-C | B-D | B-E | A-C | A-D | A-E |\n|---|---|---|---|---|---|---|---|---|---|---|\n| Prozentpunkte | 0 | 1 | 1 | 2 | 2 | 2 | 3 | 4 | 4 | 5 |\n| **Grad** | **0.0** | **3.6** | **3.6** | **7.2** | **7.2** | **7.2** | **10.8** | **14.4** | **14.4** | **18.0** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| **Sechs von zehn** Paaren unterscheiden sich um weniger als 10 Grad | Bei einem Vollkreis von 360 Grad. Das ist die Grössenordnung, ab der ein Winkelvergleich zur Ratesache wird und das ist keine Meinung, sondern die Geometrie der Grafik. |\n| Der grösste Unterschied im Datensatz sind **5 Prozentpunkte** | Und selbst der ist als Winkel nur 18 Grad, also ein Zwanzigstel des Kreises. |\n| C und D sind **exakt gleich** | In beiden Grafiken. Im Balkendiagramm sieht man das sofort, in der Torte muss man es raten. |\n| Im Balkendiagramm ist die Reihenfolge ablesbar | Weil alle Balken auf derselben Grundlinie beginnen: Position auf gemeinsamer Skala, Rang 1 der Tabelle. |\n| In der Torte beginnt jedes Segment woanders | Deshalb bleibt nur der Winkel, Rang 4 und bei Segmenten, die nicht nebeneinander liegen, zusätzlich der Vergleich über den Kreis hinweg. |\n\n::: {.note-box}\n**Wann eine Torte trotzdem geht:** wenn es um **einen** Anteil gegen den Rest\ngeht und der Unterschied gross ist, 70 gegen 30 liest jeder. Bei fünf\nähnlichen Anteilen ist sie die schlechteste verfügbare Wahl.\n\nDie ehrliche Alternative bei Anteilen, die sich zu 100 addieren, ist der\n**sortierte Balken** mit direkt angeschriebenen Werten.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Von zehn Paarvergleichen unterscheiden sich sechs um weniger als 10 von 360\n> Grad, der grösste Unterschied beträgt 18 Grad. Als Balkenlänge auf\n> gemeinsamer Grundlinie sind dieselben Unterschiede unmittelbar ablesbar.\n\n### Beispiel 2: Der doppelte Fehler der Fläche\n\n#### Frage und Datenlage\n\nVier Werte im Verhältnis 1 : 2 : 4 : 8, dargestellt als Kreise. Einmal wird\nder **Radius** proportional zum Wert gesetzt, einmal die **Fläche**. Dazu die\nFrage, wie gross der Unterschied am Ende wahrgenommen wird.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwert <- c(1, 2, 4, 8)\n\nradius_falsch <- wert / wert[1]          # Radius = Wert\nradius_richtig <- sqrt(wert / wert[1])   # Fläche = Wert\n\nround(rbind(wert = wert,\n            radius_falsch = radius_falsch,\n            flaeche_falsch = radius_falsch^2,\n            radius_richtig = radius_richtig,\n            flaeche_richtig = radius_richtig^2), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                [,1]  [,2] [,3]   [,4]\nwert               1 2.000    4  8.000\nradius_falsch      1 2.000    4  8.000\nflaeche_falsch     1 4.000   16 64.000\nradius_richtig     1 1.414    2  2.828\nflaeche_richtig    1 2.000    4  8.000\n```\n\n\n:::\n\n```{.r .cell-code}\n# Wahrnehmung: Flaeche wirkt ungefaehr mit dem Exponenten 0.7\nround(c(echter_unterschied = 8,\n        flaeche_korrekt_kodiert = 8,\n        davon_wahrgenommen = 8^0.7,\n        flaeche_bei_radiuskodierung = 64,\n        davon_wahrgenommen = 64^0.7), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         echter_unterschied     flaeche_korrekt_kodiert \n                       8.00                        8.00 \n         davon_wahrgenommen flaeche_bei_radiuskodierung \n                       4.29                       64.00 \n         davon_wahrgenommen \n                      18.38 \n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(2, 2, 3, 1))\nfor (nm in c(\"Radius = Wert\", \"Fläche = Wert\")) {\n  r <- if (nm == \"Radius = Wert\") radius_falsch else radius_richtig\n  symbols(seq_along(wert), rep(0, 4), circles = r, inches = 0.42,\n          bg = neutral, fg = \"white\", xlab = \"\", ylab = \"\", axes = FALSE,\n          main = nm, ylim = c(-1, 1))\n  text(seq_along(wert), -0.85, labels = wert)\n}\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 2: links Radius proportional zum Wert, rechts Fläche proportional zum Wert.](wahrnehmung-kodierung_files/figure-html/fig-b2-wk-r-3.png){#fig-b2-wk-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nwert = np.array([1., 2., 4., 8.])\n\nradius_falsch = wert / wert[0]\nradius_richtig = np.sqrt(wert / wert[0])\n\nprint(pd.DataFrame({\"wert\": wert,\n                    \"radius_falsch\": radius_falsch,\n                    \"flaeche_falsch\": radius_falsch ** 2,\n                    \"radius_richtig\": radius_richtig,\n                    \"flaeche_richtig\": radius_richtig ** 2}).round(3).T)\n\nprint({\"echter_unterschied\": 8,\n       \"flaeche_korrekt_kodiert\": 8,\n       \"davon_wahrgenommen\": round(8 ** 0.7, 2),\n       \"flaeche_bei_radiuskodierung\": 64,\n       \"davon_wahrgenommen_2\": round(64 ** 0.7, 2)})\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nfor achse, (titel, r) in zip(achsen, [(\"Radius = Wert\", radius_falsch),\n                                      (\"Fläche = Wert\", radius_richtig)]):\n    # In matplotlib ist s die FLAECHE des Punktes, nicht der Radius.\n    _ = achse.scatter(np.arange(1, 5), np.zeros(4), s=(r * 26) ** 2,\n                      color=NEUTRAL, edgecolor=\"white\")\n    for x, w in zip(np.arange(1, 5), wert):\n        _ = achse.text(x, -0.85, str(int(w)), ha=\"center\")\n    _ = achse.set_title(titel)\n    _ = achse.set_ylim(-1, 1)\n    _ = achse.axis(\"off\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselbe Gegenüberstellung in Python.](wahrnehmung-kodierung_files/figure-html/fig-b2-wk-py-1.png){#fig-b2-wk-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Wert | 1 | 2 | 4 | 8 |\n|---|---|---|---|---|\n| Radius bei **Radius = Wert** | 1 | 2 | 4 | **8** |\n| ergibt eine Fläche von | 1 | 4 | 16 | **64** |\n| Radius bei **Fläche = Wert** | 1 | 1.414 | 2 | **2.828** |\n| ergibt eine Fläche von | 1 | 2 | 4 | **8** |\n\n| Kette | Faktor |\n|---|---|\n| echter Unterschied in den Daten | **8** |\n| Fläche bei korrekter Kodierung | 8 → wahrgenommen als **4.29** |\n| Fläche bei Radiuskodierung | 64 → wahrgenommen als **18.38** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Radius proportional zum Wert erzeugt eine **64-fache Fläche** | Aus achtmal so viel. Der Fehler ist nicht klein, er ist quadratisch und je grösser die Spannweite der Daten, desto schlimmer. |\n| Der richtige Radius ist die **Wurzel** | 2.828 statt 8 für den grössten Wert. Das sieht nach zu wenig aus, ist aber die korrekte Fläche. |\n| Selbst korrekt kodiert wirken **8-fach nur wie 4.3-fach** | Wegen des Exponenten um 0.7. Fläche untertreibt also grundsätzlich, auch wenn alles richtig gemacht ist. |\n| Die beiden Fehler heben sich **nicht** auf | Untertreibung um den Faktor 0.7 im Exponenten, Übertreibung durch Quadrieren: Unter dem Strich bleiben statt 8 wahrgenommene 18.4. **Falsch in die andere Richtung ist nicht richtig.** |\n| In matplotlib ist `s` die **Fläche** | In `symbols()` von R dagegen der Radius. Wer die Sprache wechselt und die Formel mitnimmt, baut den Fehler ein. |\n\n::: {.warning-box}\n**Die Regel in einem Satz:** Wenn Fläche sein muss, dann Radius gleich Wurzel\ndes Werts und eine **Legende mit zwei bis drei Referenzkreisen**, weil ohne\nsie niemand die Grösse in eine Zahl zurückübersetzen kann.\n\nBesser ist meistens, die Fläche gar nicht zu brauchen. Fläche ist der Kanal\nfür die **dritte** Variable, wenn die zwei Positionen schon vergeben sind,\nnie für die Hauptaussage.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Wird der Radius proportional zum Wert gesetzt, erscheint ein achtfacher\n> Unterschied als 64-fache Fläche und wirkt wie das 18.4-Fache. Korrekt über\n> die Wurzel kodiert entsteht die achtfache Fläche, die wegen des\n> Wahrnehmungsexponenten von rund 0.7 wie das 4.3-Fache wirkt.\n\n### Beispiel 3: Ein Akzent gegen fünf\n\n#### Frage und Datenlage\n\nZehn Balken. Einmal ist einer hervorgehoben, einmal fünf. Dieselben Daten,\ndieselbe Farbe, nur die Häufigkeit des Akzents ändert sich.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwerte <- c(12, 15, 9, 22, 14, 11, 17, 13, 19, 10)\neine <- c(FALSE, FALSE, FALSE, TRUE, rep(FALSE, 6))\nviele <- c(TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE)\n\nfor (nm in c(\"eine\", \"viele\")) {\n  maske <- get(nm)\n  cat(sprintf(\"%-6s %d von %d Balken, %.1f Prozent der Balkenfläche\\n\",\n              nm, sum(maske), length(werte),\n              sum(werte[maske]) / sum(werte) * 100))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\neine   1 von 10 Balken, 15.5 Prozent der Balkenfläche\nviele  5 von 10 Balken, 47.2 Prozent der Balkenfläche\n```\n\n\n:::\n\n```{.r .cell-code}\nc(hoechster_balken = which.max(werte), sein_wert = max(werte))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nhoechster_balken        sein_wert \n               4               22 \n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(3, 4, 3, 1))\nbarplot(werte, col = ifelse(eine, akzent, neutral),\n        main = \"ein Akzent\", ylab = \"Wert\", border = NA)\nbarplot(werte, col = ifelse(viele, akzent, neutral),\n        main = \"fünf Akzente\", ylab = \"Wert\", border = NA)\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 3: ein Akzent unter zehn Balken, und fünf.](wahrnehmung-kodierung_files/figure-html/fig-b3-wk-r-3.png){#fig-b3-wk-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nwerte = np.array([12, 15, 9, 22, 14, 11, 17, 13, 19, 10], dtype=float)\neine = np.zeros(10, bool); eine[3] = True\nviele = np.zeros(10, bool); viele[[0, 2, 3, 5, 7]] = True\n\nfor nm, maske in [(\"eine\", eine), (\"viele\", viele)]:\n    print(f\"{nm:<6} {maske.sum()} von {len(werte)} Balken,\"\n          f\" {werte[maske].sum() / werte.sum() * 100:.1f} Prozent der Balkenfläche\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\neine   1 von 10 Balken, 15.5 Prozent der Balkenfläche\nviele  5 von 10 Balken, 47.2 Prozent der Balkenfläche\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"hoechster_balken\": int(np.argmax(werte)) + 1, \"sein_wert\": werte.max()})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'hoechster_balken': 4, 'sein_wert': np.float64(22.0)}\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nfor achse, (titel, maske) in zip(achsen, [(\"ein Akzent\", eine),\n                                          (\"fünf Akzente\", viele)]):\n    _ = achse.bar(np.arange(1, 11), werte,\n                  color=np.where(maske, AKZENT, NEUTRAL))\n    _ = achse.set_title(titel)\n    _ = achse.set_ylabel(\"Wert\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselbe Gegenüberstellung in Python.](wahrnehmung-kodierung_files/figure-html/fig-b3-wk-py-1.png){#fig-b3-wk-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Variante | hervorgehobene Balken | Anteil der Balkenfläche |\n|---|---|---|\n| ein Akzent | 1 von 10 | **15.5 Prozent** |\n| fünf Akzente | 5 von 10 | **47.2 Prozent** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Links findet das Auge den roten Balken **ohne zu suchen** | Farbe ist ein vorbewusst erfasstes Merkmal, aber nur, solange sie die Ausnahme ist. |\n| Rechts entstehen **zwei Gruppen** statt einer Ausnahme | Bei 47 Prozent hervorgehobener Fläche ist Rot keine Betonung mehr, sondern eine zweite Kategorie. Das Auge liest \"rote und graue Balken\", nicht \"dieser eine\". |\n| Der Akzent liegt zufällig auf dem **höchsten** Balken (Nr. 4 mit 22) | Links verstärken sich Position und Farbe. Läge der Akzent auf dem niedrigsten, wäre er schwächer, Hervorhebung arbeitet gegen die Position an, nicht mit ihr. |\n| Die Daten sind in beiden Grafiken **identisch** | Es ändert sich nur, worauf gezeigt wird. **Hervorhebung ist eine Aussage, keine Dekoration.** |\n\n::: {.note-box}\n**Wenn wirklich fünf Balken wichtig sind,** ist Farbe das falsche Werkzeug.\nDann gilt:\n\n| Situation | Mittel |\n|---|---|\n| eine Ausnahme zeigen | Akzentfarbe |\n| zwei Gruppen vergleichen | **sortieren** und räumlich trennen, oder facettieren |\n| Rangfolge zeigen | sortieren, Farbe weglassen |\n| mehrere Ausnahmen benennen | direkt beschriften statt einfärben |\n\nDie Faustregel: **Akzentfläche unter etwa einem Fünftel.** Darüber wird aus\nBetonung eine Gruppierung.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Ein hervorgehobener Balken macht 15.5 Prozent der Balkenfläche aus und wird\n> als Ausnahme gelesen; fünf hervorgehobene machen 47.2 Prozent aus und werden\n> als zweite Gruppe gelesen. Die Daten sind in beiden Fällen dieselben.\n\n### Beispiel 4: Zwölf Serien in Farbe oder in Position\n\n#### Frage und Datenlage\n\nZwölf Zeitreihen über 24 Monate. Einmal alle in einer Grafik mit zwölf Farben,\neinmal als zwölf kleine Teilgrafiken. Gemessen wird, wie oft sich die Linien\nkreuzen, denn jede Kreuzung ist eine Stelle, an der das Auge die Spur\nverlieren kann.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_serien <- 12; n_zeit <- 24\nZ <- normalmatrix(9090, n_serien, n_zeit)\nstart <- seq(40, 90, length.out = n_serien)\nreihen <- start + t(apply(Z * 4, 1, cumsum))\n\nkreuzungen <- 0\nfor (i in 1:(n_serien - 1)) {\n  for (j in (i + 1):n_serien) {\n    d <- reihen[i, ] - reihen[j, ]\n    kreuzungen <- kreuzungen + sum(sign(d[-n_zeit]) * sign(d[-1]) < 0)\n  }\n}\nc(serien = n_serien, paare = choose(n_serien, 2), kreuzungen = kreuzungen)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    serien      paare kreuzungen \n        12         66         79 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(kleinster_wert = min(reihen), groesster_wert = max(reihen)), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nkleinster_wert groesster_wert \n          27.6          113.9 \n```\n\n\n:::\n\n```{.r .cell-code}\nc(rang_gleich_geblieben = sum(order(reihen[, 1]) == order(reihen[, n_zeit])),\n  von = n_serien)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrang_gleich_geblieben                   von \n                    5                    12 \n```\n\n\n:::\n\n```{.r .cell-code}\nmatplot(t(reihen), type = \"l\", lty = 1, lwd = 1.4,\n        col = rainbow(n_serien), xlab = \"Monat\", ylab = \"Wert\")\n```\n\n::: {.cell-output-display}\n![Beispiel 4: zwölf Serien als Spaghetti-Diagramm.](wahrnehmung-kodierung_files/figure-html/fig-b4-wk-r-3.png){#fig-b4-wk-r width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlang <- data.frame(\n  serie = factor(rep(sprintf(\"S%02d\", 1:n_serien), each = n_zeit)),\n  monat = rep(1:n_zeit, times = n_serien),\n  wert = as.vector(t(reihen)))\n\nggplot(lang, aes(monat, wert)) +\n  geom_line(linewidth = 0.5) +\n  facet_wrap(~ serie, ncol = 4) +\n  labs(x = \"Monat\", y = \"Wert\")\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselben zwölf Serien als kleine Teilgrafiken.](wahrnehmung-kodierung_files/figure-html/fig-b4b-wk-r-1.png){#fig-b4b-wk-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nn_serien, n_zeit = 12, 24\nZ = normalmatrix(9090, n_serien, n_zeit)\nstart = np.linspace(40, 90, n_serien)\nreihen = start[:, None] + np.cumsum(Z * 4, axis=1)\n\nkreuzungen = 0\nfor i in range(n_serien - 1):\n    for j in range(i + 1, n_serien):\n        d = reihen[i] - reihen[j]\n        kreuzungen += int(np.sum(np.sign(d[:-1]) * np.sign(d[1:]) < 0))\nprint({\"serien\": n_serien, \"paare\": n_serien * (n_serien - 1) // 2,\n       \"kreuzungen\": kreuzungen})\nprint({\"kleinster_wert\": round(float(reihen.min()), 1),\n       \"groesster_wert\": round(float(reihen.max()), 1)})\nprint({\"rang_gleich_geblieben\":\n       int((np.argsort(reihen[:, 0]) == np.argsort(reihen[:, -1])).sum()),\n       \"von\": n_serien})\n\nfig, achse = plt.subplots(figsize=(7, 3.4))\nfor k in range(n_serien):\n    _ = achse.plot(np.arange(1, n_zeit + 1), reihen[k], lw=1.4,\n                   color=plt.cm.hsv(k / n_serien))\nachse.set_xlabel(\"Monat\")\nachse.set_ylabel(\"Wert\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dasselbe Spaghetti-Diagramm in Python.](wahrnehmung-kodierung_files/figure-html/fig-b4-wk-py-1.png){#fig-b4-wk-py width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(3, 4, figsize=(7, 3.8), sharex=True, sharey=True)\nfor k, achse in enumerate(achsen.ravel()):\n    _ = achse.plot(np.arange(1, n_zeit + 1), reihen[k], lw=0.9, color=\"black\")\n    _ = achse.set_title(f\"S{k + 1:02d}\", fontsize=9)\nfor achse in achsen[-1]:\n    _ = achse.set_xlabel(\"Monat\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselben Serien als kleine Teilgrafiken.](wahrnehmung-kodierung_files/figure-html/fig-b4b-wk-py-3.png){#fig-b4b-wk-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | Wert |\n|---|---|\n| Serien | 12 |\n| mögliche Paare | 66 |\n| **Kreuzungen insgesamt** | **79** |\n| Wertebereich | 27.6 bis 113.9 |\n| Serien mit unverändertem Rang von Monat 1 zu Monat 24 | **5 von 12** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| **79 Kreuzungen** auf 24 Monate | Im Schnitt mehr als drei pro Zeitschritt. An jeder Kreuzung muss das Auge die Linie über den Farbton wiederfinden, den ungenauesten Kanal der ganzen Tabelle. |\n| Zwölf Farben sind **mehr, als unterscheidbar sind** | Übliche Empfehlungen enden bei sieben bis neun. Der Regenbogenverlauf macht es zusätzlich schwer, weil benachbarte Farbtöne sich kaum trennen. |\n| Nur **5 von 12** Serien behalten ihren Rang | Die Reihenfolge am Anfang sagt also wenig über die am Ende, genau die Information, die das Spaghetti-Diagramm verspricht und nicht liefert. |\n| Die Teilgrafiken beantworten eine **andere** Frage gut | \"Wie verläuft Serie 7?\" ist dort sofort beantwortet, \"welche Serie ist im Monat 18 die höchste?\" dagegen nicht mehr. **Kleine Teilgrafiken tauschen den Vergleich gegen den Verlauf.** |\n| Beide Grafiken zeigen dieselben Zahlen | Der Unterschied liegt allein im Kanal: Farbton gegen Position auf getrennten Skalen, Rang 7 gegen Rang 2. |\n\n::: {.note-box}\n**Der dritte Weg, der meistens der beste ist:** alle Serien grau zeichnen und\n**eine** hervorheben, das Spaghetti-Diagramm als Hintergrund, der den\nWertebereich zeigt, plus ein Akzent für die Serie, um die es geht. Damit ist\nsowohl die Einordnung als auch der Verlauf lesbar, und man braucht nur zwei\nFarben statt zwölf.\n\nDas ist dieselbe Regel wie in Beispiel 3, nur auf Linien angewandt.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Zwölf Serien über 24 Monate kreuzen sich 79-mal; nur 5 von 12 behalten ihren\n> Rang von Anfang bis Ende. Im Spaghetti-Diagramm muss jede Kreuzung über den\n> Farbton aufgelöst werden, in kleinen Teilgrafiken entfällt das Problem, um\n> den Preis, dass der direkte Vergleich zwischen den Serien verloren geht.\n\n### Beispiel 5: Gemeinsame oder getrennte Skala\n\n#### Frage und Datenlage\n\nZwei Filialen über zwölf Monate. Die eine liegt bei rund 98, die andere bei\nrund 33, ein Faktor 3. Was passiert, wenn beide Teilgrafiken ihre **eigene**\ny-Achse bekommen?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nZ <- normalmatrix(4040, 2, 12)\ngross <- 100 + Z[1, ] * 6\nklein <- 30 + Z[2, ] * 6\n\nround(rbind(gross = c(mittel = mean(gross), spanne = diff(range(gross)),\n                      min = min(gross), max = max(gross)),\n            klein = c(mittel = mean(klein), spanne = diff(range(klein)),\n                      min = min(klein), max = max(klein))), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      mittel spanne  min   max\ngross   98.3   20.8 88.9 109.7\nklein   32.9   29.3 19.7  49.0\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(verhaeltnis_der_mittel = mean(gross) / mean(klein),\n        verhaeltnis_der_spannen = diff(range(gross)) / diff(range(klein))), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n verhaeltnis_der_mittel verhaeltnis_der_spannen \n                   2.99                    0.71 \n```\n\n\n:::\n\n```{.r .cell-code}\nlang <- data.frame(\n  filiale = rep(c(\"Zentrum\", \"Aussenstelle\"), each = 12),\n  monat = rep(1:12, 2),\n  umsatz = c(gross, klein))\n\nggplot(lang, aes(monat, umsatz)) +\n  geom_line(linewidth = 0.7) +\n  facet_wrap(~ filiale) +\n  expand_limits(y = 0) +\n  labs(x = \"Monat\", y = \"Umsatz\", subtitle = \"gemeinsame Skala\")\n```\n\n::: {.cell-output-display}\n![Beispiel 5: gemeinsame Skala für beide Filialen.](wahrnehmung-kodierung_files/figure-html/fig-b5-wk-r-5.png){#fig-b5-wk-r width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(lang, aes(monat, umsatz)) +\n  geom_line(linewidth = 0.7) +\n  facet_wrap(~ filiale, scales = \"free_y\") +\n  labs(x = \"Monat\", y = \"Umsatz\", subtitle = \"je eigene Skala\")\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselben Daten mit je eigener y-Achse.](wahrnehmung-kodierung_files/figure-html/fig-b5b-wk-r-1.png){#fig-b5b-wk-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nZ = normalmatrix(4040, 2, 12)\ngross = 100 + Z[0] * 6\nklein = 30 + Z[1] * 6\n\n\ndef kennzahlen(x):\n    return {\"mittel\": x.mean(), \"spanne\": x.max() - x.min(),\n            \"min\": x.min(), \"max\": x.max()}\n\n\nprint(pd.DataFrame({\"gross\": kennzahlen(gross),\n                    \"klein\": kennzahlen(klein)}).round(1).T)\nprint({\"verhaeltnis_der_mittel\": round(float(gross.mean() / klein.mean()), 2),\n       \"verhaeltnis_der_spannen\":\n           round(float((gross.max() - gross.min()) / (klein.max() - klein.min())), 2)})\n\nmonat = np.arange(1, 13)\nfig, achsen = plt.subplots(2, 2, figsize=(7, 4.4))\nfor spalte, (name, reihe) in enumerate([(\"Zentrum\", gross),\n                                        (\"Aussenstelle\", klein)]):\n    _ = achsen[0, spalte].plot(monat, reihe, lw=1.2, color=\"black\")\n    _ = achsen[0, spalte].set_ylim(0, 120)      # gemeinsame Skala\n    _ = achsen[0, spalte].set_title(name, fontsize=10)\n    _ = achsen[1, spalte].plot(monat, reihe, lw=1.2, color=\"black\")\n    _ = achsen[1, spalte].set_xlabel(\"Monat\")\nachsen[0, 0].set_ylabel(\"gemeinsame Skala\")\nachsen[1, 0].set_ylabel(\"je eigene Skala\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselbe Gegenüberstellung in Python.](wahrnehmung-kodierung_files/figure-html/fig-b5-wk-py-1.png){#fig-b5-wk-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Filiale | Mittel | Spanne | Minimum | Maximum |\n|---|---|---|---|---|\n| Zentrum | **98.3** | 20.8 | 88.9 | 109.7 |\n| Aussenstelle | **32.9** | **29.3** | 19.7 | 49.0 |\n\n| Verhältnis | Wert |\n|---|---|\n| der Mittelwerte | **2.99** |\n| der Spannen | **0.71** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Das Zentrum setzt **dreimal** so viel um | 98.3 gegen 32.9. Auf der gemeinsamen Skala sieht man das sofort. |\n| Auf getrennten Skalen ist dieser Faktor **unsichtbar** | Beide Kurven füllen ihr Feld gleich aus. Wer die Achsenbeschriftung nicht liest und das tut kaum jemand zuerst, sieht zwei gleich grosse Filialen. |\n| Die Aussenstelle schwankt **absolut stärker** | Spanne 29.3 gegen 20.8, Verhältnis 0.71. Das ist der eigentlich interessante Befund: Die kleinere Filiale ist die unruhigere. |\n| Und **dieser** Befund wird nur auf getrennten Skalen sichtbar | Auf der gemeinsamen Skala verschwindet die Schwankung der Aussenstelle optisch neben dem Niveauunterschied. |\n| Beide Darstellungen sind also richtig | Und beide unvollständig. **Die Skalenfrage ist keine Formfrage, sondern die Frage, welche Aussage die Grafik machen soll.** |\n\n::: {.warning-box}\n**Die Entscheidungsregel:**\n\n| Die Aussage lautet … | Skala |\n|---|---|\n| \"A ist grösser als B\" | **gemeinsam**, sonst ist die Aussage nicht zu sehen |\n| \"beide folgen demselben Muster\" | **getrennt**, sonst verschwindet das kleine Muster |\n| beides | zwei Grafiken, oder indexiert auf den Startwert = 100 |\n\nGetrennte Skalen sind nicht verboten, aber sie sind eine **Behauptung**: \"Der\nNiveauunterschied ist hier nicht das Thema.\" Wer das nicht meint, muss die\nAchse teilen. Die verwandte, deutlich schlimmere Variante ist die zweite\ny-Achse, siehe\n[irreführende Darstellungen](irrefuehrende-darstellungen.qmd).\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Das Zentrum setzt mit 98.3 rund dreimal so viel um wie die Aussenstelle mit\n> 32.9, schwankt aber absolut weniger (Spanne 20.8 gegen 29.3). Die gemeinsame\n> Skala zeigt den Niveauunterschied und verbirgt die Schwankung, die getrennte\n> Skala genau umgekehrt.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nIn einem Streudiagramm sollen zusätzlich Umsatz und Region dargestellt werden.\nWelche Zuordnung ist richtig?\n\n- [x] Umsatz auf die Fläche, Region auf den Farbton ~ Richtig. Region ist\n      kategorial und ungeordnet, dafür ist Farbton der passende Kanal. Umsatz\n      ist eine Menge und muss ungenauer abgelesen werden können, also Fläche.\n      Die beiden Hauptvariablen behalten die Position.\n- [ ] Umsatz auf den Farbton, Region auf die Fläche ~ Farbton kodiert keine\n      Mengen, und eine Fläche suggeriert bei Kategorien eine Rangfolge.\n- [ ] Beide auf die Position ~ Die Positionen sind bereits vergeben.\n:::\n\n::: {.quiz}\nEine Grafik mit zwanzig Balken hebt sechs davon farbig hervor. Was ist das\nProblem?\n\n- [ ] Sechs Farben sind zu viele für die Palette ~ Auch mit einer einzigen\n      Akzentfarbe bliebe das Problem.\n- [x] Kontrast wirkt nur, wenn er selten ist ~ Richtig. Bei sechs von zwanzig\n      hervorgehobenen Balken erfasst das Auge keine Ausnahme mehr, sondern zwei\n      Gruppen. Im Beispiel machten fünf von zehn Akzenten 47 Prozent der\n      Balkenfläche aus. Wer sechs zeigen muss, sortiert stattdessen und trennt\n      die Gruppen räumlich.\n- [ ] Balken eignen sich nicht für Hervorhebung ~ Sie eignen sich gut, solange\n      der Akzent die Ausnahme bleibt.\n:::\n\n::: {.quiz}\nEine Blasengrafik soll Werte von 1 bis 8 zeigen. Wie gross muss der Radius der\ngrössten Blase sein, wenn die kleinste den Radius 1 hat?\n\n- [x] Wurzel aus 8, also rund 2.83 ~ Richtig, denn die Fläche soll\n      proportional zum Wert sein und wächst mit dem Quadrat des Radius. Mit\n      Radius 8 entstünde die 64-fache Fläche.\n- [ ] 8, damit das Verhältnis stimmt ~ Das setzt den Radius proportional zum\n      Wert und erzeugt eine 64-fache statt achtfache Fläche.\n- [ ] 4, also die Hälfte ~ Dann wäre die Fläche 16-fach statt achtfach.\n:::\n\n::: {.quiz}\nWarum wirkt selbst eine korrekt kodierte Fläche zu klein?\n\n- [x] Flächen werden ungefähr mit dem Exponenten 0.7 wahrgenommen ~ Richtig.\n      Eine achtfache Fläche wirkt wie das 4.3-Fache. Deshalb braucht eine\n      Blasengrafik eine Legende mit Referenzkreisen.\n- [ ] Weil die Blasen sich überlappen ~ Das ist ein weiteres Problem, erklärt\n      aber die systematische Untertreibung nicht.\n- [ ] Weil der Bildschirm zu klein ist ~ Der Effekt ist unabhängig von der\n      Darstellungsgrösse.\n:::\n\n::: {.quiz}\nZwölf Zeitreihen in einer Grafik kreuzten sich 79-mal. Warum ist das ein\nProblem?\n\n- [x] An jeder Kreuzung muss die Linie über den Farbton wiedergefunden werden ~\n      Richtig, und Farbton ist der ungenaueste Kanal. Zwölf Farben liegen\n      zudem über dem, was sich unterscheiden lässt.\n- [ ] Weil sich Linien grundsätzlich nicht kreuzen dürfen ~ Bei zwei oder drei\n      Serien sind Kreuzungen unproblematisch und oft gerade die Aussage.\n- [ ] Weil die Daten zu verrauscht sind ~ Dieselben Daten sind in kleinen\n      Teilgrafiken gut lesbar; das Problem liegt in der Darstellung.\n:::\n\n::: {.quiz}\nZwei Filialen, eine mit Mittel 98.3, eine mit 32.9. In getrennten y-Achsen\ngezeichnet füllen beide Kurven ihr Feld gleich aus. Was ist davon zu halten?\n\n- [x] Das ist zulässig, aber eine Behauptung: Der Niveauunterschied sei nicht\n      das Thema ~ Richtig. Getrennte Skalen zeigen das Muster der kleinen\n      Reihe, im Beispiel schwankte die kleinere Filiale mit 29.3 sogar\n      absolut stärker als die grosse mit 20.8. Wer den Faktor 3 zeigen will,\n      braucht eine gemeinsame Skala.\n- [ ] Das ist immer irreführend ~ Dann bliebe das Muster der kleinen Reihe\n      unsichtbar; beide Darstellungen beantworten verschiedene Fragen.\n- [ ] Das ist unproblematisch, die Achsen sind ja beschriftet ~ Die\n      Beschriftung steht da, wird aber typischerweise erst nach dem\n      Gesamteindruck gelesen.\n:::\n\n## Verlinkte Ressourcen\n\n- [Claus Wilke: Fundamentals of Data Visualization, Kapitel zu Aesthetics](https://clauswilke.com/dataviz/aesthetic-mapping.html)\n- [Cleveland und McGill: Graphical Perception](https://www.jstor.org/stable/2288400)\n- [Tufte: The Visual Display of Quantitative Information](https://www.edwardtufte.com/tufte/books_vdqi)\n- [Diagrammtyp wählen](diagrammtyp-waehlen.qmd), die Kanalrangfolge angewandt\n- [Farbe](farbe.qmd), Paletten, Kontrast und der Graustufentest\n",
    "supporting": [
      "wahrnehmung-kodierung_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}