{
  "hash": "6f1879120013d79ba7f34926c675dc29",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"NumPy und SciPy\"\ndescription: \"Arrays, Vektorisierung und die wichtigsten numerischen Werkzeuge.\"\ncategories: [\"NumPy\", \"Python\", \"R\", \"Programmiergrundlagen\"]\nquelle: [\"PYFR\"]\nseitentyp: werkzeug\nstand: entwurf\norder: 60\n---\n\n\n\n## Kernideen\n\n- Das **`ndarray`** hat einen Typ für alle Elemente, eine feste Form und\n  liegt zusammenhängend im Speicher. Damit rechnet Python so, wie R es von\n  Haus aus tut.\n- Passt ein Wert nicht zum `dtype`, wird **still umgewandelt**: abgeschnitten,\n  zu Text gemacht oder bei festen Ganzzahltypen übergelaufen.\n- **`axis`** nennt die Achse, die beim Zusammenfassen **verschwindet**.\n  `axis=0` liefert ein Ergebnis je Spalte.\n- **Broadcasting** gleicht Formen von hinten an, nur wo eine Achse die Länge\n  eins hat. R recycelt spaltenweise, und das zentriert eine Matrix falsch.\n- Ein **Slice ist eine View** auf dieselben Daten, eine Auswahl per Bedingung\n  eine Kopie. R kennt keine Views.\n- **SciPy** liefert die Verfahren: Verteilungen, Tests, Integration,\n  Optimierung. Was in R zur Grundausstattung gehört, liegt in Python hier.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Python-Grundlagen](python-grundlagen.qmd) für Listen und\nSlicing. Der Unterschied zwischen Liste und Array ist der rote Faden dieser\nSeite. Wer von [R](r-grundlagen.qmd) herkommt, erkennt in NumPy das wieder,\nwas R mit Vektoren und Matrizen mitbringt. Tabellen mit benannten Spalten\nkommen danach mit [pandas](pandas.qmd).\n:::\n\n### Warum eine Liste nicht genügt\n\nEine Python-Liste darf beliebige Objekte enthalten und speichert deshalb für\njedes Element einen Verweis. Rechnen heisst dann: Verweis folgen, Typ prüfen,\nOperation heraussuchen, ausführen, und das für jedes Element einzeln. Ein\nArray speichert alle Werte desselben Typs zusammenhängend, und die Rechnung\nläuft in kompiliertem Code über den ganzen Block. Bei grossen Arrays ist das\num ein Vielfaches schneller; der genaue Faktor hängt vom Rechner ab und\ngehört deshalb nicht in eine Notiz.\n\nWichtiger als die Geschwindigkeit ist die Bedeutung der Operatoren: Auf einer\nListe hängt `+` an und `*` wiederholt, auf einem Array rechnen beide\nelementweise.\n\n### Die wichtigsten Eigenschaften eines Arrays\n\n| Attribut | Bedeutung | Beispiel |\n|---|---|---|\n| `dtype` | Typ aller Elemente | `int64`, `float64`, `bool`, `<U4` (Text) |\n| `shape` | Form als Tupel | `(3, 4)`: drei Zeilen, vier Spalten |\n| `ndim` | Anzahl der Achsen | 2 |\n| `size` | Anzahl der Elemente | 12 |\n| `nbytes` | Speicherbedarf | 12 · 8 = 96 Byte bei `int64` |\n\nFeste Ganzzahltypen wie `uint8` (0 bis 255) oder `int32` haben einen\nbegrenzten Wertebereich. Wird er überschritten, **laufen sie über** und\nbeginnen von vorn, ohne Fehler. Bilddaten sind häufig `uint8`, und genau dort\npassiert es.\n\n### Achsen\n\nBei einer 3 × 4-Matrix hat Achse 0 die Länge 3 (Zeilen) und Achse 1 die\nLänge 4 (Spalten). `a.sum(axis=0)` summiert entlang der Zeilen, Achse 0\nverschwindet, und übrig bleiben **vier** Werte, einer je Spalte. Die Zahl in\n`axis` benennt die Achse, die verschwindet, nicht die, die bleibt.\n\nIn R bedeutet die Zahl bei `apply(a, 2, mean)` das Gegenteil: Die 2 steht für\ndie Spalten, die **erhalten** bleiben. Beide Aufrufe liefern das\nSpaltenmittel, mit den Ziffern 0 und 2.\n\n### Broadcasting und Recycling\n\nNumPy vergleicht die Formen **von hinten**. Zwei Achsen passen, wenn sie\ngleich lang sind oder eine die Länge eins hat; fehlende Achsen vorne werden\nals Länge eins ergänzt. `(3, 2)` und `(2,)` passen, `(3, 2)` und `(3,)` nicht,\n`(3, 2)` und `(3, 1)` wieder.\n\nR recycelt stattdessen den kürzeren Vektor entlang der Speicherreihenfolge,\nund die ist **spaltenweise**. Deshalb verhält sich R bei Matrizen genau\numgekehrt zu NumPy: Ein Vektor mit einem Wert je Zeile passt von selbst, ein\nVektor mit einem Wert je Spalte wird falsch verteilt.\n\n### View oder Kopie\n\nEin Slice wie `a[2:5]` beschreibt ein regelmässiges Muster aus Start, Ende und\nSchrittweite und kann deshalb auf denselben Speicher zeigen. Eine Auswahl per\nBedingung oder Indexliste greift unregelmässig verteilte Elemente heraus, die\nneu abgelegt werden müssen. Die Regel: **Slice mit Doppelpunkt ist eine View,\nMaske und Indexliste sind Kopien.** Ob zwei Arrays Speicher teilen, prüft\n`np.shares_memory(a, b)`.\n\n### SciPy: die Verfahren obendrauf\n\n| Modul | Inhalt | R-Gegenstück |\n|---|---|---|\n| `scipy.stats` | Verteilungen (`norm`, `t`, `chi2`), Tests | `pnorm`, `qt`, `shapiro.test`, `t.test` |\n| `scipy.optimize` | Minimum, Nullstellen, Kurvenanpassung | `optimize`, `optim`, `uniroot`, `nls` |\n| `scipy.integrate` | numerische Integration | `integrate` |\n| `scipy.interpolate` | Interpolation | `approx`, `spline` |\n| `scipy.linalg` | lineare Algebra | `solve`, `eigen`, `qr` |\n\nJede Verteilung in `scipy.stats` hat dieselben Methoden: `pdf` (Dichte), `cdf`\n(Verteilungsfunktion), `ppf` (Quantil) und `rvs` (Zufallszahlen). In R\nentsprechen sie den Präfixen `d`, `p`, `q` und `r`. Für Tests mit\nvollständiger Ergebnistabelle nimmt diese Sammlung `pingouin`, siehe\n[Hypothesentests](../statistik/inferenz/hypothesentests-grundlagen.qmd).\n\n### Kurz nachgeschlagen\n\n| Aufgabe | R | Python |\n|---|---|---|\n| Folge erzeugen | `seq(0, 1, by = 0.1)`, `1:10` | `np.linspace(0, 1, 11)`, `np.arange(1, 11)` |\n| Matrix aus Werten | `matrix(x, nrow = 3, byrow = TRUE)` | `np.array(x).reshape(3, -1)` |\n| Spaltensummen, Zeilensummen | `colSums(a)`, `rowSums(a)` | `a.sum(axis=0)`, `a.sum(axis=1)` |\n| Spalten zentrieren | `sweep(a, 2, colMeans(a))` | `a - a.mean(axis=0)` |\n| Standardabweichung | `sd(x)` | `x.std(ddof=1)` |\n| bedingt ersetzen | `ifelse(x > 3, x, 0)` | `np.where(x > 3, x, 0)` |\n| eigene Kopie | nicht nötig | `a[1:3].copy()` |\n| Quantil der Normalverteilung | `qnorm(0.975)` | `stats.norm.ppf(0.975)` |\n| Minimum einer Funktion | `optimize(f, c(-10, 10))` | `optimize.minimize_scalar(f)` |\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Liste gegen Array\n\n#### Frage und Datenlage\n\nVier Werte `12, 45, 7, 31`, einmal als Python-Liste und einmal als\nNumPy-Array. Was bedeuten `* 2` und `+ 1` jeweils, und wie viel Speicher\nbelegt das Array?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwerte <- c(12, 45, 7, 31)\nwerte * 2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24 90 14 62\n```\n\n\n:::\n\n```{.r .cell-code}\nwerte + 1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13 46  8 32\n```\n\n\n:::\n\n```{.r .cell-code}\nc(werte, 1)                  # Anhaengen ist eine eigene Funktion\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 12 45  7 31  1\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nliste = [12, 45, 7, 31]\nfeld = np.array(liste)\n\nprint(liste * 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[12, 45, 7, 31, 12, 45, 7, 31]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(feld * 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[24 90 14 62]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(liste + [1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[12, 45, 7, 31, 1]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(feld + 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[13 46  8 32]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(feld.dtype, feld.shape, feld.nbytes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nint64 (4,) 32\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausdruck | Liste | Array | R | Erklärung |\n|---|---|---|---|---|\n| `* 2` | acht Elemente, die Liste zweimal | `[24 90 14 62]` | 24 90 14 62 | Nur das Array rechnet elementweise, wie der R-Vektor. |\n| `+` | `liste + [1]` hängt an | `feld + 1`: `[13 46 8 32]` | `werte + 1` rechnet, `c()` hängt an | Dasselbe Zeichen, verschiedene Bedeutung. |\n| `dtype` | | `int64` | | Ganze Zahlen mit 8 Byte. |\n| `shape` | | `(4,)` | | eine Achse mit vier Elementen |\n| `nbytes` | | 32 | | 4 Werte · 8 Byte, ohne Verweise dazwischen |\n\n#### Interpretation und Ergebnissatz\n\nWer von R kommt, erwartet von `* 2` eine Verdopplung jedes Werts und bekommt\nsie in Python nur vom Array. Die Umwandlung mit `np.array()` ist deshalb der\nerste Schritt jeder numerischen Arbeit in Python; pandas-Spalten sind intern\nbereits Arrays.\n\n> Auf dem Array liefert `* 2` die verdoppelten Werte 24, 90, 14 und 62, auf\n> der Liste eine Liste mit acht Elementen. Das Array belegt 32 Byte, acht je\n> ganzer Zahl.\n\n### Beispiel 2: Der dtype und seine stillen Umwandlungen\n\n#### Frage und Datenlage\n\nWas passiert, wenn in ein Ganzzahl-Array der Wert 3.7 geschrieben wird, wenn\nZahlen und Text gemischt werden, und wenn ein `uint8`-Array mit den Werten\n200 und 250 um 100 erhöht wird?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nganze <- c(1L, 2L, 3L)\nganze[1] <- 3.7              # der ganze Vektor wird Gleitkomma\nganze\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.7 2.0 3.0\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(ganze)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"numeric\"\n```\n\n\n:::\n\n```{.r .cell-code}\nc(1, 2, \"drei\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1\"    \"2\"    \"drei\"\n```\n\n\n:::\n\n```{.r .cell-code}\n.Machine$integer.max\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2147483647\n```\n\n\n:::\n\n```{.r .cell-code}\nsuppressWarnings(.Machine$integer.max + 1L)   # Ueberlauf wird NA\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA\n```\n\n\n:::\n\n```{.r .cell-code}\n.Machine$integer.max + 1                      # als Gleitkommazahl kein Problem\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2147483648\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nganze = np.array([1, 2, 3])\nprint(ganze.dtype)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nint64\n```\n\n\n:::\n\n```{.python .cell-code}\nganze[0] = 3.7               # abgeschnitten, ohne Warnung\nprint(ganze)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[3 2 3]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(np.array([1, 2.5, 3]).dtype)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfloat64\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(np.array([1, 2, \"drei\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['1' '2' 'drei']\n```\n\n\n:::\n\n```{.python .cell-code}\nklein = np.array([200, 250], dtype=np.uint8)\nprint(klein + np.uint8(100))           # Ueberlauf: modulo 256\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[44 94]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(klein.astype(np.int64) + 100)    # erst umwandeln, dann rechnen\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[300 350]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Schritt | Python | R | Erklärung |\n|---|---|---|---|\n| 3.7 in Ganzzahlen | **`[3 2 3]`** | `3.7 2.0 3.0`, Klasse `numeric` | NumPy passt den Wert an den festen `dtype` an und **schneidet ab**. R passt den Vektor an den Wert an und wird Gleitkomma. |\n| `1, 2.5, 3` | `float64` | | Eine Gleitkommazahl macht alles zu Gleitkomma. |\n| mit Text | `['1' '2' 'drei']` | `\"1\" \"2\" \"drei\"` | Alles wird Text, in beiden Sprachen. |\n| `uint8` 200 + 100, 250 + 100 | **`[44 94]`** | | 300 − 256 = 44, 350 − 256 = 94. Kein Fehler, keine Warnung. |\n| nach `astype(int64)` | `[300 350]` | | Mit genügend grossem Typ richtig. |\n| grösste ganze Zahl in R | | 2147483647 | 32-Bit-Ganzzahl |\n| plus `1L` | | **`NA`** mit Warnung | R läuft nicht über, sondern meldet einen fehlenden Wert. |\n| plus `1` | | 2147483648 | `1` ist in R eine Gleitkommazahl, die Summe auch. |\n\n#### Interpretation und Ergebnissatz\n\nNumPy behandelt den `dtype` als Vertrag: Das Array ändert seinen Typ nicht,\ndie Werte müssen sich anpassen. Das ist schnell und bei Ganzzahltypen\ngefährlich, weil Abschneiden und Überlauf keine Meldung erzeugen. R wählt die\nentgegengesetzte Strategie und ändert lieber den Typ. Wer Werte in ein\nbestehendes Array schreibt oder mit kleinen Typen rechnet, prüft zuerst\n`dtype`.\n\n> Der Wert 3.7 wurde im Ganzzahl-Array ohne Warnung zu 3 abgeschnitten, und\n> `uint8` lief bei 200 + 100 still auf 44 über. R wandelt stattdessen den\n> ganzen Vektor in Gleitkomma um und meldet einen Ganzzahlüberlauf als `NA`.\n\n### Beispiel 3: Achsen\n\n#### Frage und Datenlage\n\nEine 3 × 4-Matrix mit den Zahlen 1 bis 12, zeilenweise gefüllt. Gesucht sind\nSpaltensummen, Zeilensummen, Gesamtsumme und Spaltenmittel.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\na <- matrix(1:12, nrow = 3, byrow = TRUE)\na\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     [,1] [,2] [,3] [,4]\n[1,]    1    2    3    4\n[2,]    5    6    7    8\n[3,]    9   10   11   12\n```\n\n\n:::\n\n```{.r .cell-code}\ncolSums(a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 15 18 21 24\n```\n\n\n:::\n\n```{.r .cell-code}\nrowSums(a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10 26 42\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 78\n```\n\n\n:::\n\n```{.r .cell-code}\napply(a, 2, mean)            # 2 = die Spalten bleiben\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5 6 7 8\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\na = np.arange(1, 13).reshape(3, 4)\nprint(a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[ 1  2  3  4]\n [ 5  6  7  8]\n [ 9 10 11 12]]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(a.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(3, 4)\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(a.sum(axis=0))         # Achse 0 verschwindet\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[15 18 21 24]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(a.sum(axis=1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[10 26 42]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(a.sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n78\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(a.mean(axis=0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[5. 6. 7. 8.]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ergebnis | Python | R | Werte |\n|---|---|---|---|\n| Form | `(3, 4)` | 3 Zeilen, 4 Spalten | |\n| je Spalte summiert | `axis=0` | `colSums` | 15, 18, 21, 24 |\n| je Zeile summiert | `axis=1` | `rowSums` | 10, 26, 42 |\n| alles | ohne `axis` | `sum` | 78 |\n| Spaltenmittel | `mean(axis=0)` | `apply(a, 2, mean)` | 5, 6, 7, 8 |\n\nDie erste Spalte enthält 1, 5, 9, Summe 15; die erste Zeile 1, 2, 3, 4,\nSumme 10. Vier Spaltensummen, weil Achse 0 mit ihren drei Zeilen wegfällt.\n\n#### Interpretation und Ergebnissatz\n\n`axis=0` und `apply(..., 2, ...)` liefern beide ein Ergebnis je Spalte, mit\nverschiedenen Ziffern. Die Merkregel für NumPy lautet: Die Achse in `axis`\nverschwindet. Für R: Die Ziffer in `apply` bleibt. Bei einem Ergebnis mit\nunerwarteter Länge ist `.shape` der erste Blick.\n\n> Die Spaltensummen der Matrix betragen 15, 18, 21 und 24, die Zeilensummen\n> 10, 26 und 42, die Gesamtsumme 78. In NumPy steht dafür `axis=0`, in R\n> `colSums` oder `apply(a, 2, ...)`.\n\n### Beispiel 4: Zentrieren mit Broadcasting und Recycling\n\n#### Frage und Datenlage\n\nDrei Beobachtungen mit zwei Merkmalen (`2, 10`, `4, 30`, `9, 20`). Jede Spalte\nsoll um ihr Mittel zentriert werden, wie vor einer\n[Hauptkomponentenanalyse](../statistik/multivariat/hauptkomponentenanalyse.qmd).\nDanach dasselbe je Zeile.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm <- matrix(c(2, 10, 4, 30, 9, 20), nrow = 3, byrow = TRUE)\ncolMeans(m)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  5 20\n```\n\n\n:::\n\n```{.r .cell-code}\nm - colMeans(m)              # FALSCH, und ohne Warnung\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     [,1] [,2]\n[1,]   -3  -10\n[2,]  -16   25\n[3,]    4    0\n```\n\n\n:::\n\n```{.r .cell-code}\nsweep(m, 2, colMeans(m))     # richtig: je Spalte abziehen\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     [,1] [,2]\n[1,]   -3  -10\n[2,]   -1   10\n[3,]    4    0\n```\n\n\n:::\n\n```{.r .cell-code}\ncolMeans(sweep(m, 2, colMeans(m)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0 0\n```\n\n\n:::\n\n```{.r .cell-code}\nm - rowMeans(m)              # je Zeile: passt in R von selbst\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      [,1] [,2]\n[1,]  -4.0  4.0\n[2,] -13.0 13.0\n[3,]  -5.5  5.5\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nm = np.array([[2.0, 10.0], [4.0, 30.0], [9.0, 20.0]])\nprint(m.mean(axis=0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[ 5. 20.]\n```\n\n\n:::\n\n```{.python .cell-code}\nzentriert = m - m.mean(axis=0)          # (3, 2) minus (2,)\nprint(zentriert)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[ -3. -10.]\n [ -1.  10.]\n [  4.   0.]]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(zentriert.mean(axis=0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[0. 0.]\n```\n\n\n:::\n\n```{.python .cell-code}\ntry:\n    m - m.mean(axis=1)                  # (3, 2) minus (3,)\nexcept ValueError as fehler:\n    print(\"ValueError:\", fehler)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nValueError: operands could not be broadcast together with shapes (3,2) (3,) \n```\n\n\n:::\n\n```{.python .cell-code}\nprint(m - m.mean(axis=1, keepdims=True))   # (3, 2) minus (3, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[ -4.    4. ]\n [-13.   13. ]\n [ -5.5   5.5]]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Schritt | Python | R | Erklärung |\n|---|---|---|---|\n| Spaltenmittel | `[ 5. 20.]` | 5 20 | |\n| je Spalte zentriert | Zeilen `-3 -10`, `-1 10`, `4 0` | `sweep`: dieselbe Matrix | `(2,)` passt von hinten auf `(3, 2)`. |\n| Kontrolle | `[0. 0.]` | 0 0 | Zentrierte Spalten haben Mittel null. |\n| `m - colMeans(m)` in R | | **Spalte 1: −3, −16, 4; Spalte 2: −10, 25, 0** | R zieht 5, 20, 5, 20, 5, 20 **spaltenweise** ab: Die 20 landet in der ersten Spalte. Sechs ist ein Vielfaches von zwei, also keine Warnung. |\n| je Zeile, ohne Umformen | **`ValueError`**, Formen `(3,2)` und `(3,)` | passt | NumPy vergleicht die 2 hinten mit der 3 und bricht ab. R verteilt drei Zeilenmittel spaltenweise, also richtig. |\n| mit `keepdims=True` | Zeilen `-4 4`, `-13 13`, `-5.5 5.5` | dieselben Werte | Die Form `(3, 1)` passt. Zeilenmittel 6, 17, 14.5. |\n\n#### Interpretation und Ergebnissatz\n\nDie beiden Sprachen irren in entgegengesetzte Richtungen. NumPy verweigert\ndas Zeilenzentrieren ohne ausdrückliche Form und macht das Spaltenzentrieren\nrichtig. R macht das Zeilenzentrieren richtig und das Spaltenzentrieren\n**still falsch**. Die falsche R-Matrix sieht plausibel aus; erst die Kontrolle\n`colMeans(...)` auf null würde es zeigen. In R ist deshalb `sweep()` oder\n`scale(m, scale = FALSE)` der sichere Weg.\n\n> Mit `m - m.mean(axis=0)` sind beide Spalten zentriert, ihre Mittel sind\n> null. Derselbe Ausdruck in R, `m - colMeans(m)`, liefert ohne Warnung eine\n> falsche Matrix, weil R spaltenweise recycelt; richtig ist\n> `sweep(m, 2, colMeans(m))`.\n\n### Beispiel 5: View oder Kopie\n\n#### Frage und Datenlage\n\nAus den Zahlen 0 bis 9 wird ein Ausschnitt genommen und verändert, einmal als\nSlice, einmal als Kopie und einmal als Auswahl per Bedingung. Was passiert mit\ndem Original?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\noriginal <- 0:9\nteil <- original[3:5]\nteil[1] <- 999\noriginal                     # unveraendert: R hat keine Views\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 0 1 2 3 4 5 6 7 8 9\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\noriginal = np.arange(10)\n\nteil = original[2:5]          # View\nteil[0] = 999\nprint(original)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[  0   1 999   3   4   5   6   7   8   9]\n```\n\n\n:::\n\n```{.python .cell-code}\nkopie = original[2:5].copy()\nkopie[0] = -1\nprint(original)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[  0   1 999   3   4   5   6   7   8   9]\n```\n\n\n:::\n\n```{.python .cell-code}\nmaske = original[original > 5]    # Auswahl per Bedingung: Kopie\nmaske[0] = -5\nprint(original)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[  0   1 999   3   4   5   6   7   8   9]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(np.shares_memory(teil, original),\n      np.shares_memory(maske, original),\n      np.shares_memory(kopie, original))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue False False\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Schritt | Original danach | teilt Speicher | Erklärung |\n|---|---|---|---|\n| Slice verändert | `[  0   1 999   3 ...]` | **`True`** | Das Original hat sich mitverändert. |\n| Kopie verändert | unverändert | `False` | `.copy()` trennt. |\n| Maske verändert | unverändert | `False` | Eine Auswahl per Bedingung ist immer eine Kopie. |\n| R | `0 1 2 ... 9` | | R kopiert beim Ändern; Views gibt es nicht. |\n\nDie 999 steht an Position 2, weil der Slice bei Position 2 beginnt. Die\ndritte Ausgabe zeigt dieselbe Zeile wie die zweite: Weder Kopie noch Maske\nhaben das Original berührt.\n\n#### Interpretation und Ergebnissatz\n\nViews sparen Speicher und Zeit, weil bei grossen Arrays nichts kopiert wird.\nSie sind zugleich eine Fehlerquelle der Art aus\n[Python-Grundlagen](python-grundlagen.qmd), Beispiel 1: Zwei Namen zeigen auf\ndieselben Daten. Wer einen Ausschnitt verändern und das Original behalten\nwill, ruft `.copy()` auf. In pandas führt dasselbe Muster zur bekannten\n`SettingWithCopyWarning`.\n\n> Das Verändern des Slices `original[2:5]` setzte im Original die 999, weil\n> der Slice eine View ist; Kopie und Maske liessen das Original unverändert.\n> In R bleibt das Original immer unberührt.\n\n### Beispiel 6: SciPy für Verteilungen, Tests und Optimierung\n\n#### Frage und Datenlage\n\nZehn Messwerte `98, 102, 95, 110, 104, 99, 101, 97, 120, 100`. Gesucht sind\neinige Standardgrössen der Normal- und t-Verteilung, ein Normalitätstest mit\nund ohne den auffälligen Wert 120, eine Fläche unter der Dichte, das Minimum\neiner Funktion und die Standardabweichung.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwerte <- c(98, 102, 95, 110, 104, 99, 101, 97, 120, 100)\n\nround(c(pnorm(1.96), qnorm(0.975), qt(0.975, df = 9)), 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.975002 1.959964 2.262157\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(werte)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  werte\nW = 0.83806, p-value = 0.04182\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(werte[werte != 120])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  werte[werte != 120]\nW = 0.93586, p-value = 0.5391\n```\n\n\n:::\n\n```{.r .cell-code}\nintegrate(dnorm, -1.96, 1.96)$value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9500042\n```\n\n\n:::\n\n```{.r .cell-code}\nround(optimize(function(x) (x - 3)^2 + 2, interval = c(-10, 10))$minimum, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3\n```\n\n\n:::\n\n```{.r .cell-code}\nc(mittel = mean(werte), sd = round(sd(werte), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  mittel       sd \n102.6000   7.3967 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nwerte = np.array([98, 102, 95, 110, 104, 99, 101, 97, 120, 100])\n\nprint(round(stats.norm.cdf(1.96), 6), round(stats.norm.ppf(0.975), 6),\n      round(stats.t.ppf(0.975, df=9), 6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.975002 1.959964 2.262157\n```\n\n\n:::\n\n```{.python .cell-code}\nsw = stats.shapiro(werte)\nprint(round(sw.statistic, 5), round(sw.pvalue, 5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.83806 0.04182\n```\n\n\n:::\n\n```{.python .cell-code}\nsw_ohne = stats.shapiro(werte[werte != 120])\nprint(round(sw_ohne.statistic, 5), round(sw_ohne.pvalue, 5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.93586 0.53909\n```\n\n\n:::\n\n```{.python .cell-code}\nflaeche, _ = integrate.quad(stats.norm.pdf, -1.96, 1.96)\nprint(round(flaeche, 7))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.9500042\n```\n\n\n:::\n\n```{.python .cell-code}\nergebnis = optimize.minimize_scalar(lambda x: (x - 3) ** 2 + 2)\nprint(round(ergebnis.x, 3), round(ergebnis.fun, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n3.0 2.0\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(werte.mean(), round(werte.std(ddof=1), 4), round(werte.std(), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n102.6 7.3967 7.0171\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | Python | R | Erklärung |\n|---|---|---|---|\n| P(Z ≤ 1.96) | 0.975002 | 0.975002 | `cdf` beziehungsweise `pnorm` |\n| 97.5-%-Quantil | 1.959964 | 1.959964 | `ppf` beziehungsweise `qnorm`; die Grenze des zweiseitigen 95-%-Intervalls |\n| t-Quantil, 9 Freiheitsgrade | 2.262157 | 2.262157 | grösser als 1.96, weil die t-Verteilung breitere Ränder hat, siehe [Prüfverteilungen](../statistik/wahrscheinlichkeit/pruefverteilungen.qmd) |\n| Shapiro-Wilk, alle zehn | W = 0.83806, p = 0.04182 | `W = 0.83806, p-value = 0.04182` | Beide Sprachen nutzen denselben Algorithmus. p unter 0.05: Normalität wird verworfen. |\n| ohne den Wert 120 | W = 0.93586, p = 0.53909 | dieselben Werte | Ein einzelner Wert entscheidet über das Testergebnis. |\n| Fläche von −1.96 bis 1.96 | 0.9500042 | 0.9500042 | numerisch integriert, wie erwartet 95 % |\n| Minimum von (x − 3)² + 2 | bei x = 3.0, Wert 2.0 | 3 | R sucht im angegebenen Intervall, SciPy ohne Intervall mit dem Brent-Verfahren. |\n| Mittelwert | 102.6 | 102.6 | |\n| Standardabweichung | `std(ddof=1)`: 7.3967; **`std()`: 7.0171** | `sd`: 7.3967 | NumPy teilt ohne Angabe durch n, R durch n − 1. |\n\n#### Interpretation und Ergebnissatz\n\nSciPy liefert dieselben Zahlen wie R, nur in anderer Verpackung: Wo R eine\nformatierte Testausgabe druckt, gibt SciPy ein Objekt mit `statistic` und\n`pvalue` zurück. Zwei Dinge sind inhaltlich wichtiger als die Syntax. Erstens\nkippt der Wert 120 allein das Ergebnis des Normalitätstests, weshalb ein\nTest nie ohne Grafik gelesen wird, siehe\n[Normalitätstests](../statistik/tests/normalitaetstests.qmd). Zweitens ist\n`np.std()` ohne `ddof=1` die Populationsformel und für Stichproben um den\nFaktor √(9/10) zu klein.\n\n> Mit allen zehn Werten verwirft der Shapiro-Wilk-Test die Normalität\n> (W = 0.838, p = 0.042), ohne den Wert 120 nicht mehr (p = 0.539); R und SciPy\n> liefern identische Zahlen. Die Standardabweichung beträgt 7.3967, `np.std()`\n> ohne `ddof=1` gibt dagegen 7.0171 aus.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEin Array hat die Form `(100, 3)`, ein zweites `(3,)`. Worauf wirkt das\nzweite bei einer gemeinsamen Rechnung?\n\n- [x] Auf jede der hundert Zeilen ~ Richtig. Die Formen werden von hinten\n      verglichen, dort steht beide Male die 3. Typischer Fall ist das Abziehen\n      von Spaltenmittelwerten wie in Beispiel 4.\n- [ ] Auf die ersten drei Zeilen ~ Broadcasting schneidet nichts ab, es\n      wiederholt.\n- [ ] Es entsteht ein Fehler wegen unterschiedlicher Formen ~ Die Formen sind\n      verträglich. Ein Fehler entstünde bei `(100,)`.\n:::\n\n::: {.quiz}\nWarum liefert `a.sum(axis=0)` bei einer 3 × 4-Matrix vier Zahlen?\n\n- [x] Achse 0 ist die der Zeilen und fällt beim Summieren weg ~ Richtig.\n      Übrig bleiben die vier Spalten. Die Zahl in `axis` benennt die Achse,\n      die verschwindet.\n- [ ] Weil NumPy immer über die längere Achse summiert ~ Die Länge spielt\n      keine Rolle, nur die angegebene Achse.\n- [ ] Weil `axis=0` in NumPy dasselbe bedeutet wie die 1 in `apply` ~ In\n      `apply` steht für dasselbe Ergebnis die 2.\n:::\n\n::: {.quiz}\nIn R wird eine Matrix mit `m - colMeans(m)` zentriert. Es gibt keine\nWarnung. Ist das Ergebnis richtig?\n\n- [ ] Ja, sonst hätte R gewarnt ~ R warnt nur, wenn die Länge nicht aufgeht.\n      Bei drei Zeilen und zwei Spalten geht sie auf.\n- [x] Nein, R recycelt spaltenweise und verteilt die Spaltenmittel über die\n      Zeilen ~ Richtig, wie Beispiel 4 zeigt. `sweep(m, 2, colMeans(m))` oder\n      `scale(m, scale = FALSE)` zentrieren richtig.\n- [ ] Nur wenn die Matrix quadratisch ist ~ Auch dann wäre sie falsch\n      zentriert, nur passten die Längen immer.\n:::\n\n::: {.quiz}\n`teil = original[2:5]` und danach `teil[0] = 999`. Was ist mit `original`?\n\n- [x] Es hat sich mitverändert ~ Richtig. Ein Slice liefert eine View.\n      Wer eine unabhängige Kopie braucht, ruft `.copy()` auf.\n- [ ] Es bleibt unverändert ~ So wäre es bei `original[original > 5]` oder in\n      R.\n- [ ] Es gibt einen Fehler ~ Die Zuweisung ist gültig, und genau das macht\n      den Fall gefährlich.\n:::\n\n::: {.quiz}\nEin `uint8`-Array mit Grauwerten 0 bis 255 wird um 100 aufgehellt. Ein Pixel\nmit dem Wert 200 ist danach sehr dunkel. Warum?\n\n- [x] Der Wert ist übergelaufen, 300 − 256 = 44 ~ Richtig. Feste\n      Ganzzahltypen rechnen modulo ihres Wertebereichs, ohne Warnung. Abhilfe:\n      vorher in einen grösseren Typ umwandeln und danach mit `np.clip` auf\n      0 bis 255 begrenzen.\n- [ ] NumPy hat einen Rundungsfehler gemacht ~ Es wird nicht gerundet,\n      sondern umgebrochen.\n- [ ] Grauwerte über 255 werden auf 0 gesetzt ~ Dann wäre der Wert 0, nicht\n      44.\n:::\n\n::: {.quiz}\n`np.std(werte)` ergibt 7.0171, `sd(werte)` in R 7.3967. Welcher Wert ist für\neine Stichprobe richtig?\n\n- [x] 7.3967, mit `ddof=1` ~ Richtig. NumPy teilt ohne Angabe durch n, R\n      durch n − 1. pandas verwendet übrigens wie R n − 1.\n- [ ] 7.0171, weil NumPy genauer rechnet ~ Beide rechnen exakt, nur mit\n      verschiedenen Formeln.\n- [ ] Beide gleich gut ~ Für eine Stichprobe ist die Formel mit n − 1 die\n      übliche erwartungstreue Schätzung der Varianz.\n:::\n\n## Verlinkte Ressourcen\n\n- [NumPy-Dokumentation](https://numpy.org/doc/stable/)\n- [Broadcasting in der NumPy-Dokumentation](https://numpy.org/doc/stable/user/basics.broadcasting.html)\n- [SciPy-Dokumentation](https://docs.scipy.org/doc/scipy/)\n",
    "supporting": [
      "numpy-scipy_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}