{
  "hash": "8c9f7f18565e53c6a0a971ae49a8ecd2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Nichtparametrische Tests\"\ndescription: \"Wilcoxon, Mann-Whitney und Kruskal-Wallis als Ausweichverfahren.\"\ncategories: [\"Hypothesentests\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"ESDS\", \"STATDA\"]\nseitentyp: methode\nstand: fertig\norder: 70\n---\n\n\n\n\n\nAlle Beispiele rechnen mit fest eingetragenen Zahlen, damit R und Python\ndieselben Daten sehen und jeder Wert im Text nachprüfbar ist. Wo sich die\nAusgaben trotzdem unterscheiden, liegt es an der Behandlung von Bindungen; das\nwird bei Beispiel 1 ausführlich erklärt.\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Unterscheiden sich Gruppen, ohne dass Mittelwerte und Normalverteilung vorausgesetzt werden? |\n| Zielvariable | metrisch oder ordinal |\n| Was die Methoden liefern | Teststatistik, p-Wert, Effektmasse auf Rangbasis; in R zusätzlich eine geschätzte Verschiebung mit Konfidenzintervall |\n| R-Funktionen | `wilcox.test()` für eine und zwei Stichproben sowie gepaart, `kruskal.test()` für mehr als zwei Gruppen |\n| Python-Funktionen | `pg.mwu()`, `pg.wilcoxon()`, `pg.kruskal()`, alternativ `stats.mannwhitneyu()`, `stats.wilcoxon()`, `stats.kruskal()` |\n| Verwandte Methoden | [t-Test für zwei Stichproben](t-test-zwei-stichproben.qmd), [gepaarter t-Test](t-test-gepaart.qmd), [Varianzanalyse](anova.qmd) |\n\nDie drei Verfahren gehören zusammen, weil sie derselben Idee folgen. Welches\ndavon zutrifft, hängt allein am Design:\n\n| Design | Rangtest | Parametrisches Gegenstück |\n|---|---|---|\n| Eine Gruppe gegen einen Sollwert | Wilcoxon-Vorzeichen-Rangtest | [t-Test für eine Stichprobe](t-test-eine-stichprobe.qmd) |\n| Zwei unabhängige Gruppen | Mann-Whitney-U-Test (in R als `wilcox.test` ohne `paired`) | [t-Test für zwei Stichproben](t-test-zwei-stichproben.qmd) |\n| Zwei gepaarte Messungen | Wilcoxon-Vorzeichen-Rangtest auf den Differenzen | [gepaarter t-Test](t-test-gepaart.qmd) |\n| Mehr als zwei unabhängige Gruppen | Kruskal-Wallis-Test | [Varianzanalyse](anova.qmd) |\n\n::: {.note-box}\nDie Namensgebung ist eine häufige Fehlerquelle. Mann-Whitney-U und\nWilcoxon-Rangsummentest sind **dasselbe** Verfahren für zwei unabhängige\nGruppen; U und W lassen sich ineinander umrechnen. Der\nWilcoxon-Vorzeichen-Rangtest dagegen ist ein **anderes** Verfahren, für eine\nStichprobe oder gepaarte Daten. In R heissen beide `wilcox.test()`, und nur das\nArgument `paired` unterscheidet sie. In Python sind es zwei Funktionen: `mwu()`\nund `wilcoxon()`.\n:::\n\n## Wann diese Methode, wann nicht\n\nTypische Anlässe: eine ordinale Zielgrösse wie eine Bewertungsskala, eine kleine\nund deutlich schiefe Stichprobe, oder einzelne Extremwerte, an denen ein\nMittelwertvergleich scheitert.\n\nEin Rangtest ersetzt die Rohwerte durch ihre Reihenfolge. Damit verliert er die\nAbstände zwischen den Werten und gewinnt Unempfindlichkeit gegenüber\nAusreissern und Verteilungsform. Beides gehört zusammen: Was ihn robust macht,\nist genau das, was ihm die Aussage über Grössen nimmt.\n\n| Situation | Stattdessen |\n|---|---|\n| Voraussetzungen des t-Tests erfüllt | [t-Test](t-test-zwei-stichproben.qmd); der Rangtest kostet dann etwas Schärfe |\n| Es geht um Mittelwerte in ihrer Einheit | t-Test, oder [Bootstrap](../inferenz/bootstrap-resampling.qmd) für ein Intervall ohne Verteilungsannahme |\n| Nur der Umfang ist klein, die Form aber unauffällig | t-Test; er verträgt kleine Stichproben, solange die Verteilung nicht schief ist |\n| Zielgrösse ist kategorial | [Chi-Quadrat-Tests](chi-quadrat-tests.qmd) |\n| Mehrere Einflussgrössen sollen berücksichtigt werden | [Regression](../regression/index.qmd), gegebenenfalls mit transformierter Zielgrösse |\n| Gruppen unterscheiden sich vor allem in der Streuung | kein Rangtest; die Frage ist eine andere, siehe Interpretationsfallen |\n\n## Grundidee und Modell\n\nAlle Werte werden gemeinsam sortiert und durch ihren Rang ersetzt. Getestet\nwird dann, ob sich die Ränge zwischen den Gruppen anders verteilen, als es der\nZufall erwarten liesse.\n\nBeim Mann-Whitney-U-Test zählt man dazu, wie oft ein Wert der einen Gruppe einen\nWert der anderen übertrifft:\n\n$$U = \\#\\{(i,j) : x_i > y_j\\} + \\tfrac{1}{2}\\,\\#\\{(i,j) : x_i = y_j\\}$$\n\n| Bestandteil | Bedeutung |\n|---|---|\n| $x_i, y_j$ | Werte der beiden Gruppen |\n| $U$ | Anzahl der Paarvergleiche, die die erste Gruppe gewinnt, Gleichstände zählen halb |\n| $n_1 n_2$ | Anzahl aller Paarvergleiche |\n| $U / (n_1 n_2)$ | Anteil gewonnener Vergleiche; bei Gleichheit der Gruppen liegt er bei 0.5 |\n\nDaraus folgt die korrekte Nullhypothese: **Ein zufällig gezogener Wert der einen\nGruppe ist genauso oft grösser wie kleiner als ein zufällig gezogener Wert der\nanderen.** Das ist nicht dasselbe wie \"die Mediane sind gleich\", auch wenn es\noft so verkürzt wird; die beiden Aussagen fallen nur zusammen, wenn die\nVerteilungen dieselbe Form haben.\n\nDer Vorzeichen-Rangtest arbeitet auf den Differenzen zum Sollwert oder zwischen\nden beiden Messungen. Er rangiert deren Beträge und summiert die Ränge der\npositiven Differenzen zu $V$ beziehungsweise $W$. Nur wenn positive und negative\nAbweichungen gleich häufig und gleich gross sind, liegt diese Summe in der Mitte.\n\nKruskal-Wallis verallgemeinert den Mann-Whitney-Test auf mehr als zwei Gruppen\nund ist die Rangvariante der [Varianzanalyse](anova.qmd).\n\n## Voraussetzungen und ihre Prüfung\n\nRangtests sind nicht voraussetzungsfrei. Sie brauchen weniger, nicht nichts.\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung |\n|---|---|---|---|\n| Unabhängigkeit | Beobachtungen beeinflussen sich nicht, Gruppen sind getrennt erhoben | Erhebungsdesign | p-Wert wertlos; bei gepaarten Daten den Vorzeichen-Rangtest verwenden |\n| Mindestens ordinale Skala | Die Werte lassen sich sinnvoll in eine Reihenfolge bringen | [Skalenniveau](../grundlagen/skalenniveaus.qmd) | Ränge sind nicht definiert |\n| Stetige oder wenigstens fein abgestufte Werte | Bindungen sind die Ausnahme, nicht die Regel | Werte zählen, Anteil doppelter Werte ansehen | Exakte Verteilung nicht mehr gültig, die Programme weichen auf Näherungen aus |\n| Für die Aussage über Mediane: gleiche Verteilungsform | Nur dann ist der Test ein Medianvergleich | Verteilungen nebeneinander zeichnen | Der Test bleibt gültig, aber die Deutung als Medianvergleich nicht |\n\nDie letzte Zeile ist die, die am häufigsten übersehen wird. Sie betrifft nicht\ndie Gültigkeit des Tests, sondern die Formulierung des Ergebnisses.\n\n## Output lesen\n\nR, `wilcox.test()` und `kruskal.test()`:\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| `W` bei zwei unabhängigen Gruppen | die U-Statistik der ersten Gruppe | trotz des Buchstabens W dasselbe wie Mann-Whitneys U |\n| `V` bei einer Stichprobe oder gepaart | Rangsumme der positiven Differenzen | nicht mit W verwechseln; die beiden Verfahren sind verschieden |\n| `Kruskal-Wallis chi-squared` | Teststatistik | folgt näherungsweise einer Chi-Quadrat-Verteilung |\n| `df` | Freiheitsgrade bei Kruskal-Wallis | Anzahl Gruppen minus eins |\n| `p-value` | Wahrscheinlichkeit einer mindestens so ungleichen Rangverteilung | keine Aussage über die Grösse des Unterschieds |\n| `exact test` im Titel | R hat die Verteilung abgezählt | die genaueste Variante; sie ist nur bei kleinen Stichproben möglich |\n| `test with continuity correction` im Titel | R hat genähert | tritt bei grossen Stichproben auf und wenn Bindungen die Abzählung verhindern |\n| Warnung `cannot compute exact p-value with ties` | Bindungen verhindern die Abzählung | R weicht dann auf die Normalapproximation aus und sagt es |\n| Warnung `with zeroes` | Differenzen von genau null | diese Paare werden entfernt, das wirksame n sinkt, siehe Beispiel 2 |\n| `conf.int = TRUE` | geschätzte Verschiebung mit Intervall | die einzige Grössenangabe, die das Verfahren liefert, siehe Beispiel 4 |\n\nPython, `pingouin`:\n\n| Spalte | Was sie sagt | Unterschied zu R |\n|---|---|---|\n| `U_val` bzw. `W_val` | Teststatistik | dieselbe Grösse wie in R, andere Bezeichnung |\n| `p_val` | p-Wert | Bindungen werden anders behandelt, siehe Beispiel 2 |\n| `RBC` | rangbiseriale Korrelation | in R nicht enthalten; Effektmass zwischen -1 und 1 |\n| `CLES` | Common Language Effect Size | in R nicht enthalten; Wahrscheinlichkeit, dass ein zufälliger Wert der ersten Gruppe grösser ist |\n| keine Verschiebungsschätzung | fehlt | in R über `conf.int = TRUE` |\n\n## Interpretationsfallen\n\n- **Ein Rangtest vergleicht nicht automatisch Mediane.** Er vergleicht, wie oft\n  ein Wert der einen Gruppe grösser ist. Nur bei gleicher Verteilungsform ist\n  das gleichbedeutend mit einem Medianvergleich.\n- **Nichtparametrisch heisst nicht voraussetzungsfrei.** Unabhängigkeit bleibt\n  zwingend, und die Skala muss mindestens ordinal sein.\n- **Ein signifikanter Rangtest sagt nichts über die Grösse.** Die Rangsumme ist\n  nicht in der Einheit der Messung deutbar. Dafür gibt es die Verschiebung mit\n  Intervall, RBC oder CLES.\n- **Bindungen sind kein Randproblem.** Bei einer Skala von 1 bis 7 ist fast\n  jeder Wert mehrfach vorhanden; damit fällt die exakte Verteilung weg, und die\n  Programme rechnen unterschiedlich weiter.\n- **Der Rangtest ist keine Reparatur für schlechte Daten.** Er hilft gegen\n  Schiefe und Ausreisser, nicht gegen fehlende Werte, falsche Zuordnung oder\n  ein ungeeignetes Design.\n- **Nach Kruskal-Wallis braucht es Post-hoc-Vergleiche mit Korrektur**, genau wie\n  nach einer [Varianzanalyse](anova.qmd); der Gesamttest sagt nur, dass sich\n  irgendwo etwas unterscheidet.\n- **Bei erfüllten Voraussetzungen ist der t-Test schärfer.** Der Verzicht kostet\n  rund fünf Prozent Effizienz; wer grundsätzlich rangbasiert testet, verschenkt\n  sie ohne Not.\n\n## Ergebnis berichten\n\nVorlage für den Ergebnissatz:\n\n> [Zielgrösse] unterscheidet sich zwischen [Gruppe 1] (Median [Wert],\n> n = [n1]) und [Gruppe 2] (Median [Wert], n = [n2]): [Testname], [Statistik],\n> p = [p]. Die geschätzte Verschiebung beträgt [Wert] [Einheit]\n> (95-Prozent-Konfidenzintervall [unten] bis [oben]).\n\nGenannt werden: das Verfahren mit seinem vollen Namen, die Teststatistik, der\np-Wert, die Gruppengrössen, ein Lagemass je Gruppe (Median statt Mittelwert),\nein Effektmass und der **Grund**, warum rangbasiert getestet wurde. Der letzte\nPunkt fehlt am häufigsten und ist der wichtigste: Ohne ihn steht der Verdacht im\nRaum, dass erst der t-Test gerechnet und dann gewechselt wurde.\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt eines Rangtests |\n|---|---|\n| [t-Test für zwei Stichproben](t-test-zwei-stichproben.qmd) | Voraussetzungen erfüllt und eine Aussage über Mittelwerte gewünscht |\n| [Gepaarter t-Test](t-test-gepaart.qmd) | dasselbe bei verbundenen Messungen |\n| [Varianzanalyse](anova.qmd) | mehr als zwei Gruppen, Voraussetzungen erfüllt |\n| [Bootstrap](../inferenz/bootstrap-resampling.qmd) | ein Intervall für den Mittelwert ohne Verteilungsannahme |\n| [Chi-Quadrat-Tests](chi-quadrat-tests.qmd) | Zielgrösse kategorial statt ordinal |\n| [Korrelationstests](korrelationstests.qmd) | Frage nach Zusammenhang statt nach Unterschied; Spearman ist der Rangansatz dort |\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Zwei Gruppen auf einer Bewertungsskala\n\n#### Frage und Datenlage\n\nZwei Betreuungsvarianten werden von Kundinnen und Kunden auf einer Skala von 1\nbis 7 bewertet, 14 Personen für Variante A und 15 für Variante B. Die Frage\nlautet: Wird A besser bewertet als B?\n\nDie Zielgrösse ist ordinal. Der Abstand zwischen 5 und 6 muss nicht derselbe\nsein wie zwischen 6 und 7, und ein Mittelwert von 5.5 beschreibt keine\ntatsächlich vergebene Note. Damit ist der Rangtest nicht Ausweichverfahren,\nsondern erste Wahl.\n\n#### Voraussetzungen prüfen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvariante_a <- c(5, 6, 4, 6, 5, 7, 5, 6, 4, 6, 5, 7, 6, 5)\nvariante_b <- c(3, 4, 5, 3, 4, 2, 4, 3, 5, 4, 3, 4, 2, 5, 4)\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nbarplot(table(factor(variante_a, levels = 1:7)), main = \"Variante A\",\n        xlab = \"Bewertung\", ylab = \"Anzahl\")\nbarplot(table(factor(variante_b, levels = 1:7)), main = \"Variante B\",\n        xlab = \"Bewertung\", ylab = \"Anzahl\")\npar(mfrow = c(1, 1))\n\ndata.frame(\n  variante = c(\"A\", \"B\"),\n  n = c(length(variante_a), length(variante_b)),\n  median = c(median(variante_a), median(variante_b)),\n  min = c(min(variante_a), min(variante_b)),\n  max = c(max(variante_a), max(variante_b))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  variante  n median min max\n1        A 14    5.5   4   7\n2        B 15    4.0   2   5\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 1: Verteilung der Bewertungen je Variante.](nichtparametrische-tests_files/figure-html/fig-b1-np-voraussetzungen-r-1.png){#fig-b1-np-voraussetzungen-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nvariante_a = np.array([5, 6, 4, 6, 5, 7, 5, 6, 4, 6, 5, 7, 6, 5])\nvariante_b = np.array([3, 4, 5, 3, 4, 2, 4, 3, 5, 4, 3, 4, 2, 5, 4])\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nfor achse, werte, titel in zip(achsen, [variante_a, variante_b], \"AB\"):\n    anzahl = [np.sum(werte == k) for k in range(1, 8)]\n    achse.bar(range(1, 8), anzahl, color=\"0.4\")\n    achse.set_title(f\"Variante {titel}\")\n    achse.set_xlabel(\"Bewertung\")\n    achse.set_ylabel(\"Anzahl\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Darstellung in Python.](nichtparametrische-tests_files/figure-html/fig-b1-np-voraussetzungen-py-1.png){#fig-b1-np-voraussetzungen-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(pd.DataFrame({\n    \"variante\": [\"A\", \"B\"],\n    \"n\": [len(variante_a), len(variante_b)],\n    \"median\": [np.median(variante_a), np.median(variante_b)],\n    \"min\": [variante_a.min(), variante_b.min()],\n    \"max\": [variante_a.max(), variante_b.max()],\n}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  variante   n  median  min  max\n0        A  14     5.5    4    7\n1        B  15     4.0    2    5\n```\n\n\n:::\n:::\n\n\n:::\n\nVariante A liegt bei einem Median von 5.5 mit Werten von 4 bis 7, Variante B bei\n4.0 mit Werten von 2 bis 5. Die beiden Verteilungen haben eine ähnliche Form,\nsie sind gegeneinander verschoben. Das ist der Fall, in dem die Deutung als\nMedianvergleich zulässig ist.\n\nBindungen gibt es reichlich: Bei 29 Personen und sieben möglichen Werten kommt\njede Note mehrfach vor. Genau daran entscheidet sich, ob ein Programm die exakte\nVerteilung abzählt oder näherungsweise rechnet, und die beiden Sprachen\nentscheiden das verschieden.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(variante_a, variante_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum exact test\n\ndata:  variante_a and variante_b\nW = 190.5, p-value = 5.774e-05\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(pg.mwu(variante_a, variante_b).round(4).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   MWU\nU_val            190.5\nalternative  two-sided\np_val           0.0001\nRBC             0.8143\nCLES            0.9071\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| Testname | `Wilcoxon rank sum exact test` | Mann-Whitney-U für zwei unabhängige Gruppen | R nennt das Verfahren nach Wilcoxon, gemeint ist derselbe Test wie Mann-Whitneys U. `exact` heisst, dass R die Verteilung der Teststatistik abgezählt und nicht genähert hat. |\n| `W` bzw. `U_val` | 190.5 | Anzahl der gewonnenen Paarvergleiche | Von 14 mal 15 = 210 Vergleichen gewinnt A 190.5, wobei Gleichstände halb zählen. Bei Gleichheit der Varianten läge der Wert bei 105. Die halbe Zahl zeigt an, dass es Gleichstände gibt. |\n| `p-value` in R | 0.00005774 | Wahrscheinlichkeit einer mindestens so ungleichen Rangverteilung bei gleichen Varianten | Deutlich unter 0.05. |\n| `p_val` in Python | 0.000142 | dasselbe, anders gerechnet | Rund zweieinhalbmal so gross wie in R, siehe den Kasten unten. An der Entscheidung ändert es nichts. |\n| `RBC` (nur Python) | 0.814 | rangbiseriale Korrelation | Sie ergibt sich direkt aus U: 190.5 von 210 Vergleichen gewonnen entspricht 0.814 auf einer Skala von -1 bis 1. |\n| `CLES` (nur Python) | 0.907 | Common Language Effect Size | Die anschaulichste Zahl der ganzen Ausgabe: Greift man zufällig je eine Person aus beiden Gruppen heraus, bewertet die aus Gruppe A in rund 91 Prozent der Fälle besser. |\n\n::: {.note-box}\n**Warum R und Python hier verschiedene p-Werte zeigen.** Beide rechnen richtig,\nsie wählen nur ein anderes Verfahren für dieselbe Frage.\n\nR zählt die exakte Verteilung der Teststatistik ab und kommt auf 0.00005774.\nscipy und pingouin schalten bei Bindungen auf die Normalapproximation um und\nkommen auf 0.000142. Der Unterschied ist ein Faktor von rund 2.5 und trotzdem\nbelanglos, weil beide Werte weit unter jeder Schwelle liegen.\n\nBei einem Ergebnis nahe 0.05 wäre er das nicht. Deshalb gehört ins Protokoll,\nmit welchem Programm und welcher Einstellung gerechnet wurde. Wer beide\nSprachen verwendet und abweichende p-Werte sieht, prüft bei Rangtests zuerst,\nob Bindungen vorliegen: Die halbe Stelle in W = 190.5 ist bereits der Hinweis\ndarauf.\n:::\n\n#### Interpretation und Ergebnissatz\n\nDer p-Wert beantwortet nur, ob der Unterschied vom Zufall unterscheidbar ist.\nDie Grösse steht in CLES und, falls verlangt, in der Verschiebungsschätzung aus\nBeispiel 4.\n\nBerichtet werden Mediane, nicht Mittelwerte. Ein Mittelwert von 5.5 auf einer\nSkala mit sieben Stufen unterstellt, dass die Abstände zwischen den Stufen\ngleich gross sind, und genau das ist bei einer Bewertungsskala nicht gesichert.\n\n> Variante A wird besser bewertet als Variante B (Mann-Whitney-U-Test,\n> U = 190.5, p < 0.001; Mediane 5.5 gegenüber 4.0, n = 14 und 15). Die\n> Common Language Effect Size beträgt 0.91: Eine zufällig gewählte Person aus\n> Gruppe A bewertet in rund neun von zehn Fällen besser als eine zufällig\n> gewählte aus Gruppe B. Rangbasiert getestet wurde wegen der ordinalen Skala.\n\n### Beispiel 2: Gepaart, und warum R und Python verschiedene p-Werte zeigen\n\n#### Frage und Datenlage\n\nZwölf Personen bewerten ihre Beschwerden vor und nach einer Massnahme auf einer\nSkala von 0 bis 10. Dieselben Personen, zwei Messungen: Das ist der\nVorzeichen-Rangtest auf den Differenzen, nicht der Mann-Whitney-Test.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvorher <- c(7, 6, 8, 5, 7, 6, 8, 7, 6, 5, 7, 8)\nnachher <- c(5, 5, 6, 5, 4, 4, 7, 5, 6, 3, 5, 6)\n\ndata.frame(vorher, nachher, differenz = nachher - vorher)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   vorher nachher differenz\n1       7       5        -2\n2       6       5        -1\n3       8       6        -2\n4       5       5         0\n5       7       4        -3\n6       6       4        -2\n7       8       7        -1\n8       7       5        -2\n9       6       6         0\n10      5       3        -2\n11      7       5        -2\n12      8       6        -2\n```\n\n\n:::\n\n```{.r .cell-code}\nwilcox.test(nachher, vorher, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon signed rank exact test\n\ndata:  nachher and vorher\nV = 0, p-value = 0.001953\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nvorher = np.array([7, 6, 8, 5, 7, 6, 8, 7, 6, 5, 7, 8])\nnachher = np.array([5, 5, 6, 5, 4, 4, 7, 5, 6, 3, 5, 6])\n\nprint(\"Differenzen:\", (nachher - vorher).tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDifferenzen: [-2, -1, -2, 0, -3, -2, -1, -2, 0, -2, -2, -2]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pg.wilcoxon(nachher, vorher).round(4).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Wilcoxon\nW_val              0.0\nalternative  two-sided\np_val            0.002\nRBC               -1.0\nCLES            0.1562\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| Differenzen | zehnmal negativ, zweimal null | Veränderung je Person | Keine einzige Person hat sich verschlechtert. Das ist der ganze Befund; der Test quantifiziert nur noch, wie unwahrscheinlich das bei Wirkungslosigkeit wäre. |\n| `V` bzw. `W_val` | 0 | Rangsumme der **positiven** Differenzen | Null, weil es keine positiven Differenzen gibt. Der kleinstmögliche Wert. |\n| `p-value` | 0.001953 in R, 0.002 in Python | | Hier stimmen beide Sprachen überein, anders als in Beispiel 1. |\n| Nulldifferenzen | zwei | Personen ohne Veränderung | Sie werden aus der Rechnung entfernt. Das wirksame n sinkt von 12 auf 10, und beide Programme rechnen dann auf derselben Grundlage. |\n| `RBC` (nur Python) | -1.0 | rangbiseriale Korrelation | Der Extremwert. Alle von null verschiedenen Differenzen zeigen in dieselbe Richtung. |\n| `CLES` (nur Python) | 0.156 | Common Language Effect Size | Ein zufällig gewählter Nachher-Wert ist nur in 16 Prozent der Vergleiche höher als ein zufällig gewählter Vorher-Wert. |\n\n::: {.note-box}\n**Nulldifferenzen verschwinden aus der Rechnung.** Beide Personen ohne\nVeränderung werden vor dem Test entfernt, weil ihre Differenz kein Vorzeichen\nhat. Das wirksame n sinkt damit von 12 auf 10.\n\nDas ist mehr als eine Formalie. Die Aussage \"hat sich nicht verändert\" ist ein\nBefund, und der Test verwertet ihn nicht. Bei zwei von zwölf Fällen ist das\nverkraftbar; wären es sechs, wäre der Vorzeichen-Rangtest das falsche\nVerfahren. Dann gehört die Richtung der Veränderung als kategoriale Grösse\nausgewertet, etwa mit einem Vorzeichentest oder über die Häufigkeiten\n\"besser, gleich, schlechter\".\n\nAnders als in Beispiel 1 stimmen R und Python hier überein: Beide rechnen nach\ndem Entfernen der Nullen mit der exakten Verteilung. Ob das gelingt, hängt an\nden Daten und nicht an der Sprache, und deshalb lohnt der Blick auf die\nTestbezeichnung in der R-Ausgabe. Steht dort `exact test`, wurde abgezählt;\nsteht dort `test with continuity correction`, wurde genähert.\n:::\n\n#### Interpretation und Ergebnissatz\n\nDie zwei Personen ohne Veränderung verschwinden im Test vollständig. Das\nwirksame n sinkt damit von 12 auf 10, und die Information \"keine Veränderung\"\nwird gar nicht verwertet. Bei vielen Nulldifferenzen ist das ein ernstes\nProblem, und dann gehört ein anderes Verfahren gewählt, etwa ein Vorzeichentest\noder eine Auswertung der Veränderungsrichtung als kategoriale Grösse.\n\n> Die Beschwerden gehen nach der Massnahme zurück (Wilcoxon-Vorzeichen-Rangtest\n> für verbundene Stichproben, V = 0, p = 0.004; Mediane 7.0 vor und 5.0 nach\n> der Massnahme, n = 12). Zehn Personen verbesserten sich, zwei blieben\n> unverändert, keine verschlechterte sich; die beiden unveränderten Fälle gehen\n> nicht in den Test ein. Rangbasiert ausgewertet wurde wegen der ordinalen\n> Skala.\n\n### Beispiel 3: Mehr als zwei Gruppen\n\n#### Frage und Datenlage\n\nDrei Schulungsvarianten werden von je zehn Personen auf einer Skala von 1 bis 10\nbewertet. Die Frage lautet: Unterscheiden sich die Varianten?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschulung <- data.frame(\n  bewertung = c(6, 7, 5, 6, 7, 6, 5, 7, 6, 6,\n                8, 9, 7, 8, 9, 8, 7, 9, 8, 8,\n                6, 5, 7, 6, 6, 5, 7, 6, 5, 6),\n  variante = factor(rep(c(\"A\", \"B\", \"C\"), each = 10))\n)\n\nkruskal.test(bewertung ~ variante, data = schulung)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  bewertung by variante\nKruskal-Wallis chi-squared = 18.738, df = 2, p-value = 8.535e-05\n```\n\n\n:::\n\n```{.r .cell-code}\naggregate(bewertung ~ variante, data = schulung, median)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  variante bewertung\n1        A         6\n2        B         8\n3        C         6\n```\n\n\n:::\n\n```{.r .cell-code}\npairwise.wilcox.test(schulung$bewertung, schulung$variante,\n                     p.adjust.method = \"holm\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPairwise comparisons using Wilcoxon rank sum exact test \n\ndata:  schulung$bewertung and schulung$variante \n\n  A       B      \nB 0.00022 -      \nC 0.76048 0.00019\n\nP value adjustment method: holm \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nschulung = pd.DataFrame({\n    \"bewertung\": [6, 7, 5, 6, 7, 6, 5, 7, 6, 6,\n                  8, 9, 7, 8, 9, 8, 7, 9, 8, 8,\n                  6, 5, 7, 6, 6, 5, 7, 6, 5, 6],\n    \"variante\": [\"A\"] * 10 + [\"B\"] * 10 + [\"C\"] * 10,\n})\n\nprint(pg.kruskal(data=schulung, dv=\"bewertung\", between=\"variante\").round(6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Source  ddof1          H     p_unc\nKruskal  variante      2  18.737565  0.000085\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(schulung.groupby(\"variante\")[\"bewertung\"].median())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nvariante\nA    6.0\nB    8.0\nC    6.0\nName: bewertung, dtype: float64\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| `Kruskal-Wallis chi-squared` bzw. `H` | 18.738 | Teststatistik | Sie misst, wie ungleich sich die Ränge auf die drei Gruppen verteilen. |\n| `df` | 2 | Freiheitsgrade | Anzahl Gruppen minus eins. |\n| `p-value` | 0.000085 | | Irgendwo unterscheiden sich die Varianten. |\n| Mediane | 6.0 / 8.0 / 6.0 | Lagemass je Gruppe | Hier deutet sich bereits an, wo der Unterschied sitzt: B liegt höher, A und C liegen gleich. |\n| Paarweise p-Werte (nur R) | B gegen A 0.00022, C gegen B 0.00019, C gegen A 0.76 | Post-hoc nach Holm | Erst diese Zeilen beantworten die eigentliche Frage: B unterscheidet sich von beiden anderen, A und C nicht voneinander. |\n\nDer Aufbau ist derselbe wie bei der [Varianzanalyse](anova.qmd): Der Gesamttest\nsagt nur, dass es irgendwo einen Unterschied gibt. Ohne Post-hoc-Vergleiche\nbleibt das Ergebnis inhaltlich leer, und ohne Korrektur für\n[multiples Testen](../inferenz/multiples-testen.qmd) wären die paarweisen\np-Werte zu optimistisch.\n\nDie Holm-Korrektur ist dabei der Bonferroni-Korrektur vorzuziehen: Sie hält\ndasselbe Niveau ein, verwirft aber häufiger. pingouin liefert für Kruskal-Wallis\nkeine Post-hoc-Vergleiche mit; in Python ist dafür `scikit-posthocs` mit dem\nDunn-Test üblich.\n\n#### Interpretation und Ergebnissatz\n\n> Die Bewertungen unterscheiden sich zwischen den drei Varianten\n> (Kruskal-Wallis, H(2) = 18.74, p < 0.001, n = 10 je Variante). Variante B\n> wird höher bewertet (Median 8.0) als A und C (je Median 6.0), die sich\n> untereinander nicht unterscheiden; paarweise Vergleiche nach Holm korrigiert.\n\n### Beispiel 4: Was der Rangtest über die Grösse sagt\n\n#### Frage und Datenlage\n\nDie Daten aus Beispiel 1. Der Test hat gezeigt, **dass** sich die Varianten\nunterscheiden. Dieses Beispiel beantwortet die zweite Frage: um wie viel?\n\nDas ist der Punkt, an dem Rangtests oft aufhören und deshalb den Ruf haben, nur\np-Werte zu liefern. Das stimmt nicht: R schätzt die Verschiebung zwischen den\nbeiden Verteilungen samt Konfidenzintervall, wenn man es verlangt.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(variante_a, variante_b, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum exact test\n\ndata:  variante_a and variante_b\nW = 190.5, p-value = 5.774e-05\nalternative hypothesis: true location shift is not equal to 0\n97.7 percent confidence interval:\n 1 3\nsample estimates:\ndifference in location \n                     2 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# pingouin und scipy liefern keine Verschiebungsschaetzung. Sie ist der Median\n# aller paarweisen Differenzen, der Hodges-Lehmann-Schaetzer, und laesst sich\n# in einer Zeile nachbauen.\npaardifferenzen = np.subtract.outer(variante_a, variante_b).ravel()\nprint(\"Hodges-Lehmann-Schätzer:\", np.median(paardifferenzen))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHodges-Lehmann-Schätzer: 2.0\n```\n\n\n:::\n\n```{.python .cell-code}\nergebnis = pg.mwu(variante_a, variante_b)\nprint(\"RBC  =\", round(float(ergebnis[\"RBC\"].iloc[0]), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRBC  = 0.8143\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"CLES =\", round(float(ergebnis[\"CLES\"].iloc[0]), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCLES = 0.9071\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| `difference in location` | 2.0 | geschätzte Verschiebung zwischen den Verteilungen | Der Hodges-Lehmann-Schätzer, also der Median aller 210 paarweisen Differenzen. Nicht die Differenz der Mediane, auch wenn beide hier zufällig übereinstimmen. |\n| `97.7 percent confidence interval` | 1 bis 3 | Intervall für diese Verschiebung | Die Verschiebung liegt plausibel zwischen einem und drei Skalenpunkten. Auf einer Skala von 1 bis 7 ist das viel. Zur Prozentzahl siehe den Kasten unten. |\n| `CLES` | 0.907 | Wahrscheinlichkeit, dass A besser bewertet | Braucht keine Einheit und ist deshalb auch Laien erklärbar. |\n| `RBC` | 0.814 | rangbiseriale Korrelation | Anhaltspunkte wie bei einer Korrelation: 0.1 klein, 0.3 mittel, 0.5 gross. |\n\n::: {.note-box}\n**Warum dort 97.7 Prozent steht und nicht 95.** Das Intervall entsteht aus den\n210 paarweisen Differenzen, und diese sind bei einer siebenstufigen Skala nur\nganze Zahlen. Ein Intervall lässt sich deshalb nicht beliebig fein einstellen:\nR nimmt die nächstgelegene erreichbare Grenze und schreibt ehrlich dazu,\nwelches Niveau dabei herauskommt. Angefordert waren 95 Prozent, erreichbar\nwaren 97.7.\n\nDas ist kein Fehler, sondern eine Eigenschaft aller exakten Verfahren auf\ndiskreten Daten. Berichtet wird das tatsächlich erreichte Niveau, nicht das\nangeforderte.\n:::\n\n::: {.note-box}\nDer Hodges-Lehmann-Schätzer ist nicht die Differenz der Mediane. Er ist der\nMedian **aller** paarweisen Differenzen zwischen den beiden Gruppen. Bei\ngleicher Verteilungsform liegen beide nah beieinander, bei verschiedener können\nsie deutlich auseinanderfallen. Berichtet wird der Wert, den das Verfahren\nliefert, und zwar unter seinem Namen.\n:::\n\n#### Interpretation und Ergebnissatz\n\nMit diesen drei Zahlen ist der Bericht vollständig: Der p-Wert sagt, dass der\nUnterschied vom Zufall unterscheidbar ist. Die Verschiebung mit Intervall sagt,\nwie gross er in Skalenpunkten ist. CLES übersetzt ihn in eine Aussage, die ohne\nStatistikkenntnisse verständlich ist.\n\nGenau diese Kombination sollte auch beim [t-Test](t-test-zwei-stichproben.qmd)\nstehen: Teststatistik, Effektgrösse in der Einheit der Sache, standardisiertes\nEffektmass. Rangtests sind darin nicht schlechter, sie werden nur seltener so\nberichtet.\n\n> Variante A wird um geschätzte 2 Skalenpunkte besser bewertet als Variante B\n> (Hodges-Lehmann-Schätzer, Konfidenzintervall 1 bis 3 bei einem erreichten\n> Niveau von 97.7 Prozent; Mann-Whitney-U-Test, U = 190.5, p < 0.001, n = 14\n> und 15). Die Common Language Effect Size beträgt 0.91.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nR meldet `cannot compute exact p-value with ties`. Was ist zu tun?\n\n- [x] Nichts, ausser den Umstand im Bericht zu erwähnen ~ Richtig. Die Meldung\n      ist ein Hinweis, kein Fehler: R weicht auf die Normalapproximation aus.\n      Bei ordinalen Skalen sind Bindungen unvermeidlich. Wichtig ist nur, dass\n      man weiss, welches Verfahren gerechnet wurde, denn Python entscheidet hier\n      anders.\n- [ ] Die Bindungen durch kleine Zufallswerte auflösen ~ Das erfindet\n      Information, die nicht erhoben wurde, und macht das Ergebnis vom\n      Zufallsgenerator abhängig.\n- [ ] Auf den t-Test wechseln ~ Der Wechsel des Verfahrens aufgrund einer\n      Warnung ist keine inhaltliche Begründung.\n:::\n\n::: {.quiz}\nZwei Gruppen haben denselben Median, der Mann-Whitney-Test ist trotzdem\nsignifikant. Widerspruch?\n\n- [x] Nein, der Test vergleicht nicht Mediane, sondern wie oft ein Wert grösser\n      ist ~ Richtig. Seine Nullhypothese lautet, dass ein zufällig gezogener\n      Wert der einen Gruppe genauso oft grösser wie kleiner ist als einer der\n      anderen. Bei verschieden geformten Verteilungen kann das verletzt sein,\n      obwohl die Mediane übereinstimmen.\n- [ ] Ja, dann muss ein Rechenfehler vorliegen ~ Der Fall tritt regelmässig auf,\n      sobald die Verteilungen verschiedene Formen haben.\n- [ ] Ja, der Test ist dann ungültig ~ Er ist gültig; nur die verkürzte Deutung\n      als Medianvergleich ist es nicht.\n:::\n\n::: {.quiz}\nWarum ist CLES = 0.91 für einen Bericht oft nützlicher als U = 190.5?\n\n- [x] Weil CLES ohne Statistikkenntnisse verständlich ist ~ Richtig. \"Eine\n      zufällig gewählte Person aus A bewertet in neun von zehn Fällen besser\"\n      ist eine Aussage, die jeder versteht. U = 190.5 ist ohne die\n      Gruppengrössen nicht einmal einzuordnen.\n- [ ] Weil CLES genauer ist ~ Beide beruhen auf denselben Paarvergleichen; CLES\n      ist U geteilt durch die Anzahl aller Vergleiche.\n- [ ] Weil U von der Stichprobengrösse unabhängig ist ~ Genau umgekehrt: U\n      wächst mit den Gruppengrössen, CLES nicht.\n:::\n\n::: {.quiz}\nDie Voraussetzungen des t-Tests sind erfüllt. Spricht etwas dagegen, trotzdem\nrangbasiert zu testen?\n\n- [x] Ja, der Rangtest ist dann etwas weniger scharf ~ Richtig. Bei\n      normalverteilten Daten liegt die Effizienz des Rangtests bei rund 95\n      Prozent des t-Tests. Man verschenkt also einen kleinen Teil der\n      Aussagekraft, und man verliert die Aussage über Mittelwerte in ihrer\n      Einheit.\n- [ ] Nein, Rangtests sind immer die sichere Wahl ~ Sicherer gegen verletzte\n      Voraussetzungen, ja; kostenlos ist das aber nicht.\n- [ ] Ja, Rangtests sind bei grossem n nicht anwendbar ~ Sie sind es, und die\n      Normalapproximation wird mit wachsendem n sogar besser.\n:::\n\n## Verlinkte Ressourcen\n\n- [R-Dokumentation zu `wilcox.test`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/wilcox.test.html)\n- [R-Dokumentation zu `kruskal.test`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/kruskal.test.html)\n- [pingouin: mwu](https://pingouin-stats.org/build/html/generated/pingouin.mwu.html)\n- [pingouin: wilcoxon](https://pingouin-stats.org/build/html/generated/pingouin.wilcoxon.html)\n",
    "supporting": [
      "nichtparametrische-tests_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}