{
  "hash": "b9df9d49b1d2945b487964d86ae3dfd5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hypothesentests: Grundlagen\"\ndescription: \"Testlogik, Fehler erster und zweiter Art, p-Wert und was er nicht bedeutet.\"\ncategories: [\"Hypothesentests\", \"Schätzen\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"ESDS\", \"STATDA\"]\nseitentyp: konzept\nstand: entwurf\norder: 20\n---\n\n\n\n\n\n## Kernideen\n\n- Ein Test beantwortet nicht die Frage, die man stellt. Gefragt wird \"wie gross\n  ist der Effekt\", beantwortet wird \"wie ungewöhnlich wären diese Daten, wenn es\n  ihn nicht gäbe\".\n- Die Nullhypothese wird verworfen oder nicht verworfen. **Angenommen wird sie\n  nie**, denn ein fehlender Nachweis ist kein Nachweis des Fehlens.\n- Der p-Wert ist eine Wahrscheinlichkeit für **Daten** unter einer Annahme, nicht\n  für die Annahme. Die beiden Richtungen der Bedingung sind nicht vertauschbar.\n- Fehler erster und zweiter Art bewegen sich bei festem Stichprobenumfang\n  gegenläufig. Beide zugleich zu senken geht nur über mehr Daten.\n- Wie gross ein p-Wert wird, hängt an drei Dingen gleichzeitig: Effektgrösse,\n  Streuung und Stichprobenumfang. Er trennt sie nicht auf.\n- Ein berichtsfähiges Ergebnis besteht aus Schätzwert, Konfidenzintervall,\n  Teststatistik mit Freiheitsgraden, p-Wert, [Effektstärke](effektstaerken.qmd)\n  und n.\n\n## Erklärung\n\n::: {.note-box}\nVorausgesetzt werden die Verteilung einer Zufallsvariablen, der zentrale\nGrenzwertsatz und das Prinzip des [Schätzens mit\nUnsicherheit](schaetzen-konfidenzintervalle.qmd). Wer die Verteilung einer\nSchätzung nicht vor Augen hat, kann einen p-Wert nicht einordnen.\n:::\n\n### Die Umkehrung, mit der jeder Test arbeitet\n\nEin Test beantwortet nicht die Frage, die man eigentlich stellt. Interessant\nwäre \"wie wahrscheinlich ist mein Effekt\", beantwortet wird \"wie ungewöhnlich\nwären meine Daten, wenn es den Effekt nicht gäbe\". Dafür wird zuerst eine\nGegenannahme formuliert, die Nullhypothese: kein Unterschied, kein Zusammenhang,\nkein Effekt. Sie ist präzise, weil sie einen einzigen Wert nennt, und genau\ndeshalb lässt sich unter ihr rechnen.\n\nDer Ablauf ist immer derselbe:\n\n1. Nullhypothese und Alternativhypothese festlegen, vor dem Blick in die Daten.\n2. Signifikanzniveau festlegen, üblicherweise 5 Prozent.\n3. Eine Teststatistik berechnen, die den beobachteten Effekt an der Streuung der\n   Daten und am Stichprobenumfang misst.\n4. Die Verteilung dieser Statistik unter der Nullhypothese heranziehen und\n   fragen, wie weit aussen der beobachtete Wert liegt.\n5. Entscheiden, und zwar nur über die Nullhypothese: verwerfen oder nicht\n   verwerfen. Ein Annehmen der Nullhypothese gibt es nicht.\n\nDie Alternativhypothese entscheidet, ob ein- oder zweiseitig getestet wird.\nZweiseitig ist der Standardfall, es interessiert eine Abweichung in beide\nRichtungen. Einseitig testet nur, wer die Richtung vorher aus der Sache heraus\nfestlegen kann, und halbiert damit den p-Wert. Die Richtung nach dem Blick auf\ndie Daten zu wählen, ist keine Entscheidung, sondern eine Verschiebung des\nNiveaus.\n\n### Zwei Fehler, die sich nicht gemeinsam kleinmachen lassen\n\n| | Nullhypothese ist wahr | Nullhypothese ist falsch |\n|---|---|---|\n| verworfen | Fehler erster Art, Wahrscheinlichkeit $\\alpha$ | richtige Entscheidung, Wahrscheinlichkeit $1-\\beta$ (Power) |\n| nicht verworfen | richtige Entscheidung | Fehler zweiter Art, Wahrscheinlichkeit $\\beta$ |\n\nDer Fehler erster Art ist ein falscher Alarm: ein Effekt wird berichtet, den es\nnicht gibt. Seine Rate legt man selbst fest, sie ist das Signifikanzniveau. Der\nFehler zweiter Art ist ein übersehener Effekt. Seine Rate ergibt sich aus\nEffektgrösse, Streuung, Stichprobenumfang und Niveau, und sie ist bei kleinen\nStichproben regelmässig grösser als 50 Prozent. Wer das Niveau senkt, um falsche\nAlarme zu vermeiden, erhöht damit direkt die Rate der übersehenen Effekte. Der\neinzige Weg, beide Fehler gleichzeitig zu senken, ist ein grösserer\nStichprobenumfang, siehe [Power](power-stichprobenumfang.qmd).\n\n### Der p-Wert\n\nDer p-Wert ist die Wahrscheinlichkeit, unter der Nullhypothese ein mindestens so\nextremes Ergebnis zu beobachten wie das vorliegende. Er ist damit eine Aussage\nüber die Daten unter einer Annahme, nicht über die Annahme. Die beiden\nRichtungen der Bedingung sind nicht austauschbar: \"die Daten sind unter der\nNullhypothese unwahrscheinlich\" ist nicht dasselbe wie \"die Nullhypothese ist\nunwahrscheinlich\".\n\nWie gross ein p-Wert wird, hängt an drei Dingen gleichzeitig: an der\nEffektgrösse, an der Streuung und am Stichprobenumfang. Derselbe Effekt kann bei\nkleinem n weit von der Schwelle entfernt bleiben und bei grossem n deutlich\ndarunter liegen. Deshalb ist ein p-Wert allein niemals eine Aussage über die\nBedeutung eines Ergebnisses.\n\n### Was der Test nicht liefert, das Intervall aber schon\n\nEin Test liefert eine Ja-Nein-Entscheidung. Ein\n[Konfidenzintervall](schaetzen-konfidenzintervalle.qmd) liefert den Bereich der\nEffektgrössen, die mit den Daten vereinbar sind, und enthält die\nTestentscheidung als Nebenprodukt: schliesst das 95-Prozent-Intervall den Wert\nder Nullhypothese ein, ist der zweiseitige Test auf dem 5-Prozent-Niveau nicht\nsignifikant.\n\nDas Intervall sagt zusätzlich, ob ein nicht signifikantes Ergebnis \"kein\nnennenswerter Effekt vorhanden\" oder \"nichts erkennbar, weil die Stichprobe zu\nklein ist\" bedeutet. **Diese beiden Fälle sehen im p-Wert identisch aus**, und\nBeispiel 4 zeigt, wie weit sie inhaltlich auseinanderliegen.\n\n::: {.callout-note collapse=\"true\"}\n## Warum die Power vor der Datenerhebung gerechnet wird\n\nNach der Erhebung ist der Stichprobenumfang festgelegt, und eine niedrige Power\nlässt sich nicht mehr reparieren. Eine im Nachhinein aus dem beobachteten Effekt\ngerechnete Power ist zudem keine unabhängige Information, sondern eine\nUmrechnung des p-Werts. Nützlich ist die Rechnung nur vorher, mit einer aus der\nSache begründeten Mindesteffektgrösse. Ausführlich steht das auf der Seite zu\n[Power und Stichprobenumfang](power-stichprobenumfang.qmd), Beispiel 3.\n:::\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Ein Test von Hand\n\n#### Frage und Datenlage\n\nEin Sollwert von 500 Gramm, zwölf gemessene Packungen. Statt einen fertigen\nTestaufruf zu verwenden, wird hier jeder Schritt einzeln gerechnet. Danach sieht\nman, was `t.test()` tut.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngewicht <- c(497.2, 501.8, 496.5, 499.1, 495.8, 500.4,\n             494.9, 498.6, 496.1, 499.8, 495.2, 497.7)\nsollwert <- 500\n\n# Schritt 3: Teststatistik\nn <- length(gewicht)\ndifferenz <- mean(gewicht) - sollwert\nstandardfehler <- sd(gewicht) / sqrt(n)\nt_wert <- differenz / standardfehler\n\n# Schritt 4: Verteilung unter der Nullhypothese heranziehen\np_wert <- 2 * pt(-abs(t_wert), df = n - 1)\nkritisch <- qt(0.975, df = n - 1)\n\nround(c(mittel = mean(gewicht), differenz = differenz,\n        standardfehler = standardfehler, t = t_wert,\n        df = n - 1, kritischer_wert = kritisch, p = p_wert), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         mittel       differenz  standardfehler               t              df \n       497.7583         -2.2417          0.6348         -3.5314         11.0000 \nkritischer_wert               p \n         2.2010          0.0047 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Zum Vergleich der fertige Aufruf\nt.test(gewicht, mu = sollwert)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  gewicht\nt = -3.5314, df = 11, p-value = 0.004703\nalternative hypothesis: true mean is not equal to 500\n95 percent confidence interval:\n 496.3612 499.1555\nsample estimates:\nmean of x \n 497.7583 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ngewicht = np.array([497.2, 501.8, 496.5, 499.1, 495.8, 500.4,\n                    494.9, 498.6, 496.1, 499.8, 495.2, 497.7])\nsollwert = 500\n\nn = len(gewicht)\ndifferenz = gewicht.mean() - sollwert\nstandardfehler = gewicht.std(ddof=1) / np.sqrt(n)\nt_wert = differenz / standardfehler\np_wert = 2 * stats.t.cdf(-abs(t_wert), df=n - 1)\nkritisch = stats.t.ppf(0.975, df=n - 1)\n\nprint(f\"Mittel = {gewicht.mean():.4f}  Differenz = {differenz:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMittel = 497.7583  Differenz = -2.2417\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Standardfehler = {standardfehler:.4f}  t = {t_wert:.4f}  df = {n-1}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStandardfehler = 0.6348  t = -3.5314  df = 11\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"kritischer Wert = {kritisch:.4f}  p = {p_wert:.6f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nkritischer Wert = 2.2010  p = 0.004703\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(stats.ttest_1samp(gewicht, sollwert))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTtestResult(statistic=np.float64(-3.5313958840261623), pvalue=np.float64(0.004703285771418092), df=np.int64(11))\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Schritt | Grösse | Wert hier | Was er bedeutet |\n|---|---|---|---|\n| 1 | Nullhypothese | Erwartungswert = 500 g | Sie nennt einen einzigen Wert; nur deshalb lässt sich unter ihr rechnen. |\n| 2 | Niveau | 0.05 zweiseitig | Vorab festgelegt, nicht nach dem Blick auf die Daten. |\n| 3 | Mittelwert | 497.7583 | |\n| 3 | Differenz | -2.2417 g | Die Effektgrösse in der Einheit der Sache. |\n| 3 | Standardfehler | 0.6348 | Wie stark der Mittelwert von Stichprobe zu Stichprobe schwankt. |\n| 3 | **t** | **-3.5314** | Die Differenz, gemessen in Standardfehlern. Das ist der ganze Trick: Eine Abweichung wird an ihrer eigenen Zufallsschwankung gemessen. |\n| 4 | Freiheitsgrade | 11 | n minus eins. |\n| 4 | kritischer Wert | 2.2010 | Ab diesem Betrag wird verworfen. Bei 11 Freiheitsgraden liegt er deutlich über den 1.96 der Normalverteilung. |\n| 4 | **p** | **0.0047** | Die Fläche der t-Verteilung jenseits von ±3.5314. |\n| 5 | Entscheidung | verwerfen | Der Betrag von t übersteigt den kritischen Wert, gleichbedeutend damit, dass p unter 0.05 liegt. |\n\nDie beiden letzten Zeilen sind zwei Formulierungen derselben Entscheidung. Der\nkritische Wert war vor dem Computer üblich, weil man ihn aus einer Tabelle\nablas; der p-Wert enthält dieselbe Information feiner aufgelöst.\n\n#### Interpretation und Ergebnissatz\n\nBeachtenswert ist, was der p-Wert von 0.0047 **nicht** sagt: nicht, dass die\nNullhypothese mit 99.5-prozentiger Wahrscheinlichkeit falsch ist, und nicht,\ndass der Effekt gross ist. Er sagt nur, dass Daten wie diese unter einem wahren\nMittelwert von 500 g selten wären.\n\nWas der Effekt taugt, steht in der Differenz von -2.24 g und ihrem Intervall.\n\n> Das mittlere Füllgewicht unterschreitet den Sollwert von 500 g (M = 497.76 g,\n> SD = 2.20, n = 12): Differenz -2.24 g, t(11) = -3.53, p = 0.005.\n\n### Beispiel 2: p-Werte, wenn nichts da ist\n\n#### Frage und Datenlage\n\nWenn die Nullhypothese stimmt, gibt es nichts zu finden. Trotzdem liefert jeder\nTest einen p-Wert. Wie sind diese p-Werte verteilt?\n\nSimuliert werden 2000 Vergleiche zweier Gruppen zu je 30 Werten aus **derselben**\nVerteilung. Ein Unterschied besteht also konstruktionsbedingt nicht.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nB <- 2000\nn_gruppe <- 30\n\nwerte <- normalwerte(2026, B * 2 * n_gruppe, mittel = 100, streuung = 15)\nalle <- matrix(werte, nrow = B, ncol = 2 * n_gruppe, byrow = TRUE)\n\np_werte <- apply(alle, 1, function(zeile) {\n  t.test(zeile[1:n_gruppe], zeile[(n_gruppe + 1):(2 * n_gruppe)],\n         var.equal = TRUE)$p.value\n})\n\npar(mar = c(4, 4, 3, 1))\nhist(p_werte, breaks = seq(0, 1, by = 0.05), col = \"steelblue\",\n     border = \"white\", main = \"Verteilung der p-Werte unter der Nullhypothese\",\n     xlab = \"p-Wert\", ylab = \"Anzahl Tests\")\nabline(v = 0.05, lty = 2, lwd = 2)\nabline(h = B / 20, lty = 3)\n\nround(c(anteil_unter_0.10 = mean(p_werte < 0.10),\n        anteil_unter_0.05 = mean(p_werte < 0.05),\n        anteil_unter_0.01 = mean(p_werte < 0.01),\n        median = median(p_werte)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nanteil_unter_0.10 anteil_unter_0.05 anteil_unter_0.01            median \n           0.1120            0.0545            0.0085            0.4946 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 2: 2000 p-Werte aus Daten ohne echten Unterschied.](hypothesentests-grundlagen_files/figure-html/fig-b2-ht-r-1.png){#fig-b2-ht-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nB, n_gruppe = 2000, 30\n\nwerte = normalwerte(2026, B * 2 * n_gruppe, mittel=100, streuung=15)\nalle = werte.reshape(B, 2 * n_gruppe)\np_werte = stats.ttest_ind(alle[:, :n_gruppe], alle[:, n_gruppe:], axis=1).pvalue\n\nfig, achse = plt.subplots(figsize=(7, 3.4))\nachse.hist(p_werte, bins=np.arange(0, 1.01, 0.05),\n           color=\"steelblue\", edgecolor=\"white\")\nachse.axvline(0.05, linestyle=\"--\", linewidth=2, color=\"black\")\nachse.axhline(B / 20, linestyle=\":\", color=\"black\")\nachse.set_title(\"Verteilung der p-Werte unter der Nullhypothese\")\nachse.set_xlabel(\"p-Wert\")\nachse.set_ylabel(\"Anzahl Tests\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselbe Simulation in Python.](hypothesentests-grundlagen_files/figure-html/fig-b2-ht-py-1.png){#fig-b2-ht-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(\"Anteil unter 0.10:\", round(float((p_werte < 0.10).mean()), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnteil unter 0.10: 0.112\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Anteil unter 0.05:\", round(float((p_werte < 0.05).mean()), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnteil unter 0.05: 0.0545\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Anteil unter 0.01:\", round(float((p_werte < 0.01).mean()), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnteil unter 0.01: 0.0085\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Median:\", round(float(np.median(p_werte)), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian: 0.4946\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Erwartet | Wie er zu lesen ist |\n|---|---|---|---|\n| Anteil unter 0.10 | 0.1120 | 0.10 | |\n| Anteil unter 0.05 | **0.0545** | 0.05 | Von 2000 Tests ohne jeden echten Unterschied sind 109 signifikant. Das ist kein Fehler des Verfahrens, sondern seine Zusage. |\n| Anteil unter 0.01 | 0.0085 | 0.01 | |\n| Median | 0.4946 | 0.50 | |\n| Histogramm | rund 100 Tests je Klasse | 100 | Flach. Unter der Nullhypothese ist der p-Wert **gleichverteilt** zwischen 0 und 1. |\n\nDie Gleichverteilung ist der Kern. Sie bedeutet: Ein p-Wert von 0.03 ist unter\nder Nullhypothese genauso wahrscheinlich wie einer von 0.83. Nichts an einem\neinzelnen kleinen p-Wert beweist, dass etwas vorliegt.\n\n::: {.note-box}\n**Daraus folgt unmittelbar das Problem des mehrfachen Testens.** Wer zwanzig\nFragen an denselben Datensatz stellt, erhält im Mittel einen signifikanten\nBefund, auch wenn keiner existiert. Genau das rechnet die Seite zum\n[multiplen Testen](multiples-testen.qmd) durch.\n\nUnd es erklärt, warum das Niveau eine **Rate** ist und keine Eigenschaft des\neinzelnen Ergebnisses: Es begrenzt, wie oft man sich auf lange Sicht irrt, nicht\nob man sich diesmal geirrt hat.\n:::\n\n#### Interpretation\n\nDie 109 signifikanten Ergebnisse dieser Simulation sind ununterscheidbar von\nechten Befunden. Sie haben kleine p-Werte, ordentliche t-Werte und\nKonfidenzintervalle, die die Null nicht enthalten. Nur weil hier die Wahrheit\nbekannt ist, weiss man, dass sie falsch sind.\n\nIn der Praxis schützt davor nur eines: die Fragestellung vorab festzulegen und\nBefunde aus einer ungeplanten Suche als vorläufig zu kennzeichnen.\n\n### Beispiel 3: Test und Intervall sagen dasselbe\n\n#### Frage und Datenlage\n\nDie Behauptung \"schliesst das 95-Prozent-Intervall den Wert der Nullhypothese\nein, ist der Test auf dem 5-Prozent-Niveau nicht signifikant\" lässt sich\nnachrechnen. Dazu wird derselbe Datensatz gegen verschiedene Sollwerte getestet.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nintervall <- t.test(gewicht)$conf.int\nround(as.numeric(intervall), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 496.3612 499.1555\n```\n\n\n:::\n\n```{.r .cell-code}\nsollwerte <- c(495, 496, 496.3612, 497.7583, 499.1555, 499.2, 501)\nvergleich <- data.frame(\n  sollwert = sollwerte,\n  p = sapply(sollwerte, function(mu) t.test(gewicht, mu = mu)$p.value)\n)\nvergleich$signifikant <- vergleich$p < 0.05\nvergleich$im_intervall <- vergleich$sollwert >= intervall[1] &\n                          vergleich$sollwert <= intervall[2]\nround_df <- vergleich\nround_df$p <- round(round_df$p, 4)\nround_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  sollwert      p signifikant im_intervall\n1 495.0000 0.0012        TRUE        FALSE\n2 496.0000 0.0182        TRUE        FALSE\n3 496.3612 0.0500       FALSE         TRUE\n4 497.7583 1.0000       FALSE         TRUE\n5 499.1555 0.0500        TRUE        FALSE\n6 499.2000 0.0442        TRUE        FALSE\n7 501.0000 0.0003        TRUE        FALSE\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nse = gewicht.std(ddof=1) / np.sqrt(len(gewicht))\nhalb = stats.t.ppf(0.975, len(gewicht) - 1) * se\nintervall = (gewicht.mean() - halb, gewicht.mean() + halb)\nprint(\"Intervall:\", np.round(intervall, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIntervall: [496.3612 499.1555]\n```\n\n\n:::\n\n```{.python .cell-code}\nsollwerte = np.array([495, 496, 496.3612, 497.7583, 499.1555, 499.2, 501])\np = np.array([stats.ttest_1samp(gewicht, mu).pvalue for mu in sollwerte])\n\nprint(pd.DataFrame({\n    \"sollwert\": sollwerte,\n    \"p\": p.round(4),\n    \"signifikant\": p < 0.05,\n    \"im_intervall\": (sollwerte >= intervall[0]) & (sollwerte <= intervall[1]),\n}).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n sollwert      p  signifikant  im_intervall\n 495.0000 0.0012         True         False\n 496.0000 0.0182         True         False\n 496.3612 0.0500        False          True\n 497.7583 1.0000        False          True\n 499.1555 0.0500         True         False\n 499.2000 0.0442         True         False\n 501.0000 0.0003         True         False\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nDas 95-Prozent-Intervall lautet 496.3612 bis 499.1555.\n\n| Sollwert | p | signifikant | im Intervall |\n|---|---|---|---|\n| 495.00 | 0.0011 | ja | nein |\n| 496.00 | 0.0182 | ja | nein |\n| **496.3612** | **0.0500** | nein | ja |\n| 497.7583 | 1.0000 | nein | ja |\n| **499.1555** | **0.0500** | ja | nein |\n| 499.2000 | 0.0442 | ja | nein |\n| 501.0000 | 0.0003 | ja | nein |\n\nDie beiden Spalten rechts sind **immer** gegenläufig, und zwar exakt. Die\nIntervallgrenzen sind genau die Sollwerte, bei denen der p-Wert 0.05 beträgt.\n\nDie beiden fett gesetzten Zeilen zeigen das an der Grenze: Beide haben einen\np-Wert von 0.0500, entscheiden sich aber verschieden. Das ist kein Widerspruch,\nsondern eine Folge der Rundung — die Sollwerte wurden auf vier Stellen gekürzt\nund liegen damit minimal innerhalb beziehungsweise ausserhalb der exakten\nGrenze. Genau an der Grenze ist die Entscheidung willkürlich, und das ist ein\nArgument gegen die Schwelle als solche.\nBeim Sollwert 497.7583, dem Stichprobenmittelwert, ist p genau 1: Die Daten sind\nmit dieser Annahme so gut vereinbar, wie es überhaupt geht.\n\n::: {.note-box}\n**Das Konfidenzintervall ist die Menge aller nicht verworfenen Nullhypothesen.**\nDiese Sichtweise ist der kürzeste Weg zum Verständnis beider Begriffe: Ein\nIntervall ist kein zusätzliches Werkzeug neben dem Test, sondern der Test,\nangewendet auf alle denkbaren Sollwerte gleichzeitig.\n\nPraktisch heisst das, dass der p-Wert Information wegwirft. Er sagt \"verworfen\"\noder \"nicht verworfen\" für **einen** Wert; das Intervall sagt es für alle.\n:::\n\n#### Interpretation\n\nWer das Intervall berichtet, hat den Test damit mitberichtet, aber nicht\numgekehrt. Das ist der Grund für die Empfehlung, in erster Linie Schätzwerte mit\nIntervallen zu berichten und den p-Wert als Beigabe.\n\n### Beispiel 4: Zwei Studien, zwei Fallen\n\n#### Frage und Datenlage\n\nZwei Untersuchungen zum selben Sachverhalt, mit fast identischen p-Werten:\n\n| | n je Gruppe | beobachtetes $d$ | p |\n|---|---|---|---|\n| Studie A | 40 | 0.44 | 0.053 |\n| Studie B | 4000 | 0.045 | 0.044 |\n\nNach der üblichen Lesart ist A \"nicht signifikant\" und B \"signifikant\". Was sagen\ndie Daten wirklich?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudie <- function(n, d) {\n  se_d <- sqrt(2 / n)\n  t_wert <- d / se_d\n  p <- 2 * pt(-abs(t_wert), df = 2 * n - 2)\n  se_ki <- sqrt(2 / n + d^2 / (4 * n))\n  c(n = n, d = d, t = t_wert, p = p,\n    unten = d - 1.96 * se_ki, oben = d + 1.96 * se_ki)\n}\n\nround(rbind(A = studie(40, 0.44), B = studie(4000, 0.045)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     n     d      t      p   unten   oben\nA   40 0.440 1.9677 0.0527 -0.0035 0.8835\nB 4000 0.045 2.0125 0.0442  0.0012 0.0888\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndef studie(n, d):\n    se_d = np.sqrt(2 / n)\n    t_wert = d / se_d\n    p = 2 * stats.t.cdf(-abs(t_wert), df=2 * n - 2)\n    se_ki = np.sqrt(2 / n + d ** 2 / (4 * n))\n    return {\"n\": n, \"d\": d, \"t\": t_wert, \"p\": p,\n            \"unten\": d - 1.96 * se_ki, \"oben\": d + 1.96 * se_ki}\n\n\nprint(pd.DataFrame([studie(40, 0.44), studie(4000, 0.045)],\n                   index=[\"A\", \"B\"]).round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      n      d       t       p   unten    oben\nA    40  0.440  1.9677  0.0527 -0.0035  0.8835\nB  4000  0.045  2.0125  0.0442  0.0012  0.0888\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| | n | $d$ | t | p | Intervall für $d$ |\n|---|---|---|---|---|---|\n| A | 40 | 0.440 | 1.968 | 0.0527 | **-0.004 bis 0.884** |\n| B | 4000 | 0.045 | 2.013 | 0.0442 | **0.001 bis 0.089** |\n\nDie p-Werte liegen fünf Tausendstel auseinander, auf verschiedenen Seiten der\nSchwelle. Die Intervalle sagen etwas völlig anderes:\n\n**Studie A ist unentschieden.** Ihr Intervall reicht von praktisch null bis zu\neinem sehr grossen Effekt von 0.88. Ausgeschlossen ist so gut wie nichts. Der\nSatz \"kein Effekt nachweisbar\" ist richtig, der Satz \"kein Effekt vorhanden\"\nwäre grob falsch.\n\n**Studie B belegt einen sehr kleinen Effekt.** Ihr Intervall reicht von 0.001 bis\n0.089 und schliesst damit alles über 0.09 aus. Ein Effekt liegt vor, und er ist\nmit Sicherheit winzig.\n\nWer nur die p-Werte liest, kommt zum genau umgekehrten Eindruck: A sieht nach\n\"nichts gefunden\" aus und B nach \"Effekt bestätigt\".\n\n#### Interpretation und Ergebnissatz\n\nDie beiden Fallen dieses Beispiels sind die häufigsten überhaupt:\n\n| Falle | Was fehlt |\n|---|---|\n| \"Nicht signifikant heisst kein Effekt\" | das Intervall, das zeigt, wie viel noch möglich ist |\n| \"Signifikant heisst bedeutsam\" | die Effektstärke, die zeigt, wie wenig es ist |\n\nBeide verschwinden, sobald Intervall und Effektstärke mitberichtet werden. Genau\ndeshalb steht in der Ergebnisvorlage jeder Methodenseite dieser Sammlung nicht\nnur der p-Wert.\n\n> Studie A findet keinen nachweisbaren Unterschied ($d$ = 0.44,\n> 95-Prozent-Konfidenzintervall -0.00 bis 0.88, p = 0.053, n = 40 je Gruppe);\n> das Intervall lässt Effekte bis in den grossen Bereich zu, ein Ausschluss ist\n> damit nicht erbracht. Studie B findet einen nachweisbaren, aber sehr kleinen\n> Unterschied ($d$ = 0.045, 0.00 bis 0.09, p = 0.044, n = 4000 je Gruppe).\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEin Test wird mit $\\alpha$ = 0.01 statt 0.05 gerechnet. Was passiert?\n\n- [x] Falsche Alarme werden seltener, übersehene Effekte häufiger ~ Richtig. Die\n      Schwelle rückt nach aussen, also wird die Nullhypothese seltener verworfen,\n      unabhängig davon, ob sie stimmt. Der Preis für weniger Fehler erster Art\n      sind mehr Fehler zweiter Art.\n- [ ] Beide Fehlerarten werden seltener ~ Das geht bei gleichem\n      Stichprobenumfang nicht, die beiden Raten bewegen sich gegenläufig.\n- [ ] Das Ergebnis wird zuverlässiger, weil der Effekt grösser sein muss ~ Der\n      wahre Effekt ändert sich nicht. Nur die Schwelle ändert sich, ab der man\n      ihn berichtet.\n:::\n\n::: {.quiz}\nEin Test ergibt p = 0.42. Was darf man schliessen?\n\n- [ ] Dass die Gruppen gleich sind ~ Ein fehlender Nachweis ist kein Nachweis der\n      Gleichheit. Möglicherweise ist die Stichprobe zu klein.\n- [x] Nur, dass die Daten mit der Nullhypothese vereinbar sind ~ Richtig. Wie\n      grosse Effekte die Daten noch zulassen, zeigt allein das\n      Konfidenzintervall, und das gehört deshalb immer mitberichtet.\n- [ ] Dass die Nullhypothese mit 58 Prozent Wahrscheinlichkeit falsch ist ~ Der\n      p-Wert ist keine Wahrscheinlichkeit für eine Hypothese, in keiner\n      Rechenrichtung.\n:::\n\n::: {.quiz}\nZwei Untersuchungen betrachten denselben Effekt. A: n = 40, p = 0.053,\nKonfidenzintervall des standardisierten Unterschieds -0.00 bis 0.88. B:\nn = 4000, p = 0.044, Intervall 0.00 bis 0.09. Was ist die richtige Lesart?\n\n- [ ] B zeigt den stärkeren Effekt, weil p kleiner ist ~ Der p-Wert vergleicht\n      keine Effektgrössen. B hat vor allem mehr Beobachtungen.\n- [x] A lässt auch grosse Effekte zu, B belegt einen kleinen ~ Richtig. In A ist\n      das Intervall breit, es ist kaum etwas ausgeschlossen. In B ist es eng und\n      liegt knapp über null: Der Effekt ist gesichert, aber winzig.\n- [ ] A ist wertlos, weil nicht signifikant ~ A ist unentschieden, und das ist\n      ein Ergebnis. Wertlos wäre die Aussage nur, wenn man das Intervall\n      verschweigt.\n:::\n\n::: {.quiz}\nVon 2000 Tests auf Daten ohne jeden Unterschied sind 109 signifikant. Was folgt\ndaraus?\n\n- [x] Nichts Ungewöhnliches; das entspricht dem Niveau von 5 Prozent ~ Richtig.\n      Unter der Nullhypothese ist der p-Wert gleichverteilt, also fallen rund\n      5 Prozent unter die Schwelle. Das Niveau begrenzt diese Rate, es schliesst\n      falsche Alarme nicht aus.\n- [ ] Die Simulation ist fehlerhaft ~ 109 von 2000 sind 5.45 Prozent, also genau\n      im erwarteten Bereich.\n- [ ] Der t-Test ist unzuverlässig ~ Er hält sein Versprechen exakt ein. Das\n      Versprechen lautet nur nicht, was viele darin lesen.\n:::\n\n## Verlinkte Ressourcen\n\n- [OpenIntro Statistics, Kapitel zur Inferenz](https://www.openintro.org/book/os/)\n- [Statement der American Statistical Association zum p-Wert](https://www.tandfonline.com/doi/full/10.1080/00031305.2016.1154108)\n- [Schätzen und Konfidenzintervalle](schaetzen-konfidenzintervalle.qmd)\n",
    "supporting": [
      "hypothesentests-grundlagen_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}