{
  "hash": "fb78dcab8ac5db1a944074ef37f8d290",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"ggplot2\"\ndescription: \"Grammatik der Grafik, Ebenen, Skalen und Facetten in R.\"\ncategories: [\"ggplot2\", \"Visualisierung\", \"R\", \"Python\"]\nquelle: [\"ESDS\"]\nseitentyp: werkzeug\nstand: fertig\norder: 40\n---\n\n\n\n\n\n## Kernideen\n\n- **Grammatik statt Diagrammtypen:** Daten, Aesthetics, Geome, Skalen,\n  Facetten — frei kombinierbar.\n- Eine Angabe **innerhalb** von `aes()` wird aus den Daten abgeleitet,\n  **ausserhalb** ist sie ein fester Wert. Das ist der häufigste Anfängerfehler.\n- Geome folgen der Fragestellung und dem Skalenniveau, nicht dem Geschmack.\n- **Facetten statt Farbe**, sobald mehr als drei oder vier Gruppen im Spiel\n  sind — und mit gemeinsamen Achsen, sonst sind die Teilbilder nicht\n  vergleichbar.\n- Die Skala ist Teil der Aussage, nicht ein Darstellungsdetail.\n- Beschriftung ist kein Nachtrag.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Data Wrangling](../daten/data-wrangling.qmd), weil ggplot2 einen\naufgeräumten Data Frame im langen Format erwartet, und\n[Skalenniveaus](../statistik/grundlagen/skalenniveaus.qmd), weil das Messniveau\nbestimmt, welche Darstellung überhaupt zulässig ist. Die Wahl selbst steht\nunter [Diagrammtyp wählen](diagrammtyp-waehlen.qmd).\n:::\n\n### Warum nicht einfach ein Diagrammtyp\n\nÜbliche Programme bieten eine Liste von Diagrammtypen an: Balken, Linie, Kreis,\nStreuung. Wer etwas will, das nicht in der Liste steht, hat Pech. Und wer zwei\nTypen kombinieren will, etwa Punkte mit einer Ausgleichsgeraden, kämpft gegen\ndas Werkzeug.\n\nggplot2 folgt einem anderen Gedanken. Eine Grafik entsteht aus Bausteinen, die\nsich frei kombinieren lassen. Ein Diagrammtyp ist dann nur eine bestimmte\nKombination und kein eigener Befehl. Der Preis dafür ist, dass man die\nBausteine kennen muss; der Gewinn ist, dass Sonderfälle aufhören, Sonderfälle\nzu sein.\n\nDrei Bausteine genügen für den Anfang:\n\n| Baustein | Was er festlegt |\n|---|---|\n| Daten | Woher die Zahlen kommen |\n| Aesthetics, `aes()` | Welche Variable auf welche visuelle Eigenschaft abgebildet wird |\n| Geom | Mit welchen Objekten gezeichnet wird |\n\nDazu kommen Skalen, Facetten, Statistiken und das Theme. Der Aufbau ist immer\nderselbe:\n\n```r\nggplot(daten, aes(x, y)) +      # Daten und Zuordnung\n  geom_point() +                # womit gezeichnet wird\n  scale_y_continuous(...) +     # wie Werte in Positionen übersetzt werden\n  facet_wrap(~ gruppe) +        # Aufteilung in Teilbilder\n  labs(title = \"…\") +           # Beschriftung\n  theme_minimal()               # Aussehen\n```\n\n### Geome nach Fragestellung\n\nWelches Geom passt, hängt daran, was gezeigt werden soll und welches\n[Skalenniveau](../statistik/grundlagen/skalenniveaus.qmd) die Merkmale haben.\n\n| Frage | Geom | Merkmale |\n|---|---|---|\n| Wie ist ein Merkmal verteilt? | `geom_histogram`, `geom_density` | ein metrisches |\n| Wie hängen zwei Merkmale zusammen? | `geom_point` | zwei metrische |\n| Wie unterscheiden sich Gruppen? | `geom_boxplot`, `geom_violin` | ein metrisches, ein kategoriales |\n| Wie häufig ist eine Kategorie? | `geom_bar`, `geom_col` | ein kategoriales |\n| Wie verläuft etwas über die Zeit? | `geom_line` | Zeit und ein metrisches |\n\n`geom_bar` zählt selbst, `geom_col` nimmt fertige Werte — das ist die\nVerwechslung, die am häufigsten zu einer leeren Grafik führt.\n\n### Der Datensatz dieser Seite\n\n180 Maschinen mit Laufzeit in Stunden, Typ, Standort und Stromverbrauch. Der\nVerbrauch hängt konstruktionsgemäss von der Laufzeit ab, und Pressen brauchen\nzusätzlich 14 Einheiten. Die Daten sind deterministisch erzeugt, damit die\nR- und die Python-Fassung **dieselben** 180 Maschinen zeigen.\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Der Aufbau in drei Schritten\n\n#### Frage und Datenlage\n\nWas trägt jeder Baustein bei? Dazu wird die Grafik in drei Schritten gebaut:\nerst nur die Daten, dann die Zuordnung, dann das Geom.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(maschinen)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t180 obs. of  4 variables:\n $ laufzeit : num  2.7 7.6 22 13.3 13.5 18.3 21.1 17.7 2.3 11 ...\n $ typ      : Factor w/ 3 levels \"Drehbank\",\"Fräse\",..: 2 2 2 2 2 2 2 2 2 2 ...\n $ standort : chr  \"Bern\" \"Bern\" \"Bern\" \"Bern\" ...\n $ verbrauch: num  25.1 27.4 65.5 43.2 49.6 50.2 60.6 61.8 15.5 35 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(laufzeit_min = min(maschinen$laufzeit),\n        laufzeit_max = max(maschinen$laufzeit),\n        verbrauch_min = min(maschinen$verbrauch),\n        verbrauch_max = max(maschinen$verbrauch),\n        korrelation = cor(maschinen$laufzeit, maschinen$verbrauch)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n laufzeit_min  laufzeit_max verbrauch_min verbrauch_max   korrelation \n        2.000        22.000         6.100        78.100         0.852 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(maschinen, aes(x = laufzeit, y = verbrauch))\n```\n\n::: {.cell-output-display}\n![Schritt 1: nur Daten und Zuordnung. Die Achsen stehen, gezeichnet ist nichts.](ggplot2_files/figure-html/fig-b1a-gg-r-1.png){#fig-b1a-gg-r width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(maschinen, aes(x = laufzeit, y = verbrauch)) +\n  geom_point(alpha = 0.5)\n```\n\n::: {.cell-output-display}\n![Schritt 2: ein Geom kommt dazu.](ggplot2_files/figure-html/fig-b1b-gg-r-1.png){#fig-b1b-gg-r width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(maschinen, aes(x = laufzeit, y = verbrauch)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"lm\", formula = y ~ x, se = FALSE, colour = \"#b2182b\")\n```\n\n::: {.cell-output-display}\n![Schritt 3: eine zweite Ebene darüber.](ggplot2_files/figure-html/fig-b1c-gg-r-1.png){#fig-b1c-gg-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(maschinen.dtypes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlaufzeit     float64\ntyp           object\nstandort      object\nverbrauch    float64\ndtype: object\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"laufzeit_min\": round(float(maschinen[\"laufzeit\"].min()), 3),\n       \"laufzeit_max\": round(float(maschinen[\"laufzeit\"].max()), 3),\n       \"verbrauch_min\": round(float(maschinen[\"verbrauch\"].min()), 3),\n       \"verbrauch_max\": round(float(maschinen[\"verbrauch\"].max()), 3),\n       \"korrelation\": round(float(maschinen[\"laufzeit\"].corr(maschinen[\"verbrauch\"])), 3)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'laufzeit_min': 2.0, 'laufzeit_max': 22.0, 'verbrauch_min': 6.1, 'verbrauch_max': 78.1, 'korrelation': 0.852}\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, achse = plt.subplots(figsize=(7, 2.8))\n_ = achse.scatter(maschinen[\"laufzeit\"], maschinen[\"verbrauch\"], s=14, alpha=0.5,\n                  color=\"0.3\")\nk, d = np.polyfit(maschinen[\"laufzeit\"], maschinen[\"verbrauch\"], 1)\ngitter = np.linspace(maschinen[\"laufzeit\"].min(), maschinen[\"laufzeit\"].max(), 2)\n_ = achse.plot(gitter, k * gitter + d, lw=2, color=\"#b2182b\")\n_ = achse.set_xlabel(\"laufzeit\")\n_ = achse.set_ylabel(\"verbrauch\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Dieselben drei Schritte in matplotlib — hier gibt es keine leere Zwischenstufe.](ggplot2_files/figure-html/fig-b1-gg-py-1.png){#fig-b1-gg-py width=100%}\n:::\n\n```{.python .cell-code}\nprint({\"steigung\": round(float(k), 3), \"achsenabschnitt\": round(float(d), 2)})\n```\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | Wert |\n|---|---|\n| Beobachtungen | 180 |\n| Laufzeit | **2.0 bis 22.0** Stunden |\n| Verbrauch | **6.1 bis 78.1** |\n| Korrelation Laufzeit / Verbrauch | **0.852** |\n| Ausgleichsgerade | Steigung **2.358**, Achsenabschnitt **13.35** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Der erste Aufruf zeichnet **nichts** | Nur die Achsen. Daten und Zuordnung stehen fest, aber ohne Geom gibt es keine Objekte. Das ist kein Fehler, sondern die Grammatik: **Zuordnung und Darstellung sind getrennt.** |\n| Erst `geom_point()` bringt Punkte | Dieselbe Zuordnung könnte mit `geom_line()` Linien ergeben oder mit `geom_hex()` Sechsecke — ohne dass sich an `aes()` etwas ändert. |\n| Die zweite Ebene liegt **darüber** | `geom_smooth()` wird addiert, nicht ersetzt. Die Reihenfolge im Code ist die Reihenfolge im Bild. |\n| Die geschätzte Steigung beträgt **2.358** | Konstruiert waren 2.4. Die Abweichung kommt daher, dass die Pressen ihre zusätzlichen 14 Einheiten unabhängig von der Laufzeit haben und die Gerade das ausgleicht. |\n| In matplotlib gibt es die leere Zwischenstufe **nicht** | Dort erzeugt `plt.subplots()` die Achsen und jeder Zeichenbefehl fügt direkt Objekte hinzu. Der Unterschied ist nicht kosmetisch: In ggplot2 ist die Zuordnung ein eigenes Objekt, das wiederverwendet werden kann. |\n\n::: {.note-box}\n**Was daraus folgt, wenn man in ggplot2 denkt:** Die Frage lautet nicht \"welches\nDiagramm\", sondern zweimal getrennt:\n\n1. Welche Variable kommt auf welchen Kanal? (`aes`)\n2. Womit wird gezeichnet? (`geom`)\n\nDiese Trennung ist derselbe Gedanke wie die Kanalrangfolge unter\n[Wahrnehmung und Kodierung](wahrnehmung-kodierung.qmd) — nur als Code.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Der Datensatz umfasst 180 Maschinen mit Laufzeiten von 2.0 bis 22.0 Stunden\n> und Verbrauchswerten von 6.1 bis 78.1; die Korrelation beträgt 0.852. Ohne\n> Geom zeichnet ggplot2 nur die Achsen — Zuordnung und Darstellung sind\n> getrennte Bausteine.\n\n### Beispiel 2: Zuordnen oder festlegen\n\n#### Frage und Datenlage\n\n`colour = \"blue\"` innerhalb und ausserhalb von `aes()` — derselbe Text, zwei\nvöllig verschiedene Ergebnisse. Das ist der häufigste Anfängerfehler.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(maschinen, aes(laufzeit, verbrauch, colour = \"blue\")) +\n  geom_point(alpha = 0.6)\n```\n\n::: {.cell-output-display}\n![Innerhalb von aes(): 'blue' wird als Datenwert behandelt.](ggplot2_files/figure-html/fig-b2a-gg-r-3.png){#fig-b2a-gg-r width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(maschinen, aes(laufzeit, verbrauch)) +\n  geom_point(colour = \"blue\", alpha = 0.6)\n```\n\n::: {.cell-output-display}\n![Ausserhalb von aes(): ein fester Wert für alle Punkte.](ggplot2_files/figure-html/fig-b2b-gg-r-1.png){#fig-b2b-gg-r width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(maschinen, aes(laufzeit, verbrauch, colour = typ)) +\n  geom_point(alpha = 0.6) +\n  scale_colour_manual(values = c(Drehbank = \"#0072B2\", Fräse = \"#009E73\",\n                                 Presse = \"#D55E00\"))\n```\n\n::: {.cell-output-display}\n![Sinnvoll zugeordnet: eine echte Variable auf die Farbe.](ggplot2_files/figure-html/fig-b2c-gg-r-1.png){#fig-b2c-gg-r width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nzusammenfassung <- maschinen |>\n  group_by(typ) |>\n  summarise(anzahl = n(), mittel = mean(verbrauch), sd = sd(verbrauch)) |>\n  as.data.frame()\nzusammenfassung$mittel <- round(zusammenfassung$mittel, 2)\nzusammenfassung$sd <- round(zusammenfassung$sd, 2)\nzusammenfassung\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       typ anzahl mittel    sd\n1 Drehbank     60  37.58 15.35\n2    Fräse     60  38.09 15.23\n3   Presse     60  48.65 13.68\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfarben = {\"Drehbank\": \"#0072B2\", \"Fräse\": \"#009E73\", \"Presse\": \"#D55E00\"}\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 2.8))\n_ = achsen[0].scatter(maschinen[\"laufzeit\"], maschinen[\"verbrauch\"],\n                      s=14, alpha=0.6, color=\"blue\")\n_ = achsen[0].set_title(\"fester Wert: color=\", fontsize=10)\nfor name, teil in maschinen.groupby(\"typ\"):\n    _ = achsen[1].scatter(teil[\"laufzeit\"], teil[\"verbrauch\"], s=14, alpha=0.6,\n                          color=farben[name], label=name)\n_ = achsen[1].legend(fontsize=7, frameon=False)\n_ = achsen[1].set_title(\"zugeordnet: je Gruppe\", fontsize=10)\nfor achse in achsen:\n    _ = achse.set_xlabel(\"laufzeit\")\n    _ = achse.set_ylabel(\"verbrauch\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![In matplotlib ist der Unterschied explizit: c= nimmt Daten, color= einen festen Wert.](ggplot2_files/figure-html/fig-b2-gg-py-1.png){#fig-b2-gg-py width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(maschinen.groupby(\"typ\")[\"verbrauch\"]\n      .agg(anzahl=\"count\", mittel=\"mean\", sd=\"std\").round(2))\n```\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Typ | Anzahl | Mittel | SD |\n|---|---|---|---|\n| Drehbank | 60 | **37.58** | 15.35 |\n| Fräse | 60 | **38.10** | 15.23 |\n| **Presse** | 60 | **48.65** | 13.68 |\n\n| Beobachtung | Erklärung |\n|---|---|\n| `colour = \"blue\"` **innerhalb** von `aes()` ergibt rote Punkte und eine Legende | ggplot2 behandelt `\"blue\"` als **Datenwert**: eine Variable, die für alle 180 Zeilen denselben Wert hat. Sie bekommt eine Skala, und die erste Farbe der Standardpalette ist Rot. |\n| **Ausserhalb** wird es ein fester Wert | Blaue Punkte, keine Legende. Nichts wird aus den Daten abgeleitet. |\n| Die Faustregel steht in einem Satz | **Steht rechts vom `=` ein Spaltenname, gehört es in `aes()`; steht dort ein fester Wert, gehört es nach draussen.** |\n| Sinnvoll zugeordnet zeigt die Farbe den Typ | Und dann trägt sie Information: Die Pressen liegen mit einem Mittel von 48.65 rund 10 Einheiten über den anderen beiden, die mit 37.58 und 38.10 fast gleich sind. |\n| In matplotlib gibt es diesen Fehler **nicht** | Dort sind `color=` (fest) und `c=` (aus Daten) verschiedene Argumente. Dafür muss man dort je Gruppe selbst schleifen — ggplot2 nimmt einem das ab. |\n\n::: {.warning-box}\n**Woran man den Fehler im Bild erkennt:** Es erscheint eine Legende, die man\nnicht bestellt hat, mit genau einem Eintrag, der den Namen der Farbe trägt.\nZweiter Hinweis: Die Farbe ist nicht die, die man geschrieben hat.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Innerhalb von `aes()` wird `colour = \"blue\"` als Datenwert behandelt und\n> erzeugt eine Legende mit einem Eintrag; ausserhalb ist es ein fester Wert.\n> Sinnvoll zugeordnet zeigt die Farbe den Maschinentyp: Pressen verbrauchen im\n> Mittel 48.65 gegenüber 37.58 und 38.10 bei den anderen beiden Typen.\n\n### Beispiel 3: Geome nach Fragestellung\n\n#### Frage und Datenlage\n\nDerselbe Datensatz, vier Fragen, vier Geome. Jedes beantwortet genau eine und\nverbirgt die anderen.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(maschinen, aes(verbrauch)) +\n  geom_histogram(bins = 25, fill = \"grey70\", colour = \"white\") +\n  labs(subtitle = \"Wie ist der Verbrauch verteilt?\")\n\np2 <- ggplot(maschinen, aes(laufzeit, verbrauch)) +\n  geom_point(alpha = 0.4) +\n  labs(subtitle = \"Wie hängen Laufzeit und Verbrauch zusammen?\")\n\np3 <- ggplot(maschinen, aes(typ, verbrauch)) +\n  geom_boxplot(fill = \"grey85\") +\n  labs(subtitle = \"Wie unterscheiden sich die Typen?\")\n\np4 <- ggplot(maschinen, aes(standort)) +\n  geom_bar(fill = \"grey70\") +\n  labs(subtitle = \"Wie viele Maschinen je Standort?\")\n\n# Ohne Zusatzpaket: die vier Grafiken nacheinander\nprint(p1); print(p2); print(p3); print(p4)\n```\n\n::: {.cell-output-display}\n![Beispiel 3: Histogramm, Streudiagramm, Boxplot und Balken.](ggplot2_files/figure-html/fig-b3-gg-r-3.png){#fig-b3-gg-r-1 width=100%}\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: Histogramm, Streudiagramm, Boxplot und Balken.](ggplot2_files/figure-html/fig-b3-gg-r-4.png){#fig-b3-gg-r-2 width=100%}\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: Histogramm, Streudiagramm, Boxplot und Balken.](ggplot2_files/figure-html/fig-b3-gg-r-5.png){#fig-b3-gg-r-3 width=100%}\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: Histogramm, Streudiagramm, Boxplot und Balken.](ggplot2_files/figure-html/fig-b3-gg-r-6.png){#fig-b3-gg-r-4 width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(c(median_verbrauch = median(maschinen$verbrauch),\n        schiefe = mean((maschinen$verbrauch - mean(maschinen$verbrauch))^3) /\n          sd(maschinen$verbrauch)^3), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmedian_verbrauch          schiefe \n          41.650           -0.059 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(maschinen$standort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBern Chur \n  90   90 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(tapply(maschinen$verbrauch, maschinen$typ, median), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDrehbank    Fräse   Presse \n   38.30    38.70    49.85 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(2, 2, figsize=(7, 4.6))\n_ = sns.histplot(maschinen[\"verbrauch\"], bins=25, color=\"0.7\",\n                 ax=achsen[0, 0])\n_ = achsen[0, 0].set_title(\"Wie ist der Verbrauch verteilt?\", fontsize=9)\n_ = sns.scatterplot(data=maschinen, x=\"laufzeit\", y=\"verbrauch\", alpha=0.4,\n                    color=\"0.3\", ax=achsen[0, 1])\n_ = achsen[0, 1].set_title(\"Wie hängen Laufzeit und Verbrauch zusammen?\",\n                           fontsize=9)\n_ = sns.boxplot(data=maschinen, x=\"typ\", y=\"verbrauch\", color=\"0.85\",\n                ax=achsen[1, 0])\n_ = achsen[1, 0].set_title(\"Wie unterscheiden sich die Typen?\", fontsize=9)\n_ = sns.countplot(data=maschinen, x=\"standort\", color=\"0.7\", ax=achsen[1, 1])\n_ = achsen[1, 1].set_title(\"Wie viele Maschinen je Standort?\", fontsize=9)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselben vier Fragen in seaborn.](ggplot2_files/figure-html/fig-b3-gg-py-1.png){#fig-b3-gg-py width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint({\"median_verbrauch\": round(float(maschinen[\"verbrauch\"].median()), 3),\n       \"schiefe\": round(float(stats.skew(maschinen[\"verbrauch\"])), 3)})\nprint(maschinen[\"standort\"].value_counts().sort_index())\nprint(maschinen.groupby(\"typ\")[\"verbrauch\"].median().round(2))\n```\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Kennzahl | Wert |\n|---|---|\n| Median Verbrauch | **41.45** |\n| Schiefe | **0.033** |\n| Maschinen je Standort | Bern **90**, Chur **90** |\n\n| Typ | Median Verbrauch |\n|---|---|\n| Drehbank | **36.45** |\n| Fräse | **37.00** |\n| Presse | **48.55** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Das Histogramm zeigt eine nahezu symmetrische Verteilung | Schiefe 0.033, Median 41.45 bei einem Mittelwert von 41.44. Es ist aber eine **Mischung** aus drei Typen — das Histogramm zeigt nur die Summe. |\n| Das Streudiagramm zeigt den Zusammenhang | Und nicht die Gruppen. Dass die Pressen systematisch höher liegen, ist dort als Verbreiterung der Wolke sichtbar, nicht als Struktur. |\n| Der Boxplot zeigt die Gruppen | Und nicht den Zusammenhang mit der Laufzeit. Mediane 36.45, 37.00 und 48.55. |\n| Der Balken zählt selbst | `geom_bar` braucht kein `y`: 90 und 90. Wer bereits fertige Werte hat, nimmt `geom_col` — die Verwechslung ist die häufigste Ursache für eine unerwartet leere Grafik. |\n| Keines der vier Bilder ist **falsch** | Jedes beantwortet seine Frage und verschweigt die anderen. **Das Geom ist die Frage, nicht die Dekoration.** |\n\n::: {.note-box}\n**Mehrere ggplot-Objekte nebeneinander** brauchen ein Zusatzpaket (`patchwork`,\n`cowplot` oder `gridExtra`). Steht keines zur Verfügung — wie in dieser\nSammlung —, gibt man die Grafiken einfach nacheinander aus. In matplotlib\nlöst `plt.subplots(2, 2)` dasselbe ohne Zusatz.\n\nDas ist einer der wenigen Punkte, an denen matplotlib bequemer ist als ggplot2.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Dieselben 180 Maschinen beantworten vier Fragen mit vier Geomen: eine fast\n> symmetrische Gesamtverteilung (Median 41.45, Schiefe 0.033), einen klaren\n> Zusammenhang mit der Laufzeit, Typunterschiede mit Medianen von 36.45 bis\n> 48.55 und eine gleichmässige Verteilung von 90 zu 90 auf die Standorte.\n\n### Beispiel 4: Facetten statt Farbe\n\n#### Frage und Datenlage\n\nDer Zusammenhang zwischen Laufzeit und Verbrauch, aufgeteilt nach Typ und\nStandort. Einmal über Farbe, einmal über Facetten — und die Frage, welche der\nbeiden die sechs Gruppen lesbar macht.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(maschinen, aes(laufzeit, verbrauch, colour = typ, shape = standort)) +\n  geom_point(alpha = 0.7)\n```\n\n::: {.cell-output-display}\n![Sechs Gruppen über Farbe und Form.](ggplot2_files/figure-html/fig-b4a-gg-r-3.png){#fig-b4a-gg-r width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(maschinen, aes(laufzeit, verbrauch)) +\n  geom_point(alpha = 0.5, size = 1.2) +\n  geom_smooth(method = \"lm\", formula = y ~ x, se = FALSE,\n              colour = \"#b2182b\", linewidth = 0.8) +\n  facet_grid(standort ~ typ) +\n  labs(x = \"Laufzeit in Stunden\", y = \"Verbrauch\")\n```\n\n::: {.cell-output-display}\n![Dieselben sechs Gruppen als Facetten, mit gemeinsamen Achsen.](ggplot2_files/figure-html/fig-b4b-gg-r-1.png){#fig-b4b-gg-r width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsteigungen <- sapply(levels(maschinen$typ), function(tp) {\n  teil <- maschinen[maschinen$typ == tp, ]\n  unname(coef(lm(verbrauch ~ laufzeit, data = teil))[2])\n})\nround(steigungen, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDrehbank    Fräse   Presse \n   2.384    2.457    2.534 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(gesamt = unname(coef(lm(verbrauch ~ laufzeit, data = maschinen))[2])), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngesamt \n 2.358 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(with(maschinen, tapply(verbrauch, list(typ, standort), mean)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Bern  Chur\nDrehbank 37.04 38.13\nFräse    42.83 33.36\nPresse   49.02 48.27\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ngitter = sns.FacetGrid(maschinen, row=\"standort\", col=\"typ\", height=1.5,\n                       aspect=1.5)\n_ = gitter.map_dataframe(sns.regplot, x=\"laufzeit\", y=\"verbrauch\",\n                         scatter_kws={\"s\": 8, \"alpha\": 0.5, \"color\": \"0.3\"},\n                         line_kws={\"color\": \"#b2182b\", \"linewidth\": 1},\n                         ci=None)\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselben Facetten in seaborn.](ggplot2_files/figure-html/fig-b4-gg-py-1.png){#fig-b4-gg-py-1 width=100%}\n:::\n\n```{.python .cell-code}\n_ = gitter.set_axis_labels(\"Laufzeit in Stunden\", \"Verbrauch\")\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselben Facetten in seaborn.](ggplot2_files/figure-html/fig-b4-gg-py-2.png){#fig-b4-gg-py-2 width=100%}\n:::\n\n```{.python .cell-code}\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselben Facetten in seaborn.](ggplot2_files/figure-html/fig-b4-gg-py-3.png){#fig-b4-gg-py-3 width=100%}\n:::\n\n::: {.cell-output-display}\n![Beispiel 4: dieselben Facetten in seaborn.](ggplot2_files/figure-html/fig-b4-gg-py-4.png){#fig-b4-gg-py-4 width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.python .cell-code}\nsteigungen = {tp: round(float(np.polyfit(teil[\"laufzeit\"], teil[\"verbrauch\"], 1)[0]), 3)\n              for tp, teil in maschinen.groupby(\"typ\")}\n```\n\n::: {.cell-output-display}\n![](ggplot2_files/figure-html/b4-gg-zahlen-py-9.png){width=100%}\n:::\n\n```{.python .cell-code}\nprint(steigungen)\n```\n\n::: {.cell-output-display}\n![](ggplot2_files/figure-html/b4-gg-zahlen-py-10.png){width=100%}\n:::\n\n```{.python .cell-code}\nprint({\"gesamt\": round(float(np.polyfit(maschinen[\"laufzeit\"],\n                                        maschinen[\"verbrauch\"], 1)[0]), 3)})\n```\n\n::: {.cell-output-display}\n![](ggplot2_files/figure-html/b4-gg-zahlen-py-11.png){width=100%}\n:::\n\n```{.python .cell-code}\nprint(maschinen.pivot_table(index=\"typ\", columns=\"standort\",\n                            values=\"verbrauch\", aggfunc=\"mean\").round(2))\n```\n\n::: {.cell-output-display}\n![](ggplot2_files/figure-html/b4-gg-zahlen-py-12.png){width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Typ | Steigung je Stunde |\n|---|---|\n| Drehbank | **2.384** |\n| Fräse | **2.457** |\n| Presse | **2.534** |\n| **gesamt** | **2.358** |\n\nMittlerer Verbrauch je Typ und Standort:\n\n| | Bern | Chur |\n|---|---|---|\n| Drehbank | 37.04 | 38.13 |\n| Fräse | **42.83** | **33.36** |\n| Presse | 49.02 | 48.27 |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Sechs Gruppen über Farbe **und** Form sind kaum zu trennen | Drei Farben mal zwei Formen, und die Punkte überlagern sich. Das Auge muss zwei Kanäle gleichzeitig auflösen, beide vom unteren Ende der Rangfolge. |\n| Die Facetten geben jeder Gruppe **eigene Fläche** | Position statt Farbe, Rang 2 statt Rang 7 — siehe [Wahrnehmung und Kodierung](wahrnehmung-kodierung.qmd). |\n| Die gemeinsamen Achsen sind der **Punkt** | Ohne sie wären die sechs Teilbilder sechs getrennte Grafiken. `facet_grid` setzt sie von sich aus gemeinsam; `scales = \"free\"` würde sie freigeben und die Vergleichbarkeit zerstören. |\n| Die Steigungen sind in allen Typen **fast gleich** | 2.384, 2.457, 2.534 — konstruiert waren 2.4. Die Facetten zeigen das auf einen Blick. |\n| Die Gesamtsteigung ist mit **2.358 kleiner** als jede einzelne | Weil die Pressen ihren Zuschlag unabhängig von der Laufzeit haben und die gemeinsame Gerade dadurch flacher wird. Ein kleiner Verwandter des [Simpson-Paradox](irrefuehrende-darstellungen.qmd). |\n| Ein Unterschied fällt erst in der Tabelle auf | Fräsen in Bern liegen bei 42.83, in Chur bei 33.36 — fast zehn Einheiten. Bei den anderen Typen ist der Standortunterschied unter 1.1. |\n\n::: {.note-box}\n**`facet_wrap` gegen `facet_grid`:**\n\n| Funktion | Aufteilung | Wann |\n|---|---|---|\n| `facet_wrap(~ a)` | eine Variable, umgebrochen | viele Stufen einer Variablen |\n| `facet_grid(a ~ b)` | Zeilen mal Spalten | zwei Variablen, vollständige Kreuztabelle |\n| `facet_grid(. ~ b)` | nur Spalten | wie `facet_wrap`, aber in einer Reihe |\n\nIn Python heisst das `sns.FacetGrid(row=, col=)` oder `sns.relplot(...)`.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> In allen drei Maschinentypen steigt der Verbrauch mit 2.384 bis 2.534 je\n> Stunde fast gleich stark, während die gemeinsame Gerade mit 2.358 flacher\n> ausfällt. Die Facetten mit gemeinsamen Achsen machen das sichtbar; über Farbe\n> und Form kodiert sind die sechs Gruppen nicht mehr zu trennen.\n\n### Beispiel 5: Skalen, Nullpunkt und Beschriftung\n\n#### Frage und Datenlage\n\nDie mittleren Verbrauchswerte je Typ als Balken — einmal mit Achse ab null,\neinmal ab 35. Dazu die fertige Fassung mit Beschriftung, wie sie in einen\nBericht gehört.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmittel <- maschinen |>\n  group_by(typ) |>\n  summarise(verbrauch = mean(verbrauch)) |>\n  as.data.frame()\nmittel$verbrauch <- round(mittel$verbrauch, 2)\nmittel\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       typ verbrauch\n1 Drehbank     37.58\n2    Fräse     38.09\n3   Presse     48.65\n```\n\n\n:::\n\n```{.r .cell-code}\nlaengen <- mittel$verbrauch - 35\nround(c(echtes_verhaeltnis = max(mittel$verbrauch) / min(mittel$verbrauch),\n        ab_35_dargestellt = max(laengen) / min(laengen),\n        verzerrung = (max(laengen) / min(laengen)) /\n          (max(mittel$verbrauch) / min(mittel$verbrauch))), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nechtes_verhaeltnis  ab_35_dargestellt         verzerrung \n              1.29               5.29               4.09 \n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(mittel, aes(typ, verbrauch)) +\n  geom_col(fill = \"grey70\") +\n  coord_cartesian(ylim = c(35, 50)) +\n  labs(subtitle = \"Achse ab 35 — die Unterschiede wirken dreifach\")\n```\n\n::: {.cell-output-display}\n![Links Achse ab null, rechts ab 35 — dieselben drei Zahlen.](ggplot2_files/figure-html/fig-b5a-gg-r-17.png){#fig-b5a-gg-r width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mittel, aes(reorder(typ, verbrauch), verbrauch)) +\n  geom_col(aes(fill = typ == \"Presse\"), width = 0.65) +\n  geom_text(aes(label = sprintf(\"%.1f\", verbrauch)), hjust = -0.15, size = 3.4) +\n  scale_fill_manual(values = c(`FALSE` = \"#c7c7c7\", `TRUE` = \"#b2182b\"),\n                    guide = \"none\") +\n  scale_y_continuous(limits = c(0, 55), expand = c(0, 0)) +\n  coord_flip() +\n  labs(title = \"Pressen verbrauchen rund ein Viertel mehr Strom\",\n       subtitle = \"Mittlerer Verbrauch je Maschinentyp, 180 Maschinen\",\n       x = NULL, y = \"Verbrauch in Kilowattstunden\",\n       caption = \"Quelle: Betriebsdatenerfassung, Stand 2026\") +\n  theme(panel.grid.major.y = element_blank())\n```\n\n::: {.cell-output-display}\n![Die Fassung für den Bericht: Achse ab null, Akzent, Beschriftung.](ggplot2_files/figure-html/fig-b5b-gg-r-1.png){#fig-b5b-gg-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmittel = maschinen.groupby(\"typ\")[\"verbrauch\"].mean().round(2)\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselbe Gegenüberstellung in matplotlib.](ggplot2_files/figure-html/fig-b5-gg-py-1.png){#fig-b5-gg-py-1 width=100%}\n:::\n\n```{.python .cell-code}\nprint(mittel)\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselbe Gegenüberstellung in matplotlib.](ggplot2_files/figure-html/fig-b5-gg-py-2.png){#fig-b5-gg-py-2 width=100%}\n:::\n\n```{.python .cell-code}\nlaengen = mittel - 35\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselbe Gegenüberstellung in matplotlib.](ggplot2_files/figure-html/fig-b5-gg-py-3.png){#fig-b5-gg-py-3 width=100%}\n:::\n\n```{.python .cell-code}\nprint({\"echtes_verhaeltnis\": round(float(mittel.max() / mittel.min()), 2),\n       \"ab_35_dargestellt\": round(float(laengen.max() / laengen.min()), 2),\n       \"verzerrung\": round(float((laengen.max() / laengen.min())\n                                 / (mittel.max() / mittel.min())), 2)})\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselbe Gegenüberstellung in matplotlib.](ggplot2_files/figure-html/fig-b5-gg-py-4.png){#fig-b5-gg-py-4 width=100%}\n:::\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(1, 2, figsize=(7, 2.8))\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselbe Gegenüberstellung in matplotlib.](ggplot2_files/figure-html/fig-b5-gg-py-5.png){#fig-b5-gg-py-5 width=100%}\n:::\n\n```{.python .cell-code}\n_ = achsen[0].bar(mittel.index, mittel.to_numpy(), color=\"0.7\")\n_ = achsen[0].set_ylim(0, 55)\n_ = achsen[0].set_title(\"Achse ab null\", fontsize=10)\n_ = achsen[1].bar(mittel.index, mittel.to_numpy(), color=\"0.7\")\n_ = achsen[1].set_ylim(35, 50)\n_ = achsen[1].set_title(\"Achse ab 35\", fontsize=10)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselbe Gegenüberstellung in matplotlib.](ggplot2_files/figure-html/fig-b5-gg-py-6.png){#fig-b5-gg-py-6 width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.python .cell-code}\nsortiert = mittel.sort_values()\nfarben = [\"#b2182b\" if name == \"Presse\" else \"#c7c7c7\" for name in sortiert.index]\n\nfig, achse = plt.subplots(figsize=(7, 3))\n_ = achse.barh(sortiert.index, sortiert.to_numpy(), color=farben, height=0.65)\nfor y, wert in enumerate(sortiert.to_numpy()):\n    _ = achse.text(wert + 0.8, y, f\"{wert:.1f}\", va=\"center\", fontsize=9)\n_ = achse.set_xlim(0, 55)\n_ = achse.set_title(\"Pressen verbrauchen rund ein Viertel mehr Strom\")\n_ = achse.set_xlabel(\"Verbrauch in Kilowattstunden\")\n_ = achse.grid(axis=\"y\", visible=False)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Die Fassung für den Bericht in matplotlib.](ggplot2_files/figure-html/fig-b5b-gg-py-13.png){#fig-b5b-gg-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Typ | mittlerer Verbrauch |\n|---|---|\n| Drehbank | **37.58** |\n| Fräse | **38.10** |\n| **Presse** | **48.65** |\n\n| Kennzahl | Wert |\n|---|---|\n| echtes Verhältnis Presse zu Drehbank | **1.29** |\n| als Balkenlänge bei Achse ab 35 | **4.20** |\n| **Verzerrung** | **3.24-fach** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Pressen verbrauchen **29 Prozent** mehr als Drehbänke | 48.65 gegen 37.58. Das ist der Befund, und er ist deutlich genug. |\n| Ab 35 gezeichnet sieht es nach **Faktor 4.2** aus | Eine Übertreibung um das 3.24-Fache. `coord_cartesian(ylim = …)` macht das mit einer Zeile — deshalb passiert es so leicht. |\n| `coord_cartesian` schneidet, `scale_y_continuous(limits =)` **wirft weg** | Der Unterschied ist wichtig: Letzteres entfernt Datenpunkte vor der Berechnung und verändert damit Glättungslinien und Statistiken. |\n| Die Berichtsfassung sortiert, betont und beschriftet | `reorder()` sortiert nach Wert, eine Akzentfarbe hebt die Pressen heraus, `geom_text` schreibt die Zahlen an — und der Titel nennt die Aussage statt des Diagrammtyps. |\n| `expand = c(0, 0)` entfernt den Rand unter null | Sonst schwebt der Balken sichtbar über der Achse, was den Nullpunkt wieder unklar macht. |\n\n::: {.note-box}\n**Die Beschriftungsteile, die `labs()` kennt:**\n\n| Argument | Inhalt |\n|---|---|\n| `title` | die Aussage in einem Satz |\n| `subtitle` | Datengrundlage, Zeitraum, Fallzahl |\n| `x`, `y` | Merkmal und Einheit; `NULL` blendet aus, wenn die Kategorien selbsterklärend sind |\n| `caption` | Quelle und Stand |\n\nVier Zeilen, die aus einer Ausgabe eine Abbildung machen. Mehr dazu unter\n[Storytelling](storytelling.qmd).\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Pressen verbrauchen im Mittel 48.65 gegenüber 37.58 bei Drehbänken, also das\n> 1.29-Fache. Mit einer Achse ab 35 erscheinen die Balken im Verhältnis 4.20 —\n> eine Verzerrung um den Faktor 3.24.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\n`ggplot(daten, aes(x, y))` allein zeichnet nichts. Warum?\n\n- [x] Ohne Geom gibt es keine Objekte, nur Achsen ~ Richtig. Zuordnung und\n      Darstellung sind in der Grammatik getrennt: `aes()` legt fest, welche\n      Variable auf welchen Kanal kommt, das Geom, womit gezeichnet wird.\n- [ ] Die Daten sind falsch formatiert ~ Bei falschem Format käme eine\n      Fehlermeldung, keine leere Grafik mit korrekten Achsen.\n- [ ] Es fehlt ein `print()` ~ In einem Quarto-Chunk wird das Objekt automatisch\n      ausgegeben.\n:::\n\n::: {.quiz}\n`geom_point(aes(colour = \"blue\"))` erzeugt rote Punkte und eine Legende. Warum?\n\n- [x] Innerhalb von `aes()` wird \"blue\" als Datenwert behandelt ~ Richtig. Es\n      entsteht eine Variable mit einem einzigen Wert, die eine Skala und eine\n      Legende bekommt; die erste Farbe der Standardpalette ist rot. Fester Wert\n      gehört ausserhalb von `aes()`.\n- [ ] \"blue\" ist kein gültiger Farbname ~ Er ist gültig; nur steht er an der\n      falschen Stelle.\n- [ ] Die Standardpalette ist falsch eingestellt ~ Sie verhält sich wie\n      vorgesehen.\n:::\n\n::: {.quiz}\nWann nimmt man `geom_col` statt `geom_bar`?\n\n- [x] Wenn die Werte bereits berechnet vorliegen ~ Richtig. `geom_bar` zählt\n      selbst und braucht nur ein `x`; `geom_col` nimmt fertige `y`-Werte. Die\n      Verwechslung ist die häufigste Ursache für eine unerwartet leere Grafik.\n- [ ] Wenn die Balken waagrecht sein sollen ~ Dafür ist `coord_flip()` oder ein\n      Tausch der Zuordnung zuständig.\n- [ ] `geom_col` ist die neuere Schreibweise für dasselbe ~ Die beiden tun\n      Verschiedenes.\n:::\n\n::: {.quiz}\nSechs Gruppen sollen in einem Streudiagramm unterschieden werden. Farbe plus\nForm oder Facetten?\n\n- [x] Facetten, weil sie Position statt Farbe verwenden ~ Richtig. Position auf\n      getrennten Skalen ist Rang 2 der Kanalrangfolge, Farbton Rang 7. Wichtig\n      sind dabei die gemeinsamen Achsen, sonst sind die Teilbilder nicht\n      vergleichbar.\n- [ ] Farbe plus Form, das spart Platz ~ Platz wird gespart, Lesbarkeit\n      verloren: Das Auge muss zwei schwache Kanäle gleichzeitig auflösen.\n- [ ] Beides zusammen, das ist am sichersten ~ Doppelte Kodierung derselben\n      Information ist sinnvoll, hier geht es aber um zwei verschiedene\n      Variablen.\n:::\n\n::: {.quiz}\nDie mittleren Verbrauchswerte 37.58, 38.10 und 48.65 werden mit einer Achse ab\n35 gezeichnet. Wie stark verzerrt das?\n\n- [x] Um das 3.24-Fache: aus Verhältnis 1.29 wird 4.20 ~ Richtig. Bei Balken\n      kodiert die Länge die Menge, deshalb muss die Achse bei null beginnen.\n- [ ] Gar nicht, solange die Achse beschriftet ist ~ Die Beschriftung stimmt,\n      der Eindruck nicht.\n- [ ] Um das Doppelte ~ Die Rechnung ergibt 4.20 geteilt durch 1.29.\n:::\n\n::: {.quiz}\nWorin unterscheiden sich `coord_cartesian(ylim = …)` und\n`scale_y_continuous(limits = …)`?\n\n- [x] `coord_cartesian` zoomt, `scale_y_continuous` entfernt Datenpunkte ~\n      Richtig. Beim zweiten werden Werte ausserhalb der Grenzen vor der\n      Berechnung verworfen, was Glättungslinien und Statistiken verändert.\n- [ ] Sie sind gleichwertig ~ Optisch oft ähnlich, im Ergebnis nicht.\n- [ ] `coord_cartesian` funktioniert nur bei Balken ~ Es funktioniert bei jedem\n      Geom.\n:::\n\n## Verlinkte Ressourcen\n\n- [ggplot2: Referenz aller Geome](https://ggplot2.tidyverse.org/reference/)\n- [R for Data Science, Kapitel zur Visualisierung](https://r4ds.hadley.nz/data-visualize)\n- [Diagrammtyp wählen](diagrammtyp-waehlen.qmd) — welche Grafik die Aufgabe löst\n- [matplotlib](matplotlib.qmd) — dieselben Aufgaben in Python\n- [Storytelling](storytelling.qmd) — Beschriftung und Betonung\n",
    "supporting": [
      "ggplot2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}