{
  "hash": "efaf82f70ea736f58d1785c019069920",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Kausale Inferenz\"\ndescription: \"Ursache statt Zusammenhang aus Beobachtungsdaten: Confounder, Adjustierung, Schichtung und Difference-in-Differences.\"\ncategories: [\"Versuchsplanung\", \"Regression\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: methode\nstand: entwurf\norder: 100\n---\n\n\n\n\n\nDie Daten sind so erzeugt, dass der wahre Effekt bekannt ist: 3 für die\nWeiterbildung, 4 für die Massnahme. Nur so lässt sich zeigen, welches Verfahren\nihn trifft. R und Python sehen dieselben Werte aus dem Lehmer-Generator.\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Wie gross ist der Effekt einer Behandlung, wenn niemand die Zuteilung zufällig bestimmt hat? |\n| Grundproblem | Wer behandelt wird, unterscheidet sich oft auch sonst von den anderen |\n| Werkzeuge | Adjustierung in der Regression, Schichtung, Matching, Difference-in-Differences, Instrumentvariablen |\n| Was die Verfahren liefern | eine Effektschätzung, die **unter benannten Annahmen** kausal gelesen werden darf |\n| R | `lm()` mit Kontrollvariablen, `lm(y ~ gruppe * zeit)` für Difference-in-Differences; Matching mit `MatchIt` |\n| Python | `smf.ols()` ebenso; Matching und mehr mit `DoWhy` |\n| Verwandte Seiten | [Versuchsplanung und A/B-Tests](versuchsplanung-ab-tests.qmd), [multiple lineare Regression](../regression/multiple-lineare-regression.qmd), [Korrelation](../grundlagen/korrelation.qmd) |\n\n## Wann diese Methode, wann nicht\n\nWann immer ein Experiment nicht möglich, zu teuer oder unethisch ist, bleiben\nBeobachtungsdaten: Wer eine Weiterbildung besucht hat, wer in einer Region mit\nneuer Massnahme lebt, wer ein Medikament nimmt. Die Frage ist dieselbe wie im\nExperiment, aber die Antwort braucht zusätzliche Annahmen, und die müssen\nausgesprochen werden.\n\n| Situation | Stattdessen |\n|---|---|\n| Zuteilung lässt sich zufällig steuern | [A/B-Test oder Experiment](versuchsplanung-ab-tests.qmd), das ist immer vorzuziehen |\n| Nur ein Zusammenhang ist gefragt, keine Ursache | [Korrelation](../grundlagen/korrelation.qmd) oder [Regression](../regression/multiple-lineare-regression.qmd) ohne kausale Lesart |\n| Vorhersage steht im Vordergrund | Vorhersagemodelle; ob ein Prädiktor kausal wirkt, ist dafür unwichtig |\n\n## Grundidee und Modell\n\nEin **Confounder** beeinflusst sowohl die Behandlung als auch das Ergebnis:\n\n```{mermaid}\n%%| label: fig-confounder\n%%| fig-cap: \"Erfahrung als Confounder: Sie wirkt auf die Weiterbildung und auf das Gehalt.\"\n%%| echo: false\nflowchart LR\n    E[\"Erfahrung\"] --> K[\"Weiterbildung\"]\n    E --> G[\"Gehalt\"]\n    K -- \"gesuchter Effekt\" --> G\n```\n\nWer nur Gehälter mit und ohne Weiterbildung vergleicht, misst beide Wege von\nErfahrung zu Gehalt mit. Die Verfahren unterscheiden sich darin, wie sie den\nUmweg über den Confounder schliessen:\n\n| Verfahren | Wie es den Confounder behandelt | Zentrale Annahme |\n|---|---|---|\n| Adjustierung | Confounder als Kontrollvariable in der Regression | alle Confounder gemessen, Form des Zusammenhangs richtig |\n| Schichtung und Matching | nur Personen mit ähnlichem Confounder vergleichen | alle Confounder gemessen, Schichten fein genug |\n| Difference-in-Differences | zeitlich konstante Unterschiede zwischen Gruppen fallen durch Differenzbildung weg | ohne Massnahme wären beide Gruppen parallel verlaufen |\n| Instrumentvariable | eine Grösse nutzen, die nur über die Behandlung wirkt | das Instrument hat keinen anderen Weg zum Ergebnis |\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung | Vorgehen |\n|---|---|---|---|---|\n| Keine ungemessenen Confounder | alles, was Behandlung und Ergebnis zugleich beeinflusst, ist in den Daten | nicht mit Daten prüfbar; Fachwissen, Diagramm wie oben | verzerrte Schätzung in unbekannter Richtung | Sensitivitätsanalyse, andere Verfahren |\n| Überlappung | für jeden Confounderwert gibt es Behandelte und Unbehandelte | Verteilung des Confounders je Gruppe vergleichen | Schätzung beruht auf Extrapolation | auf den Bereich mit Überlappung beschränken |\n| Keine Kontrolle von Mediatoren | nichts adjustieren, was selbst eine Folge der Behandlung ist | Diagramm | Effekt wird kleingerechnet | nur Grössen vor der Behandlung aufnehmen |\n| Parallele Trends (für DiD) | ohne Massnahme gleiche Entwicklung | Verlauf über mehrere Perioden vor der Massnahme | DiD-Schätzung verzerrt | mehr Vorperioden, anderes Vergleichsgebiet |\n\n## Output lesen\n\nDie Verfahren auf dieser Seite verwenden die gewöhnliche Regression. Neu ist\nnicht der Output, sondern welche Zeile kausal gelesen wird:\n\n| Modell | Zeile mit dem Effekt | Was sie bedeutet |\n|---|---|---|\n| `gehalt ~ kurs + erfahrung` | `kurs` | Gehaltsunterschied mit Weiterbildung bei gleicher Erfahrung |\n| `umsatz ~ massnahme * nachher` | `massnahme:nachher` | zusätzliche Veränderung in der Region mit Massnahme, über die allgemeine Veränderung hinaus |\n\nAlle anderen Koeffizienten sind Hilfsgrössen. Der Koeffizient von `erfahrung`\netwa ist **nicht** der kausale Effekt der Erfahrung, weil für ihn andere\nConfounder gelten würden.\n\n## Interpretationsfallen\n\n- **Korrelation ist nicht Kausalität, auch mit vielen Kontrollvariablen nicht.**\n  Adjustierung hilft nur gegen gemessene Confounder.\n- **Mehr Kontrollvariablen sind nicht automatisch besser.** Ein Mediator oder\n  eine gemeinsame Folge von Behandlung und Ergebnis erzeugen Verzerrung, statt\n  sie zu beseitigen.\n- **Grobe Schichten lassen Verzerrung übrig.** Innerhalb einer Schicht von 14\n  bis 20 Jahren Erfahrung unterscheiden sich die Gruppen immer noch. Beispiel 2\n  misst den Rest.\n- **Die Tabelle-2-Falle:** In einem Modell ist nur der Koeffizient der\n  Behandlung kausal gemeint; die übrigen im selben Atemzug kausal zu\n  interpretieren ist ein verbreiteter Fehler.\n- **Vorher-nachher allein ist kein Effekt.** Alles, was sich in derselben Zeit\n  sonst verändert hat, steckt mit darin. Beispiel 3 zeigt es.\n\n## Ergebnis berichten\n\n> Unter der Annahme, dass [Confounder] die relevanten gemeinsamen Ursachen\n> erfassen, ist [Behandlung] mit [Wert] [Einheit] höherem [Ergebnis] verbunden\n> (95-Prozent-Konfidenzintervall [unten] bis [oben], [Verfahren]). Ungemessene\n> Confounder wie [Beispiele] können nicht ausgeschlossen werden.\n\nImmer genannt werden: das Verfahren, die Identifikationsannahme im Klartext,\ndie adjustierten Grössen und die bekannten Grenzen.\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt der hier beschriebenen |\n|---|---|\n| [Versuchsplanung und A/B-Tests](versuchsplanung-ab-tests.qmd) | Zuteilung lässt sich randomisieren |\n| [Multiple lineare Regression](../regression/multiple-lineare-regression.qmd) | Zusammenhänge beschreiben oder vorhersagen, ohne kausalen Anspruch |\n| [Gemischte Modelle](../regression/gemischte-modelle.qmd) | Paneldaten mit wiederholten Messungen; lassen sich mit DiD kombinieren |\n\n## Beispiele\n\nJedes Beispiel steht in einem eigenen Reiter.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Naiver Vergleich und Adjustierung\n\n#### Frage und Datenlage\n\nVerdienen Beschäftigte mit Weiterbildung mehr? 400 Personen, erfasst sind\nErfahrung in Jahren, Weiterbildung ja oder nein und Gehalt in Tausend Franken.\nErfahrene haben häufiger eine Weiterbildung besucht.\n\n#### Voraussetzungen prüfen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(c(anteil_kurs = mean(firma$kurs)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nanteil_kurs \n     0.4675 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(tapply(firma$erfahrung, firma$kurs, mean), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    0     1 \n 8.78 13.84 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(\"Anteil Kurs:\", round(firma[\"kurs\"].mean(), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnteil Kurs: 0.4675\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(firma.groupby(\"kurs\")[\"erfahrung\"].mean().round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nkurs\n0     8.78\n1    13.84\nName: erfahrung, dtype: float64\n```\n\n\n:::\n:::\n\n\n:::\n\nMit Weiterbildung liegt die Erfahrung im Mittel bei 13.84 Jahren, ohne bei 8.78.\nDie beiden Gruppen unterscheiden sich also schon vor jeder Wirkung des Kurses.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnaiv <- diff(tapply(firma$gehalt, firma$kurs, mean))\nadjustiert <- lm(gehalt ~ kurs + erfahrung, data = firma)\n\nround(c(naiv = unname(naiv), adjustiert = unname(coef(adjustiert)[\"kurs\"]),\n        se = summary(adjustiert)$coefficients[\"kurs\", \"Std. Error\"]), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      naiv adjustiert         se \n    14.856      4.549      0.703 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(confint(adjustiert)[\"kurs\", ], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 2.5 % 97.5 % \n 3.166  5.932 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmittel = firma.groupby(\"kurs\")[\"gehalt\"].mean()\nadjustiert = smf.ols(\"gehalt ~ kurs + erfahrung\", firma).fit()\n\nprint(\"naiv:\", round(mittel[1] - mittel[0], 3),\n      \" adjustiert:\", round(adjustiert.params[\"kurs\"], 3),\n      \" se:\", round(adjustiert.bse[\"kurs\"], 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnaiv: 14.856  adjustiert: 4.549  se: 0.703\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Intervall:\", np.round(adjustiert.conf_int().loc[\"kurs\"].values, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIntervall: [3.166 5.932]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| naiver Unterschied | 14.856 | Gehalt mit minus ohne Weiterbildung | fast fünfmal der wahre Effekt von 3; enthält den Umweg über die Erfahrung |\n| adjustierter Effekt | 4.549 | Unterschied bei gleicher Erfahrung | viel näher am wahren Wert |\n| Standardfehler | 0.703 | Unsicherheit der adjustierten Schätzung | |\n| Intervall | 3.166 bis 5.932 | 95-Prozent-Konfidenzintervall | Es verfehlt den wahren Wert 3 knapp. Bei 95-Prozent-Intervallen passiert das in jedem zwanzigsten Datensatz, hier ist es einer davon. |\n\n#### Interpretation und Ergebnissatz\n\nDie Adjustierung beseitigt den grössten Teil der Verzerrung. Dass sie hier\nfunktioniert, liegt an zwei Eigenschaften der erzeugten Daten, die in echten\nDaten niemand garantiert: Erfahrung ist der einzige Confounder, und sie wirkt\nlinear auf das Gehalt.\n\n> Bei gleicher Erfahrung verdienen Beschäftigte mit Weiterbildung im Mittel 4.5\n> Tausend Franken mehr (95-Prozent-Konfidenzintervall 3.2 bis 5.9, lineare\n> Regression mit Erfahrung als Kontrollvariable), unter der Annahme, dass\n> Erfahrung die relevante gemeinsame Ursache ist.\n\n### Beispiel 2: Schichtung mit groben Klassen\n\n#### Frage und Datenlage\n\nStatt die Erfahrung als Zahl ins Modell zu nehmen, werden die Personen in vier\nErfahrungsklassen eingeteilt: 2 bis 6, 6 bis 10, 10 bis 14 und 14 bis 20 Jahre.\nInnerhalb jeder Klasse wird der Gehaltsunterschied berechnet, danach nach der\nKlassengrösse gemittelt.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirma$schicht <- cut(firma$erfahrung, breaks = c(0, 6, 10, 14, 20))\nje_schicht <- sapply(split(firma, firma$schicht), function(s) {\n  c(ohne = mean(s$gehalt[s$kurs == 0]), mit = mean(s$gehalt[s$kurs == 1]),\n    n_ohne = sum(s$kurs == 0), n_mit = sum(s$kurs == 1))\n})\nje_schicht <- rbind(je_schicht, diff = je_schicht[\"mit\", ] - je_schicht[\"ohne\", ])\nround(je_schicht, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       (0,6] (6,10] (10,14] (14,20]\nohne   66.69  75.26   85.10   92.32\nmit    70.88  82.59   88.59   98.54\nn_ohne 66.00  68.00   49.00   30.00\nn_mit  11.00  28.00   45.00  103.00\ndiff    4.19   7.32    3.49    6.22\n```\n\n\n:::\n\n```{.r .cell-code}\ngewicht <- je_schicht[\"n_ohne\", ] + je_schicht[\"n_mit\", ]\nround(weighted.mean(je_schicht[\"diff\", ], gewicht), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.452\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfirma[\"schicht\"] = pd.cut(firma[\"erfahrung\"], [0, 6, 10, 14, 20])\ntabelle = firma.groupby([\"schicht\", \"kurs\"], observed=True)[\"gehalt\"].agg([\"mean\", \"size\"]).unstack()\ntabelle[\"diff\"] = tabelle[(\"mean\", 1)] - tabelle[(\"mean\", 0)]\ntabelle[\"n\"] = tabelle[(\"size\", 0)] + tabelle[(\"size\", 1)]\nprint(tabelle.round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           mean        size       diff    n\nkurs          0      1    0    1           \nschicht                                    \n(0, 6]    66.69  70.88   66   11  4.19   77\n(6, 10]   75.26  82.59   68   28  7.32   96\n(10, 14]  85.10  88.59   49   45  3.49   94\n(14, 20]  92.32  98.54   30  103  6.22  133\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"gewichtet:\", round(np.average(tabelle[\"diff\"], weights=tabelle[\"n\"]), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngewichtet: 5.452\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Schicht | ohne Kurs | mit Kurs | Differenz | Wie es zu lesen ist |\n|---|---|---|---|---|\n| 2 bis 6 Jahre | 66 Personen | 11 Personen | 4.19 | wenige Behandelte, unsichere Differenz |\n| 6 bis 10 Jahre | 68 | 28 | 7.32 | |\n| 10 bis 14 Jahre | 49 | 45 | 3.49 | |\n| 14 bis 20 Jahre | 30 | 103 | 6.22 | umgekehrtes Verhältnis: hier sind die Unbehandelten die Minderheit |\n| gewichtet | | | 5.452 | weiter vom wahren Wert 3 entfernt als die Adjustierung |\n\n#### Interpretation und Ergebnissatz\n\nInnerhalb der Schicht von 14 bis 20 Jahren sind die Weitergebildeten immer noch\nerfahrener als die anderen, weil Erfahrene in jeder Schicht häufiger einen Kurs\nbesuchen. Dieser Rest an Confounding bleibt in der Differenz stecken. Feinere\nSchichten oder Matching auf die genaue Erfahrung verringern ihn, kosten aber\nBeobachtungen je Vergleich.\n\n> Die Schichtung nach vier Erfahrungsklassen ergibt einen Effekt von 5.45\n> Tausend Franken; die groben Klassen lassen einen Teil der Verzerrung durch\n> Erfahrung bestehen.\n\n### Beispiel 3: Difference-in-Differences\n\n#### Frage und Datenlage\n\nRegion B führte eine Verkaufsmassnahme ein, Region A nicht. Gemessen wurde der\nUmsatz je Filialwoche vor und nach der Einführung, je 50 Werte. Region B lag\nschon vorher höher, und in beiden Regionen stieg der Umsatz in der zweiten\nPeriode saisonal. Welcher Anteil des Anstiegs in B geht auf die Massnahme\nzurück?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm <- tapply(did$umsatz, list(did$region, did$nachher), mean)\nround(m, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        0       1\nA  99.268 106.352\nB 106.674 116.796\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(nachher_b_minus_a = m[\"B\", \"1\"] - m[\"A\", \"1\"],\n        b_nachher_minus_vorher = m[\"B\", \"1\"] - m[\"B\", \"0\"],\n        did_von_hand = (m[\"B\", \"1\"] - m[\"B\", \"0\"]) - (m[\"A\", \"1\"] - m[\"A\", \"0\"])), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     nachher_b_minus_a b_nachher_minus_vorher           did_von_hand \n                10.444                 10.122                  3.038 \n```\n\n\n:::\n\n```{.r .cell-code}\nmodell <- lm(umsatz ~ massnahme * nachher, data = did)\nround(summary(modell)$coefficients, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Estimate Std. Error  t value Pr(>|t|)\n(Intercept)         99.268     0.8677 114.3999   0.0000\nmassnahme            7.406     1.2272   6.0351   0.0000\nnachher              7.084     1.2272   5.7727   0.0000\nmassnahme:nachher    3.038     1.7355   1.7505   0.0816\n```\n\n\n:::\n\n```{.r .cell-code}\nround(confint(modell)[\"massnahme:nachher\", ], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 2.5 % 97.5 % \n-0.385  6.461 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nm = did.groupby([\"region\", \"nachher\"])[\"umsatz\"].mean().unstack()\nprint(m.round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnachher        0        1\nregion                   \nA         99.268  106.352\nB        106.674  116.796\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"nachher B minus A:\", round(m.loc[\"B\", 1] - m.loc[\"A\", 1], 3),\n      \" B nachher minus vorher:\", round(m.loc[\"B\", 1] - m.loc[\"B\", 0], 3),\n      \" DiD von Hand:\", round((m.loc[\"B\", 1] - m.loc[\"B\", 0]) - (m.loc[\"A\", 1] - m.loc[\"A\", 0]), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnachher B minus A: 10.444  B nachher minus vorher: 10.122  DiD von Hand: 3.038\n```\n\n\n:::\n\n```{.python .cell-code}\nmodell = smf.ols(\"umsatz ~ massnahme * nachher\", did).fit()\nprint(pd.DataFrame({\"schaetzung\": modell.params, \"se\": modell.bse,\n                    \"p\": modell.pvalues}).round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   schaetzung      se       p\nIntercept              99.268  0.8677  0.0000\nmassnahme               7.406  1.2272  0.0000\nnachher                 7.084  1.2272  0.0000\nmassnahme:nachher       3.038  1.7355  0.0816\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Intervall:\", np.round(modell.conf_int().loc[\"massnahme:nachher\"].values, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIntervall: [-0.385  6.461]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| Mittel A vorher, nachher | 99.268, 106.352 | Region ohne Massnahme | Anstieg um 7.084, das ist die allgemeine Entwicklung |\n| Mittel B vorher, nachher | 106.674, 116.796 | Region mit Massnahme | Anstieg um 10.122 |\n| `massnahme` | 7.406 | Niveauunterschied vor der Massnahme | B lag schon vorher höher; das ist kein Effekt |\n| `nachher` | 7.084 | allgemeiner Anstieg | gilt für beide Regionen |\n| `massnahme:nachher` | 3.038 | Difference-in-Differences | zusätzlicher Anstieg in B, die Schätzung des Effekts |\n| Standardfehler, p | 1.7355, 0.0816 | Unsicherheit | bei je 50 Werten nicht signifikant |\n| Intervall | -0.385 bis 6.461 | 95-Prozent-Konfidenzintervall | enthält den wahren Wert 4 und auch die Null |\n\n#### Interpretation und Ergebnissatz\n\nDie beiden naiven Vergleiche liegen weit daneben: Nachher B gegen A ergibt 10.444,\nweil der alte Niveauunterschied mitgezählt wird; vorher gegen nachher in B ergibt\n10.122, weil der saisonale Anstieg mitgezählt wird. Die doppelte Differenz\nentfernt beides und landet bei 3.038. Mit 50 Werten je Zelle ist die Schätzung\naber unsicher. Die Annahme paralleler Trends lässt sich mit nur einer\nVorperiode nicht prüfen.\n\n> Unter der Annahme paralleler Trends erhöhte die Massnahme den Umsatz um 3.0\n> Einheiten (95-Prozent-Konfidenzintervall -0.4 bis 6.5, p = 0.08,\n> Difference-in-Differences mit je 50 Filialwochen). Der Effekt ist mit diesen\n> Daten nicht von null zu unterscheiden.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEine Studie findet, dass Personen mit Fitnessabo seltener krank sind, und\nadjustiert für Alter und Geschlecht. Welcher Einwand wiegt am schwersten?\n\n- [x] Gesundheitsbewusstsein beeinflusst Abo und Krankheit und ist nicht\n      gemessen ~ Richtig. Das ist ein ungemessener Confounder. Gegen ihn hilft\n      keine Adjustierung der vorhandenen Variablen.\n- [ ] Die Stichprobe ist zu klein ~ Mehr Daten verkleinern die Unsicherheit,\n      nicht die Verzerrung durch einen fehlenden Confounder.\n- [ ] Alter hätte nicht adjustiert werden dürfen ~ Alter wirkt auf Abo und\n      Krankheit und liegt zeitlich davor; es zu adjustieren ist richtig.\n:::\n\n::: {.quiz}\nEin Modell schätzt den Effekt einer Schulung auf den Umsatz. Soll die Zahl der\nKundenkontakte **nach** der Schulung als Kontrollvariable aufgenommen werden?\n\n- [x] Nein, sie ist vermutlich ein Mediator, über den die Schulung wirkt ~\n      Richtig. Wer den Mediator konstant hält, rechnet den Teil des Effekts\n      heraus, der über mehr Kundenkontakte läuft.\n- [ ] Ja, jede Variable mit Einfluss auf den Umsatz gehört ins Modell ~ Das gilt\n      für Confounder, nicht für Folgen der Behandlung.\n- [ ] Ja, sonst ist das Modell nicht signifikant ~ Signifikanz ist kein\n      Kriterium für die Auswahl der Kontrollvariablen.\n:::\n\n::: {.quiz}\nWas ist die zentrale Annahme hinter Difference-in-Differences?\n\n- [x] Ohne die Massnahme hätten sich beide Gruppen parallel entwickelt ~\n      Richtig. Unterschiede im Niveau sind erlaubt, Unterschiede in der\n      Entwicklung nicht.\n- [ ] Beide Gruppen lagen vorher auf demselben Niveau ~ Gerade das muss nicht\n      sein; der Niveauunterschied fällt durch die Differenzbildung weg.\n- [ ] Die Massnahme wurde zufällig zugeteilt ~ Dann wäre ein einfacher Vergleich\n      möglich; DiD ist gerade für den Fall ohne Randomisierung da.\n:::\n\n## Verlinkte Ressourcen\n\n- [Causal Inference: The Mixtape (Scott Cunningham)](https://mixtape.scunning.com/)\n- [The Effect (Nick Huntington-Klein)](https://theeffectbook.net/)\n- [Introduction to Causal Inference (Brady Neal), Kurs](https://www.bradyneal.com/causal-inference-course)\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}