{
  "hash": "4b7a7064857793a907ce312a5aff8257",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"k-Means\"\ndescription: \"Objekte in k Gruppen teilen, Startwerte und die Wahl von k.\"\ncategories: [\"Clustering\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: methode\nstand: fertig\norder: 40\n---\n\n\n\n\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Lassen sich die Beobachtungen in k Gruppen teilen, sodass jede Gruppe möglichst homogen ist? |\n| Zielvariable | keine, das Verfahren ist unüberwacht |\n| Eingang | metrische Variablen, standardisiert |\n| Was die Methode liefert | Gruppenzuordnung je Beobachtung, Zentren je Gruppe, Streuung innerhalb der Gruppen |\n| R-Funktion | `kmeans(scale(daten), centers = k, nstart = 25)` |\n| Python-Funktion | `KMeans(n_clusters=k, n_init=25).fit(standardisiert)` |\n| Verwandte Methoden | [hierarchisches Clustering](hierarchisches-clustering.qmd), [Clustergüte](clusterguete.qmd), [Distanzmasse](distanzmasse.qmd) |\n\n## Wann diese Methode, wann nicht\n\nTypische Fragestellungen: Kundensegmente bilden, Maschinen nach Betriebsmuster\ngruppieren, Messreihen in Zustandsklassen einteilen. Gemeinsam ist ihnen, dass\nGruppen gesucht und nicht bekannt sind, und dass alle Variablen metrisch sind.\n\nk-Means teilt die Beobachtungen so auf, dass die Summe der quadrierten Abstände\nzu den Gruppenzentren minimal wird. Das Verfahren ist schnell und funktioniert\nbei kompakten, ähnlich grossen Gruppen sehr gut. Es hat drei Eigenschaften, die\nman kennen muss: Die Anzahl Gruppen wird vorgegeben, das Ergebnis hängt von den\nStartwerten ab, und die Gruppenform ist implizit kugelig.\n\n| Situation | Stattdessen |\n|---|---|\n| Anzahl Gruppen unbekannt und Struktur soll sichtbar werden | [hierarchisches Clustering](hierarchisches-clustering.qmd) |\n| Gemischte Datentypen, nominale Merkmale dabei | Gower-Distanz mit hierarchischem Verfahren, siehe [Distanzmasse](distanzmasse.qmd) |\n| Gruppen sind langgezogen, verschachtelt oder ringförmig | dichtebasierte Verfahren wie DBSCAN |\n| Ausreisser sollen keine eigene Gruppe erzwingen | k-Medoids, DBSCAN |\n| Die Gruppen sind bekannt und sollen vorhergesagt werden | [Klassifikation](../regression/klassifikationsguete.qmd) |\n| Viele Dimensionen mit Rauschen | zuerst [Hauptkomponentenanalyse](hauptkomponentenanalyse.qmd) |\n\n## Grundidee und Modell\n\nGesucht ist eine Aufteilung in $k$ Gruppen, die die Streuung innerhalb der\nGruppen minimiert:\n\n$$\\min \\sum_{j=1}^{k} \\sum_{i \\in C_j} \\lVert x_i - \\mu_j \\rVert^2$$\n\n| Bestandteil | Bedeutung |\n|---|---|\n| $C_j$ | Menge der Beobachtungen in Gruppe $j$ |\n| $\\mu_j$ | Zentrum der Gruppe $j$, der Mittelwert ihrer Mitglieder |\n| $\\lVert x_i - \\mu_j \\rVert^2$ | quadrierte euklidische Distanz zum Zentrum |\n\nDer Algorithmus wechselt zwei Schritte ab, bis sich nichts mehr ändert: Jede\nBeobachtung wird dem nächsten Zentrum zugeordnet, dann wird jedes Zentrum als\nMittelwert seiner Mitglieder neu berechnet. Das findet garantiert ein lokales\nMinimum, aber nicht garantiert das beste. Deshalb wird das Verfahren mit\nmehreren Startwerten wiederholt, und die beste Lösung gewinnt: in R über\n`nstart`, in Python über `n_init`.\n\nWeil quadrierte euklidische Distanzen minimiert werden, sind zwei Dinge\neingebaut: Die Gruppen werden tendenziell kugelig und ähnlich gross, und die\nStandardisierung entscheidet über das Ergebnis, siehe\n[Distanzmasse](distanzmasse.qmd).\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung | Vorgehen |\n|---|---|---|---|---|\n| Metrische Variablen | Mittelwerte als Zentren sind sinnvoll | [Skalenniveau](../grundlagen/skalenniveaus.qmd) | Zentren sind nicht deutbar | Gower mit hierarchischem Verfahren |\n| Standardisierung | Keine Variable dominiert wegen ihrer Einheit | Varianzen vergleichen | Gruppierung folgt nur der grössten Variablen | `scale()` beziehungsweise `StandardScaler` |\n| Annähernd kugelige Gruppen | Gruppen sind kompakt, nicht langgezogen | Streudiagramm | Gruppen werden quer durchgeschnitten | dichtebasierte Verfahren |\n| Ähnliche Gruppengrössen | Keine Gruppe ist um Grössenordnungen kleiner | Gruppengrössen nach dem Lauf | Kleine Gruppen werden geschluckt | hierarchisch, oder k erhöhen |\n| Keine extremen Ausreisser | Einzelne Punkte ziehen kein Zentrum auf sich | Streudiagramm, Abstände zum Zentrum | Eine Gruppe besteht aus einem Punkt | Ausreisser prüfen, k-Medoids |\n| Mehrere Startwerte | Das lokale Minimum ist nicht das erste gefundene | `nstart` beziehungsweise `n_init` setzen | Ergebnis schwankt zwischen Läufen | mindestens 25 Startwerte |\n\n## Output lesen\n\nR, `kmeans()`:\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| `size` | Anzahl Beobachtungen je Gruppe | eine Gruppe mit einem oder zwei Fällen deutet auf Ausreisser |\n| `centers` | Zentren in den Einheiten der übergebenen Daten | bei standardisierten Daten in Standardabweichungen, also zurückrechnen für den Bericht |\n| `cluster` | Gruppennummer je Beobachtung | die Nummerierung ist beliebig und wechselt zwischen Läufen |\n| `tot.withinss` | Summe der quadrierten Abstände innerhalb der Gruppen | sinkt zwangsläufig mit steigendem k |\n| `betweenss` | Streuung zwischen den Gruppen | |\n| `totss` | Gesamtstreuung | `betweenss / totss` ist der erklärte Anteil |\n| `iter` | Anzahl Durchläufe bis zur Konvergenz | |\n| Warnung `did not converge` | Abbruch vor Konvergenz | `iter.max` erhöhen |\n\nPython, `KMeans`:\n\n| Zugriff | Was er liefert | Unterschied zu R |\n|---|---|---|\n| `labels_` | Gruppenzuordnung | wie `cluster`, aber nullbasiert |\n| `cluster_centers_` | Zentren | wie `centers` |\n| `inertia_` | Summe der quadrierten Abstände innerhalb der Gruppen | wie `tot.withinss` |\n| `n_iter_` | Anzahl Durchläufe | wie `iter` |\n| kein `betweenss` | selbst berechnen als Gesamtstreuung minus `inertia_` | in R enthalten |\n| `n_init` | Anzahl Startwerte | wie `nstart`; die Voreinstellung hat sich zwischen den Versionen geändert, deshalb ausdrücklich setzen |\n\n::: {.note-box}\n**Die Gruppennummern bedeuten nichts.** Gruppe 1 in einem Lauf kann Gruppe 3 im\nnächsten sein, und R und Python nummerieren dieselbe Aufteilung fast immer\nverschieden. Für den Bericht werden die Gruppen nach einem inhaltlichen Merkmal\numsortiert und benannt. Jede Aussage der Form \"Gruppe 2 kauft mehr\" ist ohne\ndiese Benennung wertlos.\n:::\n\n## Interpretationsfallen\n\n- **k-Means findet immer Gruppen.** Auch in Daten ohne Struktur. Dass eine Lösung\n  vorliegt, sagt nichts darüber, ob es Gruppen gibt.\n- **Die Streuung innerhalb sinkt mit k.** Sie taugt deshalb nicht zur Wahl von k,\n  siehe [Clustergüte](clusterguete.qmd).\n- **Gruppennummern sind beliebig.** Sie wechseln zwischen Läufen; jede Aussage\n  über \"Gruppe 2\" braucht eine inhaltliche Beschreibung.\n- **Ohne Standardisierung entscheidet die Einheit.** Der häufigste stille Fehler.\n- **Zentren in Standardabweichungen sind nicht berichtbar.** Für den Bericht\n  werden sie in die ursprünglichen Einheiten zurückgerechnet.\n- **Kugelige Gruppen sind eine Annahme.** Bei anderen Formen liegt das Verfahren\n  falsch, ohne es anzuzeigen.\n- **Ein Clustering ist keine Erklärung.** Es beschreibt Ähnlichkeit in den\n  gewählten Variablen; wer andere Variablen wählt, bekommt andere Gruppen.\n- **Ausreisser verzerren Zentren.** Ein einzelner extremer Punkt kann eine\n  eigene Gruppe erzwingen und die übrigen verschieben.\n\n## Ergebnis berichten\n\nVorlage für den Ergebnissatz:\n\n> Ein k-Means-Clustering auf [Variablen], standardisiert, mit k = [k] und [Anzahl]\n> Startwerten (n = [n]) ergibt Gruppen der Grössen [Grössen]. Die Zentren liegen\n> bei [Werte in Originaleinheiten]; die Aufteilung erklärt [Anteil] der\n> Gesamtstreuung. Die Wahl von k stützt sich auf [Kriterium].\n\nGenannt werden: verwendete Variablen und Standardisierung, k und dessen\nBegründung, Anzahl Startwerte, Gruppengrössen, Zentren in Originaleinheiten,\nerklärter Streuungsanteil, ein Gütemass wie die Silhouette und eine inhaltliche\nBeschreibung jeder Gruppe.\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt k-Means |\n|---|---|\n| [Hierarchisches Clustering](hierarchisches-clustering.qmd) | k unbekannt, Struktur soll als Dendrogramm sichtbar werden |\n| [Clustergüte](clusterguete.qmd) | die Wahl von k und die Beurteilung einer Lösung |\n| k-Medoids | Ausreisser sollen weniger Einfluss haben, Zentren sollen echte Objekte sein |\n| DBSCAN | Gruppen beliebiger Form, Ausreisser als eigene Kategorie |\n| Gaussian-Mixture-Modelle | Gruppen dürfen verschiedene Streuung und Form haben, Zuordnung mit Wahrscheinlichkeit |\n| [Hauptkomponentenanalyse](hauptkomponentenanalyse.qmd) | neue Variablen statt Gruppen von Beobachtungen |\n\n## Beispiele\n\nDie ersten vier Beispiele arbeiten mit demselben konstruierten Datensatz: 270\nKunden mit den Merkmalen Besuche und Umsatz, aufgeteilt in drei eingebaute\nGruppen von 120, 90 und 60 Personen. Weil die Wahrheit bekannt ist, lässt sich\nprüfen, ob das Verfahren sie findet.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Warum standardisiert wird\n\n#### Frage und Datenlage\n\nBesuche werden in Anzahl gemessen, Umsatz in Franken. Was passiert, wenn man\ndiesen Unterschied ignoriert?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(apply(kunden, 2, var), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n besuche   umsatz \n    26.1 259477.9 \n```\n\n\n:::\n\n```{.r .cell-code}\nskaliert <- scale(kunden)\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nplot(kunden$besuche, kunden$umsatz, pch = 16, cex = 0.6, col = \"grey40\",\n     xlab = \"Besuche\", ylab = \"Umsatz\", main = \"Rohdaten\")\nplot(skaliert[, 1], skaliert[, 2], pch = 16, cex = 0.6, col = \"grey40\",\n     xlab = \"Besuche (z)\", ylab = \"Umsatz (z)\", main = \"standardisiert\")\npar(mfrow = c(1, 1))\n\n# Was ohne Standardisierung passiert\nohne <- kmeans(kunden, centers = 3, nstart = 25)\nround(ohne$centers, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  besuche umsatz\n1    13.2 1425.6\n2     3.1 2216.3\n3     7.5  922.8\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(ohne = ohne$cluster, eingebaut = gruppe_wahr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    eingebaut\nohne  A  B  C\n   1 98  1  6\n   2  1  0 54\n   3 21 89  0\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 1: links die Rohdaten, rechts die standardisierten.](k-means_files/figure-html/fig-b1-km-r-1.png){#fig-b1-km-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(kunden.var().round(1).to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'besuche': 26.1, 'umsatz': 259477.9}\n```\n\n\n:::\n\n```{.python .cell-code}\nskalierer = StandardScaler().fit(kunden)\nskaliert = skalierer.transform(kunden)\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.4))\nachsen[0].scatter(kunden[\"besuche\"], kunden[\"umsatz\"], s=8, color=\"0.4\")\nachsen[0].set_xlabel(\"Besuche\")\nachsen[0].set_ylabel(\"Umsatz\")\nachsen[0].set_title(\"Rohdaten\")\nachsen[1].scatter(skaliert[:, 0], skaliert[:, 1], s=8, color=\"0.4\")\nachsen[1].set_xlabel(\"Besuche (z)\")\nachsen[1].set_ylabel(\"Umsatz (z)\")\nachsen[1].set_title(\"standardisiert\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Gegenüberstellung in Python.](k-means_files/figure-html/fig-b1-km-py-1.png){#fig-b1-km-py width=100%}\n:::\n\n```{.python .cell-code}\nohne = KMeans(n_clusters=3, n_init=25, random_state=2026).fit(kunden)\nprint(pd.DataFrame(ohne.cluster_centers_, columns=kunden.columns).round(1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   besuche  umsatz\n0      3.1  2216.3\n1      7.5   922.8\n2     13.2  1425.6\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pd.crosstab(ohne.labels_, gruppe_wahr))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncol_0   A   B   C\nrow_0            \n0       1   0  54\n1      21  89   0\n2      98   1   6\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Varianz `besuche` | **26.1** | in Besuchen zum Quadrat |\n| Varianz `umsatz` | **259 478** | in Franken zum Quadrat |\n| Verhältnis | rund 1 zu 10 000 | Die euklidische Distanz addiert beide Quadrate. Der Beitrag der Besuche verschwindet dabei vollständig — k-Means würde ohne Standardisierung praktisch nur nach Umsatz trennen. |\n| Zentren ohne Standardisierung | 13.2 / 1426, 7.5 / 923, 3.1 / 2216 | Die Grenzen verlaufen praktisch senkrecht zur Umsatzachse. Dass die Besuchszahlen trotzdem verschieden sind, liegt nur daran, dass Umsatz und Besuche in diesen Daten zusammenhängen — nicht daran, dass die Besuche mitgerechnet hätten. |\n| Kreuztabelle ohne Standardisierung | **241 von 270** richtig zugeordnet | Mit Standardisierung sind es 263 (Beispiel 2). Vor allem die grösste eingebaute Gruppe zerfällt: 21 ihrer Mitglieder landen bei den Gelegenheitskunden, weil ihr Umsatz zufällig tiefer liegt. |\n| Linkes Bild | eine gestreckte Wolke | Die Achsen sind nicht vergleichbar, Abstände darin auch nicht. |\n| Rechtes Bild | drei erkennbare Punktwolken | Erst hier zählen beide Merkmale gleich viel. |\n\n::: {.note-box}\nStandardisierung ist bei k-Means keine Kosmetik, sondern **Teil der\nModellentscheidung**. Sie legt fest, dass beide Merkmale gleich wichtig sein\nsollen. Wer bewusst anders gewichten will, kann das tun — aber dann als\nbegründete Entscheidung und nicht als Nebenwirkung der Masseinheit.\n:::\n\n#### Interpretation\n\nDie Wahl der Skalierung gehört in den Methodenteil jedes Berichts. Verwendet\nwird hier die z-Standardisierung: von jedem Wert wird der Mittelwert abgezogen\nund durch die Standardabweichung geteilt. Weiteres dazu unter\n[Distanzmasse](distanzmasse.qmd).\n\n### Beispiel 2: Die Lösung mit drei Gruppen\n\n#### Frage und Datenlage\n\nDrei Gruppen, 25 Startwerte, standardisierte Daten. Findet das Verfahren die\neingebaute Struktur?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkm <- kmeans(skaliert, centers = 3, nstart = 25)\n\nkm$size\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  97  58 115\n```\n\n\n:::\n\n```{.r .cell-code}\nround(km$centers, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  besuche umsatz\n1  -0.547 -0.882\n2  -1.153  1.570\n3   1.042 -0.048\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(within = km$tot.withinss, between = km$betweenss,\n        anteil = km$betweenss / km$totss), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n within between  anteil \n 88.266 449.734   0.836 \n```\n\n\n:::\n\n```{.r .cell-code}\npar(mar = c(4, 4, 2, 1))\nplot(skaliert[, 1], skaliert[, 2], pch = 16, cex = 0.7,\n     col = c(\"#2166ac\", \"#b2182b\", \"#1b7837\")[km$cluster],\n     xlab = \"Besuche (z)\", ylab = \"Umsatz (z)\")\npoints(km$centers, pch = 4, cex = 2, lwd = 3)\n\n# Zentren zurueck in die Einheiten der Rohdaten\nzentren_roh <- t(t(km$centers) * attr(skaliert, \"scaled:scale\") +\n                   attr(skaliert, \"scaled:center\"))\nround(zentren_roh, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  besuche umsatz\n1     6.0  932.4\n2     2.9 2181.7\n3    14.1 1357.6\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(gefunden = km$cluster, eingebaut = gruppe_wahr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        eingebaut\ngefunden   A   B   C\n       1   5  90   2\n       2   0   0  58\n       3 115   0   0\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 2: gefundene Gruppen mit ihren Zentren (Kreuze).](k-means_files/figure-html/fig-b2-km-r-3.png){#fig-b2-km-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nkm = KMeans(n_clusters=3, n_init=25, random_state=2026).fit(skaliert)\n\nprint(\"Gruppengrössen:\", np.bincount(km.labels_))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGruppengrössen: [ 58  97 115]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pd.DataFrame(km.cluster_centers_, columns=kunden.columns).round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   besuche  umsatz\n0   -1.155   1.573\n1   -0.548  -0.884\n2    1.044  -0.048\n```\n\n\n:::\n\n```{.python .cell-code}\ngesamt = ((skaliert - skaliert.mean(axis=0)) ** 2).sum()\nprint({\"within\": round(float(km.inertia_), 3),\n       \"between\": round(float(gesamt - km.inertia_), 3),\n       \"anteil\": round(float((gesamt - km.inertia_) / gesamt), 3)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'within': 88.594, 'between': 451.406, 'anteil': 0.836}\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achse = plt.subplots()\nfor nummer, farbe in enumerate([\"#2166ac\", \"#b2182b\", \"#1b7837\"]):\n    teil = skaliert[km.labels_ == nummer]\n    achse.scatter(teil[:, 0], teil[:, 1], s=10, color=farbe,\n                  label=f\"Gruppe {nummer + 1}\")\nachse.scatter(km.cluster_centers_[:, 0], km.cluster_centers_[:, 1],\n              marker=\"x\", s=120, linewidths=3, color=\"black\")\nachse.set_xlabel(\"Besuche (z)\")\nachse.set_ylabel(\"Umsatz (z)\")\nachse.legend(frameon=False)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselbe Darstellung in Python.](k-means_files/figure-html/fig-b2-km-py-1.png){#fig-b2-km-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(pd.DataFrame(skalierer.inverse_transform(km.cluster_centers_),\n                   columns=kunden.columns).round(1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   besuche  umsatz\n0      2.9  2181.7\n1      6.0   932.4\n2     14.1  1357.6\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pd.crosstab(km.labels_, gruppe_wahr))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncol_0    A   B   C\nrow_0             \n0        0   0  58\n1        5  90   2\n2      115   0   0\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nDie drei Zentren, zurückgerechnet in die ursprünglichen Einheiten:\n\n| Grösse | Zentrum Besuche | Zentrum Umsatz | standardisiert (Besuche / Umsatz) |\n|---|---|---|---|\n| 115 | 14.1 | 1358 | 1.044 / -0.048 |\n| 97 | 6.0 | 932 | -0.548 / -0.884 |\n| 58 | 2.9 | 2182 | -1.155 / 1.573 |\n\n| Ausgabe | Wert hier | Bedeutung |\n|---|---|---|\n| Gruppengrössen | 115, 97, 58 | Die eingebauten Gruppen waren 120, 90 und 60 gross. Die Abweichung entsteht an den Rändern, wo sich die Wolken berühren. |\n| `within` | **88.594** in Python, **88.266** in R | Summe der quadrierten Abstände jeder Beobachtung zu ihrem Zentrum. Die Einheit ist die standardisierte Skala, ein absoluter Vergleich mit anderen Datensätzen ist damit sinnlos. Zur Differenz siehe den Kasten unten. |\n| `between` | 451.406 / 449.734 | Streuung zwischen den Zentren. |\n| `totss` | 540 / 538 | Die Gesamtstreuung. `within` und `between` addieren sich genau zu diesem Wert. |\n| Anteil `between/totss` | **0.836** in beiden Sprachen | 83.6 Prozent der Streuung liegen zwischen den Gruppen. Eine Kennzahl, **kein Gütesiegel**: Sie steigt mit jedem zusätzlichen k. |\n| Kreuztabelle | 263 von 270 richtig | Fünf Kunden der grössten Gruppe und zwei der kleinsten landen in der mittleren. Genau die Randfälle also, die im Bild zwischen zwei Wolken liegen. |\n\n::: {.note-box}\n**Warum R und Python hier um 0.4 Prozent auseinanderliegen:** `scale()` in R\nteilt durch die Stichproben-Standardabweichung mit dem Nenner $n-1$,\n`StandardScaler` in Python durch die mit dem Nenner $n$. Die standardisierten\nDaten unterscheiden sich damit um den Faktor $\\sqrt{n/(n-1)}$, alle quadrierten\nAbstände um $n/(n-1) = 270/269 = 1.0037$ — genau das Verhältnis von 88.594 zu\n88.266.\n\nDie Aufteilung selbst ist identisch, denn eine gemeinsame Streckung aller\nAbstände ändert nichts daran, welches Zentrum das nächste ist. Alle Verhältnisse\n— Anteil, Silhouette, Zentren in Originaleinheiten — stimmen deshalb überein.\nNur die absoluten Streuungswerte nicht, was ein weiteres Argument dafür ist, sie\nnie ohne ihren Bezugswert zu berichten.\n:::\n\n#### Interpretation und Ergebnissatz\n\nDie zurückgerechneten Zentren sind das, was ein Clustering überhaupt erst zu\neinem Ergebnis macht:\n\n| Gruppe | n | Besuche | Umsatz | Beschreibung |\n|---|---|---|---|---|\n| Stammkunden | 115 | 14.1 | 1358 | kommen oft, geben pro Jahr solide aus |\n| Gelegenheitskunden | 97 | 6.0 | 932 | kommen selten, geben wenig aus |\n| Grosseinkäufer | 58 | 2.9 | 2182 | kommen fast nie, kaufen dann aber viel |\n\nDie dritte Gruppe ist der interessante Befund: Wer nur auf den Umsatz geschaut\nhätte, hätte sie für die beste Kundengruppe gehalten; wer nur auf die Besuche\ngeschaut hätte, für die schlechteste. Erst beide Merkmale zusammen beschreiben\nsie.\n\n> Ein k-Means-Clustering auf Besuchen und Umsatz, z-standardisiert, mit k = 3\n> und 25 Startwerten (n = 270) ergibt Gruppen von 115, 97 und 58 Kunden. Die\n> Zentren liegen bei 14.1 Besuchen und 1358 Franken, 6.0 Besuchen und 932 Franken\n> sowie 2.9 Besuchen und 2182 Franken; die Aufteilung erklärt 83.6 Prozent der\n> Gesamtstreuung.\n\n### Beispiel 3: Warum k nicht aus der Streuung folgt\n\n#### Frage und Datenlage\n\nDie naheliegende Idee, k so zu wählen, dass die Streuung innerhalb der Gruppen\nklein wird, führt zuverlässig in die Irre. Die Rechnung zeigt, warum.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (k in 2:6) {\n  lauf <- kmeans(skaliert, centers = k, nstart = 25)\n  cat(\"k =\", k,\n      \"| within:\", round(lauf$tot.withinss, 1),\n      \"| Anteil erklaert:\", round(lauf$betweenss / lauf$totss, 3),\n      \"| kleinste Gruppe:\", min(lauf$size), \"\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nk = 2 | within: 257.3 | Anteil erklaert: 0.522 | kleinste Gruppe: 59 \nk = 3 | within: 88.3 | Anteil erklaert: 0.836 | kleinste Gruppe: 58 \nk = 4 | within: 71.2 | Anteil erklaert: 0.868 | kleinste Gruppe: 49 \nk = 5 | within: 60.9 | Anteil erklaert: 0.887 | kleinste Gruppe: 24 \nk = 6 | within: 51.7 | Anteil erklaert: 0.904 | kleinste Gruppe: 24 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ngesamt = ((skaliert - skaliert.mean(axis=0)) ** 2).sum()\nfor k in range(2, 7):\n    lauf = KMeans(n_clusters=k, n_init=25, random_state=2026).fit(skaliert)\n    print(f\"k = {k} | within: {lauf.inertia_:6.1f} \"\n          f\"| Anteil erklaert: {(gesamt - lauf.inertia_) / gesamt:.3f} \"\n          f\"| kleinste Gruppe: {np.bincount(lauf.labels_).min():3d} \"\n          f\"| Silhouette: {silhouette_score(skaliert, lauf.labels_):.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nk = 2 | within:  258.3 | Anteil erklaert: 0.522 | kleinste Gruppe:  59 | Silhouette: 0.554\nk = 3 | within:   88.6 | Anteil erklaert: 0.836 | kleinste Gruppe:  58 | Silhouette: 0.626\nk = 4 | within:   71.5 | Anteil erklaert: 0.868 | kleinste Gruppe:  49 | Silhouette: 0.506\nk = 5 | within:   61.1 | Anteil erklaert: 0.887 | kleinste Gruppe:  27 | Silhouette: 0.440\nk = 6 | within:   52.1 | Anteil erklaert: 0.903 | kleinste Gruppe:  24 | Silhouette: 0.441\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| k | within | Anteil erklärt | Zugewinn | kleinste Gruppe | Silhouette |\n|---|---|---|---|---|---|\n| 2 | 258.3 | 0.522 | — | 59 | 0.554 |\n| **3** | **88.6** | **0.836** | **+0.314** | 58 | **0.626** |\n| 4 | 71.5 | 0.868 | +0.032 | 49 | 0.506 |\n| 5 | 61.1 | 0.887 | +0.019 | 27 | 0.440 |\n| 6 | 52.1 | 0.903 | +0.016 | 24 | 0.441 |\n\n(Python-Ausgabe. R liefert dieselben Anteile, aber `within`-Werte, die um den im\nvorigen Beispiel erklärten Faktor 1.0037 tiefer liegen; ab k = 5 findet es\nausserdem eine leicht andere Aufteilung, weil dort mehrere fast gleich gute\nLösungen existieren — siehe Beispiel 4.)\n\nDrei Dinge stehen in dieser Tabelle:\n\n| Beobachtung | Was folgt |\n|---|---|\n| `within` sinkt **immer** | Bei k = n wäre sie null, denn jede Beobachtung wäre ihr eigenes Zentrum. Die Kennzahl kann k nicht begründen — sie zeigt nur an, dass mehr Zentren näher liegen. |\n| Der **Zugewinn** bricht nach k = 3 ein | Von 2 auf 3 kommen 31 Prozentpunkte dazu, von 3 auf 4 nur noch 3. Das ist der Knick, den die Ellenbogenmethode sucht. |\n| Die **Silhouette** hat ein Maximum bei k = 3 | Anders als `within` steigt sie nicht mechanisch mit k, sondern fällt wieder. Deshalb ist sie das brauchbarere Kriterium; ausführlich unter [Clustergüte](clusterguete.qmd). |\n\nDer Blick auf die kleinste Gruppe ergänzt das um ein praktisches Argument: Ab\nk = 5 entstehen Gruppen von 27 Kunden, die inhaltlich kaum mehr von ihren\nNachbarn zu unterscheiden sind.\n\n#### Interpretation und Ergebnissatz\n\n> Die Wahl von k stützt sich auf den Verlauf der Streuung innerhalb der Gruppen\n> (deutlicher Knick nach k = 3), auf die mittlere Silhouettenbreite (Maximum bei\n> k = 3 mit 0.63) und auf die inhaltliche Beschreibbarkeit der Gruppen.\n\n### Beispiel 4: Startwerte\n\n#### Frage und Datenlage\n\nk-Means findet ein lokales Minimum, nicht zwingend das beste. Wie stark das ins\nGewicht fällt, hängt davon ab, wie klar die Struktur ist — hier verglichen für\nk = 3 und k = 5.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvergleiche <- function(k) {\n  werte <- sapply(1:20, function(i) {\n    set.seed(i)\n    kmeans(skaliert, centers = k, nstart = 1)$tot.withinss\n  })\n  c(k = k, bester = min(werte), schlechtester = max(werte),\n    abstand_prozent = 100 * (max(werte) - min(werte)) / min(werte),\n    verschiedene = length(unique(round(werte, 3))))\n}\n\nround(rbind(vergleiche(3), vergleiche(5)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     k bester schlechtester abstand_prozent verschiedene\n[1,] 3 88.266        88.266            0.00            1\n[2,] 5 60.863        72.342           18.86           13\n```\n\n\n:::\n\n```{.r .cell-code}\n# mit 25 Startwerten\nround(c(k3 = kmeans(skaliert, 3, nstart = 25)$tot.withinss,\n        k5 = kmeans(skaliert, 5, nstart = 25)$tot.withinss), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    k3     k5 \n88.266 60.863 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndef vergleiche(k):\n    werte = [KMeans(n_clusters=k, n_init=1, random_state=i).fit(skaliert).inertia_\n             for i in range(20)]\n    return {\"k\": k, \"bester\": round(min(werte), 3),\n            \"schlechtester\": round(max(werte), 3),\n            \"abstand_prozent\": round(100 * (max(werte) - min(werte)) / min(werte), 1),\n            \"verschiedene\": len({round(w, 3) for w in werte})}\n\n\nprint(pd.DataFrame([vergleiche(3), vergleiche(5)]).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n k  bester  schlechtester  abstand_prozent  verschiedene\n 3  88.594         88.615              0.0             2\n 5  61.189         70.405             15.1            15\n```\n\n\n:::\n\n```{.python .cell-code}\nfor k in (3, 5):\n    print(f\"k = {k} mit 25 Startwerten:\",\n          round(KMeans(n_clusters=k, n_init=25,\n                       random_state=2026).fit(skaliert).inertia_, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nk = 3 mit 25 Startwerten: 88.594\nk = 5 mit 25 Startwerten: 61.145\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| k | bester Lauf | schlechtester Lauf | Abstand | verschiedene Lösungen |\n|---|---|---|---|---|\n| 3 (Python) | 88.594 | 88.615 | **0.0 %** | 2 |\n| 3 (R) | 88.266 | 88.266 | **0.0 %** | 1 |\n| 5 (Python) | 61.189 | 70.405 | **15.1 %** | 15 |\n| 5 (R) | 60.863 | 72.342 | **18.9 %** | 13 |\n\nDass die beiden Sprachen bei k = 5 verschiedene Zahlen zeigen, ist hier kein\nStörgeräusch, sondern die Aussage selbst: Bei k = 5 hängt das Ergebnis so stark\nvom Startwert ab, dass schon eine andere Reihenfolge der Startpunkte eine andere\nLösung liefert. Bei k = 3 stimmen beide auf die zweite Nachkommastelle überein.\n\n| Beobachtung | Was sie bedeutet |\n|---|---|\n| Bei k = 3 spielt der Startwert keine Rolle | Zwanzig Einzelläufe finden praktisch dieselbe Lösung. Wo die Struktur eindeutig ist, führt jeder Weg dorthin. |\n| Bei k = 5 landen zwanzig Läufe auf **13 bis 15 verschiedenen** Lösungen | Der schlechteste hat 15 bis 19 Prozent mehr Streuung innerhalb der Gruppen als der beste. Wer einmal rechnet und das Ergebnis berichtet, berichtet ein zufälliges Zwischenergebnis. |\n| Mit 25 Startwerten wird in beiden Fällen das Minimum gefunden | Die Software rechnet 25-mal und behält die beste Lösung. Der Aufwand ist bei dieser Datengrösse vernachlässigbar. |\n\n::: {.note-box}\nDer Zusammenhang lohnt es sich zu merken: **Instabilität gegenüber Startwerten\nist selbst ein Hinweis darauf, dass k zu gross gewählt ist.** Wo es echte Gruppen\ngibt, findet das Verfahren sie fast immer; wo es willkürlich teilt, hängt das\nErgebnis vom Zufall ab.\n:::\n\n#### Interpretation\n\n`nstart` beziehungsweise `n_init` wird immer ausdrücklich gesetzt. Die\nVoreinstellung ist in beiden Sprachen niedrig — in R genau eins — und hat sich in\nPython zwischen den Versionen geändert. Ein Wert von 25 ist üblich und praktisch\nimmer ausreichend.\n\n### Beispiel 5: Wenn die Form nicht passt\n\n#### Frage und Datenlage\n\nEin Datensatz mit zwei ineinander liegenden Ringen: 200 Punkte auf einem Kreis\nmit Radius 1, 200 auf einem mit Radius 3. Die Struktur ist für das Auge\noffensichtlich. Was macht k-Means daraus?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwinkel <- gleichwerte(777, 400, 0, 2 * pi)\nradius <- c(rep(1, 200), rep(3, 200)) + normalwerte(888, 400, 0, 0.15)\nringe <- data.frame(x = radius * cos(winkel), y = radius * sin(winkel))\nring_wahr <- rep(c(\"innen\", \"aussen\"), each = 200)\n\nkm_ringe <- kmeans(scale(ringe), centers = 2, nstart = 25)\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nplot(ringe$x, ringe$y, pch = 16, cex = 0.6,\n     col = ifelse(ring_wahr == \"innen\", \"#2166ac\", \"#b2182b\"),\n     xlab = \"x\", ylab = \"y\", main = \"wahre Struktur\")\nplot(ringe$x, ringe$y, pch = 16, cex = 0.6,\n     col = c(\"#2166ac\", \"#b2182b\")[km_ringe$cluster],\n     xlab = \"x\", ylab = \"y\", main = \"k-Means mit k = 2\")\npar(mfrow = c(1, 1))\n\ntable(gefunden = km_ringe$cluster, eingebaut = ring_wahr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        eingebaut\ngefunden aussen innen\n       1    102    72\n       2     98   128\n```\n\n\n:::\n\n```{.r .cell-code}\nround(km_ringe$betweenss / km_ringe$totss, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.336\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 5: links die wahre Struktur, rechts die Aufteilung durch k-Means.](k-means_files/figure-html/fig-b5-km-r-1.png){#fig-b5-km-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nwinkel = gleichwerte(777, 400, 0, 2 * np.pi)\nradius = np.concatenate([np.ones(200), np.full(200, 3.0)]) + \\\n    normalwerte(888, 400, 0, 0.15)\nringe = pd.DataFrame({\"x\": radius * np.cos(winkel), \"y\": radius * np.sin(winkel)})\nring_wahr = np.repeat([\"innen\", \"aussen\"], 200)\n\nring_skaliert = StandardScaler().fit_transform(ringe)\nkm_ringe = KMeans(n_clusters=2, n_init=25, random_state=7).fit(ring_skaliert)\n\nprint(pd.crosstab(km_ringe.labels_, ring_wahr))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncol_0  aussen  innen\nrow_0               \n0         102     72\n1          98    128\n```\n\n\n:::\n\n```{.python .cell-code}\nring_gesamt = ((ring_skaliert - ring_skaliert.mean(axis=0)) ** 2).sum()\nprint(\"Anteil erklärt:\",\n      round(float((ring_gesamt - km_ringe.inertia_) / ring_gesamt), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnteil erklärt: 0.336\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Silhouette:\",\n      round(silhouette_score(ring_skaliert, km_ringe.labels_), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSilhouette: 0.321\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nDie Kreuztabelle der gefundenen gegen die wahren Gruppen:\n\n| | aussen | innen |\n|---|---|---|\n| gefundene Gruppe 1 | 102 | 72 |\n| gefundene Gruppe 2 | 98 | 128 |\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Kreuztabelle | jede Zeile enthält beide Ringe | **Vollständiges Versagen.** Wären die Gruppen erkannt, stünde in jeder Zeile eine Null. Hier ist die Aufteilung fast eine Halbierung nach Zufall. |\n| Anteil erklärt | 0.336 | Niedriger als bei den Kundendaten, aber nicht auffällig niedrig. Für sich genommen liest sich der Wert wie ein mässiges, nicht wie ein falsches Ergebnis. |\n| Silhouette | 0.321 | Ebenfalls mittelmässig, nicht alarmierend. Werte um 0.3 werden gelegentlich als \"schwache Struktur\" gedeutet — und genau das ist die Falle. |\n\n::: {.note-box}\n**Keine Kennzahl zeigt diesen Fehler an.** k-Means hat getan, was es tun soll: die\nAbstandssumme minimiert. Der Raum wird dabei zwangsläufig durch gerade Linien in\nBereiche geteilt, und ein Ring lässt sich so nicht von einem anderen trennen —\nganz gleich, wie gross k gewählt wird.\n\nErkennbar ist der Fall nur im **Bild**.\n:::\n\n#### Interpretation und Ergebnissatz\n\nDas Vorgehen: Vor dem Clustering die Daten ansehen — bei zwei oder drei\nDimensionen direkt, bei mehr über die ersten\n[Hauptkomponenten](hauptkomponentenanalyse.qmd). Zeigen sich langgezogene,\nringförmige oder verschachtelte Formen, ist ein dichtebasiertes Verfahren wie\nDBSCAN die passende Wahl, oder ein hierarchisches mit Single-Linkage, das\nkettenförmige Strukturen zusammenfasst.\n\n> k-Means mit k = 2 trennt die beiden ringförmigen Gruppen nicht (jede gefundene\n> Gruppe enthält Punkte aus beiden Ringen, Silhouette 0.32). Für diese Struktur\n> wird ein dichtebasiertes Verfahren verwendet.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nNach dem Erhöhen von k von 3 auf 6 sinkt die Streuung innerhalb der Gruppen von\n88.6 auf 52.1. Ist die Lösung mit sechs Gruppen besser?\n\n- [ ] Ja, geringere Streuung heisst bessere Anpassung ~ Die Streuung sinkt\n      zwangsläufig mit jedem zusätzlichen k, bis sie bei k gleich n null ist.\n- [x] Nein, die Kennzahl kann k nicht begründen ~ Richtig. Herangezogen werden\n      der Knick im Verlauf, die Silhouette (die hier bei k = 3 ihr Maximum hat)\n      und die inhaltliche Beschreibbarkeit der Gruppen samt einer Mindestgrösse.\n- [ ] Das entscheidet der erklärte Anteil der Streuung ~ Der ist dieselbe\n      Kennzahl in anderer Form und steigt ebenfalls mit k.\n:::\n\n::: {.quiz}\nZwei Läufe mit identischen Daten liefern verschiedene Gruppennummern für\ndieselben Kunden. Ist das ein Fehler?\n\n- [x] Nein, die Nummerierung ist beliebig ~ Richtig. Nur die Aufteilung zählt.\n      Für Berichte werden die Gruppen nach einem inhaltlichen Merkmal sortiert und\n      benannt, damit sie über Läufe hinweg wiedererkennbar sind.\n- [ ] Ja, das Verfahren ist instabil ~ Instabilität zeigt sich in\n      unterschiedlichen Aufteilungen, nicht in vertauschten Nummern.\n- [ ] Ja, es fehlt ein Startwert ~ Ein fester Startwert macht die Nummerierung\n      reproduzierbar, sie bleibt aber inhaltlich bedeutungslos.\n:::\n\n::: {.quiz}\nZwanzig Läufe mit je einem Startwert liefern bei k = 3 zwei praktisch identische\nLösungen, bei k = 5 aber fünfzehn verschiedene. Was lässt sich daraus ablesen?\n\n- [x] Dass drei Gruppen in den Daten stecken und fünf nicht ~ Richtig. Wo echte\n      Struktur vorliegt, führt fast jeder Startwert dorthin. Instabilität\n      gegenüber Startwerten ist selbst ein Hinweis, dass k zu gross gewählt ist.\n- [ ] Dass bei k = 5 zu wenige Läufe gerechnet wurden ~ Mehr Startwerte finden\n      zwar das Minimum, ändern aber nichts daran, dass die Aufteilung willkürlich\n      ist.\n- [ ] Dass die Daten nicht standardisiert waren ~ Sie waren es; die\n      Standardisierung betrifft die Gewichtung der Merkmale, nicht die Startwerte.\n:::\n\n::: {.quiz}\nEin Datensatz enthält zwei ineinander liegende ringförmige Gruppen. k-Means mit\nk gleich zwei liefert eine Silhouette von 0.32. Was ist passiert?\n\n- [x] Der Raum wurde geradlinig geteilt, die Ringe wurden zerschnitten ~ Richtig.\n      k-Means minimiert Abstände zu Zentren und erzeugt dadurch geradlinig\n      begrenzte Bereiche. Ringförmige Strukturen kann es grundsätzlich nicht\n      finden; die Kennzahlen zeigen das nicht an, sie sehen bloss mittelmässig aus.\n- [ ] Die Daten waren nicht standardisiert ~ Standardisierung ändert an der Form\n      der Gruppen nichts.\n- [ ] k war zu klein gewählt ~ Auch mit grösserem k entstehen geradlinig\n      begrenzte Stücke, keine Ringe.\n:::\n\n::: {.quiz}\nWarum werden die Zentren für den Bericht zurückgerechnet?\n\n- [x] Weil sie in Standardabweichungen nicht deutbar sind ~ Richtig. Ein Zentrum\n      bei 1.04 Standardabweichungen sagt niemandem etwas; 14.1 Besuche und 1358\n      Franken Umsatz beschreiben das Segment.\n- [ ] Weil die Standardisierung das Ergebnis verfälscht ~ Sie ist notwendig für\n      die Gruppierung, nur nicht für die Darstellung.\n- [ ] Weil die Zentren sonst nicht vergleichbar sind ~ Vergleichbar sind sie in\n      beiden Skalen; deutbar nur in der ursprünglichen.\n:::\n\n## Verlinkte Ressourcen\n\n- [An Introduction to Statistical Learning, Kapitel 12.4](https://www.statlearning.com/)\n- [R-Dokumentation zu `kmeans`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/kmeans.html)\n- [scikit-learn: KMeans](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html)\n",
    "supporting": [
      "k-means_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}