{
  "hash": "49b26958d53ffbb1ee3027be60a7bf3b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multiple lineare Regression\"\ndescription: \"Mehrere Prädiktoren, adjustiertes R², Multikollinearität und wie man den Output liest.\"\ncategories: [\"Regression\", \"Modelldiagnostik\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\", \"ESDS\"]\nseitentyp: methode\nstand: entwurf\norder: 20\n---\n\n\n\n\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Wie hängt eine metrische Zielgrösse gleichzeitig von mehreren Einflussgrössen ab, und wie gross ist der Beitrag jeder einzelnen bei konstant gehaltenen anderen? |\n| Zielvariable | metrisch (intervall- oder verhältnisskaliert) |\n| Prädiktoren | zwei oder mehr, metrisch oder kategorial (kategoriale werden zu Indikatorvariablen) |\n| Was die Methode liefert | Koeffizienten mit Standardfehlern, Konfidenzintervallen und p-Werten, R² und adjustiertes R², F-Test des Gesamtmodells, Residuen für die Diagnostik |\n| R-Funktion | `lm(y ~ x1 + x2, data = df)`, gelesen mit `summary()`, `confint()`, `car::vif()` |\n| Python-Funktion | `smf.ols(\"y ~ x1 + x2\", data=df).fit()`, gelesen mit `.summary()`, `.conf_int()`, `variance_inflation_factor()` |\n| Verwandte Methoden | [einfache lineare Regression](einfache-lineare-regression.qmd), [logistische Regression](logistische-regression.qmd), Varianzanalyse |\n\n## Wann diese Methode, wann nicht\n\nTypische Fragestellungen: Miete aus Fläche und Alter einer Wohnung, Absatz aus\nPreis und Werbebudget, Laborwert aus Dosis und Körpergewicht. Gemeinsam ist\nihnen, dass die Zielgrösse metrisch ist, dass mehrere Einflussgrössen zugleich\nwirken und dass der Beitrag einer einzelnen Grösse interessiert, gerade weil die\nanderen mit ihr zusammenhängen.\n\nDie Methode passt, wenn der Zusammenhang in den Prädiktoren annähernd linear\nist, die Beobachtungen unabhängig sind und die Streuung der Residuen über den\nVorhersagebereich ungefähr gleich bleibt.\n\nSie passt nicht in diesen Fällen:\n\n| Situation | Stattdessen |\n|---|---|\n| Zielvariable binär | [logistische Regression](logistische-regression.qmd) |\n| Zielvariable ist eine Zeit bis zu einem Ereignis mit zensierten Fällen | [Kaplan-Meier](../ueberlebenszeit/kaplan-meier.qmd) und [Cox-Modell](../ueberlebenszeit/cox-modell.qmd) |\n| Nur ein Prädiktor | [einfache lineare Regression](einfache-lineare-regression.qmd) |\n| Beobachtungen sind zeitlich geordnet und autokorreliert | [Zeitreihenmodelle](../zeitreihen/arima-sarima.qmd) |\n| Erkennbar krummer Zusammenhang | Transformation der Variablen oder Polynomterme im Modell |\n| Deutlich ungleiche Residuenstreuung | robuste Standardfehler oder Transformation der Zielvariable |\n\n## Grundidee und Modell\n\nGesucht ist die Ebene beziehungsweise Hyperebene, die möglichst nah an allen\nbeobachteten Punkten liegt. Nah bedeutet: die Summe der quadrierten senkrechten\nAbstände zwischen beobachteten und vorhergesagten Werten ist minimal. Das\nQuadrieren gewichtet grosse Abweichungen stärker und macht die Lösung eindeutig\nberechenbar.\n\n$$y_i = \\beta_0 + \\beta_1 x_{i1} + \\beta_2 x_{i2} + \\dots + \\beta_k x_{ik} + \\varepsilon_i$$\n\n| Bestandteil | Bedeutung |\n|---|---|\n| $y_i$ | beobachteter Wert der Zielvariable bei Beobachtung $i$ |\n| $\\beta_0$ | Achsenabschnitt, erwarteter Wert von $y$, wenn alle Prädiktoren null sind |\n| $\\beta_j$ | erwartete Änderung von $y$, wenn $x_j$ um eine Einheit steigt und alle anderen Prädiktoren konstant bleiben |\n| $x_{ij}$ | Wert des $j$-ten Prädiktors bei Beobachtung $i$ |\n| $\\varepsilon_i$ | Residuum, der von keinem Prädiktor erfasste Rest, mit Erwartungswert null und konstanter Varianz |\n\nGeschätzt wird mit der Methode der kleinsten Quadrate. Sie hat eine\ngeschlossene Lösung, es wird also nicht iteriert und es gibt keine\nKonvergenzprobleme. Entscheidend für die Interpretation ist die Wendung \"bei\nkonstant gehaltenen anderen Prädiktoren\": jeder Koeffizient beschreibt den\nBeitrag seiner Variable, nachdem der Einfluss der übrigen herausgerechnet ist.\nDeshalb kann sich ein Koeffizient beim Hinzufügen einer weiteren Variablen\ndeutlich ändern, und deshalb ist er nicht dasselbe wie eine einfache Korrelation.\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung | Vorgehen |\n|---|---|---|---|---|\n| Linearität | Der Zusammenhang jedes Prädiktors mit der Zielgrösse ist geradlinig | Residuen gegen vorhergesagte Werte, gekrümmtes Muster ist verdächtig | Koeffizienten sind systematisch verzerrt, Vorhersagen in den Randbereichen falsch | Transformation, Polynomterm oder Aufteilung in Bereiche |\n| Unabhängigkeit | Beobachtungen beeinflussen sich nicht gegenseitig | aus dem Erhebungsdesign, bei zeitlicher Ordnung Durbin-Watson | Standardfehler zu klein, p-Werte zu optimistisch | Mehrebenenmodell oder Zeitreihenmodell |\n| Homoskedastizität | Residuenstreuung ist über den Vorhersagebereich konstant | Residuenplot, Breusch-Pagan-Test | Schätzwerte bleiben brauchbar, Standardfehler und p-Werte nicht | robuste Standardfehler oder Transformation |\n| Normalverteilte Residuen | Die Residuen streuen annähernd normal | QQ-Plot der Residuen | betrifft vor allem Tests und Intervalle bei kleinem n, bei grossem n unkritisch | Transformation, Bootstrap |\n| Keine starke Multikollinearität | Prädiktoren sind nicht nahezu Linearkombinationen voneinander | VIF, Werte über 5 sind auffällig, über 10 kritisch | einzelne Koeffizienten instabil und nicht signifikant, obwohl das Modell gut passt | eine Variable entfernen oder zusammenfassen |\n| Keine einflussreichen Einzelfälle | Kein einzelner Punkt bestimmt das Ergebnis | Cook-Distanz, Hebelwerte | Koeffizient hängt an einer Beobachtung | Fall prüfen, Modell mit und ohne ihn berichten |\n\n## Output lesen\n\nR, `summary(modell)`:\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| `Call` | die geschätzte Modellformel | prüfen, ob wirklich das gemeinte Modell gerechnet wurde |\n| `Residuals` | Minimum, Quartile, Median der Residuen | Median deutlich neben null oder stark unsymmetrische Extreme deuten auf Schieflage |\n| `Estimate` | geschätzter Koeffizient | Änderung von y je Einheit von x bei konstant gehaltenen anderen Prädiktoren, in den Einheiten der Variablen |\n| `Std. Error` | Standardfehler des Koeffizienten | Unsicherheit der Schätzung, wächst mit der Streuung und mit Multikollinearität |\n| `t value` | Estimate geteilt durch Std. Error | Werte über etwa 2 in Betrag sind bei üblichem n signifikant |\n| `Pr(>|t|)` | p-Wert des Tests, dass der Koeffizient null ist | prüft nur den einzelnen Koeffizienten, sagt nichts über die Grösse des Effekts |\n| `(Intercept)` | erwartete Miete bei Fläche 0 und Alter 0 | oft ohne inhaltliche Bedeutung, weil der Punkt ausserhalb der Daten liegt |\n| `Residual standard error` | typische Abweichung einer Vorhersage in der Einheit von y | die direkt interpretierbare Gütezahl, hier vergleichbar mit dem simulierten Rauschen |\n| Freiheitsgrade | n minus Anzahl geschätzter Parameter | sinken mit jedem zusätzlichen Prädiktor |\n| `Multiple R-squared` | Anteil der erklärten Streuung | steigt mit jedem Prädiktor, auch mit einem sinnlosen |\n| `Adjusted R-squared` | um die Anzahl Prädiktoren korrigiert | die Zahl, die man beim Modellvergleich liest |\n| `F-statistic` mit p-Wert | Test, ob das Modell insgesamt besser ist als der Mittelwert | signifikant, ohne dass ein einzelner Koeffizient signifikant sein muss, typisch bei Multikollinearität |\n| `confint()` | 95-Prozent-Intervall je Koeffizient | schliesst es null ein, ist der Koeffizient nicht signifikant |\n\nPython, `modell.summary()`, mit den Unterschieden zu R:\n\n| Grösse | Was sie sagt | Unterschied zu R |\n|---|---|---|\n| `coef`, `std err`, `t`, `P>|t|` | wie Estimate, Std. Error, t value, Pr(>|t|) | nur andere Bezeichnung |\n| `[0.025 0.975]` | Konfidenzintervall | steht direkt in der Tabelle, in R braucht es `confint()` |\n| `R-squared`, `Adj. R-squared` | wie in R | identisch berechnet |\n| `F-statistic`, `Prob (F-statistic)` | Gesamttest | identisch |\n| `Df Residuals`, `Df Model` | Freiheitsgrade | R nennt sie im Fliesstext, Python in eigenen Zeilen |\n| `AIC`, `BIC`, `Log-Likelihood` | Kennzahlen für den Modellvergleich | R zeigt sie nicht in `summary()`, dort über `AIC(modell)` |\n| `Omnibus`, `Jarque-Bera`, `Skew`, `Kurtosis` | Tests und Masse zur Normalität der Residuen | in R nicht enthalten, dort über den QQ-Plot |\n| `Durbin-Watson` | Hinweis auf Autokorrelation der Residuen | Werte um 2 sind unauffällig, in R über `dwtest()` |\n| `Cond. No.` | Konditionszahl der Prädiktormatrix | grosse Werte deuten auf Multikollinearität, ergänzend zum VIF |\n| Kein `Residual standard error` | die Grösse fehlt in der Tabelle | über `np.sqrt(modell.mse_resid)` |\n\nAusgelassen wird kein Wert: auch Freiheitsgrade, Residualstreuung und die\nNormalitätskennzahlen gehören zur Beurteilung, und Warnhinweise am Fuss der\nPython-Tabelle sind Teil des Ergebnisses.\n\n## Interpretationsfallen\n\n- **Signifikanz ist keine Relevanz.** Bei grossem n wird ein Koeffizient von\n  0.4 Einheiten pro Quadratmeter signifikant, ohne für eine Mietentscheidung\n  eine Rolle zu spielen. Relevanz liest man am Schätzwert in seiner Einheit, an\n  seinem Intervall und an der Residualstreuung.\n- **Der p-Wert ist keine Wahrscheinlichkeit für die Nullhypothese.** Er ist die\n  Wahrscheinlichkeit dieser oder extremerer Daten, wenn der Koeffizient null\n  wäre. Siehe [Hypothesentests: Grundlagen](../inferenz/hypothesentests-grundlagen.qmd).\n- **R² ist keine Modellrichtigkeit.** Ein Modell mit falscher Struktur kann ein\n  hohes R² haben, und ein korrektes Modell für stark streuende Daten ein\n  niedriges. R² steigt zudem mit jedem zusätzlichen Prädiktor; für Vergleiche\n  gilt das adjustierte R².\n- **Ein Koeffizient ist keine Kausalität.** \"Bei konstant gehaltenen anderen\n  Prädiktoren\" heisst konstant gehalten unter den aufgenommenen Variablen. Eine\n  nicht erhobene gemeinsame Ursache bleibt im Modell unsichtbar und verzerrt den\n  Koeffizienten.\n- **Das Konfidenzintervall ist keine Wahrscheinlichkeitsaussage über den wahren\n  Wert.** Das Verfahren trifft in 95 Prozent aller Anwendungen den wahren Wert;\n  das konkrete Intervall enthält ihn oder nicht.\n- **Der Achsenabschnitt ist selten interpretierbar.** Fläche null und Alter null\n  kommt in den Daten nicht vor. Wer den Achsenabschnitt deuten will, zentriert\n  die Prädiktoren.\n- **Vorhersagen nur im beobachteten Bereich.** Ausserhalb der Datenspanne ist\n  die Linearität nicht geprüft und die Vorhersage eine Behauptung.\n\n## Ergebnis berichten\n\nVorlage für den Ergebnissatz:\n\n> Ein multiples lineares Modell mit [Prädiktoren] erklärt [Zielvariable]\n> (F([Df Model], [Df Residuals]) = [F], p = [p], adjustiertes R² = [Wert],\n> n = [n]). Bei konstant gehaltenen übrigen Prädiktoren steigt [Zielvariable]\n> pro Einheit [Prädiktor] um [Schätzwert] [Einheit]\n> (95-Prozent-Konfidenzintervall [unten] bis [oben], p = [p]).\n\nImmer genannt werden: Schätzwert in seiner Einheit, Konfidenzintervall,\nTeststatistik mit Freiheitsgraden, p-Wert, adjustiertes R² und n, dazu die\nResidualstreuung, wenn es um Vorhersagegüte geht. Genannt wird ausserdem, welche\nVoraussetzungen geprüft wurden und mit welchem Ergebnis.\n\nBeispiel für eine Ergebnistabelle:\n\n| Prädiktor | Schätzwert | Standardfehler | 95-Prozent-Intervall | p |\n|---|---|---|---|---|\n| Achsenabschnitt | | | | |\n| Fläche (m²) | | | | |\n| Alter (Jahre) | | | | |\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt der multiplen linearen Regression |\n|---|---|\n| [Einfache lineare Regression](einfache-lineare-regression.qmd) | genau ein Prädiktor, keine Kontrolle weiterer Grössen nötig |\n| [Logistische Regression](logistische-regression.qmd) | binäre Zielvariable |\n| [Regressionsdiagnostik](regressionsdiagnostik.qmd) | Vertiefung zu Residuen, Hebelwerten, Ausreissern und VIF |\n| [Modellauswahl](modellauswahl.qmd) | Vergleich mehrerer Modelle, AIC, Validierung |\n| Varianzanalyse | nur kategoriale Prädiktoren, Frage nach Gruppenunterschieden; rechnerisch ein Spezialfall dieses Modells |\n| [Cox-Modell](../ueberlebenszeit/cox-modell.qmd) | Zielvariable ist eine Zeit bis zu einem Ereignis mit zensierten Fällen |\n\n## Beispiele\n\nAlle Beispiele rechnen mit demselben Datensatz aus dem Setup-Chunk: 120\nWohnungen mit Miete, Fläche, Alter, Stockwerk, Zimmerzahl und Lage. Die Daten\nsind deterministisch konstruiert, damit R und Python dieselben Zahlen sehen und\njeder Wert im Text nachprüfbar ist.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Miete aus Fläche und Alter\n\n#### Frage und Datenlage\n\nVon 120 Wohnungen liegen Miete in Franken, Wohnfläche in Quadratmetern und\nAlter in Jahren vor. Die Frage lautet: Wie viel kostet ein zusätzlicher\nQuadratmeter, **wenn das Alter konstant gehalten wird**, und wie viel kostet\nein zusätzliches Jahr Alter bei gleicher Fläche?\n\nGenau dieses \"bei konstant gehaltenen anderen\" ist der Grund für die multiple\nRegression. Zwei getrennte einfache Regressionen könnten die Frage nicht\nbeantworten, sobald Fläche und Alter zusammenhängen.\n\n#### Voraussetzungen prüfen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodell <- lm(miete ~ flaeche + alter, data = wohnung)\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nplot(modell, which = 1)\nplot(modell, which = 2)\npar(mfrow = c(1, 1))\n\nbptest(modell)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  modell\nBP = 1.9986, df = 2, p-value = 0.3681\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(modell)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n flaeche    alter \n1.000488 1.000488 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 1: Residuen gegen Vorhersage und QQ-Plot der Residuen.](multiple-lineare-regression_files/figure-html/fig-b1-mlr-voraussetzungen-r-1.png){#fig-b1-mlr-voraussetzungen-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmodell = smf.ols(\"miete ~ flaeche + alter\", data=wohnung).fit()\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nachsen[0].scatter(modell.fittedvalues, modell.resid, s=14, color=\"0.3\")\nachsen[0].axhline(0, linestyle=\"--\", color=\"black\")\nachsen[0].set_xlabel(\"Vorhersage\")\nachsen[0].set_ylabel(\"Residuum\")\nsm.qqplot(modell.resid, line=\"s\", ax=achsen[1])\nachsen[1].set_title(\"QQ-Plot der Residuen\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Diagnostik in Python.](multiple-lineare-regression_files/figure-html/fig-b1-mlr-voraussetzungen-py-1.png){#fig-b1-mlr-voraussetzungen-py width=100%}\n:::\n\n```{.python .cell-code}\nlm_wert, lm_p = sm.stats.diagnostic.het_breuschpagan(\n    modell.resid, modell.model.exog)[:2]\nprint(\"Breusch-Pagan LM =\", round(lm_wert, 4), \" p =\", round(lm_p, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBreusch-Pagan LM = 1.9986  p = 0.3681\n```\n\n\n:::\n\n```{.python .cell-code}\nX = sm.add_constant(wohnung[[\"flaeche\", \"alter\"]])\nprint({name: round(variance_inflation_factor(X.values, i), 3)\n       for i, name in enumerate(X.columns)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'const': np.float64(1.0), 'flaeche': np.float64(1.0), 'alter': np.float64(1.0)}\n```\n\n\n:::\n:::\n\n\n:::\n\nDie Residuen streuen strukturlos um die Nulllinie, der QQ-Plot zeigt keine\nauffällige Abweichung, und der Breusch-Pagan-Test liefert p = 0.37, also keinen\nHinweis auf ungleiche Streuung. Die VIF-Werte liegen bei 1.0: Fläche und Alter\nhängen in diesen Daten praktisch nicht zusammen (r = 0.02), jede der beiden\nGrössen trägt also eigene Information bei.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(modell)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = miete ~ flaeche + alter, data = wohnung)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-509.46 -172.09  -11.12  178.36  528.85 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  422.547    104.265   4.053 9.15e-05 ***\nflaeche       12.097      1.170  10.340  < 2e-16 ***\nalter         -3.231      1.429  -2.261   0.0256 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 229.4 on 117 degrees of freedom\nMultiple R-squared:  0.4869,\tAdjusted R-squared:  0.4782 \nF-statistic: 55.52 on 2 and 117 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(modell)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %      97.5 %\n(Intercept) 216.056164 629.0376043\nflaeche       9.779666  14.4135906\nalter        -6.059770  -0.4013821\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(modell.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                            OLS Regression Results                            \n==============================================================================\nDep. Variable:                  miete   R-squared:                       0.487\nModel:                            OLS   Adj. R-squared:                  0.478\nMethod:                 Least Squares   F-statistic:                     55.52\nDate:                Thu, 10 Sep 2026   Prob (F-statistic):           1.11e-17\nTime:                        13:19:42   Log-Likelihood:                -820.98\nNo. Observations:                 120   AIC:                             1648.\nDf Residuals:                     117   BIC:                             1656.\nDf Model:                           2                                         \nCovariance Type:            nonrobust                                         \n==============================================================================\n                 coef    std err          t      P>|t|      [0.025      0.975]\n------------------------------------------------------------------------------\nIntercept    422.5469    104.265      4.053      0.000     216.056     629.038\nflaeche       12.0966      1.170     10.340      0.000       9.780      14.414\nalter         -3.2306      1.429     -2.261      0.026      -6.060      -0.401\n==============================================================================\nOmnibus:                        4.127   Durbin-Watson:                   2.562\nProb(Omnibus):                  0.127   Jarque-Bera (JB):                2.380\nSkew:                           0.083   Prob(JB):                        0.304\nKurtosis:                       2.330   Cond. No.                         435.\n==============================================================================\n\nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Residualstreuung:\", round(np.sqrt(modell.mse_resid), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nResidualstreuung: 229.3513\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| `(Intercept)` | 422.55 | erwartete Miete bei Fläche null und Alter null | Rechnerisch nötig, inhaltlich sinnlos: Eine Wohnung mit null Quadratmetern gibt es nicht. Wer eine deutbare Zahl braucht, zentriert die Prädiktoren. |\n| `flaeche` Estimate | 12.10 | Franken je Quadratmeter, **bei gleichem Alter** | Die zentrale Zahl. Der Zusatz \"bei gleichem Alter\" ist kein Beiwerk, sondern die eigentliche Leistung der multiplen Regression. |\n| `flaeche` Std. Error | 1.170 | Unsicherheit dieser Schätzung | Rund ein Zehntel des Schätzwerts. |\n| `flaeche` t value | 10.340 | Schätzwert durch Standardfehler | |\n| `flaeche` Pr(>&#124;t&#124;) | < 0.001 | p-Wert für \"der Koeffizient ist null\" | |\n| `alter` Estimate | -3.23 | Franken je Jahr, **bei gleicher Fläche** | Ältere Wohnungen sind bei gleicher Fläche günstiger. |\n| `alter` Std. Error | 1.429 | | Fast die Hälfte des Schätzwerts, die Schätzung ist also viel unsicherer als die der Fläche. |\n| `alter` Pr(>&#124;t&#124;) | 0.026 | | Signifikant, aber knapp. |\n| Konfidenzintervall `flaeche` | 9.78 bis 14.41 | plausibler Bereich | Rund fünf Franken breit. |\n| Konfidenzintervall `alter` | -6.06 bis -0.40 | plausibler Bereich | Die aufschlussreichste Zeile der ganzen Ausgabe: Der Alterseffekt liegt irgendwo zwischen 40 Rappen und gut sechs Franken je Jahr. Das ist ein Faktor von 15. Der p-Wert von 0.026 verdeckt diese Unsicherheit vollständig. |\n| `Residual standard error` | 229.35 auf 117 Freiheitsgraden | typischer Vorhersagefehler in Franken | Die praktisch nützlichste Gütezahl. Wer eine Miete aus Fläche und Alter vorhersagt, liegt typischerweise um 229 Franken daneben. |\n| Freiheitsgrade | 117 | n minus Anzahl Parameter | 120 minus 3, also Achsenabschnitt plus zwei Koeffizienten. |\n| `Multiple R-squared` | 0.4869 | Anteil erklärter Streuung | Knapp die Hälfte. |\n| `Adjusted R-squared` | 0.4782 | um die Parameterzahl korrigiert | Der Abstand zu R² wächst mit jedem zusätzlichen Prädiktor, siehe Beispiel 2. |\n| `F-statistic` | 55.5 auf 2 und 117 df | Gesamttest | Prüft, ob **alle** Koeffizienten zugleich null sind. Bei mehreren Prädiktoren ist er nicht mehr redundant zu den t-Tests. |\n\n#### Interpretation und Ergebnissatz\n\nDie beiden Koeffizienten sind sehr unterschiedlich gut bestimmt, obwohl beide\nsignifikant sind. Bei der Fläche ist der Effekt auf rund fünf Franken genau\neingegrenzt; beim Alter reicht das Intervall über einen Faktor 15. Wer nur die\np-Werte liest, sieht diesen Unterschied nicht.\n\nUnd die Residualstreuung von 229 Franken setzt den Rahmen: Für die Bewertung\neiner einzelnen Wohnung ist das Modell zu ungenau. Für die Aussage \"ein\nQuadratmeter kostet rund zwölf Franken\" reicht es.\n\n> Fläche und Alter erklären zusammen 49 Prozent der Mietunterschiede\n> (F(2, 117) = 55.5, p < 0.001, n = 120). Je Quadratmeter steigt die Miete um\n> 12.10 Franken (95-Prozent-Konfidenzintervall 9.78 bis 14.41, p < 0.001), je\n> Jahr Alter sinkt sie um 3.23 Franken (-6.06 bis -0.40, p = 0.026), jeweils bei\n> konstant gehaltener anderer Grösse. Die typische Abweichung einer Vorhersage\n> beträgt 229 Franken.\n\n### Beispiel 2: Ein Prädiktor ohne Beitrag\n\n#### Frage und Datenlage\n\nDem Modell wird das Stockwerk hinzugefügt. Die Frage lautet: Trägt es etwas\nbei?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodell_stock <- lm(miete ~ flaeche + alter + stockwerk, data = wohnung)\nsummary(modell_stock)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = miete ~ flaeche + alter + stockwerk, data = wohnung)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-509.46 -172.41  -11.01  178.23  528.75 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 422.8675   111.9744   3.776 0.000252 ***\nflaeche      12.0966     1.1750  10.295  < 2e-16 ***\nalter        -3.2300     1.4364  -2.249 0.026423 *  \nstockwerk    -0.1122    13.8812  -0.008 0.993564    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 230.3 on 116 degrees of freedom\nMultiple R-squared:  0.4869,\tAdjusted R-squared:  0.4737 \nF-statistic:  36.7 on 3 and 116 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(modell, modell_stock)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: miete ~ flaeche + alter\nModel 2: miete ~ flaeche + alter + stockwerk\n  Res.Df     RSS Df Sum of Sq     F Pr(>F)\n1    117 6154434                          \n2    116 6154430  1    3.4668 1e-04 0.9936\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmodell_stock = smf.ols(\"miete ~ flaeche + alter + stockwerk\",\n                       data=wohnung).fit()\nprint(modell_stock.summary().tables[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n==============================================================================\n                 coef    std err          t      P>|t|      [0.025      0.975]\n------------------------------------------------------------------------------\nIntercept    422.8675    111.974      3.776      0.000     201.088     644.647\nflaeche       12.0966      1.175     10.295      0.000       9.769      14.424\nalter         -3.2300      1.436     -2.249      0.026      -6.075      -0.385\nstockwerk     -0.1122     13.881     -0.008      0.994     -27.606      27.381\n==============================================================================\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"R^2:\", round(modell_stock.rsquared, 4),\n      \" adj. R^2:\", round(modell_stock.rsquared_adj, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR^2: 0.4869  adj. R^2: 0.4737\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(sm.stats.anova_lm(modell, modell_stock).round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   df_resid           ssr  df_diff  ss_diff       F  Pr(>F)\n0     117.0  6.154434e+06      0.0      NaN     NaN     NaN\n1     116.0  6.154430e+06      1.0   3.4668  0.0001  0.9936\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Ohne Stockwerk | Mit Stockwerk | Wie das zu lesen ist |\n|---|---|---|---|\n| `stockwerk` Estimate | | -0.11 | Elf Rappen je Stockwerk. Praktisch null. |\n| `stockwerk` Std. Error | | 13.881 | Der Standardfehler ist mehr als hundertmal so gross wie der Schätzwert. |\n| `stockwerk` p-Wert | | 0.994 | So gross, wie ein p-Wert kaum werden kann. |\n| Konfidenzintervall | | -27.6 bis 27.4 | Symmetrisch um null und knapp 55 Franken breit. Das Stockwerk könnte durchaus 25 Franken wert sein, in beide Richtungen; ausgeschlossen ist nur ein sehr grosser Effekt. |\n| `Multiple R-squared` | 0.4869 | 0.4869 | Unverändert in der vierten Stelle. |\n| `Adjusted R-squared` | 0.4782 | 0.4737 | **Gesunken.** Das ist der Unterschied zwischen den beiden Massen. |\n| `Residual standard error` | 229.35 | 230.34 | Ebenfalls leicht schlechter geworden. |\n| Modellvergleich `anova()` | | F = 0.0001, p = 0.994 | Derselbe Test wie der t-Test des Koeffizienten; bei einem einzelnen zusätzlichen Prädiktor sind sie gleichwertig, und F ist exakt t². |\n\n::: {.note-box}\n**Warum R² nicht sinken kann und adjustiertes R² schon.** R² misst, wie viel\nStreuung das Modell erklärt, und ein zusätzlicher Prädiktor kann diesen Anteil\nnie verringern: Im schlechtesten Fall bekommt er den Koeffizienten null. Deshalb\nist R² für den Vergleich von Modellen mit verschieden vielen Prädiktoren\nunbrauchbar.\n\nDas adjustierte R² zieht für jeden Parameter einen Betrag ab. Trägt ein\nPrädiktor weniger bei, als dieser Abzug ausmacht, sinkt es. Genau das ist hier\npassiert, und deshalb ist es die Zahl, die man beim Modellvergleich ansieht,\nsiehe [Modellauswahl](modellauswahl.qmd).\n:::\n\n#### Interpretation und Ergebnissatz\n\nDer Prädiktor wird entfernt, aber nicht wegen des p-Werts allein. Die\nEntscheidung stützt sich auf drei Dinge: kein erkennbarer Beitrag zur erklärten\nStreuung, ein gesunkenes adjustiertes R², und ein Konfidenzintervall, das keinen\npraktisch bedeutsamen Effekt nahelegt.\n\nWäre das Intervall stattdessen von -5 bis +120 Franken gegangen, wäre \"kein\nEffekt nachweisbar\" die falsche Zusammenfassung gewesen: Dann wäre ein grosser\nEffekt weiterhin vereinbar, und das Modell hätte schlicht zu wenig Daten.\n\n> Das Stockwerk trägt nichts zur Erklärung der Miete bei (Koeffizient -0.11\n> Franken, 95-Prozent-Konfidenzintervall -27.6 bis 27.4, p = 0.99); das\n> adjustierte R² sinkt von 0.478 auf 0.474. Der Prädiktor wurde nicht ins\n> Modell aufgenommen.\n\n### Beispiel 3: Multikollinearität\n\n#### Frage und Datenlage\n\nStatt des Stockwerks kommt die Zimmerzahl ins Modell. Sie hängt naturgemäss eng\nmit der Fläche zusammen: grössere Wohnungen haben mehr Zimmer. In diesen Daten\nbeträgt die Korrelation 0.96.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(cor(wohnung$flaeche, wohnung$zimmer), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9577\n```\n\n\n:::\n\n```{.r .cell-code}\nmodell_zimmer <- lm(miete ~ flaeche + alter + zimmer, data = wohnung)\nsummary(modell_zimmer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = miete ~ flaeche + alter + zimmer, data = wohnung)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-515.78 -179.67   -8.32  184.51  521.90 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  424.057    104.730   4.049 9.32e-05 ***\nflaeche       10.643      4.082   2.607   0.0103 *  \nalter         -3.219      1.434  -2.245   0.0267 *  \nzimmer        31.488     84.706   0.372   0.7108    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 230.2 on 116 degrees of freedom\nMultiple R-squared:  0.4876,\tAdjusted R-squared:  0.4743 \nF-statistic: 36.79 on 3 and 116 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(modell_zimmer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  flaeche     alter    zimmer \n12.089927  1.000945 12.086751 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Zimmerzahl allein, ohne die Flaeche daneben\ncoef(lm(miete ~ zimmer, data = wohnung))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)      zimmer \n   412.9103    242.2233 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(\"Korrelation Fläche/Zimmer:\",\n      round(np.corrcoef(wohnung[\"flaeche\"], wohnung[\"zimmer\"])[0, 1], 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKorrelation Fläche/Zimmer: 0.9577\n```\n\n\n:::\n\n```{.python .cell-code}\nmodell_zimmer = smf.ols(\"miete ~ flaeche + alter + zimmer\",\n                        data=wohnung).fit()\nprint(modell_zimmer.summary().tables[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n==============================================================================\n                 coef    std err          t      P>|t|      [0.025      0.975]\n------------------------------------------------------------------------------\nIntercept    424.0567    104.730      4.049      0.000     216.627     631.487\nflaeche       10.6434      4.082      2.607      0.010       2.559      18.728\nalter         -3.2192      1.434     -2.245      0.027      -6.060      -0.379\nzimmer        31.4877     84.706      0.372      0.711    -136.284     199.260\n==============================================================================\n```\n\n\n:::\n\n```{.python .cell-code}\nX = sm.add_constant(wohnung[[\"flaeche\", \"alter\", \"zimmer\"]])\nprint({name: round(variance_inflation_factor(X.values, i), 3)\n       for i, name in enumerate(X.columns)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'const': np.float64(1.0), 'flaeche': np.float64(12.09), 'alter': np.float64(1.001), 'zimmer': np.float64(12.087)}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(smf.ols(\"miete ~ zimmer\", data=wohnung).fit().params.round(3).to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'Intercept': 412.91, 'zimmer': 242.223}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Ohne Zimmer | Mit Zimmer | Wie das zu lesen ist |\n|---|---|---|---|\n| `flaeche` Estimate | 12.10 | 10.64 | Der Schätzwert verschiebt sich merklich. |\n| `flaeche` Std. Error | 1.170 | 4.082 | **Dreieinhalbmal so gross.** Das ist die eigentliche Wirkung von Multikollinearität: nicht falsche Schätzwerte, sondern unsichere. |\n| Konfidenzintervall `flaeche` | 9.78 bis 14.41 | 2.56 bis 18.73 | Aus einer Spanne von fünf Franken wird eine von sechzehn. |\n| `zimmer` Estimate | | 31.49 | |\n| `zimmer` Std. Error | | 84.706 | Fast dreimal so gross wie der Schätzwert. |\n| `zimmer` p-Wert | | 0.711 | Nicht signifikant, obwohl die Zimmerzahl offensichtlich mit der Miete zusammenhängt. |\n| `Multiple R-squared` | 0.4869 | 0.4876 | Praktisch unverändert. Das Modell als Ganzes ist genauso gut wie vorher. |\n| `VIF` | 1.0 | 12.09 für Fläche und Zimmer | Der Varianzinflationsfaktor sagt, um welchen Faktor die **Varianz** des Koeffizienten gegenüber unkorrelierten Prädiktoren wächst. 12.09 heisst: Der Standardfehler ist um Wurzel 12.09, also rund 3.5, grösser. Genau der beobachtete Faktor. |\n| Zimmerzahl allein | | 242.22 Franken je Zimmer | Ohne die Fläche daneben ist der Effekt gross und deutlich. Er beschreibt dann aber die Fläche gleich mit. |\n\n::: {.note-box}\n**Faustregeln zum VIF und was sie bedeuten.** Werte unter 5 gelten als\nunbedenklich, über 10 als kritisch. Wichtiger als die Schwelle ist die\nÜbersetzung: VIF ist der Faktor, um den die Varianz wächst; für den\nStandardfehler zieht man die Wurzel. Ein VIF von 4 bedeutet einen doppelt so\ngrossen Standardfehler, ein VIF von 100 einen zehnfachen.\n:::\n\n#### Interpretation und Ergebnissatz\n\nMultikollinearität macht das Modell nicht falsch. Die Vorhersagen bleiben genau\nso gut wie vorher, R² ändert sich nicht, und die Schätzwerte sind\nerwartungstreu. Was leidet, ist die Aussage über **einzelne** Koeffizienten:\nWenn zwei Prädiktoren fast dasselbe messen, kann kein Verfahren entscheiden,\nwelchem von beiden der gemeinsame Effekt zuzurechnen ist.\n\nDaraus folgt, was zu tun ist:\n\n| Ziel | Vorgehen |\n|---|---|\n| Vorhersage | Nichts. Multikollinearität stört die Vorhersage nicht. |\n| Aussage über einzelne Effekte | Einen der beiden Prädiktoren weglassen, inhaltlich begründet |\n| Beide Informationen behalten | Zu einer Grösse zusammenfassen, etwa Fläche je Zimmer, oder eine [Hauptkomponente](../multivariat/hauptkomponentenanalyse.qmd) bilden |\n\nNicht zulässig ist, nacheinander beide einzeln zu testen und den signifikanten\nzu berichten.\n\n> Fläche und Zimmerzahl sind stark korreliert (r = 0.96, VIF = 12.1). Bei\n> gemeinsamer Aufnahme steigt der Standardfehler der Fläche von 1.17 auf 4.08,\n> und die Zimmerzahl wird nicht signifikant (p = 0.71), obwohl sie allein\n> betrachtet 242 Franken je Zimmer erklärt. Ins Modell aufgenommen wurde die\n> Fläche, weil sie feiner abgestuft ist; die Vorhersagegüte ist von dieser\n> Entscheidung nicht betroffen (R² = 0.487 in beiden Modellen).\n\n### Beispiel 4: Ein kategorialer Prädiktor\n\n#### Frage und Datenlage\n\nZu Fläche und Alter kommt die Lage mit drei Stufen: Zentrum, Mittel, Rand. Ein\nkategorialer Prädiktor mit drei Stufen wird zu zwei Indikatorvariablen; eine\nStufe dient als Referenz.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(wohnung$lage)          # die erste Stufe ist die Referenz\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Mittel\"  \"Rand\"    \"Zentrum\"\n```\n\n\n:::\n\n```{.r .cell-code}\nmodell_lage <- lm(miete ~ flaeche + alter + lage, data = wohnung)\nsummary(modell_lage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = miete ~ flaeche + alter + lage, data = wohnung)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-367.84  -99.00   -1.92   98.76  391.02 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  364.0042    72.1425   5.046 1.71e-06 ***\nflaeche       12.4590     0.7762  16.051  < 2e-16 ***\nalter         -3.0235     0.9477  -3.191  0.00183 ** \nlageRand    -173.2605    34.0133  -5.094 1.39e-06 ***\nlageZentrum  243.2169    34.0264   7.148 8.68e-11 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 152.1 on 115 degrees of freedom\nMultiple R-squared:  0.7783,\tAdjusted R-squared:  0.7706 \nF-statistic:   101 on 4 and 115 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(modell_lage)            # gemeinsamer Test aller Lage-Stufen\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: miete\n           Df  Sum Sq Mean Sq F value    Pr(>F)    \nflaeche     1 5572205 5572205 240.994 < 2.2e-16 ***\nalter       1  269007  269007  11.634  0.000894 ***\nlage        2 3495435 1747717  75.588 < 2.2e-16 ***\nResiduals 115 2658999   23122                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmodell_lage = smf.ols(\"miete ~ flaeche + alter + C(lage)\",\n                      data=wohnung).fit()\nprint(modell_lage.summary().tables[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n======================================================================================\n                         coef    std err          t      P>|t|      [0.025      0.975]\n--------------------------------------------------------------------------------------\nIntercept            364.0042     72.143      5.046      0.000     221.104     506.905\nC(lage)[T.Rand]     -173.2605     34.013     -5.094      0.000    -240.634    -105.887\nC(lage)[T.Zentrum]   243.2169     34.026      7.148      0.000     175.817     310.617\nflaeche               12.4590      0.776     16.051      0.000      10.921      13.997\nalter                 -3.0235      0.948     -3.191      0.002      -4.901      -1.146\n======================================================================================\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"R^2:\", round(modell_lage.rsquared, 4),\n      \" Residualstreuung:\", round(np.sqrt(modell_lage.mse_resid), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR^2: 0.7783  Residualstreuung: 152.058\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(sm.stats.anova_lm(modell_lage, typ=2).round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                sum_sq     df         F  PR(>F)\nC(lage)   3.495435e+06    2.0   75.5877  0.0000\nflaeche   5.956922e+06    1.0  257.6331  0.0000\nalter     2.353701e+05    1.0   10.1796  0.0018\nResidual  2.658999e+06  115.0       NaN     NaN\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| Referenzstufe | `Mittel` | die weggelassene Stufe | Sie erscheint **nicht** in der Ausgabe. R und statsmodels sortieren die Stufen alphabetisch, und Mittel steht vor Rand und Zentrum. Das ist eine reine Zufälligkeit des Alphabets, keine inhaltliche Wahl. |\n| `lageRand` | -173.26 | Differenz Rand gegenüber Mittel | Eine Wohnung am Rand kostet bei gleicher Fläche und gleichem Alter 173 Franken weniger als eine in mittlerer Lage. |\n| `lageZentrum` | +243.22 | Differenz Zentrum gegenüber Mittel | Entsprechend 243 Franken mehr. |\n| Differenz Zentrum zu Rand | 416.48 | nicht in der Ausgabe | Sie ergibt sich als Differenz der beiden Koeffizienten. Ihr p-Wert steht dort **nicht**; dafür braucht es einen eigenen Kontrast oder eine andere Referenzstufe. |\n| `flaeche` Estimate | 12.46 | Franken je Quadratmeter | Kaum verändert gegenüber Beispiel 1 (12.10), weil die Lage nicht mit der Fläche zusammenhängt. |\n| `flaeche` Std. Error | 0.776 | | **Kleiner** als in Beispiel 1 (1.170). Ein zusätzlicher Prädiktor, der Streuung erklärt, macht die übrigen Schätzungen genauer. |\n| `Multiple R-squared` | 0.7783 | | Sprung von 0.487 auf 0.778. |\n| `Residual standard error` | 152.06 | | Von 229 auf 152 Franken gefallen. |\n| `anova()` | gemeinsamer F-Test für `lage` | | Die Frage \"spielt die Lage überhaupt eine Rolle\" wird mit **einem** Test über beide Indikatorvariablen beantwortet, nicht mit zwei einzelnen t-Tests. |\n\n::: {.note-box}\n**Zwei p-Werte für eine Frage.** Die `summary()`-Ausgabe liefert je einen\nt-Test pro Indikatorvariable, also den Vergleich jeder Stufe mit der Referenz.\nDie Frage \"hat die Lage insgesamt einen Einfluss\" beantwortet keiner dieser\nTests. Dafür ist der F-Test aus `anova()` da, der beide Indikatorvariablen\ngemeinsam prüft.\n\nDer Unterschied wird wichtig, wenn eine Stufe wenige Beobachtungen hat: Die\neinzelnen t-Tests können dann alle unauffällig sein, während der gemeinsame Test\nanschlägt.\n:::\n\n#### Interpretation und Ergebnissatz\n\nDie Lage ist in diesen Daten der stärkste Einflussfaktor. Bemerkenswert ist der\nNebeneffekt: Weil sie viel Streuung erklärt, sinkt die Residualstreuung, und\ndadurch werden **alle** Koeffizienten genauer geschätzt. Der Standardfehler der\nFläche fällt von 1.17 auf 0.78, ohne dass sich am Schätzwert viel ändert.\n\nDas ist das Gegenstück zu Beispiel 3: Ein Prädiktor, der eigene Information\nbeiträgt, verbessert die Schätzung der anderen; einer, der dieselbe Information\nnoch einmal bringt, verschlechtert sie.\n\nZur Referenzstufe: Dass hier \"Mittel\" als Bezugspunkt dient, ist alphabetischer\nZufall und passt hier ausnahmsweise gut. Wenn eine andere Stufe inhaltlich der\nnatürliche Bezugspunkt ist, wird sie mit `relevel()` beziehungsweise\n`Treatment(reference=...)` gesetzt, und der Bericht nennt sie ausdrücklich.\n\n> Fläche, Alter und Lage erklären zusammen 78 Prozent der Mietunterschiede\n> (n = 120, Residualstreuung 152 Franken). Gegenüber mittlerer Lage kostet eine\n> Wohnung im Zentrum 243 Franken mehr (p < 0.001) und am Rand 173 Franken\n> weniger (p < 0.001), bei gleicher Fläche und gleichem Alter. Je Quadratmeter\n> steigt die Miete um 12.46 Franken (p < 0.001), je Jahr Alter sinkt sie um\n> 3.02 Franken (p = 0.002). Referenzstufe der Lage ist \"Mittel\".\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nIm Output steht für einen Prädiktor `Estimate = 11.8`, `Std. Error = 1.2`. Was\nfolgt für das 95-Prozent-Konfidenzintervall?\n\n- [x] Es reicht ungefähr von 9.4 bis 14.2 und schliesst die Null nicht ein ~\n      Richtig, rund Schätzwert plus minus zwei Standardfehler. Der Koeffizient\n      ist deutlich von null verschieden.\n- [ ] Es reicht von 10.6 bis 13.0 ~ Das ist plus minus ein Standardfehler und\n      entspricht etwa 68 Prozent, nicht 95.\n- [ ] Ohne den p-Wert lässt sich das nicht sagen ~ Schätzwert und Standardfehler\n      genügen, der p-Wert enthält keine zusätzliche Information darüber.\n:::\n\n::: {.quiz}\nDer F-Test des Gesamtmodells ist mit p < 0.001 signifikant, R² beträgt 0.71,\naber kein einzelner Koeffizient hat einen p-Wert unter 0.05. Was ist die\nnaheliegendste Erklärung?\n\n- [ ] Ein Rechenfehler, das kann nicht gleichzeitig auftreten ~ Es kann, und es\n      ist ein bekanntes Muster.\n- [x] Starke Multikollinearität zwischen den Prädiktoren ~ Richtig. Gemeinsam\n      erklären sie viel, aber der Beitrag der einzelnen Variable ist nicht\n      trennbar, die Standardfehler werden gross. Prüfen mit VIF.\n- [ ] Das Modell hat zu wenige Prädiktoren ~ Zusätzliche Variablen würden die\n      Standardfehler eher weiter aufblähen.\n:::\n\n::: {.quiz}\nNach Aufnahme eines zweiten Prädiktors fällt der Koeffizient des ersten von 15\nauf 4. Was bedeutet das?\n\n- [ ] Der erste Prädiktor ist unwichtig geworden ~ Wichtigkeit ist keine\n      Eigenschaft, die sich durch Hinzufügen einer Variablen ändert. Geändert\n      hat sich die Frage, die der Koeffizient beantwortet.\n- [x] Ein Teil des Zusammenhangs lief über den zweiten Prädiktor ~ Richtig. Der\n      Koeffizient misst jetzt den Beitrag bei konstant gehaltenem zweitem\n      Prädiktor. Die beiden Grössen hängen zusammen, ein Teil des vorher\n      zugeschriebenen Effekts gehört zum neuen Prädiktor.\n- [ ] Das Modell ist jetzt falsch spezifiziert ~ Aus der Änderung allein folgt\n      das nicht. Welche Fassung passt, entscheidet die inhaltliche Frage.\n:::\n\n::: {.quiz}\nDas adjustierte R² sinkt, wenn ein weiterer Prädiktor aufgenommen wird, während\ndas gewöhnliche R² leicht steigt. Was heisst das?\n\n- [x] Der Prädiktor erklärt weniger, als seine Kosten an Freiheitsgraden wert\n      sind ~ Richtig. Das gewöhnliche R² kann durch Hinzufügen nie sinken, das\n      adjustierte schon. Genau deshalb wird für Vergleiche das adjustierte\n      gelesen.\n- [ ] Die Berechnung ist unstimmig ~ Beide Grössen verhalten sich genau so, wie\n      sie definiert sind.\n- [ ] Der Prädiktor ist mit der Zielvariable negativ korreliert ~ Die Richtung\n      des Zusammenhangs spielt für R² keine Rolle.\n:::\n\n## Verlinkte Ressourcen\n\n- [An Introduction to Statistical Learning, Kapitel 3](https://www.statlearning.com/)\n- [statsmodels: Ordinary Least Squares](https://www.statsmodels.org/stable/regression.html)\n- [R-Dokumentation zu `lm`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/lm.html)\n",
    "supporting": [
      "multiple-lineare-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}