{
  "hash": "6706afcc914eaf9b8664124579c4a98d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Einfache lineare Regression\"\ndescription: \"Ein Prädiktor, Steigung und Achsenabschnitt, Bestimmtheitsmass und Residuen.\"\ncategories: [\"Regression\", \"Modelldiagnostik\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"ESDS\", \"STATDA\"]\nseitentyp: methode\nstand: fertig\norder: 10\n---\n\n\n\n\n\nAlle Beispiele rechnen mit fest eingetragenen Zahlen. R und Python schätzen\ndasselbe Modell auf denselben Daten und müssen deshalb dieselben Koeffizienten\nausgeben; die Ausgaben unterscheiden sich nur in Anordnung und Benennung.\n\n\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Wie verändert sich eine metrische Zielgrösse, wenn eine einzelne Einflussgrösse steigt, und wie gut lässt sie sich daraus vorhersagen? |\n| Zielvariable | metrisch |\n| Prädiktoren | genau einer, metrisch oder zweistufig kategorial |\n| Was die Methode liefert | Achsenabschnitt und Steigung mit Konfidenzintervall und p-Wert, Bestimmtheitsmass, Residualstreuung, Residuen für die Diagnostik |\n| R-Funktion | `lm(y ~ x, data = df)`, gelesen mit `summary()` und `confint()` |\n| Python-Funktion | `smf.ols(\"y ~ x\", data=df).fit()`, gelesen mit `.summary()` |\n| Verwandte Methoden | [Korrelation](../grundlagen/korrelation.qmd), [multiple lineare Regression](multiple-lineare-regression.qmd), [Korrelationstests](../tests/korrelationstests.qmd) |\n\n## Wann diese Methode, wann nicht\n\nTypische Fragestellungen: Verbrauch aus Laufzeit, Miete aus Fläche, Ertrag aus\nDüngermenge. Gemeinsam ist ihnen eine metrische Zielgrösse, eine einzige\nEinflussgrösse und ein Zusammenhang, der im beobachteten Bereich annähernd\ngeradlinig verläuft.\n\nDer Unterschied zur [Korrelation](../grundlagen/korrelation.qmd) ist die\nRichtung. Die Korrelation beschreibt symmetrisch, wie eng zwei Grössen\nzusammenhängen. Die Regression legt fest, welche Grösse vorhergesagt wird, und\nliefert dafür eine Gleichung mit Einheiten.\n\nSie passt nicht in diesen Fällen:\n\n| Situation | Stattdessen |\n|---|---|\n| Mehrere Einflussgrössen, oder eine soll kontrolliert werden | [multiple lineare Regression](multiple-lineare-regression.qmd) |\n| Zielvariable binär | [logistische Regression](logistische-regression.qmd) |\n| Nur die Frage, ob überhaupt ein Zusammenhang besteht | [Korrelationstest](../tests/korrelationstests.qmd) |\n| Erkennbar krummer Zusammenhang | Transformation, Polynomterm oder ein anderes Modell |\n| Zielvariable ist eine Zeit bis zu einem Ereignis mit zensierten Fällen | [Kaplan-Meier](../ueberlebenszeit/kaplan-meier.qmd) und [Cox-Modell](../ueberlebenszeit/cox-modell.qmd) |\n\n## Grundidee und Modell\n\nGesucht ist die Gerade, die möglichst nah an allen Punkten liegt. Nah heisst:\ndie Summe der quadrierten senkrechten Abstände zwischen beobachteten und\nvorhergesagten Werten ist minimal. Quadriert wird, damit sich Abweichungen nach\noben und unten nicht aufheben und grosse Abweichungen stärker zählen.\n\n$$y_i = \\beta_0 + \\beta_1 x_i + \\varepsilon_i$$\n\n| Bestandteil | Bedeutung |\n|---|---|\n| $y_i$ | beobachteter Wert der Zielvariable |\n| $\\beta_0$ | Achsenabschnitt, erwarteter Wert von $y$ bei $x = 0$ |\n| $\\beta_1$ | Steigung, erwartete Änderung von $y$ je Einheit von $x$ |\n| $x_i$ | Wert des Prädiktors |\n| $\\varepsilon_i$ | Residuum, der nicht erklärte Rest, mit Erwartungswert null und konstanter Varianz |\n\nGeschätzt wird mit der Methode der kleinsten Quadrate; es gibt eine\ngeschlossene Lösung, also kein Iterieren und keine Konvergenzprobleme. Die\ngeschätzte Gerade geht immer durch den Punkt der beiden Mittelwerte.\n\nBei genau einem Prädiktor gilt zusätzlich: das Bestimmtheitsmass ist exakt das\nQuadrat der Korrelation zwischen $x$ und $y$, und der p-Wert der Steigung ist\nderselbe wie der des Pearson-Korrelationstests. Beide Verfahren beantworten\ndieselbe Frage in verschiedener Sprache.\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung | Vorgehen |\n|---|---|---|---|---|\n| Linearität | Der Zusammenhang ist im beobachteten Bereich geradlinig | Streudiagramm, Residuen gegen Vorhersage | Steigung ist ein Kompromiss über verschiedene Bereiche und beschreibt keinen davon richtig | Transformation, Polynomterm, Bereich einschränken |\n| Unabhängigkeit | Beobachtungen beeinflussen sich nicht | Erhebungsdesign, bei zeitlicher Ordnung Durbin-Watson | Standardfehler zu klein, p-Werte zu optimistisch | Zeitreihen- oder Mehrebenenmodell |\n| Homoskedastizität | Streuung der Residuen ist über den Vorhersagebereich konstant | Residuenplot, Breusch-Pagan-Test | Schätzwerte bleiben brauchbar, Standardfehler und Intervalle nicht | robuste Standardfehler, Transformation |\n| Normalverteilte Residuen | Residuen streuen annähernd normal | QQ-Plot | betrifft Tests und Intervalle bei kleinem n | Transformation, Bootstrap |\n| Keine einflussreichen Einzelfälle | Kein einzelner Punkt bestimmt die Gerade | Cook-Distanz, Hebelwerte, Streudiagramm | Steigung hängt an einer Beobachtung | Fall prüfen, Modell mit und ohne ihn berichten |\n\nDie Voraussetzungen betreffen die Residuen, nicht die Rohdaten. Weder $x$ noch\n$y$ müssen normalverteilt sein; eine rechtsschiefe Zielgrösse ist kein Grund zur\nSorge, solange die Residuen es nicht sind.\n\n## Output lesen\n\nR, `summary(modell)`:\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| `Call` | die geschätzte Formel | prüfen, ob Ziel- und Einflussgrösse nicht vertauscht sind |\n| `Residuals` | Minimum, Quartile, Median der Residuen | Median deutlich neben null deutet auf Schieflage |\n| `(Intercept)` Estimate | erwarteter Wert von y bei x gleich null | nur deutbar, wenn null im Datenbereich sinnvoll ist |\n| Estimate des Prädiktors | Steigung, erwartete Änderung je Einheit | in den Einheiten der Variablen |\n| `Std. Error` | Unsicherheit der Schätzung | wächst mit der Streuung, sinkt mit n und mit der Spannweite von x |\n| `t value` | Estimate durch Std. Error | Betrag über etwa 2 heisst bei üblichem n signifikant |\n| `Pr(>|t|)` | p-Wert für die Nullhypothese, dass der Koeffizient null ist | für die Steigung identisch mit dem Pearson-Korrelationstest |\n| `Residual standard error` | typische Abweichung einer Vorhersage in der Einheit von y | die praktisch nützlichste Gütezahl |\n| Freiheitsgrade | n minus 2 | zwei geschätzte Parameter |\n| `Multiple R-squared` | Anteil der erklärten Streuung | bei einem Prädiktor exakt das Quadrat der Korrelation |\n| `Adjusted R-squared` | um die Parameterzahl korrigiert | kann negativ werden, wenn der Prädiktor nichts erklärt |\n| `F-statistic` mit p-Wert | Gesamttest des Modells | bei einem Prädiktor gleichwertig zum t-Test der Steigung |\n| `confint()` | Konfidenzintervall je Koeffizient | schliesst es null ein, ist der Koeffizient nicht signifikant |\n\nPython, `modell.summary()`, mit den Unterschieden zu R:\n\n| Grösse | Was sie sagt | Unterschied zu R |\n|---|---|---|\n| `coef`, `std err`, `t`, `P>|t|` | wie in R | nur andere Bezeichnung |\n| `[0.025 0.975]` | Konfidenzintervall | steht direkt in der Tabelle, in R braucht es `confint()` |\n| `R-squared`, `Adj. R-squared` | wie in R | identisch berechnet |\n| `Df Residuals`, `Df Model` | Freiheitsgrade | in eigenen Zeilen statt im Fliesstext |\n| `AIC`, `BIC`, `Log-Likelihood` | Kennzahlen für Modellvergleiche | in R über `AIC(modell)` |\n| `Omnibus`, `Jarque-Bera`, `Skew`, `Kurtosis` | Normalität der Residuen | in R nicht enthalten, dort der QQ-Plot |\n| `Durbin-Watson` | Autokorrelation der Residuen | Werte um 2 sind unauffällig |\n| kein `Residual standard error` | fehlt in der Tabelle | über `np.sqrt(modell.mse_resid)` |\n\n## Interpretationsfallen\n\n- **Der Achsenabschnitt ist meist keine Aussage.** Er beschreibt den Fall\n  $x = 0$, und der liegt oft ausserhalb der Daten. Wer ihn deuten will,\n  zentriert den Prädiktor.\n- **Ein hohes R² heisst nicht, dass das Modell stimmt.** Beispiel 3 zeigt das\n  Gegenteil. Angemessenheit beantworten die Residuen, nicht das\n  Bestimmtheitsmass.\n- **Ein niedriges R² heisst nicht, dass das Modell falsch ist.** Bei stark\n  streuenden Daten kann ein korrekt spezifiziertes Modell wenig Streuung\n  erklären und die Steigung trotzdem gut schätzen.\n- **Die Steigung ist keine Kausalität.** Sie beschreibt, wie sich $y$ mit $x$\n  ändert, nicht warum. Eine dritte, nicht erhobene Grösse kann beides treiben,\n  siehe [Korrelation](../grundlagen/korrelation.qmd).\n- **Vertauschen ändert das Ergebnis.** Die Regression von $y$ auf $x$ ist nicht\n  die Umkehrung der Regression von $x$ auf $y$, weil jeweils andere Abstände\n  minimiert werden. Die Korrelation dagegen ist symmetrisch.\n- **Vorhersagen nur im beobachteten Bereich.** Ausserhalb ist die Linearität\n  nicht geprüft; die Zahl kommt trotzdem und sieht genauso aus.\n- **Konfidenzband und Vorhersageband sind zweierlei.** Das schmale Band gilt\n  dem Mittelwert bei gegebenem $x$, das breite einer einzelnen künftigen\n  Beobachtung.\n\n## Ergebnis berichten\n\nVorlage für den Ergebnissatz:\n\n> Eine einfache lineare Regression von [Zielvariable] auf [Prädiktor] ergibt\n> eine Steigung von [Schätzwert] [Einheit] je [Einheit des Prädiktors]\n> (95-Prozent-Konfidenzintervall [unten] bis [oben], t([Freiheitsgrade]) = [t],\n> p = [p]). Das Modell erklärt [R²] der Streuung, die typische Abweichung einer\n> Vorhersage beträgt [Residualstreuung] [Einheit] (n = [n]).\n\nImmer genannt werden Steigung in ihrer Einheit, Konfidenzintervall,\nTeststatistik mit Freiheitsgraden, p-Wert, R², Residualstreuung und n, dazu\nwelche Voraussetzungen geprüft wurden und mit welchem Ergebnis.\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt der einfachen linearen Regression |\n|---|---|\n| [Korrelation](../grundlagen/korrelation.qmd) | nur die Enge des Zusammenhangs interessiert, keine Richtung und keine Vorhersage |\n| [Korrelationstests](../tests/korrelationstests.qmd) | nur die Frage, ob ein Zusammenhang besteht, ohne Modellgleichung |\n| [Multiple lineare Regression](multiple-lineare-regression.qmd) | mehrere Einflussgrössen, oder eine soll konstant gehalten werden |\n| [Logistische Regression](logistische-regression.qmd) | Zielvariable binär |\n| [Regressionsdiagnostik](regressionsdiagnostik.qmd) | Vertiefung zu Residuen, Hebelwerten und Ausreissern |\n| [t-Test für zwei Stichproben](../tests/t-test-zwei-stichproben.qmd) | der Prädiktor ist zweistufig kategorial; rechnerisch derselbe Fall, andere Darstellung |\n\n## Beispiele\n\nJedes Beispiel steht in einem eigenen Reiter.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Verbrauch aus Laufzeit\n\n#### Frage und Datenlage\n\nVon 24 Anlagen liegen die Betriebsstunden einer Woche und der Verbrauch in\nLitern vor. Gefragt ist, um wie viele Liter der Verbrauch je zusätzlicher\nBetriebsstunde steigt, und wie genau sich der Verbrauch aus der Laufzeit\nvorhersagen lässt.\n\nBeide Grössen sind metrisch, es gibt genau einen Prädiktor, und die Richtung\nsteht fest: Die Laufzeit erklärt den Verbrauch, nicht umgekehrt. Das ist die\nStandardsituation der einfachen linearen Regression.\n\n#### Modell schätzen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanlagen <- data.frame(\n  laufzeit = c(3.2, 6.0, 6.0, 6.8, 7.7, 8.1, 8.8, 9.0, 9.3, 10.3, 10.6, 10.9,\n               11.8, 11.9, 13.8, 13.9, 14.1, 14.3, 15.8, 16.4, 17.0, 18.4,\n               18.6, 19.4),\n  verbrauch = c(26.8, 41.7, 26.5, 41.1, 28.2, 37.7, 31.6, 47.3, 45.0, 49.7,\n                38.4, 48.6, 43.9, 44.6, 55.7, 58.2, 54.7, 50.3, 53.3, 68.6,\n                65.2, 69.8, 79.2, 63.4)\n)\n\nmodell <- lm(verbrauch ~ laufzeit, data = anlagen)\nsummary(modell)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = verbrauch ~ laufzeit, data = anlagen)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-8.959 -5.723  1.316  3.790 10.934 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   15.184      3.585   4.236 0.000339 ***\nlaufzeit       2.854      0.286   9.980 1.25e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.106 on 22 degrees of freedom\nMultiple R-squared:  0.8191,\tAdjusted R-squared:  0.8109 \nF-statistic:  99.6 on 1 and 22 DF,  p-value: 1.252e-09\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(modell)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               2.5 %   97.5 %\n(Intercept) 7.749859 22.61882\nlaufzeit    2.260834  3.44690\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nanlagen = pd.DataFrame({\n    \"laufzeit\": [3.2, 6.0, 6.0, 6.8, 7.7, 8.1, 8.8, 9.0, 9.3, 10.3, 10.6, 10.9,\n                 11.8, 11.9, 13.8, 13.9, 14.1, 14.3, 15.8, 16.4, 17.0, 18.4,\n                 18.6, 19.4],\n    \"verbrauch\": [26.8, 41.7, 26.5, 41.1, 28.2, 37.7, 31.6, 47.3, 45.0, 49.7,\n                  38.4, 48.6, 43.9, 44.6, 55.7, 58.2, 54.7, 50.3, 53.3, 68.6,\n                  65.2, 69.8, 79.2, 63.4],\n})\n\nmodell = smf.ols(\"verbrauch ~ laufzeit\", data=anlagen).fit()\nprint(modell.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                            OLS Regression Results                            \n==============================================================================\nDep. Variable:              verbrauch   R-squared:                       0.819\nModel:                            OLS   Adj. R-squared:                  0.811\nMethod:                 Least Squares   F-statistic:                     99.60\nDate:                Fri, 11 Sep 2026   Prob (F-statistic):           1.25e-09\nTime:                        06:17:01   Log-Likelihood:                -76.434\nNo. Observations:                  24   AIC:                             156.9\nDf Residuals:                      22   BIC:                             159.2\nDf Model:                           1                                         \nCovariance Type:            nonrobust                                         \n==============================================================================\n                 coef    std err          t      P>|t|      [0.025      0.975]\n------------------------------------------------------------------------------\nIntercept     15.1843      3.585      4.236      0.000       7.750      22.619\nlaufzeit       2.8539      0.286      9.980      0.000       2.261       3.447\n==============================================================================\nOmnibus:                        3.388   Durbin-Watson:                   2.477\nProb(Omnibus):                  0.184   Jarque-Bera (JB):                1.373\nSkew:                           0.039   Prob(JB):                        0.503\nKurtosis:                       1.831   Cond. No.                         36.3\n==============================================================================\n\nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Residualstreuung:\", round(np.sqrt(modell.mse_resid), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nResidualstreuung: 6.1063\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| `(Intercept)` Estimate | 15.184 | erwarteter Verbrauch bei Laufzeit null | Rechnerisch nötig, inhaltlich hier ohne Aussage: Die kleinste beobachtete Laufzeit beträgt 3.2 Stunden, für den Stillstand liegen keine Daten vor. |\n| `laufzeit` Estimate | 2.854 | Steigung in Litern je Betriebsstunde | Die zentrale Zahl. Eine Stunde mehr Laufzeit geht im Mittel mit 2.85 Litern mehr Verbrauch einher. |\n| `Std. Error` der Steigung | 0.286 | Unsicherheit dieser Schätzung | Rund ein Zehntel der Steigung. Sie sinkt mit mehr Beobachtungen und mit einer breiteren Spanne der Laufzeiten. |\n| `t value` der Steigung | 9.980 | Schätzwert geteilt durch Standardfehler | Die Steigung ist knapp zehn Standardfehler von null entfernt. |\n| `Pr(>|t|)` der Steigung | 1.25e-09 | p-Wert für \"die wahre Steigung ist null\" | Praktisch ausgeschlossen. Der Wert des Achsenabschnitts (p = 0.00034) wird meistens gar nicht getestet, weil die Hypothese \"y ist null bei x gleich null\" selten interessiert. |\n| `confint()` bzw. `[0.025 0.975]` | 2.261 bis 3.447 | plausibler Bereich für die Steigung | Die aussagekräftigste Zeile: Der wahre Effekt liegt vermutlich zwischen 2.3 und 3.4 Litern je Stunde. Diese Spanne, nicht der p-Wert, entscheidet über die praktische Nutzbarkeit. |\n| `Residual standard error` | 6.106 auf 22 Freiheitsgraden | typische Abweichung einer Vorhersage in Litern | Wer den Verbrauch aus der Laufzeit vorhersagt, liegt typischerweise um rund 6 Liter daneben. Die praktisch nützlichste Gütezahl, weil sie in der Einheit der Messung steht. |\n| Freiheitsgrade | 22 | n minus 2 | 24 Beobachtungen, zwei geschätzte Parameter. |\n| `Multiple R-squared` | 0.8191 | Anteil erklärter Streuung | Rund 82 Prozent der Verbrauchsunterschiede gehen auf die Laufzeit zurück. |\n| `Adjusted R-squared` | 0.8109 | um die Parameterzahl korrigiert | Bei einem Prädiktor kaum verschieden. Der Abstand wächst mit der Zahl der Prädiktoren. |\n| `F-statistic` | 99.60 auf 1 und 22 df, p = 1.25e-09 | Gesamttest des Modells | Bei genau einem Prädiktor redundant: F ist exakt das Quadrat des t-Werts (9.98² = 99.6), und die p-Werte sind identisch. |\n\n#### Bestimmtheitsmass und Korrelation\n\nBei einem Prädiktor ist R² exakt das Quadrat der Korrelation. Das lässt sich\ndirekt nachrechnen und ist der beste Merksatz gegen die Verwechslung der beiden\nZahlen.\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(c(r = cor(anlagen$laufzeit, anlagen$verbrauch),\n        r_quadrat = cor(anlagen$laufzeit, anlagen$verbrauch)^2,\n        aus_dem_modell = summary(modell)$r.squared), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             r      r_quadrat aus_dem_modell \n        0.9050         0.8191         0.8191 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nr = anlagen[\"laufzeit\"].corr(anlagen[\"verbrauch\"])\nprint(\"r =\", round(r, 4), \" r^2 =\", round(r**2, 4),\n      \" R^2 =\", round(modell.rsquared, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nr = 0.905  r^2 = 0.8191  R^2 = 0.8191\n```\n\n\n:::\n:::\n\n\n:::\n\nDie Korrelation beträgt 0.905, ihr Quadrat 0.8191, und genau das steht als R²\nim Modell. Wichtig ist der Unterschied in der Bedeutung: r = 0.905 ist ein Mass\nfür die Enge des Zusammenhangs ohne Einheit, R² = 0.82 ein Anteil an der\nStreuung. Die Steigung von 2.854 Litern je Stunde sagt dagegen etwas über die\nGrösse des Effekts, und die drei Zahlen sind nicht ineinander überführbar, ohne\ndie Streuungen zu kennen.\n\n#### Voraussetzungen prüfen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 3), mar = c(4, 4, 3, 1))\nplot(anlagen$laufzeit, anlagen$verbrauch, pch = 16, col = \"grey30\",\n     xlab = \"Laufzeit (h)\", ylab = \"Verbrauch (l)\", main = \"Daten und Gerade\")\nabline(modell, col = \"steelblue\", lwd = 2)\nplot(modell, which = 1)\nplot(modell, which = 2)\npar(mfrow = c(1, 1))\n\nbptest(modell)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  modell\nBP = 0.00024274, df = 1, p-value = 0.9876\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 1: Streudiagramm mit Gerade, Residuen gegen Vorhersage, QQ-Plot der Residuen.](einfache-lineare-regression_files/figure-html/fig-b1-diagnostik-r-1.png){#fig-b1-diagnostik-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, axes = plt.subplots(1, 3, figsize=(7, 3.0))\naxes[0].scatter(anlagen[\"laufzeit\"], anlagen[\"verbrauch\"], s=14, color=\"0.3\")\ngerade = np.linspace(3, 20, 50)\naxes[0].plot(gerade, modell.params.iloc[0] + modell.params.iloc[1] * gerade,\n             color=\"steelblue\", linewidth=2)\naxes[0].set_xlabel(\"Laufzeit (h)\")\naxes[0].set_ylabel(\"Verbrauch (l)\")\naxes[0].set_title(\"Daten und Gerade\")\naxes[1].scatter(modell.fittedvalues, modell.resid, s=14, color=\"0.3\")\naxes[1].axhline(0, linestyle=\"--\", color=\"black\")\naxes[1].set_xlabel(\"Vorhersage\")\naxes[1].set_title(\"Residuen\")\nsm.qqplot(modell.resid, line=\"s\", ax=axes[2])\naxes[2].set_title(\"QQ-Plot\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Diagnostik in Python.](einfache-lineare-regression_files/figure-html/fig-b1-diagnostik-py-1.png){#fig-b1-diagnostik-py width=100%}\n:::\n\n```{.python .cell-code}\nlm_stat, lm_p, f_stat, f_p = sm.stats.diagnostic.het_breuschpagan(\n    modell.resid, modell.model.exog)\nprint(\"Breusch-Pagan LM =\", round(lm_stat, 4), \" p =\", round(lm_p, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBreusch-Pagan LM = 0.0002  p = 0.9876\n```\n\n\n:::\n:::\n\n\n:::\n\nLinks steigen die Punkte gleichmässig an, ohne Bogen. In der Mitte streuen die\nResiduen strukturlos um die Nulllinie, und der Streubereich bleibt von links\nnach rechts etwa gleich breit. Rechts liegen die Punkte nah an der Geraden. Der\nBreusch-Pagan-Test bestätigt das mit einem p-Wert von 0.988: kein Hinweis auf\nungleiche Streuung. Ein grosser p-Wert ist hier die gute Nachricht, weil die\nNullhypothese die konstante Streuung ist.\n\n#### Interpretation und Ergebnissatz\n\nDrei Zahlen tragen die Aussage, und sie beantworten drei verschiedene Fragen.\nDie Steigung von 2.854 Litern je Stunde beantwortet \"wie stark\". Das Intervall\nvon 2.26 bis 3.45 beantwortet \"wie sicher\". Die Residualstreuung von 6.1 Litern\nbeantwortet \"wie brauchbar für eine einzelne Vorhersage\". Ein Modell kann bei\nallen drei Fragen unterschiedlich gut abschneiden, und der p-Wert beantwortet\nkeine davon.\n\n> Der Verbrauch steigt mit der Betriebszeit: Je zusätzlicher Betriebsstunde\n> nimmt er im Mittel um 2.85 Liter zu (95-Prozent-Konfidenzintervall 2.26 bis\n> 3.45, t(22) = 9.98, p < 0.001). Das Modell erklärt 82 Prozent der Streuung,\n> die typische Abweichung einer Vorhersage beträgt 6.1 Liter (n = 24). Residuen\n> und Streudiagramm zeigen keine Auffälligkeiten.\n\n### Beispiel 2: Kein erkennbarer Zusammenhang\n\n#### Frage und Datenlage\n\nAus derselben Halle liegen für 20 Tage die Hallentemperatur in Grad Celsius und\nder Tagesverbrauch vor. Die Vermutung lautet, dass wärmere Tage den Verbrauch\ntreiben. Das Beispiel zeigt, wie ein Nullbefund aussieht und was er nicht\nbedeutet.\n\n#### Modell schätzen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhalle <- data.frame(\n  temperatur = c(15.6, 16.1, 16.3, 17.0, 17.2, 18.0, 18.5, 18.9, 19.2, 19.5,\n                 19.7, 20.4, 21.2, 21.4, 21.5, 21.8, 21.9, 22.2, 22.4, 23.5),\n  verbrauch = c(56.3, 63.1, 56.5, 55.7, 52.6, 61.1, 43.9, 60.6, 75.7, 50.8,\n                59.5, 93.8, 48.1, 40.5, 54.9, 81.7, 84.4, 45.4, 66.8, 60.1)\n)\n\nmodell_b2 <- lm(verbrauch ~ temperatur, data = halle)\nsummary(modell_b2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = verbrauch ~ temperatur, data = halle)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-21.807  -8.044  -1.008   4.126  32.463 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)\n(Intercept)  41.5439    27.1568   1.530    0.143\ntemperatur    0.9702     1.3750   0.706    0.489\n\nResidual standard error: 14.16 on 18 degrees of freedom\nMultiple R-squared:  0.02692,\tAdjusted R-squared:  -0.02715 \nF-statistic: 0.4979 on 1 and 18 DF,  p-value: 0.4895\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(modell_b2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %    97.5 %\n(Intercept) -15.510357 98.598172\ntemperatur   -1.918629  3.859092\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nhalle = pd.DataFrame({\n    \"temperatur\": [15.6, 16.1, 16.3, 17.0, 17.2, 18.0, 18.5, 18.9, 19.2, 19.5,\n                   19.7, 20.4, 21.2, 21.4, 21.5, 21.8, 21.9, 22.2, 22.4, 23.5],\n    \"verbrauch\": [56.3, 63.1, 56.5, 55.7, 52.6, 61.1, 43.9, 60.6, 75.7, 50.8,\n                  59.5, 93.8, 48.1, 40.5, 54.9, 81.7, 84.4, 45.4, 66.8, 60.1],\n})\n\nmodell_b2 = smf.ols(\"verbrauch ~ temperatur\", data=halle).fit()\nprint(modell_b2.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                            OLS Regression Results                            \n==============================================================================\nDep. Variable:              verbrauch   R-squared:                       0.027\nModel:                            OLS   Adj. R-squared:                 -0.027\nMethod:                 Least Squares   F-statistic:                    0.4979\nDate:                Fri, 11 Sep 2026   Prob (F-statistic):              0.489\nTime:                        06:17:02   Log-Likelihood:                -80.337\nNo. Observations:                  20   AIC:                             164.7\nDf Residuals:                      18   BIC:                             166.7\nDf Model:                           1                                         \nCovariance Type:            nonrobust                                         \n==============================================================================\n                 coef    std err          t      P>|t|      [0.025      0.975]\n------------------------------------------------------------------------------\nIntercept     41.5439     27.157      1.530      0.143     -15.510      98.598\ntemperatur     0.9702      1.375      0.706      0.489      -1.919       3.859\n==============================================================================\nOmnibus:                        2.293   Durbin-Watson:                   2.211\nProb(Omnibus):                  0.318   Jarque-Bera (JB):                1.373\nSkew:                           0.642   Prob(JB):                        0.503\nKurtosis:                       2.997   Cond. No.                         170.\n==============================================================================\n\nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Steigung | 0.970 | Rechnerisch steigt der Verbrauch um knapp einen Liter je Grad. Der Wert allein sagt nichts, solange die Unsicherheit fehlt. |\n| `Std. Error` | 1.375 | Grösser als die Steigung selbst. Damit ist die Schätzung von reinem Rauschen nicht zu unterscheiden. |\n| `t value` | 0.706 | Weniger als ein Standardfehler Abstand zur Null. |\n| `Pr(>|t|)` | 0.489 | Ein Wert dieser Grösse entsteht bei fehlendem Zusammenhang in rund der Hälfte aller Stichproben. |\n| Konfidenzintervall | -1.919 bis 3.859 | Die wichtigste Zeile. Das Intervall enthält die Null, ist aber fast sechs Liter je Grad breit: Ein deutlicher Effekt in beide Richtungen bleibt mit diesen Daten vereinbar. |\n| `Multiple R-squared` | 0.0269 | Nicht einmal drei Prozent der Streuung sind erklärt. |\n| `Adjusted R-squared` | -0.0271 | Negativ, und das ist kein Fehler. Das korrigierte Mass zieht für jeden Parameter etwas ab; erklärt der Prädiktor weniger, als ein zufälliger Prädiktor im Mittel erklären würde, rutscht es unter null. Ein sicheres Zeichen dafür, dass der Prädiktor nichts beiträgt. |\n| `Residual standard error` | 14.163 auf 18 Freiheitsgraden | Die Vorhersage aus der Temperatur ist kaum besser als der blosse Mittelwert des Verbrauchs. |\n| `F-statistic` | 0.498, p = 0.489 | Wie erwartet identisch mit dem t-Test der Steigung. |\n\n#### Interpretation und Ergebnissatz\n\nDer Nullbefund erlaubt genau eine Aussage: In diesen Daten ist kein Zusammenhang\nerkennbar. Er erlaubt nicht die Aussage, dass keiner existiert. Der Unterschied\nsteht im Konfidenzintervall, das Effekte bis zu 3.9 Litern je Grad weiterhin\nzulässt. Bei 20 Beobachtungen und einer Temperaturspanne von nur acht Grad ist\ndas kein Wunder: Die Genauigkeit der Steigung hängt nicht nur an n, sondern auch\nan der Spannweite des Prädiktors.\n\nWer diesen Zusammenhang ernsthaft prüfen will, erhebt mehr Tage und vor allem\nTage mit stärker unterschiedlichen Temperaturen.\n\n> Für die Hallentemperatur ergibt sich kein nachweisbarer Zusammenhang mit dem\n> Tagesverbrauch (Steigung 0.97 Liter je Grad, 95-Prozent-Konfidenzintervall\n> -1.92 bis 3.86, t(18) = 0.71, p = 0.49, R² = 0.03, n = 20). Das Intervall\n> lässt Effekte in beide Richtungen zu; ein Einfluss ist damit nicht\n> ausgeschlossen, sondern unbelegt.\n\n### Beispiel 3: Übersehene Krümmung\n\n#### Frage und Datenlage\n\nAn 24 Werkzeugen wurde die Laufzeit in tausend Stunden und der Verschleiss in\nMikrometern gemessen. Verschleiss wächst bei vielen Prozessen überproportional,\nweil eine bereits abgenutzte Schneide schneller weiter abnutzt. Genau dieser\nFall ist gefährlich, weil er sich in den Kennzahlen gut versteckt.\n\n#### Modell schätzen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwerkzeug <- data.frame(\n  laufzeit = c(3.8, 3.8, 3.9, 4.0, 4.1, 7.0, 7.6, 7.9, 9.5, 9.7, 9.9, 10.4,\n               11.4, 11.8, 12.4, 14.1, 14.5, 16.7, 16.7, 17.4, 18.0, 18.3,\n               19.6, 20.0),\n  verschleiss = c(31.9, 35.3, 16.0, 27.5, 22.2, 48.0, 44.3, 57.6, 73.8, 74.0,\n                  70.4, 81.7, 89.2, 92.7, 114.1, 130.4, 155.5, 193.1, 171.4,\n                  203.8, 205.6, 221.2, 250.8, 244.1)\n)\n\nmodell_b3 <- lm(verschleiss ~ laufzeit, data = werkzeug)\nsummary(modell_b3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = verschleiss ~ laufzeit, data = werkzeug)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-24.0024 -14.2466  -0.6001  11.8892  27.9486 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -44.5903     8.0917  -5.511 1.54e-05 ***\nlaufzeit     13.6689     0.6454  21.178 4.02e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 16.81 on 22 degrees of freedom\nMultiple R-squared:  0.9532,\tAdjusted R-squared:  0.9511 \nF-statistic: 448.5 on 1 and 22 DF,  p-value: 4.015e-16\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nwerkzeug = pd.DataFrame({\n    \"laufzeit\": [3.8, 3.8, 3.9, 4.0, 4.1, 7.0, 7.6, 7.9, 9.5, 9.7, 9.9, 10.4,\n                 11.4, 11.8, 12.4, 14.1, 14.5, 16.7, 16.7, 17.4, 18.0, 18.3,\n                 19.6, 20.0],\n    \"verschleiss\": [31.9, 35.3, 16.0, 27.5, 22.2, 48.0, 44.3, 57.6, 73.8, 74.0,\n                    70.4, 81.7, 89.2, 92.7, 114.1, 130.4, 155.5, 193.1, 171.4,\n                    203.8, 205.6, 221.2, 250.8, 244.1],\n})\n\nmodell_b3 = smf.ols(\"verschleiss ~ laufzeit\", data=werkzeug).fit()\nprint(modell_b3.summary().tables[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n==============================================================================\n                 coef    std err          t      P>|t|      [0.025      0.975]\n------------------------------------------------------------------------------\nIntercept    -44.5903      8.092     -5.511      0.000     -61.371     -27.809\nlaufzeit      13.6689      0.645     21.178      0.000      12.330      15.007\n==============================================================================\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"R^2 =\", round(modell_b3.rsquared, 4),\n      \" Residualstreuung =\", round(np.sqrt(modell_b3.mse_resid), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR^2 = 0.9532  Residualstreuung = 16.808\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Steigung | 13.669 | Sieht überzeugend aus. |\n| `Std. Error` | 0.645 | Sehr klein gegenüber der Steigung. |\n| `t value` | 21.178 | Enorm. |\n| `Pr(>|t|)` | 4.0e-16 | Hochsignifikant. |\n| `Multiple R-squared` | 0.9532 | 95 Prozent erklärte Streuung. Nach den Kennzahlen ein Musterbeispiel. |\n| `(Intercept)` | -44.590 | Hier steckt der erste Hinweis: Das Modell sagt für ein neues Werkzeug einen negativen Verschleiss voraus, was physikalisch unmöglich ist. |\n| `Residual standard error` | 16.808 | Und der zweite Hinweis: Bei Messwerten zwischen 16 und 251 Mikrometern ist das viel, gerade für ein Modell mit R² = 0.95. |\n\nAlle klassischen Gütezahlen sind gut, und das Modell ist trotzdem falsch. Warum,\nzeigen erst die Residuen.\n\n#### Voraussetzungen prüfen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nplot(werkzeug$laufzeit, werkzeug$verschleiss, pch = 16, col = \"grey30\",\n     xlab = \"Laufzeit (1000 h)\", ylab = \"Verschleiss (Mikrometer)\",\n     main = \"Gerade auf krummen Daten\")\nabline(modell_b3, col = \"steelblue\", lwd = 2)\nplot(fitted(modell_b3), resid(modell_b3), pch = 16, col = \"grey30\",\n     xlab = \"Vorhersage\", ylab = \"Residuum\", main = \"Residuen mit Bogen\")\nabline(h = 0, lty = 2)\nlines(lowess(fitted(modell_b3), resid(modell_b3)), col = \"firebrick\", lwd = 2)\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 3: Gerade auf gekrümmten Daten und der Bogen im Residuenplot.](einfache-lineare-regression_files/figure-html/fig-b3-diagnostik-r-1.png){#fig-b3-diagnostik-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, (links, rechts) = plt.subplots(1, 2, figsize=(7, 3.2))\nlinks.scatter(werkzeug[\"laufzeit\"], werkzeug[\"verschleiss\"], s=14, color=\"0.3\")\nx_gitter = np.linspace(3.5, 20.5, 50)\nlinks.plot(x_gitter,\n           modell_b3.params.iloc[0] + modell_b3.params.iloc[1] * x_gitter,\n           color=\"steelblue\", linewidth=2)\nlinks.set_xlabel(\"Laufzeit (1000 h)\")\nlinks.set_ylabel(\"Verschleiss (Mikrometer)\")\nlinks.set_title(\"Gerade auf krummen Daten\")\nrechts.scatter(modell_b3.fittedvalues, modell_b3.resid, s=14, color=\"0.3\")\nrechts.axhline(0, linestyle=\"--\", color=\"black\")\nglatt = sm.nonparametric.lowess(modell_b3.resid, modell_b3.fittedvalues)\nrechts.plot(glatt[:, 0], glatt[:, 1], color=\"firebrick\", linewidth=2)\nrechts.set_xlabel(\"Vorhersage\")\nrechts.set_title(\"Residuen mit Bogen\")\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselbe Gegenüberstellung in Python.](einfache-lineare-regression_files/figure-html/fig-b3-diagnostik-py-1.png){#fig-b3-diagnostik-py width=100%}\n:::\n:::\n\n\n:::\n\nDer Residuenplot zeigt das Muster, das eine übersehene Krümmung immer erzeugt:\nDie Residuen sind an beiden Rändern positiv und in der Mitte negativ, die\nGlättungslinie bildet einen deutlichen Bogen. Im linken Bild ist zu sehen,\nwarum: Die Gerade liegt bei kleinen und grossen Laufzeiten über den Punkten und\nim mittleren Bereich darunter.\n\n#### Modell korrigieren\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodell_b3q <- lm(verschleiss ~ laufzeit + I(laufzeit^2), data = werkzeug)\nsummary(modell_b3q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = verschleiss ~ laufzeit + I(laufzeit^2), data = werkzeug)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-11.685  -5.106   0.957   5.208  13.243 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   16.77453    7.27097   2.307   0.0313 *  \nlaufzeit       0.05442    1.43629   0.038   0.9701    \nI(laufzeit^2)  0.59307    0.06134   9.668 3.49e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.368 on 21 degrees of freedom\nMultiple R-squared:  0.9914,\tAdjusted R-squared:  0.9906 \nF-statistic:  1214 on 2 and 21 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmodell_b3q = smf.ols(\"verschleiss ~ laufzeit + I(laufzeit**2)\",\n                     data=werkzeug).fit()\nprint(modell_b3q.summary().tables[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n====================================================================================\n                       coef    std err          t      P>|t|      [0.025      0.975]\n------------------------------------------------------------------------------------\nIntercept           16.7745      7.271      2.307      0.031       1.654      31.895\nlaufzeit             0.0544      1.436      0.038      0.970      -2.933       3.041\nI(laufzeit ** 2)     0.5931      0.061      9.668      0.000       0.466       0.721\n====================================================================================\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"R^2 =\", round(modell_b3q.rsquared, 4),\n      \" Residualstreuung =\", round(np.sqrt(modell_b3q.mse_resid), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR^2 = 0.9914  Residualstreuung = 7.368\n```\n\n\n:::\n:::\n\n\n:::\n\n| Vergleich | Gerade | Mit quadratischem Term |\n|---|---|---|\n| R² | 0.9532 | 0.9914 |\n| Residualstreuung | 16.808 µm | 7.368 µm |\n| Achsenabschnitt | -44.590 (unmöglich) | 16.774 (plausibel) |\n\nDie Residualstreuung sinkt auf weniger als die Hälfte, und der Achsenabschnitt\nwird physikalisch sinnvoll. Am R² wäre der Unterschied kaum aufgefallen: 0.95 gegen\n0.99 sieht nach Feinschliff aus, ist aber der Unterschied zwischen falschem und\npassendem Modell.\n\nBemerkenswert im korrigierten Modell: Der lineare Term ist mit p = 0.97 völlig\nunbedeutend, der quadratische mit p < 0.001 hochsignifikant. Der lineare Term\nbleibt trotzdem im Modell. Polynomterme werden von unten aufgebaut und nicht\neinzeln nach p-Werten entfernt, sonst hängt das Ergebnis am willkürlich\ngewählten Nullpunkt der x-Achse.\n\n#### Interpretation und Ergebnissatz\n\nDie Lehre aus diesem Beispiel: Kennzahlen erkennen das Problem nicht. R² war\nhoch, der p-Wert winzig, und beides blieb auch dann so, als das Modell\nnachweislich falsch war. Erkannt wird die Fehlspezifikation am Residuenplot und\nan der Plausibilitätsprüfung des Achsenabschnitts. Deshalb wird der Residuenplot\nangesehen, bevor irgendeine Zahl berichtet wird.\n\n> Ein rein lineares Modell beschreibt den Zusammenhang nicht angemessen; die\n> Residuen zeigen eine deutliche Krümmung und der Achsenabschnitt ist negativ.\n> Berichtet wird das Modell mit quadratischem Term (R² = 0.99, Residualstreuung\n> 7.4 Mikrometer, n = 24); der quadratische Koeffizient beträgt 0.593 Mikrometer je\n> (1000 h)² (p < 0.001).\n\n### Beispiel 4: Ein einziger Punkt kippt das Modell\n\n#### Frage und Datenlage\n\nZu den 24 Anlagen aus Beispiel 1 kommt eine weitere hinzu: 45 Betriebsstunden\nbei nur 20 Litern Verbrauch. Der Wert stammt aus einer Anlage, deren Zähler in\nder Woche ausgefallen war. Er liegt weit rechts ausserhalb der übrigen\nLaufzeiten und weit unter der Geraden.\n\n#### Modell schätzen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmit_fall <- rbind(anlagen, data.frame(laufzeit = 45.0, verbrauch = 20.0))\n\nmodell_b4 <- lm(verbrauch ~ laufzeit, data = mit_fall)\nsummary(modell_b4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = verbrauch ~ laufzeit, data = mit_fall)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-35.668  -8.551   0.755   7.939  30.222 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  44.2644     5.8949   7.509 1.25e-07 ***\nlaufzeit      0.2534     0.3871   0.655    0.519    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 15.08 on 23 degrees of freedom\nMultiple R-squared:  0.01829,\tAdjusted R-squared:  -0.02439 \nF-statistic: 0.4285 on 1 and 23 DF,  p-value: 0.5192\n```\n\n\n:::\n\n```{.r .cell-code}\neinfluss <- data.frame(\n  cook = cooks.distance(modell_b4),\n  hebel = hatvalues(modell_b4)\n)\nround(tail(einfluss, 3), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     cook hebel\n23  0.137 0.060\n24  0.034 0.066\n25 23.906 0.711\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmit_fall = pd.concat(\n    [anlagen, pd.DataFrame({\"laufzeit\": [45.0], \"verbrauch\": [20.0]})],\n    ignore_index=True)\n\nmodell_b4 = smf.ols(\"verbrauch ~ laufzeit\", data=mit_fall).fit()\nprint(modell_b4.summary().tables[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n==============================================================================\n                 coef    std err          t      P>|t|      [0.025      0.975]\n------------------------------------------------------------------------------\nIntercept     44.2644      5.895      7.509      0.000      32.070      56.459\nlaufzeit       0.2534      0.387      0.655      0.519      -0.547       1.054\n==============================================================================\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"R^2 =\", round(modell_b4.rsquared, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR^2 = 0.0183\n```\n\n\n:::\n\n```{.python .cell-code}\neinfluss = modell_b4.get_influence()\nprint(\"Cook-Distanz des letzten Falls:\",\n      round(einfluss.cooks_distance[0][-1], 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCook-Distanz des letzten Falls: 23.906\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Hebelwert des letzten Falls:  \",\n      round(einfluss.hat_matrix_diag[-1], 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHebelwert des letzten Falls:   0.711\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"mittlerer Hebelwert:          \",\n      round(einfluss.hat_matrix_diag.mean(), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmittlerer Hebelwert:           0.08\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Ohne den Fall | Mit dem Fall | Wie das zu lesen ist |\n|---|---|---|---|\n| Steigung | 2.854 | 0.253 | Der Effekt verschwindet fast vollständig. Eine einzige von 25 Beobachtungen dreht die inhaltliche Aussage um. |\n| `Std. Error` | 0.286 | 0.387 | Auch die Unsicherheit steigt. |\n| `Pr(>|t|)` | < 0.001 | 0.519 | Aus einem hochsignifikanten Befund wird ein Nullbefund. |\n| Konfidenzintervall | 2.26 bis 3.45 | -0.55 bis 1.05 | Die beiden Intervalle überschneiden sich nicht einmal. |\n| `Multiple R-squared` | 0.8191 | 0.0183 | Von 82 Prozent auf unter 2 Prozent. |\n| Cook-Distanz des Falls | | 23.906 | Sie misst, wie stark sich alle Vorhersagen ändern, wenn genau dieser Punkt weggelassen wird. Werte über 1 gelten als auffällig; 23.9 ist eine Grössenordnung darüber. |\n| Hebelwert des Falls | | 0.711 | Der Hebel misst, wie extrem der x-Wert liegt. Der Durchschnitt beträgt hier 0.08 (zwei Parameter geteilt durch 25 Beobachtungen); dieser Punkt hat fast den neunfachen Wert. |\n\nHebel und Cook-Distanz sind nicht dasselbe. Ein Punkt mit hohem Hebel liegt weit\naussen auf der x-Achse, richtet aber keinen Schaden an, solange er auf der Linie\nder übrigen liegt. Gefährlich wird die Kombination: extremer x-Wert **und**\nAbweichung nach oben oder unten. Genau die misst die Cook-Distanz.\n\n#### Voraussetzungen prüfen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nplot(mit_fall$laufzeit, mit_fall$verbrauch, pch = 16, col = \"grey30\",\n     xlab = \"Laufzeit (h)\", ylab = \"Verbrauch (l)\", main = \"Alle 25 Fälle\")\npoints(45, 20, pch = 16, col = \"firebrick\", cex = 1.4)\nabline(modell_b4, col = \"firebrick\", lwd = 2)\nabline(modell, col = \"steelblue\", lwd = 2, lty = 2)\nlegend(\"topright\", c(\"mit\", \"ohne\"), col = c(\"firebrick\", \"steelblue\"),\n       lty = c(1, 2), lwd = 2, bty = \"n\", cex = 0.8)\nplot(cooks.distance(modell_b4), type = \"h\", lwd = 2,\n     xlab = \"Beobachtung\", ylab = \"Cook-Distanz\", main = \"Cook-Distanzen\")\nabline(h = 1, lty = 2, col = \"firebrick\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselben Daten mit und ohne den einen Fall.](einfache-lineare-regression_files/figure-html/fig-b4-einfluss-r-1.png){#fig-b4-einfluss-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, (links, rechts) = plt.subplots(1, 2, figsize=(7, 3.2))\nlinks.scatter(mit_fall[\"laufzeit\"], mit_fall[\"verbrauch\"], s=14, color=\"0.3\")\nlinks.scatter([45], [20], s=45, color=\"firebrick\")\nx_gitter = np.linspace(3, 46, 50)\nlinks.plot(x_gitter,\n           modell_b4.params.iloc[0] + modell_b4.params.iloc[1] * x_gitter,\n           color=\"firebrick\", linewidth=2, label=\"mit\")\nlinks.plot(x_gitter,\n           modell.params.iloc[0] + modell.params.iloc[1] * x_gitter,\n           color=\"steelblue\", linewidth=2, linestyle=\"--\", label=\"ohne\")\nlinks.set_xlabel(\"Laufzeit (h)\")\nlinks.set_ylabel(\"Verbrauch (l)\")\nlinks.set_title(\"Alle 25 Fälle\")\nlinks.legend(frameon=False, fontsize=8)\ncook = modell_b4.get_influence().cooks_distance[0]\nrechts.vlines(range(len(cook)), 0, cook, linewidth=2)\nrechts.axhline(1, linestyle=\"--\", color=\"firebrick\")\nrechts.set_xlabel(\"Beobachtung\")\nrechts.set_ylabel(\"Cook-Distanz\")\nrechts.set_title(\"Cook-Distanzen\")\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselbe Gegenüberstellung in Python.](einfache-lineare-regression_files/figure-html/fig-b4-einfluss-py-1.png){#fig-b4-einfluss-py width=100%}\n:::\n:::\n\n\n:::\n\nIm linken Bild ist zu sehen, wie der eine Punkt die Gerade zu sich\nherunterzieht. Rechts ragt seine Cook-Distanz so weit über die Schwelle von 1\nhinaus, dass die übrigen 24 Werte optisch auf der Nulllinie verschwinden.\n\n#### Interpretation und Ergebnissatz\n\nEntscheidend ist, was jetzt **nicht** passiert: Der Punkt wird nicht kommentarlos\ngelöscht, weil er stört. Die Reihenfolge lautet erstens Ursache klären,\nzweitens entscheiden, drittens beides berichten.\n\n| Befund zur Ursache | Vorgehen |\n|---|---|\n| Nachweislicher Messfehler, hier der ausgefallene Zähler | Fall ausschliessen, Ausschluss und Begründung im Bericht nennen |\n| Gültiger, aber andersartiger Betriebszustand | getrennt modellieren oder als zusätzliche Variable aufnehmen |\n| Gültiger Wert, Ursache unklar | Modell mit und ohne den Fall berichten und die Abhängigkeit offenlegen |\n\nIm Beispiel ist die Ursache bekannt, der Fall fliegt heraus, und der Bericht\nsagt das ausdrücklich. Wäre die Ursache unbekannt geblieben, müsste im Bericht\nstehen, dass die gesamte Aussage an einer einzigen Beobachtung hängt.\n\n> Von 25 Anlagen wurde eine ausgeschlossen, deren Verbrauchszähler nachweislich\n> ausgefallen war (45 Betriebsstunden bei 20 Litern; Cook-Distanz 23.9,\n> Hebelwert 0.71). Ohne sie steigt der Verbrauch je Betriebsstunde um 2.85 Liter\n> (95-Prozent-Konfidenzintervall 2.26 bis 3.45, p < 0.001, R² = 0.82, n = 24);\n> unter Einschluss des Falls wäre die Steigung auf 0.25 Liter gefallen und nicht\n> mehr nachweisbar gewesen (p = 0.52).\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEin Modell liefert R² = 0.95, der Residuenplot zeigt einen deutlichen Bogen.\nWas folgt?\n\n- [ ] Das Modell ist gut, R² ist hoch ~ R² misst erklärte Streuung, nicht\n      Angemessenheit. Ein falsches Modell kann viel Streuung erklären, siehe\n      Beispiel 3.\n- [x] Das Modell ist falsch spezifiziert, trotz hohem R² ~ Richtig. Der Bogen\n      zeigt eine übersehene Krümmung. Die Steigung ist ein Kompromiss und\n      stimmt in keinem Bereich; Vorhersagen an den Rändern liegen daneben.\n- [ ] Die Daten enthalten Ausreisser ~ Ausreisser zeigen sich als einzelne weit\n      entfernte Punkte, nicht als durchgehendes Muster.\n:::\n\n::: {.quiz}\nIn Beispiel 2 gibt R ein `Adjusted R-squared` von -0.0271 aus. Ist das ein\nRechenfehler?\n\n- [x] Nein, das korrigierte Mass kann negativ werden ~ Richtig. Es zieht für\n      jeden geschätzten Parameter etwas ab. Erklärt der Prädiktor weniger, als\n      ein beliebiger Prädiktor im Mittel erklären würde, rutscht der Wert unter\n      null. Das ist ein deutliches Zeichen dafür, dass er nichts beiträgt.\n- [ ] Ja, ein Anteil kann nicht negativ sein ~ Das gewöhnliche R² ist ein Anteil\n      und liegt zwischen 0 und 1. Das korrigierte ist ein Schätzer und nicht auf\n      diesen Bereich beschränkt.\n- [ ] Ja, die Daten müssen fehlerhaft sein ~ Die Daten sind in Ordnung, nur der\n      Prädiktor ist es nicht.\n:::\n\n::: {.quiz}\nDie Cook-Distanz einer Beobachtung beträgt 23.9, ihr Hebelwert 0.71. Was ist\nder Unterschied zwischen beiden Zahlen?\n\n- [x] Der Hebel misst, wie extrem der x-Wert liegt, die Cook-Distanz, wie stark\n      der Punkt das Ergebnis verändert ~ Richtig. Ein Punkt mit hohem Hebel ist\n      harmlos, solange er auf der Linie der übrigen liegt. Gefährlich ist die\n      Kombination aus extremem x-Wert und Abweichung von der Geraden, und genau\n      die misst die Cook-Distanz.\n- [ ] Beide messen dasselbe in verschiedener Skalierung ~ Dann könnte es keinen\n      Punkt mit hohem Hebel und kleiner Cook-Distanz geben, den gibt es aber.\n- [ ] Der Hebel bezieht sich auf y, die Cook-Distanz auf x ~ Genau umgekehrt\n      gedacht: Der Hebel hängt allein an den x-Werten.\n:::\n\n::: {.quiz}\nIn Beispiel 1 beträgt R² 0.82 und die Residualstreuung 6.1 Liter. Welche der\nbeiden Zahlen sagt mehr über die Nutzbarkeit einer einzelnen Vorhersage?\n\n- [x] Die Residualstreuung, weil sie in Litern angegeben ist ~ Richtig. Sie sagt\n      unmittelbar, um wie viel eine Vorhersage typischerweise danebenliegt. Ob\n      6 Liter viel oder wenig sind, entscheidet der Anwendungsfall.\n- [ ] R², weil es die Modellgüte misst ~ R² ist relativ zur Gesamtstreuung. Bei\n      sehr unterschiedlichen Laufzeiten wird es hoch, ohne dass die einzelne\n      Vorhersage genauer würde.\n- [ ] Beide gleichermassen ~ Sie hängen zusammen, beantworten aber verschiedene\n      Fragen: R² den Anteil erklärter Streuung, die Residualstreuung den\n      typischen Fehler.\n:::\n\n::: {.quiz}\nDer Achsenabschnitt beträgt 15.2 Liter, die kleinste beobachtete Laufzeit\n3.2 Stunden. Was darf berichtet werden?\n\n- [ ] Bei stillstehender Anlage werden 15.2 Liter verbraucht ~ Der Wert null\n      liegt ausserhalb des beobachteten Bereichs; für ihn ist das Modell nicht\n      geprüft.\n- [x] Der Achsenabschnitt ist ein Rechenwert und hier nicht inhaltlich deutbar ~\n      Richtig. Wer eine deutbare Zahl braucht, zentriert die Laufzeit, dann\n      beschreibt der Achsenabschnitt den Verbrauch bei mittlerer Laufzeit.\n- [ ] Der Wert ist ein Hinweis auf einen Modellfehler ~ Er ist weder falsch noch\n      auffällig, nur ausserhalb des Bereichs, für den Daten vorliegen. Auffällig\n      wäre er erst, wenn er unmöglich ist, wie der negative Verschleiss in\n      Beispiel 3.\n:::\n\n::: {.quiz}\nDer p-Wert der Steigung beträgt 1.25e-09, der p-Wert des\nPearson-Korrelationstests für dieselben Daten ebenfalls. Zufall?\n\n- [x] Nein, bei einem Prädiktor sind die beiden Tests identisch ~ Richtig. Der\n      t-Test der Steigung und der Pearson-Korrelationstest prüfen dieselbe\n      Nullhypothese und liefern dieselbe Teststatistik. Gleiches gilt für den\n      F-Test des Gesamtmodells, dessen Wert genau das Quadrat des t-Werts ist.\n- [ ] Ja, das ist eine zufällige Übereinstimmung ~ Sie tritt bei jedem Datensatz\n      mit einem Prädiktor auf.\n- [ ] Nein, weil beide Verfahren Normalverteilung voraussetzen ~ Die gemeinsame\n      Voraussetzung erklärt nicht, warum die Zahlen exakt gleich sind.\n:::\n\n## Verlinkte Ressourcen\n\n- [OpenIntro Statistics, Kapitel zur einfachen Regression](https://www.openintro.org/book/os/)\n- [An Introduction to Statistical Learning, Kapitel 3](https://www.statlearning.com/)\n- [R-Dokumentation zu `lm`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/lm.html)\n",
    "supporting": [
      "einfache-lineare-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}