{
  "hash": "ae47d7c4fcd83a2c57e421e3e4d48741",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Prüfverteilungen: t, Chi-Quadrat und F\"\ndescription: \"Woher die Verteilungen kommen, unter denen Teststatistiken beurteilt werden.\"\ncategories: [\"Wahrscheinlichkeit\", \"R\", \"Python\"]\nquelle: [\"ESDS\", \"StatDa\"]\nseitentyp: konzept\nstand: entwurf\norder: 80\n---\n\n\n\n\n\n## Kernideen\n\n- Prüfverteilungen sind keine Modelle für Daten, sondern **Verteilungen von\n  Kennzahlen**, die aus Daten berechnet werden.\n- **Chi-Quadrat** ist die Verteilung einer Summe quadrierter Standardnormalen —\n  deshalb taucht sie überall dort auf, wo **Quadrate summiert** werden:\n  Varianzen, Abweichungsquadrate in Kreuztabellen.\n- **t** entsteht, wenn die Streuung im Nenner **geschätzt** statt bekannt ist.\n  Sie ist breiter als die Normalverteilung, weil zwei Grössen zufällig sind\n  statt einer.\n- **F** ist das Verhältnis zweier Varianzschätzungen — die Verteilung hinter\n  jeder Varianzanalyse.\n- Alle drei haben **Freiheitsgrade** als einzigen Parameter (F hat zwei), und\n  alle drei nähern sich mit wachsenden Freiheitsgraden einem einfacheren Fall.\n- Die drei hängen zusammen: $t^2_{df} = F_{1,df}$, und $F$ ist ein Quotient\n  zweier Chi-Quadrat-Grössen.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Normalverteilung und zentraler Grenzwertsatz](normalverteilung-zgws.qmd)\nsowie [stetige Verteilungen](stetige-verteilungen.qmd). Diese Seite ist die\nBrücke zu [Hypothesentests](../inferenz/hypothesentests-grundlagen.qmd) und\n[Konfidenzintervallen](../inferenz/schaetzen-konfidenzintervalle.qmd).\n:::\n\n### Warum es eigene Verteilungen braucht\n\nDie Normal-, Binomial- oder Exponentialverteilung beschreiben **Daten**: Körper-\ngrössen, Trefferzahlen, Wartezeiten. Prüfverteilungen beschreiben etwas\nanderes — nämlich, wie eine aus den Daten berechnete **Kennzahl** streut, wenn\nman den Datensatz gedanklich immer wieder neu zieht.\n\nDas ist der Grund, weshalb sie kaum je zur Beschreibung eines Merkmals\nauftauchen und doch in jeder Testtabelle stehen.\n\n### Die drei auf einen Blick\n\n| | Chi-Quadrat $\\chi^2_{df}$ | $t_{df}$ | $F_{d_1, d_2}$ |\n|---|---|---|---|\n| **entsteht als** | $\\sum_{i=1}^{df} Z_i^2$ | $\\dfrac{Z}{\\sqrt{V/df}}$ | $\\dfrac{V_1/d_1}{V_2/d_2}$ |\n| **Wertebereich** | $[0, \\infty)$ | $(-\\infty, \\infty)$ | $[0, \\infty)$ |\n| **Form** | rechtsschief | symmetrisch, glockenförmig | rechtsschief |\n| **Erwartungswert** | $df$ | $0$ (für $df > 1$) | $\\dfrac{d_2}{d_2 - 2}$ |\n| **Varianz** | $2\\,df$ | $\\dfrac{df}{df-2}$ | — |\n| **Grenzfall** | für grosse $df$ normal | für grosse $df$ normal | $F_{d_1,\\infty} = \\chi^2_{d_1}/d_1$ |\n| **typischer Einsatz** | Kreuztabellen, Varianzen | Mittelwertvergleiche | Varianzanalyse, Modellvergleich |\n\n$Z$ steht dabei jeweils für eine standardnormalverteilte Grösse, $V$ für eine\nchi-quadrat-verteilte.\n\n### Freiheitsgrade\n\nEin Freiheitsgrad ist ein Wert, der noch frei variieren kann. Bei $n$\nBeobachtungen und einem daraus geschätzten Mittelwert bleiben $n-1$: Kennt man\nden Mittelwert und $n-1$ Werte, ist der letzte festgelegt.\n\n**Jeder geschätzte Parameter kostet einen Freiheitsgrad.** Deshalb steht in der\nStichprobenvarianz $n-1$ im Nenner, deshalb hat der t-Test bei zwei Gruppen\n$n_1 + n_2 - 2$ Freiheitsgrade, und deshalb hat eine Kreuztabelle mit $r$ Zeilen\nund $c$ Spalten $(r-1)(c-1)$.\n\n### Die Zusammenhänge\n\n$$t^2_{df} = F_{1, df} \\qquad\\text{und}\\qquad F_{d_1, d_2} = \\frac{\\chi^2_{d_1}/d_1}{\\chi^2_{d_2}/d_2}$$\n\nDer erste Zusammenhang erklärt, warum der t-Test bei zwei Gruppen und die\neinfaktorielle Varianzanalyse denselben p-Wert liefern: Es ist derselbe Test,\neinmal mit Vorzeichen und einmal ohne.\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Wie die Chi-Quadrat-Verteilung entsteht\n\n#### Frage und Datenlage\n\nDie Definition lautet: Summiere $df$ unabhängige quadrierte\nStandardnormalwerte. Was kommt dabei heraus, und stimmt es mit der Theorie\nüberein?\n\n20 000 Wiederholungen, Freiheitsgrade 1, 2, 4 und 10.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN <- 20000\nzeilen <- list()\n\nfor (fg in c(1, 2, 4, 10)) {\n  Z <- normalmatrix(4711, N, fg)\n  X <- rowSums(Z^2)\n  schief <- mean((X - mean(X))^3) / sd(X)^3\n  zeilen[[as.character(fg)]] <- c(\n    df = fg, mittel = mean(X), varianz = var(X),\n    median = median(X), median_theorie = qchisq(0.5, fg),\n    schiefe = schief, schiefe_theorie = sqrt(8 / fg),\n    anteil_ueber_q95 = mean(X > qchisq(0.95, fg)))\n}\nrm(fg)   # damit df weiter die F-Dichte bleibt\nround(do.call(rbind, zeilen), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   df mittel varianz median median_theorie schiefe schiefe_theorie\n1   1 1.0004  1.9834 0.4696         0.4549  2.8335          2.8284\n2   2 1.9822  3.8970 1.3712         1.3863  1.9302          2.0000\n4   4 3.9961  7.9940 3.3533         3.3567  1.3887          1.4142\n10 10 9.9744 19.7141 9.3256         9.3418  0.8717          0.8944\n   anteil_ueber_q95\n1            0.0489\n2            0.0508\n4            0.0512\n10           0.0502\n```\n\n\n:::\n\n```{.r .cell-code}\n# Und die Dichte darueber gelegt, fuer df = 4\nZ <- normalmatrix(4711, N, 4)\nX <- rowSums(Z^2)\nggplot(data.frame(x = X), aes(x)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 60,\n                 fill = \"grey80\", colour = \"white\") +\n  stat_function(fun = dchisq, args = list(df = 4), linewidth = 0.9) +\n  coord_cartesian(xlim = c(0, 25)) +\n  labs(x = \"Summe von 4 quadrierten Standardnormalwerten\", y = \"Dichte\")\n```\n\n::: {.cell-output-display}\n![Beispiel 1: simulierte Summen quadrierter Standardnormalwerte gegen die Chi-Quadrat-Dichte.](pruefverteilungen_files/figure-html/fig-b1-pv-r-1.png){#fig-b1-pv-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nN = 20000\nzeilen = []\n\nfor df in [1, 2, 4, 10]:\n    Z = normalmatrix(4711, N, df)\n    X = (Z ** 2).sum(axis=1)\n    zeilen.append({\"df\": df, \"mittel\": X.mean(), \"varianz\": X.var(ddof=1),\n                   \"median\": np.median(X), \"median_theorie\": stats.chi2.ppf(.5, df),\n                   \"schiefe\": stats.skew(X), \"schiefe_theorie\": np.sqrt(8 / df),\n                   \"anteil_ueber_q95\": (X > stats.chi2.ppf(.95, df)).mean()})\nprint(pd.DataFrame(zeilen).round(4).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n df  mittel  varianz  median  median_theorie  schiefe  schiefe_theorie  anteil_ueber_q95\n  1  1.0004   1.9834  0.4696          0.4549   2.8338           2.8284            0.0489\n  2  1.9822   3.8970  1.3712          1.3863   1.9303           2.0000            0.0508\n  4  3.9961   7.9940  3.3533          3.3567   1.3888           1.4142            0.0512\n 10  9.9744  19.7141  9.3256          9.3418   0.8717           0.8944            0.0502\n```\n\n\n:::\n\n```{.python .cell-code}\nZ = normalmatrix(4711, N, 4)\nX = (Z ** 2).sum(axis=1)\n\nfig, achse = plt.subplots(figsize=(7, 4))\nachse.hist(X, bins=60, density=True, color=\"0.8\", edgecolor=\"white\")\ngitter = np.linspace(0, 25, 400)\nachse.plot(gitter, stats.chi2.pdf(gitter, 4), lw=1.6, color=\"black\")\nachse.set_xlim(0, 25)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(0.0, 25.0)\n```\n\n\n:::\n\n```{.python .cell-code}\nachse.set_xlabel(\"Summe von 4 quadrierten Standardnormalwerten\")\nachse.set_ylabel(\"Dichte\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Simulation in Python.](pruefverteilungen_files/figure-html/fig-b1-pv-py-1.png){#fig-b1-pv-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| df | Mittel | Varianz | Median | Median theoretisch | Schiefe | Schiefe theoretisch | Anteil über $q_{0.95}$ |\n|---|---|---|---|---|---|---|---|\n| 1 | 1.000 | 1.983 | 0.470 | 0.455 | 2.834 | 2.828 | 0.0489 |\n| 2 | 1.982 | 3.897 | 1.371 | 1.386 | 1.930 | 2.000 | 0.0508 |\n| 4 | 3.996 | 7.994 | 3.353 | 3.357 | 1.389 | 1.414 | 0.0512 |\n| 10 | 9.974 | 19.714 | 9.326 | 9.342 | 0.872 | 0.894 | 0.0502 |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Der Mittelwert ist jedes Mal ungefähr **df** | $E(Z^2) = 1$ für jede Standardnormale, und $df$ davon aufsummiert ergibt $df$. Das ist die ganze Herleitung. |\n| Die Varianz ist ungefähr **2 df** | 1.98, 3.90, 7.99, 19.71 gegen 2, 4, 8, 20. |\n| Der Median liegt **unter** dem Mittelwert | 3.353 gegen 3.996 bei df = 4. Die Verteilung ist rechtsschief; ein einzelner grosser Quadratwert zieht den Mittelwert nach oben, den Median nicht. |\n| Die Schiefe sinkt von **2.83 auf 0.87** | Genau wie $\\sqrt{8/df}$ es verlangt. **Mit wachsenden Freiheitsgraden wird die Verteilung symmetrisch** — der zentrale Grenzwertsatz wirkt auch auf eine Summe von Quadraten. |\n| Der Anteil oberhalb des 95-Prozent-Quantils liegt bei **0.049 bis 0.051** | Die Simulation trifft die theoretischen Quantile. Damit ist geprüft, dass die Konstruktion stimmt und nicht nur die ersten zwei Momente passen. |\n\n::: {.warning-box}\n**Eine Falle des Lehmer-Generators, die hier zuschlägt.** Auf den anderen Seiten\ndieser Sammlung bekommt jede Variable eine eigene Saat. Für eine Summe aus\nvielen Quadraten geht das **schief**: Ein multiplikativer Generator erzeugt aus\nder Saat $s$ die Folge $16807^k \\cdot s \\bmod m$. Zwei Saaten, von denen die\neine ein kleines Vielfaches der anderen ist, liefern deshalb **linear abhängige\nStröme**.\n\n| Saatpaar | Korrelation der Ströme |\n|---|---|\n| 1000 und 1001 | 0.030 |\n| 7001 und 7002 | −0.016 |\n| **101 und 202** | **0.584** |\n\nBei 202 = 2 · 101 ist der zweite Strom exakt das Doppelte des ersten modulo $m$.\nDie Folge davon in diesem Beispiel: Mit zehn einzeln gesäten Spalten ergab sich\neine Schiefe von 3.63 statt 0.89 und ein Ablehnanteil von 0.13 statt 0.05 — bei\nkorrektem Mittelwert und korrekter Varianz. **Der Fehler wäre also durch eine\nKontrolle der ersten zwei Momente nicht aufgefallen.**\n\n**Regel:** Für mehrdimensionale Daten **einen langen Strom ziehen und umformen**\n(`normalmatrix` oben), nicht eine Saat je Spalte. Und nie Saaten wählen, bei\ndenen die eine ein kleines Vielfaches der anderen ist.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Summe von $df$ quadrierten Standardnormalwerten folgt der\n> Chi-Quadrat-Verteilung mit $df$ Freiheitsgraden: Mittelwert $df$, Varianz\n> $2\\,df$, rechtsschief mit einer Schiefe von $\\sqrt{8/df}$, die mit wachsendem\n> $df$ verschwindet.\n\n### Beispiel 2: Warum die Stichprobenvarianz chi-quadrat-verteilt ist\n\n#### Frage und Datenlage\n\nDer Zusammenhang, der die Chi-Quadrat-Verteilung in die Praxis bringt:\n\n$$\\frac{(n-1)\\,s^2}{\\sigma^2} \\sim \\chi^2_{n-1}$$\n\nSechs Beobachtungen aus einer Standardnormalverteilung, 20 000 mal. Warum\n$n-1$ und nicht $n$?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN <- 20000; n <- 6\nS <- normalmatrix(4711, N, n)\ns2 <- apply(S, 1, var)\ngroesse <- (n - 1) * s2 / 1   # sigma^2 = 1\n\nround(c(mittel = mean(groesse), theorie_mittel = n - 1,\n        varianz = var(groesse), theorie_varianz = 2 * (n - 1),\n        anteil_unter_q05 = mean(groesse <= qchisq(0.05, n - 1)),\n        anteil_ueber_q95 = mean(groesse > qchisq(0.95, n - 1))), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          mittel   theorie_mittel          varianz  theorie_varianz \n          4.9988           5.0000           9.9781          10.0000 \nanteil_unter_q05 anteil_ueber_q95 \n          0.0504           0.0496 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Der Vergleich: durch n statt durch n-1 geteilt\ns2_falsch <- apply(S, 1, function(z) mean((z - mean(z))^2))\nround(c(mit_n_minus_1 = mean(s2), mit_n = mean(s2_falsch), wahrer_wert = 1), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmit_n_minus_1         mit_n   wahrer_wert \n       0.9998        0.8331        1.0000 \n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(data.frame(x = groesse), aes(x)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 60,\n                 fill = \"grey80\", colour = \"white\") +\n  stat_function(fun = dchisq, args = list(df = n - 1), linewidth = 0.9) +\n  coord_cartesian(xlim = c(0, 20)) +\n  labs(x = \"(n-1) s² / σ²\", y = \"Dichte\")\n```\n\n::: {.cell-output-display}\n![Beispiel 2: Verteilung der skalierten Stichprobenvarianz bei n = 6.](pruefverteilungen_files/figure-html/fig-b2-pv-r-3.png){#fig-b2-pv-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nN, n = 20000, 6\nS = normalmatrix(4711, N, n)\ns2 = S.var(axis=1, ddof=1)\ngroesse = (n - 1) * s2 / 1.0\n\nprint({\"mittel\": round(float(groesse.mean()), 4), \"theorie_mittel\": n - 1,\n       \"varianz\": round(float(groesse.var(ddof=1)), 4),\n       \"theorie_varianz\": 2 * (n - 1),\n       \"anteil_unter_q05\": round(float((groesse <= stats.chi2.ppf(.05, n - 1)).mean()), 4),\n       \"anteil_ueber_q95\": round(float((groesse > stats.chi2.ppf(.95, n - 1)).mean()), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'mittel': 4.9988, 'theorie_mittel': 5, 'varianz': 9.9781, 'theorie_varianz': 10, 'anteil_unter_q05': 0.0503, 'anteil_ueber_q95': 0.0496}\n```\n\n\n:::\n\n```{.python .cell-code}\ns2_falsch = S.var(axis=1, ddof=0)\nprint({\"mit_n_minus_1\": round(float(s2.mean()), 4),\n       \"mit_n\": round(float(s2_falsch.mean()), 4), \"wahrer_wert\": 1})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'mit_n_minus_1': 0.9998, 'mit_n': 0.8331, 'wahrer_wert': 1}\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achse = plt.subplots(figsize=(7, 3.4))\nachse.hist(groesse, bins=60, density=True, color=\"0.8\", edgecolor=\"white\")\ngitter = np.linspace(0, 20, 400)\nachse.plot(gitter, stats.chi2.pdf(gitter, n - 1), lw=1.6, color=\"black\")\nachse.set_xlim(0, 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(0.0, 20.0)\n```\n\n\n:::\n\n```{.python .cell-code}\nachse.set_xlabel(\"(n-1) s² / σ²\")\nachse.set_ylabel(\"Dichte\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselbe Verteilung in Python.](pruefverteilungen_files/figure-html/fig-b2-pv-py-1.png){#fig-b2-pv-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | Wert | Theorie |\n|---|---|---|\n| Mittelwert von $(n-1)s^2/\\sigma^2$ | **4.999** | 5 |\n| Varianz | **9.978** | 10 |\n| Anteil unter $q_{0.05}$ | **0.0503** | 0.05 |\n| Anteil über $q_{0.95}$ | **0.0496** | 0.05 |\n\n| Teiler | mittlere geschätzte Varianz | wahrer Wert |\n|---|---|---|\n| $n-1$ | **1.0000** | 1 |\n| $n$ | **0.8331** | 1 |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die skalierte Varianz verhält sich exakt wie $\\chi^2_5$ | Mittelwert 5, Varianz 10, beide Randanteile bei 5 Prozent. Nicht nur ungefähr, sondern in allen vier Kennzahlen. |\n| Die Freiheitsgrade sind **5**, nicht 6 | Die Abweichungen werden vom **geschätzten** Mittelwert gemessen, nicht vom wahren. Kennt man fünf davon, ist die sechste festgelegt, weil sich alle sechs zu null addieren. |\n| Mit $n$ im Nenner ergibt sich im Mittel **0.833** statt 1 | Also $5/6$ des wahren Werts, genau der Faktor $(n-1)/n$. **Das ist die Bessel-Korrektur**, hier nicht als Formel, sondern als gemessene Unterschätzung. |\n| Die Verteilung ist stark **rechtsschief** | Bei $n = 6$. Ein Konfidenzintervall für eine Varianz ist deshalb **nicht symmetrisch** um die Schätzung — anders als bei einem Mittelwert. |\n\n::: {.note-box}\n**Warum das praktisch wichtig ist:** Aus dieser Verteilung folgt das\nKonfidenzintervall für eine Varianz —\n\n$$\\left[\\frac{(n-1)s^2}{\\chi^2_{1-\\alpha/2}},\\ \\frac{(n-1)s^2}{\\chi^2_{\\alpha/2}}\\right]$$\n\n— und bei kleinem $n$ ist es **erschreckend breit**. Bei $n = 6$ und $s^2 = 1$\nreicht es von 0.39 bis 4.85, also über mehr als eine Zehnerpotenz. Wer eine\nStreuung schätzen will, braucht deutlich mehr Beobachtungen als für einen\nMittelwert.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die mit $(n-1)/\\sigma^2$ skalierte Stichprobenvarianz folgt bei normalverteilten\n> Daten der Chi-Quadrat-Verteilung mit $n-1$ Freiheitsgraden. Teilt man\n> stattdessen durch $n$, unterschätzt die Schätzung die wahre Varianz im Mittel\n> um den Faktor $(n-1)/n$, hier 0.833 statt 1.\n\n### Beispiel 3: Warum es die t-Verteilung braucht\n\n#### Frage und Datenlage\n\nEine Stichprobe von fünf Werten, der Mittelwert wird an seiner geschätzten\nStreuung gemessen. Was passiert, wenn man dabei mit 1.96 rechnet, als wäre die\nStreuung bekannt?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN <- 20000; n <- 5\nS <- normalmatrix(5711, N, n)\nmittel <- rowMeans(S)\nstreuung <- apply(S, 1, sd)\n\nt_wert <- mittel / (streuung / sqrt(n))   # Streuung geschaetzt\nz_wert <- mittel / (1 / sqrt(n))          # Streuung bekannt\n\nround(c(sd_t = sd(t_wert), theorie_sd_t = sqrt((n - 1) / (n - 3)),\n        sd_z = sd(z_wert),\n        anteil_t_ueber_196 = mean(abs(t_wert) > 1.96),\n        anteil_t_ueber_tquantil = mean(abs(t_wert) > qt(0.975, n - 1)),\n        anteil_z_ueber_196 = mean(abs(z_wert) > 1.96),\n        t_quantil = qt(0.975, n - 1)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   sd_t            theorie_sd_t                    sd_z \n                 1.3853                  1.4142                  1.0054 \n     anteil_t_ueber_196 anteil_t_ueber_tquantil      anteil_z_ueber_196 \n                 0.1242                  0.0495                  0.0515 \n              t_quantil \n                 2.7764 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Was das fuer Konfidenzintervalle bedeutet: deckt das Intervall die wahre 0?\nbreite_z <- 2 * 1.96 * streuung / sqrt(n)\nbreite_t <- 2 * qt(0.975, n - 1) * streuung / sqrt(n)\nround(c(ueberdeckung_mit_196 = mean(abs(mittel) < 1.96 * streuung / sqrt(n)),\n        ueberdeckung_mit_t = mean(abs(mittel) < qt(0.975, n - 1) * streuung / sqrt(n)),\n        mittlere_breite_z = mean(breite_z),\n        mittlere_breite_t = mean(breite_t)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nueberdeckung_mit_196   ueberdeckung_mit_t    mittlere_breite_z \n              0.8758               0.9504               1.6539 \n   mittlere_breite_t \n              2.3428 \n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(data.frame(x = t_wert), aes(x)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 120,\n                 fill = \"grey80\", colour = NA) +\n  stat_function(fun = dt, args = list(df = n - 1), linewidth = 0.9) +\n  stat_function(fun = dnorm, linewidth = 0.9, linetype = \"dashed\") +\n  coord_cartesian(xlim = c(-6, 6)) +\n  labs(x = \"t-Wert\", y = \"Dichte\")\n```\n\n::: {.cell-output-display}\n![Beispiel 3: t-Verteilung mit 4 Freiheitsgraden gegen die Standardnormalverteilung.](pruefverteilungen_files/figure-html/fig-b3-pv-r-3.png){#fig-b3-pv-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nN, n = 20000, 5\nS = normalmatrix(5711, N, n)\nmittel = S.mean(axis=1)\nstreuung = S.std(axis=1, ddof=1)\n\nt_wert = mittel / (streuung / np.sqrt(n))\nz_wert = mittel / (1 / np.sqrt(n))\n\nprint({\"sd_t\": round(float(t_wert.std(ddof=1)), 4),\n       \"theorie_sd_t\": round(float(np.sqrt((n - 1) / (n - 3))), 4),\n       \"sd_z\": round(float(z_wert.std(ddof=1)), 4),\n       \"anteil_t_ueber_196\": round(float((abs(t_wert) > 1.96).mean()), 4),\n       \"anteil_t_ueber_tquantil\":\n           round(float((abs(t_wert) > stats.t.ppf(.975, n - 1)).mean()), 4),\n       \"anteil_z_ueber_196\": round(float((abs(z_wert) > 1.96).mean()), 4),\n       \"t_quantil\": round(float(stats.t.ppf(.975, n - 1)), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'sd_t': 1.3853, 'theorie_sd_t': 1.4142, 'sd_z': 1.0054, 'anteil_t_ueber_196': 0.1242, 'anteil_t_ueber_tquantil': 0.0495, 'anteil_z_ueber_196': 0.0515, 't_quantil': 2.7764}\n```\n\n\n:::\n\n```{.python .cell-code}\nbreite_z = 2 * 1.96 * streuung / np.sqrt(n)\nbreite_t = 2 * stats.t.ppf(.975, n - 1) * streuung / np.sqrt(n)\nprint({\"ueberdeckung_mit_196\":\n           round(float((abs(mittel) < 1.96 * streuung / np.sqrt(n)).mean()), 4),\n       \"ueberdeckung_mit_t\":\n           round(float((abs(mittel)\n                        < stats.t.ppf(.975, n - 1) * streuung / np.sqrt(n)).mean()), 4),\n       \"mittlere_breite_z\": round(float(breite_z.mean()), 4),\n       \"mittlere_breite_t\": round(float(breite_t.mean()), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'ueberdeckung_mit_196': 0.8758, 'ueberdeckung_mit_t': 0.9505, 'mittlere_breite_z': 1.6539, 'mittlere_breite_t': 2.3428}\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achse = plt.subplots(figsize=(7, 3.4))\nachse.hist(t_wert, bins=120, density=True, color=\"0.8\")\ngitter = np.linspace(-6, 6, 400)\nachse.plot(gitter, stats.t.pdf(gitter, n - 1), lw=1.6, color=\"black\")\nachse.plot(gitter, stats.norm.pdf(gitter), lw=1.6, ls=\"--\", color=\"black\")\nachse.set_xlim(-6, 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(-6.0, 6.0)\n```\n\n\n:::\n\n```{.python .cell-code}\nachse.set_xlabel(\"t-Wert\")\nachse.set_ylabel(\"Dichte\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselbe Gegenüberstellung in Python.](pruefverteilungen_files/figure-html/fig-b3-pv-py-1.png){#fig-b3-pv-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | Streuung **bekannt** (z) | Streuung **geschätzt** (t) |\n|---|---|---|\n| Standardabweichung der Statistik | **1.005** | **1.385** (Theorie $\\sqrt{4/2} = 1.414$) |\n| Anteil mit Betrag über 1.96 | **0.0515** | **0.1242** |\n| Anteil über dem richtigen Quantil | 0.0515 (bei 1.96) | **0.0495** (bei 2.7764) |\n\n| Konfidenzintervall | Überdeckung | mittlere Breite |\n|---|---|---|\n| mit 1.96 gerechnet | **0.8758** | **1.654** |\n| mit $t_{0.975;4} = 2.7764$ | **0.9505** | **2.343** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die t-Statistik streut **stärker** als die z-Statistik | 1.385 gegen 1.005. Im Nenner steht eine geschätzte Grösse, und deren Zufälligkeit kommt zur Zufälligkeit des Zählers hinzu. Ist die geschätzte Streuung zufällig klein, wird der Bruch gross. |\n| Mit 1.96 gerechnet liegt der Fehler 1. Art bei **12.4 Prozent** statt 5 | Mehr als das Doppelte. Bei $n = 5$ ist das kein Schönheitsfehler, sondern ein anderer Test. |\n| Das Konfidenzintervall deckt nur **87.6 Prozent** statt 95 | Dieselbe Sache von der anderen Seite gesehen. |\n| Der Preis der Korrektur ist die **Breite** | 2.343 gegen 1.654, also 42 Prozent breiter. Die Unsicherheit über die Streuung wird ehrlich mitgetragen. |\n| Mit dem richtigen Quantil stimmt alles | 0.0495 und 0.9505. Die t-Verteilung ist genau die Korrektur, die es braucht. |\n\n::: {.note-box}\n**Wie schnell die Korrektur unwichtig wird:** Der Faktor $t_{0.975;df}$ nähert\nsich 1.96.\n\n| df | 1 | 2 | 5 | 10 | 30 | 100 | ∞ |\n|---|---|---|---|---|---|---|---|\n| $t_{0.975}$ | 12.706 | 4.303 | 2.571 | 2.228 | 2.042 | 1.984 | 1.960 |\n\nAb etwa 30 Freiheitsgraden liegt der Unterschied unter 5 Prozent — daher die\nverbreitete Faustregel. Unter 10 ist er dramatisch, und bei df = 1 (die\nCauchy-Verteilung) hat die t-Verteilung **keinen Erwartungswert und keine\nVarianz** mehr.\n\n**Das erklärt zugleich, warum die t-Verteilung selten für Daten verwendet\nwird und trotzdem in jeder Tabelle steht:** Sie beschreibt nicht Messwerte,\nsondern das Verhältnis aus Schätzung und geschätztem Standardfehler.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Bei $n = 5$ führt das Rechnen mit dem Normalquantil 1.96 statt mit\n> $t_{0.975;4} = 2.776$ zu einem Fehler 1. Art von 12.4 statt 5 Prozent und zu\n> Konfidenzintervallen, die nur 87.6 statt 95 Prozent überdecken. Mit dem\n> t-Quantil stimmen beide Werte.\n\n### Beispiel 4: Die F-Verteilung und ihre Empfindlichkeit\n\n#### Frage und Datenlage\n\n$F$ ist ein Verhältnis zweier Varianzschätzungen. Zwei Dinge werden hier\ngeprüft: dass die Konstruktion stimmt, und was passiert, wenn die Daten nicht\nnormalverteilt sind.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN <- 20000; d1 <- 5; d2 <- 10\nA <- normalmatrix(6811, N, d1)\nB <- normalmatrix(9137, N, d2)\nFwert <- (rowSums(A^2) / d1) / (rowSums(B^2) / d2)\n\nround(c(mittel = mean(Fwert), theorie_mittel = d2 / (d2 - 2),\n        median = median(Fwert), theorie_median = qf(0.5, d1, d2),\n        anteil_ueber_q95 = mean(Fwert > qf(0.95, d1, d2))), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          mittel   theorie_mittel           median   theorie_median \n          1.2481           1.2500           0.9273           0.9319 \nanteil_ueber_q95 \n          0.0508 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Der Zusammenhang t^2 = F\nround(c(t_quantil_hoch2 = qt(0.975, 4)^2, F_quantil = qf(0.95, 1, 4)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt_quantil_hoch2       F_quantil \n         7.7086          7.7086 \n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(data.frame(x = Fwert), aes(x)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 150,\n                 fill = \"grey80\", colour = NA) +\n  stat_function(fun = df, args = list(df1 = d1, df2 = d2), linewidth = 0.9) +\n  coord_cartesian(xlim = c(0, 6)) +\n  labs(x = \"F-Wert\", y = \"Dichte\")\n```\n\n::: {.cell-output-display}\n![Beispiel 4: simuliertes Varianzverhältnis gegen die F-Dichte.](pruefverteilungen_files/figure-html/fig-b4-pv-r-3.png){#fig-b4-pv-r width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Wie robust ist der F-Test auf gleiche Varianzen?\n# Beide Gruppen haben immer dieselbe Varianz -- abgelehnt werden duerfte in\n# 5 Prozent der Faelle.\nN <- 10000; n1 <- 20; n2 <- 20\nu <- matrix(lehmer(2718, N * (n1 + n2)), nrow = N, byrow = TRUE)\nnormal <- qnorm(u)\nexponential <- -log(u)\n\nvarquotient <- function(M) {\n  apply(M[, 1:n1], 1, var) / apply(M[, (n1 + 1):(n1 + n2)], 1, var)\n}\nunten <- qf(0.025, n1 - 1, n2 - 1); oben <- qf(0.975, n1 - 1, n2 - 1)\n\nfn <- varquotient(normal); fe <- varquotient(exponential)\nround(c(F_test_normal = mean(fn < unten | fn > oben),\n        F_test_exponential = mean(fe < unten | fe > oben),\n        krit_unten = unten, krit_oben = oben), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     F_test_normal F_test_exponential         krit_unten          krit_oben \n            0.0502             0.2661             0.3958             2.5265 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Brown-Forsythe als Alternative: F-Statistik auf den Abstaenden zum Median\nbrown_forsythe <- function(M) {\n  A <- M[, 1:n1]; B <- M[, (n1 + 1):(n1 + n2)]\n  dA <- abs(A - apply(A, 1, median)); dB <- abs(B - apply(B, 1, median))\n  mA <- rowMeans(dA); mB <- rowMeans(dB)\n  gesamt <- (mA * n1 + mB * n2) / (n1 + n2)\n  zwischen <- n1 * (mA - gesamt)^2 + n2 * (mB - gesamt)^2\n  innen <- rowSums((dA - mA)^2) + rowSums((dB - mB)^2)\n  zwischen / (innen / (n1 + n2 - 2))\n}\nkf <- qf(0.95, 1, n1 + n2 - 2)\nround(c(bf_normal = mean(brown_forsythe(normal) > kf),\n        bf_exponential = mean(brown_forsythe(exponential) > kf),\n        woelbung_normal = mean((normal - mean(normal))^4) / sd(normal)^4,\n        woelbung_exponential = mean((exponential - mean(exponential))^4) /\n          sd(exponential)^4), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           bf_normal       bf_exponential      woelbung_normal \n              0.0375               0.0475               3.0080 \nwoelbung_exponential \n              9.1316 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nN, d1, d2 = 20000, 5, 10\nA = normalmatrix(6811, N, d1)\nB = normalmatrix(9137, N, d2)\nFwert = ((A ** 2).sum(axis=1) / d1) / ((B ** 2).sum(axis=1) / d2)\n\nprint({\"mittel\": round(float(Fwert.mean()), 4),\n       \"theorie_mittel\": round(d2 / (d2 - 2), 4),\n       \"median\": round(float(np.median(Fwert)), 4),\n       \"theorie_median\": round(float(stats.f.ppf(.5, d1, d2)), 4),\n       \"anteil_ueber_q95\":\n           round(float((Fwert > stats.f.ppf(.95, d1, d2)).mean()), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'mittel': 1.2481, 'theorie_mittel': 1.25, 'median': 0.9273, 'theorie_median': 0.9319, 'anteil_ueber_q95': 0.0508}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"t_quantil_hoch2\": round(float(stats.t.ppf(.975, 4)) ** 2, 4),\n       \"F_quantil\": round(float(stats.f.ppf(.95, 1, 4)), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'t_quantil_hoch2': 7.7086, 'F_quantil': 7.7086}\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achse = plt.subplots(figsize=(7, 3.4))\nachse.hist(Fwert, bins=150, density=True, color=\"0.8\")\ngitter = np.linspace(0.01, 6, 400)\nachse.plot(gitter, stats.f.pdf(gitter, d1, d2), lw=1.6, color=\"black\")\nachse.set_xlim(0, 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(0.0, 6.0)\n```\n\n\n:::\n\n```{.python .cell-code}\nachse.set_xlabel(\"F-Wert\")\nachse.set_ylabel(\"Dichte\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselbe Verteilung in Python.](pruefverteilungen_files/figure-html/fig-b4-pv-py-1.png){#fig-b4-pv-py width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.python .cell-code}\nN, n1, n2 = 10000, 20, 20\nu = lehmer(2718, N * (n1 + n2)).reshape(N, n1 + n2)\nnormal = stats.norm.ppf(u)\nexponential = -np.log(u)\n\n\ndef varquotient(M):\n    return M[:, :n1].var(axis=1, ddof=1) / M[:, n1:].var(axis=1, ddof=1)\n\n\nunten = stats.f.ppf(.025, n1 - 1, n2 - 1)\noben = stats.f.ppf(.975, n1 - 1, n2 - 1)\nfn = varquotient(normal)\nfe = varquotient(exponential)\nprint({\"F_test_normal\": round(float(((fn < unten) | (fn > oben)).mean()), 4),\n       \"F_test_exponential\": round(float(((fe < unten) | (fe > oben)).mean()), 4),\n       \"krit_unten\": round(float(unten), 4), \"krit_oben\": round(float(oben), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'F_test_normal': 0.0502, 'F_test_exponential': 0.2661, 'krit_unten': 0.3958, 'krit_oben': 2.5265}\n```\n\n\n:::\n\n```{.python .cell-code}\ndef brown_forsythe(M):\n    A, B = M[:, :n1], M[:, n1:]\n    dA = np.abs(A - np.median(A, axis=1, keepdims=True))\n    dB = np.abs(B - np.median(B, axis=1, keepdims=True))\n    mA, mB = dA.mean(axis=1), dB.mean(axis=1)\n    gesamt = (mA * n1 + mB * n2) / (n1 + n2)\n    zwischen = n1 * (mA - gesamt) ** 2 + n2 * (mB - gesamt) ** 2\n    innen = ((dA - mA[:, None]) ** 2).sum(axis=1) + ((dB - mB[:, None]) ** 2).sum(axis=1)\n    return zwischen / (innen / (n1 + n2 - 2))\n\n\nkf = stats.f.ppf(.95, 1, n1 + n2 - 2)\nprint({\"bf_normal\": round(float((brown_forsythe(normal) > kf).mean()), 4),\n       \"bf_exponential\": round(float((brown_forsythe(exponential) > kf).mean()), 4),\n       \"woelbung_normal\": round(float(stats.kurtosis(normal.ravel(), fisher=False)), 4),\n       \"woelbung_exponential\":\n           round(float(stats.kurtosis(exponential.ravel(), fisher=False)), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'bf_normal': 0.0375, 'bf_exponential': 0.0475, 'woelbung_normal': 3.008, 'woelbung_exponential': 9.1317}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nZuerst die Konstruktion, $F_{5,10}$:\n\n| Grösse | Simulation | Theorie |\n|---|---|---|\n| Mittelwert | **1.2481** | $10/8 = 1.25$ |\n| Median | **0.9273** | 0.9319 |\n| Anteil über $q_{0.95}$ | **0.0508** | 0.05 |\n| $t_{0.975;4}^2$ gegen $F_{0.95;1,4}$ | **7.7086** | **7.7086** |\n\nUnd die Empfindlichkeit, beide Gruppen mit **derselben** wahren Varianz:\n\n| Test | normalverteilte Daten | exponentialverteilte Daten |\n|---|---|---|\n| **F-Test** auf gleiche Varianzen | **0.0502** | **0.2661** |\n| **Brown-Forsythe** | **0.0375** | **0.0475** |\n| Wölbung der Daten | 3.008 | 9.132 |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Der Mittelwert ist **nicht 1**, sondern 1.25 | Obwohl Zähler und Nenner denselben Erwartungswert haben. Bei einem Quotienten ist $E(1/X) \\neq 1/E(X)$; der Nennerfreiheitsgrad bestimmt, wie stark der Effekt ist. Bei $d_2 = 10$ sind es 25 Prozent. Der **Median** liegt dagegen nahe bei 1. |\n| $t^2 = F$ auf sieben Stellen | 7.7086 beide Male. **Der t-Test mit zwei Gruppen und die Varianzanalyse sind derselbe Test.** |\n| Der F-Test hält bei Normalverteilung genau 5 Prozent | 0.0502. Unter seiner Annahme ist er exakt. |\n| Bei exponentialverteilten Daten lehnt er in **26.6 Prozent** der Fälle ab | Bei völlig gleichen Varianzen. **Das ist mehr als das Fünffache des Versprochenen.** Der F-Test auf Varianzgleichheit prüft in Wahrheit die Normalverteilungsannahme mit. |\n| Brown-Forsythe bleibt bei **4.8 Prozent** | Weil er mit Abständen zum Median statt mit Quadraten rechnet und die Wölbung damit kaum eine Rolle spielt. |\n| Brown-Forsythe ist bei Normalverteilung leicht **konservativ** | 3.75 statt 5 Prozent bei $n = 20$ pro Gruppe. Der Preis für die Robustheit. |\n\n::: {.warning-box}\n**Die praktische Folge:** Der klassische F-Test auf Varianzgleichheit — in R\n`var.test()`, in Python `scipy.stats.f.cdf` von Hand — ist als Vorschaltprüfung\nvor einem t-Test **nicht zu gebrauchen**. Bei schiefen Daten schlägt er ständig\nAlarm, ohne dass die Varianzen verschieden wären.\n\n| Aufgabe | brauchbar | nicht brauchbar |\n|---|---|---|\n| Varianzen zweier Gruppen vergleichen | Levene, Brown-Forsythe | klassischer F-Test |\n| Mittelwerte vergleichen, wenn Varianzen unklar | Welch-t-Test (immer) | t-Test nach Vorschaltprüfung |\n| Modelle vergleichen (Varianzanalyse, Regression) | F-Test — hier ist er am Platz | — |\n\nBeim **Modellvergleich** ist die F-Verteilung dagegen der richtige Rahmen und\ngegenüber mässiger Nichtnormalität unempfindlich, weil dort die\n**Mittelwerte** im Zähler stehen und der zentrale Grenzwertsatz greift. Beim\nVarianzvergleich stehen die Streuungen selbst im Zähler, und der Grenzwertsatz\nhilft nicht.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Das Verhältnis zweier unabhängiger Varianzschätzungen folgt der\n> F-Verteilung; ihr Median liegt nahe bei 1, ihr Mittelwert bei\n> $d_2/(d_2-2)$. Der F-Test auf Varianzgleichheit hält sein Niveau nur bei\n> normalverteilten Daten: bei exponentialverteilten lehnt er in 26.6 statt\n> 5 Prozent der Fälle ab, während Brown-Forsythe bei 4.8 Prozent bleibt.\n\n### Beispiel 5: Dieselben Daten, drei Prüfverteilungen\n\n#### Frage und Datenlage\n\nZwei Gruppen zu je zwölf Messwerten. Drei verschiedene Fragen, drei\nTeststatistiken, drei Verteilungen — an einem einzigen Datensatz.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 12\nX <- normalmatrix(8123, 2, n)\na <- 50 + 8 * X[1, ]\nb <- 50 + 8 * X[2, ] + 6\n\nround(rbind(gruppe_a = a, gruppe_b = b), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9] [,10] [,11] [,12]\ngruppe_a 37.8 49.63 56.23 52.34 53.48 52.14 41.48 48.35 61.50 50.21 42.90 43.80\ngruppe_b 67.9 63.61 51.07 61.51 61.31 56.65 55.71 69.96 50.31 59.19 50.79 68.15\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(mittel_a = mean(a), mittel_b = mean(b),\n        sd_a = sd(a), sd_b = sd(b)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmittel_a mittel_b     sd_a     sd_b \n 49.1542  59.6791   6.7283   6.9586 \n```\n\n\n:::\n\n```{.r .cell-code}\n# (1) Mittelwertvergleich -> t-Verteilung\nergebnis_t <- t.test(b, a, var.equal = TRUE)\nround(c(t = unname(ergebnis_t$statistic), df = unname(ergebnis_t$parameter),\n        p = ergebnis_t$p.value), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      t      df       p \n 3.7667 22.0000  0.0011 \n```\n\n\n:::\n\n```{.r .cell-code}\n# (2) Dieselbe Frage als Varianzanalyse -> F-Verteilung\nalle <- c(a, b); gesamtmittel <- mean(alle)\nsq_zwischen <- n * (mean(a) - gesamtmittel)^2 + n * (mean(b) - gesamtmittel)^2\nsq_innen <- sum((a - mean(a))^2) + sum((b - mean(b))^2)\nFwert <- (sq_zwischen / 1) / (sq_innen / (2 * n - 2))\nround(c(sq_zwischen = sq_zwischen, sq_innen = sq_innen, F = Fwert,\n        p = pf(Fwert, 1, 2 * n - 2, lower.tail = FALSE),\n        t_hoch2 = unname(ergebnis_t$statistic)^2), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsq_zwischen    sq_innen           F           p     t_hoch2 \n   664.6400   1030.6165     14.1877      0.0011     14.1877 \n```\n\n\n:::\n\n```{.r .cell-code}\n# (3) Passen die Daten zur unterstellten Verteilung? -> Chi-Quadrat\ngrenzen <- qnorm(c(0.25, 0.5, 0.75), 50, 8)\nbeobachtet <- table(cut(alle, c(-Inf, grenzen, Inf)))\nerwartet <- rep(length(alle) / 4, 4)\nchi <- sum((beobachtet - erwartet)^2 / erwartet)\nround(grenzen, 3); beobachtet\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 44.604 50.000 55.396\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n(-Inf,44.6]   (44.6,50]   (50,55.4] (55.4, Inf] \n          4           2           7          11 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(chi_quadrat = chi, df = 3,\n        p = pchisq(chi, 3, lower.tail = FALSE)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nchi_quadrat          df           p \n     7.6667      3.0000      0.0534 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nn = 12\nX = normalmatrix(8123, 2, n)\na = 50 + 8 * X[0]\nb = 50 + 8 * X[1] + 6\n\nprint(pd.DataFrame({\"gruppe_a\": a, \"gruppe_b\": b}).T.round(2).to_string())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            0      1      2      3      4      5      6      7      8      9      10     11\ngruppe_a  37.8  49.63  56.23  52.34  53.48  52.14  41.48  48.35  61.50  50.21  42.90  43.80\ngruppe_b  67.9  63.61  51.07  61.51  61.31  56.65  55.71  69.96  50.31  59.19  50.79  68.15\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"mittel_a\": round(float(a.mean()), 4), \"mittel_b\": round(float(b.mean()), 4),\n       \"sd_a\": round(float(a.std(ddof=1)), 4), \"sd_b\": round(float(b.std(ddof=1)), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'mittel_a': 49.1542, 'mittel_b': 59.6791, 'sd_a': 6.7283, 'sd_b': 6.9586}\n```\n\n\n:::\n\n```{.python .cell-code}\nt, p = stats.ttest_ind(b, a)\nprint({\"t\": round(float(t), 4), \"df\": 2 * n - 2, \"p\": round(float(p), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'t': 3.7667, 'df': 22, 'p': 0.0011}\n```\n\n\n:::\n\n```{.python .cell-code}\nalle = np.concatenate([a, b])\ngesamtmittel = alle.mean()\nsq_zwischen = n * (a.mean() - gesamtmittel) ** 2 + n * (b.mean() - gesamtmittel) ** 2\nsq_innen = ((a - a.mean()) ** 2).sum() + ((b - b.mean()) ** 2).sum()\nFwert = (sq_zwischen / 1) / (sq_innen / (2 * n - 2))\nprint({\"sq_zwischen\": round(float(sq_zwischen), 4),\n       \"sq_innen\": round(float(sq_innen), 4), \"F\": round(float(Fwert), 4),\n       \"p\": round(float(stats.f.sf(Fwert, 1, 2 * n - 2)), 4),\n       \"t_hoch2\": round(float(t) ** 2, 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'sq_zwischen': 664.64, 'sq_innen': 1030.6165, 'F': 14.1877, 'p': 0.0011, 't_hoch2': 14.1877}\n```\n\n\n:::\n\n```{.python .cell-code}\ngrenzen = stats.norm.ppf([.25, .5, .75], 50, 8)\nbeobachtet = np.histogram(alle, bins=np.concatenate([[-np.inf], grenzen, [np.inf]]))[0]\nerwartet = np.repeat(len(alle) / 4, 4)\nchi = float((((beobachtet - erwartet) ** 2) / erwartet).sum())\nprint(np.round(grenzen, 3), beobachtet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[44.604 50.    55.396] [ 4  2  7 11]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"chi_quadrat\": round(chi, 4), \"df\": 3,\n       \"p\": round(float(stats.chi2.sf(chi, 3)), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'chi_quadrat': 7.6667, 'df': 3, 'p': 0.0534}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Gruppe | Mittelwert | Standardabweichung |\n|---|---|---|\n| A | **49.154** | 6.728 |\n| B | **59.679** | 6.959 |\n\n| Frage | Statistik | Verteilung | Wert | df | p |\n|---|---|---|---|---|---|\n| Unterscheiden sich die Mittelwerte? | $t$ | **t** | **3.7667** | 22 | **0.0011** |\n| Dieselbe Frage als Varianzzerlegung | $F$ | **F** | **14.1877** | 1 und 22 | **0.0011** |\n| Passen die Werte zur Verteilung N(50, 8²)? | $\\chi^2$ | **Chi-Quadrat** | **7.6667** | 3 | **0.0534** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| $t^2 = 3.7667^2 = 14.1877 = F$ | Auf vier Stellen identisch, und die p-Werte ebenso: 0.0011 beide Male. **Es ist derselbe Test in zwei Schreibweisen.** Der t-Wert trägt das Vorzeichen und sagt, welche Gruppe grösser ist; der F-Wert wirft es weg. |\n| Die Quadratsummen zerlegen die Streuung | 664.64 zwischen den Gruppen, 1030.62 innerhalb. $F$ ist das Verhältnis der beiden, jeweils auf ihre Freiheitsgrade bezogen: $\\frac{664.64/1}{1030.62/22}$. |\n| Der Chi-Quadrat-Test beantwortet eine **andere** Frage | Nicht \"sind die Mittelwerte gleich\", sondern \"liegen die 24 Werte so, wie N(50, 8²) es erwarten liesse\". Die vier Quartilsklassen sollten je 6 Werte enthalten, beobachtet wurden **4, 2, 7 und 11**. |\n| Sein p-Wert liegt bei **0.053** | Knapp über 5 Prozent. Der Test bemerkt die Verschiebung der Gruppe B, aber er hat wenig Kraft, weil er 24 Werte in vier Klassen zusammenwirft und dabei die Gruppenzugehörigkeit ignoriert. Der t-Test mit derselben Information kommt auf 0.0011. |\n| Die Freiheitsgrade sind jedes Mal andere | 22 beim t-Test ($2n-2$, zwei geschätzte Mittelwerte), 1 und 22 beim F-Test, 3 beim Chi-Quadrat-Test (vier Klassen minus eine Nebenbedingung, die Summe ist festgelegt). |\n\n::: {.note-box}\n**Die Merkregel, welche Verteilung wann auftaucht:**\n\n| Im Zähler steht … | Verteilung | Beispiele |\n|---|---|---|\n| eine **Schätzung**, im Nenner ihr geschätzter Standardfehler | **t** | Ein-/Zweistichproben-t-Test, Regressionskoeffizient |\n| eine **Summe von Abweichungsquadraten** | **Chi-Quadrat** | Anpassungstest, Unabhängigkeitstest, Likelihood-Quotient |\n| ein **Verhältnis zweier Varianzschätzungen** | **F** | Varianzanalyse, Modellvergleich zweier Regressionen |\n\nNicht die Fragestellung entscheidet, sondern die **Bauart der Statistik**.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> An denselben 24 Werten liefert der t-Test $t(22) = 3.77$ mit $p = 0.0011$, die\n> Varianzanalyse $F(1, 22) = 14.19$ mit demselben $p$, weil $F = t^2$ gilt, und\n> der Chi-Quadrat-Anpassungstest $\\chi^2(3) = 7.67$ mit $p = 0.053$ — eine\n> andere Frage, eine andere Verteilung, eine andere Antwort.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nWarum ist die Chi-Quadrat-Verteilung nie negativ?\n\n- [x] Weil sie eine Summe von Quadraten ist ~ Richtig. Quadrate sind nicht\n      negativ, also ist ihre Summe es auch nicht.\n- [ ] Weil Wahrscheinlichkeiten nicht negativ sind ~ Das gilt für jede\n      Verteilung und erklärt den Wertebereich nicht.\n- [ ] Weil sie nur bei Häufigkeiten verwendet wird ~ Sie beschreibt auch die\n      Stichprobenvarianz, und der Grund liegt in der Konstruktion.\n:::\n\n::: {.quiz}\nDie Simulation ergab bei sechs Beobachtungen im Mittel eine Varianz von 0.833\nstatt 1, wenn durch n geteilt wurde. Wie heisst dieser Effekt?\n\n- [x] Bessel-Korrektur, der Faktor ist n minus eins durch n ~ Richtig. Die\n      Abweichungen werden vom geschätzten Mittelwert gemessen, der näher an den\n      Daten liegt als der wahre. Fünf Sechstel sind genau 0.833.\n- [ ] Zentraler Grenzwertsatz ~ Der betrifft die Verteilung von Summen, nicht\n      die Verzerrung einer Varianzschätzung.\n- [ ] Zufall, bei 20 000 Wiederholungen kann das vorkommen ~ Der\n      Standardfehler liegt hier bei rund 0.004; eine Abweichung von 0.167 ist\n      systematisch.\n:::\n\n::: {.quiz}\nWarum ist die t-Verteilung breiter als die Normalverteilung?\n\n- [x] Weil im Nenner eine geschätzte statt einer bekannten Streuung steht ~\n      Richtig. Zwei zufällige Grössen statt einer. Fällt die geschätzte\n      Streuung klein aus, wird der Quotient gross.\n- [ ] Weil die Daten nicht normalverteilt sind ~ In der Simulation waren sie es\n      exakt, und die t-Verteilung war trotzdem breiter.\n- [ ] Weil der Stichprobenumfang klein ist ~ Das bestimmt nur, wie viel\n      breiter. Der Grund ist die Schätzung der Streuung.\n:::\n\n::: {.quiz}\nBei fünf Beobachtungen wurde mit 1.96 statt mit 2.776 gerechnet. Was war die\nFolge?\n\n- [x] Der Fehler 1. Art stieg auf 12.4 Prozent und die Überdeckung sank auf\n      87.6 Prozent ~ Richtig, mehr als das Doppelte des versprochenen Niveaus.\n      Der Preis der Korrektur sind 42 Prozent breitere Intervalle.\n- [ ] Es machte praktisch keinen Unterschied ~ Ab etwa 30 Freiheitsgraden\n      stimmt das, bei vier nicht.\n- [ ] Die Intervalle wurden zu breit ~ Sie wurden zu schmal; 1.96 ist kleiner\n      als 2.776.\n:::\n\n::: {.quiz}\nDer F-Test auf gleiche Varianzen lehnte bei exponentialverteilten Daten in 26.6\nProzent der Fälle ab, obwohl die Varianzen gleich waren. Was folgt daraus?\n\n- [x] Er ist als Vorschaltprüfung vor einem t-Test unbrauchbar ~ Richtig. Er\n      reagiert auf die Wölbung der Verteilung mit, hier 9.1 statt 3.0. Levene\n      oder Brown-Forsythe blieben bei rund 5 Prozent. Praktisch sinnvoller ist\n      ohnehin der Welch-t-Test ohne Vorschaltprüfung.\n- [ ] Exponentialverteilte Daten haben verschiedene Varianzen ~ Beide Gruppen\n      stammten aus derselben Verteilung.\n- [ ] Die F-Verteilung ist grundsätzlich unbrauchbar ~ Beim Modellvergleich in\n      der Varianzanalyse ist sie am Platz und unempfindlich, weil dort\n      Mittelwerte im Zähler stehen.\n:::\n\n::: {.quiz}\nDer t-Wert war 3.7667, der F-Wert 14.1877, beide p-Werte 0.0011. Zufall?\n\n- [x] Nein, 3.7667 zum Quadrat ist 14.1877; es ist derselbe Test ~ Richtig, es\n      gilt t² mit df Freiheitsgraden gleich F mit 1 und df. Der t-Wert behält\n      das Vorzeichen und sagt zusätzlich, welche Gruppe grösser ist.\n- [ ] Zufall bei diesem Datensatz ~ Der Zusammenhang gilt algebraisch für jeden\n      Datensatz mit zwei Gruppen.\n- [ ] Weil beide Tests dieselben Daten verwenden ~ Der Chi-Quadrat-Test\n      verwendete ebenfalls dieselben Daten und kam auf p gleich 0.053.\n:::\n\n## Verlinkte Ressourcen\n\n- [Hypothesentests: Grundlagen](../inferenz/hypothesentests-grundlagen.qmd)\n- [Schätzen und Konfidenzintervalle](../inferenz/schaetzen-konfidenzintervalle.qmd)\n- [Normalverteilung und zentraler Grenzwertsatz](normalverteilung-zgws.qmd)\n- [NIST/SEMATECH e-Handbook of Statistical Methods](https://www.itl.nist.gov/div898/handbook/eda/section3/eda366.htm)\n",
    "supporting": [
      "pruefverteilungen_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}