{
  "hash": "16e79678cfa50d05c475e39d622fe0ae",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Versuchsplanung und A/B-Tests\"\ndescription: \"Randomisierung, Stichprobenumfang vorab, das Problem mit dem Zwischendurch-Schauen und die Auswertung eines A/B-Tests.\"\ncategories: [\"Versuchsplanung\", \"A/B-Testing\", \"Power\", \"Hypothesentests\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: methode\nstand: fertig\norder: 90\n---\n\n\n\n\n\nDie Beispiele rechnen mit festen Zahlen oder mit dem Lehmer-Generator. R und\nPython geben dieselben Werte aus.\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Wie wird ein Experiment so angelegt, dass es die Frage beantworten kann, und wie wird es danach ausgewertet? |\n| Kern | Randomisierung, vorab festgelegter Stichprobenumfang, eine vorab festgelegte Auswertung |\n| Was die Planung liefert | Umfang je Gruppe, Laufzeit, Entscheidungsregel |\n| Auswertung eines A/B-Tests | Differenz zweier Anteile mit Konfidenzintervall und Test |\n| R-Funktion | `power.prop.test()`, `prop.test(correct = FALSE)` |\n| Python-Funktion | `statsmodels.stats.proportion.proportions_ztest()`, `confint_proportions_2indep()` |\n| Verwandte Methoden | [Power und Stichprobenumfang](power-stichprobenumfang.qmd), [multiples Testen](multiples-testen.qmd), [Bayessche Inferenz](bayessche-inferenz.qmd) |\n\n## Wann diese Methode, wann nicht\n\nEin Experiment ist der einzige Weg, der ohne weitere Annahmen eine Ursache\nbelegt: Weil der Zufall entscheidet, wer Variante A und wer Variante B sieht,\nunterscheiden sich die Gruppen im Mittel in nichts ausser der Variante. Jeder\nUnterschied im Ergebnis geht dann auf die Variante zurück.\n\n| Situation | Stattdessen |\n|---|---|\n| Zuteilung nicht steuerbar, nur Beobachtungsdaten | [Kausale Inferenz](kausale-inferenz.qmd) mit ihren zusätzlichen Annahmen |\n| Dieselbe Person sieht beide Varianten | Messwiederholung, [gepaarter t-Test](../tests/t-test-gepaart.qmd) oder [gemischtes Modell](../regression/gemischte-modelle.qmd) |\n| Viele Varianten gleichzeitig | Varianzanalyse oder mehrere Vergleiche mit [Korrektur](multiples-testen.qmd) |\n| Laufende Überwachung mit Abbruch gewünscht | sequenzielles Testverfahren mit angepassten Grenzen |\n\n## Grundidee und Modell\n\nDrei Entscheidungen fallen **vor** dem ersten Datenpunkt:\n\n| Entscheidung | Was sie festlegt | Warum vorher |\n|---|---|---|\n| Zielgrösse | eine primäre Kennzahl, etwa die Anmelderate | Wer nachher unter zehn Kennzahlen die signifikante wählt, testet zehnmal |\n| Kleinster relevanter Effekt | ab welchem Unterschied sich eine Umstellung lohnt | bestimmt den Umfang; nachträglich gewählt ist er beliebig |\n| Stichprobenumfang und Laufzeit | wann ausgewertet wird | Wer auswertet, sobald es signifikant aussieht, erhöht die Fehlerrate (Beispiel 2) |\n\nDer Umfang je Gruppe für zwei Anteile $p_1$ und $p_2$ bei Niveau $\\alpha$ und\nPower $1-\\beta$, mit $\\bar p = (p_1+p_2)/2$:\n\n$$n = \\frac{\\left(z_{1-\\alpha/2}\\sqrt{2\\bar p(1-\\bar p)} + z_{1-\\beta}\\sqrt{p_1(1-p_1)+p_2(1-p_2)}\\right)^2}{(p_1-p_2)^2}$$\n\nDer Nenner ist das Quadrat des Effekts. Halb so grosse Effekte brauchen deshalb\nrund viermal so viele Beobachtungen.\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung | Vorgehen |\n|---|---|---|---|---|\n| Echte Randomisierung | Zufall, nicht Uhrzeit, Browser oder Wochentag, entscheidet über die Gruppe | Anteile je Gruppe gegen die geplante Aufteilung prüfen | systematische Unterschiede zwischen den Gruppen | Zuteilung reparieren, Test neu starten |\n| Unabhängige Einheiten | eine Person zählt einmal, nicht jeder Seitenaufruf | Einheit der Randomisierung gleich Einheit der Auswertung | zu kleine Standardfehler | auf Personenebene auswerten |\n| Keine Beeinflussung zwischen Gruppen | A-Nutzer sehen B nicht | Design | Effekt verwässert | Randomisierung auf höherer Ebene, etwa Region |\n| Vorab festgelegte Laufzeit | kein Abbruch nach Sichtung | Plan dokumentieren | Fehlerrate steigt | sequenzielles Verfahren, falls Abbruch nötig |\n\nEin oft übersehener Check ist der **Sample Ratio Mismatch**: Sollten 50 Prozent\nin jede Gruppe, kommen aber 52 zu 48 bei grossem n, ist die Zuteilung defekt,\nund das Ergebnis ist nicht verwertbar, egal wie gut es aussieht.\n\n## Output lesen\n\nR, `prop.test(c(xB, xA), c(nB, nA), correct = FALSE)`:\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| `X-squared` | Teststatistik, das Quadrat von z | ohne `correct = FALSE` mit Stetigkeitskorrektur und etwas grösserem p |\n| `p-value` | wie überraschend die Differenz wäre, wenn beide Varianten gleich wirken | wie bei jedem Test keine Aussage über die Grösse |\n| `95 percent confidence interval` | Intervall der Differenz der Anteile | gegen den kleinsten relevanten Effekt halten, nicht nur gegen null |\n| `prop 1`, `prop 2` | beobachtete Anteile | Reihenfolge wie in den Argumenten |\n\nPython, `proportions_ztest()` und `confint_proportions_2indep()`:\n\n| Rückgabe | Entspricht in R |\n|---|---|\n| `stat` | Wurzel aus `X-squared`, mit Vorzeichen |\n| `pvalue` | `p-value` |\n| Intervall mit `method=\"wald\"` | `95 percent confidence interval` ohne Korrektur |\n\n## Interpretationsfallen\n\n- **Zwischendurch schauen und bei Signifikanz aufhören** macht aus 5 Prozent\n  falschen Alarmen ein Vielfaches. Beispiel 2 misst es.\n- **Signifikant heisst nicht relevant.** Bei 100 000 Besuchen je Gruppe ist\n  eine Differenz von 0.3 Prozentpunkten signifikant und oft wertlos.\n- **Nicht signifikant bei zu kleinem Test heisst nichts.** Ohne Planung des\n  Umfangs ist ein Nullbefund nicht interpretierbar.\n- **Neuheitseffekte:** Eine neue Variante wirkt oft in den ersten Tagen stärker.\n  Laufzeiten unter einer vollen Woche mischen ausserdem Wochentage ungleich.\n- **Viele Kennzahlen, eine gewinnt:** Wer nachher die beste unter vielen wählt,\n  braucht eine [Korrektur für multiples Testen](multiples-testen.qmd).\n\n## Ergebnis berichten\n\n> In einem randomisierten Test mit [nA] Besuchen in Variante A und [nB] in\n> Variante B lag die [Zielgrösse] bei [Anteil A] gegen [Anteil B]. Die Differenz\n> beträgt [Wert] Prozentpunkte (95-Prozent-Konfidenzintervall [unten] bis\n> [oben], z = [z], p = [p]). Der vorab festgelegte kleinste relevante Effekt von\n> [Wert] Prozentpunkten [liegt im Intervall / liegt oberhalb des Intervalls].\n\nImmer genannt werden: Einheit der Randomisierung, geplanter und erreichter\nUmfang, Laufzeit, primäre Zielgrösse, Differenz mit Intervall und der Bezug zum\nkleinsten relevanten Effekt.\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt eines klassischen A/B-Tests |\n|---|---|\n| [Bayessche Inferenz](bayessche-inferenz.qmd) | Wahrscheinlichkeit für „B ist besser\" gefragt, Vorwissen vorhanden |\n| [Chi-Quadrat-Test](../tests/chi-quadrat-tests.qmd) | mehr als zwei Varianten oder mehr als zwei Ausgänge |\n| [t-Test für zwei Stichproben](../tests/t-test-zwei-stichproben.qmd) | metrische Zielgrösse wie Umsatz je Besuch |\n| [Kausale Inferenz](kausale-inferenz.qmd) | kein Experiment möglich |\n\n## Beispiele\n\nJedes Beispiel steht in einem eigenen Reiter.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Wie viele Besuche braucht der Test\n\n#### Frage und Datenlage\n\nDie aktuelle Anmelderate liegt bei 10 Prozent. Ein Test soll bei Niveau 0.05\nmit 80 Prozent Power einen Anstieg erkennen. Wie viele Besuche braucht es je\nGruppe, wenn der kleinste relevante Anstieg 2, 1 oder 0.5 Prozentpunkte beträgt?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nziel <- c(0.12, 0.11, 0.105)\ndata.frame(p2 = ziel,\n           n_exakt = round(sapply(ziel, function(p) n_je_gruppe(0.10, p)), 1),\n           n_je_gruppe = ceiling(sapply(ziel, function(p) n_je_gruppe(0.10, p))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     p2 n_exakt n_je_gruppe\n1 0.120  3840.8        3841\n2 0.110 14750.8       14751\n3 0.105 57762.7       57763\n```\n\n\n:::\n\n```{.r .cell-code}\n# dieselbe Zahl mit der eingebauten Funktion\nround(power.prop.test(p1 = 0.10, p2 = 0.12, power = 0.8)$n, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3840.8\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nziel = [0.12, 0.11, 0.105]\nprint(pd.DataFrame({\n    \"p2\": ziel,\n    \"n_exakt\": [round(float(n_je_gruppe(0.10, p)), 1) for p in ziel],\n    \"n_je_gruppe\": [int(np.ceil(n_je_gruppe(0.10, p))) for p in ziel],\n}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      p2  n_exakt  n_je_gruppe\n0  0.120   3840.8         3841\n1  0.110  14750.8        14751\n2  0.105  57762.7        57763\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ziel | Umfang je Gruppe | Wie er zu lesen ist |\n|---|---|---|\n| 10 auf 12 Prozent | 3841 | gut 7700 Besuche insgesamt |\n| 10 auf 11 Prozent | 14751 | halber Effekt, fast vierfacher Umfang |\n| 10 auf 10.5 Prozent | 57763 | nochmals halbiert, wieder rund viermal so viel |\n\n`power.prop.test()` liefert für den ersten Fall ebenfalls 3840.8, also\naufgerundet 3841. Die Funktion rechnet mit derselben Formel.\n\n#### Interpretation und Ergebnissatz\n\nDer Umfang hängt quadratisch am kleinsten relevanten Effekt. Daraus folgt die\neigentliche Planungsfrage: Bei 2000 Besuchen am Tag dauert der erste Test vier\nTage, der letzte acht Wochen. Ob sich ein halber Prozentpunkt acht Wochen\nTestzeit lohnt, ist eine fachliche Entscheidung, keine statistische.\n\n> Um einen Anstieg der Anmelderate von 10 auf 12 Prozent mit 80 Prozent Power\n> bei zweiseitigem Niveau 0.05 zu erkennen, braucht der Test 3841 Besuche je\n> Variante.\n\n### Beispiel 2: Zwischendurch schauen\n\n#### Frage und Datenlage\n\nEin Team schaut während des Tests regelmässig auf den p-Wert und beendet den\nTest, sobald er unter 0.05 fällt. Wie oft meldet es dann einen Effekt, obwohl es\n**keinen** gibt?\n\nSimuliert werden 1000 Tests, in denen beide Varianten gleich wirken. Jeder Test\nläuft über 20 gleich grosse Blöcke; nach jedem Block entsteht eine neue\nTeststatistik. Die Zufallszahlen kommen aus dem Lehmer-Generator, R und Python\nsehen dieselben 20 000 Werte.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nE <- 1000; L <- 20\nzuwachs <- matrix(qnorm(lehmer(2026, E * L)), nrow = E, byrow = TRUE)\n\n# Teststatistik nach k Bloecken: Summe der Zuwaechse geteilt durch Wurzel k\nz_nach_block <- t(apply(zuwachs, 1, cumsum)) / matrix(sqrt(1:L), E, L, byrow = TRUE)\nalarm <- abs(z_nach_block) > qnorm(0.975)\n\nc(nur_am_ende   = mean(alarm[, L]),\n  fuenf_blicke  = mean(apply(alarm[, c(4, 8, 12, 16, 20)], 1, any)),\n  zwanzig_blicke = mean(apply(alarm, 1, any)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   nur_am_ende   fuenf_blicke zwanzig_blicke \n         0.049          0.143          0.250 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nE, L = 1000, 20\nzuwachs = stats.norm.ppf(lehmer(2026, E * L)).reshape(E, L)\n\nz_nach_block = np.cumsum(zuwachs, axis=1) / np.sqrt(np.arange(1, L + 1))\nalarm = np.abs(z_nach_block) > stats.norm.ppf(0.975)\n\nprint(\"nur am Ende:   \", alarm[:, -1].mean())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnur am Ende:    0.049\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"fuenf Blicke:  \", alarm[:, [3, 7, 11, 15, 19]].any(axis=1).mean())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfuenf Blicke:   0.143\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"zwanzig Blicke:\", alarm.any(axis=1).mean())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nzwanzig Blicke: 0.25\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Vorgehen | Anteil falscher Alarme | Wie er zu lesen ist |\n|---|---|---|\n| nur am geplanten Ende auswerten | 0.049 | entspricht dem Niveau von 5 Prozent |\n| fünfmal schauen, bei Signifikanz aufhören | 0.143 | knapp dreimal so viele falsche Alarme |\n| nach jedem der 20 Blöcke schauen | 0.25 | jeder vierte Test meldet einen Effekt, den es nicht gibt |\n\n#### Interpretation und Ergebnissatz\n\nJeder Blick ist ein weiterer Test. Weil die Teststatistik unter der\nNullhypothese hin und her schwankt, überschreitet sie die Grenze irgendwann mit\nhoher Wahrscheinlichkeit, auch wenn sie am Ende wieder darunter läge. Wer\nzwischendurch abbrechen können muss, braucht ein sequenzielles Verfahren mit\nstrengeren Grenzen je Blick.\n\n> Wird ein Test ohne Effekt nach jedem von 20 Blöcken ausgewertet und bei\n> Signifikanz beendet, meldet er in 25 Prozent der Fälle einen Effekt, statt in\n> den vorgesehenen 5 Prozent.\n\n### Beispiel 3: Den A/B-Test auswerten\n\n#### Frage und Datenlage\n\nGeplant waren 4000 Besuche je Variante für einen kleinsten relevanten Anstieg\nvon einem Prozentpunkt. Variante A erzielte 480 Anmeldungen, Variante B 552.\nIst B besser, und ist der Unterschied relevant?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(c(552, 480), c(4000, 4000), correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions without continuity correction\n\ndata:  c(552, 480) out of c(4000, 4000)\nX-squared = 5.7672, df = 1, p-value = 0.01633\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.003314781 0.032685219\nsample estimates:\nprop 1 prop 2 \n 0.138  0.120 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom statsmodels.stats.proportion import proportions_ztest, confint_proportions_2indep\n\nz_wert, p_wert = proportions_ztest([552, 480], [4000, 4000])\nunten, oben = confint_proportions_2indep(552, 4000, 480, 4000, method=\"wald\")\nprint(\"Anteile:\", 480 / 4000, 552 / 4000, \" Differenz:\", round(552 / 4000 - 480 / 4000, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnteile: 0.12 0.138  Differenz: 0.018\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"z:\", round(z_wert, 4), \" X-squared:\", round(z_wert ** 2, 4), \" p:\", round(p_wert, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nz: 2.4015  X-squared: 5.7672  p: 0.0163\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Intervall:\", round(unten, 4), \"bis\", round(oben, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIntervall: 0.0033 bis 0.0327\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| `prop 1`, `prop 2` | 0.138 und 0.12 | Anmelderaten B und A | B liegt 1.8 Prozentpunkte vorn |\n| `X-squared` | 5.7672 | Teststatistik | das Quadrat von z = 2.4015 |\n| `p-value` | 0.0163 | unter 0.05 | spricht gegen gleiche Raten |\n| `95 percent confidence interval` | 0.0033 bis 0.0327 | plausible Differenzen | enthält die Null nicht, reicht aber von 0.3 bis 3.3 Prozentpunkten |\n\n#### Interpretation und Ergebnissatz\n\nStatistisch ist B besser. Relevant im Sinn der Planung ist der Unterschied nur\nwahrscheinlich: Das Intervall liegt überwiegend über dem kleinsten relevanten\nEffekt von einem Prozentpunkt, schliesst aber Werte darunter nicht aus. Wer\neine sichere Aussage zur Relevanz braucht, muss das vor dem Test als\nEntscheidungsregel festlegen, etwa „Umstellung, wenn die untere Grenze über\neinem Prozentpunkt liegt\".\n\n> Variante B erzielte eine Anmelderate von 13.8 Prozent gegenüber 12.0 Prozent\n> bei A (je 4000 Besuche). Die Differenz beträgt 1.8 Prozentpunkte\n> (95-Prozent-Konfidenzintervall 0.3 bis 3.3, z = 2.40, p = 0.016).\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEin Test soll einen halb so grossen Effekt erkennen wie ursprünglich geplant.\nWie verändert sich der nötige Umfang ungefähr?\n\n- [x] Er vervierfacht sich ~ Richtig. Der Effekt steht quadriert im Nenner der\n      Formel. Beispiel 1 zeigt den Faktor zweimal.\n- [ ] Er verdoppelt sich ~ Das wäre ein linearer Zusammenhang; der Umfang wächst\n      aber mit dem Quadrat.\n- [ ] Er bleibt gleich, nur die Power sinkt ~ Bei gleichem Umfang sinkt die\n      Power tatsächlich, aber für dieselbe Power braucht es mehr Daten.\n:::\n\n::: {.quiz}\nEin A/B-Test läuft seit drei Tagen, der p-Wert liegt heute bei 0.03. Geplant\nwaren zwei Wochen. Was ist richtig?\n\n- [x] Weiterlaufen lassen bis zum geplanten Ende und dann auswerten ~ Richtig.\n      Ein Abbruch bei Signifikanz erhöht die Rate falscher Alarme, wie\n      Beispiel 2 zeigt.\n- [ ] Jetzt beenden, das Ergebnis ist signifikant ~ Genau das ist das\n      Zwischendurch-Schauen mit überhöhter Fehlerrate.\n- [ ] Beenden und das Niveau nachträglich auf 0.01 senken ~ Nachträgliche\n      Anpassungen machen die Fehlerrate nicht kontrollierbar.\n:::\n\n::: {.quiz}\nStatt 50 zu 50 kamen bei 100 000 Besuchen 51 800 in Variante A. Was bedeutet\ndas?\n\n- [x] Die Zuteilung ist wahrscheinlich defekt, das Ergebnis nicht verwertbar ~\n      Richtig. Das ist ein Sample Ratio Mismatch. Bei diesem Umfang ist eine\n      solche Abweichung durch Zufall praktisch ausgeschlossen, also\n      unterscheiden sich die Gruppen systematisch.\n- [ ] Nichts, kleine Ungleichheiten sind normal ~ Bei 100 000 Besuchen\n      schwankt der Anteil nur um wenige Zehntelprozent.\n- [ ] Die Auswertung muss gewichtet werden ~ Gewichten korrigiert nicht,\n      warum bestimmte Besuche in einer Gruppe fehlen.\n:::\n\n## Verlinkte Ressourcen\n\n- [Trustworthy Online Controlled Experiments (Kohavi, Tang, Xu)](https://experimentguide.com/)\n- [Evan Miller: How Not To Run an A/B Test](https://www.evanmiller.org/how-not-to-run-an-ab-test.html)\n- [statsmodels: Proportion](https://www.statsmodels.org/stable/stats.html#proportion)\n",
    "supporting": [
      "versuchsplanung-ab-tests_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}