{
  "hash": "3293c4bbd5a34dfa86868bb1e8db6098",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Dashboards und Interaktivität\"\ndescription: \"Was Interaktion bringt, was sie kostet, und wie man Dashboards ordnet.\"\ncategories: [\"Dashboards\", \"Interaktivität\", \"Visualisierung\", \"Deployment\", \"R\", \"Python\"]\nquelle: [\"DAVI\"]\nseitentyp: werkzeug\nstand: fertig\norder: 90\nengine: knitr\n---\n\n\n\n\n\n## Kernideen\n\n- Drei Auslieferungsformen: **statisch, interaktiv, dialogisch**. Interaktion\n  verschiebt Arbeit zum Publikum und ist deshalb rechtfertigungspflichtig.\n- Ein Dashboard ohne Entscheidungsfrage wird zur Kennzahlentapete.\n- **Der Takt bestimmt die Schwelle.** Dieselbe Grenze löst bei täglicher\n  Betrachtung Dauerfeuer aus und bei monatlicher nie.\n- **Eine Kennzahl ohne festgeschriebene Definition ist keine Kennzahl.**\n  Dieselben Rohdaten ergeben je nach Rechenweg deutlich verschiedene Werte.\n- Die wichtigste Zahl gehört oben links, alles Weitere darunter und alles auf\n  eine Bildschirmhöhe.\n- Wer ein Dashboard baut, übernimmt Pflege, nicht nur Erstellung.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Zielbild und Publikum](zielbild-audience.qmd) für die\nEntscheidungsfrage und [Diagrammtyp wählen](diagrammtyp-waehlen.qmd) für die\neinzelnen Kacheln. Die technische Seite steht unter\n[seaborn und plotly](seaborn-plotly.qmd) sowie\n[Reproduzierbarkeit](../programmierung/reproduzierbarkeit.qmd).\n:::\n\n### Drei Formen der Auslieferung\n\n| Form | Was das Publikum tut | Wann passend | Kosten |\n|---|---|---|---|\n| Statisch | liest | Die Aussage steht fest und gilt für alle | gering, Pflege nur bei neuen Daten |\n| Interaktiv | filtert, zoomt, wählt aus | Verschiedene Leute haben verschiedene Fragen an dieselben Daten | Aufbau und laufender Betrieb |\n| Dialogisch | fragt in eigenen Worten | Fragen sind nicht vorhersehbar | hoch, dazu Prüfbarkeit der Antworten |\n\nDer häufigste Fehlgriff ist die interaktive Form für eine feststehende Aussage.\nWer weiss, was gezeigt werden soll, zeigt es; ein Filtermenü davor ist keine\nFreiheit, sondern eine Hausaufgabe für das Publikum. Wie viele Ansichten ein\nFilterset erzeugt, rechnet\n[seaborn und plotly, Beispiel 5](seaborn-plotly.qmd) vor.\n\n### Was ein Dashboard beantwortet\n\nEin Dashboard ist kein Ort, an dem alle verfügbaren Kennzahlen gezeigt werden,\nsondern die laufende Antwort auf eine wiederkehrende Entscheidungsfrage. Vor\ndem Bauen gehören drei Dinge festgelegt:\n\n1. **Die Frage.** \"Läuft die Produktion im Rahmen?\" ist eine Frage.\n   \"Produktionskennzahlen\" ist keine.\n2. **Der Takt.** Wird täglich, wöchentlich oder monatlich geschaut? Das\n   bestimmt die Aggregation und was als Abweichung gilt, Beispiel 1 zeigt, wie\n   stark.\n3. **Die Reaktion.** Was passiert, wenn eine Kennzahl ausschlägt? Wenn es darauf\n   keine Antwort gibt, gehört die Kennzahl nicht auf das Dashboard.\n\n### Aufbau\n\nDer Blick beginnt oben links und wandert nach rechts und unten. Daraus folgt\neine schlichte Ordnung:\n\n- **Oben links:** die eine Kennzahl, um die es geht, gross, mit Vergleichswert\n  (Vorperiode, Ziel, Schwelle).\n- **Obere Reihe:** zwei bis drei begleitende Kennzahlen im selben Format.\n- **Mitte:** der Verlauf, der zeigt, wie es dazu kam.\n- **Unten:** die Aufschlüsselung nach Gruppe, Region oder Produkt.\n- **Rand:** Filter, Stand der Daten, Quelle.\n\nWeitere Regeln, die sich bewähren:\n\n- Eine Bildschirmhöhe. Was gescrollt werden muss, wird nicht gesehen.\n- Einheitliche Skalen über vergleichbare Kacheln, sonst täuscht der Vergleich.\n- Kein Ampelrot ohne definierte Schwelle. Farbe ohne Regel ist Meinung.\n- Zahlen mit Einheit und Bezug, nie nackt.\n\n### Was danach kommt: Betrieb\n\nEin Dashboard ist eine Anwendung, keine Abgabe. Damit übernimmt man drei\nAufgaben dauerhaft: die Datenzufuhr am Laufen halten, auf Strukturänderungen in\nder Quelle reagieren, und Kennzahlen entfernen, die niemand mehr anschaut.\n\nDie häufigste Krankheit von Selbstbedienungs-Werkzeugen ist der Wildwuchs:\ndieselbe Kennzahl in drei Varianten, jede leicht anders gerechnet, und niemand\nweiss, welche gilt. Beispiel 3 rechnet vor, wie weit die Varianten\nauseinanderliegen.\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Der Takt bestimmt die Schwelle\n\n#### Frage und Datenlage\n\nEine Tagesproduktion, die um 1000 Stück schwankt, **ohne** Trend, ohne\nProblem. Eine Schwelle bei 950 Stück soll warnen. Wie oft schlägt sie an, je\nnachdem ob täglich, wöchentlich oder monatlich geschaut wird?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntage <- 364\nproduktion <- 1000 + qnorm(lehmer(1919, tage)) * 80\nschwelle <- 950\n\nmittelwerte <- function(x, fenster) {\n  gruppe <- (seq_along(x) - 1) %/% fenster\n  as.vector(tapply(x, gruppe, mean))\n}\n\nfor (nm in c(\"taeglich\", \"woechentlich\", \"monatlich\")) {\n  fenster <- c(taeglich = 1, woechentlich = 7, monatlich = 28)[[nm]]\n  agg <- mittelwerte(produktion, fenster)\n  cat(sprintf(\"%-14s Perioden %3d  SD der Mittel %6.2f (theoretisch %6.2f)  Alarme %3d (%5.1f Prozent)\\n\",\n              nm, length(agg), sd(agg), 80 / sqrt(fenster),\n              sum(agg < schwelle), 100 * mean(agg < schwelle)))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntaeglich       Perioden 364  SD der Mittel  77.78 (theoretisch  80.00)  Alarme 107 ( 29.4 Prozent)\nwoechentlich   Perioden  52  SD der Mittel  32.15 (theoretisch  30.24)  Alarme   4 (  7.7 Prozent)\nmonatlich      Perioden  13  SD der Mittel  14.88 (theoretisch  15.12)  Alarme   0 (  0.0 Prozent)\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 3), mar = c(4, 4, 3, 1))\nfor (nm in c(\"taeglich\", \"woechentlich\", \"monatlich\")) {\n  fenster <- c(taeglich = 1, woechentlich = 7, monatlich = 28)[[nm]]\n  agg <- mittelwerte(produktion, fenster)\n  plot(agg, type = \"l\", ylim = c(780, 1220), xlab = \"Periode\",\n       ylab = \"Stück\", main = nm, col = \"grey35\")\n  abline(h = schwelle, col = akzent, lty = 2, lwd = 2)\n  points(which(agg < schwelle), agg[agg < schwelle], col = akzent, pch = 16)\n}\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Reihe, drei Betrachtungstakte, eine Schwelle.](dashboards-interaktivitaet_files/figure-html/fig-b1-db-r-1.png){#fig-b1-db-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ntage = 364\nproduktion = 1000 + stats.norm.ppf(lehmer(1919, tage)) * 80\nschwelle = 950\nreihe = pd.Series(produktion)\n\ntakte = {\"taeglich\": 1, \"woechentlich\": 7, \"monatlich\": 28}\nfor nm, fenster in takte.items():\n    agg = reihe.groupby(np.arange(tage) // fenster).mean()\n    print(f\"{nm:<14} Perioden {len(agg):3d}  SD der Mittel {agg.std(ddof=1):6.2f}\"\n          f\" (theoretisch {80 / np.sqrt(fenster):6.2f})\"\n          f\"  Alarme {(agg < schwelle).sum():3d}\"\n          f\" ({100 * (agg < schwelle).mean():5.1f} Prozent)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntaeglich       Perioden 364  SD der Mittel  77.78 (theoretisch  80.00)  Alarme 107 ( 29.4 Prozent)\nwoechentlich   Perioden  52  SD der Mittel  32.15 (theoretisch  30.24)  Alarme   4 (  7.7 Prozent)\nmonatlich      Perioden  13  SD der Mittel  14.88 (theoretisch  15.12)  Alarme   0 (  0.0 Prozent)\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(1, 3, figsize=(7, 3.4))\nfor achse, (nm, fenster) in zip(achsen, takte.items()):\n    agg = reihe.groupby(np.arange(tage) // fenster).mean()\n    _ = achse.plot(agg.to_numpy(), color=\"0.35\")\n    _ = achse.axhline(schwelle, ls=\"--\", lw=2, color=AKZENT)\n    alarm = agg[agg < schwelle]\n    _ = achse.scatter(alarm.index, alarm.to_numpy(), s=16, color=AKZENT)\n    _ = achse.set_ylim(780, 1220)\n    _ = achse.set_title(nm, fontsize=10)\n    _ = achse.set_xlabel(\"Periode\")\n_ = achsen[0].set_ylabel(\"Stück\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Gegenüberstellung in Python.](dashboards-interaktivitaet_files/figure-html/fig-b1-db-py-1.png){#fig-b1-db-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Takt | Perioden | SD der Mittelwerte | theoretisch $80/\\sqrt{k}$ | Alarme bei 950 |\n|---|---|---|---|---|\n| **täglich** | 364 | 77.78 | 80.00 | **107 (29.4 %)** |\n| **wöchentlich** | 52 | 32.15 | 30.24 | **4 (7.7 %)** |\n| **monatlich** | 13 | 14.88 | 15.12 | **0 (0.0 %)** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Dieselbe Schwelle löst **29.4 Prozent** oder **0 Prozent** Alarme aus | Je nachdem, wie aggregiert wird. Die Daten sind identisch und völlig unauffällig, es gibt keinen Trend und keinen Ausreisser. |\n| Der Grund steht in der dritten Spalte | Die Streuung eines Mittelwerts sinkt mit $1/\\sqrt{k}$: 80, dann 30.2, dann 15.1. Eine Schwelle, die 0.6 Tagesstreuungen entfernt liegt, ist 1.6 Wochenstreuungen und 3.3 Monatsstreuungen entfernt. |\n| Bei täglicher Betrachtung ist die Schwelle **Dauerfeuer** | Mehr als jeder vierte Tag. Nach zwei Wochen schaut niemand mehr hin, der bekannteste Weg, eine Warnung wertlos zu machen. |\n| Bei monatlicher Betrachtung **warnt sie nie** | Auch dann nicht, wenn etwas schiefginge. Beides ist derselbe Fehler: eine Schwelle ohne Bezug zum Takt. |\n| Die Simulation bestätigt die Theorie | 77.78 gegen 80.00, 32.15 gegen 30.24, 14.88 gegen 15.12. |\n\n::: {.warning-box}\n**Die Regel: Die Schwelle gehört zum Takt, nicht zur Kennzahl.**\n\n| Takt | Streuung der Periodenmittel | sinnvolle Schwelle (2 Sigma) |\n|---|---|---|\n| täglich | 80.0 | 840 |\n| wöchentlich | 30.2 | 929 |\n| monatlich | 15.1 | 970 |\n\nWer eine Zahl wie \"unter 950 wird rot\" festlegt, ohne den Takt dazuzusagen, hat\nnichts festgelegt. Der saubere Weg sind **Kontrollgrenzen**, die aus der\nbeobachteten Streuung der jeweiligen Aggregationsebene stammen, der\nstatistische Hintergrund steht unter\n[Schätzen und Konfidenzintervalle](../statistik/inferenz/schaetzen-konfidenzintervalle.qmd).\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Eine Schwelle bei 950 Stück löst bei täglicher Betrachtung in 29.4 Prozent der\n> Perioden Alarm aus, bei wöchentlicher in 7.7 Prozent und bei monatlicher nie,\n> bei identischen, unauffälligen Daten. Die Streuung der Periodenmittel sinkt\n> von 80 über 30.2 auf 15.1.\n\n### Beispiel 2: Ampel ohne definierte Schwelle\n\n#### Frage und Datenlage\n\nDieselbe Reihe, drei Arten, die Ampelgrenze zu setzen: aus dem Bauch, aus einem\nrunden Zielwert und aus der beobachteten Streuung.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwochen <- mittelwerte(produktion, 7)\ngrenzen <- c(\n  \"rund (950)\" = 950,\n  \"Ziel minus 5 Prozent (950)\" = 950,\n  \"zwei Sigma\" = mean(wochen) - 2 * sd(wochen),\n  \"ein Sigma\" = mean(wochen) - 1 * sd(wochen))\nround(grenzen, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                rund (950) Ziel minus 5 Prozent (950) \n                    950.00                     950.00 \n                zwei Sigma                  ein Sigma \n                    928.84                     961.00 \n```\n\n\n:::\n\n```{.r .cell-code}\nfor (nm in names(grenzen)) {\n  anteil <- mean(wochen < grenzen[[nm]]) * 100\n  cat(sprintf(\"%-28s Grenze %7.2f  Alarme %2d von %d (%5.1f Prozent)\\n\",\n              nm, grenzen[[nm]], sum(wochen < grenzen[[nm]]),\n              length(wochen), anteil))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrund (950)                   Grenze  950.00  Alarme  4 von 52 (  7.7 Prozent)\nZiel minus 5 Prozent (950)   Grenze  950.00  Alarme  4 von 52 (  7.7 Prozent)\nzwei Sigma                   Grenze  928.84  Alarme  2 von 52 (  3.8 Prozent)\nein Sigma                    Grenze  961.00  Alarme  6 von 52 ( 11.5 Prozent)\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(mittel = mean(wochen), sd = sd(wochen),\n        minimum = min(wochen), maximum = max(wochen)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n mittel      sd minimum maximum \n 993.15   32.15  909.24 1053.89 \n```\n\n\n:::\n\n```{.r .cell-code}\npar(mar = c(4, 4, 2, 1))\nplot(wochen, type = \"l\", col = \"grey35\", xlab = \"Woche\", ylab = \"Stück\",\n     ylim = c(900, 1100))\nabline(h = grenzen[[\"zwei Sigma\"]], col = akzent, lty = 2, lwd = 2)\nabline(h = grenzen[[\"ein Sigma\"]], col = \"grey55\", lty = 3, lwd = 2)\nabline(h = 950, col = \"grey20\", lty = 4, lwd = 2)\nlegend(\"bottomleft\", c(\"zwei Sigma\", \"ein Sigma\", \"rund 950\"),\n       col = c(akzent, \"grey55\", \"grey20\"), lty = c(2, 3, 4), lwd = 2,\n       bty = \"n\", cex = 0.75)\n```\n\n::: {.cell-output-display}\n![Beispiel 2: drei Schwellen auf derselben Wochenreihe.](dashboards-interaktivitaet_files/figure-html/fig-b2-db-r-3.png){#fig-b2-db-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nwochen = reihe.groupby(np.arange(tage) // 7).mean()\ngrenzen = {\"rund (950)\": 950.0,\n           \"Ziel minus 5 Prozent (950)\": 950.0,\n           \"zwei Sigma\": wochen.mean() - 2 * wochen.std(ddof=1),\n           \"ein Sigma\": wochen.mean() - 1 * wochen.std(ddof=1)}\nprint({k: round(float(v), 2) for k, v in grenzen.items()})\n\nfor nm, grenze in grenzen.items():\n    treffer = int((wochen < grenze).sum())\n    print(f\"{nm:<28} Grenze {grenze:7.2f}  Alarme {treffer:2d} von {len(wochen)}\"\n          f\" ({100 * treffer / len(wochen):5.1f} Prozent)\")\n\nprint({\"mittel\": round(float(wochen.mean()), 2),\n       \"sd\": round(float(wochen.std(ddof=1)), 2),\n       \"minimum\": round(float(wochen.min()), 2),\n       \"maximum\": round(float(wochen.max()), 2)})\n\nfig, achse = plt.subplots(figsize=(7, 3))\n_ = achse.plot(wochen.to_numpy(), color=\"0.35\")\n_ = achse.axhline(grenzen[\"zwei Sigma\"], ls=\"--\", lw=2, color=AKZENT,\n                  label=\"zwei Sigma\")\n_ = achse.axhline(grenzen[\"ein Sigma\"], ls=\":\", lw=2, color=\"0.55\",\n                  label=\"ein Sigma\")\n_ = achse.axhline(950, ls=\"-.\", lw=2, color=\"0.2\", label=\"rund 950\")\n_ = achse.set_ylim(900, 1100)\n_ = achse.legend(fontsize=7, frameon=False, loc=\"lower left\")\n_ = achse.set_xlabel(\"Woche\")\n_ = achse.set_ylabel(\"Stück\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselben drei Schwellen in Python.](dashboards-interaktivitaet_files/figure-html/fig-b2-db-py-1.png){#fig-b2-db-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nWochenreihe: Mittel **993.15**, SD **32.15**, Minimum **909.24**, Maximum\n**1053.89**.\n\n| Grenze | Wert | Alarme von 52 |\n|---|---|---|\n| \"rund 950\" | 950.00 | **4 (7.7 %)** |\n| \"Ziel minus 5 Prozent\" | 950.00 | **4 (7.7 %)** |\n| **zwei Sigma** | **928.84** | **2 (3.8 %)** |\n| **ein Sigma** | **961.00** | **6 (11.5 %)** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die beiden \"runden\" Grenzen sind **dieselbe Zahl** | 950, einmal aus dem Bauch und einmal als \"fünf Prozent unter dem Ziel von 1000\". Verschiedene Begründungen, dieselbe Willkür und rein zufällig liegt sie zwischen ein und zwei Sigma. |\n| Die Zwei-Sigma-Grenze liegt bei **928.84** | Hergeleitet aus der beobachteten Streuung von 32.15. Sie schlägt in 3.8 Prozent der Wochen an, also etwa zweimal im Jahr. Das ist eine Rate, bei der man hinschaut. |\n| Die Ein-Sigma-Grenze löst **11.5 Prozent** aus | Etwa jede neunte Woche. Als Warnung unbrauchbar, als \"beobachten\" brauchbar, deshalb haben Kontrollkarten zwei Grenzen. |\n| Der Unterschied zwischen 3.8 und 11.5 Prozent entsteht aus **einer Zahl** | Dem Faktor vor der Standardabweichung. Wer keine Regel festlegt, überlässt diese Entscheidung dem Zufall der Wahl. |\n| Keine der Grenzen ist \"richtig\" | Richtig ist die, die zur Reaktion passt: Wie oft kann und will jemand reagieren? Daraus folgt der Faktor, nicht umgekehrt. |\n\n::: {.note-box}\n**Die drei Fragen, bevor eine Ampel eingebaut wird:**\n\n1. **Woher kommt die Grenze?** Aus der Streuung, aus einer Zielvorgabe oder aus\n   einer Norm, aber aus etwas.\n2. **Wie oft soll sie anschlagen?** Daraus folgt der Sigma-Faktor. Zwei Sigma\n   heisst rund fünf Prozent, drei Sigma rund ein Promille.\n3. **Was passiert dann?** Ohne Antwort gehört die Ampel weg.\n\nRot ohne Regel ist eine Meinung in Ampelfarben und sie wird vom Publikum als\nMessung gelesen.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Auf derselben Wochenreihe (Mittel 993.15, SD 32.15) lösen die Grenzen 950,\n> 928.84 und 961.00 in 7.7, 3.8 und 11.5 Prozent der Wochen Alarm aus. Der\n> Unterschied entsteht allein aus dem gewählten Faktor vor der\n> Standardabweichung.\n\n### Beispiel 3: Dieselbe Kennzahl, drei Definitionen\n\n#### Frage und Datenlage\n\n\"Verfügbarkeit\" über 30 Tage. Aus denselben Rohdaten, geplante Stunden,\nungeplanter Stillstand, geplante Wartung, lässt sie sich auf mehrere Arten\nausrechnen. Alle heissen gleich.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 30\nu <- matrix(lehmer(5252, 3 * n), ncol = 3, byrow = TRUE)\ngeplant <- round(16 + 4 * u[, 1], 1)\nstillstand <- round(u[, 2]^2 * 6, 2)\nwartung <- round(u[, 3] * 2, 2)\nlief <- geplant - stillstand - wartung\ntagesquote <- lief / geplant\n\nround(c(summe_geplant = sum(geplant), summe_stillstand = sum(stillstand),\n        summe_wartung = sum(wartung), summe_gelaufen = sum(lief)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   summe_geplant summe_stillstand    summe_wartung   summe_gelaufen \n          531.70            49.93            36.04           445.73 \n```\n\n\n:::\n\n```{.r .cell-code}\nvarianten <- c(\n  \"Stunden gelaufen / geplant\" = sum(lief) / sum(geplant) * 100,\n  \"Wartung herausgerechnet\" = sum(lief) / (sum(geplant) - sum(wartung)) * 100,\n  \"Mittel der Tagesquoten\" = mean(tagesquote) * 100,\n  \"Anteil Tage über 90 Prozent\" = mean(tagesquote > 0.90) * 100)\nround(varianten, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Stunden gelaufen / geplant     Wartung herausgerechnet \n                      83.83                       89.93 \n     Mittel der Tagesquoten Anteil Tage über 90 Prozent \n                      83.69                       36.67 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(spannweite_der_ersten_drei = max(varianten[1:3]) - min(varianten[1:3]),\n        schlechtester_tag = min(tagesquote) * 100,\n        bester_tag = max(tagesquote) * 100), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nspannweite_der_ersten_drei          schlechtester_tag \n                      6.24                      61.11 \n                bester_tag \n                     99.53 \n```\n\n\n:::\n\n```{.r .cell-code}\npar(mar = c(4, 12, 2, 1))\nbarplot(rev(varianten), horiz = TRUE, las = 1, xlim = c(0, 100),\n        col = c(neutral, neutral, neutral, akzent), border = NA,\n        xlab = \"Prozent\", cex.names = 0.75)\n```\n\n::: {.cell-output-display}\n![Beispiel 3: vier Kennzahlen, die alle Verfügbarkeit heissen.](dashboards-interaktivitaet_files/figure-html/fig-b3-db-r-3.png){#fig-b3-db-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nn = 30\nu = lehmer(5252, 3 * n).reshape(n, 3)\ngeplant = np.round(16 + 4 * u[:, 0], 1)\nstillstand = np.round(u[:, 1] ** 2 * 6, 2)\nwartung = np.round(u[:, 2] * 2, 2)\nlief = geplant - stillstand - wartung\ntagesquote = lief / geplant\n\nprint({\"summe_geplant\": round(float(geplant.sum()), 2),\n       \"summe_stillstand\": round(float(stillstand.sum()), 2),\n       \"summe_wartung\": round(float(wartung.sum()), 2),\n       \"summe_gelaufen\": round(float(lief.sum()), 2)})\n\nvarianten = {\n    \"Stunden gelaufen / geplant\": lief.sum() / geplant.sum() * 100,\n    \"Wartung herausgerechnet\": lief.sum() / (geplant.sum() - wartung.sum()) * 100,\n    \"Mittel der Tagesquoten\": tagesquote.mean() * 100,\n    \"Anteil Tage über 90 Prozent\": (tagesquote > 0.90).mean() * 100}\nprint({k: round(float(v), 2) for k, v in varianten.items()})\n\nerste_drei = list(varianten.values())[:3]\nprint({\"spannweite_der_ersten_drei\": round(float(max(erste_drei) - min(erste_drei)), 2),\n       \"schlechtester_tag\": round(float(tagesquote.min() * 100), 2),\n       \"bester_tag\": round(float(tagesquote.max() * 100), 2)})\n\nfig, achse = plt.subplots(figsize=(7, 3))\nnamen = list(varianten.keys())\nwerte = [varianten[k] for k in namen]\nfarben = [NEUTRAL] * 3 + [AKZENT]\n_ = achse.barh(namen[::-1], werte[::-1], color=farben[::-1])\n_ = achse.set_xlim(0, 100)\n_ = achse.set_xlabel(\"Prozent\")\n_ = achse.tick_params(labelsize=8)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselben vier Kennzahlen in Python.](dashboards-interaktivitaet_files/figure-html/fig-b3-db-py-1.png){#fig-b3-db-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Rohdaten über 30 Tage | Stunden |\n|---|---|\n| geplant | **531.70** |\n| ungeplanter Stillstand | 49.93 |\n| geplante Wartung | 36.04 |\n| gelaufen | **445.73** |\n\n| Rechenweg | \"Verfügbarkeit\" |\n|---|---|\n| Stunden gelaufen / geplant | **83.83 %** |\n| Wartung herausgerechnet | **89.93 %** |\n| Mittel der Tagesquoten | **83.69 %** |\n| **Anteil Tage über 90 Prozent** | **36.67 %** |\n\nSpannweite der ersten drei: **6.24 Prozentpunkte**. Schlechtester Tag\n**61.11 %**, bester **99.53 %**.\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die drei stundenbasierten Wege liegen **6.24 Punkte** auseinander | 83.69 bis 89.93. Alle drei sind vertretbar, alle drei heissen \"Verfügbarkeit\". |\n| \"Wartung herausgerechnet\" ist die **freundlichste** Zahl | 89.93 gegen 83.83. Geplante Wartung als Nichtverfügbarkeit zu zählen oder nicht, ist eine Definitionsfrage und sie entscheidet über sechs Prozentpunkte. |\n| Der Unterschied zwischen 83.83 und 83.69 ist ein **Gewichtungseffekt** | Die Summenquote gewichtet lange Tage stärker, das Mittel der Tagesquoten gewichtet alle Tage gleich. Derselbe Unterschied wie zwischen gewichtetem und ungewichtetem Mittel. |\n| Die vierte Zahl ist **etwas ganz anderes** | 36.67 Prozent ist kein Stundenanteil, sondern ein Tagesanteil. Sie beantwortet die Frage \"wie oft lief es gut\" statt \"wie viel lief es\" und sieht trotzdem aus wie dieselbe Kennzahl. |\n| Alle vier auf einem Dashboard nebeneinander | Und niemand weiss mehr, welche gilt. **Das ist der Wildwuchs, gegen den nur eine festgeschriebene Definition hilft.** |\n\n::: {.warning-box}\n**Was in die Kennzahlendefinition gehört**, damit sie eine ist:\n\n| Angabe | Beispiel |\n|---|---|\n| Zähler | tatsächlich gelaufene Stunden |\n| Nenner | geplante Stunden **einschliesslich** Wartung |\n| Aggregation | Summe über die Periode, nicht Mittel der Tageswerte |\n| Periode | Kalendermonat |\n| Ausschlüsse | Feiertage zählen nicht als geplant |\n| Verantwortlich | wer die Definition ändern darf |\n\nOhne diese sechs Zeilen ist eine Kennzahl eine Zahl mit einem Namen. Mit ihnen\nist sie vergleichbar und nur dann darf sie in eine Zeitreihe.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Aus denselben Rohdaten ergeben drei stundenbasierte Rechenwege\n> Verfügbarkeiten von 83.69, 83.83 und 89.93 Prozent, eine Spannweite von 6.24\n> Punkten. Ein vierter, ebenso \"Verfügbarkeit\" genannter Weg zählt Tage statt\n> Stunden und ergibt 36.67 Prozent.\n\n### Beispiel 4: Eine Bildschirmhöhe\n\n#### Frage und Datenlage\n\nWie viele Kacheln passen auf eine Bildschirmhöhe, und was rutscht darunter?\nGerechnet für eine typische Auflösung.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbildschirm_hoehe <- 900      # sichtbare Pixel im Browser, 1080 minus Leisten\nkopfzeile <- 80\nkachel_hoehe <- 220\nabstand <- 16\n\npassen <- floor((bildschirm_hoehe - kopfzeile + abstand) / (kachel_hoehe + abstand))\nround(c(sichtbare_hoehe = bildschirm_hoehe, kopfzeile = kopfzeile,\n        kachelhoehe_mit_abstand = kachel_hoehe + abstand,\n        reihen_sichtbar = passen), 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        sichtbare_hoehe               kopfzeile kachelhoehe_mit_abstand \n                    900                      80                     236 \n        reihen_sichtbar \n                      3 \n```\n\n\n:::\n\n```{.r .cell-code}\nfor (reihen in c(3, 4, 6)) {\n  gesamt <- kopfzeile + reihen * (kachel_hoehe + abstand) - abstand\n  sichtbar <- min(1, (bildschirm_hoehe - kopfzeile) /\n                    (reihen * (kachel_hoehe + abstand) - abstand))\n  cat(sprintf(\"%d Reihen: Gesamthöhe %4d px, sichtbar ohne Scrollen %5.1f Prozent\\n\",\n              reihen, gesamt, 100 * sichtbar))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n3 Reihen: Gesamthöhe  772 px, sichtbar ohne Scrollen 100.0 Prozent\n4 Reihen: Gesamthöhe 1008 px, sichtbar ohne Scrollen  88.4 Prozent\n6 Reihen: Gesamthöhe 1480 px, sichtbar ohne Scrollen  58.6 Prozent\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nbildschirm_hoehe = 900\nkopfzeile = 80\nkachel_hoehe = 220\nabstand = 16\n\npassen = (bildschirm_hoehe - kopfzeile + abstand) // (kachel_hoehe + abstand)\nprint({\"sichtbare_hoehe\": bildschirm_hoehe, \"kopfzeile\": kopfzeile,\n       \"kachelhoehe_mit_abstand\": kachel_hoehe + abstand,\n       \"reihen_sichtbar\": int(passen)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'sichtbare_hoehe': 900, 'kopfzeile': 80, 'kachelhoehe_mit_abstand': 236, 'reihen_sichtbar': 3}\n```\n\n\n:::\n\n```{.python .cell-code}\nfor reihen in (3, 4, 6):\n    gesamt = kopfzeile + reihen * (kachel_hoehe + abstand) - abstand\n    sichtbar = min(1.0, (bildschirm_hoehe - kopfzeile)\n                   / (reihen * (kachel_hoehe + abstand) - abstand))\n    print(f\"{reihen} Reihen: Gesamthöhe {gesamt:4d} px,\"\n          f\" sichtbar ohne Scrollen {100 * sichtbar:5.1f} Prozent\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n3 Reihen: Gesamthöhe  772 px, sichtbar ohne Scrollen 100.0 Prozent\n4 Reihen: Gesamthöhe 1008 px, sichtbar ohne Scrollen  88.4 Prozent\n6 Reihen: Gesamthöhe 1480 px, sichtbar ohne Scrollen  58.6 Prozent\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | Wert |\n|---|---|\n| sichtbare Höhe im Browser | 900 px |\n| Kopfzeile | 80 px |\n| Kachel plus Abstand | 236 px |\n| **Reihen, die sichtbar sind** | **3** |\n\n| Reihen | Gesamthöhe | sichtbar ohne Scrollen |\n|---|---|---|\n| **3** | 772 px | **100.0 %** |\n| 4 | 1008 px | **88.0 %** |\n| 6 | 1480 px | **56.0 %** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Auf einen Full-HD-Bildschirm passen **drei** Kachelreihen | Bei 220 Pixel Kachelhöhe. Mehr geht nur mit kleineren Kacheln und die tragen weniger. |\n| Bei sechs Reihen sind **44 Prozent unsichtbar** | Und das ist genau die Hälfte der Kennzahlen, die jemand für wichtig genug hielt, sie aufzunehmen. |\n| Die vierte Reihe ist die kritische | 88 Prozent sichtbar heisst: Die untere Kachel ist angeschnitten. Ein angeschnittenes Element ist schlechter als ein fehlendes, weil es Scrollen suggeriert, ohne zu lohnen. |\n| Die Rechnung ist trivial und wird trotzdem nie gemacht | Dashboards entstehen im Entwurfswerkzeug, wo beliebig viel Platz ist. **Die Begrenzung ist der Bildschirm des Publikums, nicht der eigene.** |\n| Was nicht auf drei Reihen passt, gehört auf eine **zweite Seite** | Mit eigener Frage. Nicht darunter. |\n\n::: {.note-box}\n**Die Aufteilung, die auf drei Reihen passt:**\n\n| Reihe | Inhalt |\n|---|---|\n| 1 | die Leitkennzahl gross, daneben zwei bis drei Begleitzahlen |\n| 2 | der Verlauf über die Zeit |\n| 3 | die Aufschlüsselung nach der wichtigsten Gruppierung |\n\nAlles Weitere, Detailtabellen, Nebenkennzahlen, Methodik, gehört hinter einen\nKlick oder auf eine eigene Seite.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Auf 900 sichtbaren Pixeln passen bei 220 Pixel Kachelhöhe drei Reihen. Vier\n> Reihen sind zu 88 Prozent sichtbar, sechs zu 56 Prozent, bei sechs Reihen\n> bleibt also fast die Hälfte der Kacheln ungesehen.\n\n### Beispiel 5: Überblick und Aufschlüsselung\n\n#### Frage und Datenlage\n\nSechs Standorte, eine Gesamtkennzahl. Die Frage ist, wie viel der Überblick\nverbirgt und ob die Aufschlüsselung auf das Dashboard gehört.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngruppen <- c(\"A\", \"B\", \"C\", \"D\", \"E\", \"F\")\nje_gruppe <- 40\nbasis <- c(50, 52, 49, 51, 30, 53)\nz <- qnorm(lehmer(6363, length(gruppen) * je_gruppe))\ngruppe <- rep(gruppen, each = je_gruppe)\nwert <- rep(basis, each = je_gruppe) + z * 6\n\ngesamt <- mean(wert)\nmittel <- tapply(wert, gruppe, mean)\nround(c(gesamtmittel = gesamt), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngesamtmittel \n       47.82 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(mittel, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    A     B     C     D     E     F \n50.79 51.22 51.71 51.11 28.69 53.42 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(ohne_gruppe_E = mean(mittel[names(mittel) != \"E\"])), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nohne_gruppe_E \n        51.65 \n```\n\n\n:::\n\n```{.r .cell-code}\nzwischen <- sum(je_gruppe * (mittel - gesamt)^2)\ninnen <- sum((wert - mittel[gruppe])^2)\nround(c(streuung_zwischen = zwischen, streuung_innerhalb = innen,\n        anteil_zwischen_prozent = zwischen / (zwischen + innen) * 100), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      streuung_zwischen      streuung_innerhalb anteil_zwischen_prozent \n                17746.6                  9481.7                    65.2 \n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nbarplot(gesamt, names.arg = \"alle\", col = neutral, border = NA,\n        ylim = c(0, 60), ylab = \"Wert\", main = \"Überblick\")\nbarplot(mittel, col = ifelse(mittel < 40, akzent, neutral), border = NA,\n        ylim = c(0, 60), ylab = \"Wert\", main = \"Aufschlüsselung\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 5: die Gesamtzahl und die Aufschlüsselung.](dashboards-interaktivitaet_files/figure-html/fig-b5-db-r-1.png){#fig-b5-db-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ngruppen = [\"A\", \"B\", \"C\", \"D\", \"E\", \"F\"]\nje_gruppe = 40\nbasis = np.array([50, 52, 49, 51, 30, 53])\nz = stats.norm.ppf(lehmer(6363, len(gruppen) * je_gruppe))\ngruppe = np.repeat(gruppen, je_gruppe)\nwert = np.repeat(basis, je_gruppe) + z * 6\n\ngesamt = wert.mean()\nmittel = pd.Series(wert).groupby(gruppe).mean()\nprint({\"gesamtmittel\": round(float(gesamt), 2)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'gesamtmittel': 47.82}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(mittel.round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nA    50.79\nB    51.22\nC    51.71\nD    51.11\nE    28.69\nF    53.42\ndtype: float64\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"ohne_gruppe_E\": round(float(mittel.drop(\"E\").mean()), 2)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'ohne_gruppe_E': 51.65}\n```\n\n\n:::\n\n```{.python .cell-code}\nzwischen = float((je_gruppe * (mittel - gesamt) ** 2).sum())\ninnen = float(sum(((wert[gruppe == g] - mittel[g]) ** 2).sum() for g in gruppen))\nprint({\"streuung_zwischen\": round(zwischen, 1),\n       \"streuung_innerhalb\": round(innen, 1),\n       \"anteil_zwischen_prozent\": round(zwischen / (zwischen + innen) * 100, 1)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'streuung_zwischen': 17746.6, 'streuung_innerhalb': 9481.7, 'anteil_zwischen_prozent': 65.2}\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3))\n_ = achsen[0].bar([\"alle\"], [gesamt], color=NEUTRAL)\n_ = achsen[0].set_ylim(0, 60)\n_ = achsen[0].set_title(\"Überblick\", fontsize=10)\n_ = achsen[1].bar(mittel.index, mittel.to_numpy(),\n                  color=np.where(mittel.to_numpy() < 40, AKZENT, NEUTRAL))\n_ = achsen[1].set_ylim(0, 60)\n_ = achsen[1].set_title(\"Aufschlüsselung\", fontsize=10)\nfor achse in achsen:\n    _ = achse.set_ylabel(\"Wert\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselbe Gegenüberstellung in Python.](dashboards-interaktivitaet_files/figure-html/fig-b5-db-py-1.png){#fig-b5-db-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Standort | A | B | C | D | **E** | F |\n|---|---|---|---|---|---|---|\n| Mittelwert | 50.79 | 51.22 | 51.71 | 51.11 | **28.69** | 53.42 |\n\n| Grösse | Wert |\n|---|---|\n| Gesamtmittel | **47.82** |\n| Mittel ohne Standort E | **51.65** |\n| Streuung zwischen den Gruppen | 17746.2 |\n| Streuung innerhalb der Gruppen | 9481.7 |\n| **Anteil zwischen den Gruppen** | **65.2 Prozent** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die Gesamtzahl **47.82** sieht unauffällig aus | Sie liegt nur gut drei Punkte unter dem Wert der intakten Standorte. Auf einer Kachel allein wäre nichts zu sehen. |\n| Ein Standort liegt bei **28.69** | Also bei gut der Hälfte der übrigen. Ohne ihn läge das Mittel bei 51.65. |\n| **65.2 Prozent** der Streuung liegen **zwischen** den Gruppen | Und nicht innerhalb. Das ist die Kennzahl, die sagt, ob eine Aufschlüsselung lohnt: Steckt die Information in den Gruppen oder im Rauschen? |\n| Bei einem niedrigen Anteil wäre die Aufschlüsselung **Ballast** | Läge er bei 5 Prozent, wären die sechs Balken sechsmal dasselbe mit Rauschen. Dann gehört die Kachel weg. |\n| Die Regel für das Dashboard folgt daraus | **Eine Aufschlüsselung gehört aufs Dashboard, wenn die Gruppen sich unterscheiden und das lässt sich messen, statt es zu vermuten.** |\n\n::: {.note-box}\n**Der Anteil der Zwischen-Gruppen-Streuung** ist dasselbe Mass, das in der\n[Varianzanalyse](../statistik/tests/anova.qmd) als $\\eta^2$ auftaucht. Auf\neinem Dashboard beantwortet es eine sehr praktische Frage: Lohnt die Kachel?\n\n| Anteil zwischen den Gruppen | Empfehlung |\n|---|---|\n| unter 10 Prozent | Aufschlüsselung weglassen |\n| 10 bis 40 Prozent | als Detail hinter einem Klick |\n| über 40 Prozent | auf das Dashboard, mit Akzent auf dem Ausreisser |\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Das Gesamtmittel von 47.82 verbirgt, dass ein Standort bei 28.69 liegt,\n> während die übrigen fünf zwischen 50.79 und 53.42 liegen; ohne ihn wäre das\n> Mittel 51.65. 65.2 Prozent der Gesamtstreuung liegen zwischen den Gruppen,\n> die Aufschlüsselung trägt also die eigentliche Information.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEin Bericht soll monatlich an die Bereichsleitung gehen, die Aussage steht\njeweils fest. Welche Form ist richtig?\n\n- [x] Statisch, mit der Aussage im Titel ~ Richtig. Wenn feststeht, was gezeigt\n      werden soll, ist Interaktion nur zusätzlicher Aufwand für beide Seiten.\n      Ein Dashboard lohnt sich, wenn verschiedene Leute verschiedene Fragen an\n      dieselben Daten haben.\n- [ ] Interaktiv, damit sich jeder vertiefen kann ~ Vertiefung wird selten\n      genutzt und verschiebt die Deutungsarbeit zum Publikum.\n- [ ] Dialogisch, das ist am flexibelsten ~ Flexibel und am aufwendigsten, und\n      die Antworten müssten geprüft werden.\n:::\n\n::: {.quiz}\nEine Schwelle bei 950 löst bei täglicher Betrachtung in 29.4 Prozent der Fälle\nAlarm aus, bei monatlicher nie. Was ist zu tun?\n\n- [x] Die Schwelle aus der Streuung der jeweiligen Aggregationsebene ableiten ~\n      Richtig. Die Streuung der Periodenmittel sinkt mit eins durch Wurzel k:\n      80, dann 30.2, dann 15.1. Eine feste Zahl ohne Angabe des Takts legt\n      nichts fest.\n- [ ] Den Takt auf monatlich umstellen, dann gibt es keine Fehlalarme ~ Dann\n      warnt sie auch nicht, wenn wirklich etwas schiefgeht.\n- [ ] Die Schwelle tiefer setzen ~ Das verschiebt das Problem, statt es zu\n      lösen; die Grenze braucht einen Bezug.\n:::\n\n::: {.quiz}\nAuf einem Dashboard steht eine Kennzahl, für die es keine definierte Reaktion\ngibt. Was folgt?\n\n- [ ] Sie bleibt als Kontext stehen ~ Kontext ist ein Vorwand; sie verbraucht\n      Platz und Aufmerksamkeit.\n- [x] Sie gehört nicht auf das Dashboard ~ Richtig. Ein Dashboard stützt\n      Entscheidungen. Eine Kennzahl ohne mögliche Reaktion ist Dekoration und\n      verwässert die, auf die es ankommt.\n- [ ] Sie braucht eine Ampel ~ Eine Ampel ohne definierte Schwelle macht es\n      schlimmer.\n:::\n\n::: {.quiz}\nDieselben Rohdaten ergeben Verfügbarkeiten von 83.69, 83.83 und 89.93 Prozent.\nWie kommt das?\n\n- [x] Die Rechenwege unterscheiden sich in Nenner und Gewichtung ~ Richtig. Ob\n      geplante Wartung im Nenner steht, entscheidet über sechs Prozentpunkte;\n      Summenquote und Mittel der Tagesquoten unterscheiden sich in der\n      Gewichtung langer Tage.\n- [ ] Einer der drei Werte ist falsch gerechnet ~ Alle drei sind vertretbar,\n      und genau das ist das Problem.\n- [ ] Die Daten sind fehlerhaft ~ Die Rohdaten sind dieselben für alle drei.\n:::\n\n::: {.quiz}\nEin Dashboard hat sechs Kachelreihen. Was bedeutet das auf einem\nFull-HD-Bildschirm?\n\n- [x] Rund 44 Prozent sind ohne Scrollen unsichtbar ~ Richtig. Bei 220 Pixel\n      Kachelhöhe passen drei Reihen auf 900 sichtbare Pixel. Was nicht\n      draufpasst, gehört auf eine zweite Seite mit eigener Frage, nicht\n      darunter.\n- [ ] Das ist kein Problem, man kann ja scrollen ~ Was gescrollt werden muss,\n      wird in der Praxis nicht gesehen.\n- [ ] Man verkleinert einfach die Kacheln ~ Kleinere Kacheln tragen weniger;\n      das verschiebt das Problem in die Lesbarkeit.\n:::\n\n::: {.quiz}\nWoran erkennt man, ob eine Aufschlüsselung nach Gruppen auf das Dashboard\ngehört?\n\n- [x] Am Anteil der Streuung, der zwischen den Gruppen liegt ~ Richtig. Im\n      Beispiel waren es 65.2 Prozent, die Gruppen tragen also die\n      Information. Läge der Anteil bei 5 Prozent, wären die Balken sechsmal\n      dasselbe mit Rauschen.\n- [ ] An der Zahl der Gruppen ~ Sechs Gruppen können aufschlussreich oder\n      überflüssig sein; die Zahl sagt nichts.\n- [ ] Daran, ob jemand danach gefragt hat ~ Ein Anhaltspunkt, aber messen ist\n      besser.\n:::\n\n## Verlinkte Ressourcen\n\n- [Quarto Dashboards](https://quarto.org/docs/dashboards/)\n- [Stephen Few: Information Dashboard Design](https://www.stephen-few.com/idd.php)\n- [Zielbild und Publikum](zielbild-audience.qmd), die Entscheidungsfrage davor\n- [seaborn und plotly](seaborn-plotly.qmd), wann Interaktivität lohnt\n- [Varianzanalyse](../statistik/tests/anova.qmd), der Anteil der Streuung zwischen Gruppen\n",
    "supporting": [
      "dashboards-interaktivitaet_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}