{
  "hash": "b1e3cb1eae529567fc1c8dbe3925ca00",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Gemischte Modelle\"\ndescription: \"Regression mit Gruppenstruktur: zufällige Achsenabschnitte und Steigungen, ICC und warum OLS dort zu sicher ist.\"\ncategories: [\"Regression\", \"Modelldiagnostik\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: methode\nstand: entwurf\norder: 60\n---\n\n\n\n\n\nAlle Beispiele rechnen mit denselben 180 Personen aus 12 Schulklassen. Die\nDaten entstehen in beiden Sprachen aus demselben Lehmer-Generator, R und Python\nsehen also exakt dieselben Werte.\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Wie hängt eine Zielgrösse von Prädiktoren ab, wenn die Beobachtungen in Gruppen gebündelt sind? |\n| Zielvariable | metrisch (für binäre Zielgrössen gibt es die verallgemeinerte Form) |\n| Datenstruktur | Personen in Klassen, Messungen in Personen, Filialen in Regionen |\n| Was die Methode liefert | feste Effekte mit Standardfehlern, Varianz der Gruppen und des Rests, ICC |\n| R-Funktion | `lme4::lmer(y ~ x + (1 \\| gruppe))` |\n| Python-Funktion | `smf.mixedlm(\"y ~ x\", data, groups=data[\"gruppe\"]).fit()` |\n| Verwandte Methoden | [multiple lineare Regression](multiple-lineare-regression.qmd), [gepaarter t-Test](../tests/t-test-gepaart.qmd), [Varianzanalyse](../tests/anova.qmd) |\n\n## Wann diese Methode, wann nicht\n\nGemischte Modelle sind zuständig, sobald Beobachtungen nicht unabhängig sind,\nweil sie aus derselben Gruppe stammen: Schülerinnen derselben Klasse, wiederholte\nMessungen an derselben Person, Verkäufe derselben Filiale. Innerhalb einer\nGruppe ähneln sich die Werte, und eine gewöhnliche Regression tut so, als wäre\njede Zeile neue, unabhängige Information.\n\n| Situation | Stattdessen |\n|---|---|\n| Keine Gruppenstruktur, alle Beobachtungen unabhängig | [multiple lineare Regression](multiple-lineare-regression.qmd) |\n| Nur zwei Messungen je Person, keine Prädiktoren | [gepaarter t-Test](../tests/t-test-gepaart.qmd) |\n| Sehr wenige Gruppen (unter etwa fünf) | Gruppe als fester Faktor in der Regression |\n| Binäre Zielgrösse mit Gruppen | verallgemeinertes gemischtes Modell, `glmer(..., family = binomial)` |\n| Messungen in gleichmässigem zeitlichem Abstand, Vorhersage steht im Zentrum | [Zeitreihenmodelle](../zeitreihen/index.qmd) |\n\n## Grundidee und Modell\n\nJede Klasse bekommt ihren eigenen Achsenabschnitt, aber diese Achsenabschnitte\nwerden nicht einzeln geschätzt, sondern als Streuung um einen gemeinsamen\nMittelwert modelliert:\n\n$$y_{ij} = \\beta_0 + u_{j} + \\beta_1 x_{ij} + \\varepsilon_{ij}, \\qquad u_j \\sim N(0, \\sigma_u^2), \\quad \\varepsilon_{ij} \\sim N(0, \\sigma^2)$$\n\n| Bestandteil | Bedeutung |\n|---|---|\n| $\\beta_0, \\beta_1$ | **feste Effekte**: gelten für alle, werden wie in der Regression gelesen |\n| $u_j$ | **zufälliger Effekt** der Klasse $j$: wie weit ihr Niveau vom Durchschnitt abweicht |\n| $\\sigma_u^2$ | Varianz zwischen den Klassen |\n| $\\sigma^2$ | Varianz innerhalb der Klassen, der Rest |\n| $\\text{ICC} = \\sigma_u^2 / (\\sigma_u^2 + \\sigma^2)$ | Anteil der Gesamtstreuung, der auf die Klassen entfällt |\n\nKann auch die Steigung je Klasse verschieden sein, kommt ein zweiter zufälliger\nEffekt dazu, der **zufällige Steigung** heisst: `(stunden | klasse)`.\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung | Vorgehen |\n|---|---|---|---|---|\n| Gruppenstruktur richtig abgebildet | Jede Ebene, auf der sich Werte ähneln, ist im Modell | Erhebungsdesign | Standardfehler zu klein | fehlende Ebene ergänzen |\n| Genügend Gruppen | Die Varianz zwischen Gruppen braucht Gruppen, um geschätzt zu werden | Anzahl Gruppen | Varianz auf null geschätzt, Warnung `singular fit` | ab etwa zehn Gruppen verlässlich, sonst fester Faktor |\n| Linearität, konstante Restvarianz | wie in der Regression | Residuen gegen angepasste Werte | verzerrte Effekte, falsche Unsicherheit | [Regressionsdiagnostik](regressionsdiagnostik.qmd) |\n| Annähernd normalverteilte zufällige Effekte und Residuen | | QQ-Plot der Residuen und der geschätzten $u_j$ | bei grossen Stichproben meist harmlos | robuste Standardfehler oder Bootstrap |\n\n## Output lesen\n\nR, `summary(lmer(...))`:\n\n| Abschnitt | Was er sagt |\n|---|---|\n| `REML criterion at convergence` | Anpassungsmass, nur zum Vergleich von Modellen mit denselben festen Effekten |\n| `Random effects`, `Variance` und `Std.Dev.` | $\\sigma_u^2$ je zufälligem Effekt und $\\sigma^2$ als `Residual` |\n| `Number of obs`, `groups` | Anzahl Zeilen und Anzahl Gruppen; entscheidend ist oft die zweite Zahl |\n| `Fixed effects`, `Estimate`, `Std. Error`, `t value` | wie in der Regression; **lme4 gibt bewusst keine p-Werte aus** |\n\nPython, `MixedLM.fit().summary()`:\n\n| Zeile | Was sie sagt | Unterschied zu R |\n|---|---|---|\n| `Scale` | $\\sigma^2$, die Restvarianz | in R die Zeile `Residual` |\n| `Group Var` | $\\sigma_u^2$ | in R `(Intercept)` unter `Random effects` |\n| `Coef.`, `Std.Err.`, `z`, `P>\\|z\\|` | feste Effekte mit Wald-Test | R zeigt nur `t value`, ohne p-Wert |\n| `Converged` | ob die Schätzung konvergiert ist | in R eine Warnung, falls nicht |\n\nWarum lme4 keinen p-Wert zeigt: Die Freiheitsgrade eines festen Effekts sind in\ngemischten Modellen nicht eindeutig definiert. Python rechnet mit der\nNormalverteilung, das ist bei vielen Gruppen eine gute Näherung und bei wenigen\nzu optimistisch.\n\n## Interpretationsfallen\n\n- **OLS auf gruppierten Daten ist zu sicher.** Die Schätzung selbst ist oft\n  ähnlich, der Standardfehler aber zu klein, besonders für Merkmale der Gruppe.\n  Beispiel 2 zeigt den Faktor.\n- **Die Stichprobengrösse für Gruppenmerkmale ist die Zahl der Gruppen**, nicht\n  die Zahl der Zeilen. 180 Personen in 12 Klassen sind für die Klassengrösse 12\n  Beobachtungen.\n- **Ein nicht signifikanter Test auf eine Varianzkomponente beweist nicht, dass\n  sie null ist.** Der Test liegt am Rand des Parameterraums und ist konservativ.\n- **REML und ML nicht mischen.** Modelle mit verschiedenen festen Effekten werden\n  mit ML verglichen; R erledigt das in `anova()` automatisch, Python nicht.\n- **`singular fit` ist keine Formalie.** Es heisst, dass eine Varianz auf null\n  oder eine Korrelation auf plus oder minus eins geschätzt wurde. Das Modell ist\n  dann zu komplex für die Daten.\n\n## Ergebnis berichten\n\n> [Zielgrösse] wurde mit einem linearen gemischten Modell mit zufälligem\n> Achsenabschnitt für [Gruppe] ausgewertet ([Anzahl] Beobachtungen in [Anzahl]\n> Gruppen, REML). Je [Einheit Prädiktor] steigt [Zielgrösse] um [Schätzwert]\n> (SE = [SE], 95-Prozent-Konfidenzintervall [unten] bis [oben]). Die Gruppen\n> unterscheiden sich mit einer Standardabweichung von [σu], ICC = [ICC].\n\nImmer genannt werden: Struktur der zufälligen Effekte, Zahl der Gruppen,\nSchätzverfahren, feste Effekte mit Intervall und die Varianzkomponenten.\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt eines gemischten Modells |\n|---|---|\n| [Multiple lineare Regression](multiple-lineare-regression.qmd) | Beobachtungen sind unabhängig |\n| Regression mit Gruppe als festem Faktor | wenige Gruppen, und nur genau diese Gruppen interessieren |\n| [Gepaarter t-Test](../tests/t-test-gepaart.qmd) | genau zwei Messungen je Person, keine weiteren Prädiktoren |\n| [Varianzanalyse](../tests/anova.qmd) mit Messwiederholung | klassisches Design, balanciert, keine fehlenden Werte |\n| Cluster-robuste Standardfehler | nur die Standardfehler sollen korrigiert werden, die Gruppenvarianz interessiert nicht |\n\n## Beispiele\n\nJedes Beispiel steht in einem eigenen Reiter.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Wie viel machen die Klassen aus\n\n#### Frage und Datenlage\n\nHängt die Punktzahl in einem Test von den Lernstunden ab, und welcher Anteil der\nUnterschiede geht auf die Klasse zurück? 180 Personen aus 12 Klassen, je 15.\n\n#### Voraussetzungen prüfen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(zeilen = nrow(schule), klassen = nlevels(schule$klasse))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n zeilen klassen \n    180      12 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(mittel = mean(schule$punkte), sd = sd(schule$punkte)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmittel     sd \n 61.25  11.04 \n```\n\n\n:::\n\n```{.r .cell-code}\nboxplot(punkte ~ klasse, data = schule, xlab = \"Klasse\", ylab = \"Punkte\")\n```\n\n::: {.cell-output-display}\n![Beispiel 1: Punktzahl je Klasse.](gemischte-modelle_files/figure-html/fig-b1-gm-r-1.png){#fig-b1-gm-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport matplotlib.pyplot as plt\n\nprint(\"Zeilen:\", len(schule), \"Klassen:\", schule[\"klasse\"].nunique())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nZeilen: 180 Klassen: 12\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Mittel:\", round(schule[\"punkte\"].mean(), 2), \"SD:\", round(schule[\"punkte\"].std(), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMittel: 61.25 SD: 11.04\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achse = plt.subplots(figsize=(7, 3.4))\n_ = achse.boxplot([schule.loc[schule[\"klasse\"] == k, \"punkte\"] for k in range(1, 13)])\n_ = achse.set_xlabel(\"Klasse\")\n_ = achse.set_ylabel(\"Punkte\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Übersicht in Python.](gemischte-modelle_files/figure-html/fig-b1-gm-py-1.png){#fig-b1-gm-py width=100%}\n:::\n:::\n\n\n:::\n\nDie Klassen liegen sichtbar auf verschiedenem Niveau. Das ist genau die\nStruktur, die ein gewöhnliches Regressionsmodell übersieht.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm0 <- lmer(punkte ~ stunden + (1 | klasse), data = schule)\nsummary(m0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: punkte ~ stunden + (1 | klasse)\n   Data: schule\n\nREML criterion at convergence: 1297.3\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-2.2868 -0.7036  0.0335  0.6510  3.5559 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n klasse   (Intercept) 34.85    5.903   \n Residual             70.23    8.380   \nNumber of obs: 180, groups:  klasse, 12\n\nFixed effects:\n            Estimate Std. Error t value\n(Intercept)  50.1142     2.3653  21.187\nstunden       2.2244     0.3029   7.344\n\nCorrelation of Fixed Effects:\n        (Intr)\nstunden -0.641\n```\n\n\n:::\n\n```{.r .cell-code}\nvk <- as.data.frame(VarCorr(m0))\nround(c(sd_klasse = vk$sdcor[1], sd_rest = vk$sdcor[2],\n        icc = vk$vcov[1] / sum(vk$vcov)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsd_klasse   sd_rest       icc \n    5.903     8.380     0.332 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(confint(m0, parm = \"beta_\", method = \"Wald\"), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             2.5 % 97.5 %\n(Intercept) 45.478 54.750\nstunden      1.631  2.818\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nm0 = smf.mixedlm(\"punkte ~ stunden\", schule, groups=schule[\"klasse\"]).fit(reml=True)\nprint(m0.summary())\n\nvar_klasse = float(m0.cov_re.iloc[0, 0])\nvar_rest = m0.scale\nprint(\"sd_klasse:\", round(var_klasse ** 0.5, 3), \"sd_rest:\", round(var_rest ** 0.5, 3),\n      \"icc:\", round(var_klasse / (var_klasse + var_rest), 3))\n```\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| Achsenabschnitt | 50.114 | erwartete Punktzahl bei null Lernstunden in einer durchschnittlichen Klasse | extrapoliert, niemand lernt null Stunden; nur als Rechengrösse |\n| `stunden` | 2.224 | je zusätzlicher Stunde rund 2.2 Punkte mehr | fester Effekt, gilt über alle Klassen |\n| Standardfehler `stunden` | 0.303 | Unsicherheit der Steigung | Das Wald-Intervall reicht von 1.631 bis 2.818. |\n| Varianz Klasse | 34.849 | Streuung der Klassenniveaus, als Standardabweichung 5.903 Punkte | Eine Klasse eine Standardabweichung über dem Schnitt liegt knapp 6 Punkte höher. |\n| Restvarianz | 70.227 | Streuung innerhalb der Klassen, als Standardabweichung 8.380 | in Python die Zeile `Scale` |\n| ICC | 0.332 | ein Drittel der Streuung liegt zwischen den Klassen | weit entfernt von null; die Gruppenstruktur zu ignorieren wäre ein Fehler |\n\n#### Interpretation und Ergebnissatz\n\nDie Lernstunden wirken klar, und zugleich unterscheiden sich die Klassen\nerheblich. Ein Drittel der Unterschiede zwischen Personen erklärt sich schon\ndadurch, in welche Klasse sie gehen.\n\n> Die Punktzahl wurde mit einem linearen gemischten Modell mit zufälligem\n> Achsenabschnitt je Klasse ausgewertet (180 Personen in 12 Klassen, REML). Je\n> Lernstunde steigt die Punktzahl um 2.224 Punkte (SE = 0.303,\n> 95-Prozent-Konfidenzintervall 1.631 bis 2.818). Die Klassen unterscheiden sich\n> mit einer Standardabweichung von 5.903 Punkten, ICC = 0.332.\n\n### Beispiel 2: OLS ist zu sicher\n\n#### Frage und Datenlage\n\nHat die Klassengrösse einen Einfluss auf die Punktzahl? Die Klassengrösse ist\nein Merkmal der **Klasse**, nicht der Person: Alle 15 Personen einer Klasse\nhaben denselben Wert. Die Daten wurden ohne jeden Effekt der Klassengrösse\nerzeugt.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols <- lm(punkte ~ stunden + groesse, data = schule)\ngem <- lmer(punkte ~ stunden + groesse + (1 | klasse), data = schule)\n\nk_ols <- summary(ols)$coefficients[\"groesse\", ]\nk_gem <- summary(gem)$coefficients[\"groesse\", ]\nround(rbind(\n  ols      = c(schaetzung = k_ols[[1]], se = k_ols[[2]], p = k_ols[[4]]),\n  gemischt = c(schaetzung = k_gem[[1]], se = k_gem[[2]],\n               p = 2 * pnorm(-abs(k_gem[[3]])))\n), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         schaetzung     se      p\nols          0.3481 0.4088 0.3956\ngemischt     0.3610 1.0162 0.7224\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nols = smf.ols(\"punkte ~ stunden + groesse\", schule).fit()\ngem = smf.mixedlm(\"punkte ~ stunden + groesse\", schule,\n                  groups=schule[\"klasse\"]).fit(reml=True)\n\nprint(pd.DataFrame({\n    \"schaetzung\": [ols.params[\"groesse\"], gem.params[\"groesse\"]],\n    \"se\": [ols.bse[\"groesse\"], gem.bse[\"groesse\"]],\n    \"p\": [ols.pvalues[\"groesse\"], gem.pvalues[\"groesse\"]],\n}, index=[\"ols\", \"gemischt\"]).round(4))\n```\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Modell | Schätzung | Standardfehler | p | Wie es zu lesen ist |\n|---|---|---|---|---|\n| OLS | 0.348 | 0.409 | 0.3956 | behandelt 180 Zeilen als unabhängig |\n| gemischt | 0.361 | 1.016 | 0.7224 | berücksichtigt, dass es nur 12 verschiedene Klassengrössen gibt |\n\nDie Schätzung ist fast gleich, der Standardfehler aber im gemischten Modell\nzweieinhalbmal so gross. Hier sind beide Ergebnisse nicht signifikant, und das\nist richtig, weil die Daten ohne Effekt erzeugt wurden. Der zu kleine\nStandardfehler von OLS bleibt aber ein Fehler: Über viele solche Datensätze\nmeldet OLS für ein Klassenmerkmal deutlich öfter einen Scheineffekt, als das\nSignifikanzniveau zulässt.\n\n#### Interpretation und Ergebnissatz\n\nDer Unterschied betrifft vor allem Merkmale der Gruppe. Für die Lernstunden,\ndie innerhalb jeder Klasse variieren, liegen die Standardfehler von OLS und\ngemischtem Modell näher beieinander.\n\n> Ein Effekt der Klassengrösse liess sich nicht nachweisen (Schätzung 0.361\n> Punkte je Person, SE = 1.016, p = 0.72, lineares gemischtes Modell mit\n> zufälligem Achsenabschnitt je Klasse, 12 Klassen).\n\n### Beispiel 3: Braucht es eine zufällige Steigung\n\n#### Frage und Datenlage\n\nWirkt eine Lernstunde in allen Klassen gleich, oder unterscheidet sich die\nSteigung zwischen den Klassen? Verglichen werden zwei Modelle mit einem\nLikelihood-Quotienten-Test, beide mit ML geschätzt.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int   <- lmer(punkte ~ stunden + (1 | klasse), data = schule, REML = FALSE)\nm_slope <- lmer(punkte ~ stunden + (stunden | klasse), data = schule, REML = FALSE)\nanova(m_int, m_slope)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: schule\nModels:\nm_int: punkte ~ stunden + (1 | klasse)\nm_slope: punkte ~ stunden + (stunden | klasse)\n        npar    AIC    BIC  logLik -2*log(L)  Chisq Df Pr(>Chisq)\nm_int      4 1307.7 1320.5 -649.84    1299.7                     \nm_slope    6 1311.1 1330.2 -649.53    1299.1 0.6178  2     0.7342\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nm_int = smf.mixedlm(\"punkte ~ stunden\", schule, groups=schule[\"klasse\"]).fit(reml=False)\nm_slope = smf.mixedlm(\"punkte ~ stunden\", schule, groups=schule[\"klasse\"],\n                      re_formula=\"~stunden\").fit(reml=False)\n\nlr = 2 * (m_slope.llf - m_int.llf)\nprint(\"Chisq:\", round(lr, 3), \" Df: 2  p:\", round(stats.chi2.sf(lr, 2), 4))\n```\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| `Chisq` | 0.618 | doppelte Differenz der Log-Likelihoods | wie viel besser das komplexere Modell die Daten beschreibt |\n| `Df` | 2 | zwei zusätzliche Parameter | die Varianz der Steigung und ihre Korrelation mit dem Achsenabschnitt |\n| `Pr(>Chisq)` | 0.7342 | p-Wert des Vergleichs | kein Hinweis, dass die Steigung zwischen den Klassen variiert |\n| `AIC` (nur R) | | Informationskriterium | kleiner ist besser; der Vergleich steht in der Tabelle |\n\n#### Interpretation und Ergebnissatz\n\nDie Daten wurden **mit** einer leicht unterschiedlichen Steigung je Klasse\nerzeugt. Der Test findet sie trotzdem nicht: Zwölf Klassen reichen nicht, um\neine Streuung von 0.8 Punkten je Stunde von null zu unterscheiden. Das ist\nInterpretationsfalle drei in der Praxis. Das einfachere Modell ist hier die\nvertretbare Wahl, ein Beweis für gleiche Steigungen ist das nicht.\n\n> Ein Modell mit zufälliger Steigung für die Lernstunden verbesserte die\n> Anpassung nicht (χ²(2) = 0.62, p = 0.73); berichtet wird das Modell mit\n> zufälligem Achsenabschnitt.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEin Datensatz enthält 2000 Messungen von 20 Filialen. Ein Merkmal der Filiale\n(Verkaufsfläche) soll den Umsatz erklären. Wie viele unabhängige Beobachtungen\nstehen für diesen Effekt ungefähr zur Verfügung?\n\n- [x] Eher 20 als 2000 ~ Richtig. Die Fläche variiert nur zwischen den\n      Filialen. Innerhalb einer Filiale liefert jede weitere Messung keine neue\n      Information über die Fläche.\n- [ ] 2000, jede Messung zählt ~ Das ist genau die Annahme, mit der OLS den\n      Standardfehler zu klein schätzt.\n- [ ] 100, der Durchschnitt je Filiale ~ Die Zahl der Messungen je Filiale ist\n      für diesen Effekt nicht die Stichprobengrösse.\n:::\n\n::: {.quiz}\nlme4 meldet `boundary (singular) fit`. Was ist die sinnvollste Reaktion?\n\n- [x] Die Struktur der zufälligen Effekte vereinfachen, etwa die zufällige\n      Steigung weglassen ~ Richtig. Eine Varianz wurde auf null oder eine\n      Korrelation auf ±1 geschätzt, das Modell ist für die Daten zu komplex.\n- [ ] Die Warnung unterdrücken, die festen Effekte sind trotzdem gültig ~ Sie\n      können gültig sein, aber das Modell beschreibt eine Struktur, die die\n      Daten nicht tragen.\n- [ ] Auf OLS wechseln ~ Das ignoriert die Gruppenstruktur ganz und macht die\n      Standardfehler zu klein.\n:::\n\n::: {.quiz}\nDer ICC eines Modells beträgt zwei Prozent. Was bedeutet das?\n\n- [x] Nur zwei Prozent der Streuung liegen zwischen den Gruppen ~ Richtig. Die\n      Gruppen unterscheiden sich kaum. Bei grossen Gruppen kann selbst das die\n      Standardfehler von Gruppenmerkmalen spürbar vergrössern, der Design-Effekt\n      hängt auch an der Gruppengrösse.\n- [ ] Das Modell erklärt zwei Prozent der Varianz ~ Der ICC ist kein\n      Bestimmtheitsmass, sondern die Aufteilung der Restvarianz.\n- [ ] Der Effekt der Gruppe ist signifikant ~ Der ICC ist kein p-Wert und\n      sagt nichts über Signifikanz.\n:::\n\n## Verlinkte Ressourcen\n\n- [lme4: Fitting Linear Mixed-Effects Models (Bates et al.)](https://cran.r-project.org/package=lme4/vignettes/lmer.pdf)\n- [statsmodels: Linear Mixed Effects Models](https://www.statsmodels.org/stable/mixed_linear.html)\n- [GLMM FAQ (Ben Bolker)](https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html)\n",
    "supporting": [
      "gemischte-modelle_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}