{
  "hash": "6543af9a99aa30ba215e82774d9d5d60",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Häufigkeiten\"\ndescription: \"Absolute und relative Häufigkeiten, Kreuztabellen und ihre Darstellung.\"\ncategories: [\"Deskriptive Statistik\", \"EDA\", \"R\", \"Python\"]\nquelle: [\"ESDS\"]\nseitentyp: konzept\nstand: fertig\norder: 20\n---\n\n\n\n\n\n## Kernideen\n\n- **Absolute** Häufigkeit zählt, **relative** teilt durch $n$ und macht Gruppen\n  verschiedener Grösse vergleichbar, **kumulierte** summiert von unten auf.\n- Die kumulierte Häufigkeit setzt eine **Ordnung** voraus und ist bei nominalen\n  Merkmalen sinnlos.\n- Die **empirische Verteilungsfunktion** ist die kumulierte Häufigkeit für alle\n  Werte, sie bildet keine Klassen und enthält die vollständige Information.\n- Bei Kreuztabellen gibt es **drei** Prozentangaben (Zeile, Spalte, Gesamt), und\n  sie beantworten verschiedene Fragen.\n- Die **Klassenzahl** eines Histogramms ist eine inhaltliche Entscheidung, keine\n  technische Voreinstellung.\n- **Stabdiagramm** für Kategorien, **Histogramm** für klassierte Messwerte, die\n  Verwechslung ist ein Fehler in der Aussage, keine Geschmacksfrage.\n- Bei ungleich breiten Klassen trägt die **Fläche** die Information, nicht die\n  Höhe.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Skalenniveaus](skalenniveaus.qmd), weil das Messniveau\nbestimmt, welche Zusammenfassung überhaupt zulässig ist und ob klassiert werden\nmuss. Die Kennzahlen dazu stehen unter\n[Lage- und Streuungsmasse](lage-streuungsmasse.qmd).\n:::\n\n### Häufigkeiten: die erste Zusammenfassung\n\nEin Merkmal mit tausend Beobachtungen lässt sich nicht ansehen. Die\nHäufigkeitsverteilung reduziert es auf die Frage, wie oft jede Ausprägung\nvorkommt, und ist damit die einfachste Form der Verdichtung.\n\n| Variante | Was sie beantwortet | Setzt voraus |\n|---|---|---|\n| absolut $n_j$ | Wie viele? | nichts |\n| relativ $h_j = n_j / n$ | Welcher Anteil? | nichts |\n| kumuliert $\\sum_{i \\le j} h_i$ | Welcher Anteil erreicht höchstens diese Stufe? | eine **Ordnung** der Ausprägungen |\n\nDie relative Häufigkeit macht Gruppen unterschiedlicher Grösse vergleichbar:\nZwölf Ausfälle in einem Betrieb mit zwanzig Maschinen sind etwas anderes als\nzwölf in einem mit zweihundert.\n\n### Die empirische Verteilungsfunktion\n\nDie kumulierte Häufigkeit, konsequent für alle Werte eines metrischen Merkmals\ngebildet, ergibt eine Funktion: Sie gibt zu jedem Wert an, welcher Anteil der\nBeobachtungen höchstens so gross ist. Weil die Daten endlich sind, springt sie\nan jedem beobachteten Wert und ist dazwischen konstant.\n\nAus ihr lässt sich jedes Quantil ablesen: Man geht auf der senkrechten Achse zum\ngewünschten Anteil und liest waagerecht ab. Diese Verbindung zwischen Häufigkeit\nund Kennzahl ist der Grund, warum die Verteilungsfunktion mehr ist als eine\nDarstellungsvariante.\n\n### Klassenbildung\n\nBei stetigen Merkmalen kommt fast jeder Wert nur einmal vor. Eine Auszählung\nbrächte nichts, deshalb werden benachbarte Werte zu Klassen zusammengefasst.\nDie Klassenzahl verändert das Bild erheblich, und die gängigen Faustregeln\nliefern nur einen Startwert:\n\n| Regel | Formel | bei $n = 300$ |\n|---|---|---|\n| Wurzelregel | $\\sqrt{n}$ | 17 |\n| Sturges | $1 + \\log_2 n$ | 9 |\n| Rice | $2 \\sqrt[3]{n}$ | 13 |\n\nSturges unterstellt annähernd normalverteilte Daten und liefert bei grossen oder\nschiefen Stichproben zu wenige Klassen. In R ist es trotzdem die Voreinstellung\nvon `hist()`, allerdings nur als Vorschlag, den die Funktion auf \"schöne\" Werte\nrundet.\n\n### Stabdiagramm oder Histogramm\n\nBeide zeigen Balken, meinen aber Verschiedenes.\n\n| | Stabdiagramm | Histogramm |\n|---|---|---|\n| Für | nominale und ordinale Merkmale | metrische Merkmale |\n| Balken | getrennt, mit Luft dazwischen | stossen aneinander |\n| Warum | zwischen Bern und Chur liegt nichts | der Wertebereich ist lückenlos |\n| Information trägt | die Höhe | bei gleichen Klassen die Höhe, bei ungleichen die **Fläche** |\n| Reihenfolge | bei nominal beliebig, bei ordinal fest | durch die Werte vorgegeben |\n\n::: {.note-box}\nEin Balkendiagramm für ein stetiges Merkmal oder ein Histogramm für Kategorien\nist keine Geschmacksfrage, sondern ein Fehler in der Aussage.\n:::\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Drei Häufigkeiten, drei Fragen\n\n#### Frage und Datenlage\n\n60 Zufriedenheitsangaben auf drei Stufen. Was sagen absolute, relative und\nkumulierte Häufigkeit jeweils?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(zufriedenheit)                        # absolut: wie viele?\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nzufriedenheit\ngering mittel   hoch \n    11     30     19 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(prop.table(table(zufriedenheit)), 3)  # relativ: welcher Anteil?\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nzufriedenheit\ngering mittel   hoch \n 0.183  0.500  0.317 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(cumsum(prop.table(table(zufriedenheit))), 3)  # kumuliert\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngering mittel   hoch \n 0.183  0.683  1.000 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Der Modus: die haeufigste Auspraegung\nnames(which.max(table(zufriedenheit)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"mittel\"\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(zufriedenheit.value_counts().reindex(stufen))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngering    11\nmittel    30\nhoch      19\nName: count, dtype: int64\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(zufriedenheit.value_counts(normalize=True).reindex(stufen).round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngering    0.183\nmittel    0.500\nhoch      0.317\nName: proportion, dtype: float64\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(zufriedenheit.value_counts(normalize=True)\n      .reindex(stufen).cumsum().round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngering    0.183\nmittel    0.683\nhoch      1.000\nName: proportion, dtype: float64\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Modus:\", zufriedenheit.value_counts().idxmax())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModus: mittel\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Stufe | absolut | relativ | kumuliert |\n|---|---|---|---|\n| gering | 11 | 0.183 | 0.183 |\n| **mittel** | **30** | **0.500** | 0.683 |\n| hoch | 19 | 0.317 | **1.000** |\n| Summe | 60 | 1.000 |   |\n\n| Ausgabe | Wie sie zu lesen ist |\n|---|---|\n| **absolut** | Die reine Auszählung. Ohne die Angabe von $n$ ist sie nicht einzuordnen, 11 von 60 ist etwas anderes als 11 von 11 000. |\n| **relativ** | 18.3 Prozent geben eine geringe Zufriedenheit an. Diese Zahl ist mit einer anderen Erhebung vergleichbar, die absolute nicht. |\n| **kumuliert** | 68.3 Prozent geben höchstens \"mittel\" an. Der letzte Wert ist immer 1.000, ist er es nicht, fehlen Beobachtungen oder es gibt fehlende Werte. |\n| **Modus** | \"mittel\". Bei nominalen Merkmalen das **einzige** zulässige Lagemass. |\n\n::: {.note-box}\n**Die kumulierte Zeile ist nur bei geordneten Merkmalen sinnvoll.** Bei einer\nAbteilungszugehörigkeit \"68 Prozent gehören höchstens zur Verwaltung\" zu\nschreiben, ist Unsinn und beide Programme rechnen es trotzdem klaglos aus,\nweil sie die Kategorien alphabetisch sortieren.\n\nDer Schutz davor liegt im Datentyp: Ein geordneter Faktor beziehungsweise\n`Categorical(ordered=True)` hält die inhaltliche Reihenfolge fest, siehe\n[Skalenniveaus](skalenniveaus.qmd).\n\nUnd die **Reihenfolge der Stufen** muss angegeben werden: Ohne `levels =`\nsortiert R alphabetisch, und dann steht \"hoch\" vor \"mittel\".\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Hälfte der 60 Befragten gibt eine mittlere Zufriedenheit an (n = 30,\n> 50.0 Prozent), 31.7 Prozent eine hohe und 18.3 Prozent eine geringe. Höchstens\n> mittel zufrieden sind 68.3 Prozent.\n\n### Beispiel 2: Kreuztabellen und die drei Prozentangaben\n\n#### Frage und Datenlage\n\n200 Beschäftigte, zwei Merkmale: Abteilung (drei Ausprägungen) und Schichtarbeit\n(ja/nein). Die Frage: Hängen die beiden zusammen und welche Prozentangabe\nbeantwortet das?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nu2 <- lehmer(7715, 200)\nabteilung <- ifelse(u2 < 0.4, \"Produktion\",\n                    ifelse(u2 < 0.75, \"Verwaltung\", \"Verkauf\"))\nanteil <- c(Produktion = 0.55, Verwaltung = 0.25, Verkauf = 0.35)\nschicht <- ifelse(lehmer(7716, 200) < anteil[abteilung], \"ja\", \"nein\")\n\ntab <- table(abteilung, schicht)\naddmargins(tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            schicht\nabteilung     ja nein Sum\n  Produktion  46   33  79\n  Verkauf     16   34  50\n  Verwaltung  19   52  71\n  Sum         81  119 200\n```\n\n\n:::\n\n```{.r .cell-code}\nround(prop.table(tab) * 100, 1)          # Gesamtanteile\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            schicht\nabteilung      ja nein\n  Produktion 23.0 16.5\n  Verkauf     8.0 17.0\n  Verwaltung  9.5 26.0\n```\n\n\n:::\n\n```{.r .cell-code}\nround(prop.table(tab, margin = 1), 3)    # Zeilenanteile: je Abteilung\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            schicht\nabteilung       ja  nein\n  Produktion 0.582 0.418\n  Verkauf    0.320 0.680\n  Verwaltung 0.268 0.732\n```\n\n\n:::\n\n```{.r .cell-code}\nround(prop.table(tab, margin = 2), 3)    # Spaltenanteile: je Schichtstatus\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            schicht\nabteilung       ja  nein\n  Produktion 0.568 0.277\n  Verkauf    0.198 0.286\n  Verwaltung 0.235 0.437\n```\n\n\n:::\n\n```{.r .cell-code}\ntest <- chisq.test(tab)\nround(c(chi2 = test$statistic, df = test$parameter, p = test$p.value), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nchi2.X-squared          df.df              p \n       17.3641         2.0000         0.0002 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(sqrt(test$statistic / (sum(tab) * (min(dim(tab)) - 1))), 3)   # Cramers V\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nX-squared \n    0.295 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nu2 = lehmer(7715, 200)\nabteilung = np.where(u2 < 0.4, \"Produktion\",\n                     np.where(u2 < 0.75, \"Verwaltung\", \"Verkauf\"))\nanteil = {\"Produktion\": 0.55, \"Verwaltung\": 0.25, \"Verkauf\": 0.35}\nu3 = lehmer(7716, 200)\nschicht = np.array([\"ja\" if u3[i] < anteil[abteilung[i]] else \"nein\"\n                    for i in range(200)])\n\ntab = pd.crosstab(abteilung, schicht, margins=True)\nprint(tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncol_0       ja  nein  All\nrow_0                    \nProduktion  46    33   79\nVerkauf     16    34   50\nVerwaltung  19    52   71\nAll         81   119  200\n```\n\n\n:::\n\n```{.python .cell-code}\nroh = pd.crosstab(abteilung, schicht)\nprint((roh / roh.values.sum() * 100).round(1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncol_0         ja  nein\nrow_0                 \nProduktion  23.0  16.5\nVerkauf      8.0  17.0\nVerwaltung   9.5  26.0\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(roh.div(roh.sum(axis=1), axis=0).round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncol_0          ja   nein\nrow_0                   \nProduktion  0.582  0.418\nVerkauf     0.320  0.680\nVerwaltung  0.268  0.732\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(roh.div(roh.sum(axis=0), axis=1).round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncol_0          ja   nein\nrow_0                   \nProduktion  0.568  0.277\nVerkauf     0.198  0.286\nVerwaltung  0.235  0.437\n```\n\n\n:::\n\n```{.python .cell-code}\nchi2, p, dof, _ = stats.chi2_contingency(roh)\nprint({\"chi2\": round(chi2, 4), \"df\": dof, \"p\": round(p, 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'chi2': np.float64(17.3641), 'df': 2, 'p': np.float64(0.0002)}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Cramers V:\",\n      round(float(np.sqrt(chi2 / (roh.values.sum() * (min(roh.shape) - 1)))), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCramers V: 0.295\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nDie absolute Tabelle:\n\n| | Schicht ja | Schicht nein | Summe |\n|---|---|---|---|\n| Produktion | **46** | 33 | **79** |\n| Verkauf | 16 | 34 | 50 |\n| Verwaltung | 19 | 52 | 71 |\n| **Summe** | **81** | **119** | **200** |\n\nUnd dieselbe Tabelle dreimal in Prozent:\n\n| Prozentart | Bezugsgrösse | Produktion / ja | Beantwortet die Frage |\n|---|---|---|---|\n| **Gesamt** | alle 200 | **23.0 %** | \"Welcher Anteil aller Beschäftigten arbeitet in der Produktion **und** im Schichtbetrieb?\" |\n| **Zeile** | die 79 der Produktion | **58.2 %** | \"Welcher Anteil **der Produktion** arbeitet Schicht?\" |\n| **Spalte** | die 81 Schichtarbeitenden | **56.8 %** | \"Welcher Anteil **der Schichtarbeitenden** gehört zur Produktion?\" |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Drei Zahlen aus **einer** Zelle | 23.0, 58.2 und 56.8 Prozent, alle korrekt und alle etwas anderes. Wer \"58 Prozent\" ohne Bezugsgrösse schreibt, lässt offen, welche Frage beantwortet wurde. |\n| Für die Frage \"hängt es zusammen\" zählt die **Zeilenprozentzeile** | Produktion 58.2 Prozent, Verkauf 32.0 Prozent, Verwaltung 26.8 Prozent. Wären die Merkmale unabhängig, stünde überall derselbe Anteil, nämlich die 40.5 Prozent der Randverteilung. |\n| Die Randverteilungen | 81 von 200 arbeiten Schicht (40.5 Prozent); 79, 50 und 71 verteilen sich auf die Abteilungen. Sie beschreiben jedes Merkmal für sich, nicht den Zusammenhang. |\n| $\\chi^2$(2) = 17.36, p < .001 | Der Zusammenhang ist mit Zufall nicht vereinbar. Ausführlich unter [Chi-Quadrat-Tests](../tests/chi-quadrat-tests.qmd). |\n| Cramers V = **0.295** | Das Effektmass: 0 heisst kein Zusammenhang, 1 vollständiger. Ein mittlerer Zusammenhang. |\n\n::: {.note-box}\n**Die Faustregel für die Wahl der Prozentart:** Prozentuiert wird entlang der\n**erklärenden** Variablen. Wenn die Abteilung erklärt, ob jemand Schicht\narbeitet, gehören die Zeilenprozente in die Tabelle, dann summiert sich jede\nZeile auf 100 Prozent und die Zeilen sind untereinander vergleichbar.\n\nEin praktischer Test: Ändern sich die Prozentwerte, wenn man in einer Abteilung\nmehr Leute befragt? Bei Zeilenprozenten nicht, bei Gesamt- und Spaltenprozenten\nschon. Deshalb sind Zeilenprozente bei ungleich grossen Gruppen fast immer die\nrichtige Wahl.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Schichtarbeit ist in der Produktion deutlich häufiger als in den übrigen\n> Abteilungen: 58.2 Prozent gegenüber 32.0 Prozent im Verkauf und 26.8 Prozent in\n> der Verwaltung ($\\chi^2$(2) = 17.36, p < .001, Cramers V = 0.30, n = 200).\n\n### Beispiel 3: Die empirische Verteilungsfunktion\n\n#### Frage und Datenlage\n\n40 Messwerte. Die Verteilungsfunktion zeigt sie **alle**, ohne eine einzige\nEntscheidung über Klassen.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- round(normalwerte(7712, 40, 20, 4), 1)\n\nggplot(data.frame(x), aes(x)) +\n  stat_ecdf(geom = \"step\", linewidth = 0.8) +\n  geom_hline(yintercept = c(0.25, 0.5, 0.75), linetype = \"dashed\") +\n  labs(x = \"Messwert\", y = \"Anteil höchstens so gross\")\n\nround(c(n = length(x), minimum = min(x), q25 = quantile(x, 0.25),\n        median = median(x), q75 = quantile(x, 0.75), maximum = max(x)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      n minimum q25.25%  median q75.75% maximum \n  40.00   12.00   17.08   19.30   21.63   25.30 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Die Sprunghoehe ist immer 1/n, ausser bei Bindungen\nround(1 / length(x), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.025\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(duplicated(x))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: empirische Verteilungsfunktion. Jeder Sprung entspricht einer Beobachtung.](haeufigkeiten_files/figure-html/fig-b3-haeuf-r-1.png){#fig-b3-haeuf-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nx = np.round(normalwerte(7712, 40, 20, 4), 1)\nsortiert = np.sort(x)\nanteil = np.arange(1, len(x) + 1) / len(x)\n\nfig, achse = plt.subplots(figsize=(7, 3.4))\nachse.step(sortiert, anteil, where=\"post\", linewidth=1.2, color=\"black\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[<matplotlib.lines.Line2D object at 0x7fd6decbd610>]\n```\n\n\n:::\n\n```{.python .cell-code}\nfor hoehe in [0.25, 0.5, 0.75]:\n    achse.axhline(hoehe, linestyle=\"--\", color=\"black\", linewidth=0.6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<matplotlib.lines.Line2D object at 0x7fd6df07ea20>\n<matplotlib.lines.Line2D object at 0x7fd6dea7b290>\n<matplotlib.lines.Line2D object at 0x7fd6deac0b00>\n```\n\n\n:::\n\n```{.python .cell-code}\nachse.set_xlabel(\"Messwert\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nText(0.5, 0, 'Messwert')\n```\n\n\n:::\n\n```{.python .cell-code}\nachse.set_ylabel(\"Anteil höchstens so gross\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nText(0, 0.5, 'Anteil höchstens so gross')\n```\n\n\n:::\n\n```{.python .cell-code}\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselbe Treppenfunktion mit matplotlib.](haeufigkeiten_files/figure-html/fig-b3-haeuf-py-1.png){#fig-b3-haeuf-py width=100%}\n:::\n\n```{.python .cell-code}\nq25, q50, q75 = np.quantile(x, [0.25, 0.5, 0.75])\nprint({\"n\": len(x), \"minimum\": x.min(), \"q25\": round(q25, 2),\n       \"median\": round(q50, 2), \"q75\": round(q75, 2), \"maximum\": x.max()})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'n': 40, 'minimum': np.float64(12.0), 'q25': np.float64(17.08), 'median': np.float64(19.3), 'q75': np.float64(21.62), 'maximum': np.float64(25.3)}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Sprunghöhe 1/n:\", round(1 / len(x), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSprunghöhe 1/n: 0.025\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Bindungen:\", len(x) - len(np.unique(x)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBindungen: 6\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | Wert |\n|---|---|\n| n | 40 |\n| Minimum | 12.0 |\n| $Q_{25}$ | rund 17.4 |\n| **Median** | **19.30** |\n| $Q_{75}$ | rund 21.6 |\n| Maximum | 25.3 |\n| Sprunghöhe $1/n$ | **0.025** |\n\n| Ausgabe | Wie sie zu lesen ist |\n|---|---|\n| Die Kurve springt an jedem beobachteten Wert um **0.025** | Bei 40 Beobachtungen trägt jede genau ein Vierzigstel bei. Kommt ein Wert doppelt vor, springt die Kurve dort um das Doppelte. |\n| Die gestrichelten Linien bei 0.25, 0.5 und 0.75 | schneiden die Kurve an den drei Quartilen. **So liest man Quantile aus der Grafik ab**, waagerecht hinein, senkrecht heraus. |\n| Zwischen den Sprüngen ist die Kurve **waagrecht** | Dort liegt keine Beobachtung. Ein langer waagrechter Abschnitt ist eine Lücke in den Daten. |\n| Die Kurve beginnt bei 0 und endet bei 1 | Immer. Das ist der Unterschied zu einem Histogramm, dessen Höhe von der Klassenbreite abhängt. |\n\n::: {.note-box}\n**Warum diese Darstellung unterschätzt wird:** Sie enthält die **vollständige**\nInformation der Stichprobe, aus ihr lässt sich jeder einzelne Wert\nzurückgewinnen. Ein Histogramm kann das nicht, weil es die Werte innerhalb einer\nKlasse zusammenwirft.\n\nDer Preis ist die Lesbarkeit: Die Form der Verteilung (schief, zweigipflig,\nsymmetrisch) ist in einer Treppenkurve schwerer zu erkennen als in einem\nHistogramm. Ein steiler Abschnitt bedeutet viele Werte, ein flacher wenige, man\nliest also die **Steigung** statt der Höhe.\n\nFür den Vergleich **mehrerer** Gruppen ist sie dagegen die bessere Wahl: Drei\nTreppenkurven übereinander sind lesbar, drei Histogramme nicht.\n:::\n\n#### Interpretation\n\nWo eine Darstellung frei von willkürlichen Entscheidungen sein soll, ist die\nVerteilungsfunktion die richtige. Wo die Form gezeigt werden soll, das\nHistogramm und für beides braucht es Beispiel 4.\n\n### Beispiel 4: Die Klassenzahl entscheidet\n\n#### Frage und Datenlage\n\n300 Werte aus **zwei** überlagerten Gruppen (Schwerpunkte bei 18 und 28).\nDieselben Daten, dreimal gezeichnet.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 3), mar = c(4, 4, 3, 1))\nfor (k in c(5, 15, 60)) {\n  hist(werte, breaks = k, col = \"grey75\", border = \"white\",\n       main = paste(k, \"Klassen\"), xlab = \"Wert\", ylab = \"Anzahl\")\n}\npar(mfrow = c(1, 1))\n\n# Die Faustregeln im Vergleich\nn <- length(werte)\nround(c(n = n, wurzel = sqrt(n), sturges = 1 + log2(n),\n        rice = 2 * n^(1 / 3),\n        spannweite = diff(range(werte))), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         n     wurzel    sturges       rice spannweite \n     300.0       17.3        9.2       13.4       24.9 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 4: dieselben 300 Werte mit 5, 15 und 60 Klassen.](haeufigkeiten_files/figure-html/fig-b4-haeuf-r-3.png){#fig-b4-haeuf-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(1, 3, figsize=(7, 3.2))\nfor achse, k in zip(achsen, [5, 15, 60]):\n    achse.hist(werte, bins=k, color=\"0.75\", edgecolor=\"white\")\n    achse.set_title(f\"{k} Klassen\")\n    achse.set_xlabel(\"Wert\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(array([ 50., 102.,  55.,  83.,  10.]), array([12.20146406, 17.18566959, 22.16987513, 27.15408066, 32.13828619,\n       37.12249172]), <BarContainer object of 5 artists>)\nText(0.5, 1.0, '5 Klassen')\nText(0.5, 0, 'Wert')\n(array([ 2., 14., 34., 50., 32., 20., 11., 17., 27., 30., 35., 18.,  4.,\n        3.,  3.]), array([12.20146406, 13.8628659 , 15.52426775, 17.18566959, 18.84707144,\n       20.50847328, 22.16987513, 23.83127697, 25.49267881, 27.15408066,\n       28.8154825 , 30.47688435, 32.13828619, 33.79968804, 35.46108988,\n       37.12249172]), <BarContainer object of 15 artists>)\nText(0.5, 1.0, '15 Klassen')\nText(0.5, 0, 'Wert')\n(array([ 1.,  0.,  1.,  0.,  0.,  3.,  6.,  5.,  3.,  6., 12., 13., 13.,\n        8., 17., 12.,  7., 10.,  8.,  7.,  4.,  6.,  4.,  6.,  3.,  1.,\n        4.,  3.,  3.,  3.,  4.,  7.,  7.,  5.,  7.,  8., 11.,  8.,  6.,\n        5.,  9.,  8.,  9.,  9.,  4.,  4.,  2.,  8.,  0.,  2.,  1.,  1.,\n        2.,  1.,  0.,  0.,  1.,  0.,  1.,  1.]), array([12.20146406, 12.61681452, 13.03216498, 13.44751544, 13.8628659 ,\n       14.27821636, 14.69356683, 15.10891729, 15.52426775, 15.93961821,\n       16.35496867, 16.77031913, 17.18566959, 17.60102005, 18.01637051,\n       18.43172098, 18.84707144, 19.2624219 , 19.67777236, 20.09312282,\n       20.50847328, 20.92382374, 21.3391742 , 21.75452466, 22.16987513,\n       22.58522559, 23.00057605, 23.41592651, 23.83127697, 24.24662743,\n       24.66197789, 25.07732835, 25.49267881, 25.90802928, 26.32337974,\n       26.7387302 , 27.15408066, 27.56943112, 27.98478158, 28.40013204,\n       28.8154825 , 29.23083296, 29.64618342, 30.06153389, 30.47688435,\n       30.89223481, 31.30758527, 31.72293573, 32.13828619, 32.55363665,\n       32.96898711, 33.38433757, 33.79968804, 34.2150385 , 34.63038896,\n       35.04573942, 35.46108988, 35.87644034, 36.2917908 , 36.70714126,\n       37.12249172]), <BarContainer object of 60 artists>)\nText(0.5, 1.0, '60 Klassen')\nText(0.5, 0, 'Wert')\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[0].set_ylabel(\"Anzahl\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nText(0, 0.5, 'Anzahl')\n```\n\n\n:::\n\n```{.python .cell-code}\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselbe Gegenüberstellung mit matplotlib.](haeufigkeiten_files/figure-html/fig-b4-haeuf-py-1.png){#fig-b4-haeuf-py width=100%}\n:::\n\n```{.python .cell-code}\nn = len(werte)\nprint({\"n\": n, \"wurzel\": round(np.sqrt(n), 1),\n       \"sturges\": round(1 + np.log2(n), 1),\n       \"rice\": round(2 * n ** (1 / 3), 1),\n       \"spannweite\": round(werte.max() - werte.min(), 1)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'n': 300, 'wurzel': np.float64(17.3), 'sturges': np.float64(9.2), 'rice': 13.4, 'spannweite': np.float64(24.9)}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Klassenzahl | Klassenbreite | Was zu sehen ist |\n|---|---|---|\n| **5** | rund 5 Einheiten | Ein einziger breiter Berg. Die beiden Gruppen sind **weggeglättet**, sie fallen in dieselben Klassen. |\n| **15** | rund 1.7 | Zwei Gipfel, klar getrennt. Das entspricht der Wahrheit. |\n| **60** | rund 0.4 | Ein zackiges Auf und Ab. Die zwei Gipfel sind noch erkennbar, aber jede einzelne Klasse enthält im Mittel nur fünf Werte, und deren Schwankung sieht aus wie Struktur. |\n\n| Faustregel | Wert bei $n = 300$ |\n|---|---|\n| Wurzelregel $\\sqrt{n}$ | **17.3** |\n| Sturges $1 + \\log_2 n$ | **9.2** |\n| Rice $2\\sqrt[3]{n}$ | **13.4** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die Regeln liegen zwischen 9 und 17 | Und alle drei hätten hier funktioniert, die Zweigipfligkeit ist ab etwa 10 Klassen erkennbar. |\n| Sturges liefert am wenigsten | Die Regel leitet sich aus der Binomialverteilung ab und unterstellt annähernd normalverteilte Daten. Bei zweigipfligen oder schiefen Verteilungen glättet sie zu stark. |\n| Keine Regel kennt die **Daten** | Sie hängen alle nur an $n$. Eine Regel, die auch die Streuung einbezieht, ist Freedman-Diaconis: Klassenbreite $= 2 \\cdot \\text{IQR} / \\sqrt[3]{n}$. |\n| Die Voreinstellung ist nicht neutral | R nimmt Sturges, matplotlib nimmt zehn Klassen. Wer die Voreinstellung übernimmt, hat die Entscheidung getroffen, ohne es zu merken. |\n\n::: {.note-box}\n**Was daraus für die Praxis folgt:** Die Klassenzahl wird **variiert**, bevor\neine Grafik in einen Bericht kommt. Zeigt sich dieselbe Struktur bei 10, 15 und\n25 Klassen, ist sie da. Verschwindet sie bei kleiner Änderung, war sie Zufall.\n\nUnd im Bericht gehört die gewählte Klassenzahl genannt, sobald sie von der\nVoreinstellung abweicht, genau wie jede andere Analyseentscheidung.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die 300 Messwerte verteilen sich zweigipflig mit Schwerpunkten bei rund 18 und\n> 28 (Histogramm mit 15 Klassen). Bei fünf Klassen ist die Struktur nicht mehr\n> erkennbar, bei sechzig überlagert Zufallsschwankung sie.\n\n### Beispiel 5: Stabdiagramm, Histogramm und die Klassenbreite\n\n#### Frage und Datenlage\n\nZwei Fragen auf einmal: Wann welcher Diagrammtyp und was tun, wenn die Klassen\nverschieden breit sind?\n\nDie Altersverteilung einer Belegschaft in den üblichen, **ungleich breiten**\nKlassen: bis 25 (26 Jahre), 26 bis 35 (10 Jahre), 36 bis 50 (15 Jahre), 51 bis\n65 (15 Jahre).\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nbarplot(table(zufriedenheit), col = \"grey75\",\n        main = \"Stabdiagramm, ordinal\", ylab = \"Anzahl\")\nhist(werte, breaks = 15, col = \"grey75\", border = \"white\",\n     main = \"Histogramm, metrisch\", xlab = \"Wert\", ylab = \"Anzahl\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 5: links Kategorien mit Abstand, rechts ein Kontinuum ohne Lücken.](haeufigkeiten_files/figure-html/fig-b5-haeuf-r-3.png){#fig-b5-haeuf-r width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nklassen <- c(\"bis 25\", \"26-35\", \"36-50\", \"51-65\")\nanzahl <- c(38, 52, 66, 44)\nbreite <- c(26, 10, 15, 15)\ndichte <- anzahl / breite\n\ndata.frame(klassen, anzahl, breite, dichte = round(dichte, 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  klassen anzahl breite dichte\n1  bis 25     38     26   1.46\n2   26-35     52     10   5.20\n3   36-50     66     15   4.40\n4   51-65     44     15   2.93\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nbarplot(anzahl, names.arg = klassen, col = \"grey75\", space = 0,\n        main = \"falsch: Häufigkeit als Höhe\", ylab = \"Anzahl\")\nbarplot(dichte, names.arg = klassen, col = \"grey75\", space = 0, width = breite,\n        main = \"richtig: Dichte als Höhe\", ylab = \"Personen je Jahr\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 5: ungleich breite Altersklassen. Links die reine Häufigkeit, rechts die Häufigkeitsdichte.](haeufigkeiten_files/figure-html/fig-b5b-haeuf-r-1.png){#fig-b5b-haeuf-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nanzahl_z = zufriedenheit.value_counts().reindex(stufen)\n\nklassen = [\"bis 25\", \"26-35\", \"36-50\", \"51-65\"]\nanzahl = np.array([38, 52, 66, 44])\nbreite = np.array([26, 10, 15, 15])\ndichte = anzahl / breite\n\nprint(pd.DataFrame({\"klasse\": klassen, \"anzahl\": anzahl, \"breite\": breite,\n                    \"dichte\": dichte.round(2)}).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nklasse  anzahl  breite  dichte\nbis 25      38      26    1.46\n 26-35      52      10    5.20\n 36-50      66      15    4.40\n 51-65      44      15    2.93\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(2, 2, figsize=(7, 5.5))\nachsen[0, 0].bar(list(anzahl_z.index), anzahl_z.values, color=\"0.75\", width=0.6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<BarContainer object of 3 artists>\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[0, 0].set_title(\"Stabdiagramm, ordinal\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nText(0.5, 1.0, 'Stabdiagramm, ordinal')\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[0, 0].set_ylabel(\"Anzahl\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nText(0, 0.5, 'Anzahl')\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[0, 1].hist(werte, bins=15, color=\"0.75\", edgecolor=\"white\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(array([ 2., 14., 34., 50., 32., 20., 11., 17., 27., 30., 35., 18.,  4.,\n        3.,  3.]), array([12.20146406, 13.8628659 , 15.52426775, 17.18566959, 18.84707144,\n       20.50847328, 22.16987513, 23.83127697, 25.49267881, 27.15408066,\n       28.8154825 , 30.47688435, 32.13828619, 33.79968804, 35.46108988,\n       37.12249172]), <BarContainer object of 15 artists>)\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[0, 1].set_title(\"Histogramm, metrisch\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nText(0.5, 1.0, 'Histogramm, metrisch')\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[0, 1].set_xlabel(\"Wert\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nText(0.5, 0, 'Wert')\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[1, 0].bar(klassen, anzahl, color=\"0.75\", width=1.0, edgecolor=\"white\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<BarContainer object of 4 artists>\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[1, 0].set_title(\"falsch: Häufigkeit als Höhe\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nText(0.5, 1.0, 'falsch: Häufigkeit als Höhe')\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[1, 0].set_ylabel(\"Anzahl\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nText(0, 0.5, 'Anzahl')\n```\n\n\n:::\n\n```{.python .cell-code}\nkanten = np.r_[0, np.cumsum(breite)]\nachsen[1, 1].bar(kanten[:-1], dichte, width=breite, align=\"edge\",\n                 color=\"0.75\", edgecolor=\"white\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<BarContainer object of 4 artists>\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[1, 1].set_xticks(kanten[:-1] + breite / 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[<matplotlib.axis.XTick object at 0x7fd6d5729790>, <matplotlib.axis.XTick object at 0x7fd6d589d070>, <matplotlib.axis.XTick object at 0x7fd6d588db50>, <matplotlib.axis.XTick object at 0x7fd6d5788380>]\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[1, 1].set_xticklabels(klassen, fontsize=8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[Text(13.0, 0, 'bis 25'), Text(31.0, 0, '26-35'), Text(43.5, 0, '36-50'), Text(58.5, 0, '51-65')]\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[1, 1].set_title(\"richtig: Dichte als Höhe\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nText(0.5, 1.0, 'richtig: Dichte als Höhe')\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[1, 1].set_ylabel(\"Personen je Jahr\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nText(0, 0.5, 'Personen je Jahr')\n```\n\n\n:::\n\n```{.python .cell-code}\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 5: beide Gegenüberstellungen in Python.](haeufigkeiten_files/figure-html/fig-b5-haeuf-py-1.png){#fig-b5-haeuf-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Klasse | Anzahl | Breite (Jahre) | **Dichte** (Personen je Jahr) |\n|---|---|---|---|\n| bis 25 | 38 | 26 | **1.46** |\n| 26 bis 35 | 52 | 10 | **5.20** |\n| 36 bis 50 | **66** | 15 | **4.40** |\n| 51 bis 65 | 44 | 15 | **2.93** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Nach **Anzahl** ist die Klasse 36 bis 50 die grösste | 66 Personen. |\n| Nach **Dichte** ist es die Klasse 26 bis 35 | 5.20 gegen 4.40 Personen je Jahrgang. **Die Rangfolge kehrt sich um.** |\n| Die Klasse \"bis 25\" sieht in der falschen Darstellung mittelgross aus | Mit 1.46 Personen je Jahrgang ist sie die **mit Abstand dünnste**, sie wirkt nur gross, weil sie 26 Jahrgänge zusammenfasst. |\n| Die Fläche trägt die Information | Breite mal Höhe ergibt wieder die Anzahl: $26 \\cdot 1.46 = 38$. Genau deshalb ist die Dichte die richtige Höhe. |\n\nUnd die Unterscheidung der beiden Diagrammtypen:\n\n| Woran man es erkennt | Stabdiagramm | Histogramm |\n|---|---|---|\n| Abstand zwischen den Balken | vorhanden | keiner |\n| Achsenbeschriftung | Kategorienamen | Zahlen mit Skala |\n| Umordnen der Balken | erlaubt (bei nominal) | verboten |\n\n::: {.note-box}\n**Ein verwandter Fehler, der noch häufiger vorkommt:** Ein Stabdiagramm mit\nBalken, deren Achse nicht bei null beginnt. Bei einem Histogramm ist die\nabgeschnittene Achse ausgeschlossen, weil die Fläche die Information trägt; bei\nBalken wird sie regelmässig verwendet, um kleine Unterschiede gross aussehen zu\nlassen.\n\nDie Regel: **Balkenlängen werden verglichen, also beginnt die Achse bei null.**\nWer Unterschiede genauer zeigen will, nimmt einen Punktplot, dort vergleicht\nman Positionen, nicht Längen, und eine abgeschnittene Achse ist zulässig.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Altersverteilung ist in ungleich breiten Klassen erhoben. Aufgetragen wird\n> die Häufigkeitsdichte: Am stärksten besetzt ist die Klasse 26 bis 35 mit 5.2\n> Personen je Jahrgang, am schwächsten die Klasse bis 25 mit 1.5, obwohl diese\n> in absoluten Zahlen nicht die kleinste ist.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEine Kreuztabelle nennt für die Zelle \"Produktion und Schicht\" die Zahl\n58.2 Prozent. Worauf bezieht sie sich?\n\n- [x] Auf die Beschäftigten der Produktion ~ Richtig, das ist der Zeilenanteil.\n      Die Gesamtprozente wären 23.0, die Spaltenprozente 56.8, drei richtige\n      Zahlen für dieselbe Zelle, die verschiedene Fragen beantworten.\n- [ ] Auf alle Beschäftigten ~ Das wären die Gesamtprozente.\n- [ ] Auf die Schichtarbeitenden ~ Das wären die Spaltenprozente.\n:::\n\n::: {.quiz}\nDieselben 300 Werte werden mit 5, 15 und 60 Klassen dargestellt. Was zeigt der\nVergleich?\n\n- [ ] Mehr Klassen sind immer genauer ~ Bei sechzig geht die Struktur im Rauschen\n      unter. Auflösung ist nicht dasselbe wie Erkenntnis.\n- [x] Die zwei überlagerten Gruppen sind erst ab etwa zehn Klassen zu sehen ~\n      Richtig. Zu wenige Klassen glätten die Struktur weg, zu viele lassen\n      Zufall wie Struktur aussehen.\n- [ ] Die Klassenzahl beeinflusst nur das Aussehen, nicht die Aussage ~ Sie\n      beeinflusst genau die Aussage.\n:::\n\n::: {.quiz}\nWarum ist die empirische Verteilungsfunktion unabhängig von der Klassenzahl?\n\n- [x] Weil sie keine Klassen bildet, sondern an jedem beobachteten Wert springt\n      ~ Richtig. Sie enthält damit die vollständige Information der Stichprobe\n      und eignet sich, wenn eine Darstellung frei von willkürlichen\n      Entscheidungen sein soll.\n- [ ] Weil sie immer 100 Klassen verwendet ~ Sie verwendet gar keine.\n- [ ] Weil sie nur für kleine Stichproben definiert ist ~ Sie ist für jede\n      Stichprobengrösse definiert.\n:::\n\n::: {.quiz}\nEine Altersverteilung wird in den Klassen bis 25, 26 bis 35, 36 bis 50 und 51\nbis 65 dargestellt. Was ist beim Zeichnen zu beachten?\n\n- [x] Aufzutragen ist die Häufigkeitsdichte, nicht die Häufigkeit ~ Richtig.\n      Die Klassen sind 26, 10, 15 und 15 Jahre breit. Trägt man die reinen\n      Häufigkeiten als Höhe auf, kehrt sich die Rangfolge um: Nach Anzahl ist\n      36 bis 50 die grösste Klasse, nach Dichte 26 bis 35.\n- [ ] Die Klassen müssen gleich viele Personen enthalten ~ Das ist nicht nötig\n      und meist gar nicht möglich.\n- [ ] Nichts Besonderes, ein Histogramm ist ein Histogramm ~ Bei ungleichen\n      Klassenbreiten trägt die Fläche die Information, nicht die Höhe.\n:::\n\n::: {.quiz}\nWoran erkennt man in einer fremden Grafik, ob ein Histogramm oder ein\nStabdiagramm gemeint war?\n\n- [ ] An der Farbe der Balken ~ Die Farbe trägt keine solche Information.\n- [x] Am Abstand zwischen den Balken und an der Achse ~ Richtig. Berühren sich\n      die Balken über einer kontinuierlichen Achse, ist es ein Histogramm.\n      Stehen sie getrennt über beschrifteten Kategorien, ein Stabdiagramm und\n      dort darf man sie umordnen, im Histogramm nicht.\n- [ ] An der Anzahl der Balken ~ Beide können beliebig viele haben.\n:::\n\n::: {.quiz}\nEine Auswertung nennt \"höchstens mittel: 68 Prozent\" für die Abteilungen eines\nBetriebs. Was ist daran falsch?\n\n- [x] Kumulierte Häufigkeiten setzen eine Ordnung voraus, die es hier nicht gibt\n      ~ Richtig. Abteilungen sind nominal; ihre Reihenfolge in der Tabelle ist\n      willkürlich, meist alphabetisch. Beide Programme rechnen die Summe\n      trotzdem klaglos aus.\n- [ ] 68 Prozent ist zu hoch für eine Kategorie ~ Die Höhe ist nicht das\n      Problem.\n- [ ] Es fehlt die Angabe von n ~ Sie fehlt tatsächlich, aber der eigentliche\n      Fehler liegt in der Kumulierung.\n:::\n\n## Verlinkte Ressourcen\n\n- [OpenIntro Statistics (frei verfügbar)](https://www.openintro.org/book/os/)\n- [Chi-Quadrat-Tests für Kreuztabellen](../tests/chi-quadrat-tests.qmd)\n",
    "supporting": [
      "haeufigkeiten_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}