{
  "hash": "50b87e5a1c44f794de891415e4d13100",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Farbe\"\ndescription: \"Paletten nach Aufgabe, Kontrast und Farbfehlsichtigkeit.\"\ncategories: [\"Farbe\", \"Wahrnehmung\", \"Visualisierung\", \"R\", \"Python\"]\nquelle: [\"DAVI\"]\nseitentyp: konzept\nstand: fertig\norder: 70\n---\n\n\n\n\n\n## Kernideen\n\n- Farbe hat drei Aufgaben: **unterscheiden, Mengen darstellen, hervorheben**.\n  Zu jeder gehört ein Palettentyp, und Verwechslungen führen in die Irre.\n- Ein Farbverlauf über nominale Kategorien behauptet eine Rangfolge.\n- Wie verschieden zwei Farben sind, lässt sich **messen**, im Lab-Raum, wo\n  Abstände ungefähr der wahrgenommenen Verschiedenheit entsprechen.\n- Regenbogenpaletten sind nicht **monoton in der Helligkeit**: Sie erzeugen\n  Grenzen, wo keine sind, und lassen weit entfernte Werte gleich aussehen.\n- Rot-Grün darf nie der einzige Unterscheidungskanal sein. Unter Deuteranopie\n  fällt der Abstand zwischen Rot und Grün von 120 auf 8.\n- Kontrast ist **nachrechenbar**: Für Text braucht es mindestens 4.5 zu 1.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Wahrnehmung und Kodierung](wahrnehmung-kodierung.qmd), vor\nallem die Rangfolge der Kanäle: Farbton eignet sich zum Unterscheiden, nicht\nzum Ablesen von Mengen.\n:::\n\n### Drei Aufgaben, drei Palettentypen\n\n| Aufgabe | Palettentyp | Wann | Beispiele |\n|---|---|---|---|\n| Unterscheiden | qualitativ | nominale Kategorien ohne Reihenfolge | Okabe-Ito, ColorBrewer Set2 |\n| Menge darstellen | sequenziell | kontinuierliche Werte mit einer Richtung | Viridis, Blues |\n| Abweichung zeigen | divergierend | Werte mit sinnvollem Nullpunkt: Saldo, Veränderung | RdBu, BrBG |\n| Hervorheben | Akzent auf Grau | eine Gruppe soll auffallen | alles grau, eine Serie farbig |\n\nDer häufigste Fehler ist die Verwechslung der ersten beiden. Ein Farbverlauf\nüber Standorte suggeriert, dass Bern \"weniger\" ist als Zürich. Umgekehrt\nzerlegt eine qualitative Palette eine kontinuierliche Grösse in scheinbare\nKlassen.\n\n### Warum sich Farbe rechnen lässt\n\nDer Hex-Wert einer Farbe sagt nichts darüber, wie verschieden zwei Farben\n**aussehen**: `#FF0000` und `#00FF00` unterscheiden sich in den Zahlen genauso\nstark wie `#FF0000` und `#FF0001`. Der **Lab-Raum** ist so gebaut, dass der\neuklidische Abstand ungefähr der wahrgenommenen Verschiedenheit entspricht.\nDieser Abstand heisst ΔE.\n\n| ΔE | Bedeutung |\n|---|---|\n| unter 1 | für das Auge nicht unterscheidbar |\n| 1 bis 10 | erkennbar, wenn die Flächen aneinandergrenzen |\n| 10 bis 25 | in einer Grafik sicher unterscheidbar |\n| über 25 | deutlich verschieden |\n\nFür eine Kategorienpalette gilt: Der **kleinste** paarweise Abstand entscheidet,\ndenn an ihm scheitert das Ablesen. Beispiel 2 misst das nach.\n\nDie Umrechnung braucht kein Zusatzpaket, sRGB zu linearem RGB, dann über XYZ\nnach Lab sind rund zehn Zeilen, und sie stehen im Setup dieser Seite.\n\n### Der Graustufentest\n\nDie schnellste Prüfung: die Grafik in Graustufen ansehen. Ist sie dann nicht\nmehr lesbar, trägt der Farbton zu viel Last. Das betrifft nicht nur den Druck,\nsondern auch Projektoren, schlechte Bildschirme und eingeschränktes Farbsehen.\n\nRechnerisch ist \"Graustufe\" die **relative Luminanz**, die gewichtete Summe der\nlinearisierten Kanäle mit 0.2126, 0.7152 und 0.0722. Eine sequenzielle Palette\nmuss darin **monoton** sein, sonst kodiert sie Mengen falsch. Beispiel 3 zeigt,\nworan Regenbogenpaletten scheitern.\n\n### Farbfehlsichtigkeit\n\nEtwa acht Prozent der Männer sehen Rot und Grün nur eingeschränkt getrennt. Das\nist kein Randfall, sondern in jeder grösseren Runde jemand.\n\nDrei Regeln decken das ab:\n\n1. **Rot-Grün nie als einzigen Kanal.** Zusätzlich Form, Position oder direkte\n   Beschriftung einsetzen.\n2. **Geprüfte Paletten verwenden.** Viridis für Verläufe, Okabe-Ito für\n   Kategorien sind dafür entworfen.\n3. **Nicht auf Farbe allein hervorheben.** Ein Akzent verträgt zusätzlich eine\n   dickere Linie oder eine Beschriftung.\n\nDie Okabe-Ito-Palette für Kategorien, als Werte zum Kopieren:\n\n```r\nokabe_ito <- c(\"#E69F00\", \"#56B4E9\", \"#009E73\", \"#F0E442\",\n               \"#0072B2\", \"#D55E00\", \"#CC79A7\", \"#000000\")\n```\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Der falsche Palettentyp\n\n#### Frage und Datenlage\n\nFünf Standorte ohne Reihenfolge, dargestellt mit einer sequenziellen Palette.\nWas genau behauptet diese Grafik, das die Daten nicht hergeben?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstandorte <- c(\"Bern\", \"Chur\", \"Genf\", \"Luzern\", \"Zug\")\numsatz <- c(41, 37, 52, 33, 45)\n\nverlauf <- c(\"#440154\", \"#3E4A89\", \"#26828E\", \"#35B779\", \"#FDE725\")\nround(rbind(luminanz = sapply(verlauf, luminanz)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         #440154 #3E4A89 #26828E #35B779 #FDE725\nluminanz   0.019   0.077   0.183    0.36   0.782\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(verhaeltnis_hellste_zu_dunkelste =\n          luminanz(verlauf[5]) / luminanz(verlauf[1])), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nverhaeltnis_hellste_zu_dunkelste \n                            41.3 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Die Verlaufspalette ordnet die Standorte -- nach welchem Kriterium?\ndata.frame(standort = standorte, umsatz = umsatz,\n           luminanz = round(sapply(verlauf, luminanz), 3), row.names = NULL)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  standort umsatz luminanz\n1     Bern     41    0.019\n2     Chur     37    0.077\n3     Genf     52    0.183\n4   Luzern     33    0.360\n5      Zug     45    0.782\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nbarplot(umsatz, names.arg = standorte, col = verlauf, border = NA,\n        ylab = \"Umsatz\", main = \"Verlaufspalette\")\nbarplot(umsatz, names.arg = standorte, col = OKABE[1:5], border = NA,\n        ylab = \"Umsatz\", main = \"qualitative Palette\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 1: oben nominale Standorte mit Verlaufspalette, unten mit qualitativer.](farbe_files/figure-html/fig-b1-fa-r-1.png){#fig-b1-fa-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nstandorte = [\"Bern\", \"Chur\", \"Genf\", \"Luzern\", \"Zug\"]\numsatz = np.array([41, 37, 52, 33, 45])\n\nverlauf = [\"#440154\", \"#3E4A89\", \"#26828E\", \"#35B779\", \"#FDE725\"]\nprint({\"luminanz\": [round(luminanz(h), 3) for h in verlauf]})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'luminanz': [0.019, 0.077, 0.183, 0.36, 0.782]}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"verhaeltnis_hellste_zu_dunkelste\":\n       round(luminanz(verlauf[4]) / luminanz(verlauf[0]), 1)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'verhaeltnis_hellste_zu_dunkelste': 41.3}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pd.DataFrame({\"standort\": standorte, \"umsatz\": umsatz,\n                    \"luminanz\": [round(luminanz(h), 3) for h in verlauf]})\n      .to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstandort  umsatz  luminanz\n    Bern      41     0.019\n    Chur      37     0.077\n    Genf      52     0.183\n  Luzern      33     0.360\n     Zug      45     0.782\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.4))\n_ = achsen[0].bar(standorte, umsatz, color=verlauf)\n_ = achsen[0].set_title(\"Verlaufspalette\")\n_ = achsen[1].bar(standorte, umsatz, color=OKABE[:5])\n_ = achsen[1].set_title(\"qualitative Palette\")\nfor achse in achsen:\n    _ = achse.set_ylabel(\"Umsatz\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Gegenüberstellung in Python.](farbe_files/figure-html/fig-b1-fa-py-1.png){#fig-b1-fa-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Standort | Bern | Chur | Genf | Luzern | Zug |\n|---|---|---|---|---|---|\n| Umsatz | 41 | 37 | **52** | **33** | 45 |\n| Luminanz der Balkenfarbe | **0.019** | 0.077 | 0.183 | 0.360 | **0.782** |\n\nVerhältnis der hellsten zur dunkelsten Farbe: **41.3**.\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die Farben werden von links nach rechts **immer heller** | Um den Faktor 41. Das Auge liest darin eine Steigerung, die Palette behauptet eine Reihenfolge Bern < Chur < Genf < Luzern < Zug. |\n| Diese Reihenfolge ist **alphabetisch**, nicht inhaltlich | Sie entstand aus der Sortierung der Namen. Mit den Umsätzen hat sie nichts zu tun: Genf hat den höchsten Umsatz (52) und bekommt eine mittlere Farbe, Zug mit 45 die hellste. |\n| Es werden also **zwei Grössen** dargestellt | Die Balkenhöhe zeigt den Umsatz, die Farbe zeigt die alphabetische Position und nur eine der beiden ist gemeint. |\n| Rechts trägt die Farbe **keine** Information mehr | Und das ist richtig so: Die Standorte sind bereits durch ihre Position unterscheidbar. **Farbe, die nichts kodiert, sollte gar nicht variieren.** |\n| Die ehrlichste Variante wäre **einfarbig** | Alle Balken grau, nur der hervorgehobene farbig. Siehe [Wahrnehmung, Beispiel 3](wahrnehmung-kodierung.qmd). |\n\n::: {.note-box}\n**Die Entscheidungsfrage lautet nicht \"welche Farben\", sondern \"wofür\".**\n\n| Kodiert die Farbe … | Palettentyp |\n|---|---|\n| nichts (Position reicht schon) | **keine**, einfarbig oder grau |\n| eine nominale Kategorie | qualitativ |\n| eine geordnete Grösse mit einer Richtung | sequenziell |\n| eine Abweichung von einem Nullpunkt | divergierend |\n| genau eine hervorzuhebende Gruppe | Akzent auf Grau |\n\nDie erste Zeile wird am häufigsten übersehen. Ein Balkendiagramm mit fünf\nverschiedenfarbigen Balken hat meistens fünf Farben zu viel.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die sequenzielle Palette ordnet die fünf Standorte über eine Luminanz von\n> 0.019 bis 0.782, also um den Faktor 41. Diese Ordnung entspricht der\n> alphabetischen Reihenfolge der Namen und nicht dem dargestellten Umsatz.\n\n### Beispiel 2: Wie weit die Farben auseinanderliegen\n\n#### Frage und Datenlage\n\nZwei Kategorienpaletten: Okabe-Ito mit acht Farben und eine Regenbogenpalette\nmit zwölf. Gemessen wird der **kleinste** paarweise Abstand im Lab-Raum, denn\nan ihm entscheidet sich, ob eine Legende überhaupt zuzuordnen ist.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npaarabstaende <- function(farben, namen = seq_along(farben)) {\n  paare <- t(combn(length(farben), 2))\n  data.frame(a = namen[paare[, 1]], b = namen[paare[, 2]],\n             dE = apply(paare, 1, function(p) abstand(farben[p[1]], farben[p[2]])))\n}\n\nokabe_ab <- paarabstaende(OKABE, OKABE_NAMEN)\nhead(okabe_ab[order(okabe_ab$dE), ], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            a        b       dE\n10 himmelblau     blau 26.43333\n5      orange zinnober 33.42918\n3      orange     gelb 35.09136\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(minimum = min(okabe_ab$dE), median = median(okabe_ab$dE),\n        maximum = max(okabe_ab$dE), paare = nrow(okabe_ab)), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nminimum  median maximum   paare \n   26.4    83.2   125.0    28.0 \n```\n\n\n:::\n\n```{.r .cell-code}\nregen_ab <- paarabstaende(REGEN12)\nhead(regen_ab[order(regen_ab$dE), ], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   a  b       dE\n61 9 10 17.38086\n31 4  5 18.71166\n39 5  6 37.81341\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(minimum = min(regen_ab$dE), median = median(regen_ab$dE),\n        paare_unter_20 = sum(regen_ab$dE < 20), paare = nrow(regen_ab)), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       minimum         median paare_unter_20          paare \n          17.4          145.8            2.0           66.0 \n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(2, 1), mar = c(1, 1, 2.5, 1))\nimage(matrix(1:8, ncol = 1), col = OKABE, axes = FALSE,\n      main = \"Okabe-Ito (8 Farben)\")\nimage(matrix(1:12, ncol = 1), col = REGEN12, axes = FALSE,\n      main = \"Regenbogen (12 Farben)\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 2: Okabe-Ito mit acht Farben, Regenbogen mit zwölf.](farbe_files/figure-html/fig-b2-fa-r-3.png){#fig-b2-fa-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndef paarabstaende(farben, namen=None):\n    namen = namen if namen is not None else list(range(1, len(farben) + 1))\n    return pd.DataFrame([{\"a\": namen[i], \"b\": namen[j],\n                          \"dE\": abstand(farben[i], farben[j])}\n                         for i, j in itertools.combinations(range(len(farben)), 2)])\n\n\nokabe_ab = paarabstaende(OKABE, OKABE_NAMEN)\nprint(okabe_ab.nsmallest(3, \"dE\").to_string(index=False))\nprint({\"minimum\": round(okabe_ab[\"dE\"].min(), 1),\n       \"median\": round(okabe_ab[\"dE\"].median(), 1),\n       \"maximum\": round(okabe_ab[\"dE\"].max(), 1),\n       \"paare\": len(okabe_ab)})\n\nregen_ab = paarabstaende(REGEN12)\nprint(regen_ab.nsmallest(3, \"dE\").to_string(index=False))\nprint({\"minimum\": round(regen_ab[\"dE\"].min(), 1),\n       \"median\": round(regen_ab[\"dE\"].median(), 1),\n       \"paare_unter_20\": int((regen_ab[\"dE\"] < 20).sum()),\n       \"paare\": len(regen_ab)})\n\nfig, achsen = plt.subplots(2, 1, figsize=(7, 2.6))\nfor achse, (titel, pal) in zip(achsen, [(\"Okabe-Ito (8 Farben)\", OKABE),\n                                        (\"Regenbogen (12 Farben)\", REGEN12)]):\n    for k, farbe in enumerate(pal):\n        _ = achse.bar(k, 1, width=1, color=farbe)\n    _ = achse.set_title(titel, fontsize=10)\n    _ = achse.axis(\"off\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselben zwei Paletten in Python.](farbe_files/figure-html/fig-b2-fa-py-1.png){#fig-b2-fa-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nOkabe-Ito, die drei engsten Paare:\n\n| Paar | ΔE |\n|---|---|\n| himmelblau, blau | **26.4** |\n| orange, zinnober | 33.4 |\n| orange, gelb | 35.1 |\n\n| Palette | Minimum | Median | Paare | darunter unter ΔE 20 |\n|---|---|---|---|---|\n| **Okabe-Ito** (8) | **26.4** | 83.2 | 28 | 0 |\n| **Regenbogen** (12) | **17.4** |   | 66 | **2** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Okabe-Ito hält überall mindestens **ΔE 26** ein | Auch das engste Paar liegt über der Schwelle von 25, ab der Farben \"deutlich verschieden\" sind. Die Palette ist genau darauf hin entworfen. |\n| Der Median liegt bei **83** | Die meisten Paare sind weit auseinander. Das ist der Spielraum, der die acht Farben trägt. |\n| Der Regenbogen mit zwölf Farben fällt auf **17.4** | Und zwei Paare liegen unter 20. Das ist noch unterscheidbar, wenn die Flächen gross sind, in einer Legende mit kleinen Quadraten nicht mehr zuverlässig. |\n| Das engste Paar ist **blau und violett** | Position 9 und 10 der Palette, also **benachbarte** Farbtöne. Bei zwölf Stufen auf einem Farbkreis liegen die Nachbarn zwangsläufig eng. |\n| Mehr Kategorien heisst immer **engere Abstände** | Der Farbraum ist endlich. Deshalb endet Farbe als Unterscheidungskanal bei ungefähr acht, nicht wegen einer Konvention, sondern wegen der Geometrie. |\n\n::: {.note-box}\n**Der kleinste Abstand ist das Mass, nicht der Durchschnitt.** Eine Palette mit\neinem Median von 80 und einem Minimum von 5 ist unbrauchbar: An genau dem einen\nPaar scheitert jede Zuordnung, und das Publikum weiss nicht, welches Paar es\nwar.\n\nDeshalb lohnt sich diese Rechnung vor jeder selbstgebauten Palette, sie kostet\nfünf Zeilen und beantwortet die Frage, die man sonst nur raten kann.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Okabe-Ito-Palette hält bei acht Farben einen kleinsten paarweisen\n> Lab-Abstand von 26.4 ein, bei einem Median von 83.2. Eine Regenbogenpalette\n> mit zwölf Farben fällt auf 17.4, und zwei ihrer 66 Paare liegen unter ΔE 20.\n\n### Beispiel 3: Der Graustufentest, nachgerechnet\n\n#### Frage und Datenlage\n\nZwei sequenzielle Paletten mit je zehn Stufen: Viridis und Regenbogen. Eine\nsequenzielle Palette muss in der Helligkeit **monoton** sein, sonst stehen\nverschiedene Werte für dieselbe Graustufe.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (nm in c(\"VIRIDIS10\", \"REGEN10\")) {\n  L <- sapply(get(nm), luminanz)\n  d <- diff(L)\n  cat(sprintf(\"%-10s Luminanz %s\\n\", nm,\n              paste(sprintf(\"%.3f\", L), collapse = \" \")))\n  cat(sprintf(\"           %s, Richtungswechsel %d, Spanne %.3f bis %.3f\\n\",\n              if (all(d > 0)) \"monoton steigend\" else \"NICHT monoton\",\n              sum(sign(d[-length(d)]) * sign(d[-1]) < 0), min(L), max(L)))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVIRIDIS10  Luminanz 0.019 0.043 0.077 0.125 0.183 0.266 0.360 0.476 0.621 0.782\n           monoton steigend, Richtungswechsel 0, Spanne 0.019 bis 0.782\nREGEN10    Luminanz 0.213 0.440 0.844 0.722 0.725 0.787 0.167 0.079 0.201 0.236\n           NICHT monoton, Richtungswechsel 4, Spanne 0.079 bis 0.844\n```\n\n\n:::\n\n```{.r .cell-code}\n# Welche Stufen des Regenbogens werden in Graustufen ununterscheidbar?\nL <- sapply(REGEN10, luminanz)\npaare <- t(combn(10, 2))\nkoll <- data.frame(a = paare[, 1], b = paare[, 2],\n                   unterschied = abs(L[paare[, 1]] - L[paare[, 2]]))\nhead(koll[order(koll$unterschied), ], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   a  b unterschied\n25 4  5 0.002555019\n8  1  9 0.012026308\n9  1 10 0.022999077\n```\n\n\n:::\n\n```{.r .cell-code}\nc(paare_unter_0.02 = sum(koll$unterschied < 0.02), paare = nrow(koll))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npaare_unter_0.02            paare \n               2               45 \n```\n\n\n:::\n\n```{.r .cell-code}\ngrau <- function(farben) {\n  sapply(farben, function(h) {\n    g <- luminanz(h)^(1 / 2.2)\n    rgb(g, g, g)\n  })\n}\npar(mfrow = c(2, 2), mar = c(1, 1, 2.5, 1))\nimage(matrix(1:10, ncol = 1), col = VIRIDIS10, axes = FALSE, main = \"Viridis\")\nimage(matrix(1:10, ncol = 1), col = REGEN10, axes = FALSE, main = \"Regenbogen\")\nimage(matrix(1:10, ncol = 1), col = grau(VIRIDIS10), axes = FALSE,\n      main = \"Viridis in Graustufen\")\nimage(matrix(1:10, ncol = 1), col = grau(REGEN10), axes = FALSE,\n      main = \"Regenbogen in Graustufen\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 3: beide Paletten in Farbe und als Graustufe.](farbe_files/figure-html/fig-b3-fa-r-3.png){#fig-b3-fa-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfor nm, pal in [(\"VIRIDIS10\", VIRIDIS10), (\"REGEN10\", REGEN10)]:\n    L = np.array([luminanz(h) for h in pal])\n    d = np.diff(L)\n    print(f\"{nm:<10} Luminanz \" + \" \".join(f\"{v:.3f}\" for v in L))\n    print(f\"           {'monoton steigend' if (d > 0).all() else 'NICHT monoton'},\"\n          f\" Richtungswechsel {int(np.sum(np.sign(d[:-1]) * np.sign(d[1:]) < 0))},\"\n          f\" Spanne {L.min():.3f} bis {L.max():.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVIRIDIS10  Luminanz 0.019 0.043 0.077 0.125 0.183 0.266 0.360 0.476 0.621 0.782\n           monoton steigend, Richtungswechsel 0, Spanne 0.019 bis 0.782\nREGEN10    Luminanz 0.213 0.440 0.844 0.722 0.725 0.787 0.167 0.079 0.201 0.236\n           NICHT monoton, Richtungswechsel 4, Spanne 0.079 bis 0.844\n```\n\n\n:::\n\n```{.python .cell-code}\nL = np.array([luminanz(h) for h in REGEN10])\nkoll = pd.DataFrame([{\"a\": i + 1, \"b\": j + 1, \"unterschied\": abs(L[i] - L[j])}\n                     for i, j in itertools.combinations(range(10), 2)])\nprint(koll.nsmallest(3, \"unterschied\").to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n a  b  unterschied\n 4  5     0.002555\n 1  9     0.012026\n 1 10     0.022999\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"paare_unter_0.02\": int((koll[\"unterschied\"] < 0.02).sum()),\n       \"paare\": len(koll)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'paare_unter_0.02': 2, 'paare': 45}\n```\n\n\n:::\n\n```{.python .cell-code}\ndef grau(farben):\n    return [str(luminanz(h) ** (1 / 2.2)) for h in farben]\n\n\nfig, achsen = plt.subplots(2, 2, figsize=(7, 3.4))\nfor achse, (titel, pal) in zip(achsen.ravel(),\n                               [(\"Viridis\", VIRIDIS10),\n                                (\"Regenbogen\", REGEN10),\n                                (\"Viridis in Graustufen\", grau(VIRIDIS10)),\n                                (\"Regenbogen in Graustufen\", grau(REGEN10))]):\n    for k, farbe in enumerate(pal):\n        _ = achse.bar(k, 1, width=1, color=farbe)\n    _ = achse.set_title(titel, fontsize=9)\n    _ = achse.axis(\"off\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselbe Gegenüberstellung in Python.](farbe_files/figure-html/fig-b3-fa-py-1.png){#fig-b3-fa-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Palette | Luminanz der zehn Stufen |\n|---|---|\n| **Viridis** | 0.019 · 0.043 · 0.077 · 0.125 · 0.183 · 0.266 · 0.360 · 0.476 · 0.621 · 0.782 |\n| **Regenbogen** | 0.213 · 0.440 · **0.844** · 0.722 · 0.725 · 0.787 · **0.167** · **0.079** · 0.201 · 0.236 |\n\n| Palette | monoton? | Richtungswechsel | Spanne |\n|---|---|---|---|\n| Viridis | **ja** | **0** | 0.019 bis 0.782 |\n| Regenbogen | **nein** | **4** | 0.079 bis 0.844 |\n\nDie engsten Graustufen-Paare im Regenbogen:\n\n| Stufen | Luminanzunterschied | Werte |\n|---|---|---|\n| 4 und 5 | **0.0026** | 0.722 / 0.725 |\n| 1 und 9 | 0.0120 | 0.213 / 0.201 |\n| 1 und 10 | 0.0230 | 0.213 / 0.236 |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Viridis steigt **durchgehend** | Zehn Stufen, kein Richtungswechsel. In Graustufen bleibt die Reihenfolge vollständig erhalten, der Farbverlauf ist Zierde, die Information steckt in der Helligkeit. |\n| Der Regenbogen wechselt **viermal** die Richtung | Er wird hell, dunkel, wieder hell. Eine Menge, die gleichmässig wächst, erscheint darin als Auf und Ab. |\n| Die Stufen **4 und 5** trennen 0.0026 Luminanz | Das ist in Graustufen dieselbe Farbe. Zwei verschiedene Werte, ein Grauton. |\n| **Stufe 1 und 9** sind fast gleich hell | 0.213 gegen 0.201, also Rot und Violett, die beiden **Enden** der Skala. Wer die Grafik in Graustufen sieht, hält Minimum und Maximum für denselben Wert. |\n| Das hellste Feld liegt in der **Mitte** | Stufe 3 mit 0.844, Gelb. Ein Regenbogen hat seinen Helligkeitsgipfel dort, wo inhaltlich nichts Besonderes ist und erzeugt so eine Grenze, die in den Daten nicht existiert. |\n\n::: {.warning-box}\n**Warum Regenbogenpaletten trotzdem überall sind:** Sie sehen bunt und\n\"vollständig\" aus, und sie waren jahrzehntelang die Voreinstellung. Ihre drei\nProbleme sind aber alle messbar:\n\n| Problem | Messung auf dieser Seite |\n|---|---|\n| nicht monoton in der Helligkeit | 4 Richtungswechsel |\n| erzeugt scheinbare Grenzen | Helligkeitsgipfel bei Gelb, Stufe 3 von 10 |\n| Enden sehen gleich aus | Stufe 1 und 9 unterscheiden sich um 0.012 Luminanz |\n\nViridis, Cividis, Magma und Inferno sind gegen alle drei gebaut. In R über\n`hcl.colors(n, \"Viridis\")`, in Python über `cmap=\"viridis\"`.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Viridis steigt über zehn Stufen monoton von einer Luminanz 0.019 auf 0.782\n> ohne Richtungswechsel. Die Regenbogenpalette wechselt viermal die Richtung;\n> ihre Stufen 4 und 5 unterscheiden sich um 0.0026 Luminanz und ihre Stufen 1\n> und 9, die beiden Enden, um 0.0120.\n\n### Beispiel 4: Was bei Rot-Grün-Schwäche übrig bleibt\n\n#### Frage und Datenlage\n\nDrei Farbpaare, jedes für sich gut unterscheidbar. Simuliert wird Deuteranopie\nüber die Transformation im LMS-Raum, danach wird derselbe Lab-Abstand noch\neinmal gemessen.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npaare <- list(c(\"#D62728\", \"#2CA02C\", \"rot / gruen\"),\n              c(\"#E69F00\", \"#56B4E9\", \"Okabe orange / himmelblau\"),\n              c(\"#009E73\", \"#D55E00\", \"Okabe gruen / zinnober\"))\n\nfor (p in paare) {\n  cat(sprintf(\"%-28s normal %6.1f   deuteranop %6.1f\\n\",\n              p[3], abstand(p[1], p[2]), abstand_deuteranop(p[1], p[2])))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrot / gruen                  normal  119.8   deuteranop    8.2\nOkabe orange / himmelblau    normal  113.1   deuteranop  116.2\nOkabe gruen / zinnober       normal  102.4   deuteranop   53.1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Ganze Paletten im Vergleich\nvergleich <- function(farben) {\n  idx <- t(combn(length(farben), 2))\n  d <- apply(idx, 1, function(p) abstand_deuteranop(farben[p[1]], farben[p[2]]))\n  c(minimum = min(d), paare_unter_10 = sum(d < 10), paare = length(d))\n}\nround(rbind(Okabe = vergleich(OKABE), Regenbogen12 = vergleich(REGEN12)), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             minimum paare_unter_10 paare\nOkabe           17.2              0    28\nRegenbogen12     4.9              1    66\n```\n\n\n:::\n\n```{.r .cell-code}\nals_hex <- function(h) {\n  v <- deuteranop(h)\n  rgb(v[1]^(1 / 2.2), v[2]^(1 / 2.2), v[3]^(1 / 2.2))\n}\npar(mfrow = c(2, 1), mar = c(1, 1, 2.5, 1))\nimage(matrix(1:8, ncol = 1), col = OKABE, axes = FALSE, main = \"Okabe-Ito normal\")\nimage(matrix(1:8, ncol = 1), col = sapply(OKABE, als_hex), axes = FALSE,\n      main = \"Okabe-Ito bei Deuteranopie\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 4: oben die Originalfarben, unten wie sie bei Deuteranopie erscheinen.](farbe_files/figure-html/fig-b4-fa-r-3.png){#fig-b4-fa-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\npaare = [(\"#D62728\", \"#2CA02C\", \"rot / gruen\"),\n         (\"#E69F00\", \"#56B4E9\", \"Okabe orange / himmelblau\"),\n         (\"#009E73\", \"#D55E00\", \"Okabe gruen / zinnober\")]\n\nfor a, b, name in paare:\n    print(f\"{name:<28} normal {abstand(a, b):6.1f}\"\n          f\"   deuteranop {abstand_deuteranop(a, b):6.1f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrot / gruen                  normal  119.8   deuteranop    8.2\nOkabe orange / himmelblau    normal  113.1   deuteranop  116.2\nOkabe gruen / zinnober       normal  102.4   deuteranop   53.1\n```\n\n\n:::\n\n```{.python .cell-code}\ndef vergleich(farben):\n    d = [abstand_deuteranop(farben[i], farben[j])\n         for i, j in itertools.combinations(range(len(farben)), 2)]\n    return {\"minimum\": min(d), \"paare_unter_10\": sum(1 for x in d if x < 10),\n            \"paare\": len(d)}\n\n\nprint(pd.DataFrame({\"Okabe\": vergleich(OKABE),\n                    \"Regenbogen12\": vergleich(REGEN12)}).round(1).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              minimum  paare_unter_10  paare\nOkabe            17.2             0.0   28.0\nRegenbogen12      4.9             1.0   66.0\n```\n\n\n:::\n\n```{.python .cell-code}\ndef als_hex(h):\n    v = deuteranop(h) ** (1 / 2.2)\n    return \"#%02X%02X%02X\" % tuple(int(round(x * 255)) for x in v)\n\n\nfig, achsen = plt.subplots(2, 1, figsize=(7, 3))\nfor achse, (titel, pal) in zip(achsen,\n                               [(\"Okabe-Ito normal\", OKABE),\n                                (\"Okabe-Ito bei Deuteranopie\",\n                                 [als_hex(h) for h in OKABE])]):\n    for k, farbe in enumerate(pal):\n        _ = achse.bar(k, 1, width=1, color=farbe)\n    _ = achse.set_title(titel, fontsize=10)\n    _ = achse.axis(\"off\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselbe Simulation in Python.](farbe_files/figure-html/fig-b4-fa-py-1.png){#fig-b4-fa-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Farbpaar | ΔE normal | ΔE bei Deuteranopie |\n|---|---|---|\n| **rot / grün** (matplotlib-Standardfarben) | **119.8** | **8.2** |\n| Okabe orange / himmelblau | 113.1 | **116.2** |\n| Okabe grün / zinnober | 102.4 | **53.1** |\n\n| Palette | kleinster Abstand bei Deuteranopie | Paare unter ΔE 10 |\n|---|---|---|\n| **Okabe-Ito** (28 Paare) | **17.2** | **0** |\n| **Regenbogen 12** (66 Paare) | **4.9** | **1** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Rot und Grün fallen von **119.8 auf 8.2** | Ein Abstand unter 10 heisst: nur bei direkt aneinandergrenzenden Flächen erkennbar. In einer Grafik mit getrennten Linien sind die beiden Serien nicht mehr auseinanderzuhalten. |\n| Das sind die **Standardfarben** vieler Werkzeuge | `#D62728` und `#2CA02C` sind Farbe 4 und 3 der matplotlib-Standardpalette. Wer nichts einstellt, bekommt genau dieses Paar. |\n| Okabe orange / himmelblau bleibt bei **116** | Praktisch unverändert. Die Palette ist so entworfen, dass sie sich in der Blau-Gelb-Richtung unterscheidet, die von der Rot-Grün-Schwäche nicht betroffen ist. |\n| Okabe grün / zinnober **halbiert** sich auf 53.1 | Auch die geprüfte Palette verliert Abstand, aber sie bleibt weit über der Erkennbarkeitsschwelle. |\n| Über die ganze Palette: **kein einziges** Okabe-Paar unter ΔE 10 | Gegen ein Paar beim Regenbogen mit zwölf Farben, dessen kleinster Abstand auf 4.9 fällt. |\n\n::: {.warning-box}\n**Was daraus folgt, ist nicht \"keine roten und grünen Farben mehr\".** Rot und\nGrün dürfen vorkommen, sie dürfen nur nicht **allein** die Unterscheidung\ntragen.\n\n| Situation | Lösung |\n|---|---|\n| zwei Linien | verschiedene Linienarten plus direkte Beschriftung |\n| Ampelfarben in einer Tabelle | zusätzlich ein Symbol (▲ ▼) oder Text |\n| Kategorien in einem Streudiagramm | zusätzlich die Punktform |\n| Verlauf | Viridis statt Rot-Grün-Skala |\n\nDie Prüfung kostet wenig: Diese zehn Zeilen Code auf die eigene Palette\nanwenden und schauen, ob ein Paar unter ΔE 10 fällt.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Unter simulierter Deuteranopie fällt der Lab-Abstand zwischen dem\n> Standard-Rot und -Grün von 119.8 auf 8.2 und damit unter die\n> Erkennbarkeitsschwelle. Die Okabe-Ito-Palette behält über alle 28 Paare\n> mindestens 17.2, während eine Regenbogenpalette mit zwölf Farben auf 4.9\n> fällt.\n\n### Beispiel 5: Kontrast ist nachrechenbar\n\n#### Frage und Datenlage\n\nWelche der verwendeten Farben taugen für **Text**, welche nur für Flächen? Das\nKontrastverhältnis nach WCAG beantwortet das mit einer Zahl: mindestens 4.5 zu 1\nfür normalen Text, 3 zu 1 für grosse Schrift.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfarben <- c(Akzentrot = akzent, \"Grau hell\" = \"#c7c7c7\", \"Grau mittel\" = \"#767676\",\n            \"Okabe gelb\" = \"#F0E442\", \"Okabe blau\" = \"#0072B2\",\n            \"Okabe himmelblau\" = \"#56B4E9\", Schwarz = \"#000000\")\n\nurteil <- function(k) {\n  if (k >= 4.5) \"Text ok\" else if (k >= 3) \"nur grosse Schrift\" else \"nur Fläche\"\n}\nfor (nm in names(farben)) {\n  k <- kontrast(farben[[nm]], \"#FFFFFF\")\n  cat(sprintf(\"%-18s %5.2f : 1   %s\\n\", nm, k, urteil(k)))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAkzentrot           6.87 : 1   Text ok\nGrau hell           1.69 : 1   nur Fläche\nGrau mittel         4.54 : 1   Text ok\nOkabe gelb          1.32 : 1   nur Fläche\nOkabe blau          5.19 : 1   Text ok\nOkabe himmelblau    2.31 : 1   nur Fläche\nSchwarz            21.00 : 1   Text ok\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(akzent_auf_hellgrau = kontrast(akzent, \"#c7c7c7\"),\n        akzent_auf_mittelgrau = kontrast(akzent, \"#767676\")), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  akzent_auf_hellgrau akzent_auf_mittelgrau \n                 4.06                  1.51 \n```\n\n\n:::\n\n```{.r .cell-code}\npar(mar = c(1, 1, 2, 1))\nplot(NA, xlim = c(0, 10), ylim = c(0, 8), axes = FALSE, xlab = \"\", ylab = \"\",\n     main = \"Textfarben auf weissem Grund\")\nfor (i in seq_along(farben)) {\n  k <- kontrast(farben[[i]], \"#FFFFFF\")\n  text(1, 8 - i, sprintf(\"%s, Kontrast %.2f : 1\", names(farben)[i], k),\n       col = farben[[i]], adj = 0, cex = 1.1)\n}\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselben Farben als Textfarbe auf Weiss.](farbe_files/figure-html/fig-b5-fa-r-3.png){#fig-b5-fa-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfarben = {\"Akzentrot\": AKZENT, \"Grau hell\": \"#c7c7c7\", \"Grau mittel\": \"#767676\",\n          \"Okabe gelb\": \"#F0E442\", \"Okabe blau\": \"#0072B2\",\n          \"Okabe himmelblau\": \"#56B4E9\", \"Schwarz\": \"#000000\"}\n\n\ndef urteil(k):\n    if k >= 4.5:\n        return \"Text ok\"\n    return \"nur grosse Schrift\" if k >= 3 else \"nur Fläche\"\n\n\nfor nm, h in farben.items():\n    k = kontrast(h, \"#FFFFFF\")\n    print(f\"{nm:<18} {k:5.2f} : 1   {urteil(k)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAkzentrot           6.87 : 1   Text ok\nGrau hell           1.69 : 1   nur Fläche\nGrau mittel         4.54 : 1   Text ok\nOkabe gelb          1.32 : 1   nur Fläche\nOkabe blau          5.19 : 1   Text ok\nOkabe himmelblau    2.31 : 1   nur Fläche\nSchwarz            21.00 : 1   Text ok\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"akzent_auf_hellgrau\": round(kontrast(AKZENT, \"#c7c7c7\"), 2),\n       \"akzent_auf_mittelgrau\": round(kontrast(AKZENT, \"#767676\"), 2)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'akzent_auf_hellgrau': 4.06, 'akzent_auf_mittelgrau': 1.51}\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achse = plt.subplots(figsize=(7, 3))\nfor i, (nm, h) in enumerate(farben.items()):\n    k = kontrast(h, \"#FFFFFF\")\n    _ = achse.text(0.02, 0.92 - i * 0.13, f\"{nm}, Kontrast {k:.2f} : 1\",\n                   color=h, fontsize=11, transform=achse.transAxes)\n_ = achse.set_title(\"Textfarben auf weissem Grund\")\n_ = achse.axis(\"off\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselbe Darstellung in Python.](farbe_files/figure-html/fig-b5-fa-py-1.png){#fig-b5-fa-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Farbe | Kontrast gegen Weiss | Urteil |\n|---|---|---|\n| Schwarz | **21.00 : 1** | Text ok |\n| Akzentrot `#b2182b` | **6.87 : 1** | Text ok |\n| Okabe blau `#0072B2` | **5.19 : 1** | Text ok |\n| Grau mittel `#767676` | **4.54 : 1** | Text ok, knapp |\n| Okabe himmelblau `#56B4E9` | **2.31 : 1** | nur Fläche |\n| Grau hell `#c7c7c7` | **1.69 : 1** | nur Fläche |\n| Okabe gelb `#F0E442` | **1.32 : 1** | nur Fläche |\n\n| Kombination | Kontrast |\n|---|---|\n| Akzentrot auf hellem Grau `#c7c7c7` | **4.06 : 1** |\n| Akzentrot auf mittlerem Grau `#767676` | **1.51 : 1** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| **Okabe gelb** erreicht nur 1.32 zu 1 | Als Balkenfläche gut, als Beschriftung unlesbar. Eine Palette für Flächen ist **keine** Palette für Text. |\n| Das mittlere Grau liegt mit **4.54** knapp über der Schwelle | `#767676` ist das hellste Grau, das noch als Text durchgeht. Alles Hellere gehört in Flächen oder Hilfslinien. |\n| Das Akzentrot **taugt für beides** | 6.87 zu 1 gegen Weiss. Deshalb funktioniert es sowohl für einen hervorgehobenen Balken als auch für die zugehörige Beschriftung. |\n| Akzentrot auf mittlerem Grau ist mit **1.51** unbrauchbar | Der Kontrast gilt immer gegen den **tatsächlichen** Hintergrund. Eine Farbe, die auf Weiss funktioniert, kann auf grauem Grund verschwinden. |\n| Die Schwelle 4.5 ist keine Geschmacksfrage | Sie stammt aus den WCAG-Richtlinien und ist der Wert, ab dem Text auch bei eingeschränktem Sehvermögen lesbar bleibt. |\n\n::: {.note-box}\n**Die Formel steht in drei Zeilen:** relative Luminanz beider Farben bestimmen,\nheller und dunkler sortieren, dann\n\n$$\\text{Kontrast} = \\frac{L_{\\text{hell}} + 0.05}{L_{\\text{dunkel}} + 0.05}$$\n\nDer Wertebereich reicht von 1 zu 1 (identisch) bis 21 zu 1 (Schwarz auf Weiss).\n\n| Verwendung | Mindestkontrast |\n|---|---|\n| normaler Text | 4.5 : 1 |\n| grosse Schrift ab etwa 18 pt | 3 : 1 |\n| Bedienelemente, Diagrammlinien | 3 : 1 |\n| reine Dekoration | keine Anforderung |\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Von den sieben geprüften Farben erreichen vier den für Text nötigen Kontrast\n> von 4.5 zu 1 gegen Weiss; Okabe gelb liegt mit 1.32 zu 1 weit darunter und\n> taugt nur für Flächen. Das Akzentrot erreicht 6.87 zu 1 gegen Weiss, aber nur\n> 1.51 zu 1 gegen mittleres Grau, der Kontrast gilt immer gegen den\n> tatsächlichen Hintergrund.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEine Karte färbt Kantone nach Produktgruppe mit einer Verlaufsfarbskala von\nHellblau bis Dunkelblau. Was stimmt daran nicht?\n\n- [x] Ein Verlauf behauptet eine Reihenfolge, die es bei Produktgruppen nicht\n      gibt ~ Richtig. Nominale Kategorien brauchen eine qualitative Palette;\n      der Verlauf legt nahe, dass dunkleres Blau \"mehr\" bedeutet.\n- [ ] Blau ist für Karten ungeeignet ~ Die Farbwahl selbst ist unproblematisch,\n      der Palettentyp ist es nicht.\n- [ ] Es fehlt eine Legende ~ Auch mit Legende bliebe die falsche Suggestion.\n:::\n\n::: {.quiz}\nWoran misst man, ob eine Kategorienpalette genug Farben hergibt?\n\n- [x] Am kleinsten paarweisen Abstand im Lab-Raum ~ Richtig. Am engsten Paar\n      scheitert die Zuordnung. Okabe-Ito hält bei acht Farben mindestens\n      ΔE 26.4, eine Regenbogenpalette mit zwölf fällt auf 17.4.\n- [ ] Am durchschnittlichen Abstand ~ Ein hoher Durchschnitt nützt nichts, wenn\n      ein einzelnes Paar ununterscheidbar ist.\n- [ ] An der Zahl der Farben allein ~ Entscheidend ist, wie weit sie\n      auseinanderliegen, nicht wie viele es sind.\n:::\n\n::: {.quiz}\nWarum taugt eine Regenbogenpalette nicht für eine kontinuierliche Grösse?\n\n- [x] Ihre Helligkeit ist nicht monoton, sie wechselt viermal die Richtung ~\n      Richtig. Der Helligkeitsgipfel liegt bei Gelb in der Mitte und erzeugt\n      dort eine Grenze, die in den Daten nicht existiert. Zusätzlich sind die\n      Stufen 1 und 9 fast gleich hell.\n- [ ] Weil sie zu bunt aussieht ~ Das ist Geschmack; die Probleme sind\n      messbar.\n- [ ] Weil sie zu wenige Stufen hat ~ Die Zahl der Stufen ist frei wählbar und\n      nicht das Problem.\n:::\n\n::: {.quiz}\nDer Lab-Abstand zwischen dem Standard-Rot und -Grün fällt unter simulierter\nDeuteranopie von 119.8 auf 8.2. Was folgt daraus?\n\n- [x] Farbe darf nicht der einzige Unterscheidungskanal sein ~ Richtig. Ein\n      Abstand unter 10 ist nur bei aneinandergrenzenden Flächen erkennbar.\n      Zusätzlich braucht es Linienart, Form oder direkte Beschriftung.\n- [ ] Rot und Grün dürfen nie zusammen vorkommen ~ Sie dürfen, solange ein\n      zweiter Kanal die Unterscheidung trägt.\n- [ ] Man sollte grundsätzlich in Graustufen arbeiten ~ Das wäre eine\n      Überreaktion; geprüfte Paletten wie Okabe-Ito bleiben auch unter\n      Deuteranopie über ΔE 17.\n:::\n\n::: {.quiz}\nOkabe gelb hat gegen Weiss einen Kontrast von 1.32 zu 1. Was heisst das?\n\n- [x] Als Fläche brauchbar, als Textfarbe unlesbar ~ Richtig. Für Text\n      verlangen die WCAG-Richtlinien mindestens 4.5 zu 1. Eine Palette für\n      Flächen ist keine Palette für Beschriftungen.\n- [ ] Die Farbe ist grundsätzlich unbrauchbar ~ Als Balkenfläche mit\n      danebenstehender schwarzer Beschriftung funktioniert sie gut.\n- [ ] Der Wert ist zu klein, also ist der Kontrast hoch ~ Umgekehrt: 1 zu 1\n      heisst identisch, 21 zu 1 ist Schwarz auf Weiss.\n:::\n\n::: {.quiz}\nDas Akzentrot erreicht 6.87 zu 1 gegen Weiss, aber nur 1.51 zu 1 gegen\nmittleres Grau. Was ist die Lehre?\n\n- [x] Kontrast gilt immer gegen den tatsächlichen Hintergrund ~ Richtig. Eine\n      Farbe ist nicht für sich lesbar oder unlesbar, sondern nur im Paar. Wer\n      den Hintergrund ändert, muss neu rechnen.\n- [ ] Das Akzentrot ist schlecht gewählt ~ Gegen Weiss ist es gut geeignet;\n      auf mittelgrauem Grund wäre jede mittelhelle Farbe problematisch.\n- [ ] Graue Hintergründe sind zu vermeiden ~ Sie sind brauchbar, solange die\n      Vordergrundfarben dazu passend gewählt werden.\n:::\n\n## Verlinkte Ressourcen\n\n- [Claus Wilke: Color basics](https://clauswilke.com/dataviz/color-basics.html)\n- [ColorBrewer: Paletten nach Aufgabe](https://colorbrewer2.org/)\n- [Viridis: Farbverläufe für alle Sehtypen](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html)\n- [Okabe-Ito-Palette](https://jfly.uni-koeln.de/color/)\n- [WCAG: Kontrastanforderungen](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html)\n- [Wahrnehmung und Kodierung](wahrnehmung-kodierung.qmd), warum Farbton keine Mengen kodiert\n",
    "supporting": [
      "farbe_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}