{
  "hash": "5e9889be126e39a48611d1c4050cbbee",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Normalverteilung und zentraler Grenzwertsatz\"\ndescription: \"Warum so viele Verfahren auf der Normalverteilung aufbauen.\"\ncategories: [\"Verteilungen\", \"Wahrscheinlichkeit\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"ESDS\"]\nseitentyp: konzept\nstand: entwurf\norder: 60\n---\n\n\n\n\n\n## Kernideen\n\n- Der **zentrale Grenzwertsatz** erklärt die Sonderrolle der Normalverteilung:\n  Mittelwerte vieler unabhängiger Einflüsse werden normal, ganz gleich wie die\n  Einzelwerte verteilt sind.\n- **Nicht die Daten** müssen normalverteilt sein, sondern die **Schätzung**.\n- Wie schnell die Annäherung gelingt, hängt von der **Schiefe** der\n  Ausgangsverteilung ab — die Faustregel \"$n > 30$\" ist keine Konstante.\n- Die Streuung des Mittelwerts sinkt mit $\\sigma/\\sqrt{n}$, nicht mit $\\sigma/n$.\n- **Standardisierung** übersetzt jeden Wert in Standardabweichungen und macht\n  Verteilungen vergleichbar.\n- Die Faustregeln 68, 95 und 99.7 Prozent gelten **nur** für die\n  Normalverteilung.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [stetige Verteilungen](stetige-verteilungen.qmd) für Dichte und\nVerteilungsfunktion. Diese Seite ist die Grundlage für\n[Konfidenzintervalle](../inferenz/schaetzen-konfidenzintervalle.qmd) und alle\nVerfahren, die auf Mittelwerten beruhen. Wie sich Normalität grafisch prüfen\nlässt, steht unter [QQ-Plots](qq-plots.qmd).\n:::\n\n### Der zentrale Grenzwertsatz\n\nSummen und Mittelwerte vieler unabhängiger Einflüsse nähern sich einer\nNormalverteilung an, unabhängig davon, wie die einzelnen Grössen selbst\nverteilt sind. Genauer:\n\n$$\\bar{X}_n \\approx \\mathcal{N}\\!\\left(\\mu,\\ \\frac{\\sigma^2}{n}\\right)\n\\quad \\text{für grosses } n$$\n\nDrei Aussagen stecken darin, und alle drei werden gebraucht:\n\n| Aussage | Bedeutung |\n|---|---|\n| die **Form** wird normal | unabhängig von der Ausgangsverteilung |\n| der **Erwartungswert** bleibt $\\mu$ | der Mittelwert ist erwartungstreu |\n| die **Streuung** wird $\\sigma/\\sqrt{n}$ | der Standardfehler |\n\n::: {.note-box}\nEin häufiges Missverständnis: Der Satz sagt nichts darüber, dass die\n**Ausgangsdaten** normalverteilt würden. Normal wird die Verteilung der\n**Mittelwerte**, und zwar über gedachte Wiederholungen der Stichprobenziehung.\n\nDeshalb lautet die Voraussetzung vieler Verfahren nicht \"die Daten sind\nnormalverteilt\", sondern \"die Schätzung ist annähernd normalverteilt\" — und die\nzweite Bedingung ist viel leichter erfüllt als die erste.\n:::\n\n### Voraussetzungen, die man kennen muss\n\nDer Satz gilt nicht immer:\n\n| Voraussetzung | Was passiert ohne sie |\n|---|---|\n| **unabhängige** Beobachtungen | Bei Abhängigkeit sinkt die effektive Stichprobengrösse; der Standardfehler ist zu klein. |\n| **endliche Varianz** | Bei Verteilungen ohne endliche Varianz (Cauchy) gilt der Satz nicht — der Mittelwert wird nicht genauer. |\n| **genügend grosses** $n$ | Wie gross, hängt von der Schiefe ab. Bei symmetrischen Verteilungen genügen wenige Beobachtungen, bei stark schiefen braucht es hunderte. |\n\n### Standardisierung und z-Werte\n\nVerschiedene Merkmale haben verschiedene Einheiten und Grössenordnungen. Die\nStandardisierung übersetzt jeden Wert in die Anzahl Standardabweichungen, um\ndie er vom Mittel abweicht:\n\n$$z = \\frac{x - \\mu}{\\sigma}$$\n\nDanach hat jede Verteilung den Erwartungswert 0 und die Standardabweichung 1.\nDie Form ändert sich dabei **nicht** — eine schiefe Verteilung bleibt schief.\n\n### Die Faustregeln\n\n| Bereich | Anteil bei Normalverteilung |\n|---|---|\n| $\\mu \\pm 1\\sigma$ | 68.3 % |\n| $\\mu \\pm 2\\sigma$ | 95.4 % |\n| $\\mu \\pm 3\\sigma$ | 99.7 % |\n\nDiese Zahlen sind **Eigenschaften der Normalverteilung**, keine allgemeinen\nRegeln. Beispiel 4 zeigt, wie weit sie bei anderen Verteilungen danebenliegen.\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Der Satz in Aktion\n\n#### Frage und Datenlage\n\nEine Exponentialverteilung ist stark rechtsschief — so unnormal wie möglich.\nWas passiert mit den Mittelwerten, wenn man je 1, 2, 5 und 30 solcher Werte\nmittelt? Je 4 000 Wiederholungen.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 4), mar = c(4, 4, 3, 1))\nfor (n in c(1, 2, 5, 30)) {\n  m <- rowMeans(matrix(exp_werte(1010 + n, B * n), nrow = B, byrow = TRUE))\n  hist(m, breaks = 40, col = \"grey75\", border = \"white\",\n       main = paste(\"n =\", n), xlab = \"Mittelwert\")\n}\npar(mfrow = c(1, 1))\n\nfor (n in c(1, 2, 5, 30)) {\n  m <- rowMeans(matrix(exp_werte(1010 + n, B * n), nrow = B, byrow = TRUE))\n  cat(sprintf(\"n = %2d | Mittel %.4f | SD %.4f | erwartet %.4f | Schiefe %.4f\\n\",\n              n, mean(m), sd(m), 1 / sqrt(n), schiefe(m)))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn =  1 | Mittel 1.0080 | SD 0.9907 | erwartet 1.0000 | Schiefe 1.9242\nn =  2 | Mittel 1.0027 | SD 0.7266 | erwartet 0.7071 | Schiefe 1.4500\nn =  5 | Mittel 0.9966 | SD 0.4428 | erwartet 0.4472 | Schiefe 0.7792\nn = 30 | Mittel 1.0040 | SD 0.1837 | erwartet 0.1826 | Schiefe 0.3082\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 1: von der schiefen Ausgangsverteilung zur Glocke, in vier Schritten.](normalverteilung-zgws_files/figure-html/fig-b1-zgws-r-1.png){#fig-b1-zgws-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(1, 4, figsize=(7, 3.6))\nfor achse, n in zip(achsen, [1, 2, 5, 30]):\n    m = exp_werte(1010 + n, B * n).reshape(B, n).mean(axis=1)\n    achse.hist(m, bins=40, color=\"0.75\", edgecolor=\"white\")\n    achse.set_title(f\"n = {n}\")\n    achse.set_xlabel(\"Mittelwert\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselben vier Schritte in Python.](normalverteilung-zgws_files/figure-html/fig-b1-zgws-py-1.png){#fig-b1-zgws-py width=100%}\n:::\n\n```{.python .cell-code}\nfor n in [1, 2, 5, 30]:\n    m = exp_werte(1010 + n, B * n).reshape(B, n).mean(axis=1)\n    print(f\"n = {n:2d} | Mittel {m.mean():.4f} | SD {m.std(ddof=1):.4f}\"\n          f\" | erwartet {1 / np.sqrt(n):.4f} | Schiefe {stats.skew(m):.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn =  1 | Mittel 1.0080 | SD 0.9907 | erwartet 1.0000 | Schiefe 1.9242\nn =  2 | Mittel 1.0027 | SD 0.7266 | erwartet 0.7071 | Schiefe 1.4500\nn =  5 | Mittel 0.9966 | SD 0.4428 | erwartet 0.4472 | Schiefe 0.7792\nn = 30 | Mittel 1.0040 | SD 0.1837 | erwartet 0.1826 | Schiefe 0.3082\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| n | Mittelwert | Streuung | erwartet $1/\\sqrt{n}$ | **Schiefe** | theoretisch $2/\\sqrt{n}$ |\n|---|---|---|---|---|---|\n| **1** | 1.0080 | 0.9907 | 1.0000 | **1.924** | 2.000 |\n| 2 | 1.0027 | 0.7266 | 0.7071 | **1.450** | 1.414 |\n| 5 | 0.9966 | 0.4428 | 0.4472 | **0.779** | 0.894 |\n| **30** | 1.0040 | 0.1837 | 0.1826 | **0.308** | 0.365 |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Der **Mittelwert** bleibt bei 1.00 | Bei jedem n. Der Mittelwert ist erwartungstreu — Mitteln verschiebt nichts. |\n| Die **Streuung** folgt $1/\\sqrt{n}$ | 0.99, 0.73, 0.44, 0.18 gegen 1.00, 0.71, 0.45, 0.18. Die Übereinstimmung ist der ganze zweite Teil des Satzes. |\n| Die **Schiefe** halbiert sich bei Vervierfachung von n | 1.92 → 0.78 von n=1 auf n=5, also $\\sqrt{5}$-fach kleiner. Theoretisch gilt exakt $2/\\sqrt{n}$, und die Messwerte treffen das. |\n| Bei n = 30 ist die Schiefe **0.31** | Werte unter etwa 0.5 gelten als \"annähernd symmetrisch\". Der Weg von 1.92 dorthin ist genau das, was der Satz behauptet. |\n| Die Bilder zeigen es unmittelbar | Bei n=1 ein abfallender Keil, bei n=30 eine Glocke mit leichter Rechtsschiefe. |\n\n::: {.note-box}\n**Die Schiefe ist die richtige Kennzahl, um den Satz zu beobachten** — besser als\ndas blosse Ansehen der Histogramme. Sie ist null bei symmetrischen Verteilungen\nund misst genau das, was beim Mitteln verschwindet.\n\nDie Formel $\\text{Schiefe}(\\bar{X}_n) = \\text{Schiefe}(X)/\\sqrt{n}$ gilt allgemein.\nSie ist auch die Antwort auf die Frage \"wie gross muss n sein\": so gross, dass die\nAusgangsschiefe geteilt durch $\\sqrt{n}$ klein genug ist. Beispiel 2 rechnet das\nfür drei Ausgangsverteilungen durch.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Mittelwerte aus je 30 exponentialverteilten Werten sind annähernd\n> normalverteilt (Schiefe 0.31 gegenüber 1.92 bei den Einzelwerten). Die\n> Streuung sinkt wie erwartet mit $1/\\sqrt{n}$ von 0.99 auf 0.18.\n\n### Beispiel 2: Wie gross muss n sein?\n\n#### Frage und Datenlage\n\nDie Faustregel \"$n > 30$\" steht in jedem Lehrbuch. Drei Ausgangsverteilungen\nzeigen, dass sie keine Konstante ist:\n\n| Verteilung | Schiefe | Beispiel |\n|---|---|---|\n| **gleichverteilt** | 0 | Messfehler mit fester Toleranz |\n| **exponential** | 2.0 | Wartezeiten, Lebensdauern |\n| **binär mit $p = 0.05$** | 4.1 | seltenes Ereignis, etwa eine Reklamationsquote |\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmittelwerte <- function(erzeuger, n, saat) {\n  rowMeans(matrix(erzeuger(saat, B * n), nrow = B, byrow = TRUE))\n}\n\ngleich <- function(saat, anzahl) 25 + 50 * lehmer(saat, anzahl)\nselten <- function(saat, anzahl) as.numeric(lehmer(saat, anzahl) < 0.05)\n\npar(mfrow = c(1, 3), mar = c(4, 4, 3, 1))\nhist(mittelwerte(gleich, 30, 2021), breaks = 40, col = \"grey75\",\n     border = \"white\", main = \"gleichverteilt, n = 30\", xlab = \"Mittelwert\")\nhist(mittelwerte(exp_werte, 30, 4070), breaks = 40, col = \"grey75\",\n     border = \"white\", main = \"exponential, n = 30\", xlab = \"Mittelwert\")\nhist(mittelwerte(selten, 30, 3060), breaks = 40, col = \"grey75\",\n     border = \"white\", main = \"binär p = 0.05, n = 30\", xlab = \"Anteil\")\npar(mfrow = c(1, 1))\n\ncat(\"gleichverteilt, n =  5 : Schiefe\",\n    round(schiefe(mittelwerte(gleich, 5, 2021)), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngleichverteilt, n =  5 : Schiefe -0.0148 \n```\n\n\n:::\n\n```{.r .cell-code}\nfor (n in c(5, 30)) {\n  cat(sprintf(\"exponential,   n = %2d : Schiefe %.4f (theoretisch %.4f)\\n\",\n              n, schiefe(mittelwerte(exp_werte, n, 4040 + n)), 2 / sqrt(n)))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nexponential,   n =  5 : Schiefe 0.8722 (theoretisch 0.8944)\nexponential,   n = 30 : Schiefe 0.3539 (theoretisch 0.3651)\n```\n\n\n:::\n\n```{.r .cell-code}\nfor (n in c(5, 30, 100)) {\n  cat(sprintf(\"binär p=0.05,  n = %3d : Schiefe %.4f | n*p = %.2f\\n\",\n              n, schiefe(mittelwerte(selten, n, 3030 + n)), 0.05 * n))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbinär p=0.05,  n =   5 : Schiefe 1.8191 | n*p = 0.25\nbinär p=0.05,  n =  30 : Schiefe 0.7373 | n*p = 1.50\nbinär p=0.05,  n = 100 : Schiefe 0.4234 | n*p = 5.00\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 2: Mittelwerte aus je 30 Werten, drei Ausgangsverteilungen.](normalverteilung-zgws_files/figure-html/fig-b2-zgws-r-3.png){#fig-b2-zgws-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndef mittelwerte(erzeuger, n, saat):\n    return erzeuger(saat, B * n).reshape(B, n).mean(axis=1)\n\n\ndef gleich(saat, anzahl):\n    return 25 + 50 * lehmer(saat, anzahl)\n\n\ndef selten(saat, anzahl):\n    return (lehmer(saat, anzahl) < 0.05).astype(float)\n\n\nfig, achsen = plt.subplots(1, 3, figsize=(7, 3.2))\nfor achse, (erz, saat, titel, xlabel) in zip(achsen, [\n        (gleich, 2021, \"gleichverteilt, n = 30\", \"Mittelwert\"),\n        (exp_werte, 4070, \"exponential, n = 30\", \"Mittelwert\"),\n        (selten, 3060, \"binär p = 0.05, n = 30\", \"Anteil\")]):\n    achse.hist(mittelwerte(erz, 30, saat), bins=40, color=\"0.75\",\n               edgecolor=\"white\")\n    achse.set_title(titel, fontsize=9)\n    achse.set_xlabel(xlabel)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselbe Gegenüberstellung in Python.](normalverteilung-zgws_files/figure-html/fig-b2-zgws-py-1.png){#fig-b2-zgws-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(\"gleichverteilt, n =  5 : Schiefe\",\n      round(float(stats.skew(mittelwerte(gleich, 5, 2021))), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngleichverteilt, n =  5 : Schiefe -0.0148\n```\n\n\n:::\n\n```{.python .cell-code}\nfor n in [5, 30]:\n    s = stats.skew(mittelwerte(exp_werte, n, 4040 + n))\n    print(f\"exponential,   n = {n:2d} : Schiefe {s:.4f}\"\n          f\" (theoretisch {2 / np.sqrt(n):.4f})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nexponential,   n =  5 : Schiefe 0.8722 (theoretisch 0.8944)\nexponential,   n = 30 : Schiefe 0.3539 (theoretisch 0.3651)\n```\n\n\n:::\n\n```{.python .cell-code}\nfor n in [5, 30, 100]:\n    s = stats.skew(mittelwerte(selten, n, 3030 + n))\n    print(f\"binär p=0.05,  n = {n:3d} : Schiefe {s:.4f} | n*p = {0.05 * n:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbinär p=0.05,  n =   5 : Schiefe 1.8191 | n*p = 0.25\nbinär p=0.05,  n =  30 : Schiefe 0.7373 | n*p = 1.50\nbinär p=0.05,  n = 100 : Schiefe 0.4234 | n*p = 5.00\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgangsverteilung | n | Schiefe der Mittelwerte | Beurteilung |\n|---|---|---|---|\n| gleichverteilt | 5 | **-0.015** | schon **praktisch normal** |\n| exponential | 5 | 0.872 | noch deutlich schief |\n| exponential | 30 | **0.354** | brauchbar |\n| binär, $p = 0.05$ | 5 | **1.819** | völlig unbrauchbar |\n| binär, $p = 0.05$ | 30 | **0.737** | **immer noch schief** |\n| binär, $p = 0.05$ | 100 | **0.423** | gerade so |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Bei der **Gleichverteilung** genügen fünf Werte | Sie ist bereits symmetrisch; es gibt keine Schiefe abzubauen. Die Faustregel von 30 ist hier weit übertrieben. |\n| Bei der **Exponentialverteilung** reichen 30 | Das ist der Fall, für den die Faustregel gemacht ist. |\n| Bei **seltenen Ereignissen versagt sie** | Mit $p = 0.05$ und $n = 30$ ist die Schiefe noch 0.74 — höher als bei fünf exponentialverteilten Werten. Auch bei $n = 100$ bleibt sie bei 0.42. |\n| Der Grund steht in der Spalte $n \\cdot p$ | Bei $n = 30$ erwartet man **1.5** Ereignisse. Die häufigsten Beobachtungen sind 0, 1 und 2 Treffer — eine Verteilung mit drei praktisch relevanten Werten kann nicht glockenförmig sein. |\n\n::: {.note-box}\n**Die brauchbare Faustregel für Anteile lautet deshalb nicht \"n > 30\", sondern:**\n\n$$n \\cdot p \\ge 10 \\quad \\text{und} \\quad n \\cdot (1-p) \\ge 10$$\n\nBei $p = 0.05$ bedeutet das $n \\ge 200$. Bei $p = 0.5$ genügen 20.\n\nUnd allgemein: **Die Faustregel muss zur Schiefe der Ausgangsverteilung passen.**\nWer $n$ sucht, kann rückwärts rechnen — soll die Schiefe der Mittelwerte unter\n0.5 liegen, braucht es\n\n$$n \\ge \\left(\\frac{\\text{Schiefe}(X)}{0.5}\\right)^2$$\n\nalso 16 bei einer Ausgangsschiefe von 2 und 64 bei einer von 4.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Wie gross $n$ sein muss, hängt an der Schiefe der Ausgangsverteilung: Bei\n> symmetrischen Verteilungen genügen fünf Beobachtungen, bei\n> exponentialverteilten 30, bei einem Anteil von 5 Prozent auch 100 nicht\n> (Schiefe der Mittelwerte 0.42). Für Anteile gilt stattdessen\n> $n \\cdot p \\ge 10$.\n\n### Beispiel 3: z-Werte machen Merkmale vergleichbar\n\n#### Frage und Datenlage\n\nEin IQ von 130 (Mittel 100, Standardabweichung 15) und eine Körpergrösse von\n1.92 m (Mittel 1.78, Standardabweichung 0.07). Welcher Wert ist\n\"aussergewöhnlicher\"?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz_iq <- (130 - 100) / 15\nz_groesse <- (1.92 - 1.78) / 0.07\n\nround(c(z_iq = z_iq, z_groesse = z_groesse), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     z_iq z_groesse \n        2         2 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Gleicher z-Wert heisst gleicher Rang in der jeweiligen Verteilung\nround(pnorm(c(z_iq, z_groesse)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9772 0.9772\n```\n\n\n:::\n\n```{.r .cell-code}\n# Und umgekehrt: welcher Wert entspricht dem 95. Perzentil?\nround(c(z_95 = qnorm(0.95),\n        iq_95 = 100 + qnorm(0.95) * 15,\n        groesse_95 = 1.78 + qnorm(0.95) * 0.07), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      z_95      iq_95 groesse_95 \n    1.6449   124.6728     1.8951 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Ein dritter Wert zum Vergleich: 40 Stunden Wochenarbeitszeit\n# bei Mittel 42 und Standardabweichung 6\nround(c(z = (40 - 42) / 6, perzentil = pnorm((40 - 42) / 6)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        z perzentil \n  -0.3333    0.3694 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nz_iq = (130 - 100) / 15\nz_groesse = (1.92 - 1.78) / 0.07\n\nprint({\"z_iq\": round(z_iq, 4), \"z_groesse\": round(z_groesse, 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'z_iq': 2.0, 'z_groesse': 2.0}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint([round(float(stats.norm.cdf(z)), 4) for z in (z_iq, z_groesse)])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[0.9772, 0.9772]\n```\n\n\n:::\n\n```{.python .cell-code}\nz95 = stats.norm.ppf(0.95)\nprint({\"z_95\": round(float(z95), 4),\n       \"iq_95\": round(100 + z95 * 15, 4),\n       \"groesse_95\": round(1.78 + z95 * 0.07, 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'z_95': 1.6449, 'iq_95': np.float64(124.6728), 'groesse_95': np.float64(1.8951)}\n```\n\n\n:::\n\n```{.python .cell-code}\nz_arbeit = (40 - 42) / 6\nprint({\"z\": round(z_arbeit, 4),\n       \"perzentil\": round(float(stats.norm.cdf(z_arbeit)), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'z': -0.3333, 'perzentil': 0.3694}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Merkmal | Wert | Mittel | SD | **z** | Perzentil |\n|---|---|---|---|---|---|\n| IQ | 130 | 100 | 15 | **2.000** | **97.72 %** |\n| Körpergrösse | 1.92 m | 1.78 m | 0.07 m | **2.000** | **97.72 %** |\n| Wochenarbeitszeit | 40 h | 42 h | 6 h | **-0.333** | 36.96 % |\n\n| Ausgabe | Wie sie zu lesen ist |\n|---|---|\n| Beide z-Werte sind **exakt 2.000** | Die beiden Personen liegen an derselben relativen Position ihrer Verteilung, obwohl die Einheiten nichts miteinander zu tun haben. **Das ist der Zweck der Standardisierung.** |\n| Perzentil 97.72 | 97.7 Prozent der Bevölkerung liegen darunter. Diese Übersetzung setzt allerdings voraus, dass die Verteilung **normal** ist — der z-Wert selbst nicht. |\n| Der negative z-Wert | -0.333 heisst: ein Drittel einer Standardabweichung **unter** dem Mittel. |\n| Das 95. Perzentil entspricht $z = 1.645$ | Also IQ 124.7 und Körpergrösse 1.895 m. Die Umkehrung funktioniert genauso. |\n\n::: {.note-box}\n**Zwei Dinge, die die Standardisierung nicht tut:**\n\n1. **Sie macht die Verteilung nicht normal.** Ein z-Wert von 2 bei einer stark\n   schiefen Verteilung bedeutet **nicht** das 97.7. Perzentil — die Umrechnung in\n   Perzentile gilt nur bei Normalverteilung. Der z-Wert selbst ist immer\n   berechenbar, seine Deutung als Perzentil nicht.\n2. **Sie sagt nichts über Bedeutsamkeit.** Ein z-Wert von 2 ist bei einem\n   Blutwert alarmierend und bei einer Schuhgrösse belanglos.\n\nDer praktische Nutzen liegt woanders: Standardisierte Variablen sind die\nGrundlage jedes Verfahrens, das Merkmale verschiedener Einheiten zusammenbringt\n— [Distanzmasse](../multivariat/distanzmasse.qmd),\n[Hauptkomponentenanalyse](../multivariat/hauptkomponentenanalyse.qmd),\nstandardisierte Regressionskoeffizienten.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Ein IQ von 130 und eine Körpergrösse von 1.92 m entsprechen beide einem z-Wert\n> von 2.0 und damit dem 97.7. Perzentil ihrer jeweiligen Verteilung.\n\n### Beispiel 4: Die Faustregeln und ihre Grenzen\n\n#### Frage und Datenlage\n\n68, 95 und 99.7 Prozent — gelten diese Anteile allgemein oder nur für die\nNormalverteilung? Geprüft an 100 000 exponentialverteilten Werten mit\nErwartungswert 1 und Standardabweichung 1.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheoretisch <- sapply(1:3, function(k) pnorm(k) - pnorm(-k))\n\nex <- exp_werte(5050, 100000)\nempirisch <- sapply(1:3, function(k) mean(ex >= 1 - k & ex <= 1 + k))\n\nround(rbind(normalverteilung = theoretisch, exponential = empirisch), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   [,1]   [,2]   [,3]\nnormalverteilung 0.6827 0.9545 0.9973\nexponential      0.8665 0.9508 0.9818\n```\n\n\n:::\n\n```{.r .cell-code}\ngitter <- seq(-2.5, 4.5, by = 0.01)\npar(mar = c(4, 4, 2, 1))\nplot(gitter, dnorm(gitter, mean = 1, sd = 1), type = \"l\", lwd = 2,\n     xlab = \"Wert\", ylab = \"Dichte\", ylim = c(0, 1.05))\nlines(gitter, ifelse(gitter >= 0, dexp(gitter), 0), lwd = 2, lty = 2)\nabline(v = 1, lty = 3)\nlegend(\"topright\", legend = c(\"Normal\", \"Exponential\"), lwd = 2,\n       lty = c(1, 2), bty = \"n\")\n```\n\n::: {.cell-output-display}\n![Beispiel 4: Normalverteilung und Exponentialverteilung, beide mit Mittel 1 und SD 1.](normalverteilung-zgws_files/figure-html/fig-b4-zgws-r-1.png){#fig-b4-zgws-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ntheoretisch = [stats.norm.cdf(k) - stats.norm.cdf(-k) for k in (1, 2, 3)]\n\nex = exp_werte(5050, 100000)\nempirisch = [float(((ex >= 1 - k) & (ex <= 1 + k)).mean()) for k in (1, 2, 3)]\n\nprint(pd.DataFrame({\"normalverteilung\": np.round(theoretisch, 4),\n                    \"exponential\": np.round(empirisch, 4)},\n                   index=[\"1 SD\", \"2 SD\", \"3 SD\"]).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    1 SD    2 SD    3 SD\nnormalverteilung  0.6827  0.9545  0.9973\nexponential       0.8665  0.9508  0.9818\n```\n\n\n:::\n\n```{.python .cell-code}\ngitter = np.arange(-2.5, 4.5, 0.01)\nfig, achse = plt.subplots(figsize=(7, 3.2))\nachse.plot(gitter, stats.norm.pdf(gitter, loc=1, scale=1), lw=2,\n           label=\"Normal\")\nachse.plot(gitter, np.where(gitter >= 0, stats.expon.pdf(gitter), 0), lw=2,\n           ls=\"--\", label=\"Exponential\")\nachse.axvline(1, ls=\":\", color=\"black\")\nachse.set_ylim(0, 1.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(0.0, 1.05)\n```\n\n\n:::\n\n```{.python .cell-code}\nachse.set_xlabel(\"Wert\")\nachse.set_ylabel(\"Dichte\")\nachse.legend(frameon=False)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselbe Gegenüberstellung in Python.](normalverteilung-zgws_files/figure-html/fig-b4-zgws-py-1.png){#fig-b4-zgws-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Bereich | Normalverteilung | Exponentialverteilung | Differenz |\n|---|---|---|---|\n| $\\mu \\pm 1\\sigma$ | **0.6827** | **0.8665** | **+18.4 Punkte** |\n| $\\mu \\pm 2\\sigma$ | **0.9545** | **0.9507** | -0.4 Punkte |\n| $\\mu \\pm 3\\sigma$ | **0.9973** | **0.9818** | **-1.6 Punkte** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Beide Verteilungen haben **Mittel 1 und SD 1** | Die Kennzahlen stimmen exakt überein; die Form nicht. |\n| Bei einer Standardabweichung liegen **87 statt 68 Prozent** | Weil die Exponentialverteilung ihre Masse links zusammendrängt: Der Bereich von 0 bis 2 enthält den grössten Teil. |\n| Bei zwei Standardabweichungen stimmt es fast | 95.1 gegen 95.5 Prozent. Ein Zufall der Zahlen, kein Prinzip. |\n| Bei drei Standardabweichungen fehlen 1.6 Punkte | Und die fehlen **alle auf der rechten Seite**: Die Exponentialverteilung hat einen langen Rand, den drei Standardabweichungen nicht abdecken. |\n| Nach unten reichen zwei Standardabweichungen bereits **unter null** | $1 - 2 = -1$, und dort gibt es keine Werte. Bei einer schiefen, nach unten begrenzten Verteilung ist ein symmetrisches Intervall grundsätzlich unpassend. |\n\n::: {.note-box}\n**Was allgemein gilt, ist viel schwächer.** Die Ungleichung von Tschebyscheff\nsagt für **jede** Verteilung mit endlicher Varianz:\n\n$$P(\\lvert X - \\mu \\rvert \\ge k\\sigma) \\le \\frac{1}{k^2}$$\n\nAlso liegen mindestens 75 Prozent innerhalb von zwei und mindestens 89 Prozent\ninnerhalb von drei Standardabweichungen. Das ist wahr und fast nutzlos — bei der\nNormalverteilung sind es 95.4 und 99.7 Prozent.\n\n**Die Lehre:** Die Faustregeln sind sehr nützlich, wenn die Verteilung\nannähernd normal ist, und irreführend, wenn nicht. Ob sie es ist, zeigt ein\n[QQ-Plot](qq-plots.qmd) — und für den Mittelwert einer genügend grossen\nStichprobe ist sie es meist, auch wenn die Einzelwerte es nicht sind. Genau\ndarauf beruhen die\n[Konfidenzintervalle](../inferenz/schaetzen-konfidenzintervalle.qmd).\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Bei einer Exponentialverteilung mit Erwartungswert 1 und Standardabweichung 1\n> liegen 86.7 Prozent der Werte innerhalb einer Standardabweichung vom Mittel\n> statt der bei Normalverteilung geltenden 68.3 Prozent. Die Faustregeln gelten\n> nur bei annähernder Normalität.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nDer zentrale Grenzwertsatz besagt, dass ...\n\n- [ ] die Daten bei genügend grosser Stichprobe normalverteilt werden ~ Die\n      Daten ändern sich nicht. Eine schiefe Verteilung bleibt schief, egal wie\n      viele Werte man erhebt.\n- [x] die Verteilung der Mittelwerte sich einer Normalverteilung nähert ~\n      Richtig. Gemeint ist die Verteilung über gedachte Wiederholungen der\n      Stichprobenziehung, nicht die Verteilung der Einzelwerte.\n- [ ] jede Verteilung eine Glockenform hat ~ Das wäre offensichtlich falsch.\n:::\n\n::: {.quiz}\nFür einen Anteil von 5 Prozent ist die Verteilung des Stichprobenanteils auch\nbei n = 100 noch deutlich schief. Was folgt daraus?\n\n- [x] Die Faustregel \"n > 30\" ist keine Konstante; für Anteile gilt\n      $n \\cdot p \\ge 10$ ~ Richtig. Bei p = 0.05 und n = 100 erwartet man fünf\n      Ereignisse, und eine Verteilung mit wenigen praktisch relevanten Werten\n      kann nicht glockenförmig sein. Nötig wären hier rund 200 Beobachtungen.\n- [ ] Der zentrale Grenzwertsatz gilt für Anteile nicht ~ Er gilt, nur langsamer.\n- [ ] Die Simulation ist fehlerhaft ~ Die gemessene Schiefe von 0.42 entspricht\n      dem theoretischen Wert.\n:::\n\n::: {.quiz}\nZwei Merkmale mit völlig verschiedenen Einheiten haben beide einen z-Wert von\n2.0. Was heisst das?\n\n- [x] Beide Werte liegen an derselben relativen Position ihrer Verteilung ~\n      Richtig. Der z-Wert misst den Abstand vom Mittel in Standardabweichungen\n      und ist deshalb einheitenfrei. Die Übersetzung in ein Perzentil setzt\n      allerdings Normalverteilung voraus.\n- [ ] Beide Werte sind gleich gross ~ 130 und 1.92 sind nicht gleich gross; nur\n      ihre relative Lage stimmt überein.\n- [ ] Beide Merkmale sind normalverteilt ~ Der z-Wert lässt sich bei jeder\n      Verteilung berechnen.\n:::\n\n::: {.quiz}\nEine Verteilung hat Mittel 1 und Standardabweichung 1, aber nur 86.7 Prozent\nder Werte liegen innerhalb einer Standardabweichung. Ist das möglich?\n\n- [x] Ja, die 68-Prozent-Regel gilt nur für die Normalverteilung ~ Richtig. Mittel\n      und Streuung sagen nichts über die Form. Allgemein gilt nur die Ungleichung\n      von Tschebyscheff, und die ist viel schwächer.\n- [ ] Nein, das widerspricht der Definition der Standardabweichung ~ Die\n      Standardabweichung ist definiert, ohne dass daraus Anteile folgen.\n- [ ] Nur bei diskreten Verteilungen ~ Das Beispiel ist stetig.\n:::\n\n::: {.quiz}\nDie Streuung von Mittelwerten sinkt von 0.99 bei n = 1 auf 0.18 bei n = 30. Was\nfür ein Zusammenhang ist das?\n\n- [x] Sie sinkt mit der Wurzel aus n ~ Richtig: $1/\\sqrt{30} = 0.183$. Deshalb\n      kostet eine Halbierung des Standardfehlers eine Vervierfachung der\n      Stichprobe.\n- [ ] Sie sinkt linear mit n ~ Dann läge sie bei 0.033.\n- [ ] Sie sinkt zufällig ~ Der Zusammenhang ist exakt und folgt aus der\n      Varianzrechnung für Summen unabhängiger Variablen.\n:::\n\n## Verlinkte Ressourcen\n\n- [OpenIntro Statistics, Kapitel zu Verteilungen](https://www.openintro.org/book/os/)\n- [QQ-Plots: Normalität grafisch prüfen](qq-plots.qmd)\n- [Schätzen und Konfidenzintervalle](../inferenz/schaetzen-konfidenzintervalle.qmd)\n",
    "supporting": [
      "normalverteilung-zgws_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}