{
  "hash": "078cd3d592d1bdb9662881bda38e79ec",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"pandas\"\ndescription: \"Series und DataFrame, Auswahl, Aggregation und Zusammenführen.\"\ncategories: [\"pandas\", \"Python\", \"R\", \"Data Wrangling\"]\nquelle: [\"PYFR\"]\nseitentyp: werkzeug\nstand: entwurf\norder: 70\n---\n\n\n\n\n\n## Kernideen\n\n- Eine **`Series`** ist ein Vektor mit Index, ein **`DataFrame`** eine\n  Sammlung solcher Spalten mit gemeinsamem Zeilenindex.\n- Rechnungen zwischen Series werden **nach Index ausgerichtet**, nicht nach\n  Position. Benannte Vektoren in R rechnen nach Position.\n- **`.loc`** wählt nach Beschriftung (Grenze eingeschlossen), **`.iloc`**\n  nach Position (Grenze ausgeschlossen). Bedingungen brauchen runde Klammern.\n- Zeilen- und Spaltenauswahl gehören in **einen** `.loc`-Zugriff;\n  Kettenindizierung schreibt ins Leere.\n- Aggregationen **lassen `NaN` still weg**, und `groupby` lässt Zeilen mit\n  fehlendem Gruppenschlüssel ebenso still fallen.\n- Nach jedem `merge` die Zeilenzahl prüfen: Ein nicht eindeutiger Schlüssel\n  vervielfacht Zeilen und verfälscht jede Summe.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [NumPy und SciPy](numpy-scipy.qmd), denn pandas legt eine\nbeschriftete Ebene über NumPy-Arrays, und [R-Grundlagen](r-grundlagen.qmd)\nfür den Data Frame als Vergleich. Die Arbeitsschritte selbst, also filtern,\numformen und zusammenfassen, stehen mit dplyr und pandas nebeneinander unter\n[Data Wrangling](../daten/data-wrangling.qmd).\n:::\n\n### Was pandas über NumPy legt\n\nEin NumPy-Array kennt nur Positionen. Für Daten braucht man Namen: Spalten\nheissen `verbrauch` und nicht 2, Zeilen gehören zu einem Datum und nicht zu\nPosition 17. Genau das ergänzt pandas, und zwar über den **Index**.\n\nDer Index ist mehr als eine Beschriftung. Bei jeder Rechnung zwischen zwei\nSeries oder DataFrames sucht pandas zuerst die passenden Einträge nach Index\nund rechnet dann. Fehlt ein Eintrag auf einer Seite, entsteht `NaN`. Das ist\nder grösste konzeptionelle Unterschied zum R-Data-Frame, der keinen\nvergleichbaren Mechanismus hat; dort gehen Rechnungen immer nach Position.\nWo keine Ausrichtung erwünscht ist, hilft `reset_index(drop=True)` oder das\nRechnen auf `.to_numpy()`.\n\n### Die Datenlage dieser Seite\n\n24 wöchentliche Verbrauchsmessungen vom 5. Januar bis 23. März 2026, je eine\nfür die Standorte Bern und Chur. Die Werte sind fest eingetragen, damit R und\nPython dieselben Zahlen zeigen.\n\n### Auswahl\n\n| Zugriff | arbeitet mit | obere Grenze | Beispiel |\n|---|---|---|---|\n| `df[\"a\"]` | Spaltenname | | eine Spalte als Series |\n| `df[[\"a\", \"b\"]]` | Liste von Spaltennamen | | mehrere Spalten als DataFrame |\n| `.loc[zeilen, spalten]` | Beschriftungen und Bedingungen | **eingeschlossen** | `df.loc[\"b\":\"c\", \"wert\"]` |\n| `.iloc[zeilen, spalten]` | Positionen | ausgeschlossen | `df.iloc[1:3, 0]` |\n| `.query(\"...\")` | Bedingung als Text | | `df.query(\"wert > 3\")` |\n\nBedingungen werden mit `&` (und), `|` (oder) und `~` (nicht) verknüpft, nicht\nmit `and` und `or`, und **jede Teilbedingung braucht runde Klammern**. Der\nGrund ist die Rangfolge: In Python bindet `&` stärker als `==` und `>`. In R\nist es umgekehrt, dort geht es ohne Klammern.\n\n### Warum Kettenindizierung nicht funktioniert\n\n`df[bedingung][\"wert\"] = 99` besteht aus zwei Zugriffen. Der erste erzeugt ein\nZwischenergebnis, der zweite schreibt in dieses Zwischenergebnis, das danach\nverworfen wird. Bei einer Auswahl per Bedingung ist das Zwischenergebnis eine\nKopie, die Zuweisung bewirkt nichts, und pandas warnt: bis Version 2 mit\n`SettingWithCopyWarning`, ab Version 3 (**copy on write**, dort gilt es für\njedes Zwischenergebnis) mit `ChainedAssignmentError`. Richtig ist\nein einziger Zugriff: `df.loc[bedingung, \"wert\"] = 99`. In R ist die\nverkettete Form `df$wert[bedingung] <- 99` dagegen gültig und üblich.\n\n### Fehlende Werte\n\npandas lässt `NaN` in Aggregationen weg (`skipna=True`), R gibt `NA` zurück\nund zwingt mit `na.rm = TRUE` zur Entscheidung. Wer in Python denselben\nReflex will, zählt vor jeder Aggregation mit `isna().sum()`. Dazu kommt eine\nzweite, weniger bekannte Stelle: `groupby` wirft Zeilen, deren\nGruppenschlüssel fehlt, ohne Hinweis hinaus. Erst `dropna=False` behält sie\nals eigene Gruppe.\n\n### dplyr und pandas\n\n| dplyr | pandas |\n|---|---|\n| `filter()` | `.loc[maske]`, `.query()` |\n| `select()` | `df[[\"a\", \"b\"]]` |\n| `mutate()` | `.assign()` |\n| `arrange()` | `.sort_values()` |\n| `group_by()` mit `summarise()` | `.groupby()` mit `.agg()` |\n| `left_join()` | `.merge(how=\"left\")` |\n| `pivot_wider()` | `.pivot()` |\n| `pivot_longer()` | `.melt()` |\n| `n()` | `\"size\"` |\n\nMethodenketten funktionieren wie die Pipe in R. Runde Klammern um den ganzen\nAusdruck erlauben den Zeilenumbruch, und `assign` mit einer `lambda`-Funktion\ngreift auf den Zwischenstand zu:\n\n```python\nergebnis = (messungen\n    .query(\"verbrauch > 90\")\n    .assign(abweichung=lambda d: d[\"verbrauch\"] - d[\"verbrauch\"].mean())\n    .sort_values(\"abweichung\", ascending=False))\n```\n\n### Kurz nachgeschlagen\n\n| Aufgabe | R | Python |\n|---|---|---|\n| Einlesen mit Semikolon und Dezimalkomma | `read.csv2(\"d.csv\")` | `pd.read_csv(\"d.csv\", sep=\";\", decimal=\",\")` |\n| erster Blick | `str(df)`, `summary(df)` | `df.info()`, `df.describe()` |\n| fehlende Werte je Spalte | `colSums(is.na(df))` | `df.isna().sum()` |\n| ersetzen | `tidyr::replace_na()` | `.fillna()` |\n| Häufigkeiten | `table(df$x)`, `count(df, x)` | `df[\"x\"].value_counts()` |\n| Schlüssel eindeutig? | `anyDuplicated(df$id) == 0` | `df[\"id\"].is_unique` |\n| Join mit Erwartung | `left_join(..., relationship = \"many-to-one\")` | `.merge(..., validate=\"many_to_one\")` |\n| exportieren | `write.csv(df, \"e.csv\", row.names = FALSE)` | `df.to_csv(\"e.csv\", index=False)` |\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Ausrichtung nach Index\n\n#### Frage und Datenlage\n\nZwei Serien mit den Beschriftungen x, y, z, die zweite in umgekehrter\nReihenfolge (`z = 10, y = 20, x = 30`). Was ergibt die Summe, in pandas und\nmit benannten Vektoren in R? Und was, wenn in der zweiten Serie z fehlt?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\na <- c(x = 1, y = 2, z = 3)\nb <- c(z = 10, y = 20, x = 30)\na + b                        # nach Position, die Namen von a bleiben\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n x  y  z \n11 22 33 \n```\n\n\n:::\n\n```{.r .cell-code}\na + b[names(a)]              # erst ausrichten, dann rechnen\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n x  y  z \n31 22 13 \n```\n\n\n:::\n\n```{.r .cell-code}\nc2 <- c(x = 10, y = 20)\nsuppressWarnings(a + c2)     # Recycling statt fehlender Wert\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n x  y  z \n11 22 13 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\na = pd.Series([1, 2, 3], index=[\"x\", \"y\", \"z\"])\nb = pd.Series([10, 20, 30], index=[\"z\", \"y\", \"x\"])\nprint((a + b).to_dict())                          # nach Index\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'x': 31, 'y': 22, 'z': 13}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint((a.to_numpy() + b.to_numpy()).tolist())     # nach Position\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[11, 22, 33]\n```\n\n\n:::\n\n```{.python .cell-code}\nc = pd.Series([10, 20], index=[\"x\", \"y\"])\nprint((a + c).to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'x': 11.0, 'y': 22.0, 'z': nan}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Rechnung | pandas | R | Erklärung |\n|---|---|---|---|\n| `a + b` | x 31, y 22, **z 13** | x 11, y 22, **z 33** | pandas addiert x zu x. R addiert Position zu Position und übernimmt die Namen von `a`, obwohl dort z und x zusammengezählt wurden. |\n| nach Position | `[11, 22, 33]` | | Über `.to_numpy()` rechnet pandas wie R. |\n| ausgerichtet in R | | x 31, y 22, z 13 | `b[names(a)]` sortiert `b` nach den Namen von `a`. |\n| z fehlt | x 11.0, y 22.0, **z NaN** | x 11, y 22, **z 13** | pandas meldet die Lücke als fehlenden Wert. R recycelt die 10 für z und warnt nur. |\n\nDie Werte in pandas werden zu Gleitkommazahlen (`11.0`), weil `NaN` eine\nGleitkommazahl ist und die ganze Serie denselben Typ tragen muss.\n\n#### Interpretation und Ergebnissatz\n\nDie Ausrichtung ist der Grund, warum pandas-Code selten \"danebenrechnet\",\nwenn zwei Tabellen verschieden sortiert sind. Sie ist zugleich der Grund für\nunerwartete `NaN`, sobald die Indizes nicht deckungsgleich sind. R vertraut\nauf die Reihenfolge; die Namen sind dort Beschriftung, keine Zuordnung.\n\n> pandas addiert nach Index und liefert x = 31, y = 22, z = 13, R addiert\n> benannte Vektoren nach Position und liefert unter denselben Namen 11, 22,\n> 33. Fehlt ein Eintrag, entsteht in pandas `NaN`, in R ein recycelter Wert.\n\n### Beispiel 2: loc, iloc und Bedingungen\n\n#### Frage und Datenlage\n\nEine kleine Tabelle mit Index a bis d: Was liefern `loc[\"b\":\"c\"]` und\n`iloc[1:3]`? Dann aus den 24 Messungen alle Berner Werte über 125, und die\nProbe, was ohne Klammern um die Teilbedingungen passiert.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmessungen[messungen$standort == \"Bern\" & messungen$verbrauch > 125, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        datum standort verbrauch\n3  2026-01-12     Bern     125.4\n7  2026-01-26     Bern     130.6\n13 2026-02-16     Bern     128.9\n21 2026-03-16     Bern     133.2\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(subset(messungen, verbrauch > 130))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndf = pd.DataFrame({\"wert\": [10, 20, 30, 40]}, index=[\"a\", \"b\", \"c\", \"d\"])\nprint(df.loc[\"b\":\"c\", \"wert\"].tolist(), df.iloc[1:3, 0].tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[20, 30] [20, 30]\n```\n\n\n:::\n\n```{.python .cell-code}\nmaske = (messungen[\"standort\"] == \"Bern\") & (messungen[\"verbrauch\"] > 125)\nprint(messungen.loc[maske])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        datum standort  verbrauch\n2  2026-01-12     Bern      125.4\n6  2026-01-26     Bern      130.6\n12 2026-02-16     Bern      128.9\n20 2026-03-16     Bern      133.2\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(len(messungen.loc[messungen[\"verbrauch\"] > 130, [\"datum\", \"verbrauch\"]]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2\n```\n\n\n:::\n\n```{.python .cell-code}\ntry:\n    messungen[\"standort\"] == \"Bern\" & messungen[\"verbrauch\"] > 125\nexcept TypeError as fehler:\n    print(type(fehler).__name__)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTypeError\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Schritt | Ergebnis | Erklärung |\n|---|---|---|\n| `loc[\"b\":\"c\"]` | `[20, 30]` | Beschriftungen, beide Grenzen dabei. |\n| `iloc[1:3]` | `[20, 30]` | Positionen 1 und 2, die 3 ist ausgeschlossen. Dasselbe Ergebnis auf verschiedenem Weg. |\n| Bern über 125 | vier Zeilen: 125.4, 130.6, 128.9, 133.2 | am 12. Januar, 26. Januar, 16. Februar und 16. März |\n| Zeilenbeschriftung | pandas 2, 6, 12, 20; R 3, 7, 13, 21 | Dieselben Zeilen. pandas zählt den Index ab null, R die Zeilennamen ab eins. |\n| über 130 | 2 Messungen | 130.6 und 133.2 |\n| ohne Klammern | **`TypeError`** | Python rechnet zuerst `\"Bern\" & messungen[...]`, und das ist sinnlos. R braucht die Klammern nicht, weil dort `==` stärker bindet als `&`. |\n\n#### Interpretation und Ergebnissatz\n\nDie untere Grenze wird bei beiden Zugriffen gleich behandelt, die obere\nnicht. Das ist Absicht: Bei Beschriftungen wüsste man sonst nicht, welcher\nEintrag der nächste wäre, den man ausschliessen soll. Für Bedingungen ist\n`.loc` der Zugriff der Wahl, weil er Zeilen und Spalten in einem Schritt\nnimmt.\n\n> `loc[\"b\":\"c\"]` und `iloc[1:3]` liefern beide die Werte 20 und 30. In Bern\n> lagen vier Messungen über 125, die höchste bei 133.2 am 16. März; ohne\n> Klammern um die Teilbedingungen bricht der Ausdruck mit einem `TypeError`\n> ab.\n\n### Beispiel 3: Kettenindizierung\n\n#### Frage und Datenlage\n\nIn einer Tabelle mit den Gruppen a, b, a soll der Wert aller Zeilen der Gruppe\na auf 99 gesetzt werden, einmal mit zwei Zugriffen hintereinander und einmal\nmit einem einzigen `.loc`.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- data.frame(wert = c(1, 2, 3), gruppe = c(\"a\", \"b\", \"a\"))\ndf$wert[df$gruppe == \"a\"] <- 99      # verkettet, in R gueltig\ndf$wert\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 99  2 99\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndf = pd.DataFrame({\"wert\": [1, 2, 3], \"gruppe\": [\"a\", \"b\", \"a\"]})\n\nwith warnings.catch_warnings(record=True) as meldungen:\n    warnings.simplefilter(\"always\")\n    df[df[\"gruppe\"] == \"a\"][\"wert\"] = 99          # zwei Zugriffe\nprint([type(m.message).__name__ for m in meldungen])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['SettingWithCopyWarning']\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(df[\"wert\"].tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1, 2, 3]\n```\n\n\n:::\n\n```{.python .cell-code}\ndf.loc[df[\"gruppe\"] == \"a\", \"wert\"] = 99          # ein Zugriff\nprint(df[\"wert\"].tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[99, 2, 99]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Variante | Warnung | Werte danach | Erklärung |\n|---|---|---|---|\n| zwei Zugriffe | `SettingWithCopyWarning` (ab pandas 3 `ChainedAssignmentError`) | **`[1, 2, 3]`** | Die Zuweisung traf eine Kopie, die sofort verworfen wurde. Das Original ist unverändert. |\n| ein `.loc` | keine | `[99, 2, 99]` | Zeilen und Spalte in einem Zugriff. |\n| R verkettet | | 99 2 99 | In R ist `df$wert[...] <- 99` eine gültige Ersetzung. |\n\nDie Warnung wird hier eingefangen und ausgegeben, weil diese Sammlung\nWarnungen sonst ausblendet. Im eigenen Code sollte sie nie unterdrückt werden:\nSie ist der einzige Hinweis darauf, dass eine Zuweisung nichts bewirkt hat.\n\n#### Interpretation und Ergebnissatz\n\nDer Fehler ist heimtückisch, weil der Code gültig aussieht und in R genau so\ngeschrieben würde. Bis pandas 2 hängt das Ergebnis sogar vom Fall ab, weil ein\nZwischenergebnis mal eine View und mal eine Kopie ist; ab pandas 3 ist es mit\ncopy on write eindeutig, aber eindeutig **wirkungslos**. Die Regel bleibt:\nWer schreiben will, benutzt einen einzigen `.loc`-Zugriff.\n\n> Die verkettete Zuweisung liess die Werte bei 1, 2, 3 und löste eine Warnung\n> aus; erst `df.loc[bedingung, \"wert\"] = 99`\n> setzte beide Zeilen der Gruppe a auf 99. In R ist die verkettete Form\n> gültig.\n\n### Beispiel 4: Fehlende Werte und fehlende Schlüssel\n\n#### Frage und Datenlage\n\nVier Werte `1, 2, NaN, 4`: Welcher Mittelwert kommt heraus? Und eine Tabelle\nmit den Gruppen a, b, fehlend, a und den Werten 1 bis 4: Welche Summen je\nGruppe liefert `groupby`?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(1, 2, NA, 4)\nmean(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(x, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.333333\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(x))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\nd <- data.frame(gruppe = c(\"a\", \"b\", NA, \"a\"), wert = 1:4)\nd |> group_by(gruppe) |> summarise(summe = sum(wert))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  gruppe summe\n  <chr>  <int>\n1 a          5\n2 b          2\n3 <NA>       3\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nx = pd.Series([1, 2, np.nan, 4])\nprint(round(x.mean(), 4), x.count(), len(x), x.isna().sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2.3333 3 4 1\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(x.mean(skipna=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnan\n```\n\n\n:::\n\n```{.python .cell-code}\nd = pd.DataFrame({\"gruppe\": [\"a\", \"b\", None, \"a\"], \"wert\": [1, 2, 3, 4]})\nprint(d.groupby(\"gruppe\")[\"wert\"].sum().to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'a': 5, 'b': 2}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(d.groupby(\"gruppe\", dropna=False)[\"wert\"].sum().to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'a': 5, 'b': 2, nan: 3}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | pandas | R | Erklärung |\n|---|---|---|---|\n| Mittelwert | **2.3333** | **`NA`** | pandas lässt den fehlenden Wert still weg: (1 + 2 + 4) / 3. R verweigert das Ergebnis. |\n| mit ausdrücklicher Angabe | `skipna=False`: `nan` | `na.rm = TRUE`: 2.333333 | Jede Sprache kann das Verhalten der anderen, nur mit umgekehrter Voreinstellung. |\n| vorhandene Werte | `count()`: 3 von `len()`: 4 | | `count` zählt nur Vorhandenes, `len` alles. |\n| fehlende Werte | 1 | 1 | |\n| Summen je Gruppe | **a 5, b 2** | a 5, b 2, **NA 3** | Die Zeile mit fehlender Gruppe fehlt in pandas, ohne Hinweis. dplyr führt sie als eigene Gruppe. |\n| mit `dropna=False` | a 5, b 2, nan 3 | | Jetzt ist die Summe aller Gruppen wieder 10. |\n\n#### Interpretation und Ergebnissatz\n\nBeide Stellen verlieren Daten, ohne es zu sagen. Beim Mittelwert ist das oft\ngewollt, beim `groupby` selten: Die Gruppensummen addieren sich zu 7 statt\nzu 10, und wer die Gesamtsumme nicht nachrechnet, bemerkt es nicht. Die\nKontrolle ist einfach: Summe der Gruppen gegen Summe der Spalte, und die\nAnzahl fehlender Werte je Spalte vor jeder Auswertung. Mehr dazu unter\n[Datenqualität](../daten/datenqualitaet.qmd).\n\n> pandas ergibt einen Mittelwert von 2.3333, weil der fehlende Wert still\n> weggelassen wird; R liefert `NA`. Beim Gruppieren fällt in pandas die Zeile\n> mit fehlendem Schlüssel weg, sodass sich die Summen zu 7 statt 10 addieren;\n> erst `dropna=False` behält sie.\n\n### Beispiel 5: Gruppieren, zusammenfassen, breit machen\n\n#### Frage und Datenlage\n\nAnzahl, mittlerer Verbrauch und Spannweite je Standort über alle 24\nMessungen, danach der mittlere Verbrauch je Monat und Standort als breite\nTabelle mit einer Spalte je Standort.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmessungen |>\n  group_by(standort) |>\n  summarise(n      = n(),\n            mittel = round(mean(verbrauch), 2),\n            spanne = round(max(verbrauch) - min(verbrauch), 1),\n            .groups = \"drop\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  standort     n mittel spanne\n  <chr>    <int>  <dbl>  <dbl>\n1 Bern        12  123.    17.4\n2 Chur        12   95.8   14.4\n```\n\n\n:::\n\n```{.r .cell-code}\nmonat <- as.integer(format(messungen$datum, \"%m\"))\nround(tapply(messungen$verbrauch, list(monat, messungen$standort), mean), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Bern  Chur\n1 123.80 94.62\n2 121.62 95.38\n3 123.92 97.25\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(messungen.groupby(\"standort\").agg(\n    n=(\"verbrauch\", \"size\"),\n    mittel=(\"verbrauch\", \"mean\"),\n    spanne=(\"verbrauch\", lambda s: s.max() - s.min()),\n).round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           n  mittel  spanne\nstandort                    \nBern      12  123.12    17.4\nChur      12   95.75    14.4\n```\n\n\n:::\n\n```{.python .cell-code}\nmonatlich = (messungen\n    .assign(monat=messungen[\"datum\"].dt.month)\n    .groupby([\"monat\", \"standort\"], as_index=False)\n    .agg(mittel=(\"verbrauch\", \"mean\")))\nprint(monatlich.pivot(index=\"monat\", columns=\"standort\", values=\"mittel\").round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstandort    Bern   Chur\nmonat                  \n1         123.80  94.62\n2         121.62  95.38\n3         123.92  97.25\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Standort | n | Mittel | Spannweite | Januar | Februar | März |\n|---|---|---|---|---|---|---|\n| Bern | 12 | 123.12 | 17.4 | 123.80 | 121.62 | 123.92 |\n| Chur | 12 | 95.75 | 14.4 | 94.62 | 95.38 | 97.25 |\n\n| Teil | Erklärung |\n|---|---|\n| `n` | `size` in pandas, `n()` in dplyr: Zeilen je Gruppe, fehlende Werte eingeschlossen. `count` würde nur vorhandene zählen. |\n| Mittel | 1477.4 / 12 für Bern, 1149.0 / 12 für Chur |\n| Spannweite | Bern 133.2 − 115.8, Chur 103.1 − 88.7. Eine eigene Funktion als `lambda` in `agg`. |\n| Monatsmittel | je vier Wochen, weil jeder Monat hier vier Messtage hat |\n| breite Form | `pivot` in pandas, in R hier `tapply` mit zwei Gruppierungen; mit tidyr wäre es `pivot_wider()`. |\n\n#### Interpretation und Ergebnissatz\n\n`groupby` mit benannten Aggregationen entspricht Zeile für Zeile\n`group_by` mit `summarise`, nur dass pandas die Gruppen in den Index legt.\nDie breite Tabelle zeigt, was die Gesamtmittel verbergen: Bern bleibt über\nalle drei Monate nahezu gleich, Chur steigt von 94.62 auf 97.25.\n\n> Bern verbrauchte im Mittel 123.12 bei einer Spannweite von 17.4, Chur 95.75\n> bei 14.4, je über zwölf Messungen. Nach Monaten steigt der Verbrauch in Chur\n> von 94.62 im Januar auf 97.25 im März, in Bern bleibt er zwischen 121.62\n> und 123.92.\n\n### Beispiel 6: Verknüpfen und die Zeilenzahl\n\n#### Frage und Datenlage\n\nDie Messungen sollen um den Kanton ergänzt werden. Die Stammdaten enthalten\nBern, Chur und Sion. Eine zweite Fassung der Stammdaten führt Chur\nversehentlich doppelt. Was passiert mit Zeilenzahl und Gesamtverbrauch?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstammdaten <- data.frame(standort = c(\"Bern\", \"Chur\", \"Sion\"),\n                         kanton = c(\"BE\", \"GR\", \"VS\"))\ndoppelt <- data.frame(standort = c(\"Bern\", \"Chur\", \"Chur\"),\n                      kanton = c(\"BE\", \"GR\", \"GR\"))\n\nc(vorher = nrow(messungen),\n  nachher = nrow(left_join(messungen, stammdaten, by = \"standort\")),\n  doppelt = nrow(left_join(messungen, doppelt, by = \"standort\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n vorher nachher doppelt \n     24      24      36 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(original = sum(messungen$verbrauch),\n        nach_join = sum(left_join(messungen, doppelt, by = \"standort\")$verbrauch)), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n original nach_join \n   2626.4    3775.4 \n```\n\n\n:::\n\n```{.r .cell-code}\nanyDuplicated(doppelt$standort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3\n```\n\n\n:::\n\n```{.r .cell-code}\ninherits(tryCatch(left_join(messungen, doppelt, by = \"standort\",\n                            relationship = \"many-to-one\"),\n                  error = function(e) e), \"error\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nstammdaten = pd.DataFrame({\"standort\": [\"Bern\", \"Chur\", \"Sion\"],\n                           \"kanton\": [\"BE\", \"GR\", \"VS\"]})\ndoppelt = pd.DataFrame({\"standort\": [\"Bern\", \"Chur\", \"Chur\"],\n                        \"kanton\": [\"BE\", \"GR\", \"GR\"]})\n\nverknuepft = messungen.merge(stammdaten, on=\"standort\", how=\"left\")\nfalsch = messungen.merge(doppelt, on=\"standort\", how=\"left\")\nprint(len(messungen), len(verknuepft), len(falsch))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n24 24 36\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(round(messungen[\"verbrauch\"].sum(), 1), round(falsch[\"verbrauch\"].sum(), 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2626.4 3775.4\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(stammdaten[\"standort\"].is_unique, doppelt[\"standort\"].is_unique)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue False\n```\n\n\n:::\n\n```{.python .cell-code}\ntry:\n    messungen.merge(doppelt, on=\"standort\", how=\"left\", validate=\"many_to_one\")\nexcept pd.errors.MergeError as fehler:\n    print(type(fehler).__name__)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMergeError\n```\n\n\n:::\n\n```{.python .cell-code}\naussen = messungen.merge(stammdaten, on=\"standort\", how=\"outer\")\nprint(aussen[\"standort\"].value_counts().to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'Bern': 12, 'Chur': 12, 'Sion': 1}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Schritt | Python | R | Erklärung |\n|---|---|---|---|\n| Zeilen vorher | 24 | 24 | |\n| nach Join mit eindeutigen Stammdaten | 24 | 24 | Jede Messung findet genau einen Kanton. Sion hat keine Messung und fällt beim Left Join weg. |\n| nach Join mit doppeltem Chur | **36** | **36** | Jede der zwölf Churer Messungen wird mit beiden Chur-Zeilen kombiniert. |\n| Gesamtverbrauch | 2626.4 gegen **3775.4** | dieselben | Der Churer Verbrauch von 1149.0 zählt doppelt. |\n| Schlüssel eindeutig? | `True`, `False` | `anyDuplicated`: 3 | R nennt die Position der ersten Doppelung. |\n| Join mit Erwartung | **`MergeError`** | Fehler (`TRUE`) | `validate=\"many_to_one\"` beziehungsweise `relationship = \"many-to-one\"` bricht ab, statt still zu vervielfachen. |\n| Outer Join | Bern 12, Chur 12, Sion 1 | | Ein Outer Join fügt fehlende Schlüssel als Zeile mit `NaN` hinzu, vervielfacht aber nichts. |\n\n#### Interpretation und Ergebnissatz\n\nEin Join mit doppeltem Schlüssel erzeugt keinen Fehler, sondern eine grössere\nTabelle, und jede Summe danach ist falsch. Die Gewohnheit, nach jedem Join die\nZeilenzahl mit der vorherigen zu vergleichen, kostet eine Zeile Code. Noch\nbesser ist es, die Erwartung gleich in den Aufruf zu schreiben: `validate` in\npandas, `relationship` in dplyr. Warum Schlüssel eindeutig sein müssen,\nerklärt die [Datenmodellierung](../datenbanken/datenmodellierung.qmd).\n\n> Mit eindeutigen Stammdaten behält die Tabelle ihre 24 Zeilen. Ist Chur in\n> den Stammdaten doppelt, wächst sie ohne Fehlermeldung auf 36 Zeilen, und\n> der Gesamtverbrauch steigt von 2626.4 auf 3775.4; `validate=\"many_to_one\"`\n> hätte den Join abgebrochen.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nWarum schliesst `df.loc[\"b\":\"c\"]` die Grenze ein, `df.iloc[1:3]` aber nicht?\n\n- [x] `.loc` arbeitet mit Beschriftungen, `.iloc` mit Positionen ~ Richtig.\n      Bei Beschriftungen wäre eine ausgeschlossene obere Grenze unbrauchbar,\n      weil man den nächsten Eintrag kennen müsste.\n- [ ] Es ist eine Inkonsistenz ohne Grund ~ Der Unterschied ist beabsichtigt\n      und folgt aus der Art der Angabe.\n- [ ] `.loc` ist die ältere Schreibweise ~ Beide sind aktuell und für\n      verschiedene Zwecke gedacht.\n:::\n\n::: {.quiz}\nZwei Series mit Index x, y, z und z, y, x werden addiert. In R ergäben\nbenannte Vektoren 11, 22, 33. Was ergibt pandas?\n\n- [x] x 31, y 22, z 13 ~ Richtig. pandas richtet nach Index aus und addiert\n      x zu x. R rechnet nach Position.\n- [ ] Ebenfalls 11, 22, 33 ~ Das wäre das Verhalten von NumPy-Arrays oder\n      `.to_numpy()`.\n- [ ] Einen Fehler wegen unterschiedlicher Reihenfolge ~ Der Fall ist\n      vorgesehen und läuft still durch.\n:::\n\n::: {.quiz}\nWarum ist `df[df[\"a\"] > 1][\"b\"] = 0` wirkungslos?\n\n- [x] Die Zuweisung trifft ein Zwischenergebnis, das danach verworfen wird ~\n      Richtig. pandas warnt dabei mit `SettingWithCopyWarning`, ab Version 3\n      mit `ChainedAssignmentError`. Ein einziger `.loc`-Zugriff umgeht\n      das.\n- [ ] Die Bedingung ist falsch geschrieben ~ Die Bedingung ist in Ordnung.\n- [ ] Es funktioniert nur bei numerischen Spalten ~ Der Datentyp spielt keine\n      Rolle.\n:::\n\n::: {.quiz}\nDie Summen aus `df.groupby(\"gruppe\")[\"wert\"].sum()` ergeben zusammen 7, die\nSpalte `wert` summiert 10. Was ist passiert?\n\n- [x] Zeilen mit fehlendem Gruppenschlüssel wurden weggelassen ~ Richtig.\n      `groupby` verwirft sie ohne Hinweis. `dropna=False` behält sie als\n      eigene Gruppe, wie Beispiel 4 zeigt.\n- [ ] `sum` hat einen fehlenden Wert als 0 gezählt ~ Das würde die Summe\n      nicht verringern.\n- [ ] Ein Rundungsfehler ~ Bei ganzen Zahlen gibt es keinen.\n:::\n\n::: {.quiz}\nNach einem `merge` hat die Tabelle mehr Zeilen als vorher. Was ist passiert?\n\n- [x] Der Schlüssel war in der rechten Tabelle nicht eindeutig ~ Richtig.\n      Jede Zeile links wurde mit jeder passenden Zeile rechts kombiniert. Vor\n      dem Join lohnt der Blick auf `is_unique`, oder gleich\n      `validate=\"many_to_one\"`.\n- [ ] Es wurde versehentlich ein Outer Join verwendet ~ Der fügt fehlende\n      Schlüssel hinzu, vervielfacht aber keine vorhandenen Zeilen.\n- [ ] pandas hat die Zeilen doppelt eingelesen ~ Der Einlesevorgang ist nicht\n      beteiligt.\n:::\n\n::: {.quiz}\nIn pandas liefert `x.mean()` bei einem fehlenden Wert eine Zahl, in R\n`mean(x)` den Wert `NA`. Welche Voreinstellung ist die vorsichtigere?\n\n- [x] Die von R, weil sie zur Entscheidung zwingt ~ Richtig. Wer `na.rm =\n      TRUE` schreibt, weiss, dass Werte fehlen. In pandas muss man daran\n      denken, `isna().sum()` selbst aufzurufen.\n- [ ] Die von pandas, weil sie ein Ergebnis liefert ~ Ein Ergebnis ohne\n      Hinweis auf fehlende Werte kann täuschen.\n- [ ] Beide sind gleichwertig ~ Das Ergebnis mit `na.rm = TRUE` ist gleich,\n      der Weg dorthin nicht.\n:::\n\n## Verlinkte Ressourcen\n\n- [pandas-Benutzerhandbuch](https://pandas.pydata.org/docs/user_guide/index.html)\n- [Copy on Write in pandas](https://pandas.pydata.org/docs/user_guide/copy_on_write.html)\n- [Vergleich pandas gegen R](https://pandas.pydata.org/docs/getting_started/comparison/comparison_with_r.html)\n- [dplyr-Referenz](https://dplyr.tidyverse.org/)\n",
    "supporting": [
      "pandas_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}