{
  "hash": "358fcaa7e914d3588ea45153fdab423e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Datenimport und Formate\"\ndescription: \"CSV, Excel, JSON und Pickle lesen und schreiben, Kodierung beachten.\"\ncategories: [\"Data Wrangling\", \"R\", \"Python\"]\nquelle: [\"PYFR\", \"ESDS\"]\nseitentyp: werkzeug\nstand: entwurf\norder: 10\n---\n\n\n\n\n\n## Kernideen\n\n- Der erste Blick nach dem Import gehört den **Spaltentypen**, nicht den\n  Werten.\n- Trennzeichen, Dezimalzeichen, Tausenderzeichen und **Kodierung** werden\n  angegeben, nicht geraten.\n- Ein **Datum** wird beim Import umgewandelt. Als Text sortiert es falsch.\n- Eine Kennung wie `0815` ist **Text**, keine Zahl. Sonst fällt die führende\n  Null weg.\n- **CSV trägt keine Typen.** Datum, Kategorie und ganze Zahl mit fehlendem\n  Wert kommen als etwas anderes zurück.\n- Verschachteltes JSON wird **flach gemacht**, bevor damit gerechnet wird.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [R-Grundlagen](../programmierung/r-grundlagen.qmd) oder\n[pandas](../programmierung/pandas.qmd) für Data Frames und Spaltentypen. Was\ndanach kommt, ist die Kontrolle auf [Datenqualität](datenqualitaet.qmd) und\ndas Umformen im [Data Wrangling](data-wrangling.qmd). Wie Dateien technisch\ngelesen und geschrieben werden, steht unter\n[Fehlerbehandlung und Dateizugriff](../programmierung/python-exceptions-io.qmd).\n:::\n\n### Der erste Blick gehört den Spaltentypen\n\nEin Import meldet selten einen Fehler. Er liefert eine Tabelle, die richtig\naussieht, und der Schaden zeigt sich erst in der Auswertung: eine Spalte, die\nText statt Zahl ist, ein Datum, das alphabetisch sortiert, eine Kennung ohne\nführende Null. Deshalb ist der erste Befehl nach jedem Import `str()`\nbeziehungsweise `df.dtypes`, und erst der zweite schaut auf die Werte.\n\n### Die vier Einstellungen, die im deutschsprachigen Raum nötig sind\n\n| Einstellung | Beispiel in der Datei | R (readr) | pandas |\n|---|---|---|---|\n| Spaltentrenner | `;` | `read_csv2()` | `sep=\";\"` |\n| Dezimalzeichen | `12,4` | in `read_csv2()` enthalten | `decimal=\",\"` |\n| Tausenderzeichen | `1.234` | in `read_csv2()` enthalten | `thousands=\".\"` |\n| Kodierung | `Fräse` | `locale(encoding = \"UTF-8\")` | `encoding=\"utf-8\"` |\n\n`read_csv2()` bringt die ersten drei Einstellungen mit, in pandas werden sie\neinzeln angegeben. Das ist der häufigste Unterschied beim Übertragen von\nImportcode zwischen den Sprachen.\n\n### Typen vorgeben statt raten lassen\n\nBeide Sprachen raten den Typ aus den ersten Zeilen. Das geht gut, solange die\nDaten sauber sind, und schiefgehen kann es auf zwei Arten: Eine Kennung mit\nführenden Nullen wird zur Zahl, oder ein einziger Sonderwert macht eine\nZahlenspalte zu Text. Deshalb gibt man die Typen der wichtigen Spalten vor:\n\n```r\nread_csv2(\"daten.csv\", col_types = cols(\n  plz = col_character(), menge = col_integer(), datum = col_date(\"%d.%m.%Y\")))\n```\n\n```python\npd.read_csv(\"daten.csv\", sep=\";\", decimal=\",\",\n            dtype={\"plz\": str}, parse_dates=[\"datum\"], dayfirst=True)\n```\n\n### Die Formate und wozu sie taugen\n\n| Format | trägt Typen | lesbar für | wofür |\n|---|---|---|---|\n| CSV | nein | alles, auch Tabellenkalkulationen | Austausch, Archiv |\n| Excel | teilweise | Menschen | Vorlagen, Handarbeit; `readxl` beziehungsweise `openpyxl` |\n| JSON | einfache Typen | Menschen und Programme | Schnittstellen, verschachtelte Antworten |\n| Parquet | ja | viele Sprachen | grosse Tabellen, spaltenweise, komprimiert |\n| RDS, Pickle | vollständig | nur die eigene Sprache | Zwischenstände einer Auswertung |\n\nFür einen Zwischenstand ist der Typverlust der wichtigere Punkt als die\nDateigrösse. Wer eine bereinigte Tabelle als CSV ablegt, bereinigt sie beim\nnächsten Einlesen erneut.\n\n### Kurz nachgeschlagen\n\n| Aufgabe | R | Python |\n|---|---|---|\n| CSV mit Semikolon und Dezimalkomma | `read_csv2(\"d.csv\")` | `pd.read_csv(\"d.csv\", sep=\";\", decimal=\",\")` |\n| Typen vorgeben | `col_types = cols(...)` | `dtype={...}`, `parse_dates=[...]` |\n| nur die ersten Zeilen | `n_max = 1000` | `nrows=1000` |\n| nur bestimmte Spalten | `col_select = c(a, b)` | `usecols=[\"a\", \"b\"]` |\n| Excel | `readxl::read_excel(\"m.xlsx\", sheet = \"Daten\")` | `pd.read_excel(\"m.xlsx\", sheet_name=\"Daten\")` |\n| JSON flach machen | `jsonlite::flatten()` | `pd.json_normalize()` |\n| schreiben ohne Zeilennamen | `write_csv(df, \"e.csv\")` | `df.to_csv(\"e.csv\", index=False)` |\n| mit Typen ablegen | `saveRDS(df, \"d.rds\")` | `df.to_pickle(\"d.pkl\")` |\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Eine CSV mit Semikolon und Dezimalkomma\n\n#### Frage und Datenlage\n\nEine Datei mit drei Messungen, so wie sie aus einem deutschsprachigen Export\nkommt: Semikolon als Trenner, Komma als Dezimalzeichen, Datum als\n`01.03.2026`. Was passiert ohne Einstellungen, was mit, und warum muss das\nDatum umgewandelt werden?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninhalt <- c(\"datum;typ;verbrauch\",\n            \"01.03.2026;A;12,4\",\n            \"02.03.2026;B;9,8\",\n            \"03.03.2026;A;14,1\")\npfad <- tempfile(fileext = \".csv\")\nwriteLines(inhalt, pfad)\n\nfalsch <- read_csv(pfad, show_col_types = FALSE)     # Komma als Trenner\nncol(falsch)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\nrichtig <- read_csv2(pfad, show_col_types = FALSE)   # Semikolon und Komma\nsapply(richtig, class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      datum         typ   verbrauch \n\"character\" \"character\"   \"numeric\" \n```\n\n\n:::\n\n```{.r .cell-code}\nsum(richtig$verbrauch)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 36.3\n```\n\n\n:::\n\n```{.r .cell-code}\nmit_datum <- mutate(richtig, datum = dmy(datum))\nsapply(mit_datum, class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      datum         typ   verbrauch \n     \"Date\" \"character\"   \"numeric\" \n```\n\n\n:::\n\n```{.r .cell-code}\nsort(c(\"01.03.2026\", \"02.02.2026\"))                  # als Text\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"01.03.2026\" \"02.02.2026\"\n```\n\n\n:::\n\n```{.r .cell-code}\nsort(dmy(c(\"01.03.2026\", \"02.02.2026\")))             # als Datum\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2026-02-02\" \"2026-03-01\"\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ninhalt = \"\\n\".join([\"datum;typ;verbrauch\",\n                    \"01.03.2026;A;12,4\",\n                    \"02.03.2026;B;9,8\",\n                    \"03.03.2026;A;14,1\"])\npfad = ordner / \"messung.csv\"\n_ = pfad.write_text(inhalt, encoding=\"utf-8\")\n\nfalsch = pd.read_csv(pfad)                              # Standardannahme\nprint(falsch.shape, list(falsch.columns))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(3, 1) ['datum;typ;verbrauch']\n```\n\n\n:::\n\n```{.python .cell-code}\nrichtig = pd.read_csv(pfad, sep=\";\", decimal=\",\")\nprint(richtig.dtypes.astype(str).to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'datum': 'object', 'typ': 'object', 'verbrauch': 'float64'}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(richtig[\"verbrauch\"].sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n36.300000000000004\n```\n\n\n:::\n\n```{.python .cell-code}\nrichtig[\"datum\"] = pd.to_datetime(richtig[\"datum\"], format=\"%d.%m.%Y\")\nprint(richtig.dtypes.astype(str).to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'datum': 'datetime64[ns]', 'typ': 'object', 'verbrauch': 'float64'}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(sorted([\"01.03.2026\", \"02.02.2026\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['01.03.2026', '02.02.2026']\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(list(richtig[\"datum\"].sort_values().dt.strftime(\"%d.%m.%Y\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['01.03.2026', '02.03.2026', '03.03.2026']\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Schritt | Python | R | Erklärung |\n|---|---|---|---|\n| ohne Einstellungen | Form **(3, 1)**, eine Spalte namens `datum;typ;verbrauch` | `ncol` = **1** | Ohne Semikolon als Trenner steht die ganze Zeile in einer Spalte. Kein Fehler, nur eine unbrauchbare Tabelle. |\n| mit Einstellungen | `datum` Text, `typ` Text, `verbrauch` **float64** | `character`, `character`, `numeric` | Erst mit `decimal=\",\"` beziehungsweise `read_csv2` wird `verbrauch` eine Zahl. |\n| Summe Verbrauch | 36.300000000000004 | 36.3 | Dieselbe Zahl. Python zeigt die Gleitkommadarstellung ungerundet, R rundet bei der Ausgabe auf sieben Stellen. |\n| Datum umgewandelt | `datetime64[ns]` | `Date` | `to_datetime` mit `format` beziehungsweise `dmy()`. |\n| Text sortiert | `['01.03.2026', '02.02.2026']` | dieselbe Reihenfolge | **Falsch:** Der 1. März steht vor dem 2. Februar, weil zeichenweise verglichen wird. |\n| Datum sortiert | 01.03., 02.03., 03.03. | `2026-02-02`, `2026-03-01` | Als Datum stimmt die Reihenfolge, und Differenzen lassen sich rechnen. |\n\n#### Interpretation und Ergebnissatz\n\nDer Import ohne Einstellungen liefert hier eine Tabelle mit einer einzigen\nSpalte, das fällt sofort auf. Gefährlicher ist der halbe Erfolg: Trenner\nrichtig, Dezimalzeichen falsch. Dann steht in `verbrauch` Text, jede Summe\nbricht ab oder ist falsch, und die Ursache liegt drei Schritte zurück.\n\n> Ohne Angabe des Trenners entsteht eine Tabelle mit einer einzigen Spalte;\n> mit `sep=\";\"` und `decimal=\",\"` wird `verbrauch` numerisch und summiert sich\n> zu 36.3. Das Datum muss ausdrücklich umgewandelt werden, sonst steht der\n> 1. März beim Sortieren vor dem 2. Februar.\n\n### Beispiel 2: Kennungen, Tausenderzeichen und fehlende Werte\n\n#### Frage und Datenlage\n\nEine Artikelliste mit vier Spalten: Kennung, Postleitzahl `8001`, `0815`,\n`3011`, Menge `1.234`, `987` und ein fehlender Wert, Preis mit Dezimalkomma.\nWas macht der Import daraus, wenn man ihn raten lässt?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncsv2 <- c(\"id;plz;menge;preis\",\n          \"1;8001;1.234;12,50\",\n          \"2;0815;987;9,90\",\n          \"3;3011;;7,25\")\npfad2 <- tempfile(fileext = \".csv\")\nwriteLines(csv2, pfad2)\n\ngeraten <- read_csv2(pfad2, show_col_types = FALSE)\nsapply(geraten, class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         id         plz       menge       preis \n  \"numeric\" \"character\"   \"numeric\"   \"numeric\" \n```\n\n\n:::\n\n```{.r .cell-code}\ngeraten$plz\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"8001\" \"0815\" \"3011\"\n```\n\n\n:::\n\n```{.r .cell-code}\ngeraten$menge\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1234  987   NA\n```\n\n\n:::\n\n```{.r .cell-code}\ngenau <- read_csv2(pfad2, show_col_types = FALSE,\n                   col_types = cols(plz = col_character(),\n                                    menge = col_integer()))\ngenau$plz\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"8001\" \"0815\" \"3011\"\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(genau$menge, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 987\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ncsv2 = \"id;plz;menge;preis\\n1;8001;1.234;12,50\\n2;0815;987;9,90\\n3;3011;;7,25\\n\"\npfad2 = ordner / \"artikel.csv\"\n_ = pfad2.write_text(csv2, encoding=\"utf-8\")\n\ngeraten = pd.read_csv(pfad2, sep=\";\", decimal=\",\")\nprint(geraten.dtypes.astype(str).to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'id': 'int64', 'plz': 'int64', 'menge': 'object', 'preis': 'float64'}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(geraten[\"plz\"].tolist(), geraten[\"menge\"].tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[8001, 815, 3011] ['1.234', '987', nan]\n```\n\n\n:::\n\n```{.python .cell-code}\ntry:                                   # Tausenderzeichen und Int64 zusammen\n    pd.read_csv(pfad2, sep=\";\", decimal=\",\", thousands=\".\",\n                dtype={\"plz\": str, \"menge\": \"Int64\"})\nexcept TypeError as fehler:\n    print(type(fehler).__name__, str(fehler)[:60])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTypeError cannot safely cast non-equivalent float64 to int64\n```\n\n\n:::\n\n```{.python .cell-code}\ngenau = pd.read_csv(pfad2, sep=\";\", decimal=\",\", thousands=\".\",\n                    dtype={\"plz\": str})\ngenau[\"menge\"] = genau[\"menge\"].astype(\"Int64\")\nprint(genau[\"plz\"].tolist(), genau[\"menge\"].tolist(), genau[\"menge\"].sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['8001', '0815', '3011'] [1234, 987, <NA>] 2221\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Spalte | geraten in pandas | geraten in R | Erklärung |\n|---|---|---|---|\n| `plz` | **`[8001, 815, 3011]`** | **815** statt `0815` | Beide machen aus der Kennung eine Zahl, und die führende Null ist weg. Eine Postleitzahl ist Text. |\n| `menge` | Text: `['1.234', '987', nan]` | **1234**, 987, `NA` | Hier trennen sich die Sprachen: `read_csv2` kennt den Punkt als Tausenderzeichen, pandas braucht `thousands=\".\"` und liest die Spalte sonst als Text. |\n| `preis` | `float64` | `numeric` | Das Dezimalkomma war angegeben. |\n| `thousands` mit `dtype=\"Int64\"` | **`TypeError`** | | pandas wandelt zuerst in Gleitkomma und kann dann nicht mehr verlustfrei in die ganzzahlige Spalte giessen. Erst lesen, dann `astype(\"Int64\")`. |\n| mit Vorgaben | `['8001', '0815', '3011']`, Mengen `[1234, 987, <NA>]`, Summe **2221** | `0815` bleibt, Summe 2221 | `Int64` mit grossem I trägt fehlende Werte, `int64` nicht. |\n\n#### Interpretation und Ergebnissatz\n\nZwei Fehler entstehen hier stumm: die verlorene führende Null und die\nMengenspalte, die in pandas Text bleibt. Die erste fällt später auf, wenn ein\nJoin auf die Postleitzahl nichts findet, die zweite beim ersten Rechnen.\n`read_csv2` nimmt einem in R mehr ab, dafür ist in pandas jede Annahme im\nAufruf sichtbar.\n\n> Ohne Vorgaben wird aus der Kennung `0815` die Zahl 815, und die Menge\n> `1.234` bleibt in pandas Text, während `read_csv2` daraus 1234 macht. Mit\n> `dtype`, `thousands` und `Int64` stehen am Ende die Mengen 1234, 987 und ein\n> fehlender Wert mit der Summe 2221.\n\n### Beispiel 3: Kodierung beim Import\n\n#### Frage und Datenlage\n\nEine UTF-8-Datei mit Umlauten in Spaltenname und Wert (`gerät`, `grösse`,\n`Fräse`). Was passiert beim Lesen mit der falschen Kodierung?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npfad3 <- tempfile(fileext = \".csv\")\nwriteLines(c(\"gerät;grösse\", \"Fräse;12,5\"), pfad3, useBytes = TRUE)\n\nutf <- read_csv2(pfad3, show_col_types = FALSE)\nnames(utf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"gerät\"  \"grösse\"\n```\n\n\n:::\n\n```{.r .cell-code}\nutf[[1]][1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Fräse\"\n```\n\n\n:::\n\n```{.r .cell-code}\nlat <- read_csv2(pfad3, show_col_types = FALSE,\n                 locale = locale(encoding = \"latin1\", decimal_mark = \",\"))\nnames(lat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"gerÃ¤t\"  \"grÃ¶sse\"\n```\n\n\n:::\n\n```{.r .cell-code}\nlat[[1]][1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"FrÃ¤se\"\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\npfad3 = ordner / \"umlaute.csv\"\n_ = pfad3.write_bytes(\"gerät;grösse\\nFräse;12,5\\n\".encode(\"utf-8\"))\n\nutf = pd.read_csv(pfad3, sep=\";\", decimal=\",\", encoding=\"utf-8\")\nprint(list(utf.columns), utf.iloc[0, 0])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['gerät', 'grösse'] Fräse\n```\n\n\n:::\n\n```{.python .cell-code}\nlat = pd.read_csv(pfad3, sep=\";\", decimal=\",\", encoding=\"latin-1\")\nprint(list(lat.columns), lat.iloc[0, 0])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['gerÃ¤t', 'grÃ¶sse'] FrÃ¤se\n```\n\n\n:::\n\n```{.python .cell-code}\ntry:\n    pd.read_csv(pfad3, sep=\";\", encoding=\"ascii\")\nexcept UnicodeDecodeError as fehler:\n    print(type(fehler).__name__)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nUnicodeDecodeError\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Lesart | Spaltennamen | erster Wert | Erklärung |\n|---|---|---|---|\n| UTF-8 | `gerät`, `grösse` | `Fräse` | richtig |\n| Latin-1 | **`gerÃ¤t`, `grÃ¶sse`** | **`FrÃ¤se`** | Kein Fehler, sondern verdorbener Text. Betroffen sind auch die **Spaltennamen**, und ab da scheitert jeder Zugriff über den Namen. |\n| ASCII | | **`UnicodeDecodeError`** | ASCII bricht bei Bytes über 127 ab. |\n\nDas Erkennungszeichen bleibt dasselbe wie beim Dateizugriff: `Ã¤` für `ä`,\n`Ã¶` für `ö`. Wer es sieht, hat eine UTF-8-Datei als Latin-1 gelesen.\n\n#### Interpretation und Ergebnissatz\n\nBeim Import ist die falsche Kodierung schlimmer als beim blossen Lesen einer\nTextdatei, weil sie die **Spaltennamen** trifft. Ein `df[\"gerät\"]` findet die\nSpalte dann nicht, und die Fehlermeldung nennt einen Schlüssel, der auf dem\nBildschirm richtig aussieht. Deshalb gehört die Kodierung in jeden\nImportaufruf.\n\n> Mit Latin-1 gelesen heisst die Spalte `gerÃ¤t` und der Wert `FrÃ¤se`, ohne\n> jede Fehlermeldung; mit ASCII bricht der Import mit einem\n> `UnicodeDecodeError` ab. Nur mit `encoding=\"utf-8\"` stimmen Spaltennamen und\n> Werte.\n\n### Beispiel 4: Verschachteltes JSON flach machen\n\n#### Frage und Datenlage\n\nDie Antwort einer Schnittstelle: eine Anlage, darin eine Liste von Messungen,\nund jede Messung enthält wiederum ein Objekt `sensor` mit Typ und\nSeriennummer. Wie wird daraus eine Tabelle?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nantwort <- list(anlage = \"Werk Nord\", messungen = list(\n  list(id = 1, wert = 12.4, sensor = list(typ = \"A\", seriennummer = \"S-1\")),\n  list(id = 2, wert = 9.8,  sensor = list(typ = \"B\", seriennummer = \"S-2\"))))\n\npfad4 <- tempfile(fileext = \".json\")\njsonlite::write_json(antwort, pfad4, auto_unbox = TRUE)\n\nroh <- jsonlite::fromJSON(pfad4)\nnames(roh)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"anlage\"    \"messungen\"\n```\n\n\n:::\n\n```{.r .cell-code}\nnames(roh$messungen)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"id\"     \"wert\"   \"sensor\"\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(roh$messungen$sensor)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"data.frame\"\n```\n\n\n:::\n\n```{.r .cell-code}\ntabelle <- jsonlite::flatten(roh$messungen)\nnames(tabelle)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"id\"                  \"wert\"                \"sensor.typ\"         \n[4] \"sensor.seriennummer\"\n```\n\n\n:::\n\n```{.r .cell-code}\ntabelle\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  id wert sensor.typ sensor.seriennummer\n1  1 12.4          A                 S-1\n2  2  9.8          B                 S-2\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nantwort = {\"anlage\": \"Werk Nord\", \"messungen\": [\n    {\"id\": 1, \"wert\": 12.4, \"sensor\": {\"typ\": \"A\", \"seriennummer\": \"S-1\"}},\n    {\"id\": 2, \"wert\": 9.8, \"sensor\": {\"typ\": \"B\", \"seriennummer\": \"S-2\"}}]}\npfad4 = ordner / \"antwort.json\"\n_ = pfad4.write_text(json.dumps(antwort, ensure_ascii=False), encoding=\"utf-8\")\n\nroh = pd.read_json(pfad4)\nprint(roh.shape, list(roh.columns))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(2, 2) ['anlage', 'messungen']\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(roh[\"messungen\"].iloc[0])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'id': 1, 'wert': 12.4, 'sensor': {'typ': 'A', 'seriennummer': 'S-1'}}\n```\n\n\n:::\n\n```{.python .cell-code}\ntabelle = pd.json_normalize(antwort[\"messungen\"], sep=\"_\")\nprint(list(tabelle.columns))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['id', 'wert', 'sensor_typ', 'sensor_seriennummer']\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(tabelle.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n id  wert sensor_typ sensor_seriennummer\n  1  12.4          A                 S-1\n  2   9.8          B                 S-2\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Schritt | Python | R | Erklärung |\n|---|---|---|---|\n| roh eingelesen | Form (2, 2), Spalten `anlage`, `messungen` | Liste mit `anlage` und `messungen` | Die Spalte `messungen` enthält **Dictionaries**, keine Werte. Rechnen lässt sich damit nicht. |\n| eine Zelle | das ganze Dictionary mit `sensor` darin | `sensor` ist ein eigener Data Frame | Die Verschachtelung steckt in der Zelle. |\n| flach gemacht | Spalten `id`, `wert`, `sensor_typ`, `sensor_seriennummer` | `id`, `wert`, `sensor.typ`, `sensor.seriennummer` | `json_normalize` beziehungsweise `jsonlite::flatten`. Nur der Trenner unterscheidet sich, Unterstrich gegen Punkt. |\n| Tabelle | zwei Zeilen mit Werten 12.4 und 9.8 | dieselben zwei Zeilen | Jetzt ist es eine gewöhnliche Tabelle. |\n\n#### Interpretation und Ergebnissatz\n\nJSON aus einer Schnittstelle ist fast nie flach. Wer die eingelesene Struktur\nungeprüft weiterreicht, hat Spalten, die Objekte enthalten, und stolpert erst\nbeim Gruppieren darüber. Das Flachmachen ist ein eigener Arbeitsschritt und\ngehört unmittelbar hinter den Import; die Namen wie `sensor_typ` dokumentieren\ndabei, woher ein Wert stammt.\n\n> Eingelesen enthält die Spalte `messungen` ganze Objekte; erst\n> `json_normalize` beziehungsweise `jsonlite::flatten` macht daraus eine\n> Tabelle mit den Spalten `id`, `wert`, `sensor_typ` und `sensor_seriennummer`.\n\n### Beispiel 5: Die Rundreise durch CSV\n\n#### Frage und Datenlage\n\nEine bereinigte Tabelle mit Datum, Kategorie und einer ganzzahligen Spalte\nmit einem fehlenden Wert wird als CSV geschrieben und wieder gelesen. Kommt\ndasselbe zurück?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- data.frame(datum = as.Date(c(\"2026-03-01\", \"2026-03-02\")),\n                 typ   = factor(c(\"A\", \"B\")),\n                 menge = c(5L, NA))\nsapply(df, class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    datum       typ     menge \n   \"Date\"  \"factor\" \"integer\" \n```\n\n\n:::\n\n```{.r .cell-code}\npfad5 <- tempfile(fileext = \".csv\")\nwrite_csv(df, pfad5)\nreadLines(pfad5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"datum,typ,menge\" \"2026-03-01,A,5\"  \"2026-03-02,B,NA\"\n```\n\n\n:::\n\n```{.r .cell-code}\nzurueck <- read_csv(pfad5, show_col_types = FALSE)\nsapply(zurueck, class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      datum         typ       menge \n     \"Date\" \"character\"   \"numeric\" \n```\n\n\n:::\n\n```{.r .cell-code}\npfad6 <- tempfile(fileext = \".rds\")\nsaveRDS(df, pfad6)\nidentical(readRDS(pfad6), df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndf = pd.DataFrame({\"datum\": pd.to_datetime([\"2026-03-01\", \"2026-03-02\"]),\n                   \"typ\": pd.Categorical([\"A\", \"B\"]),\n                   \"menge\": pd.array([5, None], dtype=\"Int64\")})\nprint(df.dtypes.astype(str).to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'datum': 'datetime64[ns]', 'typ': 'category', 'menge': 'Int64'}\n```\n\n\n:::\n\n```{.python .cell-code}\npfad5 = ordner / \"rund.csv\"\ndf.to_csv(pfad5, index=False)\nprint(pfad5.read_text(encoding=\"utf-8\").replace(\"\\n\", \" | \"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndatum,typ,menge | 2026-03-01,A,5 | 2026-03-02,B, | \n```\n\n\n:::\n\n```{.python .cell-code}\nzurueck = pd.read_csv(pfad5)\nprint(zurueck.dtypes.astype(str).to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'datum': 'object', 'typ': 'object', 'menge': 'float64'}\n```\n\n\n:::\n\n```{.python .cell-code}\npfad6 = ordner / \"rund.pkl\"\ndf.to_pickle(pfad6)\nprint(pd.read_pickle(pfad6).equals(df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Spalte | vorher | nach CSV in Python | nach CSV in R | Erklärung |\n|---|---|---|---|---|\n| `datum` | `datetime64[ns]` | **`object`** (Text) | `Date` | readr erkennt das ISO-Format beim Lesen wieder, pandas nicht ohne `parse_dates`. |\n| `typ` | `category` | **`object`** | **`character`** | Die Kategorie mit ihren Stufen ist weg, in beiden Sprachen. |\n| `menge` | `Int64` mit fehlendem Wert | **`float64`**, der Wert wird zu `NaN` | `numeric` | Die CSV-Zeile lautet `2026-03-02,B,`; ob dort eine leere Zahl, ein Text oder nichts stand, ist der Datei nicht anzusehen. |\n| Datei | | drei Zeilen: Kopfzeile, `2026-03-01,A,5` und `2026-03-02,B,` | | Kein Typ in Sicht; die letzte Zelle ist schlicht leer. |\n| mit Pickle bzw. RDS | | **`True`**, alles identisch | `TRUE` | Das sprachgebundene Format bringt Datum, Kategorie und fehlenden Wert unverändert zurück. |\n\n#### Interpretation und Ergebnissatz\n\nCSV ist ein Textformat, und Text hat keine Typen. Jede Bereinigung, die im\nTyp steckt (Datum, geordnete Kategorie, ganze Zahl mit fehlendem Wert), muss\nnach dem Einlesen wiederholt werden. Für den Austausch ist CSV trotzdem\nrichtig, weil es jedes Programm liest; für den eigenen Zwischenstand nimmt man\nRDS, Pickle oder Parquet, und für regelmässige Importe schreibt man die\nTypvorgaben einmal auf und verwendet sie wieder.\n\n> Nach der Rundreise durch CSV ist aus dem Datum Text geworden, aus der\n> Kategorie Text und aus der ganzzahligen Spalte eine Gleitkommaspalte; nur\n> `to_pickle` beziehungsweise `saveRDS` liefert die Tabelle unverändert\n> zurück.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEine Spalte kommt beim Import als Text an, obwohl nur Zahlen darin stehen.\nDas Dezimalzeichen ist richtig eingestellt. Was ist die nächstliegende\nUrsache?\n\n- [x] Ein einzelner Sonderwert, etwa ein Strich für einen fehlenden Wert oder\n      ein Tausenderpunkt ~ Richtig. Ein einziger solcher Eintrag genügt, weil\n      eine Spalte nur einen Typ trägt. In Beispiel 2 macht `1.234` genau das.\n- [ ] Die Datei ist zu gross ~ Die Grösse beeinflusst den erkannten Typ nicht.\n- [ ] Zahlen lassen sich nur aus Excel-Dateien lesen ~ Der Import aus Text\n      funktioniert, er muss nur richtig eingestellt sein.\n:::\n\n::: {.quiz}\nWarum sollte das Datum direkt beim Import umgewandelt werden und nicht erst\nkurz vor der Grafik?\n\n- [ ] Weil die Umwandlung später länger dauert ~ Die Rechenzeit ist nicht das\n      Problem.\n- [x] Weil jeder Schritt dazwischen sonst mit Text arbeitet und falsch\n      sortiert oder gruppiert ~ Richtig. Als Text steht der 1. März vor dem\n      2. Februar, und wer nach Monat gruppiert, gruppiert nach Zeichenketten.\n- [ ] Weil ggplot2 keine Datumsangaben darstellen kann ~ Kann es, sofern der\n      Typ stimmt.\n:::\n\n::: {.quiz}\nNach einem Import steht in der Spalte `plz` die Zahl 815 statt `0815`. Wie\nverhindert man das?\n\n- [x] Die Spalte beim Import als Text vorgeben ~ Richtig, mit\n      `col_character()` beziehungsweise `dtype={\"plz\": str}`. Nachträglich\n      lässt sich die Null nur raten, denn 815 und 0815 sind als Zahl\n      dasselbe.\n- [ ] Nach dem Import mit `str_pad` auffüllen ~ Das hilft nur, wenn alle\n      Kennungen dieselbe Länge haben; sonst rät man.\n- [ ] Die Spalte in Excel formatieren ~ Die Formatierung ändert nichts am\n      Inhalt der CSV.\n:::\n\n::: {.quiz}\nDie Spaltennamen einer eingelesenen Tabelle lauten `gerÃ¤t` und `grÃ¶sse`.\nWas ist passiert, und was ist die Folge?\n\n- [x] Eine UTF-8-Datei wurde als Latin-1 gelesen; jeder Zugriff über den\n      Spaltennamen scheitert ~ Richtig. Der Fehler trifft nicht nur die Werte,\n      sondern die Namen, und die Meldung nennt dann einen Schlüssel, der\n      richtig aussieht.\n- [ ] Die Datei ist beschädigt ~ Die Bytes sind in Ordnung, nur ihre Deutung\n      ist falsch.\n- [ ] Das Trennzeichen war falsch ~ Das ergäbe eine Spalte zu wenig, keine\n      verdorbenen Umlaute.\n:::\n\n::: {.quiz}\nEine bereinigte Tabelle mit Datum und geordneter Kategorie wird als CSV\nabgelegt und am nächsten Tag wieder eingelesen. Was ist zu erwarten?\n\n- [x] Datum und Kategorie sind Text, die Bereinigung muss wiederholt werden ~\n      Richtig, wie Beispiel 5 zeigt. Für Zwischenstände sind RDS, Pickle oder\n      Parquet die richtige Wahl.\n- [ ] Alles kommt unverändert zurück, CSV speichert die Typen mit ~ CSV ist\n      ein Textformat ohne Typinformation.\n- [ ] Die Datei lässt sich nicht mehr lesen ~ Lesen lässt sie sich immer,\n      genau darin liegt ihr Wert.\n:::\n\n## Verlinkte Ressourcen\n\n- [readr: Import in R](https://readr.tidyverse.org/)\n- [pandas: Ein- und Ausgabe](https://pandas.pydata.org/docs/user_guide/io.html)\n- [jsonlite: JSON in R](https://jeroen.r-universe.dev/jsonlite)\n",
    "supporting": [
      "datenimport-formate_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}