{
  "hash": "082f475ed8d34f55c2ee46fb707f9cc0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Storytelling mit Daten\"\ndescription: \"Aufbau, Betonung und Text als Teil der Grafik.\"\ncategories: [\"Storytelling\", \"Kommunikation\", \"Visualisierung\", \"R\", \"Python\"]\nquelle: [\"DAVI\"]\nseitentyp: konzept\nstand: entwurf\norder: 100\n---\n\n\n\n\n\n## Kernideen\n\n- Eine Grafik ohne Text ist eine Behauptung ohne Satz.\n- Der **Fünf-Sekunden-Test** prüft, ob die Aussage ankommt.\n- Reihenfolge erzeugt Bedeutung: Ausgangslage, Spannung, Auflösung.\n- **Betonen heisst zurücknehmen** — und wie stark betont wird, lässt sich\n  ausrechnen.\n- Zwei gleichzeitig steigende Kurven belegen keine Wirkung. Dafür braucht es\n  eine **Vergleichsgruppe**.\n- Wie sicher eine Prognose aussieht, entscheidet die **Modellwahl**, nicht die\n  Daten.\n- Die Handlungsempfehlung gehört dazu, sonst bleibt die Grafik folgenlos.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Zielbild und Publikum](zielbild-audience.qmd) für die\nEntscheidung, die gestützt werden soll, und\n[Wahrnehmung und Kodierung](wahrnehmung-kodierung.qmd) für die Mittel der\nBetonung.\n:::\n\n### Der Fünf-Sekunden-Test\n\nDie schnellste und härteste Prüfung: Man zeigt jemandem die Grafik fünf\nSekunden lang, nimmt sie weg und fragt, was er gesehen hat.\n\nDrei mögliche Antworten, drei verschiedene Befunde:\n\n- **Die Aussage kommt zurück.** Die Grafik funktioniert.\n- **Eine andere Aussage kommt zurück.** Die Betonung liegt falsch: das Auge\n  wurde von etwas anderem gefangen als von der Botschaft.\n- **Nur eine Beschreibung kommt zurück** (\"ein paar Balken, blau\"). Es fehlt die\n  Führung; niemand weiss, worauf zu achten ist.\n\nDer Test funktioniert auch allein: Grafik anzeigen, Bildschirm für fünf\nSekunden ansehen, wegdrehen und den Satz aufschreiben, den man mitgenommen hat.\n\n### Text ist Teil der Grafik\n\nDie verbreitetste Sparmassnahme am falschen Ort ist, den Text wegzulassen.\nVier Textelemente tragen Bedeutung:\n\n| Element | Aufgabe | Häufiger Fehler |\n|---|---|---|\n| Titel | die Aussage in einem Satz | beschreibt nur, was zu sehen ist |\n| Achsenbeschriftung | was gemessen wird, in welcher Einheit | fehlt oder nennt den Spaltennamen aus der Datei |\n| Annotation | erklärt die eine auffällige Stelle | fehlt, obwohl die Stelle die Aussage trägt |\n| Quelle und Stand | Nachvollziehbarkeit | fehlt, sobald die Grafik weitergereicht wird |\n\nEine Annotation direkt an der Stelle, um die es geht, ersetzt eine halbe Seite\nErklärtext darunter. Sie ist auch der Grund, warum Legenden oft überflüssig\nsind: Wer die Serien direkt beschriftet, spart dem Auge den Weg zur Legende und\nzurück.\n\n### Reihenfolge erzeugt Bedeutung\n\nEine Folge von Grafiken erzählt etwas, das eine einzelne nicht kann. Das\nbewährte Muster hat drei Teile:\n\n1. **Ausgangslage.** Was war der Stand, den alle kennen? Diese Grafik darf\n   langweilig sein, sie stellt den gemeinsamen Boden her.\n2. **Spannung.** Was ist anders als erwartet? Hier liegt die eigentliche\n   Beobachtung, und hier gehört die stärkste Betonung hin.\n3. **Auflösung.** Was folgt daraus, und was ist zu tun? Ohne diesen Teil bleibt\n   die Beobachtung folgenlos.\n\nWer nur eine Grafik hat, baut dieselbe Struktur in Titel, Annotation und\nBildunterschrift ein.\n\n### Betonen heisst zurücknehmen\n\nBetonung entsteht nicht dadurch, dass etwas lauter wird, sondern dadurch, dass\nalles andere leiser wird. Die Mittel, in der Reihenfolge ihrer Wirksamkeit:\n\n- alles Nebensächliche in Grau, das Wichtige in einer Farbe\n- die relevante Serie dicker, die übrigen dünn\n- die Kernzahl direkt beschriften, statt sie ablesen zu lassen\n- Zierrat entfernen, siehe\n  [Wahrnehmung und Kodierung](wahrnehmung-kodierung.qmd)\n\nWer alles betont, betont nichts. Mehr als ein Akzent je Grafik ist fast immer\neiner zu viel. Beispiel 1 rechnet aus, wie viel das ausmacht.\n\n### Die Aussage muss die Daten decken\n\nStorytelling verführt zum Zuspitzen, und genau da entstehen die Fehler, die\nspäter teuer werden. Drei Grenzen:\n\n- **Kein Kausalsatz ohne Grundlage.** \"Die Kampagne hat den Umsatz gesteigert\"\n  braucht mehr als zwei Kurven, die gleichzeitig steigen — Beispiel 2.\n- **Keine Sicherheit vortäuschen.** Wo Unsicherheit besteht, gehört sie in die\n  Grafik: Konfidenzband, Fehlerbalken oder wenigstens ein Satz — Beispiel 5.\n- **Kein Ausschnitt ohne Begründung.** Der gewählte Zeitraum darf nicht die\n  Aussage tragen, siehe\n  [irreführende Darstellungen](irrefuehrende-darstellungen.qmd).\n\n### Was am Ende dasteht\n\nEine brauchbare Abgabe beantwortet vier Fragen, und zwar sichtbar in der Grafik\noder unmittelbar daneben:\n\n1. Worum geht es (Titel mit Aussage)\n2. Woran ist das zu sehen (Betonung, Annotation)\n3. Wie sicher ist es (Unsicherheit, Stichprobenumfang, Zeitraum)\n4. Was folgt daraus (Empfehlung oder offene Frage)\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Wie stark ein Akzent wirklich betont\n\n#### Frage und Datenlage\n\nAcht Serien, eine davon ist die Aussage. Einmal alle in kräftigen Farben,\neinmal sieben grau und eine rot. Gemessen wird das **visuelle Gewicht** jeder\nSerie: Pfadlänge mal Linienstärke mal Kontrast zum Hintergrund.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nZ <- normalmatrix(5151, 8, 24)\nzeit <- 0:23\nniveau <- seq(40, 110, length.out = 8)\nreihen <- niveau + Z * 5\nziel <- 4                                  # die Serie, um die es geht\nreihen[ziel, ] <- reihen[ziel, ] + seq(0, 25, length.out = 24)\n\nbunt <- c(\"#1f77b4\", \"#ff7f0e\", \"#2ca02c\", \"#d62728\",\n          \"#9467bd\", \"#8c564b\", \"#e377c2\", \"#17becf\")\nmit_akzent <- rep(neutral, 8); mit_akzent[ziel] <- akzent\ndicke_bunt <- rep(1.5, 8)\ndicke_akzent <- rep(1.0, 8); dicke_akzent[ziel] <- 2.5\n\npfadlaenge <- function(y) {\n  dx <- diff(zeit) / (max(zeit) - min(zeit))\n  dy <- diff(y) / (max(reihen) - min(reihen))\n  sum(sqrt(dx^2 + dy^2))\n}\n\ngewichte <- function(pal, dicke) {\n  sapply(1:8, function(i) pfadlaenge(reihen[i, ]) * dicke[i] *\n           kontrast(pal[i], \"#FFFFFF\"))\n}\n\nfor (nm in c(\"alles bunt\", \"ein Akzent\")) {\n  g <- if (nm == \"alles bunt\") gewichte(bunt, dicke_bunt) else\n    gewichte(mit_akzent, dicke_akzent)\n  cat(sprintf(\"%-12s Zielserie %6.2f, Mittel der übrigen %5.2f, Verhältnis %5.2f\\n\",\n              nm, g[ziel], mean(g[-ziel]), g[ziel] / mean(g[-ziel])))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nalles bunt   Zielserie  14.66, Mittel der übrigen 10.12, Verhältnis  1.45\nein Akzent   Zielserie  33.40, Mittel der übrigen  3.13, Verhältnis 10.66\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(pfadlaenge_ziel = pfadlaenge(reihen[ziel, ]),\n        pfadlaenge_uebrige = mean(sapply((1:8)[-ziel],\n                                         function(i) pfadlaenge(reihen[i, ])))), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   pfadlaenge_ziel pfadlaenge_uebrige \n             1.946              1.854 \n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nmatplot(zeit, t(reihen), type = \"l\", lty = 1, lwd = dicke_bunt, col = bunt,\n        xlab = \"Monat\", ylab = \"Wert\", main = \"alles bunt\")\nmatplot(zeit, t(reihen), type = \"l\", lty = 1, lwd = dicke_akzent,\n        col = mit_akzent, xlab = \"Monat\", ylab = \"Wert\", main = \"ein Akzent\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 1: links alles bunt, rechts ein Akzent.](storytelling_files/figure-html/fig-b1-st-r-1.png){#fig-b1-st-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nZ = normalmatrix(5151, 8, 24)\nzeit = np.arange(24)\nniveau = np.linspace(40, 110, 8)\nreihen = niveau[:, None] + Z * 5\nziel = 3\nreihen[ziel] = reihen[ziel] + np.linspace(0, 25, 24)\n\nbunt = [\"#1f77b4\", \"#ff7f0e\", \"#2ca02c\", \"#d62728\",\n        \"#9467bd\", \"#8c564b\", \"#e377c2\", \"#17becf\"]\nmit_akzent = [NEUTRAL] * 8\nmit_akzent[ziel] = AKZENT\ndicke_bunt = [1.5] * 8\ndicke_akzent = [1.0] * 8\ndicke_akzent[ziel] = 2.5\n\n\ndef pfadlaenge(y):\n    dx = np.diff(zeit) / (zeit.max() - zeit.min())\n    dy = np.diff(y) / (reihen.max() - reihen.min())\n    return float(np.sum(np.sqrt(dx ** 2 + dy ** 2)))\n\n\ndef gewichte(pal, dicke):\n    return np.array([pfadlaenge(reihen[i]) * dicke[i] * kontrast(pal[i], \"#FFFFFF\")\n                     for i in range(8)])\n\n\nfor nm, pal, dicke in [(\"alles bunt\", bunt, dicke_bunt),\n                       (\"ein Akzent\", mit_akzent, dicke_akzent)]:\n    g = gewichte(pal, dicke)\n    rest = np.delete(g, ziel)\n    print(f\"{nm:<12} Zielserie {g[ziel]:6.2f}, Mittel der übrigen {rest.mean():5.2f},\"\n          f\" Verhältnis {g[ziel] / rest.mean():5.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nalles bunt   Zielserie  14.66, Mittel der übrigen 10.12, Verhältnis  1.45\nein Akzent   Zielserie  33.40, Mittel der übrigen  3.13, Verhältnis 10.66\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"pfadlaenge_ziel\": round(pfadlaenge(reihen[ziel]), 3),\n       \"pfadlaenge_uebrige\":\n           round(float(np.mean([pfadlaenge(reihen[i])\n                                for i in range(8) if i != ziel])), 3)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'pfadlaenge_ziel': 1.946, 'pfadlaenge_uebrige': 1.854}\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nfor achse, (titel, pal, dicke) in zip(achsen,\n                                      [(\"alles bunt\", bunt, dicke_bunt),\n                                       (\"ein Akzent\", mit_akzent, dicke_akzent)]):\n    for i in range(8):\n        _ = achse.plot(zeit, reihen[i], lw=dicke[i], color=pal[i])\n    _ = achse.set_title(titel)\n    _ = achse.set_xlabel(\"Monat\")\n    _ = achse.set_ylabel(\"Wert\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Gegenüberstellung in Python.](storytelling_files/figure-html/fig-b1-st-py-1.png){#fig-b1-st-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Fassung | Gewicht der Zielserie | Mittel der übrigen | Verhältnis |\n|---|---|---|---|\n| alles bunt | 14.66 | 10.12 | **1.45** |\n| ein Akzent | 33.40 | 3.13 | **10.66** |\n\nPfadlänge der Zielserie **1.946**, Mittel der übrigen **1.854**.\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die Zielserie hat schon von sich aus etwas mehr Gewicht | Verhältnis 1.45 in der bunten Fassung. Sie steigt, ist also länger — 1.946 gegen 1.854. Die Daten helfen ein wenig mit. |\n| Mit einem Akzent steigt das Verhältnis auf **10.66** | Also mehr als das Siebenfache. **Und der grössere Teil davon kommt vom Zurücknehmen, nicht vom Hervorheben:** Das Mittel der übrigen fällt von 10.12 auf 3.13. |\n| Die Zielserie selbst gewinnt Faktor **2.3** | 33.40 gegen 14.66 — durch Farbe und Linienstärke. Die übrigen verlieren Faktor 3.2. Beide Richtungen zusammen ergeben den Gesamteffekt. |\n| Die Rechnung ist ein **Modell**, keine Messung des Blicks | Pfadlänge mal Stärke mal Kontrast ist eine grobe Näherung für \"wie viel Tinte fällt auf\". Sie genügt, um zwei Entwürfe zu vergleichen. |\n| Acht kräftige Farben verteilen die Aufmerksamkeit **gleichmässig** | Und gleichmässig verteilte Aufmerksamkeit ist genau das Gegenteil einer Aussage. |\n\n::: {.note-box}\n**Die Reihenfolge beim Gestalten folgt daraus:** zuerst alles zurücknehmen,\ndann genau eine Sache hervorheben. Wer umgekehrt anfängt, landet bei einer\nGrafik, in der drei Dinge wichtig aussehen.\n\n| Schritt | Wirkung im Beispiel |\n|---|---|\n| alles grau | Mittel der übrigen 10.12 → 3.13 |\n| Zielserie färben und verdicken | Zielserie 14.66 → 33.40 |\n| **zusammen** | Verhältnis 1.45 → **10.66** |\n:::\n\n#### Interpretation und Ergebnissatz\n\n> In der bunten Fassung hat die Zielserie das 1.45-Fache des mittleren\n> visuellen Gewichts der übrigen, mit einem Akzent das 10.66-Fache. Zwei\n> Drittel dieses Gewinns entstehen dadurch, dass die anderen Serien\n> zurückgenommen werden, nicht dadurch, dass die Zielserie hervorgehoben wird.\n\n### Beispiel 2: Zwei steigende Kurven sind kein Beleg\n\n#### Frage und Datenlage\n\nEine Kampagne läuft ab Monat 12 in der Testregion. Der Umsatz steigt danach um\n14.7 Prozent. Die Frage ist, was davon der Kampagne zuzuschreiben ist — und\ndafür braucht es die Kontrollregion, in der nichts passiert ist.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nZ <- normalmatrix(6262, 2, 24)\nmonat <- 0:23\nsaison <- 8 * sin(2 * pi * monat / 12)\ntest <- 100 + 1.0 * monat + saison + Z[1, ] * 4\nkontrolle <- 70 + 1.0 * monat + saison + Z[2, ] * 4\n\nvor <- 1:12; nach <- 13:24\nfor (nm in c(\"test\", \"kontrolle\")) {\n  x <- get(nm)\n  cat(sprintf(\"%-10s vorher %7.2f  nachher %7.2f  Zuwachs %+7.2f  relativ %+6.1f Prozent\\n\",\n              nm, mean(x[vor]), mean(x[nach]), mean(x[nach]) - mean(x[vor]),\n              100 * (mean(x[nach]) / mean(x[vor]) - 1)))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntest       vorher  103.28  nachher  118.47  Zuwachs  +15.18  relativ  +14.7 Prozent\nkontrolle  vorher   77.47  nachher   88.10  Zuwachs  +10.63  relativ  +13.7 Prozent\n```\n\n\n:::\n\n```{.r .cell-code}\ndd <- (mean(test[nach]) - mean(test[vor])) -\n  (mean(kontrolle[nach]) - mean(kontrolle[vor]))\nround(c(differenz_von_differenzen = dd,\n        korrelation = cor(test, kontrolle)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndifferenz_von_differenzen               korrelation \n                   4.5559                    0.8109 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Derselbe Effekt als Modell, mit Standardfehler\nlang <- data.frame(\n  wert = c(test, kontrolle),\n  ist_test = rep(c(1, 0), each = 24),\n  ist_nach = rep(c(rep(0, 12), rep(1, 12)), 2))\nmodell <- lm(wert ~ ist_test * ist_nach, data = lang)\nround(summary(modell)$coefficients[\"ist_test:ist_nach\", ], 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Estimate Std. Error    t value   Pr(>|t|) \n    4.5559     3.6632     1.2437     0.2202 \n```\n\n\n:::\n\n```{.r .cell-code}\npar(mar = c(4, 4, 2, 1))\nmatplot(monat, cbind(test, kontrolle), type = \"l\", lty = 1, lwd = 2,\n        col = c(akzent, \"grey45\"), xlab = \"Monat\", ylab = \"Umsatz\")\nabline(v = 11.5, lty = 2)\nlegend(\"topleft\", c(\"Test\", \"Kontrolle\"), col = c(akzent, \"grey45\"),\n       lty = 1, lwd = 2, bty = \"n\")\n```\n\n::: {.cell-output-display}\n![Beispiel 2: Testregion und Kontrollregion, Kampagnenstart in Monat 12.](storytelling_files/figure-html/fig-b2-st-r-3.png){#fig-b2-st-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nZ = normalmatrix(6262, 2, 24)\nmonat = np.arange(24)\nsaison = 8 * np.sin(2 * np.pi * monat / 12)\ntest = 100 + 1.0 * monat + saison + Z[0] * 4\nkontrolle = 70 + 1.0 * monat + saison + Z[1] * 4\n\nvor, nach = slice(0, 12), slice(12, 24)\nfor nm, x in [(\"test\", test), (\"kontrolle\", kontrolle)]:\n    print(f\"{nm:<10} vorher {x[vor].mean():7.2f}  nachher {x[nach].mean():7.2f}\"\n          f\"  Zuwachs {x[nach].mean() - x[vor].mean():+7.2f}\"\n          f\"  relativ {100 * (x[nach].mean() / x[vor].mean() - 1):+6.1f} Prozent\")\n\ndd = ((test[nach].mean() - test[vor].mean())\n      - (kontrolle[nach].mean() - kontrolle[vor].mean()))\nprint({\"differenz_von_differenzen\": round(float(dd), 4),\n       \"korrelation\": round(float(np.corrcoef(test, kontrolle)[0, 1]), 4)})\n\ny = np.concatenate([test, kontrolle])\nist_test = np.concatenate([np.ones(24), np.zeros(24)])\nist_nach = np.tile(np.concatenate([np.zeros(12), np.ones(12)]), 2)\nX = np.column_stack([np.ones(48), ist_test, ist_nach, ist_test * ist_nach])\nb = np.linalg.lstsq(X, y, rcond=None)[0]\nrest = y - X @ b\ns2 = (rest ** 2).sum() / (48 - 4)\nse = np.sqrt(s2 * np.linalg.inv(X.T @ X)[3, 3])\nprint({\"schaetzwert\": round(float(b[3]), 4), \"standardfehler\": round(float(se), 4),\n       \"t\": round(float(b[3] / se), 4),\n       \"p\": round(float(2 * stats.t.sf(abs(b[3] / se), 44)), 4)})\n\nfig, achse = plt.subplots(figsize=(7, 3.2))\n_ = achse.plot(monat, test, lw=2, color=AKZENT, label=\"Test\")\n_ = achse.plot(monat, kontrolle, lw=2, color=\"0.45\", label=\"Kontrolle\")\n_ = achse.axvline(11.5, ls=\"--\", color=\"black\")\n_ = achse.legend(frameon=False, loc=\"upper left\")\n_ = achse.set_xlabel(\"Monat\")\n_ = achse.set_ylabel(\"Umsatz\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselbe Gegenüberstellung in Python.](storytelling_files/figure-html/fig-b2-st-py-1.png){#fig-b2-st-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Region | vorher | nachher | Zuwachs | relativ |\n|---|---|---|---|---|\n| **Test** | 103.28 | 118.47 | **+15.18** | **+14.7 %** |\n| **Kontrolle** | 77.47 | 88.10 | **+10.63** | **+13.7 %** |\n\n| Kennzahl | Wert |\n|---|---|\n| Differenz von Differenzen | **+4.56** |\n| Standardfehler | 3.663 |\n| t | 1.244 |\n| **p** | **0.2202** |\n| Korrelation Test / Kontrolle | 0.8109 |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die Testregion wächst um **14.7 Prozent** | Zeigt man nur diese Kurve, ist die Geschichte fertig: \"Die Kampagne wirkt.\" |\n| Die Kontrollregion wächst um **13.7 Prozent** | Ohne Kampagne. Der grösste Teil des Zuwachses hat also nichts mit der Massnahme zu tun, sondern mit Trend und Saison. |\n| Es bleibt eine Differenz von **+4.56** | Das ist die einzige Zahl, die überhaupt der Kampagne zugeschrieben werden könnte — nicht +15.18. |\n| Und selbst die ist **nicht belegt** | Standardfehler 3.663, t = 1.24, p = 0.22. Bei 48 Beobachtungen reicht das nicht. |\n| Die beiden Regionen korrelieren mit **0.81** | Genau deshalb taugt die Kontrollregion als Vergleich: Sie macht Trend und Saison mit, nur die Kampagne nicht. |\n\n::: {.warning-box}\n**Die Titel, die hier möglich sind:**\n\n| Titel | zulässig? |\n|---|---|\n| \"Die Kampagne steigert den Umsatz um 15 Prozent\" | **nein** — der Vergleich fehlt |\n| \"Die Kampagne steigert den Umsatz um 4.6 Punkte\" | **nein** — der Effekt ist nicht belegt |\n| \"Umsatz nach der Kampagne um 15 Prozent höher\" | zulässig, aber irreführend ohne die Kontrollkurve |\n| \"**Kein nachweisbarer Kampagneneffekt: Die Vergleichsregion wächst gleich stark**\" | **ja** |\n\nDer letzte Titel ist der unbequemste und der einzige, der hält. Er ist auch\nder nützlichere: Er verhindert, dass die Kampagne aufgrund eines Scheineffekts\nwiederholt wird.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Testregion wächst nach der Kampagne um 14.7 Prozent, die Kontrollregion\n> ohne Kampagne um 13.7 Prozent. Die Differenz von Differenzen beträgt +4.56\n> mit einem Standardfehler von 3.66 (t = 1.24, p = 0.22) und ist damit nicht\n> belegt.\n\n### Beispiel 3: Ausgangslage, Spannung, Auflösung\n\n#### Frage und Datenlage\n\nDieselben Kampagnendaten, aber als Folge von drei Grafiken erzählt. Jede\nbeantwortet genau eine Frage, und jede hat ihre eigene Kennzahl.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschritt <- data.frame(\n  schritt = c(\"1 Ausgangslage\", \"2 Spannung\", \"3 Auflösung\"),\n  frage = c(\"Wie lief es bisher?\",\n            \"Was ist nach der Kampagne passiert?\",\n            \"Was folgt daraus?\"),\n  kennzahl = c(mean(test[vor]),\n               mean(test[nach]) - mean(test[vor]),\n               dd),\n  einheit = c(\"Umsatz im Mittel\", \"Zuwachs\", \"davon der Kampagne zuschreibbar\"))\nschritt$kennzahl <- round(schritt$kennzahl, 2)\nschritt\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         schritt                               frage kennzahl\n1 1 Ausgangslage                 Wie lief es bisher?   103.28\n2     2 Spannung Was ist nach der Kampagne passiert?    15.18\n3    3 Auflösung                   Was folgt daraus?     4.56\n                          einheit\n1                Umsatz im Mittel\n2                         Zuwachs\n3 davon der Kampagne zuschreibbar\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(anteil_der_dem_trend_zuzuschreiben_ist =\n          (1 - dd / (mean(test[nach]) - mean(test[vor]))) * 100), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nanteil_der_dem_trend_zuzuschreiben_ist \n                                    70 \n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 3), mar = c(4, 4, 3, 1))\nplot(monat[vor], test[vor], type = \"l\", lwd = 2, col = \"grey35\",\n     xlim = c(0, 23), ylim = range(c(test, kontrolle)),\n     xlab = \"Monat\", ylab = \"Umsatz\", main = \"1 Ausgangslage\")\nmatplot(monat, cbind(test, kontrolle), type = \"l\", lty = 1, lwd = 2,\n        col = c(akzent, neutral), xlab = \"Monat\", ylab = \"Umsatz\",\n        main = \"2 Spannung\")\nabline(v = 11.5, lty = 2)\nbarplot(c(Trend = mean(test[nach]) - mean(test[vor]) - dd, Kampagne = dd),\n        col = c(neutral, akzent), border = NA, ylab = \"Anteil am Zuwachs\",\n        main = \"3 Auflösung\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselbe Geschichte in drei Schritten.](storytelling_files/figure-html/fig-b3-st-r-3.png){#fig-b3-st-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nschritt = pd.DataFrame({\n    \"schritt\": [\"1 Ausgangslage\", \"2 Spannung\", \"3 Auflösung\"],\n    \"frage\": [\"Wie lief es bisher?\",\n              \"Was ist nach der Kampagne passiert?\",\n              \"Was folgt daraus?\"],\n    \"kennzahl\": [test[vor].mean(),\n                 test[nach].mean() - test[vor].mean(),\n                 dd],\n    \"einheit\": [\"Umsatz im Mittel\", \"Zuwachs\",\n                \"davon der Kampagne zuschreibbar\"]})\nschritt[\"kennzahl\"] = schritt[\"kennzahl\"].round(2)\nprint(schritt.to_string(index=False))\n\nzuwachs = test[nach].mean() - test[vor].mean()\nprint({\"anteil_der_dem_trend_zuzuschreiben_ist\":\n       round(float((1 - dd / zuwachs) * 100), 1)})\n\nfig, achsen = plt.subplots(1, 3, figsize=(7, 3))\n_ = achsen[0].plot(monat[:12], test[:12], lw=2, color=\"0.35\")\n_ = achsen[0].set_xlim(0, 23)\n_ = achsen[0].set_ylim(min(test.min(), kontrolle.min()),\n                       max(test.max(), kontrolle.max()))\n_ = achsen[0].set_title(\"1 Ausgangslage\")\n_ = achsen[1].plot(monat, test, lw=2, color=AKZENT)\n_ = achsen[1].plot(monat, kontrolle, lw=2, color=NEUTRAL)\n_ = achsen[1].axvline(11.5, ls=\"--\", color=\"black\")\n_ = achsen[1].set_title(\"2 Spannung\")\n_ = achsen[2].bar([\"Trend\", \"Kampagne\"], [zuwachs - dd, dd],\n                  color=[NEUTRAL, AKZENT])\n_ = achsen[2].set_title(\"3 Auflösung\")\n_ = achsen[2].set_ylabel(\"Anteil am Zuwachs\")\nfor achse in achsen[:2]:\n    _ = achse.set_xlabel(\"Monat\")\n    _ = achse.set_ylabel(\"Umsatz\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselben drei Schritte in Python.](storytelling_files/figure-html/fig-b3-st-py-1.png){#fig-b3-st-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Schritt | Frage | Kennzahl | Einheit |\n|---|---|---|---|\n| **1 Ausgangslage** | Wie lief es bisher? | **103.28** | Umsatz im Mittel |\n| **2 Spannung** | Was ist nach der Kampagne passiert? | **+15.18** | Zuwachs |\n| **3 Auflösung** | Was folgt daraus? | **+4.56** | davon der Kampagne zuschreibbar |\n\nDem allgemeinen Trend zuzuschreiben: **70.0 Prozent** des Zuwachses.\n\n| Beobachtung | Erklärung |\n|---|---|\n| Jeder Schritt hat **genau eine** Zahl | 103.28, dann +15.18, dann +4.56. Wer eine Folge baut, prüft daran, ob die Schritte wirklich verschiedene Aussagen tragen. |\n| Der erste Schritt ist **absichtlich langweilig** | Nur die Testregion vor der Kampagne. Er stellt den gemeinsamen Boden her, damit der zweite überhaupt als Überraschung wirken kann. |\n| Der zweite bringt die **Kontrollkurve** ins Bild | Das ist der Moment der Spannung: Die zweite Kurve macht dieselbe Bewegung mit. |\n| Der dritte zerlegt den Zuwachs | **70 Prozent Trend, 30 Prozent möglicher Kampagneneffekt** — und der ist statistisch nicht belegt. |\n| Die Reihenfolge lässt sich **nicht** umstellen | Der dritte Schritt ist ohne den zweiten unverständlich, der zweite ohne den ersten wirkungslos. Das unterscheidet eine Folge von drei Einzelgrafiken. |\n\n::: {.note-box}\n**Wenn nur eine Grafik zur Verfügung steht,** wandert dieselbe Struktur in die\nTextelemente:\n\n| Teil der Geschichte | Ort in der Grafik |\n|---|---|\n| Ausgangslage | Achsenbereich und Zeitraum, der den Vorher-Zustand mitzeigt |\n| Spannung | die Betonung — Farbe, Strichstärke, Annotation |\n| Auflösung | der Titel, der die Zahl nennt |\n\nKonkret hier: Titel \"70 Prozent des Zuwachses gehen auf den allgemeinen Trend\",\nbeide Kurven gezeigt, die Kampagnenlinie markiert.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Geschichte zerfällt in drei Schritte mit je einer Kennzahl: ein\n> Ausgangsniveau von 103.28, ein Zuwachs von +15.18 und ein davon der Kampagne\n> zuschreibbarer Anteil von +4.56. Damit gehen 70.0 Prozent des Zuwachses auf\n> den allgemeinen Trend.\n\n### Beispiel 4: Legende oder direkte Beschriftung\n\n#### Frage und Datenlage\n\nAcht Serien, einmal über eine Legende erschlossen und einmal direkt\nbeschriftet. Gezählt wird, wie oft das Auge zwischen Grafik und Legende hin und\nher muss — und wie weit der Weg ist.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_serien <- 8\nc(serien = n_serien,\n  blickwechsel_mit_legende = 2 * n_serien,\n  blickwechsel_direkt = 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  serien blickwechsel_mit_legende      blickwechsel_direkt \n                       8                       16                        0 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Wie weit ist der Weg? Legende rechts aussen, Serien ueber die Flaeche verteilt\nendwerte <- reihen[, 24]\nlegendenposition <- 1.15                      # rechts neben der Zeichenflaeche\nrelativ_y <- (endwerte - min(reihen)) / (max(reihen) - min(reihen))\nlegenden_y <- seq(0.95, 0.55, length.out = n_serien)\nweg <- sqrt((legendenposition - 1)^2 + (legenden_y - relativ_y)^2)\nround(c(mittlerer_weg = mean(weg), laengster_weg = max(weg),\n        summe_hin_und_zurueck = 2 * sum(weg)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        mittlerer_weg         laengster_weg summe_hin_und_zurueck \n                0.396                 0.839                 6.330 \n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nmatplot(zeit, t(reihen), type = \"l\", lty = 1, lwd = 1.4, col = bunt,\n        xlab = \"Monat\", ylab = \"Wert\", main = \"mit Legende\")\nlegend(\"topleft\", legend = paste0(\"S\", 1:8), col = bunt, lty = 1, cex = 0.6,\n       bty = \"n\", ncol = 2)\n\npar(mar = c(4, 4, 3, 4))\nmatplot(zeit, t(reihen), type = \"l\", lty = 1, lwd = dicke_akzent,\n        col = mit_akzent, xlab = \"Monat\", ylab = \"Wert\",\n        main = \"direkt beschriftet\", xlim = c(0, 27))\ntext(24, reihen[ziel, 24], paste0(\"S\", ziel), col = akzent, adj = 0, font = 2)\ntext(24, reihen[8, 24], \"S8\", col = \"grey55\", adj = 0, cex = 0.8)\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 4: links mit Legende, rechts direkt beschriftet.](storytelling_files/figure-html/fig-b4-st-r-3.png){#fig-b4-st-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nn_serien = 8\nprint({\"serien\": n_serien, \"blickwechsel_mit_legende\": 2 * n_serien,\n       \"blickwechsel_direkt\": 0})\n\nendwerte = reihen[:, -1]\nlegendenposition = 1.15\nrelativ_y = (endwerte - reihen.min()) / (reihen.max() - reihen.min())\nlegenden_y = np.linspace(0.95, 0.55, n_serien)\nweg = np.sqrt((legendenposition - 1) ** 2 + (legenden_y - relativ_y) ** 2)\nprint({\"mittlerer_weg\": round(float(weg.mean()), 3),\n       \"laengster_weg\": round(float(weg.max()), 3),\n       \"summe_hin_und_zurueck\": round(float(2 * weg.sum()), 3)})\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.4))\nfor i in range(8):\n    _ = achsen[0].plot(zeit, reihen[i], lw=1.4, color=bunt[i], label=f\"S{i + 1}\")\n_ = achsen[0].legend(fontsize=6, ncol=2, frameon=False, loc=\"upper left\")\n_ = achsen[0].set_title(\"mit Legende\")\nfor i in range(8):\n    _ = achsen[1].plot(zeit, reihen[i], lw=dicke_akzent[i], color=mit_akzent[i])\n_ = achsen[1].set_xlim(0, 27)\n_ = achsen[1].text(24, reihen[ziel, -1], f\"S{ziel + 1}\", color=AKZENT,\n                   fontweight=\"bold\")\n_ = achsen[1].text(24, reihen[7, -1], \"S8\", color=\"0.55\", fontsize=9)\n_ = achsen[1].set_title(\"direkt beschriftet\")\nfor achse in achsen:\n    _ = achse.set_xlabel(\"Monat\")\n    _ = achse.set_ylabel(\"Wert\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselbe Gegenüberstellung in Python.](storytelling_files/figure-html/fig-b4-st-py-1.png){#fig-b4-st-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | mit Legende | direkt beschriftet |\n|---|---|---|\n| Blickwechsel, um alle Serien zuzuordnen | **16** | **0** |\n| mittlerer Weg je Zuordnung (Anteil der Bildbreite) | **0.229** | — |\n| längster Weg | **0.514** | — |\n| Weglänge insgesamt, hin und zurück | **3.669** | — |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Acht Serien kosten **16 Blickwechsel** | Einmal hin zur Legende, einmal zurück, je Serie. Jeder davon ist eine Gelegenheit, die Spur zu verlieren. |\n| Der längste Weg beträgt **halbe Bildbreite** | Für die Serie, die am weitesten von ihrem Legendeneintrag entfernt verläuft. Die Zuordnung geschieht dabei über den Farbton — den ungenauesten Kanal. |\n| Direkt beschriftet fallen **alle** Wege weg | Der Name steht am Ende der Linie. Es gibt nichts zuzuordnen. |\n| Die rechte Fassung beschriftet nur **zwei** Serien | Die Zielserie und die oberste. Die übrigen brauchen keinen Namen, weil sie nur den Wertebereich zeigen. **Weglassen ist hier Teil der Antwort.** |\n| Eine Legende bleibt sinnvoll, wenn Linien sich **kreuzen** | Dann ist am Ende der Linie kein Platz. Meistens ist das ein Hinweis, dass zu viele Serien in einer Grafik sind — siehe [Wahrnehmung, Beispiel 4](wahrnehmung-kodierung.qmd). |\n\n::: {.note-box}\n**Die Zahlen sind ein Modell, kein Blickmessgerät.** Die Weglängen entstehen\naus der Geometrie der Grafik und nicht aus einer Studie. Sie taugen zum\nVergleich zweier Entwürfe, nicht als absolute Grösse.\n\nDer robuste Teil der Aussage steht ohne Rechnung fest: **Null Blickwechsel sind\nweniger als sechzehn.**\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Acht Serien über eine Legende zu erschliessen kostet 16 Blickwechsel mit\n> einem mittleren Weg von 0.229 Bildbreiten und einem längsten von 0.514. Bei\n> direkter Beschriftung entfallen alle Wege; im Beispiel genügen zwei\n> beschriftete Serien statt acht Legendeneinträge.\n\n### Beispiel 5: Wie sicher eine Prognose aussieht\n\n#### Frage und Datenlage\n\n36 Monate Verlauf, Prognose auf bis zu 24 Monate. Zwei Modelle, dieselben\nDaten: eine lineare Trendregression und eine Irrfahrt mit Drift. Wie\nunterscheiden sich die Intervalle?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 36\nreihe <- 50 + 0.8 * (0:(n - 1)) + cumsum(qnorm(lehmer(7373, n)) * 2)\nx <- 0:(n - 1)\n\nmodell <- lm(reihe ~ x)\ns <- summary(modell)$sigma\nxb <- mean(x); sxx <- sum((x - xb)^2)\naenderungen <- diff(reihe)\ndrift <- mean(aenderungen); sd_aenderung <- sd(aenderungen)\n\nround(c(trend_steigung = unname(coef(modell)[2]), trend_reststreuung = s,\n        irrfahrt_drift = drift, irrfahrt_sd = sd_aenderung), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    trend_steigung trend_reststreuung     irrfahrt_drift        irrfahrt_sd \n             0.740              2.886              0.619              1.986 \n```\n\n\n:::\n\n```{.r .cell-code}\nfor (h in c(1, 6, 12, 24)) {\n  x0 <- n - 1 + h\n  a <- qt(0.975, n - 2) * s * sqrt(1 + 1 / n + (x0 - xb)^2 / sxx)\n  b <- 1.96 * sd_aenderung * sqrt(h)\n  cat(sprintf(\"Horizont %2d: Trend +-%6.2f   Irrfahrt +-%6.2f   Faktor %5.2f\\n\",\n              h, a, b, b / a))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHorizont  1: Trend +-  6.20   Irrfahrt +-  3.89   Faktor  0.63\nHorizont  6: Trend +-  6.34   Irrfahrt +-  9.53   Faktor  1.50\nHorizont 12: Trend +-  6.56   Irrfahrt +- 13.48   Faktor  2.05\nHorizont 24: Trend +-  7.11   Irrfahrt +- 19.07   Faktor  2.68\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(letzter_wert = reihe[n],\n        prognose_trend_h24 = unname(coef(modell)[1] + coef(modell)[2] * (n - 1 + 24)),\n        prognose_irrfahrt_h24 = reihe[n] + drift * 24), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         letzter_wert    prognose_trend_h24 prognose_irrfahrt_h24 \n                68.53                 90.61                 83.40 \n```\n\n\n:::\n\n```{.r .cell-code}\nzukunft <- (n - 1) + 1:24\npar(mar = c(4, 4, 2, 1))\nplot(x, reihe, type = \"l\", lwd = 2, xlim = c(0, n + 24),\n     ylim = c(30, 115), xlab = \"Monat\", ylab = \"Wert\")\nlines(zukunft, coef(modell)[1] + coef(modell)[2] * zukunft, col = \"grey45\", lwd = 2)\nlines(zukunft, reihe[n] + drift * (1:24), col = akzent, lwd = 2)\nlines(zukunft, reihe[n] + drift * (1:24) + 1.96 * sd_aenderung * sqrt(1:24),\n      col = akzent, lty = 2)\nlines(zukunft, reihe[n] + drift * (1:24) - 1.96 * sd_aenderung * sqrt(1:24),\n      col = akzent, lty = 2)\nlegend(\"topleft\", c(\"Trendmodell\", \"Irrfahrt mit Drift\"),\n       col = c(\"grey45\", akzent), lty = 1, lwd = 2, bty = \"n\", cex = 0.8)\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselbe Reihe, zwei Prognosemodelle.](storytelling_files/figure-html/fig-b5-st-r-3.png){#fig-b5-st-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nn = 36\nx = np.arange(n)\nreihe = 50 + 0.8 * x + np.cumsum(stats.norm.ppf(lehmer(7373, n)) * 2)\n\nk, d = np.polyfit(x, reihe, 1)\nrest = reihe - (k * x + d)\ns = np.sqrt((rest ** 2).sum() / (n - 2))\nxb = x.mean()\nsxx = ((x - xb) ** 2).sum()\naenderungen = np.diff(reihe)\ndrift = aenderungen.mean()\nsd_aenderung = aenderungen.std(ddof=1)\n\nprint({\"trend_steigung\": round(float(k), 3), \"trend_reststreuung\": round(float(s), 3),\n       \"irrfahrt_drift\": round(float(drift), 3),\n       \"irrfahrt_sd\": round(float(sd_aenderung), 3)})\n\nfor h in (1, 6, 12, 24):\n    x0 = n - 1 + h\n    a = stats.t.ppf(.975, n - 2) * s * np.sqrt(1 + 1 / n + (x0 - xb) ** 2 / sxx)\n    b = 1.96 * sd_aenderung * np.sqrt(h)\n    print(f\"Horizont {h:2d}: Trend +-{a:6.2f}   Irrfahrt +-{b:6.2f}\"\n          f\"   Faktor {b / a:5.2f}\")\n\nprint({\"letzter_wert\": round(float(reihe[-1]), 2),\n       \"prognose_trend_h24\": round(float(k * (n - 1 + 24) + d), 2),\n       \"prognose_irrfahrt_h24\": round(float(reihe[-1] + drift * 24), 2)})\n\nzukunft = (n - 1) + np.arange(1, 25)\nfig, achse = plt.subplots(figsize=(7, 3.4))\n_ = achse.plot(x, reihe, lw=2, color=\"black\")\n_ = achse.plot(zukunft, k * zukunft + d, lw=2, color=\"0.45\", label=\"Trendmodell\")\nmitte = reihe[-1] + drift * np.arange(1, 25)\nrand = 1.96 * sd_aenderung * np.sqrt(np.arange(1, 25))\n_ = achse.plot(zukunft, mitte, lw=2, color=AKZENT, label=\"Irrfahrt mit Drift\")\n_ = achse.plot(zukunft, mitte + rand, ls=\"--\", color=AKZENT)\n_ = achse.plot(zukunft, mitte - rand, ls=\"--\", color=AKZENT)\n_ = achse.set_xlim(0, n + 24)\n_ = achse.set_ylim(30, 115)\n_ = achse.legend(frameon=False, loc=\"upper left\", fontsize=8)\n_ = achse.set_xlabel(\"Monat\")\n_ = achse.set_ylabel(\"Wert\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselbe Gegenüberstellung in Python.](storytelling_files/figure-html/fig-b5-st-py-1.png){#fig-b5-st-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Modell | Parameter |\n|---|---|\n| Trendregression | Steigung **0.740**, Reststreuung **2.886** |\n| Irrfahrt mit Drift | Drift **0.619**, SD der Änderungen **1.986** |\n\n| Horizont | Trend ± | Irrfahrt ± | Faktor |\n|---|---|---|---|\n| 1 Monat | **6.20** | 3.89 | 0.63 |\n| 6 Monate | 6.34 | 9.53 | 1.50 |\n| 12 Monate | 6.56 | 13.48 | 2.05 |\n| **24 Monate** | **7.11** | **19.07** | **2.68** |\n\nLetzter beobachteter Wert **68.53**; Prognose auf 24 Monate: Trend **90.61**,\nIrrfahrt **83.40**.\n\n| Beobachtung | Erklärung |\n|---|---|\n| Das Trendintervall wächst kaum | Von ±6.20 auf ±7.11 über 24 Monate, also um 15 Prozent. Das Modell behauptet, in zwei Jahren fast so sicher zu sein wie im nächsten Monat. |\n| Das Irrfahrtintervall wächst mit der **Wurzel** | Von ±3.89 auf ±19.07, also um den Faktor 4.9. Bei einer Reihe, die wandert, ist das die angemessene Aussage. |\n| Bei 24 Monaten ist es **2.68-mal** so breit | Und die Punktprognosen liegen 7.2 auseinander (90.61 gegen 83.40). |\n| Die Daten wurden als **Trend plus Irrfahrt** erzeugt | Die Irrfahrtvariante ist hier also die ehrlichere. Die Trendregression unterstellt, dass die Abweichungen um die Gerade unabhängig sind — das sind sie nicht. |\n| Kurzfristig ist das Trendintervall sogar **zu breit** | Faktor 0.63 bei einem Monat. Das falsche Modell irrt in beide Richtungen, nur eben nicht dort, wo es auffällt. |\n\n::: {.warning-box}\n**Wie sicher eine Grafik aussieht, ist eine Modellentscheidung.** Beide\nPrognosebänder sind korrekt gerechnet; sie beantworten nur verschiedene Fragen\nüber die Welt.\n\n| Wenn die Reihe … | passendes Modell | Intervall wächst |\n|---|---|---|\n| um einen festen Trend schwankt | Trendregression | kaum |\n| wandert (Irrfahrt, Random Walk) | Drift plus √h | mit der Wurzel |\n| saisonal ist | SARIMA oder Holt-Winters | je nach Struktur |\n\nDie Prüfung, welches zutrifft, steht unter\n[Stationarität und ACF/PACF](../statistik/zeitreihen/stationaritaet-acf-pacf.qmd).\nWer das überspringt und die Standardregression nimmt, bekommt ein schmales\nBand — und damit eine Grafik, die mehr behauptet, als sie weiss.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Über 24 Monate wächst das Prognoseintervall der Trendregression nur von ±6.20\n> auf ±7.11, das der Irrfahrt mit Drift von ±3.89 auf ±19.07 — am Ende ist es\n> 2.68-mal so breit. Beide sind korrekt gerechnet; die Wahl des Modells\n> entscheidet, wie sicher die Grafik aussieht.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nIm Fünf-Sekunden-Test nennt die Testperson eine andere Aussage als die\nbeabsichtigte. Was ist der nächste Schritt?\n\n- [ ] Den Titel deutlicher formulieren ~ Hilft manchmal, behebt aber nicht die\n      Ursache.\n- [x] Die Betonung prüfen: Was zieht das Auge zuerst an? ~ Richtig. Wenn eine\n      andere Aussage ankommt, führt die Gestaltung dorthin. Meist ist etwas\n      Nebensächliches farbig, gross oder oben links, wo der Blick beginnt.\n- [ ] Mehr Erklärtext darunter schreiben ~ Text unter der Grafik wird in fünf\n      Sekunden nicht gelesen.\n:::\n\n::: {.quiz}\nEine Grafik zeigt zwei gleichzeitig steigende Kurven, der Titel lautet \"Die\nKampagne wirkt\". Was ist das Problem?\n\n- [x] Der Titel behauptet eine Ursache, die die Grafik nicht zeigt ~ Richtig.\n      Im Beispiel wuchs die Kontrollregion ohne Kampagne um 13.7 Prozent, die\n      Testregion um 14.7 — der zurechenbare Rest von +4.56 war mit p = 0.22\n      nicht belegt.\n- [ ] Zwei Kurven in einer Grafik sind zu viel ~ Zwei Kurven sind\n      unproblematisch.\n- [ ] Es fehlt die Legende ~ Möglicherweise, aber das ist nicht der inhaltliche\n      Fehler.\n:::\n\n::: {.quiz}\nAcht Serien werden alle kräftig eingefärbt, eine davon ist die Aussage. Was\nbringt der Wechsel auf grau plus einen Akzent?\n\n- [x] Das visuelle Gewicht der Zielserie steigt vom 1.45- auf das 10.66-Fache\n      der übrigen ~ Richtig, und zwei Drittel davon kommen vom Zurücknehmen der\n      anderen Serien, nicht vom Hervorheben der einen.\n- [ ] Nichts, die Daten sind dieselben ~ Die Daten schon, die Führung des\n      Blicks nicht.\n- [ ] Die Zielserie wird doppelt so auffällig ~ Sie selbst gewinnt Faktor 2.3;\n      der Gesamteffekt entsteht erst zusammen mit dem Zurücknehmen.\n:::\n\n::: {.quiz}\nWarum ist eine Legende für acht Serien ungünstig?\n\n- [x] Sie kostet 16 Blickwechsel, und die Zuordnung läuft über den Farbton ~\n      Richtig, einmal hin und einmal zurück je Serie. Direkte Beschriftung\n      spart alle Wege; im Beispiel genügten zwei Beschriftungen statt acht\n      Legendeneinträgen.\n- [ ] Legenden sind grundsätzlich zu vermeiden ~ Bei sich kreuzenden Linien,\n      wo am Linienende kein Platz ist, bleiben sie sinnvoll.\n- [ ] Acht Einträge passen nicht ins Bild ~ Sie passen; das Problem ist die\n      Zuordnungsarbeit.\n:::\n\n::: {.quiz}\nEine Prognose über 24 Monate hat bei der Trendregression ein Intervall von\n±7.11, bei der Irrfahrt ±19.07. Welches ist richtig?\n\n- [x] Das hängt davon ab, ob die Reihe um einen Trend schwankt oder wandert ~\n      Richtig. Beide sind korrekt gerechnet und beantworten verschiedene Fragen\n      über die Welt. Die Daten hier wurden als Trend plus Irrfahrt erzeugt, also\n      ist die zweite die ehrlichere.\n- [ ] Das schmalere, weil es mehr Information nutzt ~ Ein schmales Band ist\n      kein Qualitätsmerkmal, sondern eine Behauptung.\n- [ ] Das breitere, Vorsicht ist immer besser ~ Kurzfristig war das Trendband\n      mit Faktor 0.63 sogar breiter; pauschale Vorsicht ersetzt die Modellwahl\n      nicht.\n:::\n\n::: {.quiz}\nEine Geschichte wird in drei Grafiken erzählt. Wie erkennt man, ob die Folge\nträgt?\n\n- [x] Jeder Schritt hat genau eine eigene Kennzahl, und die Reihenfolge lässt\n      sich nicht umstellen ~ Richtig. Im Beispiel: Ausgangsniveau 103.28,\n      Zuwachs +15.18, davon zurechenbar +4.56. Der dritte Schritt ist ohne den\n      zweiten unverständlich.\n- [ ] Alle drei zeigen dieselben Daten aus verschiedenen Blickwinkeln ~ Das\n      allein ergibt drei Einzelgrafiken, noch keine Folge.\n- [ ] Die letzte Grafik ist die auffälligste ~ Die stärkste Betonung gehört in\n      den Spannungsteil, nicht zwingend ans Ende.\n:::\n\n## Verlinkte Ressourcen\n\n- [Cole Nussbaumer Knaflic: Storytelling with Data](https://www.storytellingwithdata.com/)\n- [Claus Wilke: Titles, captions and tables](https://clauswilke.com/dataviz/figure-titles-captions.html)\n- [Financial Times: Visual Vocabulary](https://github.com/Financial-Times/chart-doctor/tree/main/visual-vocabulary)\n- [Zielbild und Publikum](zielbild-audience.qmd) — die Entscheidung vor der Grafik\n- [Irreführende Darstellungen](irrefuehrende-darstellungen.qmd) — wo Zuspitzen in Verzerren umschlägt\n",
    "supporting": [
      "storytelling_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}