{
  "hash": "76e896977bc4f3aa629248354829a585",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"t-Test für eine Stichprobe\"\ndescription: \"Mittelwert gegen einen festen Wert prüfen und das Ergebnis deuten.\"\ncategories: [\"Hypothesentests\", \"Effektstärke\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"ESDS\"]\nseitentyp: methode\nstand: fertig\norder: 10\n---\n\n\n\n\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Weicht der Mittelwert einer Gruppe von einem vorgegebenen Sollwert ab? |\n| Zielvariable | metrisch |\n| Gruppen | eine, dazu ein fester Referenzwert |\n| Was die Methode liefert | Mittelwert und Abweichung vom Sollwert mit Konfidenzintervall, t-Statistik, Freiheitsgrade, p-Wert, Effektstärke |\n| R-Funktion | `t.test(x, mu = sollwert)`, Effektstärke mit `effectsize::cohens_d(x, mu = sollwert)` |\n| Python-Funktion | `pg.ttest(x, sollwert)` |\n| Verwandte Methoden | [Schätzen und Konfidenzintervalle](../inferenz/schaetzen-konfidenzintervalle.qmd), [t-Test für zwei Stichproben](t-test-zwei-stichproben.qmd), [gepaarter t-Test](t-test-gepaart.qmd) |\n\n## Wann diese Methode, wann nicht\n\nTypische Fragestellungen: Hält eine Fertigung das Sollmass ein, entspricht die\nFüllmenge der Deklaration, erreicht eine Bearbeitungszeit den vereinbarten\nRichtwert. Gemeinsam ist ihnen eine metrische Messgrösse, eine einzige Gruppe\nund ein von aussen vorgegebener Vergleichswert.\n\nEntscheidend ist die Herkunft des Sollwerts. Er muss aus der Sache stammen, aus\neiner Norm, einer Spezifikation oder einer früheren, unabhängigen Messreihe. Ein\naus denselben Daten abgeleiteter Wert macht den Test sinnlos, weil dann gegen\nden eigenen Mittelwert getestet wird.\n\n| Situation | Stattdessen |\n|---|---|\n| Zwei Gruppen vergleichen | [t-Test für zwei Stichproben](t-test-zwei-stichproben.qmd) |\n| Dieselben Objekte vorher und nachher | [gepaarter t-Test](t-test-gepaart.qmd) |\n| Nur die Grösse schätzen, ohne Entscheidung | [Konfidenzintervall](../inferenz/schaetzen-konfidenzintervalle.qmd) |\n| Kleine, deutlich schiefe Stichprobe | [Vorzeichen-Rangtest](nichtparametrische-tests.qmd) |\n| Nachweis, dass die Abweichung klein ist | Äquivalenztest mit vorab festgelegter Toleranz |\n| Zielvariable ist ein Anteil | Binomialtest, siehe [Chi-Quadrat-Tests](chi-quadrat-tests.qmd) |\n\n## Grundidee und Modell\n\nGemessen wird der Abstand zwischen Stichprobenmittelwert und Sollwert in\nEinheiten des Standardfehlers. Ist dieser Abstand grösser, als es der Zufall bei\ngültigem Sollwert erwarten lässt, spricht das gegen die Nullhypothese.\n\n$$t = \\frac{\\bar{x} - \\mu_0}{s/\\sqrt{n}}$$\n\n| Bestandteil | Bedeutung |\n|---|---|\n| $\\bar{x}$ | Mittelwert der Stichprobe |\n| $\\mu_0$ | vorgegebener Sollwert, die Nullhypothese |\n| $s$ | Standardabweichung der Stichprobe |\n| $n$ | Stichprobenumfang |\n| $s/\\sqrt{n}$ | Standardfehler des Mittelwerts |\n\nUnter der Nullhypothese folgt $t$ einer t-Verteilung mit $n-1$ Freiheitsgraden.\nDer Test ist damit die Entscheidungsvariante desselben Sachverhalts, den das\n[Konfidenzintervall](../inferenz/schaetzen-konfidenzintervalle.qmd) als Spanne\nbeschreibt: liegt der Sollwert ausserhalb des 95-Prozent-Intervalls, ist der\nzweiseitige Test auf dem 5-Prozent-Niveau signifikant.\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung | Vorgehen |\n|---|---|---|---|---|\n| Unabhängigkeit | Die Messwerte beeinflussen sich nicht | Erhebungsdesign, zeitliche Ordnung prüfen | Standardfehler zu klein, p-Wert zu optimistisch | Struktur ins Modell aufnehmen |\n| Metrische Werte | Mittelwert und Differenz sind sinnvoll | [Skalenniveau](../grundlagen/skalenniveaus.qmd) | Der Mittelwert ist nicht definiert | Vorzeichen-Rangtest |\n| Annähernd normalverteilter Mittelwert | Bei grossem n durch den zentralen Grenzwertsatz erfüllt | [QQ-Plot](../wahrscheinlichkeit/qq-plots.qmd), Schiefe | Bei kleinem n weicht die Fehlerrate vom Niveau ab | Vorzeichen-Rangtest oder Bootstrap |\n| Sollwert unabhängig von den Daten | Der Referenzwert stammt aus der Sache, nicht aus der Stichprobe | Herkunft klären | Der Test prüft nichts | anderen Referenzwert wählen |\n| Keine extremen Ausreisser | Einzelne Werte bestimmen den Mittelwert nicht | Boxplot | Das Ergebnis hängt an wenigen Punkten | Ursache prüfen, mit und ohne berichten |\n\nGeprüft wird vor der Rechnung und mit den Augen: Boxplot für Ausreisser,\nQQ-Plot für die Verteilungsform, der Vergleich von Mittelwert und Median für\ndie Schiefe. Ein [Normalitätstest](normalitaetstests.qmd) beantwortet die\nfalsche Frage, weil er bei kleinem n zu wenig und bei grossem n zu viel findet.\n\n## Output lesen\n\nR, `t.test(x, mu = sollwert)`:\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| `One Sample t-test` | die Variante | prüfen, dass nicht versehentlich zwei Stichproben übergeben wurden |\n| `t` | Abweichung vom Sollwert in Einheiten des Standardfehlers | Betrag über etwa 2 heisst bei üblichem n signifikant |\n| `df` | Freiheitsgrade, hier n minus eins | ganzzahlig, anders als bei Welch |\n| `p-value` | Wahrscheinlichkeit dieser oder extremerer Daten bei gültigem Sollwert | keine Aussage über die Grösse der Abweichung |\n| `95 percent confidence interval` | Intervall für den wahren Mittelwert | nicht für die Differenz; der Sollwert wird daran gehalten |\n| `mean of x` | Stichprobenmittelwert | die Differenz zum Sollwert ist die berichtete Effektgrösse |\n| `alternative hypothesis` | Richtung | `true mean is not equal to 500` nennt den tatsächlich geprüften Wert |\n| `Cohens d` | standardisierte Abweichung | Anhaltspunkte: 0.2 klein, 0.5 mittel, 0.8 gross |\n\nPython, `pg.ttest(x, sollwert)` liefert eine Zeile mit `T`, `dof`, `alternative`,\n`p_val`, `CI95`, `cohen_d`, `BF10` und `power`; die Schreibweise dieser Spalten\nhat sich zwischen den pingouin-Versionen geändert, weshalb die Beispiele hier die\nSpalten nachschlagen statt sie festzuschreiben. Zwei Unterschiede sind zu\nbeachten: `CI95%` bezieht sich wie in R auf den Mittelwert selbst, nicht auf die\nDifferenz zum Sollwert, und `power` bezieht sich auf den beobachteten Effekt,\nist also im Nachhinein nur eingeschränkt aussagekräftig. Der Sollwert taucht in\nder Tabelle nicht auf und gehört deshalb ausdrücklich in den Bericht.\n\n## Interpretationsfallen\n\n- **Nicht signifikant ist kein Nachweis der Übereinstimmung.** Wer zeigen will,\n  dass der Sollwert eingehalten wird, braucht einen Äquivalenztest.\n- **Signifikanz ist keine Relevanz.** Bei 5000 Messungen wird eine Abweichung\n  von einem Hundertstel Millimeter signifikant. Die Toleranz entscheidet, nicht\n  der p-Wert.\n- **Das Intervall gilt dem Mittelwert, nicht den Einzelwerten.** Für die Frage,\n  wie viele Werkstücke innerhalb der Toleranz liegen, ist es das falsche\n  Werkzeug.\n- **Der Sollwert darf nicht aus den Daten stammen.** Sonst wird gegen den\n  eigenen Mittelwert getestet, und das Ergebnis ist immer nicht signifikant.\n- **Einseitig nur mit vorab festgelegter Richtung.** Nachträglich einseitig zu\n  testen halbiert den p-Wert und verdoppelt die Rate falscher Alarme.\n- **Ein t-Test ersetzt keine Prozessüberwachung.** Er prüft eine Momentaufnahme;\n  eine driftende Fertigung erkennt man an der zeitlichen Entwicklung.\n\n## Ergebnis berichten\n\nVorlage für den Ergebnissatz:\n\n> [Zielgrösse] weicht vom Sollwert [Sollwert] [Einheit] ab: M = [Mittelwert]\n> [Einheit], Abweichung [Differenz] [Einheit], 95-Prozent-Konfidenzintervall\n> [unten] bis [oben], t([df]) = [t], p = [p], Cohens d = [d], n = [n].\n\nGenannt werden Sollwert und seine Herkunft, Mittelwert und Streuung, die\nAbweichung mit Konfidenzintervall, Teststatistik mit Freiheitsgraden, p-Wert,\nEffektstärke und n, dazu die geprüften Voraussetzungen und der Umgang mit\nauffälligen Werten.\n\nBeispiel für eine Ergebnistabelle:\n\n| Kennzahl | Wert |\n|---|---|\n| Sollwert | |\n| Mittelwert (SD) | |\n| Abweichung [95-Prozent-Intervall] | |\n| t (df), p | |\n| Cohens d, n | |\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt des t-Tests für eine Stichprobe |\n|---|---|\n| [Schätzen und Konfidenzintervalle](../inferenz/schaetzen-konfidenzintervalle.qmd) | es geht um die Grösse, nicht um eine Entscheidung gegen einen Sollwert |\n| [t-Test für zwei Stichproben](t-test-zwei-stichproben.qmd) | zwei Gruppen statt Gruppe gegen Sollwert |\n| [Gepaarter t-Test](t-test-gepaart.qmd) | dieselben Objekte zweimal gemessen; rechnerisch ein Einstichprobentest auf den Differenzen gegen null |\n| [Nichtparametrische Tests](nichtparametrische-tests.qmd) | kleine, schiefe Stichprobe oder ordinale Werte |\n| [Chi-Quadrat-Tests](chi-quadrat-tests.qmd) | die Zielgrösse ist kategorial |\n\n## Beispiele\n\nAlle Beispiele rechnen mit fest eingetragenen Zahlen, damit R und Python\ndieselben Daten sehen und jeder Wert im Text nachprüfbar ist.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Abfüllmenge gegen die Deklaration\n\n#### Frage und Datenlage\n\nAuf dem Etikett stehen 500 ml. Aus der laufenden Produktion werden zwanzig\nFlaschen ausgewogen. Die Frage lautet: Weicht die mittlere Abfüllmenge vom\ndeklarierten Wert ab, und falls ja, um wie viel?\n\nDer Sollwert von 500 ml stammt aus der Deklaration, also von aussen und nicht\naus den Daten. Damit ist die Grundbedingung des Verfahrens erfüllt.\n\n#### Voraussetzungen prüfen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfuellmenge <- c(498.2, 501.4, 497.6, 499.1, 502.3, 496.8, 500.5, 498.9,\n                497.2, 499.8, 496.4, 500.1, 498.5, 497.9, 499.4, 495.7,\n                498.0, 500.9, 497.3, 498.6)\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nboxplot(fuellmenge, main = \"Füllmenge\", ylab = \"Milliliter\")\nabline(h = 500, lty = 2, col = \"firebrick\")\nqqnorm(fuellmenge, main = \"QQ-Plot\"); qqline(fuellmenge)\npar(mfrow = c(1, 1))\n\nround(c(n = length(fuellmenge), mittel = mean(fuellmenge),\n        sd = sd(fuellmenge), median = median(fuellmenge)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       n   mittel       sd   median \n 20.0000 498.7300   1.7309 498.5500 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 1: Verteilung der Füllmengen und QQ-Plot.](t-test-eine-stichprobe_files/figure-html/fig-b1-1s-voraussetzungen-r-1.png){#fig-b1-1s-voraussetzungen-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfuellmenge = np.array([498.2, 501.4, 497.6, 499.1, 502.3, 496.8, 500.5, 498.9,\n                       497.2, 499.8, 496.4, 500.1, 498.5, 497.9, 499.4, 495.7,\n                       498.0, 500.9, 497.3, 498.6])\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nachsen[0].boxplot(fuellmenge)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'whiskers': [<matplotlib.lines.Line2D object at 0x7eff103bb5c0>, <matplotlib.lines.Line2D object at 0x7eff103bb2f0>], 'caps': [<matplotlib.lines.Line2D object at 0x7eff103badb0>, <matplotlib.lines.Line2D object at 0x7eff103baa80>], 'boxes': [<matplotlib.lines.Line2D object at 0x7eff12b37050>], 'medians': [<matplotlib.lines.Line2D object at 0x7eff103bb8c0>], 'fliers': [<matplotlib.lines.Line2D object at 0x7eff103bbb60>], 'means': []}\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[0].axhline(500, linestyle=\"--\", color=\"firebrick\")\nachsen[0].set_title(\"Füllmenge\")\nachsen[0].set_ylabel(\"Milliliter\")\nsm.qqplot(fuellmenge, line=\"s\", ax=achsen[1])\nachsen[1].set_title(\"QQ-Plot\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Prüfung in Python.](t-test-eine-stichprobe_files/figure-html/fig-b1-1s-voraussetzungen-py-1.png){#fig-b1-1s-voraussetzungen-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(\"n =\", len(fuellmenge), \" Mittel =\", round(fuellmenge.mean(), 4),\n      \" SD =\", round(fuellmenge.std(ddof=1), 4),\n      \" Median =\", round(np.median(fuellmenge), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 20  Mittel = 498.73  SD = 1.7309  Median = 498.55\n```\n\n\n:::\n:::\n\n\n:::\n\nDer Mittelwert liegt bei 498.73 ml, der Median bei 498.55 ml. Beide liegen dicht\nbeieinander, die Verteilung ist also nicht nennenswert schief, und im QQ-Plot\nliegen die Punkte nah an der Geraden. Der Boxplot zeigt keinen weit entfernten\nEinzelwert. Die gestrichelte Linie beim Sollwert macht schon hier sichtbar,\nworum es geht: Der Kasten liegt vollständig unterhalb von 500.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(fuellmenge, mu = 500)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  fuellmenge\nt = -3.2814, df = 19, p-value = 0.003927\nalternative hypothesis: true mean is not equal to 500\n95 percent confidence interval:\n 497.9199 499.5401\nsample estimates:\nmean of x \n   498.73 \n```\n\n\n:::\n\n```{.r .cell-code}\neffectsize::cohens_d(fuellmenge, mu = 500)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |         95% CI\n--------------------------\n-0.73     | [-1.22, -0.23]\n\n- Deviation from a difference of 500.\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(pg.ttest(fuellmenge, 500).round(4).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       T_test\nT                     -3.2814\ndof                        19\nalternative         two-sided\np_val                  0.0039\nCI95         [497.92, 499.54]\ncohen_d                0.7337\npower                  0.8753\nBF10                   11.262\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| Variante | `One Sample t-test` | eine Gruppe gegen einen festen Wert | Stünde dort `Two Sample`, wäre versehentlich ein zweiter Vektor übergeben worden. |\n| `t` | -3.281 | Der Mittelwert liegt 3.28 Standardfehler unter dem Sollwert. | Das negative Vorzeichen sagt die Richtung: zu wenig in der Flasche. |\n| `df` | 19 | Freiheitsgrade, n minus eins | Immer ganzzahlig, anders als beim Welch-Test für zwei Stichproben. |\n| `p-value` | 0.0039 | Wahrscheinlichkeit einer mindestens so grossen Abweichung, wenn im Mittel tatsächlich 500 ml abgefüllt würden | Deutlich unter 0.05. |\n| `95 percent confidence interval` | 497.92 bis 499.54 | Intervall für den **wahren Mittelwert**, nicht für die Differenz | Der Sollwert 500 liegt ausserhalb. Genau das ist der Grund für den signifikanten Test; ein p-Wert wird dafür gar nicht gebraucht. |\n| `mean of x` | 498.73 | Stichprobenmittelwert | Die berichtete Abweichung ist 498.73 minus 500, also -1.27 ml. |\n| `alternative hypothesis` | `true mean is not equal to 500` | zweiseitig, gegen 500 getestet | Diese Zeile ist die Kontrolle, dass der richtige Sollwert eingesetzt wurde. |\n| Cohens d | -0.73 | Abweichung in Einheiten der Streuung | Zwischen mittel und gross. Anders als die Zahl in Millilitern ist d von der Einheit unabhängig und damit über Messgrössen hinweg vergleichbar. |\n| `power` (nur Python) | 0.875 | Trefferwahrscheinlichkeit für den beobachteten Effekt | Im Nachhinein berechnet, siehe [Power und Stichprobenumfang](../inferenz/power-stichprobenumfang.qmd). |\n| `BF10` (nur Python) | 11.26 | Bayes-Faktor | Die Daten sind rund elfmal wahrscheinlicher unter einer Abweichung als unter exakter Einhaltung. |\n\n::: {.note-box}\nDas Konfidenzintervall bezieht sich in beiden Sprachen auf den Mittelwert\nselbst, nicht auf die Differenz zum Sollwert. Wer die Abweichung mit Intervall\nberichten will, zieht den Sollwert von beiden Grenzen ab: aus 497.92 bis 499.54\nwird -2.08 bis -0.46 ml.\n:::\n\n#### Interpretation und Ergebnissatz\n\nDie Abfüllung liegt im Mittel 1.27 ml unter der Deklaration, und das Intervall\nsagt: plausibel sind Werte zwischen 0.46 und 2.08 ml zu wenig. Ob das zählt,\nentscheidet nicht der p-Wert, sondern die Vorgabe. Bei einer zulässigen\nMinusabweichung von 3 ml wäre die Sache unkritisch; bei 1 ml wäre sie es nicht,\nweil das Intervall bis 2.08 ml reicht.\n\n> Die Abfüllmenge unterschreitet die Deklaration von 500 ml (M = 498.73 ml,\n> SD = 1.73, n = 20): Abweichung -1.27 ml, 95-Prozent-Konfidenzintervall -2.08\n> bis -0.46 ml, t(19) = -3.28, p = 0.004, Cohens d = -0.73. Boxplot und QQ-Plot\n> zeigen keine Auffälligkeiten.\n\n### Beispiel 2: Keine nachweisbare Abweichung\n\n#### Frage und Datenlage\n\nNach einer Nachjustierung der Anlage werden zwölf Flaschen geprüft. Dieselbe\nFrage, derselbe Sollwert. Das Beispiel zeigt, was ein Nullbefund aussagt und was\ner nicht aussagt.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnachjustiert <- c(499.4, 501.8, 498.2, 500.6, 497.9, 502.4,\n                  499.1, 500.3, 498.7, 501.2, 499.8, 500.9)\n\nt.test(nachjustiert, mu = 500)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  nachjustiert\nt = 0.060903, df = 11, p-value = 0.9525\nalternative hypothesis: true mean is not equal to 500\n95 percent confidence interval:\n 499.1215 500.9285\nsample estimates:\nmean of x \n  500.025 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nnachjustiert = np.array([499.4, 501.8, 498.2, 500.6, 497.9, 502.4,\n                         499.1, 500.3, 498.7, 501.2, 499.8, 500.9])\n\nprint(pg.ttest(nachjustiert, 500).round(4).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       T_test\nT                      0.0609\ndof                        11\nalternative         two-sided\np_val                  0.9525\nCI95         [499.12, 500.93]\ncohen_d                0.0176\npower                  0.0504\nBF10                    0.288\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| `mean of x` | 500.025 | Die Abweichung beträgt 0.025 ml, also ein Vierzigstel Milliliter. |\n| `t` | 0.061 | Praktisch null. Solche Abweichungen entstehen laufend rein zufällig. |\n| `df` | 11 | n minus eins. |\n| `p-value` | 0.953 | So gross, wie ein p-Wert kaum werden kann. Die Daten sind mit exakter Einhaltung bestens vereinbar. |\n| `95 percent confidence interval` | 499.12 bis 500.93 | Die entscheidende Zeile. Der Sollwert liegt bequem im Intervall, aber das Intervall ist 1.8 ml breit: Abweichungen bis knapp ein Milliliter in beide Richtungen bleiben vereinbar. |\n| `cohen_d` | 0.018 | Vernachlässigbar. |\n| `power` (nur Python) | 0.050 | Der Test hatte bei diesem Effekt und diesem Umfang praktisch keine Aussicht, etwas zu finden. Der Wert entspricht genau dem Signifikanzniveau, und das ist kein Zufall: Bei einem Effekt von praktisch null ist die Trefferwahrscheinlichkeit gleich der Rate falscher Alarme. |\n\n#### Interpretation und Ergebnissatz\n\nDer Satz \"die Anlage füllt korrekt ab\" ist hier nicht gedeckt. Gedeckt ist: In\ndiesen zwölf Flaschen ist keine Abweichung nachweisbar. Der Unterschied steht\nim Intervall, das Abweichungen bis 0.93 ml zulässt.\n\nWer den Nachweis der Einhaltung wirklich braucht, formuliert ihn umgekehrt: Man\nlegt vorab eine Toleranz fest, etwa 1 ml, und zeigt mit einem Äquivalenztest,\ndass die Abweichung innerhalb dieser Grenzen liegt. Der gewöhnliche t-Test kann\ndas grundsätzlich nicht, weil seine Nullhypothese die Übereinstimmung ist und\neine Nullhypothese nie bewiesen wird.\n\n> Nach der Nachjustierung ist keine Abweichung von der Deklaration nachweisbar\n> (M = 500.03 ml, SD = 1.42, n = 12; Abweichung 0.03 ml,\n> 95-Prozent-Konfidenzintervall -0.88 bis 0.93 ml, t(11) = 0.06, p = 0.95). Das\n> Intervall lässt Abweichungen bis rund 0.9 ml in beide Richtungen zu; ein\n> Nachweis der Einhaltung ist damit nicht erbracht.\n\n### Beispiel 3: Ein Ausreisser kippt das Ergebnis\n\n#### Frage und Datenlage\n\nEine Vereinbarung nennt acht Minuten als Richtwert für eine Bearbeitung. Zwölf\nVorgänge werden gemessen. Bearbeitungszeiten sind fast immer rechtsschief, und\nin dieser Reihe steckt zusätzlich ein Vorgang mit 30 Minuten.\n\n#### Voraussetzungen prüfen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbearbeitung <- c(7.9, 8.2, 8.4, 8.6, 8.9, 9.1, 9.4, 9.8, 10.2, 11.0, 12.5, 30.0)\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nboxplot(bearbeitung, main = \"Bearbeitungszeit\", ylab = \"Minuten\")\nabline(h = 8, lty = 2, col = \"firebrick\")\nqqnorm(bearbeitung, main = \"QQ-Plot\"); qqline(bearbeitung)\npar(mfrow = c(1, 1))\n\nround(c(mittel = mean(bearbeitung), median = median(bearbeitung),\n        sd = sd(bearbeitung)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmittel median     sd \n11.167  9.250  6.072 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: rechtsschiefe Bearbeitungszeiten mit einem Extremwert.](t-test-eine-stichprobe_files/figure-html/fig-b3-1s-voraussetzungen-r-1.png){#fig-b3-1s-voraussetzungen-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nbearbeitung = np.array([7.9, 8.2, 8.4, 8.6, 8.9, 9.1, 9.4, 9.8,\n                        10.2, 11.0, 12.5, 30.0])\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nachsen[0].boxplot(bearbeitung)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'whiskers': [<matplotlib.lines.Line2D object at 0x7eff102dec00>, <matplotlib.lines.Line2D object at 0x7eff102ded50>], 'caps': [<matplotlib.lines.Line2D object at 0x7eff102de690>, <matplotlib.lines.Line2D object at 0x7eff102de270>], 'boxes': [<matplotlib.lines.Line2D object at 0x7eff102dea20>], 'medians': [<matplotlib.lines.Line2D object at 0x7eff102de060>], 'fliers': [<matplotlib.lines.Line2D object at 0x7eff102dd220>], 'means': []}\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[0].axhline(8, linestyle=\"--\", color=\"firebrick\")\nachsen[0].set_title(\"Bearbeitungszeit\")\nachsen[0].set_ylabel(\"Minuten\")\nsm.qqplot(bearbeitung, line=\"s\", ax=achsen[1])\nachsen[1].set_title(\"QQ-Plot\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselbe Prüfung in Python.](t-test-eine-stichprobe_files/figure-html/fig-b3-1s-voraussetzungen-py-1.png){#fig-b3-1s-voraussetzungen-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(\"Mittel =\", round(bearbeitung.mean(), 3),\n      \" Median =\", round(np.median(bearbeitung), 3),\n      \" SD =\", round(bearbeitung.std(ddof=1), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMittel = 11.167  Median = 9.25  SD = 6.072\n```\n\n\n:::\n:::\n\n\n:::\n\nMittelwert 11.17 Minuten, Median 9.25 Minuten, Standardabweichung 6.07. Die\nStreuung ist mehr als halb so gross wie der Mittelwert, und der QQ-Plot biegt am\noberen Ende weit von der Geraden ab. Bei zwölf Werten hilft der zentrale\nGrenzwertsatz nicht mehr. Das Verfahren wird deshalb **vor** der Rechnung\ngewechselt.\n\n#### Rechnung\n\nBeide Verfahren stehen hier nebeneinander, damit sichtbar wird, was auf dem\nSpiel steht. Im Bericht erschiene nur der rangbasierte Test.\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(bearbeitung, mu = 8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  bearbeitung\nt = 1.8066, df = 11, p-value = 0.09822\nalternative hypothesis: true mean is not equal to 8\n95 percent confidence interval:\n  7.30877 15.02456\nsample estimates:\nmean of x \n 11.16667 \n```\n\n\n:::\n\n```{.r .cell-code}\nwilcox.test(bearbeitung, mu = 8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon signed rank exact test\n\ndata:  bearbeitung\nV = 77, p-value = 0.0009766\nalternative hypothesis: true location is not equal to 8\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nt_wert, t_p = stats.ttest_1samp(bearbeitung, 8)\nv_wert, v_p = stats.wilcoxon(bearbeitung - 8)\nprint(\"t-Test               t =\", round(t_wert, 4), \" p =\", round(t_p, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt-Test               t = 1.8066  p = 0.0982\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Vorzeichen-Rangtest  V =\", v_wert, \" p =\", round(v_p, 6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVorzeichen-Rangtest  V = 1.0  p = 0.000977\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| t-Test `mean of x` | 11.167 | Der Mittelwert liegt über drei Minuten über dem Richtwert, sieht also nach einer klaren Überschreitung aus. |\n| t-Test `t` | 1.807 | Und ist es trotzdem nicht: Der Standardfehler beträgt 1.75 Minuten, weil der eine Wert von 30 Minuten die Streuung aufbläht. |\n| t-Test `p-value` | 0.098 | Nicht signifikant. |\n| t-Test Intervall | 7.31 bis 15.02 | Fast acht Minuten breit und den Richtwert knapp einschliessend. Aus diesen Daten lässt sich über den Mittelwert nichts ableiten. |\n| Rangtest `V` | 1 | Die Rangsumme jener Differenzen, die unter null liegen. Von zwölf Vorgängen lag nur einer unter acht Minuten, deshalb ist der Wert so klein. |\n| Rangtest `p-value` | 0.00098 | Hochsignifikant, also die gegenteilige Entscheidung. |\n\nZwei Verfahren, dieselben Daten, entgegengesetzte Schlüsse. Der Grund steht in\nder Datenreihe: Elf von zwölf Vorgängen dauern länger als acht Minuten. Der\nRangtest sieht genau das. Der t-Test sieht stattdessen den Abstand des\nMittelwerts zum Sollwert, geteilt durch eine Streuung, die ein einzelner Wert\nnach oben treibt.\n\n#### Interpretation und Ergebnissatz\n\nDie Entscheidung für den Rangtest fällt an der Voraussetzungsprüfung, nicht an\nden p-Werten. Wäre es umgekehrt, wäre das Testniveau verloren.\n\nEbenso wichtig ist, was berichtet wird: Nach einem Rangtest spricht man über die\nzentrale Tendenz, nicht über den Mittelwert. Der Median von 9.25 Minuten\nbeschreibt den typischen Vorgang; der Mittelwert von 11.17 Minuten beschreibt\nkeinen einzigen der zwölf gemessenen Vorgänge auch nur annähernd.\n\nDer Wert von 30 Minuten gehört untersucht statt entfernt. Ein solcher Vorgang\nkann ein Erfassungsfehler sein, ein Sonderfall mit Rückfrage oder genau das\nProblem, um das es eigentlich geht.\n\n> Wegen deutlicher Rechtsschiefe und eines Extremwerts wurde vorab rangbasiert\n> geprüft. Die Bearbeitungszeit überschreitet den Richtwert von acht Minuten\n> (Vorzeichen-Rangtest, V = 1, p < 0.001, n = 12; Median 9.25 Minuten). Auf\n> einen Mittelwertvergleich wurde bewusst verzichtet.\n\n### Beispiel 4: Signifikant und trotzdem unerheblich\n\n#### Frage und Datenlage\n\nEine automatische Kontrolle wiegt 4000 Flaschen. Die wahre mittlere Abweichung\nbeträgt 0.15 ml, weit unterhalb jeder Toleranz. Damit beide Sprachen exakt\ndieselben Daten sehen, werden die Werte nicht gezogen, sondern als Quantile der\nNormalverteilung konstruiert.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngross <- 500.15 + 2.0 * qnorm(ppoints(4000))\n\nt.test(gross, mu = 500)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  gross\nt = 4.7436, df = 3999, p-value = 2.173e-06\nalternative hypothesis: true mean is not equal to 500\n95 percent confidence interval:\n 500.088 500.212\nsample estimates:\nmean of x \n   500.15 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ngross = 500.15 + 2.0 * stats.norm.ppf((np.arange(1, 4001) - 0.5) / 4000)\n\nprint(pg_auswahl(pg.ttest(gross, 500),\n                 \"T\", \"dof\", \"p_val\", \"p-val\", \"CI95\", \"CI95%\",\n                 \"cohen_d\", \"cohen-d\").round(6).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       T  dof    p_val             CI95  cohen_d\n4.743602 3999 0.000002 [500.09, 500.21] 0.075003\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| `mean of x` | 500.15 | Die Abweichung beträgt 0.15 ml, hier exakt bekannt. |\n| `t` | 4.744 | Weit über der üblichen Schwelle von etwa 2. |\n| `df` | 3999 | n minus eins. |\n| `p-value` | 0.0000022 | Hochsignifikant. |\n| `95 percent confidence interval` | 500.088 bis 500.212 | Nur zwölf Hundertstel Milliliter breit. Die Abweichung ist sehr präzise geschätzt und trotzdem winzig. |\n| `cohen_d` | 0.075 | Weit unter dem Anhaltspunkt 0.2 für einen kleinen Effekt. |\n\n#### Interpretation und Ergebnissatz\n\nHier lässt sich der Unterschied zwischen den beiden Fragen \"ist die Abweichung\nvom Zufall unterscheidbar\" und \"ist die Abweichung wichtig\" sauber ablesen. Die\nerste beantwortet der p-Wert, und seine Antwort hängt am Stichprobenumfang: Bei\n4000 Flaschen wird auch ein Fünfzehntel Milliliter sichtbar. Die zweite\nbeantworten die Abweichung in Millilitern und Cohens d, und diese Zahlen ändern\nsich mit dem Umfang nicht.\n\nDeshalb wird die Relevanzschwelle vor der Auswertung festgelegt. Wer sie erst\ndanach sucht, findet sie so, dass sie zum Ergebnis passt.\n\n> Die Abfüllmenge weicht statistisch nachweisbar von der Deklaration ab\n> (M = 500.15 ml, n = 4000, t(3999) = 4.74, p < 0.001). Die Abweichung beträgt\n> 0.15 ml (95-Prozent-Konfidenzintervall 0.09 bis 0.21 ml, Cohens d = 0.08) und\n> liegt damit weit innerhalb der zulässigen Toleranz; ein Eingriff in den Prozess\n> ist daraus nicht abzuleiten.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nDas 95-Prozent-Konfidenzintervall für den Mittelwert reicht von 12.05 bis 12.31,\nder Sollwert ist 12. Was folgt für den zweiseitigen Test auf dem 5-Prozent-Niveau?\n\n- [x] Er ist signifikant, der Sollwert liegt ausserhalb des Intervalls ~ Richtig.\n      Intervall und Test sind zwei Darstellungen desselben Sachverhalts; ein\n      p-Wert wird dafür nicht gebraucht.\n- [ ] Das lässt sich ohne p-Wert nicht sagen ~ Doch, die Beziehung gilt exakt.\n- [ ] Er ist nicht signifikant, weil 12 nahe an 12.05 liegt ~ Entscheidend ist,\n      ob der Wert im Intervall liegt, nicht wie nahe er an der Grenze liegt.\n:::\n\n::: {.quiz}\nEin einzelner Ausreisser wird der Stichprobe hinzugefügt, und der p-Wert steigt\nvon 0.01 auf 0.20. Wie kommt das?\n\n- [ ] Der Ausreisser zieht den Mittelwert zum Sollwert hin ~ Er zieht ihn hier\n      sogar weiter weg.\n- [x] Er vergrössert die Standardabweichung stärker als den Mittelwert ~\n      Richtig. Der Nenner der Teststatistik wächst schneller als der Zähler, und\n      damit sinkt t. Ein einzelner Wert kann so ein klares Ergebnis auflösen.\n- [ ] Die Freiheitsgrade sinken ~ Sie steigen um eins, weil eine Beobachtung\n      dazukommt.\n:::\n\n::: {.quiz}\nDer Sollwert wird als Mittelwert derselben Messreihe berechnet, gegen die\ngetestet wird. Was passiert?\n\n- [x] Die Teststatistik ist null, das Ergebnis ist wertlos ~ Richtig. Zähler und\n      Sollwert sind identisch, der Test prüft eine Aussage über sich selbst.\n- [ ] Der Test wird konservativ, aber bleibt gültig ~ Er ist nicht konservativ,\n      sondern gegenstandslos.\n- [ ] Das Ergebnis ist immer signifikant ~ Das Gegenteil ist der Fall.\n:::\n\n::: {.quiz}\nBei n = 4000 ergibt sich p < 0.001 und eine Abweichung von 0.004 mm bei einer\nToleranz von 0.5 mm. Was berichtet man?\n\n- [ ] Eine signifikante Abweichung vom Sollmass ~ Formal richtig und irreführend,\n      wenn die Grösse fehlt.\n- [x] Die Abweichung mit Intervall, dazu die Einordnung an der Toleranz ~\n      Richtig. Der Prozess ist statistisch von 12 unterscheidbar und praktisch\n      innerhalb der Spezifikation. Beides gehört in denselben Satz.\n- [ ] Dass der Test bei grossem n unbrauchbar ist ~ Er tut genau, was er soll;\n      die Einordnung leistet die Effektgrösse.\n:::\n\n## Verlinkte Ressourcen\n\n- [OpenIntro Statistics, Kapitel zum t-Test](https://www.openintro.org/book/os/)\n- [pingouin: ttest](https://pingouin-stats.org/build/html/generated/pingouin.ttest.html)\n- [R-Dokumentation zu `t.test`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/t.test.html)\n- [Prüfverteilungen: t, Chi-Quadrat und F](../wahrscheinlichkeit/pruefverteilungen.qmd), warum es die t-Verteilung braucht\n",
    "supporting": [
      "t-test-eine-stichprobe_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}