{
  "hash": "1702e5aef43534f166faeb169bbb858d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Irreführende Darstellungen\"\ndescription: \"Abgeschnittene Achsen, falsche Flächen und andere Verzerrungen.\"\ncategories: [\"Visualisierungsethik\", \"Visualisierung\", \"Wahrnehmung\", \"R\", \"Python\"]\nquelle: [\"DAVI\"]\nseitentyp: konzept\nstand: entwurf\norder: 80\n---\n\n\n\n\n\n## Kernideen\n\n- Bei **Balken** kodiert die Länge die Menge, also muss die Achse bei null\n  beginnen. Bei **Linien** trägt die Steigung die Aussage, dort ist ein\n  Ausschnitt zulässig.\n- Eine **zweite y-Achse** hat zwei frei wählbare Parameter — und damit lässt\n  sich fast jeder Gleichlauf herstellen.\n- Zwei unabhängige **Irrfahrten** korrelieren erstaunlich oft stark. Der\n  Gleichlauf von Niveaus ist kein Beleg für einen Zusammenhang.\n- Der **gewählte Zeitraum** kann die Aussage stärker bestimmen als die Daten.\n- **Prozent und Prozentpunkte** sind verschiedene Dinge, und die Wahl zwischen\n  ihnen verändert die Zahl um ein Vielfaches.\n- Die meisten Verzerrungen entstehen aus Bequemlichkeit, nicht aus Absicht.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Wahrnehmung und Kodierung](wahrnehmung-kodierung.qmd). Fast\njede Verzerrung hier ist ein Missbrauch eines Kanals: Länge, Fläche oder\nSteigung sagt etwas anderes als die Zahl.\n:::\n\n### Die abgeschnittene Achse\n\nDer bekannteste Fall, und der einzige, bei dem die Antwort von der Diagrammart\nabhängt.\n\nBei einem **Balkendiagramm** kodiert die Länge des Balkens die Menge. Wer unten\netwas wegschneidet, kürzt die Balken ungleichmässig und behauptet damit andere\nVerhältnisse, als in den Daten stehen. Beispiel 1 rechnet aus, um welchen\nFaktor.\n\nBei einem **Liniendiagramm** ist der Ausschnitt dagegen zulässig und oft\nnotwendig, weil dort die Steigung die Aussage trägt und nicht der Abstand zur\nGrundlinie. Eine Zeitreihe von Körpertemperaturen ab null darzustellen wäre\nunsinnig. Wer den Ausschnitt wählt, sagt es in der Achsenbeschriftung.\n\n### Die zweite y-Achse\n\nZwei Kurven mit verschiedenen Einheiten, jede an ihrer eigenen Achse: Das ist\ndie eleganteste Art, einen Zusammenhang zu behaupten, den es nicht gibt. Die\nzweite Achse hat **zwei freie Parameter**, Nullpunkt und Massstab. Mit zwei\nfreien Parametern lässt sich fast jede Kurve auf jede andere legen — und mit\neiner anderen Wahl derselbe Gleichlauf wieder auflösen oder umkehren.\n\nDazu kommt ein zweites Problem, das nichts mit der Grafik zu tun hat: Zwei\nZeitreihen, die beide wandern, korrelieren auch dann, wenn sie nichts\nmiteinander zu tun haben. Beispiel 2 beziffert, wie oft das passiert.\n\nWas stattdessen geht: zwei Teilgrafiken übereinander mit gemeinsamer Zeitachse.\nDer zeitliche Bezug bleibt, die Suggestion verschwindet. Wenn es wirklich um\nden Zusammenhang geht, ist das Streudiagramm der **Veränderungen** ehrlicher,\nsiehe [Korrelation](../statistik/grundlagen/korrelation.qmd).\n\n### Flächen und Radien\n\nWird eine Menge über eine Kreisfläche dargestellt und dabei der Radius\nproportional zur Menge gesetzt, wächst die Fläche im Quadrat: Der doppelte Wert\nsieht viermal so gross aus, der achtfache 64-mal. Dasselbe gilt für\nBildsymbole, die in beide Richtungen skaliert werden.\n\nDurchgerechnet ist der Fall unter\n[Wahrnehmung und Kodierung, Beispiel 2](wahrnehmung-kodierung.qmd).\n\n### Der gewählte Ausschnitt\n\nEin Zeitraum lässt sich so wählen, dass er eine Aussage trägt, die über den\nganzen Verlauf nicht gilt. Das ist besonders wirksam, weil nichts an der Grafik\nfalsch ist: Die Zahlen stimmen, die Achsen stimmen, nur der Ausschnitt ist die\nBotschaft.\n\nDie Gegenprobe ist einfach: Wie sieht dieselbe Grafik mit dem doppelten\nZeitraum aus? Ändert sich die Aussage, gehört der längere Zeitraum in die\nGrafik oder wenigstens die Begründung in die Bildunterschrift.\n\n### Aggregation, die den Effekt umdreht\n\nWenn Gruppen zusammengefasst werden, kann der Gesamttrend in die andere\nRichtung zeigen als jede einzelne Gruppe. Das ist kein Darstellungsfehler,\nsondern ein Denkfehler, der sich in der Darstellung fortsetzt, und er heisst\n**Simpson-Paradox**.\n\n### Prozent, Prozentpunkte und die Basis\n\nDieselbe Veränderung lässt sich als \"ein Prozentpunkt mehr\" oder als \"50\nProzent mehr\" beschreiben. Beides ist richtig, und die Wahl entscheidet, wie\ngross die Sache wirkt. Eine Grafik, die nur die relative Veränderung zeigt,\nohne die Basis zu nennen, ist unvollständig.\n\n### Die kurze Prüfliste\n\n- Beginnt die Balkenachse bei null?\n- Steht eine zweite y-Achse in der Grafik, und lässt sie sich vermeiden?\n- Sind Flächen nach Fläche skaliert und nicht nach Radius?\n- Ist der Zeitraum begründet, und was zeigt der doppelte?\n- Verstecken zusammengefasste Gruppen einen gegenläufigen Effekt?\n- Stehen bei Prozentangaben die **Basis** und die absolute Zahl dabei?\n- Ist die Achse nirgends umgedreht, ohne dass es dasteht?\n- Trägt der Titel eine Aussage, die die Daten hergeben?\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Um welchen Faktor die abgeschnittene Achse täuscht\n\n#### Frage und Datenlage\n\nVier Quartalswerte: 96, 98, 99, 101. Ein Zuwachs von 5.2 Prozent. Die Frage ist\nnicht, ob das Abschneiden täuscht, sondern **um wie viel**.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquartale <- c(\"Q1\", \"Q2\", \"Q3\", \"Q4\")\nwerte <- c(96, 98, 99, 101)\n\nround(c(echtes_verhaeltnis = max(werte) / min(werte),\n        zuwachs_prozent = (werte[4] / werte[1] - 1) * 100), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nechtes_verhaeltnis    zuwachs_prozent \n            1.0521             5.2083 \n```\n\n\n:::\n\n```{.r .cell-code}\nfor (basis in c(0, 90, 95)) {\n  laengen <- werte - basis\n  cat(sprintf(\"Achse ab %3d: Balkenlängen %-18s Verhältnis %5.3f  Verzerrung %4.2f-fach\\n\",\n              basis, paste(laengen, collapse = \" \"),\n              max(laengen) / min(laengen),\n              (max(laengen) / min(laengen)) / (max(werte) / min(werte))))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAchse ab   0: Balkenlängen 96 98 99 101       Verhältnis 1.052  Verzerrung 1.00-fach\nAchse ab  90: Balkenlängen 6 8 9 11           Verhältnis 1.833  Verzerrung 1.74-fach\nAchse ab  95: Balkenlängen 1 3 4 6            Verhältnis 6.000  Verzerrung 5.70-fach\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 3), mar = c(3, 4, 3, 1))\nfor (basis in c(0, 90, 95)) {\n  barplot(werte, names.arg = quartale, col = neutral, border = NA,\n          ylim = c(basis, 102), xpd = FALSE,\n          ylab = \"Index\", main = paste(\"Achse ab\", basis))\n}\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselben vier Werte mit drei Achsenanfängen.](irrefuehrende-darstellungen_files/figure-html/fig-b1-ir-r-1.png){#fig-b1-ir-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nquartale = [\"Q1\", \"Q2\", \"Q3\", \"Q4\"]\nwerte = np.array([96., 98., 99., 101.])\n\nprint({\"echtes_verhaeltnis\": round(float(werte.max() / werte.min()), 4),\n       \"zuwachs_prozent\": round(float((werte[3] / werte[0] - 1) * 100), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'echtes_verhaeltnis': 1.0521, 'zuwachs_prozent': 5.2083}\n```\n\n\n:::\n\n```{.python .cell-code}\nfor basis in [0, 90, 95]:\n    laengen = werte - basis\n    v = laengen.max() / laengen.min()\n    print(f\"Achse ab {basis:3d}: Balkenlängen {str(laengen):<22}\"\n          f\" Verhältnis {v:5.3f}  Verzerrung {v / (werte.max() / werte.min()):4.2f}-fach\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAchse ab   0: Balkenlängen [ 96.  98.  99. 101.]  Verhältnis 1.052  Verzerrung 1.00-fach\nAchse ab  90: Balkenlängen [ 6.  8.  9. 11.]      Verhältnis 1.833  Verzerrung 1.74-fach\nAchse ab  95: Balkenlängen [1. 3. 4. 6.]          Verhältnis 6.000  Verzerrung 5.70-fach\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(1, 3, figsize=(7, 3))\nfor achse, basis in zip(achsen, [0, 90, 95]):\n    _ = achse.bar(quartale, werte - basis, bottom=basis, color=NEUTRAL)\n    _ = achse.set_ylim(basis, 102)\n    _ = achse.set_title(f\"Achse ab {basis}\")\n    _ = achse.set_ylabel(\"Index\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Gegenüberstellung in Python.](irrefuehrende-darstellungen_files/figure-html/fig-b1-ir-py-1.png){#fig-b1-ir-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Achse beginnt bei | Balkenlängen | Verhältnis längster zu kürzestem | Verzerrung |\n|---|---|---|---|\n| **0** | 96, 98, 99, 101 | **1.052** | 1.00-fach |\n| **90** | 6, 8, 9, 11 | **1.833** | **1.74-fach** |\n| **95** | 1, 3, 4, 6 | **6.000** | **5.70-fach** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| In den Daten stehen **5.2 Prozent** Zuwachs | Das Verhältnis vom grössten zum kleinsten Wert ist 1.052. |\n| Ab 90 gezeichnet sieht es wie **83 Prozent** aus | Der längste Balken ist 1.83-mal so lang wie der kürzeste. Die behauptete Menge ist um den Faktor 1.74 übertrieben. |\n| Ab 95 gezeichnet wie **das Sechsfache** | Verzerrung 5.70-fach. **Je näher der Achsenanfang an den Daten liegt, desto grösser die Lüge** — und desto harmloser sieht die Entscheidung beim Erstellen aus. |\n| Die Verzerrung ist berechenbar | Sie ist das Verhältnis der beiden Verhältnisse. Man kann sie also beziffern, statt über \"irreführend\" zu streiten. |\n| Keine der drei Grafiken enthält eine **falsche Zahl** | Die Achse ist jedes Mal korrekt beschriftet. Die Täuschung entsteht im Kanal, nicht in den Daten. |\n\n::: {.note-box}\n**Wenn die Unterschiede wirklich klein und trotzdem wichtig sind,** gibt es\nehrliche Auswege:\n\n| Mittel | Wirkung |\n|---|---|\n| **Liniendiagramm** mit beschriftetem Ausschnitt | Steigung trägt die Aussage, der Ausschnitt ist zulässig |\n| **Differenz zum Vorquartal** als Balken | die kleine Grösse wird zur eigentlichen Grösse, Achse ab null |\n| **Indexiert** auf Q1 = 100 | zeigt die relative Veränderung direkt |\n| Werte **anschreiben** | die Zahl steht da, unabhängig vom Eindruck |\n\nAlle vier zeigen den Unterschied deutlich, ohne die Länge zu missbrauchen.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Ein Zuwachs von 5.2 Prozent erscheint bei einer Achse ab 90 als Verhältnis\n> 1.83 und bei einer Achse ab 95 als Verhältnis 6.0 — eine Übertreibung um den\n> Faktor 1.74 beziehungsweise 5.70, bei jedes Mal korrekt beschrifteter Achse.\n\n### Beispiel 2: Zwei Achsen, kein Zusammenhang\n\n#### Frage und Datenlage\n\nZwei Reihen, die nichts miteinander zu tun haben — beide sind reine\nIrrfahrten aus getrennten Zufallsströmen. Wie oft sehen solche Paare trotzdem\nnach einem Zusammenhang aus? 500 Paare über 36 Monate geben die Antwort.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN <- 500; n_zeit <- 36\nZ <- normalmatrix(2323, 2 * N, n_zeit)\n\nr_niveau <- numeric(N); r_aenderung <- numeric(N)\nfor (k in seq_len(N)) {\n  a <- cumsum(Z[2 * k - 1, ]); b <- cumsum(Z[2 * k, ])\n  r_niveau[k] <- cor(a, b)\n  r_aenderung[k] <- cor(diff(a), diff(b))\n}\n\nround(c(anteil_niveau_ueber_0.5 = mean(abs(r_niveau) > 0.5),\n        anteil_niveau_ueber_0.8 = mean(abs(r_niveau) > 0.8),\n        anteil_aenderung_ueber_0.5 = mean(abs(r_aenderung) > 0.5),\n        mittleres_abs_r_niveau = mean(abs(r_niveau)),\n        mittleres_abs_r_aenderung = mean(abs(r_aenderung))), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   anteil_niveau_ueber_0.5    anteil_niveau_ueber_0.8 \n                    0.4020                     0.0800 \nanteil_aenderung_ueber_0.5     mittleres_abs_r_niveau \n                    0.0040                     0.4211 \n mittleres_abs_r_aenderung \n                    0.1373 \n```\n\n\n:::\n\n```{.r .cell-code}\nk <- which.max(abs(r_niveau))\nround(c(paar = k, r_niveau = r_niveau[k], r_aenderung = r_aenderung[k]), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       paar    r_niveau r_aenderung \n   372.0000     -0.9508     -0.1239 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\na <- 100 + cumsum(Z[2 * k - 1, ] * 2)\nb <- 50 + cumsum(Z[2 * k, ] * 1.2)\nround(c(r_der_gezeigten_reihen = cor(a, b),\n        r_der_aenderungen = cor(diff(a), diff(b))), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nr_der_gezeigten_reihen      r_der_aenderungen \n               -0.9508                -0.1239 \n```\n\n\n:::\n\n```{.r .cell-code}\npar(mar = c(4, 4, 2, 4))\nplot(a, type = \"l\", lwd = 2, col = \"grey35\", xlab = \"Monat\", ylab = \"Reihe A\")\npar(new = TRUE)\nplot(b, type = \"l\", lwd = 2, col = akzent, axes = FALSE, xlab = \"\", ylab = \"\")\naxis(4, col = akzent, col.axis = akzent)\nmtext(\"Reihe B\", side = 4, line = 2.5, col = akzent)\n```\n\n::: {.cell-output-display}\n![Beispiel 2: das auffälligste der 500 Paare, an zwei y-Achsen gezeichnet.](irrefuehrende-darstellungen_files/figure-html/fig-b2-ir-r-1.png){#fig-b2-ir-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nN, T = 500, 36\nZ = normalmatrix(2323, 2 * N, T)\n\nr_niveau = np.empty(N)\nr_aenderung = np.empty(N)\nfor k in range(N):\n    a = np.cumsum(Z[2 * k]); b = np.cumsum(Z[2 * k + 1])\n    r_niveau[k] = np.corrcoef(a, b)[0, 1]\n    r_aenderung[k] = np.corrcoef(np.diff(a), np.diff(b))[0, 1]\n\nprint({\"anteil_niveau_ueber_0.5\": round(float((abs(r_niveau) > 0.5).mean()), 4),\n       \"anteil_niveau_ueber_0.8\": round(float((abs(r_niveau) > 0.8).mean()), 4),\n       \"anteil_aenderung_ueber_0.5\": round(float((abs(r_aenderung) > 0.5).mean()), 4),\n       \"mittleres_abs_r_niveau\": round(float(np.abs(r_niveau).mean()), 4),\n       \"mittleres_abs_r_aenderung\": round(float(np.abs(r_aenderung).mean()), 4)})\n\nk = int(np.argmax(np.abs(r_niveau)))\nprint({\"paar\": k + 1, \"r_niveau\": round(float(r_niveau[k]), 4),\n       \"r_aenderung\": round(float(r_aenderung[k]), 4)})\n```\n:::\n\n\n\n::: {.cell}\n\n```{.python .cell-code}\na = 100 + np.cumsum(Z[2 * k] * 2)\nb = 50 + np.cumsum(Z[2 * k + 1] * 1.2)\nprint({\"r_der_gezeigten_reihen\": round(float(np.corrcoef(a, b)[0, 1]), 4),\n       \"r_der_aenderungen\": round(float(np.corrcoef(np.diff(a), np.diff(b))[0, 1]), 4)})\n\nfig, achse = plt.subplots(figsize=(7, 3.2))\n_ = achse.plot(np.arange(1, T + 1), a, lw=2, color=\"0.35\")\n_ = achse.set_xlabel(\"Monat\")\n_ = achse.set_ylabel(\"Reihe A\")\nzweite = achse.twinx()\n_ = zweite.plot(np.arange(1, T + 1), b, lw=2, color=AKZENT)\n_ = zweite.set_ylabel(\"Reihe B\", color=AKZENT)\n_ = zweite.tick_params(axis=\"y\", colors=AKZENT)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselbe Grafik in Python.](irrefuehrende-darstellungen_files/figure-html/fig-b2-ir-py-1.png){#fig-b2-ir-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n500 Paare unabhängiger Irrfahrten über 36 Monate:\n\n| Grösse | Wert |\n|---|---|\n| Anteil mit \\|r\\| > 0.5 zwischen den **Niveaus** | **40.2 Prozent** |\n| Anteil mit \\|r\\| > 0.8 zwischen den Niveaus | **8.0 Prozent** |\n| Anteil mit \\|r\\| > 0.5 zwischen den **Veränderungen** | **0.4 Prozent** |\n| mittleres \\|r\\| der Niveaus | **0.4211** |\n| mittleres \\|r\\| der Veränderungen | **0.1373** |\n\nDas auffälligste Paar (Nummer 371):\n\n| Grösse | Wert |\n|---|---|\n| Korrelation der Niveaus | **−0.9508** |\n| Korrelation der Veränderungen | **−0.1239** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| In **40 Prozent** der Fälle korrelieren die Niveaus über 0.5 | Bei Reihen, die **nachweislich** nichts miteinander zu tun haben — sie stammen aus getrennten Zufallsströmen. |\n| In **8 Prozent** der Fälle sogar über 0.8 | Das ist der Bereich, in dem eine Grafik überzeugend aussieht. Bei acht von hundert zufälligen Paaren. |\n| Bei den **Veränderungen** passiert das fast nie | 0.4 Prozent statt 40. **Der Gleichlauf steckt im Wandern, nicht im Zusammenhang.** |\n| Das gezeigte Paar hat r = **−0.9508** | Und die Veränderungen nur −0.1239. Die Grafik legt einen starken Gegenlauf nahe, von dem in den Monatsveränderungen nichts zu finden ist. |\n| Die zweite Achse macht es **sichtbar überzeugend** | Sie gleicht Niveau und Massstab aus, sodass beide Kurven denselben Raum füllen. Ohne sie läge die eine Kurve oben und die andere unten, und niemand hielte das für einen Zusammenhang. |\n\n::: {.warning-box}\n**Zwei Fehler kommen hier zusammen, und beide sind vermeidbar.**\n\n| Fehler | Prüfung |\n|---|---|\n| Niveaus wandernder Reihen korrelieren | **Veränderungen** korrelieren, nicht Niveaus — siehe [Stationarität](../statistik/zeitreihen/stationaritaet-acf-pacf.qmd) |\n| Die zweite Achse erzeugt Deckungsgleichheit | zwei Teilgrafiken übereinander mit gemeinsamer Zeitachse |\n\nDie ehrliche Grafik für die Frage \"hängen die beiden zusammen?\" ist das\n**Streudiagramm der Veränderungen** — dort hätte dieses Paar eine formlose\nPunktwolke ergeben.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Von 500 Paaren unabhängiger Irrfahrten über 36 Monate zeigen 40.2 Prozent\n> eine Korrelation der Niveaus über 0.5 und 8.0 Prozent über 0.8; bei den\n> Veränderungen sind es 0.4 Prozent. Das auffälligste Paar erreicht −0.95\n> zwischen den Niveaus und −0.12 zwischen den Veränderungen.\n\n### Beispiel 3: Der gewählte Ausschnitt\n\n#### Frage und Datenlage\n\nEine Reihe über 60 Monate, die insgesamt deutlich fällt. Gesucht wird der\nAusschnitt, der am stärksten **steigt** — und dann die Frage, was eine Grafik\ndieses Ausschnitts aussagen würde.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt <- 0:59\nreihe <- 200 - 1.5 * t + cumsum(qnorm(lehmer(3131, 60)) * 4)\n\nround(c(gesamtsteigung = steigung(t, reihe)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngesamtsteigung \n        -1.257 \n```\n\n\n:::\n\n```{.r .cell-code}\nbestes <- list(steigung = -Inf)\nfor (start in 0:47) {\n  for (laenge in c(12, 18)) {\n    idx <- (start + 1):(start + laenge)\n    s <- steigung(t[idx], reihe[idx])\n    if (s > bestes$steigung) bestes <- list(steigung = s, start = start, laenge = laenge)\n  }\n}\nround(unlist(bestes), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsteigung    start   laenge \n   0.522   34.000   12.000 \n```\n\n\n:::\n\n```{.r .cell-code}\nidx <- (bestes$start + 1):(bestes$start + bestes$laenge)\nround(c(ausschnitt_anfang = reihe[idx[1]],\n        ausschnitt_ende = reihe[idx[length(idx)]],\n        veraenderung_prozent = (reihe[idx[length(idx)]] / reihe[idx[1]] - 1) * 100), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   ausschnitt_anfang      ausschnitt_ende veraenderung_prozent \n               123.0                129.5                  5.3 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(gesamt_anfang = reihe[1], gesamt_ende = reihe[60],\n        veraenderung_prozent = (reihe[60] / reihe[1] - 1) * 100), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       gesamt_anfang          gesamt_ende veraenderung_prozent \n               192.1                119.9                -37.6 \n```\n\n\n:::\n\n```{.r .cell-code}\npar(mar = c(4, 4, 2, 1))\nplot(t, reihe, type = \"l\", lwd = 1.6, col = \"grey55\", xlab = \"Monat\", ylab = \"Wert\")\nlines(t[idx], reihe[idx], lwd = 3, col = akzent)\n```\n\n::: {.cell-output-display}\n![Beispiel 3: der ganze Verlauf, darin der günstigste Ausschnitt hervorgehoben.](irrefuehrende-darstellungen_files/figure-html/fig-b3-ir-r-3.png){#fig-b3-ir-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nt = np.arange(60)\nreihe = 200 - 1.5 * t + np.cumsum(stats.norm.ppf(lehmer(3131, 60)) * 4)\n\nprint({\"gesamtsteigung\": round(steigung(t, reihe), 3)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'gesamtsteigung': -1.257}\n```\n\n\n:::\n\n```{.python .cell-code}\nbestes = {\"steigung\": -np.inf}\nfor start in range(48):\n    for laenge in (12, 18):\n        idx = slice(start, start + laenge)\n        s = steigung(t[idx], reihe[idx])\n        if s > bestes[\"steigung\"]:\n            bestes = {\"steigung\": s, \"start\": start, \"laenge\": laenge}\nprint({k: round(v, 3) for k, v in bestes.items()})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'steigung': 0.522, 'start': 34, 'laenge': 12}\n```\n\n\n:::\n\n```{.python .cell-code}\nidx = slice(bestes[\"start\"], bestes[\"start\"] + bestes[\"laenge\"])\nteil = reihe[idx]\nprint({\"ausschnitt_anfang\": round(float(teil[0]), 1),\n       \"ausschnitt_ende\": round(float(teil[-1]), 1),\n       \"veraenderung_prozent\": round(float((teil[-1] / teil[0] - 1) * 100), 1)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'ausschnitt_anfang': 123.0, 'ausschnitt_ende': 129.5, 'veraenderung_prozent': 5.3}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"gesamt_anfang\": round(float(reihe[0]), 1),\n       \"gesamt_ende\": round(float(reihe[-1]), 1),\n       \"veraenderung_prozent\": round(float((reihe[-1] / reihe[0] - 1) * 100), 1)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'gesamt_anfang': 192.1, 'gesamt_ende': 119.9, 'veraenderung_prozent': -37.6}\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achse = plt.subplots(figsize=(7, 3.2))\n_ = achse.plot(t, reihe, lw=1.6, color=\"0.55\")\n_ = achse.plot(t[idx], teil, lw=3, color=AKZENT)\n_ = achse.set_xlabel(\"Monat\")\n_ = achse.set_ylabel(\"Wert\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: derselbe Verlauf in Python.](irrefuehrende-darstellungen_files/figure-html/fig-b3-ir-py-1.png){#fig-b3-ir-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Betrachtung | Steigung je Monat | Anfang | Ende | Veränderung |\n|---|---|---|---|---|\n| **ganze Reihe**, 60 Monate | **−1.257** | 192.1 | 119.9 | **−37.6 Prozent** |\n| **Ausschnitt**, Monat 35 bis 46 | **+0.522** | 123.0 | 129.5 | **+5.3 Prozent** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die Reihe verliert insgesamt **37.6 Prozent** | Die Steigung ist über 60 Monate klar negativ. |\n| Es gibt einen Zwölfmonatsausschnitt mit **+5.3 Prozent** | Und er ist nicht konstruiert, sondern einfach der beste, den die Suche findet. In verrauschten Daten gibt es ihn fast immer. |\n| Die Steigungen haben **verschiedene Vorzeichen** | −1.257 gegen +0.522. Dieselben Daten, zwei gegensätzliche Aussagen — beide mit korrekt beschrifteten Achsen. |\n| Der Ausschnitt ist **ein Fünftel** der Reihe | Zwölf von 60 Monaten. Das ist kein absurd kleiner Ausschnitt, sondern ein üblicher Berichtszeitraum. |\n| Die Suche nach dem besten Ausschnitt ist **automatisierbar** | Genau das macht sie gefährlich: Man muss nicht lügen wollen, es reicht, den Zeitraum zu wählen, der die Botschaft stützt. |\n\n::: {.note-box}\n**Die Gegenprobe, die immer funktioniert:** dieselbe Grafik mit dem doppelten\nZeitraum zeichnen. Bleibt die Aussage, war der Ausschnitt in Ordnung. Dreht sie\nsich um, gehört der längere Zeitraum in die Grafik — zumindest als blasse\nLinie im Hintergrund, wie in der Abbildung oben.\n\nDas ist die visuelle Entsprechung zum\n[multiplen Testen](../statistik/inferenz/multiples-testen.qmd): Wer lange genug\nsucht, findet einen Ausschnitt, der die gewünschte Aussage stützt.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Reihe fällt über 60 Monate um 37.6 Prozent bei einer Steigung von −1.257\n> je Monat. Der günstigste Zwölfmonatsausschnitt steigt dagegen um 5.3 Prozent\n> mit einer Steigung von +0.522 — dieselben Daten, entgegengesetzte Aussage.\n\n### Beispiel 4: Das Simpson-Paradox\n\n#### Frage und Datenlage\n\nDrei Gruppen zu je 20 Beobachtungen. Innerhalb jeder Gruppe fällt der\nZusammenhang, über alle zusammen steigt er. Die Steigungen machen es eindeutig.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngruppe <- rep(c(\"A\", \"B\", \"C\"), each = 20)\nx <- c(seq(1, 4, length.out = 20), seq(4, 7, length.out = 20),\n       seq(7, 10, length.out = 20))\ny <- c(seq(6, 4, length.out = 20), seq(9, 7, length.out = 20),\n       seq(12, 10, length.out = 20))\n\nround(c(gesamtsteigung = steigung(x, y), gesamtkorrelation = cor(x, y)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   gesamtsteigung gesamtkorrelation \n           0.7977            0.8260 \n```\n\n\n:::\n\n```{.r .cell-code}\nfor (g in c(\"A\", \"B\", \"C\")) {\n  m <- gruppe == g\n  cat(sprintf(\"Gruppe %s: Steigung %7.4f  Korrelation %7.4f\\n\",\n              g, steigung(x[m], y[m]), cor(x[m], y[m])))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGruppe A: Steigung -0.6667  Korrelation -1.0000\nGruppe B: Steigung -0.6667  Korrelation -1.0000\nGruppe C: Steigung -0.6667  Korrelation -1.0000\n```\n\n\n:::\n\n```{.r .cell-code}\nfarben <- c(A = \"#1b7837\", B = \"#762a83\", C = \"#b35806\")\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nplot(x, y, pch = 16, col = \"grey45\", xlab = \"x\", ylab = \"y\",\n     main = \"alle Daten zusammen\")\nabline(lm(y ~ x), lwd = 2)\nplot(x, y, pch = 16, col = farben[gruppe], xlab = \"x\", ylab = \"y\",\n     main = \"nach Gruppen getrennt\")\nfor (g in c(\"A\", \"B\", \"C\")) {\n  m <- gruppe == g\n  abline(lm(y[m] ~ x[m]), lwd = 2, col = farben[[g]])\n}\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 4: links alle Daten zusammen, rechts nach Gruppen getrennt.](irrefuehrende-darstellungen_files/figure-html/fig-b4-ir-r-3.png){#fig-b4-ir-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ngruppe = np.repeat([\"A\", \"B\", \"C\"], 20)\nx = np.concatenate([np.linspace(1, 4, 20), np.linspace(4, 7, 20),\n                    np.linspace(7, 10, 20)])\ny = np.concatenate([np.linspace(6, 4, 20), np.linspace(9, 7, 20),\n                    np.linspace(12, 10, 20)])\n\nprint({\"gesamtsteigung\": round(steigung(x, y), 4),\n       \"gesamtkorrelation\": round(float(np.corrcoef(x, y)[0, 1]), 4)})\nfor g in \"ABC\":\n    m = gruppe == g\n    print(f\"Gruppe {g}: Steigung {steigung(x[m], y[m]):7.4f}\"\n          f\"  Korrelation {np.corrcoef(x[m], y[m])[0, 1]:7.4f}\")\n\nfarben = {\"A\": \"#1b7837\", \"B\": \"#762a83\", \"C\": \"#b35806\"}\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.4))\n_ = achsen[0].scatter(x, y, s=14, color=\"0.45\")\nk, d = np.polyfit(x, y, 1)\n_ = achsen[0].plot(x, k * x + d, lw=2, color=\"black\")\n_ = achsen[0].set_title(\"alle Daten zusammen\")\nfor g in \"ABC\":\n    m = gruppe == g\n    _ = achsen[1].scatter(x[m], y[m], s=14, color=farben[g])\n    kg, dg = np.polyfit(x[m], y[m], 1)\n    _ = achsen[1].plot(x[m], kg * x[m] + dg, lw=2, color=farben[g])\n_ = achsen[1].set_title(\"nach Gruppen getrennt\")\nfor achse in achsen:\n    _ = achse.set_xlabel(\"x\")\n    _ = achse.set_ylabel(\"y\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselbe Gegenüberstellung in Python.](irrefuehrende-darstellungen_files/figure-html/fig-b4-ir-py-1.png){#fig-b4-ir-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Betrachtung | Steigung | Korrelation |\n|---|---|---|\n| **alle Daten zusammen** | **+0.7977** | **+0.826** |\n| Gruppe A | **−0.6667** | **−1.000** |\n| Gruppe B | **−0.6667** | **−1.000** |\n| Gruppe C | **−0.6667** | **−1.000** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die Gesamtsteigung ist **positiv**, jede Gruppensteigung **negativ** | +0.80 gegen dreimal −0.67. Das ist kein Rundungsartefakt und kein Zufall der Stichprobe. |\n| Die Korrelation innerhalb der Gruppen ist **exakt −1** | Die Daten sind bewusst so gebaut: In jeder Gruppe ist der Zusammenhang perfekt und fallend. |\n| Trotzdem beträgt die Gesamtkorrelation **+0.83** | Weil die Gruppen entlang der Diagonalen versetzt liegen: Gruppe C hat sowohl höhere x- als auch höhere y-Werte. |\n| Die Grafik links ist **nicht falsch** | Sie beantwortet nur eine andere Frage: \"Wie hängen x und y zusammen, wenn ich die Gruppe nicht kenne?\" |\n| Welche Darstellung richtig ist, entscheidet die **Fragestellung** | Geht es um den Effekt innerhalb vergleichbarer Fälle, ist die getrennte Darstellung die richtige. Geht es um die Vorhersage ohne Kenntnis der Gruppe, die gemeinsame. |\n\n::: {.note-box}\n**Woran man den Verdacht früh bemerkt:** Wenn die Punktwolke in Klumpen\nzerfällt, ist die Gruppierung meist schon zu sehen — noch bevor man weiss,\nwelche Variable sie erzeugt. Das ist ein Grund, **immer zuerst das\nStreudiagramm** anzusehen und nicht nur die Korrelationszahl.\n\nDer statistische Hintergrund steht unter\n[Korrelation](../statistik/grundlagen/korrelation.qmd) und\n[multiple lineare Regression](../statistik/regression/multiple-lineare-regression.qmd);\ndort ist es dieselbe Sache unter dem Namen **Konfundierung**.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Über alle 60 Beobachtungen steigt der Zusammenhang mit einer Steigung von\n> +0.80 und einer Korrelation von +0.83; innerhalb jeder der drei Gruppen\n> fällt er mit −0.67 und einer Korrelation von exakt −1. Beide Grafiken zeigen\n> dieselben Daten und beantworten verschiedene Fragen.\n\n### Beispiel 5: Prozent, Prozentpunkte und die fehlende Basis\n\n#### Frage und Datenlage\n\nZwei Veränderungen, die sich in der Grafik gleich gross darstellen lassen: eine\nNebenwirkungsrate von 2 auf 3 Prozent und ein Marktanteil von 40 auf 44\nProzent. Welche ist die grössere?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfaelle <- data.frame(\n  name = c(\"Nebenwirkung\", \"Marktanteil\"),\n  vorher = c(0.02, 0.40),\n  nachher = c(0.03, 0.44))\n\nfaelle$punkte <- (faelle$nachher - faelle$vorher) * 100\nfaelle$relativ <- (faelle$nachher / faelle$vorher - 1) * 100\nfaelle$betroffene_je_1000 <- (faelle$nachher - faelle$vorher) * 1000\nprint(faelle)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          name vorher nachher punkte relativ betroffene_je_1000\n1 Nebenwirkung   0.02    0.03      1      50                 10\n2  Marktanteil   0.40    0.44      4      10                 40\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(4, 6, 3, 1))\nbarplot(faelle$punkte, names.arg = faelle$name, horiz = TRUE, las = 1,\n        col = neutral, border = NA, xlab = \"Prozentpunkte\",\n        main = \"absolut\")\nbarplot(faelle$relativ, names.arg = faelle$name, horiz = TRUE, las = 1,\n        col = akzent, border = NA, xlab = \"Prozent\",\n        main = \"relativ\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselben zwei Veränderungen, links absolut, rechts relativ.](irrefuehrende-darstellungen_files/figure-html/fig-b5-ir-r-3.png){#fig-b5-ir-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfaelle = pd.DataFrame({\"name\": [\"Nebenwirkung\", \"Marktanteil\"],\n                       \"vorher\": [0.02, 0.40],\n                       \"nachher\": [0.03, 0.44]})\nfaelle[\"punkte\"] = (faelle[\"nachher\"] - faelle[\"vorher\"]) * 100\nfaelle[\"relativ\"] = (faelle[\"nachher\"] / faelle[\"vorher\"] - 1) * 100\nfaelle[\"betroffene_je_1000\"] = (faelle[\"nachher\"] - faelle[\"vorher\"]) * 1000\nprint(faelle.to_string(index=False))\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3))\n_ = achsen[0].barh(faelle[\"name\"], faelle[\"punkte\"], color=NEUTRAL)\n_ = achsen[0].set_xlabel(\"Prozentpunkte\")\n_ = achsen[0].set_title(\"absolut\")\n_ = achsen[1].barh(faelle[\"name\"], faelle[\"relativ\"], color=AKZENT)\n_ = achsen[1].set_xlabel(\"Prozent\")\n_ = achsen[1].set_title(\"relativ\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselbe Gegenüberstellung in Python.](irrefuehrende-darstellungen_files/figure-html/fig-b5-ir-py-1.png){#fig-b5-ir-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Fall | vorher | nachher | Prozentpunkte | relative Zunahme | Betroffene je 1000 |\n|---|---|---|---|---|---|\n| Nebenwirkung | 2 % | 3 % | **1.0** | **+50.0 %** | **10** |\n| Marktanteil | 40 % | 44 % | **4.0** | **+10.0 %** | **40** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Absolut ist der **Marktanteil** die grössere Veränderung | 4.0 gegen 1.0 Prozentpunkte, also das Vierfache. |\n| Relativ ist die **Nebenwirkung** die grössere | +50 gegen +10 Prozent, also das Fünffache. |\n| Beide Aussagen sind **richtig** | Und sie führen zu entgegengesetzten Rangfolgen. Die linke und die rechte Grafik widersprechen sich nicht, sie messen Verschiedenes. |\n| \"50 Prozent mehr Nebenwirkungen\" klingt alarmierend | Betrifft aber **10 von 1000** zusätzlich. Die absolute Zahl ist diejenige, nach der man handelt. |\n| Wer nur eine der beiden Grafiken zeigt, hat **entschieden** | Ohne es zu sagen. Deshalb gehört die Basis dazu: \"von 2 auf 3 Prozent\" ist vollständig, \"50 Prozent mehr\" ist es nicht. |\n\n::: {.warning-box}\n**Die Regel für Berichte:** Immer **beides** nennen — die relative Veränderung\n**und** die absolute, mit Basis.\n\n| Formulierung | vollständig? |\n|---|---|\n| \"50 Prozent mehr Nebenwirkungen\" | nein — die Basis fehlt |\n| \"ein Prozentpunkt mehr\" | nein — die Grössenordnung fehlt |\n| \"von 2 auf 3 Prozent, also 10 zusätzliche Fälle je 1000\" | **ja** |\n\nDasselbe Thema in der Statistik: [Effektstärken](../statistik/inferenz/effektstaerken.qmd)\nund [bedingte Wahrscheinlichkeit](../statistik/wahrscheinlichkeit/bedingte-wahrscheinlichkeit-bayes.qmd),\nwo die Basisrate über die Aussagekraft eines Tests entscheidet.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Der Anstieg von 2 auf 3 Prozent ist relativ mit +50 Prozent die grössere\n> Veränderung, absolut mit 1.0 Prozentpunkten die kleinere; beim Marktanteil\n> von 40 auf 44 Prozent ist es umgekehrt (+10 Prozent, 4.0 Prozentpunkte).\n> Beide Darstellungen sind korrekt und ergeben entgegengesetzte Rangfolgen.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEin Liniendiagramm zeigt die Serverauslastung zwischen 68 und 74 Prozent, die\nAchse beginnt bei 65. Ist das irreführend?\n\n- [ ] Ja, jede Achse muss bei null beginnen ~ Diese Regel gilt für Balken, nicht\n      allgemein.\n- [x] Nein, bei Linien trägt die Steigung die Aussage ~ Richtig. Eine Achse ab\n      null würde den Verlauf zu einer flachen Linie zusammendrücken und die\n      Information vernichten. Der Ausschnitt gehört beschriftet, mehr nicht.\n- [ ] Nur, wenn die Schwankung klein ist ~ Die Grösse der Schwankung ändert die\n      Logik nicht.\n:::\n\n::: {.quiz}\nVier Balken mit den Werten 96 bis 101 werden ab 95 gezeichnet. Wie stark ist\nder Eindruck verzerrt?\n\n- [x] Um das rund 5.7-Fache ~ Richtig. Das echte Verhältnis ist 1.052, die\n      Balkenlängen stehen dann im Verhältnis 6.0. Je näher der Achsenanfang an\n      den Daten liegt, desto grösser die Verzerrung.\n- [ ] Um das Doppelte ~ Das wäre ungefähr der Fall bei einem Achsenanfang von\n      90, dort beträgt die Verzerrung 1.74.\n- [ ] Gar nicht, die Achse ist ja beschriftet ~ Die Beschriftung ist korrekt,\n      der Kanal Länge behauptet trotzdem etwas anderes.\n:::\n\n::: {.quiz}\nEine Infografik stellt zwei Beträge als Kreise dar, der zweite ist doppelt so\ngross im Durchmesser. Wie liest das Publikum das?\n\n- [x] Als das Vierfache, weil die Fläche quadratisch wächst ~ Richtig.\n      Wahrgenommen wird die Fläche. Wer den Betrag verdoppeln will,\n      multipliziert den Radius mit der Wurzel aus zwei.\n- [ ] Als das Doppelte, weil der Durchmesser verdoppelt wurde ~ Der Durchmesser\n      ist nicht der Kanal, über den gelesen wird.\n- [ ] Das hängt von der Legende ab ~ Eine Legende korrigiert den optischen\n      Eindruck nicht.\n:::\n\n::: {.quiz}\nZwei Zeitreihen an zwei y-Achsen laufen auffällig im Gleichschritt. Was ist die\nerste Prüfung?\n\n- [x] Die Korrelation der Veränderungen statt der Niveaus ansehen ~ Richtig. Bei\n      500 Paaren unabhängiger Irrfahrten lag die Korrelation der Niveaus in\n      40 Prozent der Fälle über 0.5, die der Veränderungen nur in 0.4 Prozent.\n      Der Gleichlauf steckt im Wandern.\n- [ ] Prüfen, ob die Achsen beschriftet sind ~ Sie sind es typischerweise; das\n      Problem sind die zwei frei wählbaren Parameter der zweiten Achse.\n- [ ] Die Stichprobe vergrössern ~ Bei längeren Irrfahrten wird die\n      Scheinkorrelation nicht kleiner.\n:::\n\n::: {.quiz}\nEine Reihe fällt über 60 Monate um 37.6 Prozent. Ein Bericht zeigt einen\nZwölfmonatsausschnitt mit +5.3 Prozent. Ist die Grafik falsch?\n\n- [x] Nein, aber unvollständig — die Aussage dreht sich mit dem Ausschnitt um ~\n      Richtig. Die Zahlen und Achsen stimmen, die Botschaft steckt in der Wahl\n      des Zeitraums. Die Gegenprobe ist der doppelte Zeitraum.\n- [ ] Ja, ein solcher Ausschnitt ist immer unzulässig ~ Ein Berichtszeitraum\n      von zwölf Monaten ist üblich; entscheidend ist, ob der längere Verlauf\n      etwas anderes sagt.\n- [ ] Nein, zwölf Monate sind repräsentativ genug ~ Hier waren sie es gerade\n      nicht: die Steigungen haben verschiedene Vorzeichen.\n:::\n\n::: {.quiz}\nEine Nebenwirkung steigt von 2 auf 3 Prozent. Wie berichtet man das\nvollständig?\n\n- [x] Von 2 auf 3 Prozent, also 10 zusätzliche Fälle je 1000 ~ Richtig,\n      relative und absolute Angabe mit Basis. \"50 Prozent mehr\" allein\n      verschweigt, wie klein die Basis ist.\n- [ ] 50 Prozent mehr Nebenwirkungen ~ Richtig gerechnet, aber ohne die Basis\n      nicht einzuordnen.\n- [ ] Ein Prozentpunkt mehr ~ Richtig gerechnet, verschweigt aber, dass sich\n      die Rate um die Hälfte erhöht hat.\n:::\n\n## Verlinkte Ressourcen\n\n- [Claus Wilke: Common pitfalls of color use und weitere Fallen](https://clauswilke.com/dataviz/)\n- [Calling Bullshit: Misleading Axes](https://www.callingbullshit.org/tools/tools_misleading_axes.html)\n- [Simpson-Paradox erklärt](https://plato.stanford.edu/entries/paradox-simpson/)\n- [Wahrnehmung und Kodierung](wahrnehmung-kodierung.qmd) — die Kanäle, die hier missbraucht werden\n- [Korrelation](../statistik/grundlagen/korrelation.qmd) — Scheinkorrelation und Konfundierung\n",
    "supporting": [
      "irrefuehrende-darstellungen_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}