{
  "hash": "9c1a97779d00b3d7563f7ef19b2d776b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Cox-Modell\"\ndescription: \"Hazard Ratio, proportionale Hazards und die Deutung mehrerer Einflussgrössen.\"\ncategories: [\"Survival-Analyse\", \"Regression\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: methode\nstand: fertig\norder: 40\n---\n\n\n\n\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Wie beeinflussen mehrere Grössen gleichzeitig das momentane Risiko eines Ereignisses? |\n| Zielvariable | Zeit bis zum Ereignis plus Statusindikator |\n| Prädiktoren | beliebig viele, metrisch oder kategorial |\n| Was die Methode liefert | Hazard Ratio je Prädiktor mit Konfidenzintervall und p-Wert, Gesamttests, Konkordanz |\n| R-Funktion | `coxph(Surv(zeit, status) ~ x1 + x2)`, geprüft mit `cox.zph()` |\n| Python-Funktion | `CoxPHFitter().fit(df, duration_col, event_col)`, geprüft mit `proportional_hazard_test()` |\n| Verwandte Methoden | [Kaplan-Meier](kaplan-meier.qmd), [Log-Rank-Test](log-rank-test.qmd), [logistische Regression](../regression/logistische-regression.qmd) |\n\n## Wann diese Methode, wann nicht\n\nTypische Fragestellungen: Welche Merkmale erhöhen das Kündigungsrisiko, wie\nwirkt eine Behandlung bei gleichem Alter, welchen Beitrag hat die Distanz zum\nStudio, wenn die Vertragsart konstant gehalten wird.\n\nDas Cox-Modell ist der Schritt vom Vergleich zum Effektmass. Es liefert je\nPrädiktor ein Hazard Ratio, also einen Faktor, um den sich das momentane Risiko\nändert, und kann dabei mehrere Grössen gleichzeitig berücksichtigen. Es heisst\nsemiparametrisch, weil es den zeitlichen Verlauf des Grundrisikos offenlässt und\nnur die Verhältnisse zwischen den Beobachtungen modelliert.\n\n| Situation | Stattdessen |\n|---|---|\n| Nur eine beschreibende Kurve gesucht | [Kaplan-Meier](kaplan-meier.qmd) |\n| Nur die Frage, ob zwei Gruppen sich unterscheiden | [Log-Rank-Test](log-rank-test.qmd) |\n| Zeitdimension unwichtig, nur ob das Ereignis eintrat | [logistische Regression](../regression/logistische-regression.qmd) |\n| Der Effekt ändert sich deutlich über die Zeit | Stratifizierung oder zeitabhängige Koeffizienten |\n| Verteilungsform ist begründet und Extrapolation nötig | parametrische Modelle, etwa Weibull |\n| Zielgrösse ist metrisch ohne Zensierung | [multiple lineare Regression](../regression/multiple-lineare-regression.qmd) |\n\n## Grundidee und Modell\n\nDas Modell zerlegt das Risiko in zwei Teile: einen zeitlichen Verlauf, der für\nalle gleich ist, und einen Faktor, der von den Prädiktoren abhängt und über die\nZeit konstant bleibt.\n\n$$h(t \\mid x) = h_0(t) \\cdot e^{\\beta_1 x_1 + \\dots + \\beta_k x_k}$$\n\n| Bestandteil | Bedeutung |\n|---|---|\n| $h(t \\mid x)$ | Hazard-Rate bei Prädiktorwerten $x$: momentanes Risiko, keine Wahrscheinlichkeit |\n| $h_0(t)$ | Grundrisiko über die Zeit, bleibt unspezifiziert und wird nicht geschätzt |\n| $\\beta_j$ | Effekt von $x_j$ auf den logarithmierten Hazard |\n| $e^{\\beta_j}$ | Hazard Ratio: Faktor, um den sich das Risiko je Einheit von $x_j$ ändert, bei konstant gehaltenen übrigen Prädiktoren |\n| $e^{\\beta_1 x_1 + \\dots}$ | gemeinsamer Faktor aller Prädiktoren |\n\nGeschätzt wird über die partielle Likelihood, die nur die Reihenfolge der\nEreignisse nutzt: Zu jedem Ereigniszeitpunkt wird gefragt, wie wahrscheinlich es\nwar, dass gerade diese Beobachtung das Ereignis hatte, gegeben wer zu diesem\nZeitpunkt unter Risiko stand. Das Grundrisiko kürzt sich dabei heraus, und genau\ndeshalb muss es nie geschätzt werden.\n\n::: {.note-box}\n**Was \"proportional\" heisst.** Zwei Beobachtungen mit verschiedenen\nPrädiktorwerten haben Hazard-Kurven, die zu jedem Zeitpunkt im **selben\nVerhältnis** stehen. Steigt und fällt das Grundrisiko im Lauf der Zeit, tun das\nbeide Kurven gemeinsam; ihr Abstand auf der Log-Skala bleibt konstant. Genau\ndiese Annahme macht ein einzelnes Hazard Ratio überhaupt erst sinnvoll — und\ngenau sie wird in Beispiel 4 verletzt.\n:::\n\nEin Hazard Ratio von 2 bedeutet: doppeltes momentanes Risiko. Es bedeutet nicht\ndoppelt so schnell, nicht halbe Laufzeit und nicht doppelte Wahrscheinlichkeit.\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung | Vorgehen |\n|---|---|---|---|---|\n| Proportionale Hazards | Das Hazard Ratio ist über die Zeit konstant | `cox.zph()` beziehungsweise `proportional_hazard_test()`, dazu die Residuenplots | Ein einzelnes Hazard Ratio ist irreführend, weil es über verschiedene Zeiträume mittelt | Stratifizieren, zeitabhängigen Effekt aufnehmen, Zeitabschnitte trennen |\n| Linearität im Log-Hazard | Metrische Prädiktoren wirken linear auf den logarithmierten Hazard | Martingale-Residuen gegen den Prädiktor | Verzerrte Schätzung, falsche Funktionsform | Transformation, Splines, Klassenbildung |\n| Nicht informative Zensierung | Zensierte haben dasselbe Risiko wie Beobachtete | inhaltlich, siehe [Zensierung](zensierung-ueberlebensfunktion.qmd) | Alle Schätzungen verzerrt | Ursachen berichten |\n| Unabhängige Beobachtungen | keine Klumpen, keine Wiederholungen je Person | Erhebungsdesign | Standardfehler zu klein | robuste Varianz, Frailty-Modelle |\n| Keine starke Multikollinearität | Prädiktoren sind nicht nahezu Linearkombinationen | Korrelationen, VIF auf dem linearen Prädiktor | Instabile Koeffizienten, wie bei der [multiplen Regression](../regression/multiple-lineare-regression.qmd) | Variable entfernen oder zusammenfassen |\n| Genügend Ereignisse je Prädiktor | Faustregel: mindestens etwa zehn Ereignisse je geschätztem Koeffizienten | Ereignisse zählen | Überanpassung, zu enge Intervalle | Modell verkleinern |\n\n## Output lesen\n\nR, `summary(coxph(...))`:\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| `n`, `number of events` | Beobachtungen und Ereignisse | die Ereigniszahl trägt die Genauigkeit |\n| `coef` | geschätztes $\\beta_j$, Effekt auf den log-Hazard | Vorzeichen zeigt die Richtung |\n| `exp(coef)` | Hazard Ratio | 1 heisst kein Effekt, über 1 höheres Risiko |\n| `se(coef)` | Standardfehler auf der log-Skala | Intervalle werden dort gebildet und dann exponiert |\n| `z`, `Pr(>|z|)` | Wald-Test je Koeffizient | prüft nur diesen Koeffizienten |\n| `lower .95`, `upper .95` | Konfidenzintervall des Hazard Ratio | enthält es 1, ist der Effekt nicht signifikant |\n| `Concordance` | Anteil richtig geordneter Paare | 0.5 ist Zufall, ab etwa 0.7 brauchbar |\n| `Likelihood ratio test` | Gesamttest gegen das Nullmodell | Gegenstück zum F-Test der linearen Regression |\n| `Wald test`, `Score (logrank) test` | zwei weitere Gesamttests | bei grossem n praktisch gleich; der Score-Test ist bei einem kategorialen Prädiktor der Log-Rank-Test |\n| `cox.zph()` | Prüfung der Proportionalität | kleiner p-Wert heisst Annahme verletzt, nicht Modell bestätigt |\n\nPython, `CoxPHFitter.print_summary()`:\n\n| Grösse | Was sie sagt | Unterschied zu R |\n|---|---|---|\n| `coef`, `exp(coef)` | wie in R | identisch |\n| `se(coef)`, `z`, `p` | wie in R | identisch |\n| `coef lower 95%`, `exp(coef) lower 95%` | Intervalle auf beiden Skalen | R zeigt nur die exponierten Grenzen |\n| `-log2(p)` | p-Wert als Bits | in R nicht enthalten |\n| `Concordance` | wie in R | identisch |\n| `Partial AIC` | Kennzahl für Modellvergleiche | in R über `AIC(modell)` |\n| `log-likelihood ratio test` | Gesamttest | wie in R |\n\nDrei Unterschiede in der Handhabung:\n\n1. In Python müssen **kategoriale Prädiktoren selbst als Indikatorvariablen**\n   vorliegen, R übernimmt das über Faktoren.\n2. Die **Referenzkategorie** ist in R die erste Faktorstufe, in Python die mit\n   dem Wert null; die Richtung des Hazard Ratio hängt daran.\n3. Die **Prüfung der Proportionalität** verwendet verschiedene\n   Zeittransformationen: `cox.zph()` in R standardmässig eine\n   Kaplan-Meier-Transformation, `proportional_hazard_test()` in Python das, was\n   man in `time_transform` angibt. Die p-Werte weichen deshalb ab, ohne dass\n   einer falsch wäre.\n\n## Interpretationsfallen\n\n- **Hazard Ratio ist kein Zeitverhältnis.** Ein Faktor 2 bedeutet doppeltes\n  momentanes Risiko, nicht halbe Laufzeit.\n- **Hazard Ratio ist keine Wahrscheinlichkeit.** Es ist ein Verhältnis von\n  Raten und kann beliebig über eins liegen.\n- **Ein einzelnes Hazard Ratio setzt Proportionalität voraus.** Ohne diese\n  Prüfung ist die Zahl ein Mittel über Zeiträume, die sich unterscheiden können.\n- **Ein signifikanter Test auf Proportionalität bestätigt nicht das Modell**, er\n  weist auf eine Verletzung hin. Umgekehrt beweist ein grosser p-Wert die\n  Annahme nicht, er widerlegt sie nur nicht.\n- **Je Einheit ist nicht je Spannweite.** Bei metrischen Prädiktoren gehört der\n  Effekt für einen fachlich sinnvollen Abstand berichtet.\n- **Bei konstant gehaltenen anderen Prädiktoren** heisst: unter den aufgenommenen.\n  Eine nicht erhobene gemeinsame Ursache bleibt unsichtbar; ein Hazard Ratio ist\n  keine Kausalaussage.\n- **Konkordanz ist keine Signifikanz.** Ein Modell kann signifikante Effekte und\n  eine Konkordanz nahe 0.5 haben.\n- **Die Ereigniszahl begrenzt das Modell**, nicht die Fallzahl. Mit 40 Ereignissen\n  sind vier Prädiktoren zu viel.\n\n## Ergebnis berichten\n\nVorlage für den Ergebnissatz:\n\n> In einem Cox-Modell mit [Prädiktoren] ist [Prädiktor] mit dem Risiko\n> assoziiert: Hazard Ratio [Wert] (95-Prozent-Konfidenzintervall [unten] bis\n> [oben], p = [p]), bei konstant gehaltenen übrigen Prädiktoren. Das Modell\n> beruht auf [n] Beobachtungen mit [Ereignisse] Ereignissen; die Konkordanz\n> beträgt [Wert]. Die Annahme proportionaler Hazards wurde geprüft [Ergebnis].\n\nImmer genannt werden: Hazard Ratio mit Konfidenzintervall und p-Wert je\nPrädiktor, n und Ereigniszahl getrennt, Konkordanz, das Ergebnis der\nProportionalitätsprüfung und bei metrischen Prädiktoren die Einheit, auf die sich\ndas Hazard Ratio bezieht.\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt des Cox-Modells |\n|---|---|\n| [Kaplan-Meier](kaplan-meier.qmd) | beschreibende Kurve ohne Einflussgrössen |\n| [Log-Rank-Test](log-rank-test.qmd) | nur die Frage, ob sich zwei Gruppen unterscheiden |\n| [Logistische Regression](../regression/logistische-regression.qmd) | nur ob, nicht wann; keine Zensierung |\n| Parametrische Modelle, etwa Weibull | Verteilungsform begründet, Vorhersage über den Beobachtungszeitraum hinaus |\n| Modelle mit zeitabhängigen Effekten | Proportionalität verletzt und der Effekt selbst interessiert |\n| Frailty-Modelle | geschachtelte oder wiederholte Ereignisse je Person |\n\n## Beispiele\n\nDie Beispiele 1 bis 3 und 5 arbeiten mit dem Abo-Datensatz aus\n[Kaplan-Meier](kaplan-meier.qmd): 400 Fitnessabos, Vertragsart und Distanz zum\nStudio als Einflussgrössen, Stichtag nach 24 Monaten. Eingebaut sind ein Faktor\n$e^{0.85} = 2.34$ für den Monatsvertrag und $e^{0.045} = 1.046$ je Kilometer.\nBeispiel 4 verwendet den Datensatz mit kreuzenden Kurven aus dem\n[Log-Rank-Test](log-rank-test.qmd).\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Das Modell und seine Zahlen\n\n#### Frage und Datenlage\n\nWie stark wirken Vertragsart und Distanz auf das Kündigungsrisiko, jeweils bei\nkonstant gehaltener anderer Grösse?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodell <- coxph(Surv(zeit, status) ~ vertrag + distanz, data = abo)\nsummary(modell)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(zeit, status) ~ vertrag + distanz, data = abo)\n\n  n= 400, number of events= 247 \n\n                coef exp(coef) se(coef)     z Pr(>|z|)    \nvertragMonat 1.11846   3.06013  0.14704 7.606 2.82e-14 ***\ndistanz      0.04670   1.04781  0.01578 2.959  0.00309 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n             exp(coef) exp(-coef) lower .95 upper .95\nvertragMonat     3.060     0.3268     2.294     4.082\ndistanz          1.048     0.9544     1.016     1.081\n\nConcordance= 0.663  (se = 0.016 )\nLikelihood ratio test= 80.88  on 2 df,   p=<2e-16\nWald test            = 71.17  on 2 df,   p=4e-16\nScore (logrank) test = 78.26  on 2 df,   p=<2e-16\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ncox = CoxPHFitter().fit(abo, duration_col=\"zeit\", event_col=\"status\")\ncox.print_summary(decimals=4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<lifelines.CoxPHFitter: fitted with 400 total observations, 153 right-censored observations>\n             duration col = 'zeit'\n                event col = 'status'\n      baseline estimation = breslow\n   number of observations = 400\nnumber of events observed = 247\n   partial log-likelihood = -1339.9673\n         time fit was run = 2026-09-11 06:19:44 UTC\n\n---\n                coef exp(coef)  se(coef)  coef lower 95%  coef upper 95% exp(coef) lower 95% exp(coef) upper 95%\ncovariate                                                                                                       \nmonatsvertrag 1.1184    3.0600    0.1470          0.8302          1.4066              2.2939              4.0821\ndistanz       0.0467    1.0478    0.0158          0.0158          0.0776              1.0159              1.0807\n\n               cmp to      z      p  -log2(p)\ncovariate                                    \nmonatsvertrag  0.0000 7.6063 <5e-05   45.0110\ndistanz        0.0000 2.9590 0.0031    8.3396\n---\nConcordance = 0.6626\nPartial AIC = 2683.9345\nlog-likelihood ratio test = 80.8835 on 2 df\n-log2(p) of ll-ratio test = 58.3451\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Konkordanz:\", round(cox.concordance_index_, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKonkordanz: 0.663\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Prädiktor | `coef` $\\beta$ | `se(coef)` | `exp(coef)` = HR | 95-Prozent-Intervall | z | p |\n|---|---|---|---|---|---|---|\n| Monatsvertrag | **1.1184** | 0.1470 | **3.060** | 2.294 – 4.082 | 7.61 | < .001 |\n| Distanz (je km) | **0.0467** | 0.0158 | **1.048** | 1.016 – 1.081 | 2.96 | .003 |\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| `coef` = 1.1184 | Effekt auf den **logarithmierten** Hazard | Auf dieser Skala wird gerechnet, und dort ist der Effekt additiv. Berichtet wird die exponierte Fassung. |\n| `exp(coef)` = **3.060** | Monatsverträge haben das rund Dreifache des momentanen Kündigungsrisikos | **Bei gleicher Distanz.** Das ist der Kern des Modells: Der Vergleich gilt zwischen zwei Personen, die sich nur in der Vertragsart unterscheiden. |\n| Intervall 2.294 – 4.082 | schliesst die 1 nicht ein | Es ist **nicht symmetrisch** um 3.06, weil es auf der Log-Skala gebildet und dann exponiert wird: $e^{1.1184 \\pm 1.96 \\cdot 0.1470}$. |\n| `exp(coef)` = **1.048** für die Distanz | 4.8 Prozent mehr Risiko **je Kilometer** | Je Einheit klein — aber die Einheit ist hier winzig gegenüber der Spannweite. |\n| Distanz über die Spannweite | $e^{0.0467 \\cdot 14.5} = 1.97$ | Zwischen der nächsten und der entferntesten Person liegt fast der Faktor 2. **Das** ist die berichtbare Grösse, nicht die 1.048. |\n| z und p | 7.61 und 2.96 | Wald-Tests je Koeffizient, jeweils gegen die Nullhypothese $\\beta = 0$, also HR = 1. |\n| Konkordanz | **0.663** | Von allen Paaren, deren Reihenfolge bestimmbar ist, ordnet das Modell 66 Prozent richtig. 0.5 wäre Zufall. Ein brauchbarer, kein guter Wert — und das bei zwei Prädiktoren, die den Prozess tatsächlich erzeugt haben. |\n| Likelihood-Ratio-Test | $\\chi^2$(2) = 80.9, p < .001 | Der Gesamttest gegen das Nullmodell, das Gegenstück zum F-Test der linearen Regression. |\n\n::: {.note-box}\n**Die Schätzungen treffen die eingebauten Werte nicht genau**, und das ist\nlehrreich: Eingebaut waren $e^{0.85} = 2.34$ und $e^{0.045} = 1.046$; geschätzt\nwerden 3.06 und 1.048. Die Distanz ist praktisch getroffen, die Vertragsart\ndeutlich überschätzt.\n\nDer Grund ist nicht Zufall, sondern eine Eigenschaft des Modells: Die Daten wurden\naus einer Exponentialverteilung mit individueller Rate erzeugt, das Cox-Modell\nschätzt aber unter der Annahme, dass **alle** Unterschiede zwischen Personen in\nden Prädiktoren stehen. Nicht modellierte Heterogenität lässt Hazard Ratios über\ndie Zeit schrumpfen und wird vom Modell teilweise in den stärksten Prädiktor\ngezogen. Bei einer einzelnen Stichprobe ist das nicht von Zufall zu unterscheiden\n— der Punkt ist, dass die 3.06 mit ihrem Intervall 2.29 bis 4.08 die\n**Modellschätzung** ist und nicht der wahre Erzeugungsparameter.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> In einem Cox-Modell mit Vertragsart und Distanz ist der Monatsvertrag mit einem\n> erhöhten Kündigungsrisiko verbunden: Hazard Ratio 3.06\n> (95-Prozent-Konfidenzintervall 2.29 bis 4.08, p < .001), bei konstant\n> gehaltener Distanz. Je fünf zusätzliche Kilometer steigt das Risiko um den\n> Faktor 1.26 (1.08 bis 1.48). Das Modell beruht auf 400 Beobachtungen mit 247\n> Kündigungen; die Konkordanz beträgt 0.66.\n\n### Beispiel 2: Die Annahme prüfen\n\n#### Frage und Datenlage\n\nEin Hazard Ratio ist nur dann eine sinnvolle Zahl, wenn es über die Zeit\nkonstant ist. Geprüft wird das über die Schoenfeld-Residuen: Hängt der\ngeschätzte Effekt vom Zeitpunkt ab?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npruefung <- cox.zph(modell)\npruefung\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        chisq df     p\nvertrag  1.66  1 0.197\ndistanz  3.71  1 0.054\nGLOBAL   5.74  2 0.057\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nplot(pruefung[1], main = \"Vertragsart\")\nabline(h = coef(modell)[1], col = \"#b2182b\", lty = 2)\nplot(pruefung[2], main = \"Distanz\")\nabline(h = coef(modell)[2], col = \"#b2182b\", lty = 2)\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 2: Schoenfeld-Residuen je Prädiktor. Ein waagrechter Verlauf spricht für proportionale Hazards.](cox-modell_files/figure-html/fig-b2-cox-r-1.png){#fig-b2-cox-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\npruefung = proportional_hazard_test(cox, abo, time_transform=\"rank\")\npruefung.print_summary(decimals=4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<lifelines.StatisticalResult: proportional_hazard_test>\n    time_transform = rank\n null_distribution = chi squared\ndegrees_of_freedom = 1\n             model = <lifelines.CoxPHFitter: fitted with 400 total observations, 153 right-censored observations>\n         test_name = proportional_hazard_test\n\n---\n               test_statistic      p  -log2(p)\ndistanz                4.2288 0.0397    4.6532\nmonatsvertrag          2.1248 0.1449    2.7865\n```\n\n\n:::\n\n```{.python .cell-code}\nereignisse = int(abo[\"status\"].sum())\nprint(\"Ereignisse:\", ereignisse,\n      \"| je geschätztem Koeffizienten:\", round(ereignisse / 2, 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEreignisse: 247 | je geschätztem Koeffizienten: 123.5\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Prädiktor | p (R, `cox.zph`) | p (Python, Rang-Transformation) |\n|---|---|---|\n| Monatsvertrag | 0.197 | **0.145** |\n| Distanz | **0.054** | **0.040** |\n| global | 0.057 | — |\n\n| Ausgabe | Wie sie zu lesen ist |\n|---|---|\n| Was der Test prüft | Ob die Schoenfeld-Residuen mit der Zeit **korrelieren**. Ein Residuum je Ereignis und Prädiktor sagt, ob die Person, die zu diesem Zeitpunkt das Ereignis hatte, einen höheren oder tieferen Prädiktorwert hatte als vom Modell erwartet. Steigen oder fallen diese Abweichungen systematisch, ändert sich der Effekt über die Zeit. |\n| Vertragsart, p = 0.15 bis 0.20 | Kein Hinweis auf eine Verletzung. Der grosse p-Wert **bestätigt die Annahme nicht** — er widerlegt sie nur nicht. |\n| Distanz, p = 0.040 in Python und 0.054 in R | Ein Grenzfall, und ein doppelt lehrreicher: Derselbe Sachverhalt fällt in der einen Umgebung unter die 5-Prozent-Schwelle und in der anderen darüber. |\n| Was mit dem Grenzfall zu tun ist | **Nicht** reflexartig das Modell verwerfen. Der Test wird mit wachsender Ereigniszahl empfindlich; bei 247 Ereignissen werden auch winzige, praktisch bedeutungslose Zeittrends signifikant. Entscheidend ist das **Bild**: Fällt die Residuenkurve über den Beobachtungszeitraum um einen Betrag, der die Deutung ändern würde, oder schwankt sie nur leicht um die waagrechte Linie des geschätzten Koeffizienten? |\n| Ereignisse je Koeffizient | 247 / 2 = 123.5 | Weit über der Faustregel von zehn. Das Modell ist nicht überfrachtet. |\n\n::: {.note-box}\n**R und Python geben hier verschiedene p-Werte aus**, und beide haben recht: Der\nTest hängt davon ab, gegen welche Funktion der Zeit die Residuen korreliert\nwerden. `cox.zph()` verwendet standardmässig eine Kaplan-Meier-Transformation,\n`proportional_hazard_test()` das in `time_transform` Angegebene — oben `\"rank\"`.\nWer den Test berichtet, nennt die Transformation dazu.\n\nEin Test, der auf die Wahl der Zeitachse reagiert, ist ohnehin ein Anlass, das\nErgebnis nicht als Ja-Nein-Entscheidung zu behandeln. Der Residuenplot bleibt\ndas wichtigere Werkzeug.\n:::\n\n#### Interpretation\n\nFür die Vertragsart ist die Annahme unauffällig, für die Distanz grenzwertig.\nBerichtet wird beides zusammen mit der verwendeten Transformation. Beispiel 3\nzeigt, was zu tun ist, wenn eine Verletzung eindeutig ist.\n\n### Beispiel 3: Ein Prädiktor ohne Effekt\n\n#### Frage und Datenlage\n\nWas passiert, wenn eine Variable ins Modell kommt, die mit dem Risiko nichts zu\ntun hat? Aufgenommen wird die durchschnittliche Trainingsdauer in Minuten,\nkonstruiert ohne jeden Zusammenhang zur Kündigung.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nabo$trainingsminuten <- round(55 + 15 * qnorm(lehmer(5555, nrow(abo))))\n\nmodell_b <- coxph(Surv(zeit, status) ~ vertrag + distanz + trainingsminuten,\n                  data = abo)\nround(summary(modell_b)$conf.int[, c(\"exp(coef)\", \"lower .95\", \"upper .95\")], 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 exp(coef) lower .95 upper .95\nvertragMonat        3.0632    2.2962    4.0866\ndistanz             1.0480    1.0160    1.0809\ntrainingsminuten    0.9984    0.9904    1.0065\n```\n\n\n:::\n\n```{.r .cell-code}\nround(summary(modell_b)$coefficients[, \"Pr(>|z|)\"], 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    vertragMonat          distanz trainingsminuten \n          0.0000           0.0030           0.6971 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Vergleich der beiden Modelle\nround(c(konkordanz_ohne = summary(modell)$concordance[1],\n        konkordanz_mit = summary(modell_b)$concordance[1]), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nkonkordanz_ohne.C  konkordanz_mit.C \n           0.6626            0.6594 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(AIC_ohne = AIC(modell), AIC_mit = AIC(modell_b)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAIC_ohne  AIC_mit \n 2683.93  2685.78 \n```\n\n\n:::\n\n```{.r .cell-code}\nanova(modell, modell_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n Cox model: response is  Surv(zeit, status)\n Model 1: ~ vertrag + distanz\n Model 2: ~ vertrag + distanz + trainingsminuten\n   loglik  Chisq Df Pr(>|Chi|)\n1 -1340.0                     \n2 -1339.9 0.1515  1     0.6971\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nabo_b = abo.copy()\nabo_b[\"trainingsminuten\"] = np.round(\n    55 + 15 * stats.norm.ppf(lehmer(5555, len(abo))))\n\ncox_b = CoxPHFitter().fit(abo_b, duration_col=\"zeit\", event_col=\"status\")\nprint(cox_b.summary[[\"exp(coef)\", \"exp(coef) lower 95%\",\n                     \"exp(coef) upper 95%\", \"p\"]].round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  exp(coef)  exp(coef) lower 95%  exp(coef) upper 95%       p\ncovariate                                                                    \nmonatsvertrag        3.0631               2.2961               4.0864  0.0000\ndistanz              1.0480               1.0160               1.0809  0.0030\ntrainingsminuten     0.9984               0.9904               1.0065  0.6971\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Konkordanz ohne:\", round(cox.concordance_index_, 4),\n      \"| mit:\", round(cox_b.concordance_index_, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKonkordanz ohne: 0.6626 | mit: 0.6594\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Partial AIC ohne:\", round(cox.AIC_partial_, 2),\n      \"| mit:\", round(cox_b.AIC_partial_, 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPartial AIC ohne: 2683.93 | mit: 2685.78\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Prädiktor | Hazard Ratio | 95-Prozent-Intervall | p |\n|---|---|---|---|\n| Monatsvertrag | 3.06 | 2.29 – 4.08 | < .001 |\n| Distanz | 1.048 | 1.016 – 1.081 | .003 |\n| **Trainingsminuten** | **0.9984** | **0.9904 – 1.0065** | **.697** |\n\n| Vergleich | ohne | mit | Deutung |\n|---|---|---|---|\n| Konkordanz | 0.6630 | **0.6594** | Sie **sinkt** leicht. Anders als das $R^2$ der linearen Regression steigt die Konkordanz nicht automatisch mit jedem Prädiktor — sie kann sich verschlechtern, wenn eine Variable nur Rauschen beisteuert. |\n| Partial AIC | 2683.93 | **2685.78** | Steigt um 1.85. Das Informationskriterium bestraft den zusätzlichen Parameter stärker, als der minimale Gewinn an Likelihood ihn rechtfertigt: Das kleinere Modell ist vorzuziehen. Siehe [Modellauswahl](../regression/modellauswahl.qmd). |\n| Hazard Ratios der übrigen | 3.060 / 1.0478 | 3.063 / 1.0480 | Praktisch unverändert. Das ist zu erwarten, weil die neue Variable mit den bestehenden nicht korreliert — im Gegensatz zu Beispiel 5. |\n\n| Ausgabe | Wie sie zu lesen ist |\n|---|---|\n| HR = 0.9984 | Rechnerisch ein winziger Schutzeffekt: 0.16 Prozent weniger Risiko je Minute. |\n| Intervall 0.9904 bis 1.0065 | **Enthält die 1** — und zwar mit reichlich Abstand auf beiden Seiten. Das ist die eigentliche Aussage: Die Daten sind mit allem zwischen einem Prozent Schutz und 0.65 Prozent Risiko je Minute vereinbar. |\n| p = .697 | Kein Nachweis eines Effekts. **Kein Nachweis der Abwesenheit** eines Effekts — den liefert das enge Intervall, nicht der p-Wert. |\n\n::: {.note-box}\nBei einem metrischen Prädiktor ist das Intervall je Einheit irreführend eng. Über\ndie Spannweite von rund 60 Minuten gerechnet, lässt es Faktoren zwischen\n$0.9904^{60} = 0.56$ und $1.0065^{60} = 1.48$ zu — also von \"halbiert das Risiko\"\nbis \"erhöht es um die Hälfte\". Ein enges Intervall je Einheit heisst nicht, dass\ndie Variable ausgeschlossen ist.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die durchschnittliche Trainingsdauer ist nicht mit dem Kündigungsrisiko\n> assoziiert (Hazard Ratio 0.998 je Minute, 95-Prozent-Konfidenzintervall 0.990\n> bis 1.007, p = .70). Die Aufnahme in das Modell verschlechtert Konkordanz\n> (0.663 auf 0.659) und Partial AIC (2683.9 auf 2685.8); berichtet wird das\n> Modell ohne diesen Prädiktor.\n\n### Beispiel 4: Wenn die Proportionalität verletzt ist\n\n#### Frage und Datenlage\n\nDer Kernfall. Zwei Gruppen zu je 250 Fällen aus dem\n[Log-Rank-Test](log-rank-test.qmd): Gruppe A hat in den ersten sechs Monaten ein\nhohes Risiko und danach ein sehr niedriges, Gruppe B durchgehend ein mittleres.\nDie Kurven kreuzen sich. Was macht das Cox-Modell daraus?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm <- 250\nfrueh <- -log(lehmer(5151, m)) / 0.16\nspaet <- 6 - log(lehmer(5252, m)) / 0.004\na_zeit <- ifelse(frueh <= 6, frueh, spaet)\nb_zeit <- -log(lehmer(5353, m)) / 0.075\n\nkreuz <- data.frame(\n  zeit = pmin(c(a_zeit, b_zeit), 24),\n  status = as.integer(c(a_zeit, b_zeit) <= 24),\n  gruppe = factor(rep(c(\"A\", \"B\"), each = m), levels = c(\"B\", \"A\"))\n)\n\nmodell_c <- coxph(Surv(zeit, status) ~ gruppe, data = kreuz)\nround(summary(modell_c)$conf.int[, c(\"exp(coef)\", \"lower .95\", \"upper .95\")], 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nexp(coef) lower .95 upper .95 \n   0.9935    0.8061    1.2246 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(summary(modell_c)$coefficients[, \"Pr(>|z|)\"], 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9515\n```\n\n\n:::\n\n```{.r .cell-code}\npruefung_c <- cox.zph(modell_c)\npruefung_c\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       chisq df      p\ngruppe  89.9  1 <2e-16\nGLOBAL  89.9  1 <2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mar = c(4, 4, 2, 1))\nplot(pruefung_c, main = \"Gruppe A gegenüber B\")\nabline(h = 0, lty = 3)\n\n# Getrennt nach Zeitabschnitt\nfrueh_teil <- transform(kreuz, z = pmin(zeit, 6),\n                        s = as.integer(status == 1 & zeit <= 6))\nspaet_teil <- subset(kreuz, zeit > 6)\nround(c(\n  bis_6 = exp(coef(coxph(Surv(z, s) ~ gruppe, data = frueh_teil))),\n  ab_6 = exp(coef(coxph(Surv(zeit, status) ~ gruppe, data = spaet_teil)))\n), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbis_6.gruppeA  ab_6.gruppeA \n        2.199         0.040 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 4: Schoenfeld-Residuen bei verletzter Annahme — der Effekt fällt sichtbar mit der Zeit.](cox-modell_files/figure-html/fig-b4-cox-r-1.png){#fig-b4-cox-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nm = 250\nfrueh = -np.log(lehmer(5151, m)) / 0.16\nspaet = 6 - np.log(lehmer(5252, m)) / 0.004\na_zeit = np.where(frueh <= 6, frueh, spaet)\nb_zeit = -np.log(lehmer(5353, m)) / 0.075\n\nroh = np.concatenate([a_zeit, b_zeit])\nkreuz = pd.DataFrame({\n    \"zeit\": np.minimum(roh, 24),\n    \"status\": (roh <= 24).astype(int),\n    \"gruppe_a\": np.concatenate([np.ones(m), np.zeros(m)]).astype(int),\n})\n\ncox_c = CoxPHFitter().fit(kreuz, duration_col=\"zeit\", event_col=\"status\")\nprint(cox_c.summary[[\"exp(coef)\", \"exp(coef) lower 95%\",\n                     \"exp(coef) upper 95%\", \"p\"]].round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           exp(coef)  exp(coef) lower 95%  exp(coef) upper 95%       p\ncovariate                                                             \ngruppe_a      0.9935               0.8061               1.2246  0.9516\n```\n\n\n:::\n\n```{.python .cell-code}\nproportional_hazard_test(cox_c, kreuz,\n                         time_transform=\"rank\").print_summary(decimals=4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<lifelines.StatisticalResult: proportional_hazard_test>\n    time_transform = rank\n null_distribution = chi squared\ndegrees_of_freedom = 1\n             model = <lifelines.CoxPHFitter: fitted with 500 total observations, 140 right-censored observations>\n         test_name = proportional_hazard_test\n\n---\n          test_statistic      p  -log2(p)\ngruppe_a         90.8313 <5e-05   69.1147\n```\n\n\n:::\n\n```{.python .cell-code}\nfrueh_teil = kreuz.assign(\n    z=np.minimum(kreuz[\"zeit\"], 6),\n    s=((kreuz[\"status\"] == 1) & (kreuz[\"zeit\"] <= 6)).astype(int)\n)[[\"z\", \"s\", \"gruppe_a\"]]\nspaet_teil = kreuz[kreuz[\"zeit\"] > 6]\n\nhr_frueh = CoxPHFitter().fit(frueh_teil, duration_col=\"z\", event_col=\"s\") \\\n    .summary.loc[\"gruppe_a\", \"exp(coef)\"]\nhr_spaet = CoxPHFitter().fit(spaet_teil, duration_col=\"zeit\",\n                             event_col=\"status\") \\\n    .summary.loc[\"gruppe_a\", \"exp(coef)\"]\nprint(f\"Hazard Ratio Monate 0 bis 6:  {hr_frueh:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHazard Ratio Monate 0 bis 6:  2.199\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Hazard Ratio Monate 6 bis 24: {hr_spaet:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHazard Ratio Monate 6 bis 24: 0.040\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Modell | Hazard Ratio (A gegenüber B) | 95-Prozent-Intervall | p |\n|---|---|---|---|\n| **Gesamter Zeitraum** | **0.994** | 0.806 – 1.225 | **.952** |\n| Monate 0 bis 6 | **2.199** | | < .001 |\n| Monate 6 bis 24 | **0.040** | | < .001 |\n\nPrüfung auf Proportionalität: $\\chi^2$ = 90.8, p < .001.\n\n| Beobachtung | Erklärung |\n|---|---|\n| Das Gesamtmodell schätzt **HR = 0.99** | Also \"kein Unterschied\". Das ist keine Mittelung im Sinne eines vernünftigen Kompromisses, sondern eine Zahl, die **keinen der beiden Zeiträume beschreibt**. |\n| Abschnittsweise: **2.20 und 0.04** | Früh hat A mehr als das Doppelte des Risikos, später ein Fünfundzwanzigstel. Zwischen den beiden Zahlen liegt ein Faktor von 55. |\n| Der Test auf Proportionalität | $\\chi^2$ = 90.8 bei einem Prädiktor — unübersehbar. Hier ist das kein Grenzfall wie in Beispiel 2. |\n| Die Schoenfeld-Residuen | fallen im Bild deutlich von oben nach unten, statt um eine Waagrechte zu schwanken. Das ist die Verletzung, **sichtbar** statt getestet. |\n| Konfidenzintervall des Gesamtmodells | 0.81 bis 1.23 | Es sieht aus wie ein sauber ausgeschlossener Effekt. Beide wahren Werte liegen weit ausserhalb. |\n\n::: {.note-box}\n**Warum das gefährlicher ist als ein einfach falscher Wert:** Das Gesamtmodell\nliefert eine unauffällige Ausgabe. Kein Wert ist absurd, das Intervall ist eng,\nder p-Wert klar. Nichts an dieser Tabelle deutet auf ein Problem hin — die\nVerletzung ist nur über den Test und den Residuenplot zu sehen. Deshalb ist die\nPrüfung der Proportionalität kein optionaler Zusatz, sondern Teil der Rechnung.\n\n**Und warum die abschnittsweisen Zahlen hier keine Berichtsergebnisse sind:** Die\nGrenze bei sechs Monaten stammt aus der Konstruktion des Beispiels. Wer sie nach\ndem Blick auf die Daten wählt, hat einen an den Daten optimierten Schnitt gesetzt.\n:::\n\nDrei zulässige Wege bei verletzter Proportionalität:\n\n| Weg | Wann |\n|---|---|\n| **Stratifizieren** nach der betroffenen Variablen | ihr Effekt interessiert nicht, sie ist nur eine Störgrösse — siehe Beispiel 5 |\n| **Zeitabhängigen Effekt** aufnehmen (`tt()` in R, `CoxTimeVaryingFitter`) | der Wechsel des Effekts ist selbst das Ergebnis |\n| **Zeitabschnitte** getrennt schätzen | die Grenze ist aus der Sache heraus begründet, nicht aus den Daten |\n\nWas nicht geht: ein einzelnes Hazard Ratio berichten und die Verletzung in einer\nFussnote erwähnen.\n\n#### Interpretation und Ergebnissatz\n\n> Die Annahme proportionaler Hazards ist für die Gruppenzugehörigkeit deutlich\n> verletzt ($\\chi^2$ = 90.8, p < .001, Rang-Transformation); die\n> Schoenfeld-Residuen fallen über den Beobachtungszeitraum. Ein einzelnes Hazard\n> Ratio (0.99, 0.81 bis 1.23) beschreibt keinen der beiden Zeiträume. Berichtet\n> werden getrennte Schätzungen für die postoperative Phase bis Monat 6 (HR 2.20)\n> und die Zeit danach (HR 0.04).\n\n### Beispiel 5: Stratifizieren statt schätzen\n\n#### Frage und Datenlage\n\nAngenommen, nur der Effekt der Distanz interessiert, und die Vertragsart ist\nlediglich eine Störgrösse, deren Proportionalität zweifelhaft ist. Dann wird nach\nihr **stratifiziert**: Jede Schicht bekommt ihr eigenes Grundrisiko $h_0(t)$, und\ndie übrigen Effekte werden über die Schichten hinweg gemeinsam geschätzt.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodell_strat <- coxph(Surv(zeit, status) ~ distanz + strata(vertrag),\n                      data = abo)\nsummary(modell_strat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(zeit, status) ~ distanz + strata(vertrag), \n    data = abo)\n\n  n= 400, number of events= 247 \n\n           coef exp(coef) se(coef)     z Pr(>|z|)   \ndistanz 0.04614   1.04723  0.01575 2.929   0.0034 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n        exp(coef) exp(-coef) lower .95 upper .95\ndistanz     1.047     0.9549     1.015      1.08\n\nConcordance= 0.555  (se = 0.019 )\nLikelihood ratio test= 8.7  on 1 df,   p=0.003\nWald test            = 8.58  on 1 df,   p=0.003\nScore (logrank) test = 8.65  on 1 df,   p=0.003\n```\n\n\n:::\n\n```{.r .cell-code}\n# Gegenüberstellung mit dem ungeschichteten Modell\nround(rbind(\n  ungeschichtet = summary(modell)$conf.int[\"distanz\",\n                                           c(\"exp(coef)\", \"lower .95\", \"upper .95\")],\n  geschichtet = summary(modell_strat)$conf.int[\"distanz\",\n                                               c(\"exp(coef)\", \"lower .95\", \"upper .95\")]\n), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              exp(coef) lower .95 upper .95\nungeschichtet    1.0478    1.0159    1.0807\ngeschichtet      1.0472    1.0154    1.0801\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ncox_strat = CoxPHFitter().fit(abo, duration_col=\"zeit\", event_col=\"status\",\n                              strata=[\"monatsvertrag\"])\nprint(cox_strat.summary[[\"coef\", \"exp(coef)\", \"exp(coef) lower 95%\",\n                         \"exp(coef) upper 95%\", \"p\"]].round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             coef  exp(coef)  exp(coef) lower 95%  exp(coef) upper 95%       p\ncovariate                                                                     \ndistanz    0.0461     1.0472               1.0154               1.0801  0.0034\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Konkordanz:\", round(cox_strat.concordance_index_, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKonkordanz: 0.555\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Modell | HR Distanz | 95-Prozent-Intervall | p | HR Vertragsart |\n|---|---|---|---|---|\n| ungeschichtet | 1.0478 | 1.0156 – 1.0807 | .003 | 3.060 |\n| **geschichtet** | **1.0472** | 1.0154 – 1.0801 | .003 | **nicht geschätzt** |\n\n| Ausgabe | Wie sie zu lesen ist |\n|---|---|\n| Die Distanz ändert sich kaum | 1.0478 gegen 1.0472. Der Effekt der Distanz ist über beide Vertragsarten hinweg derselbe, deshalb kostet die Schichtung hier fast nichts an Genauigkeit. |\n| Für die Vertragsart gibt es **kein Hazard Ratio mehr** | Und das ist keine Panne, sondern der Zweck. Jede Schicht hat ihr eigenes, frei geformtes Grundrisiko; ein Verhältnis zwischen den Schichten wird gar nicht erst unterstellt und daher auch nicht geschätzt. |\n| Die Zahl der geschätzten Parameter sinkt von 2 auf 1 | Die partielle Likelihood wird nur noch **innerhalb** der Schichten gebildet: Verglichen wird jede Person zum Ereigniszeitpunkt nur mit denen der eigenen Schicht. |\n\n::: {.note-box}\n**Der Handel in einem Satz:** Man kauft Robustheit gegen eine verletzte\nProportionalität und bezahlt mit dem Effektmass für die geschichtete Variable.\n\nDrei praktische Folgen:\n\n- Stratifizieren lohnt sich **nur für Störgrössen**. Ist die Variable die\n  eigentliche Frage, ist ein zeitabhängiger Effekt der richtige Weg.\n- Zu viele Schichten zerlegen die Risikomengen. Bei zehn Schichten mit je zwei\n  Ereignissen bleibt kaum Information übrig.\n- Metrische Variablen müssen dafür in Klassen zerlegt werden — mit allen Nachteilen\n  willkürlicher Grenzen.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> In einem nach Vertragsart stratifizierten Cox-Modell steigt das\n> Kündigungsrisiko je Kilometer Anfahrt um den Faktor 1.047\n> (95-Prozent-Konfidenzintervall 1.015 bis 1.080, p = .003), je fünf Kilometer\n> also um 1.26. Für die Vertragsart wird kein Hazard Ratio geschätzt; sie geht als\n> Schicht mit eigenem Grundrisiko ein.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEin Hazard Ratio beträgt 3.06 mit Intervall 2.29 bis 4.08. Was heisst das?\n\n- [x] Das momentane Risiko ist etwa dreimal so hoch, bei konstant gehaltenen\n      übrigen Prädiktoren ~ Richtig. Das Intervall schliesst die eins nicht ein,\n      der Effekt ist also von null verschieden. Über Laufzeiten sagt die Zahl\n      direkt nichts.\n- [ ] Die Laufzeit drittelt sich ~ Das folgt nicht; der Zusammenhang zwischen\n      Hazard Ratio und Median hängt von der Verteilungsform ab.\n- [ ] Die Wahrscheinlichkeit für das Ereignis ist 3.06 ~ Wahrscheinlichkeiten sind\n      höchstens eins; ein Hazard Ratio ist keine Wahrscheinlichkeit.\n:::\n\n::: {.quiz}\nWarum ist das Konfidenzintervall 2.29 bis 4.08 nicht symmetrisch um 3.06?\n\n- [x] Weil es auf der Log-Skala gebildet und dann exponiert wird ~ Richtig.\n      Gerechnet wird $e^{\\beta \\pm 1.96 \\cdot SE}$; die Exponentialfunktion\n      streckt oben und staucht unten. Auf der Log-Skala ist das Intervall\n      symmetrisch.\n- [ ] Weil die Verteilung der Laufzeiten schief ist ~ Die Schiefe der Laufzeiten\n      spielt hier keine Rolle.\n- [ ] Weil gerundet wurde ~ Der Unterschied ist zu gross für einen Rundungseffekt.\n:::\n\n::: {.quiz}\n`cox.zph()` liefert für einen Prädiktor p = 0.004. Was folgt?\n\n- [ ] Der Prädiktor hat einen signifikanten Effekt ~ Das ist eine andere Frage,\n      die der Wald-Test beantwortet.\n- [x] Sein Effekt ändert sich über die Zeit, ein einzelnes Hazard Ratio genügt\n      nicht ~ Richtig. Der Test prüft die Annahme proportionaler Hazards. Bei\n      Verletzung wird stratifiziert, ein zeitabhängiger Effekt aufgenommen oder\n      nach Zeitabschnitten berichtet — und zwar mit einer vorab begründeten\n      Grenze.\n- [ ] Das Modell ist insgesamt schlecht angepasst ~ Die Anpassung kann gut sein;\n      verletzt ist eine bestimmte Annahme über einen bestimmten Prädiktor.\n:::\n\n::: {.quiz}\nEin Cox-Modell schätzt für eine Gruppenvariable HR = 0.99 mit Intervall 0.81 bis\n1.23, während die abschnittsweisen Schätzungen 2.20 und 0.04 lauten. Was ist\npassiert?\n\n- [x] Die Proportionalität ist verletzt; die 0.99 beschreibt keinen der Zeiträume\n      ~ Richtig. Der Effekt kehrt sich über die Zeit um, und das Modell mittelt\n      ihn zu einer Zahl, die nirgends gilt. Am Ergebnis selbst ist das nicht zu\n      sehen — nur am Test und am Residuenplot.\n- [ ] Die abschnittsweisen Modelle sind überangepasst ~ Sie beruhen auf 249\n      beziehungsweise 111 Ereignissen; das ist reichlich.\n- [ ] Das Gesamtmodell ist präziser, weil es alle Daten nutzt ~ Präzision nützt\n      nichts, wenn die geschätzte Grösse die falsche ist.\n:::\n\n::: {.quiz}\nEin Modell mit vier Prädiktoren beruht auf 400 Beobachtungen, von denen 32 ein\nEreignis hatten. Was ist das Problem?\n\n- [x] Acht Ereignisse je Koeffizient sind zu wenig ~ Richtig. Die Genauigkeit\n      hängt an der Ereigniszahl, nicht an der Fallzahl. Die Faustregel von rund\n      zehn Ereignissen je Koeffizienten ist hier verletzt, Intervalle sind zu eng\n      und die Schätzung instabil.\n- [ ] Kein Problem, 400 Beobachtungen sind ausreichend ~ Die 368 Zensierten\n      tragen zur Schätzung der Koeffizienten nur begrenzt bei.\n- [ ] Die Zensierungsrate ist zu hoch für ein Cox-Modell ~ Hohe Zensierung ist\n      normal; entscheidend ist die absolute Ereigniszahl.\n:::\n\n::: {.quiz}\nWird nach einer Variablen stratifiziert, entfällt für sie das Hazard Ratio.\nWarum?\n\n- [x] Weil jede Schicht ein eigenes, frei geformtes Grundrisiko bekommt ~\n      Richtig. Zwischen den Schichten wird kein festes Verhältnis unterstellt,\n      also gibt es auch keines zu schätzen. Das ist der Preis für die Robustheit\n      gegen eine verletzte Proportionalität.\n- [ ] Weil die Variable aus dem Modell entfernt wurde ~ Sie ist weiterhin\n      enthalten und bestimmt, mit wem eine Person verglichen wird.\n- [ ] Weil sie nicht signifikant war ~ Mit Signifikanz hat die Entscheidung\n      nichts zu tun.\n:::\n\n## Verlinkte Ressourcen\n\n- [An Introduction to Statistical Learning, Kapitel 11.4 bis 11.5](https://www.statlearning.com/)\n- [survival: coxph](https://stat.ethz.ch/R-manual/R-devel/library/survival/html/coxph.html)\n- [lifelines: CoxPHFitter](https://lifelines.readthedocs.io/en/latest/fitters/regression/CoxPHFitter.html)\n- [Therneau und Grambsch: Modeling Survival Data](https://link.springer.com/book/10.1007/978-1-4757-3294-8)\n",
    "supporting": [
      "cox-modell_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}