{
  "hash": "affdfbbb0cf7434a1db0c184f4552f5f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Data\"\ndescription: \"Eine Zeile je Beobachtung, eine Spalte je Variable, und warum das trägt.\"\ncategories: [\"Data Wrangling\", \"Datenqualität\", \"R\", \"Python\"]\nquelle: [\"ESDS\"]\nseitentyp: konzept\nstand: entwurf\norder: 20\n---\n\n\n\n\n\n## Kernideen\n\n- **Eine Zeile je Beobachtung, eine Spalte je Merkmal, ein Wert je Zelle.**\n- Steht in einem **Spaltennamen** eine Information, die ein Wert ist (ein\n  Jahr, ein Monat, ein Gerätename), ist die Tabelle breit und die Auswertung\n  will sie lang.\n- **Langes Format** zum Rechnen, Filtern und Zeichnen, **breites Format** für\n  die Anzeige. Die Umformung ins Breite ist der letzte Schritt, nicht der\n  erste.\n- Mehrere Werte in einer Zelle werden **aufgeteilt**, bevor gerechnet wird.\n- Beschreibt eine Tabelle **zwei Beobachtungseinheiten**, gehört sie getrennt.\n  Wiederholte Angaben widersprechen sich sonst irgendwann.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [R-Grundlagen](../programmierung/r-grundlagen.qmd) oder\n[pandas](../programmierung/pandas.qmd) für den Data Frame. Wie man Daten in\ndiese Form bringt, steht unter [Data Wrangling](data-wrangling.qmd), woher\nsie kommen unter [Datenimport](datenimport-formate.qmd), und was man vor dem\nUmformen prüft unter [Datenqualität](datenqualitaet.qmd).\n:::\n\n### Warum die Aufbereitung den grössten Teil der Zeit frisst\n\nDaten kommen so, wie sie irgendwo entstanden sind, und nicht so, wie eine\nAuswertung sie braucht. Ein Export aus einer Maschinensteuerung hat\nDatumsangaben als Text, Messwerte mit Dezimalkomma, Kategorien mit\nTippfehlern und irgendwo einen Strich für einen fehlenden Wert. Nichts davon\nist ein Fehler; es ist der Normalzustand.\n\nDas Werkzeug dagegen erwartet eine bestimmte Form. Wird sie hergestellt,\nläuft alles Weitere glatt. Wird sie nicht hergestellt, kostet jeder Schritt\nSonderbehandlung, und diese Sonderbehandlungen summieren sich zu genau dem\nAufwand, der in Projektplänen fehlt.\n\n### Die drei Regeln\n\n| Regel | verletzt, wenn | Beispiel |\n|---|---|---|\n| Eine Spalte je Merkmal | ein Wert im Spaltennamen steht | `jahr_2024`, `jahr_2025` |\n| Eine Zeile je Beobachtung | mehrere Werte in einer Zelle stehen | `12,4/13,1` |\n| Eine Tabelle je Beobachtungseinheit | zwei Einheiten gemischt sind | Messungen und Standortstammdaten in einer Tabelle |\n\n### Lang und breit\n\n| | langes Format | breites Format |\n|---|---|---|\n| Aufbau | `standort`, `jahr`, `menge` | `standort`, `2024`, `2025` |\n| Zeilen | eine je Messung | eine je Standort |\n| gut für | filtern, gruppieren, zeichnen, modellieren | lesen und vergleichen im Bericht |\n| Umformung | `pivot_longer()` / `melt()` | `pivot_wider()` / `pivot()` |\n\nDer Grund für die Vorliebe der Werkzeuge ist einfach: Im langen Format ist\njede Grösse ansprechbar. Ein Filter auf das Jahr ist eine Bedingung auf einer\nSpalte, im breiten Format wäre es eine Auswahl von Spaltennamen. Eine Grafik\nnach Jahr einzufärben braucht eine Spalte `jahr`; im breiten Format gibt es\nsie nicht.\n\n### Kurz nachgeschlagen\n\n| Aufgabe | R (tidyr) | pandas |\n|---|---|---|\n| breit zu lang | `pivot_longer(cols, names_to, values_to)` | `melt(id_vars, var_name, value_name)` |\n| lang zu breit | `pivot_wider(names_from, values_from)` | `pivot(index, columns, values)` |\n| mit Aggregation ins Breite | `pivot_wider(values_fn = mean)` | `pivot_table(aggfunc=\"mean\")` |\n| Zelle mit Liste aufteilen | `separate_rows(spalte, sep = \"/\")` | `.str.split(\"/\")` und `.explode()` |\n| Spalte in zwei teilen | `separate_wider_delim()` | `.str.split(expand=True)` |\n| Eindeutigkeit prüfen | `n_distinct()` je Gruppe | `.groupby(...).nunique()` |\n| Stammdaten herausziehen | `distinct(a, b)` | `.drop_duplicates()` |\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Breit, lang und was erst dann geht\n\n#### Frage und Datenlage\n\nMengen für drei Standorte in zwei Jahren, abgelegt mit einer Spalte je Jahr\n(Bern 120 und 131, Chur 95 und 92, Sion 143 und 150). Gesucht sind das Mittel\nje Jahr und die Veränderung je Standort in Prozent.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbreit <- data.frame(standort = c(\"Bern\", \"Chur\", \"Sion\"),\n                    jahr_2024 = c(120, 95, 143),\n                    jahr_2025 = c(131, 92, 150))\nbreit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  standort jahr_2024 jahr_2025\n1     Bern       120       131\n2     Chur        95        92\n3     Sion       143       150\n```\n\n\n:::\n\n```{.r .cell-code}\nlang <- pivot_longer(breit, cols = starts_with(\"jahr_\"),\n                     names_to = \"jahr\", values_to = \"menge\",\n                     names_prefix = \"jahr_\")\nlang\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  standort jahr  menge\n  <chr>    <chr> <dbl>\n1 Bern     2024    120\n2 Bern     2025    131\n3 Chur     2024     95\n4 Chur     2025     92\n5 Sion     2024    143\n6 Sion     2025    150\n```\n\n\n:::\n\n```{.r .cell-code}\ndim(lang)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6 3\n```\n\n\n:::\n\n```{.r .cell-code}\nlang |> group_by(jahr) |> summarise(mittel = round(mean(menge), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  jahr  mittel\n  <chr>  <dbl>\n1 2024    119.\n2 2025    124.\n```\n\n\n:::\n\n```{.r .cell-code}\nbreit |>\n  mutate(wachstum = round((jahr_2025 - jahr_2024) / jahr_2024 * 100, 2)) |>\n  select(standort, wachstum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  standort wachstum\n1     Bern     9.17\n2     Chur    -3.16\n3     Sion     4.90\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nbreit = pd.DataFrame({\"standort\": [\"Bern\", \"Chur\", \"Sion\"],\n                      \"jahr_2024\": [120, 95, 143],\n                      \"jahr_2025\": [131, 92, 150]})\nprint(breit.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstandort  jahr_2024  jahr_2025\n    Bern        120        131\n    Chur         95         92\n    Sion        143        150\n```\n\n\n:::\n\n```{.python .cell-code}\nlang = breit.melt(id_vars=\"standort\", var_name=\"jahr\", value_name=\"menge\")\nlang[\"jahr\"] = lang[\"jahr\"].str.removeprefix(\"jahr_\").astype(int)\nprint(lang.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstandort  jahr  menge\n    Bern  2024    120\n    Chur  2024     95\n    Sion  2024    143\n    Bern  2025    131\n    Chur  2025     92\n    Sion  2025    150\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(lang.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(6, 3)\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(lang.groupby(\"jahr\")[\"menge\"].mean().round(2).to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{2024: 119.33, 2025: 124.33}\n```\n\n\n:::\n\n```{.python .cell-code}\nw = lang.pivot(index=\"standort\", columns=\"jahr\", values=\"menge\")\nprint(((w[2025] - w[2024]) / w[2024] * 100).round(2).to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'Bern': 9.17, 'Chur': -3.16, 'Sion': 4.9}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | Wert | Erklärung |\n|---|---|---|\n| breite Tabelle | 3 Zeilen, 3 Spalten | Eine Zeile je Standort, das Jahr steckt im Spaltennamen. |\n| lange Tabelle | **6 Zeilen, 3 Spalten** | Eine Zeile je Messung. Aus zwei Wertespalten werden zwei Spalten `jahr` und `menge`. |\n| Mittel 2024 | **119.33** | (120 + 95 + 143) / 3 |\n| Mittel 2025 | **124.33** | (131 + 92 + 150) / 3 |\n| Wachstum Bern | **+9.17 Prozent** | von 120 auf 131 |\n| Wachstum Chur | **−3.16 Prozent** | von 95 auf 92, der einzige Rückgang |\n| Wachstum Sion | **+4.90 Prozent** | von 143 auf 150 |\n\nDie beiden Auswertungen zeigen, wofür welche Form taugt. Das Mittel je Jahr\nist im langen Format ein `group_by(jahr)`, im breiten müsste man zwei Spalten\neinzeln mitteln und die Ergebnisse zusammensetzen. Die Veränderung dagegen\nvergleicht zwei Jahre **in einer Zeile** und ist deshalb im breiten Format\neinfacher. Beide Formen haben ihren Platz, man muss nur wechseln können.\n\n#### Interpretation und Ergebnissatz\n\nIm langen Format ist das Jahr ein Merkmal wie jedes andere. Alles, was\ngruppiert, filtert oder zeichnet, arbeitet damit ohne Sonderfall; Werkzeuge\nwie ggplot2 und seaborn setzen es voraus.\n\n> Aus der breiten Tabelle mit drei Zeilen wird im langen Format eine mit sechs\n> Zeilen. Im Mittel stieg die Menge von 119.33 auf 124.33; nur Chur ging mit\n> −3.16 Prozent zurück, während Bern um 9.17 Prozent zulegte.\n\n### Beispiel 2: Mehrere Werte in einer Zelle\n\n#### Frage und Datenlage\n\nIn einer Exporttabelle stehen alle Messungen eines Standorts in einer Zelle,\ndurch Schrägstrich getrennt: Bern `12,4/13,1`, Chur `9,8`. Wie wird daraus\neine Zeile je Messung, und was ist die Summe?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroh <- data.frame(standort = c(\"Bern\", \"Chur\"),\n                  messungen = c(\"12,4/13,1\", \"9,8\"))\nroh\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  standort messungen\n1     Bern 12,4/13,1\n2     Chur       9,8\n```\n\n\n:::\n\n```{.r .cell-code}\ngeteilt <- roh |>\n  separate_rows(messungen, sep = \"/\") |>\n  mutate(messung = as.numeric(sub(\",\", \".\", messungen, fixed = TRUE))) |>\n  select(standort, messung)\ngeteilt\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  standort messung\n  <chr>      <dbl>\n1 Bern        12.4\n2 Bern        13.1\n3 Chur         9.8\n```\n\n\n:::\n\n```{.r .cell-code}\nc(zeilen = nrow(geteilt), summe = sum(geteilt$messung))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nzeilen  summe \n   3.0   35.3 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nroh = pd.DataFrame({\"standort\": [\"Bern\", \"Chur\"],\n                    \"messungen\": [\"12,4/13,1\", \"9,8\"]})\nprint(roh.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstandort messungen\n    Bern 12,4/13,1\n    Chur       9,8\n```\n\n\n:::\n\n```{.python .cell-code}\ngeteilt = roh.assign(messung=roh[\"messungen\"].str.split(\"/\")).explode(\"messung\")\ngeteilt[\"messung\"] = geteilt[\"messung\"].str.replace(\",\", \".\").astype(float)\nprint(geteilt[[\"standort\", \"messung\"]].to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstandort  messung\n    Bern     12.4\n    Bern     13.1\n    Chur      9.8\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(len(geteilt), geteilt[\"messung\"].sum().round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n3 35.3\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Schritt | Ergebnis | Erklärung |\n|---|---|---|\n| Rohtabelle | 2 Zeilen | Bern trägt zwei Messungen in einer Zelle. |\n| aufgeteilt | **3 Zeilen**: Bern 12.4, Bern 13.1, Chur 9.8 | `separate_rows` beziehungsweise `.str.split()` mit `.explode()`. Der Standort wird dabei wiederholt. |\n| umgewandelt | Zahlen statt Text | Das Dezimalkomma muss ersetzt werden, sonst bleibt es Text. |\n| Summe | **35.3** | 12.4 + 13.1 + 9.8. Auf der Rohtabelle wäre sie gar nicht zu bilden. |\n\n#### Interpretation und Ergebnissatz\n\nSolche Zellen entstehen, wenn ein Export für das Auge gemacht wurde. Solange\nsie bestehen, ist jede Kennzahl blockiert: Man kann weder zählen noch\nsummieren noch gruppieren. Das Aufteilen ist deshalb kein Schönheitsschritt,\nsondern die Voraussetzung für alles Weitere. Die Zeilenzahl steigt dabei, und\nWerte, die vorher einmal dastanden (hier der Standort), wiederholen sich.\n\n> Aus zwei Zeilen mit zusammengefassten Messungen werden drei Zeilen mit je\n> einem Wert; erst danach lässt sich die Summe von 35.3 bilden.\n\n### Beispiel 3: Zwei Beobachtungseinheiten in einer Tabelle\n\n#### Frage und Datenlage\n\nEine Tabelle führt je Standort und Jahr die Menge, dazu in jeder Zeile den\nKanton. Der Kanton gehört aber zum Standort, nicht zur Messung. In der\nzweiten Chur-Zeile steht `GH` statt `GR`. Wie fällt das auf?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngemischt <- data.frame(\n  standort = c(\"Bern\", \"Bern\", \"Chur\", \"Chur\"),\n  kanton   = c(\"BE\", \"BE\", \"GR\", \"GH\"),\n  jahr     = c(2024, 2025, 2024, 2025),\n  menge    = c(120, 131, 95, 92))\ngemischt\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  standort kanton jahr menge\n1     Bern     BE 2024   120\n2     Bern     BE 2025   131\n3     Chur     GR 2024    95\n4     Chur     GH 2025    92\n```\n\n\n:::\n\n```{.r .cell-code}\ngemischt |> group_by(standort) |> summarise(kantone = n_distinct(kanton))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  standort kantone\n  <chr>      <int>\n1 Bern           1\n2 Chur           2\n```\n\n\n:::\n\n```{.r .cell-code}\norte <- distinct(gemischt, standort, kanton)\norte\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  standort kanton\n1     Bern     BE\n2     Chur     GR\n3     Chur     GH\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(orte)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ngemischt = pd.DataFrame({\n    \"standort\": [\"Bern\", \"Bern\", \"Chur\", \"Chur\"],\n    \"kanton\": [\"BE\", \"BE\", \"GR\", \"GH\"],\n    \"jahr\": [2024, 2025, 2024, 2025],\n    \"menge\": [120, 131, 95, 92]})\nprint(gemischt.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstandort kanton  jahr  menge\n    Bern     BE  2024    120\n    Bern     BE  2025    131\n    Chur     GR  2024     95\n    Chur     GH  2025     92\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(gemischt.groupby(\"standort\")[\"kanton\"].nunique().to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'Bern': 1, 'Chur': 2}\n```\n\n\n:::\n\n```{.python .cell-code}\norte = gemischt[[\"standort\", \"kanton\"]].drop_duplicates()\nprint(orte.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstandort kanton\n    Bern     BE\n    Chur     GR\n    Chur     GH\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(len(orte))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n3\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Prüfung | Ergebnis | Erklärung |\n|---|---|---|\n| Kantone je Standort | **Bern 1, Chur 2** | Ein Standort kann nur in einem Kanton liegen. Die 2 ist der Widerspruch. |\n| Stammdaten herausgezogen | **3 Zeilen** statt 2 | Hätte jeder Standort genau einen Kanton, stünden hier zwei Zeilen. Die dritte ist der Tippfehler `GH`. |\n\nDie Prüfung `n_distinct` je Gruppe beziehungsweise `nunique` ist der\nStandardgriff für diese Fehlerklasse: Für jedes Merkmal, das zu einer\nübergeordneten Einheit gehört, darf es je Einheit nur einen Wert geben.\n\n#### Interpretation und Ergebnissatz\n\nDer Tippfehler ist nur möglich, weil der Kanton in jeder Messzeile wiederholt\nwird. In zwei Tabellen, einer für Standorte und einer für Messungen, gäbe es\nden Kanton genau einmal, und die Frage \"welcher gilt\" stellte sich nicht. Das\nist derselbe Gedanke wie die Normalisierung in der\n[Datenmodellierung](../datenbanken/datenmodellierung.qmd): Jede Tatsache\ngehört an genau eine Stelle.\n\n> Chur hat in der Tabelle zwei verschiedene Kantone, `GR` und `GH`, und die\n> herausgezogenen Stammdaten haben drei statt zwei Zeilen. Der Widerspruch\n> entsteht durch die Wiederholung und verschwindet, sobald Standorte und\n> Messungen getrennte Tabellen sind.\n\n### Beispiel 4: Zurück ins Breite, für den Bericht\n\n#### Frage und Datenlage\n\nDie lange Tabelle aus Beispiel 1 soll als Berichtstabelle mit einer Spalte je\nJahr erscheinen. Und was passiert, wenn eine Zeile versehentlich doppelt\nvorkommt?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbericht <- pivot_wider(lang, names_from = jahr, values_from = menge)\nbericht\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  standort `2024` `2025`\n  <chr>     <dbl>  <dbl>\n1 Bern        120    131\n2 Chur         95     92\n3 Sion        143    150\n```\n\n\n:::\n\n```{.r .cell-code}\ndoppelt <- bind_rows(lang, lang[1, ])\nnrow(doppelt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7\n```\n\n\n:::\n\n```{.r .cell-code}\n# Ohne Angabe, wie zusammenzufassen ist, entsteht eine Listenspalte\npivot_wider(doppelt, names_from = jahr, values_from = menge)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  standort `2024`    `2025`   \n  <chr>    <list>    <list>   \n1 Bern     <dbl [2]> <dbl [1]>\n2 Chur     <dbl [1]> <dbl [1]>\n3 Sion     <dbl [1]> <dbl [1]>\n```\n\n\n:::\n\n```{.r .cell-code}\npivot_wider(doppelt, names_from = jahr, values_from = menge,\n            values_fn = length)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  standort `2024` `2025`\n  <chr>     <int>  <int>\n1 Bern          2      1\n2 Chur          1      1\n3 Sion          1      1\n```\n\n\n:::\n\n```{.r .cell-code}\npivot_wider(doppelt, names_from = jahr, values_from = menge,\n            values_fn = mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  standort `2024` `2025`\n  <chr>     <dbl>  <dbl>\n1 Bern        120    131\n2 Chur         95     92\n3 Sion        143    150\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nbericht = lang.pivot(index=\"standort\", columns=\"jahr\", values=\"menge\")\nprint(bericht.to_string())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\njahr      2024  2025\nstandort            \nBern       120   131\nChur        95    92\nSion       143   150\n```\n\n\n:::\n\n```{.python .cell-code}\ndoppelt = pd.concat([lang, lang.iloc[[0]]], ignore_index=True)\nprint(doppelt.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(7, 3)\n```\n\n\n:::\n\n```{.python .cell-code}\ntry:\n    doppelt.pivot(index=\"standort\", columns=\"jahr\", values=\"menge\")\nexcept ValueError as fehler:\n    print(type(fehler).__name__, str(fehler)[:55])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nValueError Index contains duplicate entries, cannot reshape\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(doppelt.pivot_table(index=\"standort\", columns=\"jahr\", values=\"menge\",\n                          aggfunc=\"size\").to_string())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\njahr      2024  2025\nstandort            \nBern         2     1\nChur         1     1\nSion         1     1\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(doppelt.pivot_table(index=\"standort\", columns=\"jahr\", values=\"menge\",\n                          aggfunc=\"mean\").to_string())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\njahr       2024   2025\nstandort              \nBern      120.0  131.0\nChur       95.0   92.0\nSion      143.0  150.0\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Schritt | Python | R | Erklärung |\n|---|---|---|---|\n| Berichtstabelle | 3 Zeilen, Spalten `2024` und `2025` | dieselbe Tabelle | Genau die Ausgangstabelle aus Beispiel 1. Die Umformung ist umkehrbar. |\n| mit Duplikat | 7 Zeilen | 7 Zeilen | Eine Zeile (Bern 2024) steht zweimal. |\n| `pivot` | **`ValueError`: Index contains duplicate entries** | Warnung und eine **Listenspalte** | pandas bricht ab, tidyr liefert eine Zelle mit zwei Werten darin. Beide sagen damit dasselbe: Der Schlüssel ist nicht eindeutig. |\n| mit `aggfunc=\"size\"` bzw. `values_fn = length` | Bern 2024 = **2**, alle anderen 1 | dieselbe Tabelle | So findet man die betroffene Zelle. |\n| mit Mittelwert | Bern 2024 = 120.0 | 120 | Hier harmlos, weil beide Werte gleich sind. Bei verschiedenen Werten wäre der Mittelwert eine stille Entscheidung. |\n\n#### Interpretation und Ergebnissatz\n\nDas Umformen ins Breite ist der Moment, in dem doppelte Schlüssel auffallen,\nund das ist sein zweiter Nutzen. Wer die Meldung mit einer\nAggregationsfunktion wegdrückt, ohne nachzusehen, hat die Warnung in eine\nstille Annahme verwandelt. Erst zählen, dann entscheiden, ob Mittelwert,\nSumme oder das Beseitigen des Duplikats richtig ist.\n\n> Die lange Tabelle lässt sich verlustfrei ins breite Format zurückformen. Mit\n> einer doppelten Zeile bricht `pivot` in pandas mit einem `ValueError` ab,\n> während tidyr eine Listenspalte erzeugt; `aggfunc=\"size\"` zeigt, dass die\n> Zelle Bern 2024 zwei Werte enthält.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEine Tabelle hat die Spalten `patient`, `blutdruck_vorher`,\n`blutdruck_nachher`. Warum ist sie nicht aufgeräumt?\n\n- [x] Der Messzeitpunkt steckt im Spaltennamen, ist aber ein Merkmal ~\n      Richtig. Aufgeräumt hiessen die Spalten `patient`, `zeitpunkt` und\n      `blutdruck`. Jede Zeile wäre dann eine Messung statt eines Patienten.\n- [ ] Sie enthält zu wenige Spalten ~ Die Anzahl ist nicht das Kriterium,\n      sondern was in den Spaltennamen steht.\n- [ ] Blutdruck gehört in zwei getrennte Tabellen ~ Eine Tabelle genügt, sie\n      muss nur lang statt breit vorliegen.\n:::\n\n::: {.quiz}\nWann ist die breite Form trotzdem die richtige?\n\n- [ ] Immer, sie ist kompakter ~ Kompakter ja, aber für Filtern, Gruppieren\n      und Zeichnen unbrauchbar.\n- [x] Für eine Berichtstabelle, die ein Mensch liest, und für\n      zeilenweise Vergleiche ~ Richtig. Die Veränderung zwischen zwei Jahren\n      ist im breiten Format eine Subtraktion in einer Zeile, wie in\n      Beispiel 1.\n- [ ] Wenn viele fehlende Werte vorliegen ~ Damit hat die Form nichts zu tun.\n:::\n\n::: {.quiz}\n`pivot` beziehungsweise `pivot_wider` meldet doppelte Schlüssel. Was ist der\nerste Schritt?\n\n- [ ] Eine Aggregationsfunktion angeben, damit es durchläuft ~ Das beseitigt\n      die Meldung, nicht die Ursache, und trifft eine stille Entscheidung.\n- [x] Zählen, welche Zelle mehrfach belegt ist ~ Richtig, mit\n      `aggfunc=\"size\"` beziehungsweise `values_fn = length`. Erst wenn klar\n      ist, warum es zwei Werte gibt, lässt sich entscheiden.\n- [ ] Die Tabelle vorher sortieren ~ Die Reihenfolge spielt keine Rolle.\n:::\n\n::: {.quiz}\nIn einer Messtabelle steht in jeder Zeile auch der Kanton des Standorts. Was\nist das Risiko?\n\n- [x] Die wiederholte Angabe kann sich widersprechen ~ Richtig, wie das `GH`\n      in Beispiel 3. Eine Tatsache, die an vielen Stellen steht, wird\n      irgendwann an einer Stelle falsch. Prüfen mit `nunique` je Standort.\n- [ ] Die Tabelle wird zu gross ~ Speicher ist hier nicht das Problem.\n- [ ] Kantone gehören nie in eine Auswertung ~ Sie gehören dazu, nur in eine\n      eigene Tabelle, die man bei Bedarf verknüpft.\n:::\n\n::: {.quiz}\nIn einer Zelle stehen mehrere Messwerte, durch Schrägstrich getrennt. Warum\nist das ein Problem, obwohl alle Werte vorhanden sind?\n\n- [x] Solange sie in einer Zelle stehen, sind sie Text und keine Zahlen ~\n      Richtig. Weder Summe noch Mittelwert noch eine Grafik sind möglich; erst\n      das Aufteilen in eine Zeile je Wert macht sie zugänglich.\n- [ ] Die Werte könnten in falscher Reihenfolge stehen ~ Die Reihenfolge ist\n      nicht das Hindernis.\n- [ ] Es fehlt eine Kennung ~ Die Kennung steht in der Zeile und wird beim\n      Aufteilen wiederholt.\n:::\n\n## Verlinkte Ressourcen\n\n- [Tidy Data, das Kapitel in R for Data Science](https://r4ds.hadley.nz/data-tidy)\n- [tidyr: Umformen in R](https://tidyr.tidyverse.org/)\n- [pandas: Reshaping](https://pandas.pydata.org/docs/user_guide/reshaping.html)\n",
    "supporting": [
      "tidy-data_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}