{
  "hash": "db693b539b2a472caf0f25f46747b8e8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Log-Rank-Test\"\ndescription: \"Vergleich von Überlebenskurven zwischen Gruppen und seine Voraussetzungen.\"\ncategories: [\"Survival-Analyse\", \"Hypothesentests\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: methode\nstand: fertig\norder: 30\n---\n\n\n\n\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Unterscheiden sich die Überlebenskurven zweier oder mehrerer Gruppen? |\n| Zielvariable | Zeit bis zum Ereignis plus Statusindikator |\n| Gruppen | zwei oder mehr, kategorial |\n| Was die Methode liefert | Chi-Quadrat-Statistik, Freiheitsgrade, p-Wert, beobachtete gegenüber erwarteten Ereignissen je Gruppe |\n| R-Funktion | `survdiff(Surv(zeit, status) ~ gruppe)` |\n| Python-Funktion | `logrank_test(...)`, für mehrere Gruppen `multivariate_logrank_test(...)` |\n| Verwandte Methoden | [Kaplan-Meier](kaplan-meier.qmd), [Cox-Modell](cox-modell.qmd) |\n\n## Wann diese Methode, wann nicht\n\nTypische Fragestellungen: Kündigen Monatsverträge früher als Jahresverträge,\nfallen Bauteile eines Lieferanten früher aus, unterscheiden sich zwei\nBehandlungen in der Zeit bis zum Rückfall.\n\nDer Test ist der statistische Nachbau dessen, was man in zwei\nKaplan-Meier-Kurven sieht. Er sagt, ob der Abstand mit Zufall vereinbar ist. Er\nsagt nicht, wie gross der Unterschied ist: Es gibt kein Effektmass. Wer eines\nbraucht, nimmt das [Cox-Modell](cox-modell.qmd), dessen Hazard Ratio genau diese\nLücke füllt.\n\n| Situation | Stattdessen |\n|---|---|\n| Ein Effektmass wird gebraucht | [Cox-Modell](cox-modell.qmd) |\n| Weitere Einflussgrössen sollen kontrolliert werden | [Cox-Modell](cox-modell.qmd), oder Stratifizierung |\n| Der Prädiktor ist metrisch | [Cox-Modell](cox-modell.qmd), statt willkürlich Klassen zu bilden |\n| Die Kurven kreuzen sich | Test verliert Schärfe; zeitabschnittsweise vergleichen oder anderes Verfahren |\n| Es geht nur um einen festen Zeitpunkt, etwa 12 Monate | Anteile mit Konfidenzintervall vergleichen, siehe [Kaplan-Meier](kaplan-meier.qmd) |\n| Ohne Zensierung | [t-Test](../tests/t-test-zwei-stichproben.qmd) oder [Mann-Whitney](../tests/nichtparametrische-tests.qmd) auf den Zeiten |\n\n## Grundidee und Modell\n\nDer Test geht jeden Zeitpunkt durch, an dem ein Ereignis eintritt, und fragt:\nWie viele Ereignisse wären in dieser Gruppe zu erwarten, wenn beide Gruppen\ndasselbe Risiko hätten? Erwartet wird proportional zur Anzahl unter Risiko.\nBeobachtete und erwartete Ereignisse werden über alle Zeitpunkte summiert und\nverglichen.\n\n$$\\chi^2 = \\frac{(O_1 - E_1)^2}{V}$$\n\n| Bestandteil | Bedeutung |\n|---|---|\n| $O_g$ | beobachtete Ereignisse in Gruppe $g$ über alle Zeitpunkte |\n| $E_g$ | erwartete Ereignisse unter der Nullhypothese gleicher Hazard-Raten |\n| $V$ | Varianz der Differenz, aus der Anzahl unter Risiko je Zeitpunkt |\n| Freiheitsgrade | Anzahl Gruppen minus eins |\n\nDer Erwartungswert an einem Zeitpunkt $t_i$ ist $E_{1i} = d_i \\cdot n_{1i} / n_i$,\ndie Ereignisse dieses Zeitpunkts, aufgeteilt nach dem Anteil der Gruppe an\nallen unter Risiko. Man kann das als eine Kette von Vierfeldertafeln lesen, eine\nje Ereigniszeitpunkt, deren Abweichungen aufsummiert werden.\n\nDie Nullhypothese lautet, dass die Überlebensfunktionen der Gruppen identisch\nsind. Weil der Test über alle Zeitpunkte summiert, ist er am schärfsten, wenn der\nUnterschied in eine Richtung geht und über die Zeit ähnlich bleibt. Genau das ist\nseine Stärke und seine Schwäche.\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung | Vorgehen |\n|---|---|---|---|---|\n| Nicht informative Zensierung | Zensierte haben dasselbe Risiko wie Beobachtete | inhaltlich, siehe [Zensierung](zensierung-ueberlebensfunktion.qmd) | p-Wert nicht interpretierbar | Ursachen der Zensierung berichten |\n| Unabhängige Beobachtungen | keine Paarung, keine Klumpen | Erhebungsdesign | p-Wert zu optimistisch | Verfahren für geschachtelte Daten |\n| Gruppen vorab festgelegt | Die Einteilung stammt nicht aus den Daten | Vorgehen prüfen | Der Test prüft eine an den Daten optimierte Grenze | Gruppen inhaltlich definieren |\n| Kurven kreuzen sich nicht | Der Unterschied wechselt nicht die Richtung | Kaplan-Meier-Kurven ansehen | Test verliert Schärfe, kann nichts finden, obwohl Unterschiede bestehen | abschnittsweise vergleichen, gewichtete Varianten |\n| Genügend Ereignisse | Nicht die Fallzahl zählt, sondern die Ereigniszahl | Ereignisse je Gruppe zählen | Test hat kaum Schärfe | Beobachtungszeit verlängern, Gruppen zusammenfassen |\n\n## Output lesen\n\nR, `survdiff()`:\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| `N` | Anzahl Beobachtungen je Gruppe | nicht ausschlaggebend für die Schärfe |\n| `Observed` | beobachtete Ereignisse je Gruppe | die Grösse, die zählt |\n| `Expected` | erwartete Ereignisse unter gleicher Hazard-Rate | berücksichtigt die Zeit unter Risiko |\n| `(O-E)^2/E` | Beitrag der Gruppe zur Statistik | zeigt, welche Gruppe die Abweichung treibt |\n| `(O-E)^2/V` | varianzgewichteter Beitrag | bei zwei Gruppen in beiden Zeilen gleich und identisch mit `Chisq` |\n| `Chisq` | Teststatistik | ohne Freiheitsgrade nicht deutbar |\n| `df` | Freiheitsgrade, Gruppen minus eins | bei zwei Gruppen eins |\n| `p` | p-Wert | keine Aussage über die Grösse des Unterschieds |\n\nWichtiger als die Statistik ist der Vergleich von `Observed` und `Expected`: Er\nzeigt die Richtung. Mehr beobachtete als erwartete Ereignisse heisst höheres\nRisiko in dieser Gruppe.\n\nPython, `logrank_test(...).print_summary()`:\n\n| Grösse | Was sie sagt | Unterschied zu R |\n|---|---|---|\n| `test_statistic` | Chi-Quadrat-Statistik | wie `Chisq` |\n| `p` | p-Wert | wie `p` |\n| `-log2(p)` | p-Wert als Bits | in R nicht enthalten, nur eine andere Skala |\n| `test_name` | verwendete Variante | benennt, ob gewichtet gerechnet wurde |\n\nWas in Python fehlt, sind die beobachteten und erwarteten Ereignisse je Gruppe.\nDie Richtung muss man sich also getrennt verschaffen, etwa über die\nKaplan-Meier-Mediane oder eine eigene Rechnung (Beispiel 1 zeigt sie). Wer den\nvollständigen Vergleich braucht, rechnet zusätzlich ein\n[Cox-Modell](cox-modell.qmd), dessen Hazard Ratio Richtung und Grösse in einer\nZahl liefert.\n\n## Interpretationsfallen\n\n- **Kein Effektmass.** Der Test liefert keine Grösse des Unterschieds. Ein\n  kleiner p-Wert bei grosser Ereigniszahl kann einen unbedeutenden Unterschied\n  betreffen.\n- **Nicht signifikant ist kein Beweis für Gleichheit.** Entscheidend ist die\n  Zahl der Ereignisse, nicht die der Beobachtungen.\n- **Kreuzende Kurven machen den Test blind.** Vorher ansehen, nicht nachher\n  erklären.\n- **Der Test prüft die ganzen Kurven.** Wer eine Aussage zu zwölf Monaten\n  braucht, vergleicht Anteile mit Konfidenzintervall.\n- **Keine Kontrolle weiterer Grössen.** Ein Gruppenunterschied kann von einer\n  dritten Variablen kommen; hier ist es das Cox-Modell, das kontrolliert.\n- **Gruppen nicht nachträglich bilden.** Eine an den Daten optimierte Grenze\n  macht den p-Wert wertlos.\n- **Mehrere Gruppen bedeuten mehrere Vergleiche.** Der Gesamttest sagt nur, dass\n  irgendwo ein Unterschied besteht; paarweise Vergleiche brauchen eine Korrektur,\n  siehe [multiples Testen](../inferenz/multiples-testen.qmd).\n\n## Ergebnis berichten\n\nVorlage für den Ergebnissatz:\n\n> Die Überlebenskurven unterscheiden sich zwischen [Gruppen]\n> (Log-Rank-Test, Chi-Quadrat([df]) = [Wert], p = [p]). In [Gruppe] traten\n> [beobachtet] Ereignisse gegenüber [erwartet] erwarteten auf; der Median beträgt\n> [Median] gegenüber [Median] [Einheit].\n\nGenannt werden Teststatistik mit Freiheitsgraden und p-Wert, Ereigniszahlen je\nGruppe, beobachtete gegenüber erwarteten Ereignissen als Richtungsangabe, die\nMediane oder Anteile zu festen Zeitpunkten, und die Feststellung, dass die\nKurven sich nicht kreuzen.\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt des Log-Rank-Tests |\n|---|---|\n| [Kaplan-Meier](kaplan-meier.qmd) | beschreiben statt testen, Anteile zu Zeitpunkten berichten |\n| [Cox-Modell](cox-modell.qmd) | Effektmass, mehrere Einflussgrössen, metrische Prädiktoren |\n| Gewichtete Varianten des Tests | frühe oder späte Unterschiede sollen betont werden, vorab festgelegt |\n| [Chi-Quadrat-Test](../tests/chi-quadrat-tests.qmd) | nur der Anteil zu einem festen Zeitpunkt, ohne Zeitverlauf |\n| [Mann-Whitney](../tests/nichtparametrische-tests.qmd) | keine Zensierung vorhanden |\n\n## Beispiele\n\nBeispiel 1 rechnet den Test an zehn Fällen vollständig von Hand nach. Die\nBeispiele 2 und 3 verwenden den Abo-Datensatz aus\n[Kaplan-Meier](kaplan-meier.qmd) (400 Fitnessabos, Stichtag nach 24 Monaten);\ndie Beispiele 4 und 5 zwei eigens dafür konstruierte Datensätze.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Der Test von Hand\n\n#### Frage und Datenlage\n\nZehn Fälle, fünf je Gruppe. Das Pluszeichen markiert eine Zensierung:\n\n| Zeit | 2 | 3 | 3 | 4⁺ | 5 | 6 | 7 | 8⁺ | 9 | 10 |\n|---|---|---|---|---|---|---|---|---|---|---|\n| Gruppe | A | A | B | A | B | B | A | B | A | B |\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nklein <- data.frame(\n  zeit   = c(2, 3, 3, 4, 5, 6, 7, 8, 9, 10),\n  gruppe = factor(c(\"A\", \"A\", \"B\", \"A\", \"B\", \"B\", \"A\", \"B\", \"A\", \"B\")),\n  status = c(1, 1, 1, 0, 1, 1, 1, 0, 1, 1)\n)\n\n# Schritt fuer Schritt: je Ereigniszeitpunkt eine Vierfeldertafel\nzeitpunkte <- sort(unique(klein$zeit[klein$status == 1]))\nschritte <- t(sapply(zeitpunkte, function(tt) {\n  unter_risiko <- klein$zeit >= tt\n  n_gesamt <- sum(unter_risiko)\n  n_a <- sum(unter_risiko & klein$gruppe == \"A\")\n  d <- sum(klein$zeit == tt & klein$status == 1)\n  d_a <- sum(klein$zeit == tt & klein$status == 1 & klein$gruppe == \"A\")\n  e_a <- d * n_a / n_gesamt\n  v <- if (n_gesamt > 1) d * (n_a / n_gesamt) * (1 - n_a / n_gesamt) *\n    (n_gesamt - d) / (n_gesamt - 1) else 0\n  c(t = tt, n = n_gesamt, n_A = n_a, d = d, d_A = d_a,\n    E_A = round(e_a, 4), V = round(v, 4))\n}))\nschritte\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      t  n n_A d d_A    E_A      V\n[1,]  2 10   5 1   1 0.5000 0.2500\n[2,]  3  9   4 2   1 0.8889 0.4321\n[3,]  5  6   2 1   0 0.3333 0.2222\n[4,]  6  5   2 1   0 0.4000 0.2400\n[5,]  7  4   2 1   1 0.5000 0.2500\n[6,]  9  2   1 1   1 0.5000 0.2500\n[7,] 10  1   0 1   0 0.0000 0.0000\n```\n\n\n:::\n\n```{.r .cell-code}\nzusammen <- colSums(schritte[, c(\"d_A\", \"E_A\", \"V\")])\nchi2 <- (zusammen[\"d_A\"] - zusammen[\"E_A\"])^2 / zusammen[\"V\"]\nround(c(zusammen, chisq = chi2, p = 1 - pchisq(chi2, df = 1)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      d_A       E_A         V chisq.d_A     p.d_A \n   4.0000    3.1222    1.6443    0.4686    0.4936 \n```\n\n\n:::\n\n```{.r .cell-code}\n# und zum Vergleich die fertige Funktion\nsurvdiff(Surv(zeit, status) ~ gruppe, data = klein)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nsurvdiff(formula = Surv(zeit, status) ~ gruppe, data = klein)\n\n         N Observed Expected (O-E)^2/E (O-E)^2/V\ngruppe=A 5        4     3.12     0.247     0.469\ngruppe=B 5        4     4.88     0.158     0.469\n\n Chisq= 0.5  on 1 degrees of freedom, p= 0.5 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom scipy import stats\n\nklein = pd.DataFrame({\n    \"zeit\": [2, 3, 3, 4, 5, 6, 7, 8, 9, 10],\n    \"gruppe\": list(\"AABABBABAB\"),\n    \"status\": [1, 1, 1, 0, 1, 1, 1, 0, 1, 1],\n})\n\nzeitpunkte = sorted(set(klein.loc[klein[\"status\"] == 1, \"zeit\"]))\nschritte = []\nfor tt in zeitpunkte:\n    unter_risiko = klein[\"zeit\"] >= tt\n    n_gesamt = int(unter_risiko.sum())\n    n_a = int((unter_risiko & (klein[\"gruppe\"] == \"A\")).sum())\n    ereignis = (klein[\"zeit\"] == tt) & (klein[\"status\"] == 1)\n    d = int(ereignis.sum())\n    d_a = int((ereignis & (klein[\"gruppe\"] == \"A\")).sum())\n    anteil = n_a / n_gesamt\n    v = (d * anteil * (1 - anteil) * (n_gesamt - d) / (n_gesamt - 1)\n         if n_gesamt > 1 else 0.0)\n    schritte.append({\"t\": tt, \"n\": n_gesamt, \"n_A\": n_a, \"d\": d, \"d_A\": d_a,\n                     \"E_A\": round(d * anteil, 4), \"V\": round(v, 4)})\n\nschritte = pd.DataFrame(schritte)\nprint(schritte.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n t  n  n_A  d  d_A    E_A      V\n 2 10    5  1    1 0.5000 0.2500\n 3  9    4  2    1 0.8889 0.4321\n 5  6    2  1    0 0.3333 0.2222\n 6  5    2  1    0 0.4000 0.2400\n 7  4    2  1    1 0.5000 0.2500\n 9  2    1  1    1 0.5000 0.2500\n10  1    0  1    0 0.0000 0.0000\n```\n\n\n:::\n\n```{.python .cell-code}\nO, E, V = schritte[[\"d_A\", \"E_A\", \"V\"]].sum()\nchi2 = (O - E) ** 2 / V\nprint(f\"O_A = {O}  E_A = {E:.4f}  V = {V:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nO_A = 4.0  E_A = 3.1222  V = 1.6443\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"chi2 = {chi2:.4f}  p = {1 - stats.chi2.cdf(chi2, df=1):.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nchi2 = 0.4686  p = 0.4936\n```\n\n\n:::\n\n```{.python .cell-code}\na = klein[klein[\"gruppe\"] == \"A\"]\nb = klein[klein[\"gruppe\"] == \"B\"]\nlogrank_test(a[\"zeit\"], b[\"zeit\"], a[\"status\"], b[\"status\"]).print_summary(\n    decimals=4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<lifelines.StatisticalResult: logrank_test>\n               t_0 = -1\n null_distribution = chi squared\ndegrees_of_freedom = 1\n         test_name = logrank_test\n\n---\n test_statistic      p  -log2(p)\n         0.4686 0.4936    1.0185\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nEine Zeile je Ereigniszeitpunkt:\n\n| $t_i$ | unter Risiko $n_i$ | davon A | Ereignisse $d_i$ | davon A | erwartet $E_{Ai}$ | Varianz $V_i$ |\n|---|---|---|---|---|---|---|\n| 2 | 10 | 5 | 1 | 1 | $1 \\cdot \\tfrac{5}{10} = 0.5000$ | 0.2500 |\n| 3 | 9 | 4 | 2 | 1 | $2 \\cdot \\tfrac{4}{9} = 0.8889$ | 0.4321 |\n| 5 | 6 | 2 | 1 | 0 | $1 \\cdot \\tfrac{2}{6} = 0.3333$ | 0.2222 |\n| 6 | 5 | 2 | 1 | 0 | 0.4000 | 0.2400 |\n| 7 | 4 | 2 | 1 | 1 | 0.5000 | 0.2500 |\n| 9 | 2 | 1 | 1 | 1 | 0.5000 | 0.2500 |\n| 10 | 1 | 0 | 1 | 0 | 0.0000 | 0.0000 |\n| **Summe** | | | | **4** | **3.1222** | **1.6443** |\n\n$$\\chi^2 = \\frac{(4 - 3.1222)^2}{1.6443} = \\frac{0.7705}{1.6443} = 0.4686,\n\\qquad p = 0.494$$\n\n| Schritt | Was er zeigt |\n|---|---|\n| Der zensierte Fall bei $t = 4$ | taucht **nirgends** als eigene Zeile auf, senkt aber ab $t = 5$ die Spalten $n_i$ und $n_{Ai}$. Genau wie bei [Kaplan-Meier](kaplan-meier.qmd). |\n| $E_{Ai}$ bei $t = 3$ | Zwei Ereignisse, vier von neun unter Risiko gehören zu A → erwartet werden 0.889 Ereignisse in A. Beobachtet wird eines. |\n| Die Erwartung ist **nie ganzzahlig** | Sie ist keine Zählung, sondern ein Anteil. Erst die Summe ist mit der beobachteten Zählung vergleichbar. |\n| $V_i$ bei $t = 10$ ist null | Nur noch ein Fall unter Risiko, und der gehört zu B: An diesem Zeitpunkt ist nichts mehr zu verteilen. Der Schritt trägt zur Statistik nichts bei. |\n| $O_A = 4$ gegen $E_A = 3.12$ | Gruppe A hatte etwas mehr Ereignisse als erwartet, eine Abweichung in der Grössenordnung eines knappen Ereignisses. |\n| $\\chi^2 = 0.47$, $p = 0.49$ | Vollkommen mit Zufall vereinbar. Bei sieben Ereignissen insgesamt wäre auch schwer etwas anderes zu erwarten. |\n\n::: {.note-box}\nDie Varianz $V_i$ ist die der hypergeometrischen Verteilung: Aus $n_i$ Fällen,\nvon denen $n_{Ai}$ zu A gehören, werden $d_i$ \"gezogen\" (die Ereignisse). Der\nFaktor $\\frac{n_i - d_i}{n_i - 1}$ ist die Korrektur für das Ziehen **ohne\nZurücklegen**, er wird null, wenn alle Verbliebenen ein Ereignis haben, weil\ndann nichts mehr zufällig ist.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Ein Unterschied zwischen den Gruppen lässt sich nicht nachweisen\n> (Log-Rank-Test, $\\chi^2$(1) = 0.47, p = 0.49; 4 beobachtete gegenüber 3.1\n> erwarteten Ereignissen in Gruppe A bei insgesamt 7 Ereignissen).\n\n### Beispiel 2: Vor dem Test die Kurven\n\n#### Frage und Datenlage\n\nZwei Dinge gehören geprüft, bevor der Test gerechnet wird: ob genügend\n**Ereignisse** vorliegen, nicht Fälle und ob die Kurven sich **kreuzen**.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(vertrag = abo$vertrag, ereignis = abo$status)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       ereignis\nvertrag   0   1\n  Jahr  101  64\n  Monat  52 183\n```\n\n\n:::\n\n```{.r .cell-code}\nkurven <- survfit(Surv(zeit, status) ~ vertrag, data = abo)\n\npar(mar = c(4, 4, 2, 1))\nplot(kurven, col = c(\"#2166ac\", \"#b2182b\"), lwd = 2, mark.time = TRUE,\n     xlab = \"Monate\", ylab = \"Anteil ohne Kündigung\", ylim = c(0, 1))\nlegend(\"bottomleft\", legend = c(\"Jahresvertrag\", \"Monatsvertrag\"),\n       col = c(\"#2166ac\", \"#b2182b\"), lwd = 2, bty = \"n\")\n```\n\n::: {.cell-output-display}\n![Beispiel 2: die Kurven trennen sich früh und kreuzen sich nicht. Genau dafür ist der Test gebaut.](log-rank-test_files/figure-html/fig-b2-lr-r-1.png){#fig-b2-lr-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(pd.crosstab(abo[\"vertrag\"], abo[\"status\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstatus     0    1\nvertrag          \nJahr     101   64\nMonat     52  183\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achse = plt.subplots()\nfor name, farbe in [(\"Jahr\", \"#2166ac\"), (\"Monat\", \"#b2182b\")]:\n    teil = abo[abo[\"vertrag\"] == name]\n    KaplanMeierFitter().fit(teil[\"zeit\"], teil[\"status\"], label=name) \\\n        .plot_survival_function(ax=achse, ci_show=False, color=farbe)\nachse.set_xlabel(\"Monate\")\nachse.set_ylabel(\"Anteil ohne Kündigung\")\nachse.set_ylim(0, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(0.0, 1.0)\n```\n\n\n:::\n\n```{.python .cell-code}\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselbe Prüfung in Python.](log-rank-test_files/figure-html/fig-b2-lr-py-1.png){#fig-b2-lr-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Vertragsart | zensiert (0) | Ereignis (1) | n |\n|---|---|---|---|\n| Jahr | 101 | **64** | 165 |\n| Monat | 52 | **183** | 235 |\n\n| Prüfpunkt | Befund | Bewertung |\n|---|---|---|\n| Ereignisse je Gruppe | 64 und 183 | Reichlich. Als grobe Faustregel gelten etwa zehn Ereignisse je Gruppe als untere Grenze für einen aussagekräftigen Test; hier ist das um ein Vielfaches erfüllt. |\n| Fälle je Gruppe | 165 und 235 | Diese Zahlen sind **nicht** die entscheidenden. Ein Datensatz mit 5000 Fällen und 8 Ereignissen liefert einen schwachen Test. |\n| Verlauf der Kurven | trennen sich in den ersten Monaten und bleiben getrennt | Kein Kreuzen. Der Unterschied hat über den ganzen Zeitraum dasselbe Vorzeichen, der Fall, für den der Test gebaut ist. |\n| Zensierungsanteil je Gruppe | 61 Prozent gegen 22 Prozent | Ungleich, aber unproblematisch: Die Zensierung ist rein administrativ (alle am Stichtag), und dass die Gruppe mit dem geringeren Risiko den Stichtag häufiger erreicht, ist die Folge des Effekts, nicht seine Ursache. |\n\n#### Interpretation\n\nBeide Voraussetzungen sind erfüllt; der Test darf gerechnet werden. Diese\nReihenfolge, erst Kurven, dann Test, ist keine Formalie, wie Beispiel 5 zeigt.\n\n### Beispiel 3: Der Test auf den Abo-Daten\n\n#### Frage und Datenlage\n\nUnterscheidet sich die Laufzeit von Monats- und Jahresverträgen?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest <- survdiff(Surv(zeit, status) ~ vertrag, data = abo)\ntest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nsurvdiff(formula = Surv(zeit, status) ~ vertrag, data = abo)\n\n                N Observed Expected (O-E)^2/E (O-E)^2/V\nvertrag=Jahr  165       64      129      32.7      69.7\nvertrag=Monat 235      183      118      35.7      69.7\n\n Chisq= 69.7  on 1 degrees of freedom, p= <2e-16 \n```\n\n\n:::\n\n```{.r .cell-code}\ndata.frame(\n  beobachtet = test$obs,\n  erwartet = round(test$exp, 1),\n  verhaeltnis = round(test$obs / test$exp, 2)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  beobachtet erwartet verhaeltnis\n1         64    128.9        0.50\n2        183    118.1        1.55\n```\n\n\n:::\n\n```{.r .cell-code}\n# Die Groesse des Unterschieds steht nicht im Test, sondern hier\nsummary(survfit(Surv(zeit, status) ~ vertrag, data = abo), times = c(12, 24))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(zeit, status) ~ vertrag, data = abo)\n\n                vertrag=Jahr \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n   12    134      31    0.812  0.0304        0.755        0.874\n   24    101      33    0.612  0.0379        0.542        0.691\n\n                vertrag=Monat \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n   12    108     127    0.460  0.0325        0.400        0.528\n   24     52      56    0.221  0.0271        0.174        0.281\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\njahr = abo[abo[\"vertrag\"] == \"Jahr\"]\nmonat = abo[abo[\"vertrag\"] == \"Monat\"]\n\nergebnis = logrank_test(jahr[\"zeit\"], monat[\"zeit\"],\n                        event_observed_A=jahr[\"status\"],\n                        event_observed_B=monat[\"status\"])\nergebnis.print_summary(decimals=3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<lifelines.StatisticalResult: logrank_test>\n               t_0 = -1\n null_distribution = chi squared\ndegrees_of_freedom = 1\n         test_name = logrank_test\n\n---\n test_statistic       p  -log2(p)\n         69.661 <0.0005    53.657\n```\n\n\n:::\n\n```{.python .cell-code}\ndef beobachtet_erwartet(daten, spalte, gruppe):\n    \"\"\"Was lifelines nicht ausgibt: O und E je Gruppe.\"\"\"\n    zeit, status = daten[\"zeit\"].values, daten[\"status\"].values\n    ist_gruppe = (daten[spalte] == gruppe).values\n    O = E = 0.0\n    for tt in sorted(set(zeit[status == 1])):\n        unter_risiko = zeit >= tt\n        ereignis = (zeit == tt) & (status == 1)\n        O += (ereignis & ist_gruppe).sum()\n        E += ereignis.sum() * (unter_risiko & ist_gruppe).sum() / unter_risiko.sum()\n    return O, E\n\n\nfor name in [\"Jahr\", \"Monat\"]:\n    O, E = beobachtet_erwartet(abo, \"vertrag\", name)\n    km = KaplanMeierFitter().fit(abo.loc[abo[\"vertrag\"] == name, \"zeit\"],\n                                 abo.loc[abo[\"vertrag\"] == name, \"status\"])\n    anteile = km.survival_function_at_times([12, 24]).round(3).values\n    print(f\"{name:6s} O = {O:5.0f}  E = {E:6.1f}  O/E = {O / E:.2f}\"\n          f\"  S(12) = {anteile[0]:.3f}  S(24) = {anteile[1]:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nJahr   O =    64  E =  128.9  O/E = 0.50  S(12) = 0.812  S(24) = 0.612\nMonat  O =   183  E =  118.1  O/E = 1.55  S(12) = 0.460  S(24) = 0.221\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Gruppe | n | beobachtet $O$ | erwartet $E$ | $O/E$ | $\\hat{S}(12)$ | $\\hat{S}(24)$ |\n|---|---|---|---|---|---|---|\n| Jahresvertrag | 165 | 64 | **128.9** | **0.50** | 0.812 | 0.612 |\n| Monatsvertrag | 235 | 183 | **118.1** | **1.55** | 0.460 | 0.221 |\n| gesamt | 400 | 247 | 247.0 | | | |\n\n$$\\chi^2(1) = 69.66, \\qquad p = 7 \\cdot 10^{-17}$$\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| $E$ summiert sich auf 247 | | Die Erwartungen verteilen genau die tatsächlich eingetretenen Ereignisse auf die Gruppen um. Deshalb ist $O - E$ in einer Gruppe immer das Negative der anderen: -64.9 und +64.9. |\n| $O/E = 0.50$ bei Jahresverträgen | halb so viele Kündigungen wie erwartet | Bei gleichem Risiko in beiden Gruppen wären hier 129 Kündigungen aufgetreten. Es waren 64. |\n| $O/E = 1.55$ bei Monatsverträgen | rund die Hälfte mehr als erwartet | **Die Richtung des Effekts steht hier und nirgendwo sonst im Testergebnis.** |\n| $\\chi^2(1) = 69.66$ | | Bei einem Freiheitsgrad. Der kritische Wert für 5 Prozent liegt bei 3.84, der beobachtete Wert übertrifft ihn um das Achtzehnfache. |\n| $p = 7 \\cdot 10^{-17}$ | praktisch null | Berichtet wird \"p < .001\". Weitere Stellen anzugeben, suggeriert eine Genauigkeit, die der Test nicht hat. |\n| $\\hat{S}(12)$: 0.812 gegen 0.460 | | **Das** ist die Grösse des Unterschieds. Sie steht nicht im Test. |\n\n::: {.note-box}\nDas Verhältnis $O/E$ liegt nahe bei dem, was ein [Cox-Modell](cox-modell.qmd) als\nHazard Ratio schätzen würde ($1.55 / 0.50 \\approx 3.1$), ist aber **kein**\nEffektmass im eigentlichen Sinn: Es hat keinen Standardfehler, kein\nKonfidenzintervall, und es hängt an der Zusammensetzung der Risikomengen. Als\nRichtungsangabe taugt es, als berichtete Effektstärke nicht.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Laufzeit unterscheidet sich deutlich zwischen den Vertragsarten\n> (Log-Rank-Test, $\\chi^2$(1) = 69.7, p < .001, n = 400 mit 247 Kündigungen). Bei\n> Monatsverträgen traten 183 Kündigungen gegenüber 118 unter gleichem Risiko\n> erwarteten auf, bei Jahresverträgen 64 gegenüber 129. Nach zwölf Monaten\n> bestehen noch 46.0 Prozent der Monats- und 81.2 Prozent der Jahresverträge.\n\n### Beispiel 4: Ein Nullbefund\n\n#### Frage und Datenlage\n\nZwei Gruppen zu je 100 Fällen, die aus **derselben** Verteilung stammen. Der Test\nsollte nichts finden und was heisst das dann?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_b <- 200\nzeit_b <- -log(lehmer(3131, n_b)) / 0.03          # gleiche Rate in beiden Gruppen\n\nabo_b <- data.frame(\n  zeit = pmin(zeit_b, 24),\n  status = as.integer(zeit_b <= 24),\n  gruppe = factor(rep(c(\"A\", \"B\"), times = n_b / 2))\n)\n\nsurvdiff(Surv(zeit, status) ~ gruppe, data = abo_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nsurvdiff(formula = Surv(zeit, status) ~ gruppe, data = abo_b)\n\n           N Observed Expected (O-E)^2/E (O-E)^2/V\ngruppe=A 100       50     50.2   0.00115   0.00229\ngruppe=B 100       51     50.8   0.00114   0.00229\n\n Chisq= 0  on 1 degrees of freedom, p= 1 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(gruppe = abo_b$gruppe, ereignis = abo_b$status)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      ereignis\ngruppe  0  1\n     A 50 50\n     B 49 51\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nn_b = 200\nzeit_b = -np.log(lehmer(3131, n_b)) / 0.03\n\nabo_b = pd.DataFrame({\n    \"zeit\": np.minimum(zeit_b, 24),\n    \"status\": (zeit_b <= 24).astype(int),\n    \"gruppe\": np.tile([\"A\", \"B\"], n_b // 2),\n})\n\na = abo_b[abo_b[\"gruppe\"] == \"A\"]\nb = abo_b[abo_b[\"gruppe\"] == \"B\"]\nlogrank_test(a[\"zeit\"], b[\"zeit\"],\n             event_observed_A=a[\"status\"],\n             event_observed_B=b[\"status\"]).print_summary(decimals=3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<lifelines.StatisticalResult: logrank_test>\n               t_0 = -1\n null_distribution = chi squared\ndegrees_of_freedom = 1\n         test_name = logrank_test\n\n---\n test_statistic     p  -log2(p)\n          0.002 0.962     0.056\n```\n\n\n:::\n\n```{.python .cell-code}\nfor name in [\"A\", \"B\"]:\n    O, E = beobachtet_erwartet(abo_b, \"gruppe\", name)\n    print(f\"Gruppe {name}: O = {O:.0f}  E = {E:.1f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGruppe A: O = 50  E = 50.2\nGruppe B: O = 51  E = 50.8\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Gruppe | n | beobachtet | erwartet | Differenz |\n|---|---|---|---|---|\n| A | 100 | 50 | 50.2 | -0.2 |\n| B | 100 | 51 | 50.8 | +0.2 |\n\n$$\\chi^2(1) = 0.002, \\qquad p = 0.96$$\n\n| Ausgabe | Wie sie zu lesen ist |\n|---|---|\n| $O$ und $E$ praktisch identisch | Genau das Bild, das unter der Nullhypothese zu erwarten ist. |\n| $\\chi^2 = 0.002$ | Nahe null. Solche Werte sind unter der Nullhypothese normal, aber nicht \"besonders bestätigend\", auch $\\chi^2 = 2.5$ wäre unauffällig. |\n| $p = 0.96$ | Ein hoher p-Wert ist **kein** Beleg für Gleichheit. Er sagt nur: Diese Daten sind mit gleichen Kurven vereinbar. |\n| 101 Ereignisse insgesamt | Die entscheidende Zahl für die Aussagekraft. Mit 101 Ereignissen würde ein Hazard Ratio von etwa 1.5 zuverlässig gefunden, eines von 1.15 aber meist nicht. |\n\n::: {.note-box}\n**Was ein Nullbefund berichtsfähig macht:** die Angabe, wie gross ein Effekt hätte\nsein müssen, um bei dieser Ereigniszahl entdeckt zu werden. Praktisch geschieht\ndas über ein [Cox-Modell](cox-modell.qmd): Sein Konfidenzintervall für das Hazard\nRatio zeigt unmittelbar, welche Effektgrössen die Daten noch zulassen, dieselbe\nLogik wie beim [Konfidenzintervall](../inferenz/schaetzen-konfidenzintervalle.qmd)\ngegenüber dem p-Wert.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Ein Unterschied zwischen den Gruppen lässt sich nicht nachweisen\n> (Log-Rank-Test, $\\chi^2$(1) = 0.00, p = 0.96; 50 gegenüber 51 Ereignissen bei je\n> 100 Fällen). Ob kleinere Unterschiede bestehen, lässt sich mit dieser\n> Ereigniszahl nicht entscheiden.\n\n### Beispiel 5: Kreuzende Kurven\n\n#### Frage und Datenlage\n\nDer wichtigste Fallstrick des Verfahrens. Zwei Gruppen zu je 250 Fällen:\n\n- **Gruppe A** hat in den ersten sechs Monaten ein hohes Risiko, danach ein sehr\n  niedriges, das Muster einer Operation mit früher Komplikationsgefahr und\n  gutem Verlauf danach.\n- **Gruppe B** hat durchgehend ein mittleres Risiko.\n\nDie beiden Kurven kreuzen sich. Was macht der Test daraus?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm <- 250\nfrueh <- -log(lehmer(5151, m)) / 0.16              # A: hohes Risiko bis Monat 6\nspaet <- 6 - log(lehmer(5252, m)) / 0.004          # A: danach sehr niedrig\na_zeit <- ifelse(frueh <= 6, frueh, spaet)\nb_zeit <- -log(lehmer(5353, m)) / 0.075            # B: konstant mittel\n\nkreuz <- data.frame(\n  zeit = pmin(c(a_zeit, b_zeit), 24),\n  status = as.integer(c(a_zeit, b_zeit) <= 24),\n  gruppe = factor(rep(c(\"A\", \"B\"), each = m))\n)\n\npar(mar = c(4, 4, 2, 1))\nplot(survfit(Surv(zeit, status) ~ gruppe, data = kreuz),\n     col = c(\"#2166ac\", \"#b2182b\"), lwd = 2,\n     xlab = \"Monate\", ylab = \"Anteil ohne Ereignis\", ylim = c(0, 1))\nlegend(\"topright\", legend = c(\"A\", \"B\"), col = c(\"#2166ac\", \"#b2182b\"),\n       lwd = 2, bty = \"n\")\n\nsurvdiff(Surv(zeit, status) ~ gruppe, data = kreuz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nsurvdiff(formula = Surv(zeit, status) ~ gruppe, data = kreuz)\n\n           N Observed Expected (O-E)^2/E (O-E)^2/V\ngruppe=A 250      161      162   0.00201    0.0037\ngruppe=B 250      199      198   0.00164    0.0037\n\n Chisq= 0  on 1 degrees of freedom, p= 1 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 5: kreuzende Kurven. Früh liegt A schlechter, später deutlich besser.](log-rank-test_files/figure-html/fig-b5-lr-r-1.png){#fig-b5-lr-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nm = 250\nfrueh = -np.log(lehmer(5151, m)) / 0.16\nspaet = 6 - np.log(lehmer(5252, m)) / 0.004\na_zeit = np.where(frueh <= 6, frueh, spaet)\nb_zeit = -np.log(lehmer(5353, m)) / 0.075\n\nroh = np.concatenate([a_zeit, b_zeit])\nkreuz = pd.DataFrame({\n    \"zeit\": np.minimum(roh, 24),\n    \"status\": (roh <= 24).astype(int),\n    \"gruppe\": np.repeat([\"A\", \"B\"], m),\n})\n\nka, kb = kreuz[kreuz[\"gruppe\"] == \"A\"], kreuz[kreuz[\"gruppe\"] == \"B\"]\nlogrank_test(ka[\"zeit\"], kb[\"zeit\"],\n             event_observed_A=ka[\"status\"],\n             event_observed_B=kb[\"status\"]).print_summary(decimals=3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<lifelines.StatisticalResult: logrank_test>\n               t_0 = -1\n null_distribution = chi squared\ndegrees_of_freedom = 1\n         test_name = logrank_test\n\n---\n test_statistic     p  -log2(p)\n          0.004 0.951     0.072\n```\n\n\n:::\n\n```{.python .cell-code}\nfor name in [\"A\", \"B\"]:\n    teil = kreuz[kreuz[\"gruppe\"] == name]\n    km = KaplanMeierFitter().fit(teil[\"zeit\"], teil[\"status\"])\n    werte = km.survival_function_at_times([6, 24]).round(3).values\n    print(f\"{name}: S(6) = {werte[0]:.3f}  S(24) = {werte[1]:.3f}\"\n          f\"  Ereignisse: {int(teil['status'].sum())}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nA: S(6) = 0.372  S(24) = 0.356  Ereignisse: 161\nB: S(6) = 0.632  S(24) = 0.204  Ereignisse: 199\n```\n\n\n:::\n\n```{.python .cell-code}\n# Getrennt nach Zeitabschnitt: erst alles bei Monat 6 zensieren, dann\n# nur die betrachten, die Monat 6 ueberlebt haben\nfrueh_teil = kreuz.assign(\n    z=np.minimum(kreuz[\"zeit\"], 6),\n    s=((kreuz[\"status\"] == 1) & (kreuz[\"zeit\"] <= 6)).astype(int))\nspaet_teil = kreuz[kreuz[\"zeit\"] > 6]\n\nfor name, daten, zs in [(\"Monate 0 bis 6\", frueh_teil, (\"z\", \"s\")),\n                        (\"Monate 6 bis 24\", spaet_teil, (\"zeit\", \"status\"))]:\n    ta = daten[daten[\"gruppe\"] == \"A\"]\n    tb = daten[daten[\"gruppe\"] == \"B\"]\n    t = logrank_test(ta[zs[0]], tb[zs[0]], ta[zs[1]], tb[zs[1]])\n    print(f\"{name}: chi2 = {t.test_statistic:.2f}, p = {t.p_value:.3g}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMonate 0 bis 6: chi2 = 37.60, p = 8.67e-10\nMonate 6 bis 24: chi2 = 86.60, p = 1.33e-20\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nZuerst die Kurven in Zahlen:\n\n| Gruppe | $\\hat{S}(6)$ | $\\hat{S}(24)$ | Ereignisse |\n|---|---|---|---|\n| A | **0.372** | **0.356** | 161 |\n| B | **0.632** | **0.204** | 199 |\n\nNach sechs Monaten steht A **deutlich schlechter** (37 gegen 63 Prozent), nach 24\nMonaten **deutlich besser** (36 gegen 20 Prozent). Die Kurven kreuzen sich.\n\nUnd nun die Tests:\n\n| Vergleich | $\\chi^2$ | p |\n|---|---|---|\n| **Gesamter Zeitraum** | **0.004** | **0.95** |\n| Monate 0 bis 6 | 37.60 | $9 \\cdot 10^{-10}$ |\n| Monate 6 bis 24 | 86.61 | $1 \\cdot 10^{-20}$ |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Der Gesamttest findet **nichts** | $\\chi^2 = 0.004$ ist so nahe an null, wie es überhaupt geht. Ein Bericht, der nur diese Zeile enthält, sagt \"kein Unterschied nachweisbar\", bei zwei Gruppen, die kaum verschiedener sein könnten. |\n| Beide Teilabschnitte finden **sehr viel** | Und zwar mit entgegengesetztem Vorzeichen: In den ersten sechs Monaten hat A mehr Ereignisse als erwartet, danach dramatisch weniger. |\n| Warum sich das aufhebt | Der Test summiert $O_i - E_i$ über alle Zeitpunkte, **bevor** er quadriert. Frühe positive und späte negative Abweichungen kürzen sich in dieser Summe. Erst danach wird das Quadrat gebildet, es ist also nicht so, dass Abweichungen \"unabhängig vom Vorzeichen\" zählen würden. |\n| Woran man es erkennt | Nur am **Bild**. Die Teststatistik selbst gibt keinen Hinweis auf das Problem; ein kleines $\\chi^2$ sieht bei kreuzenden Kurven genauso aus wie bei tatsächlich gleichen Kurven. |\n\n::: {.note-box}\n**Die abschnittsweisen p-Werte sind hier eine Veranschaulichung, kein\nBerichtsergebnis.** Wer die Grenze bei sechs Monaten nach dem Blick auf die\nKurven wählt, hat einen an den Daten optimierten Schnitt gesetzt, und die\np-Werte sind dadurch zu klein. Zulässig ist das Vorgehen nur mit einer vorab aus\nder Sache begründeten Grenze, hier etwa \"Ende der postoperativen Phase\".\n\nDie sauberen Alternativen: ein [Cox-Modell](cox-modell.qmd) mit zeitabhängigem\nEffekt, das den Wechsel selbst schätzt, oder eine vorab festgelegte gewichtete\nVariante des Tests (Gehan-Wilcoxon betont frühe, Fleming-Harrington je nach\nParameter frühe oder späte Unterschiede).\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Überlebenskurven kreuzen sich bei etwa sechs Monaten; Gruppe A hat früh ein\n> deutlich höheres, später ein deutlich niedrigeres Risiko. Ein einzelner\n> Log-Rank-Test über den ganzen Zeitraum ($\\chi^2$(1) = 0.00, p = 0.95) ist\n> deshalb nicht aussagekräftig, die gegenläufigen Abweichungen heben sich auf.\n> Berichtet werden die Anteile zu festen Zeitpunkten (nach 6 Monaten 37.2 gegen\n> 63.2 Prozent, nach 24 Monaten 35.6 gegen 20.4 Prozent) und ein Modell mit\n> zeitabhängigem Effekt.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nDer Test ergibt p = 0.6, die Gruppen haben je 150 Beobachtungen, aber nur 18 und\n21 Ereignisse. Was folgt?\n\n- [ ] Die Gruppen unterscheiden sich nicht ~ Das behauptet mehr, als die Daten\n      tragen.\n- [x] Mit so wenigen Ereignissen hat der Test kaum Schärfe ~ Richtig. Die\n      Genauigkeit hängt an der Ereigniszahl, nicht an der Fallzahl. Bei 39\n      Ereignissen insgesamt bleiben auch deutliche Unterschiede unentdeckt.\n- [ ] Die Beobachtungszeit war zu lang ~ Eine längere Beobachtung würde mehr\n      Ereignisse liefern und den Test schärfen.\n:::\n\n::: {.quiz}\nDie Kaplan-Meier-Kurven kreuzen sich bei etwa sechs Monaten. Der Log-Rank-Test\nüber den ganzen Zeitraum ergibt p = 0.95. Wie ist das zu deuten?\n\n- [x] Der Test ist hier nicht aussagekräftig, weil sich die Beiträge aufheben ~\n      Richtig. Er summiert die Abweichungen über die Zeit, bevor er quadriert;\n      entgegengesetzte Abweichungen kürzen sich. Die Frage muss lauten, **wann**\n      sich die Gruppen unterscheiden.\n- [ ] Die Gruppen sind über den ganzen Verlauf gleich ~ Genau das widerlegen die\n      kreuzenden Kurven.\n- [ ] Die Kurven kreuzen sich nur zufällig ~ Möglich, aber dann zeigt man es an\n      den Konfidenzbändern, statt den Gesamttest zu deuten.\n:::\n\n::: {.quiz}\nWarum liefert der Log-Rank-Test kein Effektmass?\n\n- [x] Weil er beobachtete gegen erwartete Ereignisse stellt, ohne ein Modell für\n      die Grösse des Unterschieds ~ Richtig. Er ist ein reiner Test. Ein\n      Effektmass liefert das Cox-Modell mit dem Hazard Ratio, samt\n      Konfidenzintervall.\n- [ ] Weil das Effektmass in der Statistik steht, man muss es nur umrechnen ~ Aus\n      Chi-Quadrat lässt sich kein Hazard Ratio gewinnen.\n- [ ] Weil die Zensierung ein Effektmass unmöglich macht ~ Das Cox-Modell schätzt\n      eines, ebenfalls mit zensierten Daten.\n:::\n\n::: {.quiz}\nIn einer Gruppe sind 183 Ereignisse beobachtet, 118 erwartet. Was heisst das?\n\n- [x] In dieser Gruppe traten mehr Ereignisse auf als bei gleichem Risiko zu\n      erwarten wäre ~ Richtig. Die erwarteten Ereignisse berücksichtigen die Zeit\n      unter Risiko. Mehr beobachtete als erwartete heisst höheres Risiko und\n      das ist die einzige Stelle, an der die **Richtung** des Effekts im\n      Testergebnis steht.\n- [ ] Die Gruppe ist grösser als die andere ~ Die Gruppengrösse steckt bereits in\n      der Erwartung.\n- [ ] Das Ergebnis ist damit signifikant ~ Ob die Abweichung mit Zufall\n      vereinbar ist, entscheidet der p-Wert.\n:::\n\n::: {.quiz}\nWarum ist der erwartete Wert je Gruppe nie eine ganze Zahl?\n\n- [x] Weil er die Ereignisse jedes Zeitpunkts nach dem Anteil unter Risiko\n      aufteilt ~ Richtig. Bei zwei Ereignissen und vier von neun unter Risiko in\n      Gruppe A werden 0.889 Ereignisse erwartet. Erst die Summe über alle\n      Zeitpunkte ist mit der beobachteten Zählung vergleichbar.\n- [ ] Weil gerundet wird ~ Es wird nicht gerundet; der Wert ist exakt ein Anteil.\n- [ ] Weil zensierte Fälle anteilig gezählt werden ~ Zensierte Fälle zählen gar\n      nicht als Ereignis, sie verkleinern nur die Anzahl unter Risiko.\n:::\n\n## Verlinkte Ressourcen\n\n- [An Introduction to Statistical Learning, Kapitel 11.3](https://www.statlearning.com/)\n- [survival: survdiff](https://stat.ethz.ch/R-manual/R-devel/library/survival/html/survdiff.html)\n- [lifelines: statistische Tests](https://lifelines.readthedocs.io/en/latest/lifelines.statistics.html)\n",
    "supporting": [
      "log-rank-test_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}