{
  "hash": "fd165ee8b160b5d99f8e49129ce20ef2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"SQL\"\ndescription: \"Abfragen, Joins, Aggregation und Unterabfragen.\"\ncategories: [\"SQL\", \"Datenbanken\", \"R\", \"Python\"]\nquelle: [\"PYFR\"]\nseitentyp: werkzeug\nstand: entwurf\norder: 20\n---\n\n\n\n\n\n## Kernideen\n\n- SQL ist **deklarativ**: Man beschreibt das Ergebnis, nicht den Weg dorthin.\n- Die **Auswertungsreihenfolge** weicht von der Schreibreihenfolge ab. Deshalb\n  filtert `WHERE` Zeilen **vor** der Gruppierung und `HAVING` Gruppen danach.\n- Ein **`INNER JOIN`** verliert, was keinen Partner hat; ein **`LEFT JOIN`**\n  behält es und füllt mit `NULL`.\n- **`NULL` ist kein Wert, sondern das Fehlen eines Werts.** Jeder Vergleich\n  damit ergibt weder wahr noch falsch, und das verändert Ergebnisse still.\n- `COUNT(*)` zählt Zeilen, `COUNT(spalte)` zählt **vorhandene Werte**.\n- **Fensterfunktionen** rechnen je Gruppe, ohne die Zeilen zusammenzufassen.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Datenmodellierung](datenmodellierung.qmd) für Schlüssel und\nBeziehungen. Wer [Data Wrangling](../daten/data-wrangling.qmd) oder\n[pandas](../programmierung/pandas.qmd) kennt, findet dieselben Operationen\nwieder: `WHERE` ist `filter`, `GROUP BY` ist `groupby`, `JOIN` ist `merge`,\nund `SUM() OVER (PARTITION BY ...)` ist `transform`. Wie man Abfragen aus R\noder Python absetzt, steht unter [Datenbankzugriff](datenbanken-zugriff.qmd).\n:::\n\n### Die Daten dieser Seite\n\nZwei Tabellen in einer SQLite-Datenbank, die beim Bauen der Seite entsteht:\n**sechs Artikel** (mit Kategorie und einem Rabatt, der bei drei Artikeln\nfehlt) und **zehn Bestellungen**. Ein Artikel, der Schlauch, wurde nie\nbestellt. Alle Ausgaben sind echte Abfrageergebnisse.\n\n### Die Auswertungsreihenfolge\n\n| Reihenfolge | Klausel | was passiert |\n|---|---|---|\n| 1 | `FROM`, `JOIN` | Tabellen zusammenstellen |\n| 2 | `WHERE` | einzelne Zeilen filtern |\n| 3 | `GROUP BY` | Zeilen zu Gruppen zusammenfassen |\n| 4 | `HAVING` | Gruppen filtern |\n| 5 | `SELECT` | Spalten auswählen und berechnen |\n| 6 | `ORDER BY` | sortieren |\n| 7 | `LIMIT` | abschneiden |\n\nDaraus folgt die häufigste Verwirrung: `WHERE SUM(betrag) > 500` ist nicht\nmöglich, weil zum Zeitpunkt von `WHERE` noch nicht gruppiert wurde. Ebenso\nlässt sich ein in `SELECT` vergebener Aliasname in `WHERE` nicht verwenden,\nin `ORDER BY` dagegen schon.\n\n### Die Join-Arten\n\n| Join | behält | typischer Einsatz |\n|---|---|---|\n| `INNER JOIN` | nur Paare, die auf beiden Seiten passen | Bestellungen mit ihren Artikeln |\n| `LEFT JOIN` | alle Zeilen links, rechts `NULL` wenn nichts passt | alle Artikel, auch nie bestellte |\n| `FULL OUTER JOIN` | alles von beiden Seiten | Abgleich zweier Quellen |\n| `CROSS JOIN` | jede Kombination | Kalender mal Standorte als Gerüst |\n\n### NULL: die dritte Wahrheit\n\nEin Vergleich mit `NULL` ergibt nicht wahr und nicht falsch, sondern\n**unbekannt**, und `WHERE` behält nur Zeilen, deren Bedingung wahr ist.\n\n| Ausdruck | Ergebnis | Folge |\n|---|---|---|\n| `rabatt = NULL` | unbekannt | findet **nie** etwas; richtig ist `IS NULL` |\n| `rabatt <> 5` | unbekannt, wenn `rabatt` fehlt | die Zeilen fehlen im Ergebnis |\n| `COUNT(rabatt)` | zählt nur vorhandene | weniger als `COUNT(*)` |\n| `AVG(rabatt)` | ignoriert fehlende | Nenner ist die Anzahl der vorhandenen |\n| `NOT IN (Unterabfrage mit NULL)` | nie wahr | liefert **gar nichts**; `NOT EXISTS` verwenden |\n| `COALESCE(rabatt, 0)` | Ersatzwert | macht die Annahme sichtbar |\n\n### Kurz nachgeschlagen\n\n| Aufgabe | SQL |\n|---|---|\n| filtern und sortieren | `WHERE ... ORDER BY ... LIMIT 10` |\n| Gruppen bilden und filtern | `GROUP BY kategorie HAVING COUNT(*) >= 3` |\n| verbinden | `JOIN artikel a ON a.artikel_id = b.artikel_id` |\n| fehlende Werte | `IS NULL`, `COALESCE(x, 0)` |\n| Fallunterscheidung | `CASE WHEN betrag > 500 THEN 'gross' ELSE 'klein' END` |\n| Zwischenergebnis benennen | `WITH umsatz AS (...) SELECT ... FROM umsatz` |\n| Anteil an der Gruppe | `SUM(x) OVER (PARTITION BY kategorie)` |\n| Rangfolge | `ROW_NUMBER() OVER (ORDER BY betrag DESC)` |\n| Duplikate finden | `GROUP BY schluessel HAVING COUNT(*) > 1` |\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Auswählen, filtern, sortieren\n\n#### Frage und Datenlage\n\nWelche Artikel gehören zur Kategorie Pneumatik, und wie gross sind die beiden\nTabellen?\n\n```sql\nSELECT bezeichnung, kategorie\nFROM artikel\nWHERE kategorie = 'Pneumatik'\nORDER BY bezeichnung\n```\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfrage(\"SELECT bezeichnung, kategorie FROM artikel\n       WHERE kategorie = 'Pneumatik' ORDER BY bezeichnung\")\n```\n\n::: {.cell-output-display}\n\n\n|bezeichnung  |kategorie |\n|:------------|:---------|\n|Schlauch 8mm |Pneumatik |\n|Ventil 3/8   |Pneumatik |\n|Zylinder 40  |Pneumatik |\n\n\n:::\n\n```{.r .cell-code}\nfrage(\"SELECT COUNT(*) AS artikel,\n              (SELECT COUNT(*) FROM bestellung) AS bestellungen\n       FROM artikel\")\n```\n\n::: {.cell-output-display}\n\n\n| artikel| bestellungen|\n|-------:|------------:|\n|       6|           10|\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(frage(\"\"\"SELECT bezeichnung, kategorie FROM artikel\n               WHERE kategorie = 'Pneumatik' ORDER BY bezeichnung\"\"\"\n            ).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n bezeichnung kategorie\nSchlauch 8mm Pneumatik\n  Ventil 3/8 Pneumatik\n Zylinder 40 Pneumatik\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(frage(\"\"\"SELECT COUNT(*) AS artikel,\n                      (SELECT COUNT(*) FROM bestellung) AS bestellungen\n               FROM artikel\"\"\").to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n artikel  bestellungen\n       6            10\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ergebnis | Wert | Erklärung |\n|---|---|---|\n| Pneumatik-Artikel | **Schlauch 8mm, Ventil 3/8, Zylinder 40** | `ORDER BY` sortiert nach Text, deshalb steht der Schlauch vorn. |\n| Artikel insgesamt | **6** | |\n| Bestellungen | **10** | Die Unterabfrage in `SELECT` liefert genau einen Wert und darf deshalb dort stehen. |\n\nR und Python setzen dieselbe Abfrage ab und bekommen dasselbe Ergebnis; die\nArbeit macht die Datenbank. Der Unterschied liegt nur in der Verpackung,\n`dbGetQuery` gegen `pd.read_sql_query`.\n\n#### Interpretation und Ergebnissatz\n\nDie Abfrage beschreibt, **was** gewünscht ist. Wie die Datenbank es holt\n(Index, Reihenfolge der Tabellen, Verfahren beim Verbinden), entscheidet sie\nselbst. Deshalb sieht dieselbe Abfrage auf zehn wie auf zehn Millionen Zeilen\ngleich aus.\n\n> Drei der sechs Artikel gehören zur Kategorie Pneumatik, und zu den sechs\n> Artikeln gibt es zehn Bestellungen.\n\n### Beispiel 2: INNER JOIN gegen LEFT JOIN\n\n#### Frage und Datenlage\n\nDer Schlauch wurde nie bestellt. Wie viele Zeilen liefert ein Join über\nbeide Tabellen, und welcher Join zeigt den nie bestellten Artikel?\n\n```sql\nSELECT a.bezeichnung, COUNT(b.bestell_id) AS anzahl,\n       COALESCE(SUM(b.betrag), 0) AS umsatz\nFROM artikel a\nLEFT JOIN bestellung b ON a.artikel_id = b.artikel_id\nGROUP BY a.artikel_id\nORDER BY umsatz\n```\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfrage(\"SELECT COUNT(*) AS inner_join FROM bestellung b\n       JOIN artikel a ON a.artikel_id = b.artikel_id\")\n```\n\n::: {.cell-output-display}\n\n\n| inner_join|\n|----------:|\n|         10|\n\n\n:::\n\n```{.r .cell-code}\nfrage(\"SELECT COUNT(*) AS left_join FROM artikel a\n       LEFT JOIN bestellung b ON a.artikel_id = b.artikel_id\")\n```\n\n::: {.cell-output-display}\n\n\n| left_join|\n|---------:|\n|        11|\n\n\n:::\n\n```{.r .cell-code}\nfrage(\"SELECT a.bezeichnung, COUNT(b.bestell_id) AS anzahl,\n              COALESCE(SUM(b.betrag), 0) AS umsatz\n       FROM artikel a\n       LEFT JOIN bestellung b ON a.artikel_id = b.artikel_id\n       GROUP BY a.artikel_id ORDER BY umsatz\")\n```\n\n::: {.cell-output-display}\n\n\n|bezeichnung     | anzahl| umsatz|\n|:---------------|------:|------:|\n|Schlauch 8mm    |      0|      0|\n|Dichtring       |      1|    180|\n|Kugellager 608  |      2|    560|\n|Zylinder 40     |      2|    768|\n|Ventil 3/8      |      3|   1200|\n|Sensor induktiv |      2|   2400|\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(len(frage(\"\"\"SELECT * FROM bestellung b\n                   JOIN artikel a ON a.artikel_id = b.artikel_id\"\"\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n10\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(len(frage(\"\"\"SELECT * FROM artikel a\n                   LEFT JOIN bestellung b ON a.artikel_id = b.artikel_id\"\"\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n11\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(frage(\"\"\"SELECT a.bezeichnung, COUNT(b.bestell_id) AS anzahl,\n                      COALESCE(SUM(b.betrag), 0) AS umsatz\n               FROM artikel a\n               LEFT JOIN bestellung b ON a.artikel_id = b.artikel_id\n               GROUP BY a.artikel_id ORDER BY umsatz\"\"\").to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    bezeichnung  anzahl  umsatz\n   Schlauch 8mm       0     0.0\n      Dichtring       1   180.0\n Kugellager 608       2   560.0\n    Zylinder 40       2   768.0\n     Ventil 3/8       3  1200.0\nSensor induktiv       2  2400.0\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Abfrage | Zeilen | Erklärung |\n|---|---|---|\n| `INNER JOIN` | **10** | so viele wie Bestellungen; der Schlauch fehlt. |\n| `LEFT JOIN` von `artikel` aus | **11** | zehn Bestellungen plus eine Zeile für den Schlauch mit `NULL`. |\n\n| Artikel | Bestellungen | Umsatz | Erklärung |\n|---|---|---|---|\n| Schlauch 8mm | **0** | **0.0** | `COUNT(b.bestell_id)` zählt nur vorhandene Werte und ergibt deshalb 0, während `COUNT(*)` hier 1 ergäbe. `COALESCE` macht aus dem `NULL` der Summe eine 0. |\n| Dichtring | 1 | 180.0 | |\n| Kugellager 608 | 2 | 560.0 | |\n| Zylinder 40 | 2 | 768.0 | |\n| Ventil 3/8 | 3 | 1200.0 | |\n| Sensor induktiv | 2 | 2400.0 | der umsatzstärkste Artikel bei nur zwei Bestellungen |\n\n#### Interpretation und Ergebnissatz\n\nDer Unterschied zwischen 10 und 11 Zeilen ist die ganze Geschichte: Ein\n`INNER JOIN` beantwortet \"was wurde bestellt\", ein `LEFT JOIN` \"wie steht es\num jeden Artikel\". Für eine Auswertung über das Sortiment ist der zweite\nrichtig, sonst fehlen genau die Artikel, die am meisten zu erzählen hätten,\nnämlich die mit null Bestellungen. Der Unterschied zwischen `COUNT(*)` und\n`COUNT(spalte)` ist dabei entscheidend, sonst steht beim Schlauch eine 1.\n\n> Der `INNER JOIN` liefert zehn Zeilen, der `LEFT JOIN` elf: Der nie\n> bestellte Schlauch erscheint nur im zweiten, mit null Bestellungen und\n> einem Umsatz von 0.\n\n### Beispiel 3: Gruppieren, WHERE und HAVING\n\n#### Frage und Datenlage\n\nUmsatz je Kategorie, danach nur Kategorien mit mindestens drei Bestellungen,\nund schliesslich nur Bestellungen ab Februar.\n\n```sql\nSELECT a.kategorie, COUNT(*) AS anzahl, SUM(b.betrag) AS umsatz,\n       ROUND(AVG(b.betrag), 2) AS mittel\nFROM bestellung b\nJOIN artikel a ON a.artikel_id = b.artikel_id\nGROUP BY a.kategorie\nORDER BY umsatz DESC\n```\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfrage(\"SELECT a.kategorie, COUNT(*) AS anzahl, SUM(b.betrag) AS umsatz,\n              ROUND(AVG(b.betrag), 2) AS mittel\n       FROM bestellung b JOIN artikel a ON a.artikel_id = b.artikel_id\n       GROUP BY a.kategorie ORDER BY umsatz DESC\")\n```\n\n::: {.cell-output-display}\n\n\n|kategorie  | anzahl| umsatz|  mittel|\n|:----------|------:|------:|-------:|\n|Elektronik |      2|   2400| 1200.00|\n|Pneumatik  |      5|   1968|  393.60|\n|Mechanik   |      3|    740|  246.67|\n\n\n:::\n\n```{.r .cell-code}\nfrage(\"SELECT a.kategorie, COUNT(*) AS anzahl, SUM(b.betrag) AS umsatz\n       FROM bestellung b JOIN artikel a ON a.artikel_id = b.artikel_id\n       GROUP BY a.kategorie HAVING COUNT(*) >= 3 ORDER BY umsatz DESC\")\n```\n\n::: {.cell-output-display}\n\n\n|kategorie | anzahl| umsatz|\n|:---------|------:|------:|\n|Pneumatik |      5|   1968|\n|Mechanik  |      3|    740|\n\n\n:::\n\n```{.r .cell-code}\nfrage(\"SELECT a.kategorie, SUM(b.betrag) AS umsatz\n       FROM bestellung b JOIN artikel a ON a.artikel_id = b.artikel_id\n       WHERE b.datum >= '2026-02-01'\n       GROUP BY a.kategorie ORDER BY umsatz DESC\")\n```\n\n::: {.cell-output-display}\n\n\n|kategorie  | umsatz|\n|:----------|------:|\n|Elektronik |   2400|\n|Pneumatik  |   1216|\n|Mechanik   |    560|\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(frage(\"\"\"SELECT a.kategorie, COUNT(*) AS anzahl, SUM(b.betrag) AS umsatz,\n                      ROUND(AVG(b.betrag), 2) AS mittel\n               FROM bestellung b JOIN artikel a ON a.artikel_id = b.artikel_id\n               GROUP BY a.kategorie ORDER BY umsatz DESC\"\"\").to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n kategorie  anzahl  umsatz  mittel\nElektronik       2  2400.0 1200.00\n Pneumatik       5  1968.0  393.60\n  Mechanik       3   740.0  246.67\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(frage(\"\"\"SELECT a.kategorie, COUNT(*) AS anzahl, SUM(b.betrag) AS umsatz\n               FROM bestellung b JOIN artikel a ON a.artikel_id = b.artikel_id\n               GROUP BY a.kategorie HAVING COUNT(*) >= 3\n               ORDER BY umsatz DESC\"\"\").to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nkategorie  anzahl  umsatz\nPneumatik       5  1968.0\n Mechanik       3   740.0\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(frage(\"\"\"SELECT a.kategorie, SUM(b.betrag) AS umsatz\n               FROM bestellung b JOIN artikel a ON a.artikel_id = b.artikel_id\n               WHERE b.datum >= '2026-02-01'\n               GROUP BY a.kategorie ORDER BY umsatz DESC\"\"\").to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n kategorie  umsatz\nElektronik  2400.0\n Pneumatik  1216.0\n  Mechanik   560.0\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Kategorie | Bestellungen | Umsatz | Mittel | Erklärung |\n|---|---|---|---|---|\n| Elektronik | 2 | **2400.0** | 1200.00 | wenige, aber grosse Bestellungen |\n| Pneumatik | 5 | 1968.0 | 393.60 | viele kleine |\n| Mechanik | 3 | 740.0 | 246.67 | |\n\n| Zusatz | Ergebnis | Erklärung |\n|---|---|---|\n| `HAVING COUNT(*) >= 3` | nur **Pneumatik (1968.0)** und **Mechanik (740.0)** | Elektronik fällt mit zwei Bestellungen heraus, obwohl es der grösste Umsatz ist. `HAVING` filtert **Gruppen**. |\n| `WHERE datum >= '2026-02-01'` | Elektronik 2400.0, Pneumatik **1216.0**, Mechanik **560.0** | `WHERE` filtert **Zeilen** vor der Gruppierung: Die Januarbestellungen fehlen in den Summen. Elektronik bleibt unverändert, weil dort beide Bestellungen später liegen. |\n\nDas Datum steht hier als Text `JJJJ-MM-TT`. Dieses Format sortiert und\nvergleicht sich richtig, weshalb der Textvergleich `>= '2026-02-01'`\nfunktioniert. Bei jedem anderen Format wäre es falsch, siehe\n[Datum und Zeit](../daten/datum-zeit.qmd).\n\n#### Interpretation und Ergebnissatz\n\nBeide Filter verkleinern das Ergebnis und meinen Verschiedenes. `WHERE` sagt\n\"diese Zeilen interessieren mich\", `HAVING` sagt \"diese Gruppen interessieren\nmich\". Wer eine Bedingung an der falschen Stelle setzt, bekommt ein\nplausibles, aber anderes Ergebnis: hier einmal 1968.0 und einmal 1216.0 für\ndieselbe Kategorie.\n\n> Elektronik führt mit 2400.0 Umsatz aus nur zwei Bestellungen, Pneumatik\n> folgt mit 1968.0 aus fünf. Mit `HAVING COUNT(*) >= 3` fällt Elektronik\n> heraus; mit `WHERE` ab Februar sinkt Pneumatik auf 1216.0.\n\n### Beispiel 4: NULL ist kein Wert\n\n#### Frage und Datenlage\n\nBei drei der sechs Artikel fehlt der Rabatt. Was zählen `COUNT(*)` und\n`COUNT(rabatt)`, was findet `WHERE rabatt <> 5.0`, und was liefert ein\n`NOT IN` mit einem `NULL` in der Unterabfrage?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfrage(\"SELECT COUNT(*) AS zeilen, COUNT(rabatt) AS mit_rabatt,\n              ROUND(AVG(rabatt), 4) AS mittel FROM artikel\")\n```\n\n::: {.cell-output-display}\n\n\n| zeilen| mit_rabatt| mittel|\n|------:|----------:|------:|\n|      6|          3| 5.8333|\n\n\n:::\n\n```{.r .cell-code}\nfrage(\"SELECT\n         (SELECT COUNT(*) FROM artikel WHERE rabatt = NULL)    AS gleich_null,\n         (SELECT COUNT(*) FROM artikel WHERE rabatt IS NULL)   AS ist_null,\n         (SELECT COUNT(*) FROM artikel WHERE rabatt <> 5.0)    AS ungleich_5\")\n```\n\n::: {.cell-output-display}\n\n\n| gleich_null| ist_null| ungleich_5|\n|-----------:|--------:|----------:|\n|           0|        3|          2|\n\n\n:::\n\n```{.r .cell-code}\nfrage(\"SELECT bezeichnung FROM artikel\n       WHERE artikel_id NOT IN (SELECT artikel_id FROM bestellung)\")\n```\n\n::: {.cell-output-display}\n\n\n|bezeichnung  |\n|:------------|\n|Schlauch 8mm |\n\n\n:::\n\n```{.r .cell-code}\n# Dieselbe Frage, aber ein NULL in der Unterabfrage\nfrage(\"SELECT COUNT(*) AS treffer FROM artikel\n       WHERE artikel_id NOT IN\n         (SELECT CASE WHEN artikel_id = 1 THEN NULL ELSE artikel_id END\n          FROM bestellung)\")\n```\n\n::: {.cell-output-display}\n\n\n| treffer|\n|-------:|\n|       0|\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(frage(\"\"\"SELECT COUNT(*) AS zeilen, COUNT(rabatt) AS mit_rabatt,\n                      ROUND(AVG(rabatt), 4) AS mittel FROM artikel\"\"\"\n            ).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n zeilen  mit_rabatt  mittel\n      6           3  5.8333\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(frage(\"\"\"SELECT\n         (SELECT COUNT(*) FROM artikel WHERE rabatt = NULL)  AS gleich_null,\n         (SELECT COUNT(*) FROM artikel WHERE rabatt IS NULL) AS ist_null,\n         (SELECT COUNT(*) FROM artikel WHERE rabatt <> 5.0)  AS ungleich_5\"\"\"\n            ).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n gleich_null  ist_null  ungleich_5\n           0         3           2\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(frage(\"\"\"SELECT bezeichnung FROM artikel\n               WHERE artikel_id NOT IN (SELECT artikel_id FROM bestellung)\"\"\"\n            ).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n bezeichnung\nSchlauch 8mm\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(len(frage(\"\"\"SELECT bezeichnung FROM artikel WHERE artikel_id NOT IN\n                   (SELECT CASE WHEN artikel_id = 1 THEN NULL ELSE artikel_id END\n                    FROM bestellung)\"\"\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Abfrage | Ergebnis | Erklärung |\n|---|---|---|\n| `COUNT(*)` | **6** | alle Zeilen |\n| `COUNT(rabatt)` | **3** | nur die Zeilen mit einem Wert |\n| `AVG(rabatt)` | **5.8333** | (5.0 + 2.5 + 10.0) / **3**, nicht durch 6. Der Nenner ist die Anzahl der vorhandenen Werte. |\n| `WHERE rabatt = NULL` | **0** Treffer | Der Vergleich ist nie wahr, auch nicht für die fehlenden. |\n| `WHERE rabatt IS NULL` | **3** | So fragt man nach dem Fehlen. |\n| `WHERE rabatt <> 5.0` | **2** statt 5 | Die drei Zeilen ohne Rabatt fehlen: Für sie ist die Bedingung unbekannt, nicht wahr. |\n| `NOT IN` ohne `NULL` | **Schlauch 8mm** | der nie bestellte Artikel |\n| `NOT IN` mit einem `NULL` | **0 Zeilen** | Sobald die Unterabfrage ein `NULL` enthält, ist `NOT IN` nie wahr. Das Ergebnis ist leer, ohne Fehlermeldung. |\n\n#### Interpretation und Ergebnissatz\n\nDie Zeile `WHERE rabatt <> 5.0` ist der Fall, der in Auswertungen am\nhäufigsten schadet: Sie sieht aus wie \"alle ausser den Fünfern\" und liefert\n\"alle ausser den Fünfern und ausser allen, bei denen der Rabatt fehlt\".\nRichtig wäre `WHERE rabatt IS NULL OR rabatt <> 5.0`. Beim `NOT IN` ist die\nFalle noch stiller, weil das Ergebnis nicht falsch, sondern leer ist;\n`NOT EXISTS` verhält sich dort wie erwartet.\n\n> Von sechs Artikeln haben drei einen Rabatt, ihr Mittel beträgt 5.8333.\n> `WHERE rabatt <> 5.0` findet nur zwei Artikel statt fünf, und ein `NOT IN`\n> mit einem `NULL` in der Unterabfrage liefert gar keine Zeile.\n\n### Beispiel 5: Zwischenergebnis benennen und Fensterfunktion\n\n#### Frage und Datenlage\n\nUmsatz je Artikel, und wie viel Prozent davon auf die jeweilige Kategorie\nentfallen. Ohne die Zeilen zusammenzufassen.\n\n```sql\nWITH je_artikel AS (\n  SELECT artikel_id, SUM(betrag) AS summe\n  FROM bestellung\n  GROUP BY artikel_id\n)\nSELECT a.bezeichnung, a.kategorie, j.summe,\n       ROUND(100.0 * j.summe / SUM(j.summe) OVER (PARTITION BY a.kategorie), 1)\n         AS anteil_kat\nFROM je_artikel j\nJOIN artikel a ON a.artikel_id = j.artikel_id\nORDER BY a.kategorie, j.summe DESC\n```\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfrage(\"WITH je_artikel AS (\n         SELECT artikel_id, SUM(betrag) AS summe FROM bestellung\n         GROUP BY artikel_id)\n       SELECT a.bezeichnung, a.kategorie, j.summe,\n              ROUND(100.0 * j.summe /\n                    SUM(j.summe) OVER (PARTITION BY a.kategorie), 1) AS anteil_kat\n       FROM je_artikel j JOIN artikel a ON a.artikel_id = j.artikel_id\n       ORDER BY a.kategorie, j.summe DESC\")\n```\n\n::: {.cell-output-display}\n\n\n|bezeichnung     |kategorie  | summe| anteil_kat|\n|:---------------|:----------|-----:|----------:|\n|Sensor induktiv |Elektronik |  2400|      100.0|\n|Kugellager 608  |Mechanik   |   560|       75.7|\n|Dichtring       |Mechanik   |   180|       24.3|\n|Ventil 3/8      |Pneumatik  |  1200|       61.0|\n|Zylinder 40     |Pneumatik  |   768|       39.0|\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(frage(\"\"\"WITH je_artikel AS (\n                 SELECT artikel_id, SUM(betrag) AS summe FROM bestellung\n                 GROUP BY artikel_id)\n               SELECT a.bezeichnung, a.kategorie, j.summe,\n                      ROUND(100.0 * j.summe /\n                            SUM(j.summe) OVER (PARTITION BY a.kategorie), 1)\n                        AS anteil_kat\n               FROM je_artikel j JOIN artikel a ON a.artikel_id = j.artikel_id\n               ORDER BY a.kategorie, j.summe DESC\"\"\").to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    bezeichnung  kategorie  summe  anteil_kat\nSensor induktiv Elektronik 2400.0       100.0\n Kugellager 608   Mechanik  560.0        75.7\n      Dichtring   Mechanik  180.0        24.3\n     Ventil 3/8  Pneumatik 1200.0        61.0\n    Zylinder 40  Pneumatik  768.0        39.0\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Artikel | Kategorie | Umsatz | Anteil an der Kategorie |\n|---|---|---|---|\n| Sensor induktiv | Elektronik | 2400.0 | **100.0** Prozent |\n| Kugellager 608 | Mechanik | 560.0 | **75.7** Prozent |\n| Dichtring | Mechanik | 180.0 | 24.3 Prozent |\n| Ventil 3/8 | Pneumatik | 1200.0 | **61.0** Prozent |\n| Zylinder 40 | Pneumatik | 768.0 | 39.0 Prozent |\n\n| Baustein | Wirkung |\n|---|---|\n| `WITH je_artikel AS (...)` | benennt das Zwischenergebnis, statt es zu verschachteln. Es liest sich von oben nach unten wie eine Pipe. |\n| `SUM(j.summe) OVER (PARTITION BY a.kategorie)` | die Kategoriesumme **in jeder Zeile**, ohne zu gruppieren |\n| `100.0 *` | erzwingt Gleitkommadivision; mit `100 *` würde SQLite ganzzahlig rechnen |\n| fehlender Schlauch | Er taucht nicht auf, weil `je_artikel` nur Artikel mit Bestellungen enthält. |\n\n#### Interpretation und Ergebnissatz\n\nDie Fensterfunktion ist in SQL das, was `transform` in pandas und\n`mutate(.by = ...)` in dplyr sind: ein Gruppenwert, der bei den Einzelzeilen\nbleibt. Ohne sie bräuchte es eine zweite Abfrage und einen Join auf die\nKategoriesummen. Das Ergebnis zeigt zugleich eine Abhängigkeit, die in der\nKategorie-Auswertung aus Beispiel 3 unsichtbar war: Der gesamte\nElektronikumsatz hängt an einem einzigen Artikel.\n\n> Der Sensor macht 100 Prozent des Elektronikumsatzes aus, das Kugellager\n> 75.7 Prozent der Mechanik und das Ventil 61.0 Prozent der Pneumatik. Der nie\n> bestellte Schlauch fehlt, weil das Zwischenergebnis nur Artikel mit\n> Bestellungen enthält.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nWarum lässt sich `WHERE SUM(betrag) > 500` nicht schreiben?\n\n- [x] `WHERE` wird vor der Gruppierung ausgewertet, es gibt dort noch keine\n      Summen ~ Richtig. Bedingungen auf Aggregaten gehören in `HAVING`, das\n      nach der Gruppierung läuft. Beides in einer Abfrage ist möglich und\n      üblich.\n- [ ] `SUM` ist in einer Bedingung generell nicht erlaubt ~ In `HAVING` ist\n      es erlaubt, es hängt allein am Zeitpunkt.\n- [ ] Es fehlt ein `GROUP BY` ~ Auch mit `GROUP BY` bliebe die Zeile falsch,\n      denn `WHERE` läuft trotzdem vorher.\n:::\n\n::: {.quiz}\nEine Auswertung über das Sortiment zeigt fünf statt sechs Artikel. Was ist\ndie wahrscheinlichste Ursache?\n\n- [x] Es wurde ein `INNER JOIN` verwendet, und ein Artikel hat keine\n      Bestellung ~ Richtig, wie der Schlauch in Beispiel 2. Für Auswertungen\n      über alle Artikel gehört der `LEFT JOIN` von der Artikeltabelle aus.\n- [ ] Der Artikel wurde gelöscht ~ Möglich, aber dann fehlte er auch in\n      `SELECT * FROM artikel`.\n- [ ] `GROUP BY` verwirft Gruppen mit nur einer Zeile ~ Das tut es nicht.\n:::\n\n::: {.quiz}\n`SELECT COUNT(*), COUNT(rabatt) FROM artikel` liefert 6 und 3. Was bedeutet\ndas?\n\n- [x] Bei drei Artikeln fehlt der Rabatt; `COUNT(spalte)` zählt nur\n      vorhandene Werte ~ Richtig. Deshalb teilt `AVG(rabatt)` auch durch 3\n      und nicht durch 6.\n- [ ] Drei Artikel haben den Rabatt 0 ~ Eine 0 wäre ein Wert und würde\n      mitgezählt.\n- [ ] `COUNT(*)` zählt doppelt ~ Es zählt Zeilen, hier sechs.\n:::\n\n::: {.quiz}\n`WHERE rabatt <> 5.0` liefert zwei von sechs Artikeln, obwohl nur einer den\nRabatt 5.0 hat. Warum?\n\n- [x] Für die drei Artikel ohne Rabatt ist die Bedingung unbekannt, nicht\n      wahr ~ Richtig. `WHERE` behält nur Zeilen, deren Bedingung wahr ist.\n      Gemeint war `WHERE rabatt IS NULL OR rabatt <> 5.0`.\n- [ ] `<>` ist kein gültiger Operator ~ Er ist gültig und bedeutet \"ungleich\".\n- [ ] Die Datenbank hat einen Index auf `rabatt` ~ Ein Index ändert\n      Ergebnisse nicht.\n:::\n\n::: {.quiz}\nEine Abfrage mit `NOT IN (SELECT kunde_id FROM sperrliste)` liefert plötzlich\ngar keine Zeilen mehr, obwohl es passende Kunden gibt. Was ist zu prüfen?\n\n- [x] Ob die Unterabfrage ein `NULL` enthält ~ Richtig. Ein einziges `NULL`\n      macht `NOT IN` für jede Zeile unbekannt, und das Ergebnis ist leer.\n      `NOT EXISTS` oder `WHERE kunde_id IS NOT NULL` in der Unterabfrage\n      lösen es.\n- [ ] Ob die Sperrliste zu gross ist ~ Die Grösse ändert das Ergebnis nicht.\n- [ ] Ob ein Index fehlt ~ Das beträfe die Geschwindigkeit, nicht das\n      Ergebnis.\n:::\n\n::: {.quiz}\nWelche Entsprechung hat `SUM(x) OVER (PARTITION BY g)` in pandas und dplyr?\n\n- [x] `groupby(\"g\")[\"x\"].transform(\"sum\")` beziehungsweise\n      `mutate(.by = g, s = sum(x))` ~ Richtig. Alle drei legen den\n      Gruppenwert in jede Zeile, ohne die Zeilen zusammenzufassen.\n- [ ] `groupby(\"g\").agg(...)` beziehungsweise `summarise()` ~ Die fassen\n      zusammen und liefern eine Zeile je Gruppe.\n- [ ] `merge` beziehungsweise `left_join` ~ Damit lässt sich dasselbe\n      nachbauen, es ist aber der Umweg.\n:::\n\n## Verlinkte Ressourcen\n\n- [SQLite: SQL-Referenz](https://www.sqlite.org/lang.html)\n- [SQLite: Fensterfunktionen](https://www.sqlite.org/windowfunctions.html)\n- [Use The Index, Luke: SQL-Performance erklärt](https://use-the-index-luke.com/)\n",
    "supporting": [
      "sql_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}