{
  "hash": "e342f6de119bed0fbad9ebbeb4e5113f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Skalenniveaus\"\ndescription: \"Nominal, ordinal, metrisch und was daraus für die Methodenwahl folgt.\"\ncategories: [\"Deskriptive Statistik\", \"EDA\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"ESDS\", \"Jesussek & Volk-Jesussek (2025)\"]\nseitentyp: konzept\nstand: entwurf\norder: 10\n---\n\n\n\n\n\n## Kernideen\n\n- Vier Stufen: **nominal, ordinal, intervall, verhältnis**.\n- Das Skalenniveau steckt in der **Bedeutung**, nicht in der gespeicherten Zahl —\n  deshalb muss es ein Mensch festlegen, kein Programm.\n- Es entscheidet, welche Rechenoperationen zulässig sind, und damit über den\n  ganzen weiteren Analysepfad.\n- Intervall und Verhältnis werden oft zu **metrisch** zusammengefasst; ihr\n  Unterschied liegt allein im Nullpunkt.\n- Nominale und ordinale Variablen bilden zusammen die **kategorischen**\n  Variablen — in R `factor`, in Python `pd.Categorical`.\n- Im Zweifel ein Niveau **tiefer** einordnen: Das kostet höchstens Testschärfe,\n  während zu hoch eingeordnet falsche Schlüsse erzeugt.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [R-Grundlagen](../../programmierung/r-grundlagen.qmd) für Faktor\nund Data Frame. Der Faktor ist hier zentral, weil das Skalenniveau eines\nMerkmals bestimmt, ob es überhaupt als Faktor gespeichert gehört. Was danach\nkommt, sind die [Häufigkeiten](haeufigkeiten.qmd) und die\n[Lage- und Streuungsmasse](lage-streuungsmasse.qmd).\n:::\n\n### Die Frage, die vor jeder Rechnung steht\n\nEin Datensatz enthält Zahlen. Das heisst nicht, dass mit ihnen gerechnet werden\ndarf. Postleitzahlen sind Zahlen, aber ihr Mittelwert ist sinnlos.\nKleidergrössen lassen sich ordnen, aber die Differenz zwischen 38 und 40 ist\nnicht dieselbe wie zwischen 46 und 48. Temperaturen in Grad Celsius lassen sich\nsubtrahieren, aber 20 Grad sind nicht doppelt so warm wie 10.\n\nDas Skalenniveau beantwortet, welche dieser Operationen zulässig sind. Es ist\nkeine Eigenschaft der gespeicherten Zahl, sondern der Bedeutung dahinter, und\ndeshalb muss es ein Mensch festlegen. Die Bestimmung des Skalenniveaus ist der\nerste Schritt jeder Auswertung — sie entscheidet, welche statistischen Methoden\nüberhaupt in Frage kommen.\n\n### Die vier Stufen\n\n| Niveau | erlaubt | Beispiel | zulässiges Lagemass |\n|---|---|---|---|\n| nominal | Gleichheit | Standort, Gerätetyp | Modus |\n| ordinal | zusätzlich Rangfolge | Schulnote, Zufriedenheit | zusätzlich Median |\n| intervall | zusätzlich Differenzen | Temperatur in Grad Celsius | zusätzlich Mittelwert |\n| verhältnis | zusätzlich Verhältnisse | Länge, Masse, Anzahl | alle, zusätzlich Variationskoeffizient |\n\nJe höher das Skalenniveau, desto mehr Vergleichsaussagen und Rechenoperationen\nsind möglich. Die Stufen bauen aufeinander auf: Was auf einer Stufe erlaubt ist,\nist es auf allen höheren auch.\n\n**Nominal.** Ausprägungen lassen sich unterscheiden, aber nicht sinnvoll ordnen;\ndie Reihenfolge der Kategorien ist austauschbar. Liegen nur zwei Ausprägungen\nvor, spricht man von **dichotomen** oder **binären** Variablen. Beispiele:\nGeschlecht, Religionsbekenntnis, Wohnort, Telefonnummer, Blutgruppe.\n\n**Ordinal.** Ausprägungen haben eine natürliche Rangfolge, aber die Abstände\nzwischen den Stufen sind nicht interpretierbar. Schulnoten lassen sich ordnen,\ndoch der Unterschied zwischen 1 und 2 ist nicht zwingend gleich gross wie\nzwischen 3 und 4. Beispiele: Schulnoten, Zufriedenheitsskala, Pflegestufe,\nmilitärischer Rang, Bildungsabschluss.\n\n**Metrisch: Intervall und Verhältnis.** Die beiden oberen Stufen werden häufig\nzusammengefasst. Der Unterschied liegt allein im Nullpunkt:\n\n- **Verhältnisskala:** Null bedeutet, dass nichts vorhanden ist. Aussagen wie\n  *doppelt so viel* sind zulässig. Beispiele: Gewicht, Alter, Einkommen,\n  Wohnfläche, CO₂-Ausstoss.\n- **Intervallskala:** Der Nullpunkt ist gesetzt und nicht absolut. Verhältnisse\n  sind nicht sinnvoll. Beispiele: Temperatur in °C, IQ-Score, Jahreszahl.\n\n::: {.note-box}\n**Das Marathon-Beispiel:** Werden die Zeiten ab dem Startschuss gestoppt, ist\ndie Skala verhältnisskaliert — null bedeutet *kein Zeitverbrauch*, und man kann\nsagen: Läufer A war doppelt so schnell wie Läufer B. Wird die Stoppuhr\nvergessen und stattdessen nur die Differenz zum Schnellsten gemessen, hat man\neine Intervallskala: Abstände sind sinnvoll (A ist 22 min schneller als B),\naber Verhältnisse nicht (A ist *nicht* 20 Prozent schneller als B).\n\nDasselbe Merkmal, dieselben Läufer — nur eine andere Messvorschrift, und die\nzulässigen Aussagen ändern sich.\n:::\n\n### Die drei Fragen zur Bestimmung\n\n```\n1. Gibt es eine natürliche Rangfolge?\n   NEIN → nominal\n   JA   → weiter\n\n2. Sind die Abstände zwischen den Stufen gleich und interpretierbar?\n   NEIN → ordinal\n   JA   → weiter\n\n3. Gibt es einen absoluten Nullpunkt (0 = nichts vorhanden)?\n   NEIN → intervall\n   JA   → verhältnis\n```\n\n### Warum die Unterscheidung wichtig ist\n\nDas Skalenniveau bestimmt nicht nur, welche Lagemasse erlaubt sind, sondern\nsteuert den gesamten weiteren Analysepfad:\n\n| Skalenniveau | typische Verfahren |\n|---|---|\n| nominal | [Häufigkeitstabelle](haeufigkeiten.qmd), Modus, [Chi-Quadrat-Test](../tests/chi-quadrat-tests.qmd), Cramers V |\n| ordinal | Median, [Spearman-Korrelation](korrelation.qmd), [Mann-Whitney, Kruskal-Wallis](../tests/nichtparametrische-tests.qmd) |\n| metrisch | Mittelwert, Standardabweichung, [t-Test](../tests/t-test-zwei-stichproben.qmd), [ANOVA](../tests/anova.qmd), [Pearson-Korrelation](korrelation.qmd), [Regression](../regression/einfache-lineare-regression.qmd) |\n\nDie Auswahl systematisch aufbereitet steht unter\n[Verfahren wählen](../verfahren-waehlen.qmd).\n\n::: {.note-box}\nIn der Praxis wird die Regel bei ordinalen Daten regelmässig gebrochen. Der\nMittelwert einer Zufriedenheitsskala von 1 bis 5 ist streng genommen nicht\ndefiniert, wird aber überall berichtet. Wer ihn verwendet, unterstellt damit,\ndie Abstände zwischen den Stufen seien gleich — **Beispiel 4 zeigt, wie viel an\ndieser Unterstellung hängt.**\n:::\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Zehn Variablen einordnen\n\n#### Frage und Datenlage\n\nDie drei Fragen aus der Erklärung, angewendet auf zehn Merkmale, die in echten\nDatensätzen vorkommen.\n\n#### Die Einordnung\n\n| Variable | Rangfolge? | gleiche Abstände? | absoluter Nullpunkt? | **Niveau** |\n|---|---|---|---|---|\n| Wohnort | nein | — | — | **nominal** |\n| Telefonnummer | nein | — | — | **nominal** |\n| Religionsbekenntnis | nein | — | — | **nominal** |\n| Produktbewertung (1–5 Sterne) | ja | **nein** | — | **ordinal** |\n| Prüfungsnoten (1–5) | ja | **nein** | — | **ordinal** |\n| Pflegestufe | ja | **nein** | — | **ordinal** |\n| Arbeitszufriedenheit (1–4) | ja | **nein** | — | **ordinal** |\n| IQ-Score | ja | ja | **nein** | **intervall** |\n| CO₂-Ausstoss pro Jahr | ja | ja | **ja** | **verhältnis** |\n| Wohnfläche in m² | ja | ja | **ja** | **verhältnis** |\n\n| Fall | Warum er häufig falsch eingeordnet wird |\n|---|---|\n| **Telefonnummer** | Sie ist eine Zahl und wird beim Einlesen automatisch numerisch. Ihr Mittelwert lässt sich rechnen und ist bedeutungslos. |\n| **Produktbewertung** | Vier Sterne sind besser als drei — aber ist der Sprung von 4 auf 5 derselbe wie der von 1 auf 2? Bei Sternebewertungen empirisch meist nicht: Die Verteilung ist stark linksschief, weil 5 der Standardfall ist. |\n| **IQ-Score** | Der Nullpunkt ist definitionsgemäss gesetzt (Mittelwert 100, Standardabweichung 15). Ein IQ von 140 ist nicht \"doppelt so intelligent\" wie 70. |\n| **Pflegestufe** | Der Betreuungsaufwand zwischen den Stufen wächst nicht gleichmässig — genau deshalb sind es Stufen und keine Messwerte. |\n\n::: {.note-box}\n**Zwei Sonderfälle, die regelmässig Streit auslösen:**\n\n| Fall | Einordnung | Begründung |\n|---|---|---|\n| **Zähldaten** (Anzahl Ausfälle) | verhältnis | Null Ausfälle heisst wirklich keine. Zwanzig sind doppelt so viele wie zehn. |\n| **Prozentangaben** (Anteil defekter Teile) | verhältnis, aber begrenzt | Null Prozent heisst keine, und 40 Prozent sind doppelt so viel wie 20. Die Obergrenze bei 100 macht allerdings viele Verfahren unpassend — dort hilft eine Transformation oder ein Modell für Anteile. |\n:::\n\n#### Interpretation\n\nDie Einordnung ist keine Formalie, sondern legt fest, welche Verfahren\nüberhaupt zur Wahl stehen. Wer sie überspringt, wählt sie implizit — nach dem\nDatentyp, den das Einleseprogramm geraten hat.\n\n### Beispiel 2: Kategorische Variablen richtig speichern\n\n#### Frage und Datenlage\n\nEine kleine Mitarbeiterbefragung mit allen vier Niveaus. Wie werden die\nVariablen so abgelegt, dass die Programme das Richtige tun?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\numfrage <- data.frame(\n  id            = 1:8,\n  abteilung     = c(\"IT\", \"HR\", \"IT\", \"Verkauf\", \"HR\", \"IT\", \"Verkauf\", \"HR\"),\n  zufriedenheit = c(4, 2, 5, 3, 1, 4, 5, 3),\n  gehalt        = c(85000, 62000, 91000, 58000, 64000, 78000, 55000, 67000),\n  temperatur_c  = c(22.1, 21.5, 23.0, 20.8, 21.9, 22.4, 19.5, 21.0)\n)\n\n# Nominal: Faktor ohne Ordnung\numfrage$abteilung <- factor(umfrage$abteilung)\nstr(umfrage$abteilung)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Factor w/ 3 levels \"HR\",\"IT\",\"Verkauf\": 2 1 2 3 1 2 3 1\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(umfrage$abteilung)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     HR      IT Verkauf \n      3       3       2 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Ordinal: geordneter Faktor\nstufen <- c(\"sehr unzufrieden\", \"unzufrieden\", \"neutral\",\n            \"zufrieden\", \"sehr zufrieden\")\numfrage$zufriedenheit_ord <- ordered(umfrage$zufriedenheit,\n                                     levels = 1:5, labels = stufen)\nstr(umfrage$zufriedenheit_ord)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Ord.factor w/ 5 levels \"sehr unzufrieden\"<..: 4 2 5 3 1 4 5 3\n```\n\n\n:::\n\n```{.r .cell-code}\n# Der geordnete Faktor kann vergleichen, der ungeordnete nicht\numfrage$zufriedenheit_ord > \"neutral\"\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  TRUE FALSE  TRUE FALSE FALSE  TRUE  TRUE FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\n# Median einer ordinalen Variablen: die mittlere Stufe, nicht eine Zahl\nlevels(umfrage$zufriedenheit_ord)[median(as.integer(umfrage$zufriedenheit_ord))]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"neutral\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Metrisch: einfach Zahlen\nround(c(mittel_gehalt = mean(umfrage$gehalt), sd_gehalt = sd(umfrage$gehalt),\n        mittel_temp = mean(umfrage$temperatur_c),\n        spannweite_temp = diff(range(umfrage$temperatur_c))), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  mittel_gehalt       sd_gehalt     mittel_temp spannweite_temp \n        70000.0         13136.6            21.5             3.5 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\numfrage = pd.DataFrame({\n    \"id\": range(1, 9),\n    \"abteilung\": [\"IT\", \"HR\", \"IT\", \"Verkauf\", \"HR\", \"IT\", \"Verkauf\", \"HR\"],\n    \"zufriedenheit\": [4, 2, 5, 3, 1, 4, 5, 3],\n    \"gehalt\": [85000, 62000, 91000, 58000, 64000, 78000, 55000, 67000],\n    \"temperatur_c\": [22.1, 21.5, 23.0, 20.8, 21.9, 22.4, 19.5, 21.0],\n})\n\numfrage[\"abteilung\"] = pd.Categorical(umfrage[\"abteilung\"])\nprint(umfrage[\"abteilung\"].dtype)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncategory\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(umfrage[\"abteilung\"].value_counts())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nabteilung\nHR         3\nIT         3\nVerkauf    2\nName: count, dtype: int64\n```\n\n\n:::\n\n```{.python .cell-code}\nstufen = [\"sehr unzufrieden\", \"unzufrieden\", \"neutral\",\n          \"zufrieden\", \"sehr zufrieden\"]\numfrage[\"zufriedenheit_ord\"] = pd.Categorical(\n    [stufen[v - 1] for v in umfrage[\"zufriedenheit\"]],\n    categories=stufen, ordered=True)\nprint(umfrage[\"zufriedenheit_ord\"].dtype)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncategory\n```\n\n\n:::\n\n```{.python .cell-code}\nprint((umfrage[\"zufriedenheit_ord\"] > \"neutral\").tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[True, False, True, False, False, True, True, False]\n```\n\n\n:::\n\n```{.python .cell-code}\n# Median einer ordinalen Variablen ueber die Codes\nmitte = int(np.median(umfrage[\"zufriedenheit_ord\"].cat.codes))\nprint(\"Median:\", stufen[mitte])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian: neutral\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"mittel_gehalt\": round(umfrage[\"gehalt\"].mean(), 1),\n       \"sd_gehalt\": round(umfrage[\"gehalt\"].std(), 1),\n       \"mittel_temp\": round(umfrage[\"temperatur_c\"].mean(), 1),\n       \"spannweite_temp\": round(umfrage[\"temperatur_c\"].max()\n                                - umfrage[\"temperatur_c\"].min(), 1)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'mittel_gehalt': np.float64(70000.0), 'sd_gehalt': np.float64(13136.6), 'mittel_temp': np.float64(21.5), 'spannweite_temp': np.float64(3.5)}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Variable | Speicherform | Was das Programm damit erlaubt |\n|---|---|---|\n| `abteilung` | `factor` / `Categorical` **ohne** Ordnung | Häufigkeiten, Kreuztabellen, Chi-Quadrat. Ein Vergleich `> \"HR\"` wirft eine Warnung beziehungsweise scheitert — genau richtig. |\n| `zufriedenheit_ord` | `ordered factor` / `Categorical(ordered=True)` | zusätzlich Vergleiche und Median. Die Ausgabe `sehr unzufrieden < unzufrieden < ...` zeigt die hinterlegte Ordnung. |\n| `gehalt` | `numeric` | alles, inklusive Verhältnisaussagen |\n| `temperatur_c` | `numeric` | alles ausser Verhältnisaussagen — und **das kann kein Datentyp erzwingen** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Der Vergleich `> \"neutral\"` funktioniert nur beim geordneten Faktor | Das ist der praktische Nutzen: Die Ordnung ist im Datentyp hinterlegt und muss nicht bei jeder Auswertung neu erinnert werden. |\n| Der Median wird über die **Stufennummern** gebildet und als Stufe ausgegeben | Genau die richtige Form für ein ordinales Merkmal. Beide Sprachen bieten dafür keinen direkten Aufruf auf dem Faktor — man rechnet auf den Codes und übersetzt zurück. |\n| Für `temperatur_c` gibt es **keine** Speicherform, die vor Verhältnisaussagen schützt | Intervall und Verhältnis sehen für jedes Programm gleich aus. Diesen Unterschied trägt allein der Mensch. |\n| Die Reihenfolge der Stufen wird **angegeben**, nicht geraten | Ohne `levels =` beziehungsweise `categories=` sortiert R alphabetisch — \"neutral\" käme vor \"sehr unzufrieden\". |\n\n::: {.note-box}\n**Der häufigste stille Fehler:** Eine numerisch codierte Variable bleibt als\nZahl liegen und geht so in ein Modell. R und Python rechnen dann mit den Codes,\nals wären sie metrisch — ohne Warnung, ohne Fehlermeldung, mit einem Ergebnis,\ndas plausibel aussieht.\n\nBeispiel 3 zeigt es an einer Postleitzahl.\n:::\n\n#### Interpretation\n\nDer Datentyp ist die Stelle, an der die inhaltliche Entscheidung festgehalten\nwird. Wer sie beim Einlesen trifft, muss sie später nicht wiederholen — und\nbekommt vom Programm eine Fehlermeldung statt eines falschen Ergebnisses.\n\n### Beispiel 3: Wenn das Niveau falsch angenommen wird\n\n#### Frage und Datenlage\n\nZwei Fälle, in denen das Programm bereitwillig rechnet und die Zahl trotzdem\nnichts bedeutet.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fall 1: Postleitzahl als Zahl\nplz <- c(3000, 8000, 6000, 3000, 8000)\nmean(plz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5600\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(plz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2509.98\n```\n\n\n:::\n\n```{.r .cell-code}\n# Richtig: als Faktor\ntable(factor(plz))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n3000 6000 8000 \n   2    1    2 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Fall 2: nominale Codierung, hier Geschlecht als 1 und 2\ngeschlecht <- c(1, 2, 2, 1, 2, 1, 2, 2, 1, 2)\nmean(geschlecht)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.6\n```\n\n\n:::\n\n```{.r .cell-code}\nround(prop.table(table(geschlecht)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngeschlecht\n  1   2 \n0.4 0.6 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Dieselbe Information, aber ohne Scheinbedeutung\nround(mean(geschlecht == 2), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nplz = pd.Series([3000, 8000, 6000, 3000, 8000])\nprint(\"mean(PLZ) =\", round(plz.mean(), 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean(PLZ) = 5600.0\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"sd(PLZ)   =\", round(plz.std(), 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsd(PLZ)   = 2510.0\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pd.Categorical(plz).value_counts())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n3000    2\n6000    1\n8000    2\nName: count, dtype: int64\n```\n\n\n:::\n\n```{.python .cell-code}\ngeschlecht = pd.Series([1, 2, 2, 1, 2, 1, 2, 2, 1, 2])\nprint(\"mean:\", geschlecht.mean())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean: 1.6\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(geschlecht.value_counts(normalize=True).round(2).to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{2: 0.6, 1: 0.4}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Anteil mit Code 2:\", round((geschlecht == 2).mean(), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnteil mit Code 2: 0.6\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Rechnung | Ergebnis | Wie es zu lesen ist |\n|---|---|---|\n| `mean(plz)` | **5600** | Eine Postleitzahl, die es nicht gibt, für einen Ort, der nicht existiert. Die Zahl ist rechnerisch korrekt und inhaltlich leer. |\n| `sd(plz)` | rund 2510 | Noch weniger deutbar: die Streuung eines Etiketts. |\n| Häufigkeitstabelle | 3000 zweimal, 6000 einmal, 8000 zweimal | **Das** ist die Information, die in der Variablen steckt. |\n| `mean(geschlecht)` | **1.6** | Kein \"durchschnittliches Geschlecht\". Die Zahl ist genau dann etwas wert, wenn man weiss, was die Codes bedeuten. |\n| Anteil mit Code 2 | **0.60** | Dieselbe Information, klar benannt. Zwischen den beiden Zahlen besteht der Zusammenhang $\\bar{x} = 1 + p$ — bei einer 0/1-Codierung wäre der Mittelwert direkt der Anteil. |\n\n::: {.note-box}\n**Warum die 1.6 in der Praxis trotzdem vorkommt:** Bei einer **dichotomen**\nVariablen ist der Mittelwert der Codes tatsächlich informativ, weil er sich in\neinen Anteil übersetzen lässt. Das ist der Sonderfall, in dem die Regel\nfolgenlos gebrochen werden darf — bei drei oder mehr nominalen Kategorien\nverschwindet diese Rettung sofort.\n\nDeshalb ist die 0/1-Codierung (statt 1/2) die bessere Wahl: Dort **ist** der\nMittelwert der Anteil, und es gibt nichts umzurechnen. Genau so arbeiten\nIndikatorvariablen in der [Regression](../regression/multiple-lineare-regression.qmd).\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Von zehn Befragten sind 60 Prozent mit Code 2 erfasst. Ein Mittelwert der\n> Codes wird nicht berichtet, weil das Merkmal nominal ist.\n\n### Beispiel 4: Was am Abstand hängt\n\n#### Frage und Datenlage\n\nDer Mittelwert einer Likert-Skala wird überall berichtet, obwohl er strenggenommen\nnicht definiert ist. Was genau unterstellt man damit — und was ändert sich, wenn\ndie Unterstellung nicht stimmt?\n\nZwei Gruppen zu je 30 Befragten, Zufriedenheit auf einer Skala von 1 bis 5:\n\n| Stufe | 1 | 2 | 3 | 4 | 5 |\n|---|---|---|---|---|---|\n| Gruppe A | 4 | 3 | 5 | 10 | 8 |\n| Gruppe B | 1 | 2 | 17 | 8 | 2 |\n\nGruppe A verteilt sich breit mit Schwerpunkt oben, Gruppe B klumpt sich in der\nMitte.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nA <- rep(1:5, times = c(4, 3, 5, 10, 8))\nB <- rep(1:5, times = c(1, 2, 17, 8, 2))\n\n# Drei Annahmen ueber die Abstaende zwischen den Stufen\nskalen <- list(\n  gleich    = c(1, 2, 3, 4, 5),      # 1-2-3-4-5, die uebliche Annahme\n  gestaucht = c(1, 2, 3, 3.5, 4),    # oben liegen die Stufen enger\n  gedehnt   = c(1, 2, 3, 5, 9)       # oben liegen sie weiter auseinander\n)\n\nfor (name in names(skalen)) {\n  s <- skalen[[name]]\n  a <- s[A]; b <- s[B]\n  t <- t.test(a, b, var.equal = TRUE)\n  cat(sprintf(\"%-10s Mittel A %.3f | B %.3f | Differenz %+.3f | p %.4f\\n\",\n              name, mean(a), mean(b), mean(a) - mean(b), t$p.value))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngleich     Mittel A 3.500 | B 3.267 | Differenz +0.233 | p 0.4250\ngestaucht  Mittel A 3.067 | B 3.067 | Differenz +0.000 | p 1.0000\ngedehnt    Mittel A 4.900 | B 3.800 | Differenz +1.100 | p 0.0791\n```\n\n\n:::\n\n```{.r .cell-code}\n# Die rangbasierten Auswertungen kennen das Problem nicht\nc(median_A = median(A), median_B = median(B))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmedian_A median_B \n       4        3 \n```\n\n\n:::\n\n```{.r .cell-code}\nwilcox.test(A, B)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum exact test\n\ndata:  A and B\nW = 537.5, p-value = 0.1817\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nA = np.repeat([1, 2, 3, 4, 5], [4, 3, 5, 10, 8])\nB = np.repeat([1, 2, 3, 4, 5], [1, 2, 17, 8, 2])\n\nskalen = {\"gleich\": [1, 2, 3, 4, 5],\n          \"gestaucht\": [1, 2, 3, 3.5, 4],\n          \"gedehnt\": [1, 2, 3, 5, 9]}\n\nfor name, s in skalen.items():\n    s = np.array(s, dtype=float)\n    a, b = s[A - 1], s[B - 1]\n    t = stats.ttest_ind(a, b)\n    print(f\"{name:10s} Mittel A {a.mean():.3f} | B {b.mean():.3f}\"\n          f\" | Differenz {a.mean() - b.mean():+.3f} | p {t.pvalue:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngleich     Mittel A 3.500 | B 3.267 | Differenz +0.233 | p 0.4250\ngestaucht  Mittel A 3.067 | B 3.067 | Differenz +0.000 | p 1.0000\ngedehnt    Mittel A 4.900 | B 3.800 | Differenz +1.100 | p 0.0791\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Median A:\", np.median(A), \"| Median B:\", np.median(B))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian A: 4.0 | Median B: 3.0\n```\n\n\n:::\n\n```{.python .cell-code}\nu = stats.mannwhitneyu(A, B)\nprint(f\"Mann-Whitney U = {u.statistic}, p = {u.pvalue:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMann-Whitney U = 537.5, p = 0.1795\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Annahme über die Abstände | Mittel A | Mittel B | Differenz | p |\n|---|---|---|---|---|\n| **gleich** (1, 2, 3, 4, 5) | 3.500 | 3.267 | **+0.233** | 0.425 |\n| **gestaucht** (1, 2, 3, 3.5, 4) | 3.067 | 3.067 | **±0.000** | **1.000** |\n| **gedehnt** (1, 2, 3, 5, 9) | 4.900 | 3.800 | **+1.100** | 0.079 |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die Differenz reicht von **0.000 bis +1.100** | Bei **identischen Daten**. Was sich ändert, ist allein die Annahme darüber, was die Zahlen bedeuten. |\n| Die \"gestauchte\" Skala ist nicht abwegig | Sie unterstellt, dass zwischen \"zufrieden\" und \"sehr zufrieden\" ein kleinerer Schritt liegt als zwischen \"unzufrieden\" und \"neutral\" — bei Zufriedenheitsskalen empirisch gut belegt, weil die oberen Stufen häufiger und weniger trennscharf sind. |\n| Die \"gedehnte\" Skala ebenso wenig | Bei Schmerz- oder Belastungsskalen ist der Sprung an den Extremen oft der grösste. |\n| **Der p-Wert wandert von 1.000 auf 0.079** | Und keine dieser Rechnungen ist falsch. Falsch ist nur, eine davon zu wählen, ohne die Wahl zu nennen. |\n\nDie rangbasierte Auswertung dagegen:\n\n| Grösse | Wert | Warum sie unberührt bleibt |\n|---|---|---|\n| Median A | **4** | Er zählt nur ab, wie viele Werte darüber und darunter liegen. |\n| Median B | **3** | |\n| Mann-Whitney U | 537.5, p = 0.180 | Der Test arbeitet auf Rängen. **Jede** der drei Skalen oben erzeugt dieselben Ränge, also dasselbe Ergebnis. |\n\n::: {.note-box}\n**Was daraus folgt, in drei Zeilen:**\n\n1. Wer den **Mittelwert** einer Likert-Skala berichtet, trifft eine\n   inhaltliche Annahme über die Abstände — und sollte sie nennen.\n2. Wer **Median und Rangtest** berichtet, kommt ohne diese Annahme aus. Der\n   Preis ist etwas Testschärfe.\n3. Bei **vielen Stufen** (etwa einer Skala von 0 bis 100) und ungefähr\n   symmetrischer Verteilung ist die Annahme meist harmlos. Bei **wenigen\n   Stufen** und schiefer Verteilung — wie hier — ist sie es nicht.\n\nUnd die praktische Zwischenlösung, die in Berichten oft die beste ist: **beides\nangeben.** Median mit Quartilen für die Beschreibung, Rangtest für den Vergleich,\nMittelwert nur, wenn ein Publikum ihn erwartet — mit dem Hinweis, worauf er\nberuht.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Gruppe A ist zufriedener als Gruppe B (Median 4 gegenüber 3), der Unterschied\n> ist jedoch nicht nachweisbar (Mann-Whitney U = 537.5, p = 0.18, je n = 30). Auf\n> Mittelwerte wird verzichtet, weil sie bei einer fünfstufigen Skala von der\n> Annahme gleicher Abstände abhängen: Je nach unterstellter Skalierung ergibt\n> sich eine Differenz zwischen 0.00 und 1.10.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEine Umfrage codiert das Geschlecht als 1 und 2. Der Bericht nennt einen\nMittelwert von 1.4. Was sagt diese Zahl?\n\n- [ ] Das durchschnittliche Geschlecht ~ Ein Durchschnitt setzt Abstände\n      voraus, die es hier nicht gibt.\n- [x] Indirekt, dass 40 Prozent der Gruppe mit 2 codiert sind ~ Richtig. Über\n      das Merkmal selbst sagt der Wert nichts, weil die Codierung willkürlich\n      ist. Berichtet gehört dann gleich der Anteil.\n- [ ] Dass die Skala ordinal ist ~ Sie ist nominal. Die Zahlen sind reine\n      Etiketten ohne Rangfolge.\n:::\n\n::: {.quiz}\nWarum ist die Anzahl Ausfälle pro Monat verhältnisskaliert, die Jahreszahl aber\nnur intervallskaliert?\n\n- [x] Weil null Ausfälle bedeuten, dass nichts passiert ist, das Jahr 0 aber\n      ein gesetzter Bezugspunkt ist ~ Richtig. Deshalb sind zwanzig Ausfälle\n      doppelt so viele wie zehn, das Jahr 2000 aber nicht doppelt so spät wie\n      1000.\n- [ ] Weil Jahreszahlen grösser sind ~ Die Grössenordnung spielt keine Rolle.\n- [ ] Weil Ausfälle ganzzahlig sind ~ Ganzzahligkeit und Skalenniveau sind\n      verschiedene Fragen.\n:::\n\n::: {.quiz}\nDieselben Befragungsdaten ergeben je nach unterstellter Skalierung\nMittelwertdifferenzen von 0.00 bis 1.10. Was folgt daraus?\n\n- [x] Der Mittelwert einer Likert-Skala hängt an einer Annahme, die die Daten\n      nicht belegen ~ Richtig. Gleiche Abstände zwischen den Stufen sind eine\n      Unterstellung. Median und Rangtest kommen ohne sie aus und liefern\n      dieselbe Antwort für alle drei Skalierungen.\n- [ ] Die Daten sind fehlerhaft ~ Die Daten sind dieselben; verschieden ist\n      nur ihre Übersetzung in Zahlen.\n- [ ] Man sollte die Skala mit mehr Stufen erheben ~ Das hilft tatsächlich,\n      löst aber das grundsätzliche Problem nicht.\n:::\n\n::: {.quiz}\nEine Variable wird als geordneter Faktor gespeichert statt als Zahl. Was gewinnt\nman dadurch?\n\n- [x] Die Ordnung ist im Datentyp hinterlegt, und unzulässige Rechnungen\n      scheitern ~ Richtig. Vergleiche und Median funktionieren, ein Mittelwert\n      wirft eine Warnung. Die inhaltliche Entscheidung ist damit einmal\n      festgehalten statt bei jeder Auswertung neu zu erinnern.\n- [ ] Die Rechnungen werden genauer ~ An der Genauigkeit ändert sich nichts.\n- [ ] Man spart Speicherplatz ~ Bei vielen Wiederholungen stimmt das sogar, ist\n      aber nicht der Punkt.\n:::\n\n::: {.quiz}\nFür welche Variable gibt es keine Speicherform, die vor unzulässigen Aussagen\nschützt?\n\n- [x] Temperatur in Grad Celsius ~ Richtig. Intervall- und Verhältnisskala sehen\n      für jedes Programm identisch aus — beide sind einfach Zahlen. Dass \"doppelt\n      so warm\" unzulässig ist, weiss nur der Mensch.\n- [ ] Abteilung ~ Als Faktor gespeichert, scheitern Vergleiche und Mittelwerte.\n- [ ] Zufriedenheitsstufe ~ Als geordneter Faktor gespeichert, sind Vergleiche\n      erlaubt und der Mittelwert wirft eine Warnung.\n:::\n\n## Verlinkte Ressourcen\n\n- [OpenIntro Statistics (frei verfügbar)](https://www.openintro.org/book/os/)\n- [Verfahren wählen: die Entscheidungsbäume](../verfahren-waehlen.qmd)\n- Jesussek, M. & Volk-Jesussek, H. (2025). *Statistik leichtgemacht*. 6. Auflage. numiqo.\n",
    "supporting": [
      "skalenniveaus_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}