{
  "hash": "d85ed4f39484da79c5c51535ed99ae2d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Kombinatorik und Wahrscheinlichkeit\"\ndescription: \"Zählprinzipien, Laplace-Wahrscheinlichkeit und die Rechenregeln.\"\ncategories: [\"Wahrscheinlichkeit\", \"R\", \"Python\"]\nquelle: [\"ESDS\"]\nseitentyp: konzept\nstand: fertig\norder: 10\n---\n\n\n\n\n\n## Kernideen\n\n- Kombinatorik ist kein Selbstzweck, sondern die **Rechenmaschine hinter dem\n  Nenner**.\n- Statt vier Formeln genügen zwei Fragen: **wird zurückgelegt**, und **zählt die\n  Reihenfolge**?\n- Drei Zugänge zum Wahrscheinlichkeitsbegriff, Laplace, statistisch,\n  axiomatisch, beantworten verschiedene Fragen und widersprechen einander\n  nicht.\n- Der **Additionssatz** gilt in der einfachen Form nur für disjunkte Ereignisse.\n- Aufgaben mit \"**mindestens ein**\" rechnet man über das **Gegenereignis**.\n- Der **Spielerfehlschluss**: Der Anteil pendelt sich ein, weil frühe\n  Abweichungen an Gewicht verlieren, nicht, weil sie ausgeglichen würden.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Häufigkeiten](../grundlagen/haeufigkeiten.qmd) für den Begriff\nder relativen Häufigkeit. Alles Weitere wird hier aufgebaut. Diese Seite ist\nder Übergang von der beschreibenden zur schliessenden Statistik.\n:::\n\n### Warum Abzählen der Anfang ist\n\nDie Frage, wie wahrscheinlich etwas ist, lässt sich in einfachen Fällen durch\nZählen beantworten: Wie viele Ergebnisse gibt es insgesamt, und wie viele davon\nsind die gesuchten? Beim Würfel sind es sechs und eines. Bei sechs Richtigen im\nLotto sind es rund vierzehn Millionen und eines, und diese Zahl will berechnet\nund nicht abgezählt werden.\n\n### Die zwei Fragen vor jeder Formel\n\n1. **Wird zurückgelegt?** Kann dasselbe Element mehrfach gewählt werden?\n2. **Spielt die Reihenfolge eine Rolle?** Ist ABC etwas anderes als CBA?\n\nAus den Antworten ergeben sich die vier Standardfälle. Gezogen werden $k$ aus\n$n$ Elementen:\n\n| Zurücklegen | Reihenfolge | Anzahl | Beispiel |\n|---|---|---|---|\n| ja | ja | $n^k$ | dreistelliger Zahlencode |\n| nein | ja | $\\frac{n!}{(n-k)!}$ | Podestplätze bei einem Rennen |\n| nein | nein | $\\binom{n}{k} = \\frac{n!}{k!\\,(n-k)!}$ | Lottozahlen |\n| ja | nein | $\\binom{n+k-1}{k}$ | Kugeln aus einer Urne, nur die Anzahl je Farbe zählt |\n\nDie dritte Zeile folgt aus der zweiten, und das erklärt, woher der\nBinomialkoeffizient kommt: Zieht man drei aus zehn mit Beachtung der\nReihenfolge, gibt es $10 \\cdot 9 \\cdot 8 = 720$ Möglichkeiten. Interessiert die\nReihenfolge nicht, ist jede Auswahl dabei $3! = 6$ mal gezählt worden, einmal\nje Anordnung. Also bleiben $720 / 6 = 120$.\n\n### Drei Zugänge zum Wahrscheinlichkeitsbegriff\n\n| Zugang | Wahrscheinlichkeit ist | Setzt voraus | Versagt bei |\n|---|---|---|---|\n| **Laplace** | günstige durch mögliche Fälle | alle Elementarereignisse gleich wahrscheinlich | fehlender Symmetrie, etwa einem Maschinenausfall |\n| **statistisch** | Grenzwert der relativen Häufigkeit | Wiederholbarkeit unter gleichen Bedingungen | einmaligen Ereignissen |\n| **axiomatisch** (Kolmogorow) | eine Funktion mit drei Eigenschaften | nichts |, sagt dafür auch nicht, woher die Zahlen kommen |\n\nDie drei Axiome von Kolmogorow:\n\n1. $P(A) \\ge 0$ für jedes Ereignis\n2. $P(\\Omega) = 1$ für das sichere Ereignis\n3. $P(A \\cup B) = P(A) + P(B)$ für **disjunkte** Ereignisse\n\nAlles Weitere, der Additionssatz, das Gegenereignis, die\n[bedingte Wahrscheinlichkeit](bedingte-wahrscheinlichkeit-bayes.qmd), folgt\ndaraus.\n\n### Additionssatz und Gegenereignis\n\nDer **Additionssatz** gilt in seiner einfachen Form nur für disjunkte\nEreignisse. Überschneiden sie sich, wird der gemeinsame Teil zweimal gezählt\nund muss abgezogen werden:\n\n$$P(A \\cup B) = P(A) + P(B) - P(A \\cap B)$$\n\nDas **Gegenereignis** ist der zweite Griff. Aufgaben mit \"mindestens ein\" lassen\nsich fast immer leichter über \"keiner\" rechnen, weil dort nur ein einziges\nProdukt entsteht statt einer Summe vieler Fälle:\n\n$$P(\\text{mindestens eine Sechs}) = 1 - P(\\text{keine Sechs}) = 1 - \\left(\\tfrac{5}{6}\\right)^n$$\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Die vier Fälle an einer Aufgabe\n\n#### Frage und Datenlage\n\nZehn Elemente, drei werden gezogen. Vier Fragen, vier Zahlen und derselbe\nAusgangspunkt.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 10; k <- 3\n\nround(c(\n  mit_zuruecklegen_mit_anordnung = n^k,\n  ohne_zuruecklegen_mit_anordnung = factorial(n) / factorial(n - k),\n  ohne_zuruecklegen_ohne_anordnung = choose(n, k),\n  mit_zuruecklegen_ohne_anordnung = choose(n + k - 1, k)\n), 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  mit_zuruecklegen_mit_anordnung  ohne_zuruecklegen_mit_anordnung \n                            1000                              720 \nohne_zuruecklegen_ohne_anordnung  mit_zuruecklegen_ohne_anordnung \n                             120                              220 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Die Herleitung des Binomialkoeffizienten, Schritt fuer Schritt\nc(mit_anordnung = 10 * 9 * 8,\n  anordnungen_je_auswahl = factorial(3),\n  ohne_anordnung = 10 * 9 * 8 / factorial(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         mit_anordnung anordnungen_je_auswahl         ohne_anordnung \n                   720                      6                    120 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Und die Grossenordnung im Lotto\nc(sechs_aus_49 = choose(49, 6),\n  wahrscheinlichkeit = 1 / choose(49, 6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      sechs_aus_49 wahrscheinlichkeit \n      1.398382e+07       7.151124e-08 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nn, k = 10, 3\n\nprint({\"mit_zuruecklegen_mit_anordnung\": n ** k,\n       \"ohne_zuruecklegen_mit_anordnung\": math.perm(n, k),\n       \"ohne_zuruecklegen_ohne_anordnung\": math.comb(n, k),\n       \"mit_zuruecklegen_ohne_anordnung\": math.comb(n + k - 1, k)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'mit_zuruecklegen_mit_anordnung': 1000, 'ohne_zuruecklegen_mit_anordnung': 720, 'ohne_zuruecklegen_ohne_anordnung': 120, 'mit_zuruecklegen_ohne_anordnung': 220}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"mit_anordnung\": 10 * 9 * 8,\n       \"anordnungen_je_auswahl\": math.factorial(3),\n       \"ohne_anordnung\": 10 * 9 * 8 // math.factorial(3)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'mit_anordnung': 720, 'anordnungen_je_auswahl': 6, 'ohne_anordnung': 120}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"sechs_aus_49\": math.comb(49, 6),\n       \"wahrscheinlichkeit\": 1 / math.comb(49, 6)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'sechs_aus_49': 13983816, 'wahrscheinlichkeit': 7.151123842018516e-08}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Zurücklegen | Reihenfolge | Formel | Ergebnis | Sachbeispiel |\n|---|---|---|---|---|\n| ja | ja | $10^3$ | **1 000** | dreistelliger Zahlencode |\n| nein | ja | $10 \\cdot 9 \\cdot 8$ | **720** | Gold, Silber, Bronze aus zehn Läufern |\n| nein | nein | $\\binom{10}{3}$ | **120** | eine dreiköpfige Arbeitsgruppe |\n| ja | nein | $\\binom{12}{3}$ | **220** | drei Kugeln aus zehn Farben, nur die Anzahl je Farbe zählt |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die Zahlen fallen von 1 000 auf 120 | Jede Einschränkung verkleinert den Ergebnisraum: kein Zurücklegen streicht Wiederholungen, keine Reihenfolge fasst Anordnungen zusammen. |\n| $720 / 6 = 120$ | Die Herleitung in einer Zeile. Jede Dreierauswahl wurde $3! = 6$ mal gezählt, einmal je Anordnung. **So entsteht der Binomialkoeffizient.** |\n| Der vierte Fall ist der **einzige**, bei dem die Zahl **steigt** | 220 gegen 120. Mit Zurücklegen kommen die Fälle \"dreimal dieselbe Farbe\" und \"zweimal eine, einmal eine andere\" dazu. Die Formel $\\binom{n+k-1}{k}$ wirkt willkürlich, ist aber der bekannte Trick mit $k$ Kugeln und $n-1$ Trennstrichen. |\n| Sechs aus 49 | **13 983 816** | Eine Wahrscheinlichkeit von 1 zu 14 Millionen, oder 0.0000000715. |\n\n::: {.note-box}\n**Warum sich die zwei Fragen besser merken lassen als vier Formeln:** Sie führen\nauch dann zum Ziel, wenn die Aufgabe nicht nach Lehrbuch aussieht.\n\n| Aufgabe | Zurücklegen? | Reihenfolge? |\n|---|---|---|\n| PIN mit vier Ziffern | ja | ja |\n| Sitzordnung von acht Gästen | nein | ja |\n| Auswahl von drei aus zwölf Bewerbungen | nein | nein |\n| Wie viele Eissorten-Kombinationen bei drei Kugeln aus acht Sorten? | ja | nein |\n\nDie letzte Zeile ist die, bei der die meisten hängenbleiben und die einzige,\nbei der man die vierte Formel überhaupt braucht.\n:::\n\n#### Interpretation\n\nDie Kombinatorik liefert den Nenner der Laplace-Wahrscheinlichkeit. Alles\nWeitere ist Division.\n\n### Beispiel 2: Das Geburtstagsproblem\n\n#### Frage und Datenlage\n\nWie viele Personen braucht es, damit zwei von ihnen mit mehr als 50 Prozent\nWahrscheinlichkeit am selben Tag Geburtstag haben? Die spontane Schätzung liegt\nmeist bei 180, der Hälfte von 365.\n\nGerechnet wird über das **Gegenereignis**: alle haben verschiedene Geburtstage.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_geteilt <- function(m) 1 - prod((365 - seq_len(m) + 1) / 365)\n\nstufen <- c(5, 10, 20, 23, 30, 50, 60, 70)\nround(rbind(personen = stufen,\n            wahrscheinlichkeit = sapply(stufen, p_geteilt)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     [,1]    [,2]    [,3]    [,4]    [,5]    [,6]    [,7]\npersonen           5.0000 10.0000 20.0000 23.0000 30.0000 50.0000 60.0000\nwahrscheinlichkeit 0.0271  0.1169  0.4114  0.5073  0.7063  0.9704  0.9941\n                      [,8]\npersonen           70.0000\nwahrscheinlichkeit  0.9992\n```\n\n\n:::\n\n```{.r .cell-code}\n# Gegenprobe durch Simulation: 20000 Gruppen zu je 23 Personen\nN <- 20000; m <- 23\ntage <- matrix(ganzzahlen(1357, N * m, 365), nrow = N, byrow = TRUE)\ntreffer <- apply(tage, 1, function(z) length(unique(z)) < m)\nround(mean(treffer), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5054\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mar = c(4, 4, 2, 1))\nplot(1:70, sapply(1:70, p_geteilt), type = \"l\", lwd = 2, ylim = c(0, 1),\n     xlab = \"Anzahl Personen\", ylab = \"P(mindestens zwei gleich)\")\nabline(h = 0.5, lty = 2); abline(v = 23, lty = 3)\n```\n\n::: {.cell-output-display}\n![Beispiel 2: Wahrscheinlichkeit für mindestens einen gemeinsamen Geburtstag.](kombinatorik-wahrscheinlichkeit_files/figure-html/fig-b2-komb-r-1.png){#fig-b2-komb-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndef p_geteilt(m):\n    p = 1.0\n    for i in range(m):\n        p *= (365 - i) / 365\n    return 1 - p\n\n\nstufen = [5, 10, 20, 23, 30, 50, 60, 70]\nprint(pd.DataFrame({\"personen\": stufen,\n                    \"wahrscheinlichkeit\": [p_geteilt(m) for m in stufen]})\n      .round(4).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         0        1        2  ...        5        6        7\npersonen            5.0000  10.0000  20.0000  ...  50.0000  60.0000  70.0000\nwahrscheinlichkeit  0.0271   0.1169   0.4114  ...   0.9704   0.9941   0.9992\n\n[2 rows x 8 columns]\n```\n\n\n:::\n\n```{.python .cell-code}\nN, m = 20000, 23\ntage = ganzzahlen(1357, N * m, 365).reshape(N, m)\ntreffer = np.array([len(np.unique(z)) < m for z in tage])\nprint(round(float(treffer.mean()), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.5053\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achse = plt.subplots(figsize=(7, 3.2))\nachse.plot(range(1, 71), [p_geteilt(m) for m in range(1, 71)], lw=2)\nachse.axhline(0.5, ls=\"--\", color=\"black\")\nachse.axvline(23, ls=\":\", color=\"black\")\nachse.set_ylim(0, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(0.0, 1.0)\n```\n\n\n:::\n\n```{.python .cell-code}\nachse.set_xlabel(\"Anzahl Personen\")\nachse.set_ylabel(\"P(mindestens zwei gleich)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselbe Kurve in Python.](kombinatorik-wahrscheinlichkeit_files/figure-html/fig-b2-komb-py-1.png){#fig-b2-komb-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Personen | 5 | 10 | 20 | **23** | 30 | 50 | 60 | 70 |\n|---|---|---|---|---|---|---|---|---|\n| Wahrscheinlichkeit | 0.027 | 0.117 | 0.411 | **0.507** | 0.706 | 0.970 | 0.994 | **0.999** |\n\nSimulation über 20 000 Gruppen zu je 23 Personen: **0.5054** (R) und\n**0.5053** (Python), eine einzige Gruppe wird unterschiedlich eingestuft,\nweil ein Zufallswert genau auf einer Tagesgrenze liegt und die beiden\n`floor`-Rundungen dort auseinandergehen.\n\n| Beobachtung | Erklärung |\n|---|---|\n| Schon bei **23** Personen ist es wahrscheinlicher als nicht | Nicht bei 180. Das ist das Überraschende an der Aufgabe. |\n| Bei 50 Personen sind es **97 Prozent** | Und bei 70 praktisch sicher. |\n| Die Rechnung geht über das **Gegenereignis** | $P = 1 - \\frac{365}{365}\\cdot\\frac{364}{365}\\cdot\\ldots$, ein Produkt statt einer Summe über alle Fälle mit genau zwei, genau drei, … gleichen Geburtstagen. |\n| Die Simulation bestätigt es | 0.5054 gegen 0.5073. Der Standardfehler beträgt hier $\\sqrt{0.25/20000} = 0.0035$. |\n\n::: {.note-box}\n**Warum die Intuition daneben liegt:** Gefragt ist nicht \"wer hat am selben Tag\nGeburtstag wie **ich**\", sondern \"gibt es **irgendein** Paar\". Bei 23 Personen\ngibt es $\\binom{23}{2} = 253$ Paare und 253 Gelegenheiten, jede mit einer\nWahrscheinlichkeit von $1/365$.\n\nDie Frage nach **einer bestimmten** Person ist eine ganz andere: Dafür bräuchte\nes 253 weitere Personen, um über 50 Prozent zu kommen.\n\n| Frage | Anzahl Gelegenheiten | benötigte Gruppengrösse |\n|---|---|---|\n| irgendein Paar gleich | $\\binom{m}{2}$ | **23** |\n| jemand hat wie **ich** Geburtstag | $m - 1$ | **253** |\n\nDieselbe Verwechslung, \"irgendwo\" gegen \"hier\", steckt hinter dem\n[multiplen Testen](../inferenz/multiples-testen.qmd): Bei zwanzig Tests findet\nman irgendwo einen signifikanten Befund, auch wenn keiner der einzelnen Tests\nauffällig wäre.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> In einer Gruppe von 23 Personen haben mit 50.7 Prozent Wahrscheinlichkeit\n> mindestens zwei am selben Tag Geburtstag. Eine Simulation über 20 000 Gruppen\n> ergibt 50.5 Prozent.\n\n### Beispiel 3: Wie sich der Anteil einpendelt\n\n#### Frage und Datenlage\n\n5 000 Würfe. Die relative Häufigkeit einer Sechs nähert sich $1/6$, aber wie,\nund was bedeutet das für die nächste Sechs?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwuerfe <- ganzzahlen(2468, 5000, 6)\nverlauf <- cumsum(wuerfe == 6) / seq_along(wuerfe)\n\nggplot(data.frame(wurf = seq_along(verlauf), anteil = verlauf),\n       aes(wurf, anteil)) +\n  geom_line(linewidth = 0.4) +\n  geom_hline(yintercept = 1 / 6, linetype = \"dashed\") +\n  coord_cartesian(ylim = c(0, 0.4)) +\n  labs(x = \"Anzahl Würfe\", y = \"relative Häufigkeit einer Sechs\")\n\nfor (k in c(10, 100, 1000, 5000)) {\n  cat(sprintf(\"nach %4d Würfen: %.4f | Abweichung %.4f | erwartete Streuung %.4f\\n\",\n              k, verlauf[k], abs(verlauf[k] - 1 / 6),\n              sqrt((1 / 6) * (5 / 6) / k)))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnach   10 Würfen: 0.3000 | Abweichung 0.1333 | erwartete Streuung 0.1179\nnach  100 Würfen: 0.2500 | Abweichung 0.0833 | erwartete Streuung 0.0373\nnach 1000 Würfen: 0.1500 | Abweichung 0.0167 | erwartete Streuung 0.0118\nnach 5000 Würfen: 0.1648 | Abweichung 0.0019 | erwartete Streuung 0.0053\n```\n\n\n:::\n\n```{.r .cell-code}\n# Die laengste Serie ohne Sechs\nlaeufe <- rle(wuerfe == 6)\nmax(laeufe$lengths[!laeufe$values])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 34\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(p_zehn_ohne_sechs = (5 / 6)^10), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np_zehn_ohne_sechs \n           0.1615 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: relative Häufigkeit einer Sechs über 5000 Würfe.](kombinatorik-wahrscheinlichkeit_files/figure-html/fig-b3-komb-r-3.png){#fig-b3-komb-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nwuerfe = ganzzahlen(2468, 5000, 6)\nverlauf = np.cumsum(wuerfe == 6) / np.arange(1, len(wuerfe) + 1)\n\nfig, achse = plt.subplots(figsize=(7, 3.2))\nachse.plot(np.arange(1, len(verlauf) + 1), verlauf, lw=0.5)\nachse.axhline(1 / 6, ls=\"--\", color=\"black\")\nachse.set_ylim(0, 0.4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(0.0, 0.4)\n```\n\n\n:::\n\n```{.python .cell-code}\nachse.set_xlabel(\"Anzahl Würfe\")\nachse.set_ylabel(\"relative Häufigkeit einer Sechs\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: derselbe Verlauf in Python.](kombinatorik-wahrscheinlichkeit_files/figure-html/fig-b3-komb-py-1.png){#fig-b3-komb-py width=100%}\n:::\n\n```{.python .cell-code}\nfor k in [10, 100, 1000, 5000]:\n    print(f\"nach {k:4d} Würfen: {verlauf[k-1]:.4f}\"\n          f\" | Abweichung {abs(verlauf[k-1] - 1/6):.4f}\"\n          f\" | erwartete Streuung {np.sqrt((1/6) * (5/6) / k):.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnach   10 Würfen: 0.3000 | Abweichung 0.1333 | erwartete Streuung 0.1179\nnach  100 Würfen: 0.2500 | Abweichung 0.0833 | erwartete Streuung 0.0373\nnach 1000 Würfen: 0.1500 | Abweichung 0.0167 | erwartete Streuung 0.0118\nnach 5000 Würfen: 0.1648 | Abweichung 0.0019 | erwartete Streuung 0.0053\n```\n\n\n:::\n\n```{.python .cell-code}\nlaenge, aktuell = 0, 0\nfor wert in wuerfe:\n    aktuell = 0 if wert == 6 else aktuell + 1\n    laenge = max(laenge, aktuell)\nprint(\"längste Serie ohne Sechs:\", laenge)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlängste Serie ohne Sechs: 34\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"P(zehn Würfe ohne Sechs):\", round((5 / 6) ** 10, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nP(zehn Würfe ohne Sechs): 0.1615\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| nach … Würfen | relative Häufigkeit | Abweichung von $1/6$ | erwartete Streuung $\\sqrt{pq/n}$ |\n|---|---|---|---|\n| 10 | 0.3000 | **0.1333** | 0.1179 |\n| 100 | 0.2500 | **0.0833** | 0.0373 |\n| 1 000 | 0.1500 | 0.0167 | 0.0118 |\n| 5 000 | **0.1648** | **0.0019** | 0.0053 |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die Abweichung sinkt von 0.133 auf 0.002 | Und zwar ungefähr wie $1/\\sqrt{n}$, die Spalte rechts zeigt die theoretische Streuung, die dieselbe Grössenordnung hat. |\n| Bei 100 Würfen liegt die Abweichung noch bei **0.083** | Das ist die Hälfte des wahren Werts. Wer aus hundert Würfen auf die Fairness eines Würfels schliessen will, hat wenig in der Hand. |\n| Die **längste Serie ohne Sechs** dauert **34 Würfe** | In 5 000 Würfen. Solche Serien sind normal, nicht auffällig. |\n| Zehn Würfe ohne Sechs haben die Wahrscheinlichkeit **0.1615** | Also in etwa jeder sechsten Zehnerserie. |\n\n::: {.note-box}\n**Was die Kurve nicht zeigt, und das ist der Punkt:** Sie erreicht den Wert nie\nendgültig und kehrt auch nicht zu ihm zurück, weil eine Serie ohne Sechsen\nspäter \"ausgeglichen\" würde. Diese Vorstellung ist der **Spielerfehlschluss**.\n\nDer Würfel hat kein Gedächtnis. Was geschieht, ist etwas anderes: Eine\nAbweichung von 5 Sechsen zu wenig wiegt bei 100 Würfen 5 Prozentpunkte und bei\n5 000 Würfen ein Zehntel davon. **Die Abweichung verschwindet nicht, sie\nverliert an Gewicht.**\n\nRechnerisch: Die absolute Abweichung der **Anzahl** wächst mit $\\sqrt{n}$, die\nder **relativen Häufigkeit** sinkt mit $1/\\sqrt{n}$. Beides zugleich.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Nach 5 000 Würfen liegt der beobachtete Anteil bei 0.1648 gegenüber dem\n> erwarteten 0.1667. Die Abweichung sinkt mit der Wurzel der Wurfzahl; einzelne\n> Serien von bis zu 34 Würfen ohne Sechs treten dabei auf und sind unauffällig.\n\n### Beispiel 4: Additionssatz und die doppelt gezählte Sechs\n\n#### Frage und Datenlage\n\nBeim Würfel: $A$ = gerade Zahl, $B$ = Zahl grösser als vier. Wie wahrscheinlich\nist $A$ **oder** $B$?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\naugen <- 1:6\n\np_a <- mean(augen %% 2 == 0)        # 2, 4, 6\np_b <- mean(augen > 4)              # 5, 6\np_ab <- mean(augen %% 2 == 0 & augen > 4)   # nur die 6\n\nround(c(p_a = p_a, p_b = p_b, p_schnitt = p_ab,\n        korrekt = p_a + p_b - p_ab,\n        ohne_abzug = p_a + p_b,\n        abgezaehlt = mean(augen %% 2 == 0 | augen > 4)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       p_a        p_b  p_schnitt    korrekt ohne_abzug abgezaehlt \n    0.5000     0.3333     0.1667     0.6667     0.8333     0.6667 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Welche Augenzahlen gehoeren dazu?\naugen[augen %% 2 == 0 | augen > 4]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2 4 5 6\n```\n\n\n:::\n\n```{.r .cell-code}\n# Ein disjunkter Fall zum Vergleich: gerade oder gleich 5\nround(c(disjunkt_summe = mean(augen %% 2 == 0) + mean(augen == 5),\n        disjunkt_abgezaehlt = mean(augen %% 2 == 0 | augen == 5)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     disjunkt_summe disjunkt_abgezaehlt \n             0.6667              0.6667 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\naugen = np.arange(1, 7)\n\np_a = float((augen % 2 == 0).mean())\np_b = float((augen > 4).mean())\np_ab = float(((augen % 2 == 0) & (augen > 4)).mean())\n\nprint({\"p_a\": round(p_a, 4), \"p_b\": round(p_b, 4),\n       \"p_schnitt\": round(p_ab, 4),\n       \"korrekt\": round(p_a + p_b - p_ab, 4),\n       \"ohne_abzug\": round(p_a + p_b, 4),\n       \"abgezaehlt\": round(float(((augen % 2 == 0) | (augen > 4)).mean()), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'p_a': 0.5, 'p_b': 0.3333, 'p_schnitt': 0.1667, 'korrekt': 0.6667, 'ohne_abzug': 0.8333, 'abgezaehlt': 0.6667}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(augen[(augen % 2 == 0) | (augen > 4)])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[2 4 5 6]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"disjunkt_summe\": round(float((augen % 2 == 0).mean()\n                                     + (augen == 5).mean()), 4),\n       \"disjunkt_abgezaehlt\": round(float(((augen % 2 == 0)\n                                           | (augen == 5)).mean()), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'disjunkt_summe': 0.6667, 'disjunkt_abgezaehlt': 0.6667}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | Wert | Welche Augenzahlen |\n|---|---|---|\n| $P(A)$, gerade | **0.5000** | 2, 4, 6 |\n| $P(B)$, grösser 4 | **0.3333** | 5, 6 |\n| $P(A \\cap B)$ | **0.1667** | nur die 6 |\n| $P(A) + P(B) - P(A \\cap B)$ | **0.6667** | 2, 4, 5, 6 |\n| $P(A) + P(B)$ **ohne** Abzug | **0.8333** |   |\n| abgezählt | **0.6667** | vier von sechs |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die Vereinigung enthält **vier** Augenzahlen | 2, 4, 5 und 6. Also $4/6 = 0.667$, wie die Formel sagt. |\n| Ohne Abzug kommt **0.833** heraus | Die Sechs wurde zweimal gezählt, einmal als gerade und einmal als grösser vier. |\n| Beim disjunkten Paar stimmt die einfache Summe | \"gerade oder gleich 5\": $0.5 + 0.1667 = 0.6667$, abgezählt ebenso. Dort ist $P(A \\cap B) = 0$. |\n\n::: {.note-box}\n**Die Verallgemeinerung heisst Siebformel und wird schnell unhandlich.** Bei drei\nEreignissen:\n\n$$P(A \\cup B \\cup C) = \\sum P(A) - \\sum P(A \\cap B) + P(A \\cap B \\cap C)$$\n\nAlso: Einzelne addieren, Paare abziehen, Dreifachschnitt wieder addieren. Bei\n$k$ Ereignissen sind es $2^k - 1$ Terme mit wechselnden Vorzeichen.\n\n**Deshalb rechnet man ab drei Ereignissen praktisch immer über das\nGegenereignis**, Beispiel 5 zeigt, wie stark der Unterschied ist.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Wahrscheinlichkeit für eine gerade Zahl oder eine Zahl über vier beträgt\n> 2/3. Die einfache Summe der Einzelwahrscheinlichkeiten ergäbe 5/6, weil die\n> Sechs zu beiden Ereignissen gehört und doppelt gezählt würde.\n\n### Beispiel 5: Das Gegenereignis\n\n#### Frage und Datenlage\n\nWie wahrscheinlich ist mindestens eine Sechs bei $n$ Würfen? Der direkte Weg\nsummiert über \"genau eine\", \"genau zwei\", …, der Umweg braucht eine Potenz.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(rbind(wuerfe = c(1, 2, 3, 6, 10, 25),\n            mindestens_eine_sechs = 1 - (5 / 6)^c(1, 2, 3, 6, 10, 25)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        [,1]   [,2]   [,3]   [,4]    [,5]    [,6]\nwuerfe                1.0000 2.0000 3.0000 6.0000 10.0000 25.0000\nmindestens_eine_sechs 0.1667 0.3056 0.4213 0.6651  0.8385  0.9895\n```\n\n\n:::\n\n```{.r .cell-code}\n# Der direkte Weg bei drei Wuerfen: ueber die Binomialverteilung\nround(c(genau_eine = dbinom(1, 3, 1 / 6),\n        genau_zwei = dbinom(2, 3, 1 / 6),\n        genau_drei = dbinom(3, 3, 1 / 6),\n        summe = sum(dbinom(1:3, 3, 1 / 6)),\n        gegenereignis = 1 - (5 / 6)^3), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   genau_eine    genau_zwei    genau_drei         summe gegenereignis \n       0.3472        0.0694        0.0046        0.4213        0.4213 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Gegenprobe durch Simulation\nversuche <- matrix(ganzzahlen(3690, 3 * 100000, 6), ncol = 3, byrow = TRUE)\nround(mean(apply(versuche, 1, function(z) any(z == 6))), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4208\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mar = c(4, 4, 2, 1))\nplot(1:30, 1 - (5 / 6)^(1:30), type = \"b\", pch = 16, ylim = c(0, 1),\n     xlab = \"Anzahl Würfe\", ylab = \"P(mindestens eine Sechs)\")\nabline(h = 0.5, lty = 2)\n```\n\n::: {.cell-output-display}\n![Beispiel 5: Wahrscheinlichkeit für mindestens eine Sechs, nach Anzahl Würfe.](kombinatorik-wahrscheinlichkeit_files/figure-html/fig-b5-komb-r-1.png){#fig-b5-komb-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom scipy import stats\n\nanzahl = np.array([1, 2, 3, 6, 10, 25])\nprint(pd.DataFrame({\"wuerfe\": anzahl,\n                    \"mindestens_eine_sechs\": 1 - (5 / 6) ** anzahl})\n      .round(4).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                            0       1       2       3        4        5\nwuerfe                 1.0000  2.0000  3.0000  6.0000  10.0000  25.0000\nmindestens_eine_sechs  0.1667  0.3056  0.4213  0.6651   0.8385   0.9895\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"genau_eine\": round(float(stats.binom.pmf(1, 3, 1 / 6)), 4),\n       \"genau_zwei\": round(float(stats.binom.pmf(2, 3, 1 / 6)), 4),\n       \"genau_drei\": round(float(stats.binom.pmf(3, 3, 1 / 6)), 4),\n       \"summe\": round(float(stats.binom.pmf([1, 2, 3], 3, 1 / 6).sum()), 4),\n       \"gegenereignis\": round(1 - (5 / 6) ** 3, 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'genau_eine': 0.3472, 'genau_zwei': 0.0694, 'genau_drei': 0.0046, 'summe': 0.4213, 'gegenereignis': 0.4213}\n```\n\n\n:::\n\n```{.python .cell-code}\nversuche = ganzzahlen(3690, 3 * 100000, 6).reshape(100000, 3)\nprint(round(float((versuche == 6).any(axis=1).mean()), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.4208\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achse = plt.subplots(figsize=(7, 3))\nschritte = np.arange(1, 31)\nachse.plot(schritte, 1 - (5 / 6) ** schritte, \"o-\", ms=4)\nachse.axhline(0.5, ls=\"--\", color=\"black\")\nachse.set_ylim(0, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(0.0, 1.0)\n```\n\n\n:::\n\n```{.python .cell-code}\nachse.set_xlabel(\"Anzahl Würfe\")\nachse.set_ylabel(\"P(mindestens eine Sechs)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselbe Kurve in Python.](kombinatorik-wahrscheinlichkeit_files/figure-html/fig-b5-komb-py-1.png){#fig-b5-komb-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Würfe | 1 | 2 | 3 | 6 | 10 | 25 |\n|---|---|---|---|---|---|---|\n| $P(\\text{mindestens eine Sechs})$ | 0.1667 | 0.3056 | **0.4213** | **0.6651** | 0.8385 | 0.9895 |\n\nUnd der Vergleich der beiden Wege bei drei Würfen:\n\n| Weg | Rechnung | Ergebnis |\n|---|---|---|\n| **direkt** | 0.3472 + 0.0694 + 0.0046 | **0.4213** |\n| **Gegenereignis** | $1 - (5/6)^3$ | **0.4213** |\n| Simulation (100 000 Versuche) | | **0.4208** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Beide Wege ergeben dasselbe | Wie sie müssen. Der direkte braucht drei Terme, der andere einen. |\n| Bei zehn Würfen wären es **zehn** Terme | Und bei 25 Würfen 25. Die Ersparnis wächst mit $n$. |\n| Bei **sechs** Würfen liegt die Wahrscheinlichkeit bei 0.665, nicht bei 1 | Der naheliegende Fehlschluss \"sechs Würfe, Wahrscheinlichkeit $6 \\cdot 1/6 = 1$\" addiert nicht disjunkte Ereignisse. Die Fälle mit mehreren Sechsen werden dabei mehrfach gezählt. |\n| Die Kurve steigt **nie auf genau 1** | $(5/6)^n$ wird beliebig klein, aber nie null. Bei 25 Würfen fehlt noch ein Prozent. |\n\n::: {.note-box}\n**Woran man erkennt, dass das Gegenereignis der richtige Weg ist:** an den\nWörtern \"mindestens\", \"wenigstens\" und \"irgendein\". Ihr Gegenteil ist immer ein\neinziger Fall, \"keiner\", und bei unabhängigen Versuchen ist dessen\nWahrscheinlichkeit ein Produkt.\n\n| Formulierung | Gegenereignis | Rechnung |\n|---|---|---|\n| mindestens ein Treffer | kein Treffer | $1 - (1-p)^n$ |\n| mindestens zwei Treffer | keiner **oder** genau einer | $1 - (1-p)^n - n p (1-p)^{n-1}$ |\n| alle Treffer | mindestens einer daneben | $p^n$ direkt einfacher |\n\nAb \"mindestens zwei\" verliert der Trick seinen Vorteil, dann ist die\n[Binomialverteilung](diskrete-verteilungen.qmd) das passende Werkzeug.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Wahrscheinlichkeit für mindestens eine Sechs beträgt bei drei Würfen\n> 42.1 Prozent, gerechnet als $1 - (5/6)^3$. Eine Simulation über 100 000\n> Versuche ergibt 42.1 Prozent.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEin Zahlenschloss hat vier Ringe mit je zehn Ziffern. Wie viele Einstellungen\ngibt es?\n\n- [x] Zehntausend ~ Richtig, also zehn hoch vier. Jede Ziffer darf mehrfach\n      vorkommen und die Position zählt, es wird also mit Zurücklegen und mit\n      Anordnung gezogen.\n- [ ] 5040, also 10 mal 9 mal 8 mal 7 ~ Das wäre ohne Zurücklegen. Ein\n      Zahlenschloss erlaubt aber 1111.\n- [ ] 210, also 10 über 4 ~ Das wäre ohne Zurücklegen und ohne Anordnung. Bei\n      einem Schloss ist die Reihenfolge gerade entscheidend.\n:::\n\n::: {.quiz}\nWarum ist die Zahl der Lottoziehungen 49 über 6 und nicht das Produkt\n49 mal 48 mal 47 mal 46 mal 45 mal 44?\n\n- [ ] Weil Kugeln zurückgelegt werden ~ Sie werden gerade nicht zurückgelegt,\n      deshalb sinken die Faktoren.\n- [x] Weil die Reihenfolge der gezogenen Kugeln keine Rolle spielt ~ Richtig.\n      Das Produkt zählt jede Auswahl so oft, wie sie sich anordnen lässt, also\n      sechs Fakultät mal zu häufig. Der Binomialkoeffizient teilt das heraus.\n- [ ] Weil das Produkt zu gross zum Rechnen wäre ~ Rechnen liesse es sich\n      problemlos, es beantwortet nur eine andere Frage.\n:::\n\n::: {.quiz}\nIn einer Gruppe von 23 Personen haben mit über 50 Prozent Wahrscheinlichkeit\nzwei am selben Tag Geburtstag. Warum wirkt das überraschend?\n\n- [x] Weil man an die eigene Person denkt statt an alle Paare ~ Richtig. Bei 23\n      Personen gibt es 253 Paare. Die Frage \"hat jemand wie ich Geburtstag\"\n      bräuchte 253 Personen für dieselbe Wahrscheinlichkeit.\n- [ ] Weil die Rechnung falsch ist ~ Sie lässt sich über das Gegenereignis\n      exakt nachvollziehen, und eine Simulation über 20 000 Gruppen bestätigt sie.\n- [ ] Weil Geburtstage nicht gleichverteilt sind ~ Das stimmt zwar, macht die\n      Wahrscheinlichkeit aber sogar noch etwas grösser.\n:::\n\n::: {.quiz}\nZehn Würfe brachten keine Sechs. Ist die nächste Sechs jetzt wahrscheinlicher?\n\n- [ ] Ja, der Ausgleich ist fällig ~ Das ist der Spielerfehlschluss. Der Würfel\n      hat kein Gedächtnis.\n- [x] Nein, die Wahrscheinlichkeit bleibt bei einem Sechstel ~ Richtig. Was\n      sich ausgleicht, ist der Anteil, und zwar nicht durch Gegenbewegung,\n      sondern weil frühe Abweichungen gegenüber der wachsenden Gesamtzahl an\n      Gewicht verlieren. In 5 000 Würfen trat eine Serie von 34 Würfen ohne\n      Sechs auf.\n- [ ] Nein, sie ist sogar kleiner, der Würfel ist wohl unfair ~ Zehn Würfe ohne\n      Sechs haben eine Wahrscheinlichkeit von 16.2 Prozent und sind damit\n      unauffällig.\n:::\n\n::: {.quiz}\nWie wahrscheinlich ist mindestens eine Sechs beim Wurf zweier Würfel?\n\n- [ ] 2 von 6, also ein Drittel ~ Das addiert die beiden Einzelwahrscheinlich-\n      keiten und zählt den Fall zweier Sechsen doppelt.\n- [x] 11 von 36 ~ Richtig, über das Gegenereignis eins minus fünf Sechstel zum\n      Quadrat, also 0.3056. Der Additionssatz kommt auf dasselbe, wenn man den\n      Überschneidungsteil abzieht.\n- [ ] 1 von 36 ~ Das ist die Wahrscheinlichkeit für zwei Sechsen, nicht für\n      mindestens eine.\n:::\n\n::: {.quiz}\nBei sechs Würfen beträgt die Wahrscheinlichkeit für mindestens eine Sechs\n66.5 Prozent und nicht 100 Prozent. Warum?\n\n- [x] Weil sechsmal ein Sechstel nur addiert werden dürfte, wenn die Ereignisse\n      disjunkt wären ~ Richtig. Die Fälle mit mehreren Sechsen würden dabei\n      mehrfach gezählt. Korrekt ist eins minus fünf Sechstel hoch sechs.\n- [ ] Weil der Würfel nicht fair ist ~ Er ist fair; die Rechnung ist der Fehler.\n- [ ] Weil sechs Würfe zu wenige sind ~ Auch bei 25 Würfen bleibt die\n      Wahrscheinlichkeit unter eins, nämlich bei 98.95 Prozent.\n:::\n\n## Verlinkte Ressourcen\n\n- [OpenIntro Statistics, Kapitel zur Wahrscheinlichkeit](https://www.openintro.org/book/os/)\n- [Bedingte Wahrscheinlichkeit und Bayes](bedingte-wahrscheinlichkeit-bayes.qmd)\n- [Diskrete Verteilungen](diskrete-verteilungen.qmd)\n",
    "supporting": [
      "kombinatorik-wahrscheinlichkeit_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}