{
  "hash": "8f9a67edbfd3c65204140915121b22e5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Bootstrap und Resampling\"\ndescription: \"Konfidenzintervalle ohne Verteilungsannahme, auch für Kennzahlen ohne Formel.\"\ncategories: [\"Konfidenzintervall\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: methode\nstand: entwurf\norder: 70\n---\n\n\n\n\n\nDer Bootstrap zieht zufällig, und Zufallszahlen unterscheiden sich zwischen R\nund Python. Damit die Zahlen auf dieser Seite in beiden Sprachen\nübereinstimmen, kommt ein einfacher Generator zum Einsatz, der in beiden gleich\nrechnet. In der Praxis nimmt man die eingebauten Generatoren und setzt einen\nSeed.\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Wie unsicher ist eine Kennzahl, wenn keine Formel dafür existiert oder ihre Voraussetzungen verletzt sind? |\n| Eingang | eine Stichprobe und eine beliebige Kennzahl |\n| Was die Methode liefert | Standardfehler, Konfidenzintervall und die ganze Verteilung der Kennzahl |\n| R-Funktion | von Hand mit `sample()`, oder `boot::boot()` und `boot::boot.ci()` |\n| Python-Funktion | von Hand mit `np.random.choice()`, oder `scipy.stats.bootstrap()` |\n| Verwandte Methoden | [Schätzen und Konfidenzintervalle](schaetzen-konfidenzintervalle.qmd), [nichtparametrische Tests](../tests/nichtparametrische-tests.qmd) |\n\n## Wann diese Methode, wann nicht\n\nDer Bootstrap ist die Antwort auf zwei Fragen, für die die klassische Statistik\nkeine gute hat.\n\n**Erstens: Kennzahlen ohne Formel.** Für den Mittelwert gibt es einen\nStandardfehler, für den Median, den getrimmten Mittelwert, ein Verhältnis\nzweier Grössen oder den Unterschied zweier Korrelationen nicht ohne Weiteres.\nDer Bootstrap liefert ihn für jede Kennzahl, die sich ausrechnen lässt.\n\n**Zweitens: verletzte Verteilungsannahmen.** Bei stark schiefen Daten ist das\nt-Intervall symmetrisch, obwohl die Verteilung des Mittelwerts es nicht ist. Der\nBootstrap bildet die Schiefe ab, siehe Beispiel 1.\n\n| Situation | Stattdessen |\n|---|---|\n| Voraussetzungen erfüllt, Kennzahl mit Formel | das klassische [Konfidenzintervall](schaetzen-konfidenzintervalle.qmd); es ist schneller und braucht keinen Zufall |\n| Sehr kleine Stichprobe | kein Bootstrap; er kann nur wiederverwenden, was vorhanden ist, siehe Beispiel 4 |\n| Es geht um extreme Quantile oder das Maximum | ungeeignet, aus demselben Grund |\n| Abhängige Daten, etwa Zeitreihen | Blockbootstrap statt gewöhnlichem Ziehen |\n| Es geht um einen Test statt um ein Intervall | Permutationstest, ein verwandtes Verfahren mit anderer Ziehung |\n\n## Grundidee und Modell\n\nDie klassische Statistik fragt: Wie würde meine Kennzahl schwanken, wenn ich die\nErhebung viele Male wiederholte? Beantwortet wird das über eine\nVerteilungsannahme und eine Formel.\n\nDer Bootstrap beantwortet dieselbe Frage anders: Er behandelt die vorliegende\nStichprobe als Ersatz für die Grundgesamtheit und zieht daraus wiederholt neue\nStichproben, **mit Zurücklegen** und in derselben Grösse.\n\n| Schritt | Was passiert |\n|---|---|\n| 1 | Aus den $n$ Werten werden $n$ Werte mit Zurücklegen gezogen. Manche kommen mehrfach vor, andere gar nicht. |\n| 2 | Für diese Ziehung wird die Kennzahl berechnet. |\n| 3 | Schritte 1 und 2 werden $B$-mal wiederholt, üblicherweise 1000 bis 10 000 Mal. |\n| 4 | Die $B$ Werte bilden die Bootstrap-Verteilung der Kennzahl. |\n| 5 | Ihre Standardabweichung ist der Standardfehler, ihre Quantile ergeben das Intervall. |\n\nDas Zurücklegen ist wesentlich: Ohne es wäre jede Ziehung identisch mit der\nAusgangsstichprobe. Im Mittel enthält eine Bootstrap-Ziehung rund 63 Prozent der\nursprünglichen Werte, den Rest mehrfach.\n\n::: {.note-box}\n**Die entscheidende Annahme** lautet: Die Stichprobe ist repräsentativ für die\nGrundgesamtheit. Der Bootstrap ersetzt die Verteilungsannahme durch diese\nAnnahme, er macht das Verfahren also nicht voraussetzungsfrei, sondern tauscht\neine Voraussetzung gegen eine andere.\n\nDaraus folgt unmittelbar seine Grenze: Was in der Stichprobe nicht vorkommt,\nkann er nicht erfinden. Bei kleinen Stichproben ist diese Grenze eng, siehe\nBeispiel 4.\n:::\n\n### Die Intervallvarianten\n\n| Variante | Wie sie rechnet | Wann |\n|---|---|---|\n| Perzentil | die 2.5- und 97.5-Prozent-Quantile der Bootstrap-Verteilung | einfach, verständlich, für die meisten Fälle ausreichend |\n| Basic | spiegelt die Quantile am beobachteten Wert | wenn die Verzerrung gering ist |\n| BCa | korrigiert Verzerrung und Schiefe | die genaueste Variante, in `boot.ci()` und `scipy.stats.bootstrap()` enthalten |\n| Studentisiert | verwendet einen bootstrapten Standardfehler je Ziehung | am genauesten, aber rechenaufwendig |\n\nAuf dieser Seite steht das Perzentilintervall im Vordergrund, weil sich daran\ndas Verfahren am besten erklären lässt. Für einen Bericht ist BCa vorzuziehen.\n\n## Output lesen\n\n| Grösse | Was sie sagt | Falle |\n|---|---|---|\n| Bootstrap-Standardfehler | Standardabweichung der $B$ Kennzahlwerte | ersetzt die Formel, nicht die Interpretation |\n| Verzerrung (bias) | Bootstrap-Mittel minus beobachteter Wert | kleine Werte sind normal; grosse deuten auf eine ungeeignete Kennzahl oder zu wenig Daten |\n| Perzentilintervall | Quantile der Bootstrap-Verteilung | bei starker Verzerrung zu optimistisch |\n| $B$ | Anzahl Wiederholungen | zu klein macht das Ergebnis vom Zufall abhängig, siehe Beispiel 3 |\n| Seed | Startwert des Generators | gehört ins Protokoll, sonst ist das Ergebnis nicht reproduzierbar |\n\n## Interpretationsfallen\n\n- **Der Bootstrap erzeugt keine neuen Daten.** Er nutzt die vorhandenen\n  mehrfach. Bei acht Beobachtungen bleibt es bei acht verschiedenen Werten.\n- **Er repariert keine verzerrte Stichprobe.** Ist die Erhebung schief, ist es\n  das Ergebnis auch.\n- **Er ist bei kleinem n nicht besser als die Formel**, oft schlechter.\n- **Das Intervall hängt vom Seed ab.** Bei zu kleinem $B$ merklich, siehe\n  Beispiel 3.\n- **Für Maxima und extreme Quantile ist er ungeeignet**, weil die\n  Bootstrap-Verteilung den beobachteten Wertebereich nie verlässt.\n- **Bei abhängigen Daten braucht es einen Blockbootstrap.** Gewöhnliches Ziehen\n  zerstört die zeitliche Struktur und liefert zu schmale Intervalle.\n\n## Ergebnis berichten\n\n> Für [Kennzahl] ergibt sich [Wert] (95-Prozent-Bootstrap-Konfidenzintervall\n> [unten] bis [oben], Perzentilmethode, B = [Anzahl] Ziehungen, Seed [Wert]).\n\nGenannt werden: die Kennzahl, die Intervallvariante, $B$, der Seed und der\nGrund, warum der Bootstrap statt einer Formel verwendet wurde. Die letzten\nbeiden fehlen am häufigsten.\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt Bootstrap |\n|---|---|\n| [Konfidenzintervall](schaetzen-konfidenzintervalle.qmd) | Kennzahl mit Formel und erfüllten Voraussetzungen |\n| [Nichtparametrische Tests](../tests/nichtparametrische-tests.qmd) | es geht um einen Test, nicht um ein Intervall |\n| Permutationstest | Test ohne Verteilungsannahme; zieht ohne Zurücklegen und vertauscht Gruppenzugehörigkeiten |\n| Kreuzvalidierung | es geht um Vorhersagegüte, siehe [Modellauswahl](../regression/modellauswahl.qmd) |\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Der Mittelwert bei schiefen Daten\n\n#### Frage und Datenlage\n\nVierzig Wartezeiten in Minuten, deutlich rechtsschief: Der Median liegt bei 5.7\nMinuten, der Mittelwert bei 12.3, der grösste Wert bei 78.3. Gesucht ist ein\nKonfidenzintervall für den Mittelwert.\n\n#### Voraussetzungen prüfen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nhist(warten, breaks = 12, col = \"grey85\", main = \"Wartezeiten\",\n     xlab = \"Minuten\")\nqqnorm(warten, main = \"QQ-Plot\"); qqline(warten)\npar(mfrow = c(1, 1))\n\nround(c(n = length(warten), mittel = mean(warten), median = median(warten),\n        sd = sd(warten)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     n mittel median     sd \n40.000 12.295  5.700 16.389 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 1: die rechtsschiefe Verteilung der Wartezeiten.](bootstrap-resampling_files/figure-html/fig-b1-boot-r-1.png){#fig-b1-boot-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport statsmodels.api as sm\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nachsen[0].hist(warten, bins=12, color=\"0.8\", edgecolor=\"0.3\")\nachsen[0].set_title(\"Wartezeiten\")\nachsen[0].set_xlabel(\"Minuten\")\nsm.qqplot(warten, line=\"s\", ax=achsen[1])\nachsen[1].set_title(\"QQ-Plot\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Darstellung in Python.](bootstrap-resampling_files/figure-html/fig-b1-boot-py-1.png){#fig-b1-boot-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(\"n =\", len(warten), \" Mittel =\", round(warten.mean(), 4),\n      \" Median =\", round(np.median(warten), 4),\n      \" SD =\", round(warten.std(ddof=1), 4),\n      \" Schiefe =\", round(stats.skew(warten, bias=False), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 40  Mittel = 12.295  Median = 5.7  SD = 16.389  Schiefe = 2.5706\n```\n\n\n:::\n:::\n\n\n:::\n\nDie Schiefe beträgt 2.57, der Mittelwert liegt mehr als doppelt so hoch wie der\nMedian, und der QQ-Plot biegt am oberen Ende weit von der Geraden ab. Bei 40\nBeobachtungen wirkt der zentrale Grenzwertsatz zwar schon, aber nicht so weit,\ndass die Verteilung des Mittelwerts symmetrisch wäre.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nB <- 2000\nzieh <- ziehungen(warten, B)\nmittel_boot <- rowMeans(zieh)\n\npar(mar = c(4, 4, 3, 1))\nhist(mittel_boot, breaks = 40, col = \"grey85\",\n     main = \"Bootstrap-Verteilung des Mittelwerts\", xlab = \"Minuten\")\nabline(v = mean(warten), lwd = 2, col = \"steelblue\")\nabline(v = quantile(mittel_boot, c(0.025, 0.975)), lty = 2, col = \"firebrick\")\n\nround(c(beobachtet = mean(warten),\n        boot_mittel = mean(mittel_boot),\n        verzerrung = mean(mittel_boot) - mean(warten),\n        boot_se = sd(mittel_boot)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n beobachtet boot_mittel  verzerrung     boot_se \n    12.2950     12.1596     -0.1354      2.5436 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(quantile(mittel_boot, c(0.025, 0.975)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   2.5%   97.5% \n 7.8073 17.7205 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Zum Vergleich das klassische t-Intervall\nround(t.test(warten)$conf.int, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  7.0535 17.5365\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 1: die Bootstrap-Verteilung des Mittelwerts.](bootstrap-resampling_files/figure-html/fig-b2-boot-r-3.png){#fig-b2-boot-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nB = 2000\nzieh = ziehungen(warten, B)\nmittel_boot = zieh.mean(axis=1)\n\nfig, achse = plt.subplots(figsize=(7, 3.4))\nachse.hist(mittel_boot, bins=40, color=\"0.85\", edgecolor=\"0.4\")\nachse.axvline(warten.mean(), linewidth=2, color=\"steelblue\")\nfor q in np.percentile(mittel_boot, [2.5, 97.5]):\n    achse.axvline(q, linestyle=\"--\", color=\"firebrick\")\nachse.set_title(\"Bootstrap-Verteilung des Mittelwerts\")\nachse.set_xlabel(\"Minuten\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Verteilung in Python.](bootstrap-resampling_files/figure-html/fig-b2-boot-py-1.png){#fig-b2-boot-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(\"beobachtet =\", round(warten.mean(), 4),\n      \" Bootstrap-Mittel =\", round(mittel_boot.mean(), 4),\n      \" Verzerrung =\", round(mittel_boot.mean() - warten.mean(), 4),\n      \" Bootstrap-SE =\", round(mittel_boot.std(ddof=1), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbeobachtet = 12.295  Bootstrap-Mittel = 12.1596  Verzerrung = -0.1354  Bootstrap-SE = 2.5436\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Perzentilintervall:\", np.percentile(mittel_boot, [2.5, 97.5]).round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPerzentilintervall: [ 7.8073 17.7205]\n```\n\n\n:::\n\n```{.python .cell-code}\nse = warten.std(ddof=1) / np.sqrt(len(warten))\ntk = stats.t.ppf(0.975, len(warten) - 1)\nprint(\"t-Intervall:       \",\n      np.round([warten.mean() - tk * se, warten.mean() + tk * se], 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt-Intervall:        [ 7.0535 17.5365]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| beobachteter Mittelwert | 12.295 | |\n| Bootstrap-Mittel | 12.160 | Der Mittelwert der 2000 Ziehungen. |\n| Verzerrung | -0.135 | Bootstrap-Mittel minus beobachteter Wert. Klein gegenüber dem Standardfehler von 2.54, also unbedenklich. |\n| Bootstrap-Standardfehler | 2.544 | Zum Vergleich: die Formel liefert $s/\\sqrt{n}$ = 16.389/6.325 = 2.591. Die beiden liegen nah beieinander. |\n| Perzentilintervall | 7.807 bis 17.721 | |\n| t-Intervall | 7.054 bis 17.537 | |\n\nDer aufschlussreiche Vergleich steht in den letzten beiden Zeilen. Beide\nIntervalle sind ähnlich breit, aber verschieden **platziert**:\n\n| | untere Grenze | obere Grenze | Abstand nach unten | Abstand nach oben |\n|---|---|---|---|---|\n| t-Intervall | 7.054 | 17.537 | -5.241 | +5.241 |\n| Bootstrap | 7.807 | 17.721 | -4.488 | +5.426 |\n\nDas t-Intervall ist **exakt symmetrisch**, weil die Formel es so konstruiert.\nDas Bootstrap-Intervall ist es nicht: Es reicht 4.49 Minuten nach unten und 5.43\nnach oben. Genau das erwartet man bei rechtsschiefen Daten, denn der Mittelwert\nkann durch einzelne grosse Werte weiter nach oben als nach unten wandern.\n\n#### Interpretation und Ergebnissatz\n\nDer Bootstrap bildet hier eine Eigenschaft ab, die die Formel gar nicht abbilden\nkann. Bei n = 40 ist der Unterschied noch moderat; bei n = 15 wäre er\nerheblich, und dann wäre das t-Intervall an der unteren Grenze deutlich zu\nweit.\n\nZugleich zeigt der Vergleich, dass die Formel nicht falsch ist: Die\nStandardfehler stimmen fast überein (2.54 gegen 2.59). Der Gewinn liegt in der\nForm des Intervalls, nicht in seiner Breite.\n\n> Die mittlere Wartezeit beträgt 12.3 Minuten (95-Prozent-Bootstrap-Konfidenz-\n> intervall 7.8 bis 17.7 Minuten, Perzentilmethode, B = 2000). Der Bootstrap\n> wurde wegen der deutlichen Rechtsschiefe (Schiefe 2.57) verwendet; das\n> klassische t-Intervall wäre mit 7.1 bis 17.5 symmetrisch und würde die\n> Schiefe der Verteilung nicht abbilden.\n\n### Beispiel 2: Kennzahlen ohne Formel\n\n#### Frage und Datenlage\n\nFür den Median gibt es keinen einfachen Standardfehler, für den getrimmten\nMittelwert ebenso wenig. Der Bootstrap braucht keine Formel, sondern nur eine\nRechenvorschrift.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkennzahlen <- list(\n  Mittelwert = function(m) rowMeans(m),\n  Median = function(m) apply(m, 1, median),\n  \"getrimmt 10%\" = function(m) apply(m, 1, mean, trim = 0.1)\n)\n\nergebnis <- t(sapply(names(kennzahlen), function(name) {\n  verteilung <- kennzahlen[[name]](zieh)\n  beobachtet <- switch(name,\n                       \"Mittelwert\" = mean(warten),\n                       \"Median\" = median(warten),\n                       mean(warten, trim = 0.1))\n  c(beobachtet = beobachtet,\n    boot_se = sd(verteilung),\n    unten = unname(quantile(verteilung, 0.025)),\n    oben = unname(quantile(verteilung, 0.975)))\n}))\nround(ergebnis, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             beobachtet boot_se  unten    oben\nMittelwert      12.2950  2.5436 7.8073 17.7205\nMedian           5.7000  1.2972 3.9000  8.7500\ngetrimmt 10%     8.3969  1.9836 5.5938 13.2692\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nkennzahlen = {\n    \"Mittelwert\": (warten.mean(), zieh.mean(axis=1)),\n    \"Median\": (np.median(warten), np.median(zieh, axis=1)),\n    \"getrimmt 10%\": (stats.trim_mean(warten, 0.1),\n                     np.array([stats.trim_mean(z, 0.1) for z in zieh])),\n}\n\nprint(pd.DataFrame({\n    name: {\n        \"beobachtet\": beob,\n        \"boot_se\": vert.std(ddof=1),\n        \"unten\": np.percentile(vert, 2.5),\n        \"oben\": np.percentile(vert, 97.5),\n    }\n    for name, (beob, vert) in kennzahlen.items()\n}).T.round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              beobachtet  boot_se   unten     oben\nMittelwert       12.2950   2.5436  7.8073  17.7205\nMedian            5.7000   1.2972  3.9000   8.7500\ngetrimmt 10%      8.3969   1.9836  5.5938  13.2692\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Kennzahl | beobachtet | Bootstrap-SE | 95-Prozent-Intervall | Wie das zu lesen ist |\n|---|---|---|---|---|\n| Mittelwert | 12.295 | 2.544 | 7.81 bis 17.72 | Stark von den grossen Werten geprägt. |\n| Median | 5.700 | 1.297 | 3.90 bis 8.75 | Halb so grosser Standardfehler, deutlich schmaleres Intervall, und inhaltlich die Zahl, die einen typischen Fall beschreibt. |\n| getrimmt 10 % | 8.397 | 1.984 | 5.59 bis 13.27 | Der Kompromiss: Die äussersten 10 Prozent auf jeder Seite werden weggelassen, der Rest gemittelt. |\n\nFür keine der beiden unteren Zeilen gibt es eine Standardformel. Der Bootstrap\nliefert sie ohne Zusatzaufwand, weil ihm gleichgültig ist, welche Kennzahl er\nberechnet.\n\n::: {.note-box}\n**Das Intervall des Medians ist auffällig grobkörnig**: Seine Grenzen sind 3.90\nund 8.75, also Mittelwerte benachbarter beobachteter Werte. Das liegt daran,\ndass der Median einer Ziehung immer einer der vorhandenen Werte ist oder das\nMittel zweier davon. Die Bootstrap-Verteilung ist deshalb diskret, und bei\nkleinen Stichproben wird das zum Problem, siehe Beispiel 4.\n:::\n\n#### Interpretation und Ergebnissatz\n\nDie Tabelle macht auch eine inhaltliche Entscheidung sichtbar. Welche der drei\nKennzahlen berichtet wird, ist keine statistische Frage: Der Mittelwert zählt,\nwenn es um die Gesamtbelastung geht (alle Wartezeiten zusammen), der Median,\nwenn es um den typischen Fall geht.\n\n> Die mediane Wartezeit beträgt 5.7 Minuten (95-Prozent-Bootstrap-Konfidenz-\n> intervall 3.9 bis 8.8 Minuten, Perzentilmethode, B = 2000). Berichtet wird der\n> Median statt des Mittelwerts, weil die Verteilung stark rechtsschief ist und\n> der Mittelwert von 12.3 Minuten keinen typischen Fall beschreibt.\n\n### Beispiel 3: Wie viele Ziehungen braucht es?\n\n#### Frage und Datenlage\n\n$B$ ist frei wählbar. Zu wenige Ziehungen machen das Ergebnis vom Zufall\nabhängig, zu viele kosten nur Rechenzeit. Wo liegt die Grenze?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Einfluss von B (Mittelwert, Saat 42):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEinfluss von B (Mittelwert, Saat 42):\n```\n\n\n:::\n\n```{.r .cell-code}\nfor (b in c(200, 1000, 2000)) {\n  v <- rowMeans(ziehungen(warten, b))\n  cat(sprintf(\"  B = %5d: %.4f bis %.4f\\n\", b,\n              quantile(v, 0.025), quantile(v, 0.975)))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  B =   200: 7.5031 bis 17.6306\n  B =  1000: 7.6320 bis 18.0444\n  B =  2000: 7.8073 bis 17.7205\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nEinfluss der Saat (B = 2000):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nEinfluss der Saat (B = 2000):\n```\n\n\n:::\n\n```{.r .cell-code}\nfor (saat in c(1, 42, 12345)) {\n  v <- rowMeans(ziehungen(warten, 2000, saat = saat))\n  cat(sprintf(\"  Saat %6d: %.4f bis %.4f\\n\", saat,\n              quantile(v, 0.025), quantile(v, 0.975)))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Saat      1: 7.8121 bis 17.4978\n  Saat     42: 7.8073 bis 17.7205\n  Saat  12345: 7.9123 bis 17.7652\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(\"Einfluss von B (Mittelwert, Saat 42):\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEinfluss von B (Mittelwert, Saat 42):\n```\n\n\n:::\n\n```{.python .cell-code}\nfor b in (200, 1000, 2000):\n    v = ziehungen(warten, b).mean(axis=1)\n    unten, oben = np.percentile(v, [2.5, 97.5])\n    print(f\"  B = {b:5d}: {unten:.4f} bis {oben:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  B =   200: 7.5031 bis 17.6306\n  B =  1000: 7.6320 bis 18.0444\n  B =  2000: 7.8073 bis 17.7205\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"\\nEinfluss der Saat (B = 2000):\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nEinfluss der Saat (B = 2000):\n```\n\n\n:::\n\n```{.python .cell-code}\nfor saat in (1, 42, 12345):\n    v = ziehungen(warten, 2000, saat=saat).mean(axis=1)\n    unten, oben = np.percentile(v, [2.5, 97.5])\n    print(f\"  Saat {saat:6d}: {unten:.4f} bis {oben:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Saat      1: 7.8121 bis 17.4978\n  Saat     42: 7.8073 bis 17.7205\n  Saat  12345: 7.9123 bis 17.7652\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| B | Intervall | Wie das zu lesen ist |\n|---|---|---|\n| 200 | 7.503 bis 17.631 | Die untere Grenze liegt 0.30 Minuten neben dem Wert bei B = 2000. |\n| 1000 | 7.632 bis 18.044 | Die obere Grenze weicht um 0.32 ab. |\n| 2000 | 7.807 bis 17.721 | |\n\n| Saat bei B = 2000 | Intervall | Schwankung |\n|---|---|---|\n| 1 | 7.812 bis 17.498 | |\n| 42 | 7.807 bis 17.721 | |\n| 12345 | 7.912 bis 17.765 | rund 0.27 Minuten Spanne an der oberen Grenze |\n\nBei B = 2000 schwanken die Grenzen je nach Seed noch um rund 0.3 Minuten. Ob das\nstört, hängt davon ab, wie genau berichtet wird: Für eine Angabe \"7.8 bis 17.7\"\nist es relevant, für \"rund 8 bis 18\" nicht.\n\n::: {.note-box}\n**Faustregeln für B.** Für Standardfehler genügen 1000 Ziehungen. Für\nPerzentilintervalle sind 2000 bis 5000 üblich, weil die Quantile an den Rändern\nder Verteilung liegen und dort weniger Werte zur Verfügung stehen. Für BCa oder\nfür sehr genaue Angaben sind 10 000 angebracht.\n\nRechenzeit ist selten das Argument: 10 000 Ziehungen aus 40 Werten sind eine\nSache von Sekundenbruchteilen. Auf dieser Seite steht B = 2000, weil die\nRechnung im Build für jede Seite neu läuft.\n:::\n\n#### Interpretation und Ergebnissatz\n\nDer Seed gehört ins Protokoll. Nicht weil das Ergebnis dadurch richtiger würde,\nsondern weil eine Bootstrap-Angabe ohne Seed nicht reproduzierbar ist: Wer sie\nnachrechnet, bekommt andere Grenzen und weiss nicht, ob das an einem Fehler\nliegt oder am Zufall.\n\n### Beispiel 4: Wo der Bootstrap versagt\n\n#### Frage und Datenlage\n\nNur die ersten acht Wartezeiten: 1.2 bis 2.6 Minuten. Gesucht ist ein\nKonfidenzintervall für den Median. Der Bootstrap läuft anstandslos durch — und\nliefert etwas, das nicht brauchbar ist.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nklein <- warten[1:8]\nklein\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.2 1.5 1.8 2.0 2.1 2.3 2.5 2.6\n```\n\n\n:::\n\n```{.r .cell-code}\nzieh_klein <- ziehungen(klein, 2000)\nmedian_klein <- apply(zieh_klein, 1, median)\n\nround(c(median_beobachtet = median(klein),\n        unten = unname(quantile(median_klein, 0.025)),\n        oben = unname(quantile(median_klein, 0.975))), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmedian_beobachtet             unten              oben \n             2.05              1.50              2.50 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"verschiedene Werte in der Bootstrap-Verteilung:\",\n    length(unique(median_klein)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nverschiedene Werte in der Bootstrap-Verteilung: 22 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Maximum der Bootstrap-Verteilung:\", max(median_klein),\n    \" Maximum der Daten:\", max(klein), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMaximum der Bootstrap-Verteilung: 2.6  Maximum der Daten: 2.6 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(round(median_klein, 2))[1:8]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n 1.2 1.35  1.5  1.6 1.65 1.75  1.8  1.9 \n   4   12   53    1   92   48  161  224 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nklein = warten[:8]\nprint(\"Daten:\", klein.tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDaten: [1.2, 1.5, 1.8, 2.0, 2.1, 2.3, 2.5, 2.6]\n```\n\n\n:::\n\n```{.python .cell-code}\nzieh_klein = ziehungen(klein, 2000)\nmedian_klein = np.median(zieh_klein, axis=1)\n\nprint(\"Median beobachtet =\", round(float(np.median(klein)), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian beobachtet = 2.05\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Perzentilintervall:\", np.percentile(median_klein, [2.5, 97.5]).round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPerzentilintervall: [1.5 2.5]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"verschiedene Werte in der Bootstrap-Verteilung:\",\n      len(np.unique(median_klein)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nverschiedene Werte in der Bootstrap-Verteilung: 22\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Maximum der Bootstrap-Verteilung:\", median_klein.max(),\n      \" Maximum der Daten:\", klein.max())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMaximum der Bootstrap-Verteilung: 2.6  Maximum der Daten: 2.6\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pd.Series(median_klein).round(2).value_counts().sort_index().head(8))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1.20      4\n1.35     12\n1.50     53\n1.60      1\n1.65     92\n1.75     48\n1.80    161\n1.90    224\nName: count, dtype: int64\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Median beobachtet | 2.050 | |\n| Perzentilintervall | 1.500 bis 2.500 | Sieht unauffällig aus. |\n| verschiedene Werte in der Bootstrap-Verteilung | **22** | Die ganze Verteilung besteht aus 22 verschiedenen Zahlen. Von einer glatten Verteilung, deren Quantile man ablesen könnte, kann keine Rede sein. |\n| Maximum der Bootstrap-Verteilung | 2.600 | **Genau das Maximum der Daten.** Der Bootstrap kann keinen Wert erzeugen, der nicht beobachtet wurde. |\n\nDas letzte ist der grundsätzliche Punkt: Die Bootstrap-Verteilung lebt\nausschliesslich innerhalb der beobachteten Werte. Bei acht Beobachtungen sind\ndas acht Zahlen, und aus deren Kombinationen entstehen 22 mögliche Mediane.\n\n::: {.note-box}\n**Zwei Regeln folgen daraus.**\n\n**Der Bootstrap braucht genügend Daten.** Als grobe Untergrenze gelten 20 bis 30\nBeobachtungen, für Kennzahlen an den Verteilungsrändern deutlich mehr. Bei\nkleinen Stichproben ist eine Formel mit Verteilungsannahme meist die bessere\nWahl, auch wenn ihre Annahme unsicher ist.\n\n**Für Extremwerte ist er grundsätzlich ungeeignet.** Ein Konfidenzintervall für\ndas Maximum wäre nach oben durch das beobachtete Maximum begrenzt, was\noffensichtlich falsch ist. Dasselbe gilt abgeschwächt für hohe Quantile wie das\n95-Prozent-Quantil.\n:::\n\n#### Interpretation und Ergebnissatz\n\nDer Bootstrap warnt nicht. Er liefert für acht Beobachtungen ebenso bereitwillig\nein Intervall wie für achthundert, und das Ergebnis sieht in beiden Fällen gleich\naus. Die Prüfung, ob genug Daten vorliegen, muss deshalb vorher stattfinden.\n\nEin nützlicher Blick: die Anzahl verschiedener Werte in der\nBootstrap-Verteilung. Sind es wenige Dutzend, ist die Verteilung zu grobkörnig,\num Quantile daraus abzulesen.\n\n> Für die acht Werte wurde kein Bootstrap-Intervall berechnet. Die\n> Bootstrap-Verteilung des Medians nimmt nur 22 verschiedene Werte an und ist\n> nach oben durch den grössten beobachteten Wert begrenzt; ein daraus\n> abgeleitetes Intervall wäre irreführend. Berichtet wird stattdessen die\n> Spannweite der Beobachtungen.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nWarum wird beim Bootstrap **mit** Zurücklegen gezogen?\n\n- [x] Ohne Zurücklegen wäre jede Ziehung identisch mit der Ausgangsstichprobe ~\n      Richtig. Zieht man $n$ aus $n$ ohne Zurücklegen, erhält man immer dieselben\n      Werte in anderer Reihenfolge, und jede Kennzahl wäre identisch. Erst das\n      Zurücklegen erzeugt Variation.\n- [ ] Um die Stichprobe zu vergrössern ~ Die Ziehung hat dieselbe Grösse wie das\n      Original; neue Information entsteht nicht.\n- [ ] Weil die Grundgesamtheit unendlich gross ist ~ Das Zurücklegen bildet das\n      ab, ist aber nicht der Grund für die Notwendigkeit.\n:::\n\n::: {.quiz}\nDas t-Intervall lautet 7.05 bis 17.54, das Bootstrap-Intervall 7.81 bis 17.72.\nWoher kommt der Unterschied?\n\n- [x] Das t-Intervall ist konstruktionsbedingt symmetrisch, das Bootstrap-\n      Intervall bildet die Rechtsschiefe ab ~ Richtig. Bei schiefen Daten ist die\n      Verteilung des Mittelwerts ebenfalls schief. Der Bootstrap reicht 4.5\n      Minuten nach unten und 5.4 nach oben, die Formel zwingend gleich weit in\n      beide Richtungen.\n- [ ] Eines der beiden ist falsch gerechnet ~ Beide sind korrekt; sie beruhen\n      auf verschiedenen Annahmen.\n- [ ] Der Bootstrap hat zu wenige Ziehungen verwendet ~ Der Unterschied in der\n      Symmetrie bleibt auch bei sehr grossem B bestehen.\n:::\n\n::: {.quiz}\nEine Bootstrap-Verteilung aus 2000 Ziehungen nimmt nur 22 verschiedene Werte an.\nWas folgt daraus?\n\n- [x] Die Stichprobe ist zu klein für den Bootstrap ~ Richtig. Die\n      Bootstrap-Verteilung entsteht aus Kombinationen der beobachteten Werte.\n      Wenige verschiedene Ergebnisse bedeuten, dass zu wenige Ausgangswerte\n      vorliegen, und die Quantile werden dann grobkörnig und unzuverlässig.\n- [ ] B ist zu klein gewählt ~ Mehr Ziehungen erzeugen keine neuen Werte,\n      sondern nur häufigere Wiederholungen derselben 22.\n- [ ] Die Kennzahl ist ungeeignet ~ Der Median ist eine sinnvolle Kennzahl; das\n      Problem liegt am Umfang.\n:::\n\n::: {.quiz}\nWarum eignet sich der Bootstrap nicht für ein Konfidenzintervall des Maximums?\n\n- [x] Weil die Bootstrap-Verteilung den beobachteten Wertebereich nie verlässt ~\n      Richtig. Das Maximum jeder Ziehung ist höchstens so gross wie das grösste\n      beobachtete. Die obere Intervallgrenze wäre dadurch immer das beobachtete\n      Maximum, was als Schätzung offensichtlich zu klein ist.\n- [ ] Weil das Maximum keine stetige Kennzahl ist ~ Stetigkeit ist nicht das\n      Problem; der Median ist ebenfalls nicht stetig und funktioniert bei\n      genügend Daten.\n- [ ] Weil zu viele Ziehungen nötig wären ~ Auch mit beliebig vielen Ziehungen\n      bleibt die Grenze bestehen.\n:::\n\n## Verlinkte Ressourcen\n\n- [An Introduction to Statistical Learning, Kapitel 5.2](https://www.statlearning.com/)\n- [R-Paket `boot`](https://cran.r-project.org/package=boot)\n- [scipy: bootstrap](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.bootstrap.html)\n",
    "supporting": [
      "bootstrap-resampling_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}