{
  "hash": "9ef2fb3f90ecc00f1f6ed12d6de90e7a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Stationarität, ACF und PACF\"\ndescription: \"Differenzieren, ADF-Test und wie man Korrelogramme liest.\"\ncategories: [\"Zeitreihen\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: konzept\nstand: fertig\norder: 20\n---\n\n\n\n\n\n## Kernideen\n\n- **Stationär** heisst: Mittelwert, Streuung und Abhängigkeitsstruktur ändern\n  sich nicht über die Zeit.\n- Fast alle Modelle setzen Stationarität voraus, echte Reihen erfüllen sie\n  selten.\n- Differenzieren entfernt einen Trend, saisonales Differenzieren die Saison.\n- **Nicht jeder Trend gehört wegdifferenziert**: Ein deterministischer Trend wird\n  besser herausgerechnet, sonst überdifferenziert man.\n- Die **ACF** zeigt die Gesamtabhängigkeit, die **PACF** die direkte.\n- Aus dem Muster der beiden lässt sich die Modellordnung ablesen: AR bricht in\n  der PACF ab, MA in der ACF.\n- Ein Test auf Stationarität ergänzt die Grafik, er ersetzt sie nicht und ADF\n  und KPSS haben **entgegengesetzte** Nullhypothesen.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Zeitreihen: Grundlagen](zeitreihen-grundlagen.qmd) für Trend und\nSaison sowie [Korrelation](../grundlagen/korrelation.qmd). Was darauf aufbaut,\nist die Modellwahl unter [ARIMA und SARIMA](arima-sarima.qmd).\n:::\n\n### Was stationär bedeutet\n\nEine Reihe ist stationär, wenn ihre statistischen Eigenschaften nicht davon\nabhängen, wann man hinschaut: konstanter Mittelwert, konstante Streuung, und eine\nAbhängigkeitsstruktur, die nur vom **Abstand** zweier Zeitpunkte abhängt, nicht\nvon deren Lage.\n\nDer Grund für die Wichtigkeit ist praktisch: Ein Modell lernt aus der\nVergangenheit für die Zukunft. Wenn sich das Niveau laufend verschiebt, gibt es\nkein Niveau, das sich lernen liesse. Deshalb wird eine Reihe zuerst stationär\ngemacht und danach modelliert.\n\nDrei typische Verletzungen und ihr Gegenmittel:\n\n| Verletzung | Erkennbar an | Gegenmittel |\n|---|---|---|\n| Trend | Niveau wandert | einmal differenzieren oder den Trend herausrechnen |\n| Saison | wiederkehrendes Muster | saisonal differenzieren, Abstand gleich Periode |\n| wachsende Streuung | Zacken werden höher | logarithmieren oder Wurzel ziehen |\n\n### Zwei Arten von Trend\n\nDiese Unterscheidung entscheidet über die Behandlung und wird häufig übersehen:\n\n| Art | Modell | Was passiert ohne Störung | Richtige Behandlung |\n|---|---|---|---|\n| **deterministisch** | $y_t = a + bt + \\varepsilon_t$ | die Reihe kehrt zur Geraden zurück | Trend herausrechnen (Regression gegen die Zeit) |\n| **stochastisch** | $y_t = y_{t-1} + \\delta + \\varepsilon_t$ (Zufallspfad) | die Reihe wandert beliebig weit weg | differenzieren |\n\nIm Bild sehen beide ähnlich aus. Der Unterschied zeigt sich erst in der\nBehandlung: Wer einen deterministischen Trend wegdifferenziert, erzeugt eine\nkünstliche negative Abhängigkeit, siehe Beispiel 3.\n\n### Differenzieren\n\nDifferenzieren heisst, statt der Werte deren Veränderungen zu betrachten:\n$\\Delta y_t = y_t - y_{t-1}$. Aus einem linearen Trend wird damit ein konstantes\nNiveau. Saisonales Differenzieren nimmt den Abstand einer ganzen Periode:\n$y_t - y_{t-12}$ bei Monatsdaten.\n\nDie Faustregel: In der Praxis genügt fast immer **eine** Differenz, gelegentlich\nzwei, mehr praktisch nie. Und: Nimmt die Streuung durch das Differenzieren zu,\nwar eine Differenz zu viel.\n\n### ACF und PACF\n\nBeide beschreiben, wie stark ein Wert mit früheren Werten zusammenhängt, aber\nverschieden.\n\nDie **Autokorrelationsfunktion (ACF)** gibt die Korrelation zwischen $y_t$ und\n$y_{t-k}$ für jeden Abstand $k$. Sie enthält auch indirekte Wirkungen: Wenn heute\nmit gestern und gestern mit vorgestern zusammenhängt, zeigt die ACF auch bei\nAbstand zwei einen Wert, obwohl es keine direkte Verbindung gibt.\n\nDie **partielle Autokorrelationsfunktion (PACF)** entfernt genau diese indirekten\nWirkungen: Sie gibt die Korrelation zwischen $y_t$ und $y_{t-k}$, nachdem der\nEinfluss aller dazwischenliegenden Zeitpunkte herausgerechnet ist. Es ist dieselbe\nIdee wie der Unterschied zwischen einfacher und\n[multipler Regression](../regression/multiple-lineare-regression.qmd).\n\nDie Konfidenzgrenzen in beiden Korrelogrammen liegen bei $\\pm 1.96/\\sqrt{n}$,\nbei 120 Werten also bei ±0.179. Sie prüfen jeden Abstand einzeln; bei 24\nangezeigten Abständen ist rund einer davon zufällig ausserhalb, siehe\n[multiples Testen](../inferenz/multiples-testen.qmd).\n\n### Tests auf Stationarität\n\n| Test | Nullhypothese | kleiner p-Wert heisst |\n|---|---|---|\n| **ADF** (Augmented Dickey-Fuller) | die Reihe ist **nicht** stationär (Einheitswurzel) | Beleg **für** Stationarität |\n| **KPSS** | die Reihe **ist** stationär | Beleg **gegen** Stationarität |\n\nDiese Umkehrung ist die häufigste Verwechslung des ganzen Gebiets. Weil die\nbeiden Tests entgegengesetzte Nullhypothesen haben, ergänzen sie sich: Erst wenn\n**beide** in dieselbe Richtung zeigen, ist die Sache klar.\n\n## Beispiele\n\nAlle Beispiele arbeiten mit konstruierten Monatsreihen zu je 120 Werten ab\nJanuar 2016. Weil die erzeugende Struktur bekannt ist, lässt sich prüfen, ob die\nDiagnose sie findet.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Vier Reihen und ihre Korrelogramme\n\n#### Frage und Datenlage\n\nVier Reihen mit bekannter Struktur: weisses Rauschen, ein deterministischer\nTrend, eine Jahressaison und ein Zufallspfad. Wie sehen ihre ACF und PACF aus?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreihen <- list(\"weisses Rauschen\" = weiss, \"mit Trend\" = mit_trend,\n               \"mit Saison\" = mit_saison, \"Zufallspfad\" = zufallspfad)\n\npar(mfrow = c(4, 2), mar = c(3.5, 4, 2.5, 1))\nfor (name in names(reihen)) {\n  acf(reihen[[name]], lag.max = 24, main = paste(name, \"ACF\"))\n  pacf(reihen[[name]], lag.max = 24, main = paste(name, \"PACF\"))\n}\npar(mfrow = c(1, 1))\n\n# Die ersten sechs Werte als Zahlen\nfor (name in names(reihen)) {\n  a <- acf(reihen[[name]], lag.max = 6, plot = FALSE)$acf[2:7]\n  cat(sprintf(\"%-18s ACF %s\\n\", name, paste(sprintf(\"%6.3f\", a), collapse = \" \")))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nweisses Rauschen   ACF -0.069  0.030 -0.089 -0.007 -0.039 -0.004\nmit Trend          ACF  0.876  0.823  0.807  0.788  0.756  0.732\nmit Saison         ACF  0.708  0.398  0.008 -0.404 -0.679 -0.800\nZufallspfad        ACF  0.958  0.922  0.879  0.827  0.776  0.724\n```\n\n\n:::\n\n```{.r .cell-code}\nround(1.96 / sqrt(monate), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.179\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 1: ACF und PACF für vier Reihen mit bekannter Struktur.](stationaritaet-acf-pacf_files/figure-html/fig-b1-st-r-1.png){#fig-b1-st-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nreihen = {\"weisses Rauschen\": weiss, \"mit Trend\": mit_trend,\n          \"mit Saison\": mit_saison, \"Zufallspfad\": zufallspfad}\n\nfig, achsen = plt.subplots(4, 2, figsize=(7, 6))\nfor zeile, (name, reihe) in enumerate(reihen.items()):\n    plot_acf(reihe, ax=achsen[zeile, 0], lags=24, title=f\"{name} ACF\")\n    plot_pacf(reihe, ax=achsen[zeile, 1], lags=24, title=f\"{name} PACF\",\n              method=\"ywm\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselben acht Korrelogramme in Python.](stationaritaet-acf-pacf_files/figure-html/fig-b1-st-py-1.png){#fig-b1-st-py width=100%}\n:::\n\n```{.python .cell-code}\nfor name, reihe in reihen.items():\n    werte = acf(reihe, nlags=6)[1:7]\n    print(f\"{name:18s} ACF \" + \" \".join(f\"{w:6.3f}\" for w in werte))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nweisses Rauschen   ACF -0.069  0.030 -0.089 -0.007 -0.039 -0.004\nmit Trend          ACF  0.876  0.823  0.807  0.788  0.756  0.732\nmit Saison         ACF  0.708  0.398  0.008 -0.404 -0.679 -0.800\nZufallspfad        ACF  0.958  0.922  0.879  0.827  0.776  0.724\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Konfidenzgrenze 1.96/sqrt(n):\", round(1.96 / np.sqrt(monate), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKonfidenzgrenze 1.96/sqrt(n): 0.179\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nDie ersten sechs Autokorrelationen (Konfidenzgrenze ±0.179):\n\n| Reihe | k=1 | k=2 | k=3 | k=4 | k=5 | k=6 |\n|---|---|---|---|---|---|---|\n| weisses Rauschen | -0.069 | 0.030 | -0.089 | -0.007 | -0.039 | -0.004 |\n| mit Trend | **0.876** | 0.823 | 0.807 | 0.788 | 0.756 | 0.732 |\n| mit Saison | **0.708** | 0.398 | 0.008 | **-0.404** | -0.679 | **-0.800** |\n| Zufallspfad | **0.958** | 0.922 | 0.879 | 0.827 | 0.776 | 0.724 |\n\n| Reihe | Muster | Diagnose |\n|---|---|---|\n| **weisses Rauschen** | alle Balken innerhalb der Grenzen, in ACF wie PACF | Nichts zu modellieren. Genau dieses Bild sollen die **Residuen** eines fertigen Modells zeigen. |\n| **mit Trend** | ACF fällt sehr langsam ab und bleibt über zwanzig Abstände deutlich positiv; PACF hat einen grossen Wert bei k=1 (0.876) und wird danach klein | Das klassische Zeichen für Nichtstationarität. Die Reaktion ist **differenzieren oder detrenden**, nicht ein Modell mit vielen Ordnungen. |\n| **mit Saison** | ACF schwingt: positiv bei k=1, durch null bei k=3, stark negativ bei k=6, wieder positiv bei k=12 (0.729) und k=24 (0.629) | Die Wellenform mit Spitzen bei Vielfachen der Periode ist die Signatur der Saison. |\n| **Zufallspfad** | ACF fällt noch langsamer ab (0.958 bei k=1); PACF hat nur bei k=1 einen grossen Wert | Optisch fast identisch mit dem deterministischen Trend, der Unterschied wird erst in Beispiel 3 sichtbar. |\n\n::: {.note-box}\n**Die Reihen mit Trend und der Zufallspfad sehen in ACF und PACF praktisch gleich\naus.** Beide zeigen eine langsam abfallende ACF und eine PACF mit einem einzigen\ngrossen Wert bei k=1. Kein Korrelogramm der Welt unterscheidet die beiden. Das\nist kein Mangel der Grafik, sondern eine echte Schwierigkeit und der Grund,\nwarum Beispiel 3 nötig ist.\n:::\n\n#### Interpretation\n\nDie Korrelogramme beantworten zuverlässig die Frage \"ist die Reihe stationär\"\nund zeigen die Periodenlänge der Saison. Die Frage \"welche Art von Trend\" können\nsie nicht beantworten.\n\n### Beispiel 2: Die Signaturen von AR und MA\n\n#### Frage und Datenlage\n\nDer eigentliche Zweck von ACF und PACF ist die Wahl der Modellordnung. Dafür\ngibt es zwei Signaturen, die man auswendig kennen sollte. Verglichen werden ein\nAR(1)-Prozess ($y_t = 0.7\\, y_{t-1} + \\varepsilon_t$) und ein MA(1)-Prozess\n($y_t = \\varepsilon_t + 0.8\\, \\varepsilon_{t-1}$), beide aus demselben Rauschen\nerzeugt.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2), mar = c(3.5, 4, 2.5, 1))\nacf(ar1, lag.max = 12, main = \"AR(1): ACF\")\npacf(ar1, lag.max = 12, main = \"AR(1): PACF\")\nacf(ma1, lag.max = 12, main = \"MA(1): ACF\")\npacf(ma1, lag.max = 12, main = \"MA(1): PACF\")\npar(mfrow = c(1, 1))\n\nfor (name in c(\"ar1\", \"ma1\")) {\n  reihe <- get(name)\n  a <- acf(reihe, lag.max = 5, plot = FALSE)$acf[2:6]\n  p <- pacf(reihe, lag.max = 5, plot = FALSE)$acf[1:5]\n  cat(sprintf(\"%-5s ACF  %s\\n\", name, paste(sprintf(\"%6.3f\", a), collapse = \" \")))\n  cat(sprintf(\"%-5s PACF %s\\n\", \"\", paste(sprintf(\"%6.3f\", p), collapse = \" \")))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nar1   ACF   0.602  0.412  0.272  0.284  0.278\n      PACF  0.602  0.078 -0.007  0.164  0.069\nma1   ACF   0.386 -0.153 -0.102  0.117  0.209\n      PACF  0.386 -0.355  0.155  0.069  0.127\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 2: AR(1) bricht in der PACF ab, MA(1) in der ACF.](stationaritaet-acf-pacf_files/figure-html/fig-b2-st-r-3.png){#fig-b2-st-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(2, 2, figsize=(7, 4))\nfor zeile, (reihe, name) in enumerate([(ar1, \"AR(1)\"), (ma1, \"MA(1)\")]):\n    plot_acf(reihe, ax=achsen[zeile, 0], lags=12, title=f\"{name}: ACF\")\n    plot_pacf(reihe, ax=achsen[zeile, 1], lags=12, title=f\"{name}: PACF\",\n              method=\"ywm\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselben vier Korrelogramme in Python.](stationaritaet-acf-pacf_files/figure-html/fig-b2-st-py-1.png){#fig-b2-st-py width=100%}\n:::\n\n```{.python .cell-code}\nfor name, reihe in [(\"ar1\", ar1), (\"ma1\", ma1)]:\n    a = acf(reihe, nlags=5)[1:6]\n    p = pacf(reihe, nlags=5, method=\"ywm\")[1:6]\n    print(f\"{name:5s} ACF  \" + \" \".join(f\"{w:6.3f}\" for w in a))\n    print(f\"{'':5s} PACF \" + \" \".join(f\"{w:6.3f}\" for w in p))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nar1   ACF   0.602  0.412  0.272  0.284  0.278\n      PACF  0.602  0.078 -0.007  0.164  0.069\nma1   ACF   0.386 -0.153 -0.102  0.117  0.209\n      PACF  0.386 -0.355  0.155  0.069  0.127\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Prozess | | k=1 | k=2 | k=3 | k=4 | k=5 |\n|---|---|---|---|---|---|---|\n| **AR(1)**, $\\phi = 0.7$ | ACF | 0.602 | 0.412 | 0.272 | 0.284 | 0.278 |\n| | PACF | **0.602** | **0.078** | **-0.007** | 0.164 | 0.069 |\n| **MA(1)**, $\\theta = 0.8$ | ACF | **0.386** | **-0.153** | **-0.102** | 0.117 | 0.209 |\n| | PACF | 0.386 | -0.355 | 0.155 | 0.069 | 0.127 |\n\n| Beobachtung | Deutung |\n|---|---|\n| **AR(1)**: ACF fällt **allmählich** (0.60, 0.41, 0.27) | Der Einfluss läuft über die Kette weiter: Heute wirkt auf morgen, morgen auf übermorgen. Deshalb ist auch bei Abstand 2 noch etwas messbar, obwohl keine direkte Verbindung besteht. |\n| **AR(1)**: PACF **bricht nach k=1 ab** (0.602, dann 0.078 und -0.007) | Die direkte Abhängigkeit besteht nur zum Vormonat. Genau das ist die Signatur. |\n| **MA(1)**: ACF **bricht nach k=1 ab** (0.386, dann -0.153 und -0.102, beide innerhalb ±0.179) | Ein MA(1)-Prozess teilt mit dem Vormonat eine Störung, mit dem Vorvormonat keine. |\n| **MA(1)**: PACF fällt **allmählich** mit wechselndem Vorzeichen (0.386, -0.355, 0.155) | Die spiegelbildliche Eigenschaft. |\n\nDaraus die Merkregel:\n\n| Signatur | Modell | Ordnung ablesen |\n|---|---|---|\n| ACF fällt ab, **PACF bricht ab nach $p$** | AR($p$) | aus der PACF |\n| **ACF bricht ab nach $q$**, PACF fällt ab | MA($q$) | aus der ACF |\n| beide fallen allmählich ab | ARMA($p,q$) | nicht direkt ablesbar, über [Informationskriterien](arima-sarima.qmd) |\n\n::: {.note-box}\n**Die Schätzungen treffen die eingebauten Werte nicht genau.** Theoretisch müsste\ndie ACF des AR(1) bei k=1 genau 0.7 betragen, gemessen werden 0.602; beim MA(1)\nwären $0.8/(1+0.8^2) = 0.488$ zu erwarten, gemessen 0.386. Bei 120 Werten ist der\nStandardfehler einer Autokorrelation etwa 0.09, die Abweichungen liegen in\ndieser Grössenordnung.\n\nPraktisch heisst das: **Aus einem Korrelogramm liest man Muster, nicht\nParameterwerte.** Die Ordnung ist ablesbar, der Koeffizient wird geschätzt.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die PACF bricht nach dem ersten Abstand ab (0.60, danach innerhalb der\n> Konfidenzgrenzen), während die ACF allmählich abfällt. Das spricht für ein\n> AR(1)-Modell.\n\n### Beispiel 3: Differenzieren oder detrenden\n\n#### Frage und Datenlage\n\nZwei Reihen, die im Bild fast gleich aussehen: der Zufallspfad und die Reihe mit\ndeterministischem Trend aus Beispiel 1. Beide sind nicht stationär. Werden sie\ngleich behandelt?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndetrend <- function(reihe) residuals(lm(as.numeric(reihe) ~ t))\n\npar(mfrow = c(2, 2), mar = c(3.5, 4, 2.5, 1))\nplot(diff(zufallspfad), ylab = \"\", main = \"Zufallspfad, differenziert\")\nabline(h = 0, lty = 2)\nacf(diff(zufallspfad), lag.max = 12, main = \"dessen ACF\")\nplot(diff(mit_trend), ylab = \"\", main = \"Trendreihe, differenziert\")\nabline(h = 0, lty = 2)\nacf(diff(mit_trend), lag.max = 12, main = \"dessen ACF\")\npar(mfrow = c(1, 1))\n\nkennzahlen <- function(reihe) {\n  c(sd = sd(reihe), acf1 = acf(reihe, lag.max = 1, plot = FALSE)$acf[2])\n}\n\nround(rbind(\n  \"Zufallspfad roh\" = kennzahlen(zufallspfad),\n  \"Zufallspfad differenziert\" = kennzahlen(diff(zufallspfad)),\n  \"Trendreihe roh\" = kennzahlen(mit_trend),\n  \"Trendreihe differenziert\" = kennzahlen(diff(mit_trend)),\n  \"Trendreihe detrendet\" = kennzahlen(detrend(mit_trend)),\n  \"Trendreihe zweimal differenziert\" = kennzahlen(diff(diff(mit_trend)))\n), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                     sd   acf1\nZufallspfad roh                  26.513  0.958\nZufallspfad differenziert         5.776 -0.151\nTrendreihe roh                   29.750  0.876\nTrendreihe differenziert         12.345 -0.354\nTrendreihe detrendet              9.284  0.099\nTrendreihe zweimal differenziert 20.254 -0.518\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: oben der Zufallspfad und seine Differenz, unten die Trendreihe differenziert und detrendet.](stationaritaet-acf-pacf_files/figure-html/fig-b3-st-r-3.png){#fig-b3-st-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndetrend = pd.Series(sm.OLS(mit_trend.values, sm.add_constant(t)).fit().resid,\n                    index=zeitachse)\n\nfig, achsen = plt.subplots(2, 2, figsize=(7, 4.6))\nachsen[0, 0].plot(zufallspfad.diff().dropna(), color=\"#2166ac\")\nachsen[0, 0].axhline(0, ls=\"--\", color=\"black\", lw=0.8)\nachsen[0, 0].set_title(\"Zufallspfad, differenziert\")\nplot_acf(zufallspfad.diff().dropna(), ax=achsen[0, 1], lags=12,\n         title=\"dessen ACF\")\nachsen[1, 0].plot(mit_trend.diff().dropna(), color=\"#b2182b\")\nachsen[1, 0].axhline(0, ls=\"--\", color=\"black\", lw=0.8)\nachsen[1, 0].set_title(\"Trendreihe, differenziert\")\nplot_acf(mit_trend.diff().dropna(), ax=achsen[1, 1], lags=12,\n         title=\"dessen ACF\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselbe Gegenüberstellung in Python.](stationaritaet-acf-pacf_files/figure-html/fig-b3-st-py-1.png){#fig-b3-st-py width=100%}\n:::\n\n```{.python .cell-code}\nzeilen = {\n    \"Zufallspfad roh\": zufallspfad,\n    \"Zufallspfad differenziert\": zufallspfad.diff().dropna(),\n    \"Trendreihe roh\": mit_trend,\n    \"Trendreihe differenziert\": mit_trend.diff().dropna(),\n    \"Trendreihe detrendet\": detrend,\n    \"Trendreihe zweimal differenziert\": mit_trend.diff().diff().dropna(),\n}\nprint(pd.DataFrame({\n    name: {\"sd\": round(float(r.std(ddof=1)), 3),\n           \"acf1\": round(float(acf(r, nlags=1)[1]), 3)}\n    for name, r in zeilen.items()}).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                      sd   acf1\nZufallspfad roh                   26.513  0.958\nZufallspfad differenziert          5.776 -0.151\nTrendreihe roh                    29.750  0.876\nTrendreihe differenziert          12.345 -0.354\nTrendreihe detrendet               9.284  0.099\nTrendreihe zweimal differenziert  20.254 -0.518\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Reihe | Streuung | ACF(1) | Beurteilung |\n|---|---|---|---|\n| Zufallspfad, roh | 26.51 | 0.958 | nicht stationär |\n| **Zufallspfad, differenziert** | **5.78** | **-0.151** | **richtig**: Streuung stark gesunken, ACF(1) innerhalb ±0.179, weisses Rauschen |\n| Trendreihe, roh | 29.75 | 0.876 | nicht stationär |\n| Trendreihe, differenziert | **12.35** | **-0.354** | **überdifferenziert**: ACF(1) deutlich negativ |\n| **Trendreihe, detrendet** | **9.28** | **0.099** | **richtig**: kleinste Streuung, ACF(1) unauffällig |\n| Trendreihe, zweimal differenziert | 20.25 | -0.518 | doppelt überdifferenziert |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Der Zufallspfad wird durch **eine** Differenz zu weissem Rauschen | Er **ist** ja die kumulierte Summe von Rauschen; das Differenzieren macht sie wieder rückgängig. Die Streuung fällt von 26.5 auf 5.8. |\n| Die Trendreihe wird durch Differenzieren **schlechter** | Ihre Störung ist bereits weisses Rauschen mit Streuung 10. Differenzieren erzeugt daraus $\\varepsilon_t - \\varepsilon_{t-1}$, einen MA(1)-Prozess mit theoretischer ACF(1) von **-0.5**, gemessen -0.354. Die Streuung steigt von 9.3 (nach Detrending) auf 12.3, also um den Faktor $\\sqrt{2}$. |\n| Detrending trifft es | Nach Herausrechnen der Geraden bleibt Streuung 9.28 und ACF(1) = 0.099, die eingebaute Störung, sauber zurückgewonnen. |\n| Zweimal differenziert: ACF(1) = -0.518 | Es wird noch schlimmer. Jede unnötige Differenz erzeugt zusätzliche negative Abhängigkeit, die das Modell dann mit MA-Termen wieder reparieren muss. |\n\n::: {.note-box}\n**Die praktische Faustregel**, weil man in echten Daten nicht weiss, welcher\nTrend vorliegt:\n\n1. Streuung vor und nach dem Differenzieren vergleichen. **Steigt** sie, war es\n   eine Differenz zu viel.\n2. ACF(1) der differenzierten Reihe ansehen. Ein Wert nahe **-0.5** ist das\n   Kennzeichen der Überdifferenzierung.\n3. Im Zweifel beide Wege durchrechnen und über ein\n   [Informationskriterium](../regression/modellauswahl.qmd) entscheiden.\n\nWas beide Fälle unterscheidet, ist auch inhaltlich verschieden: Eine\ntrendstationäre Reihe kehrt nach einer Störung zur Geraden zurück, ein\nZufallspfad nicht. Wer eine Prognose über mehrere Perioden braucht, sollte das\nnicht dem Zufall überlassen, die Vorhersageintervalle unterscheiden sich\ndrastisch.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Der Zufallspfad wird durch eine einfache Differenz stationär (Streuung von 26.5\n> auf 5.8, ACF(1) = -0.15). Bei der Reihe mit deterministischem Trend führt\n> dasselbe Vorgehen zur Überdifferenzierung (ACF(1) = -0.35, Streuung steigt von\n> 9.3 auf 12.3); dort wird der Trend stattdessen durch eine Regression gegen die\n> Zeit entfernt.\n\n### Beispiel 4: ADF und KPSS\n\n#### Frage und Datenlage\n\nZwei Tests mit entgegengesetzten Nullhypothesen, angewendet auf sechs Reihen.\nDie Frage: Was sagen sie, und wo hilft ihre Kombination?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkandidaten <- list(\n  \"weisses Rauschen\" = weiss,\n  \"mit Trend\" = mit_trend,\n  \"Trend differenziert\" = diff(mit_trend),\n  \"mit Saison\" = mit_saison,\n  \"Saison saisonal diff\" = diff(mit_saison, lag = 12),\n  \"Zufallspfad\" = zufallspfad,\n  \"Zufallspfad diff\" = diff(zufallspfad)\n)\n\nfor (name in names(kandidaten)) {\n  reihe <- kandidaten[[name]]\n  adf <- suppressWarnings(adf.test(reihe))\n  kp <- suppressWarnings(kpss.test(reihe))\n  cat(sprintf(\"%-22s ADF p = %.3f | KPSS p = %.3f\\n\",\n              name, adf$p.value, kp$p.value))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nweisses Rauschen       ADF p = 0.010 | KPSS p = 0.100\nmit Trend              ADF p = 0.010 | KPSS p = 0.010\nTrend differenziert    ADF p = 0.010 | KPSS p = 0.100\nmit Saison             ADF p = 0.010 | KPSS p = 0.100\nSaison saisonal diff   ADF p = 0.010 | KPSS p = 0.100\nZufallspfad            ADF p = 0.199 | KPSS p = 0.010\nZufallspfad diff       ADF p = 0.010 | KPSS p = 0.100\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nkandidaten = {\n    \"weisses Rauschen\": weiss,\n    \"mit Trend\": mit_trend,\n    \"Trend differenziert\": mit_trend.diff().dropna(),\n    \"mit Saison\": mit_saison,\n    \"Saison saisonal diff\": mit_saison.diff(12).dropna(),\n    \"Zufallspfad\": zufallspfad,\n    \"Zufallspfad diff\": zufallspfad.diff().dropna(),\n}\n\nfor name, reihe in kandidaten.items():\n    print(f\"{name:22s} ADF p = {adfuller(reihe)[1]:.3f}\"\n          f\" | KPSS p = {kpss(reihe, nlags='auto')[1]:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nweisses Rauschen       ADF p = 0.000 | KPSS p = 0.100\nmit Trend              ADF p = 0.939 | KPSS p = 0.010\nTrend differenziert    ADF p = 0.000 | KPSS p = 0.100\nmit Saison             ADF p = 0.000 | KPSS p = 0.100\nSaison saisonal diff   ADF p = 0.001 | KPSS p = 0.100\nZufallspfad            ADF p = 0.713 | KPSS p = 0.010\nZufallspfad diff       ADF p = 0.000 | KPSS p = 0.100\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Reihe | ADF p, R | ADF p, Python | KPSS p | Urteil |\n|---|---|---|---|---|\n| weisses Rauschen | 0.010 | 0.000 | 0.100 | stationär, alle einig |\n| **mit Trend** | **0.010** | **0.939** | **0.010** | **hier widersprechen sich R und Python** |\n| Trend differenziert | 0.010 | 0.000 | 0.100 | stationär (aber überdifferenziert, siehe Beispiel 3) |\n| mit Saison | 0.010 | 0.000 | 0.100 | **stationär und das ist irreführend** |\n| Saison saisonal diff | 0.010 | 0.001 | 0.100 | stationär |\n| Zufallspfad | 0.199 | 0.713 | **0.010** | nicht stationär, alle einig |\n| Zufallspfad diff | 0.010 | 0.000 | 0.100 | stationär |\n\n| Ausgabe | Wie sie zu lesen ist |\n|---|---|\n| **kleines ADF p** heisst stationär | Es verwirft die Nullhypothese \"Einheitswurzel\". |\n| **grosses KPSS p** heisst stationär | Es kann die Nullhypothese \"stationär\" nicht verwerfen. **Umgekehrte Richtung.** |\n| Die Werte 0.100 und 0.010 wiederholen sich | Das sind die Ränder der Tabellen, aus denen beide Tests ihre p-Werte interpolieren. \"0.010\" heisst \"höchstens 0.01\", \"0.100\" heisst \"mindestens 0.1\". Die Programme geben dazu eine Warnung aus. R kappt auch die ADF-Werte an diesen Grenzen, weshalb dort so oft genau 0.010 steht. |\n| **Die Reihe mit Trend: R sagt stationär, Python nicht** | Kein Fehler, sondern ein Unterschied in der Voreinstellung. `adf.test()` in R nimmt eine Regression **mit Trendterm**, es prüft also auf Trendstationarität und findet sie hier korrekt. `adfuller()` in Python nimmt voreingestellt nur eine Konstante (`regression=\"c\"`) und sieht den Trend als Nichtstationarität. Mit `regression=\"ct\"` stimmen beide überein. Wer den Test berichtet, nennt die Regressionsvariante dazu. |\n| **Die Saisonreihe gilt allen Tests als stationär** | Und formal haben sie recht: Eine rein saisonale Reihe hat konstanten Mittelwert über ganze Perioden und keine Einheitswurzel. Für die Modellierung ist sie trotzdem nicht brauchbar, die Saison muss weg. |\n\n::: {.note-box}\n**Die wichtigste Lehre dieses Beispiels** steht in der Zeile \"mit Saison\": Beide\nTests melden Stationarität, und die ACF aus Beispiel 1 zeigt eine unübersehbare\nSaisonstruktur mit Spitzen bei 12 und 24.\n\nDie Tests prüfen **nur die Einheitswurzel**, also den stochastischen Trend. Sie\nsagen nichts über Saison, nichts über wachsende Streuung und nichts darüber, ob\nman richtig differenziert hat. Deshalb gilt die Rangfolge:\n\n> **Die Grafik entscheidet, der Test bestätigt.**\n\nZwei weitere Einschränkungen: Der ADF-Test hat bei kurzen Reihen wenig Schärfe\nund findet eine Einheitswurzel dann nicht, obwohl sie vorliegt. Und die Zeile\n\"mit Trend\" zeigt, wie stark das Ergebnis an den Voreinstellungen hängt, ein\nweiterer Grund, dem Bild mehr zu trauen als dem p-Wert.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Reihe ist nicht stationär (ADF p = 0.20 in R beziehungsweise 0.71 in\n> Python, KPSS p = 0.01). Nach einfacher\n> Differenzenbildung sprechen beide Tests für Stationarität (ADF p < .001,\n> KPSS p > 0.1), und die ACF der differenzierten Reihe zeigt keine\n> Autokorrelation ausserhalb der Konfidenzgrenzen.\n\n### Beispiel 5: Saisonales Differenzieren\n\n#### Frage und Datenlage\n\nDie Saisonreihe aus Beispiel 1 besteht die Stationaritätstests, ist aber\noffensichtlich nicht brauchbar. Was leistet saisonales Differenzieren,\n$y_t - y_{t-12}$?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsaison_diff <- diff(mit_saison, lag = 12)\n\npar(mfrow = c(2, 2), mar = c(3.5, 4, 2.5, 1))\nplot(mit_saison, ylab = \"\", main = \"mit Saison\")\nacf(mit_saison, lag.max = 30, main = \"dessen ACF\")\nplot(saison_diff, ylab = \"\", main = \"saisonal differenziert\")\nabline(h = 0, lty = 2)\nacf(saison_diff, lag.max = 30, main = \"dessen ACF\")\npar(mfrow = c(1, 1))\n\nacf_werte <- function(reihe, stellen) {\n  round(acf(reihe, lag.max = 24, plot = FALSE)$acf[stellen + 1], 3)\n}\nrbind(vorher = acf_werte(mit_saison, c(1, 6, 12, 24)),\n      nachher = acf_werte(saison_diff, c(1, 6, 12, 24)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          [,1]   [,2]   [,3]   [,4]\nvorher   0.708 -0.800  0.729  0.629\nnachher -0.076 -0.044 -0.390 -0.052\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(sd_vorher = sd(mit_saison), sd_nachher = sd(saison_diff),\n        verlorene_werte = 12), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      sd_vorher      sd_nachher verlorene_werte \n         18.697          11.281          12.000 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 5: oben die Saisonreihe und ihre ACF, unten dieselbe nach saisonalem Differenzieren.](stationaritaet-acf-pacf_files/figure-html/fig-b5-st-r-1.png){#fig-b5-st-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nsaison_diff = mit_saison.diff(12).dropna()\n\nfig, achsen = plt.subplots(2, 2, figsize=(7, 4.6))\nachsen[0, 0].plot(mit_saison, color=\"#2166ac\")\nachsen[0, 0].set_title(\"mit Saison\")\nplot_acf(mit_saison, ax=achsen[0, 1], lags=30, title=\"dessen ACF\")\nachsen[1, 0].plot(saison_diff, color=\"#b2182b\")\nachsen[1, 0].axhline(0, ls=\"--\", color=\"black\", lw=0.8)\nachsen[1, 0].set_title(\"saisonal differenziert\")\nplot_acf(saison_diff, ax=achsen[1, 1], lags=30, title=\"dessen ACF\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselbe Gegenüberstellung in Python.](stationaritaet-acf-pacf_files/figure-html/fig-b5-st-py-1.png){#fig-b5-st-py width=100%}\n:::\n\n```{.python .cell-code}\nstellen = [1, 6, 12, 24]\nprint(pd.DataFrame({\n    \"vorher\": acf(mit_saison, nlags=24)[stellen].round(3),\n    \"nachher\": acf(saison_diff, nlags=24)[stellen].round(3),\n}, index=[f\"k={k}\" for k in stellen]).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           k=1    k=6   k=12   k=24\nvorher   0.708 -0.800  0.729  0.629\nnachher -0.076 -0.044 -0.390 -0.052\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"sd vorher: \", round(float(mit_saison.std(ddof=1)), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsd vorher:  18.697\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"sd nachher:\", round(float(saison_diff.std(ddof=1)), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsd nachher: 11.281\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"verlorene Werte:\", len(mit_saison) - len(saison_diff))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nverlorene Werte: 12\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| | k=1 | k=6 | k=12 | k=24 |\n|---|---|---|---|---|\n| vorher | 0.708 | **-0.800** | **0.729** | **0.629** |\n| nachher | -0.076 | -0.044 | **-0.390** | -0.052 |\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| ACF(12) vorher: **0.729** | Der Monat und derselbe Monat im Vorjahr sind stark korreliert. Bei k=24 noch 0.629, die Saison hört nicht auf. |\n| ACF(6) vorher: **-0.800** | Der Gegenmonat: Wo im Sommer ein Hoch ist, ist im Winter ein Tief. |\n| ACF(12) nachher: **-0.390** | Vom starken positiven Wert bleibt ein deutlich negativer übrig. **Das ist kein Fehler**, sondern die bekannte Nebenwirkung: Saisonales Differenzieren erzeugt eine saisonale MA-Struktur, genau wie einfaches Differenzieren eine gewöhnliche. Sie wird in einem [SARIMA-Modell](arima-sarima.qmd) durch einen Term $Q = 1$ abgebildet. |\n| ACF(1) nachher: -0.076 | Innerhalb der Konfidenzgrenzen. Auf der kurzen Zeitskala ist nichts mehr übrig. |\n| Streuung 18.70 → 11.28 | Deutlich gesunken; das saisonale Differenzieren war also angebracht. |\n| verlorene Werte | **12** | Die ersten zwölf Monate haben keinen Vorjahreswert. Bei einer kurzen Reihe ist das ein spürbarer Preis. |\n\n::: {.note-box}\n**Die Reihenfolge, wenn beides nötig ist:** Zuerst saisonal differenzieren, dann\nprüfen, ob noch eine gewöhnliche Differenz nötig ist. Oft erledigt das saisonale\nDifferenzieren den Trend gleich mit, denn $y_t - y_{t-12}$ entfernt auch einen\nlinearen Trend bis auf eine Konstante.\n\n**Und die Warnung:** Zwei Differenzen kosten 13 Beobachtungen und erzeugen zwei\nMA-Strukturen. Im Zweifel eine weniger.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Reihe zeigt eine ausgeprägte Jahressaison (ACF bei k=12 gleich 0.73, bei\n> k=24 gleich 0.63). Nach saisonalem Differenzieren mit Abstand 12 sinkt die\n> Streuung von 18.7 auf 11.3, und ausserhalb der Konfidenzgrenzen bleibt nur der\n> Wert bei k=12 von -0.39, der auf einen saisonalen MA-Term hinweist.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nDie ACF einer Reihe fällt über zwanzig Abstände hinweg nur langsam ab. Was ist zu\ntun?\n\n- [x] Die Reihe ist nicht stationär; Trend entfernen ~ Richtig. Eine langsam\n      abfallende ACF ist das klassische Zeichen. Ob differenziert oder detrendet\n      wird, entscheidet sich danach, die ACF unterscheidet die beiden Trendarten\n      nicht.\n- [ ] Ein Modell mit hoher Ordnung anpassen ~ Damit modelliert man den Trend mit\n      vielen Parametern statt ihn zu entfernen.\n- [ ] Nichts, langsames Abfallen ist normal ~ Bei stationären Reihen fällt die\n      ACF schnell ab.\n:::\n\n::: {.quiz}\nDer ADF-Test ergibt p = 0.42. Was folgt?\n\n- [ ] Die Reihe ist stationär, der p-Wert ist gross ~ Die Richtung ist vertauscht:\n      Beim ADF-Test lautet die Nullhypothese Nichtstationarität.\n- [x] Nichtstationarität kann nicht verworfen werden ~ Richtig. Ein grosser p-Wert\n      heisst hier: kein Beleg für Stationarität. Zusammen mit einer langsam\n      abfallenden ACF spricht das für Differenzieren.\n- [ ] Der Test ist ungültig ~ Er ist gültig, nur schwach bei kurzen Reihen.\n:::\n\n::: {.quiz}\nNach dem Differenzieren steigt die Streuung von 9.3 auf 12.3 und die ACF beim\nersten Abstand beträgt -0.35. Was heisst das?\n\n- [x] Es wurde überdifferenziert ~ Richtig. Beide Zeichen zusammen sind das\n      Kennzeichen: Differenzieren einer bereits stationären Reihe erzeugt eine\n      künstliche MA(1)-Struktur mit einer ACF(1) nahe -0.5 und vergrössert die\n      Streuung um etwa den Faktor Wurzel zwei.\n- [ ] Es muss ein zweites Mal differenziert werden ~ Das verschärft das Problem;\n      im Beispiel sinkt die ACF(1) dann auf -0.52.\n- [ ] Die Reihe enthält einen Ausreisser ~ Möglich, erklärt aber nicht die\n      systematisch negative Autokorrelation.\n:::\n\n::: {.quiz}\nDie PACF bricht nach dem zweiten Abstand ab, die ACF fällt allmählich. Welches\nModell?\n\n- [x] AR(2) ~ Richtig. Eine abbrechende PACF bei $k = p$ mit allmählich fallender\n      ACF ist die Signatur eines AR($p$)-Prozesses; die Ordnung wird aus der PACF\n      abgelesen.\n- [ ] MA(2) ~ Dort wäre es umgekehrt: Die ACF bricht ab, die PACF fällt\n      allmählich.\n- [ ] ARMA(2,2) ~ Bei einem gemischten Prozess fallen **beide** allmählich ab und\n      die Ordnung ist aus den Korrelogrammen nicht ablesbar.\n:::\n\n::: {.quiz}\nADF und KPSS melden für eine Reihe mit deutlicher Jahressaison beide\nStationarität. Was folgt?\n\n- [x] Die Tests prüfen nur die Einheitswurzel, nicht die Saison ~ Richtig. Formal\n      haben sie recht, die Reihe hat konstanten Mittelwert über ganze Perioden.\n      Für die Modellierung muss die Saison trotzdem weg, sichtbar wird sie in\n      der ACF an den Spitzen bei Vielfachen der Periode.\n- [ ] Die Reihe ist damit modellierbar ~ Die Saisonstruktur ist unbehandelt.\n- [ ] Einer der beiden Tests muss falsch gerechnet sein ~ Beide sind korrekt und\n      beantworten eine andere Frage als die gestellte.\n:::\n\n## Verlinkte Ressourcen\n\n- [Forecasting: Principles and Practice, Kapitel 9](https://otexts.com/fpp3/stationarity.html)\n- [tseries: adf.test und kpss.test](https://cran.r-project.org/web/packages/tseries/tseries.pdf)\n- [statsmodels: Stationaritätstests](https://www.statsmodels.org/stable/tsa.html#stationarity-and-unit-root-tests)\n",
    "supporting": [
      "stationaritaet-acf-pacf_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}