{
  "hash": "02fc86b2c7b0e96429507d54e199675e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Korrelationstests\"\ndescription: \"Pearson, Spearman und Kendall: Zusammenhang prüfen und richtig deuten.\"\ncategories: [\"Hypothesentests\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"ESDS\", \"STATDA\"]\nseitentyp: methode\nstand: entwurf\norder: 60\n---\n\n\n\n\n\nAlle Beispiele rechnen mit fest eingetragenen Zahlen, damit R und Python\ndieselben Daten sehen und jeder Wert im Text nachprüfbar ist.\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Hängen zwei Grössen zusammen, wie eng, und lässt sich der Zusammenhang vom Zufall unterscheiden? |\n| Zielvariable | keine; beide Grössen sind gleichberechtigt |\n| Eingang | zwei metrische Grössen für Pearson, mindestens ordinale für Spearman und Kendall |\n| Was die Methode liefert | Korrelationskoeffizient mit Konfidenzintervall, Teststatistik, Freiheitsgrade, p-Wert |\n| R-Funktion | `cor.test(x, y)`, mit `method = \"spearman\"` oder `\"kendall\"` |\n| Python-Funktion | `pg.corr(x, y, method=\"pearson\")`, alternativ `stats.pearsonr()` und `stats.spearmanr()` |\n| Verwandte Methoden | [Korrelation](../grundlagen/korrelation.qmd), [einfache lineare Regression](../regression/einfache-lineare-regression.qmd) |\n\nDie [Konzeptseite zur Korrelation](../grundlagen/korrelation.qmd) erklärt, was\nein Korrelationskoeffizient misst. Diese Seite behandelt den Test dazu und die\nWahl zwischen den drei Verfahren.\n\n## Wann diese Methode, wann nicht\n\nTypische Fragestellungen: Hängt der Absatz mit der Temperatur zusammen, die\nBearbeitungszeit mit der Auftragsgrösse, die Zufriedenheit mit der Wartezeit?\nGemeinsam ist ihnen, dass **keine** der beiden Grössen als Zielgrösse\nausgezeichnet ist. Sobald eine vorhergesagt werden soll, ist die\n[Regression](../regression/einfache-lineare-regression.qmd) das passende\nVerfahren.\n\n| Situation | Stattdessen |\n|---|---|\n| Eine Grösse soll aus der anderen vorhergesagt werden | [einfache lineare Regression](../regression/einfache-lineare-regression.qmd) |\n| Weitere Grössen sollen konstant gehalten werden | [multiple lineare Regression](../regression/multiple-lineare-regression.qmd) oder Partialkorrelation |\n| Beide Merkmale sind kategorial | [Chi-Quadrat-Tests](chi-quadrat-tests.qmd), Cramérs V |\n| Ein Merkmal ist zweistufig, das andere metrisch | [t-Test für zwei Stichproben](t-test-zwei-stichproben.qmd) |\n| Der Zusammenhang ist nicht monoton, etwa U-förmig | keiner der drei Koeffizienten; das Streudiagramm ansehen und ein Modell wählen |\n| Es geht um Übereinstimmung, nicht um Zusammenhang | Bland-Altman-Verfahren oder Intraklassenkorrelation |\n\nDie letzte Zeile trennt zwei Dinge, die oft verwechselt werden. Zwei Messgeräte,\nvon denen eines konstant 5 Einheiten zu viel anzeigt, korrelieren perfekt und\nstimmen trotzdem nie überein.\n\n## Grundidee und Modell\n\nAlle drei Koeffizienten messen Zusammenhang auf einer Skala von -1 bis +1, aber\nsie messen Verschiedenes.\n\n| Koeffizient | Was er misst | Grundlage |\n|---|---|---|\n| Pearson $r$ | Stärke des **linearen** Zusammenhangs | Produkte der standardisierten Abweichungen vom Mittelwert |\n| Spearman $\\rho$ | Stärke des **monotonen** Zusammenhangs | Pearson-Korrelation der Ränge |\n| Kendall $\\tau$ | Anteil gleichgerichteter Paare | Vergleich aller Paare: Steigen beide Werte gemeinsam? |\n\n$$r = \\frac{\\sum (x_i - \\bar{x})(y_i - \\bar{y})}{\\sqrt{\\sum (x_i - \\bar{x})^2 \\sum (y_i - \\bar{y})^2}}$$\n\nGetestet wird bei allen dreien dieselbe Nullhypothese: In der Grundgesamtheit\nbesteht kein Zusammenhang, der Koeffizient ist null. Für Pearson läuft der Test\nüber\n\n$$t = r \\sqrt{\\frac{n-2}{1-r^2}}$$\n\nmit $n-2$ Freiheitsgraden. Daraus folgt eine nützliche Einsicht: Ob ein\ngegebenes $r$ signifikant wird, hängt allein am Stichprobenumfang. Bei $n = 10$\nbraucht es $r > 0.63$, bei $n = 500$ genügt $r > 0.09$.\n\nDas Konfidenzintervall entsteht nicht direkt aus dieser Formel, sondern über die\nFisher-z-Transformation, weil die Verteilung von $r$ nahe -1 und +1 stark schief\nist. Deshalb liegt das Intervall auch nicht symmetrisch um $r$.\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Gilt für | Prüfung | Folge bei Verletzung |\n|---|---|---|---|\n| Unabhängige Beobachtungspaare | alle drei | Erhebungsdesign | p-Wert wertlos; bei Zeitreihen ist die Voraussetzung fast nie erfüllt |\n| Linearer Zusammenhang | Pearson | Streudiagramm | $r$ unterschätzt einen vorhandenen Zusammenhang, siehe Beispiel 2 |\n| Monotoner Zusammenhang | Spearman, Kendall | Streudiagramm | bei U-förmigem Verlauf liefern auch sie nahe null |\n| Metrische Skala | Pearson | [Skalenniveau](../grundlagen/skalenniveaus.qmd) | Mittelwerte sind nicht definiert |\n| Annähernd normalverteilte Werte | Test und Intervall bei Pearson | [QQ-Plot](../wahrscheinlichkeit/qq-plots.qmd) | p-Wert und Intervall werden unzuverlässig, besonders bei kleinem n |\n| Keine einflussreichen Ausreisser | Pearson stark, Spearman kaum | Streudiagramm | ein einzelner Punkt kann $r$ von 0.3 auf 0.96 heben, siehe Beispiel 3 |\n\n**Das Streudiagramm steht vor jeder Korrelationsrechnung.** Kein\nKorrelationskoeffizient kann die Form des Zusammenhangs beschreiben, und\nmehrere völlig verschiedene Punktwolken können denselben Wert liefern.\n\n## Output lesen\n\nR, `cor.test()`:\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| `t` | Teststatistik bei Pearson | folgt aus $r$ und $n$; sie enthält keine zusätzliche Information |\n| `df` | Freiheitsgrade | $n-2$ |\n| `p-value` | Wahrscheinlichkeit eines mindestens so grossen Betrags bei fehlendem Zusammenhang | sagt nichts über die Stärke |\n| `95 percent confidence interval` | Intervall für den wahren Koeffizienten | die aussagekräftigste Zeile; sie ist bei kleinem n erschreckend breit |\n| `sample estimates: cor` | der Koeffizient selbst | die Zahl, um die es eigentlich geht |\n| `S` bei Spearman | Summe der quadrierten Rangdifferenzen | nicht direkt deutbar; $\\rho$ steht darunter |\n| `T` oder `z` bei Kendall | Teststatistik | je nach Variante und Stichprobengrösse |\n| Warnung `Cannot compute exact p-value with ties` | Bindungen in den Rängen | R weicht auf eine Näherung aus; bei Spearman und Kendall häufig |\n| kein Konfidenzintervall bei Spearman und Kendall | fehlt in R | über Bootstrap zu bekommen; pingouin gibt eines aus |\n\nPython, `pg.corr()` liefert eine Zeile:\n\n| Spalte | Was sie sagt | Unterschied zu R |\n|---|---|---|\n| `n` | Anzahl vollständiger Paare | in R nicht ausgegeben |\n| `r` | Koeffizient | wie `cor` |\n| `CI95` | Konfidenzintervall | auch für Spearman und Kendall, anders als in R |\n| `p-val` bzw. `p_val` | p-Wert | wie `p-value` |\n| `BF10` | Bayes-Faktor bei Pearson | in R nicht enthalten |\n| `power` | erreichte Power | in R nicht enthalten |\n\n## Interpretationsfallen\n\n- **Korrelation ist keine Kausalität.** Der Satz ist abgegriffen und trotzdem\n  der häufigste Fehler. Eine dritte, nicht erhobene Grösse kann beide treiben.\n- **$r = 0$ heisst nicht \"kein Zusammenhang\".** Es heisst \"kein linearer\n  Zusammenhang\". Eine perfekte Parabel liefert $r$ nahe null.\n- **Signifikant heisst nicht stark.** Bei $n = 500$ wird $r = 0.1$ signifikant\n  und erklärt ein Prozent der Streuung.\n- **$r$ ist kein Prozentwert.** Erst $r^2$ ist ein Anteil. Von $r = 0.5$ auf\n  $r = 0.7$ verdoppelt sich der erklärte Anteil beinahe.\n- **Ausreisser bestimmen $r$.** Ein einzelner Punkt weit ausserhalb kann eine\n  Korrelation erzeugen oder verschwinden lassen.\n- **Eingeschränkte Wertebereiche senken $r$.** Wer nur Werte aus einem schmalen\n  Ausschnitt erhebt, misst eine kleinere Korrelation als in der ganzen\n  Grundgesamtheit vorhanden ist.\n- **Gemischte Gruppen erzeugen Scheinkorrelationen.** Zwei Teilgruppen ohne\n  internen Zusammenhang ergeben zusammen eine deutliche Korrelation, wenn sie\n  in beiden Grössen verschoben liegen. Deshalb das Streudiagramm.\n- **Bei Zeitreihen ist die Unabhängigkeit verletzt.** Zwei beliebige steigende\n  Reihen korrelieren hoch, ohne dass ein Zusammenhang besteht.\n\n## Ergebnis berichten\n\nVorlage für den Ergebnissatz:\n\n> [Grösse 1] und [Grösse 2] hängen zusammen: $r$ = [Wert],\n> 95-Prozent-Konfidenzintervall [unten] bis [oben], t([df]) = [t], p = [p],\n> n = [n]. Der Zusammenhang erklärt [r²] der Streuung.\n\nGenannt werden: das verwendete Verfahren und **warum** es gewählt wurde, der\nKoeffizient mit Konfidenzintervall, Teststatistik mit Freiheitsgraden, p-Wert\nund n. Dazu gehört die Feststellung, dass das Streudiagramm angesehen wurde,\nund bei Ausschlüssen die Begründung.\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt eines Korrelationstests |\n|---|---|\n| [Korrelation](../grundlagen/korrelation.qmd) | die Kennzahl allein genügt, ohne Test |\n| [Einfache lineare Regression](../regression/einfache-lineare-regression.qmd) | eine Gerade mit Steigung in der Einheit der Sache wird gebraucht |\n| [Multiple lineare Regression](../regression/multiple-lineare-regression.qmd) | weitere Einflussgrössen sollen konstant gehalten werden |\n| [Chi-Quadrat-Tests](chi-quadrat-tests.qmd) | beide Merkmale kategorial |\n| [Nichtparametrische Tests](nichtparametrische-tests.qmd) | Frage nach Unterschied statt nach Zusammenhang |\n\n::: {.note-box}\nBei genau einem Prädiktor sind der Pearson-Korrelationstest und der t-Test der\nSteigung in der [einfachen linearen Regression](../regression/einfache-lineare-regression.qmd)\n**derselbe Test**: gleiche Teststatistik, gleiche Freiheitsgrade, gleicher\np-Wert. Sie unterscheiden sich nur darin, was sie zusätzlich ausgeben.\n:::\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Temperatur und Absatz\n\n#### Frage und Datenlage\n\nAn zwanzig Tagen wurden die Höchsttemperatur in Grad Celsius und der Absatz von\nKaltgetränken in Flaschen erfasst. Die Frage lautet: Hängen die beiden Grössen\nzusammen, und wie eng?\n\nEs soll nichts vorhergesagt werden, und keine der beiden Grössen ist\nausgezeichnet. Damit ist der Korrelationstest passend und nicht die Regression.\n\n#### Voraussetzungen prüfen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntemperatur <- c(12.4, 14.1, 15.3, 16.0, 17.2, 18.5, 19.1, 20.4, 21.3, 22.0,\n                22.8, 23.5, 24.2, 25.1, 26.3, 27.0, 28.4, 29.2, 30.5, 31.1)\nabsatz <- c(118, 137, 122, 151, 145, 168, 152, 183, 175, 190,\n            181, 199, 205, 196, 228, 212, 235, 247, 239, 262)\n\npar(mar = c(4, 4, 2, 1))\nplot(temperatur, absatz, pch = 16, col = \"grey30\",\n     xlab = \"Höchsttemperatur (°C)\", ylab = \"Absatz (Flaschen)\")\nlines(lowess(temperatur, absatz), col = \"firebrick\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![Beispiel 1: Streudiagramm mit Glättungslinie.](korrelationstests_files/figure-html/fig-b1-kor-voraussetzungen-r-1.png){#fig-b1-kor-voraussetzungen-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport statsmodels.api as sm\n\ntemperatur = np.array([12.4, 14.1, 15.3, 16.0, 17.2, 18.5, 19.1, 20.4, 21.3,\n                       22.0, 22.8, 23.5, 24.2, 25.1, 26.3, 27.0, 28.4, 29.2,\n                       30.5, 31.1])\nabsatz = np.array([118, 137, 122, 151, 145, 168, 152, 183, 175, 190,\n                   181, 199, 205, 196, 228, 212, 235, 247, 239, 262])\n\nfig, achse = plt.subplots(figsize=(7, 3.4))\nachse.scatter(temperatur, absatz, s=18, color=\"0.3\")\nglatt = sm.nonparametric.lowess(absatz, temperatur)\nachse.plot(glatt[:, 0], glatt[:, 1], color=\"firebrick\", linewidth=2)\nachse.set_xlabel(\"Höchsttemperatur (°C)\")\nachse.set_ylabel(\"Absatz (Flaschen)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Darstellung in Python.](korrelationstests_files/figure-html/fig-b1-kor-voraussetzungen-py-1.png){#fig-b1-kor-voraussetzungen-py width=100%}\n:::\n:::\n\n\n:::\n\nDie Punkte steigen gleichmässig an, die Glättungslinie verläuft praktisch\ngerade, und es gibt keinen Punkt weit ausserhalb der Wolke. Der Zusammenhang ist\nlinear, damit ist Pearson das passende Verfahren.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(temperatur, absatz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  temperatur and absatz\nt = 19.396, df = 18, p-value = 1.635e-13\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.9413081 0.9910098\nsample estimates:\n      cor \n0.9769019 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(pg.corr(temperatur, absatz).round(4).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            pearson\nn                20\nr            0.9769\nCI95   [0.94, 0.99]\np_val           0.0\nBF10      1.855e+10\npower           1.0\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| `cor` bzw. `r` | 0.977 | Pearson-Korrelation | Ein sehr enger linearer Zusammenhang. Werte über 0.9 sind in erhobenen Daten selten und meist ein Hinweis darauf, dass beide Grössen von derselben Ursache getrieben werden. |\n| `t` | 19.396 | Teststatistik | Sie folgt allein aus $r$ und $n$ und enthält keine zusätzliche Information. |\n| `df` | 18 | Freiheitsgrade | $n-2$, also 20 minus 2. |\n| `p-value` | 1.6e-13 | Wahrscheinlichkeit eines mindestens so grossen Betrags ohne Zusammenhang | Praktisch ausgeschlossen. |\n| `95 percent confidence interval` | 0.941 bis 0.991 | Intervall für den wahren Koeffizienten | Die aussagekräftigste Zeile. Beachten Sie die Unsymmetrie: von 0.977 sind es 0.036 nach unten und nur 0.014 nach oben. Das liegt an der Fisher-z-Transformation und daran, dass $r$ bei 1 endet. |\n| $r^2$ | 0.954 | Anteil gemeinsamer Streuung | Rund 95 Prozent der Absatzschwankung gehen mit der Temperatur einher. Diese Zahl steht in keiner der beiden Ausgaben und muss selbst gebildet werden. |\n| `power` (nur Python) | nahe 1 | | Bei diesem Effekt und n = 20 hätte der Test kaum etwas übersehen können. |\n\n#### Interpretation und Ergebnissatz\n\nDer Zusammenhang ist eng, und trotzdem sagt er nichts über Ursachen. Denkbar\nist, dass Wärme den Durst treibt; ebenso denkbar ist, dass an warmen Tagen mehr\nMenschen unterwegs sind und deshalb mehr gekauft wird. Die Korrelation ist\nsymmetrisch und kennt keine Richtung.\n\nWer eine Aussage in Flaschen je Grad braucht, ist beim Korrelationstest falsch.\nDer Koeffizient hat keine Einheit; die Steigung liefert die\n[Regression](../regression/einfache-lineare-regression.qmd).\n\n> Höchsttemperatur und Absatz hängen eng zusammen: $r$ = 0.98,\n> 95-Prozent-Konfidenzintervall 0.94 bis 0.99, t(18) = 19.40, p < 0.001,\n> n = 20. Der Zusammenhang erklärt rund 95 Prozent der gemeinsamen Streuung.\n> Das Streudiagramm zeigt einen linearen Verlauf ohne auffällige Punkte. Über\n> die Richtung der Wirkung lässt sich daraus nichts ableiten.\n\n### Beispiel 2: Monoton, aber gekrümmt\n\n#### Frage und Datenlage\n\nFünfzehn Messungen eines Wachstumsvorgangs: Der Wert verdoppelt sich in\ngleichmässigen Abständen. Der Zusammenhang ist perfekt monoton und deutlich\ngekrümmt. Das Beispiel zeigt, warum die Wahl zwischen Pearson und Spearman\nkeine Geschmacksfrage ist.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschritt <- 1:15\nmesswert <- c(1.4, 1.9, 2.7, 3.8, 5.3, 7.4, 10.3, 14.4,\n              20.1, 28.0, 39.1, 54.6, 76.2, 106.3, 148.4)\n\npar(mar = c(4, 4, 2, 1))\nplot(schritt, messwert, pch = 16, col = \"grey30\",\n     xlab = \"Schritt\", ylab = \"Messwert\")\n\ncor.test(schritt, messwert)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  schritt and messwert\nt = 6.1142, df = 13, p-value = 3.695e-05\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.6248274 0.9530902\nsample estimates:\n      cor \n0.8613825 \n```\n\n\n:::\n\n```{.r .cell-code}\ncor.test(schritt, messwert, method = \"spearman\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tSpearman's rank correlation rho\n\ndata:  schritt and messwert\nS = 1.2434e-13, p-value < 2.2e-16\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\nrho \n  1 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 2: perfekt monoton, aber nicht linear.](korrelationstests_files/figure-html/fig-b2-kor-r-1.png){#fig-b2-kor-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nschritt = np.arange(1, 16)\nmesswert = np.array([1.4, 1.9, 2.7, 3.8, 5.3, 7.4, 10.3, 14.4,\n                     20.1, 28.0, 39.1, 54.6, 76.2, 106.3, 148.4])\n\nfig, achse = plt.subplots(figsize=(7, 3.2))\nachse.scatter(schritt, messwert, s=18, color=\"0.3\")\nachse.set_xlabel(\"Schritt\")\nachse.set_ylabel(\"Messwert\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselbe Darstellung in Python.](korrelationstests_files/figure-html/fig-b2-kor-py-1.png){#fig-b2-kor-py width=100%}\n:::\n\n```{.python .cell-code}\nfor art in (\"pearson\", \"spearman\", \"kendall\"):\n    zeile = pg.corr(schritt, messwert, method=art).round(4)\n    print(f\"{art:9s} r = {float(zeile['r'].iloc[0]):+.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npearson   r = +0.8614\nspearman  r = +1.0000\nkendall   r = +1.0000\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Koeffizient | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Pearson $r$ | 0.861 | Sieht nach einem starken, aber unvollkommenen Zusammenhang aus. Der Eindruck ist falsch. |\n| Pearson $r^2$ | 0.742 | Es fehlen scheinbar 26 Prozent der Streuung. Tatsächlich fehlt nichts: Was $r$ nicht erfasst, ist die Krümmung, nicht Zufall. |\n| Spearman $\\rho$ | 1.000 | Perfekt. Jeder Schritt liefert einen höheren Wert als der vorige, mehr verlangt ein monotoner Zusammenhang nicht. |\n| Spearman `S` | 0 | Die Summe der quadrierten Rangdifferenzen. Null bedeutet: Die Rangfolgen sind identisch. |\n| Kendall $\\tau$ | 1.000 | Ebenfalls perfekt. Von allen 105 Paaren steigt keines gegenläufig. |\n\nDer Vergleich macht den Unterschied greifbar. Pearson misst, wie gut die Punkte\nauf einer **Geraden** liegen; sie tun es nicht, also bleibt $r$ unter 1. Spearman\nund Kendall messen, ob die Reihenfolge übereinstimmt; sie tut es vollständig,\nalso erreichen beide den Höchstwert.\n\n::: {.note-box}\nHier wäre es falsch, einfach Spearman zu berichten und zufrieden zu sein. Die\ninteressante Erkenntnis ist die **Form**: Der Vorgang wächst nicht linear,\nsondern exponentiell. Eine Korrelation von 1.000 verdeckt das eher, als sie es\nzeigt. Wer die Form braucht, logarithmiert die Zielgrösse und rechnet dann\nweiter; nach dem Logarithmieren wäre auch Pearsons $r$ praktisch 1.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Zwischen Schritt und Messwert besteht ein perfekt monotoner Zusammenhang\n> (Spearman $\\rho$ = 1.00, n = 15). Pearsons $r$ beträgt 0.86 und unterschätzt\n> den Zusammenhang, weil der Verlauf gekrümmt ist; das Streudiagramm zeigt\n> exponentielles Wachstum. Für die weitere Auswertung wurde der Messwert\n> logarithmiert.\n\n### Beispiel 3: Ein Punkt erzeugt die Korrelation\n\n#### Frage und Datenlage\n\nNeunzehn Betriebe, erfasst sind die durchschnittliche Auftragsgrösse und die\nBearbeitungsdauer. Ein zwanzigster Betrieb kommt hinzu, der in beiden Grössen\nweit ausserhalb liegt.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroesse <- c(4.1, 5.2, 4.8, 5.5, 4.3, 5.1, 4.6, 5.3, 4.9, 5.0,\n             4.4, 5.4, 4.7, 5.2, 4.5, 5.1, 4.8, 5.0, 4.6)\ndauer <- c(22, 19, 24, 21, 20, 23, 18, 25, 21, 22,\n           19, 24, 20, 23, 21, 19, 25, 20, 22)\n\ngroesse_mit <- c(groesse, 12.0)\ndauer_mit <- c(dauer, 60)\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nplot(groesse, dauer, pch = 16, col = \"grey30\", main = \"ohne den Fall\",\n     xlab = \"Auftragsgrösse\", ylab = \"Dauer (min)\")\nplot(groesse_mit, dauer_mit, pch = 16, col = \"grey30\", main = \"mit dem Fall\",\n     xlab = \"Auftragsgrösse\", ylab = \"Dauer (min)\")\npoints(12.0, 60, pch = 16, col = \"firebrick\", cex = 1.4)\npar(mfrow = c(1, 1))\n\ncor.test(groesse, dauer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  groesse and dauer\nt = 1.255, df = 17, p-value = 0.2265\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.1878627  0.6583304\nsample estimates:\n      cor \n0.2911939 \n```\n\n\n:::\n\n```{.r .cell-code}\ncor.test(groesse_mit, dauer_mit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  groesse_mit and dauer_mit\nt = 14.984, df = 18, p-value = 1.313e-11\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.9049728 0.9852096\nsample estimates:\n      cor \n0.9621729 \n```\n\n\n:::\n\n```{.r .cell-code}\ncor.test(groesse_mit, dauer_mit, method = \"spearman\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tSpearman's rank correlation rho\n\ndata:  groesse_mit and dauer_mit\nS = 801.22, p-value = 0.08258\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n      rho \n0.3975777 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: dieselben 19 Punkte, einmal ohne und einmal mit dem zwanzigsten.](korrelationstests_files/figure-html/fig-b3-kor-r-3.png){#fig-b3-kor-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ngroesse = np.array([4.1, 5.2, 4.8, 5.5, 4.3, 5.1, 4.6, 5.3, 4.9, 5.0,\n                    4.4, 5.4, 4.7, 5.2, 4.5, 5.1, 4.8, 5.0, 4.6])\ndauer = np.array([22, 19, 24, 21, 20, 23, 18, 25, 21, 22,\n                  19, 24, 20, 23, 21, 19, 25, 20, 22])\ngroesse_mit = np.append(groesse, 12.0)\ndauer_mit = np.append(dauer, 60)\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nachsen[0].scatter(groesse, dauer, s=18, color=\"0.3\")\nachsen[0].set_title(\"ohne den Fall\")\nachsen[1].scatter(groesse_mit, dauer_mit, s=18, color=\"0.3\")\nachsen[1].scatter([12.0], [60], s=50, color=\"firebrick\")\nachsen[1].set_title(\"mit dem Fall\")\nfor achse in achsen:\n    achse.set_xlabel(\"Auftragsgrösse\")\n    achse.set_ylabel(\"Dauer (min)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselbe Gegenüberstellung in Python.](korrelationstests_files/figure-html/fig-b3-kor-py-1.png){#fig-b3-kor-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(\"ohne  Pearson :\", pg.corr(groesse, dauer).round(4).to_dict(\"records\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nohne  Pearson : [{'n': 19, 'r': 0.2912, 'CI95': array([-0.19,  0.66]), 'p_val': 0.2265, 'BF10': '0.562', 'power': 0.2319}]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"mit   Pearson :\", pg.corr(groesse_mit, dauer_mit).round(4).to_dict(\"records\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmit   Pearson : [{'n': 20, 'r': 0.9622, 'CI95': array([0.9 , 0.99]), 'p_val': 0.0, 'BF10': '3.773e+08', 'power': 1.0}]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"mit   Spearman:\", pg.corr(groesse_mit, dauer_mit,\n                                 method=\"spearman\").round(4).to_dict(\"records\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmit   Spearman: [{'n': 20, 'r': 0.3976, 'CI95': array([-0.05,  0.71]), 'p_val': 0.0826, 'power': 0.4254}]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Kennzahl | Ohne den Fall (n = 19) | Mit dem Fall (n = 20) | Wie das zu lesen ist |\n|---|---|---|---|\n| Pearson $r$ | 0.291 | 0.962 | Eine einzige zusätzliche Beobachtung hebt die Korrelation von schwach auf nahezu perfekt. |\n| Konfidenzintervall | -0.19 bis 0.66 | 0.90 bis 0.99 | Die beiden Intervalle überschneiden sich nicht einmal. |\n| `t` | 1.255 | 14.984 | |\n| `p-value` | 0.226 | 1.3e-11 | Aus einem Nullbefund wird ein hochsignifikantes Ergebnis. |\n| $r^2$ | 0.085 | 0.926 | Von 8 auf 93 Prozent erklärte Streuung. |\n| Spearman $\\rho$ (mit dem Fall) | | 0.398 | Der Rangkoeffizient bleibt bei 0.40 und ist mit p = 0.08 nicht signifikant. Für ihn ist der Ausreisser einfach der grösste von zwanzig Werten, nicht ein zwanzigfach entfernter. |\n\nDer Grund steckt in der Formel: Pearsons $r$ arbeitet mit Abweichungen vom\nMittelwert, und ein Punkt, der in **beiden** Grössen weit aussen liegt, liefert\nein riesiges Produkt. Er bestimmt damit den Zähler fast allein. Der\nRangkoeffizient sieht nur, dass dieser Betrieb in beiden Reihen den letzten\nPlatz belegt, und das zählt genauso viel wie jeder andere Platz.\n\n#### Interpretation und Ergebnissatz\n\nDer Punkt wird nicht gelöscht, weil er stört, und er wird nicht behalten, weil\ner ein schönes Ergebnis liefert. Er wird geprüft:\n\n| Befund | Vorgehen |\n|---|---|\n| Erfassungsfehler, etwa Minuten und Stunden vermischt | ausschliessen, Begründung berichten |\n| Anderer Betriebstyp, der nicht zur Fragestellung gehört | ausschliessen, Grundgesamtheit im Bericht enger fassen |\n| Gültiger, seltener Fall | beide Ergebnisse berichten und offenlegen, dass die Aussage an einer Beobachtung hängt |\n\nIn jedem Fall gehört ein rangbasierter Koeffizient daneben. Wenn Pearson und\nSpearman weit auseinanderliegen, ist das ein Warnsignal, und zwar unabhängig\ndavon, welcher der beiden gerade das gewünschte Ergebnis liefert.\n\n> In den 19 vergleichbaren Betrieben besteht kein nachweisbarer Zusammenhang\n> zwischen Auftragsgrösse und Bearbeitungsdauer ($r$ = 0.29,\n> 95-Prozent-Konfidenzintervall -0.19 bis 0.66, t(17) = 1.26, p = 0.23). Ein\n> zwanzigster Betrieb liegt in beiden Grössen weit ausserhalb und hebt $r$ auf\n> 0.96; Spearmans $\\rho$ bleibt mit 0.40 unauffällig. Der Fall wurde als\n> andersartiger Betriebstyp ausgeschlossen.\n\n### Beispiel 4: Signifikant und schwach\n\n#### Frage und Datenlage\n\n500 Beobachtungen, ein schwacher, aber echter Zusammenhang. Damit beide Sprachen\nexakt dieselben Daten sehen, werden sie nicht gezogen, sondern aus Quantilen der\nNormalverteilung konstruiert.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlauf <- 0:499\ngrundlage <- qnorm(ppoints(500))\nversatz <- qnorm(((lauf * 97) %% 500 + 0.5) / 500)\n\nmerkmal_x <- 50 + 10 * grundlage\nmerkmal_y <- 100 + 0.12 * (10 * grundlage) + 5 * versatz\n\ncor.test(merkmal_x, merkmal_y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  merkmal_x and merkmal_y\nt = 5.3374, df = 498, p-value = 1.435e-07\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.1479404 0.3139009\nsample estimates:\n      cor \n0.2326133 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nlauf = np.arange(500)\ngrundlage = stats.norm.ppf((np.arange(1, 501) - 0.5) / 500)\nversatz = stats.norm.ppf(((lauf * 97) % 500 + 0.5) / 500)\n\nmerkmal_x = 50 + 10 * grundlage\nmerkmal_y = 100 + 0.12 * (10 * grundlage) + 5 * versatz\n\nprint(pg.corr(merkmal_x, merkmal_y).round(4).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            pearson\nn               500\nr            0.2326\nCI95   [0.15, 0.31]\np_val           0.0\nBF10      5.495e+04\npower        0.9996\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| `cor` bzw. `r` | 0.233 | Ein schwacher Zusammenhang. |\n| `t` | 5.337 | |\n| `df` | 498 | $n-2$. |\n| `p-value` | 1.4e-07 | Hochsignifikant. |\n| `95 percent confidence interval` | 0.15 bis 0.31 | Anders als bei kleinem n ist das Intervall schmal: Der schwache Zusammenhang ist präzise geschätzt. |\n| $r^2$ | 0.054 | Und hier steht die eigentliche Antwort: Gemeinsam erklären die beiden Grössen 5 Prozent der Streuung. 95 Prozent gehen auf anderes zurück. |\n\nDerselbe Koeffizient von 0.233 wäre bei n = 20 mit p = 0.32 ein glatter\nNullbefund gewesen. Der p-Wert misst also nicht die Stärke des Zusammenhangs,\nsondern wie gut man ihn bei diesem Umfang vom Zufall unterscheiden kann.\n\n#### Interpretation und Ergebnissatz\n\nOb 5 Prozent erklärte Streuung viel oder wenig sind, entscheidet die Sache. Für\neine Vorhersage im Einzelfall ist es zu wenig; für die Beschreibung eines\nZusammenhangs in einer grossen Grundgesamtheit kann es genügen.\n\nDie brauchbarste Angabe für einen Bericht ist deshalb nicht der p-Wert, sondern\n$r$ mit Intervall und $r^2$. Sie beantworten die Frage, um die es geht: wie\nstark, und wie sicher ist diese Angabe?\n\n> Zwischen den beiden Merkmalen besteht ein schwacher, aber statistisch\n> nachweisbarer Zusammenhang ($r$ = 0.23, 95-Prozent-Konfidenzintervall 0.15\n> bis 0.31, t(498) = 5.34, p < 0.001, n = 500). Er erklärt rund 5 Prozent der\n> gemeinsamen Streuung; für Aussagen im Einzelfall ist er zu schwach.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nPearsons $r$ beträgt 0.86, Spearmans $\\rho$ beträgt 1.00. Was folgt daraus?\n\n- [x] Der Zusammenhang ist perfekt monoton, aber nicht linear ~ Richtig.\n      Spearman misst die Übereinstimmung der Rangfolgen und erreicht 1, wenn\n      jeder Schritt einen höheren Wert liefert. Pearson misst die Nähe zu einer\n      Geraden und bleibt darunter, sobald der Verlauf gekrümmt ist.\n- [ ] Einer der beiden Werte muss falsch sein ~ Beide sind korrekt; sie messen\n      Verschiedenes.\n- [ ] Die Daten enthalten Ausreisser ~ Ausreisser senken eher Spearman relativ\n      zu Pearson, nicht umgekehrt.\n:::\n\n::: {.quiz}\nEin Datensatz liefert $r$ = 0.29 und p = 0.23. Nach Hinzufügen einer einzigen\nBeobachtung liefert er $r$ = 0.96 und p < 0.001. Was ist zu tun?\n\n- [x] Den Fall prüfen und das Ergebnis mit und ohne ihn berichten ~ Richtig.\n      Welche der beiden Zahlen berichtet wird, entscheidet die Klärung der\n      Ursache, nicht das Ergebnis. Wenn die Ursache offenbleibt, gehören beide\n      Werte in den Bericht.\n- [ ] Die Beobachtung entfernen, sie ist offensichtlich fehlerhaft ~ Weit\n      aussen liegend heisst nicht fehlerhaft. Ohne Klärung ist das Entfernen\n      eine Manipulation des Ergebnisses.\n- [ ] Das Ergebnis mit allen zwanzig Beobachtungen berichten, mehr Daten sind\n      besser ~ Eine Aussage, die vollständig an einer von zwanzig Beobachtungen\n      hängt, ist keine belastbare Aussage.\n:::\n\n::: {.quiz}\nBei n = 500 ist $r$ = 0.23 hochsignifikant. Wie stark ist der Zusammenhang?\n\n- [x] Schwach: er erklärt rund 5 Prozent der Streuung ~ Richtig. Die Stärke\n      liest man an $r$ und $r^2$, nicht am p-Wert. Der p-Wert sagt nur, dass\n      der Zusammenhang bei diesem Umfang vom Zufall unterscheidbar ist.\n- [ ] Stark, sonst wäre er nicht hochsignifikant ~ Signifikanz hängt an $r$\n      **und** an n. Bei 500 Beobachtungen genügt bereits $r$ = 0.09.\n- [ ] Mittel, 0.23 liegt zwischen 0 und 0.5 ~ Die Einordnung über $r$ allein\n      unterschlägt, dass $r$ kein Anteil ist; erst $r^2$ ist einer.\n:::\n\n::: {.quiz}\nWarum liegt das Konfidenzintervall für $r$ = 0.977 nicht symmetrisch um diesen\nWert?\n\n- [x] Weil $r$ bei 1 endet und die Verteilung dort schief ist ~ Richtig. Das\n      Intervall entsteht über die Fisher-z-Transformation, die den Bereich von\n      -1 bis 1 auf die ganze Zahlengerade streckt. Zurückgerechnet ergibt das\n      ein unsymmetrisches Intervall, und zwar umso deutlicher, je näher $r$ an\n      1 liegt.\n- [ ] Weil die Stichprobe zu klein ist ~ Die Unsymmetrie bleibt auch bei\n      grossem n, sie wird nur weniger sichtbar, weil das Intervall schrumpft.\n- [ ] Weil ein Rechenfehler vorliegt ~ Ein symmetrisches Intervall wäre hier\n      der Fehler, denn es könnte über 1 hinausreichen.\n:::\n\n## Verlinkte Ressourcen\n\n- [R-Dokumentation zu `cor.test`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/cor.test.html)\n- [pingouin: corr](https://pingouin-stats.org/build/html/generated/pingouin.corr.html)\n- [OpenIntro Statistics, Kapitel zu Zusammenhängen](https://www.openintro.org/book/os/)\n",
    "supporting": [
      "korrelationstests_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}