{
  "hash": "a6c4dac534cc23177760fec6cde3563f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Glättung\"\ndescription: \"Gleitender Durchschnitt und exponentielle Glättung als erste Modelle.\"\ncategories: [\"Zeitreihen\", \"Prognose\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: methode\nstand: fertig\norder: 25\n---\n\n\n\n\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Wie glättet man Rauschen heraus, und wie prognostiziert man mit einfachen Mitteln? |\n| Zielvariable | eine Zeitreihe |\n| Prädiktoren | keine, nur die eigene Vergangenheit |\n| Was die Methode liefert | geglättete Reihe, Prognose mit Prognoseintervall, Fehlermasse |\n| R-Funktion | `ma()`, `ses()`, `holt()`, `hw()` beziehungsweise `ets()` |\n| Python-Funktion | `rolling().mean()`, `SimpleExpSmoothing()`, `ExponentialSmoothing()` |\n| Verwandte Methoden | [ARIMA und SARIMA](arima-sarima.qmd), [Zeitreihen: Grundlagen](zeitreihen-grundlagen.qmd) |\n\n## Wann diese Methode, wann nicht\n\nTypische Fragestellungen: Rauschen aus einer Reihe entfernen, um den Verlauf zu\nsehen; eine schnelle Prognose für die nächsten Monate; eine Vergleichsgrundlage,\ngegen die sich ein aufwendigeres Modell beweisen muss.\n\nGlättungsverfahren sind einfach, robust und oft überraschend gut. Ihr Kern ist\nein gewichteter Mittelwert der Vergangenheit: Der gleitende Durchschnitt gewichtet\nalle Werte im Fenster gleich, die exponentielle Glättung gewichtet neuere Werte\nstärker.\n\n| Situation | Stattdessen |\n|---|---|\n| Die Abhängigkeitsstruktur soll modelliert werden | [ARIMA und SARIMA](arima-sarima.qmd) |\n| Externe Einflussgrössen sollen einfliessen | Regression mit Zeitreihenfehlern |\n| Nur die Struktur soll sichtbar werden, ohne Prognose | Zerlegung, siehe [Grundlagen](zeitreihen-grundlagen.qmd) |\n| Reihe mit vielen Nullen oder sehr sporadisch | eigene Verfahren für spärliche Nachfrage |\n| Umbrüche im Niveau, etwa nach einer Regeländerung | Modell mit Strukturbruch, oder Reihe teilen |\n\n## Grundidee und Modell\n\n**Gleitender Durchschnitt.** Der Wert an jeder Stelle wird durch das Mittel eines\nFensters ersetzt. Bei ungerader Fensterbreite $m$:\n\n$$\\hat{y}_t = \\frac{1}{m} \\sum_{j=-(m-1)/2}^{(m-1)/2} y_{t+j}$$\n\nDas ist beschreibend, nicht prognostisch: Es braucht Werte aus der Zukunft und\nverkürzt die Reihe an beiden Enden. Für Saisonbereinigung ist die Fensterbreite die\nPeriode, also 12 bei Monatsdaten.\n\n**Exponentielle Glättung.** Hier wird nur die Vergangenheit verwendet, und ältere\nWerte zählen weniger:\n\n$$\\hat{y}_{t+1} = \\alpha y_t + (1-\\alpha)\\hat{y}_t$$\n\n| Bestandteil | Bedeutung |\n|---|---|\n| $\\alpha$ | Glättungsparameter zwischen 0 und 1 |\n| $\\alpha$ nahe 1 | reagiert schnell, folgt dem Rauschen |\n| $\\alpha$ nahe 0 | reagiert träge, glättet stark |\n| $\\hat{y}_t$ | bisherige Schätzung des Niveaus |\n\nDie einfache Form kennt nur ein Niveau und prognostiziert deshalb eine waagrechte\nLinie. Zwei Erweiterungen füllen das auf:\n\n| Verfahren | Modelliert | Prognose |\n|---|---|---|\n| Einfach | Niveau | konstant |\n| Holt | Niveau und Trend | Gerade |\n| Holt-Winters | Niveau, Trend und Saison | Gerade mit Saisonfigur |\n\nAlle drei sind Spezialfälle der ETS-Modellfamilie, die in R über `ets()`\nautomatisch die passende Variante wählt.\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung | Vorgehen |\n|---|---|---|---|---|\n| Genügend Perioden für die Saison | mindestens drei, besser vier vollständige | Länge prüfen | Saisonfigur nicht schätzbar | Saison weglassen oder Daten sammeln |\n| Kein Strukturbruch | Das Niveau springt nicht dauerhaft | Grafik | Modell mittelt über zwei Regime | Reihe teilen |\n| Passende Zerlegungsart | additiv oder multiplikativ richtig gewählt | Grafik: wachsen die Zacken | Prognoseintervalle falsch | logarithmieren oder multiplikative Variante |\n| Residuen ohne Struktur | Das Modell hat alles Systematische erfasst | ACF der Residuen, Ljung-Box-Test | Prognose systematisch daneben | Modell erweitern, ARIMA prüfen |\n| Prognose nur über kurze Horizonte | Die Unsicherheit wächst schnell | Prognoseintervall ansehen | Scheingenauigkeit | Horizont begrenzen |\n\n## Output lesen\n\nR, `hw()` und `ets()`:\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| `ETS(A,A,A)` | gewählte Struktur: Fehler, Trend, Saison, je additiv oder multiplikativ | `N` heisst nicht vorhanden |\n| `alpha` | Glättung des Niveaus | nahe 1: folgt dem Rauschen; nahe 0: träge |\n| `beta` | Glättung des Trends | nahe 0 heisst nahezu konstanter Trend |\n| `gamma` | Glättung der Saison | nahe 0: starre Saisonfigur |\n| `sigma` | Streuung der Residuen | Grundlage der Prognoseintervalle |\n| `AIC`, `BIC` | Kennzahlen für Modellvergleiche | nur zwischen Modellen auf derselben Reihe vergleichbar |\n| `accuracy()` | Fehlermasse auf Trainings- und Testteil | die Zeile `Test set` zählt |\n| `RMSE` | Wurzel des mittleren quadratischen Fehlers | in Einheiten der Reihe, empfindlich für grosse Fehler |\n| `MAE` | mittlerer absoluter Fehler | robuster, ebenfalls in Einheiten der Reihe |\n| `MAPE` | mittlerer absoluter prozentualer Fehler | ungeeignet bei Werten nahe null |\n\nPython, `ExponentialSmoothing`:\n\n| Zugriff | Was er liefert | Unterschied zu R |\n|---|---|---|\n| `params` | `smoothing_level`, `smoothing_trend`, `smoothing_seasonal` | in R `alpha`, `beta`, `gamma` |\n| `forecast(h)` | Punktprognose | in R Teil des Ergebnisobjekts |\n| `fittedvalues` | angepasste Werte | wie `fitted()` |\n| `sse`, `aic`, `bic` | Anpassungskennzahlen | wie in R |\n| keine Prognoseintervalle | über `ETSModel` oder `simulate()` zu erzeugen | in R direkt in `hw()` enthalten |\n| keine Fehlermasse | RMSE und MAE selbst rechnen | in R `accuracy()` |\n\nDrei Unterschiede, über die man stolpert. R wählt mit `ets()` die Modellstruktur\nautomatisch, in Python werden `trend` und `seasonal` von Hand gesetzt. Und\n`initialization_method=\"estimated\"` gehört gesetzt, sonst verwendet statsmodels\nein einfacheres Startverfahren mit anderen Ergebnissen. Und `forecast()` liefert\nnur die Punktprognose: Prognoseintervalle gibt es erst über `ETSModel` aus\n`statsmodels.tsa.exponential_smoothing.ets` oder über wiederholte `simulate()`.\n\n## Beispiele\n\nAlle Beispiele arbeiten mit derselben konstruierten Absatzreihe: 72 Monate ab\nJanuar 2020 mit linearem Trend, Jahressaison und festem Rauschen. **Die letzten\nzwölf Monate bleiben ungesehen**; geschätzt wird auf den ersten 60. Das ist die\neinzige zulässige Aufteilung bei Zeitreihen: Getestet wird auf der Zukunft, nie\nauf herausgelosten Zeitpunkten.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Die Fensterbreite ist die Frage\n\n#### Frage und Datenlage\n\nDer gleitende Durchschnitt hat genau eine Einstellung: die Fensterbreite. Sie\nist keine technische Nebensache, sondern die Entscheidung darüber, **was man\nsehen will**.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nabsatz_ma3 <- ma(absatz, order = 3)\nabsatz_ma12 <- ma(absatz, order = 12)\n\npar(mar = c(4, 4, 2, 1))\nplot(absatz, col = \"grey70\", ylab = \"Absatz\", xlab = \"Jahr\")\nlines(absatz_ma3, col = \"#2166ac\", lwd = 2)\nlines(absatz_ma12, col = \"#b2182b\", lwd = 2)\nlegend(\"topleft\", legend = c(\"Reihe\", \"MA(3)\", \"MA(12)\"),\n       col = c(\"grey70\", \"#2166ac\", \"#b2182b\"), lwd = c(1, 2, 2), bty = \"n\")\n\nround(rbind(\n  streuung = c(reihe = sd(absatz), ma3 = sd(absatz_ma3, na.rm = TRUE),\n               ma12 = sd(absatz_ma12, na.rm = TRUE)),\n  fehlende_werte = c(0, sum(is.na(absatz_ma3)), sum(is.na(absatz_ma12)))\n), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               reihe ma3 ma12\nstreuung        94.5  90 71.3\nfehlende_werte   0.0   2 12.0\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 1: die Reihe mit gleitenden Durchschnitten über 3 und 12 Monate.](glaettung-einfache-verfahren_files/figure-html/fig-b1-gl-r-1.png){#fig-b1-gl-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nma3 = absatz.rolling(3, center=True).mean()\nma12 = absatz.rolling(12, center=True).mean()\n\nfig, achse = plt.subplots()\nachse.plot(absatz, color=\"0.7\", label=\"Reihe\")\nachse.plot(ma3, color=\"#2166ac\", lw=2, label=\"MA(3)\")\nachse.plot(ma12, color=\"#b2182b\", lw=2, label=\"MA(12)\")\nachse.set_ylabel(\"Absatz\")\nachse.legend(frameon=False)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Gegenüberstellung in Python.](glaettung-einfache-verfahren_files/figure-html/fig-b1-gl-py-1.png){#fig-b1-gl-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(pd.DataFrame({\n    \"streuung\": [absatz.std(ddof=1), ma3.std(ddof=1), ma12.std(ddof=1)],\n    \"fehlende_werte\": [0, int(ma3.isna().sum()), int(ma12.isna().sum())],\n}, index=[\"reihe\", \"ma3\", \"ma12\"]).round(1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       streuung  fehlende_werte\nreihe      94.5               0\nma3        90.0               2\nma12       72.5              11\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| | Reihe | MA(3) | MA(12) |\n|---|---|---|---|\n| Streuung (Python / R) | 94.5 | 90.0 | **72.5 / 71.3** |\n| fehlende Werte (Python / R) | 0 | 2 | **11 / 12** |\n\n| Fenster | Was es glättet | Was es stehen lässt |\n|---|---|---|\n| **MA(3)** | das monatliche Rauschen | Trend **und** Saison. Die Streuung sinkt nur von 94.5 auf 90.0, weil die Saison den grössten Teil der Schwankung ausmacht und unberührt bleibt. |\n| **MA(12)** | Rauschen und Saison vollständig | nur den Trend. Die Streuung fällt auf rund 72 — was übrig bleibt, ist der Anstieg über sechs Jahre. |\n\n| Ausgabe | Wie sie zu lesen ist |\n|---|---|\n| Fensterbreite = Periode | Der entscheidende Punkt: Ein Fenster von genau **einer Periode** mittelt jeden Monat des Jahres genau einmal und löscht die Saison damit exakt aus. Jede andere Breite lässt einen Rest stehen. |\n| fehlende Werte: 2 und 11 | Ein zentriertes Fenster braucht Nachbarn auf beiden Seiten. Bei MA(3) fehlt je einer am Rand, bei MA(12) je rund ein halbes Jahr. |\n| Die fehlenden Werte am **rechten** Rand | sind der eigentliche Haken: Für die aktuellsten Monate gibt es keinen geglätteten Wert. **Ein gleitender Durchschnitt prognostiziert nicht** — er beschreibt. |\n\n::: {.note-box}\nBei gerader Fensterbreite gibt es ein Zentrierungsproblem: Ein Fenster über 12\nMonate hat keinen mittleren Monat. R löst es in `ma(order = 12)` über ein\ndoppeltes Mittel mit halbem Gewicht an den Enden und verliert dabei je sechs\nWerte an beiden Rändern, also zwölf. `rolling(12, center=True)` in Python legt\ndas Fenster dagegen leicht asymmetrisch und verliert elf. Für die Betrachtung\nändert das wenig, für exakte Vergleiche zwischen den Sprachen viel.\n:::\n\n#### Interpretation\n\nWer den Trend sehen will, nimmt die Periodenlänge. Wer den Verlauf inklusive\nSaison glätten will, ein kurzes Fenster. Beides ist beschreibend; für Prognosen\nbraucht es die exponentielle Glättung.\n\n### Beispiel 2: Holt-Winters, Monat für Monat\n\n#### Frage und Datenlage\n\nEin Modell mit Niveau, Trend und Saison wird auf 60 Monaten geschätzt und\nprognostiziert die folgenden zwölf. Die tatsächlichen Werte sind bekannt, aber\ndas Modell hat sie nicht gesehen.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodell_hw <- hw(training, h = 12, seasonal = \"additive\")\nmodell_hw$model\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHolt-Winters' additive method \n\nCall:\nhw(y = training, h = 12, seasonal = \"additive\")\n\n  Smoothing parameters:\n    alpha = 1e-04 \n    beta  = 1e-04 \n    gamma = 1e-04 \n\n  Initial states:\n    l = 494.6758 \n    b = 4.1177 \n    s = 11.4019 0.34 -39.623 -54.4855 -58.6967 -70.2048\n           -18.1762 16.0993 30.7372 68.748 60.1054 53.7545\n\n  sigma:  23.4454\n\n     AIC     AICc      BIC \n639.6124 654.1839 675.2163 \n```\n\n\n:::\n\n```{.r .cell-code}\npar(mar = c(4, 4, 2, 1))\nplot(modell_hw, ylab = \"Absatz\", xlab = \"Jahr\", main = \"Holt-Winters\")\nlines(test, col = \"#b2182b\", lwd = 2)\nlegend(\"topleft\", legend = c(\"Prognose\", \"tatsächlich\"),\n       col = c(\"#2166ac\", \"#b2182b\"), lwd = 2, bty = \"n\")\n\nround(cbind(prognose = as.numeric(modell_hw$mean),\n            unten = as.numeric(modell_hw$lower[, \"95%\"]),\n            oben = as.numeric(modell_hw$upper[, \"95%\"]),\n            tatsaechlich = as.numeric(test),\n            fehler = as.numeric(test) - as.numeric(modell_hw$mean)), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      prognose unten  oben tatsaechlich fehler\n [1,]    799.7 753.7 845.6          803    3.3\n [2,]    810.1 764.2 856.1          806   -4.1\n [3,]    822.9 776.9 868.8          796  -26.9\n [4,]    789.0 743.0 834.9          780   -9.0\n [5,]    778.5 732.5 824.4          754  -24.5\n [6,]    748.3 702.4 794.3          741   -7.3\n [7,]    700.4 654.4 746.4          738   37.6\n [8,]    716.0 670.1 762.0          689  -27.0\n [9,]    724.4 678.4 770.3          694  -30.4\n[10,]    743.3 697.4 789.3          747    3.7\n[11,]    787.4 741.5 833.4          829   41.6\n[12,]    802.6 756.6 848.6          788  -14.6\n```\n\n\n:::\n\n```{.r .cell-code}\nround(accuracy(modell_hw, test)[, c(\"RMSE\", \"MAE\", \"MAPE\")], 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              RMSE   MAE MAPE\nTraining set 20.08 15.75 2.57\nTest set     23.28 19.16 2.54\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 2: Holt-Winters mit Prognoseintervall, dazu die tatsächlichen Werte.](glaettung-einfache-verfahren_files/figure-html/fig-b2-gl-r-3.png){#fig-b2-gl-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmodell_hw = ExponentialSmoothing(training, trend=\"add\", seasonal=\"add\",\n                                 seasonal_periods=12,\n                                 initialization_method=\"estimated\").fit()\nprognose = modell_hw.forecast(12)\n\nprint({k: round(float(v), 4) for k, v in modell_hw.params.items()\n       if k.startswith(\"smoothing\")})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'smoothing_level': 0.0, 'smoothing_trend': 0.0, 'smoothing_seasonal': 0.0}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Residuen, Standardabweichung:\",\n      round(float(modell_hw.resid.std(ddof=1)), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nResiduen, Standardabweichung: 19.89\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achse = plt.subplots()\nachse.plot(training, color=\"0.5\", label=\"Training\")\nachse.plot(test, color=\"#b2182b\", lw=2, label=\"tatsächlich\")\nachse.plot(prognose, color=\"#2166ac\", lw=2, label=\"Prognose\")\n# Die Holt-Winters-Umsetzung in statsmodels liefert keine analytischen\n# Prognoseintervalle. Das Band hier ist eine Naeherung aus der Streuung der\n# Residuen; exakte Intervalle liefert ETSModel oder simulate().\nband = 1.96 * modell_hw.resid.std(ddof=1)\nachse.fill_between(test.index, prognose - band, prognose + band,\n                   color=\"#2166ac\", alpha=0.15)\nachse.set_ylabel(\"Absatz\")\nachse.legend(frameon=False)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselbe Prognose in Python.](glaettung-einfache-verfahren_files/figure-html/fig-b2-gl-py-1.png){#fig-b2-gl-py width=100%}\n:::\n\n```{.python .cell-code}\ndef masse(wahr, geschaetzt):\n    fehler = wahr - geschaetzt\n    return {\"RMSE\": round(float(np.sqrt((fehler ** 2).mean())), 2),\n            \"MAE\": round(float(np.abs(fehler).mean()), 2),\n            \"MAPE\": round(float(np.abs(fehler / wahr).mean() * 100), 2)}\n\n\nprint(pd.DataFrame({\"prognose\": prognose.round(1).values,\n                    \"tatsaechlich\": test.values,\n                    \"fehler\": (test.values - prognose.values).round(1)},\n                   index=test.index.strftime(\"%Y-%m\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         prognose  tatsaechlich  fehler\n2025-01     802.5         803.0     0.5\n2025-02     813.3         806.0    -7.3\n2025-03     812.5         796.0   -16.5\n2025-04     789.7         780.0    -9.7\n2025-05     779.3         754.0   -25.3\n2025-06     749.1         741.0    -8.1\n2025-07     701.5         738.0    36.5\n2025-08     712.3         689.0   -23.3\n2025-09     721.3         694.0   -27.3\n2025-10     743.5         747.0     3.5\n2025-11     789.7         829.0    39.3\n2025-12     805.1         788.0   -17.1\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(masse(test.values, prognose.values))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'RMSE': 21.6, 'MAE': 17.87, 'MAPE': 2.37}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nDie Prognose gegen die tatsächlichen Werte (Python-Ausgabe):\n\n| Monat | Prognose | tatsächlich | Fehler |\n|---|---|---|---|\n| 2025-01 | 802.5 | 803 | +0.5 |\n| 2025-02 | 813.3 | 806 | -7.3 |\n| 2025-03 | 812.5 | 796 | -16.5 |\n| 2025-04 | 789.7 | 780 | -9.7 |\n| 2025-05 | 779.3 | 754 | -25.3 |\n| 2025-06 | 749.1 | 741 | -8.1 |\n| **2025-07** | 701.5 | 738 | **+36.5** |\n| 2025-08 | 712.3 | 689 | -23.3 |\n| 2025-09 | 721.3 | 694 | -27.3 |\n| 2025-10 | 743.5 | 747 | +3.5 |\n| **2025-11** | 789.7 | 829 | **+39.3** |\n| 2025-12 | 805.1 | 788 | -17.1 |\n\n(R schätzt die Glättungsparameter und die Startwerte leicht anders und kommt auf\nPrognosen von 799.7 bis 802.6 statt 802.5 bis 805.1. Siehe den Kasten unten.)\n\n| Kennzahl | Wert (Python / R) | Bedeutung |\n|---|---|---|\n| **RMSE** | **21.60 / 23.28** | Wurzel des mittleren quadratischen Fehlers, in Einheiten der Reihe. Weil quadriert wird, schlagen die beiden Ausreisser im Juli und November überproportional durch. |\n| **MAE** | **17.87 / 19.16** | Mittlerer absoluter Fehler, ebenfalls in Einheiten der Reihe. Immer kleiner oder gleich dem RMSE; der Abstand zwischen beiden zeigt, wie ungleich die Fehler verteilt sind. |\n| **MAPE** | **2.37 / 2.54 %** | Mittlerer absoluter prozentualer Fehler. Nur brauchbar, weil die Reihe weit von null entfernt liegt. |\n| Residuenstreuung im Training | **19.89** | Fast identisch mit dem RMSE auf dem Testteil. Das ist das erwünschte Bild: Das Modell prognostiziert die ungesehenen Monate ungefähr so gut, wie es die gesehenen anpasst. |\n| Fehler mit **beiden Vorzeichen** | +0.5 bis -27.3 | Kein systematischer Versatz nach oben oder unten. Läge die Prognose durchgehend zu hoch, wäre der Trend falsch geschätzt. |\n\n::: {.note-box}\n**Die Glättungsparameter fallen in Python auf null.** Das Verfahren entscheidet\nalso, dass Niveau, Trend und Saisonfigur **gar nicht** nachgeführt werden müssen —\nund das ist richtig, denn die Reihe wurde mit einem festen Trend und einer festen\nSaisonfigur konstruiert. Aus Holt-Winters wird damit faktisch eine Regression mit\nGerade und Saisondummies.\n\nR lässt exakte Nullen nicht zu (die Optimierung läuft in den Grenzen 0.0001 bis\n0.9999) und schätzt deshalb alle drei Parameter zu 0.0001. Zusätzlich bestimmt R\ndie Startwerte anders — sichtbar an `Initial states` mit einem Niveau von 494.68\nund einem Trend von 4.12, die den eingebauten 500 und 4 sehr nahe kommen. Daraus\nergeben sich leicht andere Prognosen und ein etwas höherer Testfehler (RMSE 23.3\nstatt 21.6).\n\nIn echten Daten sind Werte nahe null ein Hinweis, dass ein einfacheres Modell\ngenügt — und Werte nahe eins einer, dass das Modell dem Rauschen folgt.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Holt-Winters mit additivem Trend und additiver Saison (geschätzt auf 60\n> Monaten) prognostiziert die folgenden zwölf Monate mit einem RMSE von 21.6 und\n> einem MAPE von 2.4 Prozent. Alle tatsächlichen Werte liegen im\n> 95-Prozent-Prognoseintervall; die grössten Abweichungen betreffen Juli (+36.5)\n> und November (+39.3).\n\n### Beispiel 3: Vier Modelle im Vergleich\n\n#### Frage und Datenlage\n\nEine Prognose ist nur so gut wie ihr Vergleich. Vier Kandidaten auf denselben\nDaten: die naive saisonale Prognose (der Wert von vor zwölf Monaten), die\neinfache exponentielle Glättung, Holt (Niveau und Trend) und Holt-Winters\n(zusätzlich Saison).\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnaiv <- snaive(training, h = 12)\nmodell_ses <- ses(training, h = 12)\nmodell_holt <- holt(training, h = 12)\n\npar(mar = c(4, 4, 2, 1))\nplot(test, col = \"black\", lwd = 2, ylim = c(600, 900),\n     ylab = \"Absatz\", xlab = \"Jahr\", main = \"Testjahr 2025\")\nlines(naiv$mean, col = \"grey50\", lwd = 2)\nlines(modell_ses$mean, col = \"#1b7837\", lwd = 2)\nlines(modell_holt$mean, col = \"#b2182b\", lwd = 2)\nlines(modell_hw$mean, col = \"#2166ac\", lwd = 2)\nlegend(\"bottomleft\",\n       legend = c(\"tatsächlich\", \"naiv\", \"einfach\", \"Holt\", \"Holt-Winters\"),\n       col = c(\"black\", \"grey50\", \"#1b7837\", \"#b2182b\", \"#2166ac\"),\n       lwd = 2, bty = \"n\", cex = 0.8)\n\nspalten <- c(\"RMSE\", \"MAE\", \"MAPE\")\nround(rbind(\n  naiv_saisonal = accuracy(naiv, test)[\"Test set\", spalten],\n  einfach = accuracy(modell_ses, test)[\"Test set\", spalten],\n  holt = accuracy(modell_holt, test)[\"Test set\", spalten],\n  holt_winters = accuracy(modell_hw, test)[\"Test set\", spalten]\n), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               RMSE   MAE MAPE\nnaiv_saisonal 50.65 42.92 5.58\neinfach       43.54 36.58 4.92\nholt          45.42 37.26 5.03\nholt_winters  23.28 19.16 2.54\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: die vier Prognosen nebeneinander.](glaettung-einfache-verfahren_files/figure-html/fig-b3-gl-r-3.png){#fig-b3-gl-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nnaiv = pd.Series(training.iloc[-12:].values, index=test.index)\nmodell_ses = SimpleExpSmoothing(training,\n                                initialization_method=\"estimated\").fit()\nmodell_holt = ExponentialSmoothing(training, trend=\"add\",\n                                   initialization_method=\"estimated\").fit()\n\nkandidaten = {\n    \"naiv_saisonal\": naiv.values,\n    \"einfach\": modell_ses.forecast(12).values,\n    \"holt\": modell_holt.forecast(12).values,\n    \"holt_winters\": prognose.values,\n}\n\nprint(pd.DataFrame({name: masse(test.values, werte)\n                    for name, werte in kandidaten.items()}).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                RMSE    MAE  MAPE\nnaiv_saisonal  50.65  42.92  5.58\neinfach        43.54  36.58  4.92\nholt           56.94  45.74  6.25\nholt_winters   21.60  17.87  2.37\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"alpha der einfachen Glättung:\",\n      round(float(modell_ses.params[\"smoothing_level\"]), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nalpha der einfachen Glättung: 1.0\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Modell | RMSE (Python / R) | MAPE (Python / R) | Was es kann |\n|---|---|---|---|\n| naiv saisonal | 50.65 / 50.65 | 5.58 / 5.58 % | Saison ja, Trend nein |\n| einfache Glättung | 43.54 / 43.54 | 4.92 / 4.92 % | nur ein Niveau |\n| Holt | 56.94 / 45.42 | 6.25 / 5.03 % | Niveau und Trend, **keine Saison** |\n| **Holt-Winters** | **21.60 / 23.28** | **2.37 / 2.54 %** | Niveau, Trend und Saison |\n\nDie beiden Spalten unterscheiden sich genau dort, wo Parameter geschätzt werden\nmüssen: Bei der naiven Prognose und der einfachen Glättung stimmen die Zahlen\nexakt überein, bei Holt und Holt-Winters nicht. Die **Rangfolge** ist in beiden\nSprachen dieselbe.\n\n| Beobachtung | Erklärung |\n|---|---|\n| Holt-Winters ist **mehr als doppelt so gut** wie alles andere | Die Reihe hat Trend **und** Saison; nur ein Modell, das beides kennt, kann sie prognostizieren. |\n| **Holt ist schlechter als die einfache Glättung** | In beiden Sprachen. Überraschend, aber erklärbar: Holt schreibt den Trend als Gerade fort und ignoriert die Saison — die Prognose läuft also mitten durch die Saisonzacken hindurch und verfehlt Hoch- wie Tiefpunkte. Die einfache Glättung liegt mit ihrer waagrechten Linie zufällig näher. **Ein zusätzlicher Modellbestandteil verbessert nicht automatisch.** |\n| Die einfache Glättung schätzt $\\alpha = 1$ | Damit ist sie die naive Prognose \"der letzte Wert\" — die Vorhersage für alle zwölf Monate ist der Dezemberwert von 2024. |\n| Die naive saisonale Prognose | ist der eigentliche Massstab: Sie kostet nichts und erreicht 5.58 Prozent MAPE. Ein Modell, das sie nicht deutlich schlägt, ist den Aufwand nicht wert. |\n\n::: {.note-box}\n**Warum die naive Prognose in jeden Bericht gehört, und zwar als Zeile in\nderselben Tabelle:** Ein RMSE von 21.6 sagt für sich genommen nichts. Erst der\nVergleich mit den 50.7 der naiven saisonalen Prognose macht daraus die Aussage\n\"das Modell halbiert den Fehler\".\n\nFormalisiert wird das im **MASE** (Mean Absolute Scaled Error), dem Verhältnis des\nMAE zum MAE der naiven Prognose: Werte unter eins heissen besser als naiv. R gibt\nihn in `accuracy()` mit aus.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Holt-Winters mit additivem Trend und additiver Saison erreicht auf den letzten\n> zwölf Monaten einen RMSE von 21.6 (MAPE 2.4 Prozent) gegenüber 50.7 (5.6\n> Prozent) bei der naiven saisonalen Prognose. Modelle ohne Saisonkomponente\n> bleiben deutlich zurück (Holt: RMSE 56.9).\n\n### Beispiel 4: Alpha von Hand gesetzt\n\n#### Frage und Datenlage\n\nDer Glättungsparameter $\\alpha$ steuert, wie stark das Modell auf den jüngsten\nWert reagiert. Was passiert, wenn man ihn selbst wählt statt ihn schätzen zu\nlassen?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalphas <- c(0.05, 0.5, 0.95)\nfarben <- c(\"#1b7837\", \"#b2182b\", \"#2166ac\")\n\npar(mar = c(4, 4, 2, 1))\nplot(training, col = \"grey70\", ylab = \"Absatz\", xlab = \"Jahr\",\n     main = \"Geglättetes Niveau\")\nfor (i in seq_along(alphas)) {\n  m <- ses(training, h = 12, alpha = alphas[i], initial = \"simple\")\n  lines(fitted(m), col = farben[i], lwd = 2)\n}\nlegend(\"topleft\", legend = paste(\"alpha =\", alphas), col = farben,\n       lwd = 2, bty = \"n\")\n\nspalten <- c(\"RMSE\", \"MAE\")\nergebnisse <- t(sapply(alphas, function(a) {\n  m <- ses(training, h = 12, alpha = a, initial = \"simple\")\n  accuracy(m, test)[\"Test set\", spalten]\n}))\nrownames(ergebnisse) <- paste(\"alpha\", alphas)\nround(rbind(ergebnisse,\n            geschaetzt = accuracy(modell_ses, test)[\"Test set\", spalten]), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             RMSE   MAE\nalpha 0.05 105.68 96.84\nalpha 0.5   45.10 37.56\nalpha 0.95  43.31 36.58\ngeschaetzt  43.54 36.58\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 4: dieselbe Glättung mit alpha = 0.05, 0.5 und 0.95.](glaettung-einfache-verfahren_files/figure-html/fig-b4-gl-r-1.png){#fig-b4-gl-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfor a in [0.05, 0.5, 0.95]:\n    m = SimpleExpSmoothing(training, initialization_method=\"known\",\n                           initial_level=float(training.iloc[0])).fit(\n                               smoothing_level=a, optimized=False)\n    print(f\"alpha = {a:<5}\", masse(test.values, m.forecast(12).values))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nalpha = 0.05  {'RMSE': 105.68, 'MAE': 96.84, 'MAPE': 12.4}\nalpha = 0.5   {'RMSE': 45.1, 'MAE': 37.56, 'MAPE': 4.88}\nalpha = 0.95  {'RMSE': 43.31, 'MAE': 36.58, 'MAPE': 4.91}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"geschätzt   \", masse(test.values, modell_ses.forecast(12).values))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngeschätzt    {'RMSE': 43.54, 'MAE': 36.58, 'MAPE': 4.92}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| $\\alpha$ | RMSE | MAE | Verhalten |\n|---|---|---|---|\n| **0.05** | **105.68** | 96.84 | Das Niveau folgt dem Trend viel zu träge und bleibt am Ende weit unter der Reihe. Der Fehler ist fünfmal so gross wie nötig. |\n| 0.5 | 45.10 | 37.56 | Schon nahe am Optimum — die Kurve ist flach. |\n| **0.95** | **43.31** | 36.58 | Minimal besser als der geschätzte Wert. |\n| geschätzt ($\\alpha = 1$) | 43.54 | 36.58 | |\n\nR und Python liefern hier **identische** Zahlen, weil $\\alpha$ vorgegeben ist und\nder Startwert in beiden Fällen auf den ersten Beobachtungswert gesetzt wurde.\n\n| Beobachtung | Erklärung |\n|---|---|\n| Ein kleines $\\alpha$ ist hier **klar schlecht** | Bei einer Reihe mit Trend muss das Niveau ständig nachgeführt werden. Mit $\\alpha = 0.05$ zählt der jüngste Wert nur zu fünf Prozent, und das geglättete Niveau hinkt Jahre hinterher. |\n| Ein grosses $\\alpha$ ist hier **fast optimal** | Weil die Reihe stark steigt, ist \"der letzte Wert\" die beste Schätzung, die ein Modell ohne Trendkomponente abgeben kann. |\n| Der geschätzte Wert ist $\\alpha = 1$ | Die Optimierung landet am Rand des zulässigen Bereichs. Das ist selbst ein Befund: **Das Modell passt nicht.** Eine einfache Glättung, die $\\alpha = 1$ wählt, sagt \"ich kann nichts glätten\" — die Reihe braucht eine Trendkomponente. |\n\n::: {.note-box}\n**Die übliche Lehrbuchwarnung \"$\\alpha$ nahe eins heisst, das Modell folgt dem\nRauschen\" gilt hier nicht** — und das zeigt, warum Faustregeln über\nParameterwerte mit Vorsicht zu geniessen sind. Ein $\\alpha$ nahe eins bedeutet\nnur: Der jüngste Wert ist die beste verfügbare Information. Bei einer\nrauschenden Reihe ohne Trend ist das ein Warnzeichen, bei einer stark steigenden\nReihe die richtige Antwort.\n\nDeshalb wird $\\alpha$ geschätzt und nicht gesetzt: Die Programme minimieren den\nFehler auf den Trainingsdaten. Und deshalb wird das Ergebnis **gedeutet** statt\ngegen eine Schwelle geprüft.\n:::\n\n#### Interpretation\n\nEin von Hand gesetzter Parameter liegt fast immer daneben. Interessanter als sein\nWert ist, was er über das Modell verrät — hier, dass die einfache Glättung für\ndiese Reihe die falsche Wahl ist.\n\n### Beispiel 5: Die Residuen prüfen\n\n#### Frage und Datenlage\n\nDer letzte Schritt jeder Zeitreihenmodellierung: Steckt in den Residuen noch\nStruktur? Wenn ja, hat das Modell etwas übersehen, und die Prognoseintervalle\nsind zu schmal.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheckresiduals(modell_hw$model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLjung-Box test\n\ndata:  Residuals from Holt-Winters' additive method\nQ* = 19.09, df = 12, p-value = 0.08637\n\nModel df: 0.   Total lags used: 12\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 5: Residuen des Holt-Winters-Modells — Verlauf, ACF und Verteilung.](glaettung-einfache-verfahren_files/figure-html/fig-b5-gl-r-1.png){#fig-b5-gl-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom statsmodels.graphics.tsaplots import plot_acf\nfrom statsmodels.stats.diagnostic import acorr_ljungbox\n\nresiduen = modell_hw.resid\n\nfig, achsen = plt.subplots(1, 3, figsize=(7.5, 3))\nachsen[0].plot(residuen, color=\"#2166ac\")\nachsen[0].axhline(0, ls=\"--\", color=\"black\", lw=0.8)\nachsen[0].set_title(\"Verlauf\")\nplot_acf(residuen, ax=achsen[1], lags=20, title=\"ACF\")\nachsen[2].hist(residuen, bins=15, color=\"#2166ac\", edgecolor=\"white\")\nachsen[2].set_title(\"Verteilung\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselbe Prüfung in Python.](glaettung-einfache-verfahren_files/figure-html/fig-b5-gl-py-1.png){#fig-b5-gl-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(acorr_ljungbox(residuen, lags=[6, 12, 18], return_df=True).round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    lb_stat  lb_pvalue\n6   12.3529     0.0545\n12  21.4998     0.0435\n18  27.1134     0.0769\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Mittelwert der Residuen:\", round(float(residuen.mean()), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMittelwert der Residuen: 0.0\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Standardabweichung:    \", round(float(residuen.std(ddof=1)), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStandardabweichung:     19.891\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nDer Ljung-Box-Test über zwölf Abstände:\n\n| Umgebung | Teststatistik | Freiheitsgrade | p |\n|---|---|---|---|\n| Python, `acorr_ljungbox` | 21.50 | 12 | **0.044** |\n| R, `checkresiduals` | 19.09 | 12 | **0.086** |\n\nZusätzlich über andere Abstandszahlen (Python): p = 0.055 bei 6 Abständen und\np = 0.077 bei 18.\n\n| Prüfpunkt | Befund | Wie er zu lesen ist |\n|---|---|---|\n| **Ljung-Box** | 0.044 in Python, 0.086 in R | Der Test prüft, ob **irgendeine** der ersten zwölf Autokorrelationen von null verschieden ist. Die Nullhypothese lautet \"keine Autokorrelation\"; ein kleiner p-Wert heisst also, dass Struktur übrig ist. Hier: ein Grenzfall. |\n| **ACF der Residuen** | ein bis zwei Balken knapp ausserhalb | Bei 20 angezeigten Abständen ist ein Ausreisser zufällig zu erwarten. Entscheidend ist, ob er an einer **deutbaren** Stelle liegt — etwa bei 12, was auf eine unerfasste Saison hinweisen würde. |\n| **Verlauf** | schwankt um null, keine Trichterform | Keine wachsende Streuung, kein Muster. |\n| **Verteilung** | ungefähr symmetrisch | Grundlage der Prognoseintervalle; starke Schiefe würde sie unbrauchbar machen. |\n| Mittelwert der Residuen | nahe null | Ein deutlich von null verschiedener Mittelwert wäre ein systematischer Versatz. |\n\n::: {.note-box}\n**Ein Grenzfall wie p = 0.044 trägt kein Urteil.** Drei Gründe:\n\n1. Der Test wird mit wachsender Reihenlänge empfindlich und findet dann auch\n   praktisch bedeutungslose Autokorrelationen.\n2. Die Anzahl geprüfter Abstände ist eine Wahl — hier ergeben 6, 12 und 18\n   Abstände p-Werte von 0.055, 0.044 und 0.077.\n3. **R und Python kommen auf verschiedene Teststatistiken** (19.09 gegen 21.50)\n   und damit auf 0.086 gegen 0.044 — einmal über und einmal unter der Schwelle.\n   Der Grund liegt in den leicht verschiedenen Modellanpassungen.\n   **Ein Befund, der an der Wahl der Umgebung kippt, ist kein Befund.**\n\nWas zählt, ist die Grafik: Liegt der auffällige Balken bei Abstand 12, fehlt\nSaison. Liegt er irgendwo, ist es Zufall. Und wenn wirklich Struktur übrig ist,\nist [ARIMA](arima-sarima.qmd) der nächste Schritt.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Residuen des Modells schwanken ohne erkennbares Muster um null\n> (Standardabweichung 19.9); der Ljung-Box-Test über zwölf Abstände liegt mit\n> p = 0.04 bis 0.09 je nach Umgebung im Grenzbereich, ohne dass die ACF eine\n> deutbare Struktur zeigt. Die Prognoseintervalle sind damit vertretbar.\n\n::::\n\n## Interpretationsfallen\n\n- **Fehlermasse auf den Trainingsdaten sagen nichts.** Das Modell hat diese Werte\n  gesehen; bewertet wird auf dem Testteil.\n- **Zufällige Aufteilung ist bei Zeitreihen falsch.** Getestet wird auf der\n  Zukunft, sonst nutzt das Modell Information, die es nicht haben dürfte.\n- **Eine Prognose ohne Intervall ist unvollständig.** Und das Intervall wächst mit\n  dem Horizont, meist schneller als man erwartet.\n- **Ein gleitender Durchschnitt prognostiziert nicht.** Er ist beschreibend und\n  braucht Werte aus der Zukunft.\n- **MAPE ist tückisch.** Bei Werten nahe null explodiert er, und er bestraft\n  Überschätzung anders als Unterschätzung.\n- **Alpha nahe eins ist keine gute Anpassung**, sondern Folgen des Rauschens.\n- **Glättung erklärt nichts.** Sie beschreibt die Reihe aus sich selbst; für\n  Ursachen braucht es Einflussgrössen.\n\n## Ergebnis berichten\n\nVorlage für den Ergebnissatz:\n\n> Die Reihe wurde mit [Verfahren] modelliert (geschätzt auf [Zeitraum], Test auf\n> den folgenden [h] Perioden). Die Prognose erreicht einen RMSE von [Wert] und\n> einen MAPE von [Wert] Prozent, gegenüber [Wert] beziehungsweise [Wert] bei der\n> naiven saisonalen Prognose. Die Residuen zeigen im Ljung-Box-Test p = [p].\n\nGenannt werden: Verfahren und Modellstruktur, Trainings- und Testzeitraum,\nFehlermasse auf dem Testteil, der Vergleich mit einer naiven Prognose, das\nErgebnis der Residuenprüfung und der Prognosehorizont mit Intervall.\n\nBeispiel für eine Ergebnistabelle:\n\n| Modell | RMSE | MAE | MAPE |\n|---|---|---|---|\n| naiv saisonal | | | |\n| einfache Glättung | | | |\n| Holt-Winters | | | |\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt der Glättung |\n|---|---|\n| [ARIMA und SARIMA](arima-sarima.qmd) | die Abhängigkeitsstruktur selbst interessiert, Modellordnung soll begründet werden |\n| Regression mit Zeitreihenfehlern | externe Einflussgrössen sollen einfliessen |\n| [Zerlegung](zeitreihen-grundlagen.qmd) | nur Beschreibung, keine Prognose |\n| Verfahren für spärliche Nachfrage | viele Nullen in der Reihe |\n| Modelle mit Strukturbruch | dauerhafter Niveausprung in der Reihe |\n\n## Verständnisfragen\n\n::: {.quiz}\nEin Modell erreicht auf den Trainingsdaten einen RMSE von 8 und auf dem Testteil\nvon 45. Was folgt?\n\n- [x] Das Modell ist an die Trainingsdaten angepasst und prognostiziert schlecht ~\n      Richtig. Der Testteil ist der einzige aussagekräftige Wert. Ein grosser\n      Unterschied deutet auf ein zu reaktives Modell, etwa ein Alpha nahe eins.\n- [ ] Der Testteil ist zu kurz ~ Möglich, aber der Unterschied ist zu gross, um\n      allein daran zu liegen.\n- [ ] Beide Werte gemeinsam beurteilen ~ Der Trainingswert trägt zur Beurteilung\n      der Prognose nichts bei.\n:::\n\n::: {.quiz}\nWarum darf man Zeitreihen nicht zufällig in Trainings- und Testdaten aufteilen?\n\n- [x] Weil das Modell dann Werte aus der Zukunft kennt ~ Richtig. Liegen\n      Testzeitpunkte zwischen Trainingszeitpunkten, nutzt das Modell Information,\n      die zum Prognosezeitpunkt nicht vorlag. Der Fehler wird dadurch zu klein.\n- [ ] Weil die Reihenfolge für die Rechnung nötig ist ~ Auch das, aber der\n      entscheidende Punkt ist die Information.\n- [ ] Weil die Stichprobe sonst zu klein wird ~ Die Grösse ändert sich nicht.\n:::\n\n::: {.quiz}\nEin gleitender Durchschnitt über zwölf Monate wird für eine Prognose verwendet.\nWas ist das Problem?\n\n- [x] Er ist beschreibend und braucht Werte aus der Zukunft ~ Richtig. Ein\n      zentrierter gleitender Durchschnitt mittelt um jeden Zeitpunkt herum, also\n      auch über spätere Werte, und endet deshalb sechs Monate vor dem\n      Reihenende.\n- [ ] Zwölf Monate sind ein zu langes Fenster ~ Die Fensterbreite ist hier nicht\n      das Problem.\n- [ ] Er glättet die Saison weg ~ Das tut er, und für die Trendbetrachtung ist es\n      gewollt.\n:::\n\n::: {.quiz}\nDer Ljung-Box-Test auf den Residuen ergibt p = 0.003. Was heisst das?\n\n- [x] In den Residuen steckt noch Abhängigkeit, das Modell hat etwas übersehen ~\n      Richtig. Die Folge sind zu schmale Prognoseintervalle. Zu prüfen ist, ob\n      Saison, Trend oder eine Abhängigkeitsstruktur fehlt, die ein ARIMA-Modell\n      erfassen würde.\n- [ ] Das Modell passt gut, der p-Wert ist klein ~ Die Richtung ist vertauscht:\n      Die Nullhypothese lautet keine Autokorrelation.\n- [ ] Die Residuen sind nicht normalverteilt ~ Das prüft ein anderer Test.\n:::\n\n## Verlinkte Ressourcen\n\n- [Forecasting: Principles and Practice, Kapitel 8](https://otexts.com/fpp3/expsmooth.html)\n- [forecast: ets und hw](https://pkg.robjhyndman.com/forecast/)\n- [statsmodels: Exponentielle Glättung](https://www.statsmodels.org/stable/examples/notebooks/generated/exponential_smoothing.html)\n",
    "supporting": [
      "glaettung-einfache-verfahren_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}