{
  "hash": "01660ed51795e0f4b80b3765771ffdb3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Distanzmasse\"\ndescription: \"Euklidisch, Manhattan, Gower und warum Skalierung entscheidend ist.\"\ncategories: [\"Distanzmasse\", \"Clustering\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: konzept\nstand: fertig\norder: 10\n---\n\n\n\n\n\n## Kernideen\n\n- Jedes Clustering und jede Dimensionsreduktion beruht auf einem Distanzbegriff.\n  Was \"nah\" heisst, steht **nicht in den Daten**, sondern in dieser Wahl.\n- Die euklidische Distanz ist der Standard, aber nicht immer der richtige.\n- Ohne Standardisierung bestimmt die Variable mit der grössten Streuung das\n  Ergebnis, allein wegen ihrer Masseinheit.\n- Manhattan reagiert schwächer auf einzelne grosse Abweichungen als euklidisch.\n- Für gemischte Datentypen gibt es Gower; euklidisch mit Hilfskonstruktion führt\n  zu willkürlichen Gewichten.\n- Korrelierte Variablen zählen mehrfach, solange man sie nicht behandelt.\n- Zwei korrekt gerechnete Distanzmatrizen desselben Datensatzes können zu\n  **verschiedenen Gruppen** führen. Die Wahl gehört deshalb in den Methodenteil.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Skalenniveaus](../grundlagen/skalenniveaus.qmd), weil der\nDatentyp das Distanzmass bestimmt, und\n[Lage- und Streuungsmasse](../grundlagen/lage-streuungsmasse.qmd) für die\nStandardisierung. Verwendet werden Distanzen unter\n[k-Means](k-means.qmd), [hierarchischem Clustering](hierarchisches-clustering.qmd)\nund bei der [Clustergüte](clusterguete.qmd).\n:::\n\n### Warum das Mass die Ergebnisse bestimmt\n\nClusterverfahren gruppieren, was nah beieinander liegt. Was nah heisst, steht\nnicht in den Daten, sondern in der Wahl des Distanzmasses und der Skalierung.\nDiese Wahl trifft man vor der Analyse, und sie entscheidet mehr über das Ergebnis\nals der Algorithmus danach.\n\n### Die gebräuchlichen Masse\n\n| Mass | Formel in Worten | Verhalten | Wofür |\n|---|---|---|---|\n| Euklidisch | Wurzel aus der Summe der quadrierten Differenzen | reagiert stark auf einzelne grosse Abweichungen | metrische Variablen, der Standardfall |\n| Manhattan | Summe der absoluten Differenzen | robuster gegen Ausreisser | metrisch, viele Dimensionen, robustere Gruppierung |\n| Maximum | grösste einzelne Differenz | eine Dimension entscheidet | wenn ein einzelnes Merkmal ausschlaggebend sein soll |\n| Korrelationsdistanz | eins minus Korrelation der Profile | ignoriert Niveau, achtet auf Verlauf | Zeitverläufe, Ausgabeprofile |\n| Gower | Mittelwert typgerechter Einzeldistanzen | für gemischte Typen gebaut | metrisch, ordinal und nominal zusammen |\n| Jaccard | Anteil gemeinsamer Einsen an allen Einsen | ignoriert gemeinsame Nullen | binäre Merkmale, Warenkörbe |\n\nFür binäre Daten ist der Unterschied zwischen Jaccard und euklidisch bedeutsam:\nJaccard zählt gemeinsame Nullen nicht als Ähnlichkeit. Bei einem Warenkorb ist\ndas richtig, denn zwei Personen, die dieselben 900 Artikel **nicht** gekauft\nhaben, sind sich deswegen nicht ähnlich.\n\n### Standardisierung ist keine Kosmetik\n\nDie euklidische Distanz summiert quadrierte Differenzen. Eine Variable in\nMillimetern trägt damit millionenfach mehr bei als dieselbe Grösse in Metern,\nobwohl es dieselbe Information ist. Ohne Standardisierung entscheidet also die\nEinheit über das Ergebnis.\n\nDie Regel lautet deshalb: **Bei metrischen Variablen verschiedener Einheiten wird\nstandardisiert**, es sei denn, die Einheiten sind vergleichbar und die\nUnterschiede in der Streuung sind inhaltlich gewollt.\n\nZwei Varianten sind gebräuchlich:\n\n| Verfahren | Rechnung | Wirkung |\n|---|---|---|\n| z-Standardisierung | minus Mittelwert, geteilt durch Standardabweichung | jede Variable hat danach Streuung eins; empfindlich gegenüber Ausreissern, weil diese die Standardabweichung aufblähen |\n| Bereichsskalierung | minus Minimum, geteilt durch Spannweite | jede Variable liegt danach zwischen 0 und 1; noch empfindlicher gegenüber Ausreissern, weil zwei Werte alles bestimmen |\n\n### Korrelierte Variablen zählen mehrfach\n\nWenn drei Variablen dasselbe messen, geht dieses Merkmal dreifach in die Distanz\nein. Das Ergebnis ist eine Gruppierung, die vor allem dieses eine Merkmal\nabbildet, ohne dass es jemand entschieden hätte. Die Standardisierung hilft hier\n**nicht**, sie gleicht die Streuungen an, nicht die Doppelungen.\n\nDrei Auswege: inhaltlich auswählen und Doppelungen entfernen; die Variablen zu\neiner zusammenfassen; oder vorab eine\n[Hauptkomponentenanalyse](hauptkomponentenanalyse.qmd) rechnen und auf den\nKomponenten clustern, die unkorreliert sind.\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Dieselben Daten, zwei Gruppierungen\n\n#### Frage und Datenlage\n\nVier Maschinen, zwei Merkmale: Laufzeit in Stunden (Spannweite 600) und\nTemperatur in Grad (Spannweite 14). Die Frage: Welche zwei Maschinen sind sich\nam ähnlichsten?\n\n| Maschine | Laufzeit (h) | Temperatur (°C) |\n|---|---|---|\n| A | 1200 | 62 |\n| B | 1800 | 61 |\n| C | 1250 | 75 |\n| D | 1750 | 74 |\n\nIn den Daten stecken zwei Strukturen: A und C haben ähnliche Laufzeiten (ebenso\nB und D), während A und B eine niedrige und C und D eine hohe Temperatur haben.\nWelche der beiden Strukturen ein Clusterverfahren findet, entscheidet die\nSkalierung.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmaschinen <- data.frame(\n  laufzeit_h = c(1200, 1800, 1250, 1750),\n  temperatur = c(62, 61, 75, 74),\n  row.names = c(\"A\", \"B\", \"C\", \"D\")\n)\n\nround(dist(maschinen), 1)                       # ohne Standardisierung\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      A     B     C\nB 600.0            \nC  51.7 550.2      \nD 550.1  51.7 500.0\n```\n\n\n:::\n\n```{.r .cell-code}\nround(scale(maschinen), 3)                      # die z-Werte\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  laufzeit_h temperatur\nA     -0.941     -0.797\nB      0.941     -0.930\nC     -0.784      0.930\nD      0.784      0.797\nattr(,\"scaled:center\")\nlaufzeit_h temperatur \n      1500         68 \nattr(,\"scaled:scale\")\nlaufzeit_h temperatur \n318.852108   7.527727 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(dist(scale(maschinen)), 2)                # mit Standardisierung\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     A    B    C\nB 1.89          \nC 1.73 2.54     \nD 2.35 1.73 1.57\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmaschinen = pd.DataFrame(\n    {\"laufzeit_h\": [1200, 1800, 1250, 1750],\n     \"temperatur\": [62, 61, 75, 74]},\n    index=[\"A\", \"B\", \"C\", \"D\"])\n\n\ndef matrix(daten):\n    return pd.DataFrame(squareform(pdist(daten)),\n                        index=daten.index, columns=daten.index)\n\n\nstandardisiert = (maschinen - maschinen.mean()) / maschinen.std(ddof=1)\n\nprint(matrix(maschinen).round(1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       A      B      C      D\nA    0.0  600.0   51.7  550.1\nB  600.0    0.0  550.2   51.7\nC   51.7  550.2    0.0  500.0\nD  550.1   51.7  500.0    0.0\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(standardisiert.round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   laufzeit_h  temperatur\nA      -0.941      -0.797\nB       0.941      -0.930\nC      -0.784       0.930\nD       0.784       0.797\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(matrix(standardisiert).round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      A     B     C     D\nA  0.00  1.89  1.73  2.35\nB  1.89  0.00  2.54  1.73\nC  1.73  2.54  0.00  1.57\nD  2.35  1.73  1.57  0.00\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nOhne Standardisierung:\n\n| | A | B | C | D |\n|---|---|---|---|---|\n| A | 0.0 | 600.0 | **51.7** | 550.1 |\n| B | 600.0 | 0.0 | 550.2 | **51.7** |\n| C | 51.7 | 550.2 | 0.0 | 500.0 |\n| D | 550.1 | 51.7 | 500.0 | 0.0 |\n\nMit z-Standardisierung:\n\n| | A | B | C | D |\n|---|---|---|---|---|\n| A | 0.00 | **1.89** | 1.73 | 2.35 |\n| B | 1.89 | 0.00 | 2.54 | **1.73** |\n| C | 1.73 | 2.54 | 0.00 | **1.57** |\n| D | 2.35 | 1.73 | 1.57 | 0.00 |\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| d(A, C) roh | **51.7** | Der Beitrag der Laufzeit ist $50^2 = 2500$, der der Temperatur $13^2 = 169$. Die Wurzel aus 2669 ist 51.7, die Temperatur macht **6 Prozent** der Distanz aus, obwohl es der grössere Unterschied in Standardabweichungen ist. |\n| kleinste rohe Distanzen | A, C und B, D | Die Gruppierung folgt der Laufzeit. |\n| z-Werte | alle zwischen -0.94 und 0.94 | Beide Merkmale liegen jetzt in derselben Grössenordnung. |\n| kleinste standardisierte Distanz | **C, D mit 1.57**, dann A, C mit 1.73 | Die Rangfolge hat sich verschoben; die Temperatur trägt jetzt gleich viel bei wie die Laufzeit. |\n\n::: {.note-box}\n**Beide Matrizen sind korrekt gerechnet.** Es gibt keinen Rechenfehler, den man\nfinden könnte, nur eine Entscheidung, die getroffen werden muss. Ohne\nStandardisierung lautet die implizite Aussage: \"Eine Stunde Laufzeit und ein Grad\nTemperatur sind gleich viel wert.\" Das ist selten gemeint, und noch seltener\nbegründet.\n:::\n\n#### Interpretation\n\nWelche Skalierung verwendet wurde, gehört in jeden Methodenteil, und zwar\nzusammen mit der Begründung. Der Standardfall ist die z-Standardisierung; sie\nsagt \"alle Merkmale sind gleich wichtig\". Wer bewusst anders gewichten will, tut\ndas ausdrücklich und nicht über die Wahl der Masseinheit.\n\n### Beispiel 2: Euklidisch oder Manhattan\n\n#### Frage und Datenlage\n\nEin Referenzpunkt im Ursprung, fünf Dimensionen. Zwei andere Punkte weichen\ndavon ab, der eine in allen fünf Dimensionen um je eine Einheit, der andere in\neiner einzigen um fünf Einheiten. Die Gesamtabweichung ist beide Male fünf\nEinheiten. Sind sie gleich weit weg?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npunkte <- rbind(\n  normal = c(0, 0, 0, 0, 0),\n  klein  = c(1, 1, 1, 1, 1),          # fuenf kleine Abweichungen\n  gross  = c(0, 0, 0, 0, 5)           # eine grosse Abweichung\n)\n\nfor (methode in c(\"euclidean\", \"manhattan\", \"maximum\")) {\n  d <- dist(punkte, method = methode)\n  cat(sprintf(\"%-10s | klein: %.3f | gross: %.3f\\n\", methode,\n              as.matrix(d)[\"normal\", \"klein\"],\n              as.matrix(d)[\"normal\", \"gross\"]))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\neuclidean  | klein: 2.236 | gross: 5.000\nmanhattan  | klein: 5.000 | gross: 5.000\nmaximum    | klein: 1.000 | gross: 5.000\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\npunkte = pd.DataFrame(\n    [[0, 0, 0, 0, 0], [1, 1, 1, 1, 1], [0, 0, 0, 0, 5]],\n    index=[\"normal\", \"klein\", \"gross\"], dtype=float)\n\nfor methode in [\"euclidean\", \"cityblock\", \"chebyshev\"]:\n    d = pd.DataFrame(squareform(pdist(punkte, metric=methode)),\n                     index=punkte.index, columns=punkte.index)\n    print(f\"{methode:10s} | klein: {d.loc['normal', 'klein']:.3f} \"\n          f\"| gross: {d.loc['normal', 'gross']:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\neuclidean  | klein: 2.236 | gross: 5.000\ncityblock  | klein: 5.000 | gross: 5.000\nchebyshev  | klein: 1.000 | gross: 5.000\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Mass | fünf kleine Abweichungen | eine grosse Abweichung | Verhältnis |\n|---|---|---|---|\n| Euklidisch | $\\sqrt{5} = $ **2.236** | $\\sqrt{25} = $ **5.000** | 1 zu 2.24 |\n| Manhattan (`cityblock`) | 5.000 | 5.000 | **1 zu 1** |\n| Maximum (`chebyshev`) | 1.000 | 5.000 | 1 zu 5 |\n\n| Beobachtung | Deutung |\n|---|---|\n| Euklidisch stuft die eine grosse Abweichung als **mehr als doppelt so weit** ein | Das Quadrieren gewichtet grosse Abweichungen überproportional. Ein Ausreisser in einer einzigen Dimension kann eine Beobachtung aus jeder Gruppe herausdrängen. |\n| Manhattan sieht **keinen Unterschied** | Es summiert nur; fünf mal eins ist dasselbe wie einmal fünf. Deshalb gilt es als robuster. |\n| Maximum sieht **den grössten Unterschied** | Nur die stärkste einzelne Abweichung zählt, alle anderen Dimensionen sind irrelevant. |\n\n::: {.note-box}\nKeines der drei Verhalten ist richtiger als die anderen, sie beantworten\nverschiedene Fragen:\n\n- \"Ist irgendetwas stark aus dem Ruder gelaufen?\" → euklidisch oder Maximum\n- \"Wie viel Abweichung insgesamt?\" → Manhattan\n\nEin praktischer Nebenaspekt: In sehr vielen Dimensionen werden alle euklidischen\nAbstände einander ähnlich (das Phänomen der leeren Räume), und Manhattan hält die\nUnterschiede etwas länger auseinander.\n:::\n\n#### Interpretation\n\nDer Standardfall bleibt euklidisch, weil er der geometrischen Anschauung\nentspricht und weil Verfahren wie [k-Means](k-means.qmd) und Ward direkt darauf\naufbauen. Manhattan ist die Wahl, wenn Ausreisser erwartet werden und nicht\ndominieren sollen, dann meist zusammen mit einem hierarchischen Verfahren oder\nk-Medoids, denn k-Means selbst setzt quadrierte euklidische Distanzen voraus.\n\n### Beispiel 3: Gemischte Datentypen mit Gower\n\n#### Frage und Datenlage\n\nVier Kunden, beschrieben durch zwei metrische, ein nominales und ein ordinales\nMerkmal:\n\n| Kunde | Umsatz | Besuche | Segment | Zufriedenheit |\n|---|---|---|---|---|\n| 1 | 1200 | 12 | Privat | hoch |\n| 2 | 1500 | 15 | Privat | mittel |\n| 3 | 900 | 9 | Gewerbe | mittel |\n| 4 | 2400 | 4 | Gewerbe | niedrig |\n\nEuklidisch ist hier nicht definiert. Der übliche Behelf, nominale Merkmale in\nIndikatorspalten verwandeln und trotzdem euklidisch rechnen, führt zu\nwillkürlichen Gewichten: Ein Merkmal mit fünf Kategorien bekommt fünf Spalten und\ndamit mehr Gewicht als ein metrisches.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkunden <- data.frame(\n  umsatz = c(1200, 1500, 900, 2400),\n  besuche = c(12, 15, 9, 4),\n  segment = factor(c(\"Privat\", \"Privat\", \"Gewerbe\", \"Gewerbe\")),\n  zufriedenheit = factor(c(\"hoch\", \"mittel\", \"mittel\", \"niedrig\"),\n                         levels = c(\"niedrig\", \"mittel\", \"hoch\"), ordered = TRUE)\n)\n\nround(daisy(kunden, metric = \"gower\"), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDissimilarities :\n      1     2     3\n2 0.243            \n3 0.493 0.486      \n4 0.882 0.775 0.489\n\nMetric :  mixed ;  Types = I, I, N, O \nNumber of objects : 4\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# Python bringt Gower nicht mit; hier von Hand fuer gemischte Typen.\nkunden = pd.DataFrame({\n    \"umsatz\": [1200, 1500, 900, 2400],\n    \"besuche\": [12, 15, 9, 4],\n    \"segment\": [\"Privat\", \"Privat\", \"Gewerbe\", \"Gewerbe\"],\n    \"zufriedenheit\": [2, 1, 1, 0],          # ordinal als Rang kodiert\n})\n\n\ndef gower_teile(df, ordinal=()):\n    \"\"\"Je Merkmal eine Distanzmatrix mit Werten zwischen 0 und 1.\"\"\"\n    teile = {}\n    for name in df.columns:\n        s = df[name]\n        if name in ordinal or s.dtype.kind in \"if\":\n            w = s.to_numpy(dtype=float)\n            teile[name] = np.abs(w[:, None] - w[None, :]) / (w.max() - w.min())\n        else:\n            w = np.asarray(s, dtype=object)\n            teile[name] = (w[:, None] != w[None, :]).astype(float)\n    return teile\n\n\nteile = gower_teile(kunden)\nfor name, d in teile.items():\n    print(f\"{name:14s} Paar 1-2: {d[0, 1]:.3f}  Paar 1-4: {d[0, 3]:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\numsatz         Paar 1-2: 0.200  Paar 1-4: 0.800\nbesuche        Paar 1-2: 0.273  Paar 1-4: 0.727\nsegment        Paar 1-2: 0.000  Paar 1-4: 1.000\nzufriedenheit  Paar 1-2: 0.500  Paar 1-4: 1.000\n```\n\n\n:::\n\n```{.python .cell-code}\ngower = np.mean(list(teile.values()), axis=0)\nprint(pd.DataFrame(gower).round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       0      1      2      3\n0  0.000  0.243  0.493  0.882\n1  0.243  0.000  0.486  0.775\n2  0.493  0.486  0.000  0.489\n3  0.882  0.775  0.489  0.000\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nDie Einzelbeiträge für zwei Paare, jeweils zwischen 0 und 1:\n\n| Merkmal | Typ | Rechnung | Paar 1 bis 2 | Paar 1 bis 4 |\n|---|---|---|---|---|\n| umsatz | metrisch | $\\lvert x_i - x_j \\rvert$ geteilt durch die Spannweite 1500 | 300/1500 = **0.200** | 1200/1500 = **0.800** |\n| besuche | metrisch | geteilt durch die Spannweite 11 | 3/11 = **0.273** | 8/11 = **0.727** |\n| segment | nominal | 0 bei Gleichheit, sonst 1 | beide Privat → **0.000** | Privat gegen Gewerbe → **1.000** |\n| zufriedenheit | ordinal | Rangdifferenz, geteilt durch die Spannweite der Ränge | hoch gegen mittel → **0.500** | hoch gegen niedrig → **1.000** |\n| **Gower** | | Mittelwert der vier Beiträge | **0.243** | **0.882** |\n\nDie vollständige Matrix:\n\n| | 1 | 2 | 3 | 4 |\n|---|---|---|---|---|\n| 1 | 0.000 | **0.243** | 0.493 | 0.882 |\n| 2 | 0.243 | 0.000 | 0.486 | 0.775 |\n| 3 | 0.493 | 0.486 | 0.000 | 0.489 |\n| 4 | 0.882 | 0.775 | 0.489 | 0.000 |\n\n| Eigenschaft | Was sie bedeutet |\n|---|---|\n| Alle Werte liegen zwischen 0 und 1 | Eine Gower-Distanz von 0.5 heisst: im Mittel über alle Merkmale halb so verschieden wie überhaupt möglich. Das ist über Datensätze hinweg vergleichbar, anders als eine euklidische Distanz. |\n| Kunden 1 und 2 sind am ähnlichsten (0.243) | Sie stimmen im Segment überein und liegen in den metrischen Merkmalen nah beieinander. |\n| Kunden 1 und 4 sind am unähnlichsten (0.882) | Sie unterscheiden sich in **jedem** Merkmal, in zweien maximal. |\n| Jedes Merkmal trägt genau ein Viertel bei | Das ist die zentrale Eigenschaft und zugleich die Falle des Verfahrens. |\n\n::: {.note-box}\n**Gower gewichtet alle Merkmale gleich, und das ist eine Entscheidung.** Wer zehn\nmetrische und ein kategoriales Merkmal in die Matrix gibt, lässt das kategoriale\nmit einem Elftel praktisch wirkungslos und umgekehrt. Die Zusammenstellung der\nMerkmalsliste ist bei Gower also eine Gewichtungsentscheidung, auch wenn sie\nnicht so aussieht.\n\nZweiter Hinweis: `cluster::daisy()` behandelt geordnete Faktoren nach der\nVorschrift von Podani über Ränge und Bindungen. Bei Merkmalen mit vielen\nBindungen kann das von einer schlichten Rangdifferenz abweichen; welcher Weg\nverwendet wurde, gehört deshalb in den Methodenteil.\n:::\n\n#### Interpretation\n\nWeil nur eine Distanzmatrix nötig ist, lässt sich mit Gower dort clustern, wo\nk-Means gar nicht anwendbar wäre, allerdings nur mit\n[hierarchischen Verfahren](hierarchisches-clustering.qmd) oder k-Medoids, nicht\nmit k-Means, das Mittelwerte als Zentren braucht.\n\n### Beispiel 4: Binäre Merkmale und gemeinsame Nullen\n\n#### Frage und Datenlage\n\nEin Sortiment aus 1000 Artikeln, zwei Warenkörbe mit je fünf Artikeln, zwei davon\ngemeinsam. Wie ähnlich sind sich die beiden Kunden?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkorb_a <- numeric(1000); korb_a[c(1, 2, 3, 4, 5)] <- 1\nkorb_b <- numeric(1000); korb_b[c(4, 5, 6, 7, 8)] <- 1\nkoerbe <- rbind(a = korb_a, b = korb_b)\n\nround(c(euklidisch = dist(koerbe),\n        jaccard = dist(koerbe, method = \"binary\")), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\neuklidisch    jaccard \n     2.449      0.750 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Woraus sich Jaccard zusammensetzt\nc(beide_eins = sum(korb_a == 1 & korb_b == 1),\n  nur_einer  = sum(korb_a != korb_b),\n  beide_null = sum(korb_a == 0 & korb_b == 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbeide_eins  nur_einer beide_null \n         2          6        992 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nkorb_a = np.zeros(1000); korb_a[[0, 1, 2, 3, 4]] = 1\nkorb_b = np.zeros(1000); korb_b[[3, 4, 5, 6, 7]] = 1\nkoerbe = np.vstack([korb_a, korb_b])\n\nprint(\"euklidisch:\", round(float(pdist(koerbe, metric=\"euclidean\")[0]), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\neuklidisch: 2.449\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"jaccard:   \", round(float(pdist(koerbe, metric=\"jaccard\")[0]), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\njaccard:    0.75\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"beide_eins\": int(((korb_a == 1) & (korb_b == 1)).sum()),\n       \"nur_einer\": int((korb_a != korb_b).sum()),\n       \"beide_null\": int(((korb_a == 0) & (korb_b == 0)).sum())})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'beide_eins': 2, 'nur_einer': 6, 'beide_null': 992}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Zählung | Wert |\n|---|---|\n| Artikel in beiden Körben | 2 |\n| Artikel in genau einem Korb | 6 |\n| Artikel in keinem der beiden | 992 |\n\n| Mass | Wert hier | Rechnung | Was es zählt |\n|---|---|---|---|\n| Euklidisch | **2.449** | $\\sqrt{6}$, denn in sechs Positionen unterscheiden sich die Vektoren um je eins | Die 992 gemeinsamen Nullen tragen null bei, was hier zufällig richtig aussieht, aber aus dem falschen Grund. |\n| Jaccard | **0.750** | $1 - \\frac{2}{2 + 6} = 1 - 0.25$ | Anteil der Nichtübereinstimmung an allen Positionen, an denen **mindestens einer** eine Eins hat. Gemeinsame Nullen sind ausdrücklich ausgeschlossen. |\n\nDer Unterschied wird sichtbar, sobald das Sortiment wächst: Bei 100 000 Artikeln\nstatt 1000 bleibt die euklidische Distanz bei 2.449 und die Jaccard-Distanz bei\n0.750, aber ein Ähnlichkeitsmass, das gemeinsame Nullen mitzählt (etwa der\neinfache Übereinstimmungskoeffizient), würde alle Kunden fast identisch finden,\nweil sie 99.99 Prozent des Sortiments gemeinsam nicht kaufen.\n\n::: {.note-box}\nDie Frage lautet immer: **Ist eine gemeinsame Null Information?** Bei \"beide haben\ndiesen Artikel nicht gekauft\" oder \"beide Patienten haben dieses seltene Symptom\nnicht\" lautet die Antwort nein, dann Jaccard. Bei \"beide Schalter stehen auf\naus\" kann sie ja lauten, dann ein Mass, das Nullen mitzählt.\n:::\n\n#### Interpretation\n\nBinäre Merkmale sind der Fall, in dem die Wahl des Masses am deutlichsten über\ndas Ergebnis entscheidet, und zugleich der, in dem sie am häufigsten\nunreflektiert bleibt.\n\n### Beispiel 5: Wenn nur die Form zählt\n\n#### Frage und Datenlage\n\nDrei Sensoren liefern je einen Verlauf über fünf Zeitpunkte. Sensor 2 hat\ndenselben Verlauf wie Sensor 1, aber einen Offset von 50 Einheiten. Sensor 3\nliegt auf demselben Niveau wie Sensor 1, hat aber einen ganz anderen Verlauf.\n\n| Sensor | t1 | t2 | t3 | t4 | t5 |\n|---|---|---|---|---|---|\n| 1 | 10 | 12 | 15 | 13 | 11 |\n| 2 | 60 | 62 | 65 | 63 | 61 |\n| 3 | 13 | 11 | 10 | 12 | 15 |\n\nWelche zwei Sensoren gehören zusammen? Die Antwort hängt davon ab, ob das Niveau\nzählt oder die Form.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nverlaeufe <- rbind(\n  s1 = c(10, 12, 15, 13, 11),\n  s2 = c(60, 62, 65, 63, 61),\n  s3 = c(13, 11, 10, 12, 15)\n)\n\nround(dist(verlaeufe), 2)                        # euklidisch: Niveau zaehlt\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       s1     s2\ns2 111.80       \ns3   7.21 112.04\n```\n\n\n:::\n\n```{.r .cell-code}\nround(as.dist(1 - cor(t(verlaeufe))), 4)         # Korrelationsdistanz: Form\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       s1     s2\ns2 0.0000       \ns3 1.7568 1.7568\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nverlaeufe = pd.DataFrame(\n    [[10, 12, 15, 13, 11], [60, 62, 65, 63, 61], [13, 11, 10, 12, 15]],\n    index=[\"s1\", \"s2\", \"s3\"], dtype=float)\n\n\ndef zeige(daten, metrik, stellen):\n    d = pd.DataFrame(squareform(pdist(daten, metric=metrik)),\n                     index=daten.index, columns=daten.index)\n    print(d.round(stellen))\n\n\nzeige(verlaeufe, \"euclidean\", 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        s1      s2      s3\ns1    0.00  111.80    7.21\ns2  111.80    0.00  112.04\ns3    7.21  112.04    0.00\n```\n\n\n:::\n\n```{.python .cell-code}\nzeige(verlaeufe, \"correlation\", 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        s1      s2      s3\ns1  0.0000  0.0000  1.7568\ns2  0.0000  0.0000  1.7568\ns3  1.7568  1.7568  0.0000\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Paar | euklidisch | Korrelationsdistanz | Korrelation |\n|---|---|---|---|\n| s1, s2 | **111.80** | **0.0000** | 1.000 |\n| s1, s3 | **7.21** | **1.7568** | -0.757 |\n\n| Beobachtung | Deutung |\n|---|---|\n| Euklidisch: s1 und s3 sind **nah** (7.21), s1 und s2 **weit** (111.80) | Das Niveau dominiert vollständig. Der Offset von 50 Einheiten in jedem der fünf Zeitpunkte ergibt $\\sqrt{5 \\cdot 2500} = 111.8$. |\n| Korrelationsdistanz: s1 und s2 sind **identisch** (0.0000) | Ein konstanter Offset ändert die Korrelation nicht. Die Distanz misst allein, ob die Verläufe gleich **verlaufen**. |\n| s1 und s3 haben eine Distanz **über eins** (1.757) | Die Korrelationsdistanz $1 - r$ liegt zwischen 0 und 2. Werte über eins bedeuten negative Korrelation: Die Verläufe sind gegenläufig. |\n\n::: {.note-box}\nZwei Punkte, die regelmässig übersehen werden:\n\n- Die Korrelationsdistanz ist **keine echte Metrik**, die Dreiecksungleichung\n  gilt nicht. Verfahren, die darauf bauen (etwa Ward), können damit unerwartete\n  Ergebnisse liefern; hierarchisches Clustering mit Average-Linkage ist die\n  übliche Wahl.\n- Sie wird **je Objekt über die Zeitpunkte** gerechnet, nicht wie die\n  Standardisierung über alle Objekte je Variable. Das sind zwei verschiedene\n  Operationen, und die zweite löst das Niveauproblem nicht.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Ähnlichkeit der Sensorverläufe wurde über die Korrelationsdistanz\n> ($1 - r$ der Verläufe) bestimmt, weil das absolute Niveau der Sensoren von der\n> Kalibrierung abhängt und nicht vom Betriebszustand. Sensor 1 und 2 sind nach\n> diesem Mass identisch (Distanz 0.00), Sensor 3 verläuft gegenläufig (1.76).\n\nMit euklidischer Distanz wäre das Ergebnis genau umgekehrt ausgefallen und\nbeide Rechnungen wären korrekt.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nZwei Variablen liegen vor: Jahresumsatz in Franken und Anzahl Besuche. Ein\nk-Means ohne Standardisierung gruppiert praktisch nur nach Umsatz. Warum?\n\n- [x] Die Streuung des Umsatzes ist um Grössenordnungen grösser ~ Richtig. Die\n      euklidische Distanz summiert quadrierte Differenzen; die Variable mit der\n      grösseren Streuung dominiert. Nach der Standardisierung tragen beide gleich\n      viel bei.\n- [ ] k-Means kann nur eine Variable verarbeiten ~ Es verarbeitet alle, gewichtet\n      sie aber nach ihrer Streuung.\n- [ ] Die Anzahl Besuche ist ordinal ~ Sie ist eine Zählung und damit metrisch;\n      das ist nicht das Problem.\n:::\n\n::: {.quiz}\nEin Punkt weicht in fünf Dimensionen um je eine Einheit ab, ein anderer in einer\neinzigen um fünf. Welches Mass sieht die beiden als gleich weit entfernt?\n\n- [x] Manhattan ~ Richtig. Es summiert die absoluten Differenzen: fünf mal eins\n      ist dasselbe wie einmal fünf. Euklidisch ergibt 2.24 gegen 5.00, weil das\n      Quadrieren grosse Abweichungen überproportional gewichtet.\n- [ ] Euklidisch ~ Es sieht den zweiten Punkt als mehr als doppelt so weit\n      entfernt.\n- [ ] Maximum ~ Es sieht den Unterschied am deutlichsten: 1 gegen 5.\n:::\n\n::: {.quiz}\nEin Datensatz enthält Umsatz, Region und eine Zufriedenheitsstufe von eins bis\nfünf. Welches Distanzmass passt?\n\n- [ ] Euklidisch nach Umwandlung aller Merkmale in Zahlen ~ Damit bekommt die\n      Region ein willkürliches Gewicht, und Abstände zwischen Regionen wären\n      erfunden.\n- [x] Gower, weil er jeden Typ eigenständig behandelt ~ Richtig. Metrische\n      Merkmale werden auf ihre Spannweite normiert, nominale über\n      Übereinstimmung verglichen, ordinale über Ränge. Alle Variablen tragen\n      danach vergleichbar bei, was zugleich heisst, dass die Merkmalsliste zur\n      Gewichtungsentscheidung wird.\n- [ ] Jaccard ~ Der ist für binäre Merkmale gedacht.\n:::\n\n::: {.quiz}\nWarum zählt die Jaccard-Distanz gemeinsame Nullen nicht mit?\n\n- [x] Weil zwei Objekte durch das gemeinsame Fehlen eines Merkmals nicht\n      ähnlicher werden ~ Richtig. Bei 1000 Artikeln und je fünf gekauften wären\n      sonst alle Kunden fast identisch, weil sie 99 Prozent des Sortiments\n      gemeinsam nicht kaufen.\n- [ ] Weil Nullen keine gültigen Werte sind ~ Sie sind gültig, nur meist nicht\n      informativ.\n- [ ] Weil das Mass sonst grösser als eins würde ~ Es liegt in beiden Varianten\n      zwischen null und eins.\n:::\n\n::: {.quiz}\nZwei Zeitverläufe haben dieselbe Form, liegen aber auf verschiedenem Niveau. Sie\nsollen als ähnlich gelten. Welches Mass?\n\n- [x] Korrelationsdistanz, weil sie das Niveau ignoriert ~ Richtig. Sie\n      vergleicht die Form des Verlaufs; ein konstanter Offset ändert sie nicht.\n      Euklidisch würde die beiden wegen des Niveauunterschieds als weit entfernt\n      einordnen.\n- [ ] Manhattan, weil es robuster ist ~ Robustheit betrifft Ausreisser, nicht\n      Niveauunterschiede.\n- [ ] Euklidisch nach Standardisierung der Variablen ~ Standardisiert wird über\n      alle Objekte hinweg je Variable, nicht je Verlauf über die Zeitpunkte; das\n      löst das Problem nicht.\n:::\n\n## Verlinkte Ressourcen\n\n- [An Introduction to Statistical Learning, Kapitel 12](https://www.statlearning.com/)\n- [cluster: daisy und Gower-Distanz](https://cran.r-project.org/web/packages/cluster/cluster.pdf)\n- [scipy: Übersicht der Distanzmasse](https://docs.scipy.org/doc/scipy/reference/spatial.distance.html)\n- [Lineare Algebra für die PCA](lineare-algebra-pca.qmd)\n",
    "supporting": [
      "distanzmasse_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}