{
  "hash": "695b2a493c0c35ac1fcace06faf217e3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"SQLite\"\ndescription: \"Die Datenbank als einzelne Datei: ohne Server, ideal für Auswertungen und Prototypen.\"\ncategories: [\"Datenbanken\", \"SQL\", \"R\", \"Python\"]\nquelle: [\"PYFR\"]\nseitentyp: werkzeug\nstand: entwurf\norder: 40\n---\n\n\n\n\n\n## Kernideen\n\n- Eine Datenbank ist **eine einzige Datei**, es läuft kein Server. In R und\n  Python ist der Treiber bereits dabei.\n- **Typen sind Empfehlungen**: Eine `INTEGER`-Spalte nimmt auch Text an, und\n  eine Summe darüber rechnet stillschweigend weiter.\n- Wer das ausschliessen will, nutzt `CHECK`, `NOT NULL` und seit SQLite 3.37\n  **`STRICT`**-Tabellen.\n- Kein eigener **Datums- und Wahrheitstyp**; beides wird als Text\n  beziehungsweise Zahl abgelegt.\n- **Fremdschlüssel sind standardmässig aus** und gehören je Verbindung\n  eingeschaltet.\n- Die Grenze ist der **gleichzeitige Schreibzugriff**, nicht die Datenmenge.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [SQL](sql.qmd) für die Abfragen,\n[Datenmodellierung](datenmodellierung.qmd) für den Tabellenentwurf und\n[Datenbankzugriff](datenbanken-zugriff.qmd) für Verbindung und Parameter.\nWelches System wann passt, steht in der [Übersicht](index.qmd).\n:::\n\n### Was SQLite ist\n\nSQLite ist eine Programmbibliothek, keine Serveranwendung. Die gesamte\nDatenbank steht in einer Datei, und das Programm spricht direkt mit dieser\nDatei. Es gibt keinen Dienst, keinen Port, keine Benutzer und keine\nRechteverwaltung. Genau das macht sie für die Datenarbeit praktisch: Eine\nAuswertung braucht keine Infrastruktur, und die Datenbank lässt sich\nkopieren, versionieren und weitergeben wie jede andere Datei.\n\nDer Preis ist das Schreibmodell. Lesen können viele Prozesse gleichzeitig,\nschreiben nur einer. Für eine Anwendung mit vielen gleichzeitigen Benutzern\nist das die falsche Wahl, für eine Auswertung spielt es keine Rolle.\n\n### Wann SQLite, wann ein Server\n\n| Fall | Wahl |\n|---|---|\n| Datei zu gross für den Arbeitsspeicher | SQLite, einmal einlesen, danach gezielt abfragen |\n| Zwischenstand mehrerer Skripte | SQLite als Datei im Projekt |\n| eine Person wertet aus | SQLite |\n| viele schreiben gleichzeitig | [PostgreSQL](postgresql.qmd), [MySQL](mysql-mariadb.qmd) |\n| Rechteverwaltung, Netzwerkzugriff | Server |\n| analytische Abfragen über viele Spalten | [DuckDB](duckdb.qmd) |\n\n### Typaffinität\n\nSQLite ist dynamisch typisiert. Der deklarierte Typ ist eine **Affinität**:\nDie Datenbank wandelt um, wo es geht, und speichert sonst, was kommt. Das ist\nbequem beim Einlesen roher Daten und eine Fehlerquelle bei allem danach. Drei\nGegenmittel:\n\n| Mittel | Wirkung |\n|---|---|\n| `CHECK (wert >= 0)` | prüft den Inhalt bei jedem Schreiben |\n| `NOT NULL` | verhindert fehlende Werte |\n| `... ) STRICT` | erzwingt die deklarierten Typen, seit SQLite 3.37 |\n\n### Die Funktion `typeof()`\n\n`SELECT typeof(spalte)` zeigt je Zeile, was wirklich gespeichert ist. Das ist\nder schnellste Weg, eine verunreinigte Spalte zu finden, und es gibt ihn nur\nin SQLite.\n\n### Kurz nachgeschlagen\n\n| Aufgabe | SQL beziehungsweise Befehl |\n|---|---|\n| Tabellen auflisten | `SELECT name FROM sqlite_master WHERE type='table'` |\n| Spalten und Typen | `PRAGMA table_info(tabelle)` oder `pragma_table_info('tabelle')` |\n| tatsächlicher Typ je Zeile | `SELECT typeof(spalte) FROM tabelle` |\n| Fremdschlüssel einschalten | `PRAGMA foreign_keys = ON` (je Verbindung) |\n| Abfrageplan ansehen | `EXPLAIN QUERY PLAN SELECT ...` |\n| Index anlegen | `CREATE INDEX idx ON tabelle(spalte)` |\n| Datei aufräumen | `VACUUM` |\n| grosse CSV überführen | stückweise lesen und `append` schreiben |\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Der Typ ist nur eine Empfehlung\n\n#### Frage und Datenlage\n\nEine Spalte ist als `INTEGER` angelegt. Was passiert, wenn dort `42`, der\nText `k.A.` und die Zahl `3.7` landen, und was ergibt die Summe?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntue(\"CREATE TABLE messung (id INTEGER PRIMARY KEY, wert INTEGER)\")\ntue(\"INSERT INTO messung VALUES (1, 42), (2, 'k.A.'), (3, 3.7)\")\n\nfrage(\"SELECT id, wert, typeof(wert) AS typ FROM messung\")\n```\n\n::: {.cell-output-display}\n\n\n| id| wert|typ     |\n|--:|----:|:-------|\n|  1| 42.0|integer |\n|  2|  0.0|text    |\n|  3|  3.7|real    |\n\n\n:::\n\n```{.r .cell-code}\nfrage(\"SELECT typeof(wert) AS typ, COUNT(*) AS n FROM messung GROUP BY typeof(wert)\")\n```\n\n::: {.cell-output-display}\n\n\n|typ     |  n|\n|:-------|--:|\n|integer |  1|\n|real    |  1|\n|text    |  1|\n\n\n:::\n\n```{.r .cell-code}\nfrage(\"SELECT SUM(wert) AS summe, COUNT(*) AS n, AVG(wert) AS mittel FROM messung\")\n```\n\n::: {.cell-output-display}\n\n\n| summe|  n|   mittel|\n|-----:|--:|--------:|\n|  45.7|  3| 15.23333|\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nverbindung.executescript(\"\"\"\n  CREATE TABLE messung (id INTEGER PRIMARY KEY, wert INTEGER);\n  INSERT INTO messung VALUES (1, 42), (2, 'k.A.'), (3, 3.7);\"\"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<sqlite3.Cursor object at 0x7f0dbff88440>\n```\n\n\n:::\n\n```{.python .cell-code}\nverbindung.commit()\n\nprint(frage(\"SELECT id, wert, typeof(wert) AS typ FROM messung\").to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n id wert     typ\n  1   42 integer\n  2 k.A.    text\n  3  3.7    real\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(frage(\"\"\"SELECT typeof(wert) AS typ, COUNT(*) AS n FROM messung\n               GROUP BY typeof(wert)\"\"\").to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    typ  n\ninteger  1\n   real  1\n   text  1\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(frage(\"SELECT SUM(wert) AS summe, COUNT(*) AS n FROM messung\"\n            ).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n summe  n\n  45.7  3\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Zeile | Wert | `typeof` | Erklärung |\n|---|---|---|---|\n| 1 | 42 | **integer** | wie deklariert |\n| 2 | `k.A.` | **text** | Der Text wird angenommen, obwohl die Spalte `INTEGER` heisst. |\n| 3 | 3.7 | **real** | Auch die Kommazahl bleibt, was sie ist. |\n\n| Kennzahl | Wert | Erklärung |\n|---|---|---|\n| `COUNT(*)` | 3 | drei Zeilen |\n| `SUM(wert)` | **45.7** | 42 + 3.7, der Text zählt als 0. **Keine Fehlermeldung, kein `NULL`.** |\n\n#### Interpretation und Ergebnissatz\n\nDie Summe 45.7 ist das Gefährliche an der Typaffinität: Sie sieht richtig aus.\nEine Spalte mit einem einzigen `k.A.` liefert eine plausible Summe, die zu\nklein ist, und nichts weist darauf hin. Deshalb gehört nach jedem Import roher\nDaten eine Abfrage auf `typeof()` je Spalte, oder die Tabelle wird gleich als\n`STRICT` angelegt.\n\n> In der als `INTEGER` deklarierten Spalte stehen ein Integer, ein Text und\n> eine Realzahl nebeneinander. Die Summe beträgt 45.7, weil der Text\n> stillschweigend als 0 zählt.\n\n### Beispiel 2: Bedingungen und STRICT\n\n#### Frage und Datenlage\n\nDieselbe Tabelle mit `NOT NULL`, `CHECK (wert >= 0)` und als `STRICT`\nangelegt. Welche vier Einfügeversuche gehen durch?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfrage(\"SELECT sqlite_version() AS version\")\n```\n\n::: {.cell-output-display}\n\n\n|version |\n|:-------|\n|3.53.3  |\n\n\n:::\n\n```{.r .cell-code}\nangelegt <- try(dbExecute(con, \"CREATE TABLE streng (\n    id   INTEGER PRIMARY KEY,\n    wert REAL NOT NULL CHECK (wert >= 0)) STRICT\"), silent = TRUE)\nif (inherits(angelegt, \"try-error\")) \"STRICT nicht unterstuetzt\" else \"STRICT angelegt\"\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"STRICT angelegt\"\n```\n\n\n:::\n\n```{.r .cell-code}\nfor (sql in c(\"INSERT INTO streng VALUES (1, 12.5)\",\n              \"INSERT INTO streng VALUES (2, -1)\",\n              \"INSERT INTO streng VALUES (3, 'k.A.')\",\n              \"INSERT INTO streng VALUES (4, NULL)\")) {\n  ergebnis <- try(dbExecute(con, sql), silent = TRUE)\n  cat(sub(\".*VALUES \", \"\", sql), \":\",\n      if (inherits(ergebnis, \"try-error\")) \"abgelehnt\" else \"angenommen\", \"\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(1, 12.5) : angenommen \n(2, -1) : abgelehnt \n(3, 'k.A.') : abgelehnt \n(4, NULL) : abgelehnt \n```\n\n\n:::\n\n```{.r .cell-code}\nfrage(\"SELECT COUNT(*) AS zeilen FROM streng\")\n```\n\n::: {.cell-output-display}\n\n\n| zeilen|\n|------:|\n|      1|\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(frage(\"SELECT sqlite_version() AS version\").to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nversion\n 3.45.1\n```\n\n\n:::\n\n```{.python .cell-code}\nverbindung.executescript(\"\"\"CREATE TABLE streng (\n    id   INTEGER PRIMARY KEY,\n    wert REAL NOT NULL CHECK (wert >= 0)) STRICT;\"\"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<sqlite3.Cursor object at 0x7f0dbff27740>\n```\n\n\n:::\n\n```{.python .cell-code}\nverbindung.commit()\n\nfor sql, was in [(\"INSERT INTO streng VALUES (1, 12.5)\", \"12.5\"),\n                 (\"INSERT INTO streng VALUES (2, -1)\", \"-1\"),\n                 (\"INSERT INTO streng VALUES (3, 'k.A.')\", \"'k.A.'\"),\n                 (\"INSERT INTO streng VALUES (4, NULL)\", \"NULL\")]:\n    try:\n        verbindung.execute(sql)\n        verbindung.commit()\n        print(was, \"angenommen\")\n    except sqlite3.Error as fehler:\n        print(was, \"abgelehnt:\", str(fehler)[:50])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<sqlite3.Cursor object at 0x7f0dbff27c40>\n12.5 angenommen\n-1 abgelehnt: CHECK constraint failed: wert >= 0\n'k.A.' abgelehnt: cannot store TEXT value in REAL column streng.wert\nNULL abgelehnt: NOT NULL constraint failed: streng.wert\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Versuch | Ergebnis | Regel, die greift |\n|---|---|---|\n| `12.5` | **angenommen** | erfüllt alles |\n| `-1` | **abgelehnt**, `CHECK constraint failed: wert >= 0` | `CHECK` |\n| `'k.A.'` | **abgelehnt**, `cannot store TEXT value in REAL column` | **`STRICT`**; ohne diesen Zusatz wäre der Text angenommen worden, wie in Beispiel 1. |\n| `NULL` | **abgelehnt**, `NOT NULL constraint failed` | `NOT NULL` |\n\n#### Interpretation und Ergebnissatz\n\nMit drei Zusätzen verhält sich SQLite wie eine Datenbank mit festen Typen.\n`STRICT` gibt es seit Version 3.37; die Abfrage `sqlite_version()` zeigt, was\ndie eigene Installation mitbringt. Für Tabellen, die roh eingelesene Daten\naufnehmen, ist die lockere Variante bequem; für alles, womit danach gerechnet\nwird, ist die strenge die richtige.\n\n> Von vier Einfügeversuchen geht nur der gültige durch: Die negative Zahl\n> scheitert am `CHECK`, der Text am `STRICT`, der fehlende Wert am\n> `NOT NULL`.\n\n### Beispiel 3: Die Datenbank ist eine Datei\n\n#### Frage und Datenlage\n\nEine Datenbank wird als Datei angelegt, gefüllt und geschlossen. Was steht\ndanach auf der Platte, und was findet man beim erneuten Öffnen?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npfad <- file.path(tempdir(), \"laden.sqlite\")\ndatei <- dbConnect(RSQLite::SQLite(), pfad)\ninvisible(dbExecute(datei, \"CREATE TABLE artikel (id INTEGER PRIMARY KEY, name TEXT)\"))\ninvisible(dbExecute(datei, \"INSERT INTO artikel VALUES (1,'Ventil'), (2,'Zylinder')\"))\ndbDisconnect(datei)\n\nc(vorhanden = file.exists(pfad), bytes = file.size(pfad))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nvorhanden     bytes \n        1      8192 \n```\n\n\n:::\n\n```{.r .cell-code}\nwieder <- dbConnect(RSQLite::SQLite(), pfad)\ndbListTables(wieder)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"artikel\"\n```\n\n\n:::\n\n```{.r .cell-code}\ndbGetQuery(wieder, \"SELECT COUNT(*) AS n FROM artikel\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  n\n1 2\n```\n\n\n:::\n\n```{.r .cell-code}\ndbDisconnect(wieder)\n```\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nordner = pathlib.Path(tempfile.mkdtemp())\npfad = ordner / \"laden.sqlite\"\n\ndatei = sqlite3.connect(pfad)\ndatei.executescript(\"\"\"CREATE TABLE artikel (id INTEGER PRIMARY KEY, name TEXT);\n                       INSERT INTO artikel VALUES (1,'Ventil'), (2,'Zylinder');\"\"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<sqlite3.Cursor object at 0x7f0dbff89340>\n```\n\n\n:::\n\n```{.python .cell-code}\ndatei.commit()\ndatei.close()\n\nprint(pfad.exists(), pfad.stat().st_size)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue 8192\n```\n\n\n:::\n\n```{.python .cell-code}\nwieder = sqlite3.connect(pfad)\nprint(pd.read_sql_query(\"SELECT name FROM sqlite_master WHERE type='table'\",\n                        wieder)[\"name\"].tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['artikel']\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pd.read_sql_query(\"SELECT COUNT(*) AS n FROM artikel\", wieder).iloc[0, 0])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2\n```\n\n\n:::\n\n```{.python .cell-code}\nwieder.close()\n```\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Schritt | Ergebnis | Erklärung |\n|---|---|---|\n| Datei vorhanden | **`True`** | Sie entsteht beim Verbinden, nicht erst beim Schreiben. |\n| Grösse | **8192 Byte** | zwei Seiten à 4096 Byte: Kopf und Inhalt. Eine leere Datenbank ist winzig. |\n| Tabellen nach dem erneuten Öffnen | `artikel` | Alles steht in der Datei, es gibt keinen Server, der etwas hält. |\n| Zeilen | 2 | |\n\nDie Liste der Tabellen steht in der Systemtabelle `sqlite_master`, die jede\nSQLite-Datei mitbringt. In R gibt es dafür zusätzlich `dbListTables()`.\n\n#### Interpretation und Ergebnissatz\n\nWeil die Datenbank eine Datei ist, gelten für sie die Regeln von Dateien: Sie\nlässt sich kopieren, in ein Backup legen und weitergeben. Was sie nicht\nverträgt, ist gleichzeitiges Schreiben aus mehreren Prozessen, und was nicht\nin die Versionsverwaltung gehört, ist die Datei selbst: Sie ist binär, und\njede Änderung erzeugt einen unlesbaren Diff.\n\n> Die angelegte Datei ist 8192 Byte gross und enthält nach dem erneuten\n> Öffnen die Tabelle `artikel` mit zwei Zeilen, ohne dass ein Dienst läuft.\n\n### Beispiel 4: Index und Abfrageplan\n\n#### Frage und Datenlage\n\nEine Tabelle mit 50 000 Messwerten und 500 Geräten. Wie beantwortet SQLite\ndie Frage nach einem Gerät, mit und ohne Index?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 50000\nmesswert <- data.frame(id = seq_len(n),\n                       geraet_id = (seq_len(n) - 1) %% 500,\n                       wert = ((seq_len(n) * 37) %% 1000) / 10)\ninvisible(dbWriteTable(con, \"messwert\", messwert, overwrite = TRUE))\nfrage(\"SELECT COUNT(*) AS zeilen FROM messwert\")\n```\n\n::: {.cell-output-display}\n\n\n| zeilen|\n|------:|\n|  50000|\n\n\n:::\n\n```{.r .cell-code}\nfrage(\"EXPLAIN QUERY PLAN SELECT * FROM messwert WHERE geraet_id = 42\")\n```\n\n::: {.cell-output-display}\n\n\n| id| parent| notused|detail        |\n|--:|------:|-------:|:-------------|\n|  2|      0|     216|SCAN messwert |\n\n\n:::\n\n```{.r .cell-code}\ntue(\"CREATE INDEX idx_geraet ON messwert(geraet_id)\")\nfrage(\"EXPLAIN QUERY PLAN SELECT * FROM messwert WHERE geraet_id = 42\")\n```\n\n::: {.cell-output-display}\n\n\n| id| parent| notused|detail                                               |\n|--:|------:|-------:|:----------------------------------------------------|\n|  3|      0|      62|SEARCH messwert USING INDEX idx_geraet (geraet_id=?) |\n\n\n:::\n\n```{.r .cell-code}\nfrage(\"SELECT COUNT(*) AS treffer FROM messwert WHERE geraet_id = 42\")\n```\n\n::: {.cell-output-display}\n\n\n| treffer|\n|-------:|\n|     100|\n\n\n:::\n\n```{.r .cell-code}\nfrage(\"EXPLAIN QUERY PLAN SELECT * FROM messwert WHERE wert > 90\")\n```\n\n::: {.cell-output-display}\n\n\n| id| parent| notused|detail        |\n|--:|------:|-------:|:-------------|\n|  2|      0|     216|SCAN messwert |\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nverbindung.execute(\"CREATE TABLE messwert (id INTEGER PRIMARY KEY, \"\n                   \"geraet_id INTEGER, wert REAL)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<sqlite3.Cursor object at 0x7f0dbff8ab40>\n```\n\n\n:::\n\n```{.python .cell-code}\nverbindung.executemany(\"INSERT INTO messwert VALUES (?,?,?)\",\n                       [(i, i % 500, (i * 37 % 1000) / 10) for i in range(1, 50001)])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<sqlite3.Cursor object at 0x7f0dbff8ae40>\n```\n\n\n:::\n\n```{.python .cell-code}\nverbindung.commit()\nprint(frage(\"SELECT COUNT(*) AS zeilen FROM messwert\").iloc[0, 0])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n50000\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(frage(\"EXPLAIN QUERY PLAN SELECT * FROM messwert WHERE geraet_id = 42\"\n            )[\"detail\"].tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['SCAN messwert']\n```\n\n\n:::\n\n```{.python .cell-code}\nverbindung.execute(\"CREATE INDEX idx_geraet ON messwert(geraet_id)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<sqlite3.Cursor object at 0x7f0dbff8b640>\n```\n\n\n:::\n\n```{.python .cell-code}\nverbindung.commit()\nprint(frage(\"EXPLAIN QUERY PLAN SELECT * FROM messwert WHERE geraet_id = 42\"\n            )[\"detail\"].tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['SEARCH messwert USING INDEX idx_geraet (geraet_id=?)']\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(frage(\"SELECT COUNT(*) AS treffer FROM messwert WHERE geraet_id = 42\").iloc[0, 0])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n100\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(frage(\"EXPLAIN QUERY PLAN SELECT * FROM messwert WHERE wert > 90\"\n            )[\"detail\"].tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['SCAN messwert']\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Abfrage | Plan | Erklärung |\n|---|---|---|\n| nach `geraet_id`, **ohne** Index | **`SCAN messwert`** | Die Datenbank liest alle 50 000 Zeilen und behält die passenden. |\n| nach `geraet_id`, **mit** Index | **`SEARCH messwert USING INDEX idx_geraet (geraet_id=?)`** | Jetzt springt sie über den Index direkt zu den Treffern. |\n| Treffer | **100** Zeilen | 50 000 / 500 Geräte |\n| nach `wert > 90`, ohne passenden Index | `SCAN messwert` | Der Index auf `geraet_id` hilft hier nicht; ein Index wirkt nur für die Spalten, über die er geht. |\n\n`EXPLAIN QUERY PLAN` ist die eigentliche Antwort auf \"warum ist das langsam\".\nDie Wörter `SCAN` und `SEARCH` sagen es direkt, und zwar ohne Zeitmessung,\ndie je nach Rechner schwankt.\n\n#### Interpretation und Ergebnissatz\n\nEin Index ist kein allgemeiner Beschleuniger, sondern ein Verzeichnis für\n**eine bestimmte Spalte**. Er kostet Platz und verlangsamt das Schreiben,\nweshalb man ihn dort setzt, wo regelmässig gefiltert oder verbunden wird,\ntypischerweise auf Fremdschlüsseln. Ob er greift, zeigt der Abfrageplan;\nVermutungen darüber sind unnötig.\n\n> Ohne Index liest SQLite für die Frage nach einem Gerät alle 50 000 Zeilen\n> (`SCAN`), mit Index greift es über `SEARCH ... USING INDEX` direkt auf die\n> 100 Treffer zu. Für die Bedingung auf `wert` bleibt es beim `SCAN`.\n\n### Beispiel 5: Stückweise lesen\n\n#### Frage und Datenlage\n\nDie Summe aller 50 000 Messwerte, ohne die Tabelle auf einmal in den\nArbeitsspeicher zu laden.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nabfrage <- dbSendQuery(con, \"SELECT wert FROM messwert\")\nsumme <- 0\nstuecke <- 0\nwhile (!dbHasCompleted(abfrage)) {\n  teil <- dbFetch(abfrage, n = 10000)\n  if (nrow(teil) == 0) break\n  summe <- summe + sum(teil$wert)\n  stuecke <- stuecke + 1\n}\ndbClearResult(abfrage)\n\nc(stuecke = stuecke, summe = summe)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstuecke   summe \n      5 2497500 \n```\n\n\n:::\n\n```{.r .cell-code}\ndbGetQuery(con, \"SELECT SUM(wert) AS summe FROM messwert\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    summe\n1 2497500\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nsumme = 0.0\nstuecke = 0\nfor teil in pd.read_sql_query(\"SELECT wert FROM messwert\", verbindung,\n                              chunksize=10000):\n    summe += teil[\"wert\"].sum()\n    stuecke += 1\n\nprint(stuecke, round(summe, 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n5 2497500.0\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(round(frage(\"SELECT SUM(wert) AS summe FROM messwert\").iloc[0, 0], 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2497500.0\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | Wert | Erklärung |\n|---|---|---|\n| Stücke | **5** | 50 000 Zeilen zu je 10 000 |\n| Summe stückweise | **2497500.0** | |\n| Summe in der Datenbank | **2497500.0** | dieselbe Zahl, aber in einer Zeile übertragen |\n\nFür eine blosse Summe ist der Weg über die Datenbank offensichtlich besser.\nDas stückweise Lesen lohnt dort, wo je Zeile etwas geschehen muss, das SQL\nnicht kann: ein Modell anwenden, Text verarbeiten, eine Datei schreiben.\n\n#### Interpretation und Ergebnissatz\n\nDer Arbeitsspeicher ist bei SQLite selten die Grenze, weil man nie alles\nladen muss. Das ist der Grund, warum eine zu grosse CSV-Datei zuerst in eine\nSQLite-Datei wandert: Danach beantwortet man jede Frage mit einer Abfrage\nstatt mit einem Import.\n\n> Stückweise gelesen ergeben die 50 000 Messwerte in fünf Teilen die Summe\n> 2497500.0, genau wie die Abfrage `SELECT SUM(wert)`, die dafür eine einzige\n> Zeile überträgt.\n\n::::\n\n\n\n\n\n## Verständnisfragen\n\n::: {.quiz}\nEine Spalte ist als `INTEGER` angelegt, und beim Import landen dort Texte wie\n`k.A.`. Was ist passiert?\n\n- [ ] Der Import ist fehlerhaft und muss wiederholt werden ~ Der Import hat\n      getan, was er sollte; SQLite hat den Wert angenommen.\n- [x] SQLite behandelt den deklarierten Typ als Empfehlung ~ Richtig. Die\n      Typaffinität wandelt um, wo möglich, und speichert sonst wie geliefert.\n      `CHECK`, `NOT NULL` oder eine `STRICT`-Tabelle schliessen es aus.\n- [ ] Die Spalte war in Wahrheit als `TEXT` deklariert ~ Auch bei `INTEGER`\n      passiert genau das.\n:::\n\n::: {.quiz}\nIn einer Spalte mit 1000 Messwerten steht in einer Zeile `k.A.`. Was liefert\n`SELECT SUM(wert)`?\n\n- [x] Eine plausible, aber zu kleine Summe, denn der Text zählt als 0 ~\n      Richtig, wie die 45.7 in Beispiel 1. Es gibt weder Fehler noch `NULL`,\n      und genau das macht den Fall gefährlich.\n- [ ] `NULL`, weil ein Wert ungültig ist ~ Das wäre das Verhalten bei einem\n      echten `NULL` in manchen anderen Systemen.\n- [ ] Einen Fehler ~ SQLite rechnet stillschweigend weiter.\n:::\n\n::: {.quiz}\nEine Abfrage auf einer grossen Tabelle ist langsam. Was ist der erste\nSchritt?\n\n- [x] `EXPLAIN QUERY PLAN` ansehen und prüfen, ob `SCAN` oder `SEARCH` steht ~\n      Richtig. Das sagt ohne Zeitmessung, ob ein Index greift, und ist auf\n      jedem Rechner gleich.\n- [ ] Die Tabelle in mehrere kleinere aufteilen ~ Das löst selten etwas und\n      verkompliziert jede Abfrage.\n- [ ] Auf jede Spalte einen Index legen ~ Indizes kosten Platz und\n      verlangsamen das Schreiben; sie gehören auf die Spalten, nach denen\n      gefiltert oder verbunden wird.\n:::\n\n::: {.quiz}\nWarum gehört eine `.sqlite`-Datei in der Regel nicht ins Git-Repository?\n\n- [x] Sie ist binär, und jede Änderung erzeugt einen unlesbaren Diff ~\n      Richtig. Versioniert wird der Code, der sie erzeugt, und bei Bedarf die\n      Rohdaten. Für kleine, unveränderliche Referenzdaten kann es Ausnahmen\n      geben.\n- [ ] Git kann keine Binärdateien speichern ~ Kann es, nur wächst das\n      Repository mit jeder Fassung.\n- [ ] SQLite-Dateien sind zu gross ~ Sie können klein sein; das Problem ist\n      die Nachvollziehbarkeit.\n:::\n\n::: {.quiz}\nEine Auswertung soll je Zeile ein Modell anwenden, und die Tabelle hat zehn\nMillionen Zeilen. Was ist der Weg?\n\n- [x] Stückweise lesen und je Stück verarbeiten ~ Richtig, mit `chunksize`\n      beziehungsweise `dbFetch(n = ...)`. So bleibt der Arbeitsspeicher\n      konstant belegt, wie in Beispiel 5.\n- [ ] Alles laden, dann verarbeiten ~ Genau das soll vermieden werden.\n- [ ] Die Verarbeitung in SQL nachbauen ~ Für Summen und Filter ja, für ein\n      Modell in der Regel nicht.\n:::\n\n## Verlinkte Ressourcen\n\n- [SQLite: Typaffinität](https://www.sqlite.org/datatype3.html)\n- [SQLite: STRICT-Tabellen](https://www.sqlite.org/stricttables.html)\n- [SQLite: Abfragepläne](https://www.sqlite.org/eqp.html)\n",
    "supporting": [
      "sqlite_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}