{
  "hash": "15b60f30580408eb8db9069768011ba6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Ergebnisse berichten\"\ndescription: \"Statistische Ergebnisse vollständig und im APA-Stil berichten: was in den Satz gehört, wie Zahlen formatiert werden und was nicht.\"\ncategories: [\"Kommunikation\", \"Interpretation\", \"Hypothesentests\", \"Effektstärke\", \"R\", \"Python\"]\nseitentyp: konzept\nstand: fertig\norder: 10\n---\n\n\n\n\n\n## Kernideen\n\n- Ein Ergebnissatz beantwortet **die Frage in Worten** und belegt die Antwort mit Zahlen in Klammern\n- Zur Teststatistik gehören immer **Freiheitsgrade, p-Wert, Effektstärke und Konfidenzintervall**\n- Die **Grösse des Effekts in seiner Einheit** ist wichtiger als der p-Wert\n- p-Werte **exakt** berichten, nur unter .001 als Schranke; nie „n.s.\" oder Sternchen allein\n- Zahlen, die höchstens 1 werden können (p, r, R²), ohne führende Null: `p = .013`\n- Die Zahlen im Satz kommen **aus dem Code**, nicht aus der abgetippten Konsole\n\n## Erklärung\n\n::: {.note-box}\nJede Methodenseite im Bereich [Statistik](../statistik/index.qmd) hat einen\nAbschnitt „Ergebnis berichten\" mit der passenden Vorlage. Diese Seite fasst\nzusammen, was für alle gilt. Die Formatregeln folgen dem Stil der American\nPsychological Association (APA, 7. Auflage), der in den Sozial-, Wirtschafts-\nund Lebenswissenschaften am weitesten verbreitet ist.\n:::\n\n### Was in einen Ergebnissatz gehört\n\n| Bestandteil | Warum | Beispiel |\n|---|---|---|\n| Antwort auf die Frage | Leserin soll ohne Zahlen verstehen, was herauskam | „Maschine A fertigt dünner als Maschine B\" |\n| deskriptive Werte je Gruppe | ohne sie ist die Richtung nicht prüfbar | M = 12.05 mm, SD = 0.16 |\n| Effekt in seiner Einheit mit Intervall | beantwortet „wie viel\" | Differenz 0.20 mm, 95% KI [0.05, 0.36] |\n| Teststatistik mit Freiheitsgraden | macht das Verfahren nachvollziehbar | t(24.38) = -2.67 |\n| p-Wert | Evidenz gegen die Nullhypothese | p = .013 |\n| standardisierte Effektstärke | vergleichbar über Studien | d = -0.97 |\n| Verfahren und Voraussetzungen | was genau gerechnet wurde | Welch-Test, Normalverteilung per QQ-Plot geprüft |\n\n### Formatregeln\n\n| Regel | richtig | falsch |\n|---|---|---|\n| Statistiksymbole kursiv | *t*, *F*, *p*, *M*, *SD* | t, F, p |\n| führende Null nur, wenn der Wert über 1 steigen kann | *p* = .013, *r* = .45, *M* = 0.97 | *p* = 0.013 |\n| p-Werte exakt, auf drei Stellen | *p* = .013 | *p* < .05 |\n| sehr kleine p-Werte als Schranke | *p* < .001 | *p* = .000 |\n| Teststatistiken und Effekte auf zwei Stellen | *t* = -2.67, *d* = -0.97 | *t* mit sechs Nachkommastellen |\n| Freiheitsgrade in Klammern | *t*(24.38), *F*(2, 42) | t = 2.67, df = 24.38 |\n| Konfidenzintervall in eckigen Klammern | 95% KI [0.05, 0.36] | (0.05-0.36) |\n\nIn deutschsprachigen Texten wird oft das Dezimalkomma verwendet. Wichtig ist\nnicht, welche Variante gewählt wird, sondern dass sie im ganzen Text einheitlich\nist und zu den Vorgaben der Zeitschrift oder Institution passt.\n\n### Muster für häufige Verfahren\n\n| Verfahren | Muster |\n|---|---|\n| t-Test | *t*(df) = t, *p* = .xxx, *d* = x.xx, 95% KI [u, o] |\n| ANOVA | *F*(df1, df2) = F, *p* = .xxx, η² = .xx |\n| Chi-Quadrat | χ²(df, *N* = n) = x.xx, *p* = .xxx, *V* = .xx |\n| Korrelation | *r*(df) = .xx, *p* = .xxx, 95% KI [.u, .o] |\n| Regression, Koeffizient | *b* = x.xx, *SE* = x.xx, *t*(df) = x.xx, *p* = .xxx |\n| Regression, Modell | *R*² = .xx, *F*(df1, df2) = x.xx, *p* = .xxx |\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: p-Werte formatieren\n\n#### Frage und Datenlage\n\nFünf p-Werte aus Auswertungen sollen im APA-Stil erscheinen: 0.0133, 0.0004,\n0.049999, 0.5 und 0.05.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwerte <- c(0.0133, 0.0004, 0.049999, 0.5, 0.05)\ndata.frame(p = werte, apa = sapply(werte, p_apa))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         p      apa\n1 0.013300 p = .013\n2 0.000400 p < .001\n3 0.049999 p = .050\n4 0.500000 p = .500\n5 0.050000 p = .050\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfor p in [0.0133, 0.0004, 0.049999, 0.5, 0.05]:\n    print(f\"{p:<10} {p_apa(p)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.0133     p = .013\n0.0004     p < .001\n0.049999   p = .050\n0.5        p = .500\n0.05       p = .050\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Eingabe | Ausgabe | Regel |\n|---|---|---|\n| 0.0133 | `p = .013` | drei Stellen, ohne führende Null |\n| 0.0004 | `p < .001` | unter .001 als Schranke |\n| 0.049999 | `p = .050` | gerundet; der Wert liegt knapp unter .05, gerundet sieht er aus wie die Grenze |\n| 0.5 | `p = .500` | Nullen werden aufgefüllt |\n\n#### Interpretation\n\nDer dritte Fall zeigt, warum exakte p-Werte besser sind als „signifikant ja oder\nnein\": .050 gerundet ist praktisch dieselbe Evidenz wie .0500001. Wer an einer\nharten Grenze entscheidet, macht aus einer kontinuierlichen Grösse eine\nSchwarz-Weiss-Aussage, siehe [Hypothesentests: Grundlagen](../statistik/inferenz/hypothesentests-grundlagen.qmd).\n\n### Beispiel 2: Der Satz entsteht aus dem Code\n\n#### Frage und Datenlage\n\nDer Welch-Test aus [t-Test für zwei Stichproben](../statistik/tests/t-test-zwei-stichproben.qmd)\nsoll als vollständiger Ergebnissatz berichtet werden, und zwar so, dass sich der\nSatz bei neuen Daten von selbst anpasst.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\na <- c(11.86, 12.24, 12.02, 11.95, 12.31, 12.10, 11.78, 12.18,\n       12.05, 11.90, 12.27, 11.99, 12.14, 11.83, 12.08)\nb <- c(12.34, 11.97, 12.51, 12.20, 11.88, 12.42, 12.09, 12.67,\n       12.26, 11.94, 12.45, 12.13, 12.30, 12.01, 12.58)\n\ntest <- t.test(a, b)\nd <- (mean(a) - mean(b)) / sqrt((var(a) + var(b)) / 2)\n\nround(c(m_a = mean(a), sd_a = sd(a), m_b = mean(b), sd_b = sd(b),\n        differenz = mean(b) - mean(a)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      m_a      sd_a       m_b      sd_b differenz \n    12.05      0.16     12.25      0.25      0.20 \n```\n\n\n:::\n\n```{.r .cell-code}\nsprintf(\"t(%.2f) = %.2f, %s, d = %.2f, 95%% KI [%.2f, %.2f]\",\n        test$parameter, test$statistic, p_apa(test$p.value), d,\n        test$conf.int[1], test$conf.int[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"t(24.38) = -2.67, p = .013, d = -0.97, 95% KI [-0.36, -0.05]\"\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\na = np.array([11.86, 12.24, 12.02, 11.95, 12.31, 12.10, 11.78, 12.18,\n              12.05, 11.90, 12.27, 11.99, 12.14, 11.83, 12.08])\nb = np.array([12.34, 11.97, 12.51, 12.20, 11.88, 12.42, 12.09, 12.67,\n              12.26, 11.94, 12.45, 12.13, 12.30, 12.01, 12.58])\n\ntest = stats.ttest_ind(a, b, equal_var=False)\nd = (a.mean() - b.mean()) / np.sqrt((a.var(ddof=1) + b.var(ddof=1)) / 2)\nki = test.confidence_interval()\n\nprint(\"M_A:\", round(a.mean(), 2), \" SD_A:\", round(a.std(ddof=1), 2),\n      \" M_B:\", round(b.mean(), 2), \" SD_B:\", round(b.std(ddof=1), 2),\n      \" Differenz:\", round(b.mean() - a.mean(), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nM_A: 12.05  SD_A: 0.16  M_B: 12.25  SD_B: 0.25  Differenz: 0.2\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"t({test.df:.2f}) = {test.statistic:.2f}, {p_apa(test.pvalue)}, \"\n      f\"d = {d:.2f}, 95% KI [{ki.low:.2f}, {ki.high:.2f}]\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt(24.38) = -2.67, p = .013, d = -0.97, 95% KI [-0.36, -0.05]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Teil | Wert | Wie er entsteht |\n|---|---|---|\n| Freiheitsgrade | 24.38 | Welch, deshalb keine ganze Zahl |\n| t | -2.67 | Vorzeichen, weil A minus B gerechnet wird |\n| p | `p = .013` | über die Formatfunktion |\n| d | -0.97 | Differenz durch die gemittelte Standardabweichung |\n| Intervall | [-0.36, -0.05] | Differenz A minus B in Millimetern |\n\n#### Interpretation und Ergebnissatz\n\nIn einem Quarto-Bericht steht dieser Ausdruck nicht in einem sichtbaren Chunk,\nsondern als Inline-Code mitten im Satz. Ändern sich die Daten, ändert sich der\nSatz beim nächsten Rendern mit, siehe\n[Reproduzierbarkeit](../programmierung/reproduzierbarkeit.qmd) und\n[Berichtsvorlage](berichtsvorlage.qmd).\n\n> Maschine A fertigte im Mittel dünnere Teile als Maschine B (*M* = 12.05 mm,\n> *SD* = 0.16, gegenüber *M* = 12.25 mm, *SD* = 0.25; je *n* = 15), *t*(24.38) =\n> -2.67, *p* = .013, *d* = -0.97, 95% KI [-0.36, -0.05].\n\n::::\n\n## Was nicht in den Bericht gehört\n\n- **Nur Sternchen oder „signifikant\"** ohne Zahlen. Der Leser kann nichts prüfen.\n- **„Der Effekt war hochsignifikant\"** als Grössenaussage. Ein kleiner p-Wert\n  sagt nichts über die Grösse, siehe [Effektstärken](../statistik/inferenz/effektstaerken.qmd).\n- **„Es gibt keinen Unterschied\"** nach einem nicht signifikanten Test. Richtig\n  ist: Ein Unterschied liess sich nicht nachweisen; dazu das Intervall.\n- **Ungerundete Softwareausgabe** wie `t = -2.669121`. Mehr Stellen täuschen eine\n  Genauigkeit vor, die die Daten nicht haben.\n- **Tests, die nachträglich ausgewählt wurden**, ohne das zu sagen, siehe\n  [multiples Testen](../statistik/inferenz/multiples-testen.qmd).\n\n## Verständnisfragen\n\n::: {.quiz}\nWelche Schreibweise folgt dem APA-Stil?\n\n- [x] *r*(48) = .32, *p* = .024 ~ Richtig. Korrelation und p-Wert können nicht\n      über 1 steigen und stehen deshalb ohne führende Null, beide exakt.\n- [ ] Dieselben Werte mit führender Null bei r und nur *p* < .05 ~ Die Null\n      gehört weg, und der p-Wert ist nicht exakt angegeben.\n- [ ] *r*(48) = .32 mit Sternchen statt p-Wert ~ Sternchen ersetzen keine\n      Angabe.\n:::\n\n::: {.quiz}\nEin Test ergibt p = .38. Welcher Satz ist korrekt?\n\n- [x] Ein Unterschied liess sich nicht nachweisen, Differenz 1.2 Punkte, 95% KI\n      [-1.5, 3.9] ~ Richtig. Das Intervall zeigt, welche Unterschiede mit den\n      Daten vereinbar bleiben, auch recht grosse.\n- [ ] Die Gruppen unterscheiden sich nicht ~ Das behauptet Gleichheit, die ein\n      nicht signifikanter Test nicht belegen kann.\n- [ ] Es gab einen nicht signifikanten Trend ~ Ein Trend ist bei p = .38 keine\n      sinnvolle Beschreibung.\n:::\n\n::: {.quiz}\nWarum sollte ein Ergebnissatz in einem Bericht mit Inline-Code statt mit\nabgetippten Zahlen geschrieben werden?\n\n- [x] Bei neuen oder korrigierten Daten bleibt der Satz automatisch richtig ~\n      Richtig. Abgetippte Zahlen veralten still, sobald sich die Daten ändern.\n- [ ] Inline-Code rechnet genauer ~ Die Rechnung ist dieselbe; der Unterschied\n      ist, dass sie beim Rendern wiederholt wird.\n- [ ] APA verlangt Inline-Code ~ Der Stil regelt die Darstellung, nicht das\n      Werkzeug.\n:::\n\n## Verlinkte Ressourcen\n\n- [APA Style: Numbers and Statistics](https://apastyle.apa.org/instructional-aids/numbers-statistics-guide.pdf)\n- [APA Style: Statistical Reporting](https://apastyle.apa.org/style-grammar-guidelines/tables-figures/sample-tables)\n- [report: automatische Ergebnissätze in R](https://easystats.github.io/report/)\n",
    "supporting": [
      "ergebnisse-berichten_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}