{
  "hash": "149b0b9ff82d50126c4fadbb55e51025",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Objektorientierung in Python\"\ndescription: \"Klassen, Instanzen, Vererbung und wann sich der Aufwand lohnt.\"\ncategories: [\"Programmiergrundlagen\", \"Python\", \"R\"]\nquelle: [\"PYFR\"]\nseitentyp: werkzeug\nstand: entwurf\norder: 30\n---\n\n\n\n## Kernideen\n\n- Eine **Klasse** ist der Bauplan, eine **Instanz** ein Exemplar davon. Sie\n  bündelt Daten und die Operationen darauf.\n- `__init__` legt beim Erzeugen fest, was vorhanden sein muss. `self` ist das\n  Exemplar, auf dem eine Methode gerade arbeitet.\n- **Klassenattribute** gelten für alle Exemplare, **Instanzattribute** je\n  Exemplar. Ein veränderliches Klassenattribut wird geteilt.\n- **Dunder-Methoden** wie `__str__`, `__len__` und `__lt__` fügen eigene\n  Klassen in die Sprache ein: `print`, `len` und `sorted` funktionieren dann.\n- **Vererbung** formuliert nur den Unterschied. Eine geerbte Methode ruft die\n  überschriebene Version auf, wenn sie `self.methode()` benutzt.\n- In der Datenarbeit lohnt eine Klasse erst, wenn **mehrere Methoden einen\n  Zustand teilen**. Sonst ist eine Funktion klarer.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Python-Grundlagen](python-grundlagen.qmd) für Dictionaries und\ndie Verweissemantik, [Funktionen und Module in Python](python-funktionen-module.qmd)\nfür Funktionen, Closures und den veränderlichen Defaultwert. Eine Methode ist\nnichts anderes als eine Funktion, die zu einem Objekt gehört.\n:::\n\n### Das Problem, bevor die Lösung kommt\n\nMehrere Messreihen sollen verwaltet werden. Mit den bisherigen Mitteln entsteht\nein Dictionary je Reihe und ein Satz Funktionen daneben. Das funktioniert und\nhat drei Schwächen: Nichts hindert daran, ein Dictionary ohne den Schlüssel\n`werte` zu übergeben, der Fehler fällt erst beim Aufruf auf. Die Funktionen\nliegen irgendwo im Modul und sind nicht als zusammengehörig erkennbar. Und wer\neine Reihe von Hand baut, kann Schlüssel vergessen oder vertippen. Eine Klasse\nbündelt Daten und Operationen und prüft beim Erzeugen, ob alles da ist.\n\n### Aufbau einer Klasse\n\n```python\nclass Messreihe:\n    einheit = \"mm\"                  # Klassenattribut\n\n    def __init__(self, name, werte):\n        self.name = name            # Instanzattribute\n        self.werte = list(werte)\n\n    def mittel(self):               # Methode\n        return sum(self.werte) / len(self.werte)\n```\n\n| Teil | Bedeutung |\n|---|---|\n| `class Messreihe:` | definiert den Bauplan; Klassennamen schreibt man in CamelCase |\n| `einheit = \"mm\"` | Klassenattribut, einmal für alle Exemplare |\n| `__init__` | läuft beim Erzeugen mit `Messreihe(...)` und legt die Instanzattribute an |\n| `self` | das Exemplar selbst; steht als erster Parameter jeder Methode |\n| `self.werte = list(werte)` | eine eigene Kopie, damit eine übergebene Liste nicht von aussen verändert wird |\n| `m.mittel()` | wird intern zu `Messreihe.mittel(m)`; deshalb fehlt `self` im Aufruf |\n\n### Die wichtigsten Dunder-Methoden\n\nDunder steht für \"double underscore\". Diese Methoden ruft man nicht selbst\nauf; Python ruft sie, wenn eine eingebaute Funktion oder ein Operator auf das\nObjekt trifft.\n\n| Methode | ausgelöst durch | Zweck |\n|---|---|---|\n| `__init__` | `Klasse(...)` | Exemplar einrichten |\n| `__str__` | `print(x)`, `str(x)` | lesbare Darstellung für Menschen |\n| `__repr__` | Anzeige in Listen, Konsole | eindeutige Darstellung für Entwickler, idealerweise gültiger Code |\n| `__len__` | `len(x)` | Anzahl |\n| `__eq__`, `__lt__` | `==`, `<`, damit auch `sorted`, `max` | Vergleich |\n| `__getitem__` | `x[i]` | Indexzugriff |\n\nFür reine Datenbehälter erzeugt der Dekorator `@dataclass` `__init__`,\n`__repr__` und `__eq__` automatisch, mit `order=True` auch die Vergleiche.\n\n### Vererbung, sparsam eingesetzt\n\nEine abgeleitete Klasse `class B(A):` übernimmt alles aus `A` und formuliert\nnur den Unterschied. `super().__init__(...)` ruft die Einrichtung der\nBasisklasse auf; ohne diesen Aufruf fehlen deren Attribute. Die Reihenfolge,\nin der Python eine Methode sucht, heisst **MRO** (method resolution order) und\nsteht in `Klasse.__mro__`.\n\nSo elegant das ist, so schnell wird es überstrapaziert. Eine tiefe Hierarchie\nist meist schwerer zu verstehen als eine flache Struktur, in der Objekte\neinander **enthalten** statt beerben (Komposition). Die Prüffrage lautet, ob\nwirklich eine ist-ein-Beziehung vorliegt.\n\n### Der Vergleich zu R\n\nR kennt mehrere Objektsysteme, und keines gleicht dem von Python ganz.\n\n| System | Idee | Methode gehört zu | Semantik |\n|---|---|---|---|\n| S3 | Liste mit Klassenattribut, `UseMethod` | der generischen Funktion: `mittel(x)` | Kopie beim Ändern |\n| S4 | formale Klassen mit `setClass`, `setMethod` | der generischen Funktion | Kopie beim Ändern |\n| Reference Classes | `setRefClass`, Felder und Methoden | dem Objekt: `x$methode()` | **Verweis**, wie Python |\n| Python | `class` | dem Objekt: `x.methode()` | Verweis |\n\nDer Unterschied ist mehr als Syntax. In Python gehört die Methode zum Objekt.\nIn S3 und S4 gehört sie zur generischen Funktion, die anhand der Klasse ihres\nArguments entscheidet, welche Umsetzung greift. Deshalb heisst es dort\n`mittel(m)` und nicht `m.mittel()`, und deshalb kann man in R einer\nbestehenden Klasse eine neue Methode geben, ohne sie anzufassen, etwa\n`print.messreihe`.\n\n### Kurz nachgeschlagen\n\n| Aufgabe | R (S3) | Python |\n|---|---|---|\n| Klasse anlegen | `structure(list(...), class = \"k\")` | `class K:` mit `__init__` |\n| Methode definieren | `mittel.k <- function(x, ...)` plus `UseMethod` | `def mittel(self):` in der Klasse |\n| Druckausgabe | `print.k <- function(x, ...)` | `def __str__(self):` |\n| erben | `class(obj) <- c(\"kind\", \"k\")` | `class Kind(K):` |\n| Basisversion aufrufen | `NextMethod()` | `super().methode()` |\n| Typ prüfen | `inherits(x, \"k\")` | `isinstance(x, K)` |\n| Attribute ansehen | `unclass(x)`, `str(x)` | `vars(x)` |\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Vom Dictionary zur Klasse\n\n#### Frage und Datenlage\n\nZwei Messreihen, Drossel `2, 4, 6` und Ventil `1.5, 1.7, 9`. Was passiert, wenn\neine Reihe als Dictionary einen falsch geschriebenen Schlüssel hat, und was,\nwenn eine Klasse ein Pflichtattribut nicht bekommt?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmessreihe <- function(name, werte) {\n  structure(list(name = name, werte = werte), class = \"messreihe\")\n}\nmittel <- function(x, ...) UseMethod(\"mittel\")\nmittel.messreihe <- function(x, ...) mean(x$werte)\n\ndrossel <- messreihe(\"Drossel\", c(2, 4, 6))\nventil  <- messreihe(\"Ventil\",  c(1.5, 1.7, 9))\n\nc(mittel(drossel), diff(range(ventil$werte)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.0 7.5\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(drossel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"messreihe\"\n```\n\n\n:::\n\n```{.r .cell-code}\nunclass(drossel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$name\n[1] \"Drossel\"\n\n$werte\n[1] 2 4 6\n```\n\n\n:::\n\n```{.r .cell-code}\ninherits(tryCatch(messreihe(\"Pumpe\"), error = function(e) e), \"error\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# Ohne Klasse: Dictionary und lose Funktion\nreihe = {\"name\": \"Drossel\", \"werte\": [2.0, 4.0, 6.0]}\n\ndef mittel(r):\n    return sum(r[\"werte\"]) / len(r[\"werte\"])\n\nprint(mittel(reihe))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n4.0\n```\n\n\n:::\n\n```{.python .cell-code}\nkaputt = {\"name\": \"Ventil\", \"wert\": [1.5, 1.7, 9.0]}     # Tippfehler\ntry:\n    mittel(kaputt)\nexcept KeyError as fehler:\n    print(type(fehler).__name__, fehler)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKeyError 'werte'\n```\n\n\n:::\n\n```{.python .cell-code}\n# Mit Klasse\nclass Messreihe:\n    einheit = \"mm\"\n\n    def __init__(self, name, werte):\n        self.name = name\n        self.werte = list(werte)\n\n    def mittel(self):\n        return sum(self.werte) / len(self.werte)\n\n    def spannweite(self):\n        return max(self.werte) - min(self.werte)\n\ndrossel = Messreihe(\"Drossel\", [2.0, 4.0, 6.0])\nventil = Messreihe(\"Ventil\", [1.5, 1.7, 9.0])\nprint(drossel.mittel(), ventil.spannweite())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n4.0 7.5\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(Messreihe.mittel(drossel))          # dasselbe, self ausdruecklich\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n4.0\n```\n\n\n:::\n\n```{.python .cell-code}\ntry:\n    Messreihe(\"Pumpe\")\nexcept TypeError as fehler:\n    print(type(fehler).__name__)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTypeError\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(vars(drossel))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'name': 'Drossel', 'werte': [2.0, 4.0, 6.0]}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(type(drossel).__name__, isinstance(drossel, Messreihe))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMessreihe True\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Zeile | Python | R | Erklärung |\n|---|---|---|---|\n| Mittel der Drossel | 4.0 | 4 | Beide Wege rechnen richtig, solange die Daten stimmen. |\n| Dictionary mit Tippfehler | **`KeyError 'werte'`** | | Der Fehler zeigt sich erst **beim Rechnen**, nicht beim Anlegen der Reihe, und nennt den fehlenden Schlüssel, nicht den falschen. |\n| Spannweite des Ventils | 7.5 | 7.5 | 9.0 minus 1.5. |\n| `Messreihe.mittel(drossel)` | 4.0 | | Der Aufruf über die Klasse zeigt, was `drossel.mittel()` intern tut: `self` ist `drossel`. |\n| Reihe ohne Werte | **`TypeError`** | `TRUE` (Fehler) | `__init__` verlangt `werte`, das Anlegen scheitert **sofort**. In R erzwingt die Konstruktorfunktion dasselbe. |\n| `vars(drossel)` | `{'name': 'Drossel', 'werte': [2.0, 4.0, 6.0]}` | `unclass()` zeigt `$name` und `$werte` | Die Instanzattribute. `einheit` fehlt, denn es gehört der Klasse. |\n| Typ | `Messreihe True` | `\"messreihe\"` | In R ist die Klasse nur ein Attribut der Liste; `unclass` entfernt es. |\n\n#### Interpretation und Ergebnissatz\n\nDie Klasse verschiebt den Fehler nach vorn: vom Rechnen zum Anlegen. Das ist\nihr eigentlicher Nutzen in der Datenarbeit. Ein Dictionary mit Tippfehler kann\nlange durch ein Programm wandern, bevor es auffällt; ein Objekt ohne\nPflichtattribut entsteht gar nicht erst.\n\n> Der Mittelwert der Drossel beträgt 4.0, die Spannweite des Ventils 7.5. Ein\n> Dictionary mit falsch geschriebenem Schlüssel scheitert erst beim Rechnen\n> mit `KeyError 'werte'`, eine Klasse ohne Pflichtattribut bereits beim\n> Anlegen mit einem `TypeError`.\n\n### Beispiel 2: Klassenattribut, Instanzattribut und geteilter Zustand\n\n#### Frage und Datenlage\n\nDie Einheit ist als Klassenattribut hinterlegt. Was passiert, wenn man sie an\nder Klasse und dann an einem einzelnen Exemplar ändert? Und was, wenn ein\nKlassenattribut eine Liste ist?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Reference Class: Verweissemantik wie in Python\nProtokoll <- setRefClass(\"Protokoll\",\n  fields = list(eintraege = \"character\"),\n  methods = list(notiere = function(text) {\n    eintraege <<- c(eintraege, text)\n    invisible(.self)\n  }))\n\nq1 <- Protokoll$new()\nq2 <- Protokoll$new()\nq1$notiere(\"Start\")\nlist(q1 = q1$eintraege, q2 = q2$eintraege)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$q1\n[1] \"Start\"\n\n$q2\ncharacter(0)\n```\n\n\n:::\n\n```{.r .cell-code}\na <- q1                      # kein neues Objekt\na$notiere(\"Stopp\")\nq1$eintraege\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Start\" \"Stopp\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# S3-Liste zum Vergleich: Kopie beim Aendern\ns3 <- list(eintraege = \"Start\")\ns3b <- s3\ns3b$eintraege <- c(s3b$eintraege, \"Stopp\")\ns3$eintraege\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Start\"\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(drossel.einheit, ventil.einheit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmm mm\n```\n\n\n:::\n\n```{.python .cell-code}\nMessreihe.einheit = \"cm\"                  # an der Klasse\nprint(drossel.einheit, ventil.einheit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncm cm\n```\n\n\n:::\n\n```{.python .cell-code}\ndrossel.einheit = \"µm\"                    # nur an diesem Exemplar\nprint(drossel.einheit, ventil.einheit, Messreihe.einheit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nµm cm cm\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"einheit\" in vars(drossel), \"einheit\" in vars(ventil))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue False\n```\n\n\n:::\n\n```{.python .cell-code}\n# Veraenderliches Klassenattribut: dieselbe Falle wie der Default []\nclass Protokoll:\n    eintraege = []\n\n    def notiere(self, text):\n        self.eintraege.append(text)\n\np1, p2 = Protokoll(), Protokoll()\np1.notiere(\"Start\")\nprint(p2.eintraege, p1.eintraege is p2.eintraege)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['Start'] True\n```\n\n\n:::\n\n```{.python .cell-code}\nclass ProtokollRichtig:\n    def __init__(self):\n        self.eintraege = []\n\n    def notiere(self, text):\n        self.eintraege.append(text)\n\nq1, q2 = ProtokollRichtig(), ProtokollRichtig()\nq1.notiere(\"Start\")\nprint(q1.eintraege, q2.eintraege)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['Start'] []\n```\n\n\n:::\n\n```{.python .cell-code}\na = q1                                    # kein neues Objekt\na.notiere(\"Stopp\")\nprint(q1.eintraege)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['Start', 'Stopp']\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Schritt | Python | Erklärung |\n|---|---|---|\n| Ausgangslage | `mm mm` | Beide Exemplare haben kein eigenes `einheit` und lesen das der Klasse. |\n| Klasse auf cm | `cm cm` | Die Änderung an der Klasse wirkt auf **alle** Exemplare, die kein eigenes Attribut haben. |\n| `drossel.einheit = \"µm\"` | `µm cm cm` | Die Zuweisung an ein Exemplar legt ein **neues Instanzattribut** an, das das Klassenattribut verdeckt. Klasse und Ventil bleiben bei cm. |\n| wer hat ein eigenes | `True False` | Nur `drossel` hat `einheit` jetzt in `vars()`. |\n| Liste als Klassenattribut | `['Start'] True` | `p2` hat nichts notiert und sieht trotzdem `Start`: Beide Exemplare teilen **eine** Liste. |\n| Liste in `__init__` | `['Start'] []` | Jedes Exemplar hat seine eigene Liste. |\n| `a = q1`, dann über `a` notiert | `['Start', 'Stopp']` | Eine Zuweisung kopiert kein Objekt, auch keines aus einer eigenen Klasse. |\n\n| Schritt | R | Erklärung |\n|---|---|---|\n| zwei Reference-Class-Objekte | `q1` hat `\"Start\"`, `q2` ist `character(0)` | Felder sind je Exemplar getrennt. |\n| über `a <- q1` notiert | `\"Start\" \"Stopp\"` | Reference Classes haben Verweissemantik: `a` und `q1` sind dasselbe Objekt, wie in Python. |\n| S3-Liste kopiert und geändert | `\"Start\"` | Eine gewöhnliche Liste wird beim Ändern kopiert; das Original bleibt. |\n\n#### Interpretation und Ergebnissatz\n\nDie Regel ist dieselbe wie beim veränderlichen Defaultwert: Was einmal für\nalle entsteht, wird von allen geteilt. Für Konstanten wie eine Einheit oder\neinen Grenzwert ist das Klassenattribut richtig, für alles, was sich im Lauf\nändert, das Instanzattribut in `__init__`. R verhält sich bei S3 und S4 wie\nbei Vektoren und kopiert; nur Reference Classes (und das Paket R6) folgen der\nPython-Logik.\n\n> Die Zuweisung `drossel.einheit = \"µm\"` legt ein Instanzattribut an und lässt\n> Klasse und Ventil bei cm. Eine Liste als Klassenattribut wird dagegen von\n> allen Exemplaren geteilt: `p2` zeigt `['Start']`, obwohl nur `p1` notiert hat.\n\n### Beispiel 3: Dunder-Methoden und Dataclasses\n\n#### Frage und Datenlage\n\nVier Reihen (Drossel, Ventil, Pumpe `5`, Filter `3, 3.4`) sollen lesbar\ngedruckt, gezählt und nach Mittelwert sortiert werden. Danach dasselbe mit\neiner Dataclass für Einzelmessungen mit Einheit.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint.messreihe <- function(x, ...) {\n  cat(x$name, \": \", format(round(mittel(x), 2), nsmall = 2),\n      \" (n=\", length(x$werte), \")\\n\", sep = \"\")\n  invisible(x)\n}\n\ndrossel\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDrossel: 4.00 (n=3)\n```\n\n\n:::\n\n```{.r .cell-code}\nventil\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVentil: 4.07 (n=3)\n```\n\n\n:::\n\n```{.r .cell-code}\nreihen <- list(drossel, ventil, messreihe(\"Pumpe\", 5),\n               messreihe(\"Filter\", c(3, 3.4)))\nsapply(reihen[order(sapply(reihen, mittel))], function(r) r$name)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Filter\"  \"Drossel\" \"Ventil\"  \"Pumpe\"  \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nclass Reihe:\n    def __init__(self, name, werte):\n        self.name = name\n        self.werte = list(werte)\n\n    def mittel(self):\n        return sum(self.werte) / len(self.werte)\n\n    def __len__(self):\n        return len(self.werte)\n\n    def __str__(self):\n        return f\"{self.name}: {self.mittel():.2f} (n={len(self)})\"\n\n    def __repr__(self):\n        return f\"Reihe({self.name!r}, {self.werte!r})\"\n\n    def __lt__(self, andere):\n        return self.mittel() < andere.mittel()\n\nprint(\"object at\" in str(Messreihe(\"Drossel\", [2.0])))   # ohne __str__\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue\n```\n\n\n:::\n\n```{.python .cell-code}\nreihen = [Reihe(\"Drossel\", [2.0, 4.0, 6.0]), Reihe(\"Ventil\", [1.5, 1.7, 9.0]),\n          Reihe(\"Pumpe\", [5.0]), Reihe(\"Filter\", [3.0, 3.4])]\nprint(reihen[0])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDrossel: 4.00 (n=3)\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(len(reihen[1]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n3\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(reihen[2:])                          # Listen zeigen __repr__\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[Reihe('Pumpe', [5.0]), Reihe('Filter', [3.0, 3.4])]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint([r.name for r in sorted(reihen)])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['Filter', 'Drossel', 'Ventil', 'Pumpe']\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(max(reihen))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPumpe: 5.00 (n=1)\n```\n\n\n:::\n\n```{.python .cell-code}\n@dataclass(order=True)\nclass Messung:\n    wert: float\n    einheit: str = field(default=\"mm\", compare=False)\n\nmessungen = [Messung(4.2), Messung(1.5, \"cm\"), Messung(3.0)]\nprint(sorted(messungen))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[Messung(wert=1.5, einheit='cm'), Messung(wert=3.0, einheit='mm'), Messung(wert=4.2, einheit='mm')]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(Messung(2.0) == Messung(2.0, \"cm\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Aufruf | Ausgabe | ausgelöst | Erklärung |\n|---|---|---|---|\n| `str()` ohne `__str__` | `True` für \"object at\" | | Ohne eigene Methode zeigt Python nur Klasse und Speicheradresse. |\n| `print(reihen[0])` | `Drossel: 4.00 (n=3)` | `__str__` | lesbare Darstellung |\n| `len(reihen[1])` | 3 | `__len__` | |\n| `print(reihen[2:])` | `[Reihe('Pumpe', [5.0]), Reihe('Filter', [3.0, 3.4])]` | `__repr__` | Eine Liste zeigt ihre Elemente immer mit `__repr__`, nie mit `__str__`. Die Ausgabe ist gültiger Python-Code. |\n| `sorted(reihen)` | Filter, Drossel, Ventil, Pumpe | `__lt__` | Mittelwerte 3.2, 4.0, 4.07, 5.0. `sorted` braucht nur den Kleiner-Vergleich. |\n| `max(reihen)` | `Pumpe: 5.00 (n=1)` | `__lt__`, dann `__str__` | |\n| R: `drossel`, `ventil` | `Drossel: 4.00 (n=3)`, `Ventil: 4.07 (n=3)` | `print.messreihe` | Die automatische Anzeige ruft die Druckmethode der Klasse auf. |\n| R: sortiert | Filter, Drossel, Ventil, Pumpe | `order()` | R sortiert über die berechneten Mittelwerte, nicht über die Objekte. |\n| Dataclass sortiert | `[Messung(wert=1.5, einheit='cm'), Messung(wert=3.0, einheit='mm'), Messung(wert=4.2, einheit='mm')]` | erzeugtes `__lt__` | **Falsch sortiert**: 1.5 cm sind 15 mm und gehören ans Ende. |\n| `Messung(2.0) == Messung(2.0, \"cm\")` | **`True`** | erzeugtes `__eq__` | 2 mm gelten als gleich 2 cm, weil `einheit` mit `compare=False` vom Vergleich ausgenommen ist. |\n\n#### Interpretation und Ergebnissatz\n\nMit vier kurzen Methoden verhält sich die eigene Klasse wie ein eingebauter\nTyp: `print`, `len`, `sorted` und `max` funktionieren ohne Sonderbehandlung.\nDie Dataclass spart diesen Code, vergleicht aber stur Feld für Feld. Sobald\nein Feld eine Einheit oder einen Massstab trägt, ist das automatische `__lt__`\n**fachlich falsch**, obwohl es fehlerfrei läuft. Dann gehört entweder eine\nUmrechnung in eine gemeinsame Einheit in `__post_init__` oder ein eigenes\n`__lt__`.\n\n> Nach Mittelwert sortiert stehen die Reihen in der Folge Filter (3.2),\n> Drossel (4.0), Ventil (4.07) und Pumpe (5.0). Die Dataclass sortiert 1.5 cm\n> vor 3.0 mm und hält 2 mm für gleich 2 cm, weil die Einheit vom Vergleich\n> ausgenommen ist.\n\n### Beispiel 4: Vererbung und super()\n\n#### Frage und Datenlage\n\nEine gewichtete Messreihe soll alles von der gewöhnlichen übernehmen und nur\nden Mittelwert anders berechnen. Drossel `2, 4, 6` mit Gewichten `1, 1, 3`.\nWas druckt `print`, obwohl `__str__` nur in der Basisklasse steht? Und was\npassiert ohne `super().__init__`?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngewichtet <- function(name, werte, gewichte) {\n  obj <- messreihe(name, werte)\n  obj$gewichte <- gewichte\n  class(obj) <- c(\"gewichtet\", class(obj))\n  obj\n}\nmittel.gewichtet <- function(x, ...) weighted.mean(x$werte, x$gewichte)\n\ng <- gewichtet(\"Drossel\", c(2, 4, 6), c(1, 1, 3))\ng                                   # print.messreihe, aber mittel.gewichtet\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDrossel: 4.80 (n=3)\n```\n\n\n:::\n\n```{.r .cell-code}\nc(mittel(g), mittel.messreihe(g))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.8 4.0\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(g)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"gewichtet\" \"messreihe\"\n```\n\n\n:::\n\n```{.r .cell-code}\ninherits(g, \"messreihe\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nclass GewichteteReihe(Reihe):\n    def __init__(self, name, werte, gewichte):\n        super().__init__(name, werte)       # den Teil, den die Basis erledigt\n        self.gewichte = list(gewichte)\n\n    def mittel(self):                        # ueberschreibt die Basisversion\n        return (sum(w * g for w, g in zip(self.werte, self.gewichte))\n                / sum(self.gewichte))\n\ng = GewichteteReihe(\"Drossel\", [2.0, 4.0, 6.0], [1, 1, 3])\nprint(g)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDrossel: 4.80 (n=3)\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(g.mittel(), Reihe.mittel(g))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n4.8 4.0\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(isinstance(g, Reihe), isinstance(reihen[0], GewichteteReihe))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrue False\n```\n\n\n:::\n\n```{.python .cell-code}\nprint([k.__name__ for k in GewichteteReihe.__mro__])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['GewichteteReihe', 'Reihe', 'object']\n```\n\n\n:::\n\n```{.python .cell-code}\nclass OhneSuper(Reihe):\n    def __init__(self, name, werte, gewichte):\n        self.gewichte = list(gewichte)       # super() vergessen\n\ntry:\n    print(OhneSuper(\"X\", [1.0], [1]))\nexcept AttributeError as fehler:\n    print(type(fehler).__name__)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAttributeError\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Zeile | Python | R | Erklärung |\n|---|---|---|---|\n| `print(g)` | `Drossel: 4.80 (n=3)` | `Drossel: 4.80 (n=3)` | Die Druckmethode stammt aus der Basisklasse, ruft aber `self.mittel()` beziehungsweise `mittel(x)` auf, und das findet die **überschriebene** Version. |\n| gewichtetes Mittel | 4.8 | 4.8 | (1·2 + 1·4 + 3·6) / 5 = 24 / 5. |\n| Basisversion ausdrücklich | 4.0 | 4.0 | `Reihe.mittel(g)` beziehungsweise `mittel.messreihe(g)` umgeht die Überschreibung. |\n| `isinstance` | `True False` | `inherits` → `TRUE` | Eine gewichtete Reihe **ist eine** Reihe, umgekehrt nicht. |\n| MRO / `class(g)` | `['GewichteteReihe', 'Reihe', 'object']` | `\"gewichtet\" \"messreihe\"` | Die Suchreihenfolge für Methoden. In R ist sie schlicht der Klassenvektor. |\n| ohne `super().__init__` | **`AttributeError`** | | `__str__` ruft `mittel()` auf, das `self.werte` braucht, und das wurde nie angelegt. |\n\n#### Interpretation und Ergebnissatz\n\nDass eine geerbte Methode die überschriebene Version aufruft, heisst\n**dynamische Bindung** und ist der eigentliche Nutzen der Vererbung: Die\nBasisklasse legt den Ablauf fest, die abgeleitete tauscht einen Baustein aus.\nS3 in R erreicht dasselbe über die Klassenreihenfolge im Vektor. Der\nvergessene `super()`-Aufruf ist der häufigste Fehler dabei, und er zeigt sich\nnicht beim Anlegen, sondern erst beim ersten Zugriff auf ein fehlendes\nAttribut.\n\n> Die gewichtete Reihe liefert einen Mittelwert von 4.8 statt 4.0, und auch\n> das geerbte `print` zeigt 4.80, weil es `self.mittel()` aufruft. Ohne\n> `super().__init__` fehlt das Attribut `werte`, und der erste Zugriff endet\n> mit einem `AttributeError`.\n\n### Beispiel 5: Wann sich eine Klasse lohnt\n\n#### Frage und Datenlage\n\nMesswerte `2, 4, 6, 1.5, 1.7, 9` treffen einzeln ein, und nach jedem Wert soll\nder laufende Mittelwert bereitstehen, ohne alle bisherigen Werte zu speichern.\nHier gibt es einen **Zustand**, der zwischen den Aufrufen erhalten bleiben\nmuss. Zum Vergleich steht die Lösung als Closure.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlaufmittel <- function() {\n  n <- 0\n  m <- 0\n  function(wert) {\n    n <<- n + 1\n    m <<- m + (wert - m) / n\n    m\n  }\n}\nneu <- laufmittel()\nround(sapply(c(2, 4, 6, 1.5, 1.7, 9), neu), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.000 3.000 4.000 3.375 3.040 4.033\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nclass Laufmittel:\n    def __init__(self):\n        self.n = 0\n        self.mittel = 0.0\n\n    def neu(self, wert):\n        self.n += 1\n        self.mittel += (wert - self.mittel) / self.n\n        return self.mittel\n\nwerte = [2.0, 4.0, 6.0, 1.5, 1.7, 9.0]\nlm = Laufmittel()\nprint([round(lm.neu(w), 3) for w in werte])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[2.0, 3.0, 4.0, 3.375, 3.04, 4.033]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(lm.n, round(lm.mittel, 4), round(sum(werte) / len(werte), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n6 4.0333 4.0333\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| nach Wert | laufender Mittelwert |\n|---|---|\n| 2 | 2.000 |\n| 4 | 3.000 |\n| 6 | 4.000 |\n| 1.5 | 3.375 |\n| 1.7 | 3.040 |\n| 9 | 4.033 |\n\n| Grösse | Wert | Erklärung |\n|---|---|---|\n| `lm.n` | 6 | Anzahl verarbeiteter Werte, im Objekt gespeichert |\n| `lm.mittel` | 4.0333 | laufender Mittelwert nach dem letzten Wert |\n| direkt gerechnet | 4.0333 | Kontrolle: Die Aktualisierung `m + (x − m) / n` liefert exakt den gewöhnlichen Mittelwert, ohne die Werte aufzubewahren. |\n\nR löst dieselbe Aufgabe mit einer Closure, wie auf der Seite\n[Funktionen und Module](python-funktionen-module.qmd) der Zähler: `n` und `m`\nleben in der Umgebung der inneren Funktion weiter.\n\n#### Interpretation und Ergebnissatz\n\nClosure und Klasse leisten hier dasselbe. Die Klasse gewinnt, sobald\n**mehrere Operationen denselben Zustand teilen**: zurücksetzen, die Anzahl\nabfragen, eine Varianz mitführen, den Stand speichern. Mit einer Closure wird\ndas schnell unübersichtlich, mit einer Klasse ist es eine weitere Methode.\nUmgekehrt gilt: Wer eine Klasse schreibt, deren Objekt nur einmal erzeugt und\nderen Methoden nacheinander je einmal aufgerufen werden, hat eine Funktion\numständlich verpackt. Für die eigentliche Analyse bleibt ein DataFrame plus\nFunktionen meist die klarere Wahl, siehe [pandas](pandas.qmd).\n\n> Nach sechs Werten steht der laufende Mittelwert bei 4.0333 und stimmt mit\n> dem direkt berechneten Mittelwert überein, ohne dass die Werte gespeichert\n> werden. Eine Klasse lohnt sich hier, weil ein Zustand über viele Aufrufe\n> erhalten bleiben muss; in R leistet eine Closure dasselbe.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nWarum steht `self` in der Definition einer Methode, aber nicht im Aufruf\n`m.mittel()`?\n\n- [x] Python setzt beim Aufruf das Objekt automatisch als erstes Argument ein ~\n      Richtig. `m.mittel()` wird intern zu `Messreihe.mittel(m)`, wie\n      Beispiel 1 mit derselben Ausgabe 4.0 zeigt.\n- [ ] `self` ist ein Schlüsselwort und wird ignoriert ~ Es ist ein\n      gewöhnlicher Parametername; die Bezeichnung ist nur Konvention.\n- [ ] Der Aufruf ist unvollständig und funktioniert nur zufällig ~ Er ist die\n      übliche und vorgesehene Schreibweise.\n:::\n\n::: {.quiz}\nWas wäre die Folge, wenn `eintraege = []` als Klassenattribut statt in\n`__init__` stünde?\n\n- [ ] Nichts, es ist dieselbe Zuweisung an anderer Stelle ~ Der Ort\n      entscheidet, ob das Objekt einmal für alle oder je Exemplar entsteht.\n- [x] Alle Instanzen teilten sich dieselbe Liste ~ Richtig. Ein `append` in\n      einem Objekt wäre in allen anderen sichtbar, wie `p2` in Beispiel 2\n      zeigt. Es ist derselbe Fehler wie der veränderliche Defaultwert bei\n      Funktionen.\n- [ ] Die Klasse liesse sich nicht mehr instanziieren ~ Sie liesse sich\n      problemlos instanziieren, und genau das macht den Fehler unauffällig.\n:::\n\n::: {.quiz}\n`print(liste_von_reihen)` zeigt `[Reihe('Pumpe', [5.0]), ...]` statt der\nschönen Ausgabe aus `__str__`. Warum?\n\n- [x] Container zeigen ihre Elemente mit `__repr__`, nicht mit `__str__` ~\n      Richtig. `__str__` greift nur, wenn das Objekt selbst gedruckt wird.\n      Deshalb lohnt es sich, beide zu definieren.\n- [ ] `__str__` ist fehlerhaft definiert ~ Beim Drucken eines einzelnen\n      Objekts funktioniert es ja.\n- [ ] Listen können keine eigenen Objekte enthalten ~ Sie enthalten sie, sie\n      zeigen sie nur anders an.\n:::\n\n::: {.quiz}\nEine Dataclass mit `order=True` hat die Felder `wert` und `einheit` (mit\n`compare=False`). Sie sortiert `Messung(1.5, \"cm\")` vor `Messung(3.0, \"mm\")`.\nWas ist das Problem?\n\n- [ ] Die Dataclass hat einen Fehler ~ Sie tut genau, was angegeben ist:\n      nach `wert` vergleichen.\n- [x] Der erzeugte Vergleich kennt die Bedeutung der Einheit nicht ~ Richtig.\n      1.5 cm sind 15 mm. Abhilfe: in `__post_init__` in eine gemeinsame\n      Einheit umrechnen oder `__lt__` selbst schreiben.\n- [ ] `compare=False` sollte `True` sein ~ Dann würde zusätzlich die Einheit\n      als Text verglichen, was ebenso wenig fachlich richtig ist.\n:::\n\n::: {.quiz}\n`__str__` steht nur in der Basisklasse, gibt bei einem abgeleiteten Objekt\naber den gewichteten Mittelwert aus. Wie kommt das?\n\n- [x] `__str__` ruft `self.mittel()` auf, und `self` ist das abgeleitete\n      Objekt ~ Richtig. Python sucht die Methode entlang der MRO und findet\n      zuerst die überschriebene Version. Dieses Verhalten heisst dynamische\n      Bindung.\n- [ ] Die abgeleitete Klasse hat `__str__` stillschweigend überschrieben ~ Sie\n      definiert es gar nicht, sondern erbt es unverändert.\n- [ ] Es ist ein Zufall der Reihenfolge ~ Das Verhalten ist festgelegt und\n      verlässlich.\n:::\n\n::: {.quiz}\nEine Klasse `Auswertung` hat `__init__(self, df)` und eine einzige Methode\n`rechne()`, die einmal aufgerufen wird. Was ist davon zu halten?\n\n- [ ] Gut, Klassen sind immer strukturierter als Funktionen ~ Struktur ohne\n      Zustand ist nur Verpackung.\n- [x] Eine Funktion `rechne(df)` wäre klarer ~ Richtig. Eine Klasse lohnt\n      sich, wenn mehrere Methoden einen Zustand teilen, wie beim laufenden\n      Mittelwert in Beispiel 5, nicht für einen einzelnen Rechenschritt.\n- [ ] Die Klasse ist falsch, weil `df` nicht in `__init__` gehört ~ Technisch\n      ist das zulässig.\n:::\n\n## Verlinkte Ressourcen\n\n- [Klassen im Python-Tutorial](https://docs.python.org/3/tutorial/classes.html)\n- [Übersicht der Dunder-Methoden](https://docs.python.org/3/reference/datamodel.html)\n- [Dataclasses](https://docs.python.org/3/library/dataclasses.html)\n- [Objektsysteme in R, Advanced R](https://adv-r.hadley.nz/oo.html)\n",
    "supporting": [
      "python-objektorientierung_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}