{
  "hash": "9d83349ff653e0703b126457f220a90a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Gepaarter t-Test\"\ndescription: \"Verbundene Messungen über die Differenzen prüfen.\"\ncategories: [\"Hypothesentests\", \"Effektstärke\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"ESDS\"]\nseitentyp: methode\nstand: entwurf\norder: 30\n---\n\n\n\n\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Hat sich eine Messgrösse an denselben Objekten zwischen zwei Zeitpunkten oder Bedingungen verändert? |\n| Zielvariable | metrisch, zweimal am selben Objekt gemessen |\n| Gruppen | zwei verbundene Messungen, gleiche Anzahl, feste Zuordnung |\n| Was die Methode liefert | mittlere Differenz mit Konfidenzintervall, t-Statistik, Freiheitsgrade, p-Wert, Effektstärke |\n| R-Funktion | `t.test(nachher, vorher, paired = TRUE)` |\n| Python-Funktion | `pg.ttest(nachher, vorher, paired=True)` |\n| Verwandte Methoden | [t-Test für zwei Stichproben](t-test-zwei-stichproben.qmd), [Wilcoxon-Test](nichtparametrische-tests.qmd), [Varianzanalyse](anova.qmd) |\n\n## Wann diese Methode, wann nicht\n\nTypische Fragestellungen: Verbrauch vor und nach einer Wartung, Blutdruck vor\nund nach einer Behandlung, Bearbeitungszeit mit zwei Werkzeugen an denselben\nWerkstücken. Gemeinsam ist ihnen, dass jede Messung einen festen Partner hat.\n\nDie Paarung ist keine Formalität, sondern der Kern des Verfahrens. Sie entfernt\ndie Unterschiede zwischen den Objekten aus der Rechnung. Wenn Maschinen sich\nstark voneinander unterscheiden, aber alle durch dieselbe Massnahme gleichmässig\ngewinnen, verschwindet dieser Gewinn im ungepaarten Vergleich in der Streuung\nzwischen den Maschinen. Rechnerisch ist der gepaarte Test ein\n[Einstichproben-t-Test](t-test-eine-stichprobe.qmd) auf den Differenzen gegen\nnull.\n\n| Situation | Stattdessen |\n|---|---|\n| Unabhängige Gruppen ohne Zuordnung | [t-Test für zwei Stichproben](t-test-zwei-stichproben.qmd) |\n| Mehr als zwei Messzeitpunkte | Varianzanalyse mit Messwiederholung, siehe [ANOVA](anova.qmd) |\n| Differenzen deutlich schief, kleines n | [Wilcoxon-Vorzeichen-Rangtest](nichtparametrische-tests.qmd) |\n| Zielvariable binär, gepaart | McNemar-Test, siehe [Chi-Quadrat-Tests](chi-quadrat-tests.qmd) |\n| Unterschiedliche Anzahl Messungen je Gruppe | Die Paarung ist verletzt; Zuordnung klären oder ungepaart rechnen |\n\n## Grundidee und Modell\n\nAus je zwei Messungen wird eine Differenz gebildet, und diese Differenzen werden\ngegen null geprüft. Alles, was ein Objekt dauerhaft auszeichnet, kürzt sich\ndabei heraus.\n\n$$d_i = y_{i,\\text{nachher}} - y_{i,\\text{vorher}}, \\qquad t = \\frac{\\bar{d}}{s_d/\\sqrt{n}}$$\n\n| Bestandteil | Bedeutung |\n|---|---|\n| $d_i$ | Differenz beim $i$-ten Objekt |\n| $\\bar{d}$ | mittlere Differenz, der berichtete Effekt |\n| $s_d$ | Standardabweichung der Differenzen, nicht der Einzelmessungen |\n| $n$ | Anzahl Paare, nicht Anzahl Messwerte |\n| $s_d/\\sqrt{n}$ | Standardfehler der mittleren Differenz |\n\nDie Nullhypothese lautet, dass die mittlere Differenz null ist. Voraussetzungen\nbetreffen deshalb die Differenzen, nicht die Ausgangswerte: die Einzelmessungen\ndürfen beliebig verteilt sein, solange ihre Differenzen es nicht sind.\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung | Vorgehen |\n|---|---|---|---|---|\n| Feste Zuordnung | Jede Messung hat genau einen Partner, die Reihenfolge stimmt | Datenstruktur prüfen, Identifikator mitführen | Die Differenzen sind Unsinn, und niemand sieht es dem Ergebnis an | Zuordnung über einen Schlüssel herstellen |\n| Unabhängigkeit der Paare | Die Objekte beeinflussen sich nicht gegenseitig | Erhebungsdesign | p-Wert zu optimistisch | Mehrebenenmodell |\n| Annähernd normalverteilte Differenzen | Nur die Differenzen, nicht die Ausgangswerte | [QQ-Plot](../wahrscheinlichkeit/qq-plots.qmd) der Differenzen | Bei kleinem n weicht die Fehlerrate ab | Wilcoxon oder Bootstrap |\n| Keine extremen Ausreisser in den Differenzen | Ein Paar bestimmt das Ergebnis nicht | Boxplot der Differenzen | Ergebnis hängt an einem Paar | Ursache prüfen, mit und ohne berichten |\n\n## Output lesen\n\nR, `t.test(..., paired = TRUE)`:\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| `Paired t-test` | die Variante | fehlt `Paired`, wurde die Paarung vergessen |\n| `t` | mittlere Differenz in Einheiten ihres Standardfehlers | beruht auf der Streuung der Differenzen |\n| `df` | Anzahl Paare minus eins | nicht Anzahl Messwerte minus zwei |\n| `p-value` | Wahrscheinlichkeit dieser oder extremerer Differenzen bei wahrer Null | keine Aussage über die Grösse |\n| `95 percent confidence interval` | Intervall der mittleren Differenz | die berichtenswerte Zeile, in der Einheit der Messung |\n| `mean difference` | Punktschätzer der mittleren Differenz | Vorzeichen hängt an der Reihenfolge der Argumente |\n| `alternative hypothesis` | Richtung | `true mean difference is not equal to 0` |\n| `Cohens d (paired)` | Effektstärke auf Basis der Differenzen | fällt deutlich grösser aus als die ungepaarte Variante; beide Fassungen nie vermischen |\n\nPython, `pg.ttest(..., paired=True)` liefert dieselben Grössen in einer Zeile:\nTeststatistik, Freiheitsgrade, p-Wert, Konfidenzintervall, Effektstärke, dazu\nBayes-Faktor und Power. Die Spaltennamen haben sich zwischen den\npingouin-Versionen geändert, weshalb die Beispiele hier die Spalten nachschlagen\nstatt sie festzuschreiben. Zwei Unterschiede zu R:\n`cohen-d` wird von pingouin für gepaarte Daten anders normiert als von\n`effectsize` in R, weshalb die beiden Zahlen abweichen können; welche Fassung\nverwendet wurde, gehört deshalb in den Bericht. Und `CI95%` bezieht sich auf die\nmittlere Differenz, was hier die interessierende Grösse ist.\n\n## Interpretationsfallen\n\n- **Die Paarung ist eine Eigenschaft der Erhebung, keine Wahl der Auswertung.**\n  Gepaarte Daten ungepaart zu rechnen verschenkt Schärfe, ungepaarte Daten\n  gepaart zu rechnen ist schlicht falsch.\n- **Freiheitsgrade richtig lesen.** Sie ergeben sich aus der Anzahl Paare, nicht\n  aus der Anzahl Messwerte.\n- **Die Effektstärke ist nicht mit der ungepaarten vergleichbar.** Für gepaarte\n  Daten wird an der Streuung der Differenzen normiert, was systematisch grössere\n  Werte ergibt.\n- **Vorzeichen prüfen.** Ob eine Verbesserung positiv oder negativ erscheint,\n  hängt allein an der Reihenfolge der Argumente.\n- **Voraussetzungen gelten den Differenzen.** Schiefe Ausgangswerte sind\n  unkritisch, solange die Differenzen symmetrisch streuen.\n- **Regression zur Mitte.** Werden Objekte wegen extremer Ausgangswerte\n  ausgewählt, fallen die zweiten Messungen schon aus statistischen Gründen\n  weniger extrem aus. Ohne Kontrollgruppe ist ein solcher Effekt kein Beleg für\n  die Wirkung der Massnahme.\n\n## Ergebnis berichten\n\nVorlage für den Ergebnissatz:\n\n> [Zielgrösse] verändert sich zwischen [Zeitpunkt 1] (M = [Mittelwert],\n> SD = [Streuung]) und [Zeitpunkt 2] (M = [Mittelwert], SD = [Streuung]) um\n> [mittlere Differenz] [Einheit] (95-Prozent-Konfidenzintervall [unten] bis\n> [oben], t([df]) = [t], p = [p], Cohens d = [d], n = [Paare]).\n\nGenannt werden beide Messzeitpunkte mit Mittelwert und Streuung, die mittlere\nDifferenz mit Konfidenzintervall, Teststatistik mit Freiheitsgraden, p-Wert,\nEffektstärke samt ihrer Fassung und die Anzahl vollständiger Paare.\n\nBeispiel für eine Ergebnistabelle:\n\n| Zeitpunkt | n | Mittelwert | Standardabweichung |\n|---|---|---|---|\n| vorher | | | |\n| nachher | | | |\n\n| Mittlere Differenz | 95-Prozent-Intervall | t | df | p | d |\n|---|---|---|---|---|---|\n| | | | | | |\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt des gepaarten t-Tests |\n|---|---|\n| [t-Test für zwei Stichproben](t-test-zwei-stichproben.qmd) | die Beobachtungen sind einander nicht zugeordnet |\n| [t-Test für eine Stichprobe](t-test-eine-stichprobe.qmd) | rechnerisch derselbe Test auf den Differenzen; nützlich, wenn die Differenzen bereits vorliegen |\n| [Wilcoxon-Vorzeichen-Rangtest](nichtparametrische-tests.qmd) | die Differenzen sind deutlich schief oder enthalten Ausreisser |\n| [Varianzanalyse](anova.qmd) | mehr als zwei Messzeitpunkte an denselben Objekten |\n| [Chi-Quadrat-Tests](chi-quadrat-tests.qmd) | gepaarte binäre Daten, dort der McNemar-Test |\n\n## Beispiele\n\nAlle Beispiele rechnen mit fest eingetragenen Zahlen, damit R und Python\ndieselben Daten sehen und jeder Wert im Text nachprüfbar ist.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Reaktionszeit vor und nach einer Schulung\n\n#### Frage und Datenlage\n\nFünfzehn Personen bearbeiten dieselbe Aufgabe zweimal, einmal vor und einmal\nnach einer Schulung. Gemessen wird die Reaktionszeit in Millisekunden. Die Frage\nlautet: Hat sich die Reaktionszeit verändert, und um wie viel?\n\nEntscheidend ist die Struktur der Daten: Es sind nicht dreissig unabhängige\nMessungen, sondern fünfzehn Personen mit je zwei Werten. Personen unterscheiden\nsich stark voneinander, und genau dieser Unterschied interessiert hier nicht.\nDer gepaarte Test entfernt ihn, indem er nur mit den Differenzen je Person\nrechnet.\n\n#### Voraussetzungen prüfen\n\nGeprüft wird nicht die Verteilung der Messwerte, sondern die der **Differenzen**.\nDas ist der häufigste Missgriff auf dieser Seite.\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvorher  <- c(412, 498, 455, 530, 388, 472, 505, 441, 519, 463, 398, 486, 527, 450, 475)\nnachher <- c(394, 493, 430, 533, 374, 450, 497, 411, 525, 451, 379, 484, 501, 441, 460)\ndifferenz <- nachher - vorher\n\npar(mfrow = c(1, 3), mar = c(4, 4, 3, 1))\nmatplot(t(cbind(vorher, nachher)), type = \"b\", pch = 16, lty = 1,\n        col = \"grey40\", xaxt = \"n\", xlab = \"\", ylab = \"Reaktionszeit (ms)\",\n        main = \"Je Person\")\naxis(1, at = 1:2, labels = c(\"vorher\", \"nachher\"))\nboxplot(differenz, main = \"Differenzen\", ylab = \"Millisekunden\")\nabline(h = 0, lty = 2, col = \"firebrick\")\nqqnorm(differenz, main = \"QQ-Plot der Differenzen\"); qqline(differenz)\npar(mfrow = c(1, 1))\n\nround(c(mittel_diff = mean(differenz), sd_diff = sd(differenz),\n        korrelation = cor(vorher, nachher)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmittel_diff     sd_diff korrelation \n   -13.0667     10.6668      0.9824 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 1: Werte je Person, Verteilung der Differenzen und QQ-Plot der Differenzen.](t-test-gepaart_files/figure-html/fig-b1-gp-voraussetzungen-r-1.png){#fig-b1-gp-voraussetzungen-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nvorher = np.array([412, 498, 455, 530, 388, 472, 505, 441, 519, 463,\n                   398, 486, 527, 450, 475])\nnachher = np.array([394, 493, 430, 533, 374, 450, 497, 411, 525, 451,\n                    379, 484, 501, 441, 460])\ndifferenz = nachher - vorher\n\nfig, achsen = plt.subplots(1, 3, figsize=(7, 3.2))\nfor v, n in zip(vorher, nachher):\n    achsen[0].plot([0, 1], [v, n], \"o-\", color=\"0.4\", markersize=4)\nachsen[0].set_xticks([0, 1], [\"vorher\", \"nachher\"])\nachsen[0].set_ylabel(\"Reaktionszeit (ms)\")\nachsen[0].set_title(\"Je Person\")\nachsen[1].boxplot(differenz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'whiskers': [<matplotlib.lines.Line2D object at 0x7f6527fec590>, <matplotlib.lines.Line2D object at 0x7f6527fec830>], 'caps': [<matplotlib.lines.Line2D object at 0x7f6527fecad0>, <matplotlib.lines.Line2D object at 0x7f6527fecd40>], 'boxes': [<matplotlib.lines.Line2D object at 0x7f6527fec410>], 'medians': [<matplotlib.lines.Line2D object at 0x7f6527fc7d40>], 'fliers': [<matplotlib.lines.Line2D object at 0x7f6527fc7bf0>], 'means': []}\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[1].axhline(0, linestyle=\"--\", color=\"firebrick\")\nachsen[1].set_title(\"Differenzen\")\nachsen[1].set_ylabel(\"Millisekunden\")\nsm.qqplot(differenz, line=\"s\", ax=achsen[2])\nachsen[2].set_title(\"QQ-Plot der Differenzen\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Prüfung in Python.](t-test-gepaart_files/figure-html/fig-b1-gp-voraussetzungen-py-1.png){#fig-b1-gp-voraussetzungen-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(\"Mittel der Differenzen =\", round(differenz.mean(), 4),\n      \" SD =\", round(differenz.std(ddof=1), 4),\n      \" Korrelation =\", round(np.corrcoef(vorher, nachher)[0, 1], 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMittel der Differenzen = -13.0667  SD = 10.6668  Korrelation = 0.9824\n```\n\n\n:::\n:::\n\n\n:::\n\nIm linken Bild verläuft fast jede Linie nach unten: Die meisten Personen sind\nnachher schneller. Zugleich liegen die Linien weit auseinander, von knapp 390 bis\nüber 530 Millisekunden. Diese Spanne zwischen den Personen ist rund viermal so\ngross wie die Veränderung innerhalb einer Person, und die Korrelation zwischen\nden beiden Messungen beträgt 0.98.\n\nGenau daraus zieht der gepaarte Test seine Schärfe: Was beide Messungen einer\nPerson gemeinsam haben, kürzt sich in der Differenz heraus.\n\nDie Differenzen selbst sind unauffällig verteilt, der QQ-Plot zeigt keine\nAbweichung von Belang, und der Boxplot liegt vollständig unterhalb der Nulllinie.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(nachher, vorher, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  nachher and vorher\nt = -4.7443, df = 14, p-value = 0.0003138\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n -18.973752  -7.159581\nsample estimates:\nmean difference \n      -13.06667 \n```\n\n\n:::\n\n```{.r .cell-code}\neffectsize::cohens_d(nachher, vorher, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |         95% CI\n--------------------------\n-1.22     | [-1.89, -0.54]\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(pg.ttest(nachher, vorher, paired=True).round(4).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      T_test\nT                    -4.7443\ndof                       14\nalternative        two-sided\np_val                 0.0003\nCI95         [-18.97, -7.16]\ncohen_d               0.2727\npower                 0.1664\nBF10                 105.393\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| Variante | `Paired t-test` | gepaart gerechnet | Fehlt das Wort `Paired`, wurde `paired = TRUE` vergessen, und das Ergebnis ist ein anderes, siehe Beispiel 2. |\n| `t` | -4.744 | Die mittlere Differenz liegt 4.74 Standardfehler unter null. | Das Vorzeichen folgt der Reihenfolge der Argumente: `nachher` minus `vorher`, negativ heisst also schneller geworden. |\n| `df` | 14 | Freiheitsgrade | Anzahl **Paare** minus eins, nicht Anzahl Messungen minus eins. Bei 15 Personen mit 30 Messwerten sind es 14, nicht 28. |\n| `p-value` | 0.00031 | Wahrscheinlichkeit einer mindestens so grossen mittleren Differenz, wenn sich in Wahrheit nichts geändert hätte | Deutlich unter 0.05. |\n| `mean difference` | -13.07 | mittlere Veränderung in Millisekunden | Die eigentliche Effektgrösse. Nach der Schulung sind die Personen im Mittel 13 ms schneller. |\n| `95 percent confidence interval` | -18.97 bis -7.16 | Intervall für die **Differenz**, nicht für einen Mittelwert | Anders als beim Einstichprobentest steht hier direkt die interessierende Grösse. Plausibel ist eine Verbesserung zwischen 7 und 19 ms. |\n| Effektstärke in R | -1.23 | Differenz in Einheiten der Streuung **der Differenzen** | Das ist $d_z$: -13.07 geteilt durch 10.67. Er beantwortet die Frage \"wie gross ist die Veränderung im Verhältnis dazu, wie unterschiedlich die Veränderungen ausfallen\". |\n| `cohen_d` in Python | 0.27 | Differenz in Einheiten der Streuung **zwischen den Personen** | Nicht derselbe Wert und kein Fehler, sondern eine andere Definition, siehe den Kasten unten. |\n| `power` (nur Python) | 0.166 | Trefferwahrscheinlichkeit für den beobachteten Effekt | Niedrig, weil pingouin sie aus dem kleinen d von 0.27 berechnet und nicht aus $d_z$. Im Nachhinein berechnete Power ist ohnehin nur eingeschränkt aussagekräftig. |\n| `BF10` (nur Python) | 105.4 | Bayes-Faktor | Die Daten sind rund hundertmal wahrscheinlicher unter einer Veränderung als unter Gleichheit. |\n\n::: {.note-box}\n**Cohens d ist bei gepaarten Daten nicht eindeutig, und die beiden Sprachen\nwählen verschieden.** R gibt mit `effectsize::cohens_d(paired = TRUE)` den Wert\n-1.23 aus, pingouin gibt 0.27 aus. Beide sind richtig gerechnet, sie teilen nur\ndurch etwas anderes:\n\n| | Nenner | Wert hier | Frage, die er beantwortet |\n|---|---|---|---|\n| $d_z$ (R) | Streuung der Differenzen, 10.67 ms | -1.23 | Wie deutlich ist die Veränderung im Verhältnis zu ihrer eigenen Schwankung? |\n| $d$ (pingouin) | gepoolte Streuung der beiden Messreihen, rund 47.9 ms | 0.27 | Wie gross ist die Veränderung im Verhältnis zu den Unterschieden zwischen Personen? |\n\n$d_z$ hängt an der Korrelation der beiden Messungen und wird gross, sobald die\nPaarung gut greift; er eignet sich für die Planung eines weiteren gepaarten\nVersuchs. Das gepoolte $d$ ist mit Effektstärken aus Zweistichprobenvergleichen\nvergleichbar und eignet sich für die Einordnung gegen Literaturwerte. Wer eine\nEffektstärke berichtet, schreibt deshalb dazu, welche gemeint ist; die blosse\nAngabe \"d = 1.23\" ist ohne diesen Zusatz nicht deutbar.\n:::\n\n#### Interpretation und Ergebnissatz\n\nBerichtet wird die Veränderung in Millisekunden mit ihrem Intervall, nicht der\np-Wert allein. Ob 13 ms viel sind, entscheidet die Sache: Bei einer Aufgabe mit\nReaktionszeiten um 460 ms sind das rund drei Prozent.\n\nUnd eine Grenze des Designs gehört dazu: Gemessen wurde vorher und nachher ohne\nKontrollgruppe. Die Verbesserung kann von der Schulung kommen, ebenso gut aber\nvom blossen Wiederholen der Aufgabe. Der gepaarte Test misst die Veränderung,\nnicht ihre Ursache.\n\n> Nach der Schulung sind die Reaktionszeiten kürzer (vorher M = 467.9 ms,\n> SD = 44.9; nachher M = 454.9 ms, SD = 50.7; n = 15 Personen): mittlere\n> Veränderung -13.1 ms, 95-Prozent-Konfidenzintervall -19.0 bis -7.2 ms,\n> t(14) = -4.74, p < 0.001, $d_z$ = -1.23 (gepoolt: d = 0.27). Ohne\n> Kontrollgruppe lässt sich die\n> Veränderung nicht ursächlich der Schulung zuschreiben.\n\n### Beispiel 2: Was die Paarung ausmacht\n\n#### Frage und Datenlage\n\nDieselben Daten wie in Beispiel 1, nur wird die Paarung diesmal ignoriert und\nmit `paired = FALSE` gerechnet. Das passiert in der Praxis leicht: Die Daten\nliegen in zwei Spalten, und die Zuordnung zur Person ist nicht sichtbar.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(nachher, vorher, paired = TRUE)$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0003137826\n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(nachher, vorher, paired = FALSE)   # falsch gerechnet\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  nachher and vorher\nt = -0.74676, df = 27.598, p-value = 0.4615\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -48.93293  22.79960\nsample estimates:\nmean of x mean of y \n 454.8667  467.9333 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nrichtig = pg.ttest(nachher, vorher, paired=True)\nfalsch = pg.ttest(nachher, vorher, paired=False, correction=True)\n\nvergleich = pd.DataFrame({\n    \"gepaart\": [pg_wert(richtig, \"t\"), pg_wert(richtig, \"dof\"),\n                pg_wert(richtig, \"p-val\")],\n    \"ungepaart\": [pg_wert(falsch, \"t\"), pg_wert(falsch, \"dof\"),\n                  pg_wert(falsch, \"p-val\")],\n}, index=[\"T\", \"dof\", \"p\"])\nprint(vergleich.round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     gepaart  ungepaart\nT    -4.7443    -0.7468\ndof  14.0000    27.5977\np     0.0003     0.4615\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Gepaart | Ungepaart | Wie das zu lesen ist |\n|---|---|---|---|\n| `t` | -4.744 | -0.747 | Derselbe Unterschied von 13 ms, sechsmal kleinere Teststatistik. |\n| `df` | 14 | rund 27.6 | Ungepaart gibt es scheinbar mehr Freiheitsgrade, was nach mehr Information aussieht. Das Gegenteil ist der Fall. |\n| `p-value` | 0.00031 | 0.462 | Aus einem klaren Befund wird ein Nullbefund. |\n| Streuung im Nenner | SD der Differenzen: 10.7 ms | SD zwischen den Personen: rund 48 ms | Hier steckt die ganze Erklärung. |\n\nDer ungepaarte Test vergleicht zwei Mittelwerte und misst die Zufallsstreuung an\nden Unterschieden **zwischen** den Personen. Die betragen hier rund 48 ms und\nhaben mit der Wirkung der Schulung nichts zu tun. Vor dieser Kulisse verschwindet\neine Veränderung von 13 ms.\n\nDer gepaarte Test rechnet dagegen mit den fünfzehn Differenzen. Deren Streuung\nbeträgt 10.7 ms, weil sich der Personenunterschied beim Subtrahieren heraushebt.\nDerselbe Effekt wird dadurch messbar.\n\n#### Interpretation und Ergebnissatz\n\nDie Lehre ist nicht \"gepaart rechnen ist besser\", sondern: Das Verfahren muss zum\nErhebungsdesign passen. Bei gepaarten Daten ungepaart zu rechnen verschenkt\nInformation und findet echte Effekte oft nicht. Der umgekehrte Fehler ist\nschwerwiegender: Unabhängige Daten gepaart zu rechnen erfindet eine Zuordnung,\ndie es nicht gibt, und liefert Ergebnisse, die durch nichts gedeckt sind.\n\nDie Frage, an der sich das entscheidet, lautet immer gleich: Gibt es einen\nsachlichen Grund, warum Wert Nummer 7 der einen Reihe zu Wert Nummer 7 der\nanderen gehört? Dieselbe Person, dasselbe Werkstück, derselbe Standort. Wenn\nja, ist es gepaart; wenn sich die Reihenfolge einer Spalte ohne Informationsverlust\nmischen liesse, ist es das nicht.\n\n> Die Auswertung erfolgte gepaart, da beide Messungen an denselben fünfzehn\n> Personen erhoben wurden. Eine ungepaarte Auswertung derselben Daten hätte den\n> Effekt nicht gefunden (t = -0.75, p = 0.46), weil sie die Unterschiede\n> zwischen den Personen als Zufallsstreuung behandelt.\n\n### Beispiel 3: Keine nachweisbare Veränderung\n\n#### Frage und Datenlage\n\nZwölf Personen, dieselbe Aufgabe, aber statt einer Schulung liegt nur eine Woche\nzwischen den Messungen. Erwartet wird keine Veränderung; das Beispiel zeigt, wie\nein Nullbefund bei gepaarten Daten aussieht.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvor_woche  <- c(412, 498, 455, 530, 388, 472, 505, 441, 519, 463, 398, 486)\nnach_woche <- c(416, 491, 457, 524, 393, 469, 513, 436, 520, 459, 405, 489)\n\nt.test(nach_woche, vor_woche, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  nach_woche and vor_woche\nt = 0.27596, df = 11, p-value = 0.7877\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n -2.906509  3.739842\nsample estimates:\nmean difference \n      0.4166667 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(sd_differenzen = sd(nach_woche - vor_woche),\n        korrelation = cor(vor_woche, nach_woche)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsd_differenzen    korrelation \n        5.2303         0.9945 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nvor_woche = np.array([412, 498, 455, 530, 388, 472, 505, 441, 519, 463, 398, 486])\nnach_woche = np.array([416, 491, 457, 524, 393, 469, 513, 436, 520, 459, 405, 489])\n\nprint(pg.ttest(nach_woche, vor_woche, paired=True).round(4).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    T_test\nT                    0.276\ndof                     11\nalternative      two-sided\np_val               0.7877\nCI95         [-2.91, 3.74]\ncohen_d             0.0091\npower               0.0501\nBF10                 0.297\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"SD der Differenzen =\", round((nach_woche - vor_woche).std(ddof=1), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSD der Differenzen = 5.2303\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| `mean difference` | 0.42 | Vier Zehntel Millisekunden. Praktisch null. |\n| `t` | 0.276 | Weit unter einem Standardfehler. |\n| `df` | 11 | Zwölf Paare minus eins. |\n| `p-value` | 0.788 | Die Daten sind mit \"keine Veränderung\" gut vereinbar. |\n| `95 percent confidence interval` | -2.91 bis 3.74 ms | Die aussagekräftigste Zeile, und hier ausnahmsweise eine starke Aussage: Das Intervall ist nur rund sieben Millisekunden breit. Veränderungen von mehr als vier Millisekunden sind mit diesen Daten kaum vereinbar. |\n| `cohen_d` | 0.08 | Vernachlässigbar. |\n\n#### Interpretation und Ergebnissatz\n\nDieser Nullbefund ist deutlich mehr wert als der aus Beispiel 2 des\n[Einstichprobentests](t-test-eine-stichprobe.qmd). Der Grund ist das schmale\nIntervall: Weil die Paarung die Streuung auf 5.2 ms drückt, schliesst dieser\nNullbefund grosse Veränderungen tatsächlich aus.\n\nDamit lässt sich mehr sagen als \"nichts gefunden\": Eine Veränderung von mehr als\netwa vier Millisekunden ist mit den Daten nicht vereinbar. Ob das als Nachweis\nder Stabilität genügt, entscheidet die vorab festgelegte Toleranz. Formal sauber\nwäre auch hier ein Äquivalenztest, aber die Aussage des Intervalls geht in\ndieselbe Richtung und ist bereits belastbar.\n\n> Über eine Woche ohne Massnahme verändert sich die Reaktionszeit nicht\n> nachweisbar (mittlere Veränderung 0.4 ms, 95-Prozent-Konfidenzintervall -2.9\n> bis 3.7 ms, t(11) = 0.28, p = 0.79, n = 12 Personen). Das Intervall schliesst\n> Veränderungen von mehr als vier Millisekunden praktisch aus.\n\n### Beispiel 4: Ein Ausreisser in den Differenzen\n\n#### Frage und Datenlage\n\nZwölf Personen, wieder eine Massnahme dazwischen. Elf Personen verbessern sich um\nrund zwölf Millisekunden, eine verschlechtert sich um 74. Solche Einzelfälle\nkommen vor: eine Störung während der Messung, ein Missverständnis der Aufgabe,\nein technisches Problem.\n\n#### Voraussetzungen prüfen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvor_m  <- c(412, 498, 455, 530, 388, 472, 505, 441, 519, 463, 398, 486)\nnach_m <- c(400, 486, 443, 517, 376, 460, 493, 429, 507, 451, 386, 560)\ndiff_m <- nach_m - vor_m\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nstripchart(diff_m, method = \"stack\", pch = 16, main = \"Differenzen je Person\",\n           xlab = \"Veränderung (ms)\")\nabline(v = 0, lty = 2, col = \"firebrick\")\nqqnorm(diff_m, main = \"QQ-Plot der Differenzen\"); qqline(diff_m)\npar(mfrow = c(1, 1))\n\nround(c(mittel = mean(diff_m), median = median(diff_m), sd = sd(diff_m)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n mittel  median      sd \n -4.917 -12.000  24.854 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 4: elf ähnliche Differenzen und ein Ausreisser.](t-test-gepaart_files/figure-html/fig-b4-gp-voraussetzungen-r-1.png){#fig-b4-gp-voraussetzungen-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nvor_m = np.array([412, 498, 455, 530, 388, 472, 505, 441, 519, 463, 398, 486])\nnach_m = np.array([400, 486, 443, 517, 376, 460, 493, 429, 507, 451, 386, 560])\ndiff_m = nach_m - vor_m\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nachsen[0].plot(diff_m, np.zeros_like(diff_m), \"o\", color=\"0.3\")\nachsen[0].axvline(0, linestyle=\"--\", color=\"firebrick\")\nachsen[0].set_yticks([])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[]\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[0].set_xlabel(\"Veränderung (ms)\")\nachsen[0].set_title(\"Differenzen je Person\")\nsm.qqplot(diff_m, line=\"s\", ax=achsen[1])\nachsen[1].set_title(\"QQ-Plot der Differenzen\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselbe Prüfung in Python.](t-test-gepaart_files/figure-html/fig-b4-gp-voraussetzungen-py-1.png){#fig-b4-gp-voraussetzungen-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(\"Mittel =\", round(diff_m.mean(), 3), \" Median =\", round(np.median(diff_m), 3),\n      \" SD =\", round(diff_m.std(ddof=1), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMittel = -4.917  Median = -12.0  SD = 24.854\n```\n\n\n:::\n:::\n\n\n:::\n\nMittelwert der Differenzen -4.9 ms, Median -12.0 ms, Standardabweichung 24.9 ms.\nDie Lücke zwischen Mittelwert und Median ist das Warnsignal: Ein einziger Wert\nzieht den Mittelwert um sieben Millisekunden nach oben und verdoppelt die\nStreuung. Im QQ-Plot liegt er weit ausserhalb.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(nach_m, vor_m, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  nach_m and vor_m\nt = -0.68528, df = 11, p-value = 0.5074\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n -20.70812  10.87479\nsample estimates:\nmean difference \n      -4.916667 \n```\n\n\n:::\n\n```{.r .cell-code}\nwilcox.test(nach_m, vor_m, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon signed rank exact test\n\ndata:  nach_m and vor_m\nV = 12, p-value = 0.02832\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nt_wert, t_p = stats.ttest_rel(nach_m, vor_m)\nv_wert, v_p = stats.wilcoxon(diff_m)\nprint(\"gepaarter t-Test     t =\", round(t_wert, 4), \" p =\", round(t_p, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngepaarter t-Test     t = -0.6853  p = 0.5074\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Wilcoxon (gepaart)   V =\", v_wert, \" p =\", round(v_p, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWilcoxon (gepaart)   V = 12.0  p = 0.0283\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| t-Test `mean difference` | -4.92 | Sieht nach einer kleinen Verbesserung aus, beschreibt aber keine einzige der zwölf Personen: Elf verbesserten sich um zwölf, eine verschlechterte sich um 74. |\n| t-Test `t` | -0.685 | Der Standardfehler beträgt 7.2 ms, weil der eine Wert die Streuung verdoppelt. |\n| t-Test `p-value` | 0.507 | Nicht signifikant. |\n| t-Test Intervall | -20.71 bis 10.87 ms | Über 31 ms breit; es schliesst nichts aus. |\n| Wilcoxon `V` | 12 | Die Rangsumme der positiven Differenzen. Nur eine Person hat sich verschlechtert, deshalb ist der Wert klein. |\n| Wilcoxon `p-value` | 0.028 | Signifikant, also die gegenteilige Entscheidung. |\n\n#### Interpretation und Ergebnissatz\n\nDer Rangtest sieht, dass sich elf von zwölf Personen verbessert haben. Der\nt-Test sieht den Mittelwert der Differenzen, geteilt durch eine Streuung, die ein\neinzelner Wert bestimmt.\n\nDie Reihenfolge bleibt dieselbe wie immer: erst die Verteilung der Differenzen\nansehen, dann das Verfahren wählen, dann rechnen. Und der auffällige Fall gehört\nin den Bericht, nicht in den Papierkorb. Wenn sich klären lässt, dass die Messung\ngestört war, wird sie mit Begründung ausgeschlossen; bleibt die Ursache offen,\nwird das Ergebnis mit und ohne den Fall berichtet.\n\n> Die Differenzen enthalten einen Extremwert (eine Verschlechterung um 74 ms bei\n> elf Verbesserungen um rund 12 ms), weshalb vorab rangbasiert ausgewertet wurde.\n> Die Reaktionszeit verkürzt sich (Wilcoxon für verbundene Stichproben, V = 12,\n> p = 0.028, n = 12; Median der Veränderung -12.0 ms). Ein Mittelwertvergleich\n> wäre an diesem Einzelfall gescheitert (t(11) = -0.69, p = 0.51).\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nDer gepaarte Test liefert p < 0.001, der ungepaarte auf denselben Daten\np = 0.85. Welche Zahl gilt?\n\n- [x] Die des gepaarten Tests, wenn die Daten tatsächlich gepaart erhoben wurden ~\n      Richtig. Die Paarung entfernt die Streuung zwischen den Objekten. Der\n      ungepaarte Test misst den Effekt an einer viel grösseren Streuung und\n      übersieht ihn deshalb.\n- [ ] Die des ungepaarten Tests, weil er konservativer ist ~ Konservativ ist\n      hier kein Vorzug, sondern das Ergebnis einer falschen Annahme über die\n      Datenstruktur.\n- [ ] Der Mittelwert beider p-Werte ~ p-Werte werden nicht gemittelt.\n:::\n\n::: {.quiz}\nNach dem Zusammenführen zweier Messreihen springt die Standardabweichung der\nDifferenzen von 0.3 auf 12. Was ist zu prüfen?\n\n- [x] Ob die Paarung noch stimmt ~ Richtig. Eine Streuung in der Grössenordnung\n      der Unterschiede zwischen den Objekten deutet darauf hin, dass die\n      Zuordnung verloren ging und falsche Paare gebildet wurden.\n- [ ] Ob die Messgeräte kalibriert waren ~ Möglich, aber dann wäre auch der\n      Mittelwert der Differenzen betroffen.\n- [ ] Nichts, das ist normal ~ Es ist das Gegenteil von normal: die Paarung\n      soll die Streuung gerade verkleinern.\n:::\n\n::: {.quiz}\nWarum sind bei 20 Maschinen die Freiheitsgrade 19 und nicht 38?\n\n- [x] Weil die Analyse auf 20 Differenzen beruht ~ Richtig. Aus 40 Messwerten\n      werden 20 Paare und daraus 20 Differenzen; ein Freiheitsgrad geht für den\n      Mittelwert verloren.\n- [ ] Weil zwei Parameter geschätzt werden ~ Das wäre die Rechnung beim\n      ungepaarten Test mit zwei Gruppen.\n- [ ] Weil die Hälfte der Werte redundant ist ~ Redundant ist nichts; die\n      Information steckt in den Differenzen.\n:::\n\n::: {.quiz}\nFür eine Massnahme wurden gezielt die 20 Maschinen mit dem höchsten Verbrauch\nausgewählt. Nach der Wartung liegt der Verbrauch signifikant niedriger. Was\nfehlt für den Schluss auf die Wirkung?\n\n- [ ] Nichts, das Ergebnis ist eindeutig ~ Es ist statistisch eindeutig und\n      inhaltlich nicht.\n- [x] Eine Kontrollgruppe, wegen der Regression zur Mitte ~ Richtig. Objekte,\n      die wegen extremer Werte ausgewählt wurden, zeigen bei der zweiten Messung\n      schon aus statistischen Gründen weniger extreme Werte, auch ohne jede\n      Massnahme.\n- [ ] Ein grösserer Stichprobenumfang ~ Mehr Maschinen würden denselben\n      systematischen Fehler nur präziser reproduzieren.\n:::\n\n## Verlinkte Ressourcen\n\n- [OpenIntro Statistics, Kapitel zu gepaarten Daten](https://www.openintro.org/book/os/)\n- [pingouin: ttest](https://pingouin-stats.org/build/html/generated/pingouin.ttest.html)\n- [R-Dokumentation zu `t.test`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/t.test.html)\n",
    "supporting": [
      "t-test-gepaart_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}