{
  "hash": "552a7dc0eb8c497ba26186a7388c689f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multiples Testen\"\ndescription: \"Warum viele Tests falsche Alarme erzeugen und wie Bonferroni, Holm und Benjamini-Hochberg gegensteuern.\"\ncategories: [\"Hypothesentests\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"ESDS\", \"STATDA\"]\nseitentyp: konzept\nstand: fertig\norder: 60\n---\n\n\n\n\n\n## Kernideen\n\n- Ein Signifikanzniveau von 0.05 bedeutet: In fünf von hundert Fällen wird ein\n  Effekt behauptet, den es nicht gibt. Bei **einem** Test. Bei zwanzig Tests\n  liegt die Wahrscheinlichkeit für mindestens einen falschen Alarm bei 64\n  Prozent.\n- Das Problem entsteht nicht durch das Rechnen, sondern durch das **Auswählen**:\n  Wer viele Tests rechnet und den kleinsten p-Wert berichtet, hat eine Auswahl\n  getroffen, die der p-Wert nicht kennt.\n- Korrekturverfahren senken die Schwelle. Sie kosten dafür Power: Dieselbe\n  Studie findet nach der Korrektur weniger.\n- Es gibt zwei verschiedene Fehlerbegriffe, und sie verlangen verschiedene\n  Verfahren: die Wahrscheinlichkeit **mindestens eines** Fehlalarms (FWER) und\n  der **Anteil** der Fehlalarme unter den Funden (FDR).\n- Am wirksamsten ist es, die Zahl der Tests von vornherein klein zu halten und\n  vorab festzulegen, welche gerechnet werden.\n\n## Erklärung\n\n### Wie schnell die Fehlerrate wächst\n\nSind alle Nullhypothesen wahr und die Tests unabhängig, beträgt die\nWahrscheinlichkeit für mindestens einen falschen Alarm $1 - (1-\\alpha)^m$:\n\n| Anzahl Tests | Wahrscheinlichkeit mindestens eines Fehlalarms |\n|---|---|\n| 1 | 5.0 % |\n| 3 | 14.3 % |\n| 5 | 22.6 % |\n| 10 | 40.1 % |\n| 20 | 64.2 % |\n| 50 | 92.3 % |\n| 100 | 99.4 % |\n\nBei zwanzig Tests ist ein falscher Alarm also der Normalfall, nicht die\nAusnahme. Und zwanzig Tests sind schnell erreicht: Fünf Gruppen paarweise\nverglichen ergeben zehn Tests, drei Zielgrössen bei vier Gruppen ergeben\nachtzehn.\n\n### Wo überall unbemerkt mehrfach getestet wird\n\n| Situation | Anzahl Tests |\n|---|---|\n| Paarweise Vergleiche nach einer [Varianzanalyse](../tests/anova.qmd) | bei $k$ Gruppen: $k(k-1)/2$ |\n| Mehrere Zielgrössen in derselben Studie | eine je Zielgrösse |\n| Zwischenauswertungen während der Erhebung | eine je Blick auf die Daten |\n| Untergruppen nachträglich betrachten | eine je Untergruppe |\n| Mehrere Verfahren ausprobieren und das passende berichten | so viele wie ausprobiert |\n| Koeffizienten einer [Regression](../regression/multiple-lineare-regression.qmd) | einer je Prädiktor |\n\nDie letzten drei Zeilen sind die gefährlichen, weil dort meist gar nicht\ngezählt wird, wie viele Tests tatsächlich stattgefunden haben.\n\n### Zwei Fehlerbegriffe\n\n| Begriff | Was kontrolliert wird | Wann passend |\n|---|---|---|\n| FWER, familienweise Fehlerrate | Wahrscheinlichkeit für **mindestens einen** Fehlalarm in der ganzen Gruppe von Tests | wenn ein einziger falscher Befund teuer ist: Zulassung, Sicherheitsnachweis, Bestätigungsstudie |\n| FDR, False Discovery Rate | erwarteter **Anteil** falscher Befunde unter den verworfenen Hypothesen | bei explorativen Auswertungen mit vielen Tests, wenn die Funde ohnehin nachgeprüft werden |\n\nDer Unterschied ist praktisch bedeutsam. FWER auf 5 Prozent heisst: \"Mit 95\nProzent Wahrscheinlichkeit ist unter allen Befunden kein einziger falsch.\" FDR\nauf 5 Prozent heisst: \"Von den Befunden sind im Mittel 5 Prozent falsch.\" Bei\nhundert Tests und zwanzig Funden erlaubt das eine Falschmeldung, das andere\netwa eine unter den zwanzig.\n\n### Die drei Verfahren\n\n| Verfahren | Kontrolliert | Wie es rechnet | Schärfe |\n|---|---|---|---|\n| Bonferroni | FWER | jeder p-Wert mit $m$ multipliziert, gleichbedeutend mit Schwelle $\\alpha/m$ | am strengsten, einfach zu erklären |\n| Holm | FWER | schrittweise: p-Werte sortieren, den kleinsten gegen $\\alpha/m$ prüfen, den zweiten gegen $\\alpha/(m-1)$ und so weiter, bis der erste nicht mehr verworfen wird | hält dasselbe Niveau wie Bonferroni, verwirft aber nie weniger |\n| Benjamini-Hochberg | FDR | sortieren, den $i$-ten gegen $\\alpha \\cdot i/m$ prüfen, vom grössten her rückwärts | deutlich mehr Funde, dafür ein anderes Versprechen |\n\n::: {.note-box}\n**Holm ist Bonferroni ohne Nachteil.** Beide kontrollieren die familienweise\nFehlerrate gleich streng, aber Holm verwirft in jeder denkbaren Lage mindestens\nso viele Hypothesen wie Bonferroni und oft mehr. Es gibt deshalb keinen\nstatistischen Grund, Bonferroni zu verwenden; der einzige Vorteil ist, dass sich\n\"Schwelle geteilt durch Anzahl Tests\" leichter erklären lässt.\n:::\n\n### Was die Korrektur kostet\n\nEine gesenkte Schwelle senkt die Power. Bei einem mittleren Effekt und 64 Fällen\nje Gruppe:\n\n| Anzahl Tests | Schwelle nach Bonferroni | Power |\n|---|---|---|\n| 1 | 0.0500 | 0.80 |\n| 5 | 0.0100 | 0.59 |\n| 10 | 0.0050 | 0.49 |\n| 20 | 0.0025 | 0.40 |\n\nWer die Zahl der Tests nicht begrenzt, verliert also an beiden Enden: ohne\nKorrektur falsche Alarme, mit Korrektur die Fähigkeit, echte Effekte zu finden.\nDer einzige Ausweg ist, vorab weniger zu testen, siehe\n[Power](power-stichprobenumfang.qmd).\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Wie schnell die Fehlerrate wächst\n\n#### Frage und Datenlage\n\nAlle Nullhypothesen sind wahr, es gibt also nichts zu finden. Wie oft wird\ntrotzdem etwas gefunden?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanzahl <- 1:100\nrate <- 1 - (1 - 0.05)^anzahl\n\npar(mar = c(4, 4, 3, 1))\nplot(anzahl, rate, type = \"l\", lwd = 2, col = \"steelblue\", ylim = c(0, 1),\n     xlab = \"Anzahl Tests\", ylab = \"Wahrscheinlichkeit\",\n     main = \"Mindestens ein falscher Alarm\")\nabline(h = 0.05, lty = 2, col = \"firebrick\")\nabline(v = c(5, 10, 20), lty = 3, col = \"grey60\")\n\nround(data.frame(tests = c(1, 3, 5, 10, 20, 50, 100),\n                 rate = 1 - 0.95^c(1, 3, 5, 10, 20, 50, 100)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  tests   rate\n1     1 0.0500\n2     3 0.1426\n3     5 0.2262\n4    10 0.4013\n5    20 0.6415\n6    50 0.9231\n7   100 0.9941\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 1: Wahrscheinlichkeit mindestens eines falschen Alarms.](multiples-testen_files/figure-html/fig-b1-mt-r-1.png){#fig-b1-mt-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nanzahl = np.arange(1, 101)\nrate = 1 - 0.95 ** anzahl\n\nfig, achse = plt.subplots(figsize=(7, 3.4))\nachse.plot(anzahl, rate, color=\"steelblue\", linewidth=2)\nachse.axhline(0.05, linestyle=\"--\", color=\"firebrick\")\nfor x in (5, 10, 20):\n    achse.axvline(x, linestyle=\":\", color=\"0.6\")\nachse.set_xlabel(\"Anzahl Tests\")\nachse.set_ylabel(\"Wahrscheinlichkeit\")\nachse.set_ylim(0, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(0.0, 1.0)\n```\n\n\n:::\n\n```{.python .cell-code}\nachse.set_title(\"Mindestens ein falscher Alarm\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Kurve in Python.](multiples-testen_files/figure-html/fig-b1-mt-py-1.png){#fig-b1-mt-py width=100%}\n:::\n\n```{.python .cell-code}\nfor m in (1, 3, 5, 10, 20, 50, 100):\n    print(f\"{m:4d} Tests: {1 - 0.95 ** m:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   1 Tests: 0.0500\n   3 Tests: 0.1426\n   5 Tests: 0.2262\n  10 Tests: 0.4013\n  20 Tests: 0.6415\n  50 Tests: 0.9231\n 100 Tests: 0.9941\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Anzahl Tests | Wahrscheinlichkeit | Wie das zu lesen ist |\n|---|---|---|\n| 1 | 0.050 | Das versprochene Niveau. |\n| 3 | 0.143 | Schon drei paarweise Vergleiche nach einer Varianzanalyse verdreifachen die Rate fast. |\n| 5 | 0.226 | |\n| 10 | 0.401 | In vier von zehn Auswertungen mit zehn Tests steht mindestens ein falscher Befund. |\n| 20 | 0.642 | Der falsche Alarm ist jetzt wahrscheinlicher als kein falscher Alarm. |\n| 50 | 0.923 | |\n| 100 | 0.994 | Praktisch sicher. |\n\nDie Kurve steigt anfangs steil und flacht dann ab; die entscheidenden Schritte\npassieren zwischen einem und zwanzig Tests, also genau in dem Bereich, in dem\nsich die meisten Auswertungen bewegen.\n\n#### Interpretation\n\nDie Zahlen gelten unter der Annahme unabhängiger Tests. Bei abhängigen Tests,\netwa mehreren Zielgrössen, die miteinander korrelieren, fällt die Rate etwas\nniedriger aus. Kleiner als das Einzelniveau wird sie aber nie, und die\nGrössenordnung bleibt.\n\nWichtig ist die Umkehrung: Wenn in einer Auswertung mit zwanzig Tests genau ein\nErgebnis knapp signifikant ist, dann ist das **kein** Befund, sondern die\nErwartung.\n\n### Beispiel 2: Drei Korrekturen im Vergleich\n\n#### Frage und Datenlage\n\nZwölf p-Werte aus einer Auswertung. Sechs liegen unter 0.05, davon einer sehr\ndeutlich. Die Frage lautet: Was bleibt nach einer Korrektur übrig?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvergleich <- data.frame(\n  p = p_werte,\n  bonferroni = p.adjust(p_werte, method = \"bonferroni\"),\n  holm = p.adjust(p_werte, method = \"holm\"),\n  BH = p.adjust(p_werte, method = \"BH\")\n)\nround(vergleich, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        p bonferroni   holm     BH\n1  0.0001     0.0012 0.0012 0.0012\n2  0.0080     0.0960 0.0880 0.0480\n3  0.0190     0.2280 0.1900 0.0690\n4  0.0230     0.2760 0.2070 0.0690\n5  0.0410     0.4920 0.3280 0.0960\n6  0.0480     0.5760 0.3360 0.0960\n7  0.1100     1.0000 0.6600 0.1886\n8  0.2600     1.0000 1.0000 0.3900\n9  0.3400     1.0000 1.0000 0.4533\n10 0.5100     1.0000 1.0000 0.6120\n11 0.6800     1.0000 1.0000 0.7418\n12 0.9200     1.0000 1.0000 0.9200\n```\n\n\n:::\n\n```{.r .cell-code}\ncolSums(vergleich < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         p bonferroni       holm         BH \n         6          1          1          2 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nvergleich = pd.DataFrame({\"p\": p_werte})\nfor methode, name in [(\"bonferroni\", \"bonferroni\"), (\"holm\", \"holm\"),\n                      (\"fdr_bh\", \"BH\")]:\n    vergleich[name] = multipletests(p_werte, alpha=0.05, method=methode)[1]\nprint(vergleich.round(4).to_string())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         p  bonferroni    holm      BH\n0   0.0001      0.0012  0.0012  0.0012\n1   0.0080      0.0960  0.0880  0.0480\n2   0.0190      0.2280  0.1900  0.0690\n3   0.0230      0.2760  0.2070  0.0690\n4   0.0410      0.4920  0.3280  0.0960\n5   0.0480      0.5760  0.3360  0.0960\n6   0.1100      1.0000  0.6600  0.1886\n7   0.2600      1.0000  1.0000  0.3900\n8   0.3400      1.0000  1.0000  0.4533\n9   0.5100      1.0000  1.0000  0.6120\n10  0.6800      1.0000  1.0000  0.7418\n11  0.9200      1.0000  1.0000  0.9200\n```\n\n\n:::\n\n```{.python .cell-code}\nprint((vergleich < 0.05).sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np             6\nbonferroni    1\nholm          1\nBH            2\ndtype: int64\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| p | Bonferroni | Holm | Benjamini-Hochberg |\n|---|---|---|---|\n| 0.0001 | **0.0012** | **0.0012** | **0.0012** |\n| 0.0080 | 0.0960 | 0.0880 | **0.0480** |\n| 0.0190 | 0.2280 | 0.1900 | 0.0690 |\n| 0.0230 | 0.2760 | 0.2070 | 0.0690 |\n| 0.0410 | 0.4920 | 0.3280 | 0.0960 |\n| 0.0480 | 0.5760 | 0.3360 | 0.0960 |\n| 0.1100 | 1.0000 | 0.6600 | 0.1886 |\n| 0.2600 | 1.0000 | 1.0000 | 0.3900 |\n| … | | | |\n| **verworfen bei 0.05** | **1** | **1** | **2** |\n\nOhne Korrektur wären sechs Hypothesen verworfen worden. Nach Bonferroni und Holm\nbleibt eine übrig, nach Benjamini-Hochberg zwei.\n\nDrei Beobachtungen zu den Zahlen:\n\n**Bonferroni multipliziert einfach mit 12.** Aus 0.008 wird 0.096, aus 0.0001\nwird 0.0012. Werte über 1 werden auf 1 gekappt.\n\n**Holm ist nie strenger als Bonferroni.** In der ersten Zeile sind beide gleich\n(0.0012), ab der zweiten liegt Holm darunter: 0.088 gegen 0.096, 0.190 gegen\n0.228, und mit wachsendem Rang wird der Abstand grösser. Der Grund ist der\nkleiner werdende Divisor.\n\n**Benjamini-Hochberg ist deutlich grosszügiger.** Der Wert 0.008 wird zu 0.048\nund bleibt damit knapp signifikant, während er bei den FWER-Verfahren\nausscheidet. Das ist kein Fehler, sondern das andere Versprechen: BH garantiert\nnicht, dass unter den beiden Funden kein falscher ist, sondern dass im Mittel\nhöchstens 5 Prozent der Funde falsch sind.\n\n::: {.note-box}\n**Korrigierte p-Werte sind eine Bequemlichkeit, keine echten p-Werte.** Sie\nwerden so umgerechnet, dass man sie weiterhin gegen 0.05 halten kann. Ein\n\"korrigierter p-Wert von 0.048\" bedeutet nicht, dass die Wahrscheinlichkeit für\ndiese Daten 4.8 Prozent beträgt, sondern nur: Bei einem FDR-Niveau von 0.048\noder mehr wäre diese Hypothese verworfen worden.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Von zwölf Tests waren sechs bei einem unkorrigierten Niveau von 0.05\n> signifikant. Nach Holm-Korrektur bleibt einer (p korrigiert = 0.0012), nach\n> Benjamini-Hochberg bleiben zwei (0.0012 und 0.0480). Berichtet wird die\n> Holm-Korrektur, da ein einzelner falscher Befund die Folgeentscheidung\n> tragen würde.\n\n### Beispiel 3: Holm Schritt für Schritt\n\n#### Frage und Datenlage\n\nDas Holm-Verfahren wird oft als Zauberkasten verwendet. Es ist aber in vier\nZeilen nachvollziehbar, und wer es einmal von Hand durchgeht, versteht auch,\nwarum es an einer Stelle abbricht.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm <- length(p_werte)\nsortiert <- sort(p_werte)\n\nschritte <- data.frame(\n  rang = 1:m,\n  p = sortiert,\n  divisor = m:1,\n  schwelle = 0.05 / (m:1)\n)\nschritte$unter_schwelle <- schritte$p < schritte$schwelle\nround(schritte, 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   rang      p divisor schwelle unter_schwelle\n1     1 0.0001      12  0.00417              1\n2     2 0.0080      11  0.00455              0\n3     3 0.0190      10  0.00500              0\n4     4 0.0230       9  0.00556              0\n5     5 0.0410       8  0.00625              0\n6     6 0.0480       7  0.00714              0\n7     7 0.1100       6  0.00833              0\n8     8 0.2600       5  0.01000              0\n9     9 0.3400       4  0.01250              0\n10   10 0.5100       3  0.01667              0\n11   11 0.6800       2  0.02500              0\n12   12 0.9200       1  0.05000              0\n```\n\n\n:::\n\n```{.r .cell-code}\n# Das Verfahren stoppt beim ersten FALSE; alles danach bleibt stehen\nerster_stopp <- which(!schritte$unter_schwelle)[1]\ncat(\"Verworfen werden die Raenge 1 bis\", erster_stopp - 1, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVerworfen werden die Raenge 1 bis 1 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nm = len(p_werte)\nsortiert = np.sort(p_werte)\n\nschritte = pd.DataFrame({\n    \"rang\": np.arange(1, m + 1),\n    \"p\": sortiert,\n    \"divisor\": np.arange(m, 0, -1),\n    \"schwelle\": 0.05 / np.arange(m, 0, -1),\n})\nschritte[\"unter_schwelle\"] = schritte[\"p\"] < schritte[\"schwelle\"]\nprint(schritte.round(5).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n rang      p  divisor  schwelle  unter_schwelle\n    1 0.0001       12   0.00417            True\n    2 0.0080       11   0.00455           False\n    3 0.0190       10   0.00500           False\n    4 0.0230        9   0.00556           False\n    5 0.0410        8   0.00625           False\n    6 0.0480        7   0.00714           False\n    7 0.1100        6   0.00833           False\n    8 0.2600        5   0.01000           False\n    9 0.3400        4   0.01250           False\n   10 0.5100        3   0.01667           False\n   11 0.6800        2   0.02500           False\n   12 0.9200        1   0.05000           False\n```\n\n\n:::\n\n```{.python .cell-code}\nerster_stopp = int(np.argmin(schritte[\"unter_schwelle\"].to_numpy()))\nprint(\"Verworfen werden die Ränge 1 bis\", erster_stopp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVerworfen werden die Ränge 1 bis 1\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Rang | p | Divisor | Schwelle | unter Schwelle? |\n|---|---|---|---|---|\n| 1 | 0.0001 | 12 | 0.00417 | **ja** |\n| 2 | 0.0080 | 11 | 0.00455 | **nein, STOPP** |\n| 3 | 0.0190 | 10 | 0.00500 | (wird nicht mehr geprüft) |\n| 4 | 0.0230 | 9 | 0.00556 | |\n\nDas Verfahren geht die sortierten p-Werte von unten durch und vergleicht jeden\nmit einer Schwelle, die von Rang zu Rang **steigt**: erst $\\alpha/12$, dann\n$\\alpha/11$ und so weiter. Beim ersten Wert, der seine Schwelle nicht\nunterschreitet, hört es auf, und alle folgenden bleiben unverworfen, auch\nsolche, die ihre eigene Schwelle unterschritten hätten.\n\nDer zweite p-Wert ist mit 0.0080 knapp über seiner Schwelle von 0.00455. Läge er\nbei 0.004, wären beide verworfen, und der dritte Rang käme gegen 0.005 an die\nReihe.\n\n::: {.note-box}\n**Warum das Abbrechen nötig ist.** Ohne die Stoppregel wäre das Verfahren keine\ngültige FWER-Kontrolle mehr. Die steigenden Schwellen sind nur deshalb zulässig,\nweil ein Rang erst geprüft wird, wenn alle kleineren verworfen wurden. Wer die\nSchwellen einzeln anwendet und die Stoppregel weglässt, hält das Niveau nicht\nein.\n:::\n\n#### Interpretation\n\nDas Nachvollziehen lohnt sich, weil es zwei verbreitete Missverständnisse\nausräumt. Erstens ist Holm **kein** Verfahren, das jeden p-Wert einzeln\numrechnet; die Reihenfolge ist wesentlich. Zweitens erklärt es, warum das\nErgebnis eines einzelnen Tests davon abhängt, welche **anderen** Tests\nmitgerechnet wurden, was zunächst befremdlich wirkt und der Kern der ganzen\nSache ist.\n\n### Beispiel 4: Was die Korrektur kostet\n\n#### Frage und Datenlage\n\nKorrekturen sind nicht umsonst. Wie viel Power geht verloren?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(pwr)\n\nfor (m in c(1, 5, 10, 20)) {\n  alpha <- 0.05 / m\n  p <- pwr.t.test(n = 64, d = 0.5, sig.level = alpha)$power\n  n_noetig <- pwr.t.test(d = 0.5, power = 0.80, sig.level = alpha)$n\n  cat(sprintf(\"%2d Tests: alpha = %.4f  Power bei n = 64: %.4f  n fuer Power 0.80: %6.2f\\n\",\n              m, alpha, p, n_noetig))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 1 Tests: alpha = 0.0500  Power bei n = 64: 0.8015  n fuer Power 0.80:  63.77\n 5 Tests: alpha = 0.0100  Power bei n = 64: 0.5853  n fuer Power 0.80:  95.10\n10 Tests: alpha = 0.0050  Power bei n = 64: 0.4909  n fuer Power 0.80: 108.48\n20 Tests: alpha = 0.0025  Power bei n = 64: 0.4028  n fuer Power 0.80: 121.80\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nanalyse = TTestIndPower()\n\nfor m in (1, 5, 10, 20):\n    alpha = 0.05 / m\n    power = analyse.power(effect_size=0.5, nobs1=64, alpha=alpha)\n    n_noetig = analyse.solve_power(effect_size=0.5, power=0.80, alpha=alpha,\n                                   ratio=1.0)\n    print(f\"{m:2d} Tests: alpha = {alpha:.4f}  Power bei n = 64: {power:.4f}\"\n          f\"  n für Power 0.80: {n_noetig:6.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 1 Tests: alpha = 0.0500  Power bei n = 64: 0.8015  n für Power 0.80:  63.77\n 5 Tests: alpha = 0.0100  Power bei n = 64: 0.5853  n für Power 0.80:  95.10\n10 Tests: alpha = 0.0050  Power bei n = 64: 0.4909  n für Power 0.80: 108.48\n20 Tests: alpha = 0.0025  Power bei n = 64: 0.4028  n für Power 0.80: 121.80\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Anzahl Tests | Schwelle | Power bei n = 64 je Gruppe | nötiges n für Power 0.80 |\n|---|---|---|---|\n| 1 | 0.0500 | 0.80 | 63.77 |\n| 5 | 0.0100 | 0.59 | 95.10 |\n| 10 | 0.0050 | 0.49 | 108.48 |\n| 20 | 0.0025 | 0.40 | 121.80 |\n\nWer denselben Versuch mit zwanzig statt einem Test auswertet, halbiert die Power\nund bräuchte fast doppelt so viele Fälle, um sie zurückzugewinnen.\n\n#### Interpretation und Ergebnissatz\n\nDaraus folgt die praktisch wichtigste Konsequenz dieser Seite, und sie ist keine\nRechenregel: **Die Zahl der Tests gehört vor der Auswertung festgelegt und klein\ngehalten.**\n\n| Vorgehen | Wirkung |\n|---|---|\n| Eine Hauptfragestellung vorab benennen | Der Haupttest bleibt unkorrigiert, alles Weitere ist ausdrücklich explorativ |\n| Zielgrössen zusammenfassen | Ein Gesamtmass statt fünf Einzelmasse ergibt einen Test statt fünf |\n| Gemeinsamen Test statt vieler Einzeltests | [Varianzanalyse](../tests/anova.qmd) statt paarweiser Vergleiche, gemeinsamer F-Test statt einzelner t-Tests |\n| Explorative Funde als solche kennzeichnen | Sie brauchen dann keine Korrektur, aber auch keine Signifikanzaussage |\n\nDer letzte Punkt ist der ehrlichste Ausweg. Ein exploratives Ergebnis darf\nberichtet werden, wenn dazugesagt wird, dass es aus einer ungeplanten Suche\nstammt und in einer neuen Erhebung zu prüfen ist.\n\n> Vorab festgelegt war eine Hauptfragestellung; die übrigen elf Vergleiche sind\n> explorativ. Für die Hauptfrage wurde ohne Korrektur auf dem 5-Prozent-Niveau\n> geprüft. Die explorativen Vergleiche sind nach Benjamini-Hochberg korrigiert\n> und als vorläufig gekennzeichnet.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nNach einer Varianzanalyse mit fünf Gruppen werden alle Paare verglichen. Wie\nviele Tests sind das, und wie hoch ist die Fehlerrate ohne Korrektur?\n\n- [x] Zehn Tests, rund 40 Prozent ~ Richtig. Bei fünf Gruppen gibt es\n      5·4/2 = 10 Paare. Ohne Korrektur liegt die Wahrscheinlichkeit für\n      mindestens einen falschen Alarm bei 1 - 0.95¹⁰ = 0.40.\n- [ ] Fünf Tests, rund 23 Prozent ~ Fünf Gruppen ergeben zehn Paare, nicht fünf.\n- [ ] Zehn Tests, weiterhin 5 Prozent ~ Die 5 Prozent gelten je Einzeltest, nicht\n      für die Gruppe von Tests.\n:::\n\n::: {.quiz}\nWarum sollte Holm gegenüber Bonferroni bevorzugt werden?\n\n- [x] Es hält dasselbe Niveau ein und verwirft nie weniger ~ Richtig. Holm ist\n      in jeder Lage mindestens so scharf wie Bonferroni und oft schärfer, bei\n      identischer Kontrolle der familienweisen Fehlerrate. Ein statistischer\n      Grund für Bonferroni existiert nicht.\n- [ ] Es ist weniger streng und findet deshalb mehr ~ Weniger streng im Sinne\n      eines schwächeren Versprechens ist es gerade nicht; das Versprechen ist\n      dasselbe.\n- [ ] Es kontrolliert die FDR statt der FWER ~ Das ist Benjamini-Hochberg.\n:::\n\n::: {.quiz}\nBenjamini-Hochberg auf 5 Prozent liefert zwanzig Funde. Was bedeutet das?\n\n- [x] Im Mittel ist etwa einer davon falsch ~ Richtig. Die FDR kontrolliert den\n      erwarteten Anteil falscher Befunde unter den Funden: 5 Prozent von zwanzig\n      ist einer. Das ist ein anderes Versprechen als \"mit 95 Prozent\n      Wahrscheinlichkeit ist keiner falsch\".\n- [ ] Mit 95 Prozent Wahrscheinlichkeit ist keiner falsch ~ Das wäre eine\n      FWER-Kontrolle, wie sie Bonferroni und Holm leisten.\n- [ ] Alle zwanzig sind mit 95 Prozent Wahrscheinlichkeit richtig ~ Die FDR sagt\n      nichts über einzelne Funde.\n:::\n\n::: {.quiz}\nEine Auswertung mit zwanzig Tests liefert genau ein knapp signifikantes\nErgebnis (p = 0.04). Wie ist das zu bewerten?\n\n- [x] Als Erwartungswert, nicht als Befund ~ Richtig. Bei zwanzig Tests unter\n      lauter wahren Nullhypothesen wird im Mittel einer signifikant. Ein\n      einzelnes knappes Ergebnis unter vielen Tests ist genau das, was der\n      Zufall liefert.\n- [ ] Als Befund, p liegt unter 0.05 ~ Die Schwelle 0.05 gilt für einen einzelnen\n      vorab festgelegten Test.\n- [ ] Als Befund, wenn er inhaltlich plausibel ist ~ Nachträgliche Plausibilität\n      ist kein Ersatz für eine vorab formulierte Hypothese; sie findet sich fast\n      immer.\n:::\n\n## Verlinkte Ressourcen\n\n- [R-Dokumentation zu `p.adjust`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/p.adjust.html)\n- [statsmodels: multipletests](https://www.statsmodels.org/stable/generated/statsmodels.stats.multitest.multipletests.html)\n- [Power und Stichprobenumfang](power-stichprobenumfang.qmd)\n",
    "supporting": [
      "multiples-testen_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}