{
  "hash": "9911b238658d48b9ce7ad6a9e65af012",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Klassifikationsgüte\"\ndescription: \"Konfusionsmatrix, Sensitivität, ROC und AUC richtig lesen.\"\ncategories: [\"Regression\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: methode\nstand: entwurf\norder: 50\n---\n\n\n\n\n\nAlle Beispiele rechnen mit deterministisch konstruierten Daten, damit R und\nPython dieselben Zahlen sehen. Die Hilfsfunktionen `auc()` und `guete()` stehen\nim Setup-Chunk und sind in beiden Sprachen gleich aufgebaut.\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Wie gut trennt ein Modell zwei Klassen, und wie gut ist es für eine konkrete Entscheidung? |\n| Eingang | vorhergesagte Wahrscheinlichkeiten oder Scores und die tatsächliche Klasse |\n| Was die Bewertung liefert | Konfusionsmatrix, daraus Sensitivität, Spezifität, PPV, NPV, F1; schwellenunabhängig ROC-Kurve und AUC |\n| R-Funktionen | `table()` für die Matrix; AUC über die Rangsumme oder das Paket `pROC` |\n| Python-Funktionen | `sklearn.metrics` mit `confusion_matrix`, `roc_curve`, `roc_auc_score` |\n| Verwandte Methoden | [logistische Regression](logistische-regression.qmd), [Modellauswahl](modellauswahl.qmd) |\n\n## Wann diese Methode, wann nicht\n\nImmer dann, wenn ein Modell eine binäre Zielgrösse vorhersagt und die\nVorhersagen zu einer Entscheidung führen sollen. Die Bewertung zerfällt in zwei\ngetrennte Fragen, die oft vermischt werden:\n\n| Frage | Womit beantwortet | Hängt von der Schwelle ab? |\n|---|---|---|\n| Wie gut trennt das Modell überhaupt? | ROC-Kurve, AUC | nein |\n| Wie gut ist die Entscheidung bei dieser Schwelle? | Konfusionsmatrix und alles daraus | ja |\n\nEin Modell mit hoher AUC kann bei einer schlecht gewählten Schwelle\nunbrauchbare Entscheidungen liefern, und umgekehrt sagt eine gute\nKonfusionsmatrix nichts darüber, ob eine andere Schwelle besser wäre.\n\n| Situation | Stattdessen |\n|---|---|\n| Zielgrösse metrisch | Residualstreuung und R², siehe [multiple lineare Regression](multiple-lineare-regression.qmd) |\n| Mehr als zwei Klassen | Konfusionsmatrix je Klasse, makro- oder mikrogemittelte Kennzahlen |\n| Es geht um die Auswahl zwischen Modellen | [Modellauswahl](modellauswahl.qmd), zusätzlich zu diesen Kennzahlen |\n| Die Wahrscheinlichkeiten selbst sollen stimmen | Kalibrierung prüfen, nicht nur die Trennschärfe |\n\n## Grundidee und Modell\n\nAus einer Schwelle und den vorhergesagten Wahrscheinlichkeiten entstehen vier\nZahlen:\n\n| | tatsächlich 1 | tatsächlich 0 |\n|---|---|---|\n| **vorhergesagt 1** | richtig positiv (TP) | falsch positiv (FP) |\n| **vorhergesagt 0** | falsch negativ (FN) | richtig negativ (TN) |\n\nAlle Kennzahlen sind Verhältnisse aus diesen vier Zahlen. Entscheidend ist,\n**in welche Richtung** geteilt wird:\n\n| Kennzahl | Formel | Frage, die sie beantwortet |\n|---|---|---|\n| Genauigkeit | $(TP+TN)/n$ | Wie viele Fälle wurden richtig eingeordnet? |\n| Sensitivität, Recall | $TP/(TP+FN)$ | Von den tatsächlichen Ereignissen: wie viele wurden gefunden? |\n| Spezifität | $TN/(TN+FP)$ | Von den tatsächlichen Nicht-Ereignissen: wie viele wurden richtig durchgelassen? |\n| PPV, Precision | $TP/(TP+FP)$ | Von den Alarmen: wie viele waren echt? |\n| NPV | $TN/(TN+FN)$ | Von den Entwarnungen: wie viele waren richtig? |\n| F1 | harmonisches Mittel aus PPV und Sensitivität | ein Kompromiss zwischen Finden und Treffen |\n\n::: {.note-box}\n**Sensitivität und PPV sehen ähnlich aus und verhalten sich völlig verschieden.**\nSensitivität teilt durch die tatsächlichen Ereignisse, PPV durch die Alarme. Die\nSensitivität ist deshalb von der Häufigkeit des Ereignisses unabhängig, der PPV\nnicht. Bei seltenen Ereignissen bricht der PPV ein, obwohl Sensitivität und\nSpezifität unverändert gut bleiben. Das ist der Inhalt von Beispiel 2 und der\nhäufigste Fehlschluss in diesem Gebiet.\n:::\n\nDie ROC-Kurve entsteht, indem die Schwelle von 1 bis 0 durchlaufen wird und für\njede Sensitivität gegen 1 minus Spezifität aufgetragen wird. Die Fläche\ndarunter, die AUC, hat eine anschauliche Bedeutung: **Sie ist die\nWahrscheinlichkeit, dass ein zufällig gewählter positiver Fall einen höheren\nScore bekommt als ein zufällig gewählter negativer.** Bei 0.5 ist das Modell so\ngut wie Münzwurf, bei 1.0 trennt es perfekt.\n\nDaraus folgt auch, wie sich die AUC ohne Zusatzpaket berechnen lässt: Sie ist\ndie Mann-Whitney-U-Statistik geteilt durch die Anzahl aller Paarvergleiche,\nsiehe [nichtparametrische Tests](../tests/nichtparametrische-tests.qmd).\n\n## Output lesen\n\n| Kennzahl | Anhaltspunkt | Falle |\n|---|---|---|\n| Genauigkeit | keiner, sie hängt an der Klassenverteilung | Bei 2 Prozent Ereignisanteil erreicht \"immer nein\" 98 Prozent |\n| Sensitivität | je nach Anwendung | steigt immer, wenn die Schwelle sinkt |\n| Spezifität | je nach Anwendung | steigt immer, wenn die Schwelle steigt |\n| PPV | hängt an der Häufigkeit des Ereignisses | nicht zwischen Studien mit verschiedener Häufigkeit vergleichbar |\n| F1 | für unausgewogene Klassen brauchbarer als Genauigkeit | ignoriert die richtig negativen Fälle vollständig |\n| AUC | 0.5 ist Zufall, 0.7 bis 0.8 brauchbar, über 0.9 sehr gut | sagt nichts über die Kalibrierung und nichts über eine konkrete Schwelle |\n\n## Interpretationsfallen\n\n- **Genauigkeit ist bei seltenen Ereignissen wertlos.** Sie wird von der\n  häufigen Klasse dominiert.\n- **PPV lässt sich nicht zwischen Anwendungen vergleichen.** Er hängt an der\n  Häufigkeit des Ereignisses, nicht nur an der Güte des Modells.\n- **Eine hohe AUC bedeutet nicht, dass die Wahrscheinlichkeiten stimmen.** Ein\n  Modell kann perfekt trennen und trotzdem durchweg zu hohe Werte ausgeben.\n  Trennschärfe und Kalibrierung sind zwei Eigenschaften.\n- **Sensitivität und Spezifität lassen sich nicht gleichzeitig maximieren.**\n  Jede Schwellenverschiebung tauscht das eine gegen das andere.\n- **An denselben Daten gemessen sind alle Kennzahlen zu gut**, siehe\n  Beispiel 4.\n- **Die Schwelle 0.5 ist eine Konvention.** Sie unterstellt gleich teure\n  Fehler.\n- **F1 ignoriert die richtig negativen Fälle.** Bei Anwendungen, in denen\n  korrekte Entwarnungen zählen, ist er das falsche Mass.\n\n## Ergebnis berichten\n\nVorlage:\n\n> Bei einer Schwelle von [Wert] erkennt das Modell [TP] der [TP+FN] Ereignisse\n> (Sensitivität [Wert]) und stuft [FP] der [FP+TN] Nicht-Ereignisse falsch ein\n> (Spezifität [Wert]). Von [TP+FP] Alarmen sind [TP] echt (PPV [Wert]). Die\n> AUC beträgt [Wert], gemessen auf [Trainings- oder Testdaten].\n\nImmer genannt werden: die Schwelle, die absolute Konfusionsmatrix, mindestens\nSensitivität und PPV, die AUC, und **auf welchen Daten** gemessen wurde. Der\nletzte Punkt fehlt am häufigsten und entwertet die Angabe, wenn er fehlt.\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese zusätzlich |\n|---|---|\n| [Logistische Regression](logistische-regression.qmd) | dort entstehen die Wahrscheinlichkeiten, die hier bewertet werden |\n| [Modellauswahl](modellauswahl.qmd) | die Wahl zwischen Modellen, nicht die Bewertung eines einzelnen |\n| [Chi-Quadrat-Tests](../tests/chi-quadrat-tests.qmd) | die Konfusionsmatrix ist eine Kreuztabelle, aber die Fragestellung ist eine andere |\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Die Konfusionsmatrix und was daraus folgt\n\n#### Frage und Datenlage\n\n400 Fälle, davon 200 mit Ereignis. Ein Modell sagt aus einem Merkmal die\nWahrscheinlichkeit vorher. Bei der üblichen Schwelle von 0.5 entsteht die\nKonfusionsmatrix.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodell <- glm(ereignis ~ merkmal, family = binomial, data = daten)\nscore <- predict(modell, type = \"response\")\n\nvorhersage <- as.integer(score > 0.5)\ntable(tatsaechlich = daten$ereignis, vorhergesagt = vorhersage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            vorhergesagt\ntatsaechlich   0   1\n           0 144  56\n           1  57 143\n```\n\n\n:::\n\n```{.r .cell-code}\nguete(daten$ereignis, vorhersage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           TP            FP            FN            TN   Genauigkeit \n     143.0000       56.0000       57.0000      144.0000        0.7175 \nSensitivitaet   Spezifitaet           PPV           NPV            F1 \n       0.7150        0.7200        0.7186        0.7164        0.7168 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(auc(daten$ereignis, score), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8004\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmodell = smf.logit(\"ereignis ~ merkmal\", data=daten).fit(disp=0)\nscore = modell.predict(daten)\n\nvorhersage = (score > 0.5).astype(int)\nprint(pd.crosstab(daten[\"ereignis\"], vorhersage,\n                  rownames=[\"tatsächlich\"], colnames=[\"vorhergesagt\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nvorhergesagt    0    1\ntatsächlich           \n0             144   56\n1              57  143\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(guete(daten[\"ereignis\"], vorhersage))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTP               143.0000\nFP                56.0000\nFN                57.0000\nTN               144.0000\nGenauigkeit        0.7175\nSensitivitaet      0.7150\nSpezifitaet        0.7200\nPPV                0.7186\nNPV                0.7164\nF1                 0.7168\ndtype: float64\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"AUC =\", round(auc(daten[\"ereignis\"], score), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAUC = 0.8004\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| | vorhergesagt 0 | vorhergesagt 1 |\n|---|---|---|\n| **tatsächlich 0** | 144 (TN) | 56 (FP) |\n| **tatsächlich 1** | 57 (FN) | 143 (TP) |\n\n| Kennzahl | Wert hier | Rechnung | Wie er zu lesen ist |\n|---|---|---|---|\n| Genauigkeit | 0.7175 | (143+144)/400 | Rund 72 Prozent aller Fälle richtig eingeordnet. Hier aussagekräftig, weil beide Klassen gleich häufig sind; in Beispiel 2 ist sie es nicht. |\n| Sensitivität | 0.7150 | 143/200 | Von den 200 tatsächlichen Ereignissen wurden 143 gefunden, 57 übersehen. |\n| Spezifität | 0.7200 | 144/200 | Von den 200 Nicht-Ereignissen wurden 144 richtig durchgelassen, 56 fälschlich alarmiert. |\n| PPV | 0.7186 | 143/199 | Von den 199 Alarmen waren 143 echt. |\n| NPV | 0.7164 | 144/201 | Von den 201 Entwarnungen waren 144 richtig. |\n| F1 | 0.7168 | harmonisches Mittel aus PPV und Sensitivität | Fasst Finden und Treffen zusammen, ignoriert aber die 144 richtigen Entwarnungen. |\n| AUC | 0.8004 | Rangsumme der positiven Fälle | Greift man je einen zufälligen positiven und negativen Fall heraus, hat der positive in 80 Prozent der Fälle den höheren Score. |\n\nDass hier alle fünf Verhältniszahlen um 0.72 liegen, ist kein Zufall, sondern\neine Folge der ausgewogenen Klassen: Bei gleich vielen Ereignissen und\nNicht-Ereignissen fallen Sensitivität und PPV zusammen. Beispiel 2 zeigt, was\npassiert, wenn das nicht so ist.\n\n#### Interpretation und Ergebnissatz\n\n> Bei einer Schwelle von 0.5 erkennt das Modell 143 der 200 Ereignisse\n> (Sensitivität 0.72) und stuft 56 der 200 Nicht-Ereignisse falsch ein\n> (Spezifität 0.72). Von 199 Alarmen sind 143 echt (PPV 0.72). Die AUC beträgt\n> 0.80, gemessen auf den Schätzdaten.\n\n### Beispiel 2: Wenn das Ereignis selten ist\n\n#### Frage und Datenlage\n\n2000 Fälle, davon 40 mit Ereignis, also 2 Prozent. Ein Prüfverfahren erkennt 90\nProzent der Ereignisse (Sensitivität 0.90) und lässt 90 Prozent der\nNicht-Ereignisse richtig durch (Spezifität 0.90). Beide Werte gelten\ngemeinhin als gut.\n\nDie Frage lautet: Wenn das Verfahren Alarm schlägt, wie wahrscheinlich ist das\nEreignis dann tatsächlich?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn2 <- 2000\nlauf2 <- 0:(n2 - 1)\nselten <- as.integer(((lauf2 * 501) %% n2) < 40)     # genau 40 Ereignisse\n\npositiv <- which(selten == 1)\nnegativ <- which(selten == 0)\n\npruefung <- integer(n2)\npruefung[positiv[1:36]] <- 1                          # 36 von 40 erkannt\npruefung[negativ[seq(1, length(negativ), by = 10)][1:196]] <- 1\n\ntable(tatsaechlich = selten, alarm = pruefung)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            alarm\ntatsaechlich    0    1\n           0 1764  196\n           1    4   36\n```\n\n\n:::\n\n```{.r .cell-code}\nguete(selten, pruefung)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           TP            FP            FN            TN   Genauigkeit \n      36.0000      196.0000        4.0000     1764.0000        0.9000 \nSensitivitaet   Spezifitaet           PPV           NPV            F1 \n       0.9000        0.9000        0.1552        0.9977        0.2647 \n```\n\n\n:::\n\n```{.r .cell-code}\nguete(selten, integer(n2))                            # \"immer nein\"\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           TP            FP            FN            TN   Genauigkeit \n         0.00          0.00         40.00       1960.00          0.98 \nSensitivitaet   Spezifitaet           PPV           NPV            F1 \n         0.00          1.00           NaN          0.98           NaN \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nn2 = 2000\nlauf2 = np.arange(n2)\nselten = (((lauf2 * 501) % n2) < 40).astype(int)\n\npositiv = np.where(selten == 1)[0]\nnegativ = np.where(selten == 0)[0]\n\npruefung = np.zeros(n2, dtype=int)\npruefung[positiv[:36]] = 1\npruefung[negativ[::10][:196]] = 1\n\nprint(pd.crosstab(selten, pruefung,\n                  rownames=[\"tatsächlich\"], colnames=[\"alarm\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nalarm           0    1\ntatsächlich           \n0            1764  196\n1               4   36\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(guete(selten, pruefung))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTP                 36.0000\nFP                196.0000\nFN                  4.0000\nTN               1764.0000\nGenauigkeit         0.9000\nSensitivitaet       0.9000\nSpezifitaet         0.9000\nPPV                 0.1552\nNPV                 0.9977\nF1                  0.2647\ndtype: float64\n```\n\n\n:::\n\n```{.python .cell-code}\nprint()\n```\n\n```{.python .cell-code}\nprint(guete(selten, np.zeros(n2, dtype=int)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTP                  0.00\nFP                  0.00\nFN                 40.00\nTN               1960.00\nGenauigkeit         0.98\nSensitivitaet       0.00\nSpezifitaet         1.00\nPPV                  NaN\nNPV                 0.98\nF1                   NaN\ndtype: float64\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| | kein Alarm | Alarm |\n|---|---|---|\n| **kein Ereignis** | 1764 | 196 |\n| **Ereignis** | 4 | 36 |\n\n| Kennzahl | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Sensitivität | 0.900 | Wie versprochen: 36 der 40 Ereignisse gefunden. |\n| Spezifität | 0.900 | Ebenfalls wie versprochen: 1764 der 1960 richtig durchgelassen. |\n| Genauigkeit | 0.900 | Sieht gut aus und ist wertlos, siehe unten. |\n| **PPV** | **0.155** | **Der eigentliche Befund.** Von 232 Alarmen sind nur 36 echt. In 85 Prozent der Fälle ist der Alarm falsch. |\n| NPV | 0.998 | Eine Entwarnung ist dagegen fast immer richtig. |\n| F1 | 0.265 | Bricht mit dem PPV ein, weil er ihn zur Hälfte enthält. |\n| Genauigkeit bei \"immer nein\" | **0.980** | Wer schlicht nie Alarm schlägt, erreicht 98 Prozent Genauigkeit und damit **mehr** als das Prüfverfahren. |\n\n::: {.note-box}\n**Warum der PPV einbricht, obwohl das Verfahren gut ist.** Die 10 Prozent\nFehlalarme beziehen sich auf 1960 Nicht-Ereignisse und ergeben 196 falsche\nAlarme. Die 90 Prozent Treffer beziehen sich auf 40 Ereignisse und ergeben 36\nechte. Die falschen Alarme kommen aus einer 49-mal grösseren Grundmenge und\nüberwiegen deshalb, obwohl ihre Rate niedriger ist.\n\nDaraus folgt eine Faustregel: **Bei seltenen Ereignissen braucht ein brauchbarer\nPPV eine sehr hohe Spezifität.** Um hier auf einen PPV von 0.5 zu kommen,\nmüsste die Spezifität auf 0.982 steigen, also die Fehlalarmrate von 10 auf 1.8\nProzent fallen.\n:::\n\n#### Interpretation und Ergebnissatz\n\nZwei Konsequenzen für die Praxis. Erstens gehört die Genauigkeit bei\nunausgewogenen Klassen gar nicht erst in den Bericht; sie beschreibt hier nur,\nwie selten das Ereignis ist. Zweitens ist der PPV die Zahl, die für die\nbetroffene Person zählt: Nicht \"das Verfahren erkennt 90 Prozent\", sondern \"wenn\nes anschlägt, liegt es in 85 Prozent der Fälle falsch\".\n\nDeshalb ist ein PPV auch nicht zwischen Anwendungen übertragbar. Dasselbe\nVerfahren, angewendet auf eine Gruppe mit 20 statt 2 Prozent Ereignisanteil,\nkäme auf einen PPV von 0.69.\n\n> Bei einer Häufigkeit von 2 Prozent erkennt das Verfahren 36 der 40 Ereignisse\n> (Sensitivität 0.90) bei 196 Fehlalarmen unter 1960 Nicht-Ereignissen\n> (Spezifität 0.90). Von 232 Alarmen sind 36 echt (PPV 0.155). Die Genauigkeit\n> von 0.90 ist hier nicht aussagekräftig: Ein Verfahren, das nie Alarm schlägt,\n> erreicht 0.98.\n\n### Beispiel 3: ROC-Kurve und die Wahl der Schwelle\n\n#### Frage und Datenlage\n\nDie Daten aus Beispiel 1. Die Frage lautet: Was ändert sich, wenn die Schwelle\nverschoben wird, und wie beurteilt man das Modell unabhängig davon?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschwellen <- sort(unique(c(0, score, 1)), decreasing = TRUE)\npunkte <- t(sapply(schwellen, function(s) {\n  v <- as.integer(score > s)\n  c(fpr = sum(v == 1 & daten$ereignis == 0) / sum(daten$ereignis == 0),\n    tpr = sum(v == 1 & daten$ereignis == 1) / sum(daten$ereignis == 1))\n}))\n\npar(mar = c(4, 4, 3, 1))\nplot(punkte[, \"fpr\"], punkte[, \"tpr\"], type = \"l\", lwd = 2, col = \"steelblue\",\n     xlab = \"1 - Spezifität\", ylab = \"Sensitivität\",\n     main = paste(\"ROC, AUC =\", round(auc(daten$ereignis, score), 3)))\nabline(0, 1, lty = 2, col = \"grey60\")\nfor (s in c(0.2, 0.5, 0.8)) {\n  v <- as.integer(score > s)\n  points(sum(v == 1 & daten$ereignis == 0) / sum(daten$ereignis == 0),\n         sum(v == 1 & daten$ereignis == 1) / sum(daten$ereignis == 1),\n         pch = 16, col = \"firebrick\", cex = 1.3)\n}\n\nfor (s in c(0.2, 0.35, 0.5, 0.65, 0.8)) {\n  cat(\"Schwelle\", s, \":\", \"\\n\")\n  print(guete(daten$ereignis, as.integer(score > s))[c(\"Sensitivitaet\",\n                                                       \"Spezifitaet\",\n                                                       \"PPV\", \"F1\")])\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSchwelle 0.2 : \nSensitivitaet   Spezifitaet           PPV            F1 \n       0.9600        0.2650        0.5664        0.7124 \nSchwelle 0.35 : \nSensitivitaet   Spezifitaet           PPV            F1 \n       0.8700        0.5200        0.6444        0.7404 \nSchwelle 0.5 : \nSensitivitaet   Spezifitaet           PPV            F1 \n       0.7150        0.7200        0.7186        0.7168 \nSchwelle 0.65 : \nSensitivitaet   Spezifitaet           PPV            F1 \n       0.5250        0.8750        0.8077        0.6364 \nSchwelle 0.8 : \nSensitivitaet   Spezifitaet           PPV            F1 \n       0.2700        0.9650        0.8852        0.4138 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: ROC-Kurve mit den drei markierten Schwellen.](klassifikationsguete_files/figure-html/fig-b3-kl-r-1.png){#fig-b3-kl-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nschwellen = np.sort(np.unique(np.concatenate([[0.0], score.to_numpy(), [1.0]])))[::-1]\nfpr, tpr = [], []\ntatsaechlich = daten[\"ereignis\"].to_numpy()\nfor s in schwellen:\n    v = (score.to_numpy() > s).astype(int)\n    fpr.append(((v == 1) & (tatsaechlich == 0)).sum() / (tatsaechlich == 0).sum())\n    tpr.append(((v == 1) & (tatsaechlich == 1)).sum() / (tatsaechlich == 1).sum())\n\nfig, achse = plt.subplots(figsize=(7, 3.6))\nachse.plot(fpr, tpr, color=\"steelblue\", linewidth=2)\nachse.plot([0, 1], [0, 1], linestyle=\"--\", color=\"0.6\")\nfor s in (0.2, 0.5, 0.8):\n    v = (score.to_numpy() > s).astype(int)\n    achse.plot(((v == 1) & (tatsaechlich == 0)).sum() / (tatsaechlich == 0).sum(),\n               ((v == 1) & (tatsaechlich == 1)).sum() / (tatsaechlich == 1).sum(),\n               \"o\", color=\"firebrick\", markersize=7)\nachse.set_xlabel(\"1 - Spezifität\")\nachse.set_ylabel(\"Sensitivität\")\nachse.set_title(f\"ROC, AUC = {auc(daten['ereignis'], score):.3f}\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselbe Kurve in Python.](klassifikationsguete_files/figure-html/fig-b3-kl-py-1.png){#fig-b3-kl-py width=100%}\n:::\n\n```{.python .cell-code}\nfor s in (0.2, 0.35, 0.5, 0.65, 0.8):\n    k = guete(daten[\"ereignis\"], (score > s).astype(int))\n    print(f\"Schwelle {s}: Sens={k['Sensitivitaet']:.4f} \"\n          f\"Spez={k['Spezifitaet']:.4f} PPV={k['PPV']:.4f} F1={k['F1']:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSchwelle 0.2: Sens=0.9600 Spez=0.2650 PPV=0.5664 F1=0.7124\nSchwelle 0.35: Sens=0.8700 Spez=0.5200 PPV=0.6444 F1=0.7404\nSchwelle 0.5: Sens=0.7150 Spez=0.7200 PPV=0.7186 F1=0.7168\nSchwelle 0.65: Sens=0.5250 Spez=0.8750 PPV=0.8077 F1=0.6364\nSchwelle 0.8: Sens=0.2700 Spez=0.9650 PPV=0.8852 F1=0.4138\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Schwelle | Sensitivität | Spezifität | PPV | F1 |\n|---|---|---|---|---|\n| 0.20 | 0.960 | 0.265 | 0.566 | 0.712 |\n| 0.35 | 0.870 | 0.520 | 0.644 | **0.740** |\n| 0.50 | 0.715 | 0.720 | 0.719 | 0.717 |\n| 0.65 | 0.525 | 0.875 | 0.808 | 0.636 |\n| 0.80 | 0.270 | 0.965 | 0.885 | 0.414 |\n\nDrei Beobachtungen:\n\n**Sensitivität und Spezifität bewegen sich gegenläufig.** Von 0.20 auf 0.80\nfällt die Sensitivität von 0.96 auf 0.27, während die Spezifität von 0.27 auf\n0.97 steigt. Es gibt keine Schwelle, die beide gleichzeitig verbessert; jede\nVerschiebung ist ein Tausch.\n\n**Der PPV steigt mit der Schwelle.** Wer selten Alarm schlägt, hat unter seinen\nAlarmen einen höheren Anteil echter Fälle. Von 0.57 auf 0.89, und das ist der\nGrund, warum ein hoher PPV allein kein Gütezeichen ist: Er lässt sich immer\nerkaufen, indem man weniger oft Alarm schlägt.\n\n**F1 ist bei 0.35 am höchsten, nicht bei 0.5.** Wer nach F1 optimiert, landet\nalso nicht bei der Voreinstellung. Ob F1 das richtige Kriterium ist, entscheidet\ndie Anwendung.\n\nDie AUC von 0.80 bleibt bei all dem unverändert, denn sie fasst die ganze Kurve\nzusammen. Sie beantwortet die Frage \"wie gut trennt das Modell\", die Tabelle\nbeantwortet die Frage \"wie gut entscheidet es bei dieser Schwelle\".\n\n#### Interpretation und Ergebnissatz\n\n> Das Modell trennt die beiden Klassen brauchbar (AUC 0.80). Bei einer Schwelle\n> von 0.5 liegen Sensitivität und Spezifität bei je 0.72. Eine Senkung auf 0.35\n> erhöht die Sensitivität auf 0.87 zulasten der Spezifität (0.52) und maximiert\n> F1 (0.74). Die Wahl richtet sich nach dem Kostenverhältnis der beiden\n> Fehlerarten.\n\n### Beispiel 4: Warum an denselben Daten gemessen zu gut ist\n\n#### Frage und Datenlage\n\nDie 400 Fälle werden geteilt: 200 zum Schätzen, 200 zum Prüfen. Verglichen\nwerden zwei Modelle. Das eine nutzt nur das echte Merkmal, das andere zusätzlich\nzwanzig Merkmale, die nichts mit dem Ereignis zu tun haben.\n\nDie Frage lautet: Welches Modell ist besser, und woran erkennt man das?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nzusatz <- as.data.frame(sapply(1:20, function(k) richtung(3 + 2 * k)))\nnames(zusatz) <- paste0(\"z\", 1:20)\nvoll <- cbind(daten, zusatz)\n\ntrainieren <- voll[seq(1, nrow(voll), by = 2), ]\ntesten     <- voll[seq(2, nrow(voll), by = 2), ]\n\nsparsam <- glm(ereignis ~ merkmal, family = binomial, data = trainieren)\nueppig  <- glm(as.formula(paste(\"ereignis ~ merkmal +\",\n                                paste(names(zusatz), collapse = \" + \"))),\n               family = binomial, data = trainieren)\n\nvergleich <- function(modell, name) {\n  s_tr <- predict(modell, newdata = trainieren, type = \"response\")\n  s_te <- predict(modell, newdata = testen, type = \"response\")\n  cat(sprintf(\"%-9s AUC Training = %.4f   AUC Test = %.4f\\n\", name,\n              auc(trainieren$ereignis, s_tr), auc(testen$ereignis, s_te)))\n  cat(sprintf(\"          Genauigkeit Training = %.4f   Test = %.4f\\n\",\n              guete(trainieren$ereignis, as.integer(s_tr > 0.5))[\"Genauigkeit\"],\n              guete(testen$ereignis, as.integer(s_te > 0.5))[\"Genauigkeit\"]))\n}\n\nvergleich(sparsam, \"sparsam\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsparsam   AUC Training = 0.8096   AUC Test = 0.7911\n          Genauigkeit Training = 0.7200   Test = 0.7150\n```\n\n\n:::\n\n```{.r .cell-code}\nvergleich(ueppig, \"üppig\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nüppig    AUC Training = 0.8886   AUC Test = 0.7388\n          Genauigkeit Training = 0.8050   Test = 0.6850\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nzusatz = {f\"z{k}\": richtung(3 + 2 * k) for k in range(1, 21)}\nvoll = daten.assign(**zusatz)\n\ntrainieren = voll.iloc[::2].reset_index(drop=True)\ntesten = voll.iloc[1::2].reset_index(drop=True)\n\nsparsam = smf.logit(\"ereignis ~ merkmal\", data=trainieren).fit(disp=0)\nueppig = smf.logit(\"ereignis ~ merkmal + \" + \" + \".join(zusatz),\n                   data=trainieren).fit(disp=0, maxiter=200)\n\n\ndef vergleich(modell, name):\n    s_tr = modell.predict(trainieren)\n    s_te = modell.predict(testen)\n    print(f\"{name:9s} AUC Training = {auc(trainieren['ereignis'], s_tr):.4f}\"\n          f\"   AUC Test = {auc(testen['ereignis'], s_te):.4f}\")\n    g_tr = guete(trainieren[\"ereignis\"], (s_tr > 0.5).astype(int))\n    g_te = guete(testen[\"ereignis\"], (s_te > 0.5).astype(int))\n    print(f\"          Genauigkeit Training = {g_tr['Genauigkeit']:.4f}\"\n          f\"   Test = {g_te['Genauigkeit']:.4f}\")\n\n\nvergleich(sparsam, \"sparsam\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsparsam   AUC Training = 0.8096   AUC Test = 0.7911\n          Genauigkeit Training = 0.7200   Test = 0.7150\n```\n\n\n:::\n\n```{.python .cell-code}\nvergleich(ueppig, \"üppig\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nüppig     AUC Training = 0.8886   AUC Test = 0.7388\n          Genauigkeit Training = 0.8050   Test = 0.6850\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Modell | AUC Training | AUC Test | Genauigkeit Training | Genauigkeit Test |\n|---|---|---|---|---|\n| nur das echte Merkmal | 0.810 | **0.791** | 0.720 | 0.715 |\n| plus 20 wertlose Merkmale | **0.889** | 0.739 | 0.805 | 0.685 |\n\nDas üppige Modell ist auf den Trainingsdaten deutlich besser (AUC 0.889 gegen\n0.810) und auf neuen Daten deutlich schlechter (0.739 gegen 0.791). Die zwanzig\nZusatzmerkmale enthalten **keinerlei** Information über das Ereignis; sie sind\ndeterministisch konstruiertes Rauschen. Das Modell hat gelernt, die zufälligen\nMuster der 200 Trainingsfälle nachzubilden.\n\nBemerkenswert ist auch die Grösse des Unterschieds beim sparsamen Modell: 0.810\ngegen 0.791. Auch ein Modell mit zwei Parametern misst sich an den eigenen Daten\netwas zu gut, nur eben wenig. Der Abstand zwischen Trainings- und Testwert wächst\nmit der Anzahl der Parameter.\n\n#### Interpretation und Ergebnissatz\n\nDaraus folgen zwei Regeln.\n\n**Jede berichtete Kennzahl braucht die Angabe, worauf sie gemessen wurde.** Eine\nAUC von 0.89 ohne diesen Zusatz ist wertlos, weil sie an denselben Daten\ngemessen sein kann, mit denen das Modell gebaut wurde.\n\n**Modelle werden nicht an den Trainingsdaten verglichen.** Wer das tut, wählt\nsystematisch das komplexere Modell, denn mehr Parameter passen sich den\nvorliegenden Daten immer besser an. Der saubere Weg ist eine Trennung in\nTrainings- und Testdaten oder eine Kreuzvalidierung; für kleine Datensätze\nleisten AIC und BIC dasselbe auf rechnerischem Weg, siehe\n[Modellauswahl](modellauswahl.qmd).\n\n> Verglichen wurden zwei Modelle an einer Aufteilung in je 200 Trainings- und\n> Testfälle. Das sparsame Modell erreicht auf den Testdaten eine AUC von 0.791,\n> das um zwanzig wertlose Merkmale erweiterte nur 0.739, obwohl es auf den\n> Trainingsdaten besser abschneidet (0.889 gegen 0.810). Berichtet werden die\n> Testwerte des sparsamen Modells.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEin Prüfverfahren hat Sensitivität 0.90 und Spezifität 0.90. Das Ereignis tritt\nbei 2 Prozent auf. Wie oft liegt ein Alarm richtig?\n\n- [x] In rund 15 Prozent der Fälle ~ Richtig. Die 10 Prozent Fehlalarme\n      beziehen sich auf 98 Prozent der Fälle und ergeben viel mehr falsche als\n      echte Alarme. Der PPV beträgt 0.155.\n- [ ] In 90 Prozent der Fälle ~ Das ist die Sensitivität, und die beantwortet\n      die umgekehrte Frage: Von den Ereignissen, wie viele werden gefunden?\n- [ ] In 98 Prozent der Fälle ~ Das ist die Genauigkeit eines Verfahrens, das\n      nie Alarm schlägt.\n:::\n\n::: {.quiz}\nEin Modell erreicht eine Genauigkeit von 0.98. Was folgt daraus?\n\n- [x] Nichts, ohne die Klassenverteilung zu kennen ~ Richtig. Bei einem\n      Ereignisanteil von 2 Prozent erreicht \"immer nein\" genau diesen Wert. Die\n      Genauigkeit muss immer gegen diesen trivialen Vergleichswert gehalten\n      werden.\n- [ ] Das Modell ist sehr gut ~ Nur wenn die Klassen einigermassen ausgewogen\n      sind.\n- [ ] Das Modell ist überangepasst ~ Dafür bräuchte es einen Vergleich zwischen\n      Trainings- und Testdaten.\n:::\n\n::: {.quiz}\nEin Modell hat auf den Trainingsdaten eine AUC von 0.89 und auf Testdaten 0.74,\nein zweites 0.81 und 0.79. Welches ist besser?\n\n- [x] Das zweite ~ Richtig. Entschieden wird an den Testdaten, und dort liegt\n      das zweite vorn. Der grosse Abstand zwischen Trainings- und Testwert beim\n      ersten ist das Kennzeichen der Überanpassung.\n- [ ] Das erste, es hat die höhere AUC ~ Die höhere AUC hat es nur auf den\n      Daten, mit denen es gebaut wurde. Das ist kein Gütezeichen, sondern das\n      erwartete Verhalten.\n- [ ] Beide gleich gut, die Unterschiede sind klein ~ 0.74 gegen 0.79 ist ein\n      spürbarer Unterschied, und die Richtung ist eindeutig.\n:::\n\n::: {.quiz}\nWarum lässt sich ein hoher PPV immer erreichen?\n\n- [x] Indem man die Schwelle anhebt und seltener Alarm schlägt ~ Richtig. Wer\n      nur bei sehr hohen Scores Alarm schlägt, hat unter seinen wenigen Alarmen\n      einen hohen Anteil echter Fälle. In Beispiel 3 steigt der PPV von 0.57 auf\n      0.89, während die Sensitivität von 0.96 auf 0.27 fällt.\n- [ ] Durch ein besseres Modell ~ Ein besseres Modell hilft, ist aber nicht\n      nötig, um den PPV zu heben.\n- [ ] Gar nicht, der PPV hängt nur an den Daten ~ Er hängt an der Schwelle und\n      an der Häufigkeit des Ereignisses.\n:::\n\n## Verlinkte Ressourcen\n\n- [An Introduction to Statistical Learning, Kapitel 4.4](https://www.statlearning.com/)\n- [scikit-learn: Metriken für Klassifikation](https://scikit-learn.org/stable/modules/model_evaluation.html#classification-metrics)\n- [Logistische Regression](logistische-regression.qmd)\n",
    "supporting": [
      "klassifikationsguete_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}