{
  "hash": "7917f511eda8d9433160e6c7f0b387bd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hauptkomponentenanalyse\"\ndescription: \"Dimensionen reduzieren, Ladungen und erklärte Varianz lesen.\"\ncategories: [\"Dimensionsreduktion\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: methode\nstand: entwurf\norder: 20\n---\n\n\n\n\n\nDie Beispieldaten werden nicht zufällig gezogen, sondern deterministisch aus\nNormalverteilungsquantilen konstruiert. R und Python rechnen deshalb mit exakt\ndenselben 300 Zeilen und liefern dieselben Eigenwerte und Ladungen. Nur die\nVorzeichen der Ladungen können sich zwischen den beiden Ausgaben unterscheiden,\nund das ist bei diesem Verfahren bedeutungslos.\n\n\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Lassen sich viele korrelierte Variablen durch wenige unkorrelierte zusammenfassen, ohne viel Information zu verlieren? |\n| Zielvariable | keine, das Verfahren ist unüberwacht |\n| Eingang | mehrere metrische Variablen, meist standardisiert |\n| Was die Methode liefert | Komponenten mit Eigenwerten, erklärte Varianzanteile, Ladungen je Variable, Komponentenwerte je Beobachtung |\n| R-Funktion | `prcomp(daten, scale. = TRUE)`, gelesen mit `summary()` und `$rotation` |\n| Python-Funktion | `PCA().fit(StandardScaler().fit_transform(daten))` |\n| Verwandte Methoden | [Faktorenanalyse](faktorenanalyse.qmd), [k-Means](k-means.qmd), [Distanzmasse](distanzmasse.qmd) |\n\n## Wann diese Methode, wann nicht\n\nTypische Fragestellungen: Zwanzig Sensorwerte auf zwei bis drei Kennzahlen\nverdichten, korrelierte Prädiktoren vor einem Modell entflechten, einen\nDatensatz zweidimensional darstellen, um Gruppen zu sehen.\n\nDie Hauptkomponentenanalyse ist eine Umrechnung, keine Modellierung: Sie sucht\ndie Richtungen im Raum, in denen die Daten am stärksten streuen, und\nbeschreibt jede Beobachtung durch ihre Lage entlang dieser Richtungen. Weil die\nKomponenten unkorreliert sind, löst sie zugleich das Problem sich doppelnder\nVariablen.\n\n| Situation | Stattdessen |\n|---|---|\n| Es geht um dahinterliegende Ursachen, nicht um Verdichtung | [Faktorenanalyse](faktorenanalyse.qmd) |\n| Gruppen sollen gebildet werden | [k-Means](k-means.qmd) oder [hierarchisches Clustering](hierarchisches-clustering.qmd) |\n| Es gibt eine Zielvariable und Vorhersage ist das Ziel | [Regression](../regression/index.qmd) mit Variablenauswahl |\n| Die Variablen sind kategorial | Korrespondenzanalyse, oder Gower-Distanz und Clustering |\n| Der Zusammenhang ist deutlich nichtlinear | nichtlineare Verfahren, etwa UMAP oder Kernel-PCA |\n| Die Variablen sind praktisch unkorreliert | nichts zu verdichten; die Analyse liefert nur eine Drehung |\n\n## Grundidee und Modell\n\nGesucht ist die Richtung im Variablenraum, entlang der die Daten am stärksten\nstreuen. Das ist die erste Hauptkomponente. Die zweite ist die Richtung mit der\nnächstgrössten Streuung, die auf der ersten senkrecht steht, und so weiter. Die\nKomponenten sind Linearkombinationen der ursprünglichen Variablen.\n\n$$z_{ij} = \\sum_{k} a_{kj} \\cdot \\tilde{x}_{ik}$$\n\n| Bestandteil | Bedeutung |\n|---|---|\n| $\\tilde{x}_{ik}$ | standardisierter Wert von Variable $k$ bei Beobachtung $i$ |\n| $a_{kj}$ | Ladung: Gewicht von Variable $k$ in Komponente $j$ |\n| $z_{ij}$ | Komponentenwert von Beobachtung $i$ auf Komponente $j$ |\n| Eigenwert | Varianz, die eine Komponente auf sich zieht |\n\nRechnerisch ist es die Eigenwertzerlegung der Korrelationsmatrix, wenn\nstandardisiert wurde, und der Kovarianzmatrix, wenn nicht. Der Unterschied ist\ngross: ohne Standardisierung dominiert die Variable mit der grössten Varianz,\nsiehe [Distanzmasse](distanzmasse.qmd). Bei verschiedenen Einheiten wird deshalb\nimmer standardisiert.\n\nDie Summe aller Eigenwerte ist bei standardisierten Daten gleich der Anzahl\nVariablen. Ein Eigenwert von 1 entspricht damit genau dem Informationsgehalt\neiner einzelnen Variablen, und das ist der Grund für die Faustregel, Komponenten\nmit Eigenwert über 1 zu behalten.\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung | Vorgehen |\n|---|---|---|---|---|\n| Metrische Variablen | Linearkombinationen sind sinnvoll | [Skalenniveau](../grundlagen/skalenniveaus.qmd) | Ladungen sind nicht deutbar | Korrespondenzanalyse, andere Verfahren |\n| Korrelation vorhanden | Es gibt etwas zu verdichten | Korrelationsmatrix ansehen | Alle Eigenwerte nahe 1, kein Gewinn | keine Reduktion vornehmen |\n| Lineare Zusammenhänge | Streuungsrichtungen sind Geraden | Streudiagramme | Struktur wird verfehlt | Transformation, nichtlineare Verfahren |\n| Vergleichbare Skalen oder Standardisierung | Keine Variable dominiert wegen ihrer Einheit | Varianzen vergleichen | Erste Komponente ist praktisch die grösste Variable | `scale. = TRUE` beziehungsweise `StandardScaler` |\n| Keine extremen Ausreisser | Varianz ist nicht von wenigen Punkten getrieben | Streudiagramme, Ausreisserdiagnostik | Komponenten zeigen auf die Ausreisser | robuste Varianten, Ursachen prüfen |\n\n## Output lesen\n\nR, `summary(prcomp(...))`:\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| `Standard deviation` | Wurzel des Eigenwerts je Komponente | quadriert ergibt den Eigenwert |\n| `Proportion of Variance` | Anteil der Gesamtvarianz, den die Komponente erklärt | summiert sich über alle Komponenten zu eins |\n| `Cumulative Proportion` | kumulierter Anteil | die Zahl, an der man die Anzahl Komponenten festlegt |\n| `$rotation` | Ladungen: Gewicht jeder Variablen in jeder Komponente | Vorzeichen sind beliebig |\n| `$x` | Komponentenwerte je Beobachtung | die neuen Variablen für weitere Analysen |\n| `$sdev` | Standardabweichungen, für den Screeplot | Eigenwert ist `$sdev^2` |\n| `$center`, `$scale` | verwendete Mittelwerte und Streuungen | nötig, um neue Daten identisch zu transformieren |\n\nPython, `PCA`:\n\n| Zugriff | Was er liefert | Unterschied zu R |\n|---|---|---|\n| `explained_variance_ratio_` | Varianzanteile | wie `Proportion of Variance` |\n| `explained_variance_` | Eigenwerte, mit n minus 1 normiert | R normiert gleich, die Werte stimmen überein |\n| `components_` | Ladungen, aber **zeilenweise** je Komponente | in R spaltenweise; deshalb transponieren |\n| `transform(X)` | Komponentenwerte | wie `$x` |\n| `n_components_` | Anzahl Komponenten | |\n| kein `summary()` | Tabelle selbst zusammenstellen | in R eine Zeile |\n\nZwei Stolpersteine gelten in beiden Sprachen. **Die Vorzeichen der Ladungen sind\nbeliebig:** Eine Komponente und ihr Negativ beschreiben dieselbe Richtung, und\ndie Programme wählen willkürlich. Ein Vorzeichenwechsel zwischen zwei Läufen\noder zwischen R und Python ist kein Fehler. **Standardisierung geschieht nicht\nautomatisch:** In R braucht es `scale. = TRUE`, in Python einen eigenen Schritt\ndavor.\n\n## Wie viele Komponenten behalten?\n\n| Kriterium | Regel | Grenzen |\n|---|---|---|\n| Kaiser | Eigenwert grösser als 1 | Mechanisch. Ein Eigenwert von 1.02 und einer von 0.98 unterscheiden sich in nichts Inhaltlichem. |\n| Screeplot | bis zum Knick | Der Knick ist Auslegungssache und manchmal nicht vorhanden. |\n| Kumulierte Varianz | so viele, bis ein gesetzter Anteil erreicht ist, oft 80 Prozent | Der Anteil wird vorher festgelegt, nicht nachträglich passend gewählt. |\n| Deutbarkeit | nur Komponenten behalten, die sich benennen lassen | Das wichtigste Kriterium und das einzige, das inhaltlich argumentiert. |\n\nDie Kriterien widersprechen sich regelmässig. Dann wird die Entscheidung\nbegründet und nicht die Regel gewechselt, bis das Ergebnis gefällt.\n\n## Interpretationsfallen\n\n- **Die erste Komponente ist nicht die wichtigste Variable.** Sie ist die\n  Richtung der grössten Streuung, und Streuung ist nicht Bedeutung.\n- **Erklärte Varianz ist keine Modellgüte.** Sie sagt, wie viel Streuung erhalten\n  bleibt, nicht ob das Ergebnis brauchbar ist.\n- **Vorzeichen der Ladungen sind beliebig.** Eine Komponente kann in zwei Läufen\n  gespiegelt erscheinen; inhaltlich ändert das nichts.\n- **Komponenten sind keine Ursachen.** Sie sind Rechengrössen. Wer nach\n  dahinterliegenden Grössen sucht, nimmt die\n  [Faktorenanalyse](faktorenanalyse.qmd).\n- **Ohne Standardisierung entscheidet die Einheit.** Das ist der häufigste\n  stille Fehler, siehe Beispiel 2.\n- **Ausreisser bestimmen Richtungen.** Ein einzelner extremer Punkt kann eine\n  Komponente vollständig auf sich ausrichten.\n- **Zwei Dimensionen sind eine Wahl, keine Wahrheit.** Wenn zwei Komponenten nur\n  40 Prozent erklären, ist die Punktwolke in der Ebene eine grobe Projektion, und\n  Abstände darin sind mit Vorsicht zu deuten.\n\n## Ergebnis berichten\n\nVorlage für den Ergebnissatz:\n\n> Eine Hauptkomponentenanalyse auf [Anzahl] standardisierten Variablen (n = [n])\n> ergibt [Anzahl] Komponenten mit Eigenwert über eins, die zusammen [Anteil] der\n> Varianz erklären. Komponente 1 lädt hoch auf [Variablen] und wird als\n> [Deutung] gelesen, Komponente 2 auf [Variablen] als [Deutung].\n\nGenannt werden: Anzahl Variablen und Beobachtungen, ob standardisiert wurde,\nEigenwerte und kumulierte erklärte Varianz, die Ladungen der behaltenen\nKomponenten, das Kriterium für die Anzahl und die inhaltliche Deutung. Ohne\nDeutung ist eine Komponentenanalyse nur eine Zahlenumformung.\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt der Hauptkomponentenanalyse |\n|---|---|\n| [Faktorenanalyse](faktorenanalyse.qmd) | latente Ursachen sollen modelliert werden, nicht Varianz verdichtet |\n| [k-Means](k-means.qmd) | Gruppen von Beobachtungen statt neuer Variablen |\n| [Multiple lineare Regression](../regression/multiple-lineare-regression.qmd) | es gibt eine Zielvariable |\n| Korrespondenzanalyse | die Variablen sind kategorial |\n| Nichtlineare Verfahren, etwa UMAP | die Struktur ist deutlich nichtlinear und nur die Darstellung zählt |\n\n## Beispiele\n\nJedes Beispiel steht in einem eigenen Reiter.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Sechs Sensoren einer Fertigungslinie\n\n#### Frage und Datenlage\n\nAn einer Fertigungslinie werden sechs Grössen aufgezeichnet: Vibration in\nMillimetern je Sekunde, Temperatur in Grad Celsius, Stromaufnahme in Ampere,\nTaktzeit in Sekunden, Ausstoss in Stück und Luftfeuchte in Prozent. Für 300\nSchichten liegen die Werte vor. Gefragt ist, ob sich die sechs Kennzahlen auf\nwenige zusammenfassen lassen und was diese wenigen inhaltlich bedeuten.\n\n#### Voraussetzungen prüfen\n\nVor jeder Komponentenanalyse steht die Korrelationsmatrix. Sie beantwortet die\nFrage, ob es überhaupt etwas zu verdichten gibt, und die Varianzen beantworten\ndie Frage, ob standardisiert werden muss.\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(cor(linie), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              vibration temperatur stromaufnahme taktzeit ausstoss luftfeuchte\nvibration          1.00       0.93          0.95    -0.03     0.05        0.06\ntemperatur         0.93       1.00          0.93    -0.08     0.10        0.04\nstromaufnahme      0.95       0.93          1.00    -0.08     0.04        0.05\ntaktzeit          -0.03      -0.08         -0.08     1.00    -0.94        0.01\nausstoss           0.05       0.10          0.04    -0.94     1.00        0.00\nluftfeuchte        0.06       0.04          0.05     0.01     0.00        1.00\n```\n\n\n:::\n\n```{.r .cell-code}\nround(sapply(linie, var), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    vibration    temperatur stromaufnahme      taktzeit      ausstoss \n         70.4          27.7           2.4          16.8        3970.9 \n  luftfeuchte \n         36.0 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(linie.corr().round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               vibration  temperatur  ...  ausstoss  luftfeuchte\nvibration           1.00        0.93  ...      0.05         0.06\ntemperatur          0.93        1.00  ...      0.10         0.04\nstromaufnahme       0.95        0.93  ...      0.04         0.05\ntaktzeit           -0.03       -0.08  ...     -0.94         0.01\nausstoss            0.05        0.10  ...      1.00         0.00\nluftfeuchte         0.06        0.04  ...      0.00         1.00\n\n[6 rows x 6 columns]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(linie.var().round(1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nvibration          70.4\ntemperatur         27.7\nstromaufnahme       2.4\ntaktzeit           16.8\nausstoss         3970.9\nluftfeuchte        36.0\ndtype: float64\n```\n\n\n:::\n:::\n\n\n:::\n\nDie Korrelationsmatrix zeigt zwei Blöcke. Vibration, Temperatur und\nStromaufnahme korrelieren untereinander mit 0.93 bis 0.95. Taktzeit und Ausstoss\nkorrelieren mit -0.94; das negative Vorzeichen ist inhaltlich richtig, weil eine\nkürzere Taktzeit mehr Stück je Schicht bedeutet. Die Luftfeuchte korreliert mit\nallem unter 0.07, also mit nichts.\n\nDie Varianzen reichen von 2.4 bei der Stromaufnahme bis 3971 beim Ausstoss, ein\nVerhältnis von rund 1 zu 1650. Der Grund sind die Einheiten: Ampere und Stück\nsind schlicht verschieden grosse Zahlen. Ohne Standardisierung würde die erste\nKomponente deshalb den Ausstoss abbilden und sonst nichts, wie Beispiel 2 zeigt.\n\n#### Analyse rechnen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca <- prcomp(linie, scale. = TRUE)\n\nsummary(pca)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nImportance of components:\n                          PC1    PC2    PC3     PC4     PC5     PC6\nStandard deviation     1.7036 1.3852 0.9981 0.31572 0.25413 0.13564\nProportion of Variance 0.4837 0.3198 0.1660 0.01661 0.01076 0.00307\nCumulative Proportion  0.4837 0.8035 0.9696 0.98617 0.99693 1.00000\n```\n\n\n:::\n\n```{.r .cell-code}\nround(pca$rotation[, 1:3], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 PC1    PC2    PC3\nvibration      0.570  0.108  0.019\ntemperatur     0.568  0.073  0.030\nstromaufnahme  0.570  0.091  0.031\ntaktzeit      -0.112  0.698  0.005\nausstoss       0.112 -0.698 -0.018\nluftfeuchte    0.043  0.023 -0.999\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nstandardisiert = StandardScaler().fit_transform(linie)\npca = PCA().fit(standardisiert)\n\nnamen = [f\"PC{i + 1}\" for i in range(pca.n_components_)]\nuebersicht = pd.DataFrame({\n    \"Standardabweichung\": np.sqrt(pca.explained_variance_).round(4),\n    \"Eigenwert\": pca.explained_variance_.round(4),\n    \"Anteil\": pca.explained_variance_ratio_.round(4),\n    \"kumuliert\": pca.explained_variance_ratio_.cumsum().round(4),\n}, index=namen)\nprint(uebersicht)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Standardabweichung  Eigenwert  Anteil  kumuliert\nPC1              1.7065     2.9121  0.4837     0.4837\nPC2              1.3875     1.9253  0.3198     0.8035\nPC3              0.9997     0.9994  0.1660     0.9696\nPC4              0.3163     0.1000  0.0166     0.9862\nPC5              0.2546     0.0648  0.0108     0.9969\nPC6              0.1359     0.0185  0.0031     1.0000\n```\n\n\n:::\n\n```{.python .cell-code}\nladungen = pd.DataFrame(pca.components_[:3].T, index=linie.columns,\n                        columns=namen[:3])\nprint(ladungen.round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 PC1    PC2    PC3\nvibration      0.570  0.108 -0.019\ntemperatur     0.568  0.073 -0.030\nstromaufnahme  0.570  0.091 -0.031\ntaktzeit      -0.112  0.698 -0.005\nausstoss       0.112 -0.698  0.018\nluftfeuchte    0.043  0.023  0.999\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nZuerst die Varianztabelle:\n\n| Komponente | Standardabweichung | Eigenwert | Anteil | kumuliert | Was das heisst |\n|---|---|---|---|---|---|\n| PC1 | 1.707 | 2.912 | 48.4 % | 48.4 % | Zieht so viel Varianz auf sich wie knapp drei einzelne Variablen. Das ist der Werkzeugblock. |\n| PC2 | 1.388 | 1.925 | 32.0 % | 80.4 % | Knapp zwei Variablen wert. Das ist der Durchsatzblock. |\n| PC3 | 1.000 | 0.999 | 16.6 % | 97.0 % | Genau eine Variable wert, und das ist wörtlich zu nehmen: Diese Komponente **ist** die Luftfeuchte. |\n| PC4 bis PC6 | 0.316 / 0.255 / 0.136 | 0.100 / 0.065 / 0.019 | zusammen 3.0 % | 100 % | Das Messrauschen der einzelnen Sensoren. |\n\nDer Eigenwert ist die entscheidende Zahl, weil er eine feste Bezugsgrösse hat:\nBei standardisierten Daten trägt jede Ausgangsvariable genau 1 bei, und die\nEigenwerte summieren sich auf die Anzahl Variablen, hier 6. Ein Eigenwert von\n2.912 heisst also wörtlich \"so viel Information wie 2.9 der ursprünglichen\nVariablen\".\n\nDann die Ladungen:\n\n| Variable | PC1 | PC2 | PC3 | Wie das zu lesen ist |\n|---|---|---|---|---|\n| vibration | 0.570 | 0.108 | -0.019 | Hohe Ladung auf PC1, sonst nichts. |\n| temperatur | 0.568 | 0.073 | -0.030 | Ebenso. |\n| stromaufnahme | 0.570 | 0.091 | -0.031 | Ebenso. Drei praktisch gleiche Ladungen bedeuten: PC1 ist der ungewichtete Durchschnitt dieser drei Grössen. |\n| taktzeit | -0.112 | 0.698 | -0.005 | Trägt PC2, mit umgekehrtem Vorzeichen zum Ausstoss. |\n| ausstoss | 0.112 | -0.698 | 0.018 | Ebenso. Die beiden Ladungen von 0.698 und -0.698 sind betragsgleich: PC2 ist im Wesentlichen die Differenz der beiden standardisierten Grössen. |\n| luftfeuchte | 0.043 | 0.023 | 0.999 | Lädt auf nichts ausser der eigenen Komponente. Eine Variable, die mit keiner anderen zusammenhängt, bekommt ihre eigene Komponente mit Eigenwert 1. |\n\nZur Grössenordnung der Ladungen: Bei sechs Variablen hat jede Ladungsspalte die\nLänge 1, eine Gleichverteilung auf alle sechs entspräche also je 0.41. Werte um\n0.57 sind demnach hoch, Werte unter etwa 0.15 sind Rauschen. Die Schwelle hängt\nan der Anzahl Variablen und ist keine feste Zahl.\n\n#### Auswahl und Darstellung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\neigenwerte <- pca$sdev^2\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nplot(eigenwerte, type = \"b\", pch = 16, xlab = \"Komponente\", ylab = \"Eigenwert\",\n     main = \"Screeplot\")\nabline(h = 1, lty = 2, col = \"firebrick\")\nplot(pca$x[, 1], pca$x[, 2], pch = 16, cex = 0.6, col = \"grey40\",\n     xlab = \"PC1 (Werkzeugzustand)\", ylab = \"PC2 (Durchsatz)\",\n     main = \"Schichten\")\nabline(h = 0, v = 0, col = \"grey80\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 1: Screeplot der Eigenwerte und die Schichten in der Ebene der ersten beiden Komponenten.](hauptkomponentenanalyse_files/figure-html/fig-b1-scree-r-1.png){#fig-b1-scree-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nwerte = pca.transform(standardisiert)\neigenwerte = pca.explained_variance_\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.4))\nachsen[0].plot(range(1, len(eigenwerte) + 1), eigenwerte, \"o-\", color=\"#2166ac\")\nachsen[0].axhline(1, linestyle=\"--\", color=\"firebrick\", linewidth=0.8)\nachsen[0].set_xlabel(\"Komponente\")\nachsen[0].set_ylabel(\"Eigenwert\")\nachsen[0].set_title(\"Screeplot\")\nachsen[1].scatter(werte[:, 0], werte[:, 1], s=8, color=\"0.4\")\nachsen[1].axhline(0, color=\"0.85\")\nachsen[1].axvline(0, color=\"0.85\")\nachsen[1].set_xlabel(\"PC1 (Werkzeugzustand)\")\nachsen[1].set_ylabel(\"PC2 (Durchsatz)\")\nachsen[1].set_title(\"Schichten\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Darstellung in Python.](hauptkomponentenanalyse_files/figure-html/fig-b1-scree-py-1.png){#fig-b1-scree-py width=100%}\n:::\n:::\n\n\n:::\n\nDer Screeplot fällt von 2.91 auf 1.93 auf 1.00 und knickt dann scharf auf 0.10\nab. Nach dem Knick ist die Sache eindeutig, davor nicht: Das Kaiser-Kriterium\n(Eigenwert grösser 1) liefert zwei Komponenten, weil PC3 mit 0.999 knapp\ndarunter liegt. Ein Hundertstel mehr, und dieselbe Regel hätte drei geliefert.\nGenau das ist gemeint, wenn vor mechanischen Schwellen gewarnt wird.\n\nInhaltlich ist die Entscheidung trotzdem klar, und zwar nicht wegen der Zahl,\nsondern wegen der Ladungen: PC3 ist nichts anderes als die Luftfeuchte, die mit\nkeiner anderen Grösse zusammenhängt. Sie zu behalten hiesse, eine\nAusgangsvariable unter neuem Namen mitzuschleppen. Wer sie braucht, nimmt sie\ndirekt und nennt sie Luftfeuchte.\n\n#### Interpretation und Ergebnissatz\n\nDie Sensordaten enthalten zwei gemeinsame Bewegungen und eine eigenständige\nGrösse. Die erste Bewegung erfasst Vibration, Temperatur und Stromaufnahme; alle\ndrei steigen zusammen, was zum Bild eines zunehmend abgenutzten Werkzeugs passt.\nDie zweite erfasst den Gegensatz von Taktzeit und Ausstoss, also die\nDurchsatzeinstellung der Linie. Die Luftfeuchte bleibt für sich.\n\nPraktisch heisst das: Statt sechs Sensorwerte zu überwachen, genügen zwei\nKennzahlen plus die Luftfeuchte, und man behält 97 Prozent der Streuung. Der\nPreis ist, dass die beiden Kennzahlen erst über die Ladungen erklärt werden\nmüssen.\n\n> Eine Hauptkomponentenanalyse auf sechs standardisierten Sensorgrössen\n> (n = 300) ergibt zwei Komponenten mit Eigenwert über eins, die zusammen\n> 80.4 Prozent der Varianz erklären. Komponente 1 (Eigenwert 2.91, 48.4 Prozent)\n> lädt gleichmässig auf Vibration, Temperatur und Stromaufnahme (Ladungen 0.57)\n> und wird als Werkzeugzustand gelesen. Komponente 2 (Eigenwert 1.93,\n> 32.0 Prozent) stellt Taktzeit und Ausstoss gegenüber (Ladungen 0.70 und -0.70)\n> und wird als Durchsatz gelesen. Die dritte Komponente (Eigenwert 1.00)\n> entspricht der Luftfeuchte, die mit keiner anderen Grösse zusammenhängt; sie\n> wird als eigene Variable weitergeführt statt als Komponente.\n\n### Beispiel 2: Fehlende Standardisierung\n\n#### Frage und Datenlage\n\nDieselben 300 Schichten und dieselben sechs Sensoren, nur wird diesmal nicht\nstandardisiert. In R heisst das `scale. = FALSE` (die Voreinstellung), in Python\nschlicht, den `StandardScaler` wegzulassen. Das ist der häufigste stille Fehler\ndieses Verfahrens, weil das Programm nicht warnt.\n\n#### Analyse rechnen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca_ohne <- prcomp(linie, scale. = FALSE)\n\nround(summary(pca_ohne)$importance[, 1:3], 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                           PC1    PC2    PC3\nStandard deviation     63.1364 9.8708 5.9833\nProportion of Variance  0.9666 0.0236 0.0087\nCumulative Proportion   0.9666 0.9902 0.9989\n```\n\n\n:::\n\n```{.r .cell-code}\nround(pca_ohne$rotation[, 1:2], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 PC1    PC2\nvibration      0.007  0.844\ntemperatur     0.008  0.511\nstromaufnahme  0.001  0.152\ntaktzeit      -0.061  0.008\nausstoss       0.998 -0.010\nluftfeuchte    0.000  0.052\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\npca_ohne = PCA().fit(linie.values)\n\nprint(pd.DataFrame({\n    \"Anteil\": pca_ohne.explained_variance_ratio_[:3].round(4),\n    \"kumuliert\": pca_ohne.explained_variance_ratio_.cumsum()[:3].round(4),\n}, index=[\"PC1\", \"PC2\", \"PC3\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Anteil  kumuliert\nPC1  0.9666     0.9666\nPC2  0.0236     0.9902\nPC3  0.0087     0.9989\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pd.DataFrame(pca_ohne.components_[:2].T, index=linie.columns,\n                   columns=[\"PC1\", \"PC2\"]).round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 PC1    PC2\nvibration      0.007  0.844\ntemperatur     0.008  0.511\nstromaufnahme  0.001  0.152\ntaktzeit      -0.061  0.008\nausstoss       0.998 -0.010\nluftfeuchte    0.000  0.052\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Anteil PC1 | 96.66 % | Sieht nach einem hervorragenden Ergebnis aus: eine Komponente genügt. Genau dieser scheinbare Erfolg ist das Warnsignal. |\n| Anteil PC2 | 2.36 % | |\n| Anteil PC3 | 0.87 % | |\n| Ladung `ausstoss` auf PC1 | 0.998 | Die Auflösung. PC1 besteht praktisch vollständig aus dem Ausstoss. |\n| Ladung `taktzeit` auf PC1 | -0.061 | |\n| Ladung `vibration` auf PC1 | 0.007 | Vibration, Temperatur und Stromaufnahme kommen in der ersten Komponente überhaupt nicht vor. |\n| Ladung `vibration` auf PC2 | 0.844 | Der Werkzeugblock taucht erst in der zweiten Komponente auf, die aber nur 2.4 Prozent trägt. |\n\nDer Vergleich mit Beispiel 1 zeigt den Schaden. Standardisiert erklärt PC1\n48.4 Prozent und fasst drei Sensoren zusammen; unstandardisiert erklärt PC1\n96.7 Prozent und ist eine einzige Variable unter anderem Namen. Der Ausstoss\ngewinnt nicht, weil er wichtiger wäre, sondern weil er in Stück gezählt wird und\nseine Varianz mit 3971 rund 1650 Mal so gross ist wie die der Stromaufnahme in\nAmpere. Wäre der Ausstoss in Tausend Stück erfasst worden, sähe das Ergebnis\nvöllig anders aus.\n\n#### Interpretation und Ergebnissatz\n\nZwei Zeichen verraten den Fehler zuverlässig: Eine einzelne Komponente erklärt\nunplausibel viel, und ihre Ladungen konzentrieren sich auf eine Variable. Beides\nlässt sich in einem Blick auf die Ladungstabelle prüfen.\n\nNicht standardisiert wird nur dann, wenn alle Variablen dieselbe Einheit haben\n**und** die Unterschiede in der Streuung inhaltlich gewollt sind, etwa bei\nmehreren Messungen derselben Grösse an verschiedenen Stellen. In allen anderen\nFällen ist die Standardisierung Pflicht.\n\n> Ohne Standardisierung beschreibt die erste Komponente mit 96.7 Prozent\n> erklärter Varianz im Wesentlichen den Ausstoss (Ladung 0.998), weil dessen\n> Varianz durch die Einheit um Grössenordnungen über den übrigen liegt.\n> Berichtet wird die Analyse auf standardisierten Daten.\n\n### Beispiel 3: Nichts zu verdichten\n\n#### Frage und Datenlage\n\nSechs Kennzahlen aus verschiedenen Bereichen eines Betriebs, die inhaltlich\nnichts miteinander zu tun haben. Das Beispiel zeigt, wie das Ergebnis aussieht,\nwenn es nichts zu reduzieren gibt, und warum man die Analyse dann abbricht statt\nsie zu berichten.\n\n#### Analyse rechnen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunabhaengig <- data.frame(\n  v1 = richtung(7),   v2 = richtung(53),  v3 = richtung(101),\n  v4 = richtung(149), v5 = richtung(197), v6 = richtung(241)\n)\n\nround(cor(unabhaengig), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       v1     v2     v3     v4     v5     v6\nv1  1.000 -0.019  0.002  0.002  0.020  0.033\nv2 -0.019  1.000  0.009 -0.021  0.031 -0.025\nv3  0.002  0.009  1.000  0.031 -0.021  0.066\nv4  0.002 -0.021  0.031  1.000  0.009  0.029\nv5  0.020  0.031 -0.021  0.009  1.000  0.115\nv6  0.033 -0.025  0.066  0.029  0.115  1.000\n```\n\n\n:::\n\n```{.r .cell-code}\npca_b3 <- prcomp(unabhaengig, scale. = TRUE)\nround(summary(pca_b3)$importance, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         PC1   PC2   PC3   PC4   PC5   PC6\nStandard deviation     1.069 1.021 1.009 0.992 0.982 0.921\nProportion of Variance 0.191 0.174 0.170 0.164 0.161 0.141\nCumulative Proportion  0.191 0.364 0.534 0.698 0.859 1.000\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nunabhaengig = pd.DataFrame({\n    \"v1\": richtung(7),   \"v2\": richtung(53),  \"v3\": richtung(101),\n    \"v4\": richtung(149), \"v5\": richtung(197), \"v6\": richtung(241),\n})\n\nprint(unabhaengig.corr().round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       v1     v2     v3     v4     v5     v6\nv1  1.000 -0.019  0.002  0.002  0.020  0.033\nv2 -0.019  1.000  0.009 -0.021  0.031 -0.025\nv3  0.002  0.009  1.000  0.031 -0.021  0.066\nv4  0.002 -0.021  0.031  1.000  0.009  0.029\nv5  0.020  0.031 -0.021  0.009  1.000  0.115\nv6  0.033 -0.025  0.066  0.029  0.115  1.000\n```\n\n\n:::\n\n```{.python .cell-code}\npca_b3 = PCA().fit(StandardScaler().fit_transform(unabhaengig))\nprint(pd.DataFrame({\n    \"Eigenwert\": pca_b3.explained_variance_.round(3),\n    \"Anteil\": pca_b3.explained_variance_ratio_.round(3),\n    \"kumuliert\": pca_b3.explained_variance_ratio_.cumsum().round(3),\n}, index=[f\"PC{i + 1}\" for i in range(6)]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Eigenwert  Anteil  kumuliert\nPC1      1.147   0.191      0.191\nPC2      1.046   0.174      0.364\nPC3      1.022   0.170      0.534\nPC4      0.986   0.164      0.698\nPC5      0.968   0.161      0.859\nPC6      0.851   0.141      1.000\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Korrelationen | alle zwischen -0.03 und 0.12 | Schon hier ist die Sache entschieden. Es gibt keine gemeinsamen Bewegungen. |\n| Eigenwerte | 1.147, 1.046, 1.022, 0.986, 0.968, 0.851 | Alle nahe 1, also trägt jede Komponente etwa so viel wie eine einzelne Variable. Genau das ist die Definition von \"nichts gewonnen\". |\n| Anteile | 19.1 %, 17.4 %, 17.0 %, 16.4 %, 16.1 %, 14.1 % | Alle nahe an einem Sechstel, also 16.7 Prozent. |\n| kumuliert nach zwei Komponenten | 36.4 % | Wer hier zwei Komponenten behält, wirft rund zwei Drittel der Information weg und bekommt dafür zwei Mischungen, die sich nicht benennen lassen. |\n\nDas Kaiser-Kriterium liefert hier scheinbar drei Komponenten mit Eigenwert über\n1. Das ist reine Stichprobenschwankung: Bei sechs unabhängigen Variablen liegen\ndie Eigenwerte per Konstruktion um 1 herum, und etwa die Hälfte davon landet\ndarüber. Ein Kriterium, das ausgerechnet bei strukturlosen Daten ein Ergebnis\nliefert, taugt nicht als alleinige Entscheidungsgrundlage.\n\n#### Interpretation und Ergebnissatz\n\nDer Abbruch ist hier das richtige Ergebnis und kein Misserfolg. Er lässt sich\nzudem vorwegnehmen: Die Korrelationsmatrix zeigt das Fehlen von Struktur, bevor\neine einzige Komponente gerechnet ist. Deshalb steht sie am Anfang jeder\nAnalyse.\n\nWer es formal prüfen will, kann den Bartlett-Test auf Sphärizität oder das\nKMO-Mass heranziehen; beide beantworten die Frage \"gibt es genug Korrelation für\neine Reduktion\". Der Blick auf die Matrix genügt in den meisten Fällen.\n\n> Die sechs Kennzahlen sind praktisch unkorreliert (alle Korrelationen unter\n> 0.12); die Eigenwerte liegen zwischen 0.85 und 1.15, jede Komponente erklärt\n> rund ein Sechstel der Varianz. Eine Dimensionsreduktion ist hier nicht\n> sinnvoll; die Variablen werden einzeln weiterverwendet.\n\n### Beispiel 4: Komponenten weiterverwenden\n\n#### Frage und Datenlage\n\nZurück zu den Sensordaten aus Beispiel 1. Die beiden Komponenten sollen nun als\nEingang für ein anschliessendes Verfahren dienen, etwa ein\n[Clustering der Schichten](k-means.qmd) oder eine Regression. Der Grund dafür ist\ntechnisch: Vibration, Temperatur und Stromaufnahme messen fast dasselbe, und in\neiner Distanz oder einem Regressionsmodell zählt dieses eine Merkmal dann\ndreifach.\n\n#### Komponenten prüfen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkomponenten <- pca$x[, 1:2]\n\nround(cor(komponenten), 12)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    PC1 PC2\nPC1   1   0\nPC2   0   1\n```\n\n\n:::\n\n```{.r .cell-code}\nround(apply(komponenten, 2, var), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   PC1    PC2 \n2.9024 1.9188 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(head(komponenten, 3), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        PC1   PC2\n[1,] -6.848 2.904\n[2,] -4.618 0.810\n[3,] -3.846 0.192\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nkomponenten = pca.transform(standardisiert)[:, :2]\n\nprint(np.corrcoef(komponenten.T).round(12))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[ 1. -0.]\n [-0.  1.]]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(komponenten.var(axis=0, ddof=1).round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[2.9121 1.9253]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(komponenten[:3].round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[-6.859  2.909]\n [-4.626  0.812]\n [-3.853  0.192]]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Korrelation der beiden Komponenten | 0 (bis auf Rundungsfehler in der zwölften Stelle) | Nicht ungefähr null, sondern konstruktionsbedingt exakt null. Die Komponenten stehen senkrecht aufeinander. |\n| Varianz von PC1 | 2.912 | Identisch mit dem Eigenwert. Das ist keine Zufälligkeit, sondern die Definition: Der Eigenwert **ist** die Varianz der Komponentenwerte. |\n| Varianz von PC2 | 1.925 | Ebenso. |\n| erste Komponentenwerte | Beträge von 0 bis rund 7 | Sie sind zentriert; der Nullpunkt ist die durchschnittliche Schicht. Ein Betrag von rund 7 auf PC1 bedeutet eine Schicht weit am Rand des Werkzeugblocks, ein Betrag nahe 0 eine unauffällige. Ob dieser Rand das positive oder das negative Ende ist, hängt an der willkürlichen Orientierung der Komponente und kann sich zwischen R und Python unterscheiden. |\n\n#### Interpretation und Ergebnissatz\n\nDer Gewinn ist die Unkorreliertheit, der Preis die Deutbarkeit. Ein Clustering\nauf PC1 und PC2 liefert Gruppen im gedrehten Raum; um sie zu beschreiben, muss\nman über die Ladungen zurückrechnen und sagen, dass \"Gruppe 2 hohe Werte auf der\nWerkzeugkomponente hat, also hohe Vibration, Temperatur und Stromaufnahme\".\n\nDrei Regeln für die Weiterverwendung:\n\n| Regel | Grund |\n|---|---|\n| Standardisierung und Komponenten aus den Trainingsdaten lernen, dann auf neue Daten anwenden | Sonst fliesst Information aus den Testdaten in die Transformation ein. In R über `predict(pca, neue_daten)`, in Python über `pca.transform()` mit demselben `StandardScaler`. |\n| Nicht nach der Zielvariable auswählen | Die Komponentenanalyse kennt die Zielvariable nicht. Die erste Komponente muss für eine Vorhersage nicht die nützlichste sein; unter Umständen ist es die vierte. |\n| Wenn Deutbarkeit zählt, lieber Variablen weglassen als Komponenten bilden | Eine weggelassene Variable erklärt sich von selbst, eine Komponente nicht. |\n\n> Für die weitere Auswertung wurden die ersten beiden Komponenten verwendet\n> (zusammen 80.4 Prozent der Varianz, konstruktionsbedingt unkorreliert). Die\n> Standardisierung und die Komponentengewichte wurden auf den Trainingsdaten\n> bestimmt und unverändert auf die übrigen Daten angewendet.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nDie erste Komponente erklärt 96.7 Prozent der Varianz und lädt mit 0.998 auf\neiner einzigen Variablen. Was ist die naheliegendste Erklärung?\n\n- [x] Es wurde nicht standardisiert, und diese Variable hat die grösste Varianz ~\n      Richtig. Ohne Standardisierung entscheidet die Einheit. Ein Blick auf die\n      Varianzen der Ausgangsvariablen bestätigt das sofort, siehe Beispiel 2.\n- [ ] Die Variable ist die wichtigste im Datensatz ~ Wichtigkeit lässt sich aus\n      Streuung nicht ableiten.\n- [ ] Die übrigen Variablen sind fehlerhaft ~ Sie sind nur im Vergleich\n      kleinskaliert.\n:::\n\n::: {.quiz}\nIn Beispiel 1 hat die dritte Komponente einen Eigenwert von 0.999 und lädt mit\n0.999 auf der Luftfeuchte. Was bedeutet das?\n\n- [x] Die Luftfeuchte hängt mit keiner anderen Variablen zusammen und bildet\n      ihre eigene Komponente ~ Richtig. Bei standardisierten Daten trägt jede\n      Variable genau 1 bei. Eine Variable ohne Zusammenhang zu den übrigen\n      behält ihren Beitrag vollständig und erscheint als eigene Komponente mit\n      Eigenwert 1. Sie zu behalten hiesse, dieselbe Variable unter neuem Namen\n      mitzuführen.\n- [ ] Die Komponente ist besonders wichtig, weil ihr Eigenwert genau 1 beträgt ~\n      Eigenwert 1 ist keine Auszeichnung, sondern genau der Beitrag einer\n      einzelnen Variablen.\n- [ ] Die Luftfeuchte wurde falsch skaliert ~ Sie ist standardisiert wie alle\n      anderen; das Ergebnis liegt an ihrer fehlenden Korrelation.\n:::\n\n::: {.quiz}\nIn einem zweiten Lauf haben alle Ladungen der ersten Komponente das umgekehrte\nVorzeichen. Was folgt daraus?\n\n- [x] Nichts, das Vorzeichen einer Komponente ist beliebig ~ Richtig. Eine\n      Komponente und ihr Negativ beschreiben dieselbe Richtung. Für die Deutung\n      dreht man die Vorzeichen so, dass sie sich gut beschreiben lässt.\n- [ ] Die Analyse ist instabil ~ Instabil wären wechselnde Ladungsmuster, nicht\n      ein Vorzeichenwechsel.\n- [ ] Die Daten haben sich geändert ~ Der Wechsel tritt auch bei identischen\n      Daten auf.\n:::\n\n::: {.quiz}\nAlle sechs Eigenwerte liegen zwischen 0.85 und 1.15, drei davon über 1. Das\nKaiser-Kriterium empfiehlt also drei Komponenten. Was ist zu tun?\n\n- [ ] Drei Komponenten behalten, das Kriterium ist eindeutig ~ Es ist eindeutig\n      und trotzdem falsch. Bei unkorrelierten Variablen streuen die Eigenwerte um\n      1, und etwa die Hälfte landet darüber.\n- [x] Keine Reduktion vornehmen, es gibt keine gemeinsame Struktur ~ Richtig.\n      Gleichverteilte Eigenwerte bedeuten unkorrelierte Variablen. Die Analyse\n      liefert dann nur eine Drehung, und die Komponenten sind nicht deutbar.\n      Sichtbar ist das schon in der Korrelationsmatrix.\n- [ ] Auf Kovarianzen statt Korrelationen umstellen ~ Das verschiebt nur das\n      Gewicht zur Variablen mit der grössten Varianz.\n:::\n\n::: {.quiz}\nDie Varianz der ersten Komponentenwerte beträgt 2.912, und der Eigenwert der\nersten Komponente beträgt ebenfalls 2.912. Zufall?\n\n- [x] Nein, der Eigenwert ist definiert als die Varianz der Komponentenwerte ~\n      Richtig. Beide Zahlen sind dieselbe Grösse, einmal aus der\n      Eigenwertzerlegung und einmal direkt aus den transformierten Daten\n      berechnet.\n- [ ] Ja, bei anderen Daten fallen die Werte auseinander ~ Die Gleichheit gilt\n      immer.\n- [ ] Nein, weil standardisiert wurde ~ Die Standardisierung sorgt dafür, dass\n      sich die Eigenwerte auf die Anzahl Variablen summieren, nicht für diese\n      Gleichheit.\n:::\n\n::: {.quiz}\nWarum sind Komponenten für ein anschliessendes Clustering nützlich, aber nicht\numsonst?\n\n- [x] Sie sind unkorreliert, dafür schlechter deutbar ~ Richtig. Korrelierte\n      Ausgangsvariablen gehen mehrfach in die Distanz ein; Komponenten\n      verhindern das. Die Gruppen müssen dann aber über die Ladungen\n      zurückübersetzt werden.\n- [ ] Sie sind robuster gegen Ausreisser ~ Im Gegenteil, Ausreisser prägen die\n      Richtungen.\n- [ ] Sie machen eine Standardisierung überflüssig ~ Die Standardisierung\n      geschieht davor und ist Voraussetzung.\n:::\n\n## Verlinkte Ressourcen\n\n- [An Introduction to Statistical Learning, Kapitel 12.2](https://www.statlearning.com/)\n- [R-Dokumentation zu `prcomp`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/prcomp.html)\n- [scikit-learn: PCA](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html)\n",
    "supporting": [
      "hauptkomponentenanalyse_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}