{
  "hash": "32b780adbed50b86f2f14705b95baf8f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Clustergüte\"\ndescription: \"Silhouette, Ellbogen und Gap-Statistik zur Beurteilung einer Lösung.\"\ncategories: [\"Clustering\", \"Modellvalidierung\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: methode\nstand: fertig\norder: 60\n---\n\n\n\n\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Wie viele Gruppen sind angemessen, und ist die gefundene Aufteilung mehr als eine Zerlegung von Rauschen? |\n| Zielvariable | keine |\n| Eingang | Daten samt einer oder mehreren Clusterlösungen |\n| Was die Methode liefert | Silhouettenwerte je Beobachtung und Gruppe, Verlauf der Streuung über k, Vergleich mit Zufallsdaten |\n| R-Funktion | `cluster::silhouette()`, `cluster::clusGap()` |\n| Python-Funktion | `silhouette_score()`, `silhouette_samples()`; Gap von Hand |\n| Verwandte Methoden | [k-Means](k-means.qmd), [hierarchisches Clustering](hierarchisches-clustering.qmd) |\n\n## Wann diese Methode, wann nicht\n\nJede Clusteranalyse endet mit zwei Fragen, die das Verfahren selbst nicht\nbeantwortet: Wie viele Gruppen, und gibt es überhaupt Gruppen? Diese Seite\nbehandelt die Werkzeuge dafür.\n\nWichtig ist die Grenze: Alle Masse hier sind **innere** Gütemasse. Sie\nbeurteilen, wie gut die Aufteilung zur Geometrie der Daten passt, nicht ob sie\ninhaltlich sinnvoll ist. Ein Clustering mit ausgezeichneter Silhouette kann\nfachlich wertlos sein, und eine mittelmässige Aufteilung kann genau die Segmente\nliefern, mit denen man arbeiten will.\n\n| Situation | Stattdessen |\n|---|---|\n| Es gibt bekannte Gruppen zum Abgleich | äussere Masse wie der bereinigte Rand-Index |\n| Die Gruppen sollen vorhergesagt werden | [Klassifikation](../regression/klassifikationsguete.qmd) mit Kreuzvalidierung |\n| Es geht um die Stabilität der Lösung | Wiederholung auf Teilstichproben, Bootstrap |\n| Die Gruppenzahl ist inhaltlich vorgegeben | keine Suche nötig, aber Beurteilung der Lösung trotzdem sinnvoll |\n\n## Grundidee und Modell\n\nDrei Werkzeuge, die verschiedene Fragen beantworten.\n\n**Silhouette** beurteilt jede Beobachtung einzeln:\n\n$$s_i = \\frac{b_i - a_i}{\\max(a_i, b_i)}$$\n\n| Bestandteil | Bedeutung |\n|---|---|\n| $a_i$ | mittlere Distanz zu den übrigen Mitgliedern der eigenen Gruppe |\n| $b_i$ | mittlere Distanz zur nächstgelegenen fremden Gruppe |\n| $s_i$ | Wert zwischen minus eins und eins |\n\nWerte nahe eins heissen: eigene Gruppe deutlich näher als die nächste fremde.\nWerte um null heissen: die Beobachtung liegt auf der Grenze. Negative Werte\nheissen: sie wäre in einer anderen Gruppe besser aufgehoben. Der Mittelwert über\nalle Beobachtungen ist ein Gesamtmass, das sich über verschiedene k vergleichen\nlässt.\n\n**Ellbogen** betrachtet die Streuung innerhalb der Gruppen über k. Diese sinkt\nimmer, aber der Zugewinn wird ab einem Punkt klein. Der Knick ist der Kandidat.\nDas Verfahren ist verbreitet und schwach: Der Knick ist oft nicht eindeutig.\n\n**Gap-Statistik** vergleicht die erreichte Streuung mit der, die sich in\nZufallsdaten gleicher Ausdehnung ergibt:\n\n$$\\text{Gap}(k) = \\overline{\\log W_k^{\\text{Zufall}}} - \\log W_k$$\n\n| Bestandteil | Bedeutung |\n|---|---|\n| $W_k$ | Streuung innerhalb der Gruppen bei k Gruppen, in den echten Daten |\n| $\\overline{\\log W_k^{\\text{Zufall}}}$ | Mittelwert desselben Werts über B Zufallsdatensätze, gleichmässig verteilt über denselben Wertebereich |\n| Gap | wie viel besser die echten Daten sich teilen lassen als reines Rauschen |\n\nDer grosse Vorteil: Die Gap-Statistik wird auch für **k = 1** berechnet. Sie kann\nals einzige der drei Methoden die Antwort \"eine Gruppe\", also **keine Struktur**,\nüberhaupt liefern.\n\nDie übliche Auswahlregel stammt von Tibshirani: Gewählt wird das **kleinste** k,\ndessen Gap mindestens so gross ist wie der Gap des nächsten k abzüglich dessen\nStandardfehler. So wird nicht auf zufällige Ausschläge reagiert.\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung | Vorgehen |\n|---|---|---|---|---|\n| Dieselbe Distanz wie beim Clustering | Gütemass und Verfahren beurteilen dasselbe | Distanzmass prüfen | Bewertung passt nicht zur Lösung | dasselbe Mass verwenden |\n| Standardisierte Daten | Kein Merkmal dominiert | Varianzen vergleichen | Silhouette misst nur die grösste Variable | vor dem Clustering standardisieren |\n| Kompakte Gruppenform | Silhouette bevorzugt kugelige Gruppen | Streudiagramm | Ringe und Ketten werden abgestraft, obwohl sie Gruppen sind | dichtebasierte Masse, oder Beurteilung im Bild |\n| Genügend Beobachtungen je Gruppe | Kleine Gruppen haben instabile Werte | Gruppengrössen | Silhouette schwankt stark | k verkleinern |\n| Mehrere Kriterien | Ein Mass allein entscheidet nicht | Silhouette, Ellbogen, Gap zusammen ansehen | Scheingenauigkeit | mindestens zwei Kriterien plus Inhalt |\n\n## Output lesen\n\nR:\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| `silhouette(...)[, \"sil_width\"]` | Silhouettenwert je Beobachtung | negative Werte markieren falsch zugeordnete Fälle |\n| Mittelwert der Silhouette | Gesamtmass für ein k | über 0.5 gilt als deutliche Struktur, unter 0.25 als kaum vorhanden |\n| `summary(silhouette(...))$clus.avg.widths` | Mittelwert je Gruppe | eine schwache Gruppe unter guten fällt hier auf |\n| `tot.withinss` | Streuung innerhalb der Gruppen | sinkt immer mit k, taugt nur für den Verlauf |\n| `clusGap(...)` | fertige Gap-Statistik je k mit Standardfehler | zieht die Referenzdaten selbst; braucht einen Startwert für Reproduzierbarkeit |\n| `maxSE(...)` | wendet die Auswahlregel auf eine Gap-Tabelle an | `method = \"Tibs2001SEmax\"` ist die Regel oben |\n\nPython:\n\n| Zugriff | Was er liefert | Unterschied zu R |\n|---|---|---|\n| `silhouette_score(X, labels)` | Mittelwert über alle Beobachtungen | in R der Mittelwert der Spalte `sil_width` |\n| `silhouette_samples(X, labels)` | Werte je Beobachtung | wie die Spalte in R |\n| `inertia_` | Streuung innerhalb | wie `tot.withinss` |\n| keine Gap-Statistik | selbst implementieren, siehe Beispiel 4 | in R über `clusGap` enthalten |\n| kein Silhouettendiagramm | selbst zeichnen, siehe Beispiel 2 | in R über `plot(silhouette(...))` |\n\nDie Faustregeln zur Silhouette sind Konvention, keine Grenzwerte mit\nstatistischer Bedeutung. Sie helfen beim Einordnen, ersetzen aber nicht den Blick\nauf die Gruppen.\n\n## Interpretationsfallen\n\n- **Ein Optimum ist kein Beleg für Struktur.** Silhouette und Ellbogen liefern\n  immer ein bestes k, auch in Rauschen. Nur die Gap-Statistik kann \"eine Gruppe\"\n  empfehlen.\n- **Die Streuung innerhalb taugt nicht als Gütemass.** Sie sinkt zwangsläufig mit\n  k; brauchbar ist nur ihr Verlauf.\n- **Der Ellbogen ist oft nicht eindeutig.** Wo drei Personen drei verschiedene\n  Knicke sehen, trägt das Kriterium nichts.\n- **Der Silhouettenmittelwert verdeckt Unterschiede.** Eine schlecht abgegrenzte\n  Gruppe fällt nur im Diagramm oder in den Gruppenmittelwerten auf.\n- **Silhouette bevorzugt kugelige Gruppen.** Bei ringförmigen oder langgezogenen\n  Strukturen bestraft sie richtige Lösungen.\n- **Innere Masse sagen nichts über Nutzen.** Ob Segmente brauchbar sind,\n  entscheidet die Sache, nicht die Geometrie.\n- **Grenzwerte sind Konvention.** 0.5 als Schwelle für deutliche Struktur ist\n  eine Faustregel, die von Dimensionszahl und Datenlage abhängt.\n\n## Ergebnis berichten\n\nVorlage für den Ergebnissatz:\n\n> Die Gruppenzahl wurde anhand von [Kriterien] auf k = [k] festgelegt (n = [n],\n> [Verfahren], standardisierte Merkmale). Die mittlere Silhouette beträgt [Wert],\n> je Gruppe [Werte]; [Anzahl] Beobachtungen haben einen negativen Wert. Die\n> Gap-Statistik empfiehlt [k]. Auf Teilstichproben bleibt die Silhouette bei\n> [Bereich].\n\nGenannt werden: alle herangezogenen Kriterien und ihre Ergebnisse, nicht nur das\ngewählte; die mittlere Silhouette gesamt und je Gruppe; Anzahl negativer Werte;\nGruppengrössen; und die Feststellung, dass überhaupt Struktur vorliegt.\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt der inneren Gütemasse |\n|---|---|\n| Bereinigter Rand-Index | es gibt bekannte Gruppen zum Abgleich |\n| Stabilitätsanalyse auf Teilstichproben | die Frage ist, ob die Lösung reproduzierbar ist |\n| [Klassifikationsgüte](../regression/klassifikationsguete.qmd) | die Gruppen sind bekannt und werden vorhergesagt |\n| Informationskriterien | modellbasiertes Clustering, etwa Gaussian-Mixture |\n| Inhaltliche Beurteilung | immer zusätzlich, nie ersetzbar |\n\n## Beispiele\n\nAlle Beispiele arbeiten mit denselben 270 Kunden wie die Seiten zu\n[k-Means](k-means.qmd) und zum\n[hierarchischen Clustering](hierarchisches-clustering.qmd): Besuche und Umsatz,\ndrei eingebaute Gruppen von 120, 90 und 60 Personen, z-standardisiert.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Ellbogen und Silhouette über k\n\n#### Frage und Datenlage\n\nFür jedes k von 2 bis 7 werden drei Kennzahlen nebeneinandergestellt: die\nStreuung innerhalb der Gruppen, die mittlere Silhouette und die kleinste\nGruppengrösse. Welche davon kann k begründen?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkennzahlen <- t(sapply(2:7, function(k) {\n  lauf <- kmeans(skaliert, centers = k, nstart = 25)\n  sil <- silhouette(lauf$cluster, distanzen)\n  c(k = k,\n    within = round(lauf$tot.withinss, 1),\n    silhouette = round(mean(sil[, \"sil_width\"]), 3),\n    kleinste_gruppe = min(lauf$size))\n}))\n\nkennzahlen\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     k within silhouette kleinste_gruppe\n[1,] 2  257.3      0.554              59\n[2,] 3   88.3      0.626              58\n[3,] 4   71.2      0.506              49\n[4,] 5   60.9      0.441              24\n[5,] 6   51.7      0.362              24\n[6,] 7   44.0      0.360              27\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nplot(kennzahlen[, \"k\"], kennzahlen[, \"within\"], type = \"b\", pch = 16,\n     xlab = \"k\", ylab = \"Streuung innerhalb\", main = \"Ellbogen\")\nplot(kennzahlen[, \"k\"], kennzahlen[, \"silhouette\"], type = \"b\", pch = 16,\n     xlab = \"k\", ylab = \"mittlere Silhouette\", main = \"Silhouette\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 1: links der Verlauf der Streuung innerhalb der Gruppen, rechts die mittlere Silhouette.](clusterguete_files/figure-html/fig-b1-cg-r-1.png){#fig-b1-cg-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nzeilen = []\nfor k in range(2, 8):\n    lauf = KMeans(n_clusters=k, n_init=25, random_state=2026).fit(skaliert)\n    zeilen.append({\n        \"k\": k,\n        \"within\": round(float(lauf.inertia_), 1),\n        \"silhouette\": round(float(silhouette_score(skaliert, lauf.labels_)), 3),\n        \"kleinste_gruppe\": int(np.bincount(lauf.labels_).min()),\n    })\n\ntabelle = pd.DataFrame(zeilen)\nprint(tabelle.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n k  within  silhouette  kleinste_gruppe\n 2   258.3       0.554               59\n 3    88.6       0.626               58\n 4    71.5       0.506               49\n 5    61.1       0.440               27\n 6    52.1       0.441               24\n 7    44.0       0.360               27\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.4))\nachsen[0].plot(tabelle[\"k\"], tabelle[\"within\"], \"o-\", color=\"#2166ac\")\nachsen[0].set_xlabel(\"k\")\nachsen[0].set_ylabel(\"Streuung innerhalb\")\nachsen[0].set_title(\"Ellbogen\")\nachsen[1].plot(tabelle[\"k\"], tabelle[\"silhouette\"], \"o-\", color=\"#b2182b\")\nachsen[1].set_xlabel(\"k\")\nachsen[1].set_ylabel(\"mittlere Silhouette\")\nachsen[1].set_title(\"Silhouette\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselben beiden Verläufe in Python.](clusterguete_files/figure-html/fig-b1-cg-py-1.png){#fig-b1-cg-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(\"bestes k nach Silhouette:\",\n      int(tabelle.loc[tabelle[\"silhouette\"].idxmax(), \"k\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbestes k nach Silhouette: 3\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| k | Streuung innerhalb | mittlere Silhouette | kleinste Gruppe |\n|---|---|---|---|\n| 2 | 258.3 | 0.554 | 59 |\n| **3** | **88.6** | **0.626** | 58 |\n| 4 | 71.5 | 0.506 | 49 |\n| 5 | 61.1 | 0.440 | 27 |\n| 6 | 52.1 | 0.441 | 24 |\n| 7 | 44.0 | 0.360 | 27 |\n\n| Spalte | Verlauf | Was daraus folgt |\n|---|---|---|\n| **Streuung innerhalb** | fällt monoton, von 258 auf 44 | Sie kann k **nicht** begründen, denn sie fällt immer. Brauchbar ist nur die Form des Verlaufs: der Absturz von 258 auf 89, danach ein flaches Auslaufen. Das ist der Ellbogen bei k = 3. |\n| **mittlere Silhouette** | steigt auf 0.626 und **fällt danach** | Das entscheidende Verhalten: Anders als die Streuung hat sie ein echtes Maximum. Ein zu grosses k zerschneidet vorhandene Gruppen, die Beobachtungen rücken näher an fremde Gruppen, und der Wert sinkt. |\n| **kleinste Gruppe** | 59, 58, 49, 27, 24, 27 | Ab k = 5 entstehen Gruppen von unter 30 Kunden. Kein Gütemass, sondern ein praktisches Argument: Wovon man nicht sinnvoll berichten kann, das braucht man nicht zu trennen. |\n| Silhouette bei k = 6 | 0.441, minimal über k = 5 mit 0.440 | Ein Ausschlag ohne Bedeutung. Er zeigt sich auch daran, dass R hier 0.362 liefert: Ab k = 5 existieren mehrere fast gleich gute Aufteilungen, und welche gefunden wird, hängt vom Startwert ab. Ein Grund, nie das nackte Maximum zu nehmen, sondern den Verlauf anzusehen. |\n\n::: {.note-box}\nDer **Ellbogen** ist das bekannteste und schwächste der Kriterien. Hier ist er\ndeutlich, weil die Struktur klar ist; in echten Daten sieht die Kurve oft aus wie\neine gleichmässige Rutsche, und dann sehen drei Personen drei verschiedene\nKnicke. Die **Silhouette** ist besser, weil sie ein Optimum hat statt einer\nNeigung.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Der Verlauf der Streuung innerhalb der Gruppen knickt nach k = 3 deutlich ab\n> (258.3 → 88.6 → 71.5), und die mittlere Silhouette hat bei k = 3 ihr Maximum\n> (0.626). Beide Kriterien sprechen für drei Gruppen.\n\n### Beispiel 2: Die Silhouette im Detail\n\n#### Frage und Datenlage\n\nDer Mittelwert von 0.626 verdeckt, wie sich die Werte auf die drei Gruppen\nverteilen. Das Silhouettendiagramm zeigt jede Beobachtung einzeln.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkm3 <- kmeans(skaliert, centers = 3, nstart = 25)\nsil3 <- silhouette(km3$cluster, distanzen)\n\nplot(sil3, col = c(\"#2166ac\", \"#b2182b\", \"#1b7837\"), border = NA,\n     main = \"Silhouette, k = 3\")\n\nround(summary(sil3)$clus.avg.widths, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    1     2     3 \n0.636 0.576 0.707 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(sil3)$clus.sizes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncl\n  1   2   3 \n 97 115  58 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(mean(sil3[, \"sil_width\"]), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.626\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(sil3[, \"sil_width\"] < 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 2: Silhouettendiagramm für k = 3. Jeder Balken ist eine Beobachtung, gruppiert und absteigend sortiert.](clusterguete_files/figure-html/fig-b2-cg-r-3.png){#fig-b2-cg-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nkm3 = KMeans(n_clusters=3, n_init=25, random_state=2026).fit(skaliert)\nwerte = silhouette_samples(skaliert, km3.labels_)\n\nfig, achse = plt.subplots(figsize=(7, 4))\nunten = 0\nfor nummer, farbe in zip(range(3), [\"#2166ac\", \"#b2182b\", \"#1b7837\"]):\n    teil = np.sort(werte[km3.labels_ == nummer])\n    achse.barh(range(unten, unten + len(teil)), teil, height=1.0, color=farbe)\n    unten += len(teil) + 8\nachse.axvline(werte.mean(), linestyle=\"--\", color=\"black\", linewidth=0.8)\nachse.set_xlabel(\"Silhouettenwert\")\nachse.set_ylabel(\"Beobachtungen, nach Gruppe\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dasselbe Diagramm in Python, von Hand gezeichnet.](clusterguete_files/figure-html/fig-b2-cg-py-1.png){#fig-b2-cg-py width=100%}\n:::\n\n```{.python .cell-code}\nfor i in range(3):\n    teil = werte[km3.labels_ == i]\n    print(f\"Gruppe {i + 1}: n = {len(teil):3d}  Mittel = {teil.mean():.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGruppe 1: n =  58  Mittel = 0.707\nGruppe 2: n =  97  Mittel = 0.636\nGruppe 3: n = 115  Mittel = 0.576\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Gesamtmittel:\", round(float(werte.mean()), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGesamtmittel: 0.626\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"negative Werte:\", int((werte < 0).sum()))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnegative Werte: 0\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Gruppe | n | mittlere Silhouette | Beschreibung (aus [k-Means](k-means.qmd)) |\n|---|---|---|---|\n| Grosseinkäufer | 58 | **0.707** | am besten abgegrenzt: wenige Besuche bei hohem Umsatz, in beiden Merkmalen weit weg von den anderen |\n| Gelegenheitskunden | 97 | 0.636 | |\n| Stammkunden | 115 | **0.576** | am schwächsten abgegrenzt: liegt zwischen den beiden anderen und hat deshalb die kürzeste Distanz zur nächsten fremden Gruppe |\n| gesamt | 270 | **0.626** | |\n| negative Werte | **0** | | Keine einzige Beobachtung wäre in einer anderen Gruppe besser aufgehoben. |\n\nDrei Dinge lassen sich im Diagramm ablesen:\n\n| Merkmal im Bild | Bedeutung |\n|---|---|\n| **Breite** der Blöcke | die Gruppengrössen |\n| **Höhe** je Block | wie gut die Gruppe abgegrenzt ist. Ein deutlich flacherer Block verrät eine schwache Gruppe, auch wenn der Gesamtmittelwert gut aussieht. |\n| Balken **links der Null** | Beobachtungen, die einer fremden Gruppe näher sind als der eigenen. Wenige sind normal, viele ein Hinweis auf eine schlechte Aufteilung. |\n\n::: {.note-box}\nDie Spanne von 0.576 bis 0.707 ist der eigentliche Ertrag dieses Beispiels: Die\ndrei Gruppen sind **verschieden gut** abgegrenzt, und der Mittelwert sagt das\nnicht. Bei einer Lösung, in der eine Gruppe bei 0.15 läge und zwei bei 0.70, wäre\nder Mittelwert immer noch gut und die Lösung trotzdem fragwürdig.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die mittlere Silhouette beträgt 0.63 (n = 270, k = 3), je Gruppe 0.71, 0.64 und\n> 0.58. Keine Beobachtung hat einen negativen Wert. Die Gruppen sind damit\n> durchgehend deutlich abgegrenzt; am schwächsten die grösste Gruppe, die\n> geometrisch zwischen den beiden anderen liegt.\n\n### Beispiel 3: Ein Optimum in reinem Rauschen\n\n#### Frage und Datenlage\n\nDer wichtigste Fall dieser Seite. 270 Beobachtungen aus einer einzigen Wolke,\nalso ohne jede Gruppenstruktur. Was sagen Silhouette und Ellbogen dazu?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrauschen <- scale(matrix(normalwerte(17017, 540), ncol = 2, byrow = TRUE))\nd_rauschen <- dist(rauschen)\n\nt(sapply(2:6, function(k) {\n  lauf <- kmeans(rauschen, centers = k, nstart = 25)\n  c(k = k,\n    within = round(lauf$tot.withinss, 1),\n    silhouette = round(mean(silhouette(lauf$cluster,\n                                       d_rauschen)[, \"sil_width\"]), 3))\n}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     k within silhouette\n[1,] 2  356.0      0.331\n[2,] 3  244.2      0.344\n[3,] 4  187.7      0.337\n[4,] 5  156.7      0.311\n[5,] 6  127.0      0.333\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nrauschen = StandardScaler().fit_transform(\n    normalwerte(17017, 540).reshape(270, 2))\n\nfor k in range(2, 7):\n    lauf = KMeans(n_clusters=k, n_init=25, random_state=17).fit(rauschen)\n    print(f\"k = {k} | within: {lauf.inertia_:6.1f} \"\n          f\"| Silhouette: {silhouette_score(rauschen, lauf.labels_):.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nk = 2 | within:  357.3 | Silhouette: 0.331\nk = 3 | within:  245.1 | Silhouette: 0.344\nk = 4 | within:  188.4 | Silhouette: 0.337\nk = 5 | within:  157.1 | Silhouette: 0.315\nk = 6 | within:  127.8 | Silhouette: 0.333\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| k | Silhouette im Rauschen | Silhouette in den Kundendaten |\n|---|---|---|\n| 2 | 0.331 | 0.554 |\n| 3 | **0.344** | **0.626** |\n| 4 | 0.337 | 0.506 |\n| 5 | 0.315 | 0.440 |\n| 6 | 0.333 | 0.441 |\n\n| Beobachtung | Deutung |\n|---|---|\n| Es **gibt** ein bestes k, nämlich 3 mit 0.344 | Und es ist reiner Zufall. Die Methode liefert immer ein Optimum, weil sie nach dem besten k fragt und nicht danach, ob es überhaupt Gruppen gibt. |\n| Der Wert liegt **deutlich über null** | 0.344 sieht nicht nach \"nichts\" aus. Nach der verbreiteten Faustregel wäre das eine \"schwache, aber erkennbare Struktur\". Es ist keine. |\n| Der Verlauf ist **flach** | 0.331, 0.344, 0.337, 0.315, 0.333, die Werte liegen alle beieinander. Bei den Kundendaten reicht die Spanne von 0.360 bis 0.626. Ein flacher Verlauf ohne ausgeprägtes Maximum ist das Warnzeichen. |\n| Absolute Schwellen versagen | Der Silhouettenwert hängt auch von der Anzahl Dimensionen ab; in höherdimensionalen Daten sind selbst 0.3 im Rauschen keine Seltenheit. |\n\n::: {.note-box}\n**Die Reihenfolge der Fragen entscheidet.** Wer zuerst nach der Gruppenzahl\nfragt, bekommt immer eine Antwort und findet immer Segmente. Sie lassen sich\nhinterher sogar beschreiben, weil jede Aufteilung Mittelwertunterschiede erzeugt.\nErst kommt die Frage, **ob** Struktur vorliegt und dafür braucht es die\nGap-Statistik aus Beispiel 4.\n:::\n\n#### Interpretation\n\nSilhouette und Ellbogen sind Werkzeuge zur Wahl von k **unter der Annahme**, dass\nGruppen existieren. Diese Annahme prüfen sie nicht.\n\n### Beispiel 4: Die Gap-Statistik entscheidet\n\n#### Frage und Datenlage\n\nDie Gap-Statistik vergleicht die erreichte Streuung mit derjenigen in\nZufallsdaten gleicher Ausdehnung. Als einzige der drei Methoden wird sie auch für\nk = 1 berechnet und kann damit \"keine Struktur\" sagen. Angewendet wird sie auf\nbeide Datensätze: die Kunden und das Rauschen aus Beispiel 3.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngap_statistik <- function(daten, k_max, B = 20, saat = 98765) {\n  unten <- apply(daten, 2, min)\n  oben <- apply(daten, 2, max)\n  n <- nrow(daten)\n  p <- ncol(daten)\n\n  # B Referenzdatensaetze, gleichverteilt ueber denselben Wertebereich\n  referenzen <- lapply(0:(B - 1), function(b) {\n    u <- matrix(lehmer(saat + b * 7, n * p), nrow = n, byrow = TRUE)\n    sweep(sweep(u, 2, oben - unten, \"*\"), 2, unten, \"+\")\n  })\n\n  streuung <- function(x, k) kmeans(x, centers = k, nstart = 25)$tot.withinss\n\n  t(sapply(1:k_max, function(k) {\n    log_w <- log(streuung(daten, k))\n    log_ref <- sapply(referenzen, function(r) log(streuung(r, k)))\n    c(k = k,\n      gap = round(mean(log_ref) - log_w, 3),\n      SE = round(sd(log_ref) * sqrt(1 + 1 / B), 3))\n  }))\n}\n\n# Auswahlregel nach Tibshirani: das kleinste k, das den naechsten Gap\n# abzueglich dessen Standardfehler erreicht\nwaehle_k <- function(tab) {\n  for (i in 1:(nrow(tab) - 1)) {\n    if (tab[i, \"gap\"] >= tab[i + 1, \"gap\"] - tab[i + 1, \"SE\"]) return(tab[i, \"k\"])\n  }\n  tab[nrow(tab), \"k\"]\n}\n\ngap_kunden <- gap_statistik(skaliert, 7)\ngap_kunden\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     k   gap    SE\n[1,] 1 0.353 0.042\n[2,] 2 0.577 0.042\n[3,] 3 1.192 0.041\n[4,] 4 0.973 0.037\n[5,] 5 0.913 0.031\n[6,] 6 0.886 0.031\n[7,] 7 0.882 0.035\n```\n\n\n:::\n\n```{.r .cell-code}\nwaehle_k(gap_kunden)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nk \n3 \n```\n\n\n:::\n\n```{.r .cell-code}\ngap_rauschen <- gap_statistik(rauschen, 6)\ngap_rauschen\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     k   gap    SE\n[1,] 1 1.092 0.044\n[2,] 2 0.904 0.039\n[3,] 3 0.885 0.038\n[4,] 4 0.743 0.038\n[5,] 5 0.683 0.031\n[6,] 6 0.690 0.033\n```\n\n\n:::\n\n```{.r .cell-code}\nwaehle_k(gap_rauschen)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nk \n1 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndef gap_statistik(daten, k_max, B=20, saat=98765):\n    unten, oben = daten.min(axis=0), daten.max(axis=0)\n    n, p = daten.shape\n\n    referenzen = [unten + (oben - unten) * lehmer(saat + b * 7, n * p).reshape(n, p)\n                  for b in range(B)]\n\n    def streuung(x, k):\n        return KMeans(n_clusters=k, n_init=25, random_state=2026).fit(x).inertia_\n\n    ausgabe = []\n    for k in range(1, k_max + 1):\n        log_w = np.log(streuung(daten, k))\n        log_ref = np.array([np.log(streuung(r, k)) for r in referenzen])\n        ausgabe.append({\"k\": k,\n                        \"gap\": round(float(log_ref.mean() - log_w), 3),\n                        \"SE\": round(float(log_ref.std(ddof=1)\n                                          * np.sqrt(1 + 1 / B)), 3)})\n    return pd.DataFrame(ausgabe)\n\n\ndef waehle_k(tab):\n    for i in range(len(tab) - 1):\n        if tab[\"gap\"][i] >= tab[\"gap\"][i + 1] - tab[\"SE\"][i + 1]:\n            return int(tab[\"k\"][i])\n    return int(tab[\"k\"].iloc[-1])\n\n\ngap_kunden = gap_statistik(skaliert, 7)\nprint(gap_kunden.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n k   gap    SE\n 1 0.353 0.042\n 2 0.577 0.042\n 3 1.192 0.041\n 4 0.973 0.037\n 5 0.913 0.031\n 6 0.883 0.032\n 7 0.881 0.036\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"gewähltes k (Kunden):\", waehle_k(gap_kunden))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngewähltes k (Kunden): 3\n```\n\n\n:::\n\n```{.python .cell-code}\ngap_rauschen = gap_statistik(rauschen, 6)\nprint(gap_rauschen.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n k   gap    SE\n 1 1.092 0.044\n 2 0.904 0.039\n 3 0.885 0.038\n 4 0.743 0.038\n 5 0.683 0.031\n 6 0.689 0.033\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"gewähltes k (Rauschen):\", waehle_k(gap_rauschen))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngewähltes k (Rauschen): 1\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nKundendaten:\n\n| k | 1 | 2 | **3** | 4 | 5 | 6 | 7 |\n|---|---|---|---|---|---|---|---|\n| Gap | 0.353 | 0.577 | **1.192** | 0.973 | 0.913 | 0.883 | 0.881 |\n| SE | 0.042 | 0.042 | 0.041 | 0.037 | 0.031 | 0.032 | 0.036 |\n\nRauschen:\n\n| k | **1** | 2 | 3 | 4 | 5 | 6 |\n|---|---|---|---|---|---|---|\n| Gap | **1.092** | 0.904 | 0.885 | 0.743 | 0.683 | 0.689 |\n| SE | 0.044 | 0.039 | 0.038 | 0.038 | 0.031 | 0.033 |\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Kunden, Gap bei k = 3 | **1.192**, klar der höchste | Die echten Daten lassen sich bei drei Gruppen erheblich besser teilen als gleichmässig gestreute Zufallsdaten desselben Wertebereichs. |\n| Kunden, Auswahlregel | **k = 3** | Bei k = 1 und k = 2 liegt der Gap unter dem des jeweils nächsten k abzüglich SE, die Regel geht also weiter. Bei k = 3 ist 1.192 grösser als 0.973 - 0.037, also wird gestoppt. |\n| Rauschen, Gap bei k = 1 | **1.092**, der höchste Wert | Die Aufteilung in mehr als eine Gruppe verbessert **nichts** gegenüber Zufallsdaten. |\n| Rauschen, Auswahlregel | **k = 1** | Die einzige der drei Methoden, die diese Antwort überhaupt geben kann. Ellbogen und Silhouette haben in Beispiel 3 fröhlich k = 3 empfohlen. |\n| Standardfehler | um 0.03 bis 0.04 | Die Streuung über die B = 20 Referenzdatensätze. Er verhindert, dass die Regel auf zufällige Ausschläge reagiert. |\n\n::: {.note-box}\nWarum die Referenzdaten **gleichverteilt** sind und nicht normalverteilt: Die\nGleichverteilung über den Wertebereich ist die strukturloseste Verteilung, die\ndenselben Raum füllt. Eine Normalverteilung hätte selbst eine Verdichtung in der\nMitte, also bereits eine Art Struktur.\n\nR bringt das Verfahren als `cluster::clusGap()` fertig mit, samt `maxSE()` für\ndie Auswahlregel. Hier ist es von Hand implementiert, damit R und Python\ndieselben Zahlen liefern: `clusGap()` zieht seine Referenzdaten zufällig, die\nFunktion oben deterministisch.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Gap-Statistik (B = 20 gleichverteilte Referenzdatensätze) erreicht ihr\n> Maximum bei k = 3 (Gap 1.19, SE 0.04); die Auswahlregel nach Tibshirani\n> bestätigt k = 3. In den strukturlosen Vergleichsdaten empfiehlt dieselbe\n> Rechnung k = 1, obwohl Silhouette und Ellbogen dort ein Optimum bei k = 3\n> anzeigen.\n\n### Beispiel 5: Hält die Lösung auch auf anderen Daten?\n\n#### Frage und Datenlage\n\nAlle bisherigen Masse beurteilen **eine** Aufteilung auf **einem** Datensatz. Sie\nsagen nichts darüber, ob dieselbe Lösung bei leicht anderen Daten wieder\nentstünde. Das prüft man durch Wiederholung auf Teilstichproben: 20-mal 80\nProzent der Kunden, jeweils neu geclustert.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstabilitaet <- t(sapply(0:19, function(b) {\n  auswahl <- order(lehmer(6000 + b * 3, nrow(skaliert)))[1:216]\n  teil <- skaliert[auswahl, ]\n  lauf <- kmeans(teil, centers = 3, nstart = 25)\n  c(silhouette = mean(silhouette(lauf$cluster, dist(teil))[, \"sil_width\"]),\n    kleinste_gruppe = min(lauf$size))\n}))\n\nround(c(mittel = mean(stabilitaet[, \"silhouette\"]),\n        min = min(stabilitaet[, \"silhouette\"]),\n        max = max(stabilitaet[, \"silhouette\"]),\n        sd = sd(stabilitaet[, \"silhouette\"])), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmittel    min    max     sd \n0.6271 0.6067 0.6518 0.0118 \n```\n\n\n:::\n\n```{.r .cell-code}\nrange(stabilitaet[, \"kleinste_gruppe\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 41 53\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nwerte_stab, kleinste = [], []\nfor b in range(20):\n    auswahl = np.argsort(lehmer(6000 + b * 3, len(skaliert)))[:216]\n    teil = skaliert[auswahl]\n    lauf = KMeans(n_clusters=3, n_init=25, random_state=5).fit(teil)\n    werte_stab.append(silhouette_score(teil, lauf.labels_))\n    kleinste.append(int(np.bincount(lauf.labels_).min()))\n\nwerte_stab = np.array(werte_stab)\nprint({\"mittel\": round(float(werte_stab.mean()), 4),\n       \"min\": round(float(werte_stab.min()), 4),\n       \"max\": round(float(werte_stab.max()), 4),\n       \"sd\": round(float(werte_stab.std(ddof=1)), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'mittel': 0.6271, 'min': 0.6067, 'max': 0.6518, 'sd': 0.0118}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"kleinste Gruppe:\", min(kleinste), \"bis\", max(kleinste))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nkleinste Gruppe: 41 bis 53\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Mittelwert über 20 Teilstichproben | **0.627** | Praktisch identisch mit den 0.626 auf den vollen Daten. |\n| Spanne | **0.6067 bis 0.6518** | Eine Breite von 0.045. Alle 20 Läufe liegen deutlich über der Faustregel von 0.5. |\n| Standardabweichung | **0.0118** | Weniger als zwei Hundertstel. Die Lösung hängt nicht an einzelnen Beobachtungen. |\n| kleinste Gruppe | **41 bis 53** | Zu erwarten wären rund 80 Prozent von 58, also etwa 46. Die Schwankung passt zur Ziehung und nicht zu einer wechselnden Aufteilung. Dass die Grössenverhältnisse erhalten bleiben, ist wichtiger noch als der Kennzahlwert. |\n\n::: {.note-box}\nWas ein instabiles Ergebnis aussähe: eine Spanne von etwa 0.35 bis 0.65, oder\nGruppengrössen, die zwischen den Läufen zwischen 10 und 90 springen. Dann hinge\ndie Aufteilung an wenigen Beobachtungen, und das gehört in den Bericht, auch\nwenn der Wert auf den vollen Daten gut aussieht.\n\nDie Silhouette ist dabei nur ein Stellvertreter. Aussagekräftiger, aber\naufwendiger ist der direkte Vergleich der Zuordnungen über den bereinigten\nRand-Index: Landen dieselben Kunden in denselben Gruppen?\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Auf 20 Teilstichproben zu je 80 Prozent bleibt die mittlere Silhouette bei\n> 0.61 bis 0.65 (Mittel 0.63, SD 0.01), und die Gruppengrössenverhältnisse\n> bleiben erhalten. Die Dreigruppenlösung ist damit stabil.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nIn strukturlosen Zufallsdaten ergibt die Silhouette ein Maximum von 0.344 bei\nk = 3. Was folgt daraus?\n\n- [x] Nichts über die Existenz von Gruppen ~ Richtig. Silhouette und Ellbogen\n      beantworten die Frage nach dem besten k unter der Annahme, dass Gruppen\n      existieren. Sie prüfen diese Annahme nicht und liefern deshalb auch in\n      Rauschen ein Optimum.\n- [ ] Es gibt eine schwache, aber erkennbare Struktur ~ Genau das legt der Wert\n      nahe, und genau das ist die Falle. Die Daten stammen aus einer einzigen\n      Wolke.\n- [ ] Die Daten müssen standardisiert werden ~ Sie waren es bereits.\n:::\n\n::: {.quiz}\nWelches der drei Kriterien kann die Antwort \"keine Gruppenstruktur\" liefern?\n\n- [x] Die Gap-Statistik ~ Richtig, weil sie als einzige auch für k = 1 berechnet\n      wird und mit Zufallsdaten derselben Ausdehnung vergleicht. Ist der Gap bei\n      k = 1 am grössten, liegt keine Struktur vor.\n- [ ] Die Silhouette ~ Sie ist für k = 1 nicht definiert; es gibt dann keine\n      nächste fremde Gruppe.\n- [ ] Der Ellbogen ~ Die Streuung innerhalb sinkt mit k, ganz gleich ob Gruppen\n      existieren.\n:::\n\n::: {.quiz}\nDie mittlere Silhouette beträgt 0.62. Je Gruppe ergeben sich 0.71, 0.64 und 0.58.\nWas ist die Lehre daraus?\n\n- [x] Die Gruppen sind unterschiedlich gut abgegrenzt, und der Mittelwert zeigt\n      das nicht ~ Richtig. Hier ist die Spanne harmlos; läge eine Gruppe bei 0.15\n      und zwei bei 0.70, wäre der Mittelwert immer noch gut und die Lösung\n      trotzdem fragwürdig. Deshalb gehören die Werte je Gruppe in den Bericht.\n- [ ] Die Lösung ist schlecht, weil eine Gruppe unter 0.6 liegt ~ 0.58 ist ein\n      guter Wert; die Schwellen sind ohnehin Konvention.\n- [ ] Der Mittelwert wurde falsch berechnet ~ Er ist das mit den Gruppengrössen\n      gewichtete Mittel der Einzelwerte, nicht der Gruppenmittel.\n:::\n\n::: {.quiz}\nWarum sind die Referenzdaten der Gap-Statistik gleichverteilt und nicht\nnormalverteilt?\n\n- [x] Weil die Gleichverteilung über den Wertebereich die strukturloseste\n      Verteilung ist ~ Richtig. Eine Normalverteilung hätte eine Verdichtung in\n      der Mitte, also bereits eine Art Struktur, und der Vergleich wäre zu\n      milde.\n- [ ] Weil sie schneller zu erzeugen ist ~ Der Unterschied im Aufwand ist\n      vernachlässigbar.\n- [ ] Weil die echten Daten nicht normalverteilt sind ~ Die Verteilung der echten\n      Daten spielt für die Wahl der Referenz keine Rolle.\n:::\n\n::: {.quiz}\nAuf 20 Teilstichproben schwankt die mittlere Silhouette zwischen 0.61 und 0.65.\nWas sagt das?\n\n- [x] Die Lösung ist stabil, sie hängt nicht an einzelnen Beobachtungen ~\n      Richtig. Eine Spanne von 0.045 bei einem Mittel von 0.63 ist schmal.\n      Zusätzlich lohnt sich der Blick auf die Gruppengrössen: Bleiben auch die\n      Verhältnisse erhalten?\n- [ ] Die Silhouette ist unzuverlässig ~ Sie schwankt, weil die Daten wechseln,\n      nicht weil das Mass ungenau wäre.\n- [ ] Es hätten mehr Teilstichproben gezogen werden müssen ~ Bei dieser geringen\n      Streuung ändern mehr Ziehungen am Bild nichts.\n:::\n\n## Verlinkte Ressourcen\n\n- [An Introduction to Statistical Learning, Kapitel 12](https://www.statlearning.com/)\n- [cluster: silhouette und clusGap](https://cran.r-project.org/web/packages/cluster/cluster.pdf)\n- [scikit-learn: Bewertung von Clusterverfahren](https://scikit-learn.org/stable/modules/clustering.html#clustering-evaluation)\n",
    "supporting": [
      "clusterguete_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}