{
  "hash": "7b8a30abb8d9a3783a012cb8c68bcd37",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regressionsdiagnostik\"\ndescription: \"Residuen, Hebelwerte, Ausreisser, VIF und was man bei Verletzungen tut.\"\ncategories: [\"Regression\", \"Modelldiagnostik\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: methode\nstand: entwurf\norder: 30\n---\n\n\n\n\n\nDie vier Beispiele rechnen mit vier deterministisch konstruierten Datensätzen.\nSie unterscheiden sich in genau einer Eigenschaft, damit sichtbar wird, welche\nDiagnose worauf anspricht.\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Sind die Voraussetzungen eines linearen Modells erfüllt, und wenn nicht, welche und mit welchen Folgen? |\n| Eingang | ein angepasstes Modell aus `lm()` beziehungsweise `smf.ols()` |\n| Was die Diagnostik liefert | Residuenplots, Hebelwerte, Cook-Distanzen, studentisierte Residuen, Testverfahren für einzelne Voraussetzungen |\n| R-Funktionen | `plot(modell)`, `lmtest::bptest()`, `lmtest::dwtest()`, `lmtest::resettest()`, `cooks.distance()`, `hatvalues()`, `rstudent()`, `car::vif()` |\n| Python-Funktionen | `het_breuschpagan()`, `durbin_watson()`, `linear_reset()`, `modell.get_influence()` |\n| Verwandte Methoden | [einfache lineare Regression](einfache-lineare-regression.qmd), [multiple lineare Regression](multiple-lineare-regression.qmd), [Modellauswahl](modellauswahl.qmd) |\n\n## Wann diese Methode, wann nicht\n\nDiagnostik ist kein eigener Arbeitsschritt am Ende, sondern gehört zu jedem\nangepassten Modell. Die Reihenfolge lautet: Modell anpassen, Residuen ansehen,\n**dann** Koeffizienten lesen. Wer die Koeffizienten zuerst liest, ist geneigt,\ndie Diagnostik so lange zu deuten, bis sie zum Ergebnis passt.\n\nSie beantwortet nicht die Frage, ob das Modell inhaltlich sinnvoll ist. Ein\nModell kann alle Voraussetzungen erfüllen und trotzdem die falsche Frage\nbeantworten oder eine Scheinbeziehung abbilden.\n\n| Situation | Stattdessen oder zusätzlich |\n|---|---|\n| Zielgrösse binär | [logistische Regression](logistische-regression.qmd); dort gelten andere Voraussetzungen |\n| Es geht um die Auswahl zwischen Modellen | [Modellauswahl](modellauswahl.qmd) |\n| Die Beobachtungen sind zeitlich geordnet | Zeitreihenverfahren, siehe [Stationarität](../zeitreihen/stationaritaet-acf-pacf.qmd) |\n| Prädiktoren messen dasselbe | Multikollinearität, siehe [multiple lineare Regression](multiple-lineare-regression.qmd) |\n\n## Die fünf Fragen der Diagnostik\n\n| Frage | Voraussetzung | Womit geprüft | Folge bei Verletzung |\n|---|---|---|---|\n| Ist der Zusammenhang geradlinig? | Linearität | Residuen gegen Vorhersage, RESET-Test | Die Steigung ist ein Kompromiss und stimmt in keinem Bereich |\n| Streuen die Residuen überall gleich? | Homoskedastizität | Residuenplot, Scale-Location-Plot, Breusch-Pagan | Schätzwerte bleiben brauchbar, Standardfehler und p-Werte nicht |\n| Sind die Residuen annähernd normal? | Normalität der Residuen | QQ-Plot | betrifft Tests und Intervalle, vor allem bei kleinem n |\n| Beeinflussen sich die Beobachtungen? | Unabhängigkeit | Durbin-Watson, Erhebungsdesign | Standardfehler zu klein, p-Werte zu optimistisch |\n| Hängt das Ergebnis an wenigen Punkten? | keine einflussreichen Einzelfälle | Cook-Distanz, Hebelwerte, studentisierte Residuen | Die Aussage hängt an einzelnen Beobachtungen |\n\nNur die erste und die fünfte Frage betreffen die **Schätzwerte** selbst. Die\nzweite, dritte und vierte betreffen die **Unsicherheit**, also Standardfehler,\nKonfidenzintervalle und p-Werte. Diese Unterscheidung entscheidet darüber, wie\ndringend eine Verletzung behandelt werden muss.\n\n## Die vier Standardplots\n\n`plot(modell)` in R liefert vier Bilder. Sie beantworten der Reihe nach:\n\n| Nummer | Titel | Was er zeigt | Was gut aussieht |\n|---|---|---|---|\n| 1 | Residuals vs Fitted | Linearität | strukturlose Wolke um die Nulllinie, keine Krümmung |\n| 2 | Q-Q Residuals | Normalität | Punkte nah an der Geraden, Abweichungen an den Enden sind üblich |\n| 3 | Scale-Location | Homoskedastizität | waagrechte Glättungslinie, gleichmässige Streubreite |\n| 4 | Residuals vs Leverage | einflussreiche Punkte | keine Punkte jenseits der Cook-Konturen |\n\nPython hat kein Gegenstück in einem Aufruf; die Plots werden einzeln gebaut.\n\n## Output lesen\n\n| Kennzahl | Was sie misst | Anhaltspunkt | Falle |\n|---|---|---|---|\n| Cook-Distanz | wie stark sich **alle** Vorhersagen ändern, wenn dieser Punkt fehlt | Werte über 1 gelten als auffällig, über 0.5 als beachtenswert | Eine einzelne grosse Cook-Distanz ist ein Befund, viele mittlere sind normal |\n| Hebelwert (leverage) | wie extrem der x-Wert liegt | mehr als das Doppelte oder Dreifache des Mittelwerts $p/n$ | Hoher Hebel allein schadet nicht, siehe Beispiel 4 |\n| studentisiertes Residuum | wie weit der Punkt von seiner eigenen Vorhersage abweicht, in Standardfehlern | Beträge über 3 sind auffällig | misst die y-Richtung, der Hebel die x-Richtung |\n| Breusch-Pagan p | Hinweis auf ungleiche Streuung | grosser p-Wert ist die gute Nachricht | findet nur Streuung, die mit den Prädiktoren zusammenhängt |\n| Durbin-Watson | Korrelation aufeinanderfolgender Residuen | Werte um 2 sind unauffällig, unter 1.5 auffällig | hängt an der **Reihenfolge der Zeilen**, siehe Beispiel 2 |\n| RESET p | Hinweis auf fehlende Nichtlinearität | kleiner p-Wert heisst: das Modell ist fehlspezifiziert | sagt nicht, welcher Prädiktor betroffen ist |\n| VIF | Multikollinearität | über 5 beachten, über 10 kritisch | nur bei mehreren Prädiktoren sinnvoll |\n\n::: {.note-box}\nAlle diese Tests haben dasselbe Problem wie\n[Normalitätstests](../tests/normalitaetstests.qmd): Ihre Aussagekraft hängt am\nStichprobenumfang. Bei n = 5000 wird jede belanglose Abweichung signifikant, bei\nn = 20 bleibt jede grobe unentdeckt. Sie ergänzen die Plots, sie ersetzen sie\nnicht.\n:::\n\n## Interpretationsfallen\n\n- **Ein hohes R² sagt nichts über die Angemessenheit.** In Beispiel 2 ist das\n  falsche Modell dasjenige mit dem höheren R².\n- **Nicht jede Verletzung ist gleich schlimm.** Ungleiche Streuung verzerrt die\n  Standardfehler, aber nicht die Schätzwerte. Eine übersehene Krümmung verzerrt\n  beides.\n- **Hoher Hebel ist kein Fehler.** Ein Punkt weit aussen auf der x-Achse ist\n  wertvoll, solange er auf der Linie der übrigen liegt. Gefährlich ist die\n  Kombination aus hohem Hebel und grossem Residuum.\n- **Ausreisser werden geprüft, nicht entfernt.** Das Entfernen ist eine\n  inhaltliche Entscheidung mit Begründung, keine statistische Reinigung.\n- **Durbin-Watson misst die Zeilenreihenfolge.** Bei nach x sortierten Daten\n  zeigt er Krümmung an, nicht Autokorrelation.\n- **Die Residuen zählen, nicht die Rohdaten.** Weder x noch y müssen\n  normalverteilt sein.\n- **Eine Transformation ändert die Fragestellung.** Nach dem Logarithmieren der\n  Zielgrösse beschreibt die Steigung eine relative statt einer absoluten\n  Änderung.\n\n## Ergebnis berichten\n\nDie Diagnostik gehört in einen eigenen kurzen Absatz, und zwar **vor** den\nKoeffizienten:\n\n> Residuen gegen Vorhersage zeigen keine Struktur, der QQ-Plot keine\n> nennenswerte Abweichung, der Breusch-Pagan-Test keinen Hinweis auf ungleiche\n> Streuung (p = [p]). Die grösste Cook-Distanz beträgt [Wert]; einflussreiche\n> Einzelfälle liegen nicht vor.\n\nBei einer Verletzung gehört dazu, was daraus folgte: welche Kennzahl auffällig\nwar, welche Massnahme gewählt wurde und ob sich das Ergebnis dadurch änderte.\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt der Diagnostik |\n|---|---|\n| [Modellauswahl](modellauswahl.qmd) | die Frage lautet, welche Prädiktoren ins Modell gehören |\n| [Multiple lineare Regression](multiple-lineare-regression.qmd) | die Schätzung selbst steht im Vordergrund |\n| [Normalitätstests](../tests/normalitaetstests.qmd) | Vertiefung zur Frage der Verteilungsform |\n| [Bootstrap](../inferenz/bootstrap-resampling.qmd) | Intervalle ohne Verteilungsannahme, wenn die Voraussetzungen nicht zu retten sind |\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Das unauffällige Modell\n\n#### Frage und Datenlage\n\n120 Beobachtungen, ein Prädiktor, ein sauber linearer Zusammenhang mit\ngleichmässiger Streuung. Dieses Beispiel ist der Referenzfall: So sehen die\nPlots aus, wenn nichts vorliegt.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodell_a <- lm(y ~ x, data = sauber)\n\npar(mfrow = c(2, 2), mar = c(4, 4, 3, 1))\nplot(modell_a)\npar(mfrow = c(1, 1))\n\nbptest(modell_a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  modell_a\nBP = 1.008, df = 1, p-value = 0.3154\n```\n\n\n:::\n\n```{.r .cell-code}\ndwtest(modell_a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tDurbin-Watson test\n\ndata:  modell_a\nDW = 2.1231, p-value = 0.7213\nalternative hypothesis: true autocorrelation is greater than 0\n```\n\n\n:::\n\n```{.r .cell-code}\nresettest(modell_a, power = 2, type = \"fitted\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tRESET test\n\ndata:  modell_a\nRESET = 1.1344, df1 = 1, df2 = 117, p-value = 0.289\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(residuals(modell_a))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(modell_a)\nW = 0.99851, p-value = 1\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(r2 = summary(modell_a)$r.squared,\n        residualstreuung = summary(modell_a)$sigma,\n        max_cook = max(cooks.distance(modell_a)),\n        max_hebel = max(hatvalues(modell_a)),\n        mittlerer_hebel = mean(hatvalues(modell_a)),\n        max_stud_residuum = rstudent(modell_a)[which.max(abs(rstudent(modell_a)))]), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 r2    residualstreuung            max_cook           max_hebel \n             0.9023              4.0097              0.2468              0.0669 \n    mittlerer_hebel max_stud_residuum.1 \n             0.0167             -2.6918 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 1: die vier Standardplots eines unauffälligen Modells.](regressionsdiagnostik_files/figure-html/fig-b1-diag-r-1.png){#fig-b1-diag-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmodell_a = smf.ols(\"y ~ x\", data=sauber).fit()\n\n\ndef vier_plots(modell, titel):\n    einfluss_obj = modell.get_influence()\n    wurzel_resid = np.sqrt(np.abs(einfluss_obj.resid_studentized_internal))\n\n    fig, achsen = plt.subplots(2, 2, figsize=(7, 5.4))\n    achsen[0, 0].scatter(modell.fittedvalues, modell.resid, s=12, color=\"0.3\")\n    achsen[0, 0].axhline(0, linestyle=\"--\", color=\"black\")\n    achsen[0, 0].set_title(\"Residuen gegen Vorhersage\", fontsize=9)\n    sm.qqplot(modell.resid, line=\"s\", ax=achsen[0, 1])\n    achsen[0, 1].set_title(\"QQ-Plot der Residuen\", fontsize=9)\n    achsen[1, 0].scatter(modell.fittedvalues, wurzel_resid, s=12, color=\"0.3\")\n    achsen[1, 0].set_title(\"Scale-Location\", fontsize=9)\n    achsen[1, 1].scatter(einfluss_obj.hat_matrix_diag,\n                         einfluss_obj.resid_studentized_internal,\n                         s=12, color=\"0.3\")\n    achsen[1, 1].axhline(0, linestyle=\"--\", color=\"black\")\n    achsen[1, 1].set_xlabel(\"Hebelwert\")\n    achsen[1, 1].set_title(\"Residuen gegen Hebelwert\", fontsize=9)\n    fig.suptitle(titel, fontsize=10)\n    plt.tight_layout()\n    plt.show()\n\n\nvier_plots(modell_a, \"Beispiel 1\")\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselben Bilder in Python.](regressionsdiagnostik_files/figure-html/fig-b1-diag-py-1.png){#fig-b1-diag-py width=100%}\n:::\n\n```{.python .cell-code}\nbp = het_breuschpagan(modell_a.resid, modell_a.model.exog)\nprint(\"Breusch-Pagan LM =\", round(bp[0], 4), \" p =\", round(bp[1], 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBreusch-Pagan LM = 1.008  p = 0.3154\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Durbin-Watson =\", round(durbin_watson(modell_a.resid), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDurbin-Watson = 2.1231\n```\n\n\n:::\n\n```{.python .cell-code}\nreset = linear_reset(modell_a, power=2, use_f=True)\nprint(\"RESET F =\", round(reset.fvalue, 4), \" p =\", round(reset.pvalue, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRESET F = 1.1344  p = 0.289\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Shapiro der Residuen p =\", round(stats.shapiro(modell_a.resid).pvalue, 5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nShapiro der Residuen p = 0.99999\n```\n\n\n:::\n\n```{.python .cell-code}\neinfluss_a = modell_a.get_influence()\nstud_a = einfluss_a.resid_studentized_external\nprint(\"R^2 =\", round(modell_a.rsquared, 4),\n      \" Residualstreuung =\", round(np.sqrt(modell_a.mse_resid), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR^2 = 0.9023  Residualstreuung = 4.0097\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"max Cook =\", round(einfluss_a.cooks_distance[0].max(), 4),\n      \" max Hebel =\", round(einfluss_a.hat_matrix_diag.max(), 4),\n      \" mittlerer Hebel =\", round(einfluss_a.hat_matrix_diag.mean(), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmax Cook = 0.2468  max Hebel = 0.0669  mittlerer Hebel = 0.0167\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"grösstes studentisiertes Residuum =\",\n      round(stud_a[np.abs(stud_a).argmax()], 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngrösstes studentisiertes Residuum = -2.6918\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Kennzahl | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| R² | 0.9023 | Merken für den Vergleich mit Beispiel 2. |\n| Residualstreuung | 4.01 | Entspricht der eingebauten Streuung von 4. |\n| Breusch-Pagan p | 0.315 | Kein Hinweis auf ungleiche Streuung. Der grosse p-Wert ist hier die gute Nachricht. |\n| Durbin-Watson | 2.123 | Um 2 herum, also unauffällig. |\n| RESET p | 0.289 | Kein Hinweis auf eine fehlende Nichtlinearität. |\n| Shapiro der Residuen p | 0.99999 | Unauffällig, und derart nahe an 1, weil die Störgrösse deterministisch aus Normalverteilungsquantilen gebaut ist. |\n| grösste Cook-Distanz | 0.247 | Weit unter der Schwelle von 1. |\n| grösster Hebelwert | 0.0669 | Der mittlere Hebel beträgt 0.0167, also 2 geteilt durch 120. Der grösste liegt beim Vierfachen, was bei 120 Punkten am Rand des Wertebereichs normal ist. |\n| grösstes studentisiertes Residuum | -2.69 | Unter 3, also unauffällig. Bei 120 Beobachtungen erwartet man einige Werte um 2.5. |\n\n#### Interpretation\n\nAlle vier Plots zeigen das erwartete Bild: strukturlose Wolke, Punkte auf der\nQQ-Geraden, waagrechte Scale-Location-Linie, keine Punkte ausserhalb der\nCook-Konturen. Das Modell darf gelesen werden.\n\nWichtig ist, dieses Bild einmal gesehen zu haben. Wer nur Verletzungen kennt,\nneigt dazu, in jedem Residuenplot ein Muster zu erkennen.\n\n### Beispiel 2: Übersehene Krümmung\n\n#### Frage und Datenlage\n\nDerselbe Prädiktor, aber der Zusammenhang ist in Wahrheit quadratisch.\nAngepasst wird trotzdem eine Gerade.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodell_b <- lm(y ~ x, data = krumm)\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nplot(krumm$x, krumm$y, pch = 16, col = \"grey40\", xlab = \"x\", ylab = \"y\",\n     main = \"Daten und Gerade\")\nabline(modell_b, col = \"steelblue\", lwd = 2)\nplot(modell_b, which = 1)\npar(mfrow = c(1, 1))\n\nround(summary(modell_b)$r.squared, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9214\n```\n\n\n:::\n\n```{.r .cell-code}\nbptest(modell_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  modell_b\nBP = 0.40991, df = 1, p-value = 0.522\n```\n\n\n:::\n\n```{.r .cell-code}\ndwtest(modell_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tDurbin-Watson test\n\ndata:  modell_b\nDW = 0.52853, p-value < 2.2e-16\nalternative hypothesis: true autocorrelation is greater than 0\n```\n\n\n:::\n\n```{.r .cell-code}\nresettest(modell_b, power = 2, type = \"fitted\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tRESET test\n\ndata:  modell_b\nRESET = 382.52, df1 = 1, df2 = 117, p-value < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(residuals(modell_b))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(modell_b)\nW = 0.90307, p-value = 2.827e-07\n```\n\n\n:::\n\n```{.r .cell-code}\nround(summary(modell_b)$sigma, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8.2458\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 2: Gerade auf gekrümmten Daten und der Bogen im Residuenplot.](regressionsdiagnostik_files/figure-html/fig-b2-diag-r-3.png){#fig-b2-diag-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmodell_b = smf.ols(\"y ~ x\", data=krumm).fit()\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nachsen[0].scatter(krumm[\"x\"], krumm[\"y\"], s=12, color=\"0.4\")\ngitter = np.linspace(krumm[\"x\"].min(), krumm[\"x\"].max(), 50)\nachsen[0].plot(gitter, modell_b.params.iloc[0] + modell_b.params.iloc[1] * gitter,\n               color=\"steelblue\", linewidth=2)\nachsen[0].set_title(\"Daten und Gerade\", fontsize=9)\nachsen[1].scatter(modell_b.fittedvalues, modell_b.resid, s=12, color=\"0.3\")\nachsen[1].axhline(0, linestyle=\"--\", color=\"black\")\nglatt = sm.nonparametric.lowess(modell_b.resid, modell_b.fittedvalues)\nachsen[1].plot(glatt[:, 0], glatt[:, 1], color=\"firebrick\", linewidth=2)\nachsen[1].set_title(\"Residuen gegen Vorhersage\", fontsize=9)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselbe Gegenüberstellung in Python.](regressionsdiagnostik_files/figure-html/fig-b2-diag-py-1.png){#fig-b2-diag-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(\"R^2 =\", round(modell_b.rsquared, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR^2 = 0.9214\n```\n\n\n:::\n\n```{.python .cell-code}\nbp = het_breuschpagan(modell_b.resid, modell_b.model.exog)\nprint(\"Breusch-Pagan p =\", round(bp[1], 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBreusch-Pagan p = 0.522\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Durbin-Watson =\", round(durbin_watson(modell_b.resid), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDurbin-Watson = 0.5285\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"RESET p =\", linear_reset(modell_b, power=2, use_f=True).pvalue)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRESET p = 1.1155488532609534e-38\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Shapiro der Residuen p =\", stats.shapiro(modell_b.resid).pvalue)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nShapiro der Residuen p = 2.8271603543096845e-07\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Residualstreuung =\", round(np.sqrt(modell_b.mse_resid), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nResidualstreuung = 8.2458\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Kennzahl | Beispiel 1 | Beispiel 2 | Wie das zu lesen ist |\n|---|---|---|---|\n| R² | 0.9023 | **0.9214** | Das falsche Modell hat das **höhere** R². Wer Modelle nach R² beurteilt, wählt hier die falsche Spezifikation. |\n| Residualstreuung | 4.01 | 8.25 | Doppelt so gross. Diese Zahl verrät das Problem, R² nicht. |\n| Breusch-Pagan p | 0.315 | 0.522 | **Unauffällig.** Der Test sucht ungleiche Streuung und findet keine, denn die Streuung ist ja gleichmässig. Er ist für dieses Problem blind. |\n| Durbin-Watson | 2.123 | **0.529** | Deutlich auffällig, und zwar aus einem Grund, der Aufmerksamkeit verdient, siehe Kasten. |\n| RESET p | 0.289 | **1.1e-38** | Der Test, der genau für diesen Fall gebaut ist. Er prüft, ob quadrierte Vorhersagewerte noch etwas erklären, und findet massiv etwas. |\n| Shapiro der Residuen p | 0.99999 | 2.8e-07 | Ebenfalls auffällig, aber irreführend: Die Residuen sind nicht deshalb nicht normalverteilt, weil die Störgrösse es nicht wäre, sondern weil sie den systematischen Bogen enthalten. |\n\n::: {.note-box}\n**Warum Durbin-Watson hier anschlägt, obwohl es keine Zeitreihe ist.** Der Test\nmisst, ob aufeinanderfolgende Residuen einander ähneln, und \"aufeinanderfolgend\"\nheisst: in der Reihenfolge der Zeilen. In diesen Daten sind die Zeilen nach x\nsortiert. Der Bogen im Residuenplot führt dann dazu, dass benachbarte Zeilen\nähnliche Residuen haben, und genau das misst Durbin-Watson.\n\nPraktisch heisst das zweierlei. Bei nach einem Prädiktor sortierten Daten ist\nein kleiner Durbin-Watson-Wert ein Hinweis auf **Krümmung**, nicht auf\nAutokorrelation. Und umgekehrt: Wer echte Autokorrelation prüfen will, muss die\nZeilen in ihrer **zeitlichen** Reihenfolge haben, sonst misst der Test etwas\nanderes.\n:::\n\n#### Interpretation und Ergebnissatz\n\nDie Lehre dieses Beispiels ist die Arbeitsteilung der Diagnosen: Breusch-Pagan\nschweigt, RESET schlägt Alarm, Durbin-Watson schlägt aus einem anderen Grund\nAlarm als vermutet, und R² zeigt in die falsche Richtung. **Kein einzelnes Mass\ndeckt alle Verletzungen ab.**\n\nDer Residuenplot zeigt alles auf einen Blick: Die Residuen sind an den Rändern\npositiv und in der Mitte negativ, die Glättungslinie bildet einen deutlichen\nBogen.\n\nDas Vorgehen: einen quadratischen Term aufnehmen, transformieren oder ein\nanderes Modell wählen, und danach die Residuen erneut ansehen.\n\n> Ein rein lineares Modell beschreibt den Zusammenhang nicht angemessen. Der\n> RESET-Test ist deutlich signifikant (F(1, 117) = 382.5, p < 0.001), und die\n> Residuen zeigen einen ausgeprägten Bogen. Das höhere R² gegenüber dem\n> korrekt spezifizierten Modell (0.921 gegenüber 0.902) ist kein Gütezeichen.\n> Berichtet wird das Modell mit quadratischem Term.\n\n### Beispiel 3: Ungleiche Streuung\n\n#### Frage und Datenlage\n\nDer Zusammenhang ist geradlinig, aber die Streuung wächst mit x: Bei kleinen\nx-Werten liegen die Punkte eng an der Geraden, bei grossen weit auseinander.\nDas ist der häufigste Fall in wirtschaftlichen Daten, wo Beträge und ihre\nSchwankung gemeinsam wachsen.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodell_c <- lm(y ~ x, data = trichter)\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nplot(modell_c, which = 1)\nplot(modell_c, which = 3)\npar(mfrow = c(1, 1))\n\nbptest(modell_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  modell_c\nBP = 16.283, df = 1, p-value = 5.455e-05\n```\n\n\n:::\n\n```{.r .cell-code}\nresettest(modell_c, power = 2, type = \"fitted\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tRESET test\n\ndata:  modell_c\nRESET = 0.0068298, df1 = 1, df2 = 117, p-value = 0.9343\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(residuals(modell_c))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(modell_c)\nW = 0.99093, p-value = 0.6198\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(modell_c)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error  t value     Pr(>|t|)\n(Intercept) 20.30292  1.4183213 14.31475 1.468395e-27\nx            2.97770  0.1317836 22.59538 1.117751e-44\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: der Trichter im Residuenplot.](regressionsdiagnostik_files/figure-html/fig-b3-diag-r-3.png){#fig-b3-diag-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmodell_c = smf.ols(\"y ~ x\", data=trichter).fit()\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nachsen[0].scatter(modell_c.fittedvalues, modell_c.resid, s=12, color=\"0.3\")\nachsen[0].axhline(0, linestyle=\"--\", color=\"black\")\nachsen[0].set_title(\"Residuen gegen Vorhersage\", fontsize=9)\nwurzel = np.sqrt(np.abs(modell_c.get_influence().resid_studentized_internal))\nachsen[1].scatter(modell_c.fittedvalues, wurzel, s=12, color=\"0.3\")\nachsen[1].set_title(\"Scale-Location\", fontsize=9)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselben Bilder in Python.](regressionsdiagnostik_files/figure-html/fig-b3-diag-py-1.png){#fig-b3-diag-py width=100%}\n:::\n\n```{.python .cell-code}\nbp = het_breuschpagan(modell_c.resid, modell_c.model.exog)\nprint(\"Breusch-Pagan LM =\", round(bp[0], 4), \" p =\", bp[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBreusch-Pagan LM = 16.283  p = 5.455243919507552e-05\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"RESET p =\", round(linear_reset(modell_c, power=2, use_f=True).pvalue, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRESET p = 0.9343\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Shapiro der Residuen p =\", round(stats.shapiro(modell_c.resid).pvalue, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nShapiro der Residuen p = 0.6198\n```\n\n\n:::\n\n```{.python .cell-code}\n# Robuste Standardfehler: derselbe Schaetzwert, andere Unsicherheit\nrobust = smf.ols(\"y ~ x\", data=trichter).fit(cov_type=\"HC3\")\nprint(pd.DataFrame({\n    \"Schätzwert\": modell_c.params.round(4),\n    \"SE gewöhnlich\": modell_c.bse.round(4),\n    \"SE robust (HC3)\": robust.bse.round(4),\n}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Schätzwert  SE gewöhnlich  SE robust (HC3)\nIntercept     20.3029         1.4183           1.1505\nx              2.9777         0.1318           0.1389\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Kennzahl | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Breusch-Pagan p | 0.0000546 | **Auffällig.** Der Test, der für diesen Fall gebaut ist, findet ihn. |\n| RESET p | 0.934 | Unauffällig, korrekt: Der Zusammenhang ist ja geradlinig. |\n| Shapiro der Residuen p | 0.620 | Ebenfalls unauffällig. Die Residuen sind normalverteilt, nur nicht gleich stark streuend. |\n| Steigung | 2.978 | Praktisch unverändert gegenüber Beispiel 1 (3.037). |\n| Standardfehler gewöhnlich | 0.132 | |\n| Standardfehler robust (HC3) | siehe Ausgabe | Die interessante Gegenüberstellung: Der Schätzwert bleibt derselbe, nur die Unsicherheit wird anders beziffert. |\n\nDer Residuenplot zeigt den namensgebenden Trichter: Die Punkte fächern nach\nrechts auf. Der Scale-Location-Plot macht dasselbe deutlicher, weil er die\nBeträge aufträgt und die Glättungslinie dann sichtbar ansteigt statt waagrecht\nzu verlaufen.\n\n#### Interpretation und Ergebnissatz\n\nUngleiche Streuung ist die harmloseste der Verletzungen, weil sie die\n**Schätzwerte** nicht verzerrt. Die Steigung von 2.98 ist so brauchbar wie im\nsauberen Fall. Verzerrt sind nur die Standardfehler, und damit\nKonfidenzintervalle und p-Werte.\n\nDrei Wege stehen offen:\n\n| Weg | Wann er passt |\n|---|---|\n| Robuste Standardfehler (HC3) | der Standardweg; Schätzwerte bleiben, nur die Unsicherheit wird korrekt beziffert |\n| Zielgrösse logarithmieren | wenn die Streuung proportional zum Niveau wächst; ändert aber die Bedeutung der Steigung |\n| Gewichtete Regression | wenn die Streuungsstruktur bekannt ist |\n\nIn R braucht der erste Weg das Zusatzpaket `sandwich` zusammen mit\n`lmtest::coeftest()`; in Python genügt `cov_type=\"HC3\"` beim Anpassen.\n\n> Der Breusch-Pagan-Test zeigt ungleiche Streuung (LM = 16.28, p < 0.001), und\n> der Residuenplot fächert nach rechts auf. Die Schätzwerte sind davon nicht\n> betroffen; berichtet werden robuste Standardfehler nach HC3. Linearität\n> (RESET p = 0.93) und Normalität der Residuen (Shapiro p = 0.62) sind erfüllt.\n\n### Beispiel 4: Ein einflussreicher Punkt\n\n#### Frage und Datenlage\n\nDie sauberen Daten aus Beispiel 1, ergänzt um eine einzige Beobachtung: x = 32,\nalso weit rechts ausserhalb des beobachteten Bereichs von rund 2 bis 18, und\ny = 20, also weit unterhalb der Geraden.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodell_d <- lm(y ~ x, data = einfluss)\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nplot(einfluss$x, einfluss$y, pch = 16, col = \"grey40\", xlab = \"x\", ylab = \"y\",\n     main = \"Mit und ohne den Fall\")\npoints(32, 20, pch = 16, col = \"firebrick\", cex = 1.4)\nabline(modell_d, col = \"firebrick\", lwd = 2)\nabline(modell_a, col = \"steelblue\", lwd = 2, lty = 2)\nlegend(\"topleft\", c(\"mit\", \"ohne\"), col = c(\"firebrick\", \"steelblue\"),\n       lty = c(1, 2), lwd = 2, bty = \"n\", cex = 0.8)\nplot(cooks.distance(modell_d), type = \"h\", lwd = 2, xlab = \"Beobachtung\",\n     ylab = \"Cook-Distanz\", main = \"Cook-Distanzen\")\nabline(h = 1, lty = 2, col = \"firebrick\")\npar(mfrow = c(1, 1))\n\nround(c(steigung_ohne = coef(modell_a)[2], steigung_mit = coef(modell_d)[2],\n        r2_ohne = summary(modell_a)$r.squared,\n        r2_mit = summary(modell_d)$r.squared), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsteigung_ohne.x  steigung_mit.x         r2_ohne          r2_mit \n         3.0369          2.1493          0.9023          0.5413 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(max_cook = max(cooks.distance(modell_d)),\n        max_hebel = max(hatvalues(modell_d)),\n        mittlerer_hebel = mean(hatvalues(modell_d)),\n        groesstes_stud_residuum = rstudent(modell_d)[which.max(abs(rstudent(modell_d)))]), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   max_cook                   max_hebel \n                    12.4670                      0.2083 \n            mittlerer_hebel groesstes_stud_residuum.121 \n                     0.0165                    -21.4831 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 4: der Punkt, die beiden Geraden und die Cook-Distanzen.](regressionsdiagnostik_files/figure-html/fig-b4-diag-r-3.png){#fig-b4-diag-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmodell_d = smf.ols(\"y ~ x\", data=einfluss).fit()\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nachsen[0].scatter(einfluss[\"x\"], einfluss[\"y\"], s=12, color=\"0.4\")\nachsen[0].scatter([32], [20], s=45, color=\"firebrick\")\ngitter = np.linspace(2, 33, 50)\nachsen[0].plot(gitter, modell_d.params.iloc[0] + modell_d.params.iloc[1] * gitter,\n               color=\"firebrick\", linewidth=2, label=\"mit\")\nachsen[0].plot(gitter, modell_a.params.iloc[0] + modell_a.params.iloc[1] * gitter,\n               color=\"steelblue\", linewidth=2, linestyle=\"--\", label=\"ohne\")\nachsen[0].legend(frameon=False, fontsize=8)\nachsen[0].set_title(\"Mit und ohne den Fall\", fontsize=9)\ncook = modell_d.get_influence().cooks_distance[0]\nachsen[1].vlines(range(len(cook)), 0, cook, linewidth=2)\nachsen[1].axhline(1, linestyle=\"--\", color=\"firebrick\")\nachsen[1].set_xlabel(\"Beobachtung\")\nachsen[1].set_ylabel(\"Cook-Distanz\")\nachsen[1].set_title(\"Cook-Distanzen\", fontsize=9)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselbe Gegenüberstellung in Python.](regressionsdiagnostik_files/figure-html/fig-b4-diag-py-1.png){#fig-b4-diag-py width=100%}\n:::\n\n```{.python .cell-code}\neinfluss_obj = modell_d.get_influence()\nprint(\"Steigung ohne:\", round(modell_a.params.iloc[1], 4),\n      \" mit:\", round(modell_d.params.iloc[1], 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSteigung ohne: 3.0369  mit: 2.1493\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"R^2 ohne:\", round(modell_a.rsquared, 4),\n      \" mit:\", round(modell_d.rsquared, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR^2 ohne: 0.9023  mit: 0.5413\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"max Cook:\", round(cook.max(), 4),\n      \" max Hebel:\", round(einfluss_obj.hat_matrix_diag.max(), 4),\n      \" mittlerer Hebel:\", round(einfluss_obj.hat_matrix_diag.mean(), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmax Cook: 12.467  max Hebel: 0.2083  mittlerer Hebel: 0.0165\n```\n\n\n:::\n\n```{.python .cell-code}\nstud = einfluss_obj.resid_studentized_external\nprint(\"grösstes studentisiertes Residuum:\",\n      round(stud[np.abs(stud).argmax()], 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngrösstes studentisiertes Residuum: -21.4831\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Breusch-Pagan p =\", het_breuschpagan(modell_d.resid, modell_d.model.exog)[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBreusch-Pagan p = 9.564024480342477e-07\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"RESET p =\", linear_reset(modell_d, power=2, use_f=True).pvalue)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRESET p = 9.873700108154505e-28\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Kennzahl | Ohne den Fall | Mit dem Fall | Wie das zu lesen ist |\n|---|---|---|---|\n| Steigung | 3.037 | 2.149 | Ein Punkt von 121 senkt die Steigung um knapp ein Drittel. |\n| R² | 0.9023 | 0.5413 | Von 90 auf 54 Prozent. |\n| Residualstreuung | 4.01 | 8.85 | Mehr als verdoppelt. |\n| grösste Cook-Distanz | 0.247 | **12.467** | Die Schwelle liegt bei 1. Der Wert liegt eine Grössenordnung darüber, und die übrigen 120 Werte verschwinden im Diagramm optisch auf der Nulllinie. |\n| grösster Hebelwert | 0.0669 | 0.2083 | Der mittlere Hebel beträgt 0.0165; dieser Punkt hat den 12.6-fachen Wert. |\n| grösstes studentisiertes Residuum | -2.69 | **-21.48** | Der Punkt liegt 21 Standardfehler unter seiner eigenen Vorhersage. |\n| Breusch-Pagan p | 0.315 | 0.0000010 | Auffällig geworden, ohne dass sich an der Streuungsstruktur etwas geändert hätte. |\n| RESET p | 0.289 | 9.9e-28 | Ebenfalls. |\n\n::: {.note-box}\n**Ein einzelner Punkt lässt alle Tests anschlagen.** Breusch-Pagan, RESET und\nShapiro sind in Beispiel 1 unauffällig und hier alle drei hochsignifikant,\nobwohl sich an Streuungsstruktur, Linearität und Verteilung nichts geändert hat.\n\nDaraus folgt eine Reihenfolge für die Diagnostik: **zuerst nach einflussreichen\nPunkten sehen, dann die übrigen Tests lesen.** Andernfalls behandelt man eine\nKrümmung oder eine Streuungsstruktur, die es gar nicht gibt.\n:::\n\n#### Interpretation und Ergebnissatz\n\nHebel und Cook-Distanz messen Verschiedenes, und beide werden hier gebraucht.\nDer Hebel von 0.21 sagt: Der Punkt liegt weit aussen auf der x-Achse. Für sich\ngenommen wäre das unproblematisch; ein weit aussen liegender Punkt auf der Linie\nder übrigen macht die Schätzung sogar genauer. Das studentisierte Residuum von\n-21.5 sagt: Er liegt zugleich weit von seiner Vorhersage entfernt. Erst die\nKombination ergibt die Cook-Distanz von 12.5.\n\nWas jetzt zu tun ist, ist keine statistische Frage:\n\n| Befund zur Ursache | Vorgehen |\n|---|---|\n| Erfassungsfehler | ausschliessen, Ausschluss und Begründung berichten |\n| Gültig, aber ausserhalb der Fragestellung | ausschliessen, Grundgesamtheit enger fassen |\n| Gültig, Ursache unklar | Ergebnis mit und ohne den Fall berichten |\n\n> Eine von 121 Beobachtungen ist stark einflussreich (Cook-Distanz 12.5,\n> Hebelwert 0.21 gegenüber einem mittleren Hebel von 0.017, studentisiertes\n> Residuum -21.5). Sie senkt die Steigung von 3.04 auf 2.15 und R² von 0.90 auf\n> 0.54. Zugleich werden Breusch-Pagan, RESET und der Shapiro-Test auf die\n> Residuen signifikant, obwohl die übrigen 120 Beobachtungen unauffällig sind.\n> Der Fall wurde als Messfehler ausgeschlossen; berichtet wird das Modell ohne\n> ihn.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEin Modell hat R² = 0.92, ein konkurrierendes mit anderer Spezifikation\nR² = 0.90. Der Residuenplot des ersten zeigt einen Bogen. Welches ist besser?\n\n- [x] Das zweite, trotz kleinerem R² ~ Richtig. R² misst erklärte Streuung,\n      nicht Angemessenheit. Ein Modell mit übersehener Krümmung kann ein höheres\n      R² haben als das korrekt spezifizierte, wie Beispiel 2 zeigt. Der\n      Residuenplot und die Residualstreuung entscheiden.\n- [ ] Das erste, R² ist das Gütemass ~ Dann würde man systematisch die falsche\n      Spezifikation wählen.\n- [ ] Nicht entscheidbar ohne p-Werte ~ Die p-Werte sind bei einem\n      fehlspezifizierten Modell ohnehin nicht vertrauenswürdig.\n:::\n\n::: {.quiz}\nDer Breusch-Pagan-Test ist unauffällig, der RESET-Test hochsignifikant. Was\nliegt vor?\n\n- [x] Eine übersehene Nichtlinearität, keine ungleiche Streuung ~ Richtig. Die\n      beiden Tests prüfen verschiedene Voraussetzungen. Breusch-Pagan sucht\n      ungleiche Streuung, RESET sucht fehlende Terme im Modell. Dass der eine\n      schweigt, sagt nichts über den anderen.\n- [ ] Ein Widerspruch, einer der beiden Tests muss falsch sein ~ Sie\n      widersprechen sich nicht, sie beantworten verschiedene Fragen.\n- [ ] Ungleiche Streuung, die der Test übersehen hat ~ Möglich, aber der\n      RESET-Test wäre dafür der falsche Anzeiger.\n:::\n\n::: {.quiz}\nEine Beobachtung hat einen Hebelwert von 0.21 bei einem mittleren Hebel von\n0.017, aber ein studentisiertes Residuum von 0.3. Ist sie ein Problem?\n\n- [x] Nein, sie liegt weit aussen und trotzdem auf der Linie der übrigen ~\n      Richtig. Hoher Hebel allein ist unproblematisch und macht die Schätzung\n      sogar genauer. Gefährlich ist die Kombination aus hohem Hebel und grossem\n      Residuum, und genau die misst die Cook-Distanz.\n- [ ] Ja, jeder Hebel über dem Dreifachen des Mittelwerts ist kritisch ~ Die\n      Faustregel markiert Punkte, die man ansehen sollte, nicht solche, die man\n      entfernen muss.\n- [ ] Ja, weil sie ausserhalb des Datenbereichs liegt ~ Ausserhalb des Bereichs\n      liegt sie nicht, sie liegt an dessen Rand; und das ist zulässig.\n:::\n\n::: {.quiz}\nDie Daten sind nach dem Prädiktor sortiert, und Durbin-Watson liefert 0.53. Was\nfolgt daraus?\n\n- [x] Ein Hinweis auf Krümmung, nicht auf Autokorrelation ~ Richtig.\n      Durbin-Watson misst die Ähnlichkeit aufeinanderfolgender Zeilen. Bei nach x\n      sortierten Daten führt ein Bogen im Residuenverlauf genau zu diesem Bild.\n      Für echte Autokorrelation müssten die Zeilen zeitlich geordnet sein.\n- [ ] Die Beobachtungen sind voneinander abhängig ~ Das wäre der Schluss bei\n      zeitlich geordneten Daten.\n- [ ] Der Test ist bei sortierten Daten nicht anwendbar ~ Anwendbar ist er, er\n      misst nur etwas anderes als erwartet.\n:::\n\n## Verlinkte Ressourcen\n\n- [An Introduction to Statistical Learning, Kapitel 3.3](https://www.statlearning.com/)\n- [R-Dokumentation zu `plot.lm`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/plot.lm.html)\n- [statsmodels: Outlier and influence measures](https://www.statsmodels.org/stable/generated/statsmodels.stats.outliers_influence.OLSInfluence.html)\n",
    "supporting": [
      "regressionsdiagnostik_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}