{
  "hash": "03b4e953e7cdaf30a53b8569ee7f5326",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Schätzen und Konfidenzintervalle\"\ndescription: \"Punktschätzung, Standardfehler und die korrekte Deutung eines Intervalls.\"\ncategories: [\"Schätzen\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"ESDS\"]\nseitentyp: methode\nstand: entwurf\norder: 10\n---\n\n---\n\n\n\n\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Wie gross ist eine Kennzahl in der Grundgesamtheit, und wie genau ist die Schätzung aus einer Stichprobe? |\n| Zielvariable | metrisch für den Erwartungswert, binär für einen Anteil |\n| Prädiktoren | keine |\n| Was die Methode liefert | Punktschätzer, Standardfehler und ein Konfidenzintervall zu einem gewählten Niveau |\n| R-Funktion | `t.test(x)$conf.int` für den Mittelwert, `prop.test()` oder `binom.test()` für Anteile |\n| Python-Funktion | `stats.t.interval()` für den Mittelwert, `proportion_confint()` für Anteile |\n| Verwandte Methoden | [Hypothesentests](hypothesentests-grundlagen.qmd), [t-Test für eine Stichprobe](../tests/t-test-eine-stichprobe.qmd), [Bootstrap](bootstrap-resampling.qmd) |\n\n## Wann diese Methode, wann nicht\n\nTypische Fragestellungen: mittlere Durchlaufzeit einer Produktion, Anteil\nfehlerhafter Teile, durchschnittliche Zustimmung in einer Befragung. Gemeinsam\nist ihnen, dass eine Stichprobe vorliegt und eine Aussage über die\nGrundgesamtheit gemacht werden soll, aus der sie stammt.\n\nDie Methode setzt voraus, dass die Stichprobe zufällig aus der interessierenden\nGrundgesamtheit gezogen wurde. Diese Bedingung ist die wichtigste und die am\nhäufigsten verletzte: eine bequem erreichbare Stichprobe liefert ein sauber\ngerechnetes Intervall um den falschen Wert.\n\n| Situation | Stattdessen |\n|---|---|\n| Zwei Gruppen sollen verglichen werden | [t-Test für zwei Stichproben](../tests/t-test-zwei-stichproben.qmd) |\n| Es geht um eine Ja-Nein-Entscheidung gegen einen Referenzwert | [t-Test für eine Stichprobe](../tests/t-test-eine-stichprobe.qmd) |\n| Die Verteilung ist stark schief und n klein | [Bootstrap](bootstrap-resampling.qmd) |\n| Die Kennzahl ist der Median oder ein anderes Quantil | Bootstrap oder verteilungsfreie Intervalle |\n| Die Stichprobe ist nicht zufällig gezogen | kein Verfahren repariert das; die Einschränkung gehört in den Bericht |\n\n## Grundidee und Modell\n\n### Die Kennzahl ist selbst zufällig\n\nBisher beschrieben Kennzahlen die vorliegenden Daten. Interessant ist aber\nselten die Stichprobe, sondern das, woraus sie stammt. Aus dreissig gemessenen\nWerkstücken soll etwas über die gesamte Produktion folgen.\n\nDer entscheidende Gedankenschritt: Eine zweite Stichprobe hätte einen anderen\nMittelwert ergeben. Der berechnete Wert ist damit selbst eine Zufallsgrösse,\nund die Frage lautet, wie stark er von Stichprobe zu Stichprobe schwankt.\n\nDas lässt sich simulieren, weil wir die Grundgesamtheit hier kennen:\n\n::: panel-tabset\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Grundgesamtheit: Erwartungswert 500, Standardabweichung 40\nwerte <- normalwerte(2026, 2000 * 30, mittel = 500, streuung = 40)\nmittelwerte <- rowMeans(matrix(werte, nrow = 2000, ncol = 30, byrow = TRUE))\n\nggplot(data.frame(mittelwerte), aes(mittelwerte)) +\n  geom_histogram(bins = 40, fill = \"grey75\", colour = \"white\") +\n  geom_vline(xintercept = 500, linewidth = 0.8) +\n  labs(x = \"Mittelwert einer Stichprobe (n = 30)\", y = \"Anzahl\")\n```\n\n::: {.cell-output-display}\n![2000 Stichproben aus derselben Grundgesamtheit. Jeder Punkt der Verteilung ist ein Stichprobenmittelwert.](schaetzen-konfidenzintervalle_files/figure-html/fig-stichprobenverteilung-r-1.png){#fig-stichprobenverteilung-r width=100%}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nwerte = normalwerte(2026, 2000 * 30, mittel=500, streuung=40)\nmittelwerte = werte.reshape(2000, 30).mean(axis=1)\n\nfig, ax = plt.subplots(figsize=(7, 3.2))\nax.hist(mittelwerte, bins=40, color=\"0.75\", edgecolor=\"white\")\nax.axvline(500, color=\"black\")\nax.set_xlabel(\"Mittelwert einer Stichprobe (n = 30)\")\nax.set_ylabel(\"Anzahl\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![Dieselbe Stichprobenverteilung mit matplotlib.](schaetzen-konfidenzintervalle_files/figure-html/fig-stichprobenverteilung-py-1.png){#fig-stichprobenverteilung-py width=100%}\n:::\n:::\n\n:::\n\nDiese Verteilung heisst Stichprobenverteilung. Sie liegt um den wahren Wert\nherum, und ihre Streuung ist die Grösse, um die es geht.\n\n### Standardfehler ist nicht Standardabweichung\n\nDer Unterschied wird ständig verwechselt und ist zentral.\n\n| Grösse | beschreibt die Streuung von | hängt ab von |\n|---|---|---|\n| Standardabweichung $s$ | den Einzelwerten | der Grundgesamtheit |\n| Standardfehler $s/\\sqrt{n}$ | dem geschätzten Mittelwert | zusätzlich vom Stichprobenumfang |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstichprobe <- werte[1:30]\n\nc(streuung_einzelwerte = sd(stichprobe),\n  standardfehler       = sd(stichprobe) / sqrt(length(stichprobe)),\n  simuliert            = sd(mittelwerte)) |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstreuung_einzelwerte       standardfehler            simuliert \n               35.26                 6.44                 7.32 \n```\n\n\n:::\n:::\n\n\nDie simulierte Streuung der 2000 Mittelwerte beträgt 7.32, die Formel\n$40/\\sqrt{30}$ liefert 7.30. Das ist der Beleg dafür, dass der Standardfehler\ntatsächlich misst, was er messen soll: die Schwankung des Mittelwerts von\nStichprobe zu Stichprobe.\n\nDer aus **einer** Stichprobe geschätzte Standardfehler weicht davon ab, hier\n6.44 statt 7.30, weil auch die geschätzte Standardabweichung schwankt.\n\nDie Wurzel im Nenner hat eine unangenehme Folge: Genauigkeit wird teuer. Wer\nden Standardfehler halbieren will, braucht die vierfache Stichprobe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- c(10, 40, 160, 640)\ndata.frame(n, standardfehler = round(40 / sqrt(n), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    n standardfehler\n1  10          12.65\n2  40           6.32\n3 160           3.16\n4 640           1.58\n```\n\n\n:::\n:::\n\n\nDas Konfidenzintervall für den Erwartungswert setzt diese Bestandteile zusammen:\n\n$$\\bar{x} \\pm t_{1-\\alpha/2,\\; n-1} \\cdot \\frac{s}{\\sqrt{n}}$$\n\n| Bestandteil | Bedeutung |\n|---|---|\n| $\\bar{x}$ | Punktschätzer, der Mittelwert der Stichprobe |\n| $s$ | Standardabweichung der Stichprobe |\n| $n$ | Stichprobenumfang |\n| $s/\\sqrt{n}$ | Standardfehler, die Streuung des Mittelwerts von Stichprobe zu Stichprobe |\n| $t_{1-\\alpha/2,\\;n-1}$ | Faktor aus der t-Verteilung, wächst bei kleinem n und bei höherem Niveau |\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung | Vorgehen |\n|---|---|---|---|---|\n| Zufallsstichprobe | Jede Einheit der Grundgesamtheit hatte eine bekannte Chance | aus dem Erhebungsdesign, nicht aus den Daten | Das Intervall ist um den falschen Wert zentriert, und keine Rechnung zeigt das | Auswahl korrigieren oder die Einschränkung berichten |\n| Unabhängigkeit | Die Beobachtungen beeinflussen sich nicht | Design, Zeit- oder Klumpenstruktur prüfen | Standardfehler zu klein, Intervall zu schmal | Verfahren für geschachtelte Daten |\n| Annähernd normalverteilter Mittelwert | Nicht die Daten, sondern der Mittelwert muss normal sein | [QQ-Plot](../wahrscheinlichkeit/qq-plots.qmd), Schiefe, n | Überdeckung weicht vom Niveau ab, vor allem bei kleinem n | Bootstrap oder Transformation |\n| Für Anteile: genügend Treffer | Faustregel: mindestens etwa zehn Treffer und zehn Nichttreffer | Auszählen | Das einfache Intervall reicht über null oder eins hinaus | Wilson oder Clopper-Pearson |\n\nBei grossem n sorgt der\n[zentrale Grenzwertsatz](../wahrscheinlichkeit/normalverteilung-zgws.qmd)\ndafür, dass die dritte Voraussetzung praktisch erfüllt ist, auch wenn die\nEinzelwerte schief verteilt sind.\n\n## Output lesen\n\nR, `t.test(x)`:\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| `mean of x` | Punktschätzer | die Zahl, um die das Intervall liegt |\n| `95 percent confidence interval` | Unter- und Obergrenze | die Spanne der mit den Daten vereinbaren Werte |\n| `t`, `df` | Teststatistik und Freiheitsgrade | `df` ist n minus eins; sie bestimmen den Faktor |\n| `p-value` | zum Test gegen null | für die reine Schätzung ohne Bedeutung |\n| `alternative hypothesis` | die geprüfte Gegenannahme | erinnert daran, dass `t.test` zugleich testet |\n\nPython, `stats.t.interval()` liefert nur das Tupel aus Unter- und Obergrenze.\nPunktschätzer, Standardfehler und Freiheitsgrade stehen dort nicht dabei,\nsondern werden selbst berechnet und gehören trotzdem in den Bericht. Wer die\nvollständige Tabelle möchte, nimmt `pingouin.ttest(x, 0)`; sie enthält\nzusätzlich Effektstärke und Power.\n\nFür Anteile gibt `prop.test()` in R Schätzwert, Intervall und einen Test aus,\n`proportion_confint()` in Python nur die beiden Grenzen. Die Methode steht in\nPython ausdrücklich im Aufruf (`wilson`, `beta`, `normal`), in R entscheidet die\nFunktionswahl darüber.\n\n## Interpretationsfallen\n\n### Was das Intervall bedeutet, und was nicht\n\nHier liegt die häufigste Fehlinterpretation der ganzen Statistik. Die Aussage\nbezieht sich auf das **Verfahren**, nicht auf das einzelne berechnete\nIntervall. Der wahre Parameter ist fest, das Intervall ist zufällig.\n\nRichtig ist: Wendet man das Verfahren immer wieder an, überdecken 95 Prozent der\nso erzeugten Intervalle den wahren Wert. Falsch ist die Aussage, der Parameter\nliege mit 95 Prozent Wahrscheinlichkeit in diesem einen Bereich.\n\nBeispiel 3 zeigt das an hundert Wiederholungen: Die Intervalle wandern, der\nwahre Wert steht fest, und 94 der 100 enthalten ihn. Welche sechs danebenliegen,\nlässt sich einem einzelnen Intervall nicht ansehen. Genau deshalb ist die\nAussage über das Verfahren und nicht über das Einzelintervall formuliert.\n\nEine zulässige Kurzform für den Bericht lautet: \"Mit den Daten vereinbar sind\nWerte zwischen [unten] und [oben].\"\n\nDazu kommen drei Verwechslungen, die regelmässig vorkommen:\n\n- **Standardabweichung und Standardfehler.** Die eine beschreibt die Streuung\n  der Einzelwerte, die andere die Genauigkeit des Mittelwerts. Wer beim\n  Berichten das Falsche nennt, gibt eine um den Faktor Wurzel n verschobene\n  Zahl an.\n- **Ein Intervall ist keine Spanne der Einzelwerte.** Dafür wäre das\n  Prognoseintervall zuständig, das deutlich breiter ausfällt.\n- **Zwei überlappende Intervalle bedeuten nicht, dass sich zwei Gruppen nicht\n  unterscheiden.** Der Vergleich zweier Gruppen wird am Intervall der Differenz\n  beurteilt, nicht am Überlappen zweier Einzelintervalle.\n\n## Ergebnis berichten\n\nVorlage für den Ergebnissatz:\n\n> [Kennzahl] beträgt [Schätzwert] [Einheit] (95-Prozent-Konfidenzintervall\n> [unten] bis [oben], n = [n]).\n\nGenannt werden Punktschätzer mit Einheit, Intervall und Niveau, der\nStichprobenumfang und bei Anteilen zusätzlich das verwendete Verfahren.\nBewertet wird das Ergebnis an der Breite des Intervalls und nicht daran, ob es\neinen bestimmten Wert enthält.\n\nBeispiel für eine Ergebnistabelle:\n\n| Kennzahl | Schätzwert | Standardfehler | 95-Prozent-Intervall | n |\n|---|---|---|---|---|\n| Mittlere Laufzeit (h) | | | | |\n| Anteil fehlerhafter Teile | | | | |\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt der reinen Schätzung |\n|---|---|\n| [Hypothesentests: Grundlagen](hypothesentests-grundlagen.qmd) | eine Ja-Nein-Entscheidung gegen eine Nullhypothese ist gefragt |\n| [t-Test für eine Stichprobe](../tests/t-test-eine-stichprobe.qmd) | derselbe Fall als Test formuliert, mit p-Wert |\n| [t-Test für zwei Stichproben](../tests/t-test-zwei-stichproben.qmd) | zwei Gruppen sollen verglichen werden |\n| [Bootstrap und Resampling](bootstrap-resampling.qmd) | die Verteilung der Schätzung ist unbekannt oder die Kennzahl ist kein Mittelwert |\n| [Power und Stichprobenumfang](power-stichprobenumfang.qmd) | die nötige Stichprobengrösse soll vorher bestimmt werden |\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Intervall für einen Mittelwert\n\n#### Frage und Datenlage\n\nZwanzig Packungen werden gewogen, angegeben sind 250 Gramm. Gesucht ist nicht\ndie Frage, **ob** das Sollgewicht eingehalten wird, sondern eine Spanne\nplausibler Werte für das mittlere Füllgewicht.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfuellgewicht <- c(249.1, 250.8, 248.6, 251.2, 249.9, 250.3, 248.2, 251.7,\n                  249.5, 250.1, 247.9, 250.6, 249.3, 251.0, 248.8, 250.4,\n                  249.7, 250.9, 248.4, 251.4)\n\nn <- length(fuellgewicht)\nmittel <- mean(fuellgewicht)\nstreuung <- sd(fuellgewicht)\nstandardfehler <- streuung / sqrt(n)\nt_kritisch <- qt(0.975, df = n - 1)\n\nround(c(n = n, mittel = mittel, sd = streuung,\n        standardfehler = standardfehler, t_kritisch = t_kritisch,\n        unten = mittel - t_kritisch * standardfehler,\n        oben = mittel + t_kritisch * standardfehler), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             n         mittel             sd standardfehler     t_kritisch \n       20.0000       249.8900         1.1327         0.2533         2.0930 \n         unten           oben \n      249.3599       250.4201 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Dasselbe in einem Aufruf\nt.test(fuellgewicht)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 249.3599 250.4201\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfuellgewicht = np.array([249.1, 250.8, 248.6, 251.2, 249.9, 250.3, 248.2,\n                         251.7, 249.5, 250.1, 247.9, 250.6, 249.3, 251.0,\n                         248.8, 250.4, 249.7, 250.9, 248.4, 251.4])\n\nn = len(fuellgewicht)\nmittel = fuellgewicht.mean()\nstreuung = fuellgewicht.std(ddof=1)\nstandardfehler = streuung / np.sqrt(n)\nt_kritisch = stats.t.ppf(0.975, df=n - 1)\n\nprint(f\"n = {n}  Mittel = {mittel:.4f}  SD = {streuung:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 20  Mittel = 249.8900  SD = 1.1327\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Standardfehler = {standardfehler:.4f}  t_kritisch = {t_kritisch:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStandardfehler = 0.2533  t_kritisch = 2.0930\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Intervall: {mittel - t_kritisch*standardfehler:.4f}\"\n      f\" bis {mittel + t_kritisch*standardfehler:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIntervall: 249.3599 bis 250.4201\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| n | 20 | Anzahl Packungen | |\n| Mittelwert | 249.890 | Punktschätzung | Die beste Einzelschätzung, aber ohne Angabe ihrer Unsicherheit wertlos. |\n| Standardabweichung | 1.133 | Streuung der **einzelnen** Packungen | Beschreibt die Daten. Rund zwei Drittel der Packungen liegen im Bereich 249.89 ± 1.13. |\n| Standardfehler | 0.253 | Streuung des **Mittelwerts** | Beschreibt die Schätzung. Er ist $s/\\sqrt{n}$ und damit rund viereinhalbmal kleiner als die Standardabweichung. Die Verwechslung dieser beiden Zahlen ist der häufigste Fehler auf dieser Seite. |\n| $t$-Quantil | 2.0930 | Faktor für 95 Prozent bei 19 Freiheitsgraden | Bei grossem n nähert er sich 1.96. Bei n = 20 ist er noch merklich grösser, was das Intervall verbreitert. |\n| Halbbreite | 0.530 | $t \\cdot SE$ | |\n| Intervall | 249.360 bis 250.420 | | Der Sollwert 250 liegt darin. |\n\n#### Interpretation und Ergebnissatz\n\nDas Intervall enthält den Sollwert 250. Daraus folgt: Ein Test gegen 250 wäre\nauf dem 5-Prozent-Niveau nicht signifikant. Das Intervall sagt aber mehr als der\nTest, denn es beziffert, was noch vereinbar ist: Ein wahres mittleres Füllgewicht\nvon 249.4 Gramm ist mit diesen Daten ebenso verträglich wie eines von 250.4.\n\nOb das genügt, entscheidet die Vorgabe. Bei einer Toleranz von einem halben\nGramm reicht das Intervall an beiden Enden knapp daran; für eine belastbare\nAussage bräuchte es mehr Packungen, siehe Beispiel 4.\n\n> Das mittlere Füllgewicht beträgt 249.89 g (95-Prozent-Konfidenzintervall\n> 249.36 bis 250.42 g, n = 20, SD = 1.13). Der deklarierte Wert von 250 g liegt\n> im Intervall.\n\n### Beispiel 2: Intervall für einen Anteil\n\n#### Frage und Datenlage\n\nVon 40 geprüften Teilen sind 3 fehlerhaft. Der geschätzte Fehleranteil beträgt\n7.5 Prozent. Gesucht ist ein Konfidenzintervall.\n\nBei Anteilen gibt es mehrere gebräuchliche Verfahren, und sie liefern spürbar\nverschiedene Ergebnisse. Das ist ein Fall, in dem die Wahl des Verfahrens die\nAussage verändert.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntreffer <- 3\ngesamt <- 40\n\n# Wald: die Lehrbuchformel\np <- treffer / gesamt\nz <- qnorm(0.975)\nwald <- p + c(-1, 1) * z * sqrt(p * (1 - p) / gesamt)\n\n# Wilson: prop.test ohne Stetigkeitskorrektur\nwilson <- prop.test(treffer, gesamt, correct = FALSE)$conf.int\n\n# Clopper-Pearson: exakt\nexakt <- binom.test(treffer, gesamt)$conf.int\n\nround(rbind(Wald = wald, Wilson = as.numeric(wilson),\n            exakt = as.numeric(exakt)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          [,1]   [,2]\nWald   -0.0066 0.1566\nWilson  0.0258 0.1986\nexakt   0.0157 0.2039\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ntreffer, gesamt = 3, 40\np = treffer / gesamt\nz = stats.norm.ppf(0.975)\n\nwald = (p - z * np.sqrt(p * (1 - p) / gesamt),\n        p + z * np.sqrt(p * (1 - p) / gesamt))\n\nnenner = 1 + z ** 2 / gesamt\nmitte = (p + z ** 2 / (2 * gesamt)) / nenner\nhalb = z * np.sqrt(p * (1 - p) / gesamt + z ** 2 / (4 * gesamt ** 2)) / nenner\nwilson = (mitte - halb, mitte + halb)\n\nexakt = (stats.beta.ppf(0.025, treffer, gesamt - treffer + 1),\n         stats.beta.ppf(0.975, treffer + 1, gesamt - treffer))\n\nprint(pd.DataFrame([wald, wilson, exakt],\n                   index=[\"Wald\", \"Wilson\", \"exakt\"],\n                   columns=[\"unten\", \"oben\"]).round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         unten    oben\nWald   -0.0066  0.1566\nWilson  0.0258  0.1986\nexakt   0.0157  0.2039\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Verfahren | Intervall | Breite | Wie es zu lesen ist |\n|---|---|---|---|\n| Wald | **-0.007** bis 0.157 | 0.163 | Die untere Grenze ist **negativ**. Ein negativer Fehleranteil existiert nicht; die Formel weiss das nicht. |\n| Wilson | 0.026 bis 0.199 | 0.173 | Bleibt im zulässigen Bereich und ist auch bei kleinen Anteilen zuverlässig. |\n| Clopper-Pearson (exakt) | 0.016 bis 0.204 | 0.188 | Das breiteste. \"Exakt\" heisst hier: Es hält das Niveau garantiert ein, tut das aber, indem es eher zu breit ist. |\n\nDer Vergleich über verschiedene Ausgangslagen zeigt, wann der Unterschied zählt:\n\n| Beobachtung | Wald | Wilson | exakt |\n|---|---|---|---|\n| 3 von 40 (7.5 %) | -0.007 bis 0.157 | 0.026 bis 0.199 | 0.016 bis 0.204 |\n| 8 von 40 (20 %) | 0.076 bis 0.324 | 0.105 bis 0.348 | 0.091 bis 0.357 |\n| 20 von 40 (50 %) | 0.345 bis 0.655 | 0.352 bis 0.648 | 0.338 bis 0.662 |\n| 45 von 300 (15 %) | 0.110 bis 0.190 | 0.114 bis 0.195 | 0.112 bis 0.196 |\n\nBei einem Anteil nahe 50 Prozent und bei grossem n stimmen alle drei praktisch\nüberein. Nahe 0 oder 1 und bei kleinem n gehen sie auseinander, und dort ist\nWald unbrauchbar.\n\n::: {.note-box}\n**Die Wald-Formel steht in jedem Lehrbuch und sollte trotzdem nicht verwendet\nwerden.** Sie unterschreitet das versprochene Niveau von 95 Prozent\nregelmässig, und zwar nicht nur bei extremen Anteilen. Ihre Beliebtheit rührt\ndaher, dass sie sich von Hand rechnen lässt.\n\nEmpfohlen ist Wilson für den Normalfall und Clopper-Pearson, wenn das Niveau\ngarantiert eingehalten werden muss. In R liefert `prop.test()` Wilson und\n`binom.test()` Clopper-Pearson; beide sind eine Zeile.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Von 40 geprüften Teilen waren 3 fehlerhaft (7.5 Prozent, 95-Prozent-\n> Konfidenzintervall nach Wilson 2.6 bis 19.9 Prozent). Das Intervall ist bei\n> diesem Umfang sehr breit; für eine Aussage über die Einhaltung einer\n> Fehlergrenze von 10 Prozent reicht die Datenlage nicht.\n\n### Beispiel 3: Was \"95 Prozent\" tatsächlich bedeutet\n\n#### Frage und Datenlage\n\nDie verbreitete Formulierung \"der wahre Wert liegt mit 95-prozentiger\nWahrscheinlichkeit im Intervall\" ist falsch. Was stimmt, lässt sich am besten\nzeigen, indem man die Erhebung hundertmal wiederholt.\n\nHier ist der wahre Mittelwert bekannt: 250 Gramm bei einer Streuung von 1.2. Aus\ndieser Grundgesamtheit werden hundert Stichproben zu je zwanzig Packungen\ngezogen, und für jede wird das Intervall berechnet.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# normalwerte() und lehmer() stehen im Setup-Chunk\ngewichte <- normalwerte(42, 2000, mittel = 250, streuung = 1.2)\nstichproben <- matrix(gewichte, nrow = 100, ncol = 20, byrow = TRUE)\n\nmittel_i <- rowMeans(stichproben)\nsd_i <- apply(stichproben, 1, sd)\nhalb_i <- qt(0.975, 19) * sd_i / sqrt(20)\nunten_i <- mittel_i - halb_i\noben_i <- mittel_i + halb_i\ntrifft <- unten_i <= 250 & 250 <= oben_i\n\npar(mar = c(4, 4, 3, 1))\nplot(NULL, xlim = range(c(unten_i, oben_i)), ylim = c(0, 101),\n     xlab = \"Füllgewicht (g)\", ylab = \"Stichprobe\",\n     main = paste(\"100 Intervalle,\", sum(trifft), \"enthalten den wahren Wert\"))\nsegments(unten_i, 1:100, oben_i, 1:100,\n         col = ifelse(trifft, \"grey60\", \"firebrick\"), lwd = 1.5)\nabline(v = 250, lwd = 2, col = \"steelblue\")\n\ncat(\"getroffen:\", sum(trifft), \"von 100\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngetroffen: 94 von 100\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"mittlere Breite:\", round(mean(oben_i - unten_i), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmittlere Breite: 1.1221 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: hundert Intervalle aus derselben Grundgesamtheit.](schaetzen-konfidenzintervalle_files/figure-html/fig-b3-ki-r-1.png){#fig-b3-ki-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# normalwerte() und lehmer() stehen im Setup-Chunk\ngewichte = normalwerte(42, 2000, mittel=250, streuung=1.2)\nstichproben = gewichte.reshape(100, 20)\n\nmittel_i = stichproben.mean(axis=1)\nsd_i = stichproben.std(axis=1, ddof=1)\nhalb_i = stats.t.ppf(0.975, 19) * sd_i / np.sqrt(20)\nunten_i, oben_i = mittel_i - halb_i, mittel_i + halb_i\ntrifft = (unten_i <= 250) & (250 <= oben_i)\n\nfig, achse = plt.subplots(figsize=(7, 4.0))\nfor k in range(100):\n    achse.plot([unten_i[k], oben_i[k]], [k + 1, k + 1],\n               color=\"0.6\" if trifft[k] else \"firebrick\", linewidth=1.5)\nachse.axvline(250, linewidth=2, color=\"steelblue\")\nachse.set_xlabel(\"Füllgewicht (g)\")\nachse.set_ylabel(\"Stichprobe\")\nachse.set_title(f\"100 Intervalle, {trifft.sum()} enthalten den wahren Wert\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselbe Darstellung in Python.](schaetzen-konfidenzintervalle_files/figure-html/fig-b3-ki-py-1.png){#fig-b3-ki-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(\"getroffen:\", int(trifft.sum()), \"von 100\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngetroffen: 94 von 100\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"mittlere Breite:\", round(float((oben_i - unten_i).mean()), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmittlere Breite: 1.1221\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| getroffene Intervalle | **94 von 100** | Nahe an den erwarteten 95. Die Abweichung ist Zufall: Bei hundert Wiederholungen schwankt die Zahl um 95 mit einer Standardabweichung von rund 2.2. |\n| verfehlte Intervalle | 6 | Im Bild rot. Sie sind nicht falsch gerechnet, sondern die vorgesehene Ausnahme. |\n| mittlere Breite | 1.122 | Die Intervalle sind verschieden breit, weil jede Stichprobe eine eigene Standardabweichung liefert. |\n\nDas Bild zeigt den entscheidenden Punkt: **Die Intervalle wandern, der wahre\nWert steht fest.** Die blaue Linie bei 250 ist unverrückbar; was von Stichprobe\nzu Stichprobe schwankt, sind Lage und Breite der Intervalle.\n\n::: {.note-box}\n**Deshalb ist die Aussage \"mit 95 Prozent Wahrscheinlichkeit liegt der wahre\nWert in diesem Intervall\" falsch.** Der wahre Wert ist eine feste Zahl. Er liegt\nim berechneten Intervall oder nicht; eine Wahrscheinlichkeit gibt es dafür\nnicht.\n\nWas stimmt: **Das Verfahren** trifft in 95 Prozent der Anwendungen. Die Aussage\ngilt der Methode, nicht dem einzelnen Ergebnis.\n\nPraktisch macht das selten einen Unterschied in der Entscheidung, wohl aber in\nder Formulierung. Eine zulässige Kurzform lautet: \"Mit den Daten vereinbar sind\nWerte zwischen 249.4 und 250.4 Gramm.\"\n:::\n\n#### Interpretation\n\nDer zweite Punkt, den das Bild zeigt: Die verfehlten Intervalle sehen nicht\nanders aus als die getroffenen. Sie sind nicht auffällig schmal oder auffällig\nweit verschoben. Es gibt kein Merkmal, an dem sich einem einzelnen Intervall\nansehen liesse, ob es zu den 95 oder zu den 5 Prozent gehört.\n\n### Beispiel 4: Wie viel Genauigkeit kostet\n\n#### Frage und Datenlage\n\nDas Intervall aus Beispiel 1 ist rund ein Gramm breit. Was kostet es, es auf ein\nhalbes Gramm zu bringen?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsigma <- 1.2\numfaenge <- seq(5, 320, by = 5)\nhalbbreiten <- qt(0.975, umfaenge - 1) * sigma / sqrt(umfaenge)\n\npar(mar = c(4, 4, 3, 1))\nplot(umfaenge, halbbreiten, type = \"l\", lwd = 2, col = \"steelblue\",\n     xlab = \"n\", ylab = \"Halbbreite (g)\",\n     main = \"Genauigkeit und Stichprobenumfang\")\nabline(h = c(0.5, 0.25), lty = 2, col = \"firebrick\")\n\nfor (nn in c(10, 20, 40, 80, 160, 320)) {\n  cat(sprintf(\"n = %3d: Halbbreite = %.4f g\\n\",\n              nn, qt(0.975, nn - 1) * sigma / sqrt(nn)))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn =  10: Halbbreite = 0.8584 g\nn =  20: Halbbreite = 0.5616 g\nn =  40: Halbbreite = 0.3838 g\nn =  80: Halbbreite = 0.2670 g\nn = 160: Halbbreite = 0.1874 g\nn = 320: Halbbreite = 0.1320 g\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 4: Halbbreite des Intervalls in Abhängigkeit vom Umfang.](schaetzen-konfidenzintervalle_files/figure-html/fig-b4-ki-r-3.png){#fig-b4-ki-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nsigma = 1.2\numfaenge = np.arange(5, 325, 5)\nhalbbreiten = stats.t.ppf(0.975, umfaenge - 1) * sigma / np.sqrt(umfaenge)\n\nfig, achse = plt.subplots(figsize=(7, 3.4))\nachse.plot(umfaenge, halbbreiten, color=\"steelblue\", linewidth=2)\nfor h in (0.5, 0.25):\n    achse.axhline(h, linestyle=\"--\", color=\"firebrick\")\nachse.set_xlabel(\"n\")\nachse.set_ylabel(\"Halbbreite (g)\")\nachse.set_title(\"Genauigkeit und Stichprobenumfang\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselbe Kurve in Python.](schaetzen-konfidenzintervalle_files/figure-html/fig-b4-ki-py-1.png){#fig-b4-ki-py width=100%}\n:::\n\n```{.python .cell-code}\nfor nn in (10, 20, 40, 80, 160, 320):\n    h = stats.t.ppf(0.975, nn - 1) * sigma / np.sqrt(nn)\n    print(f\"n = {nn:3d}: Halbbreite = {h:.4f} g\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn =  10: Halbbreite = 0.8584 g\nn =  20: Halbbreite = 0.5616 g\nn =  40: Halbbreite = 0.3838 g\nn =  80: Halbbreite = 0.2670 g\nn = 160: Halbbreite = 0.1874 g\nn = 320: Halbbreite = 0.1320 g\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| n | Halbbreite | Verhältnis zum vorigen |\n|---|---|---|\n| 10 | 0.858 g | |\n| 20 | 0.562 g | 0.65 |\n| 40 | 0.384 g | 0.68 |\n| 80 | 0.267 g | 0.70 |\n| 160 | 0.187 g | 0.70 |\n| 320 | 0.132 g | 0.71 |\n\nDas Verhältnis nähert sich $1/\\sqrt{2} = 0.707$: **Eine Verdoppelung des Umfangs\nverkleinert das Intervall um rund 29 Prozent, eine Halbierung der Breite\nverlangt viermal so viele Beobachtungen.**\n\nVon 20 auf 80 Packungen, also das Vierfache, halbiert die Halbbreite von 0.56\nauf 0.27 Gramm. Die Kurve fällt anfangs steil und wird dann flach; jenseits von\netwa hundert Beobachtungen bringt jede weitere spürbar weniger.\n\n::: {.note-box}\nDas ist die Kehrseite derselben Wurzel, die auf der Seite zur\n[Power](power-stichprobenumfang.qmd) den Stichprobenumfang treibt. Beide Male\nsteht $\\sqrt{n}$ im Nenner, und beide Male folgt daraus dasselbe: Genauigkeit\nist teuer, und der Preis steigt quadratisch.\n\nWer ein Intervall bestimmter Breite braucht, kann den Umfang direkt planen. Für\neine Halbbreite $h$ gilt näherungsweise $n \\approx (1.96 \\cdot \\sigma / h)^2$;\nfür $\\sigma$ = 1.2 und $h$ = 0.25 ergibt das rund 89 Beobachtungen.\n:::\n\n#### Interpretation und Ergebnissatz\n\nDie Planung über die Intervallbreite ist der Powerrechnung oft vorzuziehen,\nweil sie eine inhaltlich fassbare Grösse verwendet: \"Wir wollen das mittlere\nFüllgewicht auf ein Viertelgramm genau kennen\" ist eine Vorgabe, über die sich\nmit Fachleuten sprechen lässt. \"Wir wollen einen Effekt von d = 0.5 mit 80\nProzent Wahrscheinlichkeit finden\" ist es weniger.\n\n> Bei einer angenommenen Streuung von 1.2 g und einer angestrebten Halbbreite\n> von 0.25 g werden rund 89 Packungen benötigt. Mit den vorliegenden 20\n> Packungen beträgt die Halbbreite 0.53 g.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nWarum wird ein Konfidenzintervall breiter, wenn man von 95 auf 99 Prozent\nNiveau geht?\n\n- [x] Weil Sicherheit mit Unschärfe bezahlt wird ~ Richtig. Ein höheres Niveau\n      verlangt, dass das Verfahren häufiger richtig liegt. Das geht nur, indem\n      mehr Werte zugelassen werden. Bei hundert Prozent wäre das Intervall\n      unendlich breit und wertlos.\n- [ ] Weil die Stichprobe kleiner wird ~ Der Umfang bleibt unverändert, nur\n      der Faktor vor dem Standardfehler wächst.\n- [ ] Weil die Streuung der Daten zunimmt ~ Die Daten sind dieselben.\n:::\n\n::: {.quiz}\nEine Umfrage berichtet 52 Prozent Zustimmung mit einem Intervall von 49 bis 55\nProzent. Was folgt für die Frage, ob die Mehrheit zustimmt?\n\n- [ ] Die Mehrheit stimmt zu, der Punktwert liegt über 50 ~ Der Punktwert\n      allein trägt diese Aussage nicht, und genau dafür steht das Intervall\n      daneben.\n- [x] Die Frage bleibt offen ~ Richtig. Das Intervall enthält Werte unter\n      fünfzig Prozent, also ist auch eine Minderheit mit den Daten vereinbar.\n- [ ] Die Mehrheit stimmt nicht zu ~ Ebenso wenig belegt. Beide Möglichkeiten\n      liegen im Intervall.\n:::\n\n::: {.quiz}\nIn @fig-ueberdeckung-r sind hundert Konfidenzintervalle gezeichnet, einige\nverfehlen den wahren Wert. Was zeigt das Bild?\n\n- [ ] Dass das Verfahren fehlerhaft ist ~ Die Fehlschläge sind eingebaut und\n      ihre Häufigkeit ist genau das gewählte Niveau.\n- [x] Dass die Aussage dem Verfahren gilt und nicht dem einzelnen Intervall ~\n      Richtig. Rund fünf von hundert verfehlen den wahren Wert. Welches\n      betroffen ist, weiss man in der Praxis nie, weil der wahre Wert unbekannt\n      ist.\n- [ ] Dass die Stichproben zu klein waren ~ Bei grösseren Stichproben wären die\n      Intervalle schmaler, aber immer noch würden rund fünf Prozent danebenliegen.\n:::\n\n::: {.quiz}\nEine Auswertung berichtet den Mittelwert mit der Standardabweichung, eine\nzweite denselben Mittelwert mit dem Standardfehler. Welche Zahl ist grösser?\n\n- [x] Die Standardabweichung, und zwar um den Faktor Wurzel n ~ Richtig. Der\n      Standardfehler ist die Standardabweichung geteilt durch die Wurzel des\n      Stichprobenumfangs. Bei n = 100 ist er ein Zehntel davon.\n- [ ] Der Standardfehler, weil er die Unsicherheit enthält ~ Er beschreibt eine\n      andere Streuung, nämlich die des Mittelwerts, und ist deshalb kleiner.\n- [ ] Beide sind gleich gross ~ Nur bei n = 1, und dann ist keine der beiden\n      Zahlen sinnvoll.\n:::\n\n## Verlinkte Ressourcen\n\n- [OpenIntro Statistics, Kapitel zur Schätzung](https://www.openintro.org/book/os/)\n- [statsmodels: Konfidenzintervalle für Anteile](https://www.statsmodels.org/stable/generated/statsmodels.stats.proportion.proportion_confint.html)\n",
    "supporting": [
      "schaetzen-konfidenzintervalle_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}