{
  "hash": "e21a435fdff44c5478fe38a70f319141",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Explorative Datenanalyse\"\ndescription: \"Verteilungen, Ausreisser und Zusammenhänge systematisch sichten.\"\ncategories: [\"EDA\", \"Visualisierung\", \"R\", \"Python\"]\nquelle: [\"ESDS\"]\nseitentyp: konzept\nstand: fertig\norder: 50\n---\n\n\n\n\n\n## Kernideen\n\n- Explorative Analyse **erzeugt Fragen**, sie beantwortet keine.\n- Die **Erwartung wird vor** dem Blick in die Daten formuliert — sonst bestätigt\n  man, was man ohnehin vermutet hat.\n- **Variation**: ein Merkmal für sich ansehen. **Kovariation**: zwei Merkmale\n  gemeinsam.\n- Auffällige Muster verraten meist etwas über die **Erhebung**, nicht über den\n  untersuchten Gegenstand.\n- Platzhalter für fehlende Werte sind gefährlicher als offene Lücken, weil sie\n  mitgerechnet werden.\n- Die Grafiken dieser Phase sind Arbeitsmittel und **dürfen hässlich sein**.\n- Jeder Befund ist **vorläufig**, bis er an neuen Daten geprüft ist.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Data Wrangling](../../daten/data-wrangling.qmd) für die\nAufbereitung, [Skalenniveaus](skalenniveaus.qmd) und\n[Lage- und Streuungsmasse](lage-streuungsmasse.qmd) für die Kennzahlen sowie\n[ggplot2](../../visualisierung/ggplot2.qmd) für die Grafiken. Diese Seite\nbringt keine neue Technik, sondern ordnet die bisherigen zu einem Vorgehen. Was\ndabei an Mängeln auffällt, behandelt die\n[Datenqualität](../../daten/datenqualitaet.qmd).\n:::\n\n### Was EDA ist und was nicht\n\nZwischen Rohdaten und Modell liegt eine Phase, die in Lehrbüchern oft fehlt und\nin der Praxis den Ausschlag gibt. Sie besteht nicht darin, eine Liste\nvorgeschriebener Kennzahlen abzuarbeiten. Sie besteht aus einer Schleife: eine\nFrage an die Daten stellen, sie mit einer Kennzahl oder Grafik beantworten, aus\nder Antwort die nächste Frage ableiten.\n\nDaraus folgt etwas Praktisches. Die Grafiken dieser Phase sind Arbeitsmittel\nund dürfen hässlich sein. Wer hier schon an Farben und Beschriftung feilt,\nverlangsamt sich genau dort, wo Tempo zählt. Sorgfalt in der Gestaltung kommt\nspäter, wenn feststeht, was überhaupt gezeigt werden soll.\n\n### Die Erwartung kommt vor dem Blick\n\nDer menschliche Verstand findet für fast jedes Bild eine Erklärung, auch für\nZufall. Wer eine Grafik ansieht und danach überlegt, was sie bedeutet, bestätigt\noft nur, was er ohnehin vermutet hat.\n\nDer Gegenzug ist billig und wirksam: **vorher aufschreiben, was man erwartet.**\nEtwa so, für das Merkmal Blutdruck: Werte zwischen 90 und 180, eingipflig,\nleicht rechtsschief, Mittelwert um 130. Weicht die Grafik davon ab, fällt es\nsofort auf, und die Abweichung ist der interessante Teil.\n\n### Die Reihenfolge\n\n| Schritt | Frage | Werkzeug |\n|---|---|---|\n| 1. Struktur | Wie viele Zeilen, welche Spalten, welche Typen? | `str()`, `info()` |\n| 2. Vollständigkeit | Wo fehlen Werte, wo stehen **Platzhalter**? | Zählen, Minimum und Maximum |\n| 3. Variation | Wertebereich, Form, Gipfel, Absonderlichkeiten je Merkmal | Histogramm, Boxplot, Kennzahlen |\n| 4. Kovariation | Welche Merkmale hängen zusammen? | Streudiagramm, Boxplots je Gruppe, Kreuztabelle |\n| 5. Aufteilung | Ändert sich das Bild je Gruppe? | dieselben Grafiken, nach Gruppen getrennt |\n\nSchritt 2 vor Schritt 3 ist wichtig: Ein Platzhalter von -1 oder 999 verzerrt\njede Kennzahl, und zwar unauffällig.\n\n### Welche Darstellung wozu\n\n| Kombination | Darstellung |\n|---|---|\n| ein metrisches Merkmal | Histogramm, Boxplot, Verteilungsfunktion |\n| ein kategoriales Merkmal | Häufigkeitstabelle, Stabdiagramm |\n| metrisch und metrisch | Streudiagramm |\n| metrisch und kategorial | Boxplots nebeneinander |\n| kategorial und kategorial | Kreuztabelle, gestapelte Balken |\n\n## Beispiele\n\nAlle Beispiele arbeiten mit demselben konstruierten Datensatz: 400\nUntersuchungen mit Gewicht, Alter, Standort und Blutdruck. Eingebaut sind drei\nAuffälligkeiten, wie sie in echten Exporten vorkommen — welche, verrät die\nAuswertung selbst.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Erst die Struktur, dann die Zahlen\n\n#### Frage und Datenlage\n\nDer erste Blick gilt nicht der Verteilung, sondern der Vollständigkeit: Wie\nviele Zeilen, welche Typen, wo fehlen Werte — und wo stehen **Platzhalter**, die\nwie Werte aussehen?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(roh)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t400 obs. of  4 variables:\n $ gewicht  : num  65.7 104.5 85.9 71.3 73.2 ...\n $ alter    : num  21 24 40 53 60 44 49 26 72 47 ...\n $ standort : chr  \"Bern\" \"Bern\" \"Bern\" \"Bern\" ...\n $ blutdruck: num  105 124 140 135 140 145 142 115 144 130 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(roh)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    gewicht           alter            standort     blutdruck    \n Min.   : -1.00   Min.   :18.00   Length   :400   Min.   : 92.0  \n 1st Qu.: 73.95   1st Qu.:32.00   N.unique :  3   1st Qu.:123.0  \n Median : 80.50   Median :45.00   N.blank  :  0   Median :130.5  \n Mean   : 80.53   Mean   :45.35   Min.nchar:  4   Mean   :131.8  \n 3rd Qu.: 87.80   3rd Qu.:60.00   Max.nchar:  4   3rd Qu.:141.0  \n Max.   :124.50   Max.   :74.00                   Max.   :160.0  \n                                                  NAs    :18     \n```\n\n\n:::\n\n```{.r .cell-code}\n# Wo fehlt etwas, und wo sieht etwas nach Platzhalter aus?\ncolSums(is.na(roh))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  gewicht     alter  standort blutdruck \n        0         0         0        18 \n```\n\n\n:::\n\n```{.r .cell-code}\nsapply(roh[, c(\"gewicht\", \"alter\", \"blutdruck\")], range, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     gewicht alter blutdruck\n[1,]    -1.0    18        92\n[2,]   124.5    74       160\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(roh.dtypes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngewicht      float64\nalter          int64\nstandort      object\nblutdruck    float64\ndtype: object\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(roh.describe().round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       gewicht   alter  blutdruck\ncount   400.00  400.00     382.00\nmean     80.53   45.35     131.85\nstd      13.20   16.16      11.66\nmin      -1.00   18.00      92.00\n25%      73.95   32.00     123.00\n50%      80.50   45.00     130.50\n75%      87.80   60.00     141.00\nmax     124.50   74.00     160.00\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(roh.isna().sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngewicht       0\nalter         0\nstandort      0\nblutdruck    18\ndtype: int64\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(roh[[\"gewicht\", \"alter\", \"blutdruck\"]].agg([\"min\", \"max\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     gewicht  alter  blutdruck\nmin     -1.0     18       92.0\nmax    124.5     74      160.0\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Merkmal | Typ | fehlend | Minimum | Maximum | Auffällig? |\n|---|---|---|---|---|---|\n| `gewicht` | numerisch | 0 | **-1.0** | 124.5 | **ja** — ein Gewicht von -1 kg gibt es nicht |\n| `alter` | ganzzahlig | 0 | 18 | 74 | nein |\n| `standort` | Text | 0 | — | — | nein (Bern 200, Chur 129, Sion 71) |\n| `blutdruck` | numerisch | **18** | 92 | 160 | die Lücken sind offen deklariert |\n\n| Beobachtung | Erklärung |\n|---|---|\n| `gewicht` hat **null** fehlende Werte und trotzdem ein Problem | Die -1 ist ein **Platzhalter**: Irgendeine Erfassungsstelle hat \"unbekannt\" als -1 codiert. Für R und Python ist das eine gültige Zahl. |\n| `blutdruck` hat 18 offene Lücken | Das ist der **harmlosere** Fall: `NA` beziehungsweise `NaN` wird von jeder Kennzahl ausgeschlossen oder erzeugt eine Fehlermeldung. |\n| Der Blick auf **Minimum und Maximum** findet beides | Deshalb steht er vor jeder Verteilungsgrafik. Eine Kennzahl allein verrät den Platzhalter nicht — bei drei Fällen von 400 verschiebt er den Mittelwert um weniger als ein Prozent. |\n| Die Standorte sind ungleich besetzt | 200, 129 und 71. Für alle Gruppenvergleiche heisst das: **relative** Häufigkeiten verwenden. |\n\n::: {.note-box}\n**Die üblichen Platzhalter, nach denen sich zu suchen lohnt:**\n\n| Wert | Herkunft |\n|---|---|\n| -1, -99, -999 | Codierung für \"unbekannt\" in älteren Erfassungssystemen |\n| 0 bei Merkmalen, die nicht null sein können | Gewicht, Blutdruck, Alter |\n| 999, 9999 | dasselbe wie oben, nur nach oben |\n| 1900-01-01, 1970-01-01 | Standarddatum bei fehlender Eingabe |\n| leere Zeichenkette gegen `NA` | zwei verschiedene Zustände, die gleich aussehen |\n\nSie alle haben eine Eigenschaft gemeinsam: **Sie werden mitgerechnet.** Eine\noffene Lücke fällt auf, ein Platzhalter nicht.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Der Datensatz umfasst 400 Beobachtungen. Beim Blutdruck fehlen 18 Werte\n> (4.5 Prozent), beim Gewicht sind drei Werte mit dem Platzhalter -1 codiert.\n> Beide werden vor der Auswertung als fehlend gekennzeichnet.\n\n### Beispiel 2: Was der Platzhalter anrichtet\n\n#### Frage und Datenlage\n\nDrei Werte von 400 — kann das viel ausmachen? Die Antwort hängt davon ab,\nwelche Kennzahl man ansieht.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaten <- roh\ndaten$gewicht[daten$gewicht < 0] <- NA\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nhist(roh$gewicht, breaks = 30, col = \"grey75\", border = \"white\",\n     main = \"mit Platzhaltern\", xlab = \"Gewicht (kg)\")\nhist(daten$gewicht, breaks = 30, col = \"grey75\", border = \"white\",\n     main = \"bereinigt\", xlab = \"Gewicht (kg)\")\npar(mfrow = c(1, 1))\n\nround(rbind(\n  mit_platzhalter = c(n = sum(!is.na(roh$gewicht)), mittel = mean(roh$gewicht),\n                      sd = sd(roh$gewicht), min = min(roh$gewicht),\n                      median = median(roh$gewicht)),\n  bereinigt = c(n = sum(!is.na(daten$gewicht)),\n                mittel = mean(daten$gewicht, na.rm = TRUE),\n                sd = sd(daten$gewicht, na.rm = TRUE),\n                min = min(daten$gewicht, na.rm = TRUE),\n                median = median(daten$gewicht, na.rm = TRUE))\n), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  n mittel    sd  min median\nmit_platzhalter 400  80.53 13.20 -1.0   80.5\nbereinigt       397  81.15 11.17 49.7   80.6\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 2: links das Gewicht mit den Platzhaltern, rechts bereinigt.](explorative-datenanalyse_files/figure-html/fig-b2-eda-r-1.png){#fig-b2-eda-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndaten = roh.copy()\ndaten.loc[daten[\"gewicht\"] < 0, \"gewicht\"] = np.nan\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nachsen[0].hist(roh[\"gewicht\"], bins=30, color=\"0.75\", edgecolor=\"white\")\nachsen[0].set_title(\"mit Platzhaltern\")\nachsen[1].hist(daten[\"gewicht\"].dropna(), bins=30, color=\"0.75\",\n               edgecolor=\"white\")\nachsen[1].set_title(\"bereinigt\")\nfor achse in achsen:\n    achse.set_xlabel(\"Gewicht (kg)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselbe Gegenüberstellung in Python.](explorative-datenanalyse_files/figure-html/fig-b2-eda-py-1.png){#fig-b2-eda-py width=100%}\n:::\n\n```{.python .cell-code}\ndef kennzahlen(reihe):\n    return {\"n\": int(reihe.notna().sum()), \"mittel\": reihe.mean(),\n            \"sd\": reihe.std(), \"min\": reihe.min(), \"median\": reihe.median()}\n\n\nprint(pd.DataFrame([kennzahlen(roh[\"gewicht\"]), kennzahlen(daten[\"gewicht\"])],\n                   index=[\"mit_platzhalter\", \"bereinigt\"]).round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   n  mittel     sd   min  median\nmit_platzhalter  400   80.53  13.20  -1.0    80.5\nbereinigt        397   81.15  11.17  49.7    80.6\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Kennzahl | mit Platzhaltern | bereinigt | Abweichung |\n|---|---|---|---|\n| n | 400 | 397 | |\n| Mittelwert | 80.53 | 81.15 | **-0.8 %** |\n| **Standardabweichung** | **13.20** | **11.17** | **+18 %** |\n| Minimum | **-1.0** | 49.7 | |\n| Median | 80.5 | 80.6 | **+0.1** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Der **Mittelwert** verschiebt sich kaum | Drei von 400 Werten, jeder rund 82 kg zu tief — das macht 0.6 kg auf den Mittelwert. Wer nur ihn ansieht, merkt nichts. |\n| Die **Standardabweichung** ist 18 Prozent zu gross | Weil sie quadriert: $(80.5 - (-1))^2 = 6642$ je Platzhalter. Drei davon beherrschen die Summe. |\n| Der **Median** bewegt sich um 0.1 kg | Er zählt nur ab. Drei Extremwerte am unteren Ende verschieben ihn um anderthalb Rangpositionen — bei 400 Werten praktisch nichts. |\n| Das **Minimum** verrät alles | -1.0 gegen 49.7. Es ist die billigste und wirksamste Prüfung, die es gibt. |\n| Im linken **Histogramm** sitzt ein winziger Balken bei -1 | Bei 30 Klassen über einen Bereich von 125 kg ist er kaum zu sehen — und die Hauptverteilung wird zusammengedrückt, weil die Achse bis -1 reicht. |\n\n::: {.note-box}\n**Warum das die gefährlichste Sorte Datenfehler ist:** Er erzeugt keine\nFehlermeldung, verändert die auffälligste Kennzahl kaum und die unauffälligste\nstark. Ein Bericht mit \"Mittelwert 80.5 kg, Standardabweichung 13.2\" sieht\nvollkommen plausibel aus.\n\nUnd die Folge zieht sich durch: Jedes Konfidenzintervall, jeder t-Test und jede\nRegression, die auf dieser Streuung beruhen, sind zu breit beziehungsweise zu\nschwach.\n\n**Was nicht geht:** die drei Zeilen stillschweigend löschen. Berichtet gehört,\nwie viele Werte aus welchem Grund entfernt wurden.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Drei Gewichtsangaben waren mit dem Platzhalter -1 codiert und wurden als\n> fehlend gekennzeichnet (n = 397 statt 400). Dadurch sinkt die\n> Standardabweichung von 13.20 auf 11.17 kg, während sich der Mittelwert nur um\n> 0.6 kg ändert.\n\n### Beispiel 3: Ein Muster, das von der Erhebung erzählt\n\n#### Frage und Datenlage\n\nDie Erwartung für den Blutdruck war notiert: Werte zwischen 90 und 180,\neingipflig, leicht rechtsschief, Mittelwert um 130. Stimmt das Bild damit\nüberein?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(roh, aes(blutdruck)) +\n  geom_histogram(binwidth = 1, fill = \"grey70\", colour = \"white\") +\n  labs(x = \"Blutdruck\", y = \"Anzahl\")\n\nround(c(n = sum(!is.na(roh$blutdruck)),\n        mittel = mean(roh$blutdruck, na.rm = TRUE),\n        median = median(roh$blutdruck, na.rm = TRUE),\n        minimum = min(roh$blutdruck, na.rm = TRUE),\n        maximum = max(roh$blutdruck, na.rm = TRUE)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      n  mittel  median minimum maximum \n 382.00  131.85  130.50   92.00  160.00 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Der Verdacht: wie oft enden die Werte auf 0 oder 5?\nendziffern <- table(roh$blutdruck %% 10)\nround(prop.table(endziffern), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    0     1     2     3     4     5     6     7     8     9 \n0.204 0.081 0.076 0.055 0.058 0.259 0.065 0.058 0.073 0.071 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(sum(prop.table(endziffern)[c(\"0\", \"5\")]), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.463\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: Verteilung des Blutdrucks mit Klassenbreite 1. Der Bereich stimmt, die Form ist auffällig gezackt.](explorative-datenanalyse_files/figure-html/fig-b3-eda-r-3.png){#fig-b3-eda-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nwerte = roh[\"blutdruck\"].dropna()\n\nfig, achse = plt.subplots(figsize=(7, 3.2))\nachse.hist(werte, bins=int(werte.max() - werte.min()),\n           color=\"0.7\", edgecolor=\"white\")\nachse.set_xlabel(\"Blutdruck\")\nachse.set_ylabel(\"Anzahl\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselbe Verteilung mit matplotlib.](explorative-datenanalyse_files/figure-html/fig-b3-eda-py-1.png){#fig-b3-eda-py width=100%}\n:::\n\n```{.python .cell-code}\nprint({\"n\": len(werte), \"mittel\": round(werte.mean(), 2),\n       \"median\": werte.median(), \"minimum\": werte.min(),\n       \"maximum\": werte.max()})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'n': 382, 'mittel': np.float64(131.85), 'median': np.float64(130.5), 'minimum': np.float64(92.0), 'maximum': np.float64(160.0)}\n```\n\n\n:::\n\n```{.python .cell-code}\nendziffern = (werte % 10).value_counts(normalize=True).sort_index().round(3)\nprint(endziffern)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nblutdruck\n0.0    0.204\n1.0    0.081\n2.0    0.076\n3.0    0.055\n4.0    0.058\n5.0    0.259\n6.0    0.065\n7.0    0.058\n8.0    0.073\n9.0    0.071\nName: proportion, dtype: float64\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Anteil auf 0 oder 5:\",\n      round(float(endziffern[0.0] + endziffern[5.0]), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnteil auf 0 oder 5: 0.463\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nDie Erwartung gegen den Befund:\n\n| Erwartet | Beobachtet | Stimmt? |\n|---|---|---|\n| Werte zwischen 90 und 180 | 92 bis 160 | ja |\n| eingipflig | ja | ja |\n| Mittelwert um 130 | **131.85** | ja |\n| glatte Form | **stark gezackt** | **nein** |\n\nUnd die Endziffern, die den Zacken erklären:\n\n| Endziffer | 0 | 1 | 2 | 3 | 4 | **5** | 6 | 7 | 8 | 9 |\n|---|---|---|---|---|---|---|---|---|---|---|\n| Anteil | **0.204** | 0.081 | 0.076 | 0.055 | 0.058 | **0.259** | 0.065 | 0.058 | 0.073 | 0.071 |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Erwartet wären **10 Prozent** je Endziffer | Bei sauber gemessenen Werten. |\n| Beobachtet: 20.4 und 25.9 Prozent auf 0 und 5 | Zusammen **46.3 Prozent** statt der erwarteten 20. |\n| Die übrigen acht Ziffern liegen bei 5.5 bis 8.1 Prozent | Also **unter** 10 — genau um den Betrag, der auf 0 und 5 zusätzlich landet. |\n| Das ist eine **Rundungspräferenz** | Ein Teil der Werte wurde nicht abgelesen, sondern geschätzt und auf fünf gerundet. Hier betrifft es rund 150 der 400 Beobachtungen. |\n\n::: {.note-box}\n**Was das für die Auswertung heisst:** Die Genauigkeit ist geringer, als die\nZahlen suggerieren. Konkret:\n\n- Kennzahlen wie Mittelwert und Median bleiben **brauchbar** — die Rundung\n  streut in beide Richtungen und hebt sich weitgehend auf.\n- Der **Anteil unter einem Grenzwert** wird unzuverlässig, wenn der Grenzwert\n  selbst auf 0 oder 5 endet. Ein Schwellenwert von 140 trifft mitten in eine\n  Häufung.\n- **Feine Unterschiede** zwischen Gruppen verschwinden im Rundungsrauschen.\n\nSolche Muster sind fast immer Hinweise auf die **Erhebung**, nicht auf den\nuntersuchten Gegenstand. Gehäufte Rundwerte, verdächtig glatte Mittelwerte oder\nidentische Wiederholungen entstehen beim Erfassen, nicht in der Natur.\n\nUnd sie fallen nur bei **Klassenbreite 1** auf. Ein Histogramm mit der üblichen\nKlassenzahl hätte die Zacken weggeglättet — ein Beispiel dafür, dass man in der\nErkundungsphase absichtlich zu fein auflöst.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Blutdruckwerte enden zu 46.3 Prozent auf 0 oder 5, erwartet wären 20\n> Prozent. Ein erheblicher Teil der Werte wurde offenbar gerundet erfasst; die\n> tatsächliche Messgenauigkeit liegt bei etwa 5 mmHg.\n\n### Beispiel 4: Zwei Merkmale und eine dritte Aufteilung\n\n#### Frage und Datenlage\n\nBlutdruck gegen Alter — und ändert sich das Bild, wenn man nach Standort\ntrennt?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(daten, aes(alter, blutdruck)) +\n  geom_point(alpha = 0.5, size = 1.3) +\n  geom_smooth(method = \"lm\", formula = y ~ x, se = FALSE, colour = \"black\") +\n  facet_wrap(~ standort) +\n  labs(x = \"Alter\", y = \"Blutdruck\")\n\n# Steigung und Niveau je Standort\nfor (ort in c(\"Bern\", \"Chur\", \"Sion\")) {\n  teil <- subset(daten, standort == ort & !is.na(blutdruck))\n  modell <- lm(blutdruck ~ alter, data = teil)\n  cat(sprintf(\"%-5s n = %3d | Steigung %.3f | Achsenabschnitt %.1f | Mittel %.1f\\n\",\n              ort, nrow(teil), coef(modell)[2], coef(modell)[1],\n              mean(teil$blutdruck)))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBern  n = 190 | Steigung 0.406 | Achsenabschnitt 111.8 | Mittel 130.3\nChur  n = 123 | Steigung 0.426 | Achsenabschnitt 118.1 | Mittel 137.6\nSion  n =  69 | Steigung 0.447 | Achsenabschnitt 105.5 | Mittel 125.9\n```\n\n\n:::\n\n```{.r .cell-code}\n# Und die Korrelationen insgesamt\nvollstaendig <- na.omit(daten[, c(\"alter\", \"gewicht\", \"blutdruck\")])\nround(cor(vollstaendig), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           alter gewicht blutdruck\nalter      1.000  -0.034     0.581\ngewicht   -0.034   1.000     0.230\nblutdruck  0.581   0.230     1.000\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 4: Blutdruck gegen Alter, getrennt nach Standort.](explorative-datenanalyse_files/figure-html/fig-b4-eda-r-3.png){#fig-b4-eda-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\norte = [\"Bern\", \"Chur\", \"Sion\"]\nfig, achsen = plt.subplots(1, len(orte), figsize=(7, 3.2), sharey=True)\nfor achse, ort in zip(achsen, orte):\n    teil = daten[daten[\"standort\"] == ort].dropna(subset=[\"blutdruck\"])\n    achse.scatter(teil[\"alter\"], teil[\"blutdruck\"], alpha=0.5, s=12,\n                  color=\"0.3\")\n    k = np.polyfit(teil[\"alter\"], teil[\"blutdruck\"], 1)\n    gitter = np.linspace(teil[\"alter\"].min(), teil[\"alter\"].max(), 2)\n    achse.plot(gitter, np.polyval(k, gitter), color=\"black\")\n    achse.set_title(ort)\n    achse.set_xlabel(\"Alter\")\n    print(f\"{ort:5s} n = {len(teil):3d} | Steigung {k[0]:.3f}\"\n          f\" | Achsenabschnitt {k[1]:.1f} | Mittel {teil['blutdruck'].mean():.1f}\")\nachsen[0].set_ylabel(\"Blutdruck\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselbe Aufteilung mit matplotlib.](explorative-datenanalyse_files/figure-html/fig-b4-eda-py-1.png){#fig-b4-eda-py width=100%}\n:::\n\n```{.python .cell-code}\nvollstaendig = daten[[\"alter\", \"gewicht\", \"blutdruck\"]].dropna()\nprint(vollstaendig.corr().round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           alter  gewicht  blutdruck\nalter      1.000   -0.034      0.581\ngewicht   -0.034    1.000      0.230\nblutdruck  0.581    0.230      1.000\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Standort | n | Steigung je Jahr | Achsenabschnitt | mittlerer Blutdruck |\n|---|---|---|---|---|\n| Bern | 190 | **0.406** | 111.8 | 130.3 |\n| Chur | 123 | **0.426** | 118.1 | **137.6** |\n| Sion | 69 | **0.447** | 105.5 | **125.9** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die **Steigungen** sind praktisch gleich | 0.41 bis 0.45 mmHg je Lebensjahr. Der Zusammenhang zwischen Alter und Blutdruck ist an allen drei Standorten derselbe. |\n| Die **Niveaus** unterscheiden sich | Chur liegt rund 12 mmHg über Sion. Die drei Geraden verlaufen parallel, nur versetzt. |\n| Das ist der Unterschied zwischen **Versatz und Wechselwirkung** | Verschiedene Achsenabschnitte bei gleicher Steigung heissen: Der Standort verschiebt das Niveau, ändert aber nicht den Alterseffekt. Verschiedene Steigungen wären eine Wechselwirkung — dann müsste man je Standort getrennt berichten. |\n| Die Korrelationen | Alter mit Blutdruck **0.581**, Gewicht mit Blutdruck **0.230** | Beide Merkmale tragen bei, das Alter deutlich stärker. Alter und Gewicht korrelieren mit -0.034 praktisch nicht — sie tragen also unabhängig voneinander bei. |\n\n::: {.note-box}\n**Warum die Aufteilung nach einer dritten Variablen zum Pflichtprogramm gehört:**\nOhne sie hätte man einen Gesamtzusammenhang zwischen Alter und Blutdruck\ngesehen und die Standortunterschiede in der Streuung versteckt. Im Extremfall\nkann eine Aufteilung den Zusammenhang sogar **umkehren** — das ist Simpsons\nParadoxon, siehe [multiple Regression](../regression/multiple-lineare-regression.qmd).\n\nDie Faustregel: Nach jeder Variablen aufteilen, die inhaltlich als Erklärung in\nFrage kommt, und zwar **bevor** man einen Gesamtbefund formuliert. Bei drei bis\nfünf Kandidaten ist das schnell erledigt; bei zwanzig braucht es eine Auswahl aus\ndem Fachwissen.\n\n**Und die Gegenwarnung:** Wer lange genug aufteilt, findet immer eine Gruppe, in\nder etwas auffällig aussieht. Deshalb ist jeder so gefundene Befund vorläufig,\nbis er an neuen Daten geprüft ist.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Der Blutdruck steigt an allen drei Standorten mit etwa 0.4 mmHg je Lebensjahr\n> (0.41 bis 0.45). Die Standorte unterscheiden sich im Niveau: Chur liegt im\n> Mittel bei 137.6 mmHg, Bern bei 130.3 und Sion bei 125.9. Der Befund ist\n> explorativ und für eine Prüfung an neuen Daten vorzumerken.\n\n### Beispiel 5: Zwei kategoriale Merkmale\n\n#### Frage und Datenlage\n\nSind die Altersgruppen über die Standorte gleich verteilt? Wenn nicht, wäre der\nStandortunterschied aus Beispiel 4 teilweise ein Alterseffekt.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaten$altersgruppe <- cut(daten$alter, breaks = c(17, 35, 55, 75),\n                          labels = c(\"18-35\", \"36-55\", \"56-74\"))\n\ntab <- table(daten$standort, daten$altersgruppe)\naddmargins(tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      \n       18-35 36-55 56-74 Sum\n  Bern    67    69    64 200\n  Chur    43    43    43 129\n  Sion    25    21    25  71\n  Sum    135   133   132 400\n```\n\n\n:::\n\n```{.r .cell-code}\nround(prop.table(tab, margin = 1), 2)      # Anteile je Standort\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      \n       18-35 36-55 56-74\n  Bern  0.34  0.34  0.32\n  Chur  0.33  0.33  0.33\n  Sion  0.35  0.30  0.35\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mar = c(4, 4, 2, 6))\nbarplot(t(prop.table(tab, margin = 1)), col = grey.colors(3),\n        legend.text = TRUE, xlab = \"Standort\", ylab = \"Anteil\",\n        args.legend = list(x = \"right\", inset = -0.22, bty = \"n\"))\npar(mar = c(5, 4, 4, 2) + 0.1)\n\n# Und die Boxplots des Blutdrucks je Standort\nround(tapply(daten$blutdruck, daten$standort, median, na.rm = TRUE), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBern Chur Sion \n 130  140  122 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 5: Altersgruppen je Standort als gestapelte Anteile.](explorative-datenanalyse_files/figure-html/fig-b5-eda-r-3.png){#fig-b5-eda-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndaten[\"altersgruppe\"] = pd.cut(daten[\"alter\"], bins=[17, 35, 55, 75],\n                               labels=[\"18-35\", \"36-55\", \"56-74\"])\n\ntab = pd.crosstab(daten[\"standort\"], daten[\"altersgruppe\"], margins=True)\nprint(tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\naltersgruppe  18-35  36-55  56-74  All\nstandort                              \nBern             67     69     64  200\nChur             43     43     43  129\nSion             25     21     25   71\nAll             135    133    132  400\n```\n\n\n:::\n\n```{.python .cell-code}\nroh_tab = pd.crosstab(daten[\"standort\"], daten[\"altersgruppe\"])\nanteile = roh_tab.div(roh_tab.sum(axis=1), axis=0)\nprint(anteile.round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\naltersgruppe  18-35  36-55  56-74\nstandort                         \nBern           0.34   0.34   0.32\nChur           0.33   0.33   0.33\nSion           0.35   0.30   0.35\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achse = plt.subplots(figsize=(7, 3))\nunten = np.zeros(len(anteile))\nfor spalte, farbe in zip(anteile.columns, [\"0.3\", \"0.55\", \"0.8\"]):\n    achse.bar(anteile.index, anteile[spalte], bottom=unten, color=farbe,\n              label=spalte)\n    unten += anteile[spalte].values\nachse.set_xlabel(\"Standort\")\nachse.set_ylabel(\"Anteil\")\nachse.legend(frameon=False, bbox_to_anchor=(1.02, 1), loc=\"upper left\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselbe Darstellung in Python.](explorative-datenanalyse_files/figure-html/fig-b5-eda-py-1.png){#fig-b5-eda-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(daten.groupby(\"standort\")[\"blutdruck\"].median().round(1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstandort\nBern    130.0\nChur    140.0\nSion    122.0\nName: blutdruck, dtype: float64\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nAbsolut:\n\n| Standort | 18–35 | 36–55 | 56–74 | Summe |\n|---|---|---|---|---|\n| Bern | 67 | 69 | 64 | 200 |\n| Chur | 43 | 43 | 43 | 129 |\n| Sion | 25 | 21 | 25 | 71 |\n\nAls Zeilenanteile:\n\n| Standort | 18–35 | 36–55 | 56–74 |\n|---|---|---|---|\n| Bern | 0.34 | 0.34 | 0.32 |\n| Chur | 0.33 | 0.33 | 0.33 |\n| Sion | 0.35 | 0.30 | 0.35 |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die **absoluten** Zahlen sind nicht vergleichbar | Bern hat in jeder Altersgruppe die meisten Fälle — weil Bern insgesamt die meisten hat. |\n| Die **Anteile** sind es | Und sie liegen alle bei rund einem Drittel. Die Altersverteilung ist über die Standorte praktisch identisch. |\n| Was daraus für Beispiel 4 folgt | Der Standortunterschied im Blutdruck ist **kein** verkappter Alterseffekt. Wären in Chur überwiegend ältere Personen erfasst, hätte man den Unterschied damit erklären können. |\n| Die Mediane des Blutdrucks je Standort | **130, 140 und 122** bestätigen das Bild aus Beispiel 4 auch robust, also ohne Einfluss einzelner Extremwerte. |\n\n::: {.note-box}\n**Die Reihenfolge, in der diese beiden Beispiele stehen, ist kein Zufall.** Erst\nfällt ein Unterschied auf (Beispiel 4), dann wird nach der naheliegendsten\nAlternativerklärung gesucht (Beispiel 5). So sieht die Schleife aus, aus der EDA\nbesteht:\n\n> Frage → Grafik oder Kennzahl → Befund → **nächste Frage aus dem Befund**\n\nUnd sie hört nicht auf, weil die Daten erschöpft wären, sondern weil einem keine\nAlternativerklärung mehr einfällt, die man prüfen könnte. Genau deshalb ist das\nErgebnis eine **Hypothese** und kein Nachweis.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Altersgruppen sind über die drei Standorte gleichmässig verteilt (je rund\n> ein Drittel je Gruppe, n = 200, 129 und 71). Der beobachtete\n> Blutdruckunterschied zwischen den Standorten lässt sich damit nicht durch eine\n> unterschiedliche Altersstruktur erklären.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEin Merkmal hat null fehlende Werte, aber ein Minimum von -1 bei einer Grösse,\ndie nicht negativ sein kann. Was liegt vor?\n\n- [x] Ein Platzhalter für \"unbekannt\", der als Zahl gespeichert wurde ~ Richtig.\n      Er wird von jeder Kennzahl mitgerechnet, ohne eine Warnung auszulösen. Der\n      Blick auf Minimum und Maximum jedes Merkmals findet solche Fälle.\n- [ ] Ein Messfehler ~ Möglich, aber -1 bei genau drei Fällen sieht nach\n      Codierung aus, nicht nach Messung.\n- [ ] Nichts Besonderes, drei von 400 fallen nicht ins Gewicht ~ Für den\n      Mittelwert stimmt das ungefähr; die Standardabweichung wächst um 18 Prozent.\n:::\n\n::: {.quiz}\nWarum fällt ein Platzhalter beim Mittelwert kaum auf, bei der\nStandardabweichung aber deutlich?\n\n- [x] Weil die Standardabweichung die Abweichungen quadriert ~ Richtig. Ein Wert\n      80 Einheiten daneben trägt zum Mittelwert 80/n bei, zur Varianz aber\n      $80^2/n$. Deshalb ist die Streuung die empfindlichere Anzeige.\n- [ ] Weil der Mittelwert robuster ist als die Standardabweichung ~ Robust ist\n      keines von beiden; sie sind nur verschieden empfindlich.\n- [ ] Weil der Platzhalter negativ ist ~ Das Vorzeichen spielt keine Rolle, nur\n      der Abstand zum Rest.\n:::\n\n::: {.quiz}\nDie Endziffern eines Messwerts verteilen sich zu 46 Prozent auf 0 und 5. Was\nfolgt daraus?\n\n- [x] Ein Teil der Werte wurde gerundet erfasst ~ Richtig. Erwartet wären 20\n      Prozent. Solche Muster verraten etwas über die Erhebung, nicht über den\n      untersuchten Gegenstand — und die tatsächliche Genauigkeit ist geringer,\n      als die Zahlen suggerieren.\n- [ ] Die Daten sind gefälscht ~ Das ist eine viel stärkere Behauptung. Rundung\n      beim Ablesen ist die harmlose und häufigste Erklärung.\n- [ ] Die Stichprobe ist zu klein ~ Bei 382 Werten wäre die Abweichung von 20 auf\n      46 Prozent durch Zufall ausgeschlossen.\n:::\n\n::: {.quiz}\nDrei Streudiagramme zeigen für drei Standorte praktisch dieselbe Steigung, aber\nverschiedene Achsenabschnitte. Wie ist das zu deuten?\n\n- [x] Der Standort verschiebt das Niveau, ändert aber den Alterseffekt nicht ~\n      Richtig. Parallele Geraden heissen Versatz ohne Wechselwirkung. Verschiedene\n      Steigungen wären eine Wechselwirkung, und dann müsste man je Standort\n      getrennt berichten.\n- [ ] Der Standort hat keinen Einfluss ~ Er hat einen, nämlich auf das Niveau.\n- [ ] Die Standorte sind nicht vergleichbar ~ Gerade weil die Steigungen\n      übereinstimmen, sind sie es.\n:::\n\n::: {.quiz}\nEine explorative Analyse findet in einer von zwölf Untergruppen einen deutlichen\nUnterschied. Was ist damit gezeigt?\n\n- [x] Eine Hypothese, die an neuen Daten zu prüfen ist ~ Richtig. Wer lange genug\n      aufteilt, findet immer eine auffällige Gruppe. Ein Test auf denselben Daten\n      prüft nichts, weil die Fragestellung aus ihnen stammt.\n- [ ] Ein Effekt in dieser Untergruppe ~ Möglich, aber nicht belegt.\n- [ ] Nichts, Untergruppenanalysen sind wertlos ~ Sie sind das Werkzeug, um\n      Hypothesen zu finden. Nur nachweisen können sie nichts.\n:::\n\n## Verlinkte Ressourcen\n\n- [R for Data Science, Kapitel zur explorativen Datenanalyse](https://r4ds.hadley.nz/eda)\n- [Datenqualität: Platzhalter, Lücken und Ausreisser](../../daten/datenqualitaet.qmd)\n",
    "supporting": [
      "explorative-datenanalyse_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}