{
  "hash": "0708b230c78ebc786f86030353e87351",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"t-Test für zwei Stichproben\"\ndescription: \"Zwei unabhängige Gruppen vergleichen, Welch als Standardfall.\"\ncategories: [\"Hypothesentests\", \"Effektstärke\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"ESDS\", \"STATDA\"]\nseitentyp: methode\nstand: entwurf\norder: 20\n---\n\n\n\n\n\nAlle Beispiele auf dieser Seite rechnen mit fest eingetragenen Zahlen. R und\nPython sehen also dieselben Daten und müssen dieselben Werte ausgeben; wo sie es\nnicht tun, liegt es an der Konvention der Funktion und nicht an der Stichprobe.\n\n\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Unterscheiden sich die Mittelwerte zweier unabhängiger Gruppen? |\n| Zielvariable | metrisch |\n| Gruppen | genau zwei, unabhängig voneinander |\n| Was die Methode liefert | Mittelwertdifferenz mit Konfidenzintervall, t-Statistik, Freiheitsgrade, p-Wert, Effektstärke |\n| R-Funktion | `t.test(wert ~ gruppe, data = df)`, Effektstärke mit `effectsize::cohens_d()` |\n| Python-Funktion | `pg.ttest(a, b, correction=True)` |\n| Verwandte Methoden | [gepaarter t-Test](t-test-gepaart.qmd), [Varianzanalyse](anova.qmd), [nichtparametrische Tests](nichtparametrische-tests.qmd) |\n\n## Wann diese Methode, wann nicht\n\nTypische Fragestellungen: Unterscheiden sich zwei Maschinen in der gefertigten\nDicke, zwei Standorte im Durchsatz, zwei Varianten einer Seite in der\nVerweildauer. Gemeinsam ist ihnen eine metrische Zielgrösse und genau zwei\nGruppen, deren Beobachtungen nichts miteinander zu tun haben.\n\nDer Standardfall ist die Welch-Variante, die ungleiche Varianzen zulässt. Sie\nkostet fast nichts an Schärfe, wenn die Varianzen tatsächlich gleich sind, und\nsie rettet das Ergebnis, wenn sie es nicht sind. Deshalb ist sie in R die\nVoreinstellung, und in Python wird sie mit `correction=True` angefordert. Ein\nvorgeschalteter Varianzvergleich zur Entscheidung zwischen den Varianten ist\nnicht nötig und verschlechtert die Fehlerkontrolle.\n\n| Situation | Stattdessen |\n|---|---|\n| Dieselben Objekte zweimal gemessen | [gepaarter t-Test](t-test-gepaart.qmd) |\n| Mehr als zwei Gruppen | [Varianzanalyse](anova.qmd) |\n| Kleine, deutlich schiefe Stichproben | [Mann-Whitney](nichtparametrische-tests.qmd) |\n| Vergleich gegen einen festen Sollwert | [t-Test für eine Stichprobe](t-test-eine-stichprobe.qmd) |\n| Zielvariable kategorial | [Chi-Quadrat-Test](chi-quadrat-tests.qmd) |\n| Weitere Einflussgrössen sollen kontrolliert werden | [multiple lineare Regression](../regression/multiple-lineare-regression.qmd) |\n\n## Grundidee und Modell\n\nVerglichen wird die beobachtete Differenz der beiden Mittelwerte mit der\nStreuung, die man allein durch Zufall erwarten würde. Ist die Differenz gross\ngegenüber dieser Zufallsstreuung, spricht das gegen die Nullhypothese gleicher\nErwartungswerte.\n\n$$t = \\frac{\\bar{x}_1 - \\bar{x}_2}{\\sqrt{\\dfrac{s_1^2}{n_1} + \\dfrac{s_2^2}{n_2}}}$$\n\n| Bestandteil | Bedeutung |\n|---|---|\n| $\\bar{x}_1 - \\bar{x}_2$ | beobachtete Mittelwertdifferenz, die geschätzte Effektgrösse in der Einheit der Messung |\n| $s_1^2, s_2^2$ | Varianzen der beiden Gruppen |\n| $n_1, n_2$ | Gruppengrössen |\n| Nenner | Standardfehler der Differenz |\n| $t$ | Differenz in Einheiten ihres eigenen Standardfehlers |\n\nDie Nullhypothese lautet, dass die beiden Erwartungswerte gleich sind. Unter\nihr folgt $t$ näherungsweise einer t-Verteilung. Bei der Welch-Variante werden\ndie Freiheitsgrade aus den beiden Varianzen und Gruppengrössen berechnet und\nsind deshalb meist keine ganze Zahl.\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung | Vorgehen |\n|---|---|---|---|---|\n| Unabhängigkeit | Beobachtungen innerhalb und zwischen den Gruppen beeinflussen sich nicht | Erhebungsdesign | p-Werte zu optimistisch, das Verfahren ist nicht zu retten | passendes Modell für die Struktur, etwa gepaart oder Mehrebenen |\n| Metrische Zielvariable | Differenzen und Mittelwerte sind sinnvoll | [Skalenniveau](../grundlagen/skalenniveaus.qmd) | Der Mittelwert ist nicht definiert | rangbasiertes Verfahren |\n| Annähernd normalverteilte Werte | Genauer: annähernd normalverteilte Mittelwerte | [QQ-Plot](../wahrscheinlichkeit/qq-plots.qmd) je Gruppe, Schiefe, n | Bei kleinem n weicht die Fehlerrate vom Niveau ab | Mann-Whitney oder Bootstrap |\n| Keine extremen Ausreisser | Einzelne Werte bestimmen Mittelwert und Varianz nicht | Boxplot, Streudiagramm | Ergebnis hängt an wenigen Punkten | Ursache prüfen, robustes Verfahren, mit und ohne berichten |\n| Gleiche Varianzen | Nur für die Student-Variante nötig | Boxplot, Varianzen vergleichen | Bei ungleichen Varianzen und ungleichen Gruppengrössen wird das Niveau verfehlt | Welch-Variante, also der Standardfall hier |\n\nGeprüft wird vor dem Test und mit den Augen, nicht mit einem zweiten Test. Ein\n[Normalitätstest](normalitaetstests.qmd) beantwortet die falsche Frage: bei\nkleinem n findet er auch grobe Abweichungen nicht, bei grossem n stört ihn jede\nbelanglose Abweichung, obwohl gerade dort der zentrale Grenzwertsatz greift.\n\n## Output lesen\n\nR, `t.test()`:\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| `Welch Two Sample t-test` | die verwendete Variante | steht dort `Two Sample t-test`, wurde `var.equal = TRUE` gesetzt |\n| `t` | Differenz in Einheiten ihres Standardfehlers | Betrag über etwa 2 heisst bei üblichem n signifikant |\n| `df` | Freiheitsgrade | bei Welch meist keine ganze Zahl, das ist korrekt |\n| `p-value` | Wahrscheinlichkeit dieser oder extremerer Daten bei gleichen Erwartungswerten | keine Aussage über die Grösse des Unterschieds |\n| `95 percent confidence interval` | Intervall der Mittelwertdifferenz | die eigentlich interessante Zeile, in der Einheit der Messung |\n| `mean in group A`, `mean in group B` | Gruppenmittelwerte | die Differenz daraus ist der Punktschätzer |\n| `alternative hypothesis` | ein- oder zweiseitig | prüfen, dass nicht nachträglich einseitig getestet wurde |\n| `cohens_d` | standardisierte Effektstärke | Anhaltspunkte: 0.2 klein, 0.5 mittel, 0.8 gross |\n\nPython, `pg.ttest()` liefert eine Tabelle mit einer Zeile:\n\n| Spalte | Was sie sagt | Unterschied zu R |\n|---|---|---|\n| `T` | t-Statistik | wie `t` |\n| `dof` | Freiheitsgrade | wie `df` |\n| `alternative` | Richtung der Alternativhypothese | wie in R |\n| `p_val` | p-Wert | wie `p-value` |\n| `CI95` | Konfidenzintervall der Differenz | in R eine eigene Zeile, hier ein Array in einer Zelle |\n| `cohen_d` | Effektstärke | ohne Vorzeichen, R gibt sie vorzeichenbehaftet aus |\n| `power` | erreichte Power für den beobachteten Effekt | in R nicht enthalten, und im Nachhinein nur eingeschränkt aussagekräftig |\n| `BF10` | Bayes-Faktor | in R nicht enthalten; Werte über 3 gelten als Hinweis auf einen Unterschied |\n\n::: {.note-box}\nDie Schreibweise der Spalten hat sich mit pingouin 0.6 geändert: aus `p-val`,\n`CI95%` und `cohen-d` wurden `p_val`, `CI95` und `cohen_d`. Code, der die alten\nNamen fest verdrahtet, bricht still oder mit `KeyError`. Auf dieser Seite fängt\ndie Hilfsfunktion `pg_wert()` beide Schreibweisen ab.\n:::\n\nDie Vorzeichen von t und Intervall hängen an der Reihenfolge der Gruppen. In R\nbestimmt die Faktorstufe die Reihenfolge, in Python die Reihenfolge der\nArgumente. Wer die Richtung berichtet, prüft sie am Vorzeichen und an den\nGruppenmittelwerten.\n\n## Interpretationsfallen\n\n- **Signifikanz ist keine Relevanz.** Bei grossem n wird jeder noch so kleine\n  Unterschied signifikant. Die Entscheidung fällt an der Differenz in ihrer\n  Einheit und an der Effektstärke.\n- **Nicht signifikant ist kein Beweis für Gleichheit.** Wer Gleichheit zeigen\n  will, braucht ein Äquivalenztestverfahren mit vorab festgelegter\n  Toleranzgrenze.\n- **Der p-Wert ist keine Wahrscheinlichkeit für die Hypothese**, siehe\n  [Hypothesentests: Grundlagen](../inferenz/hypothesentests-grundlagen.qmd).\n- **Überlappende Fehlerbalken der Gruppen sagen wenig.** Beurteilt wird das\n  Intervall der Differenz, nicht das Überlappen zweier Einzelintervalle.\n- **Die Richtung darf nicht nachträglich gewählt werden.** Einseitig testen ist\n  zulässig, aber nur mit vor der Datenerhebung festgelegter Richtung.\n- **Gepaarte Daten ungepaart auszuwerten verschenkt Information** und findet\n  echte Effekte oft nicht, siehe [gepaarter t-Test](t-test-gepaart.qmd).\n- **Mehrere Gruppen paarweise durchzutesten** erhöht die Rate falscher Alarme,\n  siehe [Varianzanalyse](anova.qmd) und\n  [multiples Testen](../inferenz/multiples-testen.qmd).\n\n## Ergebnis berichten\n\nVorlage für den Ergebnissatz:\n\n> [Zielgrösse] unterscheidet sich zwischen [Gruppe 1] (M = [Mittelwert],\n> SD = [Streuung], n = [n1]) und [Gruppe 2] (M = [Mittelwert], SD = [Streuung],\n> n = [n2]): Differenz [Schätzwert] [Einheit], 95-Prozent-Konfidenzintervall\n> [unten] bis [oben], t([df]) = [t], p = [p], Cohens d = [d].\n\nImmer genannt werden: beide Gruppenmittelwerte mit Streuung und Umfang, die\nDifferenz mit Konfidenzintervall, Teststatistik mit Freiheitsgraden, p-Wert und\nEffektstärke, dazu die verwendete Variante (Welch oder Student) und die\ngeprüften Voraussetzungen.\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt des t-Tests für zwei Stichproben |\n|---|---|\n| [t-Test für eine Stichprobe](t-test-eine-stichprobe.qmd) | Vergleich gegen einen festen Sollwert statt gegen eine zweite Gruppe |\n| [Gepaarter t-Test](t-test-gepaart.qmd) | dieselben Objekte zweimal gemessen |\n| [Varianzanalyse](anova.qmd) | mehr als zwei Gruppen |\n| [Nichtparametrische Tests](nichtparametrische-tests.qmd) | kleine, schiefe Stichproben oder ordinale Zielgrösse |\n| [Einfache lineare Regression](../regression/einfache-lineare-regression.qmd) | derselbe Vergleich als Modell, mit metrischem statt zweistufigem Prädiktor |\n| [Multiple lineare Regression](../regression/multiple-lineare-regression.qmd) | weitere Einflussgrössen sollen konstant gehalten werden |\n\n## Beispiele\n\nJedes Beispiel steht in einem eigenen Reiter.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Zwei Maschinen\n\n#### Frage und Datenlage\n\nEine Fertigung hat zwei Maschinen, die dasselbe Blechteil schneiden. Von jeder\nwerden fünfzehn Teile vermessen, erfasst wird die Dicke in Millimetern. Die\nFrage lautet: Fertigen die beiden Maschinen im Mittel gleich dick, und falls\nnicht, wie gross ist der Unterschied?\n\nDie Zielgrösse ist metrisch, es gibt genau zwei Gruppen, und die Teile stammen\naus getrennten Läufen. Damit ist der t-Test für zwei unabhängige Stichproben das\npassende Verfahren.\n\n#### Voraussetzungen prüfen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmaschine_a <- c(11.86, 12.24, 12.02, 11.95, 12.31, 12.10, 11.78, 12.18,\n                12.05, 11.90, 12.27, 11.99, 12.14, 11.83, 12.08)\nmaschine_b <- c(12.34, 11.97, 12.51, 12.20, 11.88, 12.42, 12.09, 12.67,\n                12.26, 11.94, 12.45, 12.13, 12.30, 12.01, 12.58)\n\ndicke <- data.frame(\n  wert = c(maschine_a, maschine_b),\n  maschine = rep(c(\"A\", \"B\"), c(length(maschine_a), length(maschine_b)))\n)\n\npar(mfrow = c(1, 3), mar = c(4, 4, 3, 1))\nboxplot(wert ~ maschine, data = dicke, main = \"Verteilung je Maschine\",\n        xlab = \"Maschine\", ylab = \"Dicke (mm)\")\nqqnorm(maschine_a, main = \"QQ-Plot A\"); qqline(maschine_a)\nqqnorm(maschine_b, main = \"QQ-Plot B\"); qqline(maschine_b)\npar(mfrow = c(1, 1))\n\nround(c(mittel_a = mean(maschine_a), mittel_b = mean(maschine_b),\n        sd_a = sd(maschine_a), sd_b = sd(maschine_b)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmittel_a mittel_b     sd_a     sd_b \n 12.0467  12.2500   0.1636   0.2455 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 1: Verteilung je Maschine und QQ-Plot je Gruppe.](t-test-zwei-stichproben_files/figure-html/fig-b1-voraussetzungen-r-1.png){#fig-b1-voraussetzungen-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport statsmodels.api as sm\n\nmaschine_a = np.array([11.86, 12.24, 12.02, 11.95, 12.31, 12.10, 11.78, 12.18,\n                       12.05, 11.90, 12.27, 11.99, 12.14, 11.83, 12.08])\nmaschine_b = np.array([12.34, 11.97, 12.51, 12.20, 11.88, 12.42, 12.09, 12.67,\n                       12.26, 11.94, 12.45, 12.13, 12.30, 12.01, 12.58])\n\nfig, axes = plt.subplots(1, 3, figsize=(7, 3.4))\naxes[0].boxplot([maschine_a, maschine_b])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'whiskers': [<matplotlib.lines.Line2D object at 0x7f861257f1a0>, <matplotlib.lines.Line2D object at 0x7f861257ed20>, <matplotlib.lines.Line2D object at 0x7f8612598380>, <matplotlib.lines.Line2D object at 0x7f8612598620>], 'caps': [<matplotlib.lines.Line2D object at 0x7f861257e630>, <matplotlib.lines.Line2D object at 0x7f861257d820>, <matplotlib.lines.Line2D object at 0x7f8612598890>, <matplotlib.lines.Line2D object at 0x7f8612598b30>], 'boxes': [<matplotlib.lines.Line2D object at 0x7f86127df380>, <matplotlib.lines.Line2D object at 0x7f86125980b0>], 'medians': [<matplotlib.lines.Line2D object at 0x7f861257fb90>, <matplotlib.lines.Line2D object at 0x7f8612598dd0>], 'fliers': [<matplotlib.lines.Line2D object at 0x7f861257fe30>, <matplotlib.lines.Line2D object at 0x7f8612599070>], 'means': []}\n```\n\n\n:::\n\n```{.python .cell-code}\naxes[0].set_xticks([1, 2], [\"A\", \"B\"])\naxes[0].set_title(\"Verteilung je Maschine\")\naxes[0].set_ylabel(\"Dicke (mm)\")\nsm.qqplot(maschine_a, line=\"s\", ax=axes[1])\naxes[1].set_title(\"QQ-Plot A\")\nsm.qqplot(maschine_b, line=\"s\", ax=axes[2])\naxes[2].set_title(\"QQ-Plot B\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Prüfung in Python.](t-test-zwei-stichproben_files/figure-html/fig-b1-voraussetzungen-py-1.png){#fig-b1-voraussetzungen-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(\"Mittelwerte:\", round(maschine_a.mean(), 4), round(maschine_b.mean(), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMittelwerte: 12.0467 12.25\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Streuungen: \", round(maschine_a.std(ddof=1), 4),\n      round(maschine_b.std(ddof=1), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStreuungen:  0.1636 0.2455\n```\n\n\n:::\n:::\n\n\n:::\n\nDie Mittelwerte liegen bei 12.047 mm und 12.250 mm, die Standardabweichungen bei\n0.164 mm und 0.246 mm. Maschine B streut also rund anderthalb Mal so stark, die\nVarianzen verhalten sich wie 1 zu 2.25. Genau dafür ist die Welch-Variante da:\nDer Unterschied in der Streuung wird nicht weggemittelt, sondern in den\nFreiheitsgraden berücksichtigt.\n\nDie Boxplots zeigen zwei symmetrische Verteilungen ohne einzelne weit entfernte\nPunkte, und in beiden QQ-Plots liegen die Punkte nah an der Geraden. Die\nVoraussetzungen sind erfüllt.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(wert ~ maschine, data = dicke)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  wert by maschine\nt = -2.6691, df = 24.385, p-value = 0.01332\nalternative hypothesis: true difference in means between group A and group B is not equal to 0\n95 percent confidence interval:\n -0.36043130 -0.04623536\nsample estimates:\nmean in group A mean in group B \n       12.04667        12.25000 \n```\n\n\n:::\n\n```{.r .cell-code}\neffectsize::cohens_d(wert ~ maschine, data = dicke)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |         95% CI\n--------------------------\n-0.97     | [-1.73, -0.21]\n\n- Estimated using pooled SD.\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nb1 = pg.ttest(maschine_a, maschine_b, correction=True)\nprint(b1.round(4).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     T_test\nT                   -2.6691\ndof                 24.3847\nalternative       two-sided\np_val                0.0133\nCI95         [-0.36, -0.05]\ncohen_d              0.9746\npower                0.7313\nBF10                  4.302\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| Variante | `Welch Two Sample t-test` | ungleiche Varianzen zugelassen | Stünde dort `Two Sample t-test`, wäre versehentlich `var.equal = TRUE` gesetzt. |\n| `t` | -2.669 | Die Differenz ist 2.67 Standardfehler von null entfernt. | Das Vorzeichen ist negativ, weil A minus B gerechnet wird und A dünner fertigt. Es sagt nichts über die Stärke aus. |\n| `df` | 24.385 | Freiheitsgrade nach Welch | Keine ganze Zahl, und das ist richtig so. Bei 15 und 15 Werten läge die Student-Variante bei glatten 28; Welch zieht wegen der ungleichen Varianzen etwas ab. |\n| `p-value` | 0.0133 | Wahrscheinlichkeit, eine mindestens so grosse Differenz zu sehen, wenn beide Maschinen im Mittel gleich dick fertigen | Unter 0.05, also spricht das Ergebnis gegen die Nullhypothese. Es ist **nicht** die Wahrscheinlichkeit, dass die Maschinen gleich sind. |\n| `95 percent confidence interval` | -0.360 bis -0.046 | Bereich plausibler Werte für die Mittelwertdifferenz in Millimetern | Die interessanteste Zeile. Das Intervall enthält die Null nicht, und es sagt zugleich, dass der Unterschied irgendwo zwischen 0.05 mm und 0.36 mm liegt. Genauer wissen wir es bei fünfzehn Teilen je Maschine nicht. |\n| `mean in group A` | 12.047 | Mittelwert Maschine A | |\n| `mean in group B` | 12.250 | Mittelwert Maschine B | Differenz 0.203 mm, das ist der Punktschätzer und die Mitte des Intervalls. |\n| `alternative hypothesis` | `not equal to 0` | zweiseitig getestet | Beide Richtungen waren zugelassen, die Richtung wurde nicht nachträglich gewählt. |\n| `Cohen's d` | -0.97 | Differenz in Einheiten der gemeinsamen Streuung | Nach den üblichen Anhaltspunkten (0.2 klein, 0.5 mittel, 0.8 gross) ein grosser Effekt. Ein knapper p-Wert und ein grosser Effekt schliessen sich nicht aus: Der p-Wert hängt zusätzlich am Stichprobenumfang, die Effektstärke nicht. |\n| `power` (nur Python) | 0.731 | Wahrscheinlichkeit, einen Effekt dieser Grösse bei diesem Umfang zu finden | Im Nachhinein berechnet und deshalb nur ein grober Hinweis. Geplant wird die Power vorab, siehe [Power und Stichprobenumfang](../inferenz/power-stichprobenumfang.qmd). |\n| `BF10` (nur Python) | 4.30 | Bayes-Faktor zugunsten eines Unterschieds | Die Daten sind rund viermal wahrscheinlicher unter der Annahme eines Unterschieds als unter der Annahme der Gleichheit. Ein moderater Hinweis, kein Beweis. |\n\nDer Vorzeichenvergleich zwischen den Sprachen: R gibt `t = -2.669` und\n`d = -0.97` aus, Python `T = -2.669`, aber `cohen_d = 0.97` ohne Vorzeichen.\npingouin berichtet den Betrag der Effektstärke. Die Richtung liest man an den\nMittelwerten ab, nie am Vorzeichen von d allein.\n\n#### Interpretation und Ergebnissatz\n\nPraktisch bedeutsam ist nicht der p-Wert, sondern das Intervall. Läge die\nToleranz der Fertigung bei 0.10 mm, dann wäre die Frage nicht beantwortet,\nsondern verschärft: Das Intervall reicht von 0.046 mm bis 0.360 mm und lässt\nWerte weit über der Toleranz zu. Läge die Toleranz bei 0.50 mm, wäre der\nUnterschied statistisch nachgewiesen und praktisch belanglos. Dieselbe Zahl,\nzwei gegenteilige Konsequenzen: Deshalb wird die Relevanzschwelle vor der\nAuswertung festgelegt.\n\n> Die gefertigte Dicke unterscheidet sich zwischen Maschine A (M = 12.047 mm,\n> SD = 0.164, n = 15) und Maschine B (M = 12.250 mm, SD = 0.246, n = 15):\n> Maschine A fertigt im Mittel 0.203 mm dünner, 95-Prozent-Konfidenzintervall\n> 0.046 bis 0.360 mm, t(24.4) = -2.67, p = 0.013, Cohens d = -0.97\n> (Welch-Test, zweiseitig).\n\n### Beispiel 2: Zu wenig Daten\n\n#### Frage und Datenlage\n\nDieselbe Fragestellung, aber nur zehn Teile je Maschine, und die Mittelwerte\nliegen diesmal nur sechs Hundertstel Millimeter auseinander. Das Beispiel zeigt,\nwas ein nicht signifikantes Ergebnis aussagt und vor allem, was es nicht\naussagt.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nklein_a <- c(12.05, 11.92, 12.18, 11.87, 12.10, 12.25, 11.95, 12.02, 12.15, 11.90)\nklein_b <- c(12.20, 11.85, 12.35, 12.00, 11.95, 12.40, 12.10, 11.80, 12.30, 12.05)\n\nt.test(klein_a, klein_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  klein_a and klein_b\nt = -0.78686, df = 15.057, p-value = 0.4436\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -0.2261825  0.1041825\nsample estimates:\nmean of x mean of y \n   12.039    12.100 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nklein_a = np.array([12.05, 11.92, 12.18, 11.87, 12.10,\n                    12.25, 11.95, 12.02, 12.15, 11.90])\nklein_b = np.array([12.20, 11.85, 12.35, 12.00, 11.95,\n                    12.40, 12.10, 11.80, 12.30, 12.05])\n\nprint(pg.ttest(klein_a, klein_b, correction=True).round(4).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   T_test\nT                 -0.7869\ndof               15.0574\nalternative     two-sided\np_val              0.4436\nCI95         [-0.23, 0.1]\ncohen_d            0.3519\npower              0.1157\nBF10                0.494\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Mittelwerte | 12.039 und 12.100 | Die Differenz beträgt 0.061 mm. |\n| `t` | -0.787 | Die Differenz ist weniger als einen Standardfehler von null entfernt. Solche Abweichungen entstehen laufend rein zufällig. |\n| `df` | 15.057 | Welch zieht hier von 18 möglichen Freiheitsgraden knapp drei ab, weil B rund anderthalb Mal so stark streut. |\n| `p-value` | 0.444 | Weit über jedem üblichen Niveau. Die Daten sind mit gleichen Erwartungswerten gut vereinbar. |\n| `95 percent confidence interval` | -0.226 bis 0.104 | Die entscheidende Zeile. Das Intervall enthält die Null, reicht aber auf beiden Seiten weit über eine Toleranz von 0.10 mm hinaus. |\n| `cohen_d` | 0.35 | Ein kleiner bis mittlerer Effekt wäre mit diesen Daten durchaus vereinbar. |\n| `power` (nur Python) | rund 0.12 | Bei diesem Umfang und diesem Effekt hätte der Test einen echten Unterschied nur in etwa einem von acht Fällen gefunden. |\n\n#### Interpretation und Ergebnissatz\n\nDer häufigste Fehler an dieser Stelle ist der Satz \"es gibt keinen Unterschied\".\nDie Daten sagen etwas anderes: Sie reichen nicht aus, um einen Unterschied\nnachzuweisen. Das Konfidenzintervall macht das sichtbar. Es lässt Abweichungen\nbis 0.23 mm in die eine und 0.10 mm in die andere Richtung zu, also genau den\nBereich, der für die Fertigung interessant wäre.\n\nWer wirklich zeigen will, dass zwei Maschinen gleichwertig sind, braucht ein\nÄquivalenzverfahren mit vorab festgelegter Toleranz. Ein nicht signifikanter\nt-Test ist dafür kein Ersatz.\n\n::: {.note-box}\nDie im Nachhinein berechnete Power beantwortet die Frage \"wie wahrscheinlich\nwäre ein Fund gewesen\" nur scheinbar, denn sie wird aus genau dem Effekt\nberechnet, den man gerade beobachtet hat. Nützlich ist sie vor der Erhebung, um\nden nötigen Umfang zu bestimmen.\n:::\n\n> Ein Unterschied in der gefertigten Dicke lässt sich nicht nachweisen\n> (Welch-Test, t(15.1) = -0.79, p = 0.44, n = 10 je Maschine). Das\n> 95-Prozent-Konfidenzintervall der Differenz reicht von -0.226 bis 0.104 mm und\n> lässt Unterschiede in beide Richtungen zu; die Datenlage erlaubt keine Aussage\n> über Gleichwertigkeit.\n\n### Beispiel 3: Schiefe und Ausreisser\n\n#### Frage und Datenlage\n\nEin Support vergleicht die Wartezeit bis zur ersten Antwort zwischen zwei\nKanälen, je zwölf Anfragen, gemessen in Minuten. Wartezeiten sind fast immer\nrechtsschief: Viele Anfragen werden schnell beantwortet, wenige liegen lange\nliegen. Im Kanal B gibt es zusätzlich einen einzelnen Fall mit 30 Minuten.\n\n#### Voraussetzungen prüfen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkanal_a <- c(0.2, 0.4, 0.5, 0.7, 0.85, 1.1, 1.4, 1.8, 2.3, 3.1, 4.2, 5.0)\nkanal_b <- c(0.6, 0.9, 1.3, 1.7, 2.2, 2.8, 3.6, 4.6, 6.0, 8.0, 11.0, 30.0)\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nboxplot(list(A = kanal_a, B = kanal_b), main = \"Verteilungen\",\n        ylab = \"Wartezeit (Minuten)\")\nqqnorm(kanal_b, main = \"QQ-Plot Kanal B\"); qqline(kanal_b)\npar(mfrow = c(1, 1))\n\nround(c(mittel_a = mean(kanal_a), median_a = median(kanal_a),\n        mittel_b = mean(kanal_b), median_b = median(kanal_b),\n        sd_b = sd(kanal_b)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmittel_a median_a mittel_b median_b     sd_b \n   1.796    1.250    6.058    3.200    8.164 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: rechtsschiefe Wartezeiten, Kanal B mit einem einzelnen sehr grossen Wert.](t-test-zwei-stichproben_files/figure-html/fig-b3-voraussetzungen-r-1.png){#fig-b3-voraussetzungen-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nkanal_a = np.array([0.2, 0.4, 0.5, 0.7, 0.85, 1.1, 1.4, 1.8, 2.3, 3.1, 4.2, 5.0])\nkanal_b = np.array([0.6, 0.9, 1.3, 1.7, 2.2, 2.8, 3.6, 4.6, 6.0, 8.0, 11.0, 30.0])\n\nfig, axes = plt.subplots(1, 2, figsize=(7, 3.2))\naxes[0].boxplot([kanal_a, kanal_b])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'whiskers': [<matplotlib.lines.Line2D object at 0x7f861242d7c0>, <matplotlib.lines.Line2D object at 0x7f861242da90>, <matplotlib.lines.Line2D object at 0x7f861242c890>, <matplotlib.lines.Line2D object at 0x7f8616f72960>], 'caps': [<matplotlib.lines.Line2D object at 0x7f861242cc20>, <matplotlib.lines.Line2D object at 0x7f861242ea20>, <matplotlib.lines.Line2D object at 0x7f861242e450>, <matplotlib.lines.Line2D object at 0x7f861242c320>], 'boxes': [<matplotlib.lines.Line2D object at 0x7f861242d4f0>, <matplotlib.lines.Line2D object at 0x7f861242ebd0>], 'medians': [<matplotlib.lines.Line2D object at 0x7f861242f260>, <matplotlib.lines.Line2D object at 0x7f861242c260>], 'fliers': [<matplotlib.lines.Line2D object at 0x7f861242f6e0>, <matplotlib.lines.Line2D object at 0x7f861242e2d0>], 'means': []}\n```\n\n\n:::\n\n```{.python .cell-code}\naxes[0].set_xticks([1, 2], [\"A\", \"B\"])\naxes[0].set_title(\"Verteilungen\")\naxes[0].set_ylabel(\"Wartezeit (Minuten)\")\nsm.qqplot(kanal_b, line=\"s\", ax=axes[1])\naxes[1].set_title(\"QQ-Plot Kanal B\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselbe Prüfung in Python.](t-test-zwei-stichproben_files/figure-html/fig-b3-voraussetzungen-py-1.png){#fig-b3-voraussetzungen-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(\"A: Mittel\", round(kanal_a.mean(), 3), \"Median\", round(np.median(kanal_a), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nA: Mittel 1.796 Median 1.25\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"B: Mittel\", round(kanal_b.mean(), 3), \"Median\", round(np.median(kanal_b), 3),\n      \"SD\", round(kanal_b.std(ddof=1), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nB: Mittel 6.058 Median 3.2 SD 8.164\n```\n\n\n:::\n:::\n\n\n:::\n\nDrei Befunde sprechen gegen den t-Test. Erstens klafft in Kanal B eine Lücke\nzwischen Mittelwert (6.06 Minuten) und Median (3.20 Minuten); der Mittelwert\nbeschreibt hier keinen typischen Fall. Zweitens biegt der QQ-Plot am oberen Ende\ndeutlich von der Geraden weg. Drittens beträgt die Standardabweichung in Kanal B\n8.16 Minuten und damit mehr als der Mittelwert selbst, was fast immer auf einen\ndominierenden Einzelwert hindeutet. Bei zwölf Beobachtungen je Gruppe rettet der\nzentrale Grenzwertsatz das nicht mehr.\n\n#### Rechnung\n\nGerechnet werden beide Verfahren nebeneinander, damit sichtbar wird, was auf dem\nSpiel steht.\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(kanal_a, kanal_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  kanal_a and kanal_b\nt = -1.7764, df = 11.807, p-value = 0.1014\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -9.5001417  0.9751417\nsample estimates:\nmean of x mean of y \n 1.795833  6.058333 \n```\n\n\n:::\n\n```{.r .cell-code}\nwilcox.test(kanal_a, kanal_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum exact test\n\ndata:  kanal_a and kanal_b\nW = 37, p-value = 0.0449\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(\"t-Test  p =\", round(pg_wert(pg.ttest(kanal_a, kanal_b, correction=True), \"p-val\"), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt-Test  p = 0.1014\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Mann-Whitney p =\", round(pg_wert(pg.mwu(kanal_a, kanal_b), \"p-val\"), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMann-Whitney p = 0.0464\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| t-Test `t` | -1.776 | Die Differenz der Mittelwerte beträgt 4.26 Minuten, ihr Standardfehler aber 2.40 Minuten. Der Ausreisser hat den Nenner stärker aufgebläht als den Zähler. |\n| t-Test `df` | 11.807 | Trotz 22 möglichen Freiheitsgraden bleiben knapp 12 übrig, weil B rund fünfmal so stark streut wie A. |\n| t-Test `p-value` | 0.101 | Nicht signifikant. |\n| t-Test Intervall | -9.50 bis 0.98 Minuten | So breit, dass es praktisch nichts ausschliesst. |\n| Mann-Whitney `W` bzw. `U_val` | 37 | Die Rangstatistik, nicht in Minuten interpretierbar. In R heisst sie `W`, in pingouin `U_val`; gezählt wird gleich. |\n| Mann-Whitney `p-value` | 0.045 in R, 0.046 in Python | Knapp unter 0.05, also gegenteilige Entscheidung als beim t-Test. Die kleine Abweichung zwischen den Sprachen ist kein Fehler: R rechnet bei zwölf Werten ohne Bindungen die exakte Verteilung aus, pingouin verwendet die Normalapproximation. |\n\nBeide Tests rechnen mit denselben Daten und kommen zu verschiedenen Schlüssen.\nDer Rangtest sieht nur die Reihenfolge der Werte, und in der Reihenfolge liegt\nKanal B durchgehend hinten. Der t-Test sieht dagegen die absoluten Abstände, und\nder Wert von 30 Minuten schlägt in der Streuung so stark durch, dass die\nTeststatistik einbricht.\n\n#### Interpretation und Ergebnissatz\n\nEntscheidend ist, dass die Wahl des Verfahrens vor dem Blick auf die p-Werte\ngetroffen wird. Wer beide rechnet und nachträglich das passendere Ergebnis\nberichtet, hat kein Testniveau mehr, sondern eine Erzählung. Hier führen die\nVoraussetzungsprüfung und nichts anderes zum Rangtest.\n\nDrei gangbare Wege, alle vorab zu wählen:\n\n| Weg | Was dann berichtet wird |\n|---|---|\n| [Mann-Whitney](nichtparametrische-tests.qmd) | eine Aussage über die zentrale Tendenz, nicht über Mittelwerte |\n| Logarithmieren und dann t-Test | eine Aussage über das Verhältnis der Mediane, nicht über die Differenz |\n| [Bootstrap](../inferenz/bootstrap-resampling.qmd) | ein Intervall für die Mittelwertdifferenz ohne Verteilungsannahme |\n\nUnd in jedem Fall gehört der Ausreisser untersucht statt still entfernt: Ein\nWert von 30 Minuten kann ein Erfassungsfehler sein, ein Feiertag oder genau der\nFall, um den es eigentlich geht.\n\n> Wegen deutlich rechtsschiefer Verteilungen und eines Extremwerts bei kleinem\n> Umfang wurde vorab rangbasiert verglichen. Die Wartezeit ist in Kanal B höher\n> (Mann-Whitney, exakt, p = 0.045, n = 12 je Kanal; Median 1.25 gegenüber 3.20\n> Minuten). Auf einen Mittelwertvergleich wurde bewusst verzichtet.\n\n### Beispiel 4: Signifikant und belanglos\n\n#### Frage und Datenlage\n\nJetzt liegen aus jeder Maschine 5000 vermessene Teile vor, und der wahre\nUnterschied beträgt 0.03 mm, also weit unterhalb jeder Fertigungstoleranz. Um\nden Fall in beiden Sprachen exakt gleich zu halten, werden die Daten nicht\nzufällig gezogen, sondern als Quantile der Normalverteilung konstruiert. Beide\nGruppen haben damit exakt dieselbe Streuung und unterscheiden sich um exakt\n0.03 mm.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq <- qnorm(ppoints(5000))\ngross_a <- 12.10 + 0.40 * q\ngross_b <- 12.13 + 0.40 * q\n\ngross <- t.test(gross_a, gross_b)\nround(c(differenz = unname(diff(rev(gross$estimate))),\n        unten = gross$conf.int[1], oben = gross$conf.int[2],\n        t = unname(gross$statistic), p = gross$p.value), 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndifferenz     unten      oben         t         p \n -0.03000  -0.04568  -0.01432  -3.75012   0.00018 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom scipy import stats\n\nq = stats.norm.ppf((np.arange(1, 5001) - 0.5) / 5000)\ngross_a = 12.10 + 0.40 * q\ngross_b = 12.13 + 0.40 * q\n\nprint(pg_auswahl(pg.ttest(gross_a, gross_b, correction=True),\n                 \"T\", \"dof\", \"p_val\", \"p-val\", \"CI95\", \"CI95%\",\n                 \"cohen_d\", \"cohen-d\").round(5).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       T    dof   p_val           CI95  cohen_d\n-3.75012 9998.0 0.00018 [-0.05, -0.01]    0.075\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Differenz | -0.030 mm | Der wahre Unterschied, hier exakt bekannt. |\n| `t` | -3.750 | Deutlich über der üblichen Schwelle von etwa 2. |\n| `df` | 9998 | Ganzzahlig, weil beide Gruppen konstruktionsbedingt exakt dieselbe Varianz haben. Welch und Student fallen hier zusammen. |\n| `p-value` | 0.00018 | Hochsignifikant. |\n| Intervall | -0.046 bis -0.014 mm | Sehr eng. Der Unterschied ist präzise geschätzt und trotzdem winzig. |\n| `cohen_d` | 0.075 | Weit unter dem Anhaltspunkt 0.2 für einen kleinen Effekt. |\n\n#### Interpretation und Ergebnissatz\n\nHier trennen sich statistische und praktische Bedeutung sauber. Der p-Wert misst,\nwie gut sich der Unterschied vom Zufall abheben lässt, und das hängt am\nStichprobenumfang: Bei 5000 Teilen je Maschine wird auch ein Unterschied von\ndrei Hundertstel Millimetern sichtbar. Cohens d und das Intervall in Millimetern\nmessen dagegen, wie gross er ist, und diese Zahlen ändern sich mit dem Umfang\nnicht.\n\nDer p-Wert allein reicht deshalb nie. Berichtet werden Differenz und Intervall\nin der Einheit der Messung, und die Relevanzschwelle steht vor der Auswertung\nfest.\n\n> Die Maschinen unterscheiden sich statistisch nachweisbar (Welch-Test,\n> t(9998) = -3.75, p < 0.001, n = 5000 je Maschine). Der Unterschied beträgt\n> 0.030 mm (95-Prozent-Konfidenzintervall 0.014 bis 0.046 mm, Cohens d = 0.08)\n> und liegt damit weit unterhalb der Fertigungstoleranz; praktische\n> Konsequenzen ergeben sich daraus nicht.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nDer Output zeigt `df = 24.385`. Ist das ein Fehler?\n\n- [x] Nein, das ist die Welch-Korrektur ~ Richtig. Bei ungleichen Varianzen\n      werden die Freiheitsgrade aus beiden Varianzen und Gruppengrössen\n      geschätzt und sind dann keine ganze Zahl.\n- [ ] Ja, Freiheitsgrade sind immer ganzzahlig ~ Bei der Student-Variante ja,\n      bei Welch nicht.\n- [ ] Ja, es fehlen Beobachtungen ~ Fehlende Werte würden die Gruppengrössen\n      verringern, nicht zu Nachkommastellen führen.\n:::\n\n::: {.quiz}\nIn Beispiel 1 ist der p-Wert mit 0.013 knapp, Cohens d mit -0.97 aber gross.\nWie passt das zusammen?\n\n- [x] Der p-Wert hängt zusätzlich am Stichprobenumfang, die Effektstärke nicht ~\n      Richtig. Bei nur fünfzehn Teilen je Maschine ist der Standardfehler gross,\n      also fällt der p-Wert knapp aus, obwohl der Unterschied gemessen an der\n      Streuung erheblich ist.\n- [ ] Einer der beiden Werte muss falsch sein ~ Beide sind korrekt; sie messen\n      Verschiedenes.\n- [ ] Ein grosses d erzwingt einen kleinen p-Wert ~ Nur bei festem Umfang. Mit\n      wachsendem n sinkt der p-Wert, d bleibt gleich.\n:::\n\n::: {.quiz}\nIn Beispiel 3 liefert der t-Test p = 0.10 und der Rangtest p = 0.05. Wie wird\nentschieden?\n\n- [x] Anhand der vorab geprüften Voraussetzungen, hier also rangbasiert ~\n      Richtig. Die Voraussetzungsprüfung entscheidet über das Verfahren, und\n      zwar bevor irgendein p-Wert vorliegt.\n- [ ] Man berichtet den kleineren p-Wert ~ Das wäre eine Auswahl nach Ergebnis\n      und zerstört die Fehlerkontrolle.\n- [ ] Man berichtet beide und überlässt die Wahl dem Leser ~ Beide zu zeigen ist\n      als Sensitivitätsanalyse zulässig, aber das Hauptverfahren muss vorab\n      benannt sein.\n:::\n\n::: {.quiz}\nZwei Gruppen mit je n = 2000 unterscheiden sich um 0.01 Einheiten, p < 0.001,\nCohens d = 0.03. Was berichtet man?\n\n- [ ] Einen signifikanten Unterschied, das genügt ~ Es genügt nicht: der Leser\n      erfährt nicht, dass der Unterschied praktisch bedeutungslos ist.\n- [x] Den Unterschied mit Intervall und Effektstärke, samt Einordnung ~ Richtig.\n      Der p-Wert zeigt nur, dass der Unterschied bei diesem Umfang vom Zufall\n      unterscheidbar ist. Relevanz entscheidet die Grösse, hier praktisch null.\n- [ ] Gar nichts, das Ergebnis ist wertlos ~ Wertlos ist es nicht, es ist nur\n      korrekt einzuordnen.\n:::\n\n::: {.quiz}\nVor dem Test wird ein Varianzvergleich gerechnet, und je nach dessen Ergebnis\nwird Student oder Welch gewählt. Was ist daran problematisch?\n\n- [x] Die Entscheidung anhand derselben Daten verschlechtert die Fehlerkontrolle ~\n      Richtig. Das zweistufige Vorgehen hält das Niveau nicht ein. Welch\n      grundsätzlich zu verwenden ist einfacher und in fast allen Lagen mindestens\n      so gut.\n- [ ] Nichts, so ist es vorgesehen ~ Es war lange üblich und gilt heute als\n      überholt.\n- [ ] Der Varianzvergleich ist zu konservativ ~ Das Problem liegt nicht in\n      seiner Schärfe, sondern im datengetriebenen Wechsel des Verfahrens.\n:::\n\n::: {.quiz}\nDas Konfidenzintervall der Differenz reicht von -0.05 bis 0.62 mm, die\nToleranzgrenze der Fertigung liegt bei 0.10 mm. Was folgt?\n\n- [ ] Kein Unterschied, das Intervall enthält null ~ Formal nicht signifikant,\n      aber die Aussage greift zu kurz.\n- [x] Die Frage ist offen, und zwar in einem relevanten Bereich ~ Richtig. Das\n      Intervall lässt Werte weit über der Toleranzgrenze zu. Nicht signifikant\n      heisst hier nicht unbedenklich, sondern zu wenig Daten.\n- [ ] Der Unterschied liegt sicher unter der Toleranz ~ Das würde ein Intervall\n      erfordern, das vollständig unterhalb von 0.10 liegt.\n:::\n\n## Verlinkte Ressourcen\n\n- [OpenIntro Statistics, Kapitel zum Mittelwertvergleich](https://www.openintro.org/book/os/)\n- [pingouin: ttest](https://pingouin-stats.org/build/html/generated/pingouin.ttest.html)\n- [R-Dokumentation zu `t.test`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/t.test.html)\n",
    "supporting": [
      "t-test-zwei-stichproben_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}