{
  "hash": "9a4818632d12d39e26f5960f18e1a81e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Reproduzierbarkeit\"\ndescription: \"Projekte, Notebooks, Seeds und Quarto als durchgehender Arbeitsweg.\"\ncategories: [\"Reproduzierbarkeit\", \"Tooling\", \"R\", \"Python\"]\nquelle: [\"ESDS\"]\nseitentyp: werkzeug\nstand: entwurf\norder: 90\n---\n\n\n\n\n\n## Kernideen\n\n- Eine Auswertung ist reproduzierbar, wenn sie **nach einem Neustart von oben\n  nach unten** durchläuft und dieselben Zahlen liefert.\n- Das **Projekt** legt das Arbeitsverzeichnis fest; Pfade werden **relativ**\n  dazu geschrieben und mit `file.path` beziehungsweise `pathlib` gebaut.\n- Zahlen im Bericht kommen **aus dem Code**, nicht aus der Zwischenablage.\n  Quarto und R Markdown setzen sie beim Rendern ein.\n- Ein **Seed** macht Zufall innerhalb einer Sprache wiederholbar, aber nicht\n  zwischen den Sprachen.\n- Auch deterministische Rechnungen hängen an Details: an der **Reihenfolge**\n  von Gleitkommaoperationen und am **Zustand der Sitzung**.\n- Die **Umgebung** gehört zur Auswertung, siehe\n  [Pakete und Umgebungen](pakete-umgebungen.qmd).\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [R-Grundlagen](r-grundlagen.qmd) oder\n[Python-Grundlagen](python-grundlagen.qmd), je nachdem, womit gearbeitet wird.\nWie man die Paketstände festhält, steht unter\n[Pakete und Umgebungen](pakete-umgebungen.qmd), wie man Änderungen\nnachvollziehbar speichert, unter [Git](../werkzeuge/git.qmd).\n:::\n\n### Vier Stufen\n\n| Stufe | Frage | Mittel |\n|---|---|---|\n| wiederholbar | liefert dasselbe Skript auf demselben Rechner dasselbe? | Seed, Neustart statt gewachsener Sitzung |\n| übertragbar | läuft es auf einem anderen Rechner? | Projektordner, relative Pfade |\n| dauerhaft | läuft es in einem Jahr noch? | festgehaltene Paketversionen, Container |\n| nachvollziehbar | versteht jemand anders, was passiert ist? | Bericht mit eingebettetem Code, Versionsverwaltung |\n\n### Das Projekt statt des Arbeitsverzeichnisses\n\nEin Skript, das bei jemand anderem nicht läuft, scheitert erfahrungsgemäss an\neinem absoluten Pfad wie `C:/Users/mv/Desktop/Analyse/daten.csv`. Er\nverweist auf ein Verzeichnis, das nur auf einem Rechner existiert. Ein\nRStudio-Projekt, ein Projektordner in VS Code oder das Verzeichnis eines\nQuarto-Projekts legt das Arbeitsverzeichnis auf den Projektordner fest;\nPfade werden relativ dazu geschrieben und funktionieren überall, wo der Ordner\nals Ganzes liegt. Wer Pfade mit `file.path()` oder `pathlib` zusammensetzt\nstatt mit Schrägstrichen, muss sich zudem nicht um Windows und Linux kümmern.\n\n### Der Zustand der Sitzung\n\nRStudio bietet an, die Objekte beim Beenden zu speichern und beim Start\nwiederherzustellen. Das wirkt hilfreich und verdeckt Fehler: Ein Skript, das\nnur läuft, weil eine Variable noch aus der letzten Woche im Speicher liegt,\nist nicht reproduzierbar. Die Einstellung gehört ausgeschaltet\n(*Tools → Global Options → Workspace*). In Jupyter entsteht dasselbe\nProblem, wenn Zellen in beliebiger Reihenfolge ausgeführt werden. Die Probe\nist in beiden Fällen dieselbe: Neustart mit leerer Umgebung und ein\nvollständiger Durchlauf von oben.\n\n### Berichte, die nicht veralten\n\nEine Zahl, die von Hand aus der Konsole in ein Textdokument kopiert wurde, ist\nab dem nächsten Datenstand falsch, und niemand sieht ihr das an. Quarto und R\nMarkdown lösen das, indem Text und Rechnung in derselben Datei stehen. Beim\nRendern wird der Code ausgeführt und das Ergebnis eingesetzt, in Chunks und\nmitten im Satz:\n\n\n````{.default}\n```{r}\nwerte <- c(12.1, 14.3, 11.8, 15.0, 13.6)\n```\n\nDer Mittelwert liegt bei `r round(mean(werte), 2)`.\n````\n\nDiese Sammlung arbeitet genau so: Jede Ausgabe entsteht beim Bauen der\nWebsite aus dem Code, der daneben steht. Die Zahlen im Fliesstext werden\ndanach gegen die Ausgabe geprüft, weil ein Satz, der eine Zahl von Hand\nnennt, wieder veralten kann.\n\n### Notebooks und Versionsverwaltung\n\nAusgaben in einem Jupyter-Notebook erzeugen bei jedem Speichern grosse,\nunleserliche Änderungen in Git. Wer sie vor dem Commit entfernt\n(`jupyter nbconvert --clear-output --inplace analyse.ipynb`), bekommt\nbrauchbare Diffs. Quarto-Dateien (`.qmd`) haben das Problem nicht, weil sie\nreiner Text sind und die Ausgabe getrennt entsteht.\n\n### Kurz nachgeschlagen\n\n| Aufgabe | R | Python |\n|---|---|---|\n| Zufall wiederholbar | `set.seed(42)` | `rng = np.random.default_rng(42)` |\n| Pfad bauen | `file.path(\"daten\", \"messung.csv\")` | `Path(\"daten\") / \"messung.csv\"` |\n| Pfad relativ zum Projekt | `here::here(\"daten\", \"messung.csv\")` | `Path(__file__).resolve().parent / \"daten\"` |\n| Dokument rendern | `quarto render bericht.qmd` | `quarto render bericht.qmd` |\n| Stand festhalten | `renv::snapshot()`, `sessionInfo()` | `pip freeze > requirements.txt` |\n| Notebook ohne Ausgaben | | `jupyter nbconvert --clear-output --inplace datei.ipynb` |\n| exakte Summe | `sum()` rechnet mit erhöhter Genauigkeit | `math.fsum()` |\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Seeds innerhalb und zwischen den Sprachen\n\n#### Frage und Datenlage\n\nDrei gleichverteilte Zufallszahlen mit dem Seed 42, zweimal hintereinander:\nSind sie gleich? Und liefern R und Python mit demselben Seed dieselben Zahlen?\nZum Vergleich drei Werte aus einem Lehmer-Generator mit der Saat 12345, in\nbeiden Sprachen selbst geschrieben.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\na <- runif(3)\nset.seed(42)\nb <- runif(3)\nround(a, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9148 0.9371 0.2861\n```\n\n\n:::\n\n```{.r .cell-code}\nidentical(a, b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nround(lehmer(12345, 3), 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.096617 0.833995 0.947702\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\na = np.random.default_rng(42).random(3)\nb = np.random.default_rng(42).random(3)\nprint(np.round(a, 4), bool((a == b).all()))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[0.774  0.4389 0.8586] True\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(np.round(lehmer(12345, 3), 6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[0.096617 0.833995 0.947702]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Zeile | R | Python | Erklärung |\n|---|---|---|---|\n| zweimal Seed 42 | `identical`: `TRUE` | `True` | Innerhalb einer Sprache ist der Zufall mit Seed vollständig wiederholbar. |\n| die drei Zahlen | eine Folge | eine **andere** Folge | R verwendet den Mersenne-Twister, NumPy standardmässig PCG64. Derselbe Seed, verschiedene Generatoren. |\n| Lehmer mit Saat 12345 | 0.096617, 0.833995, 0.947702 | dieselben Werte | Ein Generator aus einer Formel, in beiden Sprachen gleich geschrieben, liefert identische Zahlen. |\n\nDer Lehmer-Generator rechnet `s = 16807 · s mod (2³¹ − 1)` und teilt durch\nden Modulus. Er ist statistisch schlicht, genügt aber für Beispieldaten und\nhat den einen Vorteil, auf den es hier ankommt: Er ist in jeder Sprache in\ndrei Zeilen nachgebaut.\n\n#### Interpretation und Ergebnissatz\n\nEin Seed garantiert Wiederholbarkeit, nicht Übertragbarkeit. Wer dieselbe\nAuswertung in R und Python rechnet und mit `set.seed(42)` und\n`default_rng(42)` Daten erzeugt, vergleicht zwei verschiedene Datensätze.\nDiese Sammlung hat genau das anfangs auf mehreren Seiten getan, und die\nInterpretationen stimmten nie für beide Sprachen zugleich. Seither sind alle\nBeispieldaten fest eingetragen oder mit dem Lehmer-Generator erzeugt.\n\n> Mit demselben Seed liefert jede Sprache bei jedem Lauf dieselben Zahlen,\n> R und Python aber verschiedene. Der in beiden Sprachen gleich geschriebene\n> Lehmer-Generator liefert identisch 0.096617, 0.833995 und 0.947702.\n\n### Beispiel 2: Die Zahl im Text kommt aus dem Code\n\n#### Frage und Datenlage\n\nFünf Messwerte `12.1, 14.3, 11.8, 15.0, 13.6`. Der Mittelwert soll im\nErgebnissatz stehen, ohne ihn abzutippen.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwerte <- c(12.1, 14.3, 11.8, 15.0, 13.6)\nround(mean(werte), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13.36\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nwerte = [12.1, 14.3, 11.8, 15.0, 13.6]\nmittel = round(sum(werte) / len(werte), 2)\nprint(f\"Der Mittelwert liegt bei {mittel}.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDer Mittelwert liegt bei 13.36.\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Teil | Ergebnis | Erklärung |\n|---|---|---|\n| R-Chunk | 13.36 | die Rechnung, sichtbar mit Code |\n| Python mit f-String | `Der Mittelwert liegt bei 13.36.` | Der Satz entsteht im Code und wird als Ausgabe gezeigt. |\n| Ergebnissatz unten | 13.36 | eingesetzt über Inline-Code, der mit `r` beginnt, beim Rendern; der Quelltext steht oben unter \"Berichte, die nicht veralten\" |\n\nInline-Code ist in dieser Sammlung auf R beschränkt, weil die Seiten mit\nknitr gerendert werden. Mit der Jupyter-Engine bietet Quarto dasselbe für\nPython in der Form `` `{python} ausdruck` ``.\n\n#### Interpretation und Ergebnissatz\n\nÄndert sich ein Messwert, ändert sich beim nächsten Rendern auch die Zahl im\nSatz. Ein abgetippter Wert bliebe stehen und wäre ab dann falsch, ohne dass\nman es ihm ansieht. Für Berichte, die mit neuen Daten wiederholt werden, ist\ndas der eigentliche Gewinn.\n\n> Der Mittelwert der fünf Messwerte liegt bei 13.36.\n\n### Beispiel 3: Pfade bauen statt zusammenkleben\n\n#### Frage und Datenlage\n\nDie Datei `messung.csv` liegt im Projekt unter `daten/roh/`. Wie baut man\ndiesen Pfad unabhängig vom Betriebssystem, und wie zerlegt man ihn in Name,\nEndung und Ordner?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npfad <- file.path(\"daten\", \"roh\", \"messung.csv\")\npfad\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"daten/roh/messung.csv\"\n```\n\n\n:::\n\n```{.r .cell-code}\nc(name = basename(pfad), ordner = dirname(pfad),\n  endung = tools::file_ext(pfad),\n  ohne_endung = tools::file_path_sans_ext(basename(pfad)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         name        ordner        endung   ohne_endung \n\"messung.csv\"   \"daten/roh\"         \"csv\"     \"messung\" \n```\n\n\n:::\n\n```{.r .cell-code}\nfile.exists(\"C:/Users/mv/Desktop/Analyse/daten.csv\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\npfad = Path(\"daten\") / \"roh\" / \"messung.csv\"\nprint(pfad.as_posix())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndaten/roh/messung.csv\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pfad.name, pfad.stem, pfad.suffix, pfad.parent.as_posix())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmessung.csv messung .csv daten/roh\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pfad.with_suffix(\".parquet\").as_posix())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndaten/roh/messung.parquet\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(str(PureWindowsPath(\"daten\") / \"roh\" / \"messung.csv\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndaten\\roh\\messung.csv\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pfad.is_absolute(), Path(\"C:/Users/mv/Desktop/Analyse/daten.csv\").exists())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFalse False\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | Python | R | Erklärung |\n|---|---|---|---|\n| Pfad | `daten/roh/messung.csv` | `\"daten/roh/messung.csv\"` | Relativ zum Projektordner, ohne Laufwerk und Benutzername. |\n| Name | `messung.csv` | `basename` | |\n| ohne Endung | `stem`: `messung` | `file_path_sans_ext` | |\n| Endung | `.csv` | `file_ext`: `csv` | Python behält den Punkt, R nicht. |\n| Ordner | `daten/roh` | `dirname` | |\n| andere Endung | `daten/roh/messung.parquet` | | etwa für die Ablage eines bereinigten Stands |\n| unter Windows | `daten\\roh\\messung.csv` | | Derselbe Code liefert dort den passenden Trenner. |\n| absolut? | `False` | | |\n| absoluter Fremdpfad vorhanden? | `False` | `FALSE` | Auf dem Rechner, der diese Seite baut, gibt es diesen Ordner nicht, genau wie auf jedem anderen fremden Rechner. |\n\n#### Interpretation und Ergebnissatz\n\nDer absolute Pfad aus der letzten Zeile ist der typische Grund, warum ein\nSkript beim Weitergeben scheitert. Ein relativer, gebauter Pfad beschreibt\nnur die Lage innerhalb des Projekts und funktioniert überall, wo der Ordner\nals Ganzes liegt. `pathlib` bietet dazu die Zerlegung in Name, Stamm und\nEndung, die beim Umbenennen und Umwandeln von Dateien laufend gebraucht wird.\n\n> Der Pfad `daten/roh/messung.csv` wird mit `file.path` beziehungsweise\n> `Path(...) / ...` gebaut und unter Windows automatisch mit Rückwärtsstrich\n> geschrieben. Der absolute Pfad auf einen fremden Benutzerordner existiert\n> auf dem Build-Rechner nicht.\n\n### Beispiel 4: Die Reihenfolge der Rechnung\n\n#### Frage und Datenlage\n\nDrei Additionen mit denselben Zahlen in verschiedener Klammerung, einmal mit\n`0.1, 0.2, 0.3` und einmal mit `1e16, 1, -1e16`. Liefern sie dasselbe, und\nwas tun die eingebauten Summenfunktionen?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- (0.1 + 0.2) + 0.3\ny <- 0.1 + (0.2 + 0.3)\nc(sprintf(\"%.17g\", x), sprintf(\"%.17g\", y))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"0.60000000000000009\" \"0.59999999999999998\"\n```\n\n\n:::\n\n```{.r .cell-code}\nx == y\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\n(1e16 + 1) - 1e16\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nReduce(`+`, c(1e16, 1, -1e16))     # Schritt fuer Schritt\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(c(1e16, 1, -1e16))             # mit erhoehter Genauigkeit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nx = (0.1 + 0.2) + 0.3\ny = 0.1 + (0.2 + 0.3)\nprint(f\"{x:.17g} {y:.17g} {x == y}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.60000000000000009 0.59999999999999998 False\n```\n\n\n:::\n\n```{.python .cell-code}\ngross = [1e16, 1.0, -1e16]\nschrittweise = 0.0\nfor wert in gross:\n    schrittweise += wert\nprint(schrittweise, sum(gross), math.fsum(gross))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.0 1.0 1.0\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Rechnung | Python | R | Erklärung |\n|---|---|---|---|\n| `(0.1 + 0.2) + 0.3` | 0.60000000000000009 | dieselbe Zahl | Das Zwischenergebnis 0.30000000000000004 trägt seinen Fehler weiter. |\n| `0.1 + (0.2 + 0.3)` | 0.59999999999999998 | dieselbe Zahl | Andere Reihenfolge, anderer Rundungsfehler. |\n| gleich? | `False` | `FALSE` | Die Addition von Gleitkommazahlen ist nicht assoziativ. |\n| `1e16 + 1 − 1e16` schrittweise | 0.0 | 0 | 1e16 + 1 lässt sich nicht darstellen und wird zu 1e16; die 1 ist verloren. |\n| eingebaute Summe | `sum`: 1.0 | `sum`: 1 | Python rechnet seit Version 3.12 mit Fehlerausgleich, R summiert intern mit erhöhter Genauigkeit. Beide finden die 1 wieder. |\n| exakte Summe | `math.fsum`: 1.0 | | garantiert korrekt gerundet |\n\n#### Interpretation und Ergebnissatz\n\nDasselbe Programm ist also nur dann bit für bit reproduzierbar, wenn auch die\nReihenfolge der Operationen gleich bleibt. Bei paralleler Berechnung, bei\nanderer Sortierung der Daten oder bei einer neuen Bibliotheksversion kann\nsich die letzte Stelle ändern. Das ist kein Fehler, sondern der Grund, warum\nErgebnisse mit Toleranz verglichen werden (siehe\n[Python-Grundlagen](python-grundlagen.qmd), Beispiel 5) und warum man in\nBerichten nicht mehr Stellen nennt, als die Daten tragen.\n\n> `(0.1 + 0.2) + 0.3` und `0.1 + (0.2 + 0.3)` unterscheiden sich in der\n> siebzehnten Stelle, in R wie in Python. Schrittweise addiert geht die 1 in\n> `1e16 + 1 − 1e16` verloren; die eingebauten Summenfunktionen beider Sprachen\n> liefern 1.\n\n### Beispiel 5: Versteckter Zustand\n\n#### Frage und Datenlage\n\nEine Funktion multipliziert mit einem Faktor, der ausserhalb von ihr\ndefiniert ist. Zwischen zwei Aufrufen wird der Faktor weiter oben im Skript\ngeändert, etwa in einer Notebook-Zelle, die später noch einmal ausgeführt\nwurde.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfaktor <- 2\nskaliere <- function(x) x * faktor\nskaliere(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6\n```\n\n\n:::\n\n```{.r .cell-code}\nfaktor <- 10                 # irgendwo weiter oben geaendert\nskaliere(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 30\n```\n\n\n:::\n\n```{.r .cell-code}\nskaliere_sauber <- function(x, faktor) x * faktor\nskaliere_sauber(3, faktor = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfaktor = 2\ndef skaliere(x):\n    return x * faktor\nprint(skaliere(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n6\n```\n\n\n:::\n\n```{.python .cell-code}\nfaktor = 10                  # irgendwo weiter oben geaendert\nprint(skaliere(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n30\n```\n\n\n:::\n\n```{.python .cell-code}\ndef skaliere_sauber(x, faktor):\n    return x * faktor\nprint(skaliere_sauber(3, faktor=2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n6\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Aufruf | Ergebnis | Erklärung |\n|---|---|---|\n| erster Aufruf | 6 | Der Faktor ist 2. |\n| nach der Änderung | **30** | Derselbe Aufruf, ein anderes Ergebnis. Die Funktion liest den Faktor erst beim Aufruf. |\n| mit Argument | 6 | Alles, was die Funktion braucht, steht im Aufruf. |\n\n#### Interpretation und Ergebnissatz\n\nIm Skript sieht man die Ursache, weil die Zeilen untereinander stehen. In einer\ngewachsenen Sitzung oder einem Notebook, dessen Zellen in anderer Reihenfolge\nliefen, sieht man sie nicht: Dieselbe Zelle liefert heute 30 und nach einem\nNeustart 6. Zwei Gegenmittel ergänzen sich. Funktionen bekommen alles, was\nsie brauchen, als Argument. Und vor jedem Ergebnis, das weitergegeben wird,\nsteht der Neustart mit vollständigem Durchlauf von oben.\n\n> Derselbe Aufruf `skaliere(3)` lieferte 6 und nach einer Änderung des\n> äusseren Faktors 30. Mit dem Faktor als Argument hängt das Ergebnis nur\n> noch vom Aufruf ab.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEin Skript liest Daten über `read.csv(\"C:/Users/mv/Desktop/Analyse/daten.csv\")`\nund läuft auf dem eigenen Rechner einwandfrei. Was spricht trotzdem dagegen?\n\n- [ ] Nichts, solange es funktioniert ~ Es funktioniert genau so lange, wie\n      niemand anders es ausführt und niemand den Ordner verschiebt.\n- [x] Der Pfad enthält eine Voraussetzung, die nirgends dokumentiert ist ~\n      Richtig. Auf einem anderen Rechner existiert der Ordner nicht, wie\n      Beispiel 3 zeigt. Ein relativer Pfad beschreibt nur die Lage innerhalb\n      des Projekts.\n- [ ] `read.csv` ist veraltet ~ Um die Funktion geht es nicht, sondern um den\n      Pfad.\n:::\n\n::: {.quiz}\nR rechnet mit `set.seed(42)`, Python mit `np.random.default_rng(42)`. Die\nMittelwerte der erzeugten Daten unterscheiden sich. Was ist los?\n\n- [x] Die beiden Sprachen verwenden verschiedene Zufallsgeneratoren ~\n      Richtig. Derselbe Seed erzeugt verschiedene Folgen. Für vergleichbare\n      Ergebnisse braucht es fest eingetragene Daten oder einen in beiden\n      Sprachen gleich geschriebenen Generator.\n- [ ] Einer der beiden Seeds wurde falsch gesetzt ~ Beide sind korrekt\n      gesetzt und je für sich wiederholbar.\n- [ ] Python rundet anders ~ Die Zahlen sind von Anfang an verschieden.\n:::\n\n::: {.quiz}\nWarum sollte RStudio den Arbeitsspeicher beim Beenden nicht sichern?\n\n- [ ] Weil das Speichern zu lange dauert ~ Die Zeit ist nicht das Problem.\n- [x] Weil sonst Objekte überleben, die das Skript gar nicht mehr erzeugt ~\n      Richtig. Das Skript läuft dann scheinbar, obwohl es unvollständig ist,\n      wie der Faktor in Beispiel 5. Die Probe ist ein Neustart mit leerer\n      Umgebung.\n- [ ] Weil die Datei zu gross wird ~ Sie kann gross werden, aber der\n      entscheidende Grund ist die verdeckte Abhängigkeit.\n:::\n\n::: {.quiz}\nZwei Läufe derselben Auswertung, einmal seriell und einmal parallel,\nunterscheiden sich in der 16. Nachkommastelle. Ist das ein Fehler?\n\n- [ ] Ja, eine deterministische Rechnung muss bitgleich sein ~ Nur bei\n      gleicher Reihenfolge der Operationen.\n- [x] Nein, Gleitkommaaddition ist nicht assoziativ, und die Reihenfolge hat\n      sich geändert ~ Richtig, wie Beispiel 4 zeigt. Ergebnisse vergleicht\n      man deshalb mit Toleranz und berichtet nur sinnvolle Stellen.\n- [ ] Ja, einer der Rechner ist defekt ~ Beide rechnen korrekt nach dem\n      Gleitkommastandard.\n:::\n\n::: {.quiz}\nEine Zahl im Bericht wurde aus der Konsole kopiert. Was ist das Risiko?\n\n- [x] Sie veraltet beim nächsten Datenstand, ohne dass es auffällt ~\n      Richtig. Inline-Code, der mit `r` beginnt, setzt die\n      Zahl bei jedem Rendern neu ein.\n- [ ] Sie wird falsch gerundet ~ Das Kopieren ändert die Rundung nicht.\n- [ ] Keines, solange sie einmal richtig war ~ Genau das ist das Risiko:\n      einmal richtig heisst nicht immer richtig.\n:::\n\n## Verlinkte Ressourcen\n\n- [Quarto: Dokumentation](https://quarto.org/docs/guide/)\n- [What They Forgot to Teach You About R: Projektarbeit](https://rstats.wtf/)\n- [Was jeder über Gleitkomma-Arithmetik wissen sollte](https://docs.python.org/3/tutorial/floatingpoint.html)\n",
    "supporting": [
      "reproduzierbarkeit_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}