{
  "hash": "2ef763e7cf77d2b03bf17101fb2d1690",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Modellauswahl\"\ndescription: \"F-Test, AIC, BIC und Kreuzvalidierung, und warum schrittweise Auswahl täuscht.\"\ncategories: [\"Regression\", \"Modelldiagnostik\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: methode\nstand: entwurf\norder: 40\n---\n\n\n\n\n\nAlle Beispiele rechnen mit demselben Datensatz: 150 Fälle, zwei Prädiktoren\n`x1` und `x2`, die tatsächlich auf `y` wirken, und sechs Grössen `z1` bis `z6`,\ndie nichts damit zu tun haben. Weil die Wahrheit hier bekannt ist, lässt sich\nprüfen, welches Auswahlverfahren sie findet.\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Welche Prädiktoren gehören ins Modell? |\n| Eingang | mehrere angepasste Modelle auf denselben Daten |\n| Was die Verfahren liefern | F-Test für geschachtelte Modelle, AIC und BIC für beliebige, Kreuzvalidierungsfehler als direkte Schätzung der Vorhersagegüte |\n| R-Funktionen | `anova(m1, m2)`, `AIC()`, `BIC()`, `step()` |\n| Python-Funktionen | `sm.stats.anova_lm(m1, m2)`, `modell.aic`, `modell.bic` |\n| Verwandte Methoden | [multiple lineare Regression](multiple-lineare-regression.qmd), [Regressionsdiagnostik](regressionsdiagnostik.qmd), [Klassifikationsgüte](klassifikationsguete.qmd) |\n\n## Wann diese Methode, wann nicht\n\nModellauswahl beantwortet eine andere Frage als die\n[Diagnostik](regressionsdiagnostik.qmd). Die Diagnostik fragt, ob ein gegebenes\nModell zulässig ist; die Auswahl fragt, welches von mehreren zulässigen\nvorzuziehen ist.\n\nEntscheidend ist zuerst eine Vorfrage, die kein Verfahren beantworten kann:\n**Wozu dient das Modell?**\n\n| Ziel | Welches Kriterium passt |\n|---|---|\n| Vorhersage neuer Fälle | Kreuzvalidierung, ersatzweise AIC |\n| Das wahre Modell finden | BIC; es bevorzugt sparsame Modelle stärker |\n| Eine bestimmte Wirkung schätzen | **gar keines.** Die Prädiktoren ergeben sich aus dem Fachwissen, nicht aus den Daten |\n| Beschreiben, was zusammenhängt | Fachwissen zuerst, Kennzahlen als Ergänzung |\n\nDie dritte Zeile ist die wichtigste. Wer den Effekt einer Grösse schätzen will\nund dafür Prädiktoren nach statistischen Kriterien auswählt, verzerrt genau die\nSchätzung, um die es geht. Welche Störgrössen kontrolliert werden müssen, ist\neine inhaltliche Frage.\n\n## Grundidee und Modell\n\nJedes Kriterium wägt Anpassung gegen Sparsamkeit ab. Sie unterscheiden sich nur\ndarin, wie teuer ein zusätzlicher Parameter ist.\n\n| Kriterium | Formel im Kern | Preis je Parameter | Neigung |\n|---|---|---|---|\n| R² | erklärter Anteil | **null** | wählt immer das grösste Modell |\n| adjustiertes R² | R² mit Abzug je Parameter | klein | zu nachsichtig, siehe Beispiel 2 |\n| F-Test | Vergleich zweier geschachtelter Modelle | über das Signifikanzniveau | nur für geschachtelte Modelle |\n| AIC | $-2\\log L + 2k$ | 2 | zielt auf gute Vorhersage |\n| BIC | $-2\\log L + \\log(n)\\,k$ | $\\log(n)$, hier 5.01 | zielt auf das wahre Modell |\n| Kreuzvalidierung | gemessener Fehler auf ungesehenen Daten | keine Formel, direkte Messung | die ehrlichste Antwort, aber rechenaufwendig |\n\nZwei Modelle heissen **geschachtelt**, wenn das kleinere aus dem grösseren\nentsteht, indem man Koeffizienten auf null setzt. Nur dann ist der F-Test\nanwendbar. AIC, BIC und Kreuzvalidierung vergleichen auch nicht geschachtelte\nModelle, solange sie auf **denselben Beobachtungen** beruhen.\n\n::: {.note-box}\n**AIC und BIC sind nur als Differenz deutbar.** Der absolute Wert hängt an\nKonstanten, die je nach Software mitgezählt werden oder nicht. R zählt die\nReststreuung als zusätzlichen Parameter, statsmodels nicht; dadurch liegen die\nR-Werte um genau 2 (AIC) beziehungsweise $\\log(n)$ (BIC) höher. Die\nDifferenzen zwischen Modellen und damit die Rangfolge sind identisch, siehe\nBeispiel 2.\n\nAls Anhaltspunkt für die Grösse einer Differenz: unter 2 ist sie kaum\nbedeutsam, ab etwa 4 spricht sie deutlich für das kleinere Modell, ab 10 ist\ndas grössere praktisch ausgeschlossen.\n:::\n\n## Output lesen\n\n| Ausgabe | Was sie sagt | Falle |\n|---|---|---|\n| `anova(m1, m2)` `F` und `Pr(>F)` | Bringen die zusätzlichen Terme gemeinsam etwas? | nur für geschachtelte Modelle auf identischen Daten |\n| `AIC()` | Vergleichswert, kleiner ist besser | absolute Höhe bedeutungslos |\n| `BIC()` | dasselbe mit strengerem Abzug | wählt bei grossem n deutlich sparsamer |\n| `Adjusted R-squared` | R² mit Abzug | zu nachsichtig; steigt oft noch, wenn AIC schon fällt |\n| `step()` in R | schrittweise Auswahl | die Ausgabe sieht objektiv aus und ist es nicht, siehe Beispiel 3 |\n| Kreuzvalidierungsfehler | geschätzter Fehler auf neuen Daten | hängt an der Aufteilung; bei kleinen Datensätzen schwankt er merklich |\n\n## Interpretationsfallen\n\n- **R² ist als Auswahlkriterium unbrauchbar.** Es kann durch einen zusätzlichen\n  Prädiktor nie sinken.\n- **Adjustiertes R² ist zu nachsichtig.** In Beispiel 2 ist es für das Modell\n  mit sechs wertlosen Prädiktoren am höchsten.\n- **AIC und BIC lassen sich nicht zwischen Datensätzen vergleichen**, auch nicht\n  zwischen Modellen mit unterschiedlich vielen Zeilen. Fehlende Werte in einem\n  Prädiktor verkleinern die Zeilenzahl unbemerkt und machen den Vergleich\n  ungültig.\n- **Ein signifikanter Koeffizient nach schrittweiser Auswahl ist nicht\n  signifikant.** Der p-Wert unterstellt, dass die Frage vorab feststand.\n- **Die schrittweise Auswahl ist nicht reproduzierbar in ihrer Aussage.** Kleine\n  Änderungen an den Daten führen zu anderen Modellen.\n- **Kein Kriterium ersetzt Fachwissen.** Alle vergleichen nur die Modelle, die\n  man ihnen vorlegt.\n- **Das beste Modell nach AIC muss nicht gut sein.** Die Kriterien sind relativ;\n  sie sagen nichts darüber, ob das Gewinnermodell die Daten überhaupt angemessen\n  beschreibt. Das beantwortet die [Diagnostik](regressionsdiagnostik.qmd).\n\n## Ergebnis berichten\n\n> Verglichen wurden [Anzahl] Modelle auf denselben [n] Beobachtungen. Gewählt\n> wurde [Modell] mit [Kriterium] = [Wert]; das nächstbeste Modell liegt um\n> [Differenz] darüber. Die Auswahl der Kandidaten erfolgte [Begründung].\n\nGenannt werden: welche Modelle verglichen wurden und warum diese, welches\nKriterium mit welcher Begründung, die Werte aller Kandidaten und nicht nur des\nGewinners, und ob eine schrittweise Auswahl stattfand. Der letzte Punkt ist\nkeine Formalie: Er ändert die Deutung aller p-Werte im gewählten Modell.\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt der Modellauswahl |\n|---|---|\n| [Regressionsdiagnostik](regressionsdiagnostik.qmd) | die Frage lautet, ob ein Modell zulässig ist |\n| [Multiple lineare Regression](multiple-lineare-regression.qmd) | die Schätzung eines feststehenden Modells |\n| [Klassifikationsgüte](klassifikationsguete.qmd) | die Zielgrösse ist binär |\n| Regularisierung (Ridge, Lasso) | viele Prädiktoren im Verhältnis zu n; sie wählen und schätzen in einem Schritt |\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Geschachtelte Modelle vergleichen\n\n#### Frage und Datenlage\n\nLohnt sich `x2` zusätzlich zu `x1`? Und lohnen sich die sechs Grössen `z1` bis\n`z6` zusätzlich zu beiden? Beide Fragen betreffen geschachtelte Modelle, also\nist der F-Test anwendbar.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1   <- lm(y ~ x1, data = daten)\nm12  <- lm(y ~ x1 + x2, data = daten)\nmall <- lm(y ~ x1 + x2 + z1 + z2 + z3 + z4 + z5 + z6, data = daten)\n\nanova(m1, m12)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: y ~ x1\nModel 2: y ~ x1 + x2\n  Res.Df     RSS Df Sum of Sq      F    Pr(>F)    \n1    148 14004.1                                  \n2    147  5207.9  1    8796.2 248.28 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(m12, mall)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: y ~ x1 + x2\nModel 2: y ~ x1 + x2 + z1 + z2 + z3 + z4 + z5 + z6\n  Res.Df    RSS Df Sum of Sq      F  Pr(>F)  \n1    147 5207.9                              \n2    141 4824.2  6     383.7 1.8691 0.09018 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(r2_x1 = summary(m1)$r.squared,\n        r2_x1x2 = summary(m12)$r.squared,\n        r2_alle = summary(mall)$r.squared), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  r2_x1 r2_x1x2 r2_alle \n 0.6555  0.8719  0.8813 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nm1 = smf.ols(\"y ~ x1\", data=daten).fit()\nm12 = smf.ols(\"y ~ x1 + x2\", data=daten).fit()\nmall = smf.ols(\"y ~ x1 + x2 + z1 + z2 + z3 + z4 + z5 + z6\", data=daten).fit()\n\nprint(sm.stats.anova_lm(m1, m12).round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   df_resid         ssr  df_diff    ss_diff         F  Pr(>F)\n0     148.0  14004.1057      0.0        NaN       NaN     NaN\n1     147.0   5207.9344      1.0  8796.1713  248.2822     0.0\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(sm.stats.anova_lm(m12, mall).round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   df_resid        ssr  df_diff   ss_diff       F  Pr(>F)\n0     147.0  5207.9344      0.0       NaN     NaN     NaN\n1     141.0  4824.2336      6.0  383.7008  1.8691  0.0902\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"R^2:\", round(m1.rsquared, 4), round(m12.rsquared, 4),\n      round(mall.rsquared, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR^2: 0.6555 0.8719 0.8813\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Vergleich | F | df | p | Wie das zu lesen ist |\n|---|---|---|---|---|\n| `x1` gegen `x1 + x2` | 248.28 | 1 und 147 | < 0.001 | `x2` bringt einen massiven Gewinn. Die Residuenquadratsumme fällt von 14004 auf 5208. |\n| `x1 + x2` gegen alle acht | 1.869 | 6 und 141 | 0.090 | Die sechs Zusatzgrössen bringen **gemeinsam** nichts Nachweisbares, obwohl sie die Residuenquadratsumme rechnerisch weiter senken (von 5208 auf 4824). |\n\n| R² | Wert | Wie er zu lesen ist |\n|---|---|---|\n| `x1` | 0.6555 | |\n| `x1 + x2` | 0.8719 | |\n| alle acht | **0.8813** | Der höchste Wert, und trotzdem das schlechteste Modell. R² kann durch einen zusätzlichen Prädiktor nie sinken, auch nicht durch reines Rauschen. |\n\n::: {.note-box}\n**Warum der gemeinsame F-Test besser ist als sechs einzelne t-Tests.** In der\nKoeffiziententabelle des vollen Modells hat `z6` einen p-Wert von 0.051 und\n`z3` einen von 0.141. Wer die sechs einzeln ansieht und den kleinsten\nherausgreift, findet fast immer etwas: Bei sechs wirkungslosen Prädiktoren liegt\ndie Wahrscheinlichkeit, dass mindestens einer unter 0.05 fällt, bei rund 26\nProzent.\n\nDer F-Test prüft alle sechs in **einem** Test und beantwortet damit die Frage,\ndie tatsächlich interessiert: Bringt diese Gruppe zusammen etwas?\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Aufnahme von `x2` verbessert das Modell deutlich (F(1, 147) = 248.3,\n> p < 0.001). Die sechs weiteren Grössen bringen gemeinsam keinen nachweisbaren\n> Gewinn (F(6, 141) = 1.87, p = 0.090), obwohl R² von 0.872 auf 0.881 steigt.\n> Berichtet wird das Modell mit `x1` und `x2`.\n\n### Beispiel 2: AIC, BIC und adjustiertes R² im Vergleich\n\n#### Frage und Datenlage\n\nFünf Modelle, von leer bis voll besetzt. Welches wählt welches Kriterium? Und\nwelches ist das richtige? Letzteres ist hier bekannt: `x1 + x2`.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm0   <- lm(y ~ 1, data = daten)\nm12z <- lm(y ~ x1 + x2 + z1, data = daten)\n\nuebersicht <- data.frame(\n  modell = c(\"nur Achsenabschnitt\", \"x1\", \"x1 + x2\", \"x1 + x2 + z1\", \"alle acht\"),\n  parameter = c(1, 2, 3, 4, 9),\n  r2 = sapply(list(m0, m1, m12, m12z, mall), function(m) summary(m)$r.squared),\n  adj_r2 = sapply(list(m0, m1, m12, m12z, mall), function(m) summary(m)$adj.r.squared),\n  AIC = sapply(list(m0, m1, m12, m12z, mall), AIC),\n  BIC = sapply(list(m0, m1, m12, m12z, mall), BIC)\n)\nuebersicht[, 3:6] <- round(uebersicht[, 3:6], 4)\nuebersicht\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               modell parameter     r2 adj_r2       AIC       BIC\n1 nur Achsenabschnitt         1 0.0000 0.0000 1270.0127 1276.0340\n2                  x1         2 0.6555 0.6532 1112.1521 1121.1840\n3             x1 + x2         3 0.8719 0.8702  965.7771  977.8196\n4        x1 + x2 + z1         4 0.8748 0.8722  964.3622  979.4154\n5           alle acht         9 0.8813 0.8746  966.2973  996.4037\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"bestes nach AIC:\", uebersicht$modell[which.min(uebersicht$AIC)], \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbestes nach AIC: x1 + x2 + z1 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"bestes nach BIC:\", uebersicht$modell[which.min(uebersicht$BIC)], \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbestes nach BIC: x1 + x2 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"bestes nach adj. R2:\", uebersicht$modell[which.max(uebersicht$adj_r2)], \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbestes nach adj. R2: alle acht \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nm0 = smf.ols(\"y ~ 1\", data=daten).fit()\nm12z = smf.ols(\"y ~ x1 + x2 + z1\", data=daten).fit()\n\nmodelle = {\"nur Achsenabschnitt\": m0, \"x1\": m1, \"x1 + x2\": m12,\n           \"x1 + x2 + z1\": m12z, \"alle acht\": mall}\nuebersicht = pd.DataFrame({\n    \"parameter\": [int(m.df_model) + 1 for m in modelle.values()],\n    \"r2\": [m.rsquared for m in modelle.values()],\n    \"adj_r2\": [m.rsquared_adj for m in modelle.values()],\n    \"AIC\": [m.aic for m in modelle.values()],\n    \"BIC\": [m.bic for m in modelle.values()],\n}, index=list(modelle)).round(4)\nprint(uebersicht)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     parameter      r2  adj_r2        AIC        BIC\nnur Achsenabschnitt          1  0.0000  0.0000  1268.0127  1271.0233\nx1                           2  0.6555  0.6532  1110.1521  1116.1734\nx1 + x2                      3  0.8719  0.8702   963.7771   972.8090\nx1 + x2 + z1                 4  0.8748  0.8722   962.3622   974.4047\nalle acht                    9  0.8813  0.8746   964.2973   991.3931\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"bestes nach AIC:    \", uebersicht[\"AIC\"].idxmin())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbestes nach AIC:     x1 + x2 + z1\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"bestes nach BIC:    \", uebersicht[\"BIC\"].idxmin())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbestes nach BIC:     x1 + x2\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"bestes nach adj. R2:\", uebersicht[\"adj_r2\"].idxmax())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbestes nach adj. R2: alle acht\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Modell | Parameter | R² | adj. R² | AIC (Python) | AIC (R) | BIC (Python) | BIC (R) |\n|---|---|---|---|---|---|---|---|\n| nur Achsenabschnitt | 1 | 0.0000 | 0.0000 | 1268.01 | 1270.01 | 1271.02 | 1276.03 |\n| x1 | 2 | 0.6555 | 0.6532 | 1110.15 | 1112.15 | 1116.17 | 1121.18 |\n| **x1 + x2** (die Wahrheit) | 3 | 0.8719 | 0.8702 | 963.78 | 965.78 | **972.81** | **977.82** |\n| x1 + x2 + z1 | 4 | 0.8748 | 0.8722 | **962.36** | **964.36** | 974.40 | 979.42 |\n| alle acht | 9 | **0.8813** | **0.8746** | 964.30 | 966.30 | 991.39 | 996.40 |\n\nVier Kriterien, drei verschiedene Antworten:\n\n| Kriterium | Wahl | Urteil |\n|---|---|---|\n| R² | alle acht | Falsch, und zwar immer: R² wählt stets das grösste Modell. |\n| adjustiertes R² | alle acht | Ebenfalls falsch. Der Abzug je Parameter ist zu klein, um sechs wertlose Prädiktoren auszuschliessen. |\n| AIC | x1 + x2 + z1 | Fast richtig; es nimmt einen wertlosen Prädiktor mit. `z1` korreliert zufällig mit 0.22 mit `y`. |\n| **BIC** | **x1 + x2** | Richtig. Der strengere Abzug von $\\log(150) = 5.01$ je Parameter reicht aus. |\n\nDie AIC-Differenz zwischen `x1 + x2` und `x1 + x2 + z1` beträgt nur 1.42 und\nliegt damit unter der Schwelle von 2, ab der eine Differenz überhaupt beachtet\nwird. **Die beiden Modelle sind nach AIC praktisch gleichwertig**, und in einem\nsolchen Fall wählt man das kleinere.\n\n::: {.note-box}\n**Warum die absoluten Werte zwischen R und Python auseinandergehen.** R zählt\ndie Reststreuung $\\sigma$ als eigenen Parameter, statsmodels nicht. R addiert\ndeshalb $2 \\cdot 1 = 2$ beim AIC und $\\log(150) = 5.01$ beim BIC.\n\nDie Differenzen zwischen Modellen sind davon nicht betroffen, und nur sie\nzählen. Wer AIC-Werte aus zwei Programmen nebeneinanderstellt, muss trotzdem\nwissen, dass die Reihen gegeneinander verschoben sind.\n:::\n\n#### Interpretation und Ergebnissatz\n\nDie Reihenfolge der Strenge lautet: R² < adjustiertes R² < AIC < BIC. Welches\ndavon passt, hängt am Ziel. Wer vorhersagen will, ist mit AIC besser bedient;\nwer die tatsächlich wirksamen Grössen finden will, mit BIC. Dass BIC hier die\nWahrheit trifft, ist kein Zufall, aber auch keine Garantie: Bei kleinerem n oder\nschwächeren Effekten übersieht BIC auch echte Prädiktoren.\n\n> Verglichen wurden fünf geschachtelte Modelle auf denselben 150 Beobachtungen.\n> BIC wählt `x1 + x2` (972.8; nächstbestes Modell 974.4), AIC wählt\n> `x1 + x2 + z1` (962.4), liegt damit aber nur 1.42 unter `x1 + x2` und ist\n> damit praktisch gleichwertig. Gewählt wurde `x1 + x2`.\n\n### Beispiel 3: Schrittweise Auswahl\n\n#### Frage und Datenlage\n\nEin verbreitetes Verfahren: Man startet mit allen acht Prädiktoren und entfernt\nschrittweise jenen, dessen Wegfall den AIC am stärksten senkt, bis keine\nVerbesserung mehr möglich ist. Findet es die Wahrheit?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngewaehlt <- step(mall, direction = \"backward\", trace = 0)\nformula(gewaehlt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ny ~ x1 + x2 + z1 + z3 + z6\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(gewaehlt)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Estimate Std. Error    t value     Pr(>|t|)\n(Intercept) 95.0898498 3.12635031  30.415609 1.463745e-64\nx1           2.6636392 0.09838869  27.072616 2.339494e-58\nx2          -0.7672567 0.04801305 -15.980169 1.049163e-33\nz1           0.8063556 0.49123003   1.641503 1.028753e-01\nz3          -0.7348353 0.48265875  -1.522474 1.300834e-01\nz6           0.9443364 0.48040918   1.965692 5.125793e-02\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nkandidaten = [\"x1\", \"x2\"] + [f\"z{k}\" for k in range(1, 7)]\naktuell = list(kandidaten)\n\nwhile True:\n    jetzt = smf.ols(\"y ~ \" + \" + \".join(aktuell), data=daten).fit()\n    beste_aic, beste_var = jetzt.aic, None\n    for kandidat in aktuell:\n        rest = [v for v in aktuell if v != kandidat]\n        formel = \"y ~ \" + (\" + \".join(rest) if rest else \"1\")\n        aic = smf.ols(formel, data=daten).fit().aic\n        if aic < beste_aic:\n            beste_aic, beste_var = aic, kandidat\n    if beste_var is None:\n        break\n    print(f\"entferne {beste_var}: AIC {jetzt.aic:.2f} -> {beste_aic:.2f}\")\n    aktuell.remove(beste_var)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nentferne z5: AIC 964.30 -> 962.59\nentferne z2: AIC 962.59 -> 961.09\nentferne z4: AIC 961.09 -> 960.31\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"gewählt:\", aktuell)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngewählt: ['x1', 'x2', 'z1', 'z3', 'z6']\n```\n\n\n:::\n\n```{.python .cell-code}\ngewaehlt = smf.ols(\"y ~ \" + \" + \".join(aktuell), data=daten).fit()\nprint(gewaehlt.summary().tables[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n==============================================================================\n                 coef    std err          t      P>|t|      [0.025      0.975]\n------------------------------------------------------------------------------\nIntercept     95.0898      3.126     30.416      0.000      88.910     101.269\nx1             2.6636      0.098     27.073      0.000       2.469       2.858\nx2            -0.7673      0.048    -15.980      0.000      -0.862      -0.672\nz1             0.8064      0.491      1.642      0.103      -0.165       1.777\nz3            -0.7348      0.483     -1.522      0.130      -1.689       0.219\nz6             0.9443      0.480      1.966      0.051      -0.005       1.894\n==============================================================================\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Schritt | Entfernt | AIC (Python) |\n|---|---|---|\n| Start | | 964.30 |\n| 1 | z5 | 962.59 |\n| 2 | z2 | 961.09 |\n| 3 | z4 | 960.31 |\n| Ende | | gewählt: `x1`, `x2`, `z1`, `z3`, `z6` |\n\nDas Verfahren behält **drei** der sechs wertlosen Prädiktoren. Und es sieht\ndabei völlig plausibel aus: Jeder Schritt senkt den AIC, das Verfahren\nkonvergiert, und am Ende steht ein Modell mit fünf Prädiktoren, von denen die\nmeisten einen kleinen p-Wert haben.\n\n::: {.note-box}\n**Warum die p-Werte im gewählten Modell nicht mehr gelten.** Ein p-Wert\nbeantwortet die Frage: Wie wahrscheinlich wäre dieser Koeffizient, wenn der\nPrädiktor wirkungslos wäre und ich ihn **vorab** ausgewählt hätte? Bei\nschrittweiser Auswahl ist die zweite Bedingung verletzt. Die Prädiktoren sind\ngerade deshalb im Modell, weil sie in **diesen** Daten gut aussahen.\n\nDie Folge: Die p-Werte sind systematisch zu klein, die Konfidenzintervalle zu\nschmal, und die Koeffizienten sind vom Betrag her zu gross. In der Literatur\nheisst das Problem \"selection bias\" oder \"the winner's curse\". Es verschwindet\nnicht dadurch, dass man ein anderes Auswahlkriterium nimmt.\n:::\n\n#### Interpretation und Ergebnissatz\n\nWas daraus folgt, ist keine Verurteilung der schrittweisen Auswahl, sondern eine\nEinschränkung ihres Einsatzbereichs:\n\n| Zweck | Schrittweise Auswahl geeignet? |\n|---|---|\n| Ein Vorhersagemodell aus vielen Kandidaten bauen | bedingt, und nur mit Bewertung auf getrennten Daten |\n| Herausfinden, welche Grössen wirken | nein |\n| p-Werte und Intervalle berichten | nein, jedenfalls nicht ohne Korrektur |\n| Ein vorab begründetes Modell prüfen | die Frage stellt sich nicht |\n\nDer saubere Weg für die zweite Zeile ist: Kandidaten aus dem Fachwissen ableiten,\ndas Modell vorab festlegen, und die Auswahl gar nicht erst den Daten überlassen.\nWo das nicht geht, sind Regularisierungsverfahren wie Lasso die bessere Wahl,\nweil sie Auswahl und Schätzung in einem Schritt vornehmen und den Schrumpfeffekt\neinrechnen.\n\n> Eine rückwärts gerichtete schrittweise Auswahl nach AIC wählt `x1`, `x2`,\n> `z1`, `z3` und `z6`, also drei der sechs konstruktionsbedingt wirkungslosen\n> Grössen. Die p-Werte dieses Modells sind wegen der datengetriebenen Auswahl\n> nicht als Signifikanzaussagen zu lesen.\n\n### Beispiel 4: Kreuzvalidierung als Schiedsrichter\n\n#### Frage und Datenlage\n\nAIC und BIC schätzen die Vorhersagegüte über eine Formel. Die Kreuzvalidierung\nmisst sie direkt: Das Modell wird auf einem Teil der Daten geschätzt und auf dem\nzurückgehaltenen Teil geprüft, und das für jeden Teil einmal.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncv_fehler <- function(spalten, k = 5) {\n  formel <- as.formula(paste(\"y ~\", if (length(spalten)) paste(spalten, collapse = \" + \") else \"1\"))\n  quadrate <- sapply(0:(k - 1), function(teil) {\n    ist_test <- (seq_len(nrow(daten)) - 1) %% k == teil\n    modell <- lm(formel, data = daten[!ist_test, ])\n    mean((daten$y[ist_test] - predict(modell, newdata = daten[ist_test, ]))^2)\n  })\n  sqrt(mean(quadrate))\n}\n\nkandidatenlisten <- list(\n  \"nur Achsenabschnitt\" = character(0),\n  \"x1\" = \"x1\",\n  \"x1 + x2\" = c(\"x1\", \"x2\"),\n  \"x1 + x2 + z1\" = c(\"x1\", \"x2\", \"z1\"),\n  \"alle acht\" = c(\"x1\", \"x2\", paste0(\"z\", 1:6))\n)\n\nround(sapply(kandidatenlisten, cv_fehler), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnur Achsenabschnitt                  x1             x1 + x2        x1 + x2 + z1 \n            16.4752              9.6976              5.9398              5.8967 \n          alle acht \n             6.4145 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndef cv_fehler(spalten, k=5):\n    formel = \"y ~ \" + (\" + \".join(spalten) if spalten else \"1\")\n    quadrate = []\n    for teil in range(k):\n        ist_test = np.arange(len(daten)) % k == teil\n        modell = smf.ols(formel, data=daten[~ist_test]).fit()\n        rest = daten.loc[ist_test, \"y\"] - modell.predict(daten[ist_test])\n        quadrate.append(np.mean(rest ** 2))\n    return np.sqrt(np.mean(quadrate))\n\n\nkandidatenlisten = {\n    \"nur Achsenabschnitt\": [],\n    \"x1\": [\"x1\"],\n    \"x1 + x2\": [\"x1\", \"x2\"],\n    \"x1 + x2 + z1\": [\"x1\", \"x2\", \"z1\"],\n    \"alle acht\": [\"x1\", \"x2\"] + [f\"z{k}\" for k in range(1, 7)],\n}\nfor name, spalten in kandidatenlisten.items():\n    print(f\"{name:22s} {cv_fehler(spalten):.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnur Achsenabschnitt    16.4752\nx1                     9.6976\nx1 + x2                5.9398\nx1 + x2 + z1           5.8967\nalle acht              6.4145\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Modell | Kreuzvalidierungsfehler | Residualstreuung im Gesamtmodell | Wie das zu lesen ist |\n|---|---|---|---|\n| nur Achsenabschnitt | 16.475 | 16.518 | Der Bezugswert: die blosse Streuung von `y`. |\n| x1 | 9.698 | 9.727 | Deutliche Verbesserung. |\n| x1 + x2 | 5.940 | 5.952 | Nochmals deutlich besser. |\n| x1 + x2 + z1 | **5.897** | 5.905 | Minimal besser, dieselbe Wahl wie beim AIC. |\n| alle acht | 6.414 | **5.849** | **Der entscheidende Vergleich.** Auf den eigenen Daten ist dieses Modell das beste (5.849), auf zurückgehaltenen Daten das zweitschlechteste (6.414). |\n\nDie letzte Zeile zeigt Überanpassung in Reinform. Die sechs wertlosen\nPrädiktoren senken die Residualstreuung im Gesamtmodell, weil sie sich an das\nRauschen dieser 150 Fälle anpassen. Auf Fälle, die das Modell nicht gesehen hat,\nüberträgt sich davon nichts, im Gegenteil: Der Fehler steigt um rund 9 Prozent\ngegenüber dem sparsamen Modell.\n\nBemerkenswert ist auch, wie nah die Kreuzvalidierungsfehler bei den sparsamen\nModellen an der Residualstreuung liegen (5.940 gegen 5.952). Solange ein Modell\nnicht überangepasst ist, schätzt die Residualstreuung den Vorhersagefehler\nbrauchbar; die Schere öffnet sich erst mit der Anzahl der Parameter.\n\n::: {.note-box}\nDer Kreuzvalidierungsfehler hängt an der Aufteilung. Hier ist sie\ndeterministisch (jeder fünfte Fall bildet einen Teil), damit die Zahlen\nnachprüfbar bleiben. In der Praxis wird zufällig aufgeteilt und die\nKreuzvalidierung mehrfach wiederholt, weil einzelne Aufteilungen bei kleinen\nDatensätzen merklich schwanken.\n:::\n\n#### Interpretation und Ergebnissatz\n\nDie Kreuzvalidierung ist die direkteste Antwort auf die Frage nach der\nVorhersagegüte, weil sie sie misst statt schätzt. Ihr Preis ist Rechenzeit und\ndie Abhängigkeit von der Aufteilung.\n\nBemerkenswert ist die Übereinstimmung mit dem AIC: Beide wählen\n`x1 + x2 + z1`, und bei beiden ist der Vorsprung vor `x1 + x2` winzig. Das ist\nkein Zufall, sondern eine bekannte Eigenschaft: AIC ist asymptotisch äquivalent\nzur Kreuzvalidierung mit einem zurückgehaltenen Fall. Wer eines von beiden\ngerechnet hat, gewinnt durch das andere selten neue Erkenntnisse.\n\n> Eine fünffache Kreuzvalidierung bestätigt die Auswahl: Der Vorhersagefehler\n> beträgt 5.94 für `x1 + x2` und 5.90 für `x1 + x2 + z1`, während das Modell mit\n> allen acht Prädiktoren trotz kleinster Residualstreuung (5.85) den höchsten\n> Kreuzvalidierungsfehler der ernsthaften Kandidaten aufweist (6.41). Gewählt\n> wurde `x1 + x2`.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEin Modell mit sechs zusätzlichen, wirkungslosen Prädiktoren hat das höchste\nadjustierte R². Was folgt daraus?\n\n- [x] Das adjustierte R² ist als alleiniges Auswahlkriterium zu nachsichtig ~\n      Richtig. Sein Abzug je Parameter ist klein; er reicht oft nicht, um\n      wertlose Prädiktoren auszuschliessen. AIC ist strenger, BIC deutlich\n      strenger.\n- [ ] Die sechs Prädiktoren wirken doch ~ In diesem Beispiel ist die Wahrheit\n      bekannt: Sie sind konstruktionsbedingt wirkungslos.\n- [ ] Das adjustierte R² wurde falsch berechnet ~ Es ist korrekt berechnet, nur\n      für diesen Zweck ungeeignet.\n:::\n\n::: {.quiz}\nZwei Modelle unterscheiden sich im AIC um 1.4. Welches wird gewählt?\n\n- [x] Das kleinere, denn eine Differenz unter 2 ist kaum bedeutsam ~ Richtig.\n      Bei praktisch gleichwertigen Modellen entscheidet die Sparsamkeit. Erst ab\n      einer Differenz von etwa 4 spricht der AIC deutlich für ein Modell.\n- [ ] Das mit dem kleineren AIC, egal wie klein der Abstand ist ~ Damit würde\n      man systematisch grössere Modelle wählen, weil zufällige Schwankungen\n      immer irgendeinen Vorteil erzeugen.\n- [ ] Keines, die Entscheidung braucht einen Test ~ AIC-Differenzen sind keine\n      Testgrössen; ein p-Wert gehört nicht dazu.\n:::\n\n::: {.quiz}\nNach schrittweiser Auswahl hat ein Prädiktor p = 0.01. Wie ist das zu deuten?\n\n- [x] Gar nicht als Signifikanzaussage; der Prädiktor wurde anhand derselben\n      Daten ausgewählt ~ Richtig. Der p-Wert unterstellt, dass die Frage vorab\n      feststand. Bei datengetriebener Auswahl sind p-Werte zu klein,\n      Intervalle zu schmal und Koeffizienten zu gross.\n- [ ] Als gewöhnlicher p-Wert, die Auswahl ändert daran nichts ~ Sie ändert\n      genau die Bedingung, unter der der p-Wert definiert ist.\n- [ ] Er müsste mit der Anzahl der Schritte multipliziert werden ~ Eine so\n      einfache Korrektur gibt es nicht; das Problem ist grundsätzlicher.\n:::\n\n::: {.quiz}\nEin Modell hat die kleinste Residualstreuung und zugleich den höchsten\nKreuzvalidierungsfehler. Was liegt vor?\n\n- [x] Überanpassung ~ Richtig. Das Modell passt sich dem Rauschen der\n      vorliegenden Daten an, was die Residualstreuung senkt, aber auf neue Fälle\n      nicht übertragbar ist. Genau dafür ist die Kreuzvalidierung da.\n- [ ] Ein Rechenfehler, beide Masse müssten in dieselbe Richtung zeigen ~ Sie\n      zeigen bei sparsamen Modellen in dieselbe Richtung und laufen mit\n      wachsender Parameterzahl auseinander.\n- [ ] Die Aufteilung der Kreuzvalidierung ist ungünstig gewählt ~ Möglich bei\n      kleinen Unterschieden, aber nicht bei einem so deutlichen Muster.\n:::\n\n## Verlinkte Ressourcen\n\n- [An Introduction to Statistical Learning, Kapitel 6](https://www.statlearning.com/)\n- [R-Dokumentation zu `step`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/step.html)\n- [Regressionsdiagnostik](regressionsdiagnostik.qmd)\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}