{
  "hash": "7681380c4f1aa6a1a9f6834e9b2ac86d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Zielbild und Publikum\"\ndescription: \"Zweck, Publikum und der Unterschied zwischen explorativ und erklärend.\"\ncategories: [\"Visualisierung\", \"Kommunikation\", \"R\", \"Python\"]\nquelle: [\"DAVI\"]\nseitentyp: konzept\nstand: fertig\norder: 10\n---\n\n\n\n\n\n## Kernideen\n\n- Vor dem Diagrammtyp steht die Frage, welche **Entscheidung** die Grafik\n  stützen soll.\n- Explorativ und erklärend sind zwei verschiedene Aufgaben mit verschiedenen\n  Regeln und beim Explorieren entstehen zwangsläufig Scheinbefunde.\n- Das Publikum entscheidet über Vorwissen, Detailtiefe und Fachbegriffe.\n- Eine Grafik ohne Aussage ist eine Ausgabe, keine Darstellung.\n- Misslungen ist nicht gleich misslungen: **hässlich, schlecht gelesen oder\n  schlicht falsch**, mit sehr verschiedener Dringlichkeit.\n- Der Titel trägt die Aussage, nicht die Beschreibung der Achsen, aber nur,\n  wenn die Daten die Aussage decken.\n\n## Erklärung\n\n::: {.note-box}\nDiese Seite steht bewusst vor den Werkzeugen. Was danach kommt, ist die\n[Wahrnehmung](wahrnehmung-kodierung.qmd) und daraus die\n[Wahl des Diagrammtyps](diagrammtyp-waehlen.qmd).\n:::\n\n### Die Frage vor der Grafik\n\nJede brauchbare Visualisierung beginnt mit einem Satz, der nichts mit\nDiagrammen zu tun hat: **Welche Entscheidung soll gestützt werden, und wer\ntrifft sie?** Erst daraus folgt, was gezeigt werden muss, wie genau es ablesbar\nsein muss und was weggelassen werden darf.\n\nOhne diesen Satz entsteht die häufigste Sorte Grafik: technisch korrekt,\nhübsch, und niemand weiss, was er damit tun soll.\n\nDrei Fragen genügen als Vorbereitung:\n\n1. **Entscheidung:** Was soll jemand nach dem Ansehen anders machen als vorher?\n2. **Publikum:** Wer sieht die Grafik, mit welchem Vorwissen, in welcher\n   Situation, mit wie viel Zeit?\n3. **Aussage:** Welcher Satz steht am Ende darüber? Wenn er nicht formulierbar\n   ist, fehlt noch etwas.\n\nDerselbe Datensatz trägt dabei **verschiedene** Aussagen, und jede verlangt eine\nandere Grafik, Beispiel 1 zeigt drei davon.\n\n### Explorativ oder erklärend\n\nDas ist der Unterschied, der am häufigsten übersehen wird, weil beide Sorten\ngleich aussehen können.\n\n| | Explorativ | Erklärend |\n|---|---|---|\n| Zweck | selbst verstehen, Muster finden | anderen etwas zeigen |\n| Publikum | man selbst | jemand anderes |\n| Anzahl | viele, schnell, wegwerfbar | wenige, sorgfältig |\n| Beschriftung | minimal, man kennt die Daten | vollständig, mit Einheit und Quelle |\n| Auswahl | alles ansehen, auch Sackgassen | eine Aussage, alles andere weg |\n| Zeitbudget je Grafik | Sekunden | Stunden |\n\nDer teure Fehler ist, eine explorative Grafik unverändert in einen Bericht zu\nübernehmen. Sie ist für jemanden gemacht, der die Daten bereits kennt, und\nlässt das Publikum genau die Arbeit tun, die man ihm hätte abnehmen sollen.\n\nDazu kommt ein zweiter, weniger bekannter Grund: Beim Explorieren sieht man\n**viele** Grafiken, und einige davon zeigen ein Muster, das nur Rauschen ist.\nBeispiel 2 zählt nach, wie viele.\n\n### Das Publikum kennen heisst drei Dinge festlegen\n\n- **Vorwissen:** Welche Begriffe sind bekannt? Ein Boxplot ist für Fachleute\n  ein Standard und für viele andere ein Rätsel.\n- **Detailtiefe:** Braucht das Publikum den einzelnen Wert oder das Muster? Ein\n  Vorstand liest keine Tabelle mit 40 Zeilen, eine Fachgruppe schon.\n- **Situation:** Wird die Grafik projiziert, gedruckt, am Bildschirm gelesen?\n  Davon hängen Schriftgrösse, Anzahl Elemente und Farbwahl ab.\n\n### Hässlich, schlecht gelesen, falsch\n\nNicht jede misslungene Grafik ist auf dieselbe Weise misslungen, und die\nUnterscheidung bestimmt, wie dringend die Korrektur ist.\n\n| Art | Was passiert | Beispiel | Dringlichkeit |\n|---|---|---|---|\n| Hässlich | korrekt und lesbar, aber ungestaltet | Standarddiagramm mit Gitterlinien und Legende in Grau | kosmetisch |\n| Schlecht gelesen | korrekt, aber die Wahrnehmung liest es falsch oder mühsam | Tortendiagramm mit zwölf Segmenten, dreidimensionale Säulen | ernst, weil das Publikum sich täuscht |\n| Falsch | die Zahlen, die Skalierung oder die Geometrie stimmen nicht | Balkenachse beginnt bei 90, Fläche nach dem Radius skaliert | sofort, denn die Aussage ist unwahr |\n\nDie mittlere Kategorie ist die gefährlichste, weil sie unauffällig ist: Es\nsteht nichts Falsches da, und trotzdem nimmt das Publikum etwas Falsches mit.\nDie Beispiele dazu stehen unter\n[irreführende Darstellungen](irrefuehrende-darstellungen.qmd).\n\n### Der Titel gehört der Aussage\n\nEin Titel wie \"Umsatz nach Region 2026\" beschreibt, was zu sehen ist, und\nverschenkt die wirksamste Zeile der Grafik. Wer stattdessen die Aussage\nhinschreibt, nimmt dem Publikum die Deutungsarbeit ab:\n\n| Statt | Besser |\n|---|---|\n| \"Umsatz nach Region 2026\" | \"Der Umsatz wächst nur im Süden\" |\n| \"Ausschussquote je Maschine\" | \"Maschine 3 verursacht zwei Drittel des Ausschusses\" |\n| \"Antwortzeiten\" | \"Seit dem Update antwortet das System doppelt so schnell\" |\n\nDie Bedingung dafür ist, dass die Aussage stimmt und die Grafik sie trägt. Ein\nAussagetitel über einer Grafik, die etwas anderes zeigt, ist schlimmer als ein\nbeschreibender, Beispiel 3 prüft drei Titel gegen dieselben Daten.\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Dieselben Daten, drei Aussagen\n\n#### Frage und Datenlage\n\nVier Regionen über 24 Monate. Drei verschiedene Entscheidungen wollen gestützt\nwerden und jede braucht eine andere Grafik, obwohl die Daten dieselben sind.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregionen <- c(\"Nord\", \"Sued\", \"Ost\", \"West\")\nZ <- normalmatrix(4711, 4, 24)\nzeit <- 0:23\nniveau <- c(120, 60, 95, 80)\ntrend <- c(0.0, 1.2, -0.15, 0.1)\ndaten <- niveau + trend %o% zeit + Z * 6   # 4 Zeilen, 24 Spalten\n\nkennzahlen <- t(sapply(1:4, function(i) {\n  y <- daten[i, ]\n  m <- lm(y ~ zeit)\n  c(mittel = mean(y), sd = sd(y), steigung = unname(coef(m)[2]))\n}))\nrownames(kennzahlen) <- regionen\nround(kennzahlen, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      mittel    sd steigung\nNord 121.126 5.197    0.084\nSued  73.634 9.747    1.258\nOst   95.110 6.436   -0.197\nWest  81.192 6.682   -0.208\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(groesste_region_mittel = max(kennzahlen[, \"mittel\"]),\n        anteil_sued_monat_1 = daten[2, 1] / sum(daten[, 1]) * 100,\n        anteil_sued_monat_24 = daten[2, 24] / sum(daten[, 24]) * 100), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngroesste_region_mittel    anteil_sued_monat_1   anteil_sued_monat_24 \n                 121.1                   16.6                   24.3 \n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 3), mar = c(4, 4, 3, 1))\n# Aussage 1: Wer ist am groessten?\nbarplot(sort(kennzahlen[, \"mittel\"]), horiz = TRUE, las = 1, col = neutral,\n        border = NA, main = \"1: Wer ist am grössten?\", xlab = \"Umsatz\")\n# Aussage 2: Wer waechst?\nmatplot(zeit, t(daten), type = \"l\", lty = 1, lwd = 1.6,\n        col = c(neutral, akzent, neutral, neutral),\n        xlab = \"Monat\", ylab = \"Umsatz\", main = \"2: Wer wächst?\")\n# Aussage 3: Wie verschiebt sich der Anteil?\nanteile <- prop.table(daten, margin = 2) * 100\nplot(zeit, anteile[2, ], type = \"l\", lwd = 2, col = akzent, ylim = c(0, 40),\n     xlab = \"Monat\", ylab = \"Anteil Süd in Prozent\",\n     main = \"3: Wie verschiebt sich der Anteil?\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselben Daten für drei Aussagen.](zielbild-audience_files/figure-html/fig-b1-zb-r-1.png){#fig-b1-zb-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nregionen = [\"Nord\", \"Sued\", \"Ost\", \"West\"]\nZ = normalmatrix(4711, 4, 24)\nzeit = np.arange(24)\nniveau = np.array([120., 60., 95., 80.])\ntrend = np.array([0.0, 1.2, -0.15, 0.1])\ndaten = niveau[:, None] + trend[:, None] * zeit + Z * 6\n\nkennzahlen = pd.DataFrame(\n    [{\"mittel\": daten[i].mean(), \"sd\": daten[i].std(ddof=1),\n      \"steigung\": np.polyfit(zeit, daten[i], 1)[0]} for i in range(4)],\n    index=regionen)\nprint(kennzahlen.round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       mittel     sd  steigung\nNord  121.126  5.197     0.084\nSued   73.634  9.747     1.258\nOst    95.110  6.436    -0.197\nWest   81.192  6.682    -0.208\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"groesste_region_mittel\": round(float(kennzahlen[\"mittel\"].max()), 1),\n       \"anteil_sued_monat_1\": round(float(daten[1, 0] / daten[:, 0].sum() * 100), 1),\n       \"anteil_sued_monat_24\": round(float(daten[1, -1] / daten[:, -1].sum() * 100), 1)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'groesste_region_mittel': 121.1, 'anteil_sued_monat_1': 16.6, 'anteil_sued_monat_24': 24.3}\n```\n\n\n:::\n\n```{.python .cell-code}\nanteile = daten / daten.sum(axis=0) * 100\n\nfig, achsen = plt.subplots(1, 3, figsize=(7, 3.2))\nsortiert = kennzahlen[\"mittel\"].sort_values()\n_ = achsen[0].barh(sortiert.index, sortiert.to_numpy(), color=NEUTRAL)\n_ = achsen[0].set_title(\"1: Wer ist am grössten?\", fontsize=10)\n_ = achsen[0].set_xlabel(\"Umsatz\")\nfor i in range(4):\n    _ = achsen[1].plot(zeit, daten[i], lw=1.6,\n                       color=AKZENT if i == 1 else NEUTRAL)\n_ = achsen[1].set_title(\"2: Wer wächst?\", fontsize=10)\n_ = achsen[1].set_xlabel(\"Monat\")\n_ = achsen[1].set_ylabel(\"Umsatz\")\n_ = achsen[2].plot(zeit, anteile[1], lw=2, color=AKZENT)\n_ = achsen[2].set_ylim(0, 40)\n_ = achsen[2].set_title(\"3: Wie verschiebt sich der Anteil?\", fontsize=10)\n_ = achsen[2].set_xlabel(\"Monat\")\n_ = achsen[2].set_ylabel(\"Anteil Süd in Prozent\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselben drei Grafiken in Python.](zielbild-audience_files/figure-html/fig-b1-zb-py-1.png){#fig-b1-zb-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Region | Mittel | SD | Steigung je Monat |\n|---|---|---|---|\n| **Nord** | **121.1** | 5.20 | +0.084 |\n| Sued | 73.6 | 9.75 | **+1.258** |\n| Ost | 95.1 | 6.44 | −0.197 |\n| West | 81.2 | 6.68 | −0.208 |\n\n| Aussage | Kennzahl | Passende Grafik |\n|---|---|---|\n| \"Nord ist die grösste Region\" | Mittel **121.1** gegen 73.6 bis 95.1 | sortierter Balken |\n| \"Nur der Süden wächst\" | Steigung **+1.258** gegen −0.21 bis +0.08 | Linien, Süd hervorgehoben |\n| \"Der Süden holt auf\" | Anteil von **16.6** auf **24.3 Prozent** | eine Linie, der Anteil |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Alle drei Aussagen stimmen | Und sie stehen nicht im Widerspruch. Nord ist gross und wächst nicht, Süd ist klein und wächst. |\n| Jede braucht eine **andere** Grafik | Der sortierte Balken zeigt die erste und verbirgt die zweite, weil er die Zeit wegmittelt. Die Liniengrafik zeigt die zweite und macht die erste mühsam. Die Anteilskurve zeigt die dritte und keine der beiden anderen. |\n| Die dritte Grafik enthält **eine einzige Linie** | Aus 96 Zahlen wird eine Kurve mit 24 Punkten. Das ist keine Verarmung, sondern die Antwort auf die gestellte Frage. |\n| Ohne die Frage gäbe es **keinen Grund**, eine davon zu wählen | Genau deshalb steht die Frage vor der Grafik und nicht danach. |\n| Die Alternative wäre, **alle drei** zu zeigen | Zulässig, wenn wirklich drei Entscheidungen anstehen. Meistens steht aber eine an, und die anderen zwei kosten nur Aufmerksamkeit. |\n\n::: {.note-box}\n**Die Probe:** Wenn sich der Titel der Grafik nicht ändert, sobald man die\nGrafik austauscht, war der Titel nie eine Aussage. \"Umsatz nach Region\" passt\nüber alle drei Bilder und sagt bei keinem, was zu sehen ist.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Aus denselben 96 Werten folgen drei zutreffende Aussagen: Nord ist mit einem\n> Mittel von 121.1 die grösste Region, Süd wächst als einzige mit +1.258 je\n> Monat, und Süds Anteil steigt von 16.6 auf 24.3 Prozent. Jede verlangt eine\n> andere Grafik.\n\n### Beispiel 2: Was beim Explorieren zwangsläufig passiert\n\n#### Frage und Datenlage\n\nZehn Variablen, 200 Beobachtungen, **alle voneinander unabhängig** erzeugt. Wer\nsie explorativ paarweise ansieht, betrachtet 45 Streudiagramme. Wie viele davon\nzeigen ein Muster?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_var <- 10; n <- 200\nX <- normalmatrix(1234, p_var, n)\n\npaare <- t(combn(p_var, 2))\nergebnis <- data.frame(\n  a = paare[, 1], b = paare[, 2],\n  r = apply(paare, 1, function(k) cor(X[k[1], ], X[k[2], ])))\nergebnis$p <- 2 * pt(abs(ergebnis$r) * sqrt((n - 2) / (1 - ergebnis$r^2)),\n                     n - 2, lower.tail = FALSE)\n\nc(variablen = p_var, paare = nrow(ergebnis), beobachtungen = n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    variablen         paare beobachtungen \n           10            45           200 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(signifikant_bei_0.05 = sum(ergebnis$p < 0.05),\n        erwartet = nrow(ergebnis) * 0.05,\n        bonferroni_schwelle = 0.05 / nrow(ergebnis),\n        signifikant_nach_bonferroni = sum(ergebnis$p < 0.05 / nrow(ergebnis))), 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       signifikant_bei_0.05                    erwartet \n                    3.00000                     2.25000 \n        bonferroni_schwelle signifikant_nach_bonferroni \n                    0.00111                     0.00000 \n```\n\n\n:::\n\n```{.r .cell-code}\nbestes <- ergebnis[which.max(abs(ergebnis$r)), ]\nround(bestes, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   a b      r      p\n27 4 7 0.1849 0.0088\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mar = c(4, 4, 3, 1))\nplot(X[bestes$a, ], X[bestes$b, ], pch = 16, col = adjustcolor(\"grey25\", 0.6),\n     xlab = paste(\"Variable\", bestes$a), ylab = paste(\"Variable\", bestes$b),\n     main = sprintf(\"r = %.4f, p = %.4f und doch nur Rauschen\",\n                    bestes$r, bestes$p))\nabline(lm(X[bestes$b, ] ~ X[bestes$a, ]), lwd = 2, col = akzent)\n```\n\n::: {.cell-output-display}\n![Beispiel 2: das auffälligste der 45 Paare, reines Rauschen.](zielbild-audience_files/figure-html/fig-b2-zb-r-3.png){#fig-b2-zb-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\np_var, n = 10, 200\nX = normalmatrix(1234, p_var, n)\n\npaare = list(itertools.combinations(range(p_var), 2))\nergebnis = pd.DataFrame([{\"a\": i + 1, \"b\": j + 1,\n                          \"r\": np.corrcoef(X[i], X[j])[0, 1]}\n                         for i, j in paare])\nergebnis[\"p\"] = 2 * stats.t.sf(\n    ergebnis[\"r\"].abs() * np.sqrt((n - 2) / (1 - ergebnis[\"r\"] ** 2)), n - 2)\n\nprint({\"variablen\": p_var, \"paare\": len(ergebnis), \"beobachtungen\": n})\nprint({\"signifikant_bei_0.05\": int((ergebnis[\"p\"] < 0.05).sum()),\n       \"erwartet\": len(ergebnis) * 0.05,\n       \"bonferroni_schwelle\": round(0.05 / len(ergebnis), 5),\n       \"signifikant_nach_bonferroni\":\n           int((ergebnis[\"p\"] < 0.05 / len(ergebnis)).sum())})\n\nbestes = ergebnis.loc[ergebnis[\"r\"].abs().idxmax()]\nprint(bestes.round(4))\n\ni, j = int(bestes[\"a\"]) - 1, int(bestes[\"b\"]) - 1\nfig, achse = plt.subplots(figsize=(7, 3))\n_ = achse.scatter(X[i], X[j], s=14, color=\"0.25\", alpha=0.6)\nk, d = np.polyfit(X[i], X[j], 1)\ngitter = np.linspace(X[i].min(), X[i].max(), 2)\n_ = achse.plot(gitter, k * gitter + d, lw=2, color=AKZENT)\n_ = achse.set_xlabel(f\"Variable {i + 1}\")\n_ = achse.set_ylabel(f\"Variable {j + 1}\")\n_ = achse.set_title(f\"r = {bestes['r']:.4f}, p = {bestes['p']:.4f}\"\n                    \" und doch nur Rauschen\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dasselbe Paar in Python.](zielbild-audience_files/figure-html/fig-b2-zb-py-1.png){#fig-b2-zb-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | Wert |\n|---|---|\n| Variablen | 10 |\n| paarweise Streudiagramme | **45** |\n| Beobachtungen je Variable | 200 |\n| Paare mit p < 0.05 | **3** |\n| davon zu erwarten | **2.25** |\n| Bonferroni-Schwelle | 0.00111 |\n| Paare, die diese Schwelle unterschreiten | **0** |\n\nDas auffälligste Paar: Variable 4 gegen 7, **r = 0.1849**, **p = 0.0088**.\n\n| Beobachtung | Erklärung |\n|---|---|\n| Drei von 45 Paaren sind \"signifikant\" | Bei **konstruierter Unabhängigkeit**. Es gibt keinen einzigen echten Zusammenhang in diesen Daten. |\n| Und das ist genau die **Erwartung** | 45 × 0.05 = 2.25. Drei Treffer sind kein Ausreisser, sondern der Normalfall. |\n| Nach Bonferroni bleibt **kein einziges** übrig | Die Korrektur tut genau das, wofür sie da ist. Siehe [multiples Testen](../statistik/inferenz/multiples-testen.qmd). |\n| Das stärkste Paar hat r = **0.1849** | Im Streudiagramm mit Regressionsgerade sieht das nach einem schwachen, aber vorhandenen Zusammenhang aus. Es ist keiner. |\n| **Darum ist Explorieren keine Ergebnisproduktion** | Die 45 Grafiken sind richtig und nützlich, zum Suchen. Die eine, die auffiel, ist danach eine **Hypothese** und kein Befund. |\n\n::: {.warning-box}\n**Der Schritt, der übersprungen wird:** Zwischen \"beim Explorieren aufgefallen\"\nund \"steht im Bericht\" gehört eine Prüfung an **neuen** Daten oder wenigstens\ndie ehrliche Angabe, wie viele Grafiken angesehen wurden.\n\n| Was man sagt | Was man sagen müsste |\n|---|---|\n| \"Variable 4 und 7 hängen zusammen, p = 0.009\" | \"Unter 45 angesehenen Paaren war dies das stärkste; nach Korrektur nicht signifikant\" |\n\nDas ist derselbe Mechanismus wie beim\n[gewählten Ausschnitt](irrefuehrende-darstellungen.qmd), nur dass hier nicht\nder Zeitraum, sondern das Variablenpaar gesucht wurde.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Unter 45 paarweisen Streudiagrammen von zehn unabhängigen Variablen erreichen\n> drei einen p-Wert unter 0.05, bei einer Erwartung von 2.25. Das stärkste Paar\n> zeigt r = 0.1849 mit p = 0.0088 und überlebt die Bonferroni-Schwelle von\n> 0.00111 nicht.\n\n### Beispiel 3: Trägt der Titel, was er behauptet?\n\n#### Frage und Datenlage\n\nDrei Titelvorschläge für die Regionen-Grafik aus Beispiel 1. Jeder wird gegen\ndie Daten geprüft: Steigung, Konfidenzintervall, p-Wert.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npruefe_trend <- function(y) {\n  m <- lm(y ~ zeit)\n  s <- summary(m)$coefficients[2, ]\n  ki <- unname(confint(m)[2, ])   # unname: sonst heisst die Spalte \"unten.2.5 %\"\n  c(steigung = unname(s[1]), unten = ki[1], oben = ki[2], p = unname(s[4]))\n}\n\npruefung <- t(sapply(1:4, function(i) pruefe_trend(daten[i, ])))\nrownames(pruefung) <- regionen\nround(pruefung, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     steigung   unten   oben      p\nNord   0.0843 -0.2386 0.4071 0.5938\nSued   1.2578  1.0085 1.5072 0.0000\nOst   -0.1967 -0.5897 0.1962 0.3104\nWest  -0.2083 -0.6158 0.1993 0.3008\n```\n\n\n:::\n\n```{.r .cell-code}\n# Deckt das Intervall die Null? Dann ist \"waechst\" oder \"faellt\" nicht belegt.\ndata.frame(region = regionen,\n           richtung = ifelse(pruefung[, \"unten\"] > 0, \"waechst\",\n                             ifelse(pruefung[, \"oben\"] < 0, \"faellt\", \"nicht belegt\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     region     richtung\nNord   Nord nicht belegt\nSued   Sued      waechst\nOst     Ost nicht belegt\nWest   West nicht belegt\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndef pruefe_trend(y):\n    k, d = np.polyfit(zeit, y, 1)\n    rest = y - (k * zeit + d)\n    se = np.sqrt((rest ** 2).sum() / (len(zeit) - 2)\n                 / ((zeit - zeit.mean()) ** 2).sum())\n    rand = stats.t.ppf(.975, len(zeit) - 2) * se\n    return {\"steigung\": k, \"unten\": k - rand, \"oben\": k + rand,\n            \"p\": float(2 * stats.t.sf(abs(k / se), len(zeit) - 2))}\n\n\npruefung = pd.DataFrame([pruefe_trend(daten[i]) for i in range(4)],\n                        index=regionen)\nprint(pruefung.round(4))\n\nrichtung = np.where(pruefung[\"unten\"] > 0, \"waechst\",\n                    np.where(pruefung[\"oben\"] < 0, \"faellt\", \"nicht belegt\"))\nprint(pd.DataFrame({\"region\": regionen, \"richtung\": richtung}).to_string(index=False))\n```\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Region | Steigung | 95-Prozent-Intervall | p | Richtung belegt? |\n|---|---|---|---|---|\n| Nord | +0.084 | **−0.239 bis +0.407** | 0.5938 | **nicht belegt** |\n| **Sued** | **+1.258** | **+1.008 bis +1.507** | **< 0.0001** | **wächst** |\n| Ost | −0.197 | −0.590 bis +0.196 | 0.3104 | nicht belegt |\n| West | −0.208 | −0.616 bis +0.199 | 0.3008 | nicht belegt |\n\nDrei Titel, geprüft:\n\n| Titelvorschlag | gedeckt? | Begründung |\n|---|---|---|\n| \"Umsatz nach Region, 24 Monate\" |   | beschreibend, behauptet nichts |\n| **\"Nur der Süden wächst\"** | **ja** | Süd: Intervall über null; die drei anderen schliessen null ein |\n| \"Ost und West brechen ein\" | **nein** | Steigungen −0.197 und −0.208, beide Intervalle enthalten null |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Nur **eine** von vier Regionen hat einen belegten Trend | Süd, mit einem Intervall von +1.008 bis +1.507, das die Null deutlich verfehlt. |\n| Ost und West haben **negative** Steigungen | −0.197 und −0.208. Wer nur die Zahl ansieht, formuliert \"beide schrumpfen\" und liegt daneben, weil die Intervalle von −0.59 bis +0.20 reichen. |\n| Nord hat die **kleinste** Steigung von allen | +0.084, und p = 0.59. Die Region ist stabil, nicht wachsend. |\n| Der Aussagetitel ist hier **möglich** | \"Nur der Süden wächst\" ist genau das, was die Prüfung ergibt, inklusive des Wörtchens \"nur\". |\n| Ohne die Prüfung wäre der Titel geraten | Und mit 24 Monaten Rauschen um ±6 wäre er leicht falsch geraten. **Ein Aussagetitel verpflichtet zur Rechnung.** |\n\n::: {.note-box}\n**Die drei Stufen eines Titels:**\n\n| Stufe | Beispiel | Wann |\n|---|---|---|\n| **beschreibend** | \"Umsatz nach Region, 24 Monate\" | wenn die Grafik zum Nachschlagen da ist |\n| **hinweisend** | \"Der Süden entwickelt sich anders\" | wenn die Richtung klar, das Ausmass aber offen ist |\n| **behauptend** | \"Nur der Süden wächst, 1.3 Prozent je Monat\" | wenn die Rechnung es trägt |\n\nNach unten wird der Titel wirksamer und riskanter. Die Zahl im Titel ist dabei\nkein Schmuck: Sie macht die Behauptung überprüfbar.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Von vier Regionen hat nur Süd einen belegten Trend (+1.258 je Monat,\n> Intervall +1.008 bis +1.507). Die Intervalle der drei anderen schliessen die\n> Null ein, obwohl zwei negative Punktschätzungen haben. Der Titel \"Nur der\n> Süden wächst\" ist gedeckt, \"Ost und West brechen ein\" ist es nicht.\n\n### Beispiel 4: Wie viel in der Grafik keine Daten ist\n\n#### Frage und Datenlage\n\nDieselbe Grafik zweimal: einmal als Standardausgabe aus der Analyse, einmal für\nden Bericht aufgeräumt. Gezählt wird, wie viele Elemente Daten zeigen und wie\nviele nicht.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nelemente <- data.frame(\n  art = c(\"Datenmarken\", \"Gitterlinien\", \"Achsenticks\",\n          \"Legendeneinträge\", \"Rahmenlinien\", \"Titel\", \"Anmerkungen\"),\n  explorativ = c(96, 14, 18, 4, 4, 0, 0),\n  erklaerend = c(96, 4, 10, 0, 0, 1, 2))\nelemente\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               art explorativ erklaerend\n1      Datenmarken         96         96\n2     Gitterlinien         14          4\n3      Achsenticks         18         10\n4 Legendeneinträge          4          0\n5     Rahmenlinien          4          0\n6            Titel          0          1\n7      Anmerkungen          0          2\n```\n\n\n:::\n\n```{.r .cell-code}\nfor (sp in c(\"explorativ\", \"erklaerend\")) {\n  daten_marken <- elemente[1, sp]\n  rest <- sum(elemente[-1, sp])\n  cat(sprintf(\"%-12s Datenmarken %d, andere Elemente %d, Anteil Daten %.1f Prozent\\n\",\n              sp, daten_marken, rest, daten_marken / (daten_marken + rest) * 100))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nexplorativ   Datenmarken 96, andere Elemente 40, Anteil Daten 70.6 Prozent\nerklaerend   Datenmarken 96, andere Elemente 17, Anteil Daten 85.0 Prozent\n```\n\n\n:::\n\n```{.r .cell-code}\nlang <- data.frame(\n  region = rep(regionen, each = 24),\n  monat = rep(zeit, times = 4),\n  umsatz = as.vector(t(daten)))\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nmatplot(zeit, t(daten), type = \"l\", lty = 1, lwd = 1.2, col = 1:4,\n        xlab = \"monat\", ylab = \"umsatz\", main = \"Standardausgabe\")\ngrid(nx = 7, ny = 7, col = \"grey70\")\nlegend(\"topright\", legend = regionen, col = 1:4, lty = 1, cex = 0.7)\nbox()\n\nmatplot(zeit, t(daten), type = \"l\", lty = 1, lwd = 1.6,\n        col = c(neutral, akzent, neutral, neutral), bty = \"n\",\n        xlab = \"Monat\", ylab = \"Umsatz in Tausend Franken\",\n        main = \"Nur der Süden wächst\")\ntext(23, daten[2, 24] + 4, \"Süd\", col = akzent, adj = 1, font = 2)\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 4: links die Standardausgabe, rechts die aufgeräumte Fassung.](zielbild-audience_files/figure-html/fig-b4-zb-r-1.png){#fig-b4-zb-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nelemente = pd.DataFrame({\n    \"art\": [\"Datenmarken\", \"Gitterlinien\", \"Achsenticks\",\n            \"Legendeneinträge\", \"Rahmenlinien\", \"Titel\", \"Anmerkungen\"],\n    \"explorativ\": [96, 14, 18, 4, 4, 0, 0],\n    \"erklaerend\": [96, 4, 10, 0, 0, 1, 2]})\nprint(elemente.to_string(index=False))\n\nfor sp in (\"explorativ\", \"erklaerend\"):\n    marken = int(elemente.loc[0, sp])\n    rest = int(elemente[sp][1:].sum())\n    print(f\"{sp:<12} Datenmarken {marken}, andere Elemente {rest},\"\n          f\" Anteil Daten {marken / (marken + rest) * 100:.1f} Prozent\")\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.4))\nfor i in range(4):\n    _ = achsen[0].plot(zeit, daten[i], lw=1.2, label=regionen[i])\n_ = achsen[0].grid(True, color=\"0.7\")\n_ = achsen[0].legend(fontsize=7)\n_ = achsen[0].set_xlabel(\"monat\")\n_ = achsen[0].set_ylabel(\"umsatz\")\n_ = achsen[0].set_title(\"Standardausgabe\")\n\nfor i in range(4):\n    _ = achsen[1].plot(zeit, daten[i], lw=1.6,\n                       color=AKZENT if i == 1 else NEUTRAL)\n_ = achsen[1].text(23, daten[1, -1] + 4, \"Süd\", color=AKZENT, ha=\"right\",\n                   fontweight=\"bold\")\nfor rand in (\"top\", \"right\"):\n    _ = achsen[1].spines[rand].set_visible(False)\n_ = achsen[1].set_xlabel(\"Monat\")\n_ = achsen[1].set_ylabel(\"Umsatz in Tausend Franken\")\n_ = achsen[1].set_title(\"Nur der Süden wächst\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselbe Gegenüberstellung in Python.](zielbild-audience_files/figure-html/fig-b4-zb-py-1.png){#fig-b4-zb-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Element | explorativ | erklärend |\n|---|---|---|\n| Datenmarken | 96 | 96 |\n| Gitterlinien | 14 | **4** |\n| Achsenticks | 18 | **10** |\n| Legendeneinträge | 4 | **0** |\n| Rahmenlinien | 4 | **0** |\n| Titel | 0 | **1** |\n| Anmerkungen | 0 | **2** |\n\n| Fassung | Datenmarken | andere Elemente | Anteil Daten |\n|---|---|---|---|\n| explorativ | 96 | **40** | **70.6 Prozent** |\n| erklärend | 96 | **17** | **85.0 Prozent** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die **Datenmenge ändert sich nicht** | 96 Werte in beiden Fassungen. Es wird nichts weggelassen, was Information trägt. |\n| Die anderen Elemente sinken von 40 auf **17** | Gitterlinien, Ticks, Rahmen und Legende. Jedes davon hat einmal einen Zweck gehabt und hier keinen. |\n| Die **Legende verschwindet ganz** | Weil die eine Serie, um die es geht, direkt beschriftet ist. Das spart dem Auge den Weg zwischen Linie und Legende, bei vier Serien viermal. |\n| Es kommen **drei** Elemente dazu | Titel und zwei Anmerkungen. Aufräumen heisst nicht nur streichen: Der Titel trägt jetzt die Aussage, die Einheit steht an der Achse. |\n| Die rechte Fassung hat **weniger Farben** | Drei graue Linien und eine rote statt vier bunte. Die Aussage bestimmt, was Farbe bekommt. |\n\n::: {.note-box}\n**Die Zählung ist ein Hilfsmittel, kein Ziel.** Der Anteil von 85 Prozent ist\nkeine Norm, die es zu erreichen gilt, eine Grafik ohne Achsenbeschriftung\nhätte einen noch höheren Wert und wäre unbrauchbar.\n\nNützlich ist die Zählung als **Frage an jedes Element**: Was passiert, wenn ich\nes weglasse? Verliert die Grafik Information, bleibt es. Sieht sie nur anders\naus, geht es. Und was fehlt, Einheit, Quelle, Aussage, kommt dazu.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Beide Fassungen zeigen dieselben 96 Werte. Die Zahl der Elemente ohne\n> Dateninhalt sinkt von 40 auf 17, der Anteil der Datenmarken steigt damit von\n> 70.6 auf 85.0 Prozent, bei drei neu hinzugekommenen Elementen für Titel und\n> Beschriftung.\n\n### Beispiel 5: Hässlich, schlecht gelesen oder falsch\n\n#### Frage und Datenlage\n\nDrei fehlerhafte Fassungen derselben Grafik. Die Frage ist nicht, welche am\nschlechtesten aussieht, sondern **wie gross der Schaden** in jedem Fall ist.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmittel <- kennzahlen[, \"mittel\"]\n\n# 1 haesslich: nichts stimmt inhaltlich nicht\nc(ablesefehler_haesslich = 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nablesefehler_haesslich \n                     0 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 2 schlecht gelesen: Torte statt Balken\ngrad <- mittel / sum(mittel) * 360\npaare <- t(combn(4, 2))\nwinkel_diff <- apply(paare, 1, function(k) abs(grad[k[1]] - grad[k[2]]))\nc(paare_unter_15_grad = sum(winkel_diff < 15), paare = length(winkel_diff))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npaare_unter_15_grad               paare \n                  2                   6 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 3 falsch: Balkenachse ab 60\nlaengen <- mittel - 60\nround(c(echtes_verhaeltnis = max(mittel) / min(mittel),\n        dargestelltes_verhaeltnis = max(laengen) / min(laengen),\n        verzerrung = (max(laengen) / min(laengen)) / (max(mittel) / min(mittel))), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       echtes_verhaeltnis dargestelltes_verhaeltnis                verzerrung \n                     1.64                      4.48                      2.73 \n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 3), mar = c(4, 4, 3, 1))\nbarplot(mittel, names.arg = regionen, col = rainbow(4), border = \"black\",\n        ylab = \"Umsatz\", main = \"1 hässlich\")\ngrid(col = \"grey50\")\npie(mittel, labels = regionen, col = grey.colors(4), main = \"2 schlecht gelesen\")\nbarplot(mittel, names.arg = regionen, col = neutral, border = NA,\n        ylim = c(60, 125), xpd = FALSE, ylab = \"Umsatz\", main = \"3 falsch\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 5: hässlich, schlecht gelesen, falsch.](zielbild-audience_files/figure-html/fig-b5-zb-r-3.png){#fig-b5-zb-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmittel = kennzahlen[\"mittel\"].to_numpy()\n\nprint({\"ablesefehler_haesslich\": 0})\n\ngrad = mittel / mittel.sum() * 360\nwinkel_diff = [abs(grad[i] - grad[j])\n               for i, j in itertools.combinations(range(4), 2)]\nprint({\"paare_unter_15_grad\": sum(1 for d in winkel_diff if d < 15),\n       \"paare\": len(winkel_diff)})\n\nlaengen = mittel - 60\nprint({\"echtes_verhaeltnis\": round(float(mittel.max() / mittel.min()), 2),\n       \"dargestelltes_verhaeltnis\": round(float(laengen.max() / laengen.min()), 2),\n       \"verzerrung\": round(float((laengen.max() / laengen.min())\n                                 / (mittel.max() / mittel.min())), 2)})\n\nfig, achsen = plt.subplots(1, 3, figsize=(7, 3))\n_ = achsen[0].bar(regionen, mittel,\n                  color=[\"#FF0000\", \"#00FF00\", \"#0000FF\", \"#FFFF00\"],\n                  edgecolor=\"black\")\n_ = achsen[0].grid(True, color=\"0.5\")\n_ = achsen[0].set_title(\"1 hässlich\")\n_ = achsen[0].set_ylabel(\"Umsatz\")\n_ = achsen[1].pie(mittel, labels=regionen,\n                  colors=[str(g) for g in np.linspace(0.3, 0.85, 4)])\n_ = achsen[1].set_title(\"2 schlecht gelesen\")\n_ = achsen[2].bar(regionen, mittel - 60, bottom=60, color=NEUTRAL)\n_ = achsen[2].set_ylim(60, 125)\n_ = achsen[2].set_title(\"3 falsch\")\n_ = achsen[2].set_ylabel(\"Umsatz\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselben drei Fassungen in Python.](zielbild-audience_files/figure-html/fig-b5-zb-py-1.png){#fig-b5-zb-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Fassung | Messbarer Schaden |\n|---|---|\n| **1 hässlich**, Regenbogenfarben, Gitter, Rahmen | **0** Ablesefehler: alle Werte bleiben korrekt ablesbar |\n| **2 schlecht gelesen**, Torte statt Balken | **2 von 6** Paaren unterscheiden sich um weniger als 15 Grad |\n| **3 falsch**, Achse ab 60 | echtes Verhältnis **1.65**, dargestelltes **4.44**, Verzerrung **2.69-fach** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die erste Fassung ist nur **hässlich** | Jeder Wert lässt sich korrekt ablesen, die Achse beginnt bei null, die Länge stimmt. Der Schaden ist ästhetisch und damit der geringste. |\n| Die zweite **täuscht, ohne zu lügen** | Zwei von sechs Paarvergleichen liegen unter 15 Grad und sind damit Ratesache. Es steht nichts Falsches da; das Publikum nimmt trotzdem etwas Falsches mit. |\n| Die dritte **behauptet Unwahres** | Aus einem Verhältnis von 1.65 wird eines von 4.44. Die Grafik sagt, Nord sei viereinhalbmal so gross wie Süd. Tatsächlich ist es das 1.65-Fache. |\n| Die Dringlichkeit folgt der Zahl | 0 bis 2 von 6, Faktor 2.69. **Wer Zeit für genau eine Korrektur hat, korrigiert die dritte.** |\n| Am häufigsten korrigiert wird die **erste** | Weil sie am schnellsten auffällt. Das ist die falsche Reihenfolge. |\n\n::: {.note-box}\n**Die Prüfreihenfolge, die daraus folgt:**\n\n1. **Stimmt es?** Achsen, Skalierung, Geometrie, Aggregation. Das ist die\n   Prüfliste unter\n   [irreführende Darstellungen](irrefuehrende-darstellungen.qmd).\n2. **Wird es richtig gelesen?** Kanal zur Aufgabe passend? Das ist\n   [Wahrnehmung und Kodierung](wahrnehmung-kodierung.qmd).\n3. **Sieht es gut aus?** Erst jetzt.\n\nIn der Praxis läuft es meistens rückwärts und dann bleibt für die erste Frage\nkeine Zeit mehr.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die drei Fehlerarten unterscheiden sich messbar: Die hässliche Fassung\n> verursacht keinen Ablesefehler, die Torte macht 2 von 6 Paarvergleichen zur\n> Ratesache, und die abgeschnittene Achse übertreibt das Verhältnis von 1.65\n> auf 4.44, eine Verzerrung um den Faktor 2.69.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEine explorative Grafik aus der Analyse soll in den Abschlussbericht. Was ist\nzu tun?\n\n- [ ] Übernehmen, sie zeigt das Ergebnis korrekt ~ Korrektheit genügt nicht:\n      sie ist für jemanden gemacht, der die Daten schon kennt.\n- [x] Neu bauen für das Publikum des Berichts ~ Richtig. Zu klären sind Aussage,\n      Vorwissen und Detailtiefe; im Beispiel sank die Zahl der Elemente ohne\n      Dateninhalt dabei von 40 auf 17, während Titel und Einheit dazukamen.\n- [ ] Nur den Titel anpassen ~ Der Titel ist ein Teil davon, aber Auswahl und\n      Beschriftung tragen die Verständlichkeit.\n:::\n\n::: {.quiz}\nBeim Explorieren von zehn unabhängigen Variablen fällt ein Paar mit p = 0.009\nauf. Was ist das?\n\n- [x] Der erwartete Zufallsbefund unter 45 Vergleichen ~ Richtig. Erwartet\n      waren 2.25 signifikante Paare bei reinem Rauschen, gefunden wurden drei.\n      Nach Bonferroni bleibt keines übrig.\n- [ ] Ein schwacher, aber echter Zusammenhang ~ Die Variablen wurden\n      nachweislich unabhängig erzeugt.\n- [ ] Ein Fehler im Zufallsgenerator ~ Über dreissig Saaten entsprach die Zahl\n      auffälliger Paare der Erwartung.\n:::\n\n::: {.quiz}\nDrei Regionen haben Steigungen von +0.084, −0.197 und −0.208 je Monat. Welcher\nTitel ist gedeckt?\n\n- [x] Keiner, der eine Richtung behauptet, alle drei Intervalle enthalten die\n      Null ~ Richtig. Die Intervalle reichen etwa von −0.6 bis +0.4; die\n      Vorzeichen der Punktschätzungen tragen keine Aussage.\n- [ ] \"Ost und West brechen ein\", beide Steigungen sind negativ ~ Genau das ist\n      der Fehlschluss: Das Vorzeichen allein belegt nichts.\n- [ ] \"Nord wächst am stärksten\" ~ Nord hat mit +0.084 die kleinste Steigung\n      aller vier Regionen und p = 0.59.\n:::\n\n::: {.quiz}\nDieselben Daten sollen \"Nord ist am grössten\" und \"nur Süd wächst\" zeigen.\nGenügt eine Grafik?\n\n- [x] Nein, die zwei Aussagen verlangen verschiedene Darstellungen ~ Richtig.\n      Der sortierte Balken mittelt die Zeit weg und verbirgt den Trend, die\n      Liniengrafik macht den Grössenvergleich mühsam. Beide Aussagen stimmen.\n- [ ] Ja, eine Liniengrafik zeigt beides ~ Sie zeigt den Trend gut und den\n      Niveauvergleich schlecht, weil die Linien verschieden hoch verlaufen.\n- [ ] Nein, weil die Aussagen sich widersprechen ~ Sie widersprechen sich\n      nicht: Nord ist gross und stabil, Süd klein und wachsend.\n:::\n\n::: {.quiz}\nEin Diagramm ist korrekt gerechnet, aber die zwölf Segmente einer Torte sind\nkaum unterscheidbar. Wie ist das einzuordnen?\n\n- [ ] Als kosmetisches Problem ~ Kosmetisch wäre es, wenn die Grafik nur\n      ungestaltet aussähe.\n- [x] Als Wahrnehmungsproblem: das Publikum liest die Anteile falsch ~ Richtig.\n      Winkel lassen sich schlecht vergleichen; im Beispiel lagen 2 von 6\n      Paarvergleichen unter 15 Grad. Der Balken löst dieselbe Aufgabe besser.\n- [ ] Als Rechenfehler ~ Gerechnet ist alles richtig, gelesen wird es falsch.\n:::\n\n::: {.quiz}\nDrei Fassungen einer Grafik sind hässlich, schlecht lesbar und falsch. In\nwelcher Reihenfolge korrigiert man?\n\n- [x] Zuerst die falsche, dann die schlecht lesbare, zuletzt die hässliche ~\n      Richtig, nach dem Schaden: Verzerrung um den Faktor 2.69 gegen 2 von 6\n      unlesbaren Vergleichen gegen null Ablesefehler.\n- [ ] Zuerst die hässliche, sie fällt am meisten auf ~ Genau das passiert in\n      der Praxis, und es ist die falsche Reihenfolge.\n- [ ] Alle gleichzeitig ~ Wenn die Zeit reicht, gern; die Frage ist, womit man\n      anfängt, wenn sie nicht reicht.\n:::\n\n## Verlinkte Ressourcen\n\n- [Claus Wilke: Fundamentals of Data Visualization](https://clauswilke.com/dataviz/)\n- [Storytelling with Data: Blog](https://www.storytellingwithdata.com/blog)\n- [Multiples Testen](../statistik/inferenz/multiples-testen.qmd), warum beim Explorieren Scheinbefunde entstehen\n- [Irreführende Darstellungen](irrefuehrende-darstellungen.qmd), die Prüfliste für \"stimmt es?\"\n",
    "supporting": [
      "zielbild-audience_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}