{
  "hash": "0ad35106deb62f18bfc1eec0e0ed882a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Normalitätstests\"\ndescription: \"Shapiro und Kolmogorow-Smirnow, und warum Plots oft mehr zeigen.\"\ncategories: [\"Hypothesentests\", \"Verteilungen\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"ESDS\", \"STATDA\"]\nseitentyp: konzept\nstand: fertig\norder: 80\n---\n\n\n\n\n\nAlle Beispiele rechnen mit deterministisch konstruierten Zahlen, damit R und\nPython dieselben Daten sehen und jeder Wert im Text nachprüfbar ist.\n\n## Kernideen\n\n- Ein Normalitätstest prüft die Nullhypothese \"die Daten stammen aus einer\n  Normalverteilung\". Ein grosser p-Wert ist **kein Nachweis** dieser Annahme,\n  sondern nur das Ausbleiben eines Gegenbeweises.\n- Die Aussagekraft hängt fast vollständig am Stichprobenumfang, und zwar in\n  beide Richtungen. Bei kleinem n findet der Test auch grobe Abweichungen\n  nicht; bei grossem n verwirft er wegen Abweichungen, die keine Rolle spielen.\n- Genau das macht ihn als Entscheidungshilfe untauglich: Er schlägt dort an, wo\n  es unwichtig ist, und schweigt dort, wo es darauf ankäme.\n- Die meisten Verfahren setzen ohnehin nicht normalverteilte **Daten** voraus,\n  sondern normalverteilte **Residuen** oder Mittelwerte. Der zentrale\n  Grenzwertsatz erledigt Letzteres mit wachsendem n von selbst.\n- Was stattdessen hilft: [QQ-Plot](../wahrscheinlichkeit/qq-plots.qmd),\n  Histogramm, der Vergleich von Mittelwert und Median, und die Frage, wie\n  empfindlich das geplante Verfahren überhaupt reagiert.\n\n## Erklärung\n\n### Was die Tests tun\n\n| Test | Grundidee | R | Python |\n|---|---|---|---|\n| Shapiro-Wilk | Vergleicht die geordneten Werte mit den unter Normalverteilung erwarteten; im Kern ein QQ-Plot als Zahl | `shapiro.test(x)` | `stats.shapiro(x)` |\n| Kolmogorow-Smirnow | Grösster senkrechter Abstand zwischen empirischer und theoretischer Verteilungsfunktion | `ks.test(x, \"pnorm\", mean, sd)` | `stats.kstest(x, \"norm\")` |\n| Anderson-Darling | Wie KS, gewichtet aber die Ränder stärker | `nortest::ad.test(x)` | `stats.anderson(x)` |\n\nShapiro-Wilk ist der schärfste der drei und der übliche Standard. Der\nKolmogorow-Smirnow-Test ist verbreiteter, als er es verdient: In der Form, in\nder er meist verwendet wird, werden Mittelwert und Streuung aus denselben Daten\ngeschätzt, für die er dann prüft. Das macht ihn deutlich zu konservativ, wie\nBeispiel 2 zeigt.\n\n### Die Nullhypothese steht auf der falschen Seite\n\nBei einem Normalitätstest lautet die Nullhypothese, dass alles in Ordnung ist.\nMan möchte sie aber **bestätigen**, nicht verwerfen, und genau das kann ein\nTest grundsätzlich nicht. Ein p-Wert von 0.95 heisst nicht \"normalverteilt\", er\nheisst \"diese Daten sprechen nicht dagegen\".\n\nDie Folge ist eine Fehlerlogik, die genau verkehrt herum läuft:\n\n| Umfang | Was passiert | Warum das falsch herum ist |\n|---|---|---|\n| klein, etwa n < 30 | Der Test hat kaum Power und verwirft fast nie | Gerade hier wäre die Verteilungsform wichtig, weil der zentrale Grenzwertsatz noch nicht greift |\n| gross, etwa n > 300 | Der Test verwirft schon bei winzigen Abweichungen | Gerade hier ist die Verteilungsform fast egal, weil der zentrale Grenzwertsatz greift |\n\n### Was die Verfahren wirklich voraussetzen\n\nEin verbreitetes Missverständnis ist, dass t-Test und Regression normalverteilte\nRohdaten bräuchten. Das trifft nicht zu:\n\n| Verfahren | Voraussetzung betrifft | Praktische Konsequenz |\n|---|---|---|\n| [t-Test](t-test-zwei-stichproben.qmd) | die Verteilung des **Mittelwerts** | Bei n über etwa 30 je Gruppe und ohne extreme Schiefe unkritisch |\n| [Lineare Regression](../regression/einfache-lineare-regression.qmd) | die **Residuen**, nicht x und y | Eine rechtsschiefe Zielgrösse ist kein Problem, solange die Residuen unauffällig sind |\n| [Varianzanalyse](anova.qmd) | die Residuen | Wie oben; Varianzhomogenität ist meist das grössere Thema |\n| Konfidenzintervall für den Mittelwert | die Verteilung des Mittelwerts | Wie beim t-Test |\n\nWer also die Rohdaten auf Normalität testet, prüft in mehreren dieser Fälle die\nfalsche Grösse.\n\n### Wie stattdessen vorgehen\n\n1. **Streudiagramm, Histogramm und Boxplot ansehen.** Sie zeigen Schiefe,\n   Mehrgipfligkeit und Ausreisser, und zwar mit ihrer Grössenordnung.\n2. **QQ-Plot lesen.** Er zeigt nicht nur, **dass** etwas abweicht, sondern\n   **wie**: an den Rändern, in der Mitte, einseitig oder symmetrisch.\n3. **Mittelwert und Median vergleichen.** Klaffen sie auseinander, ist die\n   Verteilung schief, und der Mittelwert beschreibt keinen typischen Fall mehr.\n4. **Fragen, wie empfindlich das Verfahren ist.** Bei n = 200 je Gruppe ist ein\n   t-Test gegen mässige Schiefe unempfindlich; bei n = 8 ist er es nicht.\n5. **Im Zweifel das robuste Verfahren wählen**, also\n   [Rangtests](nichtparametrische-tests.qmd) oder\n   [Bootstrap](../inferenz/bootstrap-resampling.qmd), und die Wahl vorab\n   festlegen.\n\n::: {.note-box}\nEin Normalitätstest darf durchaus berichtet werden, ergänzend und mit seinem\nUmfang. Was nicht tragfähig ist, ist die Entscheidungsregel \"p über 0.05, also\nt-Test, sonst Rangtest\". Sie macht die Verfahrenswahl von einer Zahl abhängig,\ndie vor allem den Stichprobenumfang widerspiegelt, und sie hält das Testniveau\ndes nachfolgenden Verfahrens nicht ein, weil zweimal an denselben Daten\nentschieden wird.\n:::\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Unauffällige Daten\n\n#### Frage und Datenlage\n\nZwanzig Messwerte eines Fertigungsmasses. Die Frage lautet: Sprechen sie gegen\neine Normalverteilung?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmesswerte <- c(98.4, 101.2, 99.7, 100.3, 102.1, 97.9, 100.8, 99.1, 101.6,\n               100.0, 98.8, 101.9, 99.4, 100.6, 97.2, 102.6, 99.9, 100.4,\n               98.1, 101.3)\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nhist(messwerte, breaks = 8, col = \"grey85\", main = \"Histogramm\",\n     xlab = \"Messwert\")\nqqnorm(messwerte, main = \"QQ-Plot\"); qqline(messwerte)\npar(mfrow = c(1, 1))\n\nshapiro.test(messwerte)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  messwerte\nW = 0.98167, p-value = 0.9537\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(mittel = mean(messwerte), median = median(messwerte)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n mittel  median \n100.065 100.150 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 1: Histogramm und QQ-Plot von zwanzig Messwerten.](normalitaetstests_files/figure-html/fig-b1-nt-r-1.png){#fig-b1-nt-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmesswerte = np.array([98.4, 101.2, 99.7, 100.3, 102.1, 97.9, 100.8, 99.1,\n                      101.6, 100.0, 98.8, 101.9, 99.4, 100.6, 97.2, 102.6,\n                      99.9, 100.4, 98.1, 101.3])\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nachsen[0].hist(messwerte, bins=8, color=\"0.8\", edgecolor=\"0.3\")\nachsen[0].set_title(\"Histogramm\")\nachsen[0].set_xlabel(\"Messwert\")\nsm.qqplot(messwerte, line=\"s\", ax=achsen[1])\nachsen[1].set_title(\"QQ-Plot\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Prüfung in Python.](normalitaetstests_files/figure-html/fig-b1-nt-py-1.png){#fig-b1-nt-py width=100%}\n:::\n\n```{.python .cell-code}\nergebnis = stats.shapiro(messwerte)\nprint(\"Shapiro-Wilk  W =\", round(ergebnis.statistic, 4),\n      \" p =\", round(ergebnis.pvalue, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nShapiro-Wilk  W = 0.9817  p = 0.9537\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Mittelwert =\", round(messwerte.mean(), 3),\n      \" Median =\", round(np.median(messwerte), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMittelwert = 100.065  Median = 100.15\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| `W` | 0.9817 | Shapiro-Wilk-Statistik | Sie liegt zwischen 0 und 1; Werte nahe 1 bedeuten gute Übereinstimmung mit der Normalverteilung. W ist im Kern das Quadrat der Korrelation zwischen den Daten und den im QQ-Plot erwarteten Werten. |\n| `p-value` | 0.954 | Wahrscheinlichkeit einer mindestens so grossen Abweichung, wenn die Daten normalverteilt wären | Kein Anlass zur Sorge. Aber eben auch **kein Nachweis** der Normalverteilung. |\n| Mittelwert und Median | 100.06 und 100.15 | Lagemasse | Sie liegen praktisch übereinander, also ist die Verteilung nicht schief. |\n| QQ-Plot | Punkte nah an der Geraden | | Die eigentliche Prüfung. Sie zeigt zusätzlich, dass die Abweichungen klein und über den ganzen Bereich verteilt sind. |\n\n#### Interpretation\n\nDer korrekte Satz lautet: \"Die Daten sprechen nicht gegen eine\nNormalverteilung.\" Nicht: \"Die Daten sind normalverteilt.\"\n\nDer Unterschied ist bei n = 20 erheblich, denn der Test hätte selbst eine\ndeutliche Schiefe wahrscheinlich nicht gefunden. Genau das zeigt Beispiel 3.\n\n### Beispiel 2: Zu viel Power bei grossem n\n\n#### Frage und Datenlage\n\nTausend Werte mit einer leichten Rechtsschiefe. Die Schiefe beträgt 0.47 und\nist damit so klein, dass sie für jedes übliche Verfahren belanglos wäre.\nZusätzlich werden dieselben hundert Werte, also derselbe Verteilungstyp bei\nkleinerem Umfang, mitgerechnet.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschief <- function(n) {\n  q <- qnorm(ppoints(n))\n  q + 0.08 * q^2\n}\n\ngross <- schief(1000)\nklein <- schief(100)\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nqqnorm(gross, main = \"n = 1000\"); qqline(gross)\nqqnorm(klein, main = \"n = 100\"); qqline(klein)\npar(mfrow = c(1, 1))\n\nshapiro.test(gross)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  gross\nW = 0.9875, p-value = 1.583e-07\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(klein)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  klein\nW = 0.98811, p-value = 0.5164\n```\n\n\n:::\n\n```{.r .cell-code}\nks.test(gross, \"pnorm\", mean(gross), sd(gross))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic one-sample Kolmogorov-Smirnov test\n\ndata:  gross\nD = 0.032218, p-value = 0.2504\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 2: leichte Rechtsschiefe, einmal mit n = 1000 und einmal mit n = 100.](normalitaetstests_files/figure-html/fig-b2-nt-r-3.png){#fig-b2-nt-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndef schief(n):\n    q = stats.norm.ppf((np.arange(1, n + 1) - 0.5) / n)\n    return q + 0.08 * q ** 2\n\n\ngross = schief(1000)\nklein = schief(100)\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nsm.qqplot(gross, line=\"s\", ax=achsen[0])\nachsen[0].set_title(\"n = 1000\")\nsm.qqplot(klein, line=\"s\", ax=achsen[1])\nachsen[1].set_title(\"n = 100\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselbe Gegenüberstellung in Python.](normalitaetstests_files/figure-html/fig-b2-nt-py-1.png){#fig-b2-nt-py width=100%}\n:::\n\n```{.python .cell-code}\nfor name, werte in [(\"n = 1000\", gross), (\"n = 100\", klein)]:\n    e = stats.shapiro(werte)\n    print(f\"{name}: Shapiro W = {e.statistic:.4f}  p = {e.pvalue:.3g}\"\n          f\"  Schiefe = {stats.skew(werte, bias=False):+.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 1000: Shapiro W = 0.9875  p = 1.58e-07  Schiefe = +0.469\nn = 100: Shapiro W = 0.9881  p = 0.516  Schiefe = +0.439\n```\n\n\n:::\n\n```{.python .cell-code}\nstandardisiert = (gross - gross.mean()) / gross.std(ddof=1)\nks = stats.kstest(standardisiert, \"norm\")\nprint(f\"n = 1000: Kolmogorow-Smirnow p = {ks.pvalue:.3g}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 1000: Kolmogorow-Smirnow p = 0.245\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | n = 1000 | n = 100 | Wie das zu lesen ist |\n|---|---|---|---|\n| Schiefe | +0.47 | +0.47 | **Identisch.** Beide Datensätze folgen exakt derselben Verteilungsform. |\n| Shapiro `W` | 0.9875 | 0.9881 | Ebenfalls praktisch identisch. W misst die Abweichung und hängt kaum am Umfang. |\n| Shapiro `p-value` | 0.00000016 | 0.516 | Und hier gehen sie auseinander: hochsignifikant gegen völlig unauffällig. Der Unterschied liegt allein am Stichprobenumfang. |\n| Kolmogorow-Smirnow `p-value` (n = 1000) | 0.250 in R, 0.245 in Python | | Derselbe Datensatz, ein anderer Test, ein gegenteiliges Ergebnis. Die winzige Abweichung zwischen den Sprachen ruehrt daher, dass R die geschaetzten Parameter uebergeben bekommt und Python auf standardisierten Werten rechnet. |\n\nZwei Lehren stecken darin.\n\n**Erstens** entscheidet der Umfang, nicht die Verteilung. Dieselbe leichte\nSchiefe führt bei 1000 Werten zur Ablehnung und bei 100 Werten nicht. Wer die\nVerfahrenswahl an den p-Wert bindet, bindet sie in Wahrheit an den Umfang —\nund ausgerechnet bei n = 1000 ist die Verteilungsform für einen t-Test völlig\nbelanglos, weil der zentrale Grenzwertsatz längst greift.\n\n**Zweitens** ist der Kolmogorow-Smirnow-Test in dieser Form zu schwach. Er\nschätzt Mittelwert und Streuung aus denselben Daten, für die er dann prüft, und\npasst sich der Verteilung damit teilweise an. Sein p-Wert von rund 0.25 ist kein\nGegenbeweis zu Shapiro, sondern ein Zeichen mangelnder Schärfe. Wer KS\nverwendet, braucht die Lilliefors-Korrektur; einfacher ist es, Shapiro-Wilk zu\nnehmen.\n\n#### Interpretation\n\nDer QQ-Plot zeigt in beiden Fällen dasselbe Bild: eine leichte Krümmung an den\nEnden, die auf die Rechtsschiefe hinweist. Diese Darstellung ist umfangsunabhängig\nund beantwortet die Frage, um die es geht: **wie stark** weicht die Verteilung ab.\n\n> Die Werte weichen leicht von der Normalverteilung ab (Schiefe 0.47). Bei\n> n = 1000 wird diese Abweichung vom Shapiro-Wilk-Test erkannt (W = 0.99,\n> p < 0.001), bei n = 100 nicht (p = 0.52). Für die geplante Auswertung ist die\n> Abweichung ohne Belang, weil der Mittelwert bei diesem Umfang praktisch\n> normalverteilt ist.\n\n### Beispiel 3: Zu wenig Power bei kleinem n\n\n#### Frage und Datenlage\n\nFünfzehn Werte aus einer deutlich rechtsschiefen Verteilung. Die Schiefe beträgt\n1.31 und ist damit fast dreimal so gross wie in Beispiel 2. Ausgerechnet hier,\nbei kleinem Umfang, wäre sie inhaltlich wichtig.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq15 <- qnorm(ppoints(15))\nrechtsschief <- round(exp(0.6 * q15), 2)\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nhist(rechtsschief, breaks = 8, col = \"grey85\", main = \"Histogramm\",\n     xlab = \"Wert\")\nqqnorm(rechtsschief, main = \"QQ-Plot\"); qqline(rechtsschief)\npar(mfrow = c(1, 1))\n\nshapiro.test(rechtsschief)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  rechtsschief\nW = 0.90175, p-value = 0.1012\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(mittel = mean(rechtsschief), median = median(rechtsschief)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmittel median \n 1.178  1.000 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: deutlich rechtsschief, und der Test schlägt trotzdem nicht an.](normalitaetstests_files/figure-html/fig-b3-nt-r-3.png){#fig-b3-nt-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nq15 = stats.norm.ppf((np.arange(1, 16) - 0.5) / 15)\nrechtsschief = np.round(np.exp(0.6 * q15), 2)\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nachsen[0].hist(rechtsschief, bins=8, color=\"0.8\", edgecolor=\"0.3\")\nachsen[0].set_title(\"Histogramm\")\nachsen[0].set_xlabel(\"Wert\")\nsm.qqplot(rechtsschief, line=\"s\", ax=achsen[1])\nachsen[1].set_title(\"QQ-Plot\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselbe Prüfung in Python.](normalitaetstests_files/figure-html/fig-b3-nt-py-1.png){#fig-b3-nt-py width=100%}\n:::\n\n```{.python .cell-code}\ne = stats.shapiro(rechtsschief)\nprint(\"Shapiro W =\", round(e.statistic, 4), \" p =\", round(e.pvalue, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nShapiro W = 0.9018  p = 0.1012\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Schiefe =\", round(stats.skew(rechtsschief, bias=False), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSchiefe = 1.306\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Mittelwert =\", round(rechtsschief.mean(), 3),\n      \" Median =\", round(np.median(rechtsschief), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMittelwert = 1.178  Median = 1.0\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Schiefe | +1.31 | Deutlich rechtsschief, fast dreimal so stark wie in Beispiel 2. |\n| Shapiro `W` | 0.9018 | Merklich unter 1, also durchaus eine Abweichung. |\n| Shapiro `p-value` | 0.101 | **Nicht signifikant.** Bei fünfzehn Werten reicht die Power nicht, um selbst diese deutliche Schiefe nachzuweisen. |\n| Mittelwert und Median | 1.18 und 1.00 | Sie klaffen um rund 18 Prozent auseinander. Das ist der schnellste Hinweis auf Schiefe und braucht keinen Test. |\n| QQ-Plot | deutlicher Bogen | Die Punkte biegen am oberen Ende klar von der Geraden weg. Das Auge sieht, was der Test nicht findet. |\n\nWer der Entscheidungsregel \"p über 0.05, also t-Test\" folgt, würde hier einen\nMittelwertvergleich rechnen — bei fünfzehn deutlich schiefen Werten, also genau\nin der Lage, in der er unzuverlässig ist. Das ist der Kern des Problems: Der\nTest versagt dort, wo man ihn am dringendsten bräuchte.\n\n#### Interpretation\n\n> Die Verteilung ist deutlich rechtsschief (Schiefe 1.31; Mittelwert 1.18\n> gegenüber Median 1.00), was im QQ-Plot und im Histogramm klar erkennbar ist.\n> Der Shapiro-Wilk-Test wird bei n = 15 nicht signifikant (W = 0.90, p = 0.10),\n> was allein an der geringen Power liegt. Die Auswertung erfolgt deshalb\n> rangbasiert.\n\n### Beispiel 4: Was der QQ-Plot zeigt und ein p-Wert nicht\n\n#### Frage und Datenlage\n\nVier Datensätze mit je sechzig Werten. Alle vier würde ein Normalitätstest mit\neiner einzigen Zahl beantworten. Der QQ-Plot beantwortet stattdessen die Frage,\ndie weiterhilft: **wie** weicht die Verteilung ab?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq60 <- qnorm(ppoints(60))\n\nmuster <- list(\n  \"normal\"          = q60,\n  \"rechtsschief\"    = exp(0.7 * q60),\n  \"schwere Ränder\"  = qt(ppoints(60), df = 3),\n  \"ein Ausreisser\"  = c(q60[1:59], 8)\n)\n\npar(mfrow = c(1, 4), mar = c(4, 4, 3, 1))\nfor (name in names(muster)) {\n  qqnorm(muster[[name]], main = name, xlab = \"\", ylab = \"\")\n  qqline(muster[[name]])\n}\npar(mfrow = c(1, 1))\n\nround(sapply(muster, function(x) shapiro.test(x)$p.value), 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        normal   rechtsschief schwere Ränder ein Ausreisser \n       1.00000        0.00000        0.08801        0.00000 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 4: vier Abweichungsmuster im QQ-Plot.](normalitaetstests_files/figure-html/fig-b4-nt-r-3.png){#fig-b4-nt-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nq60 = stats.norm.ppf((np.arange(1, 61) - 0.5) / 60)\n\nmuster = {\n    \"normal\": q60,\n    \"rechtsschief\": np.exp(0.7 * q60),\n    \"schwere Ränder\": stats.t.ppf((np.arange(1, 61) - 0.5) / 60, df=3),\n    \"ein Ausreisser\": np.append(q60[:59], 8.0),\n}\n\nfig, achsen = plt.subplots(1, 4, figsize=(7, 3.0))\nfor achse, (name, werte) in zip(achsen, muster.items()):\n    sm.qqplot(werte, line=\"s\", ax=achse)\n    achse.set_title(name, fontsize=9)\n    achse.set_xlabel(\"\")\n    achse.set_ylabel(\"\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselben vier Muster in Python.](normalitaetstests_files/figure-html/fig-b4-nt-py-1.png){#fig-b4-nt-py width=100%}\n:::\n\n```{.python .cell-code}\nfor name, werte in muster.items():\n    print(f\"{name:16s} Shapiro p = {stats.shapiro(werte).pvalue:.5f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnormal           Shapiro p = 1.00000\nrechtsschief     Shapiro p = 0.00000\nschwere Ränder   Shapiro p = 0.08801\nein Ausreisser   Shapiro p = 0.00000\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Muster | Shapiro p | Bild im QQ-Plot | Was daraus folgt |\n|---|---|---|---|\n| normal | 1.000 | Punkte liegen auf der Geraden | Nichts zu tun. |\n| rechtsschief | < 0.001 | Punkte biegen am oberen Ende nach oben weg, unten liegen sie über der Geraden | Der Mittelwert beschreibt keinen typischen Fall. Logarithmieren oder rangbasiert vergleichen. |\n| schwere Ränder | 0.088 | S-förmiger Verlauf: unten unter, oben über der Geraden | Extremwerte sind häufiger als bei einer Normalverteilung. Der t-Test verliert Schärfe; robuste Verfahren helfen. |\n| ein Ausreisser | < 0.001 | Punkte liegen auf der Geraden, ein einzelner weit rechts oben | Kein Verteilungsproblem, sondern ein Einzelfall. Ihn zu prüfen ist sinnvoller, als das Verfahren zu wechseln. |\n\nDie p-Werte fallen ausgerechnet dort verkehrt herum aus, wo es darauf ankommt.\n\n**Bei den schweren Rändern schlägt der Test nicht an** (p = 0.088), obwohl genau\ndiese Lage dem t-Test tatsächlich Schärfe kostet. **Beim einzelnen Ausreisser\nschlägt er deutlich an** (p < 0.001), obwohl hier ein Verfahrenswechsel die\nfalsche Reaktion wäre: Das Problem ist eine Beobachtung, keine Verteilungsform.\nWer der Regel \"p klein, also Rangtest\" folgt, wechselt also im falschen Fall das\nVerfahren und behält es im richtigen bei.\n\nDer QQ-Plot unterscheidet die vier Lagen dagegen auf einen Blick, und jede\nverlangt eine andere Reaktion.\n\n::: {.note-box}\nDer p-Wert von 1.000 im ersten Muster ist ein Nebeneffekt der Konstruktion: Die\nDaten sind exakt die Quantile der Normalverteilung, also normalverteilter als\njede echte Stichprobe je sein könnte. In erhobenen Daten kommt ein solcher Wert\nnicht vor.\n:::\n\n#### Interpretation\n\nGenau deshalb steht auf den Methodenseiten dieser Sammlung durchgehend der\nQQ-Plot in der Voraussetzungsprüfung und nicht ein Normalitätstest. Der Plot\nkostet dieselbe Zeile Code und beantwortet die nützlichere Frage.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nBei n = 1000 liefert Shapiro-Wilk p < 0.001, der QQ-Plot zeigt eine leichte\nKrümmung an den Enden. Was folgt für einen geplanten t-Test?\n\n- [x] Nichts; bei diesem Umfang ist der Mittelwert praktisch normalverteilt ~\n      Richtig. Der zentrale Grenzwertsatz greift, und der t-Test setzt die\n      Normalverteilung des Mittelwerts voraus, nicht die der Rohdaten. Der\n      signifikante Test spiegelt vor allem den Umfang wider.\n- [ ] Der t-Test ist unzulässig, es muss rangbasiert getestet werden ~ Das wäre\n      der Wechsel des Verfahrens aufgrund einer Zahl, die hier gerade keine\n      inhaltliche Aussage trägt.\n- [ ] Die Daten müssen transformiert werden ~ Eine Transformation ändert die\n      Fragestellung; sie ist bei starker Schiefe sinnvoll, nicht bei einer\n      Abweichung dieser Grössenordnung.\n:::\n\n::: {.quiz}\nEin Shapiro-Test bei n = 15 liefert p = 0.10. Was ist die zulässige Aussage?\n\n- [x] Die Daten sprechen nicht gegen eine Normalverteilung, mehr nicht ~\n      Richtig. Bei fünfzehn Werten hätte der Test selbst eine deutliche Schiefe\n      wahrscheinlich nicht gefunden, wie Beispiel 3 zeigt. Ein grosser p-Wert\n      ist kein Nachweis.\n- [ ] Die Daten sind normalverteilt ~ Eine Nullhypothese wird nie bewiesen,\n      schon gar nicht mit geringer Power.\n- [ ] Die Daten sind nicht normalverteilt, p liegt nahe 0.05 ~ Die Nähe zur\n      Schwelle ist keine Zwischenkategorie.\n:::\n\n::: {.quiz}\nDerselbe Datensatz liefert bei Shapiro-Wilk p < 0.001 und bei\nKolmogorow-Smirnow p = 0.25. Wie ist das zu deuten?\n\n- [x] Der KS-Test ist in dieser Form deutlich schwächer ~ Richtig. Er schätzt\n      Mittelwert und Streuung aus denselben Daten, für die er prüft, und passt\n      sich der Verteilung damit teilweise an. Ohne Lilliefors-Korrektur ist er\n      zu konservativ.\n- [ ] Die beiden Tests prüfen verschiedene Verteilungen ~ Beide prüfen gegen\n      die Normalverteilung.\n- [ ] Der grössere p-Wert ist der verlässlichere ~ Die Wahl nach dem\n      angenehmeren Ergebnis ist keine Begründung.\n:::\n\n::: {.quiz}\nWarum steht auf den Methodenseiten dieser Sammlung der QQ-Plot und nicht ein\nNormalitätstest in der Voraussetzungsprüfung?\n\n- [x] Weil er zeigt, **wie** die Verteilung abweicht, und nicht nur, dass sie\n      es tut ~ Richtig. Rechtsschiefe, schwere Ränder und ein einzelner\n      Ausreisser erfordern drei verschiedene Reaktionen, und der p-Wert\n      unterscheidet sie nicht.\n- [ ] Weil Normalitätstests unzuverlässig rechnen ~ Sie rechnen korrekt; das\n      Problem liegt in der Fragestellung und in der Abhängigkeit vom Umfang.\n- [ ] Weil der QQ-Plot objektiver ist ~ Er verlangt im Gegenteil eine\n      Beurteilung durch den Betrachter. Sein Vorteil ist der Informationsgehalt,\n      nicht die Objektivität.\n:::\n\n## Verlinkte Ressourcen\n\n- [QQ-Plots](../wahrscheinlichkeit/qq-plots.qmd)\n- [R-Dokumentation zu `shapiro.test`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/shapiro.test.html)\n- [scipy: shapiro](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.shapiro.html)\n",
    "supporting": [
      "normalitaetstests_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}