{
  "hash": "a99b0a96acd70b6f273bdde48c928765",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Diagrammtyp wählen\"\ndescription: \"Vom Datentyp und der Botschaft zur passenden Darstellung.\"\ncategories: [\"Visualisierung\", \"Wahrnehmung\", \"R\", \"Python\"]\nquelle: [\"DAVI\"]\nseitentyp: konzept\nstand: fertig\norder: 30\n---\n\n\n\n\n\n## Kernideen\n\n- Die Wahl folgt der **Aufgabe**, nicht dem Aussehen.\n- Sechs Aufgaben decken fast alles ab: Mengen, Verteilungen, Anteile,\n  Zusammenhänge, Verläufe, Unsicherheit.\n- Das **Skalenniveau** entscheidet, welche Darstellung überhaupt zulässig ist.\n- Ordinale Reihenfolgen sind Information und werden nie alphabetisch sortiert.\n- Ein **Boxplot** zeigt fünf Zahlen und verbirgt die Form, auch dann, wenn die\n  Daten in der Nähe des Medians fast leer sind.\n- Ab einigen tausend Punkten zeigt ein Streudiagramm nicht mehr die Daten,\n  sondern nur noch den zuletzt gezeichneten Punkt je Bildschirmstelle.\n- Nicht beim Lieblingsdiagramm anfangen, sondern bei der Aussage.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Wahrnehmung und Kodierung](wahrnehmung-kodierung.qmd) für die\nRangfolge der Kanäle und [Skalenniveaus](../statistik/grundlagen/skalenniveaus.qmd)\nfür die Frage, was mit welchen Daten zulässig ist. Umgesetzt wird die Wahl mit\n[ggplot2](ggplot2.qmd), [matplotlib](matplotlib.qmd) oder\n[seaborn und plotly](seaborn-plotly.qmd).\n:::\n\n### Zuerst die Aufgabe bestimmen\n\nDie Frage lautet nicht \"welches Diagramm sieht gut aus\", sondern \"welche Art von\nAussage soll transportiert werden\". Sechs Aufgaben decken den Alltag ab:\n\n| Aufgabe | Typische Frage | Kandidaten |\n|---|---|---|\n| Mengen vergleichen | Wer ist grösser, wie viel liegt dazwischen? | Balken, sortierter Punktplot, Heatmap |\n| Verteilung zeigen | Wie streuen die Werte, gibt es mehrere Gipfel? | Histogramm, Dichtekurve, Boxplot, Violinplot, empirische Verteilungsfunktion |\n| Anteile zeigen | Wie verteilt sich ein Ganzes? | gestapelter Balken, Torte bei wenigen Teilen, Mosaik, Treemap |\n| Zusammenhang zeigen | Hängen zwei Grössen zusammen? | Streudiagramm, Blasendiagramm, Steigungsdiagramm |\n| Verlauf zeigen | Wie entwickelt sich etwas über die Zeit? | Liniendiagramm, Flächendiagramm, Kalender-Heatmap |\n| Unsicherheit zeigen | Wie genau ist die Schätzung? | Fehlerbalken, Konfidenzband, Quantilpunkte |\n\nDer Weg ist immer derselbe: Aussage formulieren, Aufgabe zuordnen, aus den\nKandidaten den einfachsten wählen, der die Aussage trägt.\n\n### Dann das Skalenniveau prüfen\n\n| Datentyp | Beispiel | Zulässig | Nicht zulässig |\n|---|---|---|---|\n| kontinuierlich | Temperatur, Umsatz, Dauer | Position, Länge, Fläche, Farbverlauf | |\n| diskret gezählt | Stückzahl, Anzahl Personen | wie kontinuierlich | zwischen den Punkten interpolieren |\n| kategorial mit Ordnung | Note, klein/mittel/gross | Position, sequenzieller Farbverlauf | alphabetisch sortieren |\n| kategorial ohne Ordnung | Standort, Produktgruppe | Form, qualitative Palette | Farbverlauf, der eine Rangfolge suggeriert |\n\nDrei Regeln fallen daraus:\n\n1. **Ordinale Reihenfolge erhalten.** \"klein, mittel, gross\" alphabetisch\n   sortiert ergibt \"gross, klein, mittel\" und macht die Grafik unlesbar.\n2. **Nominale Daten nicht mit Verlaufsfarben.** Ein Verlauf behauptet eine\n   Ordnung, die es nicht gibt.\n3. **Ab etwa sieben Kategorien** ist Farbe als Unterscheidungskanal am Ende.\n   Dann trennt Position, etwa als sortierte Balken oder kleine Teilgrafiken.\n\n### Die drei häufigsten Fehlgriffe\n\n**Torte statt Balken.** Winkel liest sich schlechter als Länge. Eine Torte\nfunktioniert bei zwei, höchstens drei Teilen und wenn es um \"ungefähr die\nHälfte\" geht, nicht um Rangfolgen. Durchgerechnet unter\n[Wahrnehmung und Kodierung, Beispiel 1](wahrnehmung-kodierung.qmd).\n\n**Linie über kategoriale Achsen.** Eine Linie behauptet, dass es zwischen den\nPunkten Werte gibt. Zwischen \"Bern\" und \"Chur\" gibt es keine.\n\n**Doppelachse für zwei Grössen.** Die zweite Achse ist frei skalierbar, also ist\nauch der suggerierte Gleichlauf frei erfunden, siehe\n[irreführende Darstellungen](irrefuehrende-darstellungen.qmd). Besser sind zwei\nTeilgrafiken übereinander mit gemeinsamer Zeitachse.\n\n### Wenn es viele Beobachtungen sind\n\nAb einigen tausend Punkten überdecken sich die Marken im Streudiagramm, und man\nsieht nur noch eine Wolke. Drei Auswege, in dieser Reihenfolge:\n\n1. Transparenz und kleinere Punkte\n2. Binning: Sechsecke oder Kacheln statt Punkte\n3. Zusammenfassen: Dichtekonturen oder eine Glättungslinie über die Punkte\n\nBeispiel 2 beziffert, wie viel dabei auf dem Spiel steht.\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Was der Boxplot verbirgt\n\n#### Frage und Datenlage\n\nZwei Verteilungen mit je 300 Werten: eine eingipflige um 50 und eine\nzweigipflige mit Schwerpunkten bei 38 und 62. Beide haben denselben\nMittelwert. Was zeigt der Boxplot davon?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nZ <- normalmatrix(1212, 2, 300)\neinfach <- 50 + Z[1, ] * 10\nzweigipflig <- c(38 + Z[2, 1:150] * 4, 62 + Z[2, 151:300] * 4)\n\nfor (nm in c(\"einfach\", \"zweigipflig\")) {\n  x <- get(nm)\n  q <- quantile(x, c(0, 0.25, 0.5, 0.75, 1))\n  cat(sprintf(\"%-12s min %6.2f  Q1 %6.2f  Median %6.2f  Q3 %6.2f  max %6.2f  Mittel %6.2f  SD %5.2f\\n\",\n              nm, q[1], q[2], q[3], q[4], q[5], mean(x), sd(x)))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\neinfach      min  17.10  Q1  43.70  Median  50.13  Q3  57.26  max  77.10  Mittel  50.05  SD  9.87\nzweigipflig  min  25.51  Q1  38.53  Median  50.95  Q3  61.97  max  73.47  Mittel  50.17  SD 13.00\n```\n\n\n:::\n\n```{.r .cell-code}\n# Wie viele Werte liegen ueberhaupt in der Naehe des Medians?\nround(c(einfach_band_46_54 = mean(einfach > 46 & einfach < 54) * 100,\n        zweigipflig_band_46_54 = mean(zweigipflig > 46 & zweigipflig < 54) * 100), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    einfach_band_46_54 zweigipflig_band_46_54 \n                  29.7                    1.7 \n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(2, 2), mar = c(4, 4, 2.5, 1))\nboxplot(einfach, horizontal = TRUE, ylim = c(15, 80), col = neutral,\n        main = \"eingipflig, Boxplot\")\nboxplot(zweigipflig, horizontal = TRUE, ylim = c(15, 80), col = neutral,\n        main = \"zweigipflig, Boxplot\")\nhist(einfach, breaks = 25, xlim = c(15, 80), col = neutral, border = \"white\",\n     main = \"eingipflig, Histogramm\", xlab = \"Wert\")\nhist(zweigipflig, breaks = 25, xlim = c(15, 80), col = neutral, border = \"white\",\n     main = \"zweigipflig, Histogramm\", xlab = \"Wert\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 1: oben die Boxplots, unten dieselben Daten als Histogramm.](diagrammtyp-waehlen_files/figure-html/fig-b1-dt-r-1.png){#fig-b1-dt-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nZ = normalmatrix(1212, 2, 300)\neinfach = 50 + Z[0] * 10\nzweigipflig = np.concatenate([38 + Z[1][:150] * 4, 62 + Z[1][150:] * 4])\n\nfor name, x in [(\"einfach\", einfach), (\"zweigipflig\", zweigipflig)]:\n    q = np.percentile(x, [0, 25, 50, 75, 100])\n    print(f\"{name:<12} min {q[0]:6.2f}  Q1 {q[1]:6.2f}  Median {q[2]:6.2f}\"\n          f\"  Q3 {q[3]:6.2f}  max {q[4]:6.2f}\"\n          f\"  Mittel {x.mean():6.2f}  SD {x.std(ddof=1):5.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\neinfach      min  17.10  Q1  43.70  Median  50.13  Q3  57.26  max  77.10  Mittel  50.05  SD  9.87\nzweigipflig  min  25.51  Q1  38.53  Median  50.95  Q3  61.97  max  73.47  Mittel  50.17  SD 13.00\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"einfach_band_46_54\":\n           round(float(((einfach > 46) & (einfach < 54)).mean() * 100), 1),\n       \"zweigipflig_band_46_54\":\n           round(float(((zweigipflig > 46) & (zweigipflig < 54)).mean() * 100), 1)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'einfach_band_46_54': 29.7, 'zweigipflig_band_46_54': 1.7}\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(2, 2, figsize=(7, 4.4))\nfor spalte, (name, x) in enumerate([(\"eingipflig\", einfach),\n                                    (\"zweigipflig\", zweigipflig)]):\n    _ = achsen[0, spalte].boxplot(x, vert=False, widths=0.6)\n    _ = achsen[0, spalte].set_xlim(15, 80)\n    _ = achsen[0, spalte].set_title(f\"{name}, Boxplot\", fontsize=10)\n    _ = achsen[1, spalte].hist(x, bins=25, range=(15, 80), color=NEUTRAL,\n                               edgecolor=\"white\")\n    _ = achsen[1, spalte].set_title(f\"{name}, Histogramm\", fontsize=10)\n    _ = achsen[1, spalte].set_xlabel(\"Wert\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Gegenüberstellung in Python.](diagrammtyp-waehlen_files/figure-html/fig-b1-dt-py-1.png){#fig-b1-dt-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Verteilung | Minimum | Q1 | Median | Q3 | Maximum | Mittel | SD |\n|---|---|---|---|---|---|---|---|\n| eingipflig | 17.10 | 43.70 | **50.13** | 57.26 | 77.10 | 50.05 | 9.87 |\n| zweigipflig | 25.51 | 38.53 | **50.95** | 61.97 | 73.47 | 50.17 | 13.00 |\n\n| Anteil im Band 46 bis 54 | |\n|---|---|\n| eingipflig | **29.7 Prozent** |\n| zweigipflig | **1.7 Prozent** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Die Mediane liegen bei **50.13 und 50.95** | Praktisch gleich, und beide Mittelwerte bei 50.1. Die fünf Kennzahlen des Boxplots unterscheiden sich nur in der Breite der Box. |\n| **Nur 1.7 Prozent** der zweigipfligen Werte liegen in der Nähe ihres Medians | Gegen 29.7 Prozent bei der eingipfligen. **Der Median der zweigipfligen Verteilung liegt in einem Bereich, in dem fast keine Daten sind**, er ist rechnerisch korrekt und inhaltlich irreführend. |\n| Die grössere SD ist der einzige Hinweis | 13.00 gegen 9.87. Wer nur die Kennzahlen sieht, hält die zweite Verteilung für etwas breiter gestreut, nicht für zweigipflig. |\n| Das Histogramm zeigt es **sofort** | Zwei Berge mit einem Tal dazwischen. Kein Nachdenken nötig. |\n| Der Boxplot bleibt trotzdem nützlich | Für den Vergleich **vieler** Gruppen: kompakt, und Lage und Streuung sind über Position vergleichbar. Bei wenigen Gruppen ist die Form wichtiger. |\n\n::: {.note-box}\n**Die Entscheidungsregel für Verteilungen:**\n\n| Anzahl Gruppen | Empfehlung |\n|---|---|\n| 1 bis 3 | Histogramm oder Dichtekurve, die Form ist die Aussage |\n| 4 bis 10 | Violinplot oder Boxplot **mit** überlagerten Punkten |\n| mehr als 10 | Boxplot, sortiert nach Median |\n\nDer Zusatz \"mit überlagerten Punkten\" ist der billigste Gewinn der ganzen\nListe: Er kostet eine Codezeile und hätte den zweiten Gipfel sichtbar gemacht.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Beide Verteilungen haben einen Mittelwert um 50.1 und Mediane von 50.13 und\n> 50.95. In der Nähe des Medians liegen jedoch 29.7 Prozent der eingipfligen,\n> aber nur 1.7 Prozent der zweigipfligen Werte, ein Unterschied, den der\n> Boxplot nicht zeigt und das Histogramm sofort.\n\n### Beispiel 2: Wie viele Punkte ein Streudiagramm verschluckt\n\n#### Frage und Datenlage\n\n5000 Punkte in einem Streudiagramm. Die Frage ist nicht, ob es unübersichtlich\nwird, sondern **wie viele Punkte überhaupt noch sichtbar sind**. Gezählt wird\nüber ein Raster in der Grössenordnung einer Punktmarke.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 5000\nZ <- normalmatrix(5566, 2, n)\nx <- 50 + Z[1, ] * 10\ny <- 0.6 * x + 20 + Z[2, ] * 8\nround(c(korrelation = cor(x, y)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nkorrelation \n     0.6036 \n```\n\n\n:::\n\n```{.r .cell-code}\nfor (zellen in c(60, 120)) {\n  ix <- floor((x - min(x)) / (max(x) - min(x)) * (zellen - 1e-9))\n  iy <- floor((y - min(y)) / (max(y) - min(y)) * (zellen - 1e-9))\n  schluessel <- ix * zellen + iy\n  belegt <- length(unique(schluessel))\n  cat(sprintf(\"Raster %3dx%3d: %4d belegte Zellen, %4.1f Prozent der Punkte verdeckt, dichteste Zelle %2d Punkte\\n\",\n              zellen, zellen, belegt, 100 * (1 - belegt / n),\n              max(table(schluessel))))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRaster  60x 60: 1021 belegte Zellen, 79.6 Prozent der Punkte verdeckt, dichteste Zelle 23 Punkte\nRaster 120x120: 2451 belegte Zellen, 51.0 Prozent der Punkte verdeckt, dichteste Zelle 10 Punkte\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 3), mar = c(4, 4, 3, 1))\nplot(x, y, pch = 16, cex = 0.7, col = \"grey25\", main = \"roh\")\nplot(x, y, pch = 16, cex = 0.7, col = adjustcolor(\"grey25\", alpha.f = 0.08),\n     main = \"Transparenz 0.08\")\nsmoothScatter(x, y, main = \"Dichte\", xlab = \"x\", ylab = \"y\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselben 5000 Punkte roh, mit Transparenz und als Sechseckraster.](diagrammtyp-waehlen_files/figure-html/fig-b2-dt-r-3.png){#fig-b2-dt-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nn = 5000\nZ = normalmatrix(5566, 2, n)\nx = 50 + Z[0] * 10\ny = 0.6 * x + 20 + Z[1] * 8\nprint({\"korrelation\": round(float(np.corrcoef(x, y)[0, 1]), 4)})\n\nfor zellen in (60, 120):\n    ix = np.floor((x - x.min()) / (x.max() - x.min()) * (zellen - 1e-9)).astype(int)\n    iy = np.floor((y - y.min()) / (y.max() - y.min()) * (zellen - 1e-9)).astype(int)\n    schluessel = ix * zellen + iy\n    _, anzahl = np.unique(schluessel, return_counts=True)\n    belegt = len(anzahl)\n    print(f\"Raster {zellen:3d}x{zellen:3d}: {belegt:4d} belegte Zellen,\"\n          f\" {100 * (1 - belegt / n):4.1f} Prozent der Punkte verdeckt,\"\n          f\" dichteste Zelle {anzahl.max():2d} Punkte\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRaster  60x 60: 1021 belegte Zellen, 79.6 Prozent der Punkte verdeckt, dichteste Zelle 23 Punkte\nRaster 120x120: 2451 belegte Zellen, 51.0 Prozent der Punkte verdeckt, dichteste Zelle 10 Punkte\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(1, 3, figsize=(7, 3.2))\n_ = achsen[0].scatter(x, y, s=5, color=\"0.25\")\n_ = achsen[0].set_title(\"roh\")\n_ = achsen[1].scatter(x, y, s=5, color=\"0.25\", alpha=0.08)\n_ = achsen[1].set_title(\"Transparenz 0.08\")\n_ = achsen[2].hexbin(x, y, gridsize=40, cmap=\"Greys\")\n_ = achsen[2].set_title(\"Sechseckraster\")\nfor achse in achsen:\n    _ = achse.set_xlabel(\"x\")\n    _ = achse.set_ylabel(\"y\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselben drei Darstellungen in Python.](diagrammtyp-waehlen_files/figure-html/fig-b2-dt-py-1.png){#fig-b2-dt-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Raster | belegte Zellen | verdeckte Punkte | dichteste Zelle |\n|---|---|---|---|\n| 60 × 60 | 1021 von 5000 | **79.6 Prozent** | **23 Punkte** |\n| 120 × 120 | 2451 von 5000 | **51.0 Prozent** | 10 Punkte |\n\nKorrelation zwischen x und y: **0.6036**.\n\n| Beobachtung | Erklärung |\n|---|---|\n| Bei grober Auflösung sind **fast 80 Prozent** der Punkte unsichtbar | Sie liegen auf einer Stelle, die schon belegt ist. Man sieht also 1021 Punkte und glaubt, 5000 zu sehen. |\n| Selbst bei feiner Auflösung ist es die **Hälfte** | 51 Prozent bei 120 × 120 Zellen. Das Problem verschwindet nicht durch eine grössere Grafik, es wird nur kleiner. |\n| In der dichtesten Zelle liegen **23 Punkte** | Ein einzelner sichtbarer Punkt steht dort für 23. Genau in der Mitte der Wolke, wo die meiste Information wäre. |\n| Das verzerrt den **Eindruck der Form** | Der Rand der Wolke ist dünn besetzt und daher vollständig sichtbar, die Mitte ist dicht und wird auf einen Punkt reduziert. **Ein rohes Streudiagramm zeigt systematisch die Ausreisser und unterschlägt die Masse.** |\n| Transparenz und Raster lösen dasselbe Problem verschieden | Transparenz behält die einzelnen Punkte und macht Dichte über Helligkeit sichtbar; das Raster gibt die Einzelpunkte auf und zeigt Dichte als Zahl je Zelle. |\n\n::: {.note-box}\n**Welcher Ausweg wann:**\n\n| Punktzahl | Mittel |\n|---|---|\n| bis ~1000 | kleinere Punkte genügen meist |\n| 1000 bis ~20 000 | Transparenz, Wert um 0.05 bis 0.2 |\n| ab ~20 000 | Sechseckraster (`geom_hex`, `ax.hexbin`) oder Dichtekonturen |\n| beliebig viele, wenn es um den Trend geht | Glättungslinie über eine ausgedünnte Punktwolke |\n\nDie Transparenz ist so zu wählen, dass die **dichteste Stelle gerade noch nicht\ngesättigt** ist, hier also etwa 1/23, entsprechend 0.04 bis 0.08.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Von 5000 Punkten sind bei einer Auflösung von 60 × 60 Zellen nur 1021 Stellen\n> belegt: 79.6 Prozent der Punkte liegen auf einer bereits gezeichneten\n> Position, in der dichtesten Zelle 23 übereinander. Die Verdeckung trifft\n> systematisch die dichte Mitte und nicht die Ränder.\n\n### Beispiel 3: Was alphabetische Sortierung zerstört\n\n#### Frage und Datenlage\n\nEine Zufriedenheitsumfrage mit 500 Antworten auf fünf ordinalen Stufen. Einmal\nin der natürlichen Reihenfolge dargestellt, einmal alphabetisch sortiert und\ndie Frage, was dabei messbar verloren geht.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstufen <- c(\"sehr unzufrieden\", \"unzufrieden\", \"neutral\",\n            \"zufrieden\", \"sehr zufrieden\")\nanzahl <- c(18, 44, 91, 165, 182)\n\nreihenfolge <- order(stufen)\ndata.frame(alphabetisch = stufen[reihenfolge], anzahl = anzahl[reihenfolge])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      alphabetisch anzahl\n1          neutral     91\n2 sehr unzufrieden     18\n3   sehr zufrieden    182\n4      unzufrieden     44\n5        zufrieden    165\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(spearman_natuerlich = cor(1:5, anzahl, method = \"spearman\"),\n        spearman_alphabetisch = cor(1:5, anzahl[reihenfolge], method = \"spearman\"),\n        anteil_zufrieden_oder_besser = sum(anzahl[4:5]) / sum(anzahl) * 100), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         spearman_natuerlich        spearman_alphabetisch \n                         1.0                          0.3 \nanteil_zufrieden_oder_besser \n                        69.4 \n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(9, 4, 3, 1))\nbarplot(anzahl, names.arg = stufen, las = 2, col = neutral, border = NA,\n        ylab = \"Antworten\", main = \"natürliche Reihenfolge\")\nbarplot(anzahl[reihenfolge], names.arg = stufen[reihenfolge], las = 2,\n        col = akzent, border = NA, ylab = \"Antworten\", main = \"alphabetisch\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 3: links die natürliche Reihenfolge, rechts alphabetisch.](diagrammtyp-waehlen_files/figure-html/fig-b3-dt-r-3.png){#fig-b3-dt-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nstufen = [\"sehr unzufrieden\", \"unzufrieden\", \"neutral\",\n          \"zufrieden\", \"sehr zufrieden\"]\nanzahl = np.array([18, 44, 91, 165, 182])\n\nreihenfolge = sorted(range(5), key=lambda i: stufen[i])\nprint(pd.DataFrame({\"alphabetisch\": [stufen[i] for i in reihenfolge],\n                    \"anzahl\": anzahl[reihenfolge]}).to_string(index=False))\n\nprint({\"spearman_natuerlich\":\n           round(float(stats.spearmanr(np.arange(5), anzahl).statistic), 4),\n       \"spearman_alphabetisch\":\n           round(float(stats.spearmanr(np.arange(5), anzahl[reihenfolge]).statistic), 4),\n       \"anteil_zufrieden_oder_besser\":\n           round(float(anzahl[3:].sum() / anzahl.sum() * 100), 4)})\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.6))\n_ = achsen[0].bar(stufen, anzahl, color=NEUTRAL)\n_ = achsen[0].set_title(\"natürliche Reihenfolge\")\n_ = achsen[1].bar([stufen[i] for i in reihenfolge], anzahl[reihenfolge],\n                  color=AKZENT)\n_ = achsen[1].set_title(\"alphabetisch\")\nfor achse in achsen:\n    _ = achse.set_ylabel(\"Antworten\")\n    _ = achse.tick_params(axis=\"x\", rotation=90)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselbe Gegenüberstellung in Python.](diagrammtyp-waehlen_files/figure-html/fig-b3-dt-py-1.png){#fig-b3-dt-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| natürliche Reihenfolge | sehr unzufrieden | unzufrieden | neutral | zufrieden | sehr zufrieden |\n|---|---|---|---|---|---|\n| Antworten | 18 | 44 | 91 | 165 | 182 |\n\n| alphabetisch | neutral | sehr unzufrieden | sehr zufrieden | unzufrieden | zufrieden |\n|---|---|---|---|---|---|\n| Antworten | 91 | 18 | 182 | 44 | 165 |\n\n| Kennzahl | Wert |\n|---|---|\n| Spearman (Position gegen Anzahl), natürlich | **1.0000** |\n| Spearman, alphabetisch | **0.3000** |\n| Anteil \"zufrieden\" oder besser | 69.4 Prozent |\n\n| Beobachtung | Erklärung |\n|---|---|\n| In der natürlichen Reihenfolge steigen die Balken **monoton** | Spearman genau 1.0. Die Aussage \"je zufriedener, desto häufiger\" ist die Form der Grafik selbst, man muss keine Zahl lesen. |\n| Alphabetisch sinkt der Zusammenhang auf **0.3** | Aus einer Treppe wird ein Zickzack. Dieselben fünf Zahlen, dieselben fünf Balken. |\n| Die beiden **\"sehr\"-Stufen** landen nebeneinander | \"sehr unzufrieden\" (18) direkt neben \"sehr zufrieden\" (182), die beiden Extreme der Skala, weil beide mit \"sehr\" beginnen. |\n| Der Fehler entsteht **von allein** | Weder R noch Python kennen die Reihenfolge einer Zeichenkette. Wer nichts angibt, bekommt die alphabetische. **Das ist die Voreinstellung, nicht die Entscheidung.** |\n| Die Rettung ist ein **Faktor** mit gesetzten Stufen | `factor(x, levels = stufen)` in R, `pd.Categorical(x, categories=stufen, ordered=True)` in Python. |\n\n::: {.warning-box}\n**Die alphabetische Sortierung hängt zudem an der Spracheinstellung.** Gross-\nund Kleinschreibung, Umlaute und länderspezifische Regeln führen zu\nverschiedenen Reihenfolgen auf verschiedenen Rechnern, dieselbe Grafik sieht\ndann woanders anders aus.\n\nAuf dieser Seite sind alle Stufen klein geschrieben und ohne Umlaute, damit R\nund Python garantiert dieselbe Reihenfolge liefern. Das ist ein Umweg um das\nProblem, keine Lösung: **Die Lösung ist, die Reihenfolge festzulegen.**\n\nMehr zum Thema unter\n[Skalenniveaus](../statistik/grundlagen/skalenniveaus.qmd).\n:::\n\n#### Interpretation und Ergebnissatz\n\n> In der natürlichen Reihenfolge steigen die Antwortzahlen monoton, der\n> Rangkorrelationskoeffizient zwischen Position und Anzahl beträgt 1.0.\n> Alphabetisch sortiert sinkt er auf 0.3, und die Extremstufen \"sehr\n> unzufrieden\" und \"sehr zufrieden\" stehen nebeneinander.\n\n### Beispiel 4: Gestapelt oder gruppiert\n\n#### Frage und Datenlage\n\nVier Regionen mit je drei Produktgruppen. Die Frage: In welcher Region ist die\nProduktgruppe B am stärksten? Einmal als gestapelter Balken, einmal gruppiert.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregionen <- c(\"Nord\", \"Sued\", \"Ost\", \"West\")\nmat <- rbind(Nord = c(30, 25, 20), Sued = c(28, 31, 18),\n             Ost = c(26, 24, 29), West = c(32, 22, 21))\ncolnames(mat) <- c(\"A\", \"B\", \"C\")\nmat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      A  B  C\nNord 30 25 20\nSued 28 31 18\nOst  26 24 29\nWest 32 22 21\n```\n\n\n:::\n\n```{.r .cell-code}\nc(groesste_B = regionen[which.max(mat[, \"B\"])],\n  wert = max(mat[, \"B\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngroesste_B       wert \n    \"Sued\"       \"31\" \n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(spannweite_der_startlinien = max(mat[, \"A\"]) - min(mat[, \"A\"]),\n        unterschied_in_B = max(mat[, \"B\"]) - min(mat[, \"B\"])), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nspannweite_der_startlinien           unterschied_in_B \n                         6                          9 \n```\n\n\n:::\n\n```{.r .cell-code}\nfarben <- c(\"grey45\", akzent, \"grey80\")\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nbarplot(t(mat), col = farben, border = NA, ylab = \"Umsatz\",\n        main = \"gestapelt\", legend.text = colnames(mat),\n        args.legend = list(x = \"topright\", bty = \"n\", cex = 0.8))\nbarplot(t(mat), beside = TRUE, col = farben, border = NA, ylab = \"Umsatz\",\n        main = \"gruppiert\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 4: links gestapelt, rechts gruppiert.](diagrammtyp-waehlen_files/figure-html/fig-b4-dt-r-3.png){#fig-b4-dt-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nregionen = [\"Nord\", \"Sued\", \"Ost\", \"West\"]\nmat = pd.DataFrame([[30, 25, 20], [28, 31, 18], [26, 24, 29], [32, 22, 21]],\n                   index=regionen, columns=[\"A\", \"B\", \"C\"], dtype=float)\nprint(mat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         A     B     C\nNord  30.0  25.0  20.0\nSued  28.0  31.0  18.0\nOst   26.0  24.0  29.0\nWest  32.0  22.0  21.0\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"groesste_B\": regionen[int(np.argmax(mat[\"B\"]))],\n       \"wert\": float(mat[\"B\"].max())})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'groesste_B': 'Sued', 'wert': 31.0}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"spannweite_der_startlinien\": float(mat[\"A\"].max() - mat[\"A\"].min()),\n       \"unterschied_in_B\": float(mat[\"B\"].max() - mat[\"B\"].min())})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'spannweite_der_startlinien': 6.0, 'unterschied_in_B': 9.0}\n```\n\n\n:::\n\n```{.python .cell-code}\nfarben = [\"0.45\", AKZENT, \"0.80\"]\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.4))\nunten = np.zeros(4)\nfor spalte, farbe in zip(mat.columns, farben):\n    _ = achsen[0].bar(regionen, mat[spalte], bottom=unten, color=farbe,\n                      label=spalte)\n    unten = unten + mat[spalte].to_numpy()\n_ = achsen[0].set_title(\"gestapelt\")\n_ = achsen[0].legend(frameon=False, fontsize=8)\nbreite = 0.26\nfor k, (spalte, farbe) in enumerate(zip(mat.columns, farben)):\n    _ = achsen[1].bar(np.arange(4) + (k - 1) * breite, mat[spalte],\n                      width=breite, color=farbe, label=spalte)\n_ = achsen[1].set_xticks(np.arange(4), regionen)\n_ = achsen[1].set_title(\"gruppiert\")\nfor achse in achsen:\n    _ = achse.set_ylabel(\"Umsatz\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselbe Gegenüberstellung in Python.](diagrammtyp-waehlen_files/figure-html/fig-b4-dt-py-1.png){#fig-b4-dt-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Region | A | B | C |\n|---|---|---|---|\n| Nord | 30 | 25 | 20 |\n| **Sued** | 28 | **31** | 18 |\n| Ost | 26 | 24 | 29 |\n| West | 32 | 22 | 21 |\n\n| Kennzahl | Wert |\n|---|---|\n| Region mit dem grössten B | **Sued (31)** |\n| Spannweite der Startlinien von B (= Höhe von A) | **6.0** |\n| Unterschied in B, grösste minus kleinste Region | **9.0** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Im gestapelten Balken hat **nur A** eine gemeinsame Grundlinie | A liegt unten und lässt sich über Position vergleichen, Rang 1 der Kanalrangfolge. B und C schweben und lassen sich nur über Länge vergleichen, Rang 3. |\n| Die Startlinien von B schwanken um **6.0** | Bei einem echten Unterschied in B von **9.0**. Die Störgrösse ist also zwei Drittel so gross wie das Signal, deshalb ist \"welche Region hat das grösste B\" im gestapelten Balken kaum zu beantworten. |\n| Gruppiert ist die Antwort **sofort** da | Alle B-Balken stehen auf derselben Grundlinie. Sued ragt heraus. |\n| Der gestapelte Balken kann dafür etwas anderes | Er zeigt die **Summe** je Region auf einen Blick, was der gruppierte nicht kann. |\n| Es gibt keinen Sieger, nur eine Frage | \"Wie gross ist das Ganze?\" → gestapelt. \"Wie vergleichen sich die Teile?\" → gruppiert. **Wer beides braucht, zeichnet beides.** |\n\n::: {.note-box}\n**Die Sonderregel für gestapelte Balken:** Die Reihenfolge der Segmente ist\neine Entscheidung. Die Kategorie, auf die es ankommt, gehört **nach unten**,\ndamit sie die gemeinsame Grundlinie bekommt.\n\nBei gestapelten Balken mit **Anteilen** (alle Stapel gleich hoch) verschwindet\ndas Problem für das unterste **und** das oberste Segment, beide haben eine\nGrundlinie. Nur die Mitte bleibt schwer lesbar. Bei mehr als drei bis vier\nSegmenten ist ein Stapel ohnehin nicht mehr zu lesen; dann sind kleine\nTeilgrafiken die bessere Wahl.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Produktgruppe B ist in Sued mit 31 am grössten; der Unterschied zur\n> schwächsten Region beträgt 9.0. Im gestapelten Balken schwanken die\n> Startlinien von B jedoch um 6.0, sodass der Vergleich dort kaum möglich ist,\n> im gruppierten Balken steht er auf gemeinsamer Grundlinie.\n\n### Beispiel 5: Balken ohne Unsicherheit\n\n#### Frage und Datenlage\n\nZwei Gruppen zu je 40 Messungen, Mittelwerte 10.18 und 11.55. Ein\nBalkendiagramm zeigt zwei Balken verschiedener Höhe. Trägt es die Aussage\n\"B ist grösser als A\"?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nZ <- normalmatrix(8899, 2, 40)\na <- 10.2 + Z[1, ] * 3\nb <- 11.8 + Z[2, ] * 3\n\nkennzahl <- function(x) {\n  se <- sd(x) / sqrt(length(x))\n  ki <- qt(0.975, length(x) - 1) * se\n  c(mittel = mean(x), sd = sd(x), se = se,\n    unten = mean(x) - ki, oben = mean(x) + ki)\n}\nround(rbind(A = kennzahl(a), B = kennzahl(b)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  mittel    sd    se  unten   oben\nA 10.179 3.090 0.489  9.191 11.167\nB 11.553 3.283 0.519 10.503 12.603\n```\n\n\n:::\n\n```{.r .cell-code}\ntest <- t.test(b, a, var.equal = TRUE)\nround(c(differenz = mean(b) - mean(a), t = unname(test$statistic),\n        p = test$p.value), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndifferenz         t         p \n   1.3740    1.9275    0.0576 \n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 3), mar = c(4, 4, 3, 1))\nmitten <- c(mean(a), mean(b))\nbarplot(mitten, names.arg = c(\"A\", \"B\"), col = neutral, border = NA,\n        ylim = c(0, 14), ylab = \"Wert\", main = \"nur Mittelwerte\")\n\nmp <- barplot(mitten, names.arg = c(\"A\", \"B\"), col = neutral, border = NA,\n              ylim = c(0, 14), ylab = \"Wert\", main = \"mit 95-Prozent-Intervall\")\ngrenzen <- rbind(kennzahl(a), kennzahl(b))\narrows(mp, grenzen[, \"unten\"], mp, grenzen[, \"oben\"],\n       angle = 90, code = 3, length = 0.08, lwd = 2)\n\nplot(rep(1:2, each = 40) + (lehmer(31, 80) - 0.5) * 0.3, c(a, b),\n     pch = 16, col = adjustcolor(\"grey25\", alpha.f = 0.5), xaxt = \"n\",\n     xlab = \"\", ylab = \"Wert\", main = \"die Daten selbst\", xlim = c(0.5, 2.5))\naxis(1, at = 1:2, labels = c(\"A\", \"B\"))\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Beispiel 5: links nur die Mittelwerte, Mitte mit Konfidenzintervall, rechts die Daten.](diagrammtyp-waehlen_files/figure-html/fig-b5-dt-r-3.png){#fig-b5-dt-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nZ = normalmatrix(8899, 2, 40)\na = 10.2 + Z[0] * 3\nb = 11.8 + Z[1] * 3\n\n\ndef kennzahl(x):\n    se = x.std(ddof=1) / np.sqrt(len(x))\n    ki = stats.t.ppf(.975, len(x) - 1) * se\n    return {\"mittel\": x.mean(), \"sd\": x.std(ddof=1), \"se\": se,\n            \"unten\": x.mean() - ki, \"oben\": x.mean() + ki}\n\n\nprint(pd.DataFrame({\"A\": kennzahl(a), \"B\": kennzahl(b)}).round(3).T)\n\nt, p = stats.ttest_ind(b, a)\nprint({\"differenz\": round(float(b.mean() - a.mean()), 4),\n       \"t\": round(float(t), 4), \"p\": round(float(p), 4)})\n\nkA, kB = kennzahl(a), kennzahl(b)\nmitten = [kA[\"mittel\"], kB[\"mittel\"]]\nfehler = [kA[\"oben\"] - kA[\"mittel\"], kB[\"oben\"] - kB[\"mittel\"]]\n\nfig, achsen = plt.subplots(1, 3, figsize=(7, 3.2))\n_ = achsen[0].bar([\"A\", \"B\"], mitten, color=NEUTRAL)\n_ = achsen[0].set_ylim(0, 14)\n_ = achsen[0].set_title(\"nur Mittelwerte\")\n_ = achsen[1].bar([\"A\", \"B\"], mitten, color=NEUTRAL, yerr=fehler, capsize=5)\n_ = achsen[1].set_ylim(0, 14)\n_ = achsen[1].set_title(\"mit 95-Prozent-Intervall\")\nstreu = (lehmer(31, 80) - 0.5) * 0.3\n_ = achsen[2].scatter(np.repeat([1, 2], 40) + streu, np.concatenate([a, b]),\n                      s=12, color=\"0.25\", alpha=0.5)\n_ = achsen[2].set_xticks([1, 2], [\"A\", \"B\"])\n_ = achsen[2].set_title(\"die Daten selbst\")\nfor achse in achsen:\n    _ = achse.set_ylabel(\"Wert\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselben drei Darstellungen in Python.](diagrammtyp-waehlen_files/figure-html/fig-b5-dt-py-1.png){#fig-b5-dt-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Gruppe | Mittel | SD | Standardfehler | 95-Prozent-Intervall |\n|---|---|---|---|---|\n| A | **10.179** | 3.090 | 0.489 | 9.191 bis 11.167 |\n| B | **11.553** | 3.283 | 0.519 | 10.503 bis 12.603 |\n\n| Kennzahl | Wert |\n|---|---|\n| Differenz | **1.374** |\n| t | 1.9275 |\n| p | **0.0576** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Der reine Balken zeigt einen **klaren** Unterschied | 11.55 gegen 10.18, gut sichtbar. Das Bild behauptet eine Gewissheit, die in den Daten nicht steht. |\n| Die Intervalle **überlappen sich** | 10.503 bis 12.603 gegen 9.191 bis 11.167, der Überlappungsbereich reicht von 10.50 bis 11.17. |\n| Der p-Wert liegt bei **0.0576** | Also knapp über der üblichen Schwelle. Nicht \"kein Unterschied\", aber auch nicht \"nachgewiesen\". |\n| Die Punktwolke zeigt, **warum** | Beide Gruppen streuen mit SD um 3.1 bis 3.3, die Differenz beträgt 1.37. Die Verteilungen überlappen sich fast vollständig. |\n| Der Balken unterschlägt **39 von 40 Werten je Gruppe** | Er zeigt nur den Mittelwert. **Ein Balkendiagramm von Mittelwerten ist die datenärmste Darstellung, die es gibt**, eine Zahl je Balken. |\n\n::: {.warning-box}\n**Die Regel für Mittelwertvergleiche:** Ein Balken ohne Unsicherheitsmass ist\nbei Messdaten fast immer die falsche Wahl.\n\n| Stichprobengrösse | bessere Darstellung |\n|---|---|\n| bis ~30 je Gruppe | **alle Punkte zeigen**, Mittelwert als Strich darüber |\n| 30 bis ~200 | Punkte mit Streuung plus Intervall, oder Boxplot mit Punkten |\n| darüber | Boxplot oder Violinplot mit Intervall des Mittelwerts |\n\nUnd: **Überlappende Konfidenzintervalle sind kein Test.** Sie sind ein\nkonservativer Hinweis, der p-Wert kann trotz Überlappung unter 0.05 liegen.\nDer Test gehört gerechnet, siehe\n[Hypothesentests](../statistik/inferenz/hypothesentests-grundlagen.qmd) und\n[t-Test für zwei Stichproben](../statistik/tests/t-test-zwei-stichproben.qmd).\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Mittelwerte betragen 10.179 und 11.553, die Differenz 1.374. Die\n> 95-Prozent-Intervalle überlappen sich (9.19 bis 11.17 gegen 10.50 bis 12.60) und der\n> t-Test ergibt p = 0.0576. Das reine Balkendiagramm zeigt einen deutlichen\n> Unterschied, den die Daten nicht belegen.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEine Umfrage misst Zufriedenheit auf einer Skala von \"sehr unzufrieden\" bis\n\"sehr zufrieden\". Die Grafik sortiert die Balken alphabetisch. Was ist der\nFehler?\n\n- [x] Die Ordnung der Kategorien ist Information und geht verloren ~ Richtig.\n      Im Beispiel sank die Rangkorrelation zwischen Position und Anzahl von 1.0\n      auf 0.3, und \"sehr zufrieden\" landete direkt neben \"sehr unzufrieden\".\n- [ ] Balken sind für Umfragedaten ungeeignet ~ Sie sind hier passend, nur die\n      Sortierung stimmt nicht.\n- [ ] Die Skala ist zu fein ~ Fünf Stufen sind unproblematisch.\n:::\n\n::: {.quiz}\nZwei Verteilungen haben Mediane von 50.13 und 50.95. Genügt der Boxplot?\n\n- [x] Nein, bei der einen liegen nur 1.7 Prozent der Werte in der Nähe des\n      Medians ~ Richtig. Sie ist zweigipflig, der Median fällt ins Tal\n      dazwischen. Der Boxplot zeigt fünf Zahlen und keine Form; das Histogramm\n      zeigt es sofort.\n- [ ] Ja, gleiche Mediane heissen ähnliche Verteilungen ~ Der Mittelwert war\n      ebenfalls fast gleich, die Formen sind völlig verschieden.\n- [ ] Nein, weil die Standardabweichungen verschieden sind ~ Der Unterschied\n      13.0 gegen 9.9 ist ein Hinweis, erklärt die Zweigipfligkeit aber nicht.\n:::\n\n::: {.quiz}\nEin Streudiagramm mit 5000 Punkten wirkt als dichte Wolke. Wie viele Punkte\nsind tatsächlich sichtbar?\n\n- [x] Rund ein Fünftel, der Rest liegt auf schon belegten Stellen ~ Richtig, im\n      Beispiel 1021 belegte Rasterzellen von 5000 Punkten. In der dichtesten\n      Zelle lagen 23 Punkte übereinander.\n- [ ] Alle, sie überlappen nur ~ Überlappen heisst verdecken; der untere Punkt\n      trägt nichts mehr zum Bild bei.\n- [ ] Das lässt sich nicht bestimmen ~ Über ein Raster in Markengrösse lässt es\n      sich genau auszählen.\n:::\n\n::: {.quiz}\nWarum ist im gestapelten Balken die mittlere Kategorie schwer zu vergleichen?\n\n- [x] Sie hat keine gemeinsame Grundlinie, ihre Startlinie schwankt ~ Richtig.\n      Im Beispiel schwankten die Startlinien um 6.0 bei einem echten\n      Unterschied von 9.0. Nur das unterste Segment liegt auf gemeinsamer\n      Position.\n- [ ] Die Farben sind zu ähnlich ~ Auch mit klar getrennten Farben bliebe das\n      Problem der fehlenden Grundlinie.\n- [ ] Gestapelte Balken sind grundsätzlich falsch ~ Für die Summe je Gruppe\n      sind sie gerade die richtige Wahl.\n:::\n\n::: {.quiz}\nZwei Balken zeigen Mittelwerte von 10.18 und 11.55. Was fehlt?\n\n- [x] Ein Unsicherheitsmass, die Intervalle überlappen sich und p liegt bei\n      0.058 ~ Richtig. Der Balken zeigt eine Zahl je Gruppe und unterschlägt\n      die Streuung von rund 3.1, die fast so gross ist wie der Abstand.\n- [ ] Nichts, der Unterschied ist ja sichtbar ~ Sichtbar ist er, belegt nicht.\n- [ ] Eine logarithmische Achse ~ Die ändert an der Unsicherheit nichts.\n:::\n\n::: {.quiz}\nZwei Kennzahlen mit sehr verschiedenen Einheiten sollen im Zeitverlauf\nverglichen werden. Was ist die bessere Lösung als eine zweite y-Achse?\n\n- [ ] Beide Reihen auf denselben Wertebereich normieren und in eine Grafik ~\n      Möglich, aber die Normierung ist ebenso willkürlich wie die zweite Achse.\n- [x] Zwei Teilgrafiken übereinander mit gemeinsamer Zeitachse ~ Richtig. Der\n      zeitliche Zusammenhang bleibt sichtbar, und keine Skalierung suggeriert\n      einen Gleichlauf, den es so nicht gibt.\n- [ ] Eine Kennzahl weglassen ~ Das löst das Darstellungsproblem, aber nicht die\n      Aufgabe.\n:::\n\n## Verlinkte Ressourcen\n\n- [From Data to Viz: Entscheidungsbaum nach Datentyp](https://www.data-to-viz.com/)\n- [Claus Wilke: Directory of Visualizations](https://clauswilke.com/dataviz/directory-of-visualizations.html)\n- [Wahrnehmung und Kodierung](wahrnehmung-kodierung.qmd), warum die Rangfolge der Kanäle die Wahl bestimmt\n- [Irreführende Darstellungen](irrefuehrende-darstellungen.qmd), was schiefgeht, wenn die Wahl falsch ist\n- [Skalenniveaus](../statistik/grundlagen/skalenniveaus.qmd), welche Darstellung welcher Datentyp zulässt\n",
    "supporting": [
      "diagrammtyp-waehlen_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}