{
  "hash": "c6b915e39835c4042ff823433dc3d717",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"seaborn und plotly\"\ndescription: \"Statistische Standardgrafiken und interaktive Darstellungen in Python.\"\ncategories: [\"seaborn\", \"plotly\", \"Visualisierung\", \"Python\"]\nquelle: [\"PYFR\", \"DAVI\"]\nseitentyp: werkzeug\nstand: fertig\norder: 60\n---\n\n\n\n\n\n## Kernideen\n\n- seaborn baut auf matplotlib auf: **jede seaborn-Grafik bleibt eine\n  matplotlib-Figur**, und der Feinschliff läuft weiterhin über die Achse.\n- Es erwartet Daten im **langen Format**, eine Zeile je Beobachtung.\n- Statistische Standardgrafiken entstehen mit einem Aufruf statt mit zehn.\n- Funktionen auf **Achsenebene** nehmen `ax=`, Funktionen auf **Rasterebene**\n  erzeugen eine eigene Figur und nehmen es nicht.\n- plotly erzeugt interaktive Grafiken für HTML, nicht für Papier.\n- **Interaktivität lohnt sich nur, wenn sie eine Frage beantwortet**, die man\n  vorher nicht kennt.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [matplotlib](matplotlib.qmd) für Figure und Axes,\n[pandas](../programmierung/pandas.qmd) für die Datenstruktur und\n[Tidy Data](../daten/tidy-data.qmd) für das lange Format. Welche Darstellung zur\nAufgabe passt, klärt [Diagrammtyp wählen](diagrammtyp-waehlen.qmd).\n:::\n\n### Was seaborn abnimmt\n\nmatplotlib zeichnet, seaborn fasst zusammen. Der Unterschied zeigt sich bei\nStandardaufgaben der Datenanalyse: Gruppen vergleichen, Verteilungen\ndarstellen, Zusammenhänge mit Ausgleichsgerade zeigen. In matplotlib sind das\njeweils mehrere Schritte — gruppieren, aggregieren, positionieren, beschriften;\nin seaborn ist es ein Aufruf, der die Daten selbst gruppiert.\n\nDer Preis ist eine Vorbedingung: Die Daten müssen im **langen Format** vorliegen\nund die Spaltennamen werden zu Beschriftungen. Wer das breite Format hat, muss\nvorher umformen.\n\n### Achsenebene oder Rasterebene\n\nDie Eigenheit, über die man einmal stolpert:\n\n| Ebene | Funktionen | Zeichnet in | Nimmt `ax=` |\n|---|---|---|---|\n| **Achsenebene** | `scatterplot`, `lineplot`, `boxplot`, `histplot`, `regplot` | eine bestehende Achse | **ja** |\n| **Rasterebene** | `relplot`, `catplot`, `displot`, `lmplot`, `pairplot` | eine **eigene** Figur mit Facetten | **nein** |\n\nDie Rasterfunktionen sind die facettierten Geschwister der Achsenfunktionen:\n`relplot(kind=\"scatter\")` ist `scatterplot` plus `FacetGrid`.\n\n### Die wichtigsten Funktionen\n\n| Aufgabe | Funktion | Bemerkung |\n|---|---|---|\n| Verteilung | `sns.histplot`, `sns.kdeplot`, `sns.ecdfplot` | `ecdfplot` zeigt alle Daten ohne Bandbreitenwahl |\n| Gruppen vergleichen | `sns.boxplot`, `sns.violinplot`, `sns.stripplot` | Box und Punkte kombinieren |\n| Zusammenhang | `sns.scatterplot`, `sns.regplot`, `sns.lmplot` | `regplot` zeichnet Gerade samt Konfidenzband |\n| Mengen | `sns.barplot`, `sns.countplot` | `barplot` aggregiert selbst und zeigt Unsicherheit |\n| Verlauf | `sns.lineplot` | aggregiert mehrere Werte je x automatisch |\n| Matrix | `sns.heatmap` | für Korrelationen, mit `annot=True` beschriftet |\n| Aufteilen | `sns.relplot`, `sns.displot`, `sns.catplot` | die Varianten mit eingebauter Facettierung |\n\n### plotly: wann Interaktivität lohnt\n\nplotly erzeugt Grafiken, die im Browser reagieren: Werte beim Überfahren,\nZoomen, Serien ein- und ausblenden. Das ist nützlich, wenn die Grafik eine\nFrage beantwortet, die man **nicht vorher kennt** — beim eigenen Erkunden oder\nin einem Dashboard.\n\nFür Bericht und Druck bleibt die statische Grafik die richtige Wahl: Sie hat\neine Aussage, und die steht im Titel. Eine interaktive Grafik verschiebt die\nArbeit zum Publikum, und das ist genau dann falsch, wenn die Aussage feststeht.\n\nplotly ist in der Rechenumgebung dieser Seite nicht installiert; die\nentsprechenden Beispiele stehen deshalb als Listing.\n\n### Der Datensatz dieser Seite\n\n240 Messungen mit Laufzeit, Maschinentyp, Standort und Verbrauch,\ndeterministisch erzeugt.\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Wie viel seaborn abnimmt\n\n#### Frage und Datenlage\n\nEin Boxplot des Verbrauchs je Maschinentyp, mit den Einzelwerten darüber.\nEinmal mit seaborn, einmal mit matplotlib von Hand — und gezählt, was das an\nCode kostet.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### seaborn\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, achse = plt.subplots(figsize=(7, 3))\n_ = sns.boxplot(data=messung, x=\"typ\", y=\"verbrauch\", color=\"0.85\",\n                showfliers=False, ax=achse)\n_ = sns.stripplot(data=messung, x=\"typ\", y=\"verbrauch\", size=3, alpha=0.5,\n                  color=\"0.25\", ax=achse)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: Boxplot mit Einzelwerten, zwei Aufrufe.](seaborn-plotly_files/figure-html/fig-b1a-sb-py-1.png){#fig-b1a-sb-py width=100%}\n:::\n:::\n\n\n##### matplotlib von Hand\n\n\n::: {.cell}\n\n```{.python .cell-code}\ntypen = sorted(messung[\"typ\"].unique())\ngruppen = [messung.loc[messung[\"typ\"] == t, \"verbrauch\"].to_numpy() for t in typen]\n\nfig, achse = plt.subplots(figsize=(7, 3))\n# set_xticks statt tick_labels/labels: die Namen dieses Arguments haben sich\n# zwischen den matplotlib-Versionen geaendert.\n_ = achse.boxplot(gruppen, showfliers=False, patch_artist=True,\n                  boxprops={\"facecolor\": \"0.85\"},\n                  medianprops={\"color\": \"black\"})\n_ = achse.set_xticks(range(1, len(typen) + 1), typen)\nstreu = (lehmer(99, len(messung)) - 0.5) * 0.25\nfor k, (t, werte) in enumerate(zip(typen, gruppen), start=1):\n    maske = (messung[\"typ\"] == t).to_numpy()\n    _ = achse.scatter(k + streu[maske], werte, s=9, alpha=0.5, color=\"0.25\")\n_ = achse.set_xlabel(\"typ\")\n_ = achse.set_ylabel(\"verbrauch\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dasselbe Bild, ohne seaborn.](seaborn-plotly_files/figure-html/fig-b1b-mp-py-3.png){#fig-b1b-mp-py width=100%}\n:::\n:::\n\n\n##### Zahlen\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(messung.groupby(\"typ\")[\"verbrauch\"]\n      .agg(anzahl=\"count\", mittel=\"mean\", median=\"median\", sd=\"std\").round(2))\n\nzeilen = {\"seaborn\": 4, \"matplotlib von Hand\": 11}\nprint({**zeilen, \"verhaeltnis\": round(zeilen[\"matplotlib von Hand\"]\n                                      / zeilen[\"seaborn\"], 2)})\n```\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Typ | Anzahl | Mittel | Median | SD |\n|---|---|---|---|---|\n| Drehbank | 60 | 35.50 | 33.50 | 14.53 |\n| Fräse | 60 | 36.60 | 36.85 | 15.89 |\n| **Presse** | 60 | **51.02** | **51.95** | 13.70 |\n| Saege | 60 | 32.60 | 33.35 | 15.25 |\n\n| Fassung | Codezeilen (ohne `subplots`, `tight_layout`, `show`) |\n|---|---|\n| seaborn | **4** |\n| matplotlib von Hand | **11** |\n| Verhältnis | **2.75** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| seaborn braucht **keine Gruppierung im Code** | `x=\"typ\"` genügt. Die Aufteilung in vier Gruppen, ihre Reihenfolge und die Achsenbeschriftung kommen aus den Daten. |\n| Von Hand sind es die Schritte einzeln | Gruppen bilden, Liste übergeben, Beschriftungen setzen, Streuung für die Punkte erzeugen, je Gruppe zeichnen. Jeder Schritt ist eine Stelle, an der etwas schiefgehen kann. |\n| Der Faktor liegt bei **2.75** | Und er wächst mit der Zahl der Gruppierungsvariablen: Bei zwei Gruppierungen (`hue=`) bleibt seaborn bei einem Aufruf, die Handarbeit verdoppelt die Schleife. |\n| Das Ergebnis ist **dasselbe Objekt** | seaborn gibt ein matplotlib-`Axes` zurück. Alles, was danach kommt — Titel, Grenzen, Anmerkungen —, läuft über die gewohnten Aufrufe. |\n| Die Pressen liegen mit **51.02** klar über den anderen | Und die Sägen mit 32.60 darunter. Der Boxplot zeigt das, die Einzelwerte zeigen zusätzlich, wie stark sich die Gruppen überlappen. |\n\n::: {.note-box}\n**Der Zusatz, der fast nichts kostet und viel bringt:** `stripplot` über den\nBoxplot legen. Damit sind beide Fragen beantwortet — Lage und Streuung aus der\nBox, Form und Fallzahl aus den Punkten. Siehe\n[Diagrammtyp wählen, Beispiel 1](diagrammtyp-waehlen.qmd), wo ein Boxplot eine\nzweigipflige Verteilung verbirgt.\n\nAb etwa 500 Punkten je Gruppe wird `stripplot` unübersichtlich; dann ist\n`violinplot` oder `boxenplot` die bessere Wahl.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Derselbe Boxplot mit Einzelwerten kostet in seaborn 4 und in matplotlib 11\n> Codezeilen, ein Verhältnis von 2.75. Die Pressen liegen mit einem Mittel von\n> 51.02 über den übrigen Typen, die Sägen mit 32.60 darunter.\n\n### Beispiel 2: Langes Format ist die Vorbedingung\n\n#### Frage und Datenlage\n\nDieselben Daten im breiten und im langen Format. seaborn arbeitet mit dem\nlangen — und der Weg dorthin ist eine Zeile.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### seaborn\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# Breites Format: eine Spalte je Typ\nbreit = (messung.assign(nr=messung.groupby(\"typ\").cumcount())\n         .pivot(index=\"nr\", columns=\"typ\", values=\"verbrauch\"))\nprint(breit.head(3).round(1))\nprint({\"breit_form\": breit.shape, \"lang_form\": messung.shape})\n\n# Zurueck ins lange Format\nlang = breit.reset_index().melt(id_vars=\"nr\", var_name=\"typ\",\n                                value_name=\"verbrauch\")\nprint(lang.head(3))\nprint({\"lang_zeilen\": len(lang), \"fehlende\": int(lang[\"verbrauch\"].isna().sum())})\n```\n:::\n\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3))\n_ = sns.violinplot(data=messung, x=\"typ\", y=\"verbrauch\", color=\"0.8\",\n                   ax=achsen[0])\n_ = achsen[0].set_title(\"aus dem langen Format\", fontsize=10)\n_ = achsen[0].tick_params(axis=\"x\", rotation=30)\n_ = sns.ecdfplot(data=messung, x=\"verbrauch\", hue=\"typ\", ax=achsen[1])\n_ = achsen[1].set_title(\"hue= gruppiert ohne Zusatzcode\", fontsize=10)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: aus dem langen Format ein Aufruf je Grafik.](seaborn-plotly_files/figure-html/fig-b2-sb-py-5.png){#fig-b2-sb-py width=100%}\n:::\n:::\n\n\n##### matplotlib von Hand\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, achse = plt.subplots(figsize=(7, 3))\nfor t in sorted(messung[\"typ\"].unique()):\n    werte = np.sort(messung.loc[messung[\"typ\"] == t, \"verbrauch\"].to_numpy())\n    anteil = np.arange(1, len(werte) + 1) / len(werte)\n    _ = achse.step(werte, anteil, where=\"post\", label=t)\n_ = achse.legend(fontsize=8, frameon=False)\n_ = achse.set_xlabel(\"verbrauch\")\n_ = achse.set_ylabel(\"Anteil\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: die empirische Verteilungsfunktion je Gruppe von Hand.](seaborn-plotly_files/figure-html/fig-b2b-mp-py-7.png){#fig-b2b-mp-py width=100%}\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Format | Form |\n|---|---|\n| breit | **(60, 4)** — eine Spalte je Typ |\n| lang | **(240, 4)** — eine Zeile je Messung |\n| nach `melt` | **240** Zeilen, **0** fehlende Werte |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Das breite Format hat **60 Zeilen und 4 Spalten** | Es funktioniert nur, weil alle vier Gruppen gleich gross sind. Bei ungleichen Gruppen entstünden fehlende Werte. |\n| Das lange Format hat **240 Zeilen** | Eine je Messung. Die Gruppenzugehörigkeit steht als **Wert** in einer Spalte, nicht als Spaltenname. |\n| seaborn braucht genau diese Form | `x=\"typ\"` verweist auf eine Spalte. Im breiten Format gäbe es keine solche Spalte — der Typ wäre im Spaltennamen versteckt. |\n| `melt` ist die eine Zeile dorthin | `id_vars` bleibt stehen, alles andere wird zu zwei Spalten: Name und Wert. In R heisst das `pivot_longer`. |\n| `hue=\"typ\"` erzeugt die Gruppen samt Legende | Die Handarbeit daneben braucht eine Schleife, ein `label=` je Durchlauf und einen `legend()`-Aufruf — und die Sortierung der Werte für die Verteilungsfunktion obendrein. |\n\n::: {.note-box}\n**Die Faustregel zum Erkennen des langen Formats:** Jede Spalte ist eine\n**Variable**, jede Zeile eine **Beobachtung**. Steht in einem Spaltennamen ein\nDatenwert — ein Jahr, ein Produktname, ein Maschinentyp —, ist das Format\nbreit.\n\nAusführlich unter [Tidy Data](../daten/tidy-data.qmd).\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Im breiten Format stehen die 240 Messungen als 60 Zeilen mal 4 Spalten, im\n> langen als 240 Zeilen mit der Gruppenzugehörigkeit als Spaltenwert. Nur die\n> zweite Form lässt sich mit `x=\"typ\"` und `hue=\"typ\"` ansprechen; `melt` ist\n> der Weg dorthin.\n\n### Beispiel 3: Achsenebene oder Rasterebene\n\n#### Frage und Datenlage\n\n`sns.scatterplot` nimmt `ax=`, `sns.relplot` nicht. Warum — und was\nzurückgegeben wird.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### seaborn\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, achse = plt.subplots(figsize=(3, 2))\nergebnis_achse = sns.scatterplot(data=messung, x=\"laufzeit\", y=\"verbrauch\",\n                                 ax=achse)\nprint({\"scatterplot_gibt_zurueck\": type(ergebnis_achse).__name__,\n       \"ist_dieselbe_achse\": ergebnis_achse is achse})\nplt.close(fig)\n\nergebnis_raster = sns.relplot(data=messung, x=\"laufzeit\", y=\"verbrauch\",\n                              col=\"typ\", col_wrap=2, height=1.4)\nprint({\"relplot_gibt_zurueck\": type(ergebnis_raster).__name__,\n       \"anzahl_teilbilder\": ergebnis_raster.axes.size,\n       \"hat_eigene_figur\": ergebnis_raster.figure is not fig})\nplt.close(ergebnis_raster.figure)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.python .cell-code}\nraster = sns.relplot(data=messung, x=\"laufzeit\", y=\"verbrauch\", col=\"typ\",\n                     hue=\"standort\", col_wrap=2, height=1.7, aspect=1.5, s=14)\n_ = raster.set_axis_labels(\"Laufzeit in Stunden\", \"Verbrauch\")\n```\n\n::: {.cell-output-display}\n![Beispiel 3: relplot erzeugt Facetten mit gemeinsamen Achsen.](seaborn-plotly_files/figure-html/fig-b3-sb-py-9.png){#fig-b3-sb-py-1 width=100%}\n:::\n\n```{.python .cell-code}\n_ = raster.set_titles(\"{col_name}\")\n```\n\n::: {.cell-output-display}\n![Beispiel 3: relplot erzeugt Facetten mit gemeinsamen Achsen.](seaborn-plotly_files/figure-html/fig-b3-sb-py-10.png){#fig-b3-sb-py-2 width=100%}\n:::\n\n```{.python .cell-code}\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: relplot erzeugt Facetten mit gemeinsamen Achsen.](seaborn-plotly_files/figure-html/fig-b3-sb-py-11.png){#fig-b3-sb-py-3 width=100%}\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: relplot erzeugt Facetten mit gemeinsamen Achsen.](seaborn-plotly_files/figure-html/fig-b3-sb-py-12.png){#fig-b3-sb-py-4 width=100%}\n:::\n:::\n\n\n##### matplotlib von Hand\n\n\n::: {.cell}\n\n```{.python .cell-code}\ntypen = sorted(messung[\"typ\"].unique())\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselben Facetten von Hand, mit eigener Legende.](seaborn-plotly_files/figure-html/fig-b3b-mp-py-17.png){#fig-b3b-mp-py-1 width=100%}\n:::\n\n```{.python .cell-code}\nfarben = {\"Bern\": \"#0072B2\", \"Chur\": \"#D55E00\"}\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselben Facetten von Hand, mit eigener Legende.](seaborn-plotly_files/figure-html/fig-b3b-mp-py-18.png){#fig-b3b-mp-py-2 width=100%}\n:::\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(2, 2, figsize=(7, 3.4), sharex=True, sharey=True)\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselben Facetten von Hand, mit eigener Legende.](seaborn-plotly_files/figure-html/fig-b3b-mp-py-19.png){#fig-b3b-mp-py-3 width=100%}\n:::\n\n```{.python .cell-code}\nfor achse, t in zip(achsen.ravel(), typen):\n    teil = messung[messung[\"typ\"] == t]\n    for ort, gruppe in teil.groupby(\"standort\"):\n        _ = achse.scatter(gruppe[\"laufzeit\"], gruppe[\"verbrauch\"], s=10,\n                          alpha=0.7, color=farben[ort], label=ort)\n    _ = achse.set_title(t, fontsize=9)\n_ = achsen[0, 0].legend(fontsize=7, frameon=False)\nfor achse in achsen[-1]:\n    _ = achse.set_xlabel(\"Laufzeit in Stunden\")\nfor achse in achsen[:, 0]:\n    _ = achse.set_ylabel(\"Verbrauch\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselben Facetten von Hand, mit eigener Legende.](seaborn-plotly_files/figure-html/fig-b3b-mp-py-20.png){#fig-b3b-mp-py-4 width=100%}\n:::\n:::\n\n\n##### Zahlen\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(pd.crosstab(messung[\"typ\"], messung[\"standort\"]))\nprint(messung.groupby([\"typ\", \"standort\"])[\"verbrauch\"].mean().round(2))\n```\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Aufruf | Rückgabe | `ax=` |\n|---|---|---|\n| `sns.scatterplot(..., ax=achse)` | **Axes**, und zwar **dieselbe** | ja |\n| `sns.relplot(...)` | **FacetGrid** mit **4** Teilbildern, eigene Figur | nein |\n\nVerteilung auf Typ und Standort:\n\n| | Bern | Chur |\n|---|---|---|\n| Drehbank | **35** | 25 |\n| Fräse | 29 | 31 |\n| Presse | 23 | **37** |\n| Saege | 30 | 30 |\n\n| Beobachtung | Erklärung |\n|---|---|\n| `scatterplot` gibt **dieselbe Achse** zurück, die es bekommen hat | Deshalb lässt sich danach wie gewohnt weiterarbeiten: `achse.set_title(...)`, `achse.axhline(...)`. |\n| `relplot` gibt ein **FacetGrid** zurück | Das ist kein Axes. Es hat eine eigene Figure, eigene Methoden (`set_axis_labels`, `set_titles`) und lässt sich nicht in eine vorbereitete Achse zeichnen. |\n| Der Fehler tritt immer gleich auf | Man baut `fig, achsen = plt.subplots(...)`, ruft dann `relplot(..., ax=achsen[0])` — und bekommt einen Fehler über ein unerwartetes Argument. **Lösung: die Funktion ohne `rel`/`cat`/`dis`-Vorsilbe nehmen.** |\n| Die Standorte sind **nicht gleichmässig** verteilt | 23 zu 37 bei den Pressen, 35 zu 25 bei den Drehbänken. Das ist Zufall der Zuteilung und ein Grund, die Fallzahlen je Facette anzuschreiben. |\n| Von Hand kostet dasselbe Bild eine doppelte Schleife | Über Typen und über Standorte, plus Legende und Achsenbeschriftung an den richtigen Rändern. |\n\n::: {.note-box}\n**Die Paare merken sich leicht:**\n\n| Achsenebene | Rasterebene |\n|---|---|\n| `scatterplot`, `lineplot` | `relplot` |\n| `boxplot`, `violinplot`, `barplot`, `stripplot` | `catplot` |\n| `histplot`, `kdeplot`, `ecdfplot` | `displot` |\n| `regplot` | `lmplot` |\n\nWer `ax=` braucht, nimmt die linke Spalte. Wer Facetten will, die rechte.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> `sns.scatterplot` gibt dasselbe `Axes` zurück, das es über `ax=` bekommen hat;\n> `sns.relplot` gibt ein `FacetGrid` mit vier Teilbildern und eigener Figur\n> zurück und kennt kein `ax=`. Die vier Typen verteilen sich ungleich auf die\n> Standorte, von 23 zu 37 bis 35 zu 25.\n\n### Beispiel 4: Die Matrix und die Aggregation\n\n#### Frage und Datenlage\n\nZwei Funktionen, die mehr tun, als sie auf den ersten Blick zeigen: `heatmap`\nfür eine Korrelationsmatrix und `barplot`, der selbst aggregiert und ein\nUnsicherheitsmass einzeichnet.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### seaborn\n\n\n::: {.cell}\n\n```{.python .cell-code}\nerweitert = messung.assign(\n    stunden_quadrat=messung[\"laufzeit\"] ** 2,\n    verbrauch_je_stunde=messung[\"verbrauch\"] / messung[\"laufzeit\"])\nkorr = erweitert[[\"laufzeit\", \"verbrauch\", \"stunden_quadrat\",\n                  \"verbrauch_je_stunde\"]].corr()\nprint(korr.round(3))\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3))\n_ = sns.heatmap(korr, annot=True, fmt=\".2f\", cmap=\"RdBu_r\", vmin=-1, vmax=1,\n                square=True, cbar=False, ax=achsen[0],\n                annot_kws={\"size\": 7})\n_ = achsen[0].set_title(\"heatmap\", fontsize=10)\n_ = achsen[0].tick_params(labelsize=6)\n_ = sns.barplot(data=messung, x=\"typ\", y=\"verbrauch\", errorbar=(\"ci\", 95),\n                color=\"0.7\", ax=achsen[1])\n_ = achsen[1].set_title(\"barplot: aggregiert selbst\", fontsize=10)\n_ = achsen[1].tick_params(axis=\"x\", rotation=30)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: Korrelationsmatrix und aggregierender Balken.](seaborn-plotly_files/figure-html/fig-b4-sb-py-25.png){#fig-b4-sb-py width=100%}\n:::\n:::\n\n\n##### Zahlen\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# Was barplot im Hintergrund rechnet\nzusammen = messung.groupby(\"typ\")[\"verbrauch\"].agg(\n    mittel=\"mean\", sd=\"std\", anzahl=\"count\")\nzusammen[\"standardfehler\"] = zusammen[\"sd\"] / np.sqrt(zusammen[\"anzahl\"])\nzusammen[\"ki_unten\"] = zusammen[\"mittel\"] - 1.96 * zusammen[\"standardfehler\"]\nzusammen[\"ki_oben\"] = zusammen[\"mittel\"] + 1.96 * zusammen[\"standardfehler\"]\nprint(zusammen.round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          mittel      sd  anzahl  standardfehler  ki_unten  ki_oben\ntyp                                                                \nDrehbank  35.500  14.532      60           1.876    31.823   39.177\nFräse     36.595  15.894      60           2.052    32.573   40.617\nPresse    51.017  13.701      60           1.769    47.550   54.484\nSaege     32.603  15.251      60           1.969    28.744   36.462\n```\n\n\n:::\n\n```{.python .cell-code}\nprint({\"korrelation_laufzeit_verbrauch\":\n       round(float(messung[\"laufzeit\"].corr(messung[\"verbrauch\"])), 4)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'korrelation_laufzeit_verbrauch': 0.8694}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nKorrelationsmatrix:\n\n| | laufzeit | verbrauch |\n|---|---|---|\n| **laufzeit** | 1.000 | **0.869** |\n| **verbrauch** | **0.869** | 1.000 |\n\nWas `barplot` im Hintergrund rechnet:\n\n| Typ | Mittel | SD | Standardfehler | 95-Prozent-Intervall |\n|---|---|---|---|---|\n| Drehbank | 35.50 | 14.53 | **1.876** | 31.82 bis 39.18 |\n| Fräse | 36.60 | 15.89 | 2.051 | 32.58 bis 40.62 |\n| **Presse** | **51.02** | 13.70 | 1.769 | **47.55 bis 54.48** |\n| Saege | 32.60 | 15.25 | 1.969 | 28.74 bis 36.46 |\n\n| Beobachtung | Erklärung |\n|---|---|\n| `barplot` zeigt **nicht die Summe**, sondern den Mittelwert | Das ist die häufigste Überraschung. Wer Summen will, aggregiert vorher und nimmt `barplot` mit `estimator=\"sum\"` oder gleich `achse.bar`. |\n| Und er zeichnet von sich aus ein **Konfidenzintervall** | `errorbar=(\"ci\", 95)`. Damit macht seaborn genau das richtig, was ein reines Balkendiagramm falsch macht — siehe [Diagrammtyp wählen, Beispiel 5](diagrammtyp-waehlen.qmd). |\n| Das Intervall der Pressen überlappt **keines** der anderen | 47.55 bis 54.48 gegen höchstens 40.62. Der Unterschied ist damit anders als in jenem Beispiel tatsächlich belegt. |\n| Die Heatmap braucht `vmin`, `vmax` und eine **divergierende** Palette | Sonst nutzt sie den Wertebereich der Daten aus und Null liegt nicht in der Mitte. Bei Korrelationen ist Null der Nullpunkt — siehe [Farbe](farbe.qmd). |\n| `annot=True` schreibt die Zahlen hinein | Eine Heatmap ohne Zahlen ist bei wenigen Zellen eine verschenkte Tabelle. |\n\n::: {.warning-box}\n**Die Voreinstellung von `heatmap` ist eine Falle.** Ohne `vmin=-1, vmax=1`\nwird die Farbskala auf den beobachteten Bereich gestreckt: Eine Matrix mit\nKorrelationen zwischen 0.80 und 1.00 sieht dann aus, als reiche sie von\n\"nichts\" bis \"alles\".\n\nBei Korrelationsmatrizen gehören deshalb immer dazu:\n\n```python\nsns.heatmap(korr, vmin=-1, vmax=1, cmap=\"RdBu_r\", annot=True, fmt=\".2f\")\n```\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Laufzeit und Verbrauch korrelieren mit 0.869. `barplot` zeigt den Mittelwert\n> je Gruppe samt 95-Prozent-Intervall: Die Pressen liegen mit 47.55 bis 54.48\n> ausserhalb aller anderen Intervalle, die höchstens bis 40.62 reichen.\n\n### Beispiel 5: Wann Interaktivität lohnt\n\n#### Frage und Datenlage\n\nEine interaktive Grafik ersetzt rechnerisch eine bestimmte Zahl statischer\nGrafiken. Diese Zahl lässt sich ausrechnen — und sie ist das Argument für oder\ngegen den Aufwand.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### Rechnung\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# Wie viele statische Grafiken bräuchte es, um dieselben Fragen zu beantworten?\nauswahl = {\"Maschinentyp (4 plus alle)\": 5,\n           \"Standort (2 plus beide)\": 3,\n           \"Kennzahl\": 3,\n           \"Zeitraum\": 2}\nprint(auswahl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'Maschinentyp (4 plus alle)': 5, 'Standort (2 plus beide)': 3, 'Kennzahl': 3, 'Zeitraum': 2}\n```\n\n\n:::\n\n```{.python .cell-code}\nanzahl = 1\nfor wert in auswahl.values():\n    anzahl *= wert\nprint({\"kombinationen\": anzahl})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'kombinationen': 90}\n```\n\n\n:::\n\n```{.python .cell-code}\n# Und wie viele davon tatsaechlich gebraucht werden\nfor genutzt in (1, 3, 10):\n    print(f\"genutzt {genutzt:2d} von {anzahl}: \"\n          f\"{100 * genutzt / anzahl:5.1f} Prozent der vorbereiteten Grafiken\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngenutzt  1 von 90:   1.1 Prozent der vorbereiteten Grafiken\ngenutzt  3 von 90:   3.3 Prozent der vorbereiteten Grafiken\ngenutzt 10 von 90:  11.1 Prozent der vorbereiteten Grafiken\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, achse = plt.subplots(figsize=(7, 3))\nist_presse = messung[\"typ\"] == \"Presse\"\n_ = achse.scatter(messung.loc[~ist_presse, \"laufzeit\"],\n                  messung.loc[~ist_presse, \"verbrauch\"],\n                  s=12, alpha=0.6, color=\"#c7c7c7\")\n_ = achse.scatter(messung.loc[ist_presse, \"laufzeit\"],\n                  messung.loc[ist_presse, \"verbrauch\"],\n                  s=12, alpha=0.8, color=\"#b2182b\")\n_ = achse.annotate(\"Pressen\", xy=(3, 70), color=\"#b2182b\", fontsize=10,\n                   fontweight=\"bold\")\n_ = achse.set_title(\"Pressen verbrauchen bei gleicher Laufzeit mehr\")\n_ = achse.set_xlabel(\"Laufzeit in Stunden\")\n_ = achse.set_ylabel(\"Verbrauch\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 5: die statische Fassung — eine Aussage, ein Bild.](seaborn-plotly_files/figure-html/fig-b5-sb-py-27.png){#fig-b5-sb-py width=100%}\n:::\n:::\n\n\n##### plotly als Listing\n\n```python\nimport plotly.express as px\n\nabb = px.scatter(messung, x=\"laufzeit\", y=\"verbrauch\", color=\"typ\",\n                 facet_col=\"standort\",\n                 hover_data=[\"typ\", \"standort\"],\n                 labels={\"laufzeit\": \"Laufzeit in Stunden\",\n                         \"verbrauch\": \"Verbrauch\"},\n                 title=\"Verbrauch nach Laufzeit\")\nabb.update_layout(template=\"simple_white\")\nabb.show()\n\n# Als eigenständige HTML-Datei, etwa für den Versand\nabb.write_html(\"verbrauch.html\", include_plotlyjs=\"cdn\")\n```\n\n`include_plotlyjs=\"cdn\"` hält die Datei klein, verlangt dafür aber eine\nInternetverbindung beim Öffnen. Mit `include_plotlyjs=True` wird die Bibliothek\neingebettet: rund 3 Megabyte, dafür offline lesbar.\n\n:::\n\n#### Output Zeile für Zeile\n\n| Auswahlmöglichkeit | Stufen |\n|---|---|\n| Maschinentyp (4 plus \"alle\") | 5 |\n| Standort (2 plus \"beide\") | 3 |\n| Kennzahl | 3 |\n| Zeitraum | 2 |\n| **Kombinationen insgesamt** | **90** |\n\n| tatsächlich angesehen | Anteil der vorbereiteten Grafiken |\n|---|---|\n| 1 von 90 | **1.1 Prozent** |\n| 3 von 90 | **3.3 Prozent** |\n| 10 von 90 | **11.1 Prozent** |\n\n| Beobachtung | Erklärung |\n|---|---|\n| Vier Auswahlfelder ergeben **90** mögliche Ansichten | Und das ist ein bescheidenes Dashboard. Statisch vorzubereiten ist das nicht. |\n| Wer eine feste Aussage hat, braucht **eine** | Dann sind 89 der 90 Ansichten Ballast, und die interaktive Fassung verschiebt nur Arbeit zum Publikum. |\n| Die Rechnung ist das Entscheidungskriterium | **Interaktiv lohnt sich, wenn die Zahl der sinnvollen Fragen gross und die Auswahl vorab unbekannt ist.** Ist beides nicht der Fall, ist die statische Grafik besser. |\n| Die statische Fassung trifft eine Entscheidung | Pressen rot, alles andere grau, Aussage im Titel. Sie beantwortet eine Frage vollständig statt neunzig halb. |\n| Für Papier und PDF gibt es **keine** Alternative | Eine interaktive Grafik wird dort zum Standbild — und zwar zu dem, das gerade eingestellt war. |\n\n::: {.note-box}\n**Die Entscheidungshilfe in vier Zeilen:**\n\n| Lage | Wahl |\n|---|---|\n| Aussage steht fest, Publikum liest | **statisch** |\n| Publikum stellt eigene Fragen | interaktiv |\n| Ausgabe ist Papier oder PDF | **statisch** |\n| eigenes Erkunden während der Analyse | interaktiv, oder gleich im Notebook |\n\nMehr zur Abwägung unter\n[Dashboards und Interaktivität](dashboards-interaktivitaet.qmd).\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Vier Auswahlfelder mit 5, 3, 3 und 2 Stufen ergeben 90 mögliche Ansichten.\n> Wer eine feste Aussage hat, braucht davon eine — 1.1 Prozent. Interaktivität\n> lohnt sich, wenn die Auswahl vorab unbekannt ist, und sonst nicht.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEin seaborn-Aufruf mit `relplot` soll in eine vorbereitete Achse gezeichnet\nwerden, aber `ax=` wird nicht akzeptiert. Warum?\n\n- [x] `relplot` arbeitet auf Rasterebene und erzeugt eine eigene Figur ~ Richtig.\n      Es gibt ein FacetGrid zurück, kein Axes. Für das Zeichnen in eine\n      bestehende Achse nimmt man die Funktion auf Achsenebene, hier\n      `scatterplot` oder `lineplot`.\n- [ ] Das Argument heisst in seaborn anders ~ Es heisst überall `ax`, existiert\n      aber nur auf Achsenebene.\n- [ ] Die Figur muss vorher geschlossen werden ~ Das ändert nichts.\n:::\n\n::: {.quiz}\n`sns.barplot(data=df, x=\"typ\", y=\"verbrauch\")` — was zeigen die Balken?\n\n- [x] Den Mittelwert je Gruppe, dazu ein Konfidenzintervall ~ Richtig, und das\n      ist die häufigste Überraschung. Wer Summen braucht, setzt\n      `estimator=\"sum\"` oder aggregiert vorher.\n- [ ] Die Summe je Gruppe ~ Das wäre die naheliegende Erwartung und ist falsch.\n- [ ] Die Anzahl je Gruppe ~ Dafür ist `countplot` zuständig.\n:::\n\n::: {.quiz}\nWarum braucht `sns.heatmap` bei einer Korrelationsmatrix `vmin=-1, vmax=1`?\n\n- [x] Sonst wird die Farbskala auf den beobachteten Bereich gestreckt ~ Richtig.\n      Korrelationen zwischen 0.80 und 1.00 sähen dann aus, als reichten sie von\n      nichts bis alles. Bei Korrelationen ist null der Nullpunkt, also gehört\n      eine divergierende Palette dazu.\n- [ ] Sonst funktioniert `annot=True` nicht ~ Die Beschriftung ist davon\n      unabhängig.\n- [ ] Das ist nur Geschmackssache ~ Es entscheidet darüber, was das Publikum\n      abliest.\n:::\n\n::: {.quiz}\nseaborn verlangt das lange Format. Woran erkennt man, dass Daten breit sind?\n\n- [x] In einem Spaltennamen steht ein Datenwert ~ Richtig: ein Jahr, ein\n      Produktname, ein Maschinentyp. Im langen Format ist jede Spalte eine\n      Variable und jede Zeile eine Beobachtung; `melt` beziehungsweise\n      `pivot_longer` führt dorthin.\n- [ ] Es gibt mehr Spalten als Zeilen ~ Das kommt vor, ist aber kein Kriterium.\n- [ ] Es fehlen Werte ~ Fehlende Werte können in beiden Formaten auftreten.\n:::\n\n::: {.quiz}\nEin Dashboard hat vier Auswahlfelder mit 5, 3, 3 und 2 Stufen. Wie viele\nAnsichten sind das?\n\n- [x] 90, und davon wird typischerweise eine Handvoll wirklich angesehen ~\n      Richtig. Das ist das Argument für Interaktivität, wenn die Auswahl vorab\n      unbekannt ist — und dagegen, wenn die Aussage feststeht.\n- [ ] 13, also die Summe der Stufen ~ Die Möglichkeiten multiplizieren sich.\n- [ ] Das lässt sich nicht beziffern ~ Es ist ein einfaches Produkt.\n:::\n\n::: {.quiz}\nDerselbe Boxplot mit Einzelwerten kostet in seaborn 4 und von Hand 11\nCodezeilen. Was folgt daraus?\n\n- [x] seaborn nimmt die Gruppierung ab, das Ergebnis bleibt eine\n      matplotlib-Achse ~ Richtig. Der Feinschliff läuft danach über die\n      gewohnten Aufrufe; man verliert nichts, man spart die Schleifen.\n- [ ] matplotlib ist überflüssig ~ seaborn setzt darauf auf; ohne matplotlib\n      gäbe es keine seaborn-Grafik.\n- [ ] seaborn ist immer die bessere Wahl ~ Bei ungewöhnlichen Grafiken, die\n      nicht zum Standardrepertoire gehören, ist die Handarbeit direkter.\n:::\n\n## Verlinkte Ressourcen\n\n- [seaborn: Übersicht der Funktionen](https://seaborn.pydata.org/api.html)\n- [seaborn: Overview of plotting functions](https://seaborn.pydata.org/tutorial/function_overview.html)\n- [plotly express: Einstieg](https://plotly.com/python/plotly-express/)\n- [matplotlib](matplotlib.qmd) — worauf seaborn aufsetzt\n- [Dashboards und Interaktivität](dashboards-interaktivitaet.qmd) — wann sich der Aufwand lohnt\n- [Tidy Data](../daten/tidy-data.qmd) — das lange Format\n",
    "supporting": [
      "seaborn-plotly_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}