{
  "hash": "49887917a198ea32828fe7cdda146ed3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Effektstärken\"\ndescription: \"Cohens d, Hedges g, r und η²: wie gross ist der Unterschied wirklich?\"\ncategories: [\"Effektstärke\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"ESDS\", \"STATDA\"]\nseitentyp: konzept\nstand: fertig\norder: 40\n---\n\n\n\n\n\n## Kernideen\n\n- Eine Effektstärke beantwortet die Frage **wie gross**, ein p-Wert die Frage\n  **vom Zufall unterscheidbar**. Die beiden hängen nur über den\n  Stichprobenumfang zusammen.\n- Cohens $d$ misst die Mittelwertdifferenz in Einheiten der Streuung. Dieselbe\n  Differenz kann je nach Streuung ein winziger oder ein riesiger Effekt sein.\n- Effektstärken sind vom Stichprobenumfang unabhängig. Der p-Wert ist es nicht:\n  Mit wachsendem n wird jeder noch so kleine Effekt signifikant.\n- Eine Effektstärke ohne Konfidenzintervall ist eine Punktschätzung wie jede\n  andere und bei kleinem n sehr unsicher.\n- Die Anhaltspunkte \"0.2 klein, 0.5 mittel, 0.8 gross\" sind eine Notlösung für\n  Gebiete ohne eigene Erfahrungswerte, keine Naturkonstanten.\n\n## Erklärung\n\n### Die drei Familien\n\n| Familie | Masse | Wofür | Bereich |\n|---|---|---|---|\n| Differenzmasse | Cohens $d$, Hedges $g$ | Mittelwertunterschiede zwischen Gruppen | unbeschränkt, praktisch -3 bis 3 |\n| Zusammenhangsmasse | $r$, $R^2$, $\\eta^2$, Cramérs $V$ | Stärke eines Zusammenhangs | 0 bis 1, $r$ auch negativ |\n| Verhältnismasse | Odds Ratio, Risikoverhältnis | binäre Zielgrössen | 0 bis unendlich, 1 heisst kein Effekt |\n\nWelches passt, ergibt sich aus dem Verfahren:\n\n| Verfahren | Übliches Mass |\n|---|---|\n| [t-Test](../tests/t-test-zwei-stichproben.qmd) | Cohens $d$, bei kleinem n Hedges $g$ |\n| [gepaarter t-Test](../tests/t-test-gepaart.qmd) | $d_z$ auf den Differenzen, siehe dortigen Kasten |\n| [Varianzanalyse](../tests/anova.qmd) | $\\eta^2$ oder partielles $\\eta^2$ |\n| [Korrelation](../grundlagen/korrelation.qmd) | $r$ ist bereits eine Effektstärke |\n| [Regression](../regression/multiple-lineare-regression.qmd) | $R^2$, und der Koeffizient in seiner Einheit |\n| [Chi-Quadrat](../tests/chi-quadrat-tests.qmd) | Cramérs $V$ |\n| [logistische Regression](../regression/logistische-regression.qmd) | Odds Ratio |\n| [Rangtests](../tests/nichtparametrische-tests.qmd) | rangbiseriale Korrelation, CLES |\n\n### Cohens d und seine Geschwister\n\n$$d = \\frac{\\bar{x}_2 - \\bar{x}_1}{s_{\\text{gepoolt}}}, \\qquad\ns_{\\text{gepoolt}} = \\sqrt{\\frac{(n_1-1)s_1^2 + (n_2-1)s_2^2}{n_1+n_2-2}}$$\n\nDer Zähler ist die Effektgrösse in der Einheit der Messung, der Nenner macht sie\neinheitenlos. Genau dadurch wird $d$ zwischen Studien vergleichbar und verliert\nzugleich den Bezug zur Sache: 0.5 sagt nichts darüber, ob es um Millimeter oder\nMonate geht.\n\n**Hedges $g$** korrigiert eine Verzerrung, die $d$ bei kleinen Stichproben nach\noben treibt. Der Korrekturfaktor beträgt $1 - \\frac{3}{4(n_1+n_2)-9}$, bei\ninsgesamt 24 Fällen also rund 0.965. Ab etwa 50 Fällen ist der Unterschied\nbelanglos; darunter gehört $g$ berichtet.\n\n### Die Anhaltspunkte und ihre Grenzen\n\n| $d$ | Bezeichnung | Überlappung der Verteilungen | Anteil von B über dem Median von A |\n|---|---|---|---|\n| 0.2 | klein | 92 % | 58 % |\n| 0.5 | mittel | 80 % | 69 % |\n| 0.8 | gross | 69 % | 79 % |\n| 1.2 | sehr gross | 55 % | 88 % |\n\nDiese Bezeichnungen stammen aus einem Vorschlag für die Sozialwissenschaften und\nwurden dort ausdrücklich als Notlösung eingeführt. In einem Fachgebiet mit\neigenen Erfahrungswerten ist der Vergleich mit früheren Studien die bessere\nEinordnung. In der Fertigung kann $d = 0.2$ teuer sein, in der Psychologie ist\n$d = 0.8$ ungewöhnlich gross.\n\n### Umrechnung\n\nDie Masse lassen sich ineinander überführen, was beim Vergleich von Studien mit\nverschiedenen Verfahren hilft:\n\n| Von | Nach | Formel | Beispiel $d = 0.5$ |\n|---|---|---|---|\n| $d$ | $r$ | $r = d/\\sqrt{d^2+4}$ | 0.243 |\n| $r$ | $d$ | $d = 2r/\\sqrt{1-r^2}$ | |\n| $d$ | CLES | $\\Phi(d/\\sqrt{2})$ | 0.638 |\n| $\\eta^2$ | $f$ | $f = \\sqrt{\\eta^2/(1-\\eta^2)}$ | |\n\n::: {.note-box}\n**Die Common Language Effect Size ist die verständlichste Übersetzung.** Sie\nbeantwortet die Frage: Wie wahrscheinlich ist es, dass ein zufällig gewählter\nFall aus Gruppe B über einem zufällig gewählten aus Gruppe A liegt? Bei\n$d = 0.5$ sind das 64 Prozent, bei $d = 0$ genau 50 Prozent.\n\nDiese Zahl braucht keine Statistikkenntnisse und macht sofort deutlich, wie\nbescheiden ein \"mittlerer\" Effekt ist: In gut einem Drittel der Vergleiche\ngewinnt die andere Gruppe.\n:::\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Dieselbe Differenz, zwei Effektstärken\n\n#### Frage und Datenlage\n\nZwei Vergleiche, beide mit einer Mittelwertdifferenz von genau 0.50 Einheiten.\nIm ersten streuen die Werte eng, im zweiten weit. Die Frage lautet: Ist das\nderselbe Effekt?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nboxplot(list(A = eng_a, B = eng_b), main = \"enge Streuung\",\n        ylab = \"Messwert\", ylim = c(10, 15.2))\nboxplot(list(A = weit_a, B = weit_b), main = \"weite Streuung\",\n        ylab = \"Messwert\", ylim = c(10, 15.2))\npar(mfrow = c(1, 1))\n\neffekt(eng_a, eng_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  differenz gepoolte_sd           d    hedges_g       unten        oben \n     0.5000      0.2812      1.7779      1.7166      0.8328      2.7230 \n```\n\n\n:::\n\n```{.r .cell-code}\neffekt(weit_a, weit_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  differenz gepoolte_sd           d    hedges_g       unten        oben \n     0.5000      1.4513      0.3445      0.3326     -0.4616      1.1506 \n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(eng_b, eng_a, var.equal = TRUE)$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0002535206\n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(weit_b, weit_a, var.equal = TRUE)$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.407821\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Differenz vor unterschiedlichem Hintergrund.](effektstaerken_files/figure-html/fig-b1-eff-r-1.png){#fig-b1-eff-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nfor achse, paar, titel in zip(achsen, [(eng_a, eng_b), (weit_a, weit_b)],\n                              [\"enge Streuung\", \"weite Streuung\"]):\n    achse.boxplot(list(paar))\n    achse.set_xticks([1, 2], [\"A\", \"B\"])\n    achse.set_ylim(10, 15.2)\n    achse.set_ylabel(\"Messwert\")\n    achse.set_title(titel)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Darstellung in Python.](effektstaerken_files/figure-html/fig-b1-eff-py-1.png){#fig-b1-eff-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(pd.DataFrame({\"eng\": effekt(eng_a, eng_b),\n                    \"weit\": effekt(weit_a, weit_b)}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                eng    weit\ndifferenz    0.5000  0.5000\ngepoolte_sd  0.2812  1.4513\nd            1.7779  0.3445\nhedges_g     1.7166  0.3326\nunten        0.8328 -0.4616\noben         2.7230  1.1506\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"p eng: \", round(stats.ttest_ind(eng_b, eng_a).pvalue, 6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np eng:  0.000254\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"p weit:\", round(stats.ttest_ind(weit_b, weit_a).pvalue, 6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np weit: 0.407821\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Kennzahl | enge Streuung | weite Streuung | Wie das zu lesen ist |\n|---|---|---|---|\n| Mittelwertdifferenz | 0.500 | 0.500 | **Identisch.** In der Einheit der Messung ist der Unterschied derselbe. |\n| gepoolte Standardabweichung | 0.281 | 1.451 | Der Unterschied steckt hier: gut fünfmal so gross. |\n| Cohens $d$ | **1.778** | **0.345** | Ein Faktor von fünf, allein aus der Streuung. Links ein sehr grosser, rechts ein kleiner Effekt. |\n| Hedges $g$ | 1.717 | 0.333 | Um 3.5 Prozent kleiner, weil bei 24 Fällen die Korrektur greift. |\n| Näherungsintervall für $d$ | 0.83 bis 2.72 | -0.46 bis 1.15 | Beide Intervalle sind breit; bei 12 Fällen je Gruppe ist die Effektstärke schlecht bestimmt. |\n| p-Wert | 0.00025 | 0.408 | Derselbe Unterschied, einmal hochsignifikant, einmal weit von jeder Schwelle entfernt. |\n\n#### Interpretation\n\nDie Boxplots machen sichtbar, was die Zahlen sagen: Links liegen die beiden\nGruppen fast getrennt nebeneinander, rechts überlappen sie fast vollständig.\n\nDaraus folgt, wozu die Standardisierung dient und wo ihre Grenze liegt. Sie\nmacht Effekte über Messgrössen hinweg vergleichbar, indem sie die Differenz an\nder natürlichen Schwankung misst. Zugleich geht die Einheit verloren: $d = 1.78$\nsagt nicht, dass der Unterschied praktisch zählt.\n\n**Deshalb gehören immer beide Zahlen in den Bericht**: die Differenz in ihrer\nEinheit für die Sache, die Effektstärke für den Vergleich mit anderen Studien.\n\n### Beispiel 2: Derselbe Effekt, verschiedene Stichprobenumfänge\n\n#### Frage und Datenlage\n\nDer Effekt ist festgehalten bei $d = 0.5$. Verändert wird nur der\nStichprobenumfang. Die Frage lautet: Was macht das mit dem p-Wert, und was mit\nder Effektstärke?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd <- 0.5\ntabelle <- data.frame(n_je_gruppe = c(10, 20, 50, 100, 400))\ntabelle$t <- d * sqrt(tabelle$n_je_gruppe / 2)\ntabelle$p <- 2 * (1 - pt(abs(tabelle$t), 2 * tabelle$n_je_gruppe - 2))\ntabelle$d <- d\nround(tabelle, 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  n_je_gruppe       t       p   d\n1          10 1.11803 0.27825 0.5\n2          20 1.58114 0.12214 0.5\n3          50 2.50000 0.01408 0.5\n4         100 3.53553 0.00051 0.5\n5         400 7.07107 0.00000 0.5\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nd = 0.5\nn_je = np.array([10, 20, 50, 100, 400])\nt = d * np.sqrt(n_je / 2)\np = 2 * (1 - stats.t.cdf(np.abs(t), 2 * n_je - 2))\nprint(pd.DataFrame({\"n_je_gruppe\": n_je, \"t\": t.round(3),\n                    \"p\": p.round(5), \"d\": d}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   n_je_gruppe      t        p    d\n0           10  1.118  0.27825  0.5\n1           20  1.581  0.12214  0.5\n2           50  2.500  0.01408  0.5\n3          100  3.536  0.00051  0.5\n4          400  7.071  0.00000  0.5\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| n je Gruppe | t | p | d |\n|---|---|---|---|\n| 10 | 1.118 | 0.278 | 0.5 |\n| 20 | 1.581 | 0.122 | 0.5 |\n| 50 | 2.500 | **0.014** | 0.5 |\n| 100 | 3.536 | **0.0005** | 0.5 |\n| 400 | 7.071 | **< 0.00001** | 0.5 |\n\nDerselbe Effekt wandert von \"nicht nachweisbar\" zu \"hochsignifikant\", ohne dass\nsich an der Sache etwas ändert. Die Effektstärke bleibt konstant, weil sie den\nStichprobenumfang gar nicht enthält.\n\n::: {.note-box}\nDaraus folgen zwei praktische Regeln.\n\n**Ein nicht signifikantes Ergebnis bei kleinem n sagt wenig.** Bei zehn Fällen\nje Gruppe bleibt ein mittlerer Effekt in vier von fünf Fällen unentdeckt, siehe\n[Power](power-stichprobenumfang.qmd).\n\n**Ein signifikantes Ergebnis bei sehr grossem n sagt ebenfalls wenig**, jedenfalls\nnicht über die Grösse. Bei 400 Fällen je Gruppe genügt $d = 0.14$ für p < 0.05.\n:::\n\n#### Interpretation\n\nDiese Tabelle ist der Grund, warum ein p-Wert allein keine Aussage über die\nSache trägt. Er vermischt zwei Dinge: wie gross der Effekt ist und wie viele\nDaten vorliegen. Die Effektstärke trennt das erste heraus.\n\n### Beispiel 3: Effektstärke mit Konfidenzintervall\n\n#### Frage und Datenlage\n\nEffektstärken werden meist als blosse Zahl berichtet. Sie sind aber Schätzungen\nwie jede andere und haben eine Unsicherheit. Wie gross ist sie?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\neffekt(eng_a, eng_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  differenz gepoolte_sd           d    hedges_g       unten        oben \n     0.5000      0.2812      1.7779      1.7166      0.8328      2.7230 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Zum Vergleich das Paket, das die genauere Methode ueber die\n# nichtzentrale t-Verteilung verwendet\neffectsize::cohens_d(eng_b, eng_a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |       95% CI\n------------------------\n1.78      | [0.81, 2.72]\n\n- Estimated using pooled SD.\n```\n\n\n:::\n\n```{.r .cell-code}\neffectsize::hedges_g(eng_b, eng_a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHedges' g |       95% CI\n------------------------\n1.72      | [0.78, 2.63]\n\n- Estimated using pooled SD.\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(effekt(eng_a, eng_b))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndifferenz      0.5000\ngepoolte_sd    0.2812\nd              1.7779\nhedges_g       1.7166\nunten          0.8328\noben           2.7230\ndtype: float64\n```\n\n\n:::\n\n```{.python .cell-code}\n# Wie breit waere das Intervall bei mehr Daten? Dieselbe Effektstaerke,\n# verschiedene Umfaenge.\nd_fest = 1.7779\nfor n in (12, 30, 100, 300):\n    se = np.sqrt(2 * n / (n * n) + d_fest ** 2 / (4 * n))\n    print(f\"n je Gruppe = {n:3d}: {d_fest - 1.96*se:.3f} bis {d_fest + 1.96*se:.3f}\"\n          f\"  (Breite {2*1.96*se:.3f})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn je Gruppe =  12: 0.833 bis 2.723  (Breite 1.890)\nn je Gruppe =  30: 1.180 bis 2.376  (Breite 1.195)\nn je Gruppe = 100: 1.451 bis 2.105  (Breite 0.655)\nn je Gruppe = 300: 1.589 bis 1.967  (Breite 0.378)\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| $d$ | 1.778 | Ein sehr grosser Effekt. |\n| Hedges $g$ | 1.717 | Die Korrektur um Faktor 0.965 bei 24 Fällen. Der Unterschied ist hier klein, bei sechs Fällen je Gruppe wären es rund 8 Prozent. |\n| Näherungsintervall | 0.83 bis 2.72 | **Fast zwei Einheiten breit.** Mit denselben Daten ist alles zwischen \"gross\" und \"extrem gross\" vereinbar. |\n| Intervall bei n = 30 | siehe Ausgabe | Es schrumpft mit wachsendem n, aber langsam: Für eine Halbierung der Breite braucht es viermal so viele Fälle. |\n\n::: {.note-box}\n**Warum die Intervalle zwischen den Verfahren abweichen.** Die Hilfsfunktion auf\ndieser Seite verwendet eine Normalapproximation, damit R und Python dieselbe\nZahl liefern und die Rechnung nachvollziehbar bleibt. Das Paket `effectsize`\nrechnet über die nichtzentrale t-Verteilung und ist damit genauer, besonders bei\nkleinem n und grossem $d$. Die Grössenordnung ist dieselbe, die Grenzen\nunterscheiden sich.\n\nFür einen Bericht ist die Paketvariante die richtige Wahl. Für das Verständnis\nist die Formel nützlich: Der Standardfehler von $d$ hängt fast nur an n, und\ndeshalb sind Effektstärken aus kleinen Studien grundsätzlich unzuverlässig.\n:::\n\n#### Interpretation\n\nDie verbreitete Praxis, eine Effektstärke als blosse Zahl zu berichten, verdeckt\ndiese Unsicherheit. Bei zwölf Fällen je Gruppe ist die Angabe \"$d = 1.78$\"\ntechnisch richtig und praktisch wenig wert; \"$d = 1.78$, Intervall 0.83 bis\n2.72\" ist ehrlich.\n\nDas erklärt auch, warum Effektstärken aus kleinen Studien in Metaanalysen\nregelmässig nach unten korrigiert werden: Kleine Studien, die es überhaupt in\neine Veröffentlichung schaffen, haben meist überschätzte Effekte, weil nur die\nzufällig grossen signifikant wurden.\n\n### Beispiel 4: Eine Effektstärke verständlich machen\n\n#### Frage und Datenlage\n\n\"$d = 0.5$\" sagt Fachleuten etwas und sonst niemandem. Welche Übersetzungen gibt\nes, und was sagen sie?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nuebersetzung <- function(d) {\n  round(c(d = d,\n          r = d / sqrt(d^2 + 4),\n          CLES = pnorm(d / sqrt(2)),\n          ueberlappung = 2 * pnorm(-abs(d) / 2),\n          ueber_median_A = pnorm(d)), 4)\n}\n\nt(sapply(c(0.2, 0.5, 0.8, 1.2, 1.78), uebersetzung))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        d      r   CLES ueberlappung ueber_median_A\n[1,] 0.20 0.0995 0.5562       0.9203         0.5793\n[2,] 0.50 0.2425 0.6382       0.8026         0.6915\n[3,] 0.80 0.3714 0.7142       0.6892         0.7881\n[4,] 1.20 0.5145 0.8019       0.5485         0.8849\n[5,] 1.78 0.6648 0.8959       0.3735         0.9625\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndef uebersetzung(d):\n    return {\n        \"d\": d,\n        \"r\": d / np.sqrt(d ** 2 + 4),\n        \"CLES\": stats.norm.cdf(d / np.sqrt(2)),\n        \"ueberlappung\": 2 * stats.norm.cdf(-abs(d) / 2),\n        \"ueber_median_A\": stats.norm.cdf(d),\n    }\n\n\nprint(pd.DataFrame([uebersetzung(d) for d in (0.2, 0.5, 0.8, 1.2, 1.78)]).round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      d       r    CLES  ueberlappung  ueber_median_A\n0  0.20  0.0995  0.5562        0.9203          0.5793\n1  0.50  0.2425  0.6382        0.8026          0.6915\n2  0.80  0.3714  0.7142        0.6892          0.7881\n3  1.20  0.5145  0.8019        0.5485          0.8849\n4  1.78  0.6648  0.8959        0.3735          0.9625\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| $d$ | $r$ | CLES | Überlappung | Anteil über dem Median von A |\n|---|---|---|---|---|\n| 0.2 | 0.100 | 0.556 | 0.920 | 0.579 |\n| 0.5 | 0.243 | 0.638 | 0.803 | 0.691 |\n| 0.8 | 0.371 | 0.714 | 0.689 | 0.788 |\n| 1.2 | 0.514 | 0.802 | 0.549 | 0.885 |\n| 1.78 | 0.665 | 0.896 | 0.374 | 0.962 |\n\n| Übersetzung | Wie sie sich liest |\n|---|---|\n| $r$ | Für den Vergleich mit Korrelationsstudien. Bemerkenswert: Ein \"grosses\" $d$ von 0.8 entspricht einem $r$ von 0.37, das für sich genommen als mittel gilt. Die Anhaltspunkte der beiden Masse passen nicht zueinander. |\n| CLES | \"Greift man je einen Fall aus beiden Gruppen heraus, liegt der aus B in X Prozent der Fälle höher.\" Die beste Zahl für Nichtfachleute. |\n| Überlappung | \"So viel Prozent der beiden Verteilungen liegen übereinander.\" Macht deutlich, wie viel Gemeinsamkeit auch bei grossen Effekten bleibt. |\n| Anteil über dem Median von A | \"So viele aus B liegen über der Hälfte von A.\" Nützlich, wenn eine Schwelle inhaltlich bedeutsam ist. |\n\n#### Interpretation\n\nDie Zeile für $d = 0.5$ ist die lehrreichste. Ein \"mittlerer\" Effekt bedeutet:\nDie beiden Verteilungen überlappen zu 80 Prozent, und in gut einem Drittel aller\nPaarvergleiche liegt die Kontrollgruppe höher. Wer das ausspricht, erzeugt ein\nsehr viel realistischeres Bild als \"mittlerer Effekt, p < 0.05\".\n\nUmgekehrt zeigt die letzte Zeile, wie ungewöhnlich der Effekt aus Beispiel 1\nist: Bei $d = 1.78$ überlappen die Verteilungen nur noch zu 37 Prozent. Solche\nWerte kommen in erhobenen Daten selten vor und sind ein Anlass zu prüfen, ob die\nbeiden Gruppen sich nicht in etwas anderem unterscheiden als gedacht.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nZwei Studien finden dieselbe Mittelwertdifferenz von 0.5 Einheiten. Studie A\nberichtet $d = 1.78$, Studie B $d = 0.35$. Wie ist das möglich?\n\n- [x] Die Streuung in den Gruppen ist verschieden ~ Richtig. Cohens $d$ misst\n      die Differenz in Einheiten der gepoolten Standardabweichung. Bei enger\n      Streuung ist dieselbe Differenz ein grosser Effekt, bei weiter ein\n      kleiner.\n- [ ] Eine der beiden hat sich verrechnet ~ Beide können korrekt gerechnet\n      haben; $d$ hängt eben nicht nur an der Differenz.\n- [ ] Die Stichprobenumfänge sind verschieden ~ Der Umfang beeinflusst $d$\n      nicht, sondern nur seine Unsicherheit und den p-Wert.\n:::\n\n::: {.quiz}\nEin Versuch mit n = 400 je Gruppe liefert p < 0.001 bei $d = 0.14$. Wie ist das\nzu berichten?\n\n- [x] Als nachweisbarer, aber sehr kleiner Effekt, mit der Differenz in ihrer\n      Einheit ~ Richtig. Der p-Wert sagt nur, dass der Effekt bei diesem Umfang\n      vom Zufall unterscheidbar ist. Ob er zählt, entscheidet die\n      Effektstärke und die Sache.\n- [ ] Als starker Nachweis eines Effekts ~ Stark ist der Nachweis, nicht der\n      Effekt. Die beiden Wörter meinen Verschiedenes.\n- [ ] Gar nicht, $d = 0.14$ liegt unter der Schwelle für \"klein\" ~ Berichtet\n      wird, was gefunden wurde; die Einordnung gehört dazu, das Verschweigen\n      nicht.\n:::\n\n::: {.quiz}\nWarum sollte bei zwölf Fällen je Gruppe Hedges $g$ statt Cohens $d$ berichtet\nwerden?\n\n- [x] Weil $d$ bei kleinen Stichproben systematisch zu gross ausfällt ~ Richtig.\n      Der Korrekturfaktor beträgt hier rund 0.965 und wird mit sinkendem n\n      grösser. Ab etwa 50 Fällen insgesamt ist der Unterschied belanglos.\n- [ ] Weil $g$ ein Konfidenzintervall hat und $d$ nicht ~ Beide haben eines.\n- [ ] Weil $d$ eine Normalverteilung voraussetzt und $g$ nicht ~ Die\n      Voraussetzungen sind dieselben.\n:::\n\n::: {.quiz}\nEin Effekt von $d = 0.5$ gilt als mittel. Was bedeutet das anschaulich?\n\n- [x] Die Verteilungen überlappen zu 80 Prozent; in gut einem Drittel der\n      Paarvergleiche liegt die Kontrollgruppe höher ~ Richtig. Die Common\n      Language Effect Size beträgt 0.638, also gewinnt die Vergleichsgruppe in\n      36 Prozent der Vergleiche. \"Mittel\" klingt deutlicher, als es ist.\n- [ ] Die Hälfte der Fälle verbessert sich ~ Effektstärken beschreiben\n      Verteilungen, nicht Anteile von Personen mit einer Veränderung.\n- [ ] Der Unterschied beträgt 50 Prozent ~ $d$ ist kein Prozentwert, sondern ein\n      Vielfaches der Standardabweichung.\n:::\n\n## Verlinkte Ressourcen\n\n- [effectsize: Übersicht der Masse](https://easystats.github.io/effectsize/)\n- [Power und Stichprobenumfang](power-stichprobenumfang.qmd)\n- [t-Test für zwei Stichproben](../tests/t-test-zwei-stichproben.qmd)\n",
    "supporting": [
      "effektstaerken_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}