{
  "hash": "1cd530cf0b56a6f54a19f9f36d72db0e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Faktorenanalyse\"\ndescription: \"Latente Faktoren schätzen, Rotation und Abgrenzung zur Hauptkomponentenanalyse.\"\ncategories: [\"Faktorenanalyse\", \"Dimensionsreduktion\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: methode\nstand: entwurf\norder: 30\n---\n\n\n\n\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Welche wenigen nicht beobachtbaren Grössen erzeugen die Korrelationen zwischen vielen beobachteten Variablen? |\n| Zielvariable | keine, das Verfahren ist unüberwacht |\n| Eingang | mehrere metrische oder als metrisch behandelte Variablen, meist Fragebogenitems |\n| Was die Methode liefert | Ladungsmatrix nach Rotation, Kommunalitäten, erklärte Varianz je Faktor, Faktorwerte |\n| R-Funktion | `psych::fa(daten, nfactors = 2, rotate = \"oblimin\")` |\n| Python-Funktion | `FactorAnalyzer(n_factors=2, rotation=\"oblimin\").fit(daten)` |\n| Verwandte Methoden | [Hauptkomponentenanalyse](hauptkomponentenanalyse.qmd), Strukturgleichungsmodelle |\n\n## Wann diese Methode, wann nicht\n\nTypische Fragestellungen: Welche Dimensionen misst ein Fragebogen wirklich,\nlassen sich zwanzig Items zu drei Skalen zusammenfassen, misst eine Skala das,\nwas sie messen soll.\n\nDer Unterschied zur [Hauptkomponentenanalyse](hauptkomponentenanalyse.qmd) ist\nnicht rechnerischer Feinschliff, sondern die Denkrichtung. Die\nHauptkomponentenanalyse fasst beobachtete Variablen zusammen: Die Komponente ist\neine Summe der Items. Die Faktorenanalyse unterstellt das Gegenteil: Es gibt\nnicht beobachtbare Grössen, und die Items sind deren Ausprägungen plus\nEigenanteil. Wer nach Ursachen fragt, braucht die Faktorenanalyse; wer nur\nverdichten will, die Komponentenanalyse.\n\n| Situation | Stattdessen |\n|---|---|\n| Nur Verdichtung, keine Deutung als Ursache | [Hauptkomponentenanalyse](hauptkomponentenanalyse.qmd) |\n| Die Faktorstruktur ist bereits bekannt und soll geprüft werden | konfirmatorische Faktorenanalyse, Strukturgleichungsmodelle |\n| Gruppen von Personen statt Dimensionen von Items | [k-Means](k-means.qmd) |\n| Es gibt eine Zielvariable | [Regression](../regression/index.qmd) |\n| Items sind binär oder stark schief | Faktorenanalyse auf polychorischen Korrelationen |\n| Weniger als etwa drei Items je erwartetem Faktor | keine sinnvolle Schätzung möglich |\n\n## Grundidee und Modell\n\nJedes Item wird als Kombination gemeinsamer Faktoren und eines Eigenanteils\nbeschrieben:\n\n$$x_j = \\lambda_{j1} F_1 + \\dots + \\lambda_{jm} F_m + e_j$$\n\n| Bestandteil | Bedeutung |\n|---|---|\n| $x_j$ | beobachtetes Item $j$, standardisiert |\n| $F_k$ | latenter Faktor $k$, nicht beobachtbar |\n| $\\lambda_{jk}$ | Ladung: wie stark Faktor $k$ auf Item $j$ wirkt |\n| $e_j$ | Eigenanteil des Items, alles Nichtgemeinsame samt Messfehler |\n| Kommunalität | Anteil der Varianz von $x_j$, den die Faktoren erklären, also die Summe der quadrierten Ladungen |\n| Uniqueness | eins minus Kommunalität, der Eigenanteil |\n\nDer Unterschied zur Komponentenanalyse steckt genau in $e_j$: Die\nFaktorenanalyse modelliert nur die **gemeinsame** Varianz und lässt den\nEigenanteil ausdrücklich draussen. Deshalb sind ihre Ladungen in der Regel etwas\nkleiner, und deshalb ist sie das richtige Werkzeug, wenn Messfehler eine Rolle\nspielt.\n\n**Rotation** löst ein Problem der Deutbarkeit: Die Lage der Faktoren im Raum ist\nnicht eindeutig bestimmt, man kann sie drehen, ohne die Anpassung zu ändern.\nGedreht wird auf Einfachstruktur, also darauf, dass jedes Item möglichst nur auf\neinem Faktor hoch lädt. Orthogonale Rotation, etwa Varimax, hält die Faktoren\nunkorreliert; oblique Rotation, etwa Oblimin, erlaubt Korrelation zwischen ihnen.\nBei inhaltlich verwandten Dimensionen ist oblique die realistischere Annahme.\n\n::: {.note-box}\n**Reihenfolge und Vorzeichen der Faktoren sind beliebig.** Welcher Faktor als\nerster ausgegeben wird und ob seine Ladungen positiv oder negativ sind, ist eine\nEigenschaft des Rechenverfahrens, keine des Fragebogens. Ein Faktor wird deshalb\nnie über seine Nummer benannt, sondern über die Items, die auf ihm laden.\n:::\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung | Vorgehen |\n|---|---|---|---|---|\n| Genügend Korrelation | Die Items hängen zusammen | Korrelationsmatrix, Bartlett-Test, KMO-Kriterium | Keine gemeinsamen Faktoren auffindbar | Items überarbeiten, Analyse abbrechen |\n| Genügend Beobachtungen | Faustregel: mindestens fünf bis zehn je Item, nie unter 100 | n zählen | Ladungen instabil, Struktur nicht reproduzierbar | mehr Daten, weniger Items |\n| Genügend Items je Faktor | mindestens drei, besser vier | Struktur planen | Faktor nicht identifizierbar | Items ergänzen oder Faktoren zusammenlegen |\n| Metrisch oder annähernd metrisch | Korrelationen sind sinnvoll interpretierbar | Skalenniveau, Verteilung der Items | Ladungen verzerrt | polychorische Korrelationen |\n| Lineare Zusammenhänge | Ladungen beschreiben lineare Wirkung | Streudiagramme | Struktur wird verfehlt | Transformation |\n| Keine extremen Ausreisser | Korrelationen nicht von Einzelfällen getrieben | Ausreisserdiagnostik | Faktoren richten sich auf Ausreisser aus | Ursachen prüfen |\n\n## Output lesen\n\nR, `psych::fa()`:\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| `loadings` | Ladung je Item und Faktor nach Rotation | ab etwa 0.4 als bedeutsam, ab 0.3 erwähnenswert |\n| `communality` | Anteil der Itemvarianz, den die Faktoren erklären | unter 0.3 heisst: Item passt nicht zur Struktur |\n| `uniquenesses` | Eigenanteil, eins minus Kommunalität | hoch bei Items, die etwas Eigenes messen |\n| `SS loadings` | Summe der quadrierten Ladungen je Faktor | Beitrag des Faktors, in Varianzeinheiten |\n| `Proportion Var` | Anteil der Gesamtvarianz je Faktor | summiert über Faktoren die gemeinsame Varianz |\n| `Cor of factors` | Korrelation zwischen den Faktoren | nur bei obliquer Rotation vorhanden |\n| `Mean item complexity` | wie viele Faktoren ein Item durchschnittlich braucht | nahe 1 heisst gute Einfachstruktur |\n| `RMSEA`, `TLI`, `BIC` | Anpassungsmasse | RMSEA unter 0.06 gilt als gut, aber vor allem bei bestätigenden Modellen aussagekräftig |\n| Warnung `Heywood case` | eine Kommunalität über eins | Modell überparametrisiert; Faktorenzahl reduzieren |\n\nPython, `FactorAnalyzer`:\n\n| Zugriff | Was er liefert | Unterschied zu R |\n|---|---|---|\n| `loadings_` | Ladungsmatrix nach Rotation | Zeilen sind Items, wie in R |\n| `get_communalities()` | Kommunalitäten | wie `communality` |\n| `get_factor_variance()` | Summe der Ladungen, Anteil, kumuliert | in R Teil der Ausgabe von `print` |\n| `get_uniquenesses()` | Eigenanteile | wie `uniquenesses` |\n| `phi_` | Faktorkorrelationen bei obliquer Rotation | wie `Cor of factors` |\n| keine Anpassungsmasse | RMSEA und Ähnliches fehlen | in R vorhanden |\n| kein Abschneiden der Anzeige | Filterung selbst vornehmen | in R über `cutoff =` |\n\nEin Unterschied in der Vorgabe: R verwendet in `fa()` standardmässig Oblimin,\nPython ohne Angabe keine Rotation. Ohne Rotation ist die Ladungsmatrix fast\nimmer unlesbar, deshalb gehört sie ausdrücklich gesetzt.\n\n## Interpretationsfallen\n\n- **Faktoren sind keine gemessenen Grössen.** Sie sind Modellkonstrukte, deren\n  Deutung von den Items kommt und nicht von der Rechnung.\n- **Faktorenanalyse ist keine Komponentenanalyse.** Die eine modelliert\n  gemeinsame Varianz und Messfehler, die andere verdichtet beobachtete Varianz.\n  Wer Ladungen der einen mit Komponenten der anderen vergleicht, vergleicht\n  Verschiedenes.\n- **Erklärte Varianz taugt nicht zur Faktorenwahl.** Sie steigt mit jedem\n  Faktor; entscheidend sind Screeplot, Parallelanalyse und Deutbarkeit.\n- **Rotation ändert die Anpassung nicht.** Sie verbessert nur die Lesbarkeit.\n  Wer verschiedene Rotationen ausprobiert, bis eine These bestätigt ist, betreibt\n  keine Analyse.\n- **Ladungsschwellen sind Konvention.** 0.3 oder 0.4 sind Faustregeln, keine\n  Grenzen mit statistischer Bedeutung.\n- **Ein Heywood-Fall ist ein Warnsignal**, keine Formalie: Eine Kommunalität über\n  eins ist unmöglich und heisst, dass das Modell zu gross ist.\n- **Explorativ ist nicht bestätigend.** Wer eine Struktur an denselben Daten\n  findet und dort prüft, prüft nichts. Bestätigung braucht neue Daten und ein\n  konfirmatorisches Modell.\n\n## Ergebnis berichten\n\nVorlage für den Ergebnissatz:\n\n> Eine explorative Faktorenanalyse ([Schätzmethode], [Rotation], n = [n],\n> KMO = [Wert], Bartlett p = [p]) ergibt [Anzahl] Faktoren, die zusammen [Anteil]\n> der Varianz erklären. Faktor 1 lädt hoch auf [Items] und wird als [Deutung]\n> gelesen, Faktor 2 auf [Items] als [Deutung]. Die Faktoren korrelieren mit\n> [Wert]. Item [Name] wurde wegen einer Kommunalität von [Wert] nicht\n> berücksichtigt.\n\nGenannt werden: Schätzmethode und Rotation, n, Eignungsmasse, Kriterium für die\nFaktorenzahl, die Ladungsmatrix mit Schwelle, Kommunalitäten, erklärte Varianz,\nFaktorkorrelationen und die inhaltliche Deutung jedes Faktors.\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt der explorativen Faktorenanalyse |\n|---|---|\n| [Hauptkomponentenanalyse](hauptkomponentenanalyse.qmd) | Verdichtung ohne Anspruch auf latente Ursachen |\n| Konfirmatorische Faktorenanalyse | die Struktur ist theoretisch vorgegeben und soll geprüft werden |\n| Strukturgleichungsmodelle | Faktoren sollen zusätzlich untereinander in Beziehung stehen |\n| [k-Means](k-means.qmd) | Gruppen von Personen statt Dimensionen von Items |\n| Item-Response-Modelle | binäre oder stark abgestufte Items, Fähigkeitsmessung |\n\n## Beispiele\n\nAlle vier Beispiele arbeiten mit demselben konstruierten Datensatz: 400\nBefragte, neun Items eines Zufriedenheitsfragebogens. Vier Items entstehen aus\neinem gemeinsamen Faktor Betreuung, vier aus einem Faktor Anlage, und ein Item\nzum Parkplatz misst etwas Eigenes. Weil die Wahrheit hier bekannt ist, lässt sich\nprüfen, ob das Verfahren sie findet.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Darf man überhaupt anfangen?\n\n#### Frage und Datenlage\n\nBevor Faktoren geschätzt werden, ist zu klären, ob die Korrelationsmatrix\nüberhaupt gemeinsame Struktur enthält. Ohne Korrelationen gibt es nichts\nzusammenzufassen, und das Verfahren liefert trotzdem eine Lösung.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(cor(fragebogen), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             freundlich beratung erreichbar hilfsbereit geraete sauberkeit\nfreundlich         1.00     0.71       0.65        0.66   -0.08      -0.03\nberatung           0.71     1.00       0.67        0.65   -0.09      -0.08\nerreichbar         0.65     0.67       1.00        0.65    0.01      -0.01\nhilfsbereit        0.66     0.65       0.65        1.00   -0.08      -0.06\ngeraete           -0.08    -0.09       0.01       -0.08    1.00       0.63\nsauberkeit        -0.03    -0.08      -0.01       -0.06    0.63       1.00\ngarderobe         -0.08    -0.09      -0.04       -0.04    0.61       0.63\nplatzangebot      -0.07    -0.13      -0.05       -0.12    0.61       0.63\nparkplatz          0.02     0.05       0.05        0.05    0.05       0.00\n             garderobe platzangebot parkplatz\nfreundlich       -0.08        -0.07      0.02\nberatung         -0.09        -0.13      0.05\nerreichbar       -0.04        -0.05      0.05\nhilfsbereit      -0.04        -0.12      0.05\ngeraete           0.61         0.61      0.05\nsauberkeit        0.63         0.63      0.00\ngarderobe         1.00         0.53     -0.01\nplatzangebot      0.53         1.00     -0.06\nparkplatz        -0.01        -0.06      1.00\n```\n\n\n:::\n\n```{.r .cell-code}\nKMO(fragebogen)$MSA                                    # gesamtes KMO-Mass\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.823533\n```\n\n\n:::\n\n```{.r .cell-code}\nround(KMO(fragebogen)$MSAi, 3)                         # je Item\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  freundlich     beratung   erreichbar  hilfsbereit      geraete   sauberkeit \n       0.821        0.828        0.842        0.849        0.807        0.806 \n   garderobe platzangebot    parkplatz \n       0.820        0.825        0.382 \n```\n\n\n:::\n\n```{.r .cell-code}\ncortest.bartlett(cor(fragebogen), n = nrow(fragebogen))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$chisq\n[1] 1600.856\n\n$p.value\n[1] 1.560567e-313\n\n$df\n[1] 36\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom factor_analyzer.factor_analyzer import (calculate_kmo,\n                                             calculate_bartlett_sphericity)\n\nprint(fragebogen.corr().round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              freundlich  beratung  ...  platzangebot  parkplatz\nfreundlich          1.00      0.71  ...         -0.07       0.02\nberatung            0.71      1.00  ...         -0.13       0.05\nerreichbar          0.65      0.67  ...         -0.05       0.05\nhilfsbereit         0.66      0.65  ...         -0.12       0.05\ngeraete            -0.08     -0.09  ...          0.61       0.05\nsauberkeit         -0.03     -0.08  ...          0.63      -0.00\ngarderobe          -0.08     -0.09  ...          0.53      -0.01\nplatzangebot       -0.07     -0.13  ...          1.00      -0.06\nparkplatz           0.02      0.05  ...         -0.06       1.00\n\n[9 rows x 9 columns]\n```\n\n\n:::\n\n```{.python .cell-code}\nkmo_item, kmo_gesamt = calculate_kmo(fragebogen)\nprint(\"KMO gesamt:\", round(kmo_gesamt, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKMO gesamt: 0.824\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pd.Series(kmo_item, index=fragebogen.columns).round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfreundlich      0.821\nberatung        0.828\nerreichbar      0.842\nhilfsbereit     0.849\ngeraete         0.807\nsauberkeit      0.806\ngarderobe       0.820\nplatzangebot    0.825\nparkplatz       0.382\ndtype: float64\n```\n\n\n:::\n\n```{.python .cell-code}\nchi2, p = calculate_bartlett_sphericity(fragebogen)\nprint(f\"Bartlett: chi2 = {chi2:.1f}, p = {p:.3g}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBartlett: chi2 = 1600.9, p = 0\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Korrelationsmatrix | zwei Blöcke um 0.6 bis 0.7, sonst nahe null | Die vier Betreuungsitems korrelieren untereinander, die vier Anlageitems untereinander, quer darüber praktisch nicht. Genau diese Blockstruktur ist das, was die Faktorenanalyse in Faktoren übersetzt. |\n| Parkplatz-Zeile | alle Werte unter 0.1 | Das Item hängt mit keinem anderen zusammen. |\n| KMO gesamt | **0.824** | Über 0.8 gilt als gut. Das Mass fragt, wie stark die Korrelation zweier Items durch die übrigen erklärt wird; hohe Werte heissen, dass gemeinsame Struktur vorliegt. |\n| KMO je Item | für `parkplatz` deutlich am tiefsten | Unter 0.5 wäre ein Grund, das Item vor der Analyse zu entfernen. |\n| Bartlett $\\chi^2$ | rund 1601 bei 36 Freiheitsgraden | Prüft die Nullhypothese, die Korrelationsmatrix sei die Einheitsmatrix. |\n| Bartlett p | praktisch null | Die Matrix weicht von der Einheitsmatrix ab. |\n\n::: {.note-box}\nBeide Kennzahlen sind **Eingangsprüfungen**. Sie sagen, ob man anfangen darf,\nnicht ob das Ergebnis gut wird. Der Bartlett-Test ist dabei der schwächere von\nbeiden: Bei n = 400 wird er praktisch immer signifikant, auch bei schwachen\nKorrelationen. Aussagekräftig ist vor allem, wenn er **nicht** signifikant wird,\ndenn dann ist die Analyse sinnlos.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Korrelationsmatrix eignet sich für eine Faktorenanalyse (KMO = 0.82,\n> Bartlett-Test auf Sphärizität $\\chi^2$(36) = 1601, p < .001, n = 400).\n\n### Beispiel 2: Die Zweifaktorenlösung\n\n#### Frage und Datenlage\n\nZwei Faktoren werden geschätzt und oblique rotiert. Die Frage: Findet das\nVerfahren die Struktur, die den Daten zugrunde liegt?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nefa <- fa(fragebogen, nfactors = 2, rotate = \"oblimin\", fm = \"ml\")\n\nprint(efa$loadings, cutoff = 0.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLoadings:\n             ML2    ML1   \nfreundlich    0.833       \nberatung      0.834       \nerreichbar    0.802       \nhilfsbereit   0.790       \ngeraete              0.795\nsauberkeit           0.819\ngarderobe            0.752\nplatzangebot         0.749\nparkplatz                 \n\n                 ML2   ML1\nSS loadings    2.661 2.435\nProportion Var 0.296 0.271\nCumulative Var 0.296 0.566\n```\n\n\n:::\n\n```{.r .cell-code}\nround(data.frame(kommunalitaet = efa$communality,\n                 eigenanteil = efa$uniquenesses), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             kommunalitaet eigenanteil\nfreundlich           0.693       0.307\nberatung             0.703       0.297\nerreichbar           0.638       0.362\nhilfsbereit          0.627       0.373\ngeraete              0.631       0.369\nsauberkeit           0.668       0.332\ngarderobe            0.566       0.434\nplatzangebot         0.568       0.432\nparkplatz            0.003       0.997\n```\n\n\n:::\n\n```{.r .cell-code}\nround(efa$Phi, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       ML2    ML1\nML2  1.000 -0.099\nML1 -0.099  1.000\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nefa = FactorAnalyzer(n_factors=2, rotation=\"oblimin\",\n                     method=\"ml\").fit(fragebogen)\n\nladungen = pd.DataFrame(efa.loadings_, index=fragebogen.columns,\n                        columns=[\"F1\", \"F2\"]).round(3)\nprint(ladungen.where(ladungen.abs() >= 0.3, \"\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 F1     F2\nfreundlich    0.833       \nberatung      0.834       \nerreichbar    0.802       \nhilfsbereit    0.79       \ngeraete              0.795\nsauberkeit           0.819\ngarderobe            0.752\nplatzangebot         0.749\nparkplatz                 \n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pd.DataFrame({\n    \"kommunalitaet\": efa.get_communalities().round(3),\n    \"eigenanteil\": efa.get_uniquenesses().round(3),\n}, index=fragebogen.columns))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              kommunalitaet  eigenanteil\nfreundlich            0.693        0.307\nberatung              0.697        0.303\nerreichbar            0.646        0.354\nhilfsbereit           0.625        0.375\ngeraete               0.632        0.368\nsauberkeit            0.672        0.328\ngarderobe             0.566        0.434\nplatzangebot          0.563        0.437\nparkplatz             0.003        0.997\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pd.DataFrame(efa.get_factor_variance(),\n                   index=[\"SS loadings\", \"Anteil\", \"kumuliert\"],\n                   columns=[\"F1\", \"F2\"]).round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                F1     F2\nSS loadings  2.661  2.435\nAnteil       0.296  0.271\nkumuliert    0.296  0.566\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Faktorkorrelation:\", np.round(efa.phi_[0, 1], 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFaktorkorrelation: -0.099\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nDie Ladungsmatrix (Python-Werte, gerundet; die Ladungen unter 0.3 sind in der\nAnzeige ausgeblendet, das ist eine Darstellungsentscheidung):\n\n| Item | Faktor mit den Betreuungsitems | Faktor mit den Anlageitems | Kommunalität |\n|---|---|---|---|\n| freundlich | **0.833** | 0.003 | 0.693 |\n| beratung | **0.834** | -0.040 | 0.697 |\n| erreichbar | **0.802** | 0.053 | 0.646 |\n| hilfsbereit | **0.790** | -0.013 | 0.625 |\n| geraete | 0.004 | **0.795** | 0.632 |\n| sauberkeit | 0.025 | **0.819** | 0.672 |\n| garderobe | 0.000 | **0.752** | 0.566 |\n| platzangebot | -0.038 | **0.749** | 0.563 |\n| parkplatz | 0.052 | 0.004 | **0.003** |\n\n| Grösse | Wert hier | Bedeutung |\n|---|---|---|\n| Ladung, etwa 0.833 | Zusammenhang von Item und Faktor | Bei standardisierten Items ist sie die Korrelation zwischen Item und Faktor. Quadriert ergibt sie den erklärten Varianzanteil: $0.833^2 \\approx 0.69$. |\n| Nebenladungen | alle unter 0.06 | **Einfachstruktur**: Jedes Item lädt auf genau einem Faktor. Das ist der Idealfall, den die Rotation anstrebt. |\n| Kommunalität | 0.56 bis 0.70 | Der von beiden Faktoren erklärte Varianzanteil eines Items. Hier ist es die quadrierte Hauptladung, weil die Nebenladung fast null ist. |\n| Eigenanteil | eins minus Kommunalität | Bei `freundlich` bleiben 0.307 unerklärt: Messfehler plus alles, was nur dieses Item misst. |\n| `SS loadings` | 2.661 und 2.435 | Summe der quadrierten Ladungen je Faktor, also sein Beitrag in Varianzeinheiten. Bei neun Items entspricht die Gesamtvarianz dem Wert 9. |\n| Anteil | 0.296 und 0.271 | 2.661 / 9 = 0.296. Zusammen erklären die beiden Faktoren **56.6 Prozent** der Gesamtvarianz. |\n| Faktorkorrelation | **-0.099** | Bei obliquer Rotation Teil des Ergebnisses. Nahe null heisst: Die beiden Dimensionen sind unabhängig, eine orthogonale Rotation hätte hier genauso gut gepasst. |\n\n::: {.note-box}\nDas Vorzeichen der Faktorkorrelation ist so wenig aussagekräftig wie das\nVorzeichen einer Ladungsspalte: Kehrt man einen Faktor um, kehrt sich auch die\nKorrelation um. Interessant ist allein ihr Betrag.\n:::\n\n#### Interpretation und Ergebnissatz\n\nDie Rechnung hat die eingebaute Struktur gefunden. Die **Deutung** kommt aber\nnicht aus der Rechnung, sondern aus den Items: Der eine Faktor bündelt\nfreundlich, beratung, erreichbar und hilfsbereit und lässt sich als\nZufriedenheit mit der Betreuung lesen; der andere bündelt geraete, sauberkeit,\ngarderobe und platzangebot und steht für die Zufriedenheit mit der Anlage.\n\nEin Faktor ohne inhaltliche Beschreibung ist kein Ergebnis, sondern eine\nZahlenspalte.\n\n> Eine explorative Faktorenanalyse (Maximum-Likelihood-Schätzung,\n> Oblimin-Rotation, n = 400, KMO = 0.82) ergibt zwei Faktoren, die zusammen 56.6\n> Prozent der Varianz erklären. Der erste Faktor lädt hoch auf die vier Items zur\n> Betreuung (Ladungen 0.79 bis 0.83) und wird als Zufriedenheit mit der Betreuung\n> gelesen, der zweite auf die vier Items zur Anlage (0.75 bis 0.82) als\n> Zufriedenheit mit der Anlage. Die Faktoren korrelieren zu -0.10.\n\n### Beispiel 3: Ein Item, das nicht passt\n\n#### Frage und Datenlage\n\nEin Fragebogen enthält fast immer Items, die nicht zur gefundenen Struktur\ngehören. Woran erkennt man sie, und was macht man mit ihnen?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(sort(efa$communality), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   parkplatz    garderobe platzangebot  hilfsbereit      geraete   erreichbar \n       0.003        0.566        0.568        0.627        0.631        0.638 \n  sauberkeit   freundlich     beratung \n       0.668        0.693        0.703 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(efa$loadings[\"parkplatz\", ], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ML2   ML1 \n0.052 0.004 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Was passiert, wenn das Item entfernt wird?\nohne <- fa(fragebogen[, names(fragebogen) != \"parkplatz\"],\n           nfactors = 2, rotate = \"oblimin\", fm = \"ml\")\nround(ohne$Vaccounted[\"Proportion Var\", ], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ML1   ML2 \n0.332 0.304 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nkommunalitaeten = pd.Series(efa.get_communalities(), index=fragebogen.columns)\nprint(kommunalitaeten.sort_values().round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nparkplatz       0.003\nplatzangebot    0.563\ngarderobe       0.566\nhilfsbereit     0.625\ngeraete         0.632\nerreichbar      0.646\nsauberkeit      0.672\nfreundlich      0.693\nberatung        0.697\ndtype: float64\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(ladungen.loc[\"parkplatz\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nF1    0.052\nF2    0.004\nName: parkplatz, dtype: float64\n```\n\n\n:::\n\n```{.python .cell-code}\nohne = FactorAnalyzer(n_factors=2, rotation=\"oblimin\", method=\"ml\") \\\n    .fit(fragebogen.drop(columns=\"parkplatz\"))\nprint(\"Anteil je Faktor ohne parkplatz:\",\n      np.round(ohne.get_factor_variance()[1], 3).tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnteil je Faktor ohne parkplatz: [0.332, 0.304]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Kommunalität `parkplatz` | **0.003** | Die beiden Faktoren erklären 0.3 Prozent seiner Varianz. Praktisch nichts. |\n| nächsthöhere Kommunalität | 0.563 (`platzangebot`) | Der Abstand ist der eigentliche Befund: Das Item fällt nicht knapp durch, es gehört gar nicht dazu. |\n| Ladungen `parkplatz` | 0.052 und 0.004 | Weit unter jeder üblichen Schwelle von 0.3 oder 0.4. |\n| Anteile ohne das Item | steigen gegenüber 0.296 / 0.271 | **Kein inhaltlicher Gewinn.** Die Anteile beziehen sich auf acht statt neun Items, also auf eine kleinere Gesamtvarianz. Wer nach dem Entfernen eines Items eine höhere erklärte Varianz meldet, meldet einen Rechenartefakt. |\n\n#### Interpretation und Ergebnissatz\n\nDas Item misst etwas Eigenes, das mit den beiden gefundenen Dimensionen nichts\nzu tun hat. **Das ist ein Befund, kein Fehler** — die Zufriedenheit mit dem\nParkplatz kann für die Befragten durchaus wichtig sein, sie ist nur keine\nAusprägung von Betreuung oder Anlage.\n\nDrei Wege sind vertretbar, einer nicht:\n\n| Vorgehen | Wann angemessen |\n|---|---|\n| Item entfernen | Es trägt zur Fragestellung nichts bei. |\n| Als Einzelfrage stehen lassen | Es ist inhaltlich wichtig, geht aber in keine Skala ein. |\n| Weitere Items zum Thema ergänzen | Es gibt eine dritte Dimension, für die bisher nur ein Item vorliegt. |\n| **Einer bestehenden Skala zuschlagen** | **Nie.** Die Skala misst danach etwas Vermischtes, und ihre Zuverlässigkeit sinkt. |\n\n> Das Item zum Parkplatz lädt auf keinen der beiden Faktoren (Ladungen 0.05 und\n> 0.00, Kommunalität 0.003) und geht in keine Skala ein.\n\n### Beispiel 4: Wie viele Faktoren?\n\n#### Frage und Datenlage\n\nDie Faktorenzahl ist die wichtigste Entscheidung der ganzen Analyse, und sie\nwird nicht von der Rechnung getroffen. Drei Kriterien werden verglichen —\ninklusive eines Falls, in dem das bekannteste davon in die Irre führt.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\neigen_werte <- eigen(cor(fragebogen))$values\nround(eigen_werte, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.179 2.641 1.007 0.479 0.399 0.360 0.339 0.319 0.277\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mar = c(4, 4, 3, 1))\nplot(eigen_werte, type = \"b\", pch = 16, xlab = \"Faktor\", ylab = \"Eigenwert\",\n     main = \"Screeplot\")\nabline(h = 1, lty = 2)\n\n# Parallelanalyse: Vergleich mit Eigenwerten aus Zufallsdaten gleicher Groesse\nparallel <- fa.parallel(fragebogen, fa = \"fa\", plot = FALSE, n.iter = 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParallel analysis suggests that the number of factors =  2  and the number of components =  NA \n```\n\n\n:::\n\n```{.r .cell-code}\nparallel$nfact\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 4: Eigenwerte der Korrelationsmatrix mit der Schwelle bei eins.](faktorenanalyse_files/figure-html/fig-b4-fa-r-1.png){#fig-b4-fa-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\neigenwerte = FactorAnalyzer(n_factors=9, rotation=None) \\\n    .fit(fragebogen).get_eigenvalues()[0]\nprint(eigenwerte.round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[3.179 2.641 1.007 0.479 0.399 0.36  0.339 0.319 0.277]\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, achse = plt.subplots(figsize=(7, 3.4))\nachse.plot(range(1, 10), eigenwerte, \"o-\", color=\"#2166ac\")\nachse.axhline(1, linestyle=\"--\", color=\"black\", linewidth=0.8)\nachse.set_xlabel(\"Faktor\")\nachse.set_ylabel(\"Eigenwert\")\nachse.set_title(\"Screeplot\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselben Eigenwerte in Python.](faktorenanalyse_files/figure-html/fig-b4-fa-py-1.png){#fig-b4-fa-py width=100%}\n:::\n\n```{.python .cell-code}\n# Parallelanalyse von Hand\nzufall = np.zeros((20, 9))\nfor i in range(20):\n    daten = pd.DataFrame(normalwerte(100 + i, 9 * n).reshape(n, 9))\n    zufall[i] = FactorAnalyzer(n_factors=9,\n                               rotation=None).fit(daten).get_eigenvalues()[0]\n\nvergleich = pd.DataFrame({\"daten\": eigenwerte.round(3),\n                          \"zufall_mittel\": zufall.mean(axis=0).round(3)},\n                         index=[f\"F{i + 1}\" for i in range(9)])\nprint(vergleich)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    daten  zufall_mittel\nF1  3.179          1.232\nF2  2.641          1.146\nF3  1.007          1.096\nF4  0.479          1.046\nF5  0.399          0.999\nF6  0.360          0.947\nF7  0.339          0.902\nF8  0.319          0.853\nF9  0.277          0.779\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"über dem Zufallsniveau:\", int((eigenwerte > zufall.mean(axis=0)).sum()))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nüber dem Zufallsniveau: 2\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nDie neun Eigenwerte der Korrelationsmatrix:\n\n| Rang | 1 | 2 | **3** | 4 | 5 | 6 | 7 | 8 | 9 |\n|---|---|---|---|---|---|---|---|---|---|\n| Eigenwert | 3.179 | 2.641 | **1.007** | 0.479 | 0.399 | 0.360 | 0.339 | 0.319 | 0.277 |\n\n| Kriterium | Was es hier sagt | Bewertung |\n|---|---|---|\n| **Kaiser** (Eigenwert > 1) | 3.179, 2.641 und 1.007 liegen über eins → **drei** Faktoren | Die Antwort ist falsch. Der dritte Eigenwert stammt vom Parkplatz-Item, das mit nichts korreliert: Ein völlig isoliertes Item hat immer einen Eigenwert nahe eins. Kaiser zählt es als Faktor, obwohl es nur eine Variable trägt. |\n| **Screeplot** | Der Knick liegt nach dem zweiten Wert; von 2.641 auf 1.007 und dann auf 0.479 | Zwei Faktoren. Der Knick ist deutlich, aber die Ablesung bleibt Augenmass. |\n| **Parallelanalyse** | Zufallsdaten derselben Grösse liefern Eigenwerte um eins herum; nur die ersten beiden echten Werte liegen klar darüber | **Zwei Faktoren**, und dies ist die verlässlichste der drei Auskünfte. |\n\n::: {.note-box}\nDas Kaiser-Kriterium ist verbreitet und die schwächste der drei Regeln. Die\nSchwelle von eins bedeutet nur \"der Faktor erklärt mehr als eine einzelne\nVariable\" — und genau diese Schwelle erreicht ein isoliertes Item von selbst,\nohne irgendetwas zu bündeln. Die **Parallelanalyse** vergleicht dagegen mit dem,\nwas reiner Zufall bei dieser Anzahl Items und Beobachtungen hervorbringt, und\nberücksichtigt damit die Grösse des Datensatzes.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Faktorenzahl wurde über eine Parallelanalyse bestimmt (20 Ziehungen); zwei\n> Faktoren liegen über dem Zufallsniveau. Das Kaiser-Kriterium legt drei Faktoren\n> nahe, der dritte Eigenwert (1.007) stammt jedoch von einem Item ohne\n> Korrelation zu den übrigen und trägt keinen deutbaren Faktor.\n\n### Beispiel 5: Zu viele Faktoren\n\n#### Frage und Datenlage\n\nWer der erklärten Varianz folgt, wählt zu viele Faktoren, denn sie steigt mit\njedem zusätzlichen. Was dabei herauskommt, zeigt eine Lösung mit vier Faktoren\nauf denselben Daten.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nefa_zu_viele <- fa(fragebogen, nfactors = 4, rotate = \"oblimin\", fm = \"ml\")\n\nprint(efa_zu_viele$loadings, cutoff = 0.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLoadings:\n             ML2    ML3    ML1    ML4   \nfreundlich    0.845                     \nberatung      0.830                     \nerreichbar    0.798                     \nhilfsbereit   0.787                     \ngeraete              0.584         0.354\nsauberkeit           0.636              \ngarderobe                   0.991       \nplatzangebot         0.862              \nparkplatz                               \n\n                 ML2   ML3   ML1   ML4\nSS loadings    2.663 1.521 1.040 0.219\nProportion Var 0.296 0.169 0.116 0.024\nCumulative Var 0.296 0.465 0.580 0.605\n```\n\n\n:::\n\n```{.r .cell-code}\nround(efa_zu_viele$Vaccounted[\"Proportion Var\", ], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ML2   ML3   ML1   ML4 \n0.296 0.186 0.129 0.031 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(sort(efa_zu_viele$communality, decreasing = TRUE), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   garderobe      geraete   freundlich     beratung platzangebot   erreichbar \n       0.995        0.726        0.713        0.700        0.680        0.649 \n hilfsbereit   sauberkeit    parkplatz \n       0.631        0.620        0.062 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nefa_viele = FactorAnalyzer(n_factors=4, rotation=\"oblimin\",\n                           method=\"ml\").fit(fragebogen)\n\nviele = pd.DataFrame(efa_viele.loadings_, index=fragebogen.columns,\n                     columns=[f\"F{i + 1}\" for i in range(4)]).round(3)\nprint(viele.where(viele.abs() >= 0.3, \"\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 F1     F2    F3     F4\nfreundlich    0.845                    \nberatung       0.83                    \nerreichbar    0.799                    \nhilfsbereit   0.787                    \ngeraete              0.611        0.338\nsauberkeit           0.643             \ngarderobe                   0.99       \nplatzangebot         0.862             \nparkplatz                              \n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Anteil je Faktor:\",\n      np.round(efa_viele.get_factor_variance()[1], 3).tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnteil je Faktor: [0.296, 0.173, 0.115, 0.023]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nDie vier Ladungsspalten (Python-Werte):\n\n| Item | F1 | F2 | F3 | F4 |\n|---|---|---|---|---|\n| freundlich | **0.845** | 0.078 | -0.040 | -0.097 |\n| beratung | **0.830** | -0.052 | 0.006 | 0.006 |\n| erreichbar | **0.799** | 0.044 | -0.041 | 0.100 |\n| hilfsbereit | **0.787** | -0.089 | 0.077 | 0.009 |\n| geraete | -0.008 | **0.611** | 0.098 | **0.338** |\n| sauberkeit | 0.026 | **0.643** | 0.188 | 0.023 |\n| garderobe | -0.004 | 0.014 | **0.990** | -0.009 |\n| platzangebot | -0.021 | **0.862** | -0.026 | -0.089 |\n| parkplatz | 0.036 | -0.102 | -0.011 | 0.256 |\n\nAnteil je Faktor: 0.296, 0.173, 0.115, 0.023.\n\nDrei Warnzeichen, alle in diesen Zahlen sichtbar:\n\n| Zeichen | Beleg hier |\n|---|---|\n| **Faktoren mit zu wenig Items** | F3 wird von einem einzigen Item getragen (`garderobe`, 0.990), F4 von keinem einzigen mit einer Ladung über 0.4. Ein Faktor braucht mindestens drei tragende Items. |\n| **Winzige Varianzanteile** | F4 erklärt 2.3 Prozent. Der Zuwachs an erklärter Varianz ist nicht null, aber bedeutungslos. |\n| **Die klare Struktur zerfällt** | Der Anlage-Faktor ist auf F2, F3 und F4 verteilt: `garderobe` ist herausgebrochen, `geraete` lädt zusätzlich mit 0.338 auf F4. In der Zweifaktorenlösung lagen alle vier sauber beieinander. |\n\nEine Ladung von 0.990 bei einer Kommunalität nahe eins ist zudem die Vorstufe\neines **Heywood-Falls**: Steigt die geschätzte Kommunalität über eins, ist sie\ninhaltlich unmöglich, und die Software warnt. R meldet das als `Heywood case`;\n`psych::fa()` gibt in solchen Lagen zusätzlich Hinweise auf eine\n\"ultra-Heywood\"-Lösung aus.\n\n#### Interpretation und Ergebnissatz\n\nDie Faktorenzahl wird nicht nach der erklärten Varianz gewählt. Herangezogen\nwerden Parallelanalyse, Screeplot, die inhaltliche Deutbarkeit und die Forderung,\ndass jeder Faktor mindestens drei Items mit bedeutsamer Ladung trägt. Alle vier\nsprechen hier für zwei Faktoren.\n\n> Eine Lösung mit vier Faktoren erklärt zusammen 60.7 statt 56.6 Prozent der Varianz,\n> erzeugt dabei aber zwei Faktoren mit weniger als drei tragenden Items und eine\n> Ladung von 0.99 als Vorstufe eines Heywood-Falls. Berichtet wird die\n> Zweifaktorenlösung.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nWann ist die Faktorenanalyse der Hauptkomponentenanalyse vorzuziehen?\n\n- [x] Wenn dahinterliegende, nicht beobachtbare Grössen unterstellt werden ~\n      Richtig. Die Faktorenanalyse modelliert gemeinsame Varianz und trennt den\n      Eigenanteil ab, was bei Fragebogenitems mit Messfehler der passende Ansatz\n      ist. Wer nur verdichten will, nimmt Komponenten.\n- [ ] Wenn mehr als zehn Variablen vorliegen ~ Die Anzahl entscheidet nicht.\n- [ ] Wenn die Variablen unkorreliert sind ~ Dann funktioniert keines der beiden\n      Verfahren.\n:::\n\n::: {.quiz}\nEin Item hat eine Kommunalität von 0.003. Was heisst das?\n\n- [x] Die Faktoren erklären praktisch nichts von seiner Varianz; es passt nicht\n      zur Struktur ~ Richtig. Das Item misst etwas Eigenes. Es wird entfernt oder\n      als Einzelfrage geführt, aber keiner Skala zugeschlagen.\n- [ ] Das Item ist unzuverlässig gemessen ~ Möglich, aber die Kommunalität\n      unterscheidet Messfehler nicht von inhaltlicher Eigenständigkeit.\n- [ ] Es lädt auf allen Faktoren gleich stark ~ Das wäre eine hohe\n      Kommunalität bei schlechter Einfachstruktur.\n:::\n\n::: {.quiz}\nDer dritte Eigenwert beträgt 1.007. Das Kaiser-Kriterium spricht damit für drei\nFaktoren. Was ist davon zu halten?\n\n- [x] Wenig; der Wert stammt von einem Item, das mit keinem anderen korreliert ~\n      Richtig. Ein isoliertes Item erreicht einen Eigenwert nahe eins von selbst,\n      ohne etwas zu bündeln. Die Parallelanalyse erkennt das und bleibt bei zwei\n      Faktoren.\n- [ ] Drei Faktoren sind zu schätzen, das Kriterium ist eindeutig ~ Die\n      Eindeutigkeit der Schwelle sagt nichts über ihre Eignung.\n- [ ] Der Wert ist ein Rechenfehler ~ Er ist korrekt, nur seine Deutung als\n      Faktor ist falsch.\n:::\n\n::: {.quiz}\nDie Vier-Faktoren-Lösung erklärt mehr Varianz als die Zwei-Faktoren-Lösung. Ist\nsie deshalb besser?\n\n- [ ] Ja, mehr erklärte Varianz ist besser ~ Sie steigt mit jedem zusätzlichen\n      Faktor, ganz unabhängig davon, ob er etwas bedeutet.\n- [x] Nein, entscheidend sind Deutbarkeit und tragende Items je Faktor ~ Richtig.\n      Ein Faktor mit einem einzigen Item ist kein Faktor. Herangezogen werden\n      Parallelanalyse, Screeplot und die inhaltliche Beschreibbarkeit.\n- [ ] Das entscheidet der Bartlett-Test ~ Der prüft nur, ob überhaupt\n      Korrelationen vorliegen.\n:::\n\n::: {.quiz}\nWas ändert eine oblique Rotation gegenüber einer orthogonalen?\n\n- [x] Sie erlaubt Korrelation zwischen den Faktoren ~ Richtig. Bei inhaltlich\n      verwandten Dimensionen ist das die realistischere Annahme, und die\n      Faktorkorrelation wird Teil des Ergebnisses. Die Anpassung an die Daten\n      ändert sich dadurch nicht.\n- [ ] Sie verbessert die Anpassung des Modells ~ Rotation ändert die Anpassung\n      nicht, nur die Lesbarkeit.\n- [ ] Sie erzwingt Einfachstruktur ~ Sie strebt sie an, erzwingen kann sie\n      keine Rotation.\n:::\n\n## Verlinkte Ressourcen\n\n- [psych: Vignette zur Faktorenanalyse](https://cran.r-project.org/web/packages/psych/vignettes/intro.pdf)\n- [factor_analyzer: Dokumentation](https://factor-analyzer.readthedocs.io/en/latest/)\n- [Was Parallelanalyse leistet](https://link.springer.com/article/10.1007/BF02289447)\n",
    "supporting": [
      "faktorenanalyse_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}