{
  "hash": "0adfc82badf1b79563e37992b986236e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Power und Stichprobenumfang\"\ndescription: \"Wie viele Fälle braucht es, und was findet man mit denen, die man hat?\"\ncategories: [\"Hypothesentests\", \"Effektstärke\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"ESDS\", \"STATDA\"]\nseitentyp: methode\nstand: fertig\norder: 50\n---\n\n\n\n\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Wie viele Beobachtungen braucht es, um einen Effekt bestimmter Grösse zu finden? Und was lässt sich mit dem vorhandenen Umfang finden? |\n| Eingang | drei von vier Grössen: Effektstärke, Stichprobenumfang, Signifikanzniveau, Power |\n| Was die Methode liefert | die vierte Grösse |\n| R-Funktion | `pwr::pwr.t.test()`, `pwr.anova.test()`, `pwr.r.test()`, `pwr.chisq.test()` |\n| Python-Funktion | `statsmodels.stats.power.TTestIndPower()` mit `.power()` und `.solve_power()` |\n| Verwandte Methoden | [Effektstärken](effektstaerken.qmd), [Hypothesentests: Grundlagen](hypothesentests-grundlagen.qmd) |\n\n## Wann diese Methode, wann nicht\n\nDie Powerrechnung gehört **vor** die Datenerhebung. Sie beantwortet die Frage,\nob sich der geplante Versuch überhaupt lohnt: Wer einen mittleren Effekt sucht\nund zwanzig Fälle je Gruppe erheben kann, wird ihn in zwei von drei Fällen\nverfehlen, und das lässt sich vorher wissen.\n\nNach der Datenerhebung ist ihr Nutzen begrenzt und ihre häufigste Anwendung\nsogar irreführend, siehe Beispiel 3.\n\n| Situation | Stattdessen |\n|---|---|\n| Die Daten liegen bereits vor und waren nicht signifikant | das [Konfidenzintervall](schaetzen-konfidenzintervalle.qmd) berichten, nicht die nachträgliche Power |\n| Der Umfang steht fest und ist nicht änderbar | ausrechnen, welcher Effekt überhaupt findbar wäre, siehe Beispiel 2 |\n| Es geht um die Genauigkeit einer Schätzung statt um einen Test | Umfang über die gewünschte Intervallbreite planen |\n| Mehrere Tests sind geplant | die Korrektur für [multiples Testen](multiples-testen.qmd) in die Rechnung aufnehmen |\n\n## Grundidee und Modell\n\nVier Grössen hängen zusammen. Legt man drei fest, ergibt sich die vierte:\n\n| Grösse | Übliche Wahl | Bedeutung |\n|---|---|---|\n| Signifikanzniveau $\\alpha$ | 0.05 | Wahrscheinlichkeit, einen Effekt zu behaupten, den es nicht gibt (Fehler erster Art) |\n| Power $1-\\beta$ | 0.80 | Wahrscheinlichkeit, einen vorhandenen Effekt zu finden |\n| Effektstärke | aus Vorwissen oder Relevanzschwelle | wie gross der gesuchte Effekt ist, siehe [Effektstärken](effektstaerken.qmd) |\n| Stichprobenumfang $n$ | das Ergebnis | |\n\nDie Power ist das Gegenstück zum Fehler zweiter Art: $\\beta$ ist die\nWahrscheinlichkeit, einen vorhandenen Effekt zu übersehen, und $1-\\beta$ die,\nihn zu finden.\n\n| | Effekt existiert | Effekt existiert nicht |\n|---|---|---|\n| **Test signifikant** | richtig, Wahrscheinlichkeit $1-\\beta$ | Fehler erster Art, Wahrscheinlichkeit $\\alpha$ |\n| **Test nicht signifikant** | Fehler zweiter Art, Wahrscheinlichkeit $\\beta$ | richtig |\n\nDie Konvention 0.80 bedeutet, dass ein Fehler zweiter Art viermal so oft\nhingenommen wird wie einer erster Art. Das ist eine Setzung, keine Notwendigkeit:\nWo ein übersehener Effekt teuer ist, gehört die Power höher.\n\n::: {.note-box}\n**Die wichtigste Zahl in der Rechnung ist die Effektstärke, und sie ist die\nunsicherste.** Sie soll den **kleinsten Effekt** bezeichnen, den zu finden sich\nlohnt, nicht den erwarteten. Wer den erwarteten einsetzt und danebenliegt,\nerhebt zu wenig; wer aus einer kleinen Vorstudie schätzt, übernimmt deren\nÜberschätzung, siehe [Effektstärken](effektstaerken.qmd), Beispiel 3.\n:::\n\n## Output lesen\n\nR, `pwr.t.test()`:\n\n| Grösse | Was sie sagt | Falle |\n|---|---|---|\n| `n` | Umfang **je Gruppe** | nicht der Gesamtumfang; bei zwei Gruppen verdoppeln |\n| `d` | angenommene Effektstärke | die Eingabe, nicht ein Ergebnis |\n| `sig.level` | $\\alpha$ | Voreinstellung 0.05 |\n| `power` | Trefferwahrscheinlichkeit | Voreinstellung, wenn `n` gesucht wird, ist keine gesetzt; sie muss angegeben werden |\n| `alternative` | ein- oder zweiseitig | einseitig senkt den nötigen Umfang und verlangt eine vorab festgelegte Richtung |\n\nPython, `TTestIndPower`:\n\n| Aufruf | Ergebnis | Unterschied zu R |\n|---|---|---|\n| `.power(effect_size=, nobs1=, alpha=)` | Power | wie `pwr.t.test(n=, d=)` |\n| `.solve_power(effect_size=, power=, alpha=)` | `nobs1`, also n je Gruppe | wie `pwr.t.test(d=, power=)` |\n| `ratio=` | Verhältnis der Gruppengrössen | in R über `pwr.t2n.test()` |\n\nBeide geben gebrochene Umfänge aus. Aufgerundet wird immer, nie ab.\n\n## Interpretationsfallen\n\n- **Nachträglich berechnete Power ist zirkulär.** Sie wird aus dem beobachteten\n  Effekt berechnet und ist deshalb eine Umrechnung des p-Werts, siehe\n  Beispiel 3.\n- **Power gilt für den angenommenen Effekt.** Ist der wahre Effekt kleiner,\n  ist die tatsächliche Power kleiner.\n- **`n` ist der Umfang je Gruppe.** Der häufigste Ablesefehler.\n- **Ungleiche Gruppen kosten Power.** Bei festem Gesamtumfang ist die\n  Aufteilung 50 zu 50 die beste; 80 zu 20 verliert spürbar.\n- **Ausfälle einplanen.** Wer 64 je Gruppe braucht und mit 10 Prozent Ausfall\n  rechnet, erhebt 72.\n- **Mehrere Tests senken die Power.** Eine Bonferroni-Korrektur auf 0.01 statt\n  0.05 verlangt rund 50 Prozent mehr Fälle.\n- **Power ersetzt keine Voraussetzungsprüfung.** Sie unterstellt, dass das\n  geplante Verfahren anwendbar ist.\n\n## Ergebnis berichten\n\n> Der Versuch wurde auf einen Effekt von [Effektstärke] ausgelegt, der als\n> kleinste praktisch bedeutsame Grösse festgelegt wurde. Bei $\\alpha$ = 0.05\n> zweiseitig und einer Power von [Wert] ergibt sich ein Umfang von [n] je\n> Gruppe; erhoben wurden [tatsächlich] je Gruppe.\n\nGenannt werden: die angenommene Effektstärke **und ihre Herkunft**, $\\alpha$,\ndie angestrebte Power, das Verfahren, und ob ein- oder zweiseitig geprüft wird.\nDie Herkunft der Effektstärke ist der Punkt, an dem eine Powerrechnung steht\noder fällt.\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt der Powerrechnung |\n|---|---|\n| [Effektstärken](effektstaerken.qmd) | die Grösse eines gefundenen Effekts beschreiben |\n| [Schätzen und Konfidenzintervalle](schaetzen-konfidenzintervalle.qmd) | nach der Erhebung: was ist mit den Daten vereinbar? |\n| [Multiples Testen](multiples-testen.qmd) | mehrere Tests sind geplant |\n| Äquivalenztest | die Frage lautet, ob ein Effekt klein genug ist |\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Wie viele Fälle brauche ich?\n\n#### Frage und Datenlage\n\nEin Vergleich zweier Gruppen ist geplant. Als kleinster praktisch bedeutsamer\nUnterschied wurde ein mittlerer Effekt festgelegt, also $d = 0.5$. Angestrebt\nwird eine Power von 0.80 bei $\\alpha$ = 0.05 zweiseitig.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npwr.t.test(d = 0.5, power = 0.80, sig.level = 0.05,\n           type = \"two.sample\", alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Two-sample t test power calculation \n\n              n = 63.76561\n              d = 0.5\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n\n\n:::\n\n```{.r .cell-code}\n# Umfang fuer verschiedene Effektstaerken\nfor (d in c(0.2, 0.3, 0.5, 0.8, 1.0)) {\n  n <- pwr.t.test(d = d, power = 0.80, sig.level = 0.05)$n\n  cat(sprintf(\"d = %.1f: %6.2f je Gruppe, aufgerundet %3d, insgesamt %3d\\n\",\n              d, n, ceiling(n), 2 * ceiling(n)))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nd = 0.2: 393.41 je Gruppe, aufgerundet 394, insgesamt 788\nd = 0.3: 175.38 je Gruppe, aufgerundet 176, insgesamt 352\nd = 0.5:  63.77 je Gruppe, aufgerundet  64, insgesamt 128\nd = 0.8:  25.52 je Gruppe, aufgerundet  26, insgesamt  52\nd = 1.0:  16.71 je Gruppe, aufgerundet  17, insgesamt  34\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nn_noetig = analyse.solve_power(effect_size=0.5, power=0.80, alpha=0.05, ratio=1.0)\nprint(\"n je Gruppe für d = 0.5:\", round(n_noetig, 3),\n      \"-> aufgerundet\", int(np.ceil(n_noetig)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn je Gruppe für d = 0.5: 63.766 -> aufgerundet 64\n```\n\n\n:::\n\n```{.python .cell-code}\nfor d in (0.2, 0.3, 0.5, 0.8, 1.0):\n    n = analyse.solve_power(effect_size=d, power=0.80, alpha=0.05, ratio=1.0)\n    print(f\"d = {d}: {n:6.2f} je Gruppe, aufgerundet {int(np.ceil(n)):3d}, \"\n          f\"insgesamt {2*int(np.ceil(n)):3d}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nd = 0.2: 393.41 je Gruppe, aufgerundet 394, insgesamt 788\nd = 0.3: 175.38 je Gruppe, aufgerundet 176, insgesamt 352\nd = 0.5:  63.77 je Gruppe, aufgerundet  64, insgesamt 128\nd = 0.8:  25.52 je Gruppe, aufgerundet  26, insgesamt  52\nd = 1.0:  16.71 je Gruppe, aufgerundet  17, insgesamt  34\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Effektstärke | n je Gruppe (genau) | aufgerundet | insgesamt |\n|---|---|---|---|\n| 0.2 (klein) | 393.41 | 394 | 788 |\n| 0.3 | 175.38 | 176 | 352 |\n| 0.5 (mittel) | 63.77 | 64 | 128 |\n| 0.8 (gross) | 25.52 | 26 | 52 |\n| 1.0 | 16.71 | 17 | 34 |\n\nDie entscheidende Beobachtung: **Der Umfang wächst mit dem Quadrat des\nKehrwerts der Effektstärke.** Ein halb so grosser Effekt braucht viermal so\nviele Fälle. Von $d = 0.8$ auf $d = 0.2$, also ein Viertel der Effektstärke,\nsteigt der Umfang von 26 auf 394 je Gruppe, also auf das Fünfzehnfache.\n\nDas ist der Grund, warum kleine Effekte in der Praxis so schwer nachzuweisen\nsind, und warum Studien, die kleine Effekte mit kleinen Stichproben finden,\nskeptisch zu betrachten sind.\n\n#### Interpretation und Ergebnissatz\n\n> Der Versuch wurde auf einen Effekt von $d$ = 0.5 ausgelegt, der als kleinste\n> praktisch bedeutsame Grösse festgelegt wurde. Bei $\\alpha$ = 0.05 zweiseitig\n> und einer angestrebten Power von 0.80 ergibt sich ein Umfang von 64 Fällen je\n> Gruppe, also 128 insgesamt. Unter Einplanung von 10 Prozent Ausfällen werden\n> 72 je Gruppe erhoben.\n\n### Beispiel 2: Was finde ich mit dem Umfang, den ich habe?\n\n#### Frage und Datenlage\n\nDer Umfang steht fest: zwanzig Fälle je Gruppe, mehr ist nicht zu bekommen. Die\nFrage dreht sich um: Welche Effekte lassen sich damit überhaupt finden?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\numfaenge <- seq(5, 200, by = 5)\n\npar(mar = c(4, 4, 3, 1))\nplot(NULL, xlim = range(umfaenge), ylim = c(0, 1),\n     xlab = \"n je Gruppe\", ylab = \"Power\", main = \"Power-Kurven\")\nabline(h = 0.8, lty = 2, col = \"firebrick\")\nfarben <- c(\"steelblue\", \"darkorange\", \"seagreen\")\nfor (i in seq_along(c(0.2, 0.5, 0.8))) {\n  d <- c(0.2, 0.5, 0.8)[i]\n  werte <- sapply(umfaenge, function(n) pwr.t.test(n = n, d = d,\n                                                   sig.level = 0.05)$power)\n  lines(umfaenge, werte, col = farben[i], lwd = 2)\n}\nlegend(\"bottomright\", paste(\"d =\", c(0.2, 0.5, 0.8)), col = farben,\n       lwd = 2, bty = \"n\")\n\nfor (d in c(0.2, 0.5, 0.8, 1.2)) {\n  cat(sprintf(\"d = %.1f: Power bei n = 20 je Gruppe = %.4f\\n\",\n              d, pwr.t.test(n = 20, d = d, sig.level = 0.05)$power))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nd = 0.2: Power bei n = 20 je Gruppe = 0.0946\nd = 0.5: Power bei n = 20 je Gruppe = 0.3379\nd = 0.8: Power bei n = 20 je Gruppe = 0.6934\nd = 1.2: Power bei n = 20 je Gruppe = 0.9588\n```\n\n\n:::\n\n```{.r .cell-code}\n# Welcher Effekt ist mit n = 20 bei Power 0.80 gerade noch findbar?\npwr.t.test(n = 20, power = 0.80, sig.level = 0.05)$d\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9091587\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 2: Power in Abhängigkeit vom Umfang, für drei Effektstärken.](power-stichprobenumfang_files/figure-html/fig-b2-pow-r-1.png){#fig-b2-pow-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\numfaenge = np.arange(5, 205, 5)\n\nfig, achse = plt.subplots(figsize=(7, 3.6))\nachse.axhline(0.8, linestyle=\"--\", color=\"firebrick\")\nfor d, farbe in zip((0.2, 0.5, 0.8), (\"steelblue\", \"darkorange\", \"seagreen\")):\n    werte = [analyse.power(effect_size=d, nobs1=n, alpha=0.05) for n in umfaenge]\n    achse.plot(umfaenge, werte, color=farbe, linewidth=2, label=f\"d = {d}\")\nachse.set_xlabel(\"n je Gruppe\")\nachse.set_ylabel(\"Power\")\nachse.set_ylim(0, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(0.0, 1.0)\n```\n\n\n:::\n\n```{.python .cell-code}\nachse.set_title(\"Power-Kurven\")\nachse.legend(frameon=False, loc=\"lower right\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselben Kurven in Python.](power-stichprobenumfang_files/figure-html/fig-b2-pow-py-1.png){#fig-b2-pow-py width=100%}\n:::\n\n```{.python .cell-code}\nfor d in (0.2, 0.5, 0.8, 1.2):\n    print(f\"d = {d}: Power bei n = 20 je Gruppe = \"\n          f\"{analyse.power(effect_size=d, nobs1=20, alpha=0.05):.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nd = 0.2: Power bei n = 20 je Gruppe = 0.0946\nd = 0.5: Power bei n = 20 je Gruppe = 0.3379\nd = 0.8: Power bei n = 20 je Gruppe = 0.6934\nd = 1.2: Power bei n = 20 je Gruppe = 0.9588\n```\n\n\n:::\n\n```{.python .cell-code}\nfindbar = analyse.solve_power(nobs1=20, power=0.80, alpha=0.05, ratio=1.0)\nprint(\"Mit n = 20 bei Power 0.80 findbar ab d =\", round(findbar, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMit n = 20 bei Power 0.80 findbar ab d = 0.9091\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Effektstärke | Power bei n = 20 je Gruppe | Wie das zu lesen ist |\n|---|---|---|\n| 0.2 | 0.095 | In neun von zehn Versuchen bleibt ein kleiner Effekt unentdeckt. Die Power liegt kaum über dem Signifikanzniveau von 0.05, also kaum über der Rate falscher Alarme. |\n| 0.5 | 0.338 | Ein mittlerer Effekt wird in zwei von drei Versuchen übersehen. |\n| 0.8 | 0.693 | Auch ein grosser Effekt bleibt in knapp einem Drittel der Fälle unentdeckt. |\n| 1.2 | 0.959 | Erst hier wird der Versuch verlässlich. |\n\nDie Kurven zeigen dasselbe grafisch: Für $d = 0.8$ ist die Schwelle von 0.80\nbei rund 26 Fällen je Gruppe erreicht, für $d = 0.5$ erst bei 64, und für\n$d = 0.2$ liegt die Kurve über den ganzen dargestellten Bereich unter 0.55.\n\n::: {.note-box}\n**Die nützlichste Rechnung bei festem Umfang** ist die Umkehrung: Welcher Effekt\nwäre mit dieser Fallzahl gerade noch findbar? Bei n = 20 je Gruppe und Power\n0.80 liegt diese Grenze bei $d$ = 0.91.\n\nDas ist eine Zahl, mit der sich vorab argumentieren lässt: Wenn der erwartete\nEffekt deutlich darunter liegt, ist der Versuch in dieser Form nicht\naussagekräftig, und die ehrliche Konsequenz ist entweder mehr Daten, ein\npräziseres Design (etwa gepaart statt ungepaart) oder der Verzicht.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Bei einem festen Umfang von 20 Fällen je Gruppe beträgt die Power für einen\n> mittleren Effekt ($d$ = 0.5) nur 0.34. Verlässlich findbar (Power 0.80) sind\n> erst Effekte ab $d$ = 0.91. Der Versuch ist damit nicht geeignet, einen\n> mittleren Effekt nachzuweisen; ein nicht signifikantes Ergebnis wäre nicht als\n> Beleg für dessen Fehlen zu lesen.\n\n### Beispiel 3: Warum nachträgliche Power nichts sagt\n\n#### Frage und Datenlage\n\nEin Versuch ist gelaufen und nicht signifikant geworden. Eine verbreitete\nReaktion ist, die Power **nachträglich** aus dem beobachteten Effekt zu\nberechnen und zu berichten. Was kommt dabei heraus?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fuer eine Reihe beobachteter Effekte bei festem n: p-Wert und nachtraegliche\n# Power nebeneinander\nn <- 20\nbeobachtet <- c(0.10, 0.30, 0.45, 0.64, 0.90)\n\ntabelle <- data.frame(\n  d_beobachtet = beobachtet,\n  t = beobachtet * sqrt(n / 2)\n)\ntabelle$p <- 2 * (1 - pt(tabelle$t, 2 * n - 2))\ntabelle$power_nachtraeglich <- sapply(beobachtet, function(d)\n  pwr.t.test(n = n, d = d, sig.level = 0.05)$power)\nround(tabelle, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  d_beobachtet      t      p power_nachtraeglich\n1         0.10 0.3162 0.7536              0.0610\n2         0.30 0.9487 0.3488              0.1523\n3         0.45 1.4230 0.1629              0.2838\n4         0.64 2.0239 0.0501              0.5051\n5         0.90 2.8460 0.0071              0.7920\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nn = 20\nbeobachtet = np.array([0.10, 0.30, 0.45, 0.64, 0.90])\nt = beobachtet * np.sqrt(n / 2)\np = 2 * (1 - stats.t.cdf(t, 2 * n - 2))\npower_nach = [analyse.power(effect_size=d, nobs1=n, alpha=0.05)\n              for d in beobachtet]\n\nprint(pd.DataFrame({\"d_beobachtet\": beobachtet, \"t\": t.round(4),\n                    \"p\": p.round(4),\n                    \"power_nachtraeglich\": np.round(power_nach, 4)}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   d_beobachtet       t       p  power_nachtraeglich\n0          0.10  0.3162  0.7536               0.0610\n1          0.30  0.9487  0.3488               0.1523\n2          0.45  1.4230  0.1629               0.2838\n3          0.64  2.0239  0.0501               0.5051\n4          0.90  2.8460  0.0071               0.7920\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| beobachtetes $d$ | t | p | nachträgliche Power |\n|---|---|---|---|\n| 0.10 | 0.316 | 0.754 | 0.061 |\n| 0.30 | 0.949 | 0.349 | 0.152 |\n| 0.45 | 1.423 | 0.163 | 0.284 |\n| 0.64 | 2.024 | 0.050 | 0.505 |\n| 0.90 | 2.846 | 0.007 | 0.792 |\n\nDie beiden letzten Spalten sind **dieselbe Information in zwei Schreibweisen**.\nEin kleiner p-Wert geht immer mit hoher nachträglicher Power einher, ein grosser\nimmer mit niedriger, und der Zusammenhang ist bei festem n eindeutig. Die Zeile\nmit p = 0.05 hat eine Power von genau 0.50, das gilt allgemein und ist kein\nZufall dieses Beispiels: Liegt der beobachtete Effekt genau auf der\nSignifikanzschwelle, ergibt die nachträgliche Rechnung immer eine Power um 0.5.\n\n::: {.note-box}\n**Warum die Aussage \"die Power war zu niedrig, deshalb nicht signifikant\"\nzirkulär ist.** Sie berechnet die Power aus genau dem Effekt, der beobachtet\nwurde, und stellt dann fest, dass ein kleiner beobachteter Effekt eine kleine\nPower ergibt. Das ist keine neue Erkenntnis, sondern eine Umformulierung von\n\"der beobachtete Effekt war klein\".\n\n**Was stattdessen zu berichten ist:** das Konfidenzintervall. Es beantwortet die\nFrage, die tatsächlich interessiert, nämlich welche Effektgrössen mit den Daten\nnoch vereinbar sind. Ein Intervall von -0.2 bis 1.4 sagt \"wir wissen es nicht\",\neines von -0.1 bis 0.15 sagt \"ein bedeutsamer Effekt ist ausgeschlossen\". Der\np-Wert von 0.35 sagt in beiden Fällen dasselbe.\n:::\n\n#### Interpretation und Ergebnissatz\n\nEine Powerrechnung ist nach der Erhebung nur in einer Form sinnvoll: mit einer\n**vorab** oder unabhängig festgelegten Effektstärke, um zu zeigen, dass der\nVersuch für diese Grösse ausgelegt war. Diese Rechnung hängt nicht vom Ergebnis\nab und ist deshalb nicht zirkulär.\n\n> Der Versuch war auf $d$ = 0.5 ausgelegt (Power 0.80 bei 64 je Gruppe);\n> erhoben wurden 20 je Gruppe, was die Power auf 0.34 senkt. Das Ergebnis war\n> nicht signifikant (p = 0.35); das 95-Prozent-Konfidenzintervall der\n> standardisierten Differenz reicht von -0.32 bis 0.92 und lässt damit Effekte\n> bis in den grossen Bereich zu.\n\n### Beispiel 4: Was den nötigen Umfang sonst noch treibt\n\n#### Frage und Datenlage\n\nNeben der Effektstärke gibt es drei Stellschrauben, die den Umfang deutlich\nverändern und in der Planung oft übersehen werden: das Signifikanzniveau, die\nAufteilung auf die Gruppen und die Wahl zwischen gepaartem und ungepaartem\nDesign.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Wirkung des Signifikanzniveaus (d = 0.5, Power 0.80):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWirkung des Signifikanzniveaus (d = 0.5, Power 0.80):\n```\n\n\n:::\n\n```{.r .cell-code}\nfor (a in c(0.10, 0.05, 0.01, 0.001)) {\n  n <- pwr.t.test(d = 0.5, power = 0.80, sig.level = a)$n\n  cat(sprintf(\"  alpha = %.3f: %6.2f je Gruppe\\n\", a, n))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  alpha = 0.100:  50.15 je Gruppe\n  alpha = 0.050:  63.77 je Gruppe\n  alpha = 0.010:  95.10 je Gruppe\n  alpha = 0.001: 139.31 je Gruppe\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nWirkung der Aufteilung bei rund 128 Faellen insgesamt (d = 0.5):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nWirkung der Aufteilung bei rund 128 Faellen insgesamt (d = 0.5):\n```\n\n\n:::\n\n```{.r .cell-code}\nfor (paar in list(c(64, 64), c(80, 48), c(96, 32), c(110, 18))) {\n  p <- pwr.t2n.test(n1 = paar[1], n2 = paar[2], d = 0.5, sig.level = 0.05)$power\n  cat(sprintf(\"  %3d zu %3d: Power = %.4f\\n\", paar[1], paar[2], p))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   64 zu  64: Power = 0.8015\n   80 zu  48: Power = 0.7757\n   96 zu  32: Power = 0.6811\n  110 zu  18: Power = 0.4967\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nEinseitig statt zweiseitig (d = 0.5, Power 0.80):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nEinseitig statt zweiseitig (d = 0.5, Power 0.80):\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"  zweiseitig: %6.2f  einseitig: %6.2f\\n\",\n            pwr.t.test(d = 0.5, power = 0.80, alternative = \"two.sided\")$n,\n            pwr.t.test(d = 0.5, power = 0.80, alternative = \"greater\")$n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  zweiseitig:  63.77  einseitig:  50.15\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(\"Wirkung des Signifikanzniveaus (d = 0.5, Power 0.80):\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWirkung des Signifikanzniveaus (d = 0.5, Power 0.80):\n```\n\n\n:::\n\n```{.python .cell-code}\nfor a in (0.10, 0.05, 0.01, 0.001):\n    n = analyse.solve_power(effect_size=0.5, power=0.80, alpha=a, ratio=1.0)\n    print(f\"  alpha = {a:.3f}: {n:6.2f} je Gruppe\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  alpha = 0.100:  50.15 je Gruppe\n  alpha = 0.050:  63.77 je Gruppe\n  alpha = 0.010:  95.10 je Gruppe\n  alpha = 0.001: 139.31 je Gruppe\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"\\nWirkung der Aufteilung bei rund 128 Fällen insgesamt (d = 0.5):\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nWirkung der Aufteilung bei rund 128 Fällen insgesamt (d = 0.5):\n```\n\n\n:::\n\n```{.python .cell-code}\nfor n1, n2 in [(64, 64), (80, 48), (96, 32), (110, 18)]:\n    p = analyse.power(effect_size=0.5, nobs1=n1, alpha=0.05, ratio=n2 / n1)\n    print(f\"  {n1:3d} zu {n2:3d}: Power = {p:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   64 zu  64: Power = 0.8015\n   80 zu  48: Power = 0.7757\n   96 zu  32: Power = 0.6811\n  110 zu  18: Power = 0.4967\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n**Signifikanzniveau.** Je strenger, desto mehr Fälle:\n\n| $\\alpha$ | n je Gruppe | Bemerkung |\n|---|---|---|\n| 0.10 | 50.15 | |\n| 0.05 | 63.77 | die Voreinstellung |\n| 0.01 | 95.10 | rund 50 Prozent mehr als bei 0.05 |\n| 0.001 | 139.31 | mehr als das Doppelte |\n\nDas ist der versteckte Preis einer Korrektur für\n[multiples Testen](multiples-testen.qmd): Wer fünf Tests plant und nach\nBonferroni auf $\\alpha$ = 0.01 geht, braucht rund die Hälfte mehr Fälle je Test,\num dieselbe Power zu halten.\n\n**Aufteilung auf die Gruppen.** Bei festem Gesamtumfang:\n\n| Aufteilung | Power | Bemerkung |\n|---|---|---|\n| 64 zu 64 | 0.801 | das Optimum |\n| 80 zu 48 | 0.776 | schon spürbar weniger |\n| 96 zu 32 | 0.681 | |\n| 110 zu 18 | 0.497 | statt 0.80 nur noch 0.50, bei gleichem Gesamtumfang |\n\nDie kleinere Gruppe bestimmt die Power fast allein. Eine Kontrollgruppe von 18\nFällen lässt sich nicht dadurch ausgleichen, dass die Behandlungsgruppe auf 110\naufgestockt wird.\n\n**Ein- statt zweiseitig** senkt den Umfang von 63.77 auf rund 50.15 je Gruppe,\nalso um gut ein Fünftel. Der Preis ist, dass die Richtung vorab festgelegt sein\nmuss und ein Effekt in die andere Richtung nicht nachweisbar wäre, selbst wenn\ner deutlich ausfiele.\n\n#### Interpretation und Ergebnissatz\n\nDie grösste Reserve steckt aber nicht in diesen Stellschrauben, sondern im\nDesign. Ein [gepaarter Versuch](../tests/t-test-gepaart.qmd) misst dieselbe\nPerson zweimal und entfernt damit die Unterschiede zwischen den Personen aus der\nFehlerstreuung. Bei einer Korrelation von 0.8 zwischen den beiden Messungen\nsinkt der nötige Umfang auf einen Bruchteil.\n\nDeshalb lohnt sich die Frage nach dem Design vor der Frage nach dem Umfang:\nFünfzehn Personen, zweimal gemessen, schlagen oft hundert Personen, einmal\ngemessen.\n\n> Geplant war ein Umfang von 64 je Gruppe für $d$ = 0.5 bei $\\alpha$ = 0.05 und\n> Power 0.80. Wegen der geplanten fünf Vergleiche wurde $\\alpha$ nach Bonferroni\n> auf 0.01 gesenkt, was den Umfang auf 95 je Gruppe erhöht. Die Gruppen werden\n> gleich gross besetzt, da eine ungleiche Aufteilung die Power spürbar senkt.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEin Versuch mit 20 Fällen je Gruppe ist nicht signifikant geworden. Die\nnachträglich berechnete Power beträgt 0.28. Was folgt daraus?\n\n- [x] Nichts, was der p-Wert nicht schon gesagt hätte ~ Richtig. Die\n      nachträgliche Power wird aus dem beobachteten Effekt berechnet und ist bei\n      festem n eine eindeutige Umrechnung des p-Werts. Aussagekräftig ist\n      stattdessen das Konfidenzintervall.\n- [ ] Der Versuch war zu klein, deshalb war er nicht signifikant ~ Der Satz\n      klingt plausibel und ist zirkulär: Er begründet den grossen p-Wert mit\n      einer Zahl, die aus demselben p-Wert stammt.\n- [ ] Es gibt keinen Effekt ~ Ein nicht signifikantes Ergebnis belegt nie das\n      Fehlen eines Effekts.\n:::\n\n::: {.quiz}\nDer Umfang für $d$ = 0.5 beträgt 64 je Gruppe. Wie viele braucht es für\n$d$ = 0.25?\n\n- [x] Rund viermal so viele, also etwa 250 je Gruppe ~ Richtig. Der Umfang\n      wächst mit dem Quadrat des Kehrwerts der Effektstärke. Halbierte\n      Effektstärke bedeutet vervierfachten Umfang.\n- [ ] Doppelt so viele, also 128 ~ Der Zusammenhang ist quadratisch, nicht\n      linear.\n- [ ] Dasselbe, der Umfang hängt nur an Power und alpha ~ Die Effektstärke ist\n      die Grösse, die den Umfang am stärksten bestimmt.\n:::\n\n::: {.quiz}\nBei 128 Fällen insgesamt: Welche Aufteilung liefert die höchste Power?\n\n- [x] 64 zu 64 ~ Richtig. Bei festem Gesamtumfang ist die gleiche Aufteilung\n      optimal. Die kleinere Gruppe bestimmt die Power fast allein; 110 zu 18\n      erreicht nur 0.50 statt 0.80.\n- [ ] 96 zu 32, weil die grössere Gruppe genauer geschätzt wird ~ Die Genauigkeit\n      der grösseren Gruppe nützt wenig, solange die kleinere die Unsicherheit\n      bestimmt.\n- [ ] Die Aufteilung spielt keine Rolle, nur die Summe zählt ~ Sie spielt eine\n      erhebliche Rolle, wie die Tabelle in Beispiel 4 zeigt.\n:::\n\n::: {.quiz}\nWelche Effektstärke gehört in eine Powerrechnung vor der Erhebung?\n\n- [x] Der kleinste Effekt, dessen Nachweis sich lohnt ~ Richtig. Die\n      Powerrechnung soll sicherstellen, dass ein Effekt dieser Grösse gefunden\n      wird. Wer den erwarteten Effekt einsetzt und ihn überschätzt, plant zu\n      klein.\n- [ ] Der in einer Vorstudie beobachtete Effekt ~ Effektstärken aus kleinen\n      Vorstudien sind systematisch überschätzt und führen zu zu kleinen\n      Umfängen.\n- [ ] Der grösste plausible Effekt ~ Damit wäre der Versuch für alle kleineren\n      Effekte unterdimensioniert.\n:::\n\n## Verlinkte Ressourcen\n\n- [pwr: Basic Power Analysis](https://cran.r-project.org/package=pwr)\n- [statsmodels: Power and Sample Size](https://www.statsmodels.org/stable/stats.html#power-and-sample-size-calculations)\n- [Effektstärken](effektstaerken.qmd)\n",
    "supporting": [
      "power-stichprobenumfang_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}