{
  "hash": "8a818f4052f51393bec83296fcd635eb",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"ARIMA und SARIMA\"\ndescription: \"Modellordnung wählen, schätzen, Residuen prüfen und prognostizieren.\"\ncategories: [\"Zeitreihen\", \"Prognose\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: methode\nstand: fertig\norder: 30\n---\n\n\n\n\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Wie lässt sich die Abhängigkeitsstruktur einer Zeitreihe modellieren und daraus prognostizieren? |\n| Zielvariable | eine stationäre oder durch Differenzieren stationär gemachte Zeitreihe |\n| Prädiktoren | die eigene Vergangenheit, optional externe Grössen |\n| Was die Methode liefert | Koeffizienten mit Standardfehlern, Informationskriterien, Prognose mit Intervall, Residuendiagnostik |\n| R-Funktion | `Arima(reihe, order = c(p, d, q), seasonal = c(P, D, Q))`, automatisch `auto.arima()` |\n| Python-Funktion | `SARIMAX(reihe, order=(p, d, q), seasonal_order=(P, D, Q, s)).fit()` |\n| Verwandte Methoden | [Glättung](glaettung-einfache-verfahren.qmd), [Stationarität](stationaritaet-acf-pacf.qmd) |\n\n## Wann diese Methode, wann nicht\n\nTypische Fragestellungen: Prognose einer Absatzreihe mit Trend und Saison,\nModellierung der Abhängigkeitsstruktur, Vergleich verschiedener Modellordnungen\nüber Informationskriterien.\n\nARIMA-Modelle beschreiben eine Reihe durch drei Bausteine: die eigene\nVergangenheit (AR), die Vergangenheit der Fehler (MA) und die Anzahl nötiger\nDifferenzen (I). SARIMA ergänzt dieselben Bausteine für die saisonale Ebene. Der\nVorteil gegenüber der [Glättung](glaettung-einfache-verfahren.qmd) ist die\nexplizite Modellierung der Abhängigkeit und die saubere Herleitung der\nPrognoseintervalle; der Preis ist die Wahl der Ordnung.\n\n| Situation | Stattdessen |\n|---|---|\n| Schnelle, robuste Prognose ohne Modellwahl | [Glättung](glaettung-einfache-verfahren.qmd) |\n| Externe Einflussgrössen sind entscheidend | Regression mit Zeitreihenfehlern, oder SARIMAX mit exogenen Variablen |\n| Mehrere Reihen beeinflussen sich gegenseitig | Vektorautoregression |\n| Die Streuung selbst schwankt über die Zeit, etwa bei Kursen | GARCH-Modelle |\n| Reihe zu kurz, weniger als etwa 50 Beobachtungen | einfache Verfahren, keine Saisonschätzung |\n| Deutliche Strukturbrüche | Reihe teilen oder Modell mit Bruch |\n\n## Grundidee und Modell\n\nEin ARIMA(p, d, q)-Modell auf der differenzierten Reihe $\\Delta^d y_t$:\n\n$$\\Delta^d y_t = c + \\phi_1 \\Delta^d y_{t-1} + \\dots + \\phi_p \\Delta^d y_{t-p} + \\theta_1 \\varepsilon_{t-1} + \\dots + \\theta_q \\varepsilon_{t-q} + \\varepsilon_t$$\n\n| Bestandteil | Bedeutung |\n|---|---|\n| $p$ | Ordnung des autoregressiven Teils: wie viele frühere Werte |\n| $d$ | Anzahl Differenzen, um Stationarität zu erreichen |\n| $q$ | Ordnung des Fehlerteils: wie viele frühere Fehler |\n| $\\phi_i$ | Gewichte der früheren Werte |\n| $\\theta_j$ | Gewichte der früheren Fehler |\n| $\\varepsilon_t$ | Rauschen, unabhängig und mit konstanter Streuung |\n\nSARIMA ergänzt $(P, D, Q)_s$ für die saisonale Ebene, wobei $s$ die Periode ist,\nalso 12 bei Monatsdaten. Ein SARIMA(1,1,1)(0,1,1)$_{12}$ differenziert also\neinmal gewöhnlich und einmal saisonal.\n\nDie Ordnung liest man aus den Korrelogrammen der stationär gemachten Reihe, siehe\n[Stationarität, ACF und PACF](stationaritaet-acf-pacf.qmd):\n\n| Muster | Deutung |\n|---|---|\n| PACF bricht nach $p$ Abständen ab, ACF fällt langsam | AR($p$) |\n| ACF bricht nach $q$ Abständen ab, PACF fällt langsam | MA($q$) |\n| beide fallen langsam | gemischtes Modell, Ordnung über Informationskriterien wählen |\n| Spitzen bei Vielfachen der Periode | saisonale Anteile nötig |\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung | Vorgehen |\n|---|---|---|---|---|\n| Stationarität nach Differenzieren | Niveau und Streuung konstant | ACF, ADF- und KPSS-Test | Koeffizienten nicht interpretierbar, Prognose driftet | differenzieren, logarithmieren |\n| Konstante Streuung | Die Schwankungsbreite wächst nicht | Grafik | Prognoseintervalle falsch | logarithmieren, Box-Cox |\n| Residuen ohne Autokorrelation | Das Modell hat alle Struktur erfasst | ACF der Residuen, Ljung-Box | Intervalle zu schmal, Prognose systematisch daneben | Ordnung erhöhen, saisonale Anteile prüfen |\n| Genügend Beobachtungen | Faustregel: mindestens 50, für Saison vier Perioden | Länge prüfen | Ordnung nicht schätzbar, Überanpassung | einfachere Modelle |\n| Kein Strukturbruch | Ein Modell für die ganze Reihe | Grafik | Modell mittelt über zwei Regime | Reihe teilen |\n| Sparsame Ordnung | Nicht mehr Parameter als nötig | Informationskriterien, Testfehler | Überanpassung, schlechte Prognose | Ordnung reduzieren |\n\n## Output lesen\n\nR, `summary(Arima(...))`:\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| `ARIMA(1,1,1)(0,1,1)[12]` | gewählte Ordnung, gewöhnlich und saisonal | die Zahl in Klammern ist die Periode |\n| `ar1`, `ma1` | Koeffizienten der gewöhnlichen Anteile | Betrag unter eins nötig für Stationarität |\n| `sma1` | saisonaler MA-Koeffizient | oft nahe minus eins bei saisonal differenzierten Reihen |\n| `s.e.` | Standardfehler je Koeffizient | Koeffizient geteilt durch Standardfehler über 2 heisst bedeutsam |\n| `sigma^2` | Streuung der Residuen | Grundlage der Prognoseintervalle |\n| `log likelihood` | Anpassungsmass | nur zwischen Modellen auf identischen Daten vergleichbar |\n| `AIC`, `AICc`, `BIC` | Informationskriterien | kleiner ist besser; `AICc` bei kurzen Reihen bevorzugen |\n| `Training set error measures` | RMSE, MAE, MAPE auf den Trainingsdaten | nicht zur Beurteilung der Prognose geeignet |\n| `ACF1` | Autokorrelation der Residuen im ersten Abstand | nahe null erwartet |\n\nPython, `SARIMAX.summary()`:\n\n| Grösse | Was sie sagt | Unterschied zu R |\n|---|---|---|\n| `coef`, `std err`, `z`, `P>|z|` | Koeffizienten mit Test | R nennt keine p-Werte, nur Standardfehler |\n| `sigma2` | Residuenstreuung | wie `sigma^2` |\n| `Log Likelihood`, `AIC`, `BIC` | Anpassung | `AICc` fehlt |\n| `Ljung-Box (L1) (Q)` | Test auf Autokorrelation im ersten Abstand | in R über `checkresiduals()` |\n| `Jarque-Bera (JB)` | Test auf Normalität der Residuen | in R im Diagnoseplot |\n| `Heteroskedasticity (H)` | Test auf konstante Streuung | in R nicht enthalten |\n| Warnungen zu Konvergenz | Optimierung nicht konvergiert | ernst nehmen, Ordnung vereinfachen |\n\nZwei Unterschiede in der Handhabung: In Python steht die Periode als vierter Wert\nin `seasonal_order`, in R getrennt über `frequency` der Reihe. Und `SARIMAX`\nschätzt standardmässig kein konstantes Glied, wenn differenziert wird, während R\nmit `include.drift` steuerbar ist; bei Reihen mit Trend nach einer Differenz ist\ndas ein häufiger Grund für abweichende Prognosen.\n\n## Beispiele\n\nAlle Beispiele arbeiten mit derselben konstruierten Absatzreihe: 96 Monate ab\nJanuar 2018 mit linearem Trend, Jahressaison und einem **autokorrelierten**\nFehler (AR(1) mit Koeffizient 0.6). Die letzten zwölf Monate bleiben als\nTestteil ungesehen; geschätzt wird auf den ersten 84.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Wie viele Differenzen, welche Ordnung?\n\n#### Frage und Datenlage\n\nVor jedem ARIMA-Modell stehen zwei Entscheidungen: wie oft differenziert wird\n($d$ und $D$) und welche Ordnungen ($p$, $q$, $P$, $Q$) daraus folgen. Beide\nwerden aus den Korrelogrammen der stationär gemachten Reihe gelesen.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(c(d = forecast::ndiffs(training),\n        D = forecast::nsdiffs(training)), 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nd D \n1 1 \n```\n\n\n:::\n\n```{.r .cell-code}\nstationaer <- diff(diff(training, lag = 12))\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nacf(stationaer, lag.max = 24, main = \"ACF nach Differenzieren\")\npacf(stationaer, lag.max = 24, main = \"PACF nach Differenzieren\")\npar(mfrow = c(1, 1))\n\nround(c(n = length(stationaer),\n        grenze = 1.96 / sqrt(length(stationaer)),\n        sd_roh = sd(training),\n        sd_stationaer = sd(stationaer)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            n        grenze        sd_roh sd_stationaer \n       71.000         0.233       105.072        25.937 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 1: ACF und PACF nach gewöhnlichem und saisonalem Differenzieren.](arima-sarima_files/figure-html/fig-b1-ar-r-1.png){#fig-b1-ar-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom statsmodels.graphics.tsaplots import plot_acf, plot_pacf\nfrom statsmodels.tsa.stattools import adfuller, acf, pacf\n\nstationaer = training.diff(12).diff().dropna()\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.6))\nplot_acf(stationaer, ax=achsen[0], lags=24, title=\"ACF nach Differenzieren\")\nplot_pacf(stationaer, ax=achsen[1], lags=24, title=\"PACF nach Differenzieren\",\n          method=\"ywm\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselben Korrelogramme in Python.](arima-sarima_files/figure-html/fig-b1-ar-py-1.png){#fig-b1-ar-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(\"ADF p nach Differenzieren:\", round(adfuller(stationaer)[1], 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nADF p nach Differenzieren: 0.0092\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"n =\", len(stationaer),\n      \"| Konfidenzgrenze:\", round(1.96 / np.sqrt(len(stationaer)), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 71 | Konfidenzgrenze: 0.233\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"ACF \", np.round(acf(stationaer, nlags=14)[1:15], 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nACF  [-0.022 -0.12  -0.261 -0.193 -0.046 -0.101  0.177  0.134  0.123  0.091\n  0.024 -0.401 -0.149  0.101]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"PACF\", np.round(pacf(stationaer, nlags=14, method=\"ywm\")[1:15], 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPACF [-0.022 -0.12  -0.271 -0.25  -0.176 -0.322 -0.084 -0.075 -0.015  0.119\n  0.217 -0.281 -0.077  0.104]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nNach einer gewöhnlichen und einer saisonalen Differenz bleiben 71 Werte übrig;\ndie Konfidenzgrenze liegt bei ±0.233. Der ADF-Test bestätigt Stationarität\n(p = 0.009).\n\n| Abstand | 1 | 2 | 3 | 4 | 5 | 6 | 11 | **12** | 13 |\n|---|---|---|---|---|---|---|---|---|---|\n| ACF | -0.022 | -0.120 | **-0.261** | -0.193 | -0.046 | -0.101 | 0.024 | **-0.401** | -0.149 |\n| PACF | -0.022 | -0.120 | **-0.271** | **-0.250** | -0.176 | **-0.322** | 0.217 | **-0.281** | -0.077 |\n\n| Ausgabe | Wie sie zu lesen ist |\n|---|---|\n| **ACF bei 12: -0.401** | Der grösste Einzelwert und weit ausserhalb der Grenze. Ein **negativer** Wert genau bei der Periode ist die Signatur des saisonalen Differenzierens: Es erzeugt eine saisonale MA-Struktur. Daraus folgt $Q = 1$. |\n| Keine weitere Spitze bei 24 | Ein saisonaler MA-Term reicht; $Q = 2$ wäre nicht begründet. |\n| **Auf der kurzen Skala ist das Bild unklar** | ACF und PACF haben beide einen Ausschlag bei 3 und danach kleinere Werte, ohne dass eine der beiden sauber abbricht. Genau der Fall aus der Theorie: **beide fallen allmählich ab, also gemischtes Modell**, die Ordnung ist nicht ablesbar. |\n| Streuung vor und nach dem Differenzieren | sinkt deutlich | Ein Hinweis, dass nicht überdifferenziert wurde. |\n| `ndiffs` und `nsdiffs` in R | schlagen $d$ und $D$ vor | Python hat dafür keine eingebaute Entsprechung; dort entscheidet man über Tests und Grafik. |\n\n::: {.note-box}\n**Was die Korrelogramme hier leisten und was nicht.** Sie liefern eindeutig\n$D = 1$ und $Q = 1$, die saisonale Ebene ist klar. Für die gewöhnliche Ebene\ngeben sie nur die Auskunft \"es ist etwas da, aber weder reines AR noch reines\nMA\". Die Wahl zwischen (1,1,1), (0,1,1), (1,1,0) und (2,1,2) fällt deshalb in\nBeispiel 2 über Informationskriterien und den Testfehler, nicht über das Bild.\n\nDas ist der Normalfall. Lehrbuchbeispiele mit klar abbrechender PACF sind\nkonstruiert; echte Reihen sehen aus wie diese.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Reihe wird einmal gewöhnlich und einmal saisonal differenziert; danach ist\n> sie stationär (ADF p = 0.009). Die ACF zeigt bei Abstand 12 einen deutlich\n> negativen Wert (-0.40), was für einen saisonalen MA-Term spricht ($Q = 1$). Auf\n> der kurzen Zeitskala brechen weder ACF noch PACF ab; die gewöhnliche Ordnung\n> wird über Informationskriterien gewählt.\n\n### Beispiel 2: Vier Ordnungen im Vergleich\n\n#### Frage und Datenlage\n\nVier Kandidaten für die gewöhnliche Ordnung, alle mit derselben saisonalen\nStruktur $(0,1,1)_{12}$. Welcher gewinnt, und woran misst man das?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkandidaten <- list(\n  \"(0,1,1)\" = c(0, 1, 1),\n  \"(1,1,0)\" = c(1, 1, 0),\n  \"(1,1,1)\" = c(1, 1, 1),\n  \"(2,1,2)\" = c(2, 1, 2)\n)\n\nfor (name in names(kandidaten)) {\n  m <- Arima(training, order = kandidaten[[name]], seasonal = c(0, 1, 1))\n  cat(sprintf(\"%-9s AICc = %8.2f | BIC = %8.2f | logLik = %8.2f\\n\",\n              name, m$aicc, m$bic, m$loglik))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(0,1,1)   AICc =   637.62 | BIC =   644.05 | logLik =  -315.63\n(1,1,0)   AICc =   637.82 | BIC =   644.25 | logLik =  -315.73\n(1,1,1)   AICc =   626.93 | BIC =   635.38 | logLik =  -309.16\n(2,1,2)   AICc =   631.11 | BIC =   643.37 | logLik =  -308.90\n```\n\n\n:::\n\n```{.r .cell-code}\nautomatisch <- auto.arima(training, stepwise = FALSE, approximation = FALSE)\nautomatisch\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: training \nARIMA(1,0,0)(2,1,0)[12] with drift \n\nCoefficients:\n         ar1     sar1     sar2   drift\n      0.4436  -0.7188  -0.6356  3.9558\ns.e.  0.1085   0.0983   0.1003  0.1372\n\nsigma^2 = 262.3:  log likelihood = -308.2\nAIC=626.41   AICc=627.32   BIC=637.79\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfor ordnung in [(0, 1, 1), (1, 1, 0), (1, 1, 1), (2, 1, 2)]:\n    m = SARIMAX(training, order=ordnung, seasonal_order=(0, 1, 1, 12),\n                enforce_stationarity=False,\n                enforce_invertibility=False).fit(disp=False)\n    print(f\"{str(ordnung):<10} AIC = {m.aic:8.2f} | BIC = {m.bic:8.2f}\"\n          f\" | logLik = {m.llf:8.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(0, 1, 1)  AIC =   511.02 | BIC =   517.15 | logLik =  -252.51\n(1, 1, 0)  AIC =   519.90 | BIC =   526.08 | logLik =  -256.95\n(1, 1, 1)  AIC =   501.64 | BIC =   509.81 | logLik =  -246.82\n(2, 1, 2)  AIC =   483.41 | BIC =   495.56 | logLik =  -235.70\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ordnung | Parameter | AICc, R | BIC, R | AIC, Python | BIC, Python |\n|---|---|---|---|---|---|\n| (0,1,1) | 2 | 637.62 | 644.05 | 511.02 | 517.15 |\n| (1,1,0) | 2 | 637.82 | 644.25 | 519.90 | 526.08 |\n| **(1,1,1)** | 3 | **626.93** | **635.38** | 501.64 | 509.81 |\n| (2,1,2) | 5 | 631.11 | 643.37 | **483.41** | **495.56** |\n\n| Beobachtung | Deutung |\n|---|---|\n| **Die beiden Umgebungen wählen verschieden** | R nimmt (1,1,1), Python (2,1,2). Das ist der wichtigste Befund dieses Beispiels und kein Widerspruch, sondern die Folge davon, dass `Arima()` und `SARIMAX` verschieden rechnen. |\n| Die Zahlenniveaus liegen 130 Punkte auseinander | Die beiden Funktionen behandeln die Startwerte der differenzierten Reihe verschieden; R bezieht die Likelihood auf die volle Reihe, Python auf die differenzierte. Verglichen wird deshalb **innerhalb** einer Umgebung, nie über die Tabs hinweg. |\n| Warum Python (2,1,2) bevorzugt | Weil hier `enforce_stationarity` und `enforce_invertibility` abgeschaltet sind, darf das grösste Modell an den Rand des Parameterraums laufen und holt sich dort ein besseres Kriterium. R lässt das nicht zu. |\n| Die log-Likelihood **steigt immer** mit mehr Parametern | Das ist keine Information, sondern eine Selbstverständlichkeit; deshalb braucht es überhaupt Kriterien. |\n| AIC und BIC bestrafen Parameter verschieden | AIC mit 2 je Parameter, BIC mit $\\ln n$, hier also 4.4. `AICc` korrigiert AIC zusätzlich für kleine Stichproben und ist bei $n = 84$ die bessere Wahl. |\n| Unterschiede unter etwa **zwei** gelten als unbedeutend | In der R-Spalte liegen (0,1,1) und (1,1,0) mit 637.62 und 637.82 gleichauf; zwischen ihnen entscheidet das Kriterium nichts. |\n\n::: {.note-box}\n**Zwei Regeln zu Informationskriterien, die oft verletzt werden:**\n\n1. Sie sind nur zwischen Modellen auf **identischen Daten** vergleichbar. Wer $d$\n   oder $D$ ändert, ändert die Daten, auf die das Modell passt, die Werte sind\n   dann nicht mehr vergleichbar. Nur $p$, $q$, $P$ und $Q$ dürfen variieren.\n2. Ein kleines Kriterium ist **keine gute Prognose**. Es misst die Anpassung an\n   die Trainingsdaten, bestraft um die Parameterzahl. Bewertet wird auf dem\n   Testteil.\n\nDie automatische Suche in R landet meist nicht bei der von Hand gewählten\nOrdnung, sondern bei einer Variante mit Drift und saisonalen AR-Termen. Beide\nbeschreiben dieselbe Struktur, Trend plus Jahressaison, nur über verschiedene\nBauteile. Das ist der Normalfall und kein Widerspruch.\n:::\n\n#### Interpretation\n\nDas Kriterium liefert eine Vorauswahl, keine Entscheidung. Die Entscheidung\nfällt über Residuendiagnostik (Beispiel 4) und Testfehler (Beispiel 3).\n\n### Beispiel 3: Das Modell lesen\n\n#### Frage und Datenlage\n\nDas Modell SARIMA(1,1,1)(0,1,1)$_{12}$ wird geschätzt und seine Ausgabe Zeile\nfür Zeile gelesen. Dabei zeigt sich ein Problem, das die Informationskriterien\nnicht anzeigen.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodell <- Arima(training, order = c(1, 1, 1), seasonal = c(0, 1, 1))\nsummary(modell)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: training \nARIMA(1,1,1)(0,1,1)[12] \n\nCoefficients:\n         ar1      ma1     sma1\n      0.5535  -1.0000  -0.9999\ns.e.  0.1008   0.0726   0.2714\n\nsigma^2 = 249.6:  log likelihood = -309.16\nAIC=626.33   AICc=626.93   BIC=635.38\n\nTraining set error measures:\n                     ME     RMSE      MAE         MPE     MAPE      MASE\nTraining set -0.5614175 14.21601 10.23293 -0.07878486 1.517141 0.2157456\n                   ACF1\nTraining set 0.09953009\n```\n\n\n:::\n\n```{.r .cell-code}\n# Zum Vergleich: ohne die gewoehnliche Differenz, dafuer mit Drift\nohne_d <- Arima(training, order = c(1, 0, 0), seasonal = c(0, 1, 1),\n                include.drift = TRUE)\nround(coef(ohne_d), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    ar1    sma1   drift \n 0.5335 -1.0000  3.9541 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmodell = SARIMAX(training, order=(1, 1, 1), seasonal_order=(0, 1, 1, 12),\n                 enforce_stationarity=False,\n                 enforce_invertibility=False).fit(disp=False)\nprint(modell.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                     SARIMAX Results                                      \n==========================================================================================\nDep. Variable:                                  y   No. Observations:                   84\nModel:             SARIMAX(1, 1, 1)x(0, 1, 1, 12)   Log Likelihood                -246.818\nDate:                            Sat, 12 Sep 2026   AIC                            501.636\nTime:                                    06:38:43   BIC                            509.808\nSample:                                01-01-2018   HQIC                           504.812\n                                     - 12-01-2024                                         \nCovariance Type:                              opg                                         \n==============================================================================\n                 coef    std err          z      P>|z|      [0.025      0.975]\n------------------------------------------------------------------------------\nar.L1          0.5341      0.163      3.277      0.001       0.215       0.854\nma.L1         -1.0000   1391.775     -0.001      0.999   -2728.830    2726.830\nma.S.L12      -1.0000   3094.192     -0.000      1.000   -6065.504    6063.504\nsigma2       247.7772   8.92e+05      0.000      1.000   -1.75e+06    1.75e+06\n===================================================================================\nLjung-Box (L1) (Q):                   2.11   Jarque-Bera (JB):                11.26\nProb(Q):                              0.15   Prob(JB):                         0.00\nHeteroskedasticity (H):               0.56   Skew:                            -0.60\nProb(H) (two-sided):                  0.22   Kurtosis:                         4.82\n===================================================================================\n\nWarnings:\n[1] Covariance matrix calculated using the outer product of gradients (complex-step).\n```\n\n\n:::\n\n```{.python .cell-code}\nohne_d = SARIMAX(training, order=(1, 0, 0), seasonal_order=(0, 1, 1, 12),\n                 trend=\"c\", enforce_stationarity=False,\n                 enforce_invertibility=False).fit(disp=False)\nprint(ohne_d.params.round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nintercept     23.4348\nar.L1          0.5028\nma.S.L12      -1.0000\nsigma2       234.7663\ndtype: float64\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Koeffizient | Schätzung (R / Python) | Standardfehler (R / Python) | Was er sagt |\n|---|---|---|---|\n| `ar1` beziehungsweise `ar.L1` | **0.554 / 0.534** | 0.101 / 0.163 | Trägheit auf der gewöhnlichen Ebene: Gut die Hälfte der Abweichung überträgt sich auf den Folgemonat. Schätzung geteilt durch Standardfehler ergibt 5.5 beziehungsweise 3.3, deutlich von null verschieden. |\n| `ma1` beziehungsweise `ma.L1` | **-1.000 / -1.000** | 0.073 / **1393** | Beide landen **exakt auf -1**. Hier stimmt etwas nicht. |\n| `sma1` beziehungsweise `ma.S.L12` | -1.000 / -1.000 | 0.271 / 3098 | Ebenfalls am Rand, hier aber der Normalfall. |\n| `sigma^2` | 249.6 / 247.8 | | Streuung der Residuen, Grundlage der Prognoseintervalle. |\n\n| Befund | Erklärung |\n|---|---|\n| **Der MA-Koeffizient liegt exakt bei -1.000** | Auf dem Rand des zulässigen Bereichs; Invertierbarkeit verlangt einen Betrag unter eins. Dass **beide** Umgebungen dort landen, ist der eigentliche Befund. |\n| Die Standardfehler unterscheiden sich um vier Grössenordnungen | R erzwingt Invertierbarkeit und meldet einen unauffälligen Wert von 0.073; Python hat die Schranke hier abgeschaltet, läuft frei in den Rand und meldet 1393, also \"an dieser Stelle ist die Likelihood flach, der Wert ist unbestimmt\". **Die ehrlichere Ausgabe ist die von Python**, weil sie das Problem sichtbar macht statt es wegzuklemmen. |\n| Was das inhaltlich bedeutet | Ein MA(1)-Koeffizient von -1 hebt eine Differenz genau wieder auf. Das Modell sagt also: **die gewöhnliche Differenz war unnötig.** Und das stimmt, die Reihe wurde mit einem *deterministischen* Trend erzeugt, der nicht wegdifferenziert gehört, siehe [Stationarität](stationaritaet-acf-pacf.qmd), Beispiel 3. |\n| `ma.S.L12 = -1.000` ist dagegen unauffällig | Bei saisonal differenzierten Reihen ist ein saisonaler MA-Koeffizient nahe -1 der Regelfall und kein Warnzeichen. |\n| Die Alternative ohne gewöhnliche Differenz | `(1,0,0)(0,1,1)` mit Drift kommt ohne Randwert aus. In R lautet der Drift 3.96 je Monat (nahe an den eingebauten 4), in Python nennt `trend=\"c\"` stattdessen ein Absolutglied. |\n\n::: {.note-box}\n**Warum die Informationskriterien das nicht zeigen:** Ein Modell, das eine\nüberflüssige Differenz durch einen MA-Term von -1 wieder aufhebt, passt genauso\ngut wie das Modell ohne beides. Die Likelihood ist gleich, die Parameterzahl um\neins höher, der AIC-Nachteil beträgt magere zwei Punkte und verschwindet im\nVergleich mit anderen Ordnungen.\n\n**Woran man es erkennt**, ist deshalb immer der Blick auf die Koeffizienten:\n\n| Zeichen | Bedeutung |\n|---|---|\n| MA-Koeffizient nahe -1 auf der gewöhnlichen Ebene | $d$ ist um eins zu hoch |\n| AR-Koeffizient nahe +1 | $d$ ist um eins zu niedrig; die Reihe ist noch nicht stationär |\n| Standardfehler um Grössenordnungen zu gross | die Likelihood ist flach, das Modell überparametrisiert |\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Das Modell SARIMA(1,1,1)(0,1,1)$_{12}$ schätzt einen AR-Koeffizienten von 0.55\n> (SE 0.10); der gewöhnliche MA-Koeffizient läuft mit -1.00 auf den Rand des\n> Parameterraums, was auf eine überflüssige gewöhnliche Differenz hinweist. Eine\n> Variante ohne diese Differenz und mit Drift schätzt dieselbe Trägheit ohne\n> Randwert und einen Drift von 3.96 je Monat.\n\n### Beispiel 4: Residuen mit und ohne Struktur\n\n#### Frage und Datenlage\n\nDer entscheidende Prüfschritt. Ein Modell ohne saisonale Anteile passt scheinbar,\nlässt aber Struktur in den Residuen zurück. Verglichen werden ARIMA(1,1,0) ohne\nSaison und das vollständige Modell.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nzu_einfach <- Arima(training, order = c(1, 1, 0))\n\ncheckresiduals(zu_einfach)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLjung-Box test\n\ndata:  Residuals from ARIMA(1,1,0)\nQ* = 70.798, df = 16, p-value = 7.23e-09\n\nModel df: 1.   Total lags used: 17\n```\n\n\n:::\n\n```{.r .cell-code}\ncheckresiduals(modell)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLjung-Box test\n\ndata:  Residuals from ARIMA(1,1,1)(0,1,1)[12]\nQ* = 16.028, df = 14, p-value = 0.3117\n\nModel df: 3.   Total lags used: 17\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 4: Residuendiagnostik ohne saisonale Anteile, die ACF zeigt Spitzen bei Vielfachen von zwölf.](arima-sarima_files/figure-html/fig-b4-ar-r-1.png){#fig-b4-ar-r-1 width=100%}\n:::\n\n::: {.cell-output-display}\n![Beispiel 4: Residuendiagnostik ohne saisonale Anteile, die ACF zeigt Spitzen bei Vielfachen von zwölf.](arima-sarima_files/figure-html/fig-b4-ar-r-2.png){#fig-b4-ar-r-2 width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nzu_einfach = SARIMAX(training, order=(1, 1, 0),\n                     enforce_stationarity=False).fit(disp=False)\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.4))\nfor achse, (name, m) in zip(achsen, [(\"ohne Saison\", zu_einfach),\n                                     (\"mit Saison\", modell)]):\n    plot_acf(m.resid[13:], ax=achse, lags=24, title=f\"Residuen {name}\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: die ACF der Residuen beider Modelle.](arima-sarima_files/figure-html/fig-b4-ar-py-1.png){#fig-b4-ar-py width=100%}\n:::\n\n```{.python .cell-code}\nfor name, m in [(\"ohne Saison\", zu_einfach), (\"mit Saison\", modell)]:\n    residuen = m.resid[13:]\n    lb = acorr_ljungbox(residuen, lags=[12, 24], return_df=True)\n    print(f\"{name:12s} Ljung-Box p: {lb['lb_pvalue'].round(4).tolist()}\"\n          f\" | ACF(12) = {acf(residuen, nlags=24)[12]:+.3f}\"\n          f\" | ACF(24) = {acf(residuen, nlags=24)[24]:+.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nohne Saison  Ljung-Box p: [0.0001, 0.0] | ACF(12) = +0.284 | ACF(24) = +0.193\nmit Saison   Ljung-Box p: [0.2401, 0.1234] | ACF(12) = -0.054 | ACF(24) = -0.106\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Modell | Ljung-Box p (12) | Ljung-Box p (24) | ACF(12) | ACF(24) |\n|---|---|---|---|---|\n| **ohne Saison** | **0.0001** | **< 0.0001** | **+0.284** | **+0.193** |\n| mit Saison | 0.240 | 0.123 | -0.054 | -0.106 |\n\n(Python-Werte. `checkresiduals()` in R wählt die Anzahl Abstände selbst, für das\nModell ohne Saison 17 statt 12 und kommt auf $Q^* = 70.8$ mit p = 7·10⁻⁹, also\nzum selben Schluss.)\n\n| Befund | Erklärung |\n|---|---|\n| **ACF(12) = +0.284 ohne Saison** | Die Residuen von vor zwölf Monaten sagen etwas über die heutigen, genau die Saisonstruktur, die das Modell nicht kennt. Bei 24 noch +0.193. |\n| Ljung-Box p = 0.0001 | Der Test verwirft die Annahme unkorrelierter Residuen deutlich. Er prüft **alle** Abstände bis 12 gemeinsam. |\n| Mit Saison: ACF(12) = -0.054, p = 0.24 | Innerhalb der Konfidenzgrenzen, der Test unauffällig. Die Struktur ist erfasst. |\n| Die Punktprognosen sind dabei **nicht** das Hauptproblem | Verzerrt sind vor allem die **Intervalle**: Das Modell behandelt verbleibende Struktur als Rauschen und schätzt die Unsicherheit falsch ein. |\n\n::: {.note-box}\n**Die Diagnose ist zugleich das Rezept:**\n\n| Wo die Spitze liegt | Was fehlt |\n|---|---|\n| bei Vielfachen der Periode (12, 24) | saisonale Anteile, $P$, $Q$ oder $D$ |\n| beim ersten Abstand | ein gewöhnlicher AR- oder MA-Term |\n| langsam abfallend über viele Abstände | eine Differenz |\n| überall verstreut, einzelne knapp draussen | nichts; bei 24 Abständen ist ein Ausreisser zufällig zu erwarten |\n\nUnd immer beides prüfen: **ACF und Test**, nicht eines allein. Der Test fasst\nzusammen und sagt nicht, **wo** das Problem sitzt; die Grafik sagt es, hat aber\nkeine Schwelle.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Ohne saisonale Anteile bleiben die Residuen deutlich autokorreliert\n> (Ljung-Box p < .001, ACF bei Abstand 12 gleich +0.28). Das vollständige Modell\n> besteht die Prüfung (p = 0.24, ACF(12) = -0.05); berichtet wird dieses.\n\n### Beispiel 5: Prognose und der Vergleich, der zählt\n\n#### Frage und Datenlage\n\nZwölf Monate Prognose gegen die tatsächlichen Werte und gegen drei einfachere\nModelle. Rechtfertigt der Aufwand sich?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprognose <- forecast(modell, h = 12)\n\npar(mar = c(4, 4, 2, 1))\nplot(prognose, ylab = \"Absatz\", xlab = \"Jahr\",\n     main = \"SARIMA(1,1,1)(0,1,1)[12]\", include = 36)\nlines(test, col = \"#b2182b\", lwd = 2)\n\nnaiv <- snaive(training, h = 12)\nhw <- hw(training, h = 12, seasonal = \"additive\")\nzu_einfach_p <- forecast(zu_einfach, h = 12)\n\nspalten <- c(\"RMSE\", \"MAE\", \"MAPE\")\nround(rbind(\n  naiv_saisonal = accuracy(naiv, test)[\"Test set\", spalten],\n  ohne_saison = accuracy(zu_einfach_p, test)[\"Test set\", spalten],\n  holt_winters = accuracy(hw, test)[\"Test set\", spalten],\n  sarima = accuracy(prognose, test)[\"Test set\", spalten]\n), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               RMSE   MAE MAPE\nnaiv_saisonal 50.29 47.08 5.62\nohne_saison   72.56 60.06 7.34\nholt_winters  19.22 16.95 2.02\nsarima        16.96 14.06 1.67\n```\n\n\n:::\n\n```{.r .cell-code}\n# Wie schnell wird das Intervall breiter?\nround(c(monat_1 = prognose$upper[1, \"95%\"] - prognose$lower[1, \"95%\"],\n        monat_12 = prognose$upper[12, \"95%\"] - prognose$lower[12, \"95%\"]), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n monat_1.95% monat_12.95% \n        67.9         85.1 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 5: Prognose des SARIMA-Modells mit Intervall, dazu die tatsächlichen Werte.](arima-sarima_files/figure-html/fig-b5-ar-r-3.png){#fig-b5-ar-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom statsmodels.tsa.holtwinters import ExponentialSmoothing\n\nvorhersage = modell.get_forecast(12)\nmittel = vorhersage.predicted_mean\nband = vorhersage.conf_int(alpha=0.05)\n\nfig, achse = plt.subplots()\nachse.plot(training.iloc[-36:], color=\"0.5\", label=\"Training\")\nachse.plot(test, color=\"#b2182b\", lw=2, label=\"tatsächlich\")\nachse.plot(mittel, color=\"#2166ac\", lw=2, label=\"Prognose\")\nachse.fill_between(test.index, band.iloc[:, 0], band.iloc[:, 1],\n                   color=\"#2166ac\", alpha=0.15)\nachse.set_ylabel(\"Absatz\")\nachse.legend(frameon=False)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselbe Prognose in Python.](arima-sarima_files/figure-html/fig-b5-ar-py-1.png){#fig-b5-ar-py width=100%}\n:::\n\n```{.python .cell-code}\ndef masse(wahr, geschaetzt):\n    fehler = np.asarray(wahr) - np.asarray(geschaetzt)\n    return {\"RMSE\": round(float(np.sqrt((fehler ** 2).mean())), 2),\n            \"MAE\": round(float(np.abs(fehler).mean()), 2),\n            \"MAPE\": round(float(np.abs(fehler / np.asarray(wahr)).mean() * 100), 2)}\n\n\nhw = ExponentialSmoothing(training, trend=\"add\", seasonal=\"add\",\n                          seasonal_periods=12,\n                          initialization_method=\"estimated\").fit()\n\nkandidaten = {\n    \"naiv_saisonal\": training.iloc[-12:].values,\n    \"ohne_saison\": zu_einfach.get_forecast(12).predicted_mean.values,\n    \"holt_winters\": hw.forecast(12).values,\n    \"sarima\": mittel.values,\n}\nprint(pd.DataFrame({name: masse(test, werte)\n                    for name, werte in kandidaten.items()}).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                RMSE    MAE  MAPE\nnaiv_saisonal  50.29  47.08  5.62\nohne_saison    72.63  60.13  7.35\nholt_winters   18.17  15.49  1.84\nsarima         17.07  14.15  1.68\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Bandbreite Monat 1: \", round(float(band.iloc[0, 1] - band.iloc[0, 0]), 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBandbreite Monat 1:  67.7\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Bandbreite Monat 12:\", round(float(band.iloc[-1, 1] - band.iloc[-1, 0]), 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBandbreite Monat 12: 83.4\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Modell | RMSE (Python / R) | MAPE (Python / R) |\n|---|---|---|\n| naiv saisonal | 50.29 / 50.29 | 5.62 / 5.62 % |\n| ARIMA ohne Saison | 72.63 /, | 7.35 /, % |\n| Holt-Winters | 18.17 / 19.22 | 1.84 / 2.02 % |\n| **SARIMA(1,1,1)(0,1,1)** | **17.07 / 16.96** | **1.68 / 1.67 %** |\n\n| Beobachtung | Deutung |\n|---|---|\n| SARIMA schlägt die naive Prognose um den **Faktor 3** | Das rechtfertigt den Aufwand gegenüber \"gar kein Modell\". |\n| Gegenüber **Holt-Winters** beträgt der Vorsprung rund einen Punkt RMSE | Also 6 Prozent in Python, 12 Prozent in R. Das ist der Vergleich, der wirklich zählt: gegen das einfachere Verfahren, das dieselbe Aufgabe löst. Ob der Gewinn den zusätzlichen Aufwand aus Ordnungswahl und Diagnostik wert ist, ist eine Sachfrage, keine statistische. |\n| Das Modell **ohne Saison** ist schlechter als die naive Prognose | 72.6 gegen 50.3. Ein Modell kann alles andere unterbieten, wenn ihm der wichtigste Bestandteil fehlt. |\n| Bandbreite Monat 1 gegen Monat 12 | 67.7 gegen 83.4 | Das Intervall wächst um rund ein Viertel. Bei ARIMA-Modellen mit Differenzen wächst es mit dem Horizont unbegrenzt weiter, deshalb gehört der Horizont begrenzt und die Bandbreite mitberichtet. |\n\n::: {.note-box}\n**Warum SARIMA hier nur knapp gewinnt**, obwohl die Reihe mit einem\nautokorrelierten Fehler konstruiert wurde: Der AR(1)-Anteil mit Koeffizient 0.6\nträgt zwar zur Prognose bei, aber nur für die ersten Monate. Danach ist sein\nBeitrag abgeklungen ($0.6^{6} = 0.05$), und übrig bleibt dasselbe, was\nHolt-Winters auch kann, Trend und Saison fortschreiben.\n\nDie allgemeine Lehre: **Der Vorsprung eines Modells über eine explizite\nAbhängigkeitsstruktur ist bei kurzen Horizonten gross und bei langen klein.**\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Das Modell SARIMA(1,1,1)(0,1,1)$_{12}$ prognostiziert die folgenden zwölf\n> Monate mit einem RMSE von 17.1 (MAPE 1.7 Prozent), gegenüber 50.3 (5.6 Prozent)\n> bei der naiven saisonalen Prognose und 18.2 (1.8 Prozent) bei Holt-Winters.\n> Alle tatsächlichen Werte liegen im 95-Prozent-Prognoseintervall, dessen Breite\n> von 68 auf 83 Einheiten wächst. Der Gewinn gegenüber der naiven Prognose ist\n> gross, gegenüber dem einfacheren Verfahren gering.\n\n### Beispiel 6: Rollierende Bewertung\n\n#### Frage und Datenlage\n\nEin einzelner Testzeitraum ist eine Stichprobe von eins. Was, wenn gerade dieses\nJahr besonders gut oder schlecht prognostizierbar war? Die rollierende Bewertung\nverschiebt den Prognosezeitpunkt über die Reihe.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfehler_rollierend <- tsCV(absatz, forecastfunction = function(x, h) {\n  forecast(Arima(x, order = c(1, 1, 1), seasonal = c(0, 1, 1)), h = h)\n}, h = 6, initial = 60)\n\nround(c(RMSE_rollierend = sqrt(mean(fehler_rollierend^2, na.rm = TRUE)),\n        anzahl_fehler = sum(!is.na(fehler_rollierend)),\n        RMSE_einmalig = accuracy(prognose, test)[\"Test set\", \"RMSE\"]), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRMSE_rollierend   anzahl_fehler   RMSE_einmalig \n          18.98          195.00           16.96 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfehler_liste = []\nfor ende in range(72, len(absatz) - 6, 6):\n    teil = absatz.iloc[:ende]\n    m = SARIMAX(teil, order=(1, 1, 1), seasonal_order=(0, 1, 1, 12),\n                enforce_stationarity=False,\n                enforce_invertibility=False).fit(disp=False)\n    p = m.get_forecast(6).predicted_mean\n    fehler_liste.append(absatz.iloc[ende:ende + 6].values - p.values)\n\nalle = np.concatenate(fehler_liste)\nprint({\"RMSE_rollierend\": round(float(np.sqrt((alle ** 2).mean())), 2),\n       \"Anzahl Prognosen\": len(alle),\n       \"Anzahl Fenster\": len(fehler_liste)})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'RMSE_rollierend': 18.08, 'Anzahl Prognosen': 18, 'Anzahl Fenster': 3}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Bewertung | RMSE (Python / R) | Grundlage |\n|---|---|---|\n| einmaliger Testteil | 17.07 / 16.96 | 12 Prognosen von **einem** Zeitpunkt aus |\n| rollierend | **18.08 / 18.98** | Python: 18 Prognosen aus 3 Fenstern; R: `tsCV()` schiebt um je einen Schritt und sammelt deutlich mehr |\n\n| Beobachtung | Deutung |\n|---|---|\n| Die Werte liegen nahe beieinander | 17.1 gegen 18.1 in Python, 17.0 gegen 19.0 in R. Der einmalige Testteil war also nicht ungewöhnlich günstig, ein beruhigender Befund. |\n| Die rollierende Zahl beruht auf **mehr** Prognosen | und ist damit weniger vom gewählten Abschnitt abhängig. Bei knapp beieinander liegenden Modellen ist sie die richtige Grundlage. |\n| Der Horizont unterscheidet sich | 6 statt 12 Monate. Kürzere Horizonte sind leichter, deshalb sind die Zahlen nicht direkt vergleichbar, nur die Grössenordnung. |\n| Der Preis | Das Modell wird für jedes Fenster neu geschätzt. Bei drei Fenstern ist das harmlos, bei einer langen Reihe mit Schrittweite eins nicht. |\n\n::: {.note-box}\nDie R-Funktion `tsCV()` macht es gründlicher: Sie schiebt den Zeitpunkt **um je\neinen Schritt** weiter und liefert daher viel mehr Fehler. Die Python-Schleife\noben nimmt Schritte von sechs Monaten, um die Rechenzeit zu begrenzen. Beide\nZahlen sind deshalb nicht direkt vergleichbar, wohl aber jede für sich mit dem\neinmaligen Testfehler.\n\n**Wann sich der Aufwand lohnt:** wenn zwei Modelle im einmaligen Testfehler\nweniger als etwa zehn Prozent auseinanderliegen, wie hier SARIMA und\nHolt-Winters. Dann entscheidet ein einzelner Testabschnitt zufällig.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> In einer rollierenden Bewertung mit sechs Monaten Horizont erreicht das Modell\n> einen RMSE von 18.1 (Python, drei Fenster) beziehungsweise 19.0 (R, `tsCV()`),\n> gegenüber 17.0 auf dem einmaligen Testteil. Die Prognosegüte hängt damit nicht am gewählten Testabschnitt.\n\n::::\n\n## Interpretationsfallen\n\n- **Informationskriterien vergleichen nur gleiche Daten.** Wer die Anzahl\n  Differenzen ändert, darf AIC-Werte nicht mehr vergleichen.\n- **Ein kleines AIC ist keine gute Prognose.** Bewertet wird auf einem Testteil,\n  nicht am Kriterium.\n- **Residuen ohne Prüfung sind ein Kunstfehler.** ACF und Ljung-Box gehören zu\n  jedem berichteten Modell.\n- **Die automatische Suche ersetzt das Denken nicht.** Sie findet ein Modell mit\n  gutem Kriterium; ob die Ordnung zur Reihe passt, sagt die Grafik.\n- **Überdifferenzieren verschlechtert das Modell.** Eine Differenz mehr als nötig\n  erzeugt künstliche Struktur, siehe\n  [Stationarität](stationaritaet-acf-pacf.qmd).\n- **Koeffizienten sind selten inhaltlich deutbar.** Ein AR-Koeffizient von 0.6\n  beschreibt Trägheit, nicht eine Ursache.\n- **Prognosen driften zum Mittel.** Über längere Horizonte laufen ARIMA-Prognosen\n  gegen einen konstanten Wert oder eine Gerade; die Intervalle werden dabei sehr\n  breit.\n- **Kein Modell überlebt einen Strukturbruch.** Wer über einen Bruch hinweg\n  schätzt, mittelt zwei Regime.\n\n## Ergebnis berichten\n\nVorlage für den Ergebnissatz:\n\n> Die Reihe wurde als [Ordnung] modelliert (geschätzt auf [Zeitraum], n = [n]).\n> Die Residuen zeigen keine Autokorrelation (Ljung-Box p = [p]). Auf dem Testteil\n> von [h] Perioden erreicht die Prognose einen RMSE von [Wert] und einen MAPE von\n> [Wert] Prozent, gegenüber [Wert] beziehungsweise [Wert] bei der naiven\n> saisonalen Prognose.\n\nGenannt werden: Modellordnung samt Periode, Trainingszeitraum und n, Anzahl\nDifferenzen und deren Begründung, Koeffizienten mit Standardfehlern,\nInformationskriterium, Residuendiagnostik, Fehlermasse auf dem Testteil und der\nVergleich mit einer naiven Prognose.\n\nBeispiel für eine Ergebnistabelle:\n\n| Modell | AICc | Ljung-Box p | RMSE (Test) | MAPE (Test) |\n|---|---|---|---|---|\n| naiv saisonal | | | | |\n| Holt-Winters | | | | |\n| SARIMA(1,1,1)(0,1,1) | | | | |\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt ARIMA |\n|---|---|\n| [Glättung](glaettung-einfache-verfahren.qmd) | schnelle robuste Prognose, keine Modellwahl gewünscht |\n| Regression mit Zeitreihenfehlern | externe Einflussgrössen sind wichtig |\n| Vektorautoregression | mehrere Reihen beeinflussen sich gegenseitig |\n| GARCH | die Schwankungsbreite selbst ist das Thema |\n| [Multiple lineare Regression](../regression/multiple-lineare-regression.qmd) | keine zeitliche Abhängigkeit vorhanden |\n| Verfahren des maschinellen Lernens | viele Reihen, viele Prädiktoren, Deutbarkeit zweitrangig |\n\n## Verständnisfragen\n\n::: {.quiz}\nDie ACF der Residuen zeigt Spitzen bei den Abständen 12 und 24. Was fehlt dem\nModell?\n\n- [x] Saisonale Anteile ~ Richtig. Spitzen bei Vielfachen der Periode sind das\n      Zeichen für nicht erfasste Saisonstruktur. Ergänzt wird ein saisonaler AR-\n      oder MA-Term, oft zusammen mit saisonalem Differenzieren.\n- [ ] Ein zusätzlicher gewöhnlicher AR-Term ~ Der würde den ersten Abstand\n      betreffen, nicht Vielfache von zwölf.\n- [ ] Eine weitere gewöhnliche Differenz ~ Sie entfernt Trend, nicht Saison.\n:::\n\n::: {.quiz}\nModell A hat AIC 512 bei zwei Differenzen, Modell B hat AIC 498 bei einer\nDifferenz. Welches ist besser?\n\n- [ ] B, das AIC ist kleiner ~ Die Werte sind nicht vergleichbar.\n- [x] Nicht entscheidbar: verschiedene Anzahl Differenzen heisst verschiedene\n      Daten ~ Richtig. Informationskriterien gelten nur zwischen Modellen auf\n      identischen Daten. Verglichen wird dann über die Prognosegüte auf einem\n      Testteil.\n- [ ] A, weil weniger Differenzen sparsamer sind ~ A hat mehr Differenzen, und\n      Sparsamkeit entscheidet hier nicht.\n:::\n\n::: {.quiz}\nWas bedeutet ein AR-Koeffizient von 0.6?\n\n- [x] Trägheit: ein Teil der Abweichung vom Niveau überträgt sich auf den nächsten\n      Zeitpunkt ~ Richtig. Der Wert beschreibt die Struktur der Reihe, nicht eine\n      Ursache. Beträge unter eins sind für Stationarität nötig.\n- [ ] Der nächste Wert ist 60 Prozent des aktuellen ~ Der Koeffizient wirkt auf\n      die Abweichung vom Niveau, nicht auf den Wert selbst.\n- [ ] Das Modell erklärt 60 Prozent der Varianz ~ Das wäre eine andere Kennzahl.\n:::\n\n::: {.quiz}\nDie automatische Suche wählt ARIMA(3,0,2) für eine Reihe mit sichtbarem Trend.\nWas ist zu prüfen?\n\n- [x] Ob die Reihe differenziert werden müsste; ohne Differenz modelliert das\n      Modell den Trend über viele AR-Terme ~ Richtig. Eine hohe AR-Ordnung bei\n      `d = 0` und sichtbarem Trend ist ein typisches Zeichen. Ein Blick auf ACF\n      und Stationaritätstests klärt es.\n- [ ] Nichts, die Suche minimiert das Kriterium ~ Sie tut das, kann dabei aber\n      eine unpassende Struktur wählen.\n- [ ] Ob genügend Beobachtungen vorliegen ~ Auch eine Frage, aber nicht die\n      auffällige hier.\n:::\n\n## Verlinkte Ressourcen\n\n- [Forecasting: Principles and Practice, Kapitel 9](https://otexts.com/fpp3/arima.html)\n- [forecast: Arima und auto.arima](https://pkg.robjhyndman.com/forecast/)\n- [statsmodels: SARIMAX](https://www.statsmodels.org/stable/examples/notebooks/generated/statespace_sarimax_stata.html)\n",
    "supporting": [
      "arima-sarima_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}