{
  "hash": "98ac585d09762f3d61580d871e8f2ba4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Logistische Regression\"\ndescription: \"Binäre Zielgrösse modellieren, Odds Ratios und Wahrscheinlichkeiten lesen.\"\ncategories: [\"Regression\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: methode\nstand: fertig\norder: 30\n---\n\n\n\n\n\nAlle Beispiele rechnen mit demselben deterministisch konstruierten Datensatz:\n200 Anlagen mit der Angabe, ob innerhalb eines Jahres ein Ausfall auftrat, der\nLaufzeit in Jahren und der Wartungsart.\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Wie hängt die Wahrscheinlichkeit eines Ereignisses von mehreren Einflussgrössen ab? |\n| Zielvariable | binär: ja oder nein, 0 oder 1 |\n| Prädiktoren | beliebig viele, metrisch oder kategorial |\n| Was die Methode liefert | Koeffizienten auf der Logit-Skala, daraus Odds Ratios mit Konfidenzintervall, vorhergesagte Wahrscheinlichkeiten |\n| R-Funktion | `glm(y ~ x1 + x2, family = binomial, data = df)` |\n| Python-Funktion | `smf.logit(\"y ~ x1 + x2\", data=df).fit()` |\n| Verwandte Methoden | [multiple lineare Regression](multiple-lineare-regression.qmd), [Klassifikationsgüte](klassifikationsguete.qmd), [Chi-Quadrat-Tests](../tests/chi-quadrat-tests.qmd) |\n\n## Wann diese Methode, wann nicht\n\nTypische Fragestellungen: Fällt eine Anlage aus, wird ein Kredit\nzurückgezahlt, klickt eine Besucherin, besteht eine Prüfung? Gemeinsam ist\nihnen, dass die Zielgrösse genau zwei Ausprägungen hat und dass mehrere\nEinflussgrössen zugleich wirken.\n\nWarum nicht einfach eine lineare Regression auf 0 und 1? Sie liefert\nVorhersagen unter 0 und über 1, die als Wahrscheinlichkeit sinnlos sind,\nunterstellt eine konstante Residuenstreuung, die bei binären Daten nicht\nexistieren kann, und erzwingt einen geradlinigen Verlauf, obwohl\nWahrscheinlichkeiten an den Rändern zwangsläufig abflachen.\n\n| Situation | Stattdessen |\n|---|---|\n| Zielgrösse metrisch | [multiple lineare Regression](multiple-lineare-regression.qmd) |\n| Zielgrösse mit mehr als zwei ungeordneten Stufen | multinomiale logistische Regression |\n| Zielgrösse mit geordneten Stufen | ordinale Regression, Proportional-Odds-Modell |\n| Zielgrösse ist eine Anzahl | Poisson- oder negative Binomialregression |\n| Zeit bis zum Ereignis, mit zensierten Fällen | [Cox-Modell](../ueberlebenszeit/cox-modell.qmd) |\n| Nur zwei kategoriale Merkmale ohne weitere Einflussgrössen | [Chi-Quadrat-Test](../tests/chi-quadrat-tests.qmd) |\n\n## Grundidee und Modell\n\nModelliert wird nicht die Wahrscheinlichkeit selbst, sondern ihr Logarithmus\nder Chancen. Die Chance (englisch odds) ist das Verhältnis von Ereignis zu\nGegenereignis:\n\n$$\\text{Chance} = \\frac{p}{1-p}, \\qquad\n\\log\\left(\\frac{p}{1-p}\\right) = \\beta_0 + \\beta_1 x_1 + \\beta_2 x_2 + \\dots$$\n\nDiese Umformung löst genau die drei Probleme der linearen Regression: Der\nLogarithmus der Chancen kann jeden Wert zwischen minus und plus unendlich\nannehmen, während $p$ immer zwischen 0 und 1 bleibt.\n\n| Grösse | Bereich | Bedeutung |\n|---|---|---|\n| Wahrscheinlichkeit $p$ | 0 bis 1 | Anteil der Fälle mit Ereignis |\n| Chance $p/(1-p)$ | 0 bis unendlich | Bei $p = 0.5$ ist die Chance 1, also \"eins zu eins\" |\n| Logit $\\log(p/(1-p))$ | minus bis plus unendlich | die Skala, auf der das Modell linear ist |\n\nDie Rücktransformation lautet:\n\n$$p = \\frac{1}{1 + e^{-(\\beta_0 + \\beta_1 x_1 + \\dots)}}$$\n\nGeschätzt wird nicht mit kleinsten Quadraten, sondern mit der\nMaximum-Likelihood-Methode und einem iterativen Verfahren. Daraus folgen zwei\npraktische Unterschiede zur linearen Regression: Es gibt kein R², sondern nur\nErsatzmasse, und die Schätzung kann scheitern, wenn die Gruppen zu sauber\ngetrennt sind, siehe Beispiel 3.\n\n::: {.note-box}\n**Der Koeffizient ist nicht die Änderung der Wahrscheinlichkeit.** Er ist die\nÄnderung des Logits. Exponenziert ergibt er das Odds Ratio, also den Faktor,\num den sich die **Chance** ändert. Um wie viele Prozentpunkte sich die\n**Wahrscheinlichkeit** ändert, hängt davon ab, wo man startet. Das ist der\nwichtigste Punkt dieser Seite und der Inhalt von Beispiel 2.\n:::\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung |\n|---|---|---|---|\n| Unabhängige Beobachtungen | Jede Zeile ist ein eigener Fall | Erhebungsdesign | Standardfehler zu klein |\n| Binäre Zielgrösse | genau zwei Ausprägungen | Werte zählen | falsches Modell |\n| Linearität im Logit | Der Prädiktor wirkt geradlinig auf den Logit, nicht auf $p$ | Prädiktor gruppiert gegen den beobachteten Logit auftragen | Effekt wird verzerrt geschätzt |\n| Keine starke Multikollinearität | Prädiktoren messen nicht dasselbe | VIF wie bei der linearen Regression | Standardfehler wachsen |\n| Genug Ereignisse je Prädiktor | Faustregel: mindestens 10 Ereignisse je geschätztem Koeffizienten | Ereignisse zählen | Schätzung instabil, Intervalle unbrauchbar |\n| Keine vollständige Trennung | Kein Prädiktor trennt die Gruppen perfekt | Warnung des Programms, absurd grosse Koeffizienten | Schätzung existiert nicht, siehe Beispiel 3 |\n\n## Output lesen\n\nR, `summary(glm(..., family = binomial))`:\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| `Estimate` | Koeffizient auf der **Logit-Skala** | nicht direkt deutbar; erst exponenziert ergibt er das Odds Ratio |\n| `Std. Error` | Unsicherheit auf der Logit-Skala | |\n| `z value` | Estimate durch Std. Error | heisst z, nicht t: die Verteilung ist nur näherungsweise normal |\n| `Pr(>|z|)` | p-Wert des Koeffizienten | |\n| `Null deviance` | Abweichung des Modells ohne Prädiktoren | Ausgangspunkt |\n| `Residual deviance` | Abweichung des angepassten Modells | Die Differenz zur Null-Devianz ist der Gewinn |\n| `AIC` | für Modellvergleiche | kleiner ist besser, siehe [Modellauswahl](modellauswahl.qmd) |\n| `Number of Fisher Scoring iterations` | Anzahl Iterationen | Werte über etwa 25 deuten auf Trennungsprobleme |\n| Warnung `fitted probabilities numerically 0 or 1 occurred` | Trennung | ernst nehmen, siehe Beispiel 3 |\n\nPython, `smf.logit(...).fit()`:\n\n| Ausgabe | Was sie sagt | Unterschied zu R |\n|---|---|---|\n| `coef`, `std err`, `z`, `P>|z|` | wie in R | nur andere Bezeichnung |\n| `[0.025 0.975]` | Konfidenzintervall auf der Logit-Skala | steht direkt in der Tabelle |\n| `Pseudo R-squ.` | McFadden-Pseudo-R² | in R nicht enthalten, dort aus den Devianzen zu bilden |\n| `Log-Likelihood`, `LL-Null`, `LLR p-value` | Anpassungsgüte und Gesamttest | in R als Devianzen ausgegeben, Devianz ist minus zweimal die Log-Likelihood |\n| keine Devianzen | fehlen | über `-2 * modell.llf` zu bekommen |\n\n::: {.note-box}\n**Konfidenzintervalle unterscheiden sich zwischen den Sprachen.** `confint()`\nin R rechnet über die Profil-Likelihood, statsmodels und `confint.default()`\nin R über die Wald-Näherung. Die Ergebnisse liegen meist nah beieinander,\nkönnen bei kleinen Stichproben aber merklich abweichen. Auf dieser Seite wird\n`confint.default()` verwendet, damit R und Python vergleichbar bleiben; für\neinen Bericht ist die Profil-Variante die genauere Wahl.\n:::\n\n## Interpretationsfallen\n\n- **Odds Ratio ist kein Risikoverhältnis.** Ein Odds Ratio von 3.8 bedeutet\n  nicht, dass das Ereignis 3.8 mal so häufig auftritt. Bei häufigen Ereignissen\n  überschätzt es das Risikoverhältnis deutlich.\n- **Derselbe Koeffizient bedeutet verschiedene Wahrscheinlichkeitsänderungen.**\n  Siehe Beispiel 2.\n- **Pseudo-R² ist nicht R².** Werte von 0.2 bis 0.4 gelten bereits als gute\n  Anpassung. Wer sie wie ein Bestimmtheitsmass liest, hält jedes Modell für\n  schlecht.\n- **Genauigkeit ist ein schlechtes Gütemass bei seltenen Ereignissen.** Bei\n  einem Ereignisanteil von 2 Prozent erreicht \"immer nein\" eine Genauigkeit von\n  98 Prozent, siehe [Klassifikationsgüte](klassifikationsguete.qmd).\n- **Die Schwelle 0.5 ist eine Konvention, keine Vorgabe.** Sie ergibt sich aus\n  der Annahme, dass beide Fehlerarten gleich teuer sind, siehe Beispiel 4.\n- **Vollständige Trennung ist kein gutes Zeichen.** Sie sieht nach einem\n  perfekten Modell aus und bedeutet, dass keine Schätzung existiert.\n- **Kausalität folgt auch hier nicht aus dem Modell.** Ein Koeffizient\n  beschreibt einen Zusammenhang bei konstant gehaltenen anderen Grössen, nicht\n  eine Wirkung.\n\n## Ergebnis berichten\n\nVorlage für den Ergebnissatz:\n\n> [Prädiktor] hängt mit [Ereignis] zusammen: Odds Ratio [Wert],\n> 95-Prozent-Konfidenzintervall [unten] bis [oben], p = [p]. Bei einer\n> Ausgangswahrscheinlichkeit von [p1] entspricht das [p2], also einer Änderung\n> um [Prozentpunkte] Prozentpunkte (n = [n], davon [Anzahl] Ereignisse).\n\nGenannt werden: Anzahl Beobachtungen **und** Anzahl Ereignisse, alle\nKoeffizienten als Odds Ratios mit Intervall, ein Anpassungsmass, und\nmindestens eine Übersetzung in Wahrscheinlichkeiten für eine konkrete\nAusgangslage. Ohne diese Übersetzung bleibt das Ergebnis für die meisten Leser\nunzugänglich.\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt der logistischen Regression |\n|---|---|\n| [Multiple lineare Regression](multiple-lineare-regression.qmd) | Zielgrösse metrisch |\n| [Chi-Quadrat-Test](../tests/chi-quadrat-tests.qmd) | nur zwei kategoriale Merkmale, keine weiteren Einflussgrössen |\n| [Klassifikationsgüte](klassifikationsguete.qmd) | die Bewertung der Vorhersagen steht im Vordergrund |\n| [Cox-Modell](../ueberlebenszeit/cox-modell.qmd) | es interessiert, **wann** das Ereignis eintritt, und es gibt zensierte Fälle |\n| Poisson-Regression | die Zielgrösse ist eine Anzahl statt ja oder nein |\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Ausfall aus Laufzeit und Wartung\n\n#### Frage und Datenlage\n\nVon 200 Anlagen ist bekannt, ob sie im Beobachtungsjahr ausgefallen sind, wie\nviele Jahre sie schon laufen und ob sie regelmässig gewartet werden. Die Frage\nlautet: Wie wirken Laufzeit und Wartungsart auf die Ausfallwahrscheinlichkeit?\n\n#### Datenüberblick\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(anlagen$wartung, anlagen$ausfall)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                \n                  0  1\n  regelmaessig   64 36\n  unregelmaessig 40 60\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(anzahl = nrow(anlagen), ausfaelle = sum(anlagen$ausfall),\n        anteil = mean(anlagen$ausfall)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   anzahl ausfaelle    anteil \n   200.00     96.00      0.48 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(pd.crosstab(anlagen[\"wartung\"], anlagen[\"ausfall\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nausfall          0   1\nwartung               \nregelmaessig    64  36\nunregelmaessig  40  60\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"n =\", len(anlagen), \" Ausfälle =\", int(anlagen[\"ausfall\"].sum()),\n      \" Anteil =\", round(anlagen[\"ausfall\"].mean(), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 200  Ausfälle = 96  Anteil = 0.48\n```\n\n\n:::\n:::\n\n\n:::\n\n96 der 200 Anlagen sind ausgefallen, also 48 Prozent. Bei regelmässiger Wartung\nsind es 36 von 100, bei unregelmässiger 60 von 100. Damit ist die Faustregel\n\"mindestens zehn Ereignisse je Koeffizient\" mit grossem Abstand erfüllt: Zwei\nKoeffizienten stehen 96 Ereignissen gegenüber.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodell <- glm(ausfall ~ laufzeit + wartung, family = binomial, data = anlagen)\nsummary(modell)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = ausfall ~ laufzeit + wartung, family = binomial, \n    data = anlagen)\n\nCoefficients:\n                      Estimate Std. Error z value Pr(>|z|)    \n(Intercept)           -3.32241    0.53584  -6.200 5.63e-10 ***\nlaufzeit               0.42304    0.07094   5.963 2.48e-09 ***\nwartungunregelmaessig  1.32944    0.34534   3.850 0.000118 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 276.94  on 199  degrees of freedom\nResidual deviance: 215.60  on 197  degrees of freedom\nAIC: 221.6\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\n# Odds Ratios mit Wald-Intervall\nround(exp(cbind(OR = coef(modell), confint.default(modell))), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                          OR  2.5 % 97.5 %\n(Intercept)           0.0361 0.0126 0.1031\nlaufzeit              1.5266 1.3284 1.7543\nwartungunregelmaessig 3.7789 1.9205 7.4358\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmodell = smf.logit(\"ausfall ~ laufzeit + C(wartung)\", data=anlagen).fit(disp=0)\nprint(modell.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                           Logit Regression Results                           \n==============================================================================\nDep. Variable:                ausfall   No. Observations:                  200\nModel:                          Logit   Df Residuals:                      197\nMethod:                           MLE   Df Model:                            2\nDate:                Fri, 11 Sep 2026   Pseudo R-squ.:                  0.2215\nTime:                        06:16:54   Log-Likelihood:                -107.80\nconverged:                       True   LL-Null:                       -138.47\nCovariance Type:            nonrobust   LLR p-value:                 4.786e-14\n================================================================================================\n                                   coef    std err          z      P>|z|      [0.025      0.975]\n------------------------------------------------------------------------------------------------\nIntercept                       -3.3224      0.536     -6.200      0.000      -4.373      -2.272\nC(wartung)[T.unregelmaessig]     1.3294      0.345      3.850      0.000       0.653       2.006\nlaufzeit                         0.4230      0.071      5.963      0.000       0.284       0.562\n================================================================================================\n```\n\n\n:::\n\n```{.python .cell-code}\nodds = pd.DataFrame({\n    \"OR\": np.exp(modell.params),\n    \"unten\": np.exp(modell.conf_int()[0]),\n    \"oben\": np.exp(modell.conf_int()[1]),\n})\nprint(odds.round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                  OR   unten    oben\nIntercept                     0.0361  0.0126  0.1031\nC(wartung)[T.unregelmaessig]  3.7789  1.9205  7.4358\nlaufzeit                      1.5266  1.3284  1.7543\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Devianzen:\", round(-2 * modell.llnull, 3), \"und\",\n      round(-2 * modell.llf, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDevianzen: 276.939 und 215.598\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| `(Intercept)` Estimate | -3.3224 | Logit bei Laufzeit null und regelmässiger Wartung | Auf der Logit-Skala nicht deutbar. Exponenziert ergibt sich eine Chance von 0.036, also rund 1 zu 28. Eine Laufzeit von null kommt in den Daten nicht vor, der Wert ist also ohnehin eine Extrapolation. |\n| `laufzeit` Estimate | 0.4230 | Änderung des Logits je Betriebsjahr | Positiv, also steigt die Ausfallwahrscheinlichkeit mit der Laufzeit. Die Grösse ist auf dieser Skala nicht greifbar. |\n| `laufzeit` Std. Error | 0.0709 | | |\n| `laufzeit` z value | 5.963 | Estimate durch Std. Error | Heisst z und nicht t, weil die Verteilung nur näherungsweise normal ist. |\n| `laufzeit` Pr(>&#124;z&#124;) | < 0.001 | | |\n| `wartungunregelmaessig` Estimate | 1.3294 | Änderung des Logits gegenüber regelmässiger Wartung | Die Referenzstufe `regelmaessig` erscheint nicht in der Ausgabe; sie ist alphabetisch die erste. |\n| Odds Ratio `laufzeit` | 1.5266 | Faktor je Betriebsjahr | Die zentrale Zahl: Jedes zusätzliche Betriebsjahr multipliziert die **Chance** eines Ausfalls mit 1.53, erhöht sie also um 53 Prozent. |\n| Intervall `laufzeit` | 1.3284 bis 1.7543 | | Es enthält die 1 nicht, der Effekt ist also nachgewiesen. Die 1 spielt bei Odds Ratios die Rolle, die bei linearen Koeffizienten die 0 hat. |\n| Odds Ratio `wartung` | 3.7789 | Faktor für unregelmässige Wartung | Unregelmässig gewartete Anlagen haben eine 3.78 mal so hohe Ausfallchance wie regelmässig gewartete gleicher Laufzeit. |\n| Intervall `wartung` | 1.9205 bis 7.4358 | | Deutlich breiter als beim Laufzeiteffekt. Bei Odds Ratios ist das Intervall immer unsymmetrisch, weil auf der Logit-Skala symmetrisch gerechnet und dann exponenziert wird. |\n| `Null deviance` | 276.94 auf 199 df | Modell ohne Prädiktoren | |\n| `Residual deviance` | 215.60 auf 197 df | angepasstes Modell | Die Differenz von 61.34 ist der Gewinn durch die beiden Prädiktoren. Sie wird gegen eine Chi-Quadrat-Verteilung mit 2 Freiheitsgraden geprüft: p = 4.8e-14. |\n| `AIC` | 221.60 | für Modellvergleiche | Residual deviance plus zweimal die Anzahl Parameter. |\n| `Pseudo R-squ.` (nur Python) | 0.2215 | McFadden | **Nicht** wie R² zu lesen. Werte zwischen 0.2 und 0.4 gelten bereits als gute Anpassung. |\n\n#### Interpretation und Ergebnissatz\n\nBeide Effekte sind nachgewiesen, und beide lassen sich als Faktor auf die\nChance beziffern. Was daraus für die Praxis folgt, zeigt aber erst die\nÜbersetzung in Wahrscheinlichkeiten, und die steht in Beispiel 2.\n\n> Von 200 Anlagen fielen 96 aus (48 Prozent). Laufzeit und Wartungsart hängen\n> beide mit der Ausfallwahrscheinlichkeit zusammen (Likelihood-Quotienten-Test\n> über beide Prädiktoren: Devianzdifferenz 61.34 bei 2 Freiheitsgraden,\n> p < 0.001). Je Betriebsjahr steigt die Ausfallchance um den Faktor 1.53\n> (95-Prozent-Konfidenzintervall 1.33 bis 1.75, p < 0.001). Unregelmässig\n> gewartete Anlagen haben bei gleicher Laufzeit eine 3.78 mal so hohe\n> Ausfallchance (1.92 bis 7.44, p < 0.001). McFaddens Pseudo-R² beträgt 0.22.\n\n### Beispiel 2: Dasselbe Odds Ratio, verschiedene Wahrscheinlichkeiten\n\n#### Frage und Datenlage\n\nDas Odds Ratio für unregelmässige Wartung beträgt 3.78, unabhängig von der\nLaufzeit. Die Frage lautet: Um wie viele Prozentpunkte steigt dadurch die\nAusfallwahrscheinlichkeit?\n\nDie Antwort ist: Das kommt darauf an. Und genau das ist der Punkt.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfaelle <- expand.grid(\n  laufzeit = c(3, 6, 9),\n  wartung = c(\"regelmaessig\", \"unregelmaessig\")\n)\nfaelle$p <- round(predict(modell, newdata = faelle, type = \"response\"), 4)\n\nbreit <- reshape(faelle, idvar = \"laufzeit\", timevar = \"wartung\",\n                 direction = \"wide\")\nnames(breit) <- c(\"laufzeit\", \"p_regelmaessig\", \"p_unregelmaessig\")\nbreit$differenz_punkte <- round(\n  100 * (breit$p_unregelmaessig - breit$p_regelmaessig), 1)\nbreit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  laufzeit p_regelmaessig p_unregelmaessig differenz_punkte\n1        3         0.1137           0.3265             21.3\n2        6         0.3134           0.6330             32.0\n3        9         0.6189           0.8599             24.1\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfaelle = pd.DataFrame([(lz, w) for w in (\"regelmaessig\", \"unregelmaessig\")\n                       for lz in (3, 6, 9)],\n                      columns=[\"laufzeit\", \"wartung\"])\nfaelle[\"p\"] = modell.predict(faelle).round(4)\n\nbreit = faelle.pivot(index=\"laufzeit\", columns=\"wartung\", values=\"p\")\nbreit[\"differenz_punkte\"] = (100 * (breit[\"unregelmaessig\"]\n                                    - breit[\"regelmaessig\"])).round(1)\nprint(breit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwartung   regelmaessig  unregelmaessig  differenz_punkte\nlaufzeit                                                \n3               0.1137          0.3265              21.3\n6               0.3134          0.6330              32.0\n9               0.6189          0.8599              24.1\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Laufzeit | p bei regelmässiger Wartung | p bei unregelmässiger | Differenz in Prozentpunkten |\n|---|---|---|---|\n| 3 Jahre | 0.114 | 0.327 | +21.3 |\n| 6 Jahre | 0.313 | 0.633 | +32.0 |\n| 9 Jahre | 0.619 | 0.860 | +24.1 |\n\nIn allen drei Zeilen ist das Odds Ratio exakt 3.78. Nachrechnen für die erste\nZeile: Die Chance steigt von 0.114/0.886 = 0.129 auf 0.327/0.673 = 0.486, und\n0.486 geteilt durch 0.129 ergibt 3.78.\n\nDie Änderung in Prozentpunkten schwankt dagegen zwischen 21 und 32. Sie ist am\ngrössten in der Mitte, wo die Ausgangswahrscheinlichkeit nahe 50 Prozent liegt,\nund wird an beiden Rändern kleiner. Das ist keine Eigenheit dieser Daten,\nsondern folgt aus der Form der logistischen Kurve: Sie ist in der Mitte am\nsteilsten und flacht zu beiden Seiten ab.\n\n::: {.note-box}\n**Warum das für den Bericht entscheidend ist.** Der Satz \"unregelmässige\nWartung verdreifacht das Ausfallrisiko\" ist bei einer Ausgangswahrscheinlichkeit\nvon 62 Prozent schlicht unmöglich: Das Dreifache wäre über 100 Prozent. Er\nverwechselt Chance mit Wahrscheinlichkeit.\n\nKorrekt ist entweder \"die Ausfallchance ist 3.78 mal so hoch\" oder eine Aussage\nin Prozentpunkten **für eine genannte Ausgangslage**: \"Bei einer sechs Jahre\nalten Anlage steigt die Ausfallwahrscheinlichkeit von 31 auf 63 Prozent.\"\n:::\n\n#### Interpretation und Ergebnissatz\n\nFür einen Bericht gehören beide Angaben dazu: das Odds Ratio, weil es vom\nAusgangspunkt unabhängig und damit übertragbar ist, und mindestens eine\nÜbersetzung in Wahrscheinlichkeiten für eine typische Ausgangslage, weil erst\nsie greifbar wird.\n\n> Unregelmässige Wartung erhöht die Ausfallchance um den Faktor 3.78 (95-Prozent-\n> Konfidenzintervall 1.92 bis 7.44). Für eine sechs Jahre alte Anlage entspricht\n> das einer Ausfallwahrscheinlichkeit von 63 statt 31 Prozent, also 32\n> Prozentpunkten mehr; für eine drei Jahre alte Anlage 33 statt 11 Prozent, also\n> 21 Prozentpunkten mehr.\n\n### Beispiel 3: Vollständige Trennung\n\n#### Frage und Datenlage\n\nSechzehn Bauteile, geprüft wird der Zusammenhang zwischen Prüftemperatur und\nAusfall. In diesen Daten fällt **jedes** Bauteil ab 82 Grad aus und keines\ndarunter. Der Prädiktor trennt die beiden Gruppen perfekt.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbauteile <- data.frame(\n  temperatur = c(62, 65, 68, 70, 72, 74, 76, 78, 82, 84, 86, 88, 90, 92, 95, 98),\n  ausfall    = c(0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1)\n)\n\ngetrennt <- glm(ausfall ~ temperatur, family = binomial, data = bauteile)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: glm.fit: algorithm did not converge\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: glm.fit: fitted probabilities numerically 0 or 1 occurred\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(getrennt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = ausfall ~ temperatur, family = binomial, data = bauteile)\n\nCoefficients:\n              Estimate Std. Error z value Pr(>|z|)\n(Intercept)    -878.13 1003759.01  -0.001    0.999\ntemperatur       10.98   12543.07   0.001    0.999\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 2.2181e+01  on 15  degrees of freedom\nResidual deviance: 1.1691e-09  on 14  degrees of freedom\nAIC: 4\n\nNumber of Fisher Scoring iterations: 25\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport warnings\n\nbauteile = pd.DataFrame({\n    \"temperatur\": [62, 65, 68, 70, 72, 74, 76, 78,\n                   82, 84, 86, 88, 90, 92, 95, 98],\n    \"ausfall\": [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1],\n})\n\nwith warnings.catch_warnings():\n    warnings.simplefilter(\"ignore\")\n    getrennt = smf.logit(\"ausfall ~ temperatur\", data=bauteile).fit(disp=0)\nprint(getrennt.summary().tables[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n==============================================================================\n                 coef    std err          z      P>|z|      [0.025      0.975]\n------------------------------------------------------------------------------\nIntercept   -655.4634   1.02e+05     -0.006      0.995   -2.01e+05       2e+05\ntemperatur     8.1936   1279.264      0.006      0.995   -2499.119    2515.506\n==============================================================================\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Was zu sehen ist | Wie es zu lesen ist |\n|---|---|---|\n| `Estimate` für `temperatur` | ein sehr grosser Wert | Er wächst mit jeder Iteration weiter; das Verfahren strebt gegen unendlich. |\n| `Std. Error` | ein extrem grosser Wert, oft in der Grössenordnung von Tausenden | Das eigentliche Warnzeichen. Ein Standardfehler, der um Grössenordnungen über dem Schätzwert liegt, ist keine Unsicherheit, sondern ein Rechenabbruch. |\n| `Pr(>&#124;z&#124;)` | nahe 1 | Absurd: Der Prädiktor sagt die Zielgrösse perfekt vorher und ist trotzdem \"nicht signifikant\". |\n| `Residual deviance` | praktisch null | Das Modell passt perfekt, weil es die Daten auswendig lernt. |\n| Warnung in R | `fitted probabilities numerically 0 or 1 occurred` | Der eindeutige Hinweis. |\n| `Number of Fisher Scoring iterations` | 25, das Maximum | Das Verfahren ist nicht konvergiert, sondern abgebrochen worden. |\n\n::: {.note-box}\n**Die konkreten Zahlen sind hier bedeutungslos**, und zwar buchstäblich: Sie\nhängen davon ab, wann das Optimierungsverfahren abbricht, und unterscheiden\nsich deshalb zwischen R und Python und sogar zwischen Versionen desselben\nPakets. Genau daran erkennt man das Problem. Bei einer normalen Schätzung\nliefern beide Sprachen dieselben Werte, wie Beispiel 1 zeigt.\n:::\n\n#### Interpretation und Ergebnissatz\n\nEs gibt keine Maximum-Likelihood-Schätzung. Jeder noch so grosse Koeffizient\nwird durch einen grösseren verbessert, weil sich die vorhergesagten\nWahrscheinlichkeiten dadurch weiter an 0 und 1 annähern. Das Verfahren\nkonvergiert nicht, es bricht ab.\n\nWas zu tun ist:\n\n| Vorgehen | Wann es passt |\n|---|---|\n| Firth-Korrektur (in R `logistf`, in Python `statsmodels` mit Penalisierung) | der Standardweg; sie liefert endliche Schätzwerte und brauchbare Intervalle |\n| Den trennenden Prädiktor weglassen | wenn er inhaltlich verzichtbar ist |\n| Kategorien zusammenfassen | wenn die Trennung von einer dünn besetzten Stufe kommt |\n| Mehr Daten erheben | Trennung tritt fast nur bei kleinen Stichproben auf |\n\nNicht zulässig ist, das Ergebnis als \"perfektes Modell\" zu berichten. Das\nModell hat nichts gelernt, es hat die sechzehn Fälle auswendig gelernt.\n\n> Die Prüftemperatur trennt ausgefallene und intakte Bauteile in diesen Daten\n> vollständig (alle Ausfälle ab 82 Grad, kein Ausfall darunter). Eine\n> logistische Regression liefert deshalb keine gültige Schätzung; berichtet wird\n> stattdessen die Trenngrenze mit dem Hinweis, dass n = 16 für eine Schätzung\n> nicht ausreicht.\n\n### Beispiel 4: Von Wahrscheinlichkeiten zu Entscheidungen\n\n#### Frage und Datenlage\n\nDas Modell aus Beispiel 1 liefert für jede Anlage eine Wahrscheinlichkeit. Für\neine Entscheidung, etwa \"vorsorglich warten oder nicht\", braucht es eine\nSchwelle. Die Frage lautet: Welche?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_vorher <- predict(modell, type = \"response\")\n\nfor (schwelle in c(0.3, 0.5, 0.7)) {\n  vorhersage <- as.integer(p_vorher > schwelle)\n  tp <- sum(vorhersage == 1 & anlagen$ausfall == 1)\n  fp <- sum(vorhersage == 1 & anlagen$ausfall == 0)\n  fn <- sum(vorhersage == 0 & anlagen$ausfall == 1)\n  tn <- sum(vorhersage == 0 & anlagen$ausfall == 0)\n  cat(sprintf(\n    \"Schwelle %.1f: TP=%3d FP=%3d FN=%3d TN=%3d  Sensitivität=%.3f  Spezifität=%.3f  Genauigkeit=%.3f\\n\",\n    schwelle, tp, fp, fn, tn, tp / (tp + fn), tn / (tn + fp), (tp + tn) / nrow(anlagen)))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSchwelle 0.3: TP= 85 FP= 53 FN= 11 TN= 51  Sensitivität=0.885  Spezifität=0.490  Genauigkeit=0.680\nSchwelle 0.5: TP= 67 FP= 26 FN= 29 TN= 78  Sensitivität=0.698  Spezifität=0.750  Genauigkeit=0.725\nSchwelle 0.7: TP= 40 FP=  9 FN= 56 TN= 95  Sensitivität=0.417  Spezifität=0.913  Genauigkeit=0.675\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\np_vorher = modell.predict(anlagen)\ntatsaechlich = anlagen[\"ausfall\"].to_numpy()\n\nfor schwelle in (0.3, 0.5, 0.7):\n    vorhersage = (p_vorher > schwelle).astype(int)\n    tp = int(((vorhersage == 1) & (tatsaechlich == 1)).sum())\n    fp = int(((vorhersage == 1) & (tatsaechlich == 0)).sum())\n    fn = int(((vorhersage == 0) & (tatsaechlich == 1)).sum())\n    tn = int(((vorhersage == 0) & (tatsaechlich == 0)).sum())\n    print(f\"Schwelle {schwelle}: TP={tp:3d} FP={fp:3d} FN={fn:3d} TN={tn:3d}\"\n          f\"  Sensitivität={tp/(tp+fn):.3f}\"\n          f\"  Spezifität={tn/(tn+fp):.3f}\"\n          f\"  Genauigkeit={(tp+tn)/len(anlagen):.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSchwelle 0.3: TP= 85 FP= 53 FN= 11 TN= 51  Sensitivität=0.885  Spezifität=0.490  Genauigkeit=0.680\nSchwelle 0.5: TP= 67 FP= 26 FN= 29 TN= 78  Sensitivität=0.698  Spezifität=0.750  Genauigkeit=0.725\nSchwelle 0.7: TP= 40 FP=  9 FN= 56 TN= 95  Sensitivität=0.417  Spezifität=0.913  Genauigkeit=0.675\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Schwelle | Richtig erkannte Ausfälle | Fehlalarme | Übersehene Ausfälle | Sensitivität | Spezifität | Genauigkeit |\n|---|---|---|---|---|---|---|\n| 0.3 | 85 | 53 | 11 | 0.885 | 0.490 | 0.680 |\n| 0.5 | 67 | 26 | 29 | 0.698 | 0.750 | 0.725 |\n| 0.7 | 40 | 9 | 56 | 0.417 | 0.913 | 0.675 |\n\nDasselbe Modell, dieselben Wahrscheinlichkeiten, drei völlig verschiedene\nEntscheidungsverhalten. Bei einer Schwelle von 0.3 werden 85 der 96 Ausfälle\nvorhergesagt, dafür 53 Anlagen unnötig gewartet. Bei 0.7 sinken die Fehlalarme\nauf 9, dafür bleiben 56 Ausfälle unentdeckt.\n\nBemerkenswert ist die Spalte Genauigkeit: Sie ist bei 0.5 am höchsten und\nunterscheidet sich zwischen 0.3 und 0.7 kaum. Sie ist damit gerade **nicht** das\nKriterium, an dem sich die Wahl entscheidet.\n\n#### Interpretation und Ergebnissatz\n\nDie Schwelle ergibt sich aus den Kosten der beiden Fehlerarten, nicht aus der\nStatistik. Kostet ein übersehener Ausfall ein Vielfaches einer unnötigen\nWartung, gehört die Schwelle nach unten. Ist die Wartung teuer und der Ausfall\nverkraftbar, nach oben.\n\nDie Voreinstellung 0.5 unterstellt, dass beide Fehler gleich teuer sind. Das ist\nselten der Fall und noch seltener geprüft.\n\nZwei Warnungen zum Schluss. Erstens sind diese Kennzahlen an denselben Daten\ngemessen, mit denen das Modell geschätzt wurde; sie fallen deshalb zu gut aus.\nBelastbare Werte braucht getrennte Daten oder Kreuzvalidierung. Zweitens ist die\nTrennschärfe des Modells von der Schwelle unabhängig und wird mit der\nROC-Kurve und dem AUC beurteilt. Beides steht auf der Seite\n[Klassifikationsgüte](klassifikationsguete.qmd).\n\n> Bei der üblichen Schwelle von 0.5 erkennt das Modell 67 der 96 Ausfälle\n> (Sensitivität 0.70) und stuft 26 der 104 intakten Anlagen falsch ein\n> (Spezifität 0.75). Eine Senkung der Schwelle auf 0.3 erhöht die Sensitivität\n> auf 0.89, verdoppelt aber die Fehlalarme. Die Wahl der Schwelle richtet sich\n> nach dem Kostenverhältnis der beiden Fehlerarten. Alle Kennzahlen sind an den\n> Schätzdaten gemessen und deshalb optimistisch.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEin Odds Ratio beträgt 3.78. Was folgt für die Wahrscheinlichkeit?\n\n- [x] Das kommt auf die Ausgangswahrscheinlichkeit an ~ Richtig. Das Odds Ratio\n      wirkt auf die Chance, nicht auf die Wahrscheinlichkeit. Bei einer\n      Ausgangswahrscheinlichkeit von 11 Prozent führt es zu 33 Prozent, bei 31\n      Prozent zu 63, bei 62 Prozent zu 86. Die Änderung in Prozentpunkten ist in\n      der Mitte am grössten.\n- [ ] Die Wahrscheinlichkeit ist 3.78 mal so hoch ~ Das wäre ein\n      Risikoverhältnis, und bei einer Ausgangswahrscheinlichkeit über 27 Prozent\n      käme dabei ein Wert über 1 heraus.\n- [ ] Die Wahrscheinlichkeit steigt um 3.78 Prozentpunkte ~ Das Odds Ratio ist\n      ein Faktor, keine Differenz.\n:::\n\n::: {.quiz}\nEin Koeffizient hat einen Standardfehler von 1279 bei einem Schätzwert von 8.2,\nund R warnt `fitted probabilities numerically 0 or 1 occurred`. Was liegt vor?\n\n- [x] Vollständige Trennung: es existiert keine Schätzung ~ Richtig. Ein\n      Prädiktor trennt die Gruppen perfekt, das Optimierungsverfahren strebt\n      gegen unendlich und bricht ab. Die ausgegebenen Zahlen hängen nur davon\n      ab, wann es abbricht.\n- [ ] Ein besonders starker Effekt ~ Er sieht so aus und ist keiner. Ein\n      Standardfehler, der um Grössenordnungen über dem Schätzwert liegt, ist\n      keine Unsicherheit, sondern ein Rechenabbruch.\n- [ ] Multikollinearität ~ Sie erhöht Standardfehler ebenfalls, aber nicht um\n      diese Grössenordnung und ohne diese Warnung.\n:::\n\n::: {.quiz}\nEin Modell erreicht ein McFadden-Pseudo-R² von 0.22. Wie ist das einzuordnen?\n\n- [x] Eine gute Anpassung; Werte zwischen 0.2 und 0.4 gelten als solche ~\n      Richtig. Pseudo-R² ist anders konstruiert als R² und erreicht selbst bei\n      sehr guten Modellen selten hohe Werte. Wer es wie ein Bestimmtheitsmass\n      liest, hält jedes logistische Modell für schlecht.\n- [ ] Schlecht, nur 22 Prozent der Streuung sind erklärt ~ Genau diese\n      Übertragung ist der Fehler; Pseudo-R² misst keinen Streuungsanteil.\n- [ ] Nicht beurteilbar ohne Vergleichsmodell ~ Für einen Modellvergleich ist\n      ein Vergleichsmodell nötig, für die Einordnung dieser Zahl nicht.\n:::\n\n::: {.quiz}\nWarum ist die Schwelle 0.5 nicht automatisch die richtige?\n\n- [x] Weil sie unterstellt, dass beide Fehlerarten gleich teuer sind ~ Richtig.\n      Ein übersehener Ausfall und eine unnötige Wartung kosten selten dasselbe.\n      Die Schwelle ist eine betriebswirtschaftliche Entscheidung, keine\n      statistische.\n- [ ] Weil sie die Genauigkeit nicht maximiert ~ In diesem Beispiel tut sie das\n      sogar. Genauigkeit ist nur nicht das entscheidende Kriterium.\n- [ ] Weil sie bei unausgeglichenen Klassen mathematisch unzulässig ist ~\n      Unzulässig ist sie nie, nur oft unpassend.\n:::\n\n## Verlinkte Ressourcen\n\n- [An Introduction to Statistical Learning, Kapitel 4](https://www.statlearning.com/)\n- [R-Dokumentation zu `glm`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/glm.html)\n- [statsmodels: Logit](https://www.statsmodels.org/stable/generated/statsmodels.discrete.discrete_model.Logit.html)\n",
    "supporting": [
      "logistische-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}