{
  "hash": "623122866cd96c114386ae314ffddcd2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Chi-Quadrat-Tests\"\ndescription: \"Unabhängigkeit und Anpassung bei kategorialen Daten prüfen.\"\ncategories: [\"Hypothesentests\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"ESDS\"]\nseitentyp: methode\nstand: fertig\norder: 50\n---\n\n\n\n\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Passen beobachtete Häufigkeiten zu einer erwarteten Verteilung, oder hängen zwei kategoriale Merkmale zusammen? |\n| Zielvariable | kategorial (nominal oder ordinal, die Ordnung wird nicht genutzt) |\n| Gruppen | eine Verteilung gegen eine Vorgabe, oder eine Kreuztabelle aus zwei Merkmalen |\n| Was die Methode liefert | Chi-Quadrat-Statistik, Freiheitsgrade, p-Wert, erwartete Häufigkeiten und standardisierte Residuen |\n| R-Funktion | `chisq.test(x, p = anteile)` für die Anpassung, `chisq.test(tabelle)` für die Unabhängigkeit |\n| Python-Funktion | `stats.chisquare()` und `stats.chi2_contingency()` |\n| Verwandte Methoden | [t-Test für zwei Stichproben](t-test-zwei-stichproben.qmd), [Korrelationstests](korrelationstests.qmd), [logistische Regression](../regression/logistische-regression.qmd) |\n\n## Wann diese Methode, wann nicht\n\nTypische Fragestellungen: Verteilen sich Ausschussgründe wie behauptet, hängt\ndie Fehlerart von der Schicht ab, unterscheidet sich die Zustimmung zwischen\nStandorten. Gemeinsam ist ihnen, dass nur Häufigkeiten vorliegen und es nichts\nzu mitteln gibt.\n\nZwei Varianten mit derselben Rechenidee: Beim Anpassungstest kommt die erwartete\nVerteilung von aussen, beim Unabhängigkeitstest aus den Randsummen der Tabelle\nselbst.\n\n| Situation | Stattdessen |\n|---|---|\n| Metrische Zielgrösse | [t-Test](t-test-zwei-stichproben.qmd) oder [Varianzanalyse](anova.qmd) |\n| Erwartete Häufigkeiten unter fünf | exakter Test nach Fisher |\n| Gepaarte binäre Daten, etwa vorher und nachher am selben Objekt | McNemar-Test |\n| Beide Merkmale ordinal, Richtung interessiert | [Rangkorrelation](korrelationstests.qmd) |\n| Mehrere Einflussgrössen auf ein binäres Merkmal | [logistische Regression](../regression/logistische-regression.qmd) |\n| Stärke des Zusammenhangs statt Nachweis | Cramérs V als Effektstärke |\n\n## Grundidee und Modell\n\nAus der Nullhypothese werden erwartete Häufigkeiten abgeleitet, und dann wird\ngemessen, wie weit die beobachteten davon abweichen.\n\n### Die Teststatistik\n\n$$\\chi^2 = \\sum_i \\frac{(B_i - E_i)^2}{E_i}$$\n\nDrei Bestandteile, jeder mit einem Grund. Die Differenz misst die Abweichung.\nDas Quadrat sorgt dafür, dass sich Abweichungen nach oben und unten nicht\naufheben. Die Division durch die erwartete Häufigkeit setzt die Abweichung ins\nVerhältnis zur Grösse der Zelle.\n\nDer letzte Punkt ist der entscheidende und lässt sich zeigen:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# zehn Faelle Abweichung, einmal bei kleiner, einmal bei grosser Erwartung\ndata.frame(\n  erwartet   = c(20, 1000),\n  beobachtet = c(30, 1010),\n  beitrag    = round((c(30, 1010) - c(20, 1000))^2 / c(20, 1000), 3)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  erwartet beobachtet beitrag\n1       20         30     5.0\n2     1000       1010     0.1\n```\n\n\n:::\n:::\n\n\nDieselben zehn Fälle Abweichung wiegen bei zwanzig erwarteten Fällen fünfzig\nMal so schwer wie bei tausend. Das entspricht der Anschauung: Zehn statt zwanzig\nFällen ist auffällig, 1010 statt 1000 nicht.\n\nFür den Unabhängigkeitstest ergeben sich die erwarteten Häufigkeiten je Zelle\naus den Randsummen:\n\n$$E_{ij} = \\frac{\\text{Zeilensumme}_i \\cdot \\text{Spaltensumme}_j}{n}$$\n\nDas ist genau die Regel aus der\n[bedingten Wahrscheinlichkeit](../wahrscheinlichkeit/bedingte-wahrscheinlichkeit-bayes.qmd),\nnach der sich bei Unabhängigkeit die Wahrscheinlichkeiten multiplizieren.\n\nDie Freiheitsgrade zählen, wie viel an der Tabelle bei festen Randsummen noch\nvariieren kann: beim Anpassungstest Kategorien minus eins, beim\nUnabhängigkeitstest das Produkt aus um eins verminderten Zeilen- und\nSpaltenzahlen. Jeder aus den Daten geschätzte Parameter kostet einen weiteren\nFreiheitsgrad.\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung | Vorgehen |\n|---|---|---|---|---|\n| Unabhängige Beobachtungen | Jede Beobachtung zählt in genau eine Zelle, niemand wird doppelt gezählt | Erhebungsdesign, Summe der Tabelle gegen n prüfen | p-Wert wertlos | Design klären, bei gepaarten Daten McNemar |\n| Absolute Häufigkeiten | Gezählt wird, nicht gemittelt oder prozentuiert | Tabelleninhalt prüfen | Der Test rechnet mit falschem n und liefert beliebige Ergebnisse | Rohzahlen einsetzen |\n| Erwartete Häufigkeiten mindestens fünf | Die Chi-Quadrat-Verteilung ist eine Näherung | `chisq.test(...)$expected` ansehen | Näherung unzuverlässig, in beide Richtungen | Kategorien zusammenfassen oder Fisher-Test |\n| Kategorien schliessen sich aus und sind vollständig | Jede Beobachtung passt in genau eine Zelle | Kategoriendefinition prüfen | Zellen sind nicht vergleichbar | Kategorien neu bilden |\n\nDie erwarteten Häufigkeiten sind die wichtigste Nebenausgabe des Tests. Sie\nentscheiden erstens, ob die Näherung überhaupt tragfähig ist, und sind zweitens\ndie Grundlage jeder inhaltlichen Deutung: Erst der Vergleich von beobachtet und\nerwartet sagt, in welche Richtung eine Zelle abweicht. Sie werden deshalb immer\nmitausgegeben und gehören in den Bericht.\n\n## Output lesen\n\nR, `chisq.test()`:\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| Testname | `Chi-squared test for given probabilities` oder `Pearson's Chi-squared test` | zeigt an, welche Variante gerechnet wurde |\n| `X-squared` | Summe der normierten quadrierten Abweichungen | hat ohne Freiheitsgrade keine Bedeutung |\n| `df` | Freiheitsgrade | Kategorien minus eins, oder Produkt der verminderten Dimensionen |\n| `p-value` | Wahrscheinlichkeit dieser oder grösserer Abweichung bei gültiger Nullhypothese | sagt nicht, wo die Abweichung sitzt |\n| `$expected` | erwartete Häufigkeiten | die Prüfgrösse für die Faustregel und die Grundlage der Deutung |\n| `$stdres` | standardisierte Residuen je Zelle | Beträge über etwa 2 markieren auffällige Zellen |\n| Warnmeldung | `Chi-squared approximation may be incorrect` | ernst nehmen: mindestens eine erwartete Häufigkeit ist zu klein |\n| `correct = TRUE` | Stetigkeitskorrektur bei Vierfeldertafeln | in R Voreinstellung, in Python abschaltbar; erklärt kleine Abweichungen zwischen den Sprachen |\n\nPython:\n\n| Aufruf | Rückgabe | Unterschied zu R |\n|---|---|---|\n| `stats.chisquare(f_obs, f_exp)` | Statistik und p-Wert | erwartete Häufigkeiten müssen selbst berechnet werden, als absolute Zahlen |\n| `stats.chi2_contingency(tab)` | Statistik, p-Wert, Freiheitsgrade, erwartete Häufigkeiten | liefert die Freiheitsgrade ausdrücklich, R nennt sie in der Ausgabe |\n| standardisierte Residuen | nicht enthalten | in R `$stdres`, in Python von Hand oder über `pingouin` |\n| `correction=True` | Stetigkeitskorrektur bei 2x2 | in R heisst der Schalter `correct` |\n\nDer häufigste stille Fehler in beiden Sprachen: `f_exp` beziehungsweise `p` mit\nAnteilen statt mit absoluten Häufigkeiten zu füllen. R normiert Anteile selbst,\nPython erwartet absolute Zahlen; wer das verwechselt, bekommt eine Zahl ohne\nFehlermeldung.\n\n## Interpretationsfallen\n\n- **Ein signifikanter Test sagt nicht, wo die Abweichung sitzt.** Das\n  beantworten die standardisierten Residuen, und ohne sie bleibt das Ergebnis\n  inhaltlich leer.\n- **Signifikanz ist keine Stärke.** Chi-Quadrat wächst mit n. Für die Stärke des\n  Zusammenhangs gibt es Cramérs V, das zwischen null und eins liegt und nicht\n  von n abhängt.\n- **Prozentwerte gehören nicht in den Test.** Gerechnet wird mit absoluten\n  Häufigkeiten; Prozente setzen n implizit auf hundert.\n- **Ein Zusammenhang ist keine Ursache.** Dass Fehlerart und Schicht\n  zusammenhängen, heisst nicht, dass die Schicht die Fehler verursacht; eine\n  dritte Grösse wie das bearbeitete Material kann beides erklären.\n- **Die Ordnung ordinaler Kategorien wird verschenkt.** Der Test behandelt\n  \"gering, mittel, hoch\" wie unsortierte Namen; für gerichtete Fragen ist ein\n  Trendtest oder eine [Rangkorrelation](korrelationstests.qmd) passender.\n- **Gepaarte Daten brauchen McNemar.** Zwei Messungen am selben Objekt in eine\n  Kreuztabelle zu schreiben verletzt die Unabhängigkeit.\n\n## Ergebnis berichten\n\nVorlage für den Ergebnissatz:\n\n> [Merkmal 1] und [Merkmal 2] hängen zusammen, Chi-Quadrat([df], n = [n]) =\n> [Statistik], p = [p], Cramérs V = [V]. Auffällig sind [Zelle] (standardisiertes\n> Residuum [Wert]) und [Zelle] ([Wert]).\n\nGenannt werden Statistik mit Freiheitsgraden und n, p-Wert, eine Effektstärke,\ndie Kreuztabelle mit beobachteten und erwarteten Häufigkeiten sowie die\nauffälligen Zellen. Wurde wegen kleiner Erwartungswerte ein exaktes Verfahren\nverwendet oder wurden Kategorien zusammengefasst, gehört das ebenfalls in den\nBericht.\n\nBeispiel für eine Ergebnistabelle:\n\n| | Kategorie 1 | Kategorie 2 | Kategorie 3 |\n|---|---|---|---|\n| Gruppe A beobachtet (erwartet) | | | |\n| Gruppe B beobachtet (erwartet) | | | |\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt des Chi-Quadrat-Tests |\n|---|---|\n| Exakter Test nach Fisher | erwartete Häufigkeiten unter fünf, kleine Tabellen |\n| McNemar-Test | gepaarte binäre Daten, etwa vorher und nachher am selben Objekt |\n| [Korrelationstests](korrelationstests.qmd) | beide Merkmale ordinal und die Richtung des Zusammenhangs interessiert |\n| [t-Test für zwei Stichproben](t-test-zwei-stichproben.qmd) | die Zielgrösse ist metrisch |\n| [Logistische Regression](../regression/logistische-regression.qmd) | mehrere Einflussgrössen auf ein binäres Merkmal, mit Effektschätzung |\n\n## Beispiele\n\nAlle Beispiele rechnen mit fest eingetragenen Häufigkeiten, damit R und Python\ndieselben Tabellen sehen und jeder Wert im Text nachprüfbar ist.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Unabhängigkeit, und wo die Abweichung sitzt\n\n#### Frage und Datenlage\n\nAn einer Linie werden 140 Ausfälle erfasst, jeder mit seiner Ursache\n(Werkzeugbruch oder Materialfehler) und der Schicht, in der er auftrat. Die\nFrage lautet: Hängen Ausfallursache und Schicht zusammen?\n\n| | Früh | Spät | Nacht | Summe |\n|---|---|---|---|---|\n| Werkzeug | 38 | 22 | 14 | 74 |\n| Material | 12 | 28 | 26 | 66 |\n| **Summe** | 50 | 50 | 40 | 140 |\n\nBeide Merkmale sind kategorial, jeder Ausfall zählt in genau eine Zelle, und die\nSumme der Tabelle ist die Anzahl der Ausfälle. Damit ist der\nUnabhängigkeitstest das passende Verfahren.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nausfaelle <- matrix(c(38, 22, 14,\n                      12, 28, 26),\n                    nrow = 2, byrow = TRUE,\n                    dimnames = list(ursache = c(\"Werkzeug\", \"Material\"),\n                                    schicht = c(\"Früh\", \"Spät\", \"Nacht\")))\n\nergebnis <- chisq.test(ausfaelle)\nergebnis\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  ausfaelle\nX-squared = 17.44, df = 2, p-value = 0.0001633\n```\n\n\n:::\n\n```{.r .cell-code}\nround(ergebnis$expected, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          schicht\nursache     Früh  Spät Nacht\n  Werkzeug 26.43 26.43 21.14\n  Material 23.57 23.57 18.86\n```\n\n\n:::\n\n```{.r .cell-code}\nround(ergebnis$stdres, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          schicht\nursache      Früh   Spät  Nacht\n  Werkzeug  4.089 -1.565 -2.677\n  Material -4.089  1.565  2.677\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nausfaelle = np.array([[38, 22, 14],\n                      [12, 28, 26]])\nzeilen = [\"Werkzeug\", \"Material\"]\nspalten = [\"Früh\", \"Spät\", \"Nacht\"]\n\nstatistik, p_wert, fg, erwartet = stats.chi2_contingency(ausfaelle)\nprint(\"Chi-Quadrat =\", round(statistik, 4), \" df =\", fg,\n      \" p =\", round(p_wert, 6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nChi-Quadrat = 17.4398  df = 2  p = 0.000163\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pd.DataFrame(erwartet.round(2), index=zeilen, columns=spalten))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Früh   Spät  Nacht\nWerkzeug  26.43  26.43  21.14\nMaterial  23.57  23.57  18.86\n```\n\n\n:::\n\n```{.python .cell-code}\n# Standardisierte Residuen: scipy liefert sie nicht, R schon.\nn = ausfaelle.sum()\nzeilenanteil = ausfaelle.sum(axis=1) / n\nspaltenanteil = ausfaelle.sum(axis=0) / n\nnenner = np.sqrt(erwartet * np.outer(1 - zeilenanteil, 1 - spaltenanteil))\nprint(pd.DataFrame(((ausfaelle - erwartet) / nenner).round(3),\n                   index=zeilen, columns=spalten))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Früh   Spät  Nacht\nWerkzeug  4.089 -1.565 -2.677\nMaterial -4.089  1.565  2.677\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| Testname | `Pearson's Chi-squared test` | Unabhängigkeitstest | Bei einer 2x2-Tabelle stünde hier zusätzlich `with Yates' continuity correction`, siehe Beispiel 3. |\n| `X-squared` | 17.440 | Summe der normierten quadrierten Abweichungen über alle sechs Zellen | Für sich genommen ohne Bedeutung; sie hängt an Tabellengrösse und n. |\n| `df` | 2 | Freiheitsgrade | (Zeilen minus 1) mal (Spalten minus 1), also 1 mal 2. Bei festen Randsummen sind nur zwei Zellen frei wählbar, der Rest ergibt sich. |\n| `p-value` | 0.00016 | Wahrscheinlichkeit einer mindestens so grossen Abweichung bei Unabhängigkeit | Die beiden Merkmale hängen zusammen. Wo, sagt diese Zeile nicht. |\n| `$expected` kleinster Wert | 18.86 | kleinste erwartete Häufigkeit | Die Voraussetzung \"mindestens fünf\" ist deutlich erfüllt, die Näherung also tragfähig. Diese Zahl gehört geprüft, bevor der p-Wert gelesen wird. |\n| `$stdres` Werkzeug/Früh | +4.089 | standardisiertes Residuum | Der auffälligste Wert der Tabelle. In der Frühschicht treten deutlich mehr Werkzeugbrüche auf als bei Unabhängigkeit zu erwarten wäre. Beträge über etwa 2 gelten als auffällig. |\n| `$stdres` Werkzeug/Nacht | -2.677 | | In der Nachtschicht deutlich weniger Werkzeugbrüche als erwartet. |\n| `$stdres` Werkzeug/Spät | -1.565 | | Unauffällig. Die Spätschicht trägt wenig zum Befund bei. |\n\n::: {.note-box}\nBei einer Tabelle mit zwei Zeilen sind die Residuen der zweiten Zeile exakt die\nnegierten der ersten: +4.089 und -4.089. Das ist keine Redundanz, sondern folgt\naus den festen Randsummen. Mehr Werkzeugbrüche in der Frühschicht heisst\nzwangsläufig weniger Materialfehler dort.\n:::\n\n#### Wie stark ist der Zusammenhang?\n\nDer p-Wert sagt nur, dass ein Zusammenhang besteht. Für seine Stärke gibt es\nCramérs V, das zwischen 0 und 1 liegt und im Gegensatz zu Chi-Quadrat nicht mit\nn wächst.\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncramers_v <- function(tabelle) {\n  test <- suppressWarnings(chisq.test(tabelle))\n  n <- sum(tabelle)\n  sqrt(as.numeric(test$statistic) / (n * (min(dim(tabelle)) - 1)))\n}\n\nround(cramers_v(ausfaelle), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3529\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndef cramers_v(tabelle):\n    statistik = stats.chi2_contingency(tabelle)[0]\n    n = tabelle.sum()\n    return np.sqrt(statistik / (n * (min(tabelle.shape) - 1)))\n\n\nprint(round(cramers_v(ausfaelle), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.3529\n```\n\n\n:::\n:::\n\n\n:::\n\nCramérs V beträgt 0.353. Als Anhaltspunkte bei einem Freiheitsgrad in der\nkleineren Dimension gelten 0.1 klein, 0.3 mittel, 0.5 gross; der Zusammenhang\nist also mittelstark. Die Formel ist $V = \\sqrt{\\chi^2 / (n \\cdot (k-1))}$, wobei\n$k$ die kleinere der beiden Dimensionen ist.\n\n#### Interpretation und Ergebnissatz\n\nDer Befund ist erst mit den Residuen eine Aussage. \"Ursache und Schicht hängen\nzusammen\" ist inhaltlich leer; \"in der Frühschicht überwiegen Werkzeugbrüche, in\nder Nachtschicht Materialfehler\" ist eine Aussage, mit der sich arbeiten lässt.\n\nWas der Test **nicht** sagt: warum. Denkbar ist, dass in der Frühschicht andere\nAufträge laufen, dass Werkzeuge morgens gewechselt werden oder dass die\nErfassung je Schicht unterschiedlich genau ist. Ein Zusammenhang zweier Merkmale\nlässt offen, ob eines das andere verursacht oder ob ein drittes beide erklärt.\n\n> Ausfallursache und Schicht hängen zusammen, Chi-Quadrat(2, n = 140) = 17.44,\n> p < 0.001, Cramérs V = 0.35. Auffällig sind Werkzeugbrüche in der Frühschicht\n> (standardisiertes Residuum +4.09) und Materialfehler in der Nachtschicht\n> (+2.68); die Spätschicht ist unauffällig. Alle erwarteten Häufigkeiten liegen\n> über 18.\n\n### Beispiel 2: Anpassungstest gegen eine erwartete Verteilung\n\n#### Frage und Datenlage\n\n190 Ausfälle verteilen sich auf die fünf Arbeitstage einer Woche. Die Frage\nlautet: Treten sie gleichmässig über die Woche auf, oder häufen sie sich an\nbestimmten Tagen?\n\n| | Mo | Di | Mi | Do | Fr |\n|---|---|---|---|---|---|\n| beobachtet | 41 | 33 | 29 | 35 | 52 |\n| erwartet | 38 | 38 | 38 | 38 | 38 |\n\nAnders als in Beispiel 1 gibt es nur **ein** Merkmal. Verglichen wird nicht mit\neinem zweiten Merkmal, sondern mit einer von aussen vorgegebenen Verteilung,\nhier der Gleichverteilung über fünf Tage.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwochentage <- c(Mo = 41, Di = 33, Mi = 29, Do = 35, Fr = 52)\n\nanpassung <- chisq.test(wochentage)          # Gleichverteilung ist Voreinstellung\nanpassung\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test for given probabilities\n\ndata:  wochentage\nX-squared = 8.4211, df = 4, p-value = 0.07732\n```\n\n\n:::\n\n```{.r .cell-code}\nround(anpassung$expected, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMo Di Mi Do Fr \n38 38 38 38 38 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(anpassung$residuals, 3)                # Pearson-Residuen\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Mo     Di     Mi     Do     Fr \n 0.487 -0.811 -1.460 -0.487  2.271 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nwochentage = np.array([41, 33, 29, 35, 52])\ntage = [\"Mo\", \"Di\", \"Mi\", \"Do\", \"Fr\"]\nerwartet_gleich = np.full(5, wochentage.sum() / 5)\n\nstatistik, p_wert = stats.chisquare(wochentage, erwartet_gleich)\nprint(\"Chi-Quadrat =\", round(statistik, 4), \" df =\", len(wochentage) - 1,\n      \" p =\", round(p_wert, 6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nChi-Quadrat = 8.4211  df = 4  p = 0.077317\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pd.DataFrame({\n    \"beobachtet\": wochentage,\n    \"erwartet\": erwartet_gleich,\n    \"Beitrag\": ((wochentage - erwartet_gleich) ** 2 / erwartet_gleich).round(3),\n    \"Residuum\": ((wochentage - erwartet_gleich)\n                 / np.sqrt(erwartet_gleich)).round(3),\n}, index=tage))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    beobachtet  erwartet  Beitrag  Residuum\nMo          41      38.0    0.237     0.487\nDi          33      38.0    0.658    -0.811\nMi          29      38.0    2.132    -1.460\nDo          35      38.0    0.237    -0.487\nFr          52      38.0    5.158     2.271\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Testname | `Chi-squared test for given probabilities` | Anpassungstest, nicht Unabhängigkeitstest. Der Name ist die Kontrolle, dass die richtige Variante lief. |\n| `X-squared` | 8.421 | Summe der fünf Beiträge. |\n| `df` | 4 | Kategorien minus eins. Bei fester Gesamtzahl sind nur vier der fünf Häufigkeiten frei. |\n| `p-value` | 0.077 | Knapp über 0.05, also kein Nachweis einer ungleichen Verteilung. |\n| Beitrag Freitag | 5.158 | Die aufschlussreichste Zahl. Der Freitag allein steuert 61 Prozent der gesamten Teststatistik bei; die übrigen vier Tage zusammen nur 3.26. |\n| Residuum Freitag | +2.27 | Am Freitag treten mehr Ausfälle auf als erwartet. |\n| Residuum Mittwoch | -1.46 | Am Mittwoch weniger, aber im unauffälligen Bereich. |\n\n#### Interpretation und Ergebnissatz\n\nHier liegt die Lehre nicht im p-Wert, sondern im Umgang mit einem knappen\nErgebnis. Drei Aussagen sind zu unterscheiden:\n\n| Aussage | Zulässig? |\n|---|---|\n| \"Die Ausfälle verteilen sich gleichmässig über die Woche.\" | Nein. Nicht nachgewiesen ist nicht dasselbe wie gleichverteilt. |\n| \"Es gibt keinen Wochentagseffekt.\" | Nein, aus demselben Grund. |\n| \"Eine ungleiche Verteilung liess sich nicht nachweisen; auffällig ist der Freitag, der 61 Prozent der Teststatistik trägt.\" | Ja. |\n\nDer Freitag darf jetzt **nicht** nachträglich einzeln getestet werden. Wer nach\neinem nicht signifikanten Gesamttest die auffälligste Kategorie herausgreift und\ngegen den Rest prüft, hat sie anhand der Daten ausgewählt und das Testniveau\nverloren. Der saubere Weg ist eine neue Erhebung mit der nun vorab formulierten\nHypothese \"am Freitag treten mehr Ausfälle auf\".\n\n::: {.note-box}\nDie Gleichverteilung ist in `chisq.test()` nur die Voreinstellung. Erwartet man\netwas anderes, etwa weil am Freitag kürzer gearbeitet wird, übergibt man das über\n`p = c(...)`. Wichtig: R erwartet dort **Anteile**, die sich zu 1 summieren,\n`stats.chisquare()` dagegen **absolute** erwartete Häufigkeiten. Das ist der\nhäufigste stille Fehler dieser Funktion, denn beide Sprachen rechnen ohne\nFehlermeldung weiter.\n:::\n\n> Eine Abweichung von der Gleichverteilung über die Wochentage lässt sich nicht\n> nachweisen, Chi-Quadrat(4, n = 190) = 8.42, p = 0.077. Der Freitag trägt mit\n> einem Beitrag von 5.16 den grössten Anteil an der Teststatistik\n> (52 beobachtete gegenüber 38 erwarteten Ausfällen); eine gezielte Prüfung\n> dieser Hypothese erfordert neue Daten.\n\n### Beispiel 3: Zu kleine erwartete Häufigkeiten\n\n#### Frage und Datenlage\n\nZwei Werkzeugtypen, je zehn Einsätze, erfasst wird, ob ein Fehler auftrat.\n\n| | Fehler | in Ordnung | Summe |\n|---|---|---|---|\n| neuer Typ | 9 | 1 | 10 |\n| alter Typ | 4 | 6 | 10 |\n| **Summe** | 13 | 7 | 20 |\n\nZwanzig Beobachtungen in vier Zellen: Hier greift die Faustregel, dass alle\nerwarteten Häufigkeiten mindestens fünf betragen sollen.\n\n#### Voraussetzungen prüfen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwerkzeugtyp <- matrix(c(9, 1,\n                        4, 6),\n                      nrow = 2, byrow = TRUE,\n                      dimnames = list(typ = c(\"neu\", \"alt\"),\n                                      ergebnis = c(\"Fehler\", \"in Ordnung\")))\n\ntest <- chisq.test(werkzeugtyp)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in chisq.test(werkzeugtyp): Chi-squared approximation may be incorrect\n```\n\n\n:::\n\n```{.r .cell-code}\nround(test$expected, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     ergebnis\ntyp   Fehler in Ordnung\n  neu    6.5        3.5\n  alt    6.5        3.5\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nwerkzeugtyp = np.array([[9, 1],\n                        [4, 6]])\n\nerwartet = stats.chi2_contingency(werkzeugtyp)[3]\nprint(pd.DataFrame(erwartet.round(2), index=[\"neu\", \"alt\"],\n                   columns=[\"Fehler\", \"in Ordnung\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Fehler  in Ordnung\nneu     6.5         3.5\nalt     6.5         3.5\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"kleinste erwartete Häufigkeit:\", round(erwartet.min(), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nkleinste erwartete Häufigkeit: 3.5\n```\n\n\n:::\n:::\n\n\n:::\n\nDie kleinste erwartete Häufigkeit beträgt 3.5 und liegt damit unter fünf. R gibt\nvon sich aus die Warnung `Chi-squared approximation may be incorrect` aus.\nPython schweigt an dieser Stelle, weshalb die erwarteten Häufigkeiten dort von\nHand geprüft werden müssen.\n\n#### Rechnung\n\nDrei Wege stehen offen. Sie werden hier nebeneinander gezeigt, weil sie zu\nverschiedenen Ergebnissen führen.\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(werkzeugtyp, correct = FALSE)   # ohne Stetigkeitskorrektur\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in chisq.test(werkzeugtyp, correct = FALSE): Chi-squared approximation\nmay be incorrect\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  werkzeugtyp\nX-squared = 5.4945, df = 1, p-value = 0.01908\n```\n\n\n:::\n\n```{.r .cell-code}\nchisq.test(werkzeugtyp)                    # mit Yates, in R Voreinstellung\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in chisq.test(werkzeugtyp): Chi-squared approximation may be incorrect\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  werkzeugtyp\nX-squared = 3.5165, df = 1, p-value = 0.06076\n```\n\n\n:::\n\n```{.r .cell-code}\nfisher.test(werkzeugtyp)                   # exakt\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  werkzeugtyp\np-value = 0.05728\nalternative hypothesis: true odds ratio is not equal to 1\n95 percent confidence interval:\n   0.9487882 684.4235629\nsample estimates:\nodds ratio \n   11.6367 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nohne = stats.chi2_contingency(werkzeugtyp, correction=False)\nmit = stats.chi2_contingency(werkzeugtyp, correction=True)\nexakt = stats.fisher_exact(werkzeugtyp)\n\nprint(\"ohne Korrektur  Chi-Quadrat =\", round(ohne[0], 4), \" p =\", round(ohne[1], 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nohne Korrektur  Chi-Quadrat = 5.4945  p = 0.0191\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"mit Yates       Chi-Quadrat =\", round(mit[0], 4), \" p =\", round(mit[1], 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmit Yates       Chi-Quadrat = 3.5165  p = 0.0608\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Fisher exakt    Odds Ratio =\", round(exakt[0], 2), \" p =\", round(exakt[1], 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFisher exakt    Odds Ratio = 13.5  p = 0.0573\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Verfahren | Teststatistik | p-Wert | Entscheidung bei 5 Prozent |\n|---|---|---|---|\n| Chi-Quadrat ohne Korrektur | 5.494 | 0.019 | signifikant |\n| Chi-Quadrat mit Yates-Korrektur | 3.517 | 0.061 | nicht signifikant |\n| Exakter Test nach Fisher | Odds Ratio 13.5 | 0.057 | nicht signifikant |\n\nDrei Verfahren, dieselben zwanzig Beobachtungen, und die Entscheidung kippt.\nDie Yates-Korrektur zieht von jeder Abweichung 0.5 ab, bevor quadriert wird; das\ngleicht aus, dass die stetige Chi-Quadrat-Verteilung eine diskrete Zählgrösse\nannähert. Der Fisher-Test rechnet gar nicht mit einer Näherung, sondern zählt\nalle Tabellen ab, die bei festen Randsummen mindestens so extrem sind.\n\n::: {.note-box}\nBeide Sprachen korrigieren bei Vierfeldertafeln von sich aus: `chisq.test()`\nhat `correct = TRUE`, `stats.chi2_contingency()` hat `correction=True`. Wer die\nKorrektur abschaltet, weil eine Anleitung es so zeigt, bekommt den kleineren\np-Wert und hier eine andere Entscheidung.\n\nZwei Unterschiede bleiben trotzdem. Erstens gibt es die Korrektur **nur** bei\n2x2-Tabellen; bei grösseren Tabellen wie in Beispiel 1 ist der Schalter ohne\nWirkung. Zweitens warnt R bei zu kleinen erwarteten Häufigkeiten von sich aus,\nscipy nicht. In Python muss die Prüfung deshalb von Hand erfolgen, so wie oben\nunter \"Voraussetzungen prüfen\".\n:::\n\n#### Interpretation und Ergebnissatz\n\nBei zwanzig Beobachtungen und einer erwarteten Häufigkeit von 3.5 ist der\nFisher-Test die richtige Wahl, und zwar unabhängig davon, welches Ergebnis er\nliefert. Die Entscheidung fällt an der Tabelle der erwarteten Häufigkeiten, nicht\nan den p-Werten.\n\nDas Odds Ratio von 13.5 ist dabei die inhaltlich interessante Zahl: Die Chance\nauf einen Fehler ist beim neuen Typ rund dreizehnmal so hoch. Dass dieser\ndeutliche Unterschied trotzdem nicht signifikant wird, liegt allein am Umfang.\nZehn Einsätze je Typ reichen nicht; das Konfidenzintervall des Odds Ratio, das\n`fisher.test()` mit ausgibt, macht diese Unsicherheit sichtbar.\n\n> Wegen einer erwarteten Häufigkeit von 3.5 wurde der exakte Test nach Fisher\n> verwendet. Ein Zusammenhang zwischen Werkzeugtyp und Fehlerauftreten lässt\n> sich nicht nachweisen (p = 0.057, n = 20), das geschätzte Odds Ratio beträgt\n> jedoch 13.5. Die Datenlage ist für eine Entscheidung zu dünn.\n\n### Beispiel 4: Signifikant bei grossem n, praktisch belanglos\n\n#### Frage und Datenlage\n\nEin Test zweier Varianten einer Seite, je 10 000 Aufrufe. Erfasst wird, ob\ngeklickt wurde.\n\n| | Klick | kein Klick | Summe | Klickrate |\n|---|---|---|---|---|\n| Variante A | 5200 | 4800 | 10 000 | 52.0 % |\n| Variante B | 5050 | 4950 | 10 000 | 50.5 % |\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvarianten <- matrix(c(5200, 4800,\n                      5050, 4950),\n                    nrow = 2, byrow = TRUE,\n                    dimnames = list(variante = c(\"A\", \"B\"),\n                                    ergebnis = c(\"Klick\", \"kein Klick\")))\n\nchisq.test(varianten, correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  varianten\nX-squared = 4.5028, df = 1, p-value = 0.03384\n```\n\n\n:::\n\n```{.r .cell-code}\nround(cramers_v(varianten), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0149\n```\n\n\n:::\n\n```{.r .cell-code}\nround(prop.table(varianten, margin = 1), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        ergebnis\nvariante Klick kein Klick\n       A 0.520      0.480\n       B 0.505      0.495\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nvarianten = np.array([[5200, 4800],\n                      [5050, 4950]])\n\nstatistik, p_wert, fg, erwartet = stats.chi2_contingency(varianten,\n                                                         correction=False)\nprint(\"Chi-Quadrat =\", round(statistik, 4), \" df =\", fg,\n      \" p =\", round(p_wert, 6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nChi-Quadrat = 4.5028  df = 1  p = 0.033839\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Cramérs V =\", round(cramers_v(varianten), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCramérs V = 0.0149\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Klickraten:\", (varianten[:, 0] / varianten.sum(axis=1)).round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKlickraten: [0.52  0.505]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| `X-squared` | 4.503 | Über der kritischen Schwelle von 3.84 bei einem Freiheitsgrad. |\n| `df` | 1 | Vierfeldertafel. |\n| `p-value` | 0.034 | Signifikant auf dem 5-Prozent-Niveau. |\n| Cramérs V | 0.015 | Und hier steht die eigentliche Antwort: praktisch null. Der Anhaltspunkt für einen kleinen Zusammenhang liegt bei 0.1, also fast siebenmal höher. |\n| Klickraten | 52.0 % gegenüber 50.5 % | Der Unterschied beträgt 1.5 Prozentpunkte. |\n| standardisierte Residuen | ±2.122 | Knapp über der Auffälligkeitsschwelle von 2, aber bei 20 000 Beobachtungen sagt das wenig über die Grösse. |\n\nChi-Quadrat wächst proportional mit n. Dieselben Klickraten bei je 1000 statt\n10 000 Aufrufen ergäben Chi-Quadrat 0.45 und p = 0.50, also einen glatten\nNullbefund. An den Klickraten und an Cramérs V ändert der Umfang dagegen nichts.\n\n#### Interpretation und Ergebnissatz\n\nOb 1.5 Prozentpunkte zählen, ist keine statistische Frage. Bei einer Million\nAufrufen im Monat sind es 15 000 zusätzliche Klicks und damit womöglich eine\nklare Entscheidung; bei tausend Aufrufen sind es fünfzehn und damit belanglos.\nGenau deshalb wird die Relevanzschwelle vor der Auswertung festgelegt und nicht\ndanach an das Ergebnis angepasst.\n\nBerichtet werden deshalb immer beide Ebenen: der Test für die Frage \"vom Zufall\nunterscheidbar\" und die Kennzahl in der Einheit der Sache für die Frage \"wie\ngross\". Der p-Wert allein beantwortet die zweite Frage nicht und wird bei\ngrossem n regelmässig überinterpretiert.\n\n> Die Klickrate unterscheidet sich zwischen den Varianten,\n> Chi-Quadrat(1, n = 20 000) = 4.50, p = 0.034. Der Unterschied beträgt\n> 1.5 Prozentpunkte (52.0 % gegenüber 50.5 %), Cramérs V = 0.015 und damit\n> praktisch null. Ob der Unterschied eine Entscheidung trägt, hängt am Volumen\n> und nicht am p-Wert.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nWarum hat eine Kreuztabelle mit 4 Zeilen und 3 Spalten sechs Freiheitsgrade?\n\n- [x] Weil bei festen Randsummen nur drei mal zwei Zellen frei wählbar sind ~\n      Richtig. Sind sechs Zellen gefüllt, ergeben sich die übrigen zwangsläufig.\n      Die Freiheitsgrade zählen, wie viel an der Tabelle variieren kann.\n- [ ] Weil 4 plus 3 minus 1 gleich 6 ist ~ Das Ergebnis stimmt zufällig, die\n      Regel nicht. Bei 5 Zeilen und 3 Spalten käme man damit auf 7 statt auf 8.\n- [ ] Weil zwölf Zellen minus sechs Randsummen bleiben ~ Die Randsummen sind\n      sieben, und die Rechnung führt hier nur zufällig in die Nähe.\n:::\n\n::: {.quiz}\nEin Unabhängigkeitstest ergibt p = 0.002. Wie berichtet man das inhaltlich\nsinnvoll? @fig-residuen-chi-r zeigt den nächsten Schritt.\n\n- [ ] Mit dem p-Wert, der spricht für sich ~ Er sagt nur, dass es irgendwo eine\n      Abweichung gibt, nicht wo.\n- [x] Mit der Aussage über den Zusammenhang und den auffälligen Zellen ~\n      Richtig. Erst die standardisierten Residuen zeigen, welche Kombinationen\n      häufiger oder seltener auftreten als bei Unabhängigkeit zu erwarten. Das\n      beantwortet die Frage, die zum Test geführt hat.\n- [ ] Mit der Chi-Quadrat-Statistik statt des p-Werts ~ Auch sie ist nur eine\n      Gesamtzahl ohne inhaltliche Richtung.\n:::\n\n::: {.quiz}\nIn einer Kreuztabelle liegen mehrere erwartete Häufigkeiten unter fünf. Was\nfolgt daraus?\n\n- [ ] Der Test wird konservativer und damit sicherer ~ Er wird nicht sicherer,\n      sondern unzuverlässig, und zwar in beide Richtungen.\n- [x] Die Näherung durch die Chi-Quadrat-Verteilung ist nicht mehr verlässlich ~\n      Richtig. Auswege sind das inhaltlich sinnvolle Zusammenfassen dünn\n      besetzter Kategorien oder ein exaktes Verfahren wie der Test nach Fisher.\n- [ ] Die Stichprobe muss verworfen werden ~ Sie bleibt brauchbar, nur das\n      Verfahren muss angepasst werden.\n:::\n\n## Verlinkte Ressourcen\n\n- [OpenIntro Statistics, Kapitel zu kategorialen Daten](https://www.openintro.org/book/os/)\n- [scipy: chi2_contingency](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chi2_contingency.html)\n- [R-Dokumentation zu `chisq.test`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/chisq.test.html)\n- [Prüfverteilungen: t, Chi-Quadrat und F](../wahrscheinlichkeit/pruefverteilungen.qmd), woher die Chi-Quadrat-Verteilung kommt und was die Freiheitsgrade zählen\n",
    "supporting": [
      "chi-quadrat-tests_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}