{
  "hash": "aa370a4d08ca0e2f54f0036e61faa8fc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Datenqualität\"\ndescription: \"Plausibilität, fehlende Werte, Duplikate und uneinheitliche Kategorien.\"\ncategories: [\"Datenqualität\", \"Data Wrangling\", \"R\", \"Python\"]\nquelle: [\"ESDS\"]\nseitentyp: werkzeug\nstand: entwurf\norder: 50\n---\n\n\n\n\n\n## Kernideen\n\n- **Plausibilität zuerst:** Was gar nicht sein kann, ist kein Ausreisser,\n  sondern ein Fehler oder ein Platzhalter.\n- Ein Platzhalter wie `-1` oder `9999` ist **gefährlicher als eine leere\n  Zelle**, weil er mitrechnet.\n- Bei fehlenden Werten zählt nicht die Anzahl, sondern das **Muster**: Hängt\n  das Fehlen mit anderen Merkmalen zusammen, verzerrt jedes Weglassen.\n- **Duplikate** entstehen leise, meist beim Zusammenführen, und verschieben\n  jede Kennzahl.\n- Kategorien sind **uneinheitlich geschrieben**, bevor jemand sie\n  vereinheitlicht: `Bern`, `bern`, `Bern ` sind drei Gruppen.\n- **Ziffernhäufung** verrät gerundete oder geschätzte Werte.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Data Wrangling](data-wrangling.qmd) für die Handgriffe und\n[Tidy Data](tidy-data.qmd) für die Form. Woher die Fehler kommen, steht unter\n[Datenimport](datenimport-formate.qmd); die systematische Sichtung insgesamt\nunter [explorative Datenanalyse](../statistik/grundlagen/explorative-datenanalyse.qmd).\n:::\n\n### Die Reihenfolge der Prüfungen\n\n| Schritt | Frage | Werkzeug |\n|---|---|---|\n| 1. Struktur | Stimmen Zeilenzahl und Spaltentypen? | `str()`, `df.dtypes` |\n| 2. Plausibilität | Was kann gar nicht sein? | `summary()`, `describe()`, Minimum und Maximum |\n| 3. Fehlende Werte | Wie viele, und **wo**? | `is.na()`, `isna().sum()`, Vergleich der Gruppen |\n| 4. Duplikate | Gibt es Zeilen doppelt, gibt es Schlüssel doppelt? | `duplicated()`, `.duplicated()` |\n| 5. Kategorien | Wie viele Ausprägungen, und sind es wirklich so viele? | `table()`, `value_counts()` |\n| 6. Verteilung | Häufen sich Werte an runden Stellen? | letzte Ziffer auszählen |\n\nErst danach beginnt die Auswertung. Jeder Schritt wird **im Code**\nfestgehalten, nicht von Hand in der Datei korrigiert: Sonst ist die\nBereinigung beim nächsten Datenstand weg und niemand kann sie nachvollziehen.\n\n### Fehlende Werte: drei Muster\n\n| Muster | heisst | Folge |\n|---|---|---|\n| rein zufällig | das Fehlen hängt von nichts ab | Weglassen kostet nur Fälle |\n| von beobachteten Merkmalen abhängig | Ältere antworten seltener | Weglassen **verzerrt**; die Abhängigkeit gehört ins Modell |\n| vom fehlenden Wert selbst abhängig | wer viel verdient, nennt das Einkommen nicht | aus den Daten allein nicht erkennbar |\n\nDie zweite Sorte lässt sich aufdecken, indem man die Fälle mit und ohne\nLücke vergleicht. Genau das macht Beispiel 2.\n\n### Der Umgang mit Lücken\n\n| Vorgehen | wann | Vorsicht |\n|---|---|---|\n| Fall weglassen | wenige Fälle, zufälliges Fehlen | bei Abhängigkeit verzerrt es |\n| Mittelwert einsetzen | nie ohne Not | verkleinert die Streuung, täuscht Genauigkeit vor |\n| Modellbasiert ersetzen | wenn viele Fälle betroffen sind | aufwendig, und die Unsicherheit muss mitgeführt werden |\n| als eigene Kategorie führen | kategoriale Merkmale | oft die ehrlichste Lösung |\n\nIn jedem Fall gehört die Anzahl der weggelassenen oder ersetzten Werte in den\nBericht.\n\n### Kurz nachgeschlagen\n\n| Aufgabe | R | Python |\n|---|---|---|\n| fehlende Werte je Spalte | `colSums(is.na(df))` | `df.isna().sum()` |\n| Platzhalter auf `NA` setzen | `df$x[df$x < 0] <- NA` | `df.loc[df[\"x\"] < 0, \"x\"] = np.nan` |\n| vollständige Fälle | `df[complete.cases(df), ]` | `df.dropna()` |\n| exakte Duplikate | `sum(duplicated(df))` | `df.duplicated().sum()` |\n| doppelte Schlüssel | `sum(duplicated(df$id))` | `df[\"id\"].duplicated().sum()` |\n| Duplikate entfernen | `distinct(df)` | `df.drop_duplicates()` |\n| Leerzeichen entfernen | `trimws(x)` | `s.str.strip()` |\n| Gross- und Kleinschreibung | `tolower(x)` | `s.str.lower()` |\n| Ausprägungen zählen | `table(x)` | `s.value_counts()` |\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Der Platzhalter, der mitrechnet\n\n#### Frage und Datenlage\n\n402 Datensätze mit Gewicht, Alter, Standort und Blutdruck. Der Blick auf die\nKennzahlen des Gewichts zeigt ein Minimum, das es nicht geben kann.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(roh)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 402\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(roh$gewicht)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  -1.00   72.72   80.80   80.41   88.80  117.70 \n```\n\n\n:::\n\n```{.r .cell-code}\nsum(roh$gewicht < 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(roh[roh$gewicht < 0, ], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    gewicht alter standort blutdruck\n12       -1    73     Chur       140\n88       -1    45     Chur       144\n301      -1    18     Bern       123\n```\n\n\n:::\n\n```{.r .cell-code}\nsauber <- roh\nsauber$gewicht[sauber$gewicht < 0] <- NA\nround(c(vorher = mean(roh$gewicht), nachher = mean(sauber$gewicht, na.rm = TRUE)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n vorher nachher \n  80.41   81.02 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(len(roh))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n402\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(roh[\"gewicht\"].describe().round(2).to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'count': 402.0, 'mean': 80.41, 'std': 13.49, 'min': -1.0, '25%': 72.72, '50%': 80.8, '75%': 88.8, 'max': 117.7}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"negativ:\", int((roh[\"gewicht\"] < 0).sum()))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnegativ: 3\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(roh[roh[\"gewicht\"] < 0].head(3).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n gewicht  alter standort  blutdruck\n    -1.0     73     Chur      140.0\n    -1.0     45     Chur      144.0\n    -1.0     18     Bern      123.0\n```\n\n\n:::\n\n```{.python .cell-code}\nsauber = roh.copy()\nsauber.loc[sauber[\"gewicht\"] < 0, \"gewicht\"] = np.nan\nprint(round(roh[\"gewicht\"].mean(), 2), round(sauber[\"gewicht\"].mean(), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n80.41 81.02\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | Wert | Erklärung |\n|---|---|---|\n| Zeilen | 402 | |\n| Minimum Gewicht | **−1.0** | Ein Gewicht von minus eins ist kein Ausreisser, sondern ein Code. |\n| Maximum | 117.7 | plausibel |\n| Anzahl negativer Werte | **3** | Drei Erfassungen mit Platzhalter. |\n| Mittelwert vorher | **80.41** | mit den drei Platzhaltern |\n| Mittelwert nachher | **81.02** | nach dem Ersetzen durch `NA`, also 0.61 höher |\n\n#### Interpretation und Ergebnissatz\n\nDer Unterschied von 0.61 wirkt harmlos und ist es nur, weil es drei von 402\nFällen sind. Derselbe Platzhalter bei zehn Prozent der Werte, oder ein Code\nwie 9999 statt −1, verschöbe das Ergebnis massiv. Der eigentliche Punkt ist\nnicht die Grösse der Verschiebung, sondern dass sie **ohne jeden Hinweis**\nentsteht: Eine leere Zelle wird als `NA` gelesen und von jeder Rechnung\nsichtbar behandelt, ein Platzhalter rechnet mit.\n\n> Drei der 402 Gewichte sind mit dem Platzhalter −1 erfasst. Ersetzt man sie\n> durch `NA`, steigt der Mittelwert von 80.41 auf 81.02.\n\n### Beispiel 2: Fehlende Werte haben ein Muster\n\n#### Frage und Datenlage\n\nBeim Blutdruck fehlen Werte. Wie viele sind es, und unterscheiden sich die\nFälle mit Lücke von denen ohne?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(fehlend = sum(is.na(sauber$blutdruck)),\n  anteil  = round(mean(is.na(sauber$blutdruck)) * 100, 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfehlend  anteil \n     28       7 \n```\n\n\n:::\n\n```{.r .cell-code}\nsauber |>\n  mutate(fehlt = is.na(blutdruck)) |>\n  summarise(.by = fehlt, n = n(), mittleres_alter = round(mean(alter), 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  fehlt   n mittleres_alter\n1 FALSE 374            43.4\n2  TRUE  28            70.0\n```\n\n\n:::\n\n```{.r .cell-code}\nsauber |>\n  mutate(gruppe = cut(alter, c(17, 40, 65, 100),\n                      labels = c(\"18-40\", \"41-65\", \"66+\"))) |>\n  summarise(.by = gruppe,\n            anteil_fehlend = round(mean(is.na(blutdruck)) * 100, 1)) |>\n  arrange(gruppe)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  gruppe anteil_fehlend\n1  18-40              0\n2  41-65              0\n3    66+             50\n```\n\n\n:::\n\n```{.r .cell-code}\nround(mean(sauber$blutdruck, na.rm = TRUE), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 129.06\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(\"fehlend:\", int(sauber[\"blutdruck\"].isna().sum()),\n      round(sauber[\"blutdruck\"].isna().mean() * 100, 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfehlend: 28 7.0\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(sauber.assign(fehlt=sauber[\"blutdruck\"].isna())\n      .groupby(\"fehlt\")\n      .agg(n=(\"alter\", \"size\"), mittleres_alter=(\"alter\", \"mean\"))\n      .round(1).to_string())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         n  mittleres_alter\nfehlt                      \nFalse  374             43.4\nTrue    28             70.0\n```\n\n\n:::\n\n```{.python .cell-code}\ngruppen = pd.cut(sauber[\"alter\"], [17, 40, 65, 100],\n                 labels=[\"18-40\", \"41-65\", \"66+\"])\nprint(sauber.groupby(gruppen, observed=True)[\"blutdruck\"]\n      .apply(lambda s: round(s.isna().mean() * 100, 1)).to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'18-40': 0.0, '41-65': 0.0, '66+': 50.0}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(round(sauber[\"blutdruck\"].mean(), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n129.06\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | Wert | Erklärung |\n|---|---|---|\n| fehlende Werte | **28** von 402, **7.0 Prozent** | Für sich genommen unauffällig. |\n| mittleres Alter, Wert vorhanden | **43.4** Jahre | 374 Fälle |\n| mittleres Alter, Wert fehlt | **70.0** Jahre | 28 Fälle. Der Unterschied von über 26 Jahren ist das Warnzeichen. |\n| Anteil fehlend, 18 bis 40 | **0.0 Prozent** | |\n| Anteil fehlend, 41 bis 65 | **0.0 Prozent** | |\n| Anteil fehlend, 66 und älter | **50.0 Prozent** | Jede zweite ältere Person hat keinen Blutdruckwert. |\n| Mittelwert der vorhandenen Werte | 129.06 | Dieser Wert beschreibt eine Stichprobe, in der die Älteren fehlen. |\n\n#### Interpretation und Ergebnissatz\n\nSieben Prozent Lücken klingen nach einer Kleinigkeit, die man wegwirft. Der\nVergleich zeigt das Gegenteil: Die Lücken liegen fast vollständig bei den\nüber 65-Jährigen. Wer die Fälle weglässt, rechnet den Blutdruck einer\njüngeren Bevölkerung aus, und weil Blutdruck mit dem Alter steigt, ist das\nErgebnis zu niedrig. Der Anteil fehlender Werte je Altersgruppe gehört\ndeshalb in den Bericht, und die Altersabhängigkeit ins Modell.\n\n> Von 402 Blutdruckwerten fehlen 28, also 7.0 Prozent, und zwar ausschliesslich\n> bei den über 65-Jährigen, wo jeder zweite Wert fehlt. Die Fälle mit Lücke\n> sind im Mittel 70.0 Jahre alt, die vollständigen 43.4.\n\n### Beispiel 3: Duplikate\n\n#### Frage und Datenlage\n\nBeim Zusammenführen zweier Exporte sind Zeilen doppelt in den Datensatz\ngeraten. Wie viele, und was ändert sich, wenn man sie entfernt?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(duplicated(roh))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n\n```{.r .cell-code}\nwhich(duplicated(roh))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 401 402\n```\n\n\n:::\n\n```{.r .cell-code}\nohne <- distinct(roh)\nc(mit = nrow(roh), ohne = nrow(ohne))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n mit ohne \n 402  400 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(mit = mean(roh$alter), ohne = mean(ohne$alter)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   mit   ohne \n45.221 45.138 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(\"exakte Duplikate:\", int(roh.duplicated().sum()))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nexakte Duplikate: 2\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(roh.index[roh.duplicated()].tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[400, 401]\n```\n\n\n:::\n\n```{.python .cell-code}\nohne = roh.drop_duplicates()\nprint(len(roh), len(ohne))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n402 400\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(round(roh[\"alter\"].mean(), 3), round(ohne[\"alter\"].mean(), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n45.221 45.138\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | Wert | Erklärung |\n|---|---|---|\n| exakte Duplikate | **2** | Zeilen, die in allen Spalten mit einer früheren übereinstimmen. |\n| Zeilen mit, ohne | **402** gegen **400** | |\n| mittleres Alter | 45.221 gegen **45.138** | Der Unterschied ist klein, weil es zwei von 402 sind. Er zeigt aber, dass jede Kennzahl betroffen ist. |\n\n`duplicated()` markiert das **zweite** und jedes weitere Vorkommen, nicht das\nerste. Für Schlüsselspalten prüft man zusätzlich `duplicated(df$id)`: Zwei\nZeilen mit derselben Kennung, aber verschiedenen Werten sind der schlimmere\nFall, weil keine der beiden falsch aussieht.\n\n#### Interpretation und Ergebnissatz\n\nExakte Duplikate sind leicht zu finden und meist harmlos zu beheben. Die\neigentliche Gefahr liegt davor: Sie entstehen fast immer beim Verknüpfen mit\neinem nicht eindeutigen Schlüssel, siehe [pandas](../programmierung/pandas.qmd),\nBeispiel 6. Deshalb ist die Zeilenzahl vor und nach jedem Join die billigste\nKontrolle, die es gibt.\n\n> Der Datensatz enthält zwei exakte Duplikate; nach dem Entfernen bleiben 400\n> Zeilen, und das mittlere Alter verschiebt sich von 45.221 auf 45.138.\n\n### Beispiel 4: Dieselbe Kategorie, drei Schreibweisen\n\n#### Frage und Datenlage\n\nDer Standort ist als Text erfasst. Wie viele Ausprägungen gibt es, und wie\nviele sollten es sein?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsort(unique(roh$standort))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"bern\"  \"Bern\"  \"Bern \" \"Chur\"  \"Sion\" \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(roh$standort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n bern  Bern Bern   Chur  Sion \n    3   200     2   114    83 \n```\n\n\n:::\n\n```{.r .cell-code}\nnormiert <- trimws(roh$standort)\nnormiert <- paste0(toupper(substr(normiert, 1, 1)),\n                   tolower(substring(normiert, 2)))\ntable(normiert)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnormiert\nBern Chur Sion \n 205  114   83 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(sorted(roh[\"standort\"].unique().tolist()))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['Bern', 'Bern ', 'Chur', 'Sion', 'bern']\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(roh[\"standort\"].value_counts().to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'Bern': 200, 'Chur': 114, 'Sion': 83, 'bern': 3, 'Bern ': 2}\n```\n\n\n:::\n\n```{.python .cell-code}\nnormiert = roh[\"standort\"].str.strip().str.capitalize()\nprint(normiert.value_counts().to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'Bern': 205, 'Chur': 114, 'Sion': 83}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausprägung | Anzahl | Erklärung |\n|---|---|---|\n| `Bern` | 200 | |\n| `Chur` | 114 | |\n| `Sion` | 83 | |\n| `bern` | **3** | kleingeschrieben erfasst |\n| `Bern ` | **2** | mit angehängtem Leerzeichen, im Ausdruck **unsichtbar** |\n| nach dem Normieren | Bern **205**, Chur 114, Sion 83 | drei Ausprägungen statt fünf |\n\nDas angehängte Leerzeichen ist der tückischere Fall: In jeder Tabelle und\njeder Grafik sieht `Bern ` genau aus wie `Bern`, aber eine Gruppierung\ntrennt beide, und ein Join findet die Zeilen nicht. Ein Blick auf die Anzahl\nder Ausprägungen (`length(unique(x))` gegen die erwartete Zahl) findet das\nsofort.\n\n#### Interpretation und Ergebnissatz\n\nFünf Gruppen statt drei bedeuten fünf Zeilen in jeder Auswertung, zwei davon\nmit winzigen Fallzahlen, und einen Mittelwert für \"Bern\", der drei Prozent\nder Berner Fälle nicht enthält. Das Vereinheitlichen (Leerzeichen entfernen,\nSchreibweise angleichen) gehört vor jede Gruppierung; bei freiem Text kommt\ndas Abgleichen gegen eine Referenzliste dazu.\n\n> Der Standort hat fünf Ausprägungen, obwohl es drei Orte sind: `bern`\n> dreimal und `Bern ` mit Leerzeichen zweimal. Nach dem Vereinheitlichen\n> stehen 205 Berner Fälle statt 200.\n\n### Beispiel 5: Ziffernhäufung\n\n#### Frage und Datenlage\n\nBlutdruckwerte werden oft geschätzt oder auf \"runde\" Werte gerundet. Lässt\nsich das an den Daten selbst erkennen? Dazu die Häufigkeit der letzten Ziffer\naller vorhandenen Werte.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbd <- sauber$blutdruck[!is.na(sauber$blutdruck)]\nlength(bd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 374\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(bd %% 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  0   1   2   3   4   5   6   7   8   9 \n102  24  25  26  22  72  30  24  19  30 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(mean(bd %% 5 == 0) * 100, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 46.5\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nbd = sauber[\"blutdruck\"].dropna()\nprint(len(bd))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n374\n```\n\n\n:::\n\n```{.python .cell-code}\nprint((bd % 10).astype(int).value_counts().sort_index().to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{0: 102, 1: 24, 2: 25, 3: 26, 4: 22, 5: 72, 6: 30, 7: 24, 8: 19, 9: 30}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(round(((bd % 5) == 0).mean() * 100, 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n46.5\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| letzte Ziffer | Anzahl | Erwartung bei gleichmässiger Verteilung |\n|---|---|---|\n| **0** | **102** | rund 37 |\n| 1 | 24 | |\n| 2 | 25 | |\n| 3 | 26 | |\n| 4 | 22 | |\n| **5** | **72** | rund 37 |\n| 6 | 30 | |\n| 7 | 24 | |\n| 8 | 19 | |\n| 9 | 30 | |\n\n| Grösse | Wert | Erklärung |\n|---|---|---|\n| Werte insgesamt | 374 | |\n| Anteil auf 0 oder 5 | **46.5 Prozent** | Bei gleichmässiger Verteilung wären es 20 Prozent. |\n\n#### Interpretation und Ergebnissatz\n\nFast die Hälfte aller Werte endet auf 0 oder 5. Das kommt in der Natur nicht\nvor, es kommt aus dem Erfassungsvorgang: geschätzte oder gerundete Ablesungen.\nFür die Auswertung heisst das zweierlei. Die Werte sind gröber, als ihre\nNachkommastellen vortäuschen, und eine Kennzahl sollte nicht mehr Stellen\nnennen, als die Erfassung hergibt. Und wenn nur ein Teil der Erhebung so\nzustande kam, unterscheiden sich die Teile systematisch, was vor jedem\nGruppenvergleich zu klären ist.\n\n> 46.5 Prozent der 374 Blutdruckwerte enden auf 0 oder 5, erwartet wären\n> 20 Prozent; allein die Endziffer 0 kommt 102-mal statt rund 37-mal vor. Die\n> Werte sind also zu einem erheblichen Teil gerundet erfasst.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nIn den Daten steht bei drei Personen ein Gewicht von minus eins. Warum ist so\nein Platzhalter gefährlicher als eine leere Zelle?\n\n- [ ] Er ist nicht gefährlicher, nur unschöner ~ Der Unterschied ist, ob ein\n      Fehler auffällt oder nicht.\n- [x] Er sieht wie ein gültiger Wert aus und rechnet stillschweigend mit ~\n      Richtig. Eine leere Zelle wird als `NA` eingelesen und von jeder\n      Rechnung sichtbar behandelt; −1 verschiebt den Mittelwert ohne Warnung,\n      hier um 0.61.\n- [ ] Er lässt sich nicht in `NA` umwandeln ~ Umwandeln lässt er sich gut, man\n      muss ihn nur zuerst bemerken.\n:::\n\n::: {.quiz}\nBei sieben Prozent der Fälle fehlt der Blutdruck. Diese Fälle sind im Mittel\n70 Jahre alt, die übrigen 43. Was folgt daraus?\n\n- [ ] Sieben Prozent sind wenig, die Fälle können weg ~ Die Anzahl ist nicht\n      das Kriterium, sondern das Muster.\n- [x] Das Fehlen hängt vom Alter ab, Weglassen verzerrt das Ergebnis nach\n      unten ~ Richtig. Übrig bleibt eine jüngere Stichprobe, und da der\n      Blutdruck mit dem Alter steigt, ist das Ergebnis zu niedrig.\n- [ ] Die Messgeräte waren defekt ~ Möglich, aber das ändert nichts an der\n      Verzerrung.\n:::\n\n::: {.quiz}\nEine Auswertung nach Standort zeigt fünf Gruppen, obwohl es drei Standorte\ngibt. Was ist zuerst zu prüfen?\n\n- [x] Schreibweise und unsichtbare Leerzeichen ~ Richtig. `Bern`, `bern` und\n      `Bern ` sind drei verschiedene Zeichenketten, und das Leerzeichen sieht\n      man im Ausdruck nicht. `trimws` beziehungsweise `.str.strip()` und eine\n      einheitliche Schreibweise lösen es.\n- [ ] Ob zwei Standorte neu eröffnet wurden ~ Möglich, aber die Fallzahlen\n      von 3 und 2 sprechen dagegen.\n- [ ] Ob die Gruppierung falsch programmiert ist ~ Die Gruppierung tut genau,\n      was sie soll; die Werte unterscheiden sich wirklich.\n:::\n\n::: {.quiz}\n46.5 Prozent der Blutdruckwerte enden auf 0 oder 5. Was sagt das über die\nDaten?\n\n- [x] Ein grosser Teil wurde gerundet oder geschätzt erfasst ~ Richtig. Bei\n      gleichmässiger Verteilung der Endziffern wären es 20 Prozent. Die Werte\n      sind gröber, als sie aussehen.\n- [ ] Die Messgeräte sind besonders genau ~ Genaue Geräte erzeugen keine\n      Häufung auf runden Werten.\n- [ ] Es ist Zufall ~ Bei 374 Werten ist eine Abweichung von 20 auf 46.5\n      Prozent kein Zufall.\n:::\n\n::: {.quiz}\nNach dem Entfernen von zwei Duplikaten ändert sich das mittlere Alter von\n45.221 auf 45.138. Ist der Aufwand gerechtfertigt?\n\n- [x] Ja, denn die Grösse der Änderung ist Zufall der Anzahl ~ Richtig. Bei\n      zwei von 402 Zeilen ist sie klein; entstünden die Duplikate durch einen\n      Join mit nicht eindeutigem Schlüssel, wären es schnell Hunderte.\n- [ ] Nein, die dritte Nachkommastelle ist belanglos ~ Belanglos ist die\n      Verschiebung hier, nicht die Ursache.\n- [ ] Nein, Duplikate sind immer echte Beobachtungen ~ Zwei identische Zeilen\n      können echt sein; dann braucht es eine Kennung, die sie unterscheidet.\n:::\n\n## Verlinkte Ressourcen\n\n- [Missing data, Kapitel in R for Data Science](https://r4ds.hadley.nz/missing-values)\n- [pandas: Umgang mit fehlenden Werten](https://pandas.pydata.org/docs/user_guide/missing_data.html)\n- [naniar: fehlende Werte sichtbar machen](https://naniar.njtierney.com/)\n",
    "supporting": [
      "datenqualitaet_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}