{
  "hash": "28946b2026c0db36bbcba7add0ab0648",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Varianzanalyse\"\ndescription: \"Mehr als zwei Gruppen vergleichen, Post-hoc und Bezug zur Regression.\"\ncategories: [\"Hypothesentests\", \"Regression\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: methode\nstand: fertig\norder: 40\n---\n\n\n\n\n\n## Kurzsteckbrief\n\n| | |\n|---|---|\n| Fragestellung | Unterscheiden sich die Mittelwerte von mehr als zwei Gruppen? |\n| Zielvariable | metrisch |\n| Gruppen | drei oder mehr, unabhängig voneinander |\n| Was die Methode liefert | F-Statistik mit Freiheitsgraden, p-Wert, Streuungszerlegung, Effektstärke, auf Wunsch paarweise Vergleiche |\n| R-Funktion | `aov(wert ~ gruppe, data = df)`, ungleiche Varianzen mit `oneway.test()` |\n| Python-Funktion | `pg.anova(data=df, dv=\"wert\", between=\"gruppe\")`, ungleiche Varianzen mit `pg.welch_anova()` |\n| Verwandte Methoden | [t-Test für zwei Stichproben](t-test-zwei-stichproben.qmd), [multiple lineare Regression](../regression/multiple-lineare-regression.qmd), [nichtparametrische Tests](nichtparametrische-tests.qmd) |\n\n## Wann diese Methode, wann nicht\n\nTypische Fragestellungen: Unterscheidet sich der Durchsatz zwischen drei\nStandorten, die Haltbarkeit zwischen vier Materialien, die Bearbeitungszeit\nzwischen mehreren Teams. Gemeinsam ist ihnen eine metrische Zielgrösse und eine\nGruppierung mit mehr als zwei Stufen.\n\nDer Grund für ein eigenes Verfahren ist die Fehlerrate. Bei drei Gruppen gibt es\ndrei Paarvergleiche, bei fünf Gruppen schon zehn. Wer sie alle einzeln auf dem\nFünf-Prozent-Niveau prüft, findet fast sicher irgendwo einen Unterschied, auch\nwenn keiner besteht, siehe [multiples Testen](../inferenz/multiples-testen.qmd).\nDie Varianzanalyse stellt stattdessen eine einzige Frage: Gibt es überhaupt einen\nUnterschied irgendwo? Erst wenn die Antwort ja lautet, folgen die paarweisen\nVergleiche mit Korrektur.\n\n| Situation | Stattdessen |\n|---|---|\n| Genau zwei Gruppen | [t-Test für zwei Stichproben](t-test-zwei-stichproben.qmd) |\n| Dieselben Objekte mehrfach gemessen | Varianzanalyse mit Messwiederholung oder gemischtes Modell |\n| Deutlich ungleiche Varianzen | Welch-Variante, siehe Szenario C auf dieser Seite |\n| Kleine, stark schiefe Gruppen | [Kruskal-Wallis](nichtparametrische-tests.qmd) |\n| Zielvariable kategorial | [Chi-Quadrat-Test](chi-quadrat-tests.qmd) |\n| Weitere Einflussgrössen sollen konstant gehalten werden | [multiple lineare Regression](../regression/multiple-lineare-regression.qmd) |\n\n## Grundidee und Modell\n\nDie Streuung aller Werte wird in zwei Teile zerlegt: den Teil, der auf die\nUnterschiede zwischen den Gruppenmittelwerten zurückgeht, und den Teil innerhalb\nder Gruppen. Sind die Gruppen wirklich verschieden, ist der erste Teil gross\ngegenüber dem zweiten.\n\n$$F = \\frac{\\text{mittlere Quadratsumme zwischen den Gruppen}}{\\text{mittlere Quadratsumme innerhalb der Gruppen}}$$\n\n| Bestandteil | Bedeutung |\n|---|---|\n| $SS_{\\text{zwischen}}$ | Abweichungen der Gruppenmittelwerte vom Gesamtmittel, gewichtet mit der Gruppengrösse |\n| $SS_{\\text{innerhalb}}$ | Abweichungen der einzelnen Werte von ihrem Gruppenmittel |\n| $df_{\\text{zwischen}}$ | Anzahl Gruppen minus eins |\n| $df_{\\text{innerhalb}}$ | Gesamtzahl Beobachtungen minus Anzahl Gruppen |\n| $F$ | Verhältnis der beiden mittleren Quadratsummen, unter der Nullhypothese nahe eins |\n| $\\eta^2$ | Anteil der Streuung, der auf die Gruppierung entfällt |\n\nDie Nullhypothese lautet, dass alle Gruppenerwartungswerte gleich sind. Die\nAlternative ist nicht \"alle sind verschieden\", sondern \"mindestens einer weicht\nab\". Das ist der Grund, warum ein signifikanter F-Wert allein noch keine Aussage\ndarüber erlaubt, welche Gruppen sich unterscheiden.\n\nFormal ist die Varianzanalyse ein Spezialfall der linearen Regression mit einem\nkategorialen Prädiktor. Dieselben Daten, dieselben Quadratsummen, andere\nDarstellung; das letzte Szenario auf dieser Seite zeigt es an den Zahlen.\n\n## Voraussetzungen und ihre Prüfung\n\n| Voraussetzung | Was sie bedeutet | Prüfung | Folge bei Verletzung | Vorgehen |\n|---|---|---|---|---|\n| Unabhängigkeit | Beobachtungen beeinflussen sich weder innerhalb noch zwischen den Gruppen | Erhebungsdesign | p-Werte zu optimistisch, nicht reparierbar | Modell für die Struktur, etwa Messwiederholung |\n| Metrische Zielvariable | Mittelwerte und Quadratsummen sind sinnvoll | [Skalenniveau](../grundlagen/skalenniveaus.qmd) | Das Modell rechnet mit undefinierten Grössen | rangbasiertes Verfahren |\n| Annähernd normalverteilte Residuen | Die Abweichungen vom Gruppenmittel, nicht die Rohwerte | [QQ-Plot](../wahrscheinlichkeit/qq-plots.qmd) der Residuen | Bei kleinen Gruppen weicht die Fehlerrate ab | Kruskal-Wallis oder Bootstrap |\n| Gleiche Varianzen in allen Gruppen | Homoskedastizität | Boxplot, Levene-Test | Bei ungleichen Gruppengrössen wird das Niveau verfehlt | Welch-Variante |\n| Keine extremen Ausreisser | Einzelne Werte bestimmen Mittel und Varianz nicht | Boxplot | Das Ergebnis hängt an wenigen Punkten | Ursache prüfen, mit und ohne berichten |\n\n## Output lesen\n\nR, `summary(aov())`:\n\n| Grösse | Was sie sagt | Faustregel oder Falle |\n|---|---|---|\n| `Df` | Freiheitsgrade, eine Zeile je Quelle | oben Anzahl Gruppen minus eins, unten n minus Anzahl Gruppen |\n| `Sum Sq` | Quadratsummen zwischen und innerhalb | ihr Verhältnis ergibt $\\eta^2$ |\n| `Mean Sq` | Quadratsumme geteilt durch Freiheitsgrade | die beiden Werte bilden den F-Bruch |\n| `F value` | Teststatistik | unter der Nullhypothese nahe eins |\n| `Pr(>F)` | p-Wert | sagt nur, dass irgendwo ein Unterschied besteht |\n| `Residuals` | die Zeile innerhalb der Gruppen | ihre Mean Sq ist die geschätzte Fehlervarianz |\n\nPython, `pg.anova(detailed=True)`:\n\n| Spalte | Was sie sagt | Unterschied zu R |\n|---|---|---|\n| `Source` | Quelle der Streuung | wie die Zeilenbeschriftung in R |\n| `SS`, `DF`, `MS` | Quadratsumme, Freiheitsgrade, mittlere Quadratsumme | wie `Sum Sq`, `Df`, `Mean Sq` |\n| `F` | Teststatistik | wie `F value` |\n| `p_unc` | unkorrigierter p-Wert | wie `Pr(>F)` |\n| `np2` | partielles Eta-Quadrat | in R nur über ein Zusatzpaket |\n\nZwei Unterschiede in der Handhabung. Beide Funktionen erwarten die Daten in langer\nForm, also eine Zeile je Beobachtung mit einer Gruppenspalte, `aov()` über eine\nFormel und `pg.anova` über Spaltennamen. Und `pg.anova` liefert die Effektstärke\ngleich mit, während `summary()` nur die Quadratsummen zeigt, aus denen sie sich\nberechnen lässt.\n\n## Interpretationsfallen\n\n- **Ein signifikanter F-Wert sagt nicht, welche Gruppen sich unterscheiden.**\n  Dafür braucht es die paarweisen Vergleiche mit Korrektur.\n- **Paarweise t-Tests ohne Korrektur** erhöhen die Rate falscher Alarme, siehe\n  [multiples Testen](../inferenz/multiples-testen.qmd).\n- **Nicht signifikant ist kein Nachweis von Gleichheit.** Das gilt hier wie beim\n  t-Test.\n- **Der QQ-Plot gehört zu den Residuen.** Die Rohwerte dürfen mehrgipflig sein,\n  das ist gerade der gesuchte Effekt.\n- **Ungleiche Varianzen bei ungleichen Gruppengrössen sind der gefährliche Fall.**\n  Im Zweifel die Welch-Variante rechnen.\n- **Post-hoc-Vergleiche nur nach vorab festgelegtem Plan.** Wer erst die Daten\n  ansieht und dann die interessanten Paare auswählt, prüft nicht mehr fair.\n- **Eta-Quadrat ist keine Relevanz.** Ein hoher Anteil erklärter Streuung sagt\n  nichts darüber, ob der Unterschied fachlich zählt.\n\n## Ergebnis berichten\n\nVorlage für den Ergebnissatz:\n\n> [Zielgrösse] unterscheidet sich zwischen den [Anzahl] Gruppen:\n> F([df zwischen], [df innerhalb]) = [F], p = [p], Eta-Quadrat = [Wert].\n> Im paarweisen Vergleich nach [Verfahren] unterscheidet sich [Gruppe] von\n> [Gruppe] um [Differenz] [Einheit], 95-Prozent-Konfidenzintervall [unten] bis\n> [oben].\n\nImmer genannt werden: Gruppengrössen, Mittelwerte und Streuungen je Gruppe, die\nF-Statistik mit beiden Freiheitsgraden, der p-Wert, eine Effektstärke, das\nverwendete Post-hoc-Verfahren und die Entscheidung zwischen gewöhnlicher und\nWelch-Variante samt Begründung.\n\nBeispiel für eine Ergebnistabelle:\n\n| Gruppe | n | Mittelwert | Standardabweichung |\n|---|---|---|---|\n| A | | | |\n| B | | | |\n| C | | | |\n\n| Quelle | Df | Sum Sq | Mean Sq | F | p |\n|---|---|---|---|---|---|\n| zwischen | | | | | |\n| innerhalb | | | | | |\n\n## Abgrenzung zu verwandten Methoden\n\n| Methode | Wann diese statt der Varianzanalyse |\n|---|---|\n| [t-Test für zwei Stichproben](t-test-zwei-stichproben.qmd) | genau zwei Gruppen |\n| [Nichtparametrische Tests](nichtparametrische-tests.qmd) | kleine, stark schiefe Gruppen oder ordinale Zielgrösse |\n| [Multiple lineare Regression](../regression/multiple-lineare-regression.qmd) | weitere Einflussgrössen sollen konstant gehalten werden |\n| [Chi-Quadrat-Test](chi-quadrat-tests.qmd) | die Zielgrösse ist kategorial |\n| Varianzanalyse mit Messwiederholung | dieselben Objekte mehrfach gemessen |\n| [Effektstärken](../inferenz/effektstaerken.qmd) | die Grösse des Unterschieds steht im Vordergrund |\n\n## Beispiele\n\nAlle Beispiele rechnen mit den fest eingetragenen Daten aus dem Setup-Chunk:\nDurchsatz dreier Standorte in Stück pro Stunde. R und Python sehen dieselben\nZahlen, jeder Wert im Text ist nachprüfbar.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Drei Standorte im Vergleich\n\n#### Frage und Datenlage\n\nAn drei Standorten wird derselbe Artikel gefertigt. Von jedem liegen fünfzehn\nSchichten mit dem erreichten Durchsatz vor. Die Frage lautet: Unterscheiden sich\ndie Standorte, und falls ja, welche?\n\nDie beiden Teilfragen brauchen zwei verschiedene Werkzeuge, und das ist der\nwichtigste Punkt dieser Seite. Die Varianzanalyse beantwortet nur die erste:\nGibt es überhaupt einen Unterschied irgendwo? Welche Standorte sich unterscheiden,\nbeantworten erst die Post-hoc-Vergleiche.\n\n#### Voraussetzungen prüfen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodell <- aov(durchsatz ~ standort, data = werk)\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nboxplot(durchsatz ~ standort, data = werk, xlab = \"Standort\",\n        ylab = \"Durchsatz (Stück/h)\", main = \"Je Standort\")\nqqnorm(residuals(modell), main = \"QQ-Plot der Residuen\")\nqqline(residuals(modell))\npar(mfrow = c(1, 1))\n\ncar::leveneTest(durchsatz ~ standort, data = werk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value Pr(>F)\ngroup  2  0.0837 0.9198\n      42               \n```\n\n\n:::\n\n```{.r .cell-code}\naggregate(durchsatz ~ standort, data = werk,\n          function(x) round(c(n = length(x), mittel = mean(x), sd = sd(x)), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  standort durchsatz.n durchsatz.mittel durchsatz.sd\n1        A      15.000          102.360        5.842\n2        B      15.000          104.453        6.043\n3        C      15.000          111.967        6.967\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 1: Durchsatz je Standort und QQ-Plot der Residuen.](anova_files/figure-html/fig-b1-av-voraussetzungen-r-1.png){#fig-b1-av-voraussetzungen-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmodell = smf.ols(\"durchsatz ~ C(standort)\", data=werk).fit()\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.2))\nachsen[0].boxplot([werk.loc[werk[\"standort\"] == g, \"durchsatz\"] for g in \"ABC\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'whiskers': [<matplotlib.lines.Line2D object at 0x7fb9d463cec0>, <matplotlib.lines.Line2D object at 0x7fb9d44504d0>, <matplotlib.lines.Line2D object at 0x7fb9d4451730>, <matplotlib.lines.Line2D object at 0x7fb9d44519a0>, <matplotlib.lines.Line2D object at 0x7fb9d44528d0>, <matplotlib.lines.Line2D object at 0x7fb9d4452b40>], 'caps': [<matplotlib.lines.Line2D object at 0x7fb9d44501a0>, <matplotlib.lines.Line2D object at 0x7fb9d4450d40>, <matplotlib.lines.Line2D object at 0x7fb9d4451c10>, <matplotlib.lines.Line2D object at 0x7fb9d4451e80>, <matplotlib.lines.Line2D object at 0x7fb9d4452de0>, <matplotlib.lines.Line2D object at 0x7fb9d4453080>], 'boxes': [<matplotlib.lines.Line2D object at 0x7fb9d4653e30>, <matplotlib.lines.Line2D object at 0x7fb9d4451460>, <matplotlib.lines.Line2D object at 0x7fb9d4452630>], 'medians': [<matplotlib.lines.Line2D object at 0x7fb9d4450fe0>, <matplotlib.lines.Line2D object at 0x7fb9d4452120>, <matplotlib.lines.Line2D object at 0x7fb9d4453320>], 'fliers': [<matplotlib.lines.Line2D object at 0x7fb9d4451250>, <matplotlib.lines.Line2D object at 0x7fb9d44523c0>, <matplotlib.lines.Line2D object at 0x7fb9d44535c0>], 'means': []}\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[0].set_xticks([1, 2, 3], list(\"ABC\"))\nachsen[0].set_xlabel(\"Standort\")\nachsen[0].set_ylabel(\"Durchsatz (Stück/h)\")\nachsen[0].set_title(\"Je Standort\")\nsm.qqplot(modell.resid, line=\"s\", ax=achsen[1])\nachsen[1].set_title(\"QQ-Plot der Residuen\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselbe Prüfung in Python.](anova_files/figure-html/fig-b1-av-voraussetzungen-py-1.png){#fig-b1-av-voraussetzungen-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(pg.homoscedasticity(data=werk, dv=\"durchsatz\", group=\"standort\").round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             W    pval  equal_var\nlevene  0.0837  0.9198       True\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(werk.groupby(\"standort\")[\"durchsatz\"].agg([\"count\", \"mean\", \"std\"]).round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          count     mean    std\nstandort                       \nA            15  102.360  5.842\nB            15  104.453  6.043\nC            15  111.967  6.967\n```\n\n\n:::\n:::\n\n\n:::\n\n| Standort | n | Mittelwert | Standardabweichung |\n|---|---|---|---|\n| A | 15 | 102.36 | 5.84 |\n| B | 15 | 104.45 | 6.04 |\n| C | 15 | 111.97 | 6.97 |\n\nDie drei Streuungen liegen zwischen 5.8 und 7.0 und damit dicht beieinander; der\nLevene-Test bestätigt das mit p = 0.92. Ein **grosser** p-Wert ist hier die gute\nNachricht, weil die Nullhypothese dieses Tests die Gleichheit der Varianzen ist.\nDer QQ-Plot der Residuen zeigt keine Auffälligkeit, und die Gruppen sind gleich\ngross. Die klassische Varianzanalyse ist anwendbar.\n\nIm Boxplot ist bereits sichtbar, worauf es hinausläuft: A und B liegen fast\nübereinander, C liegt deutlich höher.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(modell)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nstandort     2  765.6   382.8   9.636 0.000359 ***\nResiduals   42 1668.4    39.7                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\neffectsize::eta_squared(modell)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA\n\nParameter | Eta2 |       95% CI\n-------------------------------\nstandort  | 0.31 | [0.12, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(pg.anova(data=werk, dv=\"durchsatz\", between=\"standort\",\n               detailed=True).round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Source         SS  DF        MS       F   p_unc     np2\n0  standort   765.6013   2  382.8007  9.6364  0.0004  0.3145\n1    Within  1668.4267  42   39.7244     NaN     NaN     NaN\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nDie klassische Ausgabe der Varianzanalyse ist eine Tabelle mit zwei Zeilen. Sie\nzerlegt die gesamte Streuung des Durchsatzes in zwei Teile.\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| `Df` Standort | 2 | Freiheitsgrade zwischen den Gruppen | Anzahl Gruppen minus eins. |\n| `Df` Residuals | 42 | Freiheitsgrade innerhalb | Gesamtzahl der Messungen minus Anzahl Gruppen, also 45 minus 3. |\n| `Sum Sq` Standort | 765.6 | Streuung **zwischen** den Standorten | Wie weit die drei Gruppenmittelwerte vom Gesamtmittelwert abweichen. |\n| `Sum Sq` Residuals | 1668.4 | Streuung **innerhalb** der Standorte | Wie weit die einzelnen Schichten von ihrem eigenen Gruppenmittelwert abweichen. Das ist die Zufallsstreuung, gegen die verglichen wird. |\n| `Mean Sq` Standort | 382.8 | Quadratsumme geteilt durch Freiheitsgrade | 765.6 geteilt durch 2. |\n| `Mean Sq` Residuals | 39.7 | dasselbe für die Residuen | 1668.4 geteilt durch 42. Die Wurzel daraus, rund 6.3 Stück pro Stunde, ist die typische Schwankung einer Schicht. |\n| `F value` | 9.636 | Verhältnis der beiden mittleren Quadrate | 382.8 geteilt durch 39.7. Die Streuung zwischen den Standorten ist knapp zehnmal so gross wie die zufällige Streuung innerhalb. Bei völlig gleichen Standorten läge F im Mittel bei etwa 1. |\n| `Pr(>F)` | 0.00036 | p-Wert des Gesamttests | Irgendwo zwischen den drei Standorten besteht ein Unterschied. Welche es sind, sagt diese Zeile **nicht**. |\n| `Eta2` | 0.3145 | Anteil der erklärten Streuung | 765.6 geteilt durch 2434.0. Rund 31 Prozent der Durchsatzschwankung gehen auf den Standort zurück, der Rest auf alles andere. Anhaltspunkte: 0.01 klein, 0.06 mittel, 0.14 gross. |\n\n::: {.note-box}\n$\\eta^2$ ist dieselbe Zahl wie das Bestimmtheitsmass einer Regression auf\ndenselben Daten, siehe Beispiel 4. Die Varianzanalyse ist kein eigenes\nVerfahren, sondern eine andere Darstellung eines linearen Modells.\n:::\n\n#### Post-hoc: welche Standorte unterscheiden sich?\n\nDer Gesamttest sagt nur, dass es irgendwo einen Unterschied gibt. Für die Frage,\nzwischen welchen Standorten, braucht es paarweise Vergleiche mit Korrektur für\n[multiples Testen](../inferenz/multiples-testen.qmd). Ohne Korrektur läge die\nWahrscheinlichkeit eines falschen Alarms bei drei Vergleichen nicht bei 5, sondern\nbei bis zu rund 14 Prozent.\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(modell)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = durchsatz ~ standort, data = werk)\n\n$standort\n        diff       lwr      upr     p adj\nB-A 2.093333 -3.497983  7.68465 0.6373364\nC-A 9.606667  4.015350 15.19798 0.0004249\nC-B 7.513333  1.922017 13.10465 0.0060618\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(pg.pairwise_tukey(data=werk, dv=\"durchsatz\", between=\"standort\").round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   A  B    mean_A    mean_B    diff      se       T  p_tukey  hedges\n0  A  B  102.3600  104.4533 -2.0933  2.3014 -0.9096   0.6373 -0.3427\n1  A  C  102.3600  111.9667 -9.6067  2.3014 -4.1742   0.0004 -1.4539\n2  B  C  104.4533  111.9667 -7.5133  2.3014 -3.2646   0.0061 -1.1210\n```\n\n\n:::\n:::\n\n\n:::\n\n| Vergleich | Differenz | 95-Prozent-Intervall | p (korrigiert) | Lesart |\n|---|---|---|---|---|\n| B gegen A | 2.09 | -3.50 bis 7.68 | 0.637 | Kein nachweisbarer Unterschied. Das Intervall enthält die Null und lässt Unterschiede in beide Richtungen zu. |\n| C gegen A | 9.61 | 4.02 bis 15.20 | 0.0004 | Deutlich. Standort C fertigt im Mittel rund zehn Stück pro Stunde mehr als A. |\n| C gegen B | 7.51 | 1.92 bis 13.10 | 0.0061 | Ebenfalls deutlich, wenn auch knapper. |\n\nDamit ist die eigentliche Frage beantwortet, und die Antwort ist präziser als\n\"die Standorte unterscheiden sich\": **C hebt sich von den beiden anderen ab, A\nund B unterscheiden sich nicht nachweisbar.**\n\nDie p-Werte sind korrigiert, das heisst sie sind grösser als ein einzelner\nt-Test ergäbe. Genau das ist beabsichtigt: Wer drei Vergleiche anstellt, hat drei\nGelegenheiten für einen falschen Alarm, und die Korrektur bezahlt dafür mit\netwas Schärfe.\n\n#### Interpretation und Ergebnissatz\n\nBerichtet werden beide Ebenen. Der Gesamttest rechtfertigt, dass überhaupt\npaarweise verglichen wurde; die paarweisen Intervalle sagen, worin der\nUnterschied besteht und wie gross er ist.\n\nOb zehn Stück pro Stunde viel sind, entscheidet die Sache: Bei rund 105 Stück\nsind das etwa neun Prozent, über eine Schicht gerechnet also ein spürbarer\nBetrag. Der nächste Schritt wäre nicht ein weiterer Test, sondern die Frage,\nworan es liegt.\n\n> Der Durchsatz unterscheidet sich zwischen den drei Standorten\n> (F(2, 42) = 9.64, p < 0.001, $\\eta^2$ = 0.31). Post-hoc nach Tukey liegt\n> Standort C über A (Differenz 9.6 Stück/h, 95-Prozent-Konfidenzintervall 4.0\n> bis 15.2, p < 0.001) und über B (7.5 Stück/h, 1.9 bis 13.1, p = 0.006); A und\n> B unterscheiden sich nicht nachweisbar (2.1 Stück/h, -3.5 bis 7.7, p = 0.64).\n> Varianzhomogenität war gegeben (Levene p = 0.92), n = 15 je Standort.\n\n### Beispiel 2: Kein nachweisbarer Unterschied\n\n#### Frage und Datenlage\n\nDieselbe Fragestellung an drei anderen Standorten, wieder je fünfzehn Schichten.\nDas Beispiel zeigt, wie ein Nullbefund in der Varianzanalyse aussieht und warum\ndanach **keine** Post-hoc-Vergleiche folgen.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodell_ohne <- aov(durchsatz ~ standort, data = werk_ohne)\nsummary(modell_ohne)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)\nstandort     2   84.1   42.04   0.864  0.429\nResiduals   42 2044.4   48.68               \n```\n\n\n:::\n\n```{.r .cell-code}\neffectsize::eta_squared(modell_ohne)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA\n\nParameter | Eta2 |       95% CI\n-------------------------------\nstandort  | 0.04 | [0.00, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n\n```{.r .cell-code}\naggregate(durchsatz ~ standort, data = werk_ohne,\n          function(x) round(c(mittel = mean(x), sd = sd(x)), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  standort durchsatz.mittel durchsatz.sd\n1        A          101.753        6.887\n2        B          103.827        5.895\n3        C          105.067        7.990\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(pg.anova(data=werk_ohne, dv=\"durchsatz\", between=\"standort\",\n               detailed=True).round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Source         SS  DF       MS       F  p_unc     np2\n0  standort    84.0724   2  42.0362  0.8636  0.429  0.0395\n1    Within  2044.3600  42  48.6752     NaN    NaN     NaN\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(werk_ohne.groupby(\"standort\")[\"durchsatz\"].agg([\"mean\", \"std\"]).round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             mean    std\nstandort                \nA         101.753  6.887\nB         103.827  5.895\nC         105.067  7.990\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Mittelwerte | 101.75 / 103.83 / 105.07 | Die Spanne beträgt 3.3 Stück pro Stunde. |\n| `Sum Sq` Standort | 84.1 | Die Streuung zwischen den Gruppen ist klein. |\n| `Sum Sq` Residuals | 2044.4 | Die Streuung innerhalb ist rund 24 Mal so gross. |\n| `Mean Sq` Standort / Residuals | 42.0 / 48.7 | Fast gleich gross. Genau das erwartet man, wenn die Gruppen sich nicht unterscheiden: Beide schätzen dann dieselbe Zufallsstreuung. |\n| `F value` | 0.864 | Kleiner als 1. Die Unterschiede zwischen den Standorten sind sogar etwas kleiner, als der Zufall allein erwarten liesse. |\n| `Pr(>F)` | 0.429 | Kein Nachweis. |\n| `Eta2` | 0.0395 | Rund vier Prozent, im Bereich dessen, was bei drei Gruppen und 45 Messungen rein zufällig entsteht. |\n\n::: {.note-box}\nEin F-Wert unter 1 ist kein Fehler und kein Hinweis auf einen \"negativen\nEffekt\". F ist ein Verhältnis zweier Varianzschätzungen und schwankt um 1, wenn\ndie Nullhypothese gilt. Ungefähr die Hälfte aller Nullbefunde liefert deshalb\nF kleiner als 1.\n:::\n\n#### Interpretation und Ergebnissatz\n\nNach diesem Ergebnis folgen **keine** Post-hoc-Vergleiche. Der Gesamttest ist\ndas Eintrittsbillett; ohne ihn paarweise weiterzusuchen, bis sich ein Paar\nfindet, ist genau der Fehler, gegen den die Varianzanalyse gebaut wurde.\n\nUnd wie bei jedem Nullbefund gilt: Nicht nachweisbar ist nicht dasselbe wie\ngleich. Bei fünfzehn Schichten je Standort und einer Streuung von rund 7 Stück\npro Stunde bleiben Unterschiede von mehreren Stück durchaus vereinbar; die\nTukey-Intervalle würden das zeigen, wenn man sie berechnete.\n\n> Zwischen den drei Standorten ist kein Unterschied im Durchsatz nachweisbar\n> (F(2, 42) = 0.86, p = 0.43, $\\eta^2$ = 0.04, n = 15 je Standort). Auf\n> paarweise Vergleiche wurde verzichtet, da der Gesamttest nicht signifikant\n> ist. Ein Nachweis der Gleichwertigkeit ist damit nicht erbracht.\n\n### Beispiel 3: Ungleiche Varianzen kippen das Ergebnis\n\n#### Frage und Datenlage\n\nDrei Standorte mit sehr verschiedenen Gruppengrössen und sehr verschiedener\nStreuung: zehn Schichten mit sehr gleichmässigem Betrieb, zwanzig mit stark\nschwankendem, dreissig mit mittlerem. Diese Kombination aus ungleichen\nGruppengrössen und ungleichen Varianzen ist der Fall, in dem die klassische\nVarianzanalyse versagt.\n\n#### Voraussetzungen prüfen\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mar = c(4, 4, 3, 1))\nboxplot(durchsatz ~ standort, data = werk_streuung, xlab = \"Standort\",\n        ylab = \"Durchsatz (Stück/h)\", main = \"Je Standort\")\n\ncar::leveneTest(durchsatz ~ standort, data = werk_streuung)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value    Pr(>F)    \ngroup  2  17.488 1.196e-06 ***\n      57                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\naggregate(durchsatz ~ standort, data = werk_streuung,\n          function(x) round(c(n = length(x), sd = sd(x)), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  standort durchsatz.n durchsatz.sd\n1        A      10.000        1.953\n2        B      20.000       13.595\n3        C      30.000        3.905\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: sehr unterschiedliche Streuung je Standort.](anova_files/figure-html/fig-b3-av-voraussetzungen-r-1.png){#fig-b3-av-voraussetzungen-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, achse = plt.subplots(figsize=(7, 3.2))\nachse.boxplot([werk_streuung.loc[werk_streuung[\"standort\"] == g, \"durchsatz\"]\n               for g in \"ABC\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'whiskers': [<matplotlib.lines.Line2D object at 0x7fb9d32e80e0>, <matplotlib.lines.Line2D object at 0x7fb9d32e8350>, <matplotlib.lines.Line2D object at 0x7fb9d3297170>, <matplotlib.lines.Line2D object at 0x7fb9d44abcb0>, <matplotlib.lines.Line2D object at 0x7fb9d32e9880>, <matplotlib.lines.Line2D object at 0x7fb9d32e9b20>], 'caps': [<matplotlib.lines.Line2D object at 0x7fb9d32e85c0>, <matplotlib.lines.Line2D object at 0x7fb9d32e8830>, <matplotlib.lines.Line2D object at 0x7fb9d32608f0>, <matplotlib.lines.Line2D object at 0x7fb9d32e8e60>, <matplotlib.lines.Line2D object at 0x7fb9d32e9dc0>, <matplotlib.lines.Line2D object at 0x7fb9d32ea060>], 'boxes': [<matplotlib.lines.Line2D object at 0x7fb9d3297ef0>, <matplotlib.lines.Line2D object at 0x7fb9d3295bb0>, <matplotlib.lines.Line2D object at 0x7fb9d32e95e0>], 'medians': [<matplotlib.lines.Line2D object at 0x7fb9d32e8ad0>, <matplotlib.lines.Line2D object at 0x7fb9d32e9100>, <matplotlib.lines.Line2D object at 0x7fb9d32ea2d0>], 'fliers': [<matplotlib.lines.Line2D object at 0x7fb9d32e8d10>, <matplotlib.lines.Line2D object at 0x7fb9d32e9370>, <matplotlib.lines.Line2D object at 0x7fb9d32ea570>], 'means': []}\n```\n\n\n:::\n\n```{.python .cell-code}\nachse.set_xticks([1, 2, 3], list(\"ABC\"))\nachse.set_xlabel(\"Standort\")\nachse.set_ylabel(\"Durchsatz (Stück/h)\")\nachse.set_title(\"Je Standort\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselbe Prüfung in Python.](anova_files/figure-html/fig-b3-av-voraussetzungen-py-1.png){#fig-b3-av-voraussetzungen-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(pg.homoscedasticity(data=werk_streuung, dv=\"durchsatz\",\n                          group=\"standort\").round(6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                W      pval  equal_var\nlevene  17.487693  0.000001      False\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(werk_streuung.groupby(\"standort\")[\"durchsatz\"].agg([\"count\", \"std\"]).round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          count     std\nstandort               \nA            10   1.953\nB            20  13.595\nC            30   3.905\n```\n\n\n:::\n:::\n\n\n:::\n\n| Standort | n | Standardabweichung |\n|---|---|---|\n| A | 10 | 1.95 |\n| B | 20 | 13.60 |\n| C | 30 | 3.91 |\n\nStandort B streut siebenmal so stark wie A, und die Gruppen sind unterschiedlich\ngross. Der Levene-Test liefert p = 0.0000012, also einen klaren Befund gegen die\nVarianzhomogenität. Damit ist die Voraussetzung der klassischen Varianzanalyse\nverletzt, und zwar in der ungünstigsten Konstellation: Die grösste Streuung\ngehört nicht zur grössten Gruppe.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(aov(durchsatz ~ standort, data = werk_streuung))    # klassisch\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)\nstandort     2    330  164.88   2.356  0.104\nResiduals   57   3988   69.97               \n```\n\n\n:::\n\n```{.r .cell-code}\noneway.test(durchsatz ~ standort, data = werk_streuung,\n            var.equal = FALSE)                              # Welch\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne-way analysis of means (not assuming equal variances)\n\ndata:  durchsatz and standort\nF = 19.467, num df = 2.000, denom df = 31.906, p-value = 2.977e-06\n```\n\n\n:::\n\n```{.r .cell-code}\nkruskal.test(durchsatz ~ standort, data = werk_streuung)    # rangbasiert\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  durchsatz by standort\nKruskal-Wallis chi-squared = 10.421, df = 2, p-value = 0.005458\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(pg.anova(data=werk_streuung, dv=\"durchsatz\",\n               between=\"standort\").round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Source  ddof1  ddof2       F   p_unc     np2\n0  standort      2     57  2.3564  0.1039  0.0764\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pg.welch_anova(data=werk_streuung, dv=\"durchsatz\",\n                     between=\"standort\").round(6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Source  ddof1     ddof2          F     p_unc       np2\n0  standort      2  31.90607  19.466812  0.000003  0.076367\n```\n\n\n:::\n\n```{.python .cell-code}\nh_wert, h_p = stats.kruskal(\n    *[werk_streuung.loc[werk_streuung[\"standort\"] == g, \"durchsatz\"]\n      for g in \"ABC\"])\nprint(\"Kruskal-Wallis  H =\", round(h_wert, 4), \" p =\", round(h_p, 6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKruskal-Wallis  H = 10.4214  p = 0.005458\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Verfahren | Teststatistik | p-Wert | Wie das zu lesen ist |\n|---|---|---|---|\n| Klassische Varianzanalyse | F(2, 57) = 2.356 | 0.104 | Kein Nachweis. Dieses Ergebnis ist nicht vertrauenswürdig, weil die Voraussetzung verletzt ist. |\n| Welch-Varianzanalyse | F(2, 31.9) = 19.467 | 0.0000030 | Ein klarer Befund auf denselben Daten. |\n| Kruskal-Wallis | H(2) = 10.421 | 0.0055 | Ebenfalls signifikant, rangbasiert und damit gegen die Streuungsunterschiede robust. |\n\nDie Erklärung steht in der Konstruktion des F-Werts. Der Nenner der klassischen\nVarianzanalyse ist eine **gemeinsame** Schätzung der Zufallsstreuung über alle\nGruppen hinweg. Standort B mit seiner Streuung von 13.6 zieht diese gemeinsame\nSchätzung nach oben und macht damit auch die Unterschiede zwischen A und C\nunsichtbar, obwohl diese beiden Gruppen sehr gleichmässig messen.\n\nDie Welch-Variante schätzt die Streuung je Gruppe getrennt und gewichtet\nentsprechend. Sie zahlt dafür mit gebrochenen Freiheitsgraden, hier 31.9 statt\n57, und findet den Unterschied trotzdem.\n\n::: {.note-box}\nDie Welch-Variante ist bei ungleichen Gruppengrössen der sicherere Standardfall,\ngenau wie beim [t-Test für zwei Stichproben](t-test-zwei-stichproben.qmd). Sie\nkostet fast nichts, wenn die Varianzen tatsächlich gleich sind, und rettet das\nErgebnis, wenn sie es nicht sind. In R ist sie über `oneway.test()` zu haben,\nnicht über `aov()`.\n:::\n\n#### Interpretation und Ergebnissatz\n\nDie Wahl fällt an der Voraussetzungsprüfung, also am Levene-Test und am Boxplot,\nund sie fällt vor dem Blick auf die p-Werte. Hier führt sie zur Welch-Variante.\n\nBemerkenswert ist der Nebenbefund: Die Streuung selbst ist ein Ergebnis. Ein\nStandort, dessen Durchsatz zwischen 74 und 131 Stück schwankt, hat ein anderes\nProblem als einen zu niedrigen Mittelwert, und dieses Problem findet kein\nMittelwertvergleich.\n\n> Die Varianzhomogenität ist deutlich verletzt (Levene p < 0.001;\n> Standardabweichungen 1.95, 13.60 und 3.91 bei n = 10, 20 und 30), weshalb die\n> Welch-Variante verwendet wurde. Der Durchsatz unterscheidet sich zwischen den\n> Standorten (F(2, 31.9) = 19.47, p < 0.001). Die klassische Varianzanalyse\n> hätte den Unterschied nicht gefunden (F(2, 57) = 2.36, p = 0.10). Zusätzlich\n> auffällig ist die stark erhöhte Streuung an Standort B.\n\n### Beispiel 4: Dieselbe Rechnung als Regression\n\n#### Frage und Datenlage\n\nDie Daten aus Beispiel 1, diesmal als lineares Modell gerechnet. Das Beispiel\nzeigt, dass Varianzanalyse und Regression nicht zwei Verfahren sind, sondern zwei\nAusgabeformate desselben Modells.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear <- lm(durchsatz ~ standort, data = werk)\nsummary(linear)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = durchsatz ~ standort, data = werk)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11.1533  -3.4600   0.0333   3.7467  19.8333 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  102.360      1.627  62.899  < 2e-16 ***\nstandortB      2.093      2.301   0.910 0.368235    \nstandortC      9.607      2.301   4.174 0.000147 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.303 on 42 degrees of freedom\nMultiple R-squared:  0.3145,\tAdjusted R-squared:  0.2819 \nF-statistic: 9.636 on 2 and 42 DF,  p-value: 0.0003594\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(linear)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: durchsatz\n          Df Sum Sq Mean Sq F value    Pr(>F)    \nstandort   2  765.6  382.80  9.6364 0.0003594 ***\nResiduals 42 1668.4   39.72                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nlinear = smf.ols(\"durchsatz ~ C(standort)\", data=werk).fit()\nprint(linear.summary().tables[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n====================================================================================\n                       coef    std err          t      P>|t|      [0.025      0.975]\n------------------------------------------------------------------------------------\nIntercept          102.3600      1.627     62.899      0.000      99.076     105.644\nC(standort)[T.B]     2.0933      2.301      0.910      0.368      -2.551       6.738\nC(standort)[T.C]     9.6067      2.301      4.174      0.000       4.962      14.251\n====================================================================================\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"F =\", round(linear.fvalue, 4), \" p =\", round(linear.f_pvalue, 8),\n      \" R^2 =\", round(linear.rsquared, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nF = 9.6364  p = 0.00035943  R^2 = 0.3145\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Bedeutung | Wie er zu lesen ist |\n|---|---|---|---|\n| `(Intercept)` | 102.36 | Mittelwert der Referenzgruppe | Das ist exakt der Mittelwert von Standort A. R wählt die erste Faktorstufe als Referenz, hier alphabetisch A. |\n| `standortB` | 2.09 | Differenz B minus A | Dieselbe Zahl wie im Tukey-Vergleich B gegen A. |\n| `standortC` | 9.61 | Differenz C minus A | Ebenso. |\n| `Pr(>|t|)` für `standortB` | 0.368 | p-Wert dieses Vergleichs | **Nicht** derselbe wie bei Tukey (dort 0.637), weil hier keine Korrektur für multiples Testen erfolgt. |\n| `F-statistic` | 9.636 auf 2 und 42 df | Gesamttest des Modells | Exakt der F-Wert der Varianzanalyse. |\n| `Multiple R-squared` | 0.3145 | Anteil erklärter Streuung | Exakt das $\\eta^2$ der Varianzanalyse. |\n| `anova(linear)` | dieselbe Tabelle wie `summary(aov(...))` | | Beide Ausgaben stammen aus demselben angepassten Modell. |\n\n#### Interpretation und Ergebnissatz\n\nDrei Dinge folgen daraus, und alle drei sind praktisch nützlich.\n\n**Erstens** ist die Wahl zwischen `aov()` und `lm()` eine Frage der Darstellung,\nnicht des Verfahrens. `aov()` zeigt die Zerlegung der Streuung, `lm()` zeigt die\nDifferenzen zu einer Referenzgruppe. Wen die Grösse der Unterschiede interessiert,\nist mit der Regressionsausgabe besser bedient.\n\n**Zweitens** erklärt es, warum der [t-Test für zwei Stichproben](t-test-zwei-stichproben.qmd)\nein Sonderfall ist: Bei zwei Gruppen hat das Modell einen einzigen Koeffizienten,\nund dann gilt F gleich t im Quadrat.\n\n**Drittens** öffnet es den Weg zu allem, was die Varianzanalyse allein nicht\nkann. Weitere Einflussgrössen, metrische Kovariaten, Wechselwirkungen: Sobald das\nModell als Regression geschrieben ist, kommen sie einfach als weitere Terme\ndazu, siehe [multiple lineare Regression](../regression/multiple-lineare-regression.qmd).\n\nDie Voreinstellung der Referenzgruppe verdient Aufmerksamkeit: R nimmt die erste\nFaktorstufe, also die alphabetisch erste. Wer eine inhaltlich sinnvolle\nReferenz braucht, etwa den Hauptstandort, setzt sie mit `relevel()`\nbeziehungsweise über `Treatment(reference=...)` in der Formel. Sonst berichtet\nman Differenzen zu einer Gruppe, die nur durch ihren Anfangsbuchstaben\nausgezeichnet ist.\n\n> Ein lineares Modell mit dem Standort als Faktor liefert dieselben Ergebnisse\n> wie die Varianzanalyse (F(2, 42) = 9.64, p < 0.001, R² = 0.31 entspricht\n> $\\eta^2$). Gegenüber Standort A liegt B um 2.1 Stück/h höher (p = 0.37) und C\n> um 9.6 Stück/h (p < 0.001); die p-Werte sind hier unkorrigiert und deshalb\n> kleiner als die Tukey-Werte.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nDie Varianzanalyse ergibt p = 0.002. Welche Aussage ist zulässig?\n\n- [ ] Alle drei Gruppen unterscheiden sich voneinander ~ Die Alternative lautet\n      nur, dass mindestens eine abweicht.\n- [x] Mindestens eine Gruppe weicht von den übrigen ab ~ Richtig. Welche das ist,\n      beantwortet erst ein paarweiser Vergleich mit Korrektur.\n- [ ] Die grösste beobachtete Differenz ist signifikant ~ Das ist eine eigene\n      Frage, und wer sie nach dem Blick auf die Daten stellt, prüft nicht mehr\n      fair.\n:::\n\n::: {.quiz}\nDrei Gruppen sollen verglichen werden. Warum nicht einfach drei t-Tests?\n\n- [x] Weil die Rate falscher Alarme mit der Anzahl Vergleiche steigt ~ Richtig.\n      Bei drei unabhängigen Vergleichen auf dem Fünf-Prozent-Niveau liegt die\n      Wahrscheinlichkeit für mindestens einen falschen Alarm bereits bei rund\n      vierzehn Prozent.\n- [ ] Weil der t-Test nur bei Normalverteilung gilt ~ Diese Annahme trifft die\n      Varianzanalyse genauso.\n- [ ] Weil t-Tests bei drei Gruppen nicht rechenbar sind ~ Rechenbar sind sie,\n      nur die Fehlerkontrolle stimmt nicht.\n:::\n\n::: {.quiz}\nDer QQ-Plot der Rohwerte zeigt drei Gipfel. Ist die Voraussetzung verletzt?\n\n- [ ] Ja, die Werte sind nicht normalverteilt ~ Geprüft wird nicht die\n      Gesamtverteilung der Rohwerte.\n- [x] Nein, geprüft werden die Residuen ~ Richtig. Verschiedene\n      Gruppenmittelwerte erzeugen genau dieses Bild; die Annahme betrifft die\n      Abweichungen vom jeweiligen Gruppenmittel.\n- [ ] Nein, die Annahme ist bei mehr als zwei Gruppen unnötig ~ Sie gilt weiter,\n      nur bezieht sie sich auf die Residuen.\n:::\n\n::: {.quiz}\nEine Gruppe mit zehn Beobachtungen streut dreimal so stark wie eine mit dreissig.\nWas folgt?\n\n- [ ] Nichts, die Varianzanalyse ist robust ~ Robust ist sie bei gleichen\n      Gruppengrössen; hier sind sie ungleich.\n- [x] Die Welch-Variante rechnen und sie berichten ~ Richtig. Ungleiche Varianzen\n      zusammen mit ungleichen Gruppengrössen verfehlen das Niveau, und die\n      Richtung des Fehlers hängt davon ab, wo die grosse Streuung sitzt.\n- [ ] Die kleine Gruppe entfernen ~ Das ändert die Fragestellung und wirft Daten\n      weg.\n:::\n\n## Verlinkte Ressourcen\n\n- [OpenIntro Statistics, Kapitel zur Varianzanalyse](https://www.openintro.org/book/os/)\n- [R-Dokumentation zu `aov`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/aov.html)\n- [R-Dokumentation zu `oneway.test`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/oneway.test.html)\n- [pingouin: anova](https://pingouin-stats.org/build/html/generated/pingouin.anova.html)\n- [pingouin: welch_anova](https://pingouin-stats.org/build/html/generated/pingouin.welch_anova.html)\n- [Prüfverteilungen: t, Chi-Quadrat und F](../wahrscheinlichkeit/pruefverteilungen.qmd) — die F-Verteilung und der Zusammenhang F = t²\n",
    "supporting": [
      "anova_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}