{
  "hash": "a42af63188d64174f8c7db2caf5b8f2c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Zeitreihen: Grundlagen\"\ndescription: \"Trend, Saison und Rest, Zerlegung und was daran ablesbar ist.\"\ncategories: [\"Zeitreihen\", \"Interpretation\", \"R\", \"Python\"]\nquelle: [\"STATDA\"]\nseitentyp: konzept\nstand: fertig\norder: 10\n---\n\n\n\n\n\n## Kernideen\n\n- Die **Reihenfolge** der Beobachtungen ist Information, nicht Zufall.\n- Die Annahme unabhängiger Beobachtungen fällt weg, und mit ihr viele\n  Standardverfahren — insbesondere jede naive Korrelation zwischen zwei Reihen.\n- Eine Zeitreihe zerfällt in Trend, Saison und Rest.\n- Additiv oder multiplikativ ist eine Entscheidung, die man an der Grafik trifft.\n- Der Rest soll strukturlos sein; ist er es nicht, fehlt dem Modell etwas.\n- Aggregationsebene und Zeitraum bestimmen, was man überhaupt sehen kann.\n- Die Zerlegung ist **beschreibend**. Sie sagt, wie sich die Reihe aufteilen\n  lässt, nicht warum.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Datum und Zeit](../../daten/datum-zeit.qmd) für den Umgang mit\nZeitstempeln und [Lage- und Streuungsmasse](../grundlagen/lage-streuungsmasse.qmd).\nWas danach kommt, ist die [Stationarität](stationaritaet-acf-pacf.qmd) als\nVoraussetzung für Modelle.\n:::\n\n### Was Zeitreihen von anderen Daten unterscheidet\n\nBei einer Querschnittserhebung ist die Reihenfolge der Zeilen beliebig. Bei einer\nZeitreihe trägt sie die Information: Der Wert von heute hängt mit dem von gestern\nzusammen. Damit fällt die Unabhängigkeitsannahme, auf der die meisten Verfahren\ndieser Sammlung beruhen.\n\nZwei praktische Folgen:\n\n| Folge | Warum |\n|---|---|\n| Standardfehler sind zu klein | Aufeinanderfolgende Werte enthalten teilweise dieselbe Information; die effektive Stichprobengrösse ist kleiner als $n$. |\n| Korrelationen sind irreführend | Zwei Reihen mit Trend korrelieren fast immer hoch, ohne jeden inhaltlichen Zusammenhang. Beispiel 5 rechnet das durch. |\n\n### Die drei Bestandteile\n\n| Bestandteil | Was er beschreibt | Woran erkennbar |\n|---|---|---|\n| Trend | langfristige Richtung | die Reihe steigt oder fällt über Jahre |\n| Saison | Muster mit fester Periode | dieselbe Form in jedem Jahr, Quartal, Wochentag |\n| Rest | was übrig bleibt | soll strukturlos um null schwanken |\n\nManche Reihen haben zusätzlich einen **Zyklus**: Auf und Ab ohne feste Periode,\netwa Konjunkturwellen. Der Unterschied zur Saison ist die Vorhersagbarkeit der\nLänge — eine Saison kommt immer im Dezember, ein Zyklus irgendwann in den\nnächsten Jahren.\n\n### Additiv oder multiplikativ\n\nBei additiver Struktur bleibt die Saisonschwankung über die Jahre gleich gross,\nbei multiplikativer wächst sie mit dem Niveau.\n\n$$\\text{additiv: } y_t = T_t + S_t + R_t \\qquad \\text{multiplikativ: } y_t = T_t \\cdot S_t \\cdot R_t$$\n\nDie Entscheidung fällt am Bild: Werden die Zacken mit steigendem Niveau höher, ist\ndie Struktur multiplikativ. Eine Logarithmierung macht daraus eine additive, weil\naus dem Produkt eine Summe wird:\n\n$$\\ln y_t = \\ln T_t + \\ln S_t + \\ln R_t$$\n\nDas ist der übliche Weg, weil danach alle Verfahren für additive Reihen anwendbar\nsind. Beispiel 4 zeigt es an Zahlen.\n\n### Die Zerlegung mit gleitenden Mitteln\n\nDas klassische Verfahren (`decompose()` beziehungsweise `seasonal_decompose()`)\narbeitet in drei Schritten:\n\n1. **Trend** über ein zentriertes gleitendes Mittel der Periodenlänge. Bei\n   gerader Periode wird es zweimal geglättet, damit es zentriert bleibt — bei\n   zwölf Monaten also mit den Gewichten $\\tfrac{1}{2}, 1, \\dots, 1, \\tfrac{1}{2}$\n   geteilt durch 12.\n2. **Saison** als Mittelwert der trendbereinigten Werte je Monat, anschliessend\n   so verschoben, dass die Figur im Mittel null ergibt.\n3. **Rest** als das, was nach Abzug von Trend und Saison bleibt.\n\nDaraus folgen zwei Eigenschaften, die man kennen muss: Am Rand fehlt der Trend\nfür je eine halbe Periode, und die Saisonfigur ist in **jedem** Jahr identisch.\nGenau diese Starrheit behebt STL, siehe Beispiel 3.\n\n### Was man aus der Zerlegung nicht ablesen darf\n\nDie Zerlegung ist beschreibend. Sie sagt, wie sich die Reihe in Bestandteile\naufteilen lässt, und nicht, warum. Insbesondere:\n\n- Ein Trend ist keine Ursache und keine Garantie für die Zukunft.\n- Die Saisonfigur ist ein Mittel über die beobachteten Jahre; ein einzelnes\n  ungewöhnliches Jahr verzerrt sie.\n- Der Rest enthält alles, was das Verfahren nicht kennt, also auch echte\n  Ereignisse wie einen Streik oder eine Preisänderung.\n\n### Aggregationsebene und Zeitraum\n\nBeides entscheidet, was sichtbar ist. Tagesdaten zeigen Wochenmuster, die in\nMonatsdaten verschwinden. Ein Zeitraum von zwei Jahren erlaubt keine Aussage über\nSaisonalität, weil zwei Wiederholungen kein Muster belegen. Als Faustregel\nbraucht eine Saisonschätzung mindestens drei, besser vier vollständige Perioden.\n\nUmgekehrt kann eine zu feine Ebene Muster erzeugen, die inhaltlich nicht\ninteressieren: Wer Tagesdaten auf Trend untersucht, kämpft mit Wochenenden und\nFeiertagen.\n\n## Beispiele\n\nDie Beispiele 1 bis 3 arbeiten mit einer konstruierten Absatzreihe: 72\nMonatswerte ab Januar 2020, ein linearer Trend von 500 mit 4 Einheiten Zuwachs je\nMonat, eine Jahressaison und ein Rest mit Streuung 20. Weil die Bestandteile\nbekannt sind, lässt sich prüfen, was die Zerlegung davon zurückgewinnt.\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Die Reihe ansehen\n\n#### Frage und Datenlage\n\nVor jeder Rechnung steht der Zeitplot. Er beantwortet vier Fragen auf einmal:\nGibt es einen Trend, gibt es Saison, ist die Struktur additiv oder\nmultiplikativ, und gibt es Ausreisser oder Brüche?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\n\nplot(absatz, xlab = \"Jahr\", ylab = \"Absatz\", main = \"Zeitplot\", lwd = 1.5)\n\n# Saisonplot: jedes Jahr eine Linie\nmatrix_jahre <- matrix(as.numeric(absatz), nrow = 12)\nmatplot(1:12, matrix_jahre, type = \"l\", lty = 1, lwd = 1.5,\n        col = hcl.colors(6, \"Blues 3\"),\n        xlab = \"Monat\", ylab = \"Absatz\", main = \"Saisonplot\")\nlegend(\"topright\", legend = 2020:2025, col = hcl.colors(6, \"Blues 3\"),\n       lwd = 1.5, bty = \"n\", cex = 0.7)\npar(mfrow = c(1, 1))\n\n# Spannweite je Jahr: waechst sie mit dem Niveau?\nround(rbind(mittel = apply(matrix_jahre, 2, mean),\n            spannweite = apply(matrix_jahre, 2, function(x) diff(range(x)))), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            [,1]  [,2]  [,3]  [,4] [,5]  [,6]\nmittel     525.8 582.4 621.1 670.2  725 775.8\nspannweite 154.0 187.0 141.0 149.0  147 105.0\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 1: links die Reihe im Zeitverlauf, rechts jedes Jahr als eigene Linie über die Monate.](zeitreihen-grundlagen_files/figure-html/fig-b1-zr-r-1.png){#fig-b1-zr-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\njahre = absatz.groupby(absatz.index.year)\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.6))\nachsen[0].plot(absatz.index, absatz.values, lw=1.5, color=\"#2166ac\")\nachsen[0].set_xlabel(\"Jahr\")\nachsen[0].set_ylabel(\"Absatz\")\nachsen[0].set_title(\"Zeitplot\")\n\nfarben = plt.cm.Blues(np.linspace(0.4, 0.95, 6))\nfor (jahr, werte), farbe in zip(jahre, farben):\n    achsen[1].plot(range(1, 13), werte.values, lw=1.5, color=farbe, label=jahr)\nachsen[1].set_xlabel(\"Monat\")\nachsen[1].set_title(\"Saisonplot\")\nachsen[1].legend(frameon=False, fontsize=7)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 1: dieselben beiden Darstellungen in Python.](zeitreihen-grundlagen_files/figure-html/fig-b1-zr-py-1.png){#fig-b1-zr-py width=100%}\n:::\n\n```{.python .cell-code}\nprint(pd.DataFrame({\n    \"mittel\": jahre.mean().round(1),\n    \"spannweite\": jahre.apply(lambda g: g.max() - g.min()).round(1),\n}).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             2020   2021   2022   2023   2024   2025\nmittel      525.8  582.4  621.1  670.2  725.0  775.8\nspannweite  154.0  187.0  141.0  149.0  147.0  105.0\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Jahr | 2020 | 2021 | 2022 | 2023 | 2024 | 2025 |\n|---|---|---|---|---|---|---|\n| Mittel | 525.8 | 582.4 | 621.1 | 670.2 | 725.0 | 775.8 |\n| Spannweite | 154 | 187 | 141 | 149 | 147 | 105 |\n\n| Frage | Antwort aus dem Bild | Woran |\n|---|---|---|\n| **Trend?** | Ja, steigend | Der Zeitplot steigt über sechs Jahre um rund 250 Einheiten; die Jahresmittel wachsen gleichmässig um etwa 50 je Jahr, also gut 4 je Monat. |\n| **Saison?** | Ja, mit Jahresperiode | Im Saisonplot liegen alle sechs Linien **parallel** übereinander: dieselbe Form, nur nach oben verschoben. Das ist die klarste Art, Saisonalität zu sehen — im Zeitplot verdeckt der Trend sie leicht. |\n| **Additiv oder multiplikativ?** | Additiv | Das Mittel steigt um 48 Prozent, die Spannweite schwankt dabei ohne Richtung um 150 herum (154, 187, 141, 149, 147, 105). Bei multiplikativer Struktur müsste sie **mitwachsen** — in Beispiel 4 tut sie das, von 179 auf 284. |\n| **Ausreisser oder Brüche?** | Keine | Kein einzelner Punkt fällt aus dem Muster, kein Niveausprung. |\n\n::: {.note-box}\n**Der Saisonplot ist die wichtigste Grafik dieses Beispiels.** Im Zeitplot sind\nTrend und Saison überlagert und schwer zu trennen; legt man die Jahre\nübereinander, wird die Saisonfigur unmittelbar sichtbar — und ebenso, ob sie sich\nüber die Jahre verändert (Beispiel 3) oder ob ein einzelnes Jahr aus der Reihe\nfällt.\n:::\n\n#### Interpretation\n\nAlle Voraussetzungen für eine additive Zerlegung sind erfüllt: klarer Trend,\nstabile Saison, keine Brüche, sechs vollständige Perioden.\n\n### Beispiel 2: Die Zerlegung Schritt für Schritt\n\n#### Frage und Datenlage\n\nWas macht `decompose()` genau, und wie gut trifft es die eingebauten\nBestandteile?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nzerlegung <- decompose(absatz, type = \"additive\")\nplot(zerlegung)\n\n# Der Trendwert bei t = 13 von Hand: zentriertes gleitendes Mittel\ngewichte <- c(0.5, rep(1, 11), 0.5) / 12\nround(c(von_hand = sum(as.numeric(absatz)[7:19] * gewichte),\n        aus_decompose = zerlegung$trend[13]), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     von_hand aus_decompose \n      559.625       559.625 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Saisonfigur gegen die eingebauten Werte\neingebaut <- 60 * sin(2 * pi * (1:12) / 12) + 25 * cos(2 * pi * (1:12) / 12)\nround(rbind(geschaetzt = zerlegung$figure,\n            eingebaut = eingebaut,\n            differenz = zerlegung$figure - eingebaut), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           [,1] [,2] [,3] [,4] [,5]  [,6]  [,7]  [,8]  [,9] [,10] [,11] [,12]\ngeschaetzt 46.5 75.5 66.1 42.2 -1.2 -24.7 -59.3 -72.9 -57.7 -37.9  -0.8  24.2\neingebaut  51.7 64.5 60.0 39.5  8.3 -25.0 -51.7 -64.5 -60.0 -39.5  -8.3  25.0\ndifferenz  -5.2 11.0  6.1  2.7 -9.6   0.3  -7.6  -8.4   2.3   1.5   7.5  -0.8\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(summe_figur = sum(zerlegung$figure),\n        fehlende_trendwerte = sum(is.na(zerlegung$trend)),\n        rest_sd = sd(zerlegung$random, na.rm = TRUE)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        summe_figur fehlende_trendwerte             rest_sd \n              0.000              12.000              20.685 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 2: Zerlegung der Absatzreihe in Trend, Saison und Rest.](zeitreihen-grundlagen_files/figure-html/fig-b2-zr-r-3.png){#fig-b2-zr-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nzerlegung = seasonal_decompose(absatz, model=\"additive\", period=12)\nabb = zerlegung.plot()\nabb.set_size_inches(7, 4.4)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 2: dieselbe Zerlegung mit statsmodels.](zeitreihen-grundlagen_files/figure-html/fig-b2-zr-py-1.png){#fig-b2-zr-py width=100%}\n:::\n\n```{.python .cell-code}\ngewichte = np.r_[0.5, np.ones(11), 0.5] / 12\nprint(\"Trend bei t = 13 von Hand:  \",\n      round(float((absatz.values[6:19] * gewichte).sum()), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrend bei t = 13 von Hand:   559.625\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Trend bei t = 13 aus statsmodels:\",\n      round(float(zerlegung.trend.iloc[12]), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrend bei t = 13 aus statsmodels: 559.625\n```\n\n\n:::\n\n```{.python .cell-code}\nfigur = zerlegung.seasonal[:12].values\neingebaut = (60 * np.sin(2 * np.pi * np.arange(1, 13) / 12)\n             + 25 * np.cos(2 * np.pi * np.arange(1, 13) / 12))\nprint(pd.DataFrame({\"geschaetzt\": figur.round(1),\n                    \"eingebaut\": eingebaut.round(1),\n                    \"differenz\": (figur - eingebaut).round(1)},\n                   index=range(1, 13)).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              1     2     3     4    5   ...    8     9     10   11    12\ngeschaetzt  46.5  75.5  66.1  42.2 -1.2  ... -72.9 -57.7 -37.9 -0.8  24.2\neingebaut   51.7  64.5  60.0  39.5  8.3  ... -64.5 -60.0 -39.5 -8.3  25.0\ndifferenz   -5.2  11.0   6.1   2.7 -9.6  ...  -8.4   2.3   1.5  7.5  -0.8\n\n[3 rows x 12 columns]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Summe der Figur:\", round(float(figur.sum()), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSumme der Figur: 0.0\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"fehlende Trendwerte:\", int(zerlegung.trend.isna().sum()))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfehlende Trendwerte: 12\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Rest, Standardabweichung:\", round(float(zerlegung.resid.std(ddof=1)), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRest, Standardabweichung: 20.69\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nDie geschätzte Saisonfigur gegen die eingebauten Werte:\n\n| Monat | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| geschätzt | 46.5 | 75.5 | 66.1 | 42.2 | -1.2 | -24.7 | -59.3 | -72.9 | -57.7 | -37.9 | -0.8 | 24.2 |\n| eingebaut | 51.7 | 64.5 | 60.0 | 39.5 | 8.3 | -25.0 | -51.7 | -64.5 | -60.0 | -39.5 | -8.3 | 25.0 |\n| Differenz | -5.2 | **11.0** | 6.1 | 2.7 | **-9.5** | 0.3 | -7.6 | **-8.4** | 2.3 | 1.6 | 7.5 | -0.8 |\n\nDie Schwankung der Spannweite ist selbst lehrreich: Bei nur zwölf Werten je Jahr\nist der Abstand zwischen Maximum und Minimum eine sehr unruhige Kennzahl. Was\nzählt, ist die **Richtung** über die Jahre, nicht der einzelne Wert.\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Trend bei $t = 13$ | **559.625**, von Hand wie aus der Funktion | Das zentrierte gleitende Mittel über 13 Werte mit halbem Gewicht an den Enden. Die 13 Werte reichen von Juli 2020 bis Juli 2021 — der Trendwert für Januar 2021 nutzt also ein halbes Jahr Zukunft. |\n| fehlende Trendwerte | **12** | Sechs am Anfang, sechs am Ende. Bei einer Periode von 12 fehlt an jedem Rand eine halbe Periode. **Deshalb taugt `decompose()` nicht zur Vorhersage** — für den aktuellsten Monat gibt es keinen Trend. |\n| Summe der Saisonfigur | **0.000** | Per Konstruktion. Die Figur wird so verschoben, dass sie sich über ein Jahr aufhebt; das Niveau steckt vollständig im Trend. |\n| Abweichungen der Figur | bis zu **11 Einheiten** | Die geschätzte Figur trifft die eingebaute nicht genau — bei sechs Wiederholungen und einem Rest mit Streuung 20 ist der Standardfehler je Monat etwa $20/\\sqrt{6} = 8.2$. Die Abweichungen liegen in dieser Grössenordnung. |\n| Rest, Standardabweichung | **20.685** | Sehr nahe an der eingebauten 20. Die Zerlegung hat also im Wesentlichen alles gefunden, was es zu finden gab. |\n\n::: {.note-box}\n**Die Abweichungen in der Saisonfigur sind kein Fehler des Verfahrens, sondern\nStichprobenzufall.** Sie sind aber ein Grund, eine Saisonfigur nicht auf die\nNachkommastelle zu deuten: Dass der Februar mit 75.5 statt 64.5 geschätzt wird,\nheisst nicht, dass der Februar besonders stark ist — es heisst, dass sechs\nFebruare für eine genaue Schätzung wenig sind.\n\nDie Faustregel \"mindestens drei, besser vier Perioden\" ist eine **Untergrenze für\nErkennbarkeit**, keine für Genauigkeit.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Eine additive Zerlegung der Monatsreihe (72 Werte, Periode 12) ergibt einen\n> gleichmässig steigenden Trend von rund 529 auf 773 und eine Saisonfigur mit\n> Maximum im Februar (+75.5) und Minimum im August (-72.9). Der Rest streut mit\n> einer Standardabweichung von 20.7 ohne erkennbares Muster.\n\n### Beispiel 3: Wenn sich die Saison ändert\n\n#### Frage und Datenlage\n\n`decompose()` erzwingt in jedem Jahr **dieselbe** Saisonfigur. Was passiert, wenn\nsich die Saison über die Jahre tatsächlich verändert?\n\nKonstruiert wird eine Reihe über acht Jahre, deren Saisonamplitude von rund 30\nauf 90 wächst und deren Hochpunkt sich langsam verschiebt.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2 <- 96\nt2 <- 1:m2\namplitude <- 30 + 60 * (t2 - 1) / (m2 - 1)\nphase <- 2 * pi * t2 / 12 - 0.5 * (t2 - 1) / (m2 - 1) * pi\nwandel <- ts(round(600 + 2 * t2 + amplitude * sin(phase) +\n                     normalwerte(1414, m2, 0, 12)),\n             start = c(2018, 1), frequency = 12)\n\nzerl_klassisch <- decompose(wandel, type = \"additive\")\nzerl_stl <- stl(wandel, s.window = 7, robust = TRUE)\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nplot(zerl_klassisch$seasonal, ylab = \"Saisonanteil\", xlab = \"Jahr\",\n     main = \"decompose: starr\")\nplot(zerl_stl$time.series[, \"seasonal\"], ylab = \"Saisonanteil\", xlab = \"Jahr\",\n     main = \"STL: veränderlich\")\npar(mfrow = c(1, 1))\n\n# Saisonspanne je Jahr\nspanne <- function(x) tapply(as.numeric(x), rep(2018:2025, each = 12),\n                             function(v) round(diff(range(v)), 1))\nrbind(decompose = spanne(zerl_klassisch$seasonal),\n      stl = spanne(zerl_stl$time.series[, \"seasonal\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           2018  2019  2020  2021  2022  2023  2024  2025\ndecompose 111.3 111.3 111.3 111.3 111.3 111.3 111.3 111.3\nstl       106.7 107.7 110.3 115.1 117.3 130.6 136.8 140.1\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(rest_sd_decompose = sd(zerl_klassisch$random, na.rm = TRUE),\n        rest_sd_stl = sd(zerl_stl$time.series[, \"remainder\"])), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrest_sd_decompose       rest_sd_stl \n            21.24             16.81 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 3: links die klassische Zerlegung mit starrer Saison, rechts STL mit sich änderndem Muster.](zeitreihen-grundlagen_files/figure-html/fig-b3-zr-r-3.png){#fig-b3-zr-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nm2 = 96\nt2 = np.arange(1, m2 + 1)\namplitude = 30 + 60 * (t2 - 1) / (m2 - 1)\nphase = 2 * np.pi * t2 / 12 - 0.5 * (t2 - 1) / (m2 - 1) * np.pi\nwandel = pd.Series(\n    np.round(600 + 2 * t2 + amplitude * np.sin(phase)\n             + normalwerte(1414, m2, 0, 12)),\n    index=pd.date_range(\"2018-01-01\", periods=m2, freq=\"MS\"))\n\nzerl_klassisch = seasonal_decompose(wandel, model=\"additive\", period=12)\nzerl_stl = STL(wandel, period=12, robust=True).fit()\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.6))\nachsen[0].plot(wandel.index, zerl_klassisch.seasonal, color=\"#b2182b\")\nachsen[0].set_title(\"decompose: starr\")\nachsen[1].plot(wandel.index, zerl_stl.seasonal, color=\"#2166ac\")\nachsen[1].set_title(\"STL: veränderlich\")\nfor achse in achsen:\n    achse.set_xlabel(\"Jahr\")\n    achse.set_ylabel(\"Saisonanteil\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 3: dieselbe Gegenüberstellung in Python.](zeitreihen-grundlagen_files/figure-html/fig-b3-zr-py-1.png){#fig-b3-zr-py width=100%}\n:::\n\n```{.python .cell-code}\ndef spanne(reihe):\n    return reihe.groupby(reihe.index.year).apply(\n        lambda g: round(float(g.max() - g.min()), 1))\n\n\nprint(pd.DataFrame({\"decompose\": spanne(zerl_klassisch.seasonal),\n                    \"stl\": spanne(zerl_stl.seasonal)}).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            2018   2019   2020   2021   2022   2023   2024   2025\ndecompose  111.3  111.3  111.3  111.3  111.3  111.3  111.3  111.3\nstl         96.6   92.9  105.6  115.4  120.8  133.9  164.0  193.8\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Rest sd decompose:\", round(float(zerl_klassisch.resid.std(ddof=1)), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRest sd decompose: 21.24\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Rest sd STL:      \", round(float(zerl_stl.resid.std(ddof=1)), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRest sd STL:       11.17\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nDie Spannweite der geschätzten Saisonfigur, Jahr für Jahr:\n\n| Jahr | 2018 | 2019 | 2020 | 2021 | 2022 | 2023 | 2024 | 2025 |\n|---|---|---|---|---|---|---|---|---|\n| `decompose` | 111.3 | 111.3 | 111.3 | 111.3 | 111.3 | 111.3 | 111.3 | 111.3 |\n| **STL, R** | 106.7 | 107.7 | 110.3 | 115.1 | 117.3 | 130.6 | 136.8 | **140.1** |\n| **STL, Python** | 96.6 | 92.9 | 105.6 | 115.4 | 120.8 | 133.9 | 164.0 | **193.8** |\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| `decompose`: achtmal **111.3** | | Nicht ähnlich, sondern **identisch** — die Figur wird einmal geschätzt und in jedem Jahr wiederholt. Der Wert ist der Mittelwert über acht Jahre und beschreibt kein einziges davon richtig. |\n| STL: von rund 100 auf 140 bis 194 wachsend | | Das Verfahren folgt der tatsächlichen Entwicklung. |\n| R und Python weichen dabei ab | 140.1 gegen 193.8 im letzten Jahr | Beide verwenden ein Glättungsfenster von 7 für die Saison, aber verschiedene Voreinstellungen für die inneren Iterationen und die Trendglättung. Das Fenster steuert, **wie schnell** sich die Figur ändern darf — R glättet hier stärker. Wer STL berichtet, nennt Fensterbreite und Umgebung dazu. |\n| Rest sd `decompose` | **21.24** in beiden | |\n| Rest sd STL | **16.81** in R, **11.17** in Python | In beiden Fällen deutlich kleiner. Was `decompose()` nicht in die Saison stecken kann, landet im Rest — dort steht also Struktur, die keine sein sollte. |\n\nDamit ist auch die Diagnose beschrieben: **Ein Rest, dessen Schwankungsbreite sich\nüber die Jahre systematisch ändert, ist das Erkennungszeichen einer\nSaisonfigur, die nicht mehr passt.** Bei `decompose()` wächst der Betrag des\nRests gegen Ende der Reihe deutlich an, bei STL bleibt er ungefähr gleich.\n\n::: {.note-box}\n**Was STL zusätzlich kann und was es kostet.** STL glättet Trend und Saison\ngetrennt mit lokalen Regressionen; die Fensterbreite `s.window` beziehungsweise\n`seasonal` steuert, **wie schnell** sich die Saisonfigur ändern darf. Ein kleines\nFenster folgt jedem Jahr, ein grosses nähert sich der starren Figur an;\n`s.window = \"periodic\"` in R erzwingt sie ganz.\n\nDer Preis ist eine Entscheidung mehr — und die Gefahr, mit einem zu kleinen\nFenster Rauschen in die Saison zu ziehen. Mit `robust = TRUE` werden Ausreisser\nzudem heruntergewichtet, statt die Figur zu verbiegen.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Saisonamplitude wächst über den Beobachtungszeitraum um rund 40 Prozent.\n> Eine klassische Zerlegung mit starrer Saisonfigur bildet das nicht ab und\n> verschiebt die Differenz in den Rest (Standardabweichung 21.2 gegenüber 16.8\n> bei STL mit `s.window = 7`); berichtet wird die STL-Zerlegung.\n\n### Beispiel 4: Multiplikativ und der Logarithmus\n\n#### Frage und Datenlage\n\nEine Umsatzreihe, die um 1.2 Prozent je Monat wächst und deren Saisonschwankung\n**prozentual** konstant ist. Was tut eine additive Zerlegung damit, und was\nändert der Logarithmus?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3 <- 72\nt3 <- 1:m3\numsatz <- ts(round(500 * 1.012^t3 *\n                     (1 + 0.12 * sin(2 * pi * t3 / 12) +\n                        0.05 * cos(2 * pi * t3 / 12)) *\n                     exp(normalwerte(1313, m3, 0, 0.03))),\n             start = c(2020, 1), frequency = 12)\n\npar(mfrow = c(2, 1), mar = c(3, 4, 2, 1))\nplot(umsatz, ylab = \"Umsatz\", main = \"Rohdaten\", lwd = 1.5)\nplot(log(umsatz), ylab = \"log(Umsatz)\", main = \"logarithmiert\", lwd = 1.5)\npar(mfrow = c(1, 1))\n\n# Spannweite je Jahr, roh und logarithmiert\njahr <- rep(2020:2025, each = 12)\nround(rbind(\n  roh = tapply(as.numeric(umsatz), jahr, function(v) diff(range(v))),\n  logarithmiert = tapply(log(as.numeric(umsatz)), jahr,\n                         function(v) diff(range(v)))\n), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                2020    2021    2022    2023    2024    2025\nroh           179.00 159.000 218.000 225.000 218.000 284.000\nlogarithmiert   0.32   0.254   0.295   0.274   0.226   0.262\n```\n\n\n:::\n\n```{.r .cell-code}\n# Reste beider Zerlegungen\nround(c(rest_sd_additiv = sd(decompose(umsatz, \"additive\")$random, na.rm = TRUE),\n        rest_sd_multiplikativ = sd(decompose(umsatz, \"multiplicative\")$random,\n                                   na.rm = TRUE)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      rest_sd_additiv rest_sd_multiplikativ \n              23.0107                0.0227 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 4: oben die Reihe mit wachsenden Zacken, unten dieselbe Reihe logarithmiert.](zeitreihen-grundlagen_files/figure-html/fig-b4-zr-r-3.png){#fig-b4-zr-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nm3 = 72\nt3 = np.arange(1, m3 + 1)\numsatz = pd.Series(\n    np.round(500 * 1.012 ** t3\n             * (1 + 0.12 * np.sin(2 * np.pi * t3 / 12)\n                + 0.05 * np.cos(2 * np.pi * t3 / 12))\n             * np.exp(normalwerte(1313, m3, 0, 0.03))),\n    index=pd.date_range(\"2020-01-01\", periods=m3, freq=\"MS\"))\n\nfig, achsen = plt.subplots(2, 1, figsize=(7, 4))\nachsen[0].plot(umsatz.index, umsatz.values, lw=1.5, color=\"#2166ac\")\nachsen[0].set_ylabel(\"Umsatz\")\nachsen[0].set_title(\"Rohdaten\")\nachsen[1].plot(umsatz.index, np.log(umsatz.values), lw=1.5, color=\"#b2182b\")\nachsen[1].set_ylabel(\"log(Umsatz)\")\nachsen[1].set_title(\"logarithmiert\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 4: dieselbe Gegenüberstellung in Python.](zeitreihen-grundlagen_files/figure-html/fig-b4-zr-py-1.png){#fig-b4-zr-py width=100%}\n:::\n\n```{.python .cell-code}\nnach_jahr = umsatz.groupby(umsatz.index.year)\nlog_umsatz = np.log(umsatz)\nprint(pd.DataFrame({\n    \"roh\": nach_jahr.apply(lambda g: g.max() - g.min()).round(1),\n    \"logarithmiert\": log_umsatz.groupby(log_umsatz.index.year)\n                     .apply(lambda g: g.max() - g.min()).round(3),\n}).T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2020     2021     2022     2023     2024     2025\nroh            179.00  159.000  218.000  225.000  218.000  284.000\nlogarithmiert    0.32    0.254    0.295    0.274    0.226    0.262\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Rest sd additiv:      \",\n      round(float(seasonal_decompose(umsatz, model=\"additive\",\n                                     period=12).resid.std(ddof=1)), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRest sd additiv:       23.0107\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Rest sd multiplikativ:\",\n      round(float(seasonal_decompose(umsatz, model=\"multiplicative\",\n                                     period=12).resid.std(ddof=1)), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRest sd multiplikativ: 0.0227\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\nSpannweite je Jahr:\n\n| Jahr | 2020 | 2021 | 2022 | 2023 | 2024 | 2025 |\n|---|---|---|---|---|---|---|\n| roh | 179 | 159 | 218 | 225 | 218 | **284** |\n| logarithmiert | 0.320 | 0.254 | 0.295 | 0.274 | 0.226 | **0.262** |\n\n| Ausgabe | Wie sie zu lesen ist |\n|---|---|\n| Roh: 179 wächst auf 284 | Die Zacken werden mit dem Niveau höher — das Erkennungszeichen multiplikativer Struktur. Der Umsatz steigt im selben Zeitraum von rund 520 auf 1200, also um den Faktor 2.3; die Spannweite um den Faktor 1.6. |\n| Logarithmiert: zwischen **0.226 und 0.320**, ohne Richtung | Nach dem Logarithmieren schwankt die Breite nur noch zufällig, statt zu wachsen. Genau das ist der Zweck: Aus einem konstanten **Verhältnis** wird eine konstante **Differenz**. |\n| Rest sd additiv: 23.01 | Auf der Skala der Rohdaten. |\n| Rest sd multiplikativ: 0.0227 | Ein Faktor, kein Betrag: Der Rest schwankt um 2.3 Prozent um den Wert 1. |\n\nDie beiden Reste sind nicht direkt vergleichbar — sie stehen auf verschiedenen\nSkalen. Vergleichbar wird es über die **Struktur** im Rest: Beim additiven Modell\nwächst der Betrag des Rests mit dem Niveau (Korrelation 0.20), beim\nmultiplikativen nicht (-0.11).\n\n::: {.note-box}\n**Zwei Wege, dasselbe zu tun:**\n\n| Weg | Rechnung | Wann |\n|---|---|---|\n| multiplikatives Modell | $y_t = T_t \\cdot S_t \\cdot R_t$ | wenn die Software es anbietet und man auf der Originalskala bleiben will |\n| logarithmieren, dann additiv | $\\ln y_t = \\ln T_t + \\ln S_t + \\ln R_t$ | fast immer besser: Danach sind **alle** Verfahren für additive Reihen anwendbar, inklusive [ARIMA](arima-sarima.qmd) |\n\nDer Preis des Logarithmierens ist die Rücktransformation. $e^{\\hat{y}}$ schätzt\nden **Median**, nicht den Mittelwert der Originalskala; für den Mittelwert braucht\nes eine Korrektur um $e^{\\sigma^2/2}$. Und Nullwerte sind nicht logarithmierbar.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Die Saisonschwankung wächst mit dem Niveau (Spannweite je Jahr von 179 auf 284\n> bei einem Anstieg des Niveaus um den Faktor 2.3); nach Logarithmierung schwankt\n> sie ohne Richtung zwischen 0.23 und 0.32. Modelliert wird deshalb die logarithmierte Reihe mit\n> additiver Zerlegung.\n\n### Beispiel 5: Zwei Reihen mit Trend\n\n#### Frage und Datenlage\n\nZwei Reihen, die inhaltlich nichts miteinander zu tun haben. Beide steigen\nlinear und enthalten unabhängiges Rauschen. Wie hoch ist ihre Korrelation?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreihe_a <- 100 + 2.0 * t + normalwerte(2121, monate, 0, 8)\nreihe_b <- 50 + 1.2 * t + normalwerte(3131, monate, 0, 6)\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nplot(t, reihe_a, type = \"l\", lwd = 1.5, col = \"#2166ac\", ylim = c(0, 260),\n     xlab = \"Monat\", ylab = \"Wert\", main = \"beide Reihen\")\nlines(t, reihe_b, lwd = 1.5, col = \"#b2182b\")\nlegend(\"topleft\", legend = c(\"A\", \"B\"), col = c(\"#2166ac\", \"#b2182b\"),\n       lwd = 1.5, bty = \"n\")\n\nplot(diff(reihe_a), diff(reihe_b), pch = 16, cex = 0.7, col = \"grey30\",\n     xlab = \"Differenz A\", ylab = \"Differenz B\", main = \"nach Differenzenbildung\")\npar(mfrow = c(1, 1))\n\ntest_roh <- cor.test(reihe_a, reihe_b)\ntest_diff <- cor.test(diff(reihe_a), diff(reihe_b))\nround(c(r_roh = test_roh$estimate, p_roh = test_roh$p.value,\n        r_differenzen = test_diff$estimate, p_differenzen = test_diff$p.value), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        r_roh.cor             p_roh r_differenzen.cor     p_differenzen \n           0.9636            0.0000            0.0310            0.7977 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![Beispiel 5: links die beiden Reihen, rechts ihre Monatsdifferenzen gegeneinander.](zeitreihen-grundlagen_files/figure-html/fig-b5-zr-r-3.png){#fig-b5-zr-r width=100%}\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nreihe_a = 100 + 2.0 * t + normalwerte(2121, monate, 0, 8)\nreihe_b = 50 + 1.2 * t + normalwerte(3131, monate, 0, 6)\n\nfig, achsen = plt.subplots(1, 2, figsize=(7, 3.4))\nachsen[0].plot(t, reihe_a, lw=1.5, color=\"#2166ac\", label=\"A\")\nachsen[0].plot(t, reihe_b, lw=1.5, color=\"#b2182b\", label=\"B\")\nachsen[0].set_ylim(0, 260)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(0.0, 260.0)\n```\n\n\n:::\n\n```{.python .cell-code}\nachsen[0].set_xlabel(\"Monat\")\nachsen[0].set_ylabel(\"Wert\")\nachsen[0].set_title(\"beide Reihen\")\nachsen[0].legend(frameon=False)\nachsen[1].scatter(np.diff(reihe_a), np.diff(reihe_b), s=10, color=\"0.3\")\nachsen[1].set_xlabel(\"Differenz A\")\nachsen[1].set_ylabel(\"Differenz B\")\nachsen[1].set_title(\"nach Differenzenbildung\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![Beispiel 5: dieselbe Gegenüberstellung in Python.](zeitreihen-grundlagen_files/figure-html/fig-b5-zr-py-1.png){#fig-b5-zr-py width=100%}\n:::\n\n```{.python .cell-code}\nfor name, x, y in [(\"roh\", reihe_a, reihe_b),\n                   (\"Differenzen\", np.diff(reihe_a), np.diff(reihe_b))]:\n    r, p = stats.pearsonr(x, y)\n    print(f\"{name:12s} r = {r: .4f}   p = {p:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nroh          r =  0.9636   p = 0.0000\nDifferenzen  r =  0.0310   p = 0.7977\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Rechnung | $r$ | p |\n|---|---|---|\n| auf den Rohreihen | **0.964** | **< .001** |\n| auf den Monatsdifferenzen | **0.031** | **0.798** |\n\n| Ausgabe | Wie sie zu lesen ist |\n|---|---|\n| $r = 0.964$ auf den Rohreihen | Ein Wert, der in jeder Querschnittsauswertung als sehr starker Zusammenhang gälte. Hier ist er **vollständig durch die Konstruktion erzeugt**: Beide Reihen steigen, also sind beide früh klein und spät gross. Die Korrelation misst nur das. |\n| $p < .001$ | Der Test macht es nicht besser, sondern schlimmer: Er verleiht dem Artefakt den Anschein von Verlässlichkeit. Seine Voraussetzung — unabhängige Beobachtungen — ist bei Zeitreihen verletzt, der p-Wert also ohnehin nicht gültig. |\n| $r = 0.031$ auf den Differenzen | Nach Entfernen des Trends bleibt nichts übrig. Das ist die richtige Antwort. |\n| $p = 0.798$ | Ebenfalls unauffällig. |\n| Das rechte Streudiagramm | zeigt eine strukturlose Punktwolke — im Gegensatz zu den beiden parallel steigenden Linien links. |\n\n::: {.note-box}\n**Warum die Differenzenbildung hilft:** $\\Delta y_t = y_t - y_{t-1}$ entfernt\neinen linearen Trend vollständig, denn die konstante Steigung fällt beim\nSubtrahieren heraus. Was bleibt, sind die Abweichungen von Monat zu Monat — und\ngenau dort sitzt der Zusammenhang, wenn es einen gibt.\n\n**Warum das nicht die ganze Lösung ist:** Auch differenzierte Reihen können\ngemeinsame Zyklen haben, und die Unabhängigkeitsannahme des Korrelationstests\nbleibt fraglich. Die saubere Behandlung von Zusammenhängen zwischen Zeitreihen\nläuft über Modelle, die die Autokorrelation ausdrücklich abbilden — siehe\n[Stationarität](stationaritaet-acf-pacf.qmd) und\n[ARIMA](arima-sarima.qmd).\n\nUnd der Sonderfall, in dem gerade der gemeinsame Trend echt ist, heisst\n**Kointegration** — dann ist das Differenzieren zu viel des Guten. Erkennbar\ndaran, dass die Differenz der beiden Reihen selbst stationär ist.\n:::\n\n#### Interpretation und Ergebnissatz\n\n> Zwischen den beiden Reihen besteht kein nachweisbarer Zusammenhang: Auf den\n> Monatsdifferenzen beträgt die Korrelation 0.03 (p = .80, n = 71). Die\n> Korrelation der Rohreihen von 0.96 geht vollständig auf den gemeinsamen\n> Aufwärtstrend zurück und ist inhaltlich nicht deutbar.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nEine Monatsreihe zeigt Saisonzacken, die mit dem steigenden Niveau immer höher\nwerden. Was folgt für die Zerlegung?\n\n- [ ] Additive Zerlegung, sie ist der Standard ~ Sie unterstellt konstante\n      Schwankungsbreite und passt hier nicht.\n- [x] Multiplikative Zerlegung, oder additiv nach Logarithmierung ~ Richtig. Wenn\n      die Schwankung mit dem Niveau wächst, ist die Struktur multiplikativ. Das\n      Logarithmieren macht aus dem Produkt eine Summe und erlaubt danach alle\n      Verfahren für additive Reihen.\n- [ ] Die Saison muss vorher entfernt werden ~ Das ist das Ergebnis der\n      Zerlegung, nicht ihre Voraussetzung.\n:::\n\n::: {.quiz}\nIm Rest der Zerlegung schwankt der Betrag über die Jahre systematisch: erst\nklein, später gross. Was heisst das?\n\n- [x] Die Saisonfigur passt nicht mehr, weil sie sich verändert hat ~ Richtig.\n      Was `decompose()` nicht in die starre Figur stecken kann, landet im Rest.\n      STL erlaubt eine Saisonfigur, die sich langsam ändert, und halbiert im\n      Beispiel die Reststreuung.\n- [ ] Das ist normal, der Rest enthält immer Muster ~ Er enthält Rauschen; ein\n      systematisches Muster ist ein Befund.\n- [ ] Die Reihe ist zu kurz ~ Eine kurze Reihe erzeugt kein systematisch\n      wachsendes Restmuster.\n:::\n\n::: {.quiz}\nWarum fehlt der Trend aus `decompose()` an beiden Rändern der Reihe?\n\n- [x] Weil ein zentriertes gleitendes Mittel eine halbe Periode Vergangenheit und\n      Zukunft braucht ~ Richtig. Bei Periode 12 fehlen je sechs Werte. Deshalb\n      liefert das Verfahren gerade für den aktuellsten Monat keinen Trend und\n      taugt nicht zur Vorhersage.\n- [ ] Weil dort zu wenige Beobachtungen vorliegen ~ Die Beobachtungen sind da;\n      es fehlen die Nachbarn, über die gemittelt wird.\n- [ ] Weil die Saison am Rand nicht bestimmbar ist ~ Die Saisonfigur wird über\n      alle Jahre geschätzt und gilt auch am Rand.\n:::\n\n::: {.quiz}\nZwei Reihen mit deutlichem Aufwärtstrend korrelieren mit 0.96 bei p < .001. Was\nfolgt?\n\n- [ ] Ein starker Zusammenhang zwischen den beiden Grössen ~ Der gemeinsame Trend\n      genügt für eine hohe Korrelation, auch ohne jeden inhaltlichen Zusammenhang.\n- [x] Nichts, solange der Trend nicht entfernt ist ~ Richtig. Auf den\n      Monatsdifferenzen bleibt im Beispiel r = 0.03 übrig. Der p-Wert ist\n      zusätzlich ungültig, weil er unabhängige Beobachtungen voraussetzt.\n- [ ] Die Korrelation ist falsch berechnet ~ Sie ist korrekt berechnet und\n      trotzdem inhaltlich wertlos.\n:::\n\n::: {.quiz}\nDie geschätzte Saisonfigur weicht für den Februar um 11 Einheiten von der\ntatsächlichen ab. Ist das ein Problem?\n\n- [x] Nein, bei sechs Jahren ist das die normale Schätzunsicherheit ~ Richtig.\n      Der Standardfehler je Monat ist etwa die Reststreuung geteilt durch die\n      Wurzel aus der Anzahl Jahre, hier rund 8. Eine Saisonfigur ist deshalb\n      nicht auf die Nachkommastelle deutbar.\n- [ ] Ja, die Zerlegung ist fehlerhaft ~ Sie rechnet korrekt; die Unsicherheit\n      steckt in den Daten.\n- [ ] Ja, es hätte multiplikativ gerechnet werden müssen ~ Die\n      Schwankungsbreite ist konstant; additiv ist richtig.\n:::\n\n## Verlinkte Ressourcen\n\n- [Forecasting: Principles and Practice, Kapitel 2 und 3](https://otexts.com/fpp3/)\n- [R-Dokumentation zu `stl`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/stl.html)\n- [statsmodels: Saisonzerlegung](https://www.statsmodels.org/stable/generated/statsmodels.tsa.seasonal.seasonal_decompose.html)\n",
    "supporting": [
      "zeitreihen-grundlagen_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}