{
  "hash": "edf50b8038cf918b458e929b164befc0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Data Wrangling\"\ndescription: \"Filtern, sortieren, gruppieren, umformen und verbinden in beiden Sprachen.\"\ncategories: [\"Data Wrangling\", \"pandas\", \"tidyverse\", \"R\", \"Python\"]\nquelle: [\"PYFR\", \"ESDS\"]\nseitentyp: werkzeug\nstand: entwurf\norder: 30\n---\n\n\n\n\n\n## Kernideen\n\n- **Fünf Verben** decken den grössten Teil der Aufbereitung ab: filtern,\n  auswählen, rechnen, sortieren, zusammenfassen.\n- Die **Pipe** beziehungsweise die Methodenkette bringt die Reihenfolge im\n  Code in die Reihenfolge im Kopf.\n- Gruppieren heisst **aufteilen, rechnen, zusammensetzen**. In R bleibt die\n  Gruppierung nach `summarise` bestehen, und das ist die häufigste Falle.\n- `mutate` nach `group_by` beziehungsweise `transform` behält **alle Zeilen**,\n  `summarise` dampft sie ein.\n- Beim **Klassieren** entscheidet die Wahl des Werkzeugs über die Grenze:\n  `case_when` mit `<` und `cut` teilen den Randwert verschieden zu.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Tidy Data](tidy-data.qmd) für die Zielform und\n[R-Grundlagen](../programmierung/r-grundlagen.qmd) beziehungsweise\n[pandas](../programmierung/pandas.qmd) für die Datenstrukturen. Woher die\nDaten kommen, steht unter [Datenimport](datenimport-formate.qmd), was vorher\nzu prüfen ist unter [Datenqualität](datenqualitaet.qmd).\n:::\n\n### Die fünf Verben\n\nJedes tut genau eine Sache und gibt einen Data Frame zurück. Genau deshalb\nlassen sie sich beliebig aneinanderreihen.\n\n| Verb in dplyr | Frage | pandas |\n|---|---|---|\n| `filter()` | Welche Zeilen interessieren mich? | `.query()`, `.loc[maske]` |\n| `select()` | Welche Spalten brauche ich? | `df[[\"a\", \"b\"]]` |\n| `mutate()` | Welche Spalte fehlt noch? | `.assign()` |\n| `arrange()` | In welcher Reihenfolge? | `.sort_values()` |\n| `summarise()` | Wie fasse ich zusammen? | `.agg()` |\n\n### Die Daten dieser Seite\n\n24 Messungen, zwölf Wochen ab dem 5. Januar 2026, je eine für Bern und Chur,\nmit Verbrauch und Laufzeit. Die Werte sind fest eingetragen, damit R und\nPython dieselben Zahlen zeigen.\n\n### Gruppieren, und was danach noch gruppiert ist\n\n`group_by()` verändert die Daten nicht, es markiert sie. Erst die folgende\nOperation wertet je Gruppe aus, und davon gibt es zwei Sorten:\n\n| nach `group_by` | Ergebnis | Zeilen | pandas |\n|---|---|---|---|\n| `summarise()` | eine Zeile je Gruppe | weniger | `.groupby().agg()` |\n| `mutate()` | Gruppenwert in jeder Zeile | gleich viele | `.groupby().transform()` |\n\nIn R bleibt nach `summarise()` die **äusserste Gruppierung bestehen**. Wer\ndanach weiterrechnet, rechnet unbemerkt je Gruppe statt über alles; `.groups\n= \"drop\"` oder `ungroup()` beendet das. pandas kennt dieses Verhalten nicht,\nlegt die Gruppen dafür in den **Index**, was beim Weiterverarbeiten\nüberrascht; `as_index=False` oder `reset_index()` hilft.\n\n### Klassieren\n\nAus einer Zahl eine Kategorie zu machen, sieht in beiden Sprachen einfach\naus, und die Randwerte entscheiden:\n\n| Werkzeug | Intervall | der Wert 10 bei Grenze 10 |\n|---|---|---|\n| `case_when(wert < 10 ~ ...)` | oben offen | fällt in die **obere** Klasse |\n| `cut(..., right = TRUE)` (R-Vorgabe) | `(a, b]` | fällt in die **untere** Klasse |\n| `pd.cut(..., right=True)` (Vorgabe) | `(a, b]` | fällt in die **untere** Klasse |\n| `pd.cut(..., right=False)` | `[a, b)` | fällt in die obere Klasse |\n\nDie Grenze gehört deshalb in den Text der Auswertung, nicht nur in den Code.\n\n### Kurz nachgeschlagen\n\n| Aufgabe | R | Python |\n|---|---|---|\n| Zeilen filtern | `filter(df, x > 5, g == \"A\")` | `df.query(\"x > 5 and g == 'A'\")` |\n| Spalte berechnen | `mutate(df, y = a / b)` | `df.assign(y=lambda d: d[\"a\"] / d[\"b\"])` |\n| sortieren | `arrange(df, desc(x))` | `df.sort_values(\"x\", ascending=False)` |\n| zusammenfassen je Gruppe | `summarise(.by = g, m = mean(x))` | `df.groupby(\"g\").agg(m=(\"x\", \"mean\"))` |\n| Gruppenwert je Zeile | `mutate(.by = g, s = sum(x))` | `df.groupby(\"g\")[\"x\"].transform(\"sum\")` |\n| Gruppierung lösen | `ungroup()`, `.groups = \"drop\"` | `as_index=False`, `reset_index()` |\n| klassieren | `case_when()`, `cut()` | `np.select()`, `pd.cut()` |\n| verbinden | `left_join(a, b, by = \"id\")` | `a.merge(b, on=\"id\", how=\"left\")` |\n| Zeilen zählen je Gruppe | `count(df, g)` | `df[\"g\"].value_counts()` |\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Die fünf Verben\n\n#### Frage und Datenlage\n\nAus den 24 Messungen: Wie viele Berner Werte liegen über 125? Wie sieht der\nVerbrauch je Laufzeitstunde aus, welches sind die beiden höchsten Werte, und\nwie lautet der Gesamtmittelwert?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(filter(messungen, standort == \"Bern\", verbrauch > 125))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(select(messungen, datum, verbrauch), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       datum verbrauch\n1 2026-01-05     118.2\n2 2026-01-05      96.4\n3 2026-01-12     125.4\n```\n\n\n:::\n\n```{.r .cell-code}\nmit_kennzahl <- mutate(messungen, pro_stunde = round(verbrauch / laufzeit, 2))\nhead(mit_kennzahl$pro_stunde, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  9.46 10.26  8.96 11.37\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(arrange(mit_kennzahl, desc(verbrauch))[, c(\"standort\", \"verbrauch\")], 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  standort verbrauch\n1     Bern     133.2\n2     Bern     130.6\n```\n\n\n:::\n\n```{.r .cell-code}\nsummarise(messungen, n = n(), mittel = round(mean(verbrauch), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   n mittel\n1 24 109.43\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(len(messungen.query(\"standort == 'Bern' and verbrauch > 125\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n4\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(messungen[[\"datum\", \"verbrauch\"]].head(3).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     datum  verbrauch\n2026-01-05      118.2\n2026-01-05       96.4\n2026-01-12      125.4\n```\n\n\n:::\n\n```{.python .cell-code}\nmit_kennzahl = messungen.assign(\n    pro_stunde=lambda d: (d[\"verbrauch\"] / d[\"laufzeit\"]).round(2))\nprint(mit_kennzahl[\"pro_stunde\"].head(4).tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[9.46, 10.26, 8.96, 11.37]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(mit_kennzahl.sort_values(\"verbrauch\", ascending=False)\n      .head(2)[[\"standort\", \"verbrauch\"]].to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstandort  verbrauch\n    Bern      133.2\n    Bern      130.6\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(len(messungen), round(messungen[\"verbrauch\"].mean(), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n24 109.43\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Verb | Ergebnis | Erklärung |\n|---|---|---|\n| `filter` | **4** Zeilen | Bern über 125: die Werte 125.4, 130.6, 128.9 und 133.2. |\n| `select` | zwei Spalten, erste drei Zeilen | Die ersten beiden Zeilen teilen sich das Datum 2026-01-05, je eine pro Standort. |\n| `mutate` | 9.46, 10.26, 8.96, 11.37 | Verbrauch je Laufzeitstunde. Bern und Chur liegen hier nahe beieinander, obwohl der Verbrauch weit auseinanderliegt. |\n| `arrange` | 133.2 und 130.6, beide Bern | die beiden höchsten Werte |\n| `summarise` | n = **24**, Mittel **109.43** | Über beide Standorte zusammen, also eine Zahl, die für keinen der beiden gilt. |\n\n#### Interpretation und Ergebnissatz\n\nDer Gesamtmittelwert von 109.43 ist das Musterbeispiel einer Zahl, die\nrechnerisch stimmt und inhaltlich in die Irre führt: Sie liegt zwischen den\nStandorten und beschreibt keinen von beiden. Erst die Gruppierung in\nBeispiel 2 macht daraus eine brauchbare Aussage. Die abgeleitete Kennzahl\n`pro_stunde` zeigt zugleich, wofür `mutate` da ist: Sie ist die Grösse, die\nman eigentlich vergleichen will.\n\n> Vier Berner Messungen liegen über 125, die höchsten sind 133.2 und 130.6.\n> Der Mittelwert über alle 24 Messungen beträgt 109.43, eine Zahl zwischen\n> den beiden Standorten.\n\n### Beispiel 2: Kette statt Verschachtelung\n\n#### Frage und Datenlage\n\nDer mittlere Verbrauch je Standort, absteigend sortiert. Einmal\nverschachtelt, einmal als Kette.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# von innen nach aussen zu lesen\narrange(summarise(group_by(messungen, standort),\n                  mittel = round(mean(verbrauch), 2)),\n        desc(mittel))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  standort mittel\n  <chr>     <dbl>\n1 Bern      123. \n2 Chur       95.8\n```\n\n\n:::\n\n```{.r .cell-code}\n# dieselbe Rechnung als Kette\nmessungen |>\n  group_by(standort) |>\n  summarise(mittel = round(mean(verbrauch), 2)) |>\n  arrange(desc(mittel))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  standort mittel\n  <chr>     <dbl>\n1 Bern      123. \n2 Chur       95.8\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(messungen\n      .groupby(\"standort\", as_index=False)\n      .agg(mittel=(\"verbrauch\", \"mean\"))\n      .round(2)\n      .sort_values(\"mittel\", ascending=False)\n      .to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstandort  mittel\n    Bern  123.12\n    Chur   95.75\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Standort | Mittel | Erklärung |\n|---|---|---|\n| Bern | **123.12** | 1477.4 / 12 |\n| Chur | **95.75** | 1149.0 / 12 |\n\nBeide R-Fassungen liefern dasselbe. Die verschachtelte liest sich von innen\nnach aussen, also in umgekehrter Reihenfolge zum Ablauf; die Kette steht in\nder Reihenfolge, in der man sie denkt. `|>` reicht das Ergebnis links als\nerstes Argument nach rechts weiter, in pandas übernimmt die Methodenkette\ndieselbe Rolle.\n\n#### Interpretation und Ergebnissatz\n\nDer Abstand zwischen den Standorten beträgt 27.37, der Gesamtmittelwert aus\nBeispiel 1 liegt dazwischen und beschreibt keinen der beiden. Genau deshalb\nist die Gruppierung fast immer der erste Schritt nach dem Filtern.\n\n> Bern verbraucht im Mittel 123.12, Chur 95.75. Verschachtelte Aufrufe und\n> Kette liefern dasselbe Ergebnis, die Kette ist in der Denkreihenfolge\n> geschrieben.\n\n### Beispiel 3: Gruppieren, und was danach noch gruppiert ist\n\n#### Frage und Datenlage\n\nDer Monatsmittelwert je Standort, danach der Mittelwert dieser Monatswerte.\nIn R einmal mit und einmal ohne `.groups = \"drop\"`.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nje_monat <- messungen |>\n  mutate(monat = month(datum)) |>\n  group_by(standort, monat) |>\n  summarise(n = n(), mittel = round(mean(verbrauch), 2), .groups = \"drop\")\nje_monat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  standort monat     n mittel\n  <chr>    <dbl> <int>  <dbl>\n1 Bern         1     4  124. \n2 Bern         2     4  122. \n3 Bern         3     4  124. \n4 Chur         1     4   94.6\n5 Chur         2     4   95.4\n6 Chur         3     4   97.2\n```\n\n\n:::\n\n```{.r .cell-code}\n# Ohne .groups bleibt nach standort gruppiert\nnoch_gruppiert <- messungen |>\n  mutate(monat = month(datum)) |>\n  group_by(standort, monat) |>\n  summarise(n = n(), mittel = round(mean(verbrauch), 2))\n\ngroup_vars(noch_gruppiert)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"standort\"\n```\n\n\n:::\n\n```{.r .cell-code}\nsummarise(noch_gruppiert, gesamt = round(mean(mittel), 2))   # je Standort!\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  standort gesamt\n  <chr>     <dbl>\n1 Bern      123. \n2 Chur       95.8\n```\n\n\n:::\n\n```{.r .cell-code}\nsummarise(ungroup(noch_gruppiert), gesamt = round(mean(mittel), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  gesamt\n   <dbl>\n1   109.\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nje_monat = (messungen\n    .assign(monat=messungen[\"datum\"].dt.month)\n    .groupby([\"standort\", \"monat\"], as_index=False)\n    .agg(n=(\"verbrauch\", \"size\"), mittel=(\"verbrauch\", \"mean\")))\nje_monat[\"mittel\"] = je_monat[\"mittel\"].round(2)\nprint(je_monat.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstandort  monat  n  mittel\n    Bern      1  4  123.80\n    Bern      2  4  121.62\n    Bern      3  4  123.92\n    Chur      1  4   94.62\n    Chur      2  4   95.38\n    Chur      3  4   97.25\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(round(je_monat[\"mittel\"].mean(), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n109.43\n```\n\n\n:::\n\n```{.python .cell-code}\n# Ohne as_index=False landen die Gruppen im Index\nmit_index = messungen.groupby(\"standort\")[\"verbrauch\"].mean()\nprint(type(mit_index).__name__, mit_index.index.name, list(mit_index.index))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries standort ['Bern', 'Chur']\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Standort | Januar | Februar | März | Erklärung |\n|---|---|---|---|---|\n| Bern | 123.80 | 121.62 | 123.92 | je vier Messungen |\n| Chur | 94.62 | 95.38 | 97.25 | Chur steigt über die drei Monate |\n\n| Rechnung | Ergebnis | Erklärung |\n|---|---|---|\n| Mittel der sechs Monatswerte | **109.43** | Weil jede Gruppe gleich viele Messungen hat, stimmt es hier mit dem Gesamtmittel überein. |\n| R ohne `.groups` | `group_vars` meldet **`standort`** | Die Tabelle ist noch nach Standort gruppiert, ohne dass man es ihr ansieht. |\n| zweites `summarise` darauf | **zwei Zeilen**: Bern 123.11, Chur 95.75 | Gefragt war eine Zahl, geliefert werden zwei. Das Ergebnis sieht plausibel aus und beantwortet eine andere Frage. |\n| nach `ungroup()` | eine Zeile: 109.43 | So war es gemeint. |\n| pandas ohne `as_index=False` | eine **Series** mit Index `standort` | Kein Fehler, aber die Gruppen sind keine Spalte mehr. Beim nächsten `merge` fehlt die Spalte, auf die verknüpft werden soll. |\n\n#### Interpretation und Ergebnissatz\n\nBeide Sprachen hinterlassen nach dem Gruppieren einen Zustand, den man\nmitdenken muss: R eine bestehende Gruppierung, pandas einen Index. Beide\nführen zu Ergebnissen, die nicht falsch aussehen. Die Gewohnheit, jede\nZusammenfassung mit `.groups = \"drop\"` beziehungsweise `as_index=False` zu\nschreiben, kostet nichts und erspart die Fehlersuche.\n\n> Die Monatsmittel reichen von 94.62 bis 123.92, ihr Mittel beträgt 109.43.\n> Ohne `.groups = \"drop\"` liefert die zweite Zusammenfassung statt einer Zahl\n> zwei, nämlich 123.11 für Bern und 95.75 für Chur.\n\n### Beispiel 4: Klassieren und der Randwert\n\n#### Frage und Datenlage\n\nDie Werte 5, 10, 50, 100 und 250 sollen in klein (unter 10), mittel (bis 100)\nund gross eingeteilt werden. Was passiert mit den Werten **auf** der Grenze?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwerte <- c(5, 10, 50, 100, 250)\n\ncase_when(werte < 10  ~ \"klein\",\n          werte < 100 ~ \"mittel\",\n          TRUE        ~ \"gross\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"klein\"  \"mittel\" \"mittel\" \"gross\"  \"gross\" \n```\n\n\n:::\n\n```{.r .cell-code}\ncut(werte, breaks = c(-Inf, 10, 100, Inf),\n    labels = c(\"klein\", \"mittel\", \"gross\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] klein  klein  mittel mittel gross \nLevels: klein mittel gross\n```\n\n\n:::\n\n```{.r .cell-code}\ncut(werte, breaks = c(-Inf, 10, 100, Inf),\n    labels = c(\"klein\", \"mittel\", \"gross\"), right = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] klein  mittel mittel gross  gross \nLevels: klein mittel gross\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nwerte = pd.Series([5, 10, 50, 100, 250])\n\nrechts = pd.cut(werte, bins=[-np.inf, 10, 100, np.inf],\n                labels=[\"klein\", \"mittel\", \"gross\"])\nprint(list(zip(werte.tolist(), rechts.astype(str).tolist())))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[(5, 'klein'), (10, 'klein'), (50, 'mittel'), (100, 'mittel'), (250, 'gross')]\n```\n\n\n:::\n\n```{.python .cell-code}\nlinks = pd.cut(werte, bins=[-np.inf, 10, 100, np.inf],\n               labels=[\"klein\", \"mittel\", \"gross\"], right=False)\nprint(list(zip(werte.tolist(), links.astype(str).tolist())))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[(5, 'klein'), (10, 'mittel'), (50, 'mittel'), (100, 'gross'), (250, 'gross')]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Wert | `case_when` mit `<` | `cut` (Vorgabe, `right = TRUE`) | `cut` mit `right = FALSE` |\n|---|---|---|---|\n| 5 | klein | klein | klein |\n| **10** | **mittel** | **klein** | **mittel** |\n| 50 | mittel | mittel | mittel |\n| **100** | **gross** | **mittel** | **gross** |\n| 250 | gross | gross | gross |\n\n`case_when` mit `<` prüft \"kleiner als\" und schiebt den Randwert nach oben.\n`cut` schneidet in der Voreinstellung Intervalle der Form `(a, b]`, also\noben geschlossen, und behält den Randwert unten. pandas verhält sich genau\nwie `cut` in R, samt dem Schalter `right`.\n\n#### Interpretation und Ergebnissatz\n\nZwei Werkzeuge derselben Sprache teilen denselben Wert verschieden zu, und\nkeines davon ist falsch. Bei Altersklassen, Preisstufen oder\nToleranzgrenzen entscheidet genau das darüber, auf welcher Seite ein\nGrenzfall landet. Deshalb gehört die Grenze ausgeschrieben in den Bericht\n(\"bis und mit 100\" gegen \"unter 100\"), und bei einer Übernahme von Code aus\nder anderen Sprache ist sie der erste Punkt zum Nachrechnen.\n\n> Der Wert 10 fällt mit `case_when` in die Klasse mittel, mit `cut` in die\n> Klasse klein; der Wert 100 einmal in gross und einmal in mittel. Mit\n> `right = FALSE` verhält sich `cut` wie `case_when`.\n\n### Beispiel 5: Gruppenwert in jeder Zeile\n\n#### Frage und Datenlage\n\nJede Messung soll ihren Anteil am Verbrauch ihres Standorts bekommen. Die\nTabelle soll dabei **alle 24 Zeilen** behalten.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanteil <- messungen |>\n  mutate(.by = standort,\n         gruppensumme = sum(verbrauch)) |>\n  mutate(anteil = round(verbrauch / gruppensumme * 100, 2))\n\nhead(anteil[, c(\"standort\", \"verbrauch\", \"gruppensumme\", \"anteil\")], 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  standort verbrauch gruppensumme anteil\n1     Bern     118.2       1477.4   8.00\n2     Chur      96.4       1149.0   8.39\n3     Bern     125.4       1477.4   8.49\n4     Chur      92.1       1149.0   8.02\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(anteil)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24\n```\n\n\n:::\n\n```{.r .cell-code}\nanteil |>\n  summarise(.by = standort,\n            summe = sum(verbrauch), anteile = sum(anteil))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  standort  summe anteile\n1     Bern 1477.4  100.01\n2     Chur 1149.0  100.01\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nanteil = messungen.assign(\n    gruppensumme=messungen.groupby(\"standort\")[\"verbrauch\"].transform(\"sum\"))\nanteil[\"anteil\"] = (anteil[\"verbrauch\"] / anteil[\"gruppensumme\"] * 100).round(2)\n\nprint(anteil.head(4)[[\"standort\", \"verbrauch\", \"gruppensumme\", \"anteil\"]]\n      .to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstandort  verbrauch  gruppensumme  anteil\n    Bern      118.2        1477.4    8.00\n    Chur       96.4        1149.0    8.39\n    Bern      125.4        1477.4    8.49\n    Chur       92.1        1149.0    8.02\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(len(anteil))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n24\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(anteil.groupby(\"standort\")[\"verbrauch\"].sum().round(1).to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'Bern': 1477.4, 'Chur': 1149.0}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(anteil.groupby(\"standort\")[\"anteil\"].sum().round(2).to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'Bern': 100.01, 'Chur': 100.01}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | Wert | Erklärung |\n|---|---|---|\n| Zeilen | **24**, unverändert | `mutate(.by = ...)` beziehungsweise `transform` fasst nicht zusammen, es verteilt den Gruppenwert auf jede Zeile. |\n| Gruppensumme Bern | **1477.4** | steht in jeder der zwölf Berner Zeilen |\n| Gruppensumme Chur | **1149.0** | |\n| erste Berner Messung | 118.2, Anteil **8.00 Prozent** | 118.2 / 1477.4 |\n| erste Churer Messung | 96.4, Anteil **8.39 Prozent** | 96.4 / 1149.0. Der kleinere Verbrauch ist der grössere Anteil, weil die Bezugsgrösse kleiner ist. |\n| Summe der Anteile | je **100.01** | Nicht exakt 100, weil jeder Anteil einzeln auf zwei Stellen gerundet wurde. |\n\n#### Interpretation und Ergebnissatz\n\nDas ist der Unterschied zwischen den beiden Gruppenoperationen: `summarise`\nbeantwortet \"wie ist die Gruppe insgesamt\", `mutate` mit `.by`\nbeziehungsweise `transform` beantwortet \"wie steht diese Zeile zu ihrer\nGruppe\". Der Anteil zeigt auch, warum ein Vergleich absoluter Werte zwischen\nverschieden grossen Gruppen selten trägt. Und die Summe 100.01 ist die\nübliche Erinnerung: Gerundete Anteile addieren sich nicht zwangsläufig zu\n100, was in einer Berichtstabelle vorab zu klären ist.\n\n> Alle 24 Zeilen bleiben erhalten, jede trägt die Summe ihres Standorts\n> (Bern 1477.4, Chur 1149.0) und ihren Anteil daran. Die erste Churer Messung\n> hat mit 8.39 Prozent den grösseren Anteil als die erste Berner mit 8.00\n> Prozent, obwohl sie absolut kleiner ist.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nWarum liefert `summarise` ohne vorheriges `group_by` genau eine Zeile?\n\n- [x] Weil ohne Gruppierung die ganze Tabelle eine einzige Gruppe ist ~\n      Richtig. Die Zusammenfassung dampft jede Gruppe auf eine Zeile ein, hier\n      also alles auf eine, wie die 109.43 in Beispiel 1.\n- [ ] Weil `summarise` immer nur eine Zeile zurückgeben kann ~ Mit\n      Gruppierung gibt es eine Zeile je Gruppe.\n- [ ] Weil die übrigen Zeilen verworfen werden ~ Verworfen wird nichts, sie\n      gehen in die Berechnung ein.\n:::\n\n::: {.quiz}\nNach `group_by(standort, monat)` und `summarise` wird ohne `.groups = \"drop\"`\nein zweites Mal zusammengefasst. Was passiert?\n\n- [ ] Ein Fehler, weil die Tabelle schon zusammengefasst ist ~ Es gibt keinen\n      Fehler, und das ist gerade das Problem.\n- [x] Die zweite Zusammenfassung rechnet je Standort statt über alle ~\n      Richtig. In Beispiel 3 kommen zwei Zeilen (123.11 und 95.75) statt der\n      erwarteten einen. Abhilfe: `.groups = \"drop\"` oder `ungroup()`.\n- [ ] Das Ergebnis ist identisch ~ Es unterscheidet sich, sobald es mehr als\n      einen Standort gibt.\n:::\n\n::: {.quiz}\nEine Auswertung soll für jede Zeile den Anteil am Gruppentotal ausweisen.\nWelche Operation ist richtig?\n\n- [ ] `summarise` je Gruppe ~ Das ergäbe eine Zeile je Gruppe, die einzelnen\n      Messungen wären weg.\n- [x] `mutate` mit `.by` beziehungsweise `groupby().transform()` ~ Richtig.\n      Der Gruppenwert wird auf jede Zeile verteilt, die Zeilenzahl bleibt\n      gleich.\n- [ ] Ein `left_join` der Gruppensummen ~ Funktioniert auch, ist aber der\n      Umweg für dasselbe Ergebnis.\n:::\n\n::: {.quiz}\nEine Klassierung mit `case_when(wert < 10 ~ \"klein\", ...)` wird nach pandas\nals `pd.cut(..., bins=[-inf, 10, ...])` übertragen. Worauf ist zu achten?\n\n- [x] Der Wert genau auf der Grenze wechselt die Klasse ~ Richtig. `cut`\n      schneidet `(a, b]` und ordnet die 10 der unteren Klasse zu, `case_when`\n      mit `<` der oberen. Mit `right=False` stimmen beide überein.\n- [ ] `pd.cut` kann keine unendlichen Grenzen ~ `-np.inf` und `np.inf` sind\n      zulässig.\n- [ ] Die Reihenfolge der Klassen dreht sich um ~ Die Reihenfolge folgt den\n      Grenzen.\n:::\n\n::: {.quiz}\nIn pandas liefert `df.groupby(\"g\")[\"x\"].mean()` eine Series, deren Gruppen im\nIndex stehen. Warum ist das beim Weiterarbeiten unpraktisch?\n\n- [x] Die Gruppenspalte ist keine Spalte mehr, ein folgendes `merge` findet\n      sie nicht ~ Richtig. `as_index=False` oder `reset_index()` macht sie\n      wieder zur Spalte.\n- [ ] Der Index geht beim Speichern verloren ~ Er wird mitgeschrieben, das\n      ist nicht das Problem.\n- [ ] Series können keine Gruppen enthalten ~ Können sie, eben über den\n      Index.\n:::\n\n## Verlinkte Ressourcen\n\n- [dplyr: Referenz](https://dplyr.tidyverse.org/)\n- [pandas: Gruppieren](https://pandas.pydata.org/docs/user_guide/groupby.html)\n- [pandas: Vergleich mit R](https://pandas.pydata.org/docs/getting_started/comparison/comparison_with_r.html)\n",
    "supporting": [
      "data-wrangling_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}