{
  "hash": "97a368ad729f5095d426d2da2e1da5e3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"R-Grundlagen\"\ndescription: \"Vektoren, Data Frames, Funktionen und die Eigenheiten von R.\"\ncategories: [\"Programmiergrundlagen\", \"R\", \"Python\"]\nquelle: [\"ESDS\"]\nseitentyp: werkzeug\nstand: fertig\norder: 50\n---\n\n\n\n## Kernideen\n\n- **Alles ist ein Vektor**, auch der einzelne Wert. Rechnungen laufen\n  elementweise über den ganzen Vektor, ohne Schleife.\n- **Recycling:** Ist ein Vektor kürzer, wiederholt R ihn. Das ist bei einer\n  einzelnen Zahl bequem und bei unpassenden Längen eine stille Fehlerquelle.\n- **Ein Vektor, ein Typ.** Treffen Typen aufeinander, wandelt R still in den\n  allgemeineren um: logisch, dann Zahl, dann Text.\n- **Faktoren** sind Kategorien mit festgelegten Stufen. Die Stufen bestimmen\n  Tabellen, Reihenfolgen und Referenzkategorien.\n- Der **Data Frame** ist eine Liste gleich langer Spalten: jede Zeile eine\n  Beobachtung, jede Spalte ein Merkmal.\n- **Liste** für Ungleichartiges, **Matrix** für Zahlen in Zeilen und Spalten.\n  R füllt Matrizen spaltenweise, NumPy zeilenweise.\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** keines. Diese Seite setzt weder Statistik noch\nProgrammiererfahrung voraus. Wer von Python kommt, findet den Vergleich in\njedem Beispiel; die Python-Seite dazu ist\n[Python-Grundlagen](python-grundlagen.qmd). Die Datenstrukturen von hier\ntauchen im [Data Wrangling](../daten/data-wrangling.qmd) auf jeder Zeile\nwieder auf, und wie man daraus reproduzierbare Auswertungen macht, steht\nunter [Reproduzierbarkeit](reproduzierbarkeit.qmd).\n:::\n\n### Wozu eine eigene Sprache für Daten\n\nEine Tabellenkalkulation kommt weit. Sie stösst dort an ihre Grenze, wo eine\nAuswertung wiederholbar sein soll: Wer dieselbe Analyse mit neuen Zahlen\nbraucht, klickt sie erneut zusammen und weiss hinterher nicht sicher, ob\ndieselben Schritte in derselben Reihenfolge erwischt wurden. Ein Skript\nbeantwortet diese Frage, weil jeder Schritt darin nachlesbar ist.\n\nR ist für genau diesen Zweck entstanden, nicht als allgemeine\nProgrammiersprache mit angebauter Statistik. Das erklärt einige Eigenheiten,\ndie zunächst ungewohnt wirken und später Arbeit sparen.\n\n### Alles ist ein Vektor\n\nIn vielen Sprachen ist die Grundeinheit die einzelne Zahl, und wer\nfünfhundert Messwerte umrechnen will, schreibt eine Schleife. In R ist die\nGrundeinheit die **Folge** von Werten, und ein einzelner Wert ist eine Folge\nder Länge eins. Deshalb wirkt `werte / 10` auf jeden Wert, und `werte > 20`\nliefert für jeden Wert ein `TRUE` oder `FALSE`. Summiert man diese\nWahrheitswerte, zählt man die Treffer, weil `TRUE` beim Rechnen als 1 gilt;\nihr Mittelwert ist der Anteil.\n\nPython bringt das nicht von Haus aus mit. Eine Python-Liste rechnet nicht\nelementweise; das Verhalten von R entsteht erst mit einem NumPy-Array, siehe\n[NumPy und SciPy](numpy-scipy.qmd).\n\n### Recycling\n\nSind zwei Vektoren unterschiedlich lang, wiederholt R den kürzeren, bis er\npasst. Bei `werte / 10` ist das der Grund, warum die eine 10 auf alle Werte\nangewendet wird. Geht die Länge des längeren nicht in einem Vielfachen auf,\ngibt R eine **Warnung** aus und rechnet trotzdem. Geht sie auf, rechnet R\n**ohne jeden Hinweis**, auch wenn die Absicht eine andere war.\n\nNumPy folgt einer engeren Regel, dem **Broadcasting**: Formen werden von\nhinten verglichen und nur dort angeglichen, wo eine Achse die Länge eins hat.\nSonst bricht die Rechnung ab.\n\n### Ein Vektor, ein Typ\n\nEin Vektor trägt genau einen Typ. Treffen verschiedene Typen aufeinander,\nwandelt R sie in den allgemeineren um, statt einen Fehler zu melden. Dieser\nVorgang heisst **Coercion**, und die Rangfolge lautet\n\n$$\n\\text{logisch} \\;\\rightarrow\\; \\text{ganze Zahl} \\;\\rightarrow\\; \\text{Gleitkommazahl} \\;\\rightarrow\\; \\text{Text}\n$$\n\nEin einziger Texteintrag in einer Spalte, etwa ein Strich für einen fehlenden\nWert, verwandelt deshalb die ganze Spalte in Text. Die Kontrolle der\nSpaltentypen gehört direkt hinter jeden Import.\n\n### Faktoren\n\nKategoriale Merkmale liessen sich als Text speichern. Damit ginge verloren,\nwelche Ausprägungen überhaupt möglich sind und in welcher Reihenfolge sie\nstehen. Der Faktor führt die Stufen (`levels`) als eigene Eigenschaft mit.\nIntern speichert er ganze Zahlen, die auf die Stufen zeigen; das ist der\nGrund für die bekannteste Faktor-Falle in Beispiel 4. Das Gegenstück in\npandas ist `pd.Categorical`.\n\n| Eigenschaft | Faktor ohne Vorgabe | Faktor mit `levels` | geordneter Faktor |\n|---|---|---|---|\n| Stufen | aus den Daten, alphabetisch | wie vorgegeben, auch unbesetzte | wie vorgegeben |\n| Vergleich `<`, `>` | nicht sinnvoll | nicht sinnvoll | erlaubt |\n| typischer Fall | Gerätetyp, Standort | Umfrage mit fester Antwortliste | Bewertungsskala |\n\n### Data Frame, Liste, Matrix\n\n| Struktur | Inhalt | Typen | Python |\n|---|---|---|---|\n| Vektor | eine Folge | einer | NumPy-Array, `pd.Series` |\n| Data Frame | gleich lange Spalten | je Spalte einer | `pd.DataFrame` |\n| Liste | beliebige Objekte unter Namen | beliebig | Dictionary |\n| Matrix | Zahlen in Zeilen und Spalten | einer | zweidimensionales NumPy-Array |\n\nDer Data Frame ist genau genommen eine Liste gleich langer Vektoren. Deshalb\nfunktioniert `df$spalte` wie bei einer Liste, und deshalb dürfen die Spalten\nverschiedene Typen tragen, aber nicht verschieden lang sein: Sonst ginge die\nZuordnung zur Beobachtung verloren.\n\nBeim Auswählen trennt das Komma Zeilen von Spalten: `df[zeilen, spalten]`.\nEin leerer Platz heisst \"alle\". `df[df$gruppe == \"A\", ]` wählt alle Zeilen\nder Gruppe A und alle Spalten; innen steht eine Bedingung, die für jede Zeile\nwahr oder falsch ist.\n\n### Kurz nachgeschlagen\n\n| Aufgabe | R | Python |\n|---|---|---|\n| Struktur ansehen | `str(df)` | `df.dtypes`, `df.info()` |\n| Kennzahlen je Spalte | `summary(df)` | `df.describe()` |\n| Zeilen und Spalten wählen | `df[df$x > 40, c(\"a\", \"b\")]` | `df.loc[df[\"x\"] > 40, [\"a\", \"b\"]]` |\n| Spalte anlegen | `df$neu <- df$a / df$b` | `df[\"neu\"] = df[\"a\"] / df[\"b\"]` |\n| Mittel je Gruppe | `tapply(df$x, df$g, mean)` | `df.groupby(\"g\")[\"x\"].mean()` |\n| Stufen festlegen | `factor(x, levels = c(...))` | `pd.Categorical(x, categories=[...])` |\n| unbesetzte Stufen entfernen | `droplevels(f)` | `s.cat.remove_unused_categories()` |\n| Zahlen aus einem Faktor | `as.numeric(as.character(f))` | `s.astype(float)` |\n| fehlende Werte zählen | `sum(is.na(x))` | `s.isna().sum()` |\n| Länge prüfen | `stopifnot(length(x) == n)` | `assert len(x) == n` |\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Rechnen mit ganzen Vektoren\n\n#### Frage und Datenlage\n\nVier Messwerte `12, 45, 7, 31`. Sie sollen durch 10 geteilt werden, es soll\ngezählt werden, wie viele über 20 liegen, und welcher Anteil das ist. Dazu\ndie Multiplikation mit einem zweiten Vektor gleicher Länge.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- 5\nlength(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\nis.vector(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nwerte <- c(12, 45, 7, 31)\nwerte / 10\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.2 4.5 0.7 3.1\n```\n\n\n:::\n\n```{.r .cell-code}\nwerte > 20\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE  TRUE FALSE  TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(werte > 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(werte > 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5\n```\n\n\n:::\n\n```{.r .cell-code}\nwerte * c(10, 20, 30, 40)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  120  900  210 1240\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nx = 5\nprint(type(x).__name__, np.array([5]).shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nint (1,)\n```\n\n\n:::\n\n```{.python .cell-code}\nwerte = np.array([12, 45, 7, 31])\nprint(werte / 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1.2 4.5 0.7 3.1]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(werte > 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[False  True False  True]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint((werte > 20).sum(), (werte > 20).mean())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2 0.5\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(werte * np.array([10, 20, 30, 40]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[ 120  900  210 1240]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausdruck | R | Python | Erklärung |\n|---|---|---|---|\n| einzelner Wert | Länge 1, `is.vector` ist `TRUE` | `int`, erst als Array Form `(1,)` | In R ist die 5 ein Vektor, in Python eine einzelne Zahl. |\n| `werte / 10` | 1.2 4.5 0.7 3.1 | `[1.2 4.5 0.7 3.1]` | Die eine 10 wird auf alle vier Werte angewendet. |\n| `werte > 20` | `FALSE TRUE FALSE TRUE` | `[False True False True]` | Ein Wahrheitswert je Messwert. |\n| Summe der Wahrheitswerte | 2 | 2 | Anzahl der Werte über 20: 45 und 31. |\n| Mittel der Wahrheitswerte | 0.5 | 0.5 | Anteil der Werte über 20. |\n| paarweise mal | 120 900 210 1240 | `[ 120  900  210 1240]` | Erstes mit erstem, zweites mit zweitem. Kein Skalarprodukt; das wäre `%*%` beziehungsweise `@`. |\n\n#### Interpretation und Ergebnissatz\n\nDas Muster `sum(bedingung)` und `mean(bedingung)` taucht in jeder Auswertung\nauf: Aus einer Bedingung wird ohne Schleife eine Anzahl oder ein Anteil. In\nPython gilt dasselbe, sobald die Werte in einem NumPy-Array oder einer\npandas-Series stehen.\n\n> Zwei der vier Messwerte liegen über 20, das ist ein Anteil von 0.5. Die\n> Rechnung läuft in R auf dem Vektor selbst, in Python erst nach der\n> Umwandlung in ein NumPy-Array.\n\n### Beispiel 2: Recycling und Broadcasting\n\n#### Frage und Datenlage\n\nEin Vektor mit sechs Werten `1` bis `6` wird mit einem Vektor der Länge zwei\n(`10, 100`) und einem der Länge vier (`10, 100, 1000, 10000`) multipliziert.\nWas tut R, was tut NumPy?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlang <- c(1, 2, 3, 4, 5, 6)\nkurz <- c(10, 100)\n\nlang * kurz                          # 6 ist ein Vielfaches von 2: kein Hinweis\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  10 200  30 400  50 600\n```\n\n\n:::\n\n```{.r .cell-code}\nvier <- c(10, 100, 1000, 10000)\ntryCatch(lang * vier, warning = function(w) conditionMessage(w))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"longer object length is not a multiple of shorter object length\"\n```\n\n\n:::\n\n```{.r .cell-code}\nsuppressWarnings(lang * vier)        # gerechnet wird trotzdem\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]    10   200  3000 40000    50   600\n```\n\n\n:::\n\n```{.r .cell-code}\n# Kontrolle vor der Rechnung\nstopifnot(length(lang) %% length(kurz) == 0)\n```\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nlang = np.array([1, 2, 3, 4, 5, 6])\nkurz = np.array([10, 100])\n\ntry:\n    lang * kurz\nexcept ValueError as fehler:\n    print(\"ValueError:\", fehler)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nValueError: operands could not be broadcast together with shapes (6,) (2,) \n```\n\n\n:::\n\n```{.python .cell-code}\nprint(lang * 10)                         # eine Zahl passt immer\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[10 20 30 40 50 60]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(lang.reshape(3, 2) * kurz)         # passende Achse: Broadcasting\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[ 10 200]\n [ 30 400]\n [ 50 600]]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Rechnung | R | Python | Erklärung |\n|---|---|---|---|\n| sechs mal zwei | 10 200 30 400 50 600, **ohne Hinweis** | **`ValueError`**, Formen `(6,)` und `(2,)` passen nicht | R wiederholt `10, 100` dreimal. Ob das gemeint war, prüft niemand. |\n| sechs mal vier | Warnung `longer object length is not a multiple of shorter object length` | | 6 ist kein Vielfaches von 4. R warnt, rechnet aber: 10, 200, 3000, 40000, 50, 600. |\n| mal eine Zahl | | 10 20 30 40 50 60 | Eine Zahl hat die Form `()` und passt zu jeder Form. |\n| `(3, 2)` mal `(2,)` | | Zeilen `10 200`, `30 400`, `50 600` | Von hinten verglichen stimmen die 2 überein; die Zeile `10, 100` wird auf jede der drei Zeilen angewendet. |\n| `stopifnot` | kein Output | | Die Annahme stimmt, also läuft das Skript weiter. Stimmte sie nicht, bräche es an dieser Stelle ab. |\n\n#### Interpretation und Ergebnissatz\n\nDer gefährliche Fall ist nicht die Warnung, sondern die **Stille**: Sechs mal\nzwei liefert ein plausibel aussehendes Ergebnis ohne jeden Hinweis. NumPy\nverlangt, dass die Formen ausdrücklich zusammenpassen, und gleicht nur\nAchsen der Länge eins an. Wer in R mit Vektoren unterschiedlicher Länge\nrechnet, sollte die Längen vorher mit `stopifnot` festschreiben.\n\n> Die Multiplikation eines Vektors der Länge sechs mit einem der Länge zwei\n> ergibt in R ohne Hinweis `10 200 30 400 50 600`; NumPy bricht mit einem\n> `ValueError` ab. Bei Länge vier warnt R, rechnet aber dennoch.\n\n### Beispiel 3: Coercion und die Textspalte\n\n#### Frage und Datenlage\n\nWelchen Typ erhält ein Vektor aus Wahrheitswert, Zahl und Text? Und was\npassiert beim Einlesen einer CSV-Datei, in der ein fehlender Wert als Strich\neingetragen ist (`1.5`, `-`, `2.0`)?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(c(TRUE, FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"logical\"\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(c(TRUE, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"numeric\"\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(c(TRUE, 3, \"drei\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n\n```{.r .cell-code}\nc(TRUE, 3, \"drei\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"TRUE\" \"3\"    \"drei\"\n```\n\n\n:::\n\n```{.r .cell-code}\ncsv_text <- \"id,wert\\n1,1.5\\n2,-\\n3,2.0\"\nroh <- read.csv(text = csv_text)\nclass(roh$wert)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n\n```{.r .cell-code}\nroh$wert\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1.5\" \"-\"   \"2.0\"\n```\n\n\n:::\n\n```{.r .cell-code}\nzahlen <- suppressWarnings(as.numeric(roh$wert))\nzahlen\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.5  NA 2.0\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(zahlen, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.5\n```\n\n\n:::\n\n```{.r .cell-code}\nsauber <- read.csv(text = csv_text, na.strings = \"-\")\nclass(sauber$wert)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"numeric\"\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(pd.Series([1, 2, \"3\"]).dtype)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nobject\n```\n\n\n:::\n\n```{.python .cell-code}\ncsv_text = \"id,wert\\n1,1.5\\n2,-\\n3,2.0\\n\"\nroh = pd.read_csv(io.StringIO(csv_text))\nprint(roh[\"wert\"].dtype, roh[\"wert\"].tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nobject ['1.5', '-', '2.0']\n```\n\n\n:::\n\n```{.python .cell-code}\nzahlen = pd.to_numeric(roh[\"wert\"], errors=\"coerce\")\nprint(zahlen.tolist(), zahlen.sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1.5, nan, 2.0] 3.5\n```\n\n\n:::\n\n```{.python .cell-code}\nsauber = pd.read_csv(io.StringIO(csv_text), na_values=\"-\")\nprint(sauber[\"wert\"].dtype)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfloat64\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Schritt | R | Python | Erklärung |\n|---|---|---|---|\n| logisch und logisch | `logical` | | |\n| logisch und Zahl | `numeric` | | `TRUE` wird zu 1. |\n| dazu ein Text | `character`, Inhalt `\"TRUE\" \"3\" \"drei\"` | gemischte Series: `object` | Alles wird Text, auch die 3 und das `TRUE`. pandas hält gemischte Werte als allgemeine Objekte. |\n| Spalte mit Strich | `character`, `\"1.5\" \"-\" \"2.0\"` | Textspalte, `['1.5', '-', '2.0']` | Der eine Strich macht die ganze Spalte zu Text. Rechnen ist damit nicht mehr möglich. |\n| umgewandelt | `1.5 NA 2.0` | `[1.5, nan, 2.0]` | `as.numeric` beziehungsweise `to_numeric(errors=\"coerce\")` machen aus dem Strich einen fehlenden Wert. |\n| Summe | 3.5 | 3.5 | Ohne den fehlenden Wert. |\n| mit Angabe beim Import | `numeric` | `float64` | Der bessere Weg: dem Import sagen, was \"fehlend\" bedeutet. |\n\n#### Interpretation und Ergebnissatz\n\nCoercion ist eine Regel und kein Fehler, und deshalb meldet sie sich nicht.\nDie Spalte sieht in der Vorschau richtig aus, und der Fehler zeigt sich erst,\nwenn eine Rechnung scheitert oder ein Mittelwert fehlt. Die Abhilfe gehört an\nden Anfang: fehlende Werte beim Import deklarieren (`na.strings`,\n`na_values`) und danach die Typen mit `str()` beziehungsweise `df.dtypes`\nkontrollieren.\n\n> Ein einziger Strich in der Spalte `wert` machte beim Einlesen die ganze\n> Spalte zu Text. Mit `na.strings = \"-\"` beziehungsweise `na_values=\"-\"` wird\n> sie als Zahl gelesen, und die Summe der beiden gültigen Werte beträgt 3.5.\n\n### Beispiel 4: Faktoren und ihre Stufen\n\n#### Frage und Datenlage\n\nFünf Umfrageantworten (`ja, nein, ja, ja, nein`) auf die Antwortliste ja,\nnein, weiss nicht. Dann Schulnoten `5, 3, 4` als Faktor und eine\nBewertungsskala von schlecht bis ausgezeichnet.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nantworten <- c(\"ja\", \"nein\", \"ja\", \"ja\", \"nein\")\nals_faktor <- factor(antworten, levels = c(\"ja\", \"nein\", \"weiss nicht\"))\nlevels(als_faktor)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"ja\"          \"nein\"        \"weiss nicht\"\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(als_faktor)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nals_faktor\n         ja        nein weiss nicht \n          3           2           0 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(factor(antworten))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  ja nein \n   3    2 \n```\n\n\n:::\n\n```{.r .cell-code}\nnoten <- factor(c(5, 3, 4))\nas.numeric(noten)                    # die internen Codes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3 1 2\n```\n\n\n:::\n\n```{.r .cell-code}\nas.numeric(as.character(noten))      # die Werte\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5 3 4\n```\n\n\n:::\n\n```{.r .cell-code}\nskala <- factor(c(\"gut\", \"schlecht\", \"ausgezeichnet\", \"gut\"),\n                levels = c(\"schlecht\", \"gut\", \"ausgezeichnet\"), ordered = TRUE)\nsort(skala)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] schlecht      gut           gut           ausgezeichnet\nLevels: schlecht < gut < ausgezeichnet\n```\n\n\n:::\n\n```{.r .cell-code}\nskala > \"schlecht\"\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  TRUE FALSE  TRUE  TRUE\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nantworten = [\"ja\", \"nein\", \"ja\", \"ja\", \"nein\"]\nkat = pd.Categorical(antworten, categories=[\"ja\", \"nein\", \"weiss nicht\"])\nprint(kat.categories.tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['ja', 'nein', 'weiss nicht']\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pd.Series(kat).value_counts(sort=False).to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'ja': 3, 'nein': 2, 'weiss nicht': 0}\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pd.Series(antworten).value_counts().to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'ja': 3, 'nein': 2}\n```\n\n\n:::\n\n```{.python .cell-code}\nnoten = pd.Categorical([5, 3, 4])\nprint(noten.categories.tolist(), noten.codes.tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[3, 4, 5] [2, 0, 1]\n```\n\n\n:::\n\n```{.python .cell-code}\nskala = pd.Categorical([\"gut\", \"schlecht\", \"ausgezeichnet\", \"gut\"],\n                       categories=[\"schlecht\", \"gut\", \"ausgezeichnet\"],\n                       ordered=True)\nprint(list(skala.sort_values()))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['schlecht', 'gut', 'gut', 'ausgezeichnet']\n```\n\n\n:::\n\n```{.python .cell-code}\nprint((skala > \"schlecht\").tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[True, False, True, True]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Schritt | R | Python | Erklärung |\n|---|---|---|---|\n| Stufen | ja, nein, weiss nicht | dieselben | wie vorgegeben |\n| Häufigkeiten mit Stufen | ja 3, nein 2, **weiss nicht 0** | `{'ja': 3, 'nein': 2, 'weiss nicht': 0}` | Die unbesetzte Stufe bleibt sichtbar. Für eine Umfrage ist das die vollständige Information. |\n| Häufigkeiten ohne Vorgabe | ja 3, nein 2 | `{'ja': 3, 'nein': 2}` | Was niemand gewählt hat, existiert nicht. |\n| `as.numeric(noten)` | **3 1 2** | Codes **`[2, 0, 1]`** | Die internen Codes, also die Position in der sortierten Stufenliste 3, 4, 5. Die Note 5 steht an dritter Stelle. pandas zählt ab null. |\n| über `as.character` | 5 3 4 | | der sichere Weg zurück zu den Werten |\n| geordnet sortiert | schlecht, gut, gut, ausgezeichnet | dieselbe Folge | Nach den Stufen, nicht alphabetisch; alphabetisch stünde ausgezeichnet vorne. |\n| `> \"schlecht\"` | `TRUE FALSE TRUE TRUE` | `[True, False, True, True]` | Vergleiche sind nur bei geordneten Faktoren sinnvoll. |\n\n#### Interpretation und Ergebnissatz\n\nDie Stufen sind keine Beschriftung, sondern Teil der Daten. Sie bestimmen,\nwelche Kategorien in Tabellen erscheinen, in welcher Reihenfolge Balken in\neinem Diagramm stehen und welche Stufe in einem Regressionsmodell als\nReferenz dient, siehe [multiple lineare Regression](../statistik/regression/multiple-lineare-regression.qmd).\nDie Faktor-Falle mit `as.numeric` ist die häufigste stille Fehlerquelle: Die\nRechnung läuft, nur mit den Codes 3, 1, 2 statt mit den Noten 5, 3, 4.\n\n> Mit vorgegebenen Stufen weist die Tabelle `weiss nicht` mit 0 aus, ohne\n> Vorgabe fehlt die Stufe. `as.numeric` auf dem Notenfaktor liefert die Codes\n> 3, 1, 2 statt der Noten 5, 3, 4; richtig ist `as.numeric(as.character())`.\n\n### Beispiel 5: Der Data Frame im Alltag\n\n#### Frage und Datenlage\n\nFünf Beobachtungen mit Kennnummer, Messwert (`2.5, 3.1, 4.0, 2.8, 3.6`) und\nGruppe (`A, B, A, B, A`). Struktur ansehen, Kennzahlen, Zeilen der Gruppe A\nauswählen, Mittelwert je Gruppe.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- data.frame(\n  id     = 1:5,\n  wert   = c(2.5, 3.1, 4.0, 2.8, 3.6),\n  gruppe = factor(c(\"A\", \"B\", \"A\", \"B\", \"A\"))\n)\nstr(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t5 obs. of  3 variables:\n $ id    : int  1 2 3 4 5\n $ wert  : num  2.5 3.1 4 2.8 3.6\n $ gruppe: Factor w/ 2 levels \"A\",\"B\": 1 2 1 2 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(df$wert)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n    2.5     2.8     3.1     3.2     3.6     4.0 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(sd(df$wert), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.604\n```\n\n\n:::\n\n```{.r .cell-code}\ndf[df$gruppe == \"A\", ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  id wert gruppe\n1  1  2.5      A\n3  3  4.0      A\n5  5  3.6      A\n```\n\n\n:::\n\n```{.r .cell-code}\ntapply(df$wert, df$gruppe, mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       A        B \n3.366667 2.950000 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndf = pd.DataFrame({\n    \"id\":     [1, 2, 3, 4, 5],\n    \"wert\":   [2.5, 3.1, 4.0, 2.8, 3.6],\n    \"gruppe\": pd.Categorical([\"A\", \"B\", \"A\", \"B\", \"A\"]),\n})\nprint(df.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(5, 3)\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(df.dtypes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nid           int64\nwert       float64\ngruppe    category\ndtype: object\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(df[\"wert\"].describe().round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncount    5.000\nmean     3.200\nstd      0.604\nmin      2.500\n25%      2.800\n50%      3.100\n75%      3.600\nmax      4.000\nName: wert, dtype: float64\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(df[df[\"gruppe\"] == \"A\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   id  wert gruppe\n0   1   2.5      A\n2   3   4.0      A\n4   5   3.6      A\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(df.groupby(\"gruppe\", observed=True)[\"wert\"].mean().round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngruppe\nA    3.3667\nB    2.9500\nName: wert, dtype: float64\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Grösse | R | Python | Erklärung |\n|---|---|---|---|\n| Umfang | `5 obs. of 3 variables` | `(5, 3)` | Zeilen und Spalten. Die erste Kontrolle nach jedem Import. |\n| Typ `id` | `int` | `int64` | `1:5` erzeugt in R ganze Zahlen. |\n| Typ `wert` | `num` | `float64` | |\n| Typ `gruppe` | `Factor w/ 2 levels \"A\",\"B\": 1 2 1 2 1` | `category` | R zeigt die Stufen und die internen Codes. |\n| Minimum, Maximum | 2.5, 4.0 | 2.5, 4.0 | |\n| Quartile | 2.8, 3.1, 3.6 | 25 %, 50 %, 75 %: 2.8, 3.1, 3.6 | Beide rechnen die Quantile nach derselben Voreinstellung. |\n| Mittelwert | 3.2 | 3.2 | |\n| Standardabweichung | 0.604 | 0.604 | Nur `describe` zeigt sie von selbst, in R braucht es `sd()`. |\n| Zeilen der Gruppe A | id 1, 3, 5 | Index 0, 2, 4 | Dieselben Zeilen; pandas zeigt den Index ab null, R die Zeilennamen ab eins. |\n| Mittel je Gruppe | A 3.366667, B 2.950000 | A 3.3667, B 2.95 | (2.5 + 4.0 + 3.6) / 3 und (3.1 + 2.8) / 2 |\n\n#### Interpretation und Ergebnissatz\n\n`str()` in R und `df.dtypes` in Python sind die Befehle, die nach jedem\nImport zuerst kommen: Sie zeigen, ob die Zeilenzahl plausibel ist und ob jede\nSpalte den erwarteten Typ hat. Die Kennzahlen danach verteilen sich\nverschieden: `summary` bringt Quartile und Mittelwert, `describe` zusätzlich\nAnzahl und Standardabweichung. Was diese Kennzahlen bedeuten, steht unter\n[Lage- und Streuungsmasse](../statistik/grundlagen/lage-streuungsmasse.qmd).\n\n> Die fünf Messwerte reichen von 2.5 bis 4.0 bei einem Mittelwert von 3.2 und\n> einer Standardabweichung von 0.604. Gruppe A liegt im Mittel bei 3.37,\n> Gruppe B bei 2.95.\n\n### Beispiel 6: Liste und Matrix\n\n#### Frage und Datenlage\n\nEin Ergebnis mit Text, drei Zahlen und einer Anzahl soll zusammengehalten\nwerden, das passt in keine Tabelle. Danach eine Matrix aus den Zahlen `1` bis\n`6` mit zwei Zeilen: in welcher Reihenfolge wird sie gefüllt?\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nergebnis <- list(methode = \"Beispiel\", werte = c(1.2, 3.4, 5.6), n = 3)\nstr(ergebnis)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 3\n $ methode: chr \"Beispiel\"\n $ werte  : num [1:3] 1.2 3.4 5.6\n $ n      : num 3\n```\n\n\n:::\n\n```{.r .cell-code}\nergebnis$werte\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.2 3.4 5.6\n```\n\n\n:::\n\n```{.r .cell-code}\nm <- matrix(1:6, nrow = 2)\nm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     [,1] [,2] [,3]\n[1,]    1    3    5\n[2,]    2    4    6\n```\n\n\n:::\n\n```{.r .cell-code}\ndim(m)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2 3\n```\n\n\n:::\n\n```{.r .cell-code}\nmatrix(1:6, nrow = 2, byrow = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     [,1] [,2] [,3]\n[1,]    1    2    3\n[2,]    4    5    6\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nergebnis = {\"methode\": \"Beispiel\", \"werte\": [1.2, 3.4, 5.6], \"n\": 3}\nprint(ergebnis[\"werte\"], len(ergebnis))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1.2, 3.4, 5.6] 3\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(np.arange(1, 7).reshape(2, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1 2 3]\n [4 5 6]]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(np.arange(1, 7).reshape(2, 3).shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(2, 3)\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(np.arange(1, 7).reshape(2, 3, order=\"F\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1 3 5]\n [2 4 6]]\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Schritt | R | Python | Erklärung |\n|---|---|---|---|\n| Ergebnis | `List of 3` mit `chr`, `num [1:3]`, `num` | Dictionary mit drei Einträgen | Beliebige Objekte unter Namen. |\n| `ergebnis$werte` | 1.2 3.4 5.6 | `[1.2, 3.4, 5.6]` | |\n| Matrix, Voreinstellung | Zeilen `1 3 5` und `2 4 6` | Zeilen `[1 2 3]` und `[4 5 6]` | **R füllt spaltenweise, NumPy zeilenweise.** Derselbe Aufruf ergibt verschiedene Matrizen. |\n| Dimension | 2 3 | `(2, 3)` | |\n| umgestellt | `byrow = TRUE`: `1 2 3`, `4 5 6` | `order=\"F\"`: `1 3 5`, `2 4 6` | Mit diesen Argumenten füllt jede Sprache wie die andere. `F` steht für Fortran, das wie R spaltenweise speichert. |\n\n#### Interpretation und Ergebnissatz\n\nDie Liste ist die Struktur, in der R fast alle Ergebnisse zurückgibt: Das\nResultat von `t.test()` oder `lm()` ist eine Liste mit Klassenattribut. Die\nMatrix-Reihenfolge ist die Stelle, an der beim Übertragen von Code zwischen\nden Sprachen am leichtesten ein Fehler entsteht, der keine Meldung erzeugt:\nBeide Matrizen sind gültig, nur ist die eine die umsortierte andere.\n\n> Die Liste hält Text, drei Messwerte und eine Anzahl unter einem Namen\n> zusammen. `matrix(1:6, nrow = 2)` füllt spaltenweise und ergibt die erste\n> Zeile `1 3 5`; `reshape(2, 3)` in NumPy füllt zeilenweise und ergibt `1 2 3`.\n\n::::\n\n## Verständnisfragen\n\n::: {.quiz}\nWas liefert `c(2, 4, 6) * c(10, 20, 30)`?\n\n- [ ] Die Zahl 280, also das Skalarprodukt ~ R fasst die beiden nicht als\n      mathematische Vektoren auf. Für das Skalarprodukt gäbe es `%*%`.\n- [x] Den Vektor `20 80 180` ~ Richtig. Multipliziert wird paarweise, erstes\n      mit erstem und so weiter.\n- [ ] Einen Fehler wegen fehlender Schleife ~ Genau die ist nicht nötig.\n:::\n\n::: {.quiz}\nBei den Werten `12, 45, 7, 31` ergibt `mean(werte > 20)` den Wert 0.5. Was\nsagt diese Zahl inhaltlich?\n\n- [ ] Der Mittelwert der Messwerte beträgt 0.5 ~ Gemittelt wird nicht über\n      die Messwerte, sondern über das Ergebnis des Vergleichs.\n- [x] Die Hälfte der Messwerte liegt über 20 ~ Richtig. Der Mittelwert von\n      Wahrheitswerten ist der Anteil der wahren Fälle.\n- [ ] Es gibt 0.5 Werte über 20 ~ Eine Anzahl kann nicht gebrochen sein. Für\n      die Anzahl müsste `sum` statt `mean` stehen.\n:::\n\n::: {.quiz}\n`c(1, 2, 3, 4, 5, 6) * c(10, 100)` läuft in R ohne Warnung. Heisst das, die\nRechnung ist richtig?\n\n- [ ] Ja, sonst hätte R gewarnt ~ R warnt nur, wenn die Längen nicht in einem\n      Vielfachen aufgehen. 6 ist ein Vielfaches von 2.\n- [x] Nein, R wiederholt den kurzen Vektor still, ob das gemeint war oder\n      nicht ~ Richtig. NumPy würde hier abbrechen. In R schützt nur eine\n      ausdrückliche Kontrolle der Längen.\n- [ ] Nein, R hat das Skalarprodukt gebildet ~ Es rechnet elementweise mit\n      Wiederholung.\n:::\n\n::: {.quiz}\nEine eingelesene Spalte `wert` hat den Typ `character`, obwohl sie Zahlen\nenthält. Was ist die wahrscheinlichste Ursache?\n\n- [x] Mindestens ein Eintrag ist kein gültiger Zahlentext, etwa ein Strich für\n      einen fehlenden Wert ~ Richtig. Ein Vektor trägt nur einen Typ, und ein\n      Texteintrag macht die ganze Spalte zu Text. Abhilfe: `na.strings` beim\n      Import.\n- [ ] R liest Zahlen aus CSV-Dateien immer als Text ~ Ohne störenden Eintrag\n      erkennt `read.csv` Zahlen richtig.\n- [ ] Die Datei hat das falsche Encoding ~ Das verdirbt Umlaute, macht aber\n      keine Zahlen zu Text.\n:::\n\n::: {.quiz}\n`noten <- factor(c(5, 3, 4))`. Was gibt `as.numeric(noten)` zurück?\n\n- [ ] `5 3 4`, die ursprünglichen Werte ~ Dafür braucht es den Umweg\n      `as.numeric(as.character(x))`.\n- [x] `3 1 2`, die internen Codes ~ Richtig. Der Faktor speichert die\n      Position in der sortierten Stufenliste 3, 4, 5. Die 5 steht an dritter\n      Stelle.\n- [ ] `1 2 3` in der Reihenfolge des Auftretens ~ Sortiert wird aufsteigend,\n      nicht nach Auftreten.\n:::\n\n::: {.quiz}\nEin Skript baut eine Matrix mit `matrix(werte, nrow = 2)` und wird nach\nPython als `np.array(werte).reshape(2, -1)` übertragen. Worauf ist zu achten?\n\n- [x] R füllt spaltenweise, NumPy zeilenweise; die Matrizen unterscheiden\n      sich ~ Richtig. Mit `order=\"F\"` in NumPy oder `byrow = TRUE` in R\n      stimmen sie überein. Ohne diese Angabe entsteht kein Fehler, nur eine\n      andere Matrix.\n- [ ] Nichts, beide füllen gleich ~ Beispiel 6 zeigt die Zeilen `1 3 5`\n      gegen `1 2 3`.\n- [ ] `-1` ist in NumPy ungültig ~ `-1` heisst \"so viele wie nötig\" und ist\n      gültig.\n:::\n\n## Verlinkte Ressourcen\n\n- [R for Data Science (frei verfügbar)](https://r4ds.hadley.nz/)\n- [Advanced R, Kapitel zu Datenstrukturen](https://adv-r.hadley.nz/vectors-chap.html)\n",
    "supporting": [
      "r-grundlagen_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}