{
  "hash": "a904df81918a50506360c5b1000413b8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"APIs und Web-Scraping\"\ndescription: \"Daten aus Schnittstellen und Webseiten holen: JSON seitenweise abrufen, HTML auslesen, Fehler abfangen und fair bleiben.\"\ncategories: [\"Data Wrangling\", \"Datenqualität\", \"R\", \"Python\"]\nquelle: [\"PYFR\"]\nseitentyp: werkzeug\nstand: fertig\norder: 60\n---\n\n\n\n\n\n## Kernideen\n\n- Eine **API** liefert strukturierte Daten, meist JSON; sie ist immer der erste Weg, bevor man eine Webseite ausliest\n- Antworten kommen oft **seitenweise**; abgerufen wird, bis kein Verweis auf eine nächste Seite mehr kommt\n- **HTML** wird mit einem Parser gelesen und über CSS-Selektoren angesprochen, nicht mit regulären Ausdrücken\n- Was aus einer Webseite kommt, ist **Text**; Zahlen, Einheiten und Tausendertrennzeichen werden danach bereinigt\n- Fehler wie `429` (zu viele Anfragen) und `5xx` werden mit **Wartezeit und Wiederholung** behandelt\n- Nutzungsbedingungen, `robots.txt` und eine vernünftige Abfragefrequenz gehören zur Arbeit dazu\n\n## Erklärung\n\n::: {.note-box}\n**Vorwissen:** [Datenimport und Formate](datenimport-formate.qmd) für JSON und\ndas Flachmachen verschachtelter Antworten, [Textdaten und reguläre Ausdrücke](textdaten-regex.qmd)\nfür das Bereinigen danach. Diese Seite ruft **keine** echte Adresse ab: Der\nBuild der Website soll nicht davon abhängen, ob ein fremder Server gerade\nantwortet. Die Antworten stehen deshalb als Text im Code, die Verarbeitung ist\ndieselbe wie bei einem echten Abruf.\n:::\n\n### API oder Scraping\n\n| | API | Web-Scraping |\n|---|---|---|\n| Liefert | strukturierte Daten, meist JSON | HTML für Menschen gemacht |\n| Stabilität | versioniert, dokumentiert | bricht bei jeder Umgestaltung der Seite |\n| Regeln | Nutzungsbedingungen, oft Schlüssel und Kontingent | `robots.txt`, Nutzungsbedingungen, Urheberrecht |\n| Wann | immer, wenn es eine gibt | nur wenn es keine API und keinen Datendownload gibt |\n\n### Ein Abruf in beiden Sprachen\n\nSo sieht ein echter Abruf aus. Diese Listings laufen im Build nicht:\n\n```r\nlibrary(httr2)\nantwort <- request(\"https://api.beispiel.ch/v1/messungen\") |>\n  req_url_query(ort = \"Bern\", seite = 1) |>\n  req_headers(Authorization = paste(\"Bearer\", Sys.getenv(\"API_SCHLUESSEL\"))) |>\n  req_retry(max_tries = 3) |>\n  req_perform()\ndaten <- resp_body_json(antwort)\n```\n\n```python\nimport os\nimport requests\n\nantwort = requests.get(\n    \"https://api.beispiel.ch/v1/messungen\",\n    params={\"ort\": \"Bern\", \"seite\": 1},\n    headers={\"Authorization\": f\"Bearer {os.environ['API_SCHLUESSEL']}\"},\n    timeout=10,\n)\nantwort.raise_for_status()\ndaten = antwort.json()\n```\n\nDer Schlüssel steht nie im Code, sondern in einer Umgebungsvariablen. Eine\nDatei `.env` mit dem Schlüssel gehört in `.gitignore`, siehe\n[Git](../werkzeuge/git.qmd).\n\n### Statuscodes\n\n| Code | Bedeutung | Vorgehen |\n|---|---|---|\n| `200` | alles in Ordnung | Antwort verarbeiten |\n| `400`, `404` | Anfrage falsch, Ressource fehlt | Anfrage prüfen; Wiederholen hilft nicht |\n| `401`, `403` | nicht angemeldet, keine Berechtigung | Schlüssel prüfen |\n| `429` | zu viele Anfragen | warten, dann wiederholen; Header `Retry-After` beachten |\n| `500`, `502`, `503` | Fehler auf dem Server | mit wachsender Wartezeit wiederholen |\n\n### Fair abfragen\n\n- In `robots.txt` der Seite nachsehen, welche Bereiche für automatische Abrufe\n  gesperrt sind.\n- Zwischen Abrufen warten, eine Sekunde ist ein vernünftiger Anfang.\n- Einen erkennbaren `User-Agent` mit Kontaktadresse setzen.\n- Abgerufenes lokal speichern, statt dieselbe Seite wiederholt abzufragen.\n- Personenbezogene Daten nur mit Rechtsgrundlage erheben.\n\n## Beispiele\n\n:::: {.panel-tabset}\n\n### Beispiel 1: Seitenweise abrufen\n\n#### Frage und Datenlage\n\nEine Schnittstelle liefert Messungen in Seiten zu höchstens zwei Einträgen.\nJede Antwort enthält die Daten und im Feld `weiter` den Schlüssel für die\nnächste Seite, auf der letzten Seite `null`. Alle Messungen sollen in eine\nTabelle.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Die drei Antworten des Servers, hier als Text statt als echter Abruf\nseiten <- list(\n  start = '{\"daten\":[{\"id\":1,\"ort\":\"Bern\",\"wert\":12.5},{\"id\":2,\"ort\":\"Chur\",\"wert\":9.1}],\"weiter\":\"s2\"}',\n  s2    = '{\"daten\":[{\"id\":3,\"ort\":\"Sion\",\"wert\":14.0},{\"id\":4,\"ort\":\"Bern\",\"wert\":11.8}],\"weiter\":\"s3\"}',\n  s3    = '{\"daten\":[{\"id\":5,\"ort\":\"Chur\",\"wert\":10.2}],\"weiter\":null}'\n)\nhole <- function(cursor) seiten[[if (is.null(cursor)) \"start\" else cursor]]\n\nteile <- list(); cursor <- NULL; abrufe <- 0\nrepeat {\n  antwort <- fromJSON(hole(cursor))\n  abrufe <- abrufe + 1\n  teile[[abrufe]] <- antwort$daten\n  cursor <- antwort$weiter\n  if (is.null(cursor)) break\n}\ntabelle <- do.call(rbind, teile)\ntabelle\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  id  ort wert\n1  1 Bern 12.5\n2  2 Chur  9.1\n3  3 Sion 14.0\n4  4 Bern 11.8\n5  5 Chur 10.2\n```\n\n\n:::\n\n```{.r .cell-code}\nc(abrufe = abrufe, zeilen = nrow(tabelle))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nabrufe zeilen \n     3      5 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(tapply(tabelle$wert, tabelle$ort, mean), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Bern  Chur  Sion \n12.15  9.65 14.00 \n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nseiten = {\n    None: '{\"daten\":[{\"id\":1,\"ort\":\"Bern\",\"wert\":12.5},{\"id\":2,\"ort\":\"Chur\",\"wert\":9.1}],\"weiter\":\"s2\"}',\n    \"s2\": '{\"daten\":[{\"id\":3,\"ort\":\"Sion\",\"wert\":14.0},{\"id\":4,\"ort\":\"Bern\",\"wert\":11.8}],\"weiter\":\"s3\"}',\n    \"s3\": '{\"daten\":[{\"id\":5,\"ort\":\"Chur\",\"wert\":10.2}],\"weiter\":null}',\n}\n\n\ndef hole(cursor):\n    return seiten[cursor]\n\n\nzeilen, cursor, abrufe = [], None, 0\nwhile True:\n    antwort = json.loads(hole(cursor))\n    abrufe += 1\n    zeilen.extend(antwort[\"daten\"])\n    cursor = antwort[\"weiter\"]\n    if cursor is None:\n        break\n\ntabelle = pd.DataFrame(zeilen)\nprint(tabelle)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   id   ort  wert\n0   1  Bern  12.5\n1   2  Chur   9.1\n2   3  Sion  14.0\n3   4  Bern  11.8\n4   5  Chur  10.2\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"abrufe:\", abrufe, \" zeilen:\", len(tabelle))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nabrufe: 3  zeilen: 5\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(tabelle.groupby(\"ort\")[\"wert\"].mean().round(2).to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{'Bern': 12.15, 'Chur': 9.65, 'Sion': 14.0}\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| Abrufe | 3 | so viele Seiten, bis `weiter` leer war |\n| Zeilen | 5 | alle Messungen aus allen Seiten |\n| Mittel Bern | 12.15 | aus zwei Seiten zusammengesetzt; wer nur die erste Seite liest, bekommt 12.5 |\n| Mittel Chur | 9.65 | ebenso |\n\n#### Interpretation\n\nDer häufigste Fehler bei Schnittstellen ist nicht ein falscher Abruf, sondern\nein unvollständiger: Nur die erste Seite wird gelesen, und die Auswertung\nrechnet still mit einem Bruchteil der Daten. Die Zahl der Zeilen gehört deshalb\ngegen die Gesamtzahl geprüft, die viele Schnittstellen in der Antwort mitliefern.\n\n### Beispiel 2: Eine HTML-Tabelle auslesen\n\n#### Frage und Datenlage\n\nEine Webseite zeigt eine Preisliste als HTML-Tabelle und darunter eine Liste\nmit Hinweisen. Gesucht sind die Preise als Zahlen, der Lagerwert und der\nHinweis, der als neu markiert ist.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhtml_text <- '<html><body><h1>Preisliste</h1>\n<table id=\"preise\"><tr><th>Artikel</th><th>Preis</th><th>Lager</th></tr>\n<tr><td>Schraube M6</td><td>CHF 0.35</td><td>1\\'200</td></tr>\n<tr><td>Mutter M6</td><td>CHF 0.20</td><td>950</td></tr>\n<tr><td>Winkel 40 mm</td><td>CHF 2.80</td><td>k.A.</td></tr></table>\n<ul class=\"hinweise\"><li class=\"neu\">Winkel neu im Sortiment</li><li>Preise ohne MWST</li></ul>\n</body></html>'\n\nseite <- read_html(html_text)\npreise <- html_table(html_element(seite, \"#preise\"), convert = FALSE)\nnames(preise) <- c(\"artikel\", \"preis\", \"lager\")\n\npreise$preis_chf <- as.numeric(gsub(\"[^0-9.]\", \"\", preise$preis))\npreise$lager_n   <- suppressWarnings(as.numeric(gsub(\"[^0-9]\", \"\", preise$lager)))\npreise\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  artikel      preis    lager preis_chf lager_n\n  <chr>        <chr>    <chr>     <dbl>   <dbl>\n1 Schraube M6  CHF 0.35 1'200      0.35    1200\n2 Mutter M6    CHF 0.20 950        0.2      950\n3 Winkel 40 mm CHF 2.80 k.A.       2.8       NA\n```\n\n\n:::\n\n```{.r .cell-code}\nround(sum(preise$preis_chf * preise$lager_n, na.rm = TRUE), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 610\n```\n\n\n:::\n\n```{.r .cell-code}\nhtml_text(html_elements(seite, \"ul.hinweise li.neu\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Winkel neu im Sortiment\"\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nhtml_text = \"\"\"<html><body><h1>Preisliste</h1>\n<table id=\"preise\"><tr><th>Artikel</th><th>Preis</th><th>Lager</th></tr>\n<tr><td>Schraube M6</td><td>CHF 0.35</td><td>1'200</td></tr>\n<tr><td>Mutter M6</td><td>CHF 0.20</td><td>950</td></tr>\n<tr><td>Winkel 40 mm</td><td>CHF 2.80</td><td>k.A.</td></tr></table>\n<ul class=\"hinweise\"><li class=\"neu\">Winkel neu im Sortiment</li><li>Preise ohne MWST</li></ul>\n</body></html>\"\"\"\n\nsuppe = BeautifulSoup(html_text, \"html.parser\")\nreihen = [[zelle.get_text(strip=True) for zelle in tr.find_all(\"td\")]\n          for tr in suppe.select(\"#preise tr\")[1:]]\npreise = pd.DataFrame(reihen, columns=[\"artikel\", \"preis\", \"lager\"])\n\npreise[\"preis_chf\"] = pd.to_numeric(preise[\"preis\"].str.replace(r\"[^0-9.]\", \"\", regex=True))\npreise[\"lager_n\"] = pd.to_numeric(preise[\"lager\"].str.replace(r\"[^0-9]\", \"\", regex=True),\n                                  errors=\"coerce\")\nprint(preise)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        artikel     preis  lager  preis_chf  lager_n\n0   Schraube M6  CHF 0.35  1'200       0.35   1200.0\n1     Mutter M6  CHF 0.20    950       0.20    950.0\n2  Winkel 40 mm  CHF 2.80   k.A.       2.80      NaN\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"Lagerwert:\", round((preise[\"preis_chf\"] * preise[\"lager_n\"]).sum(), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLagerwert: 610.0\n```\n\n\n:::\n\n```{.python .cell-code}\nprint([li.get_text() for li in suppe.select(\"ul.hinweise li.neu\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['Winkel neu im Sortiment']\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Ausgabe | Wert hier | Wie er zu lesen ist |\n|---|---|---|\n| `preis_chf` | 0.35, 0.20, 2.80 | Einheit `CHF` und Leerzeichen entfernt, danach Zahl |\n| `lager_n` | 1200, 950, fehlend | das Hochkomma als Tausendertrennzeichen entfernt; `k.A.` wird zu einem fehlenden Wert |\n| Lagerwert | 610 | Summe über die zwei Artikel mit Bestand; der Winkel fällt mangels Lagerzahl heraus |\n| Hinweis | `Winkel neu im Sortiment` | über den Selektor `ul.hinweise li.neu` gefunden |\n\n#### Interpretation\n\nDer CSS-Selektor beschreibt die Stelle im Dokument so, wie ein Stylesheet sie\nbeschreibt: `#preise` ist das Element mit dieser ID, `li.neu` ein Listenpunkt\nmit der Klasse `neu`. Die Selektoren findet man, indem man in den\nEntwicklerwerkzeugen des Browsers auf das Element klickt. Ohne Bereinigung wäre\ndie Lagerspalte Text, und `1'200` ergäbe keine Zahl. Dass der Lagerwert ohne\nden Winkel berechnet ist, gehört ausdrücklich dazugesagt.\n\n### Beispiel 3: Wiederholen mit wachsender Wartezeit\n\n#### Frage und Datenlage\n\nDrei Abrufe gegen einen überlasteten Server. Er antwortet der Reihe nach mit den\nCodes 200, 429, 429, 200, 500, 503, 200. Jeder Auftrag wird höchstens dreimal\nversucht, die Wartezeit verdoppelt sich ab einer Sekunde. Gezeigt wird das\nProtokoll; gewartet wird hier nicht wirklich.\n\n#### Rechnung\n\n::: {.panel-tabset}\n\n##### R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncodes <- c(200, 429, 429, 200, 500, 503, 200)\n\nmit_wiederholung <- function(codes, auftraege = 3, max_versuche = 3, basis = 1) {\n  i <- 0; protokoll <- NULL\n  for (auftrag in seq_len(auftraege)) {\n    for (versuch in seq_len(max_versuche)) {\n      i <- i + 1\n      code <- codes[i]\n      warten <- if (code == 200) 0 else basis * 2^(versuch - 1)\n      protokoll <- rbind(protokoll, data.frame(auftrag, versuch, status = code, warten_s = warten))\n      if (code == 200) break\n    }\n  }\n  protokoll\n}\nmit_wiederholung(codes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  auftrag versuch status warten_s\n1       1       1    200        0\n2       2       1    429        1\n3       2       2    429        2\n4       2       3    200        0\n5       3       1    500        1\n6       3       2    503        2\n7       3       3    200        0\n```\n\n\n:::\n:::\n\n\n##### Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ncodes = [200, 429, 429, 200, 500, 503, 200]\n\n\ndef mit_wiederholung(codes, auftraege=3, max_versuche=3, basis=1.0):\n    i, protokoll = 0, []\n    for auftrag in range(1, auftraege + 1):\n        for versuch in range(1, max_versuche + 1):\n            code = codes[i]\n            i += 1\n            warten = 0.0 if code == 200 else basis * 2 ** (versuch - 1)\n            protokoll.append((auftrag, versuch, code, warten))\n            if code == 200:\n                break\n    return pd.DataFrame(protokoll, columns=[\"auftrag\", \"versuch\", \"status\", \"warten_s\"])\n\n\nprint(mit_wiederholung(codes))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   auftrag  versuch  status  warten_s\n0        1        1     200       0.0\n1        2        1     429       1.0\n2        2        2     429       2.0\n3        2        3     200       0.0\n4        3        1     500       1.0\n5        3        2     503       2.0\n6        3        3     200       0.0\n```\n\n\n:::\n:::\n\n\n:::\n\n#### Output Zeile für Zeile\n\n| Auftrag | Verlauf | Wartezeit gesamt | Wie es zu lesen ist |\n|---|---|---|---|\n| 1 | 200 im ersten Versuch | 0 s | |\n| 2 | 429, 429, dann 200 | 3 s | zweimal zu viele Anfragen, erst 1, dann 2 Sekunden gewartet |\n| 3 | 500, 503, dann 200 | 3 s | Serverfehler, gleiche Behandlung |\n\n#### Interpretation\n\nDie wachsende Wartezeit entlastet den Server genau dann, wenn er überlastet\nist. Sofortige Wiederholungen würden die Überlastung verstärken. Nach dem\nletzten Versuch wird nicht still weitergemacht, sondern der Auftrag als\nfehlgeschlagen protokolliert; sonst fehlt am Ende ein Teil der Daten, ohne dass\nes jemand merkt. In der Praxis übernehmen `httr2::req_retry()` und der\n`Retry`-Mechanismus von `requests` diese Logik.\n\n::::\n\n## Typische Aufgaben\n\n**JSON-Antwort flach machen**\n\n```r\njsonlite::fromJSON(text, flatten = TRUE)\n```\n\n```python\npd.json_normalize(json.loads(text), sep=\"_\")\n```\n\n**Alle Links einer Seite**\n\n```r\nhtml_attr(html_elements(read_html(url), \"a\"), \"href\")\n```\n\n```python\n[a.get(\"href\") for a in BeautifulSoup(html, \"html.parser\").find_all(\"a\")]\n```\n\n**Einfache Tabelle einer Webseite direkt als Data Frame**\n\n```r\nhtml_table(read_html(url))[[1]]\n```\n\n```python\npd.read_html(url)[0]   # braucht lxml oder html5lib\n```\n\n**Zwischen Abrufen warten**\n\n```r\nSys.sleep(1)\n```\n\n```python\ntime.sleep(1)\n```\n\n## Verständnisfragen\n\n::: {.quiz}\nEine Auswertung über eine Schnittstelle liefert 100 Zeilen, laut Dokumentation\ngibt es aber rund 2400 Einträge. Was ist die wahrscheinlichste Ursache?\n\n- [x] Nur die erste Seite wurde abgerufen ~ Richtig. Viele Schnittstellen liefern\n      standardmässig 100 Einträge je Seite. Abgerufen wird, bis kein Verweis\n      auf eine weitere Seite kommt.\n- [ ] Die Schnittstelle ist fehlerhaft ~ Möglich, aber seltener als eine\n      fehlende Schleife über die Seiten.\n- [ ] JSON kann nur 100 Zeilen fassen ~ JSON hat keine solche Grenze.\n:::\n\n::: {.quiz}\nEin Abruf antwortet mit `429`. Was ist richtig?\n\n- [x] Warten und später erneut versuchen, idealerweise nach der Angabe im Header\n      `Retry-After` ~ Richtig. Der Server sagt, dass zu viele Anfragen in kurzer\n      Zeit kamen.\n- [ ] Sofort wiederholen ~ Das verschärft genau das Problem, das der Code meldet.\n- [ ] Den Schlüssel erneuern ~ Ein ungültiger Schlüssel ergäbe `401` oder `403`.\n:::\n\n::: {.quiz}\nWarum sollte HTML nicht mit regulären Ausdrücken ausgelesen werden?\n\n- [x] HTML ist verschachtelt und in der Schreibweise frei, ein Parser versteht\n      die Struktur, ein Muster nur Zeichenfolgen ~ Richtig. Zusätzliche\n      Attribute, Zeilenumbrüche oder verschachtelte Tags brechen ein Muster,\n      einen Parser nicht.\n- [ ] Reguläre Ausdrücke sind zu langsam ~ Die Geschwindigkeit ist nicht das\n      Problem.\n- [ ] R und Python können HTML nicht als Text lesen ~ Sie können; das Problem ist\n      die Struktur, nicht das Lesen.\n:::\n\n## Verlinkte Ressourcen\n\n- [httr2: Einführung](https://httr2.r-lib.org/articles/httr2.html)\n- [rvest: Web scraping 101](https://rvest.tidyverse.org/articles/rvest.html)\n- [Requests: Quickstart](https://requests.readthedocs.io/en/latest/user/quickstart/)\n- [Beautiful Soup: Dokumentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)\n- [MDN: CSS-Selektoren](https://developer.mozilla.org/de/docs/Web/CSS/CSS_selectors)\n- [MDN: HTTP-Statuscodes](https://developer.mozilla.org/de/docs/Web/HTTP/Status)\n",
    "supporting": [
      "apis-web-scraping_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}